### ISSUE TITLE
Make sure values in Reduction Settings tab are included when displaying mask

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10079]
sans_bugfix
This issue was originally [TRAC 9236](http://trac.mantidproject.org/mantid/ticket/9236)

To reproduce:
1.  Start the ISIS SANS interface.
2.  Load a mask.
3.  Load some data.
4.  Change some of the values on the Reduction Settings tab.  Radius min and max are nice, easily visible ones to change.
5.  Clicking “Display Mask”.

The changes made during (4) will not be shown in the displayed mask.  Note, if you’d ran a reduction or tried to find the centre between (4) and (5), then they would be included!

**Comment by gemmaguest** [comment]
Closing as this relates to the old interface
