### ISSUE TITLE
SANS: Consider spotting when user has entered SANS run instead of TRANS run in error

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10112]
sans_bugfix
This issue was originally [TRAC 9269](http://trac.mantidproject.org/mantid/ticket/9269)

From Ann:

> Using the SANS-ISIS gui, for LOQ, we can (in error) enter a SANS run number in the TRANS and direct beam boxes. Mantid then uses spectrum 3 to reduce the data but this is the bottom left hand pixel in the LOQ case. Would it be possible to catch this error for just LOQ please? It could be done just by looking at the number of spectra in the file to decide between SANS and TRANS.

Further comment from Steve:

> When Ann says ‘bottom left hand pixel’ she means of the main (rear) detector.
> This MAY also affect SANS2D when it is using M3, rather than M4, for transmissions as then it, too, has separate SANS & TRANS runs.

**Comment by AntonPiccardoSelg** [comment]
That might be hard to do, especially since we allow the detector regions for TRANS now.

**Comment by DavidFair** [comment]
I'm going to close this as stale as we haven't heard much about it
If users are still running into it often enough to warrant work feel free to re-open it and we can look at it
