### ISSUE TITLE
SANS: Fix bug in batch files when incorrect run number is specified

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10111]
sans_bugfix
This issue was originally [TRAC 9268](http://trac.mantidproject.org/mantid/ticket/9268)

Comment from Ann:

> If a user enters a wrong run number in a batch file, specifically a TRANS run number as a SANS run, it causes mantid to stop as there are not enough spectra in the file. If you correct the batch file and re-load it, you cannot re-run the 1D reduction. Instead you get an error of 'NoneType' object has no attribute 'wksp_name'. You now have to exit the gui and re-start it to clear the error.

This will need investigating further as I do not have a clear idea yet of what is causing the problem.

**Comment by gemmaguest** [comment]
Closing as this relates to the old interface/backend
