### ISSUE TITLE
GUI design guidelines - Implementation

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10118]
This issue was originally [TRAC 9275](http://trac.mantidproject.org/mantid/ticket/9275)
1. Apply the design standards across exiting interfaces
2. Common use of mantid widgets
3. Common look and feel

Would need to change both C++ and Python GUIs. Serious amount of effort involved.

Work may cover more than one release

---

Keywords: SSC,2014,All

**Comment by martyngigg** [comment]
This is being developed at http://developer.mantidproject.org/GUIDesignGuidelines.html and will be ongoing.
