### ISSUE TITLE
Crystal Plan implementation

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10145]
This issue was originally [TRAC 9302](http://trac.mantidproject.org/mantid/ticket/9302)

One person (Andrei) working full time on this. Should mostly involve swapping out python functionality for Mantid functionality.

---

Keywords: SSC,2014,All,Planning

**Comment by martyngigg** [comment]
As far as I know CrystalPlan is now in use on various instruments at SNS and ISIS so I'm closing this original issue. Please let me know if this is not the case.
