### ISSUE TITLE
Inelastic planning tools - Porting Chop functionality

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10147]
This issue was originally [TRAC 9304](http://trac.mantidproject.org/mantid/ticket/9304)

This ticket is blocked by : 
 - [X] [TRAC10611](http://trac.mantidproject.org/mantid/ticket/10611)
 - [X] [TRAC10940](http://trac.mantidproject.org/mantid/ticket/10940)

Includes porting Horace Planner, Chop, etc to Mantid.  

 - - - - 
Keywords: SSC,2014,All

**Comment by mducle** [comment]
@NickDraper @AndreiSavici @stuartcampbell 

Do you mind if I work on this and replace the current PyChop? Russell Ewings has benchmarked and fixed bugs and generally improved the Chop scripts, and put his things on the user script repository, but there's no GUI. In addition the current chop calculations for LET relies on lookup tables calculated in McStas for an old configuration of the choppers which LET no longer uses. Instead, David Voneshen has a script that calculates the elastic resolution from the chopper opening times which would be good to have to replace the current LET script. 

Finally, I'd like to make an improve command-line interface to be able to use Chop to calculate the linewidths for fitting crystal fields ( re #15684 ). So, my intention is to replace the current PyChop with the updates from Russell and David and to revamp the GUI, and add a CLI.

However, the current scripts only really cover ISIS instruments - I presume that "Garrett's Python Scripts" (e.g.  #7737 or #8442 ) cover SNS instruments? I can't seem to find any sign of these scripts on the web though... Do you know of any SNS chop equivalents?

**Comment by NickDraper** [comment]
Duc,

We would be more than happy for you to work on this.  As far as I know @AndreiSavici  is not currently working on this, although he can correct me if I'm wrong.
