### ISSUE TITLE
Stop Reduction Clearly if User File Does Not Contain a MASK Command

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10189]
sans_bugfix
This issue was originally [TRAC 9346](http://trac.mantidproject.org/mantid/ticket/9346)

The ISIS SANS interface currently does not allow one to have a User File that does not contain the [http://www.mantidproject.org/SANS_User_File_Commands#MASK MASK] command -- you will be presented with some obscure divide-by-zero errors and the reduction will fail.

Rob Dalgliesh recently ran into this problem trying to get some Larmor data through the reduction, and lost a considerable amount of time as a result.

Admittedly this is not likely in normal use, but we should either a) allow for completely unmasked reductions or b) warn the user of what they've failed to provide before stopping the reduction.

**Comment by smk78** [comment]
Will the new TOML user file make this obsolete?

**Comment by smk78** [comment]
Also see https://github.com/mantidproject/mantid/issues/27665, https://github.com/mantidproject/mantid/issues/27666 and https://github.com/mantidproject/mantid/pull/28513

**Comment by smk78** [comment]
One assume sthe TOML parser will make this obsolete, though what happens with backward-compatibility. Until @DavidFair can comment will mark this as Never Stale
