### ISSUE TITLE
Extend "TRANS" Command To Allow "Beam Stop Out" Method

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10192]
This issue was originally [TRAC 9349](http://trac.mantidproject.org/mantid/ticket/9349)

The current functionality of the SANS User File command `TRANS` is outlined [http://www.mantidproject.org/SANS_User_File_Commands#TRANS here].

Proposed changes to the syntax of this command:

* Add "`MAIN`" and "`REAR`" options to the `/TRANSPEC` qualifier.
* Add `/RADIUS=r` qualifier, where r is a decimal value measured in mm.
* Add `/MASK=filepath` qualifier.  This file would be a Mantid Mask File that specifies a particular region of interest.

This should work either with a single line (e.g. `TRANS/TRANSPEC=MAIN/RADIUS=3/MASK=mask_file.xml`) or via multiple calls to `TRANS`.

 - - - - 
Keywords: Bilby

**Comment by picatess** [comment]
The extraction of the spectra list has been accelerated considerably and a number of bugs were dealt with. Richard had got at it and it seemed to produce the right results. There are a number of exitension and modifications though which Richard asked for:
*  Rename TRANS/MASK to TRANS/ROI
* Introduce TRANS/MASK in order to specify regions to exclude from being used for the Transmission calculation
*  Remove TRANS/MAIN and others in that category
*  Add TRANS\BACK to specify a separate time region for FlatBackground Correction for the Trans data
*  Provide FlatBackground Correction for the Incident Monitor and the Trans data separately

**Comment by picatess** [comment]
Richard suggested that we add the new Trans functionality to the GUI:

'''
Ideally it would be good to have all the transmission options able to be changed in the gui, but it might get a bit messy (top right of reduction settings tab)
 
Drop down for:
 
M3                                   equivalent to TRANS/TRANSPEC=3
M4                                   equivalent to TRANS/TRANSPEC=4
RADIUS                            equivalent to TRANS/RADIUS= nnn where nnn is whatever was last used, default say 200mm
ROI                                   equivalent to TRANS/ROI= roifile.xml
 
The M4 option also needs a value box for shift e.g. TRANS/SHIFT=-55
 
The RADIUS option needs a value box for radius. 
 
The ROI option needs filename/browser box for TRANS/ ROI= roifile.xml
 
The RADIUS and ROI options both need filename/browser box for TRANS/MASK= maskfile.xml
 
===========================
 
As a slightly quicker fix, the one thing that we are likely to want to experiment with is RADIUS, as well as changing the M3/M4/RADIUS method, so a minimal set for the gui would be:
 
Drop down for:
 
M3                                   equivalent to TRANS/TRANSPEC=3
M4                                   equivalent to TRANS/TRANSPEC=4
RADIUS                            equivalent to TRANS/RADIUS= nnn where nnn is whatever was last used, default say 200mm
 
The M4 option also needs a value box for shift e.g. TRANS/SHIFT=-55
 
The RADIUS option needs a value box for radius  .
 
The .xml file names for the MASK and ROI could simply be set and remembered in the user file, without triggering a change in method, possibly just copied to gui but greyed out, as done already for the efficiency correction files.
'''

**Comment by picatess** [comment]
I spoke with Richard about the GUI request and we will have this as a separate ticket
