### ISSUE TITLE
Optionally Apply Background Correction

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10193]
sans_feature
This issue was originally [TRAC 9350](http://trac.mantidproject.org/mantid/ticket/9350)

The ISIS SANS interface needs to be expanded to allow background corrections using so-called "dark runs".

My understanding is that there are two kinds of dark run; "natural background" (i.e. source off) and "dark current" (i.e. source on, but shutter closed).

It is not clear whether or not this would be best implemented as a User File command, as checkboxes in the GUI, or both.

Implementing this seems trivial enough, though we'd need to be careful about scaling a 10-hour background run before applying it to a 1-hour data run, run example.  It may be useful to see how this has been done at the SNS.

We are to account for periods where they have been used.

 - - - - 
Keywords: Bilby

**Comment by picatess** [comment]
From Richard:
>In our case “background” could be a beam on “Cd run”, “fast shutter closed” or “main shutter closed”. These could be normalised to either microamphours or (if you think cosmic & electronic noise is dominant) to time. For electronic noise and/or “cosmic ray background” we might do a long “beam off” run in a shutdown.
 
>Thus I think we need to specify:  run number (or file name);  normalise to data collection time (=number of good frames x collection time in each frame) or to good uamps; whether for monitors or for which particular detector bank.
 
>Since we already use “BACK” for tof monitor electronic noise, http://www.mantidproject.org/SANS_User_File_Commands#BACK we could use e,g.
 
>BACK/REAR/UAMP/TOF/RUN=12345
BACK/FRONT/UAMP/TOF/RUN=12346
BACK/MON/RUN=23456/TIME/MEAN
 
>/TOF means apply subtraction in tof
/MEAN is to average the RUN over the whole spectrum and subtract the same count rate from all tof bins in each spectrum, this is appropriate if electronic noise or cosmic background dominate.
