### ISSUE TITLE
Extend the "MASK S" User File Command to Accept Ranges of Spectra

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10191]
sans_feature
This issue was originally [TRAC 9348](http://trac.mantidproject.org/mantid/ticket/9348)

This ticket is blocks :  [TRAC8847](http://trac.mantidproject.org/mantid/ticket/8847)

In SANS User Files there is currently a command available to [http://www.mantidproject.org/SANS_User_File_Commands#MASK mask single spectra].  Extend this so that one may mask a range (or ranges) of spectra.

Consider also allowing users to specify Detectors ID as well as spectra numbers.

Modify the appropriate Wiki page to represent any changes.

Note:  This would appear to be at odds with our new strategy of using the Mask Files generated from Instrument View (http://trac.mantidproject.org/mantid/ticket/9204), but will still be of use to the scientists and should be easy to implement, so offers us a quick win.

**Comment by AntonPiccardoSelg** [comment]
This should be discussed if it is useful. Mask files from the instrument view seem to be much more useful.

**Comment by DavidFair** [comment]
I've not heard anything about this whilst discussing the new file format, so I'm going to close until we hear about it
