### ISSUE TITLE
Allow the Specification of User Files in Batch Files

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10190]
This issue was originally [TRAC 9347](http://trac.mantidproject.org/mantid/ticket/9347)

Steve King would like to the ability to specify User Files in the .csv Batch Files.  He mentioned the first line of the batch file being an ideal place for this, but based on an initial code inspection I'm not convinced this is the ideal place for it since `BatchReduce` of `SANSBatchMode.py` tries to parse every line.

From a usability standpoint, we'd also need to put some thought into how this information would be displayed in the GUI.  It would not be good to have the "User File" field at the top of the GUI displaying one thing, only to then have the batch file go away and use something else in the reduction.  Perhaps adding an extra column in the batch table and then striking out the User File field is the way forward?

Any changes need to be documented on the appropriate Wiki page:

http://www.mantidproject.org/SANS_batch_file_format

 - - - - 
Keywords: sasnUI

**Comment by picatess** [comment]
Richard mentioned several points regarding the user file:
*  The user should have an extra column option: ```user_file``` to specify the user file for each row
*  The rows should be worked down as they are specified in the batch file. That excludes sorting on the user_file name to group reductions which use the same user file
*  When the user file is not specified for a run, then specify the standard user file specified in the "User file" input field. This means we need to keep it enabled.
