### ISSUE TITLE
Unable to Load User File if its Path Contains Spaces

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10209]
This issue was originally [TRAC 9366](http://trac.mantidproject.org/mantid/ticket/9366)

To reproduce:

* Go to your System Tests\Data\SANS2D folder, and copy `MaskSANS2DReductionGUI.txt` (a User File) and `DIRECTM1_15785_12m_31Oct12_v12.dat` (a requirement of the User File) to another directory that has a space in its name.

* Open up the ISIS SANS interface in Mantid, and click "Load Mask".

* Browse to wherever you have put `MaskSANS2DReductionGUI.txt` and select it.

The interface will try to load the file but will fail.

**Comment by picatess** [comment]
This must have been fixed along the way. Having the files in a folder which contains a space or not produced the same output. I followed the path with a debugger and saw that the correction file gets loaded in the `CalculateNormISIS` class. 

This issue should be closed.
