### ISSUE TITLE
Don't Load Any IDFs Until We Know Which Version of the Instrument Should Be Used

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10210]
sans_feature
This issue was originally [TRAC 9367](http://trac.mantidproject.org/mantid/ticket/9367)

The ISIS SANS system tests currently load IDF's without knowing which version of the instrument the data being reduced corresponds to.  LOQ has for some reason been [https://github.com/mantidproject/mantid/blob/master/Code/Mantid/scripts/SANS/isis_instrument.py#L718 hard-coded] to use the second-to-last (chronologically speaking) of the four available IDF's by default, and since http://trac.mantidproject.org/mantid/ticket/9361, SANS2D defaults to the _oldest_ of two IDF's.

To further complicate matters, the ISIS SANS interface actually waits until some data has been loaded before reading IDFs (and so is able to pick the correct one), except in the case where users go straight to the Masking tab and click "Display Mask" without first loading data.  In that case, the defaults mentioned above are also used.

This is a mess.

My preference here would be to get rid of these arbitrary defaults and instead simply enforce a universal rule that no IDF-dependant ISIS SANS command can take place without first knowing which data file (and therefore which exact IDF) is being used.  This would be the cleanest (and I'd also argue, easiest) way to guarantee that the correct IDF is being used at any given time.

I need to run this by the scientists, but I think they will be in general agreement.

**Comment by AntonPiccardoSelg** [comment]
This has been fixed in the old reduction backend and is a non-issue in the new reduction backend
