### ISSUE TITLE
SliceViewer cluster display

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10218]
This issue was originally [TRAC 9375](http://trac.mantidproject.org/mantid/ticket/9375)

This ticket is blocked by : 
- [X] [TRAC9428](http://trac.mantidproject.org/mantid/ticket/9428)
- [ ] [TRAC9469](http://trac.mantidproject.org/mantid/ticket/9469)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)
- Take a peaks workspace integrated via IntegratePeaksUsingCluster
- Display it in the PeaksOverlay of the SliceViewer
- This should automatically render with an outline (stencil) view of the clusters

To do this, we must mark the PeaksWorkspaces that have been through IntegratePeaksUsingClusters. This could be done by holding a weak pointer to the MDWorkspace image. It could also be done via some kind of naming + using the ADS. We would then need to make a new PeakOverlayView type, that allowed us to render workspaces of this type.

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92 This looks again like sometign that could have come from Pascal. I am assigning this to you, but please feel free to reassign it not appropriate.
