### ISSUE TITLE
Mantid Catalog search does not produce the same results as Journal viewer search and some Mantid searches are failing.

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10226]
This issue was originally [TRAC 9383](http://trac.mantidproject.org/mantid/ticket/9383)

ISIS instrument scientists use [https://data.isis.rl.ac.uk/journals/ journal viewer] to find information on their runs. I observed that the search results returned from the journal viewer are different from the results which can be found using Mantid's ICAT GUI for searching.

== Example one ==

=== Searching on journal viewer ===
1. Go to the [https://data.isis.rl.ac.uk/journals/ journal viewer] website.
2. Click `HTML` for the `MARI` instrument (or click [https://data.isis.rl.ac.uk/journals/ndxmari/journal_main.html])
3. From the `from cycle(s)` drop-menu select `Current`.
4. From the `sorted by` drop-menu select `RB number` and `Ascending` from the adjacent drop-menu.
5. Click the `Refresh` button.

You should now observe that there are '''nine''' proposals with the following IDs:

```
1010514;
1310471;
1320246;
1320539;
1410203;
1410359;
1410388;
1410550;
1410559;
```

=== Searching on ICAT ===
1. Open the ICAT GUI within Mantid.
2. Enter a start-date of `11/02/2014` and end-date of `04/04/2014` (according to the [http://www.isis.stfc.ac.uk/beam-status/beam-status4463.html last cycle dates]) 
3. Click `Search` and observe that '''zero''' results are returned.
4. Perform the same searches on the [https://data4.isis.stfc.ac.uk:8443 ICAT web interface (TOPCAT)]

== Example two == 
1. Log into the `Catalog` in `Mantid`.
2. Enter `19247-19295` in the `Run range` field.
3. Click `Search`. 0 investigations are returned.

When performing the search on the journal viewer above the run range entered in the search relate to those specific runs.

=== Conclusion ===

The results that I get from Mantid are different from the data journal, which will prevent certain users from using ICAT within Mantid. This looks to be an `ICAT` specific issue, and I think may be related to permissions.

==== Other minor issues ====
1. Searching by cycle is a very convenient option that scientists would like.
2. Some investigations do not have run numbers in `ICAT`, but they do on the data journal.
3. There are occasions when a name appears in the run-range column rather than a run-range.

**Comment by Anders-Markvardsen** [comment]
may need to be closed

**Comment by gemmaguest** [comment]
@ElliotAOram I just came across this issue which may be of interest as it has some details of ICat vs JournalViewer differences.

I'm going to close this issue because this is an ICat problem rather than a Mantid issue.
