### ISSUE TITLE
"Display Mask" is Different After a Mask Reload Without a Data Reload

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10257]
sans_bugfix
This issue was originally [TRAC 9414](http://trac.mantidproject.org/mantid/ticket/9414)

Make sure the SANS2D folder of the system tests repo is a managed directory within Mantid, then open up the ISIS SANS interface and do the following:
1. Load the MaskSANS2DReductionGUI.txt mask.
2. Load scattering sample 22048 / can 22023; transmission sample 22041 / can 22024; and direct sample 22024 / can 22024.
3. Go to the Masking tab and click "Display Mask".
4. Go back and reload the mask.
5. Go back to the Masking tab and re-click "Display Mask".

The mask will appear different (slightly shifted) the second time around.

Either:

a) this is a bug and it should be made to display the same way both times; or

b) the reducer was never intended to be used this way and so we should explicitly disallow this from happening in the interface by forcing the user to reload some data before re-displaying the mask.

**Comment by gemmaguest** [comment]
Closing as this refers to the old backend
