### ISSUE TITLE
In InstrumentDefinitionParser: use of atoi and boost::lexical_cast consistent

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#10270]
This issue was originally [TRAC 9427](http://trac.mantidproject.org/mantid/ticket/9427)

This ticket is blocked by : 
 - [X] [TRAC9406](http://trac.mantidproject.org/mantid/ticket/9406)

Originally atoi and atof used to convert string to int and double. 

At recently boost::lexical_cast used, which is generally recommended over using atoi and atof, although as was found it http://trac.mantidproject.org/mantid/ticket/9406 boost::lexical_cast does not strip for spaces.

This ticket is proposed to translate all atoi and atof to boost::lexical_cast. 

In doing this it has to be checked that the performance of loading IDF does not increase (or only increase very little). 

One way of implementing this is to add a private method getStripedAttValue() which returns a string that can be passed to boost::lexical_cast

 - - - - 
Keywords: Maintenance

**Comment by FedeMPouzols** [comment]
Archiving this, as many tests turned out to be very sensitive to numerical differences between lexical_cast and atoi/atof.
Low benefit given the amount of higher priority issues.
New geometry being planned which would deprecate this code.
