### ISSUE TITLE
LoadEventNexus with filtering does not work on (some?) event Nexus runs

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10287]
This issue was originally [TRAC 9444](http://trac.mantidproject.org/mantid/ticket/9444)

Lets try to load event nexus data from MER18972 run (see in archive or I can put it on ftp on request.) 

If I issue 
```
w1=LoadEventNexus('MER18972') 
```

it works and from the data log I see it containing ~2*10^6^ good frames collected during 40000 sec, Workspace without monitors contains ~67M events. 

If I try 
```
w1=LoadEventNexus('MER18972.nxs',FilterByTimeStart=0,FilterByTimeStop=40000) 
```

or any other time interval, the resulting workspace contains no events. 

Looks like a bug. 

Freddy said that nothing is wrong with the data inside of the workspace except the frame current is mainly 0 due to problems with DAE. 

If this is the reason for the problem, LoadEventNexus should issue clear warning about it. A measures have to be taken to be able recovering the data.

**Comment by NickDraper** [comment]
No progress for some time - archived for now
