### ISSUE TITLE
WorkspaceProperty isDefault Issue

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10286]
This issue was originally [TRAC 9443](http://trac.mantidproject.org/mantid/ticket/9443)

If you have an algorithm with an optional WorkspaceProperty, and if you run that algorithm in child mode, then calling isDefault on your property will not behave as you expect it to. Even if you have set the property, isDefault will return true.

Looking at the implementation:

```
      bool isDefault() const
      {
        return  m_initialWSName == m_workspaceName;
      }
```

It's using the workspace names for comparision. If the workspaces are outside the ADS, then their names are not set, and so you are comparing two empty strings (returns True).

**Comment by NickDraper** [comment]
We need to add a test of the pointer into this as well.
