### ISSUE TITLE
Allow Beam Centre Finding Using SANS2D Front Detector Data

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10296]
sans_feature
This issue was originally [TRAC 9453](http://trac.mantidproject.org/mantid/ticket/9453)

Richard talked about how it would be nice for the "Automatic Search" box of the "Geometry" tab to take its cues regarding front/rear detector choice from the "Reduction Settings" tab.  I.e. the selected "Detector Bank" would be the one used when finding the beam centre.

Note that it would not make sense for "both" to be a valid beam centre choice.  We'd need to think about that in our implementation.

**Comment by AntonPiccardoSelg** [comment]
It looks like it can do that already
