### ISSUE TITLE
Investigate Instrument View Masking Glitch

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10299]
sans_bugfix
This issue was originally [TRAC 9456](http://trac.mantidproject.org/mantid/ticket/9456)

Richard has shown me a glitch with the Instrument View whereby clicking "Display Mask" in the ISIS SANS interface for SANS2D run 23785 shows blue "patches" in the masked areas of the rear detector bank.

It is unclear whether or not this is a result of:

a) how we're applying the mask as specified in the User File;

b) our current masking situation within Mantid; or

c) how we display logarithmic colours in the Instrument View.

**Comment by AntonPiccardoSelg** [comment]
This should be improved in the new ISIS SANS GUI. I will leave this issue open for now

**Comment by Mantid-Matthew** [comment]
This is a non-urgent issue with the old GUI so closing for now.
