### ISSUE TITLE
Ability to "Lock" Values in Geometry Tab

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10295]
sans_feature
This issue was originally [TRAC 9452](http://trac.mantidproject.org/mantid/ticket/9452)

In contrast to the "Reduction Settings" tab, the user-editable fields on the left-hand side of the "Geometry" tab change whenever new data is loaded, since they are populated with values from the nexus files.

Richard would like to see a way to "lock" these values, so that they persist between the loading of different sets of data.

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew This might be relevant for the new GUI too. Speak to Richard or Steve

**Comment by gemmaguest** [comment]
Closing as this is not relevant in the new GUI format
