### ISSUE TITLE
Associate ClusterImage (IMDHistoWorkspace) with a PeaksWorkspace

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10312]
This issue was originally [TRAC 9469](http://trac.mantidproject.org/mantid/ticket/9469)

This ticket is blocks :  [TRAC9375](http://trac.mantidproject.org/mantid/ticket/9375)

IntegratePeaksUsingClusters generates two useful output. An integrated peaks workspace, and a cluster image workspace. Both need to be used in combination at a later time, for example, when viewing the integrated volume in the SliceViewer.

I think that this is a subset of a more general problem, where we want to try to weakly tether an IMDHistoWorkspace to a a PeaksWorkspace.

Solving this is a key component of achieving http://trac.mantidproject.org/mantid/ticket/9375 now that http://trac.mantidproject.org/mantid/ticket/9428 is complete. 

---

Keywords: CORE

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92 This again sounds like it could be related to Pascal. It is related to https://github.com/mantidproject/mantid/issues/10218 , hence I assigned it to you. Again feel free to reassign

**Comment by martyngigg** [comment]
@DannyHindson @RichardWaiteSTFC This is an old issue that I found while search sliceviewer-related issues.

Has the issue described in https://trac.mantidproject.org/mantid/ticket/9375 been raised on the SX longer-term roadmap recently? If not then I'm tempted to close it.
