### ISSUE TITLE
Make 'load current' work for linux and mac also

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#10329]
This issue was originally [TRAC 9486](http://trac.mantidproject.org/mantid/ticket/9486)

It was noticed during testing of http://trac.mantidproject.org/mantid/ticket/9417 that 'load current' in fact have hardcoded paths for Windows, which means this functionality currently only works for Windows.

No Muon user have ever complained about this, hence interested they all appear to be windows users!

However, Jay showed me code in std::string CatalogInfo::transformArchivePath(std::string &path) that demonstrate how to make this work for linux and mac also using the path information in facilities.xml

    `<filelocation>`
      `<prefix regex="\\\\isis\\inst\$\\Instruments\$">``</prefix>`
      `<windows replacement="">``</windows>`
      `<linux replacement="/archive">``</linux>`
      `<mac replacement="/archive">``</mac>`
    `</filelocation>`

This ticket is to do something similar here for MuonAnalysis

**Comment by tom-perkins** [comment]
There is no good way to do this at the moment (see discussion in PR) and it hasn't been asked for in a long time because all muon users use Windows. Archiving for now, can reopen if the feature is asked for again
