### ISSUE TITLE
No test XML for PythonInterfaces python tests

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10325]
This issue was originally [TRAC 9482](http://trac.mantidproject.org/mantid/ticket/9482)

The JUnit style xml outputs from the PythonInterface python tests do not seem to get generated. Look at any of the build server jobs and they do not list the test outputs from the python algorithms.

 - - - - 
Keywords: Maintenance

**Comment by NickDraper** [comment]
This is working now

works4me
