### ISSUE TITLE
Refactor Single Mode to Call Batch Mode or Vice-Versa

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10328]
sans_code
This issue was originally [TRAC 9485](http://trac.mantidproject.org/mantid/ticket/9485)

Currently, there is some duplication (and subtle differences) with how we perform the ISIS SANS reduction in "Single Mode" and "Batch Mode".  We should factor out common code and have either:

1. Batch Mode written completely in terms of Single Mode, i.e. running the Single Mode reduction multiple times; or,
2. Single Modewritten completely in terms of Batch Mode, i.e. running the Batch Mode reduction but just feeding it a single entry.

I think we'd get the most benefit (having the two modes be as similar as possible) with option 2.

 - - - - 
Keywords: Maintenance

**Comment by NickDraper** [comment]
To be considered during the SANS refactoring #15876 note added, close this issue
