### ISSUE TITLE
Expose copyExperimentInfos/ addExperimentInfo to python

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#10320]
This issue was originally [TRAC 9477](http://trac.mantidproject.org/mantid/ticket/9477)

When one creates an MDHisto workspace with ImportMDHistoWorkspace, one cannot add an oriented lattice since there is no ExperimentInfo attached to the MD workspace. One should be able to copy an experiment info, or add one

**Comment by rosswhitfield** [comment]
This was done in #19384
