### ISSUE TITLE
Trouble exporting Publication quality graphs

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#10353]
This issue was originally [TRAC 9510](http://trac.mantidproject.org/mantid/ticket/9510)

I'm trying to export a 2D colour fill plot from Mantid, though most of these arguments apply to line plots too.

If I export the graph as a bitmap, it's exported at the resolution I see on screen. To get high resolution it's necessary to maximise the graph window - and then go round and change all the font sizes so that they are still a sensible fraction of the graph size and will be legible. It would be nice to be able to specify a higher DPI for export. The "graph.exportImage(...)" or "layer.exportImage(...)" functions don't seem to work quite like the web page suggests (http://www.mantidproject.org/MantidPlot:_Exporting_plots/layers_to_different_image_formats). As an aside the text in the image has coloured fringe edges which are the result of antialiasing on a colour screen, but look horrible when zoomed in.

If I export as PDF, line graphs and axes are OK but the 2D colour plot is exported as an image with pixel size matching the current screen resolution and some rather nasty compression artefacts - there's no way to specify the image compression factor. It might be good to draw the image as individual vector blocks of colour, especially if there aren't many pixels.

Exporting 2D colour plots as EPS fails (mostly black image with a few lines on it).

There aren't any vector export formats that can be imported into PowerPoint... while Mantid is probably trying to be platform independent, being able to export something like WMF might be nice.

James Lord.

**Comment by martyngigg** [comment]
Workbench will be taking over in this arena so improvements to MantidPlot will not be made.
