### ISSUE TITLE
Allow Tube Calibration File for Each Bank

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10390]
sans_feature
This issue was originally [TRAC 9547](http://trac.mantidproject.org/mantid/ticket/9547)

The `TUBECALIBFILE` command in User Files can be used to specify a calibration file for the SANS2D instrument.  Currently, this is set up so that only one file can be specified.

Unfortunately, each bank in SANS2D will have it's own calibration file, and so we need some way to specify ''two'' files, and then merge the detector positions of one bank into a workspace containing the detectors positions of the other.

I'm not yet sure how we should change the command to accommodate this.  Maybe `TUBECALIBFILE/REAR` and `TUBECALIBFILE/FRONT` is the best way, but I'd like to try and make things as generic as possible.

Meanwhile, I provided a script to Richard so that he can merge the files manually so that he only has to specify one file.  It may come in useful when implementing this ticket:

```
  #!python
# Files in \\isis\inst$\Instruments$\NDXSANS2D\user\Masks:
rear_calib_file = "TubeCalibrationTable_512pixel_23563rear_29May14.nxs"
front_calib_file = "TubeCalibrationTable_512pixel_23610front_28May14.nxs"

rear_calib = Load(rear_calib_file)
front_calib = Load(front_calib_file)

det_id_list = []
for ws_index in range(rear_calib.getNumberHistograms()):
    spectrum = rear_calib.getSpectrum(ws_index)
    if spectrum.getSpectrumNo() < 0:
        continue
    for det_id in spectrum.getDetectorIDs():
        if det_id > 2523511:
            continue
        det_id_list.append(det_id)

rear_inst = rear_calib.getInstrument()

# Creating an unmanaged version of the algorithm is important here.  Otherwise,
# things get really slow, and the workspace history becomes unmanageable.
move = AlgorithmManager.createUnmanaged('MoveInstrumentComponent')
move.initialize()
move.setChild(True)
move.setProperty("Workspace", "front_calib")
move.setProperty("RelativePosition", False)

for det_id in det_id_list:
    det = rear_inst.getDetector(det_id)
    if "rear-detector" in det.getFullName():
        move.setProperty("DetectorID", det_id)
        move.setProperty("X", det.getPos().getX())
        move.setProperty("Y", det.getPos().getY())
        move.setProperty("Z", det.getPos().getZ())
        move.setProperty("DetectorID", det_id)
        move.execute()

RenameWorkspace(InputWorkspace="front_calib", OutputWorkspace="merged")
DeleteWorkspace(Workspace="rear_calib")
```

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew Ask the scientists if this is relevant (It would only be relevant for SANS2D)

**Comment by gemmaguest** [comment]
Check with Richard what, if anything, needs doing

**Comment by RichardHeenan** [comment]
SANS2d does still have to run a script to merge two tubecalibfiles, would be useful to keep them separate! (Thinking ahead to ESS, where LoKI will start with 5 detector banks, and eventually reach 9, with many more tubes in each, keeping them separate would be essential !)

**Comment by smk78** [comment]
After review by the SANS Group, ISIS SANS wishes to continue with the two tube calibrations in the one file. But RKH says ESS SANS will want them separate! The ticket should remain open, but it is not a priority for ISIS SANS.
