### ISSUE TITLE
Allow Easy Resetting of MaxEnt Dat Files

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10401]
This issue was originally [TRAC 9558](http://trac.mantidproject.org/mantid/ticket/9558)

Alongside a data file and a detector grouping file, MaxEnt reads in two .dat files containing phase and deadtime information ("phase.dat" and "taud.dat" by default).  All this is passed to the underlying Fortran so that it may carry out its analysis.  A by-product of the analysis is modified phase and deadtime data, which (by convention, as per the old OpenGENIE functionality) we then write back out to the .dat files, replacing what we had originally.

Unfortunately this is a problem since repeatedly feeding the phase and deadtime output of the algorithm back in as an input can sometimes lead to the algorithm getting "stuck" and spitting out NaN values.  These cannot then be used in subsequent runs of the algorithm.

Adrian has asked that there be some easy way of "resetting" the contents of the .dat files back to some sensible default.  This needs some thought however, since there would be at least one set of "default" .dat files for each instrument.

I think we need more information on how the scientists are using this algorithm before we decide on the best way to achieve this.

**Comment by raquelalvarezbanos** [comment]
We now have a C++ MaxEnt algorithm that only needs to read in a matrix workspace: phases and deadtimes are not needed anymore, so this issue is no longer valid. At present, the idea is that these corrections (deadtimes and phases) are performed outside of MaxEnt as a previous step in the analysis and using the existing muon algorithms.
