### ISSUE TITLE
Handle Monitors in a Consistant Way For Histogram and Event Data

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10404]
sans_bugfix
This issue was originally [TRAC 9561](http://trac.mantidproject.org/mantid/ticket/9561)

We did some work before Gesner left surrounding monitors, but I still think the difference between how we handle monitors for histogram and event data is problematic.  See problem 2. and 3. in the third comment in http://trac.mantidproject.org/mantid/ticket/9429 for more details.

**Comment by AntonPiccardoSelg** [comment]
In the new reduction backend there is no difference
