### ISSUE TITLE
Better Naming Conventions For Added Data

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10403]
sans_code
This issue was originally [TRAC 9560](http://trac.mantidproject.org/mantid/ticket/9560)

http://trac.mantidproject.org/mantid/ticket/9429 highlighted two problems with the current naming conventions for added data:
- Adding runs using the "Add Runs" tab gives us files with names of the form "SANS2D00023626-add.nxs".  This is a bad since we have no way of knowing exactly which runs it consists of -- it probably contains 23627, but does it also contain 23628, 23629 or 23630?
- We don't distinguish between having loaded 23626 and having loaded 23626-add when loading via the interface; in both cases the workspace containing the data will be called "23626_sans_nxs".

**Comment by AntonPiccardoSelg** [comment]
Note that if we change this then we might run into trouble with file loading. We would have to adapt that too.

**Comment by RichardHeenan** [comment]
Perhaps an easily accessible second level title, with the sample name (useful for all workspaces) and a list of added files ?

**Comment by smk78** [comment]
After review, the SANS Group concluded that whilst immensely irritating, this was a luxury.
