### ISSUE TITLE
"GroupingWorkspace" property of SmoothData doesn't have a test

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#10476]
This issue was originally [TRAC 9633](http://trac.mantidproject.org/mantid/ticket/9633)

Issue details are blank in trac

**Comment by Anders-Markvardsen** [comment]
In SmoothDataTest.h include a test where the property GroupingWorkspace is set.

Set as low priority since this is already been tested in a usage of http://docs.mantidproject.org/nightly/algorithms/SmoothData-v1.html but it would be additionally benefit to also test this in a unit test
