### ISSUE TITLE
Verify links in help pages

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#10521]
This issue was originally [TRAC 9679](http://trac.mantidproject.org/mantid/ticket/9679)

Now that the python documentation in bundled with algorithms, do a verification that things are rendered correctly and that the links work. Rather than methodically going through every page, this is a time-boxing exercise to check what you have the will-power for.

**Comment by NickDraper** [comment]
Verified that the existing external links work using the docs-linkcheck target.

This fails for all https links or http links that are redirected to https.  Verified those manually.
Due to the https failures this is not something that would make sense to automate.

**Comment by martyngigg** [comment]
Maybe we should have someone do a weekly check by building the target to see if anything is broken, much like the performance review. I'll put something in my calendar
