### ISSUE TITLE
MacOS crash

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10534]
This issue was originally [TRAC 9692](http://trac.mantidproject.org/mantid/ticket/9692)

Mac OSX 10.9x. Crashes  on load of any data. Had to clear the ~/.config/Mantid directory to get it to work again

I this seems to happen when users move from version X to version Y (X and Y are unknown) and the Mantid config directory is not cleared.

 - - - - 
Keywords: ILL

**Comment by NickDraper** [comment]
Without a bit more specifics there is noting to do on this one.

Archived until more info is available
