### ISSUE TITLE
ConvertUnits Should determine EMode

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10539]
This issue was originally [TRAC 9697](http://trac.mantidproject.org/mantid/ticket/9697)

If the Params file specified that an instrument is elastic/direct etc, then ConvertUnits should use this, and not prompt for an EMode

 - - - - 
Keywords: ILL, CORE

**Comment by NickDraper** [comment]
Looked further into the possibility of doing this, in particular into using the afterPropertySet(propertyName) callback.  However there are various problems that have lead me to the conclusion that this is not worth doing.

1. afterPropertySet is not fully implemented, it is called when a dialog box is filled with history values, and just before execution when the property values are set on the clean algorithm, but NOT when a change is made to a widget on the dialog box.  Further more you would need to have knowledge of why it was called (history vs user interaction vs internal copying), you don't need this is you are just validating, but if you are going to change other properties it is essential.
1. Assuming we fixed and extended the above, then I have real concerns about he confusing nature of this.  Almost every algorithm ever run will already have history records for the last run of that alg.  Which means that the EMode dialog in this case will already have a value in it.  It is potentially very confusing if that value were to change as a side effect of picking the workspace without making it very visible and obvious it was happening.  The various property states and icons are confusing enough when you consider Historic values, error states and overwrite warnings, adding another type of warning of set by other property would only make things worse. 
1. What would we do it the Emode had been manually set before changing the workspace.  Would we override that manually set value?  If so would this fit other situations that are not as clear cut as EMode?
1. Given all the above requirements I'm not sure this specific case is worth the effort.
