### ISSUE TITLE
Plotting mac issue

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10537]
This issue was originally [TRAC 9695](http://trac.mantidproject.org/mantid/ticket/9695)

Investigate a reported issue. Found during the ILL mantid training course.

```
Plot layers on the Mac. Plotting the fourth layer (says guess) and then hides the first layer.
```

 - - - - 
Keywords: ILL

**Comment by NickDraper** [comment]
Layers are so infrequently used we should not worry too much about this.

wontfix - for now

archived
