### ISSUE TITLE
Review MaxEnt Testing Situation

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10569]
This issue was originally [TRAC 9727](http://trac.mantidproject.org/mantid/ticket/9727)

Currently we are providing the MaxEnt algorithm to users via the script repo.  This has its benefits, but unfortunately it means that the unit tests we have for it are only ever run manually.

We need a way to have these tests run automatically, since we have already had our first instance where a change elsewhere has had a detrimental knock-on effect for MaxEnt.

A couple of options are open to us:

* Provide the ability to run script repository tests, though this would require some thought about where data would be stored, etc.

* Bring MaxEnt in to the main repository, perhaps when we're sure the algorithm is not going to change much and we won't need to keep on adding binary .pyd files.

**Comment by raquelalvarezbanos** [comment]
No longer an issue. MaxEnt was added to Mantid as a C++ algorithm, including a couple of unit tests (#12683). More testing will be added as we make progress (as mentioned in the original issue, the current algorithm is just a first version).
