### ISSUE TITLE
Algorithm properties should be able to accept unicode strings in python.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#10575]
This issue was originally [TRAC 9733](http://trac.mantidproject.org/mantid/ticket/9733)

At the moment this doesn't work:

```
alg.setProperty("Property",u"Value")
```

**Comment by NickDraper** [comment]
Roman - do we have an example where this is causing a problem at the moment?

**Comment by mantid-roman** [comment]
I think it was a suggestion that it would be nice to be able to use unicode in properties. I am not sure if it causes any problems.

**Comment by martyngigg** [comment]
This is no longer and issue with Python3 as `Boost.Python` knows how to handle unicode automatically.
