### ISSUE TITLE
Ubuntu package name clashes across different Ubuntu versions

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#10574]
This issue was originally [TRAC 9732](http://trac.mantidproject.org/mantid/ticket/9732)

If we want to release versions for both Ubuntu 12.04 & 14.04, we need a way to distinguish the files by distribution type.

**Comment by martyngigg** [comment]
This is now a problem for supporting 14.04/16.04 simultaneously.

**Comment by NickDraper** [comment]
has been merged - closing
