### ISSUE TITLE
Have Beam Centre Finder Log Always Reporting Messages

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10583]
This issue was originally [TRAC 9741](http://trac.mantidproject.org/mantid/ticket/9741)

Currently, when a user changes the logging level for the Results Log, this also affects the Beam Centre Finder Log in the ISIS SANS interface.  This caused some confusion for the SANS guys, and I think it's worth having these two things separate anyway.

**Comment by picatess** [comment]
Was fixed by #14506
