### ISSUE TITLE
Deb package bad quality

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#10588]
This issue was originally [TRAC 9746](http://trac.mantidproject.org/mantid/ticket/9746)

I've created a deb package for ubuntu 14.04, and when I install it, Ubuntu complains that package is of bad quality

```
E: mantid: control-file-has-bad-permissions md5sums 0664 != 0644
E: mantid: maintainer-name-missing mantid-help@mantidproject.org
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.
```

**Comment by martyngigg** [comment]
This is currently completely controlled by cmake and we are not really in control of it. The future dependencies work will probably make this irrelevant.
