### ISSUE TITLE
Better Error Message When Attempting to Save 2D Data to CanSAS

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10610]
sans_code
This issue was originally [TRAC 9768](http://trac.mantidproject.org/mantid/ticket/9768)

From Steve:

> While demonstrating Mantid [...] I went to show that it saved 2D datasets to file from the GUI too, but forgot to UNCHECK the CanSas box.
> 
> This caused a fatal error, the Results window muttering about it couldn’t write some histogram or something.
> 
> Ok, this was a totally stupid thing to do I agree, but very easy to do… it should be trapped nicely (until CanSAS have finalised the nD format!).

The error is actually not a "fatal" one (it is caught, and an admittedly obscure message is sent to the Results Log) but it's not really clear to users what went wrong.  We need to tidy use case this up.

**Comment by gemmaguest** [comment]
Closing as relates to the old gui/backend
