### ISSUE TITLE
Improve Y-Axis Units in ISIS SANS Reduction and Load/SaveCanSAS

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10629]
sans_feature
This issue was originally [TRAC 9787](http://trac.mantidproject.org/mantid/ticket/9787)

http://trac.mantidproject.org/mantid/ticket/9710, http://trac.mantidproject.org/mantid/ticket/9721 and http://trac.mantidproject.org/mantid/ticket/9772 were all "band-aid" fixes, trying to get correct unit labels for the y-axis of ISIS SANS-reduced workspaces for the purposes of plotting, as well as writing out to CanSAS data files which are then loaded into SasView.

There are some problems that need to be addressed:
- SaveCanSAS looks for `YUnitLabels` of "I(q) (cm-1)" and writes out `I` and `Idev` units of "1/cm", else it writes out whatever the `YUnitLabel` is.  Since the CanSAS format is strict about [http://www.cansas.org/formats/canSAS1d/1.1/doc/element_SASdata.html#idata which units can be used], we need to get a better handle on what other units `SaveCanSAS` should be able to write out (if any), and what the `YUnitLabels` of the workspaces being written have to be in those cases.  Should we disallow workspaces with `YUnitLabels` we don't recognise, or should we default to some sensible unit and output a warning?
- LoadCanSAS does not (and has never) read in y-axis unit labels, meaning YUnitLabels on plots do not survive the roundtrip of Save/LoadCanSAS.

The algorithm documentation should be updated accordingly.

**Comment by gemmaguest** [comment]
Closing as users are being recommended to use Load/SaveNXCanSAS instead
