### ISSUE TITLE
CatalogDownloadDataFiles should indicate if archive search needs to be enabled

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#10662]
This issue was originally [TRAC 9820](http://trac.mantidproject.org/mantid/ticket/9820)

If CatalogDownloadDataFiles returns some archive locations to load from and the search archive property is off the download will fail.

The algorithm should either have an output property indicating if archive search is required or fall back to http download if it's unavailable.

**Comment by NickDraper** [comment]
Just tested with GEM62851, with archivesearch off and this now works fine.

Must have been fixed since this ticket.

works4me
