### ISSUE TITLE
Some LARMOR Runs Still Can't Be Reduced

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10669]
sans_bugfix
This issue was originally [TRAC 9827](http://trac.mantidproject.org/mantid/ticket/9827)

http://trac.mantidproject.org/mantid/ticket/9634 was introduced to allow data files without Sample Geometry information to go through the ISIS SANS reduction.  Unfortunately, the changes have only meant that the LARMOR files we were having the problem with now get further along in the reduction before falling over somewhere else.

Testing for http://trac.mantidproject.org/mantid/ticket/9634 included manually removing the Sample Geometry information from a SANS2D run.  There must be something else wrong with the LARMOR files besides missing Sample Geometry information.

LARMOR run 217, for example, fails with the following error:

```
CropWorkspace started
EndWorkspaceIndex out of range!
Error in execution of algorithm CropWorkspace:
EndWorkspaceIndex out of range!
ValueError: Can not find spectra for DetectorBench in the workspace 217rear_1D_0.9_12.5 [10,40969]
Exception:(`<type 'exceptions.IndexError'>`, IndexError('EndWorkspaceIndex out of range!',), `<traceback object at 0x000000000F7C0988>`)
at line 32 in '`<Interface>`'
caused by line 402 in 'scripts/SANS\ISISCommandInterface.py'
caused by line 679 in 'scripts/SANS\ISISCommandInterface.py'
caused by line 673 in 'scripts/SANS\ISISCommandInterface.py'
caused by line 377 in 'scripts/SANS\isis_reducer.py'
caused by line 1109 in 'scripts/SANS\isis_reduction_steps.
```

**Comment by AntonPiccardoSelg** [comment]
LARMOR does not seem to have any issues any more. Should be closed
