### ISSUE TITLE
Disable Buttons on User File Reload

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10677]
sans_feature
This issue was originally [TRAC 9835](http://trac.mantidproject.org/mantid/ticket/9835)

Richard has pointed out that it is possible to press the "1D/2D Reduce" buttons when the User File is reloading, causing yourself some trouble.  This has become more of an issue as the loading of User Files is starting to take longer than it used to.

He quite rightly suggested that we should disable any buttons that users shouldn't be clicking while User Files are loading.

**Comment by AntonPiccardoSelg** [comment]
Seems to not exist any longer
