### ISSUE TITLE
Allow Unmasking By Time Channel for Specific Parts of Detector Bank

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10676]
sans_feature
This issue was originally [TRAC 9834](http://trac.mantidproject.org/mantid/ticket/9834)

Currently we can mask by time channel, but the mask is applied to the entire detector bank.  Richard has asked for a way to only mask certain parts of the bank.

It is not clear how well Q1D is currently set up to accommodate a change like this.

**Comment by AntonPiccardoSelg** [comment]
We don't have time masking on a per detector basis in Mantid as far as I am aware.

**Comment by RichardHeenan** [comment]
At present if we see say Bragg spikes we play safe and take out those time bins over the whole detector (all detector banks ? - CHECK) , which is often over kill.

(If it is all banks, then we ought to have time masking on specific banks only.)

However to time mask in specific regions would make the setting up of a mask and Q1D etc much more complicated, and probably not worth the effort or the slow down in reduction.
