### ISSUE TITLE
Issues around Group Workspaces

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10709]
This issue was originally [TRAC 9867](http://trac.mantidproject.org/mantid/ticket/9867)

There is a very annoying defect in the WorkspaceGroups in the WorkspaceList in mantid plot. 

* Create a WorkspaceGroup 
* Add some workspaces to it, say 5 workspaces.
* Recreate the WorkspaceGroup, this time with just 2 workspaces, but don't explicitly Delete the WorkspaceGroup.
* The group has been recreated, and the 2 workspaces are renewed, however, the  other 3 workspaces are orphaned.

I'm sure that this isn't the correct behaviour. Surely the workspaces should be removed.

**Comment by NickDraper** [comment]
Looked into this one and it appears that the current behaviour (effectively ungrouping and then regrouping) is probably the best in most situations:

1. the problem above only occurs if the group workspace is named the same (this is easy to do by mistake using the group button)
1. The current approach avoid implicitly deleting workspaces which could be a very bad thing is that was not the intent.
1. If a gui or script intended to fully overwite a group workspace it would not be hard to delete that group workspace first.

Wontfix
