### ISSUE TITLE
PointDetectorStart PointDetectorStop

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10701]
This issue was originally [TRAC 9859](http://trac.mantidproject.org/mantid/ticket/9859)

Not sure that the concept of PointDetectorStart PointDetectorStop actually makes sense, though it does for a MultiDetector.

* Does the start/stop make sense
* Change the behaviour inclusive/exclusive to match that for CropWorkspace

**Comment by raquelalvarezbanos** [comment]
Agreed to archive and close this.
