### ISSUE TITLE
Mask by Component (I.e. by Tube)

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10711]
This issue was originally [TRAC 9869](http://trac.mantidproject.org/mantid/ticket/9869)

We currently have the ability to "pick" by component in the Instrument View.  It would be nice if we had a similar functionality when masking.

Richard Heenan has commented that it is quite fiddly to mask the entirety of a SANS2D tube without accidentally masking other detectors.  This would seem to be a perfect solution.

**Comment by soininen** [comment]
@mantid-roman Have you any plans on working on this issue? I'm planning to add mask-by-component functionality to [`MaskDetectors`](http://docs.mantidproject.org/nightly/algorithms/MaskDetectors-v1.html), and I would like to avoid duplicate work.

**Comment by mantid-roman** [comment]
@soininen Not in the immediate future. If you would like to take over it I'd be happy to let you.

**Comment by soininen** [comment]
@mantid-roman I don't know what this current issue actually includes --- it is labeled as 'GUI' so I am not sure to what extend my intended changes would help here. On the other hand I have assigned myself to issue #18327  Perhaps when its done you can judge whether to close this issue as well.

**Comment by mantid-roman** [comment]
@soininen It is a GUI issue. It can use the results of #18327. There will be no clash then.
