### ISSUE TITLE
Reword "Save" Button in File Dialog

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10713]
sans_bugfix
This issue was originally [TRAC 9871](http://trac.mantidproject.org/mantid/ticket/9871)

The "Browse" button in the "Save" widget group of the "Run Numbers" tab of the interface has a button labelled "Save".  This is misleading, since nothing actually gets saved until "Save Result" is clicked in the interface.

Some rewording is required here.

**Comment by gemmaguest** [comment]
Closing as this relates to the old interface
