### ISSUE TITLE
Default Directories in File Saving Dialogs

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10714]
sans_feature
This issue was originally [TRAC 9872](http://trac.mantidproject.org/mantid/ticket/9872)

During beta testing Steve King brought up the fact that it can be hard to predict/understand which directory various dialogs in the interface will point to when you want to save a file, etc.

We need to take a look at this and see exactly what the current behaviour of the dialogs is, and then decide how it can be improved.

Possibilities:
- Have them point to the user's specified save directory by default.
- When remembering which directory the user navigated to last, have this remembered across all ISIS SANS dialogs.

We need to make sure all the scientists agree on what the desired behaviour should be.

**Comment by gemmaguest** [comment]
Closing as the directory is now consistent with the default save directory in the new interface
