### ISSUE TITLE
Modify ConvertUnits to take detector table

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#10722]
This issue was originally [TRAC 9880](http://trac.mantidproject.org/mantid/ticket/9880)

This ticket is blocked by : 
 - [ ] [TRAC9879](http://trac.mantidproject.org/mantid/ticket/9879)

Add an optional workspace with a detector table which will be used rather than the instrument geometry. The table is changing according to http://trac.mantidproject.org/mantid/ticket/9879.

**Comment by stuartcampbell** [comment]
Closing this now as we are just going to use a separate algorithm for now and probably need to look more seriously at ```ConvertUnits()``` in the future.
