### ISSUE TITLE
EQSANS data catalog

### ISSUE THREAD

**Issue by mdoucet** [mantidproject/mantid#10725]
This issue was originally [TRAC 9883](http://trac.mantidproject.org/mantid/ticket/9883)

The EQSANS team would like to add columns to the data catalog tab of their reduction interface.
The items they would like to see are LambdaRequest, file_notes, and whether we are in frame-skipping mode or not (using SpeedRequest1 from the logs).

**Comment by ricleal** [comment]
TODO:

In:
```
/home/rhf/git/mantid/Code/Mantid/scripts/Interface/reduction_gui/reduction/sans/eqsans_catalog.py
```
Add new properties in: 
```
EQSANSDataSet.read_properties
EQSANSDataSet.__init__
```
Change accordingly:
```
/home/rhf/git/mantid/Code/Mantid/scripts/Interface/reduction_gui/reduction/sans/data_cat.py
```

Fields available in logs when loading:
```
LoadEventNexus(Filename='/SNS/EQSANS/IPTS-9820/data/EQSANS_24440_event.nxs', OutputWorkspace='test', MetaDataOnly=True)
```
| file_notes | string | NONE |
| LambdaRequest | num.series | 2 |
| SpeedRequest1 | num.series | 60 |
