### ISSUE TITLE
Only Positive Q Included When Doing a "Merged" 2D Reduction

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10732]
This issue was originally [TRAC 9890](http://trac.mantidproject.org/mantid/ticket/9890)

From Richard

>
>Babylon5/public/rkh/forMantidTests
>
>Has files for
>
>MASK141O  using M3 transmissions
>
>24274    24282   24272
>
>27300    24293   24272
>
>This has massive scatter at small Q, plus three peaks on the border between front and rear detectors, see pdf plots. When I tried a 2d reduction “merged” there seems to be a bug in that only positive Q was included.

**Comment by picatess** [comment]
This was fixed in #14700
