### ISSUE TITLE
LoadSPE does not close (locks) opened spe files

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10776]
This issue was originally [TRAC 9934](http://trac.mantidproject.org/mantid/ticket/9934)

or lock them, so they can not be deleted/moved etc even though Mantid have finished with these files. 

Should be fixed

**Comment by NickDraper** [comment]
Just tested on windows

LoadSPE
then go to windows explorer and rename file

Passed just fine

Works4me
