### ISSUE TITLE
Migrate Remaining Contents of the WorkflowAlgorithmsTest Project to System Tests

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10816]
This issue was originally [TRAC 9975](http://trac.mantidproject.org/mantid/ticket/9975)

http://trac.mantidproject.org/mantid/ticket/9896 highlighted a slow unit test in the WorkflowAlgorithmsTest project that had to be moved to a system test.  Ideally, all the tests in that project should be moved, since they are by definition integration tests.

 - - - - 
Keywords: Maintenance

**Comment by NickDraper** [comment]
Most slow test have now been dealt with. No workflow algorithms test takes more than 5.5 seconds, and most are quicker than that.

http://builds.mantidproject.org/job/master_incremental/label=win7/lastCompletedBuild/testReport/WorkflowAlgorithmsTest/
