### ISSUE TITLE
SliceViewer line view does not work on rotated slice

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10814]
This issue was originally [TRAC 9972](http://trac.mantidproject.org/mantid/ticket/9972)

This ticket is blocks :  [TRAC11618](http://trac.mantidproject.org/mantid/ticket/11618)

Take Mary reduced sample Data from Mantid system tests and convert it in QW space. 

```
Load(Filename='D:\users\abuts\SVN\MantidTraining\MARIReduction.nxs', OutputWorkspace='MARIReduction', LoaderName='LoadNexusProcessed', LoaderVersion=1)
SofQW3(InputWorkspace='MARIReduction', OutputWorkspace='MARIReductionMD', QAxisBinning='0,0.05,5', EMode='Direct')

```

Rotate the slice (change axis X and Y to get usual inelastic view) and try to look at the slice using line tool. The result is unreasonable -- it looks like it integrates along x-axis and draws line along Y. 

Normalization also does not work (ok, it should not on a matrix workspace, but then why it is there?)

**Comment by OwenArnold** [comment]
This might have been fixed. There was an issue a while back where we had to fix how Rebin2D took its parameters from the SliceViewer in the case of rebinning a MatrixWorkspace.

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew Check with Alex Buts how to reproduce this issue fully

**Comment by AntonPiccardoSelg** [comment]
Apparently there has been a shift away from the SliceViewer to MSlice. Therefore this issue can be closed
