### ISSUE TITLE
'Advanced' Refl GUI

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10847]
This issue was originally [TRAC 10005](http://trac.mantidproject.org/mantid/ticket/10005)

Report on status of advanced reflectometry gui to ISIS instrument scientists. How is the data loaded, presumably default nexus loading is not used.

**Comment by OwenArnold** [comment]
There may be an opportunity now not to do this.

**Comment by raquelalvarezbanos** [comment]
Note from Owen: @peterfpeterson was unable to reconcile the two branches of this at the SNS. Then Harry looked at writing a swappable backend, but found that the data structures where too different between Arthurs GUI and Mantid. Then Arthurs left the SNS. In conclusion, we desire this functionality, but it's not clear how to harmonize Mantid and Arthurs GUI. I suggest that we follow through what Tim is doing now on REFM, and see what tools he needs to work with Area detectors as he works through Mantid. Those tools should be as decoupled as possible from Mantid and MantidPlot, but still use Mantid for the data reduction.
