### ISSUE TITLE
Improve code documentation in Rules.cpp

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#10843]
This issue was originally [TRAC 10001](http://trac.mantidproject.org/mantid/ticket/10001)

Documentation in Objects/Rules.cpp is not bad, but looking at this as part of coverity warning (CID=1075601) and ticket http://trac.mantidproject.org/mantid/ticket/9943, in this ticket improve document of Rules.cpp lines:

// Clear up the mess and delete the rule that we have changes
delete tmpA;  

i.e. explain better than using 'clear up the mess' to give confidence to the reader that deleting tmpA is the right thing to do, also with reference to the Rules.cpp line:

         tmpA=TreeComp.third;       // get base item

 - - - - 
Keywords: Maintenance

**Comment by NickDraper** [comment]
archived
