### ISSUE TITLE
Profile LoadISIS Nexus

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10848]
This issue was originally [TRAC 10006](http://trac.mantidproject.org/mantid/ticket/10006)
- What is the status of the HDF5 loading that peter peterson was looking into.
- What is taking the time when the ISIS Nexus files are loaded? Use KCacheGrid to get some information.
- What sort of speedup could be achieved, and where could it come from?

**Comment by NickDraper** [comment]
ISIS SANS event files have been highlighted as a particular area that needs some speedup.

Speak to Stephen King for some concrete examples

**Comment by gemmaguest** [comment]
Closing as now covered as part of #25723
