### ISSUE TITLE
Create ExtractSpectra Algorithm -- A More Generic Version of ExtractSingleSpectrum

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10867]
This issue was originally [TRAC 10025](http://trac.mantidproject.org/mantid/ticket/10025)

It would be nice to have a more generic version of the ExtractSingleSpectrum algorithm, so one can specify an arbitrary list of detector IDs / workspace indices / spectra numbers to keep, and ignore the rest.

(Note that CropWorkspace does not provide this functionality, since that only accepts a single range of workspace indices, and our arbitrary list of spectra may not be contiguous.)

Martyn has said that it would make sense for such an algorithm to take out the existing code from ExtractSingleSpectrum and adjust it so that it works in the new general case.  ExtractSingleSpectrum could then just make a forwarding call to ExtractSpectra.

Note that there currently is a workaround (multiple calls to ExtractSingleSpectrum followed by calls to ConjoinWorkspaces), but this new algorithm would be more convenient.

**Comment by martyngigg** [comment]
This has been done as part of #12457
