### ISSUE TITLE
User suggestion for Binary Operations Compatiblility

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10878]
This issue was originally [TRAC 10036](http://trac.mantidproject.org/mantid/ticket/10036)

Users want to be able to replicate A - B where B is a single spectra workspace, from a workspace B where B > 1 histogram by providing a workspace index.

I guess it would make sense to provide this option for all binary operation. We should also update the workspace compatibility documentation as part of this.

**Comment by NickDraper** [comment]
The functionality of minus of one spectra against a workspace of many is to apply that to all spectra in turn.

wontfix
