### ISSUE TITLE
Fix DET/MERGE(D) Command

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10888]
This issue was originally [TRAC 10046](http://trac.mantidproject.org/mantid/ticket/10046)

There are several problems here.  Some comments from Steve:

- - - - 

>I have a user file that starts
>
>```
>LOQ
>PRINT This is a LOQ user file for Mantid merging detectors
>DET/MERGED
>```
>
>To which Mantid quietly (ie, no red text) reports
>
>```
>THIS IS A LOQ USER FILE FOR MANTID MERGING DETECTORS
>setDetector: Detector not found
>setDetector: Detector set to main-detector-bank in LOQ
>```
>
>even though it **has** set the Detector Bank in the Reduction tab to ‘merged’…

- - - - 

>Actually there is a slight correction to what I said previously:
>
>If you put DET/MERGED in the user file, which is what http://www.mantidproject.org/SANS_User_File_Commands#FIT says you should put, then it **does not** set merged detectors, it does indeed default to the main only.
>
>If you put DET/MERGE in the user file it sets merged detectors.
>
>I’ve only just found this.
>
>Can we make the script command parser insensitive to the ‘D’ on MERGED?

- - - - 

>Actually I think I may have a handle on where the
>
>```
>setDetector: Detector not found
>setDetector: Detector set to main-detector-bank in LOQ
>```
>
>its not just the DET/MERGE, it’s **any** incorrect use of the DET >command; eg, a DET/RESCALE, with a simple typo and so on.

- - - - 

>Right, let me see if I can be more definitive:
>
>1. On first running Mantid:
>
>  a. If the user file contains DET/MERGED (what the wiki says you should type) the results log returns
>  ```
>  setDetector: Detector not found
>  setDetector: Detector set to main-detector-bank in LOQ
>  ```
>
>  and **does not** set merged detectors in the GUI (it defaults to the main detector)
>
>  b.	If the user file contains DET/MERGE the results log returns
>
>  ```
>  setDetector: Detector not found
>  setDetector: Detector set to main-detector-bank in LOQ
>  ```
>
>  and **does not** set merged detectors in the GUI (it defaults to the main detector)
>
>2. If you specifically **reload** the user file after starting the ISIS SANS GUI:
>
>  a) And the user file contains DET/MERGED (what the wiki says you should type) the results log returns
>
>  ```
>  setDetector: Detector not found
>  setDetector: Detector set to main-detector-bank in LOQ
>  ```
>
>  but **does** set merged detectors
>
>  b. And the user file contains DET/MERGE the results log returns
>
>  ```
>  setDetector: Detector not found
>  setDetector: Detector set to main-detector-bank in LOQ
>  ```
>
>  but **does** set merged detectors
>
>  So contrary to what I thought yesterday the parser does seem to be agnostic to the ‘D’ on MERGED, but >currently the only way to get a user file to set merged detectors is to specifically **reload** the user file.
>
>3. Interestingly, if the user file contains a DET/RESCALE/FIT (in my example after the DET/MERGE(D)) that **is** correctly implemented when the user file is initially loaded.
>
>4. Likewise, if the user file contains a DET/SHIFT/FIT (again, after the DET/MERGE(D)) that **is** correctly implemented when the user file is initially loaded.
>
>So there is something odd about the way the GUI is treating the DET/MERGE(D) command on initially loading of the user file which is different to how it treats other qualifiers on the DET command.

- - - - 

After a quick look at the code, this boils down to three issues as far as I can tell:

1. We don't parse the input correctly.
2. We don't cope with `merged`/`both` options correctly.
3. We store the result of parsing in a couple places, that don't all get updated in all circumstance.

**Comment by picatess** [comment]
__Partial solution__

Modifications in the [isis_reduction_steps](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/scripts/SANS/isis_reduction_steps.py#L2086:L2094)
```
elif det_specif == 'REAR' or det_specif == 'FRONT' or  det_specif == 'BOTH' or det_specif == 'MERGED' or det_specif == 'MERGE':
...
else: # This will catch typos and raise a specific warning
      _issueWarning(....)
```
This should fix the first two points mentioned by Peter. 

I am currently not sure what Stephen means with points 3 and 4

**Comment by picatess** [comment]
As Peter has mentioned there are several issues:
*  We don't parse REAR, FRONT, MERGE, MERGED, BOTH at all. It rather falls through and gets picked up by the the instrument. We should parse for these exact values and relase a warning if they are misspelt.
*  Setting the detector selection is a mix of new code (which is about setting the detector selection) and old code which is related with the two physical detectors. Ideally these two things are separated, but as unit tests are missing it is hard to see what the implications might be. The warnings of this method relate to a time where the detector seleciton could only be one of the two physical detectors. It does not take into account the possibility of BOTH or MERGED. Hence we should silence the warning.
*  The actual issue is caused when starting the GUI. Two methods are called in the initialization which affect the detectors selection: ```loadUserFile()```` whichis followed by `` handleInstrumentChange()```. While the first method sets the detector selection correctly, the second method overwrites it with ```.ReductionSingleton().instrument.cur_detector().name()``` . This also seems from a time when there was no MERGED or BOTH option. We will fall back to this procedure if ```ReductionSingleton().instrument.det_selection``` is empty, else we leave it.
