### ISSUE TITLE
Reduce Number of Time We Reload/Process the Calibration File

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10890]
sans_code
This issue was originally [TRAC 10048](http://trac.mantidproject.org/mantid/ticket/10048)

As per the ticket summary.  We need to be more clever about when the calibration file gets loaded/applied, rather than just blindly loading/applying it every time it is used.

There are probably a few more similar things we could squeeze into this ticket if we have the time.

**Comment by AntonPiccardoSelg** [comment]
Handled in the new reduction backend
