### ISSUE TITLE
Merge in Tube Calibration Changes from Richard

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#10892]
sans_feature
This issue was originally [TRAC 10050](http://trac.mantidproject.org/mantid/ticket/10050)

At some point we need to merge in Richard's changes to the Tube Calibration code.  This will get to be a bigger and bigger issue the longer we leave it.

**Comment by AntonPiccardoSelg** [comment]
Hmm, I have been unaware of this. @Mantid-Matthew Pleas speak to Richard about this.

**Comment by Mantid-Matthew** [comment]
Tube calibration code is separate to Mantid and used to generate calibration files. Need to check with current scientists where these scripts are currently stored.

**Comment by gemmaguest** [comment]
Check with Richard what, if anything, needs doing

**Comment by RichardHeenan** [comment]
I think this still needs some work.
There were a handful of changes to the underlying shared py code (e.g. it only worked for vertical tubes, not the horizontal ones on SANS2d), but then there were recently some py3 issues.

**Comment by smk78** [comment]
This is important, but will be much more effort than integrating the Direct Beam iterating script.
Also see https://github.com/mantidproject/mantid/issues/27386

**Comment by gemmaguest** [comment]
Closing this in favour of #27386 because I think we only need to worry about the latest versions of the scripts
