### ISSUE TITLE
Using class_maker.py on MantidGeometry breaks the build

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#10900]
This issue was originally [TRAC 10058](http://trac.mantidproject.org/mantid/ticket/10058)

When adding a new class to MantidGeometry with the class_maker.py script, the CMakeLists-file is altered. The following line, which is located near the end of the CMakeLists-file:

```
   set (SRC_FILES ${SRC_FILES} ${OPENCASCADE_SRC} )
```

is replaced by an additional line at the beginning of `set ( SRC_FILES ...`:

```
   ${SRC_FILES} ${OPENCASCADE_SRC}
```

which is at the beginning of the file.

After this modification, building Mantid results in the following linker errors (Ubuntu):

```
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::OCGeometryHandler(Mantid::Geometry::Object*)'
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::getTriangleFaces()'
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::NumberOfTriangles()'
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::getTriangleVertices()'
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::NumberOfPoints()'
../bin/libMantidGeometry.so: undefined reference to `Mantid::Geometry::OCGeometryHandler::~OCGeometryHandler()'
```

Another problem is that the generated unit test file contains this line:

```
using namespace Mantid::API;
```

which will only compile if something that imports something from Mantid::API is tested.

**Comment by martyngigg** [comment]
This was fixed by #17324.
