### ISSUE TITLE
Separate monitors into a subworkspace when loading live data.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#10913]
This issue was originally [TRAC 10071](http://trac.mantidproject.org/mantid/ticket/10071)

For some instruments at ISIS the monitors can have a time regime (binning, number of bins) different form those of the data spectra. In this case the monitors cannot be put into the same workspace with the data. 

When loading live histogram data the monitors should be stored in a subworkspace (monitor workspace) of the data matrix workspace. If we are loading a list of spectra mixing of time regimes isn't allowed, throw an error.

**Comment by NickDraper** [comment]
There is little drive to develop live data at isis at present - archived
