### ISSUE TITLE
Optional tickbox to continually run ICAT loop

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#10959]
This issue was originally [TRAC 10117](http://trac.mantidproject.org/mantid/ticket/10117)

If the tickbox is ticked and an ICAT search is performed. The search will be re-run every time period (unspecified) the workspace list in the ReflGui will be repopulated and the actual data will be downloaded into Mantid ready for processing.

**Comment by raquelalvarezbanos** [comment]
Message from @OwenArnold: Looking back at this, I'm not sure that an ICAT loop is a good idea. Does this fit somehow with what @zjttoefs might be doing at the ESS in terms of cataloging (I could be completely wrong about this)?
