### ISSUE TITLE
SofQW3 throws bad alloc and Mantid generates spurions instances  when logs are set to Debug level (at least on large files under Windows)

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10968]
This issue was originally [TRAC 10126](http://trac.mantidproject.org/mantid/ticket/10126)

This ticket is blocked by : 
- [X] [TRAC9971](http://trac.mantidproject.org/mantid/ticket/9971)
  
  The script below works fine when logs are in Notice mode: Produces reasonably looking file in 35 seconds:

SofQW3 started SofQW3 successful, Duration 34.91 seconds

```
######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
Load(Filename=r'D:\Data\Fe\Fe_Mantid\MAP15052.nxspe',OutputWorkspace='MAP15052')
SofQW3(InputWorkspace='MAP15052',OutputWorkspace='MAP15052MD',QAxisBinning='0,0.1,14',EMode='Direct')


```

Trying the same job when logs are on debug level: after some time the program becomes unresponsive (you can not cancel the algorithm)  and number of empty windows with Mantid logo is generated. Then the algorithm finishes without providing result throwing bad alloc (caught by upper Mantid catch clause, suggesting to terminate the program)

User have the opportunity to save results and restart Mantid but any further operations with Mantid become impossible

I suspect problem lies not with SofQW3 but with logs thread safety. SofQW3 just generates logs which are too big. 

Strange behaviour of ISISDirectReduction script run with the logs at debug level observed with Matid3.2, but I can not clearly associate it with logging.

**Comment by JoachimCoenen** [comment]
When logs are set to Debug level, the output log created by SofQW3 easily exceeds 150 MB and > 900K lines. (Version 3.12.1, Ubuntu)
