### ISSUE TITLE
Add description of the error propagation in some algorithms to existing error propagation description

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10969]
This issue was originally [TRAC 10127](http://trac.mantidproject.org/mantid/ticket/10127)

Explicit description of the error propagation/calculation procedure should be added to http://www.mantidproject.org/Error_Propagation for 
Rebin, CalculateFlatBackground (and similar) and ConvertMDHistoToMatrixWorkspace. 

I heard complains about their procedure and suspect follow up tickets there. 

---

Keywords: Maintenance

**Comment by Anders-Markvardsen** [comment]
Example where link to error propagation page has been added: http://docs.mantidproject.org/nightly/algorithms/Plus-v1.html
