### ISSUE TITLE
SliceViewer and VATES simple interface throw scary exceptions, while visualizing a MD workspace with an infinite dimension

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#10972]
This issue was originally [TRAC 10130](http://trac.mantidproject.org/mantid/ticket/10130)

This is follow-up from the ticket 
http://trac.mantidproject.org/mantid/ticket/9798. 

run script

```

CreateSampleWorkspace(OutputWorkspace='TWS', WorkspaceType='Event')
ConvertToMD(InputWorkspace='TWS', QDimensions='Q3D', dEAnalysisMode='Elastic', QConversionScales='HKL', OutputWorkspace='mdWs1', SplitInto='100,100,10')

```

There is no crash now, but I am not sure if the issue can be considered solved. 
# 

VATES Simple interface:
# 

while trying to view the workspace in questions it brings the empty window up, but then when trying to see what is inside (pressing rebin), an  unexpected exception is thrown.

"Sorry, MantidPlot has caught an unexpected exception:

Invalid string passed to createDimension: Syntax error"

and usual scary stuff, suggesting to save the data and restart Mantid. 

no rebinning interface appears and attempt to look at it brings the window with following:

```

ERROR: In C:\jenkins\workspace\isis_win7_paraview-3.98.1\build\paraview\src\paraview\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 780
vtkPVCompositeDataPipeline (0000000013EE8850): UpdateInformation invoked during another request.  Returning failure to algorithm vtkMDEWRebinningCutter(0000000014F18E20).


ERROR: In C:\jenkins\workspace\isis_win7_paraview-3.98.1\build\paraview\src\paraview\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 780
vtkPVCompositeDataPipeline (0000000013EE8850): UpdateInformation invoked during another request.  Returning failure to algorithm vtkMDEWRebinningCutter(0000000014F18E20).


ERROR: In C:\jenkins\workspace\isis_win7_paraview-3.98.1\build\paraview\src\paraview\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 780
vtkPVCompositeDataPipeline (00000000143E3430): UpdateInformation invoked during another request.  Returning failure to algorithm vtkMDEWRebinningCutter(000000001416D820).


ERROR: In C:\jenkins\workspace\isis_win7_paraview-3.98.1\build\paraview\src\paraview\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 780
vtkPVCompositeDataPipeline (00000000143E3430): UpdateInformation invoked during another request.  Returning failure to algorithm vtkMDEWRebinningCutter(000000001416D820).

```

I know that mainly workspace is fine so you would be able to rebin and see the main part of the workspace except the one which contains unphysical values. I think, dimensions limits in this case should be reduced automatically to large negative (non-infinite) values
# 

Sliceviewer:
# 

Ok, this probably acceptable solution except the standard scare window is thrown which suggest you to terminate Mantid by default. 

Do not know how difficult it would be to change this window, but if it is really difficult at least the custom message should sound more reassuring like:

"You can disregard this error message and continue to use Mantid. To view the workspace you should rebin it and cut-off the infinite limit in the dimension N 1 (2,3... whatever is suitable) " 

This is not a crash now but substantial usability issue, so I am decreasing the importance of this ticket.

**Comment by martyngigg** [comment]
Closed as this relates to features being removed with MantidPlot.
The new workbench sliceviewer shows a warning about not having a compatible workspace and does not raise an unhandled exception.
