### ISSUE TITLE
Constraint setting isn't working in FitPropertyBrowser, and other issues

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#11019]
This issue was originally [TRAC 10177](http://trac.mantidproject.org/mantid/ticket/10177)
- If you try to set constraints to 10% or 50% you always get zeros.
- "To function" tie option shows only for top-level composite function.
- "Workspace" attribute should have a drop-down box.

**Comment by DanielMurphy22** [comment]
No longer issues!
