### ISSUE TITLE
Python rebinning memory leak

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#11046]
This issue was originally [TRAC 10204](http://trac.mantidproject.org/mantid/ticket/10204)

From a user:

---

Unfortunately I have found another issue with Mantid scripting.  Using the algorithms natively I can produce the following script history:

```
Load(Filename='\\isis\inst$\NDXENGINX\Instrument\data\cycle_12_1\ENGINX00185905.raw', OutputWorkspace='ENGINX00185905', LoaderName='LoadRaw', LoaderVersion=3, SpectrumMax=2400)
ConvertUnits(InputWorkspace='ENGINX00185905', OutputWorkspace='185905-d', Target='dSpacing', AlignBins=True)
Rebin(InputWorkspace='185905-d', OutputWorkspace='185905-bin', Params='0.001')
```

However, executing the last line in any python shell consumes infinite system memory indefinitely. Executing the Rebin algorithm on its own typically takes 0.1 seconds. The problem persists in the distributions anaconda, canopy and IDLE, and is reproduced in the mantidplot command-line, as well as the python.exe contained in MantidInstall/bin/.
This is a new problem on 3.2.0. 

---

I have tested this thoroughly on Ubuntu 14.04 against the latest `master` and could not reproduce it. I suspect this may be a Windows specific problem. Could someone with a Windows environment try to reproduce this.

**Comment by DavidFair** [comment]
Tested against Mantid 3.11. At a rebin parameter of 0.001 about ~48GB of RAM would be required. I suspect the user has experienced OOM conditions

Closing.
