### ISSUE TITLE
LoadSQW will fail when loading sqw file with image not aligned with lab frame

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#11056]
This issue was originally [TRAC 10214](http://trac.mantidproject.org/mantid/ticket/10214)

subj. 

Currently LoadSQW will not load a sqw file with DND image not aligned according to "lab frame ?" coordinates (not sure the term is correct). The pixels (MD events) in SQW file are expressed in these coordinates. 

The algorithm will formally work, but the result will be incorrect. 

The purpose of the ticket is to modify load SQW to load data properly.

**Comment by abuts** [comment]
The issue is actually much deeper as there are subtle differences in data loading procedure which generate MD workspaces slightly different from SQW workspaces. The differences should be rectified.

**Comment by martyngigg** [comment]
The way `LoadSQW` is currently structured is making it difficult to change what is loaded and understand how the file is layed out. My plan is therefore to create a `LoadSQW` v2.
