### ISSUE TITLE
Improve description of Processing Instructions in documentation of PerformIndexOperations

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#11071]
This issue was originally [TRAC 10229](http://trac.mantidproject.org/mantid/ticket/10229)

This ticket is blocked by : 
 - [X] [TRAC10052](http://trac.mantidproject.org/mantid/ticket/10052)

Prior to ticket http://trac.mantidproject.org/mantid/ticket/10052 the documentation of PerformIndexOperations has no description of the ProcessInstructions property. Ticket http://trac.mantidproject.org/mantid/ticket/10052 adds something of use, but it could be improved.

**Comment by NickDraper** [comment]
documentation is now present

works4me
