### ISSUE TITLE
Ability to plot a mini contour plot in a custom interface

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11167]
This issue was originally [TRAC 10325](http://trac.mantidproject.org/mantid/ticket/10325)

Similar to the curve mini plots, a Qt widget that shows a preview of a contour plot.

**Comment by NickDraper** [comment]
without a place we need this is it not worth starting this work.

Invalid

**Comment by DanNixon** [comment]
This has been something Spencer has been wanting on the indirect interfaces for a while, that is why the ticket was created.
