### ISSUE TITLE
SofQW3 plotting issue

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11236]
This issue was originally [TRAC 10394](http://trac.mantidproject.org/mantid/ticket/10394)

There is some confusion here about vertical axis names and y-data names. For example, in the following the plot y-axis is called 'SpectrumNumber', but shouldn't this be counts? I made a note about this in http://trac.mantidproject.org/mantid/ticket/10365 because it's affecting the SliceViewer plotting too.

```
#!python
# create sample inelastic workspace for MARI instrument containing 1 at all spectra
ws=CreateSimulationWorkspace(Instrument='MAR',BinParams='-10,1,10')
# convert workspace into Matrix workspace with Q-dE coordinates
ws=SofQW3(InputWorkspace=ws,QAxisBinning='-3,0.1,3',Emode='Direct',EFixed=12)

plotSpectrum(ws, 0)
# Plot y axis is called SpectrumNumber? 
```

**Comment by martyngigg** [comment]
This is no longer an issue. The y-axis on a 1D plot now has the correct Intensity label.
