### ISSUE TITLE
IPython crashes Mantid on string substitution

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#11286]
This issue was originally [TRAC 10444](http://trac.mantidproject.org/mantid/ticket/10444)

Observed on windows

Build mantid in Debug mode, go to Ipyton window, type Re and tab to see the list of algorithm starting with Re

Mantid throws Runtime error

assert: "f==frame" in file text\qtextdocument_p.cpp line 1500. 

You can debug the application or just finish Mantid session.

**Comment by jclarkeSTFC** [comment]
This isn't a problem in 6.8, must have been fixed sometime.
