### ISSUE TITLE
Overlaying peaks

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#11348]
This issue was originally [TRAC 10506](http://trac.mantidproject.org/mantid/ticket/10506)

Feng wants Mantid to only overlay peaks if the run number of the peak matches the run number of the MD workspace or of the sample file for the instrument view.

**Comment by NickDraper** [comment]
Vickie, is this still a current request?

Comment and assign back to me if it is, otherwise add the archive label and close

**Comment by VickieLynch** [comment]
Yes, Feng noticed this was not done in the past few days when we were looking at his data.
