### ISSUE TITLE
Data vs Instrument Load Times

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11342]
This issue was originally [TRAC 10500](http://trac.mantidproject.org/mantid/ticket/10500)

This ticket is blocked by : 
- [X] [TRAC10385](http://trac.mantidproject.org/mantid/ticket/10385)
- [X] [TRAC10471](http://trac.mantidproject.org/mantid/ticket/10471)

This is a report requested by the reflectometry group.

It should be possible to separate out and establish how much time the load algorithms spend loading workspace values as opposed to loading, logs, parameters and other instrument related information. The previous tickets will help with this.

Also investigate how the SECI loads are happening. I'm told that the load times are much faster.

**Comment by gemmaguest** [comment]
Closing as Stale because this is not currently a concern for the scientists.
