### ISSUE TITLE
Implement WorkspaceGroup getters

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11345]
This issue was originally [TRAC 10503](http://trac.mantidproject.org/mantid/ticket/10503)

This ticket is blocked by : 
 - [ ] [TRAC10501](http://trac.mantidproject.org/mantid/ticket/10501)

This will be the realisation of the design agreed in 10501.

**Comment by raquelalvarezbanos** [comment]
Archived and closed for the same reason as #11343
