### ISSUE TITLE
Generate getter design for WorkspaceGroups

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11343]
This issue was originally [TRAC 10501](http://trac.mantidproject.org/mantid/ticket/10501)

This ticket is blocks :  [TRAC10503](http://trac.mantidproject.org/mantid/ticket/10503)

For workspace groups:

1) Where we have multiperiod data (identified by existing isMultiperiod() method), we ought to have forwarding functionality to get the run_number, nhistograms, blocksize from the group.

Easy enough to do in python. Should this also be a c++ feature?

2) A mechanism for a generic group workspace to extract all the run numbers from a group as a list in python.

This needs to go to the SSC, possibly with a design.

**Comment by raquelalvarezbanos** [comment]
I think the proper answer to this is related to what we discussed with @martyngigg at the Developer workshop 2016 regarding workspace types. A design document for this is pending.
