### ISSUE TITLE
Polynomial for Transmission Correction

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11428]
This issue was originally [TRAC 10586](http://trac.mantidproject.org/mantid/ticket/10586)

Don't do until release 3.4. Ask Owen Arnold for guidance.

Essentially, If no transmission run is provided in the ReflectometryReductionOne workflow algorithms we should:

1) Get a warning about one not being provided. 

2) Create a polynomial correction workspace (similar to the way PolarizationCorrection works) and divide by that.

**Comment by eXeC64** [comment]
@OwenArnold Could you provide some details please about the correct way to determine the number of terms in the polynomial, and which instrument parameters are used for which coefficients?

**Comment by OwenArnold** [comment]
https://github.com/mantidproject/mantid/blob/master/Code/Mantid/scripts/Reflectometry/isis_reflectometry/quick.py#L391:L392

https://github.com/mantidproject/mantid/blob/master/Code/Mantid/scripts/Reflectometry/isis_reflectometry/quick.py#L35:L53
