### ISSUE TITLE
Allow X^n scaling in plots

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11422]
This issue was originally [TRAC 10580](http://trac.mantidproject.org/mantid/ticket/10580)

Add the ability to change the X axis of a plot to x^n scale.

This can be done by implementing a new scale engine.

This forms part of #10564.

**Comment by martyngigg** [comment]
@ElliotAOram As this is now a general ticket I'm going to pass it to Matt as he has a bit more time available to spend on general things

**Comment by matthew-d-jones** [comment]
Following a conversation with Martyn:
- "n" will not be restricted to integer or positive values.
- A warning to "Ensure axis and data ranges are compatible with chosen axis scale" will be displayed in the GUI when the "power" scale type is selected.

It is hoped the warning will prompt users to check the axis or data range if the plot does not look like they expect. For example, it is possible to choose axis scales which diverge at 0, but are valid (and possibly useful) elsewhere.
