### ISSUE TITLE
Dispaly log messages in GUI and allow filtering

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11430]
This issue was originally [TRAC 10588](http://trac.mantidproject.org/mantid/ticket/10588)

For release 3.4 or later.

User request for both GUIs. It would be good to have an option to print out (possibly also filter) all log messages generated by the GUI, and show them in some kind of scrolling pane directly in the GUIs.

**Comment by gemmaguest** [comment]
We should check if this is still required. The old GUI is being retired so this will only apply to the new GUI.

**Comment by gemmaguest** [comment]
Closing because the new GUI now has tooltips showing error messages on a per-row basis which I think is sufficient for now.
