### ISSUE TITLE
Non-workspace output properties are not propogated from algorithms on workspace groups

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#11439]
This issue was originally [TRAC 10597](http://trac.mantidproject.org/mantid/ticket/10597)

If you run an algorithm against a workspace group Mantid will run the algorithm against every workspace in that group, and then provide a group workspace of the output workspaces as the output, essentially mapping the algorithm onto every workspace in the group.

However, non-workspace output properties are left as their default value. These values should be propagated to the outermost execution of the algorithm.

 - - - - 
Keywords: CORE

**Comment by NickDraper** [comment]
archived
