### ISSUE TITLE
System Test for Display Mask Functionality

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#11454]
sans_test
This issue was originally [TRAC 10612](http://trac.mantidproject.org/mantid/ticket/10612)

We recently had a regression in the ISIS SANS "Display Mask" functionality (http://trac.mantidproject.org/mantid/ticket/10607) that could have been avoided with proper test coverage.

In its current form it's not really possible to cover Display Mask with a system test, but we should be able to factor out the non-Instrument View parts and therefore isolate the parts we can test.

**Comment by AntonPiccardoSelg** [comment]
We have unit tests for the masking_table presenter. This can be closed
