### ISSUE TITLE
Remove or rename DownloadRemoteFile, which is only used by the RemoteJobManager interface

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#11470]
This issue was originally [TRAC 10628](http://trac.mantidproject.org/mantid/ticket/10628)

This now almost clashes with DowndloadFile

**Comment by FedeMPouzols** [comment]
Note: `DownloadRemoteFile` has a sibling `UploadRemoteFile` algorithm which should be renamed consistently.

**Comment by FedeMPouzols** [comment]
Would `RemoteDownloadFile` and RemoteUploadFile` be better names? This should be simple if we find a good name, and it could be done as a small maintenance 3.8 task.

**Comment by FedeMPouzols** [comment]
Oh well, as suggested above, `DownloadRemoteDataFile` and `UploadRemoteDataFile` would be good alternatives.
