### ISSUE TITLE
Bugfix: Inconsistency of view buttons for multiple workspaces in the VSI

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#11482]
This issue was originally [TRAC 10640](http://trac.mantidproject.org/mantid/ticket/10640)

The view buttons behave inconsistently when loading several workspaces. 
1. Load an MDHisto workspace into the VSI
   You should see only the MULTISLICE and THREESLICE view as selectable
2. Load an MDEvent workspace into the VSI
   You should see that the MULTISLICE, THREESLICE and the SPLATTERPLOT  view are selectable. This is fine.
3. Switch to multislice
   You should see that only the STANDARD and THREESLICE view are available
   ---
   
   Keywords: VATES-vis

**Comment by picatess** [comment]
As of 3.5.1 this issue still remains

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.
