### ISSUE TITLE
Fix bugs in peaksviewer

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11492]
This issue was originally [TRAC 10650](http://trac.mantidproject.org/mantid/ticket/10650)

This ticket is blocked by : 
- [ ] [TRAC6727](http://trac.mantidproject.org/mantid/ticket/6727)
- [X] [TRAC10846](http://trac.mantidproject.org/mantid/ticket/10846)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)

1) Strange issue when zoom to peak with background selected. Seems to hide the background. Have to reselect background colour and then toggle off then on the background again.

2) When zooming to a peak with the rebin option set on, you do not get a rebinned background image of the data until you move the point of focus either into the plane or out. This should happen automatically.

**Comment by Mantid-Matthew** [comment]
Closing as stale.
