### ISSUE TITLE
Visualising Peaks with adaptiveQ = true

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11493]
This issue was originally [TRAC 10651](http://trac.mantidproject.org/mantid/ticket/10651)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)

There are two issues here.

1) With adaptiveQ=True, the peak radius is allowed to vary, and according to the IntegratePeaksMD algorithm, this is calculated to be  |Q| \* base_radius. So what you should see is there is little scaling around |Q|=1, minimal sizes at around |Q|=0 and large sizes at |Q| > 1 . There should be an obvious pattern for this when visualised in the PeaksOverlays of the SliceViewer, but this isn't what we see. Needs investigation.

2) Looks like the Paraview Peaks Overlay sets all radius of peaks to be equal. It doesn't look like it scales the radius peak by peak.

**Comment by NickDraper** [comment]
@OwenArnold is this still current?  if not please archive and close

**Comment by OwenArnold** [comment]
This must only be applying to the VSI, because the slice viewer already does this.

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.
