### ISSUE TITLE
Save/LoadNexusProcessed does not load spectrum numbers correctly

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11520]
This issue was originally [TRAC 10678](http://trac.mantidproject.org/mantid/ticket/10678)

Discovered in http://trac.mantidproject.org/mantid/ticket/10663, a workspace with a vertical axis not in spectrum number will not have the same spectra index to spectra number mapping after a round trip of SaveNexusProcessed and LoadNexusProcessed.

The script in http://trac.mantidproject.org/mantid/ticket/10663 can be used to demonstrate this.

**Comment by NickDraper** [comment]
duplicate
