### ISSUE TITLE
SANS Q resolutions for ISIS (SNS)

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#11530]
This issue was originally [TRAC 10688](http://trac.mantidproject.org/mantid/ticket/10688)

This ticket is blocked by : 
 - [X] [TRAC10689](http://trac.mantidproject.org/mantid/ticket/10689)
 - [x] [TRAC10692](http://trac.mantidproject.org/mantid/ticket/10692)
 - [x] [TRAC10775](http://trac.mantidproject.org/mantid/ticket/10775)
 - [X] [TRAC10987](http://trac.mantidproject.org/mantid/ticket/10987)

 ~~ [TRAC10691](http://trac.mantidproject.org/mantid/ticket/10691)~~

Based on detailed investigation http://trac.mantidproject.org/mantid/ticket/2161. 

The main purpose of this ticket is to enable Q resolution to ISIS SANS. As discussed in http://trac.mantidproject.org/mantid/ticket/2161 a straight copy is not feasible at this point, for example, because of the differences in preferred way ISIS and SNS scientists like to sum contributions for different wavelength into Q.

As a minimum this umbrella ticket will entail:

1) Implementation of new TOFSANSResolutionByPixel algorithm that output the resolution by pixel into a workspace that can a) be reused for more than one sans reduction and b) be plotted for inspection by advanced user 

2) Take output of 1) and allow it as input into Q1D for summed Q resolution

The main purpose of this ticket is to enable ISIS Q resolution but where possible to share code with SNS.

**Comment by picatess** [comment]
These issues were addressed in several tickets, e.g. (here)[https://github.com/mantidproject/mantid/pull/13312]

 TOFSANSResolution is not really used for this functionality and seems to be rather related to the SNS. The TOFSANSResolutionByPixel has now unit tests and documentation
