### ISSUE TITLE
Huge memory usage compiling Kernel with clang.

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#11542]
This issue was originally [TRAC 10700](http://trac.mantidproject.org/mantid/ticket/10700)

I was having a quick play with the `include-what-you-use` tool after merging in the changes from http://trac.mantidproject.org/mantid/ticket/10685 locally. It seems that clang requires about ~12Gb of memory to compile Kernel. It looks as if it is the linking step that ramps up the memory usage.

I don't it's anything to do with those changes but something about the code in Kernel. We should find out why.

It's worth noting that when compiling with gcc the linking step seems to take a disproportionate amount of time to the size of the library.

My suspicion is all of the static objects in Atom.cpp but that's just a guess.

**Comment by DavidFair** [comment]
Just done a quick test with my copy of clang 8 locally, compiling `Kernel` used < 2gb memory so I suspect it was a compiler bug rather than a code-gen issue
