### ISSUE TITLE
Imcompatible 2D and 3D plots

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#11562]
This issue was originally [TRAC 10720](http://trac.mantidproject.org/mantid/ticket/10720)

The default behavior for 1D plots sets the Y axis to counts/bin. However, 3D plots still use counts, causing an inconsistency between both representations.

**Comment by NickDraper** [comment]
3D plots have a whole collection of issues, however they are also not used much

archived for now
