### ISSUE TITLE
Rows added when changing entries in matrix

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#11566]
This issue was originally [TRAC 10724](http://trac.mantidproject.org/mantid/ticket/10724)

To reproduce:

- File -> New -> New Matrix
- Matrix -> Set Dimensions, set for instance two rows and two columns
- If you double click in cell (2,1) or (2,2) to enter a number, a new row is added. This is a bit inconvenient if you want to compute the determinant, as you need to manually remove the new row.

**Comment by NickDraper** [comment]
QTIplot Matrices are not really used in day to day mantid usage, and are just an artefact of the qtiplot code

wontfix
