### ISSUE TITLE
Table Column Statistics index naming

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11578]
This issue was originally [TRAC 10736](http://trac.mantidproject.org/mantid/ticket/10736)

When you run Column Statistics on a table you get two fields named ```iMin``` and ```iMax```, whilst it can be seen this is the index of the max and min values, a name like ```IdxMax``` and ```IdxMin``` would be better.

**Comment by NickDraper** [comment]
wontfix
