### ISSUE TITLE
SaveNexus progress is not uniform

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11574]
This issue was originally [TRAC 10732](http://trac.mantidproject.org/mantid/ticket/10732)

The script below creates quite a large workspace (just shy of 1GB):

```CreateSampleWorkspace(OutputWorkspace='sample', Function='Multiple Peaks', NumBanks='10', Random='1', XUnit='MomentumTransfer', XMin='-20', XMax='20', BinWidth='0.001')```

If I try and save this with SaveNexus or SaveNexusProcessed the progress bar "sticks" at 57% then 71%, whereas if I load the saved file I get a fairly constant change in progress between the algorithm staring and completing.

**Comment by NickDraper** [comment]
Uniform would be very hard in all cases and is not important.

wontfix
