### ISSUE TITLE
Output workspace group created when an algorithm failed

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#11570]
This issue was originally [TRAC 10728](http://trac.mantidproject.org/mantid/ticket/10728)

When an algorithm fails to run on a workspace group, the output workspace group is created. It is empty and you cannot delete it. If you go to "Details" the algorithm is still running, and when you try to close mantid, it does not respond.

I tried the following:

- Load MUSR00015189
- Run ApplyDeadTimeCorr providing an empty table workspace as DeadTimeTable

Also tried:

- Load MUSR00015189
- Run PhaseQuad providing only InputWorkspace and OutputWorkspace

**Comment by NickDraper** [comment]
Neither of the two examples cause a failure in R3.6

**Comment by NickDraper** [comment]
works4me
