### ISSUE TITLE
Powder Diffraction Reduction UI not working on windows 7 64bit

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11586]
This issue was originally [TRAC 10744](http://trac.mantidproject.org/mantid/ticket/10744)

With settings shown in attached, error is given about "PG3_4867_event.nxs" not being found, despite the run number being used being different to 4867.

To replicate, either use same settings as shown in attached, or following instructions shown here: http://www.mantidproject.org/PowderDiffractionReduction, substituting the run no. 4844 with 9829, which is available in the ORNL sample data file.

**Comment by NickDraper** [comment]
This was an issue wirth the filefinder that has since been addressed
