### ISSUE TITLE
SNS powder reduction Problems with python reading in file paths containing python escape characters

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11593]
This issue was originally [TRAC 10751](http://trac.mantidproject.org/mantid/ticket/10751)

Windows specific due to the use of backslash.
\x is used as example below but any character that is considered special if within a string with '\' before it will be a problem.

When mantid is reading in files using python, where the path name contains \x (e.g \xxu\datafiles...) in some circumstances it appears to to read it as a special escape character and throw a 'ValueError: invalid \x escape' error. 

To replicate:

Put data in a folder which at some point in it's file path has an \x. Follow http://www.mantidproject.org/PowderDiffractionReduction  using the data from that folder.

**Comment by NickDraper** [comment]
Verified still happens in R3.6
