### ISSUE TITLE
When switching between algorithms in S(Q,w)

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11599]
This issue was originally [TRAC 10757](http://trac.mantidproject.org/mantid/ticket/10757)

This ticket is blocks :  [TRAC8236](http://trac.mantidproject.org/mantid/ticket/8236)

In S(Q,w), if you plot the output as a spectra graph and have over a certain number of spectra, a dialogue appears to make sure you are certain. However, if you already have a spectra plot up that was created by a different algorithm, even if you click cancel, it will have already overwritten that graph with the newly calculated spectra plot. In this circumstance the dialogue is effectively useless.

To reproduce:

 * Open Indirect > Data Reduction > S(Q, w)
 * Load input file: irs26176_graphite002_red.nxs
 * Q binning: 0.6, 0.1, 1.8
 * Energy binning: -0.5, 0.05, 0.5
 * Plot output = spectra
 * Run with one Rebin type, leaving the spectra plot window up
 * Run with other Rebin type, click cancel on dialogue and note the plot has changed anyway

**Comment by ElliotAOram** [comment]
This will be resolved by #17023
