### ISSUE TITLE
Project save button is still disabled after deleting a workspace

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11605]
This issue was originally [TRAC 10763](http://trac.mantidproject.org/mantid/ticket/10763)

In fact any operation on a workspace does not allow me to save changes to a project without having to use File > Save Project As..., yet moving a plot widow slightly within the work area does.

**Comment by NickDraper** [comment]
This is because we are not marking the workspace as dirty, we should

**Comment by samueljackson92** [comment]
This is a sub issue of #15602
