### ISSUE TITLE
DGS Reduction stuck if reduce with no monitor set

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11602]
This issue was originally [TRAC 10760](http://trac.mantidproject.org/mantid/ticket/10760)

When filling in DGS Reduction form, if you enter nothing into the Monitor Spectrum IDs box, then click reduce, the Reduce button will grey out and not become clickable again until you exist the DGS Reduction form and re-open it.

**Comment by NickDraper** [comment]
One for you to assign on

**Comment by AndreiSavici** [comment]
@lottiegreenwood could you send me an example for inputs? Instead of clicking reduce, please click export. Attach the xml file to this ticket. If the file you want to reduce is not in the repository, please attach that one as well.

**Comment by AndreiSavici** [comment]
@lottiegreenwood I think I see how you produced the error. Did you delete the inputs in the monitor id boxes?

**Comment by NickDraper** [comment]
Actually, I can help with this one.

Just start up the DGS reduction interface and delete the default  monitor 1 and 2, so it is monitors "empty box" and "empty box", then click reduce.  Then the reduce button left left disabled.

**Comment by NickDraper** [comment]
Yes

**Comment by lottiegreenwood** [comment]
@AndreiSavici Yes. I tried to export the example but (I'm assuming because it's just an entirely empty dialogue) it wouldn't save the file.
