### ISSUE TITLE
Print All Plots gives an extra blank page

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11606]
This issue was originally [TRAC 10764](http://trac.mantidproject.org/mantid/ticket/10764)

To reproduce:
- Create/load some workspaces
- Plot multiple spectra plots
- File > Print All Plots
- Select Print To File (PDF)
- Print
- Open the file and notice the first page is blank

Note sure if this is just the PDF output or it happens with actual printers as well.

**Comment by NickDraper** [comment]
Not urgent but should be fairly easy to track down
