### ISSUE TITLE
Exiting Mantid before it has fully loaded on Linux does not exit

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11622]
This issue was originally [TRAC 10780](http://trac.mantidproject.org/mantid/ticket/10780)

If I start Mantid from the terminal and exit before the splash screen has closed I get the following output on the terminal and Mantid never exits (at least as long as I have ever left it without issuing as SIGINT).

```
dan@dannixon-ubuntu ~/r/master-build> ./bin/MantidPlot 
FrameworkManager-[Notice] Welcome to Mantid 3.2.20141212.952
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
MantidUI-[Notice] MantidPlot is shutting down...
```

```ps aux | grep MantidPlot``` shows the process is still hanging around there not doing much.

Giving a SIGINT exits instantly:

```
^Cfish: Job 1, “./bin/MantidPlot ” terminated by signal SIGINT (Quit request from job control (^C))
dan@dannixon-ubuntu ~/r/master-build>
```

Tested on Ubuntu 14.04, haven't haven't tried on Windows or other flavors of Linux.

**Comment by NickDraper** [comment]
wontfix
