### ISSUE TITLE
Bug in loading of GSS files

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#11623]
This issue was originally [TRAC 10781](http://trac.mantidproject.org/mantid/ticket/10781)

When loaded, the attached files have different numbers of bins for each spectrum. Attempting to run these through a binary operation algorithm results in memory corruption, and usually a crash.

```
pol64 = Load("pol64374.gss")
pol59 = Load("pol59543.gss")

for i in range(0,4):
    print "pol59[%d] contains %d bins" % (i, len(pol59.readY(i)))
    print "pol64[%d] contains %d bins" % (i, len(pol64.readY(i)))
```

Yields

```
pol59[0] contains 1021 bins
pol64[0] contains 1021 bins
pol59[1] contains 4646 bins
pol64[1] contains 4646 bins
pol59[2] contains 4570 bins
pol64[2] contains 4564 bins
pol59[3] contains 4439 bins
pol64[3] contains 4428 bins
```

These should all have the same number of bins per spectrum.

**Comment by raquelalvarezbanos** [comment]
Not sure if this is an issue.

**Comment by NickDraper** [comment]
Agreed
