### ISSUE TITLE
A few issues with VSI

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#11625]
This issue was originally [TRAC 10783](http://trac.mantidproject.org/mantid/ticket/10783)
1. Dialogs hide VSI behind MantidPlot.
2. ThreeSlice: slices can rotate (middle button). Reset tool button doesn't cancel the rotation.
3. View settings General page doesn't make it clear colour of which component is being set here. The preset colours in the drop-down boxes are those that are used for edges, text, etc. I don't think that they are useful.
4. View settings General page: Use Parallel Projection check box isn't synced with the tool button on the main view. The same is for the Orientation Axes on the Annotation page.
5. Axis Label Color doesn't stay set to the custom value: after switching view (e.g. from Standard  to MultiSlice and back) it changes back to default.
6. I am not sure if Zoom to Box works correctly. After a few mouse zooms it stops working at all.
   ---
   
   Keywords: VSI

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.
