### ISSUE TITLE
Direct convert to Energy interface Documentation out of date

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11637]
This issue was originally [TRAC 10795](http://trac.mantidproject.org/mantid/ticket/10795)

In http://www.mantidproject.org/Direct:ConvertToEnergy the first two documentation examples no longer work, probably because default files they rely on have been removed from the installation package. Update this.

**Comment by NickDraper** [comment]
wiki page deleted as the UI is no longer in Mantid
