### ISSUE TITLE
Send a screenshot automatically with Help->Report A Bug

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#11660]
This issue was originally [TRAC 10818](http://trac.mantidproject.org/mantid/ticket/10818)

Chrome has this quite nice feature where you get the option to send a screenshot along with the bug report you are submitting.

It seems like this would be a nice way to automatically get extra detail from user-submitted bug reports.

**Comment by NickDraper** [comment]
Bug reporting has moved to the forum, this would then be much harder.

wontfix

**Comment by NickDraper** [comment]
closed by mistake
