### ISSUE TITLE
Improve efficiency, code quality and usability of MDNormDirectSC

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#11672]
This issue was originally [TRAC 10830](http://trac.mantidproject.org/mantid/ticket/10830)

This ticket is blocked by : 
- [X] [TRAC10829](http://trac.mantidproject.org/mantid/ticket/10829)

This is mainly thought which can be spread into separate tickets or dealt all together

1) Why to calculate detector positions in the algorithm when convertToMD have just calculated them using PreprocessDetectorsToMd and placed them into separate workspace for further usage? It is expensive operation. 

2) Enable OMP in the algorithm (after logical bugs are fixed)

3) in 90% of cases one wants to obtain normalized workspace of the size of the source workspace. Why to combine MDNormDirectSC with rebin and allow it to work on part of the workspace? If this feature is important, at least the algorithm with empty dimension parameters should pick up binning ranges from source workspace.  

4) Create meaningful unit test for the algorithm

**Comment by AndreiSavici** [comment]
1. We don't know if the geometry is constant between runs
 2. Done
 3. Implemented in MDNorm
 4. Done
