### ISSUE TITLE
tcmalloc issues with performance tests

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11702]
This issue was originally [TRAC 10860](http://trac.mantidproject.org/mantid/ticket/10860)

Changes merged in https://github.com/mantidproject/mantid/commit/b04d8438bd8a74c88c5595938de317af7da74107 caused a massive slow down for the performance tests. See http://builds.mantidproject.org/job/performance_tests_master/Master_branch_performance_tests/ FileFinderTests 

Can probably be fixed by setting LD_PRELOAD to load libtcmalloc prior to running the performance tests.

 - - - - 
Keywords: Maintenance

**Comment by martyngigg** [comment]
We appear to have lost the history before this point. I'm not sure running with tcmalloc will do much for most of the tests so I'm going to close this one as wontfix
