### ISSUE TITLE
Allow mantid C++ widgets to be used in Python interfaces

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#11716]
This issue was originally [TRAC 10877](http://trac.mantidproject.org/mantid/ticket/10877)

http://trac.mantidproject.org/mantid/ticket/8915 defined a set of guidelines to use when creating user interfaces. While it is easier to create interfaces from Python, we cannot reuse the same set of widgets as in C++ making code duplication much more likely.

It should be possible to create wrappers for the widgets using sip.

**Comment by NickDraper** [comment]
Is this something we could teach a student to do?

**Comment by martyngigg** [comment]
I think this is something we should teach everyone to do

**Comment by NickDraper** [comment]
@picatess A topic for a mantid review!
