### ISSUE TITLE
QuickNXS: Optimise out getIxyt

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#11745]
This issue was originally [TRAC 10906](http://trac.mantidproject.org/mantid/ticket/10906)

This ticket concerns work relating to this repository: ​https://github.com/aglavic/quicknxs

getIxyt is slow and mostly unnecessary. It could be refactored out to improve the reduction time.

**Comment by raquelalvarezbanos** [comment]
Agreed to archive and close this.
