### ISSUE TITLE
EnginXFitPeaks expected Peak analysis problem

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11746]
This issue was originally [TRAC 10907](http://trac.mantidproject.org/mantid/ticket/10907)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

When entering a list of expectedPeaks into FitPeaks, if one expected peak is not there, the algorithm will stop and not produce any results. If just one peak is out of range of the data then this should be stated but otherwise ignored. If all expectedPeaks are not there then the algorithm should fail gracefully.

This affects EnginXCalibrate and CalibrateFull which both utilise FitPeaks.

**Comment by FedeMPouzols** [comment]
It looks like this is the behavior that we want: if errors such as 'some peaks were not found by FindPeaks' happen, the calibration algorithms should continue as far as possible. The output files generated will have a suffix like '_with_errrors` appended, to give a hint.

When used from the GUI, a pop-up should warn the user, before the "peaks diagnostics" visualization, but it should still be possible to go on and then accept the diagnostics step and save the files.
