### ISSUE TITLE
Redesign the PeaksViewer to draw multiple shape types

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11744]
This issue was originally [TRAC 10905](http://trac.mantidproject.org/mantid/ticket/10905)

This ticket is blocked by : 
 - [X] [TRAC10904](http://trac.mantidproject.org/mantid/ticket/10904)

Now that we are able to integrate peaks and remember their integrated shapes, we should be able to draw them correctly too. This is a follow on from 10904.

See the design document notes attached.

**Comment by OwenArnold** [comment]
@picatess. This is the feature we want for the SliceViewer and then VSI. Pascal mentioned this again recently as determining peak shape will be important for an upcoming experiment.

**Comment by picatess** [comment]
# Redesign of the PeaksViewer to draw multiple shape types within a single Peaks Workspace

## Current implementation

The *PeakOverlayViewFactorySelector* in *SliceViewer::setPeaksWorkspace* registers several factories for overlays such as *PeakOverlayMultiSphereFactory* and *PeakOverlayMultiCrossFactory*.

Then a new *ConcretePeaksPresenter* is added to the *CompositePeaksPresenter* for each peaksworkspace. The "correct" *PeakOverlayXXXXFactory* is selected, based on a figure-of-merit approach. This *PeakOverlayViewFactory* is stored in the *ConcretePeaksPresenter* and queried in *ConcretePeaksPresenter::produceViews* where *PeakOverlayViewFactory::createView* is called. 

Through this mechanism the Presenter has a handle to a set of *PeakOverlayView* ( this can be a *PeakOverlayMultiCross* or a *PeakOverlayMultiSphere* object). An important note here is that teh *PeakOverlayView* has access to the data strucutre *PhysicalSphericalPeak* or *PhysicalCrossPeak*).

The *PeakOverlayInteractive::doPaintPeaks* is called whenver the QWidget gets a *PeakOverlayInteractive::paintEvent*.

## The issue with the current implemenation

The current implementation only creates spheres and crosses as peak markers. Users are asking for additonal representations, such as elliptical and eventually aribtrary shapes which become available through the [*integratePeaksHybrid*](http://docs.mantidproject.org/nightly/algorithms/IntegratePeaksHybrid-v1.html)algorithm

In addition the representation of a workspace is currently homogenous. Users want to be able to have a mixed peak-type represenation of a workspace.


## Changes required to allow for mixed peak representations with arbitrary peak shapes

Owen has provided a sketch for a solution:

>PeakRepresentation # This is not a QWidget, but may need to be a QObject?
+ draw(QPainter&)
|
PeakRepresentationSpherical
	| PeakRepresentationEllipticl
		| PeakRepresentationCross

>PeakViewFactory (concrete type, no base)
+ createView(const Peak&) : PeakView # calls makeView with shape
- makeView(const PeakShapeSpherical&) : PeakRepresentationSpherical
- makeView(const PeakShapeEliptical&) : PeakRepresentationElliptical
- makeView(const PeakShapeNone&) : PeakRepresentationCross

>PeakView (concrete type) : public QWidget
- vector<PeakRepresentation*>
PeakView(vector<PeakRepresentation>
+ paint(QPaintEvent*) # overload


>Peak

>PeakViewFactory - Refactored from PeakOverlayMulti{X}Factory

>PeakRepresentation is essentially the Physical{X}Peaks rolled into a public inherited hierarchy with an additional draw method taking a QPainter& 

>PeakView is essentially PeakOverlayMulti{X}, inside the paint method, we now call PeakRepresentation::draw(QPainter). Each PeakView instance 
has a unique m_foreground color and m_background color that are applied to all drawn peaks.
