### ISSUE TITLE
BigTableData Design.

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11754]
This issue was originally [TRAC 10915](http://trac.mantidproject.org/mantid/ticket/10915)

BigTableData is a runtime accident waiting to happen. We think it would be better to have a formal declared type for this complex and critical data structure.

Create a new design document (markdown) and put it in the existing Documents/Design/quick_nxs directory of the documents repository.

* Outline why this work is important
* Outline what the existing BigTableData does and stores. 
* Detail what the new type would be called, what it's structure is, and what module it would live in
* Think about testability of the new structure
* Think about how the BigTableData replacement would be eased in to the codebase
* Share the design with Owen 
* Share the design with Peter and Jean

**Comment by raquelalvarezbanos** [comment]
Archived for the same reason as #10847
