### ISSUE TITLE
Generalisation of scaling factors

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#11755]
This issue was originally [TRAC 10916](http://trac.mantidproject.org/mantid/ticket/10916)

Break this up into separate tickets if you want.

QuickNXS changes

1. Mock-up in balsamiq changes to the ui to allow 3 options for scaling factor applicaition
1. Figure out how we could save the results of the ISIS Stitch1D scaling factor to the existing file format, so that it could be reload and applied.

**Comment by raquelalvarezbanos** [comment]
Archived, same reason as #11754
