### ISSUE TITLE
Selecting files in catalog search with large numbers of data files is incredibly slow

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11764]
This issue was originally [TRAC 10925](http://trac.mantidproject.org/mantid/ticket/10925)

This is not usually a problem as most instruments have sensible numbers of data files for their investigations, however the following steps produce a list of data files (>7000) at which point checking the box next to a filename causes the UI to hang for a significant amount of time.

- Login to ISIS archive
- Search for all TFXA investigations
- Select the "CAL_TFXA_24/09/1987" investigation
- Select a range of data files form various points on the list

**Comment by NickDraper** [comment]
There are other mechanisms for download lots of files for use in these kinds of situations.

Wontfix
