### ISSUE TITLE
Bank interpretation on EnginX Algorithms

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#11808]
This issue was originally [TRAC 10969](http://trac.mantidproject.org/mantid/ticket/10969)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

Currently in the EnginX Focus/Calibrate/CalibrateAll you are only able to select bank 1 or 2. It would be better if north/south could also be used as references, and if selected arrays of pixels used (eg 1-500 instead of automatically either 0-12k/12k-24k)

**Comment by FedeMPouzols** [comment]
There should be support for Bank='North', Bank='South', and also another option to support multiple ranges of pixels/detectors, like: DetectorIndices='10-20, 50-100'.
