### ISSUE TITLE
Extract ROI into a new workspace

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#11824]
This issue was originally [TRAC 10985](http://trac.mantidproject.org/mantid/ticket/10985)

SANS would like to define an ROI, or a set of ROI, then extract those selected pixels into a new workspace.

**Comment by NickDraper** [comment]
This is possible, but some of the labels are unclear so it is not so easy to spot

![image](https://cloud.githubusercontent.com/assets/1017173/9224115/eee1b974-40f7-11e5-8f90-7a8869c8178b.png)
Under the Save button in Group mode is "Extract Detectors to workspace"

Which produces this 
![image](https://cloud.githubusercontent.com/assets/1017173/9224142/1bdf2eac-40f8-11e5-8fc0-d85a7eafd1c4.png)

**Comment by NickDraper** [comment]
I propose to change the Mask/Group option list to Mask/ROI/Group and update the operations underneath accordingly.

**Comment by NickDraper** [comment]
something a bit like this
![image](https://cloud.githubusercontent.com/assets/1017173/9224297/31400036-40f9-11e5-8879-cd7881189a95.png)
