### ISSUE TITLE
Send crash reports

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#11828]
This issue was originally [TRAC 10989](http://trac.mantidproject.org/mantid/ticket/10989)

When mantid crashes, it should give the user an option to send it to the developers. On linux the framework is called "abrt".

**Comment by NickDraper** [comment]
Please take a look into the options for windows, linux and Mac

**Comment by FedeMPouzols** [comment]
This is very closely related to #13036.
