### ISSUE TITLE
allow official build on OS X 10.9+

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#11847]
This issue was originally [TRAC 11008](http://trac.mantidproject.org/mantid/ticket/11008)

Currently we use whether the OS X version is `<10.9 or >`= 10.9 to determine whether we are building with intel or clang. Can we refine this so that someone can perform the official os x build on 10.9+ ?

issue raised in https://github.com/mantidproject/mantid/pull/162

**Comment by quantumsteve** [comment]
close because we no longer support building Mantid with the intel compiler and libstdc++.

**Comment by AndreiSavici** [comment]
There might be still some INTEL preprocessor directives left
