### ISSUE TITLE
Update PhaseQuad algorithm according to input from CalibrateDetectors

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#11869]
This issue was originally [TRAC 11030](http://trac.mantidproject.org/mantid/ticket/11030)

This ticket is blocked by : 
 - [x] [TRAC11029](http://trac.mantidproject.org/mantid/ticket/11029)

Update PhaseQuad algorithm's input dialog according to output from CalMuonDetectorPhases. CalMuonDetectorPhases will create the detector phases needed as input to PhaseQuad.

**Comment by raquelalvarezbanos** [comment]
To test: run the following script:

```
Load(Filename='EMU00006473.nxs', OutputWorkspace='EMU00006473', SpectrumMin=1, SpectrumMax=4)
CalMuonDetectorPhases(InputWorkspace='EMU00006473', FirstGoodData=0.5, LastGoodData=3.5, DetectorTable='tab2', DataFitted='fit2')
PhaseQuad(InputWorkspace='EMU00006473', PhaseTable='tab2', OutputWorkspace='out2')
```

`CalMuonDetectorPhases()` creates a table workspace, `tab2`, that can then be used as an input to `PhaseQuad()`.

**Comment by tom-perkins** [comment]
Script ran ok. tab2 was created by CalMuonDetectorPhases, and PhaseQuad's input dialog automatically picked this up as input when run manually (displayed it in a drop-down list).
Closing as fixed.
