### ISSUE TITLE
Prepare for Qt5 by removing Qt3 support code in MantidPlot

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#11891]
This issue was originally [TRAC 11052](http://trac.mantidproject.org/mantid/ticket/11052)

So that we are not on the back foot we need to ensure that Mantid, without Vates and ParaView, will compile with Qt5. This requires removing some of the Qt3 support code that is still being used in MantidPlot.

I don't anticipate this being a simple task to ensure that the functionality still works

The issue is divided into these parts:

- [x] #15314 Table Widget
- [X] #15315 Project View
- [x] #15475 ImportASCIIDialog
- [x] #15316 muParserScript

- - - - 
Keywords: Maintenance,Core

**Comment by martyngigg** [comment]
@mantid-roman I'm afraid you got volunteered for this one for maintenance: https://github.com/mantidproject/documents/blob/master/Project-Management/TechnicalSteeringCommittee/reports/MaintenanceTasks.md

**Comment by martyngigg** [comment]
It might be a good idea to first have a look at how much there is to do. If it is highly involved then we can find some others to help

**Comment by mantid-roman** [comment]
QtiPlot Table is based on Q3Table. There was an idea to replace Table with MantidTable. Maybe it's a good time to do it now.

**Comment by martyngigg** [comment]
What's a `MantidTable`?

**Comment by mantid-roman** [comment]
Here I mean a table widget that displays and edits a table workspace.

**Comment by mantid-roman** [comment]
The project view is also Q3.

**Comment by martyngigg** [comment]
`MantidTable` seems like a good way to go if we already have it.

**Comment by martyngigg** [comment]
I seem to remember Harry saying that it might be easier just to redesign/rewrite the project stuff rather than trying to unpick the Qt3 stuff. What do you think? It could be done with MVP and put in the widgets library.

**Comment by mantid-roman** [comment]
I agree completely.

**Comment by mantid-roman** [comment]
muParserScript has some Q3. I wonder if we need it at all.

**Comment by martyngigg** [comment]
We should check with others but I would be in favour of no longer supporting that

**Comment by martyngigg** [comment]
@NickDraper @mantidproject/tech-steering: See above. Can we drop `muParser` support?

**Comment by NickDraper** [comment]
We only need muparser for the aspects we have used it for in Mantid, not the historic uses from qtiplot

**Comment by mantid-roman** [comment]
This issue is finished. Should I close it?

**Comment by martyngigg** [comment]
That's fine with me.
