### ISSUE TITLE
VSI: crash when clicking Scale/Cut

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#11947]
This issue was originally [TRAC 11108](http://trac.mantidproject.org/mantid/ticket/11108)

1. Open a workspace in VSI.
2. Select the 'builtin' node in the filter tree.
3. Click Scale or Cut button.
4. Crash.

The same with the mode changing tool buttons.

**Comment by NickDraper** [comment]
Anton, I'd check first if this still happens
