### ISSUE TITLE
Investigate why OSIRIS I(Q, t) fit test fails on OSX

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#11989]
This issue was originally [TRAC 11150](http://trac.mantidproject.org/mantid/ticket/11150)

This test fails as the Tau spectrum has an artefact in it that is far enough out of the comparison tolerance to fail the test.

**Comment by ElliotAOram** [comment]
This no longer appears to be the case as no OSX tests are failing

**Comment by DanNixon** [comment]
It doesn't fail because it's skipped on OSX: https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py#L1017

**Comment by ElliotAOram** [comment]
Ah okay, sorry didn't realise this. Thanks
