### ISSUE TITLE
RefAxis wastes memory by calling NumericAxis constructor.

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#12033]
This issue was originally [TRAC 11194](http://trac.mantidproject.org/mantid/ticket/11194)

RefAxis inherits NumericAxis and on construction calls the NumericAxis constructor. The NumericAxis constructor then initializes  std::vector`<double>`m_values of length l. This vector is unused by RefAxis, whose values are stored in the parent workspace. 

The larger issue is cases like in ticket http://trac.mantidproject.org/mantid/ticket/1179 ( http://trac.mantidproject.org/mantid/ticket/11179 ) where a member function inherited from NumericAxis used m_values instead of the parent workspace. In this particular case, the two were of different length.

**Comment by SimonHeybrock** [comment]
If I didn't misunderstand something, these small changes should fix the problem. All tests pass, but I did not test more than that.

**Comment by quantumsteve** [comment]
@SimonHeybrock I think this is a reasonable fix to address the unused `std::vector<double>` initialized by NumericAxes. 

I'll make another comment about a small style issue, but other than that think it's ready to be submitted as a pull request.
