### ISSUE TITLE
Implement a mechanism for profile fitting

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12063]
This issue was originally [TRAC 11224](http://trac.mantidproject.org/mantid/ticket/11224)

This is a requirement for macro-molecular work, e.g. MANDI at SNS.

Contact Leighton Coates at SNS for more detailed requirements.

---

Keywords: SSC 2015 sns, fitting

**Comment by Anders-Markvardsen** [comment]
We have contact with Leighton and Federico will follow this up in upcoming ssc meetings

**Comment by FedeMPouzols** [comment]
Current status: much work and improvements are required in the single crystal diffraction area before implementing profile fitting. This is not feasible short-middle term. There are related issues in SCDCalibratePanels and the functionality included in the SCD event data reduction interface. The expertise and development skills required are scarce.

I understand that this is a significant effort that would need serious commitment of resources from (possibly several) facilities. I'm leaving it unassigned and without estimated milestone to reflect the lack of a concrete and feasible plan.

@MichaelWedel : this ticket/issue had been created from a previous SSC.

**Comment by FedeMPouzols** [comment]
@raquelalvarezbanos
