### ISSUE TITLE
Improve usability of fitting e.g. during calibration

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12062]
This issue was originally [TRAC 11223](http://trac.mantidproject.org/mantid/ticket/11223)

Usability of fitting e.g. during calibration:
- Single peak - Initial guesses based on instrument in non-TOF units (all)
- Improved algorithms for different dspacing range, e.g. different shapes for different banks
- Look at things done on e.g. SXD
- Defined outputs based on instrument/technique
- Batch fitting with functions, consider interface to GSAS (Pascal)

Ask Pascal Manuel for more information.

---

Keywords: SSC 2015 all, fitting

**Comment by FedeMPouzols** [comment]
Small note on the comments about units: sometimes that issue is that Fullprof uses diferent units than GSAS. The comment from Pascal here is that Fit works well already, but the details about the units need polishing.

**Comment by FedeMPouzols** [comment]
I think that this would be probably handled much better by @raquelalvarezbanos and @samueljackson92, as the main contact for this issue was Pascal. The roadmap includes this / points with a lot of overlap with this.
