### ISSUE TITLE
Peak integration for non-spherical shapes

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12066]
This issue was originally [TRAC 11227](http://trac.mantidproject.org/mantid/ticket/11227)

This was a request from most of the group but I think Pascal should be able to give us more detail on specific requirements.

This is to cover shoe box / line etc techniques to handle more than just spheres or ellipses.

---

Keywords: SSC 2015 all SX

**Comment by AntonPiccardoSelg** [comment]
Generalized peak integraion has been implemented. See [here](http://docs.mantidproject.org/nightly/algorithms/IntegratePeaksHybrid-v1.html)

We still need to be able to visualize them though.

**Comment by AntonPiccardoSelg** [comment]
Visualization is provided for non-shape, spherical and elliptical peaks. We don't support arbitrary shaped peaks. 

@samueljackson92 I am assigning this to you, since Pascal is being mentioned here. Please feel free to reassign

**Comment by martyngigg** [comment]
Arbitrary shapes have not yet been requested. Closing as the main set as been done.
