### ISSUE TITLE
Documentation/Consistency for input parameters e.g. workspace index vs spectrum number

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12069]
This issue was originally [TRAC 11230](http://trac.mantidproject.org/mantid/ticket/11230)

Algorithm inputs and documentation can sometimes use the terms workspace index and spectrum number interchangeable when they shouldn't.

Contact Ron Smith at ISIS to see if he has any concrete examples.

 - - - - 
Keywords: SSC 2015 isis frameOther

**Comment by NickDraper** [comment]
Searched Documentation with regexes
```
workspace\s*index.*spectrum\s*number
and
spectrum\s*number.*workspace\s*index
```
Found the following files that include both terms
- [ ] CalculateGammaBackground-v1.html
- [ ] EventWorkspace.html
- [ ] GetDetOffsetsMultiPeaks-v1.html
- [ ] GroupDetectors-v2.html
- [ ] IEventWorkspace.html
- [ ] Integration-v1.html
- [ ] MatrixWorkspace.html
- [ ] VesuvioResolution-v1.html

**Comment by NickDraper** [comment]
Issue corrected in 
- GetDetOffsetsMultiPeaks-v1.html
- GroupDetectors-v2.html
- VesuvioResolution-v1.html
