### ISSUE TITLE
Non-rectangular detector geometry for calibration

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12067]
This issue was originally [TRAC 11228](http://trac.mantidproject.org/mantid/ticket/11228)

Most of the calibration algorithms are geared towards rectangular detectors and need to be generalised to other detector types.

Contact Leighton Coates at SNS for more information

 - - - - 
Keywords: SSC 2015 sns calibration

**Comment by NickDraper** [comment]
No reply from Leighton despite attempts to contact.  Recent calibration changes have probably covered this and docus have been improved in R3.7
