### ISSUE TITLE
Improve ability to work in detector coordinates

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12065]
This issue was originally [TRAC 11226](http://trac.mantidproject.org/mantid/ticket/11226)

Mantid does not currently offer many mechanisms to work with detector coordinates.

Both Pascal Manuel & Leighton Coates expressed interest in this area although it is not yet clear what their requirements are.

Gather requirements & allow a 2 week timebox for implementation

 - - - - 
Keywords: SSC 2015 all SX

**Comment by NickDraper** [comment]
Duplicate of #15546
