### ISSUE TITLE
Integration with DFT code

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12076]
This issue was originally [TRAC 11237](http://trac.mantidproject.org/mantid/ticket/11237)

Integration of DFT
- CASTEP
- Gaussian
- "Quantum" 

Speak to James Lord for more details

---

Keywords: SSC, 2015, RAL, muonOther

**Comment by NickDraper** [comment]
Gaussian has been highlighted as perhaps the first to focus on

**Comment by tom-perkins** [comment]
Requirement for muons:
Import the results of muon DFT calculations into Mantid. The calculations give information on muon stopping sites.

Within Mantid, use these results to generate simulated data sets with James Lord's Quantum and/or the dipolar field calculations. Ask scientists for further information.
The time estimate is around 3 months. Target: release 3.9.

**Comment by tom-perkins** [comment]
DFT calculations give several candidate muon sites.
For each, we want to be able to calculate the local fields at that site - and visualise them all at once.

This will be done using the [Muesr](https://github.com/bonfus/muesr) package. 

Crystal structure and magnetic structure should go in the workspace. We have [`LoadCIF`](http://docs.mantidproject.org/nightly/algorithms/LoadCIF-v1.html) for the crystal structure and Muesr has the ability to load MCIF files. Should also have the capability to specify the magnetic structure manually, as is done in Muesr.

Visualisation: in Muesr at present this is done using Fullprof Studio or XCrysDen, find out if it is possible to do this in Mantid e.g. by creating an MDWorkspace with the fields and using the VSI.
What we want to visualise is a unit cell (or supercell) with a vector field.

**Comment by tom-perkins** [comment]
![sequence_diagram](https://cloud.githubusercontent.com/assets/15363125/20058944/9a4f960c-a4eb-11e6-80cc-3343c3188dcd.png)

**Comment by tom-perkins** [comment]
This is what has been implemented so far:
[ISIS-PARMA-WP10-Coimbra.pdf](https://github.com/mantidproject/mantid/files/575637/ISIS-PARMA-WP10-Coimbra.pdf)

**Comment by tom-perkins** [comment]
Usage videos for the MuESR package are too big to upload here, but are stored at ``\\olympic\babylon5\Public\TomPerkins\MuESR_usage``

**Comment by Anders-Markvardsen** [comment]
A first step towards integrating with DFT has been completed, this includes:

* James quantum code now in the scriptrepository
* SimulatedDensityOfStates algorithm which can load castep outputs and calculate Raman and IR spectra
* Abins algorithm which can load CASTEP/CRYSTAL outputs (like soon more outputs) and calculate neutron S(Q, omega)

More will be done it this area, including making the above described MuESR code available to Mantid users, which will be dealt with in separate issues
