### ISSUE TITLE
Enhancment for Vesuvio

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12074]
This issue was originally [TRAC 11235](http://trac.mantidproject.org/mantid/ticket/11235)

This ticket is blocked by : 
 - [X] [TRAC11205](http://trac.mantidproject.org/mantid/ticket/11205)

For startup in June.

Martyn please add the blocking subtickets

 - - - - 
Keywords: SSC,2015, RAL, indirectShort

**Comment by martyngigg** [comment]
The scripts are completed and in the [ https://github.com/mantidproject/scripts/tree/master/development/inelastic](scripts) repository. There are just minor issues to work with Matthew
