### ISSUE TITLE
Horace like commands in Python

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12070]
This issue was originally [TRAC 11231](http://trac.mantidproject.org/mantid/ticket/11231)

This ticket is blocked by : 
- [X] [TRAC10693](http://trac.mantidproject.org/mantid/ticket/10693)
- [X] [TRAC11304](http://trac.mantidproject.org/mantid/ticket/11304)
- [X] [TRAC11393](http://trac.mantidproject.org/mantid/ticket/11393)
- [X] #13508
- [x] #12689 was [TRAC 11851](http://trac.mantidproject.org/mantid/ticket/11851)
- [X] #12690 was [TRAC11852](http://trac.mantidproject.org/mantid/ticket/11852)
- [ ]  #12691 was [TRAC11853](http://trac.mantidproject.org/mantid/ticket/11853)
- [ ] #12692 was [TRAC11854](http://trac.mantidproject.org/mantid/ticket/11854)
- [ ] #12693 was [TRAC 11855](http://trac.mantidproject.org/mantid/ticket/11855).
- [X] #12694 was [TRAC11856](http://trac.mantidproject.org/mantid/ticket/11856)
- [X] #13507

Copied from a list by Toby Perring, with a few comments, roughly in priority order.

*\* means not in the original survey

```

**           gen_sqw
             cut_sqw
                - combine_sqw

**           compact (May have not meaning in Mantid - need to check)

             mask (check what masking in Horace means)
             mask_pixels
             mask_points
             mask_runs

**           noisify

**           rebin_sqw - this is really just cut all over again (use cut as sub-alg)
**           section - likewise

**           replicate

**           smooth
**           symmetrise


             func_eval (this and next one may be best tackled by Martyn or Roman)
             sqw_eval (like quantification but without resolution conv)

**           fake_sqw (create an MD workspace with fake data, most common is using the rotation angle as counts)

             fit
             fit_sqw

             refine_crystal
**           change_crystal

```

---

Keywords: SSC, 2015, All, vates-cli

**Comment by matthew-d-jones** [comment]
I've updated this issue with git issue numbers and ticked some things which have been done.

**Comment by AndreiSavici** [comment]
`CutMD` or `MDNorm` are doing this
