### ISSUE TITLE
Space Group awareness

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12073]
This issue was originally [TRAC 11234](http://trac.mantidproject.org/mantid/ticket/11234)

Mantid now has a concept of space groups, implemented by Michael Wedel from PSI,  but we need to check with Leighton Coates and Pascal Manuel whether what we have is enough.

 - - - - 
Keywords: SSC 2015 all SX

**Comment by OwenArnold** [comment]
Michael knows way more about this than anyone else

**Comment by MichaelWedel** [comment]
After the SSC this year it seems that the degree of space group awareness is enough for the time being, closing the issue.
