### ISSUE TITLE
Live data roll out acrosss more SNS instruments

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12071]
This issue was originally [TRAC 11232](http://trac.mantidproject.org/mantid/ticket/11232)

Kate Page was keen to see live data rolled out across more instruments at the SNS.

---

Keywords: SSC 2015 sns DiffOther

**Comment by granrothge** [comment]
This should Move to release 3.8 because the next bunch to get live data won't have their hardware upgraded until this summer.
