### ISSUE TITLE
Multiple scattering correction

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12075]
This issue was originally [TRAC 11236](http://trac.mantidproject.org/mantid/ticket/11236)

Multiple scattering corrections
- Different from analytical and Gudrun formalisms.
- Basically what DISCUS/MSCATT used to do
- Monte Carlo based (preferably not McStas based)

Talk to Spencer Howells/Toby Perring/Doug Abernathy for more details

---

Keywords: SSC, 2015, All

**Comment by martyngigg** [comment]
Removed High Priority label as its meaning doesn't fit this.
