### ISSUE TITLE
Detector Dark Current correction

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12087]
This issue was originally [TRAC 11248](http://trac.mantidproject.org/mantid/ticket/11248)

(source on detector background)

Top priority for SNS, only middling priority for ISIS.

Develop a common solution that can be used at either location.

Contacts:
- William Heller
- Richard Heenan
- Andrew Jackson (ESS)
  ---
  
  Keywords: SSC, 2015,All, sansCorr

**Comment by RichardHeenan** [comment]
At ISIS there is a py routine to do this:

https://docs.mantidproject.org/nightly/algorithms/SANSDarkRunBackgroundCorrection-v1.html

but in tests for SANS2d and LARMOR the corrections were found to be negligible, so it was not incorporated into the main gui.

Note that for tof there are two main options 
(a) flat "cosmic" background, collected with shutter closed and/or the neutron source off, which may be time averaged over each detector pixel.
(b) tof dependent background from the pulsed accelerator source (or other beam lines), which is subtracted in tof, after allowing for the relative lengths of the runs, collected with either shutter closed or an adsorbing beam blocker at the sample, and the neutron source running.

Users might for example opt to treat beam monitors by (b) with shutter closed , but main detector by either (a) and/or (b)  depending on the magnitudes of the different background components!

HIFR and EQSANS have similar versions
https://docs.mantidproject.org/nightly/algorithms/HFIRDarkCurrentSubtraction-v1.html
https://docs.mantidproject.org/nightly/algorithms/EQSANSDarkCurrentSubtraction-v2.html

**Comment by smk78** [comment]
Low priority given what the tests showed. Can always be resurrected if something changes.
