### ISSUE TITLE
Include fitting with resolution within MD data sets (inc TobyFit)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12084]
This issue was originally [TRAC 11245](http://trac.mantidproject.org/mantid/ticket/11245)

This is an umbrella ticket for VATES quantification

---

Keywords: SSC, 2015, All, VATES-quant

**Comment by martyngigg** [comment]
This is going to comprise of many pieces of work so this issue will simply consist of many sub-issues:

* #11889 - Comparison of Tobyfit/Mantid for simulations

**Comment by martyngigg** [comment]
The PACE project has now superseeded this and the quantification code is no longer in Mantid.
