### ISSUE TITLE
Connection to modeling software (Direct)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12086]
This issue was originally [TRAC 11247](http://trac.mantidproject.org/mantid/ticket/11247)

Improved connection to McStas. McVine

To allow Simulations to be started from Mantid, result imported, resolution convolution, comparison tools, possible fitting and optimisation

---

Keywords: SSC, 2015,All

**Comment by NickDraper** [comment]
to be partially addressed during geomtery redo

**Comment by Anders-Markvardsen** [comment]
McStas has been enhanced to be able to write simulated data which can subsequently be loaded into Mantid: http://docs.mantidproject.org/nightly/algorithms/LoadMcStas-v1.html

**Comment by Anders-Markvardsen** [comment]
Connection to modelling software has improved: This includes to McStas, SasView, Castep and nMoldyn
