### ISSUE TITLE
Allow unit conversions without an instrument

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12082]
This issue was originally [TRAC 11243](http://trac.mantidproject.org/mantid/ticket/11243)

Integration of 'Detector.dat' type parameter table. (Timmy)
* Could this be used for a coherent approach to applying calibration values.
* Make it easy to change IDF variables 

The underlying wish for this is to be able to inject L1, L2, 2theta and efixed values in to override  Instrument values, either when there are none or hey are considered incorrect.

 - - - - 
Keywords: SSC, 2015, SNS, indirectShort

**Comment by stuartcampbell** [comment]
A prototype has been done and merged (see http://docs.mantidproject.org/nightly/algorithms/ConvertUnitsUsingDetectorTable-v1.html)

A new issue should be raised for problems arising from it.
