### ISSUE TITLE
DAQ and Detector deadtime

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12088]
sans_feature
This issue was originally [TRAC 11249](http://trac.mantidproject.org/mantid/ticket/11249)

(DAQ: delay from readout and ADC conversion. Detector: delay from intrinsic ion pair/photon production)

Don’t know the physics of this. Including can delays from DAQ and detector can distinguished. 

Priority 4 - fairly low

Contacts:
- William Heller
- Richard Heenan
- Andrew Jackson (ESS)
  ---
  
  Keywords: SSC, 2015, sansCorr

**Comment by AntonPiccardoSelg** [comment]
At the user meeting 2017 it was made clear that it is in parts still not clear how to handle this. The priority was considered appropriate

**Comment by gemmaguest** [comment]
Closing as a duplicate of #9937
