### ISSUE TITLE
Enhance Bayesian analysis (Indirect)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12080]
This issue was originally [TRAC 11241](http://trac.mantidproject.org/mantid/ticket/11241)

To Do: 
 - [x] [Add FABADA option to IDR fitting](http://trac.mantidproject.org/mantid/ticket/11561)
 - [x] [Port ResNorm](http://trac.mantidproject.org/mantid/ticket/11703)
 - [x] #12904
 - [x] [Fix FABADA](https://github.com/mantidproject/mantid/issues/13012)
 - [ ] Port quasi fitting
 - [ ] Port stretch exponential fitting

 - - - - 
Keywords: SSC, 2015, All,, indirectMed

**Comment by ElliotAOram** [comment]
Spencer has advised me that this has been completely with various other issues are therefore this umbrella ticket should be closed.
