### ISSUE TITLE
Detector spherical dilation (parallax)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12089]
sans_feature
This issue was originally [TRAC 11250](http://trac.mantidproject.org/mantid/ticket/11250)

(for larger solid area of pixels at wider angles)

Now know where the detectors are within 2 mm (ISIS). Hence this now makes this relevant. SNS not expecting this to have much effect yet but would like to follow discussions

Priority 2 (pretty high)
Contacts:
- William Heller
- Richard Heenan
- Andrew Jackson (ESS)
  ---
  
  Keywords: SSC, 2015, All, sansCorr

**Comment by smk78** [comment]
The SANS Group need to remind themselves what this is about.
