### ISSUE TITLE
Masking from sample

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12094]
sans_feature
This issue was originally [TRAC 11255](http://trac.mantidproject.org/mantid/ticket/11255)

(to exclude pixels from data reduction)

For high-angle detectors, detector pixels can be shadowed by the sample environment or baffles in vac tank.

Priority 3 (middle)

Contacts:
- Richard Heenan
- Andrew Jackson
  ---
  
  Keywords: SSC, 2015, RAL, sansCorr

**Comment by AntonPiccardoSelg** [comment]
At the user meeting 2017 the participants tried to recollect what the scope of this issue should be. It was understood that based on a a specific sample environment a specific mask is applied. It was mentioned that ray tracing might be one way to achieve this.

**Comment by DavidFair** [comment]
I'm going to close this as stale, since we haven't hard about this since.
Feel free to re-open if this becomes required
