### ISSUE TITLE
Sample self-absorbtion (ISIS)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12091]
sans_feature
This issue was originally [TRAC 11252](http://trac.mantidproject.org/mantid/ticket/11252)

(for greater path length through sample at wider angles)

Is available for high angle bank on LOQ only at ISIS. Need to be available for main bank

Priority:2 pretty high

Contact Richard Heenan

---

Keywords: SSC, 2015, RAL, sansCorr

**Comment by RichardHeenan** [comment]
For the normal flat plate SANS samples at ISIS or SNS this is done, see
https://docs.mantidproject.org/nightly/algorithms/SANSWideAngleCorrection-v1.html

sample/path/on  in the ISIS user file will activate it.

(Perhaps however wide angle path corrections for the detector ought to be included at the same time to avoid over correction?)
