### ISSUE TITLE
Detector detection depth (‘gondola effect’)

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12090]
sans_feature
This issue was originally [TRAC 11251](http://trac.mantidproject.org/mantid/ticket/11251)

(for greater path length at wider angles)

First understand the physics of this.

Priority:low, Only affects LOQ (2014-)

Contact: Richard Heenan

---

Keywords: SSC, 2015, RAL, sansCorr

**Comment by smk78** [comment]
The SANS Group need to remind themselves what this was about.
