### ISSUE TITLE
GISans Slicing

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12093]
sans_feature
This issue was originally [TRAC 11254](http://trac.mantidproject.org/mantid/ticket/11254)

Priority 2 pretty high

Contacts: 
- ~~Richard Heenan~~
- Sarah Rogers (ISIS)
- Anderw Jackson (ESS)
- Shuo
- Qian
  ---
  
  Keywords: SSC, 2015, All, sansOther

**Comment by AntonPiccardoSelg** [comment]
At the user meeting 2017 it was noted that Sarah Rogers is the contact person for GISANS at ISIS now. The ticket is still relevant.
