### ISSUE TITLE
Performance: Adding two events files is too slow

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12098]
This issue was originally [TRAC 11259](http://trac.mantidproject.org/mantid/ticket/11259)

Need to get a specific example from Richard Heenan

1. Write performance test
1. Profile
1. Improve
1. Have coffee

Priority 2 (Pretty high)

 - - - - 
Keywords: SSC, 2015, RAL, sansEvents

**Comment by picatess** [comment]
This issue was addressed [here](https://github.com/mantidproject/mantid/pull/662)
