### ISSUE TITLE
TOF flux line lattice (slices & rotations) for superconductivity

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12097]
sans_feature
This issue was originally [TRAC 11258](http://trac.mantidproject.org/mantid/ticket/11258)

Priority 5 (lowest)

Contacts:
- William Heller
- Richard Heenan
- Andrew Jackson (ESS)
  ---
  
  Keywords: SSC, 2015, All, sansOther

**Comment by AntonPiccardoSelg** [comment]
At the user meeting 2017 this was picked up and said to be relevant for Zoom/ESS/ILL but that it is something for later

**Comment by DavidFair** [comment]
I'm going to close this as stale, it was already lowest priority when moving from TRAC before
Feel free to re-open if this becomes a pressing need again
