### ISSUE TITLE
More ways of masking detectors based on defined criteria

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12112]
This issue was originally [TRAC 11273](http://trac.mantidproject.org/mantid/ticket/11273)

We currently have basic mechanisms for automatic masking of detectors based on e.g. thresholds.

There is interest in other automatic masking mechanisms.

Contact Pascal Manuel for more information

After gathering the specific requirements and finding what are existing algs don't do the implementation of this would be great starter tickets for new starters.

---

Keywords: SSC 2015 all DiffOther

**Comment by samueljackson92** [comment]
Pascal is looking for far more complicated masking shapes. Talk to him when the time comes to look at this. He did not indicate that this was especially urgent.
