### ISSUE TITLE
Ability to handle Multiple UBs

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12116]
This issue was originally [TRAC 11277](http://trac.mantidproject.org/mantid/ticket/11277)

A single crystal requirement.

Pascal Manuel at ISIS will be a good contact.

---

Keywords: SSC 2015 all SX

**Comment by samueljackson92** [comment]
Pascal indicated that this should still be a priority and agrees that PWs should have a single UB and when peaks are transferred they should use that UB.

**Comment by martyngigg** [comment]
@rosswhitfield @DannyHindson I think this is still on the SC roadmap? Is it tracked somewhere else or should we keep this on open?

**Comment by DannyHindson** [comment]
> @rosswhitfield @DannyHindson I think this is still on the SC roadmap? Is it tracked somewhere else or should we keep this on open?

Yes WISH still want us to implement this so I'll reopen. I don't see another issue for this
