### ISSUE TITLE
Non-orthogonal axes in Slice Viewer

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12110]
This issue was originally [TRAC 11271](http://trac.mantidproject.org/mantid/ticket/11271)

The slice viewer needs to be able to work with non-orthogonal axes.

This was raised by Pascal from ISIS but of interest to all.

---

Keywords: SSC 2015 all SX VATES

**Comment by lottiegreenwood** [comment]
Trello page, contains more detail about ticket: https://trello.com/b/MdHm5lIj/non-orthogonal-slice-viewer
