### ISSUE TITLE
Convert to MD is slow for some diffraction cases

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12115]
This issue was originally [TRAC 11276](http://trac.mantidproject.org/mantid/ticket/11276)

Leighton Coates has an example where ConvertToMD is extremely slow. This needs profiling to understand why.

---

Keywords: SSC 2015 sns SX

**Comment by martyngigg** [comment]
I have emailed Leighton to ask for an example

**Comment by OwenArnold** [comment]
@martyngigg would be good to get the test case for this. Might be interesting to see if what @igudich has been doing fixes the performance.

**Comment by martyngigg** [comment]
@OwenArnold We had been waiting on an instrument scientist in the US to give us a test case. @peterfpeterson Do you know if there are still issues here? We captured this quite some time ago...

**Comment by martyngigg** [comment]
Closing due to lack of user response.
