### ISSUE TITLE
Improve performance by minimizing repeated reduction operations

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12138]
sans_code
This issue was originally [TRAC 11299](http://trac.mantidproject.org/mantid/ticket/11299)

Improve speed by reducing the number of repeated operations in the reduction process. E.g. if the same CAN run is used then there is no point re-reduce CAN run. PP, suggested a technical solution using something similar to where build server register which files have been touched (like Ninja).

priority 2

contacts 
 Richard Heenan (RH) ISIS
 William Heller (WH) SNS
 Andrew Jackson (AJ) ESS

---

Keywords: SSC,2015,All, sansUI

**Comment by AntonPiccardoSelg** [comment]
This has been solved in the new reduction backend.
