### ISSUE TITLE
Discuss Improving the pipelining to fitting codes e.g. SASVIEW

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12136]
sans_feature
This issue was originally [TRAC 11297](http://trac.mantidproject.org/mantid/ticket/11297)

Possibly by pipelining mantid workspace into sasview. Harmonise sasview and mantid interfaces. Sasview may separate GUI and backend, in which case Mantid can link to a sasview backend. This may open up for enable a tighter feedback loop between analysis and a decision making while running an experiment. Have Mantid interface to sasview.

Ticket here is to open this up for further discussion

Priority 2
Contacts: 
1. Richard Heenan (RH) ISIS
1. William Heller (WH) SNS
1. Andrew Jackson (AJ) ESS

 - - - - 
Keywords: SSC, 2015, All, sansOther

**Comment by Anders-Markvardsen** [comment]
Work on improving the intrastructure between Mantid and Sasview is now being worked on as part of SINE2020 WP10 at ESS and e.g. with input from Andrew Jackson. The process of separating sasview backend and GUI is progressing
