### ISSUE TITLE
REFM instrument definition

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12147]
This issue was originally [TRAC 11308](http://trac.mantidproject.org/mantid/ticket/11308)

Allow better sharing of reflectomtery tools

 - - - - 
Keywords: SSC, 2015, SNS reflOther

**Comment by OwenArnold** [comment]
@raquelalvarezbanos Tim has had a go with this. I'm going to forward the emails on to you. I think he's nearly completed the area detector. Could you have a go at completing the IDF and running the standard reduction. I can help with this too.
