### ISSUE TITLE
Use of meta data to fill in field in GUIs.

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12140]
sans_feature
This issue was originally [TRAC 11301](http://trac.mantidproject.org/mantid/ticket/11301)

Priority 3

Investigate whether values that the GUI needs arae available in metadata within the files, or other stores withinin the facilities, and use as appropriate.  This needs an investigataion phase at each facility before implementation can begin.

 - - - - 
Keywords: SSC,2015, All, sansUI

**Comment by Anders-Markvardsen** [comment]
This has been investigated
