### ISSUE TITLE
Initial Splitting Follow on Fixes

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12159]
This issue was originally [TRAC 11320](http://trac.mantidproject.org/mantid/ticket/11320)

This ticket is blocked by : 
- [X] [TRAC10973](http://trac.mantidproject.org/mantid/ticket/10973)

1) ConvertToMD::performInitialSplitting should not have a hard-coded number of boxes. Although 50 is likely to remain as the default, It worries me that we cannot change this without recompiling and distributing mantid. Can you change this to be a user property which defaults to 50?

2) The initial splitting is Off by default, Nick's opinion is now that it should be ON by default. In the code use true/false rather than 0/1 to set default values. It's just a coincidence that 1 == true and 0 == false in c++, makes for more readable code if you don't mix boolean and integer types.

3) Unit tests should be made to run fast. If you cannot get the time down < 1 second, for this test method, then write it as a system test.

**Comment by AntonPiccardoSelg** [comment]
Should be easy to do and something that @Mantid-Matthew can use to get into VATES

**Comment by Mantid-Matthew** [comment]
closing as stale
