### ISSUE TITLE
Feature: Improve speed of ConvertToMD unit test

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#12156]
This issue was originally [TRAC 11317](http://trac.mantidproject.org/mantid/ticket/11317)

The particular test testInitialSplitting enabled takes 12s in Release mode. It might be possible to reduce this time by setting the number of banks to 1 and to reduce the number of pixels.

---

Keywords: Unit tests

**Comment by DavidFair** [comment]
ConvertToMD unit tests run in < 1 second currently. Closing
