### ISSUE TITLE
Copy windows paths into LoadMD

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12177]
This issue was originally [TRAC 11338](http://trac.mantidproject.org/mantid/ticket/11338)

Load seems to handle windows paths being copied in, but LoadMD can't handle them, and give a user-message that is very hard to understand.

1/2 days work.

 - - - - 
Keywords: VATES-cli

**Comment by tom-perkins** [comment]
Failed to reproduce issue on 3.5.0 (g613f181), Windows 7 64-bit system.
- LoadMD succeeded with MD nxs files
- LoadSQW succeeded with sqw files
- Loads succeeded whether path was typed in, pasted (ctrl-v) or pasted via right-click
- Tried relative and absolute paths
- Tried single and double backslashes in Windows paths
- Tried via GUI and script window

Expected errors were seen in the following situations. In each case the error was expected and the message was understandable.
- Loading a non-MD nexus file with LoadMD (unexpected NXEntry name)
- Loading a non-sqw file with LoadSQW
- Missing 'r' off the front of path with single backslashes in script window (bad path syntax)
- Error when trying to overwrite an existing workspace

Closing, pending re-opening if further information on how to reproduce comes to light.

**Comment by OwenArnold** [comment]
@tom-perkins Agreed. Looks thoroughly tested.
