### ISSUE TITLE
Smooth Button

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12181]
This issue was originally [TRAC 11342](http://trac.mantidproject.org/mantid/ticket/11342)

It's already on Owen Arnold's plan to implement a Smooth algorithm like Horace, but this should be exposed in the SliceViewer
- Choose number of pixels in each dimension to smooth.
- Choose a smoothing function?

See Horace signature and follow that as closely as possible

---

Keywords: VATES-vis

**Comment by OwenArnold** [comment]
@MattKing06 . I think this might be a duplicate of something you already have.

**Comment by MattKing06** [comment]
@OwenArnold You're right, This functionality is being implemented in #13493 which still needs to be completed.
