### ISSUE TITLE
Line Cut Tool looses focus

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12182]
This issue was originally [TRAC 11343](http://trac.mantidproject.org/mantid/ticket/11343)

You can end up with the pencil tool suppressed, but with out the ability to draw a line cut. Issue reported by Ross.

Seems to happen when you have been using the line cut tool and then switch to something else like zoom. You get the wrong cursor. Hitting the X fixes this.

1/2 day to fix estimate.

---

Keywords: VATES-vis

**Comment by lottiegreenwood** [comment]
After discussion, the aim of this ticket is now to change slice viewer so clicking on the 'clear line' button untoggles the line cut tool. 
A separate ticket has been made for the larger task of being able to add multiple line cuts and therefore plots to the slice viewer
