### ISSUE TITLE
SliceViewer Rebin mode of 2D slice step size

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12184]
This issue was originally [TRAC 11345](http://trac.mantidproject.org/mantid/ticket/11345)

By T Perring

Switch to Rebin mode in the SV. For the X, Y dims, we specify n-bins. We should be able to say that we want this in step size instead. 

We should be able to globally (or at least for that instance of the SliceViewer) set whether we want to work in #bins or in step size. All relevant controls should then be made to work like that.

3 day estimate.

---

Keywords: VATES-vis

**Comment by martyngigg** [comment]
Request from Excitations but they now primarily use mslice or non-mantid things for this type of work. Closing as stale.
