### ISSUE TITLE
Auto determine step size. SliceViewer.

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12183]
This issue was originally [TRAC 11344](http://trac.mantidproject.org/mantid/ticket/11344)

View an Q3 E workspace (MDEW) then apply histogram mode in the SV. The step-size in the slider dimensions for Energy are not sensibly calculated, and are often far too small. Your default is then to see nothing. Would be better if we could somehow drag the energy bin widths through from the loaded data.

I'm not sure the best way to do this? Field in multiple experiment info? The bin widths could be different per-file after all. And if you merge more runs you need to look at all bin withs to calculate a good one for the plot.

Changing the default in the SliceViewer is easy. Passing and calculating bin widths would be the tricky part. 4+ days estimate.

---

Keywords: VATES-vis

**Comment by martyngigg** [comment]
Closing this as we're not improving the old sliceviewer any further.
