### ISSUE TITLE
Creating a new project / clear all memory when an algorithm is running crashes Mantid

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12205]
This issue was originally [TRAC 11367](http://trac.mantidproject.org/mantid/ticket/11367)

To reproduce:
- Configure the script repository
- Open Mantid
- While the script repository is updating (seems to be any time the algorithm is running) click the new project button
- Mantid terminates with SIGILL

**Comment by NickDraper** [comment]
To reproduce:
1. Run the Pause algorithm with a time of 10
1. File ->new->new project
1. Crash

**Comment by NickDraper** [comment]
Algorithm manager should be the place to tackle this, in clear/destructor it should attempt to cancel all running algs, give them a short < 1s time to respond before carrying on regardless.

**Comment by FedeMPouzols** [comment]
I don't think I'll have much chance to tackle this. @DavidFair, @DimitarTasev: Have you observed issues like this in recent testing efforts?

**Comment by DavidFair** [comment]
I've just testing this against the latest build and the issue is no longer present. 
Closing as fixed
