### ISSUE TITLE
DKT fitting function improvements

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#12248]
This issue was originally [TRAC 11409](http://trac.mantidproject.org/mantid/ticket/11409)

The Dynamic Kubo Toyabe fitting function uses two parameters (```tsmax``` and ```eps```) to set the bin width to integrate the static function (```gStat```). Results may get inaccurate if the hopping rate, v, is high, that is, if v/G >> 1 (being G the local field). Ideally, eps<<v/G to obtain good results. Investigate how fitting results depend on these parameters and set a sensible factor for "<<".

 - - - - 
Keywords: muonFit

**Comment by raquelalvarezbanos** [comment]
This is no longer an issue: it was agreed with scientists, that, as fitting results do depend on these parameters, and given that they may need to use different values for different runs, an attribute should be added to the fitting function. To test: open Interfaces > Muon > MuonAnalysis. Go to the "Data analysis" tab. Right-click on "Functions" and add Muon > DynamicKuboToyabe. Make sure that there is an attribute called "BinWidth".

**Comment by tom-perkins** [comment]
Tested by adding a DynamicKuboToyabe function as above.
Verified that a BinWidth attribute was present with default value 0.05 as in documentation. 
Verified that it was not possible to set BinWidth outside of limits 0.001-0.1.
Closing issue
