### ISSUE TITLE
Const correctness for Workspaces

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12247]
This issue was originally [TRAC 11408](http://trac.mantidproject.org/mantid/ticket/11408)

I cannot do this inside the execute method of my algorithm.

```
 boost::shared_ptr`<const T>` prop = this->getProperty("InputWorkspace");
```

I can only do this
```
 boost::shared_ptr`<T>` prop = this->getProperty("InputWorkspace");
```

This is bad because If I have an InputWorkspace as Kernel::Direction.In (not Direction.InOut) I do not, and should not be given the ability to modify that Workspace.

The problem is in IPropertyManager TypedValue.

It should just be a case of introducing this to get things working. 

```
 /// explicit specialization for boost::shared_const_ptr
    template `<typename T>` operator boost::shared_ptr`<const T>`() {
      return pm.getValue`<boost::shared_ptr<T>`>(prop);
    }
```

**Comment by tom-perkins** [comment]
It's already possible to do this with many types of workspace, for example [MatrixWorkspaces](https://github.com/mantidproject/mantid/blob/86d2fbee4bd0bbbaa27d70c4d17c794dbc1f9920/Framework/Algorithms/src/CalculateFlatBackground.cpp#L78) (in the linked example, `MatrixWorkspace_const_sptr` is a typedef for `boost::shared_ptr<const MatrixWorkspace>`).

Stepping through, this code uses the existing specialisation for non-const shared_ptrs in TypedValue, and then there is a const_sptr specialisation for MatrixWorkspace itself [here](https://github.com/mantidproject/mantid/blob/86d2fbee4bd0bbbaa27d70c4d17c794dbc1f9920/Framework/API/src/MatrixWorkspace.cpp#L2058-L2072).

Searching through the code for `IPropertyManager::getValue<`, nearly all workspace types have specialisations for `shared_ptr<T>` and `const shared_ptr<T>`. A few do not have the const version: TableWorkspace (though ITableWorkspace does), IFunction and WorkspaceSingleValue, and these could be introduced for completeness.

**Comment by OwenArnold** [comment]
@tom-perkins If this is possible, could you please fix-up an algorithm to make a "model example" of how to obtain the right const-correctness, and then link to it in the tips section of Slack?
