### ISSUE TITLE
ISIS SANS GUI enhancement to Diagnostics Tab

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#12254]
This issue was originally [TRAC 11415](http://trac.mantidproject.org/mantid/ticket/11415)

Implement as described from email from Steve:

When you currently perform a horizontal or vertical integral, irrespective of what run, or range of rows/columns, you inspected, Mantid creates workspaces called

{detector}-detector-bank_H1
{detector}-detector-bank_V1

which is irritating if you want to compare different runs/ranges as you have to rename the workspaces each time before proceeding.

Please could we adopt a workspace naming more akin to that used for the reduced data, say

{runnum}-{detector}-detector-Hmin-Hmax

and similarly for V?

I realise that the range specifications can be quite complicated (and trying to implement such in a workspace name would be quite convoluted), hence I propose the above as a compromise.

The good news is that the H & V integrals do seem to be working as expected.

**Comment by picatess** [comment]
Stephen had written earlier that the worksapce names are for example
< {detector}-detector-bank_H1

I had a closer look at the code and it seems that the "detector-bank" string is part of the detector descriptor and not a separately added "noise" string.  For example I integrated the data set 74019 of LOQ and found that {detector} = main-detector-bank. This means that the file name is something like {detector}_H1.

In principle we could remove the "detector-bank" part of the detector descriptor, but it seems that if this string is not longer desired, then we should remove it self-consistently across all of SANS in a separate ticket. 

The ticket currently produces a workspace name of the type  {runnum}-{detector}-Hmin-Hmax.
