### ISSUE TITLE
Long term handling of embedding Nexus IDFs

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#12255]
This issue was originally [TRAC 11416](http://trac.mantidproject.org/mantid/ticket/11416)

As approved by TSC implement suggestion 2 in https://github.com/mantidproject/documents/blob/master/Design/EmbeddedInstrumentInfoNexus.md

 - - - - 
Keywords: core

**Comment by KarlPalmen** [comment]
All that remains is step 6:

(6) Code that makes use of the products of the previous steps to implement the ticket in each loader that may make use on an embedded IDF

This can be done in LoadIDFFromNexus and consists of adding the code to select parameters as appropriate making use of the previous steps. This will be done in this issue.

**Comment by KarlPalmen** [comment]
I have found out in a talk with Anders that the loading of an IDF adds some parameters directly and these need to be removed if append in false. There is an algorithm to clear parameters, which could be used for this. This makes a small change in the plan
```
# Some of Existing part
Load Embedded IDF

# New part
if( Correction file) 
   load it
   fn = ""
   ap = true
   for (each correction_item) 
      if(rawfile.date in correction_item.dates) 
         fn = correction_item.filename
         ap = correction_item.append
   if(fn)
       if(ap == true)
          # from existing part
          If(Embedded PF) load it
          else if (external PF) load it 
       else
           # Load Embedded IDF adds parameters
           clear parameters
        load fn
   else
       # from existing part
       If(Embedded PF) load it
       else if (external PF) load it 
else
   # from existing part
   If(Embedded PF) load it
   else if (external PF) load it 
```

**Comment by KarlPalmen** [comment]
I found that clearing the parameters still does not resolve the issue and so I made it issue #13328 , so this can be released for evaluation by scientists.

**Comment by KarlPalmen** [comment]
Release notes updated in LoadIDFFromNexus line of http://www.mantidproject.org/ReleaseNotes_3_5_Framework_Changes#Updated .
