### ISSUE TITLE
Feature: Add CutMD option for rebinning in the VSI

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#12287]
This issue was originally [TRAC 11448](http://trac.mantidproject.org/mantid/ticket/11448)

In addition to the currently available SliceMD and BinMD algorithms, we want to make the CutMD algorithm available as part of the rebinning feature in the VSI

 - - - - 
Keywords: VATES

**Comment by OwenArnold** [comment]
This has already been done.
