### ISSUE TITLE
Interface to McPhase

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12280]
This issue was originally [TRAC 11441](http://trac.mantidproject.org/mantid/ticket/11441)

This was basically described as a wrapper for running McPhase, an algorithm (possibly with custom interface).

---

Keywords: SSC, 2015, All, model

**Comment by mducle** [comment]
There is now a project (awaiting a developer) to re-implement McPhase in modern C++ with a PyBind11 interface: https://github.com/mducle/libmcphase 

It is envisaged that this project will have bindings to Mantid if both it and Mantid are available on a system.
