### ISSUE TITLE
Increase precision of sample log plots.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#12281]
1. Increase precision of the displayed numeric logs. Log Field_NMR of HIFI00077855 should look like the attached picture after some zooming.

2. Axis settings dialog rounds up entered min/max scale values to 2 decimal points. Increase precision to be able to enter double precision values.

**Comment by NickDraper** [comment]
From James Lord: 
Just tidying up some old emails and found this, and thought I’d check. I see that bug 2 is fixed (the inability to set precise start/end values for an axis), but bug 1 regarding loss of precision in the Sample Logs dialog remains (or has reappeared in 3.5.1 which I’m using now). If this is bug https://github.com/mantidproject/mantid/issues/12281 it needs reopening.

![graph](https://cloud.githubusercontent.com/assets/1017173/11711036/8f870a56-9f1b-11e5-98af-8a5a934d37bf.png)
