### ISSUE TITLE
Allow validateInputs to be unit tested on Python algorithms

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12330]
This issue was originally [TRAC 11491](http://trac.mantidproject.org/mantid/ticket/11491)

Currently the ```validateInputs``` function cannot be called in such a way that it can be used to unit test the validation in a more accurate way than just checking that running the algorithm raises ```RuntimeError```.

**Comment by NickDraper** [comment]
This is now exposed to python

duplicate
