### ISSUE TITLE
Issue with running LoadMDTest in Release under Windows

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#12334]
This issue was originally [TRAC 11496](http://trac.mantidproject.org/mantid/ticket/11496)

The unit test LoadMDTest has been failing while in release but not in debug. Martyn could track down the issue to be related to the defaultsave.directory being set to a custom path. 

You should be able to reproduce this issue, when resetting 
defaultsave.directory=YOURPATH in the Mantid.user.properties file.

 - - - - 
Keywords: Maintenance

**Comment by martyngigg** [comment]
We should first investigate whether this is still a problem.

**Comment by matthew-d-jones** [comment]
I've confirmed this is still a problem.
