### ISSUE TITLE
Optimise FileLoaderRegistry::chooseLoader

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#12409]
This issue was originally [TRAC 11571](http://trac.mantidproject.org/mantid/ticket/11571)

When loading a large multiperiod workspace, such as `INTER00027729.nxs`, Mantid freezes for several seconds. This is highly visible to the users, and takes up a non-trivial amount of the total loading time.

This freeze has been profiled to be coming from `FileLoaderRegistry::chooseLoader`. For a more detailed explanation of where the time is being spent, see comment 3 of http://trac.mantidproject.org/mantid/ticket/11483. You're encouraged to do some further profiling work yourself to verify this.

Ticket objective:
* Optimise chooseLoader to run against INTER27729 in a second or less.

 - - - - 
Keywords: CORE

**Comment by NickDraper** [comment]
Just tested on windows and this was quick.  Recent work on performance has obviously solved this.
