### ISSUE TITLE
FABADA can segfault when fit is bad

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12416]
This issue was originally [TRAC 11578](http://trac.mantidproject.org/mantid/ticket/11578)

When running FABADA with stupid limits for the chain length and max iterations the minimizer can segfault when generating the reduced chain (reducing the number of chain points by a factor of StepsBetweenValues).

The times I've managed to get this to happen the MaxIteration limit was hit and the ChainLength was significantly larger then MaxIterations.

You would never actually run FABADA with this setup but reducing MaxIterations is usually how I speed up testing.

**Comment by DanNixon** [comment]
After using it more I'm not convinced what I thought was the original issue actually is, even with correct values for the attributes it can still segfault, I think the issue still only happens when the fit is bad but not sure of the actual reason yet.

**Comment by NickDraper** [comment]
Without better reproducability archiving for now
