### ISSUE TITLE
Add Vanadium (V-Nb) consideration into EnginX algorithms

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#12426]
This issue was originally [TRAC 11588](http://trac.mantidproject.org/mantid/ticket/11588)

This ticket is blocks :  [TRAC8368](http://trac.mantidproject.org/mantid/ticket/8368)

Currently EnginX CalibrateAll does not consider the vanadium number when calibrating. This is necessary to get useful calibration results.

In order to do this, there are two methods:

'''Method one'''

1) Add in option to load the ceria and vanadium numbers

2) Fit a spline to each pixel (V-Nb) and store them with vanadium in a filename

3) Divide each Ceria pixel by the spline

'''Method two'''

1) Add in option to load the ceria and vanadium numbers

2) Add together each V-Nb pixel to get 1 number (the sensitivity) and store it

3) Divide the ceria pixel with corrected sensitivity number

4) Convert unit to dspacing on V-Nb and add each bank together to get 2 spectr.

5) Fit spline to 2 spectrum and store

6) Convert unit ceria to dspacing and divide each pixel with the corresponding curve

7) Divide each ceria pixel by corrected sensitivity number

**Comment by FedeMPouzols** [comment]
From further discussions:

- Method 1 is not a good option. Go for method 2.
- This Vanadium consideration or correction needs to be added into `EnginXFocus` and `EnginXCalibrateFull`. Both algorithm will need an additional, mandatory input, say `VanadiumFile`.
- Steps for the Vanadium correction:
  - sensitivity correction.
  - pixel-by-pixel (detector-by-detector) correction.

To do the sensitivity correction:
- In ToF space, for every spectrum, every bin of the input data needs to be rescaled by multiplying by the following value from the vanadium data: bin * (integral of spectrum) / (number_of_bins). when this is done, remember to double-check with scientists that with this we get a proper normalization or scale.

To do the pixel-by-pixel correction:
- All in d-spacing. Take all the spectra of one bank and sum them all. Fit a spline to the sum. For every spectrum, divide by it. Do this for bank 1 and bank 2 separately.
