### ISSUE TITLE
Mouse sensitivity in new VSI

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12438]
This issue was originally [TRAC 11600](http://trac.mantidproject.org/mantid/ticket/11600)

Roman, I understand you have some experience with this. Do you think you could look into the issue for us please.

Message from Jon Taylor:

> Lastly on mac it seems that everything is scrollable via the “magic mouse” virtual scroll, is there a way of changing the sensitivity of this as its very sensitive.

---

Keywords: vates

**Comment by quantumsteve** [comment]
@OwenArnold @mantid-roman Would you mind trying this again on master or a recently nightly build with ParaView 5.1? I can no longer reproduce this scrolling issue with my "magic trackpad" on OS X.

**Comment by quantumsteve** [comment]
ParaView removed from 6.0 release
