### ISSUE TITLE
Stop Reduction with Visible Error if SANS2DTUBES Not Selected

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#12444]
sans_bugfix
This issue was originally [TRAC 11606](http://trac.mantidproject.org/mantid/ticket/11606)

We have as an eventual aim the complete removal of SANS2DTUBES from the instrument drop-down (the reasons for the option's existence being documented elsewhere).  This however will likely be done as part of a complete overhaul of the reduction code, and so in the meantime we'd like to visibly warn users in the following use case:
- They do some work in the interface with SANS2DTUBES selected.
- They close down the interface (possibly as a workaround to clear all settings!)
- They reopen the interface, and intend to continue using new tube data, but forget to reselect the SANS2DTUBES instrument therefore leaving it on the SANS2D setting.
- It's unclear whether or not the reduction falls over with an obtuse error message or just carries on merrily, but either way we need to do better.

Although not really ideal practice to code in this way, an easy way to implement this would be to (at the appropriate place in the code), check to see if the run number of any SANS2D data that gets loaded post-dates the switch to gas tube detectors.

It may be easier / better to instead check the date of the file itself rather than use run numbers.

This came out of the initial handover / catch up session with the scientists, who confirmed that although not a high-priority ticket, would be a nice "easy win" for Anton to accomplish in the short term.

**Comment by AntonPiccardoSelg** [comment]
This is not relevant for the new reduction framework and will most liekly not be done for the old one
