### ISSUE TITLE
LoadEventNexus needs to be able to handle multiple periods for ISIS files

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12443]
This issue was originally [TRAC 11605](http://trac.mantidproject.org/mantid/ticket/11605)

Larmor run number 2827 is now a file with the monitors in histogram mode with 4 periods and the detectors in event mode with the correct information in
 
```Raw_data_1/framelog/period_log```

where each entry is the period assigned to the frame (pulse) at the given index.

**Comment by martyngigg** [comment]
@OwenArnold I'm not sure if you have an open issue for this already...

**Comment by OwenArnold** [comment]
#12776 is handling this

**Comment by martyngigg** [comment]
Okay. Closing as duplicate of #12776
