### ISSUE TITLE
System Tests for LARMOR and ZOOM

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#12446]
sans_test
This issue was originally [TRAC 11608](http://trac.mantidproject.org/mantid/ticket/11608)

We do not have any system tests in place for LARMOR yet.  We are waiting for Rob to be happy with the reduction and how it will be used "in the wild" before committing to concrete test coverage.

Rob would be the person to speak to for example reductions and data.

**Comment by AntonPiccardoSelg** [comment]
This is not true any longer for the new reduction framework, however LARMOR is underrepresented in the tests. In addition we need to write ZOOM tests when appropriate
