### ISSUE TITLE
Improvements to SliceViewer User expreience: Part 2

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12456]
This issue was originally [TRAC 11618](http://trac.mantidproject.org/mantid/ticket/11618)

This ticket is blocked by : 
- [ ] [TRAC9646](http://trac.mantidproject.org/mantid/ticket/9646)
- [ ] [TRAC9962](http://trac.mantidproject.org/mantid/ticket/9962)
- [ ] [TRAC9965](http://trac.mantidproject.org/mantid/ticket/9965)
- [ ] [TRAC9972](http://trac.mantidproject.org/mantid/ticket/9972)
- [ ] [TRAC9995](http://trac.mantidproject.org/mantid/ticket/9995)

Cloned from http://trac.mantidproject.org/mantid/ticket/9307: 

---

Improvements to various GUIs and CLIs.  Probably needs more input from instrument scientists. Dependent on the outcomes of MSlice, VATES defaults and general scriptability tasks.  

Remaining items from part 1 in blocked by list:

---

Keywords: SSC,2014,All, VATES-vis

**Comment by OwenArnold** [comment]
@picatess  check that this stuff is still important to do. Some of it might have been fixed already.

**Comment by AntonPiccardoSelg** [comment]
Apparently there has been a shift away from the SliceViewer to MSlice and some SSC issues have been overriden (including this one). Hence we are closing this
