### ISSUE TITLE
Unit test for PlotAsymmetryByLogValue skipping missing files

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#12469]
This issue was originally [TRAC 11631](http://trac.mantidproject.org/mantid/ticket/11631)

Add unit test for the ability of PlotAsymmetryByLogValue to skip a missing file as implemented in ticket http://trac.mantidproject.org/mantid/ticket/11624.

**Comment by tom-perkins** [comment]
Linked: system test for PABLV (#13072), refactor PABLV for testability (#13152)
