### ISSUE TITLE
Frames and Axis issues

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12473]
This issue was originally [TRAC 11635](http://trac.mantidproject.org/mantid/ticket/11635)

You can treat this as an umbrella ticket. The issues that have plagued paraview regarding model coordinates and axis MUST be fixed in the next version of Mantid. Minimum steps would be (not necessarily in this order) :
1. Move to ParaView 4.4 and check that existing issues have been resolved
2. Enable switching between non-orthogonal and orthogonal respresentations (ask owen)
3. Ensure that cube axis can be sensibly applied and customised everywhere that we would need them
4. We should be able to throw up 2D labels to be be locked to 3D/4D points in space.
5. QuadView should default to have the slice increment move by 1 exactly in every dimension.
   ---
   
   Keywords: vates

**Comment by AntonPiccardoSelg** [comment]
Some of these items have been dealt with. The features which are missing, are very unlikely to be added in the future, hence I am closing this issue.
