### ISSUE TITLE
WISH monitors in Live Data

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#12507]
This issue was originally [TRAC 11669](http://trac.mantidproject.org/mantid/ticket/11669)

Live Data can have the wrong number of bins for WISH monitors. Attached is a plot of a monitor loaded form the DAE. The irregularity there is due to empty bins (X=Y=E=0). 

This could be a result of
1. old software on WISH (needs updating) or
2. a bug in mantid.

My understanding is that Live Data is not widely used on WISH so I give the ticket a low priority.

**Comment by stuartcampbell** [comment]
![wish](https://cloud.githubusercontent.com/assets/284663/7987516/fcec8170-0aab-11e5-9a81-905947ba4e63.png)

**Comment by NickDraper** [comment]
not mentioned again for year - archived

**Comment by NickDraper** [comment]
not mentioned for years - archived
