### ISSUE TITLE
VSI help page

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12536]
This issue was originally [TRAC 11698](http://trac.mantidproject.org/mantid/ticket/11698)

http://www.mantidproject.org/VatesSimpleInterface_v2_future Must be made ready for the new release.
- Updated to match the version 3.4 PV changes
- Swapped with the current page so that it gets linked to from the help
- Check content, probably best done by tester. Does this page explain the concepts well.
- Also, a comment from Nick: For the help file – we need to be explicit how to zoom, and interact with the three slice view
  ---
  
  Keywords: vates

**Comment by AntonPiccardoSelg** [comment]
All of this is complete, closing issue.
