### ISSUE TITLE
Slice increments on the three slice view are too large

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12546]
This issue was originally [TRAC 11707](http://trac.mantidproject.org/mantid/ticket/11707)

Would be good if we could set these increments to some good default value based on the actual binning if possible.

Anton, could you spec this out and then pass on to Federico please.

---

Keywords: vates

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.
