### ISSUE TITLE
LoadNXSPE

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12553]
This issue was originally [TRAC 11715](http://trac.mantidproject.org/mantid/ticket/11715)

For most load algorithms, the load offers to fill in the name of the output workspace from the filename. However for LoadNXSPE you have to fill it in yourself when opening the algorithm in MantidPlot. This should be fixed.

 - - - - 
Keywords: vates

**Comment by KarlPalmen** [comment]
When I loaded (via load)  the NXSPE file used to test LoadNXSPE in its unit test I found the output workspace filled in as with other algorithm.

However I've found that if one runs a load algorithm (such as LoadNexus) directly one does have to fill in the output workspace.

**Comment by KarlPalmen** [comment]
Closed after chat with @OwenArnold .
