### ISSUE TITLE
Set sensible default end file directory

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#12564]
This issue was originally [TRAC 11726](http://trac.mantidproject.org/mantid/ticket/11726)

In PlotAsymmetryByLogValue (and ALC) the user selects a set of runs by indicating the first run in the set and the last one. This is a ticket to set the default end file directory to the directory from which the first run was selected.

**Comment by tom-perkins** [comment]
Issue raised again during beta test period for 3.6, so returning to normal priority
