### ISSUE TITLE
Add ability to select peaks by right-clicking on graph

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#12563]
This issue was originally [TRAC 11725](http://trac.mantidproject.org/mantid/ticket/11725)

In ALC (PeakFitting step), add the ability to select peaks by right-clicking on the graph.

 - - - - 
Keywords: ALC

**Comment by raquelalvarezbanos** [comment]
This issue was raised by scientists because they were not aware (and neither was I) that the interface already allows to do this. Therefore, this is not an issue anymore.

To test: Open the interface: Interfaces > Muon > ALC. Read the documentation: http://docs.mantidproject.org/nightly/interfaces/Muon_ALC.html and use the example dataset used there (you can find the HIFI runs here: \\ISIS\inst$\NDXHIFI\Instrument\data\cycle_13_1). When you reach the PeakFitting step, add two peaks to the function browser, select the first one (it will be highlighted in blue) press Shift and left click near the peak. A red peak picker will appear. To change the peak's width, click and drag while holding Crtl. Repeat the same steps with the second peak.

**Comment by tom-perkins** [comment]
Tested with example HIFI data as above. Added peaks to function browser.
Verified that peak positions can be set by Shift-clicking and peak width can be set by Ctrl-clicking.
Closing issue as required functionality is already present.
