### ISSUE TITLE
Calling MergeRuns on a WorkspaceGroup gives an error

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12573]
This issue was originally [TRAC 11735](http://trac.mantidproject.org/mantid/ticket/11735)

```
Only one input workspace specified
Logic Error in execution of algorithm MergeRuns
Only one input workspace specified
```

And the algorithm cannot be terminated.

I had originally assumed that this might allow me to merge multi period data without having to type the same workspace name 6 times.

**Comment by soininen** [comment]
This issues seems to have been fixed as `MergeRuns` works on workspace groups on current master.
