### ISSUE TITLE
Sliceviewer intensity incorrect after rebin

### ISSUE THREAD

**Issue by eXeC64** [mantidproject/mantid#12602]
This issue was originally [TRAC 11764](http://trac.mantidproject.org/mantid/ticket/11764)

If you enable rebin mode in the slice viewer, the intensity indicated when hovering the mouse over the plot shows the pre-rebin intensity, rather than the post-rebin intensity.

It should show the intensity of the rebinned data, if it's being shown.

**Comment by martyngigg** [comment]
We have little capacity to fix this before 5.1 and there is then no point. It has not caused problems this far. Closing as stale and wontfix.
