### ISSUE TITLE
All systemtests to work on at least one platform

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#12615]
This issue was originally [TRAC 11777](http://trac.mantidproject.org/mantid/ticket/11777)

This ticket is blocked by : 
- [X] [TRAC11797](http://trac.mantidproject.org/mantid/ticket/11797)
- [ ] [TRAC11799](http://trac.mantidproject.org/mantid/ticket/11799) #12637 
- [X] [TRAC11800](http://trac.mantidproject.org/mantid/ticket/11800)
- [X] [TRAC11801](http://trac.mantidproject.org/mantid/ticket/11801)
- [ ] [TRAC11802](http://trac.mantidproject.org/mantid/ticket/11802) #12640
- [X] [TRAC11803](http://trac.mantidproject.org/mantid/ticket/11803)
- [ ] [TRAC11804](http://trac.mantidproject.org/mantid/ticket/11804) #12642

With reference to https://github.com/mantidproject/documents/blob/master/Project-Management/TechnicalSteeringCommittee/reports/MaintenanceTasks.md, this is the umbrella ticket to ensure that every systemtest runs on at least one platform. 

Please see http://developer.mantidproject.org/systemtests/ for which tests are not run on any platform (those which have crosses against all platforms).

Email/create tickets for developers for each systemtest, which currently are not running on any platform.

---

Keywords: Maintenance

**Comment by KarlPalmen** [comment]
Issue numbers of open blocking tickets (June 4, 2015)
#12637 and #12642 assigned to @abuts and #12640 assigned to @mdoucet .
