### ISSUE TITLE
Fill in argument list in python bindings

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#12624]
This issue was originally [TRAC 11786](http://trac.mantidproject.org/mantid/ticket/11786)

This will allow for better documentation in python help system. [IEventWorkspace](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/PythonInterface/mantid/api/src/Exports/IEventWorkspace.cpp)  is an example of what the work actually is.

This is an umbrella ticket to cover the actual work being done.

 - - - - 
Keywords: Maintenance
 
#### Sub tasks

- [x] kernel - #13690
- [x] geometry - #13691
- [x] api - #13692
- [x] dataobjects - #13693

**Comment by AndreiSavici** [comment]
Here is a simple way to check (just replace ```mantid.kernel``` with your favourite module):

```python
import mantid.kernel as module
import inspect
import re

counter=0
classes=inspect.getmembers(module,inspect.isclass)
for c in classes:
    member_class_object=getattr(module,c[0])
    functions=inspect.getmembers(member_class_object,inspect.ismethod)
    for f in functions:
        function_object=getattr(member_class_object,f[0])
        function_doc=function_object.__doc__
        if function_doc!=None and re.search('arg[0-9]',function_doc):
            print "\n*****\n",c[0], f[0], function_doc
            counter+=1

print "Found "+str(counter)+" functions with undocumented arguments"
```

**Comment by peterfpeterson** [comment]
Assuming the last pull request is merged, this is "done."
