### ISSUE TITLE
Use header analysis tools

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#12627]
This issue was originally [TRAC 11789](http://trac.mantidproject.org/mantid/ticket/11789)

Improve headers (e.g. includes) based on the results of header analysis (e.g. include what you use and CLion) - Limited to 2 man days

This is an umbrella ticket. Distribute the actual work as you see fit.

 - - - - 
Keywords: Maintenance

**Comment by stuartcampbell** [comment]
The work for the period mentioned was completed.  Will open a new ticket for the next maintenance period.
