### ISSUE TITLE
Harmonize the PSI contributions

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#12630]
This issue was originally [TRAC 11792](http://trac.mantidproject.org/mantid/ticket/11792)

There are various things in the package that should either be dropped in favor of the "standard" way, or should be made available to the project as a whole.

---

Keywords: Maintenance

**Comment by OwenArnold** [comment]
There's quite a few MD-algorithms that are duplicates of existing ones, or have more generic versions elsewhere in Mantid now. For example TransposeMD.
