### ISSUE TITLE
Add StretchedExpFT function to IDA ConvFit

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#12643]
This issue was originally [TRAC 11805](http://trac.mantidproject.org/mantid/ticket/11805)

The StretchedExpFT fit function can be used to fit data doing a resolution convolution as is done in ConvFit so could easily be added to the interface.

**Comment by DanNixon** [comment]
#12669 will make this redundant.

**Comment by ElliotAOram** [comment]
This has been completed in #12669
