### ISSUE TITLE
OFFSPEC IDF

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12644]
Important IDF updates. Provided by and tested by Tim Charlton.

The IDF is attached, but as Harry has said it's failing to pick up the required 'vertical gap' parameter. The problem concerns http://docs.mantidproject.org/nightly/algorithms/CalculateResolution-v1.html, that should be a good starting point. 

When you run it through the User Interface (ISIS Reflectometry Polref). You'll have to add an 'OFFSPEC' entry in the gui so that this can be used. 

For comparison. Look at how the Inter IDF is setup. You can just put 13460 into the run column an hit 'Process' and it works.

**Comment by MattKing06** [comment]
I have changed the IDF and tested it on my own machine; I believe it works properly now. 
The new IDF can be found on the PR in Refs #825.
