### ISSUE TITLE
Error message for loading PeaksWorkspace

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#12653]
This issue was originally [TRAC 11815](http://trac.mantidproject.org/mantid/ticket/11815)

When loading a nexus file containing a PeaksWorkspace with no peaks, the error message is "Runtime Error:  Cannot open group /mantid_workspace_1/workspace of class NXdata"  Check for this and print better error message.

 - - - - 
Keywords: Nexus

**Comment by Anders-Markvardsen** [comment]
@VickieLynch could you provide a step by step example of how to reproduce this. i.e. load so and so file etc. then this issue may be a good new starter (easy) issue candidate

**Comment by shahrozahmed1** [comment]
[Nexus File](http://we.tl/YyEDHMG4uP) which will reproduce this error message
