### ISSUE TITLE
Combination of QxQz maps

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12672]
This issue was originally [TRAC 11834](http://trac.mantidproject.org/mantid/ticket/11834)

QxQz maps can be created using ConvertToReflectomtryQ.

This ticket is two allow two or more maps to be combined.

Speak to Tim Charlton to work out how they want them combined.

---

Keywords: reflOther

**Comment by raquelalvarezbanos** [comment]
Asked Tim about this:

> The end goal is a user callable function similar to Stitch1DMany which could take a lift of 2D workspaces and a specification for the output grid.  Combining full q-maps is tricky for two reasons,  a) the relative scaling and b) the variation in bin size across the qx-qz surface. The output would be a seamless qx-qz-Intensity surface which could be used to extract 1D cuts along the primary coordinate axes. I believe that there are some tool which preform a similar task for diffraction data.

**Comment by raquelalvarezbanos** [comment]
Assigning this to Release 3.8 as it was marked as Low priority. The estimate time to complete this task was initially 2-3 weeks.

**Comment by raquelalvarezbanos** [comment]
In a meeting with Jos and Max today, we agreed that they will ask Tim about this, as they are not 100% sure it is the best way to combine the data.

**Comment by raquelalvarezbanos** [comment]
I think this is no longer a requirement, at least scientists haven't mentioned this recently. I am leaving this open but we should ask them at some point if they still need this.

**Comment by gemmaguest** [comment]
Closing as Stale because the scientists are not sure how this would be done anyway.
