### ISSUE TITLE
MantidPlot crashes on startup with non-default theme on Ubuntu

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#12673]
This issue was originally [TRAC 11835](http://trac.mantidproject.org/mantid/ticket/11835)

To reproduce:
- go to the Apperance menu from the Ubuntu launcher
- select a different theme to Ambiance
- start MantidPlot
- bang!

**Comment by jpcastell** [comment]
On Ubuntu mine crashes as well on start of the program.  It doesn't matter what theme I use though.

"
FrameworkManager-[Notice] Welcome to Mantid version 3.2.1 - Manipulation and Analysis Toolkit for Instrument Data
FrameworkManager-[Notice] Please cite Mantid in your publications using: http://dx.doi.org/10.5286/Software/Mantid3.2.1
MantidPlot: /build/buildd/sip4-4.15.5/siplib/siplib.c:8407: sip_api_can_convert_to_type: Assertion `(((td)->td_flags & 0x0007) == 0x0000) || (((td)->td_flags & 0x0007) == 0x0002)' failed.
Aborted (core dumped)
"

**Comment by martyngigg** [comment]
@jpcastell It seems to be pointing at a custom build of the `sip` rather than the version we built against. What does `python -c "import sip; print sip.__file__"` say?

**Comment by jpcastell** [comment]
/usr/lib/python2.7/dist-packages/sip.so


On Thu, Jun 25, 2015 at 2:26 PM, Martyn Gigg <notifications@github.com>
wrote:

> @jpcastell <https://github.com/jpcastell> It seems to be pointing at a
> custom build of the sip rather than the version we built against. What
> does python -c "import sip; print sip.__file__" say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mantidproject/mantid/issues/12673#issuecomment-115234005>
> .
>



-- 
John-Paul Castellan

mobile phone: +33781159511

**Comment by martyngigg** [comment]
@jpcastell Is this from a package install? Could you try the latest version from http://sourceforge.net/projects/mantid/files/3.4/mantid_3.4.0-1_amd64.deb/download. Sorry it's not in the repo yet

**Comment by martyngigg** [comment]
Not moving forward with this as Workbench will do a better job.
