### ISSUE TITLE
Multiple instrument views in the multi graph window

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12674]
sans_feature
This issue was originally [TRAC 11836](http://trac.mantidproject.org/mantid/ticket/11836)

This ticket is blocks :  [TRAC11837](http://trac.mantidproject.org/mantid/ticket/11837)

Allow users to dock instrument view in the multi graph window, showing just the  current display section (no toolbars or tabs) when docked.

Also allow the creation of a window given several workspaces or workspace group.  The view should default to the default instrument view.

---

Keywords: sansUI

**Comment by smk78** [comment]
Also see https://github.com/mantidproject/mantid/issues/12675
