### ISSUE TITLE
ISIS Sans GUI Introduce mechanism to launch the "raw data view"

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12675]
sans_feature
This issue was originally [TRAC 11837](http://trac.mantidproject.org/mantid/ticket/11837)

This ticket is blocked by : 
- [ ] [TRAC11836](http://trac.mantidproject.org/mantid/ticket/11836)

ISIS Sans GUI Introduce mechanism to launch the "raw data view" - a multiple graph window with instrument displays for one or more workspaces.

---

Keywords: sansUI

**Comment by AntonPiccardoSelg** [comment]
Steve King would like to have this. The `InstrumentView` is very resource intensive. Future changes to it might improve the situation. Speak to Lamar about this.

**Comment by gemmaguest** [comment]
Discuss with Nick

**Comment by smk78** [comment]
After review, the SANS Group would like to clarify that all we are really looking for here is the ability to plot the raw detector data from one or more nxs files. The 3D instrument geometry that the instrument view puts on top is unnecessary for this. In essence, colorfill plots of raw data, as opposed to processed data.

**Comment by smk78** [comment]
Being able to visualise on demand what the 2D detector patterns look like from any runs in the reduction table in the SANS GUI _without_ having to load every single run and open it in the Instrument View remains a key aspiration of the SANS Group and its Users.

**Comment by martyngigg** [comment]
I'm just removing the MantidPlot label from the remaining issues that have it to be clear it's not related to that.
