### ISSUE TITLE
GUI for Muon frequency domain analysis

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12682]
Purpose to add a muon frequency domain analysis gui, which includes the option to run a MaxEnt fourier analysis.

**Comment by raquelalvarezbanos** [comment]
This is blocked by:

- [ ] #12683

**Comment by raquelalvarezbanos** [comment]
A first version of MaxEnt was added. However, before we can start thinking about a GUI for MaxEnt, we have to make sure scientists are happy with the algorithm. I'll write a comment here when we are ready to start working on this.

**Comment by tom-perkins** [comment]
Roadmap estimate: 6-12m. Target: release 3.9

**Comment by tom-perkins** [comment]
Meeting 11/5/16: James Lord sent a document about this. Uploaded it to documents repository at https://github.com/mantidproject/documents/blob/master/Design/Muon%20Frequency%20Domain%20analysis.docx

**Comment by Anders-Markvardsen** [comment]
Note that the ported Fortran code to python should not be used for this GUI. Instead the more recentlly added MaxEnt algorithm

**Comment by AnthonyLim23** [comment]
The MaxEnt algorithm can calculate the fit to time-domain data without an explicit model. This is achieved by altering a frequency domain model, which is then converted it into time domain data, via a FFT (Fast Fourier Transform), and compared to the real data. The algorithm is complete when the chi squared value is below some threshold value. 

The MaxEnt algorithm has already been added to Mantid. The next step is to produces a GUI. The GUI should allow the user to modify the parameters in an intuitive manner. The GUI should also produce plots of the time domain data (raw data and the model) and the frequency domain data. The GUI could be a stand alone or part of the muon analysis GUI (or both). 

It may be worth adding an option for showing the FFT of the real data.

**Comment by AnthonyLim23** [comment]
This is done :)
