### ISSUE TITLE
Port maxEnt to Python from FORTRAN

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12683]
This issue was originally [TRAC 11845](http://trac.mantidproject.org/mantid/ticket/11845)

F2Py usage limits the code to windows only.

Look to port and document the code to python (or C++ if performance requires it).

 - - - - 
Keywords: muonOther

**Comment by raquelalvarezbanos** [comment]
This should block #12682

Anders provided a C code that can be used as a starting point. I will take it as a reference, as well as the original Fortran code provided by muon scientists, which can be found here https://github.com/mantidproject/3rdpartysources/tree/master/Fortran/Muon/MaxEnt

Additional references:
- http://prjemian.github.io/sizes/_modules/SB_MaxEnt/sbmaxent.html
- http://rd.springer.com/article/10.1007%2FBF02068515
- http://articles.adsabs.harvard.edu/cgi-bin/nph-iarticle_query?1984MNRAS.211..111S&defaultprint=YES&page_ind=4&filetype=.pdf
