### ISSUE TITLE
Horace like Fitting

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12693]
This issue was originally [TRAC 11855](http://trac.mantidproject.org/mantid/ticket/11855)

This ticket blocks :  #12070

Implement horace style fitting http://horace.isis.rl.ac.uk/Fitting

Ask Alex Buts/Russell Ewings/Toby Perring for help with this.

**Estimate 4-8 man-weeks effort** - Roman, please update this estimate if you know better.

Create python wrappers for easier function setup.

---

Keywords: vates-cli

**Comment by NickDraper** [comment]
This is now the PACE project
