### ISSUE TITLE
Symmetrisation Operations Horace-like

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12691]
This issue was originally [TRAC 11853](http://trac.mantidproject.org/mantid/ticket/11853)

This ticket is blocks :  [TRAC11231](http://trac.mantidproject.org/mantid/ticket/11231)

We have a requirement to deal with Symmetrisation like Horace http://horace.isis.rl.ac.uk/Symmetrising_etc#symmetrise_sqw

I think this has been discussed, but I didn't see any existing tickets for it. 

At a very naive estimate, I guess **4 man-weeks**. Andrei please update as appropriate, and grab any help you need to do this work.

---

Keywords: vates-cli

**Comment by AndreiSavici** [comment]
This is implemented by `MDNorm` algorithm.
