### ISSUE TITLE
Add MSlice to Mantid

### ISSUE THREAD

**Issue by millersd** [mantidproject/mantid#12704]
This issue was originally [TRAC 11866](http://trac.mantidproject.org/mantid/ticket/11866)

put together a specification, then evaluate existing (half done?) code

Look at the work that was done by Steve Miller
https://github.com/neutrons/mslice_2.0

It is likely that this is the best starting point for this.

Also it may be worth looking at the work done by Jon Taylor on this.

**Comment by NickDraper** [comment]
The prototype is now in the Mantid repo, and has been released to scientists for feedback
