### ISSUE TITLE
Update logging properties configuration

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#12703]
This issue was originally [TRAC 11865](http://trac.mantidproject.org/mantid/ticket/11865)

It would be really useful to be able to log to console at ```notice``` and file at ```information```. However, the current [http://docs.mantidproject.org/nightly/concepts/PropertiesFile.html#logging-properties documentation] does not explain how to have ```logging.channels.fileFilterChannel.level``` be lower than ```logging.loggers.root.level```. Update the documentation to explain how to do this.

**Comment by NickDraper** [comment]
You can't  logs are not even generated if they are below the root level, although you could reconfigure it to have the root level lower and put a more specific filter on the console output.

**Comment by peterfpeterson** [comment]
The docs need information on how to set the filter for the console output.

**Comment by NickDraper** [comment]
I'll have a fiddle to see that it is possible first
