### ISSUE TITLE
FilterEvents UI

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12702]
This issue was originally [TRAC 11864](http://trac.mantidproject.org/mantid/ticket/11864)

We have a FilterEventsUI that could be useful but needs some work

* No Help
* Doesn't seem to do FastLogs time at sample correction (or at least doesn't list it)
* Not easy to figure out how to work with, and I know the EventFiltering side of things

If this is done, should be done in conjunction with Wenduo. 

 - - - - 
Keywords: Student

**Comment by shahrozahmed1** [comment]
Cannot be resolved until issue #13229 has been resolved
