### ISSUE TITLE
Move IPeak.cpp python export is in the wrong directory now

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12716]
This issue was originally [TRAC 11878](http://trac.mantidproject.org/mantid/ticket/11878)

This ticket is blocked by : 
- [X] [TRAC11868](http://trac.mantidproject.org/mantid/ticket/11868)

Issue details are blank in trac

**Comment by raquelalvarezbanos** [comment]
Not sure what this refers to, can it be closed?
