### ISSUE TITLE
Migrate to newer ParaView

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#12719]
This issue was originally [TRAC 11881](http://trac.mantidproject.org/mantid/ticket/11881)

We would like to move VATES from ParaView 4.3.1 to a later snapshot so that we can use the new features from our latest contract and also ease our move to ParaView 5. The SHA1 Utkarsh suggests is `b40280a2f274aa27aac707abf9097317f731dcc1` from May 31, 2015

**Comment by quantumsteve** [comment]
There is something strange with Paraview 4.4 and the VSI. It's as though the signal has disappeared! Perhaps this is related to changes in either the signal or the colormap?

Below is the view at z=-3.5 from slice viewer.
![viewfromsliceviewer](https://cloud.githubusercontent.com/assets/5920552/8171625/6c879a22-1387-11e5-9458-20a7ff0d3276.png)
Below is the same view at z=-3.5 in the VSI

![viewfromvsi](https://cloud.githubusercontent.com/assets/5920552/8171629/74429ad2-1387-11e5-965d-71e6bcfbf02b.png)

**Comment by picatess** [comment]
The auto scale checkbox is unchecked. What happens when you check the "Auto Scale" checkbox? It seems though that the range is 2e-3 to 2e-2 for both the SliceViewer and the VSI, so auto scaling will probably have no effect.

Things to check:
*  Have you tried another color map?
*  Does this happen for all views?
*  If you play manually with the limits of the color scale, can you create some differentation in the display color?
* Have you tried to open this in the "old" Mantid build and checked if this happens? It might be independent of PV4.4

**Comment by quantumsteve** [comment]
* Yes, I tried several colormaps
* Yes, it appears to be consistent among all of the views.
* There is some signal on the order of 10^-7, but it doesn't match the pattern above.
* I opened and viewed the same dataset in mantid nightly without issue.

**Comment by quantumsteve** [comment]
It was human error and not some bizarre change in PV. I clicked the wrong download link and got v3.4 instead of nightly. Mantid nightly has the same issues auto-selecting the correct normalization.

The normalization selection isn't a PV 4.4-specific issue, I created a separate issue #12832.

**Comment by quantumsteve** [comment]
I think the next commit fixes the following warning. 

```
[2651/3054] Building CXX object Vates/VatesSimpleGui/ViewWidgets/CMakeFiles/VatesSimpleGuiViewWidgets.dir/src/ViewBase.cpp.o
/Users/svh/Documents/MantidProject/mantid/Code/Mantid/Vates/VatesSimpleGui/ViewWidgets/src/ViewBase.cpp:86:25: warning: 'getWidget' is deprecated [-Wdeprecated-declarations]
  hbox->addWidget(view->getWidget());
                        ^
/Users/svh/Documents/MantidProject/ParaView/Qt/Core/pqView.h:79:23: note: 'getWidget' has been explicitly marked deprecated here
  VTK_LEGACY(QWidget* getWidget());
                      ^
/Users/svh/Documents/MantidProject/ParaView/VTK/Common/Core/vtkSetGet.h:795:30: note: expanded from macro 'VTK_LEGACY'
#  define VTK_LEGACY(method) method __attribute__((deprecated))
                             ^
1 warning generated.
```
