### ISSUE TITLE
Extend LoadEventNexus to handle multiperiod event files

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12776]
From Rob Dalgleish:

Freddie has fixed the problem with counting using software periods in event mode on Larmor
Larmor run number 2827 is now a file with the monitors in histogram mode with 4 periods and the detectors in event mode with the correct information in 
 
Raw_data_1/framelog/period_log
 
I’ve checked the filtering of the events and compared it to Freddie’s pre filtered raw file which gives the run as histograms separated into periods and you can see the result below. (Thankfully the same!)
 
Could you change the LoadNexus routine using run 2827 as a check to make sure the monitors and detectors behave correctly.
 
![sample](https://cloud.githubusercontent.com/assets/1017173/8056146/499e6994-0e9d-11e5-87c0-401cae62b969.png)

**Comment by OwenArnold** [comment]
This will now generate the same plot Rob provided above
```python
Load(Filename='LARMOR00002827.nxs', OutputWorkspace='LARMOR00002827', LoadMonitors=True)
Rebin(InputWorkspace='LARMOR00002827_1', OutputWorkspace='rebinned_1', Params='1000')
SumSpectra(InputWorkspace='rebinned', OutputWorkspace='rebinnedsummed')
rebinnedsummed = mtd['rebinnedsummed'][0]
plot_spectrum(workspaces=rebinnedsummed, indices=0)
```
