### ISSUE TITLE
Downgrade a couple of warning/notice messages in FindPeaks to 'debug' level

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#12807]
These two messages:
- https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/Algorithms/src/FindPeaks.cpp#L378
- https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/Algorithms/src/FindPeaks.cpp#L1471-L1473

Will show up when you run algorithms that use FindPeaks, like EnginXCalibrate for example. They should be 'debug' level. Also, check the messages logged by FindPeaks in general and make sure that there're no other too loud logs about details of the fitting.

This is 'blocked by'
- [ ] #12686

(See also #806, where this was spotted from unrelated work on EnginXCalibrate).

**Comment by peterfpeterson** [comment]
There is the middle ground of `information`, but debug doesn't seem like a crazy choice.
