### ISSUE TITLE
LoadShape algorithm

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12828]
Create an algorithm that will load an STL sample geometry file and assign that geometry to the sample, or any named instrument component.

Example algorithm Dialog:

![new mockup 1](https://user-images.githubusercontent.com/1017173/34947430-fd282778-fa01-11e7-869d-de9c311cc018.png)

sample files can be found here
http://files.mantidproject.org/videos/StlFiles/

needs
- [x] #12827

**Comment by KarlPalmen** [comment]
The picture appears to be a customized dialog box, which would not arise by default when writing an algorithm. I'll need help about this.

**Comment by KarlPalmen** [comment]
Also, I don't understand the context of the algorithm. Shouldn't a workspace be involved?

**Comment by NickDraper** [comment]
Yes, good point about the workspace, yes it needs a workspace to get the instrument.

**Comment by NickDraper** [comment]
For the enabling / disabling based on another property you can use setPropertySettings.  Take a look at line 107 of ConvertToMD.cp for an example.
