### ISSUE TITLE
Add a keep open option to algorithm dialog boxes

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12835]
Some algorithms would be good to keep the dialog box open to allow it to be rerun.

Look at adding an unobstrusive checkbox to allow this.

**Comment by martyngigg** [comment]
It looks like a ticket was raised a while ago by Russell to look at the multiple algorithm object creation by the proxy - #9480. If you reference that issue and this in the pull request then both will be closed when it is merged.

**Comment by NickDraper** [comment]
closing issue as I am recreating the branch with a cleaner commit

**Comment by NickDraper** [comment]
whoops meant to close the pull request, not the issue - reopened
