### ISSUE TITLE
Reduce memory requirements for MDNormSCD

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#12862]
For diffuse scattering, a fine grid and many runs are needed to see the diffuse structures.  MDNormSCD runs out of memory on the analysis clusters and is killed when running for a group of runs and a fine grid.
   runs=range(11892,11910)

    a,b=MDNormSCD(InputWorkspace=md,FluxWorkspace=flux,SolidAngleWorkspace=sa,
        AlignedDim0="[H,0,0],-5.005,5.005,2001",
        AlignedDim1="[0,K,0],-5.005,5.005,2001",
        AlignedDim2="[0,0,L],-20.05,20.05,401")

**Comment by AndreiSavici** [comment]
There is nothing to fix in MDNormSCD. The user creates a lot of output workspaces that are very large. The solution is to create fewer workspaces, and reuse them: write a `for` loop and accumulate the data and normalization.
