### ISSUE TITLE
Determine bounding box dimensions

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#12933]
issue #12932 requires we set a bounding box in terms of the model units. @AndreiSavici agreed to check the units of the min and max dimensions reported by MDHistoWorkspace and how they relate the the ChangeOfBasisMatrix.

**Comment by AndreiSavici** [comment]
I have tested multiple scenarios, and for the MDHistograms almost all look fine. Did not work for MDEvents.
* HKL no projections in HKL units
* HKL no projection in A^-1
* HKL with projection vectors in A^-1 and HKL
* Q_sample with and without projection
The Q_sample does not print label
