### ISSUE TITLE
PABLV: Make it possible to set the last run to 'Auto'

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#12966]
Make it possible to set last_run to "Auto" in PlotAsymmetryByLogValue (PABLV) algorithm. This will make the algorithm to observe changes in the directory of the first_run and append any new files to the data set. This new functionality can then be added to the ALC interface as well.

This issue is blocking #10057

**Comment by raquelalvarezbanos** [comment]
This option was added to the ALC interface. It does not make sense to add it in the algorithm I believe.

**Comment by NickDraper** [comment]
agreed
