### ISSUE TITLE
FindPeaksMD Performance Problems

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12967]
There has been a huge drop in the performance since v3.4 of Mantid for the FindPeaksMD algorithm. I just ran [this]( https://github.com/mantidproject/mantid/blob/master/Code/Mantid/scripts/Vates/SXD_NaCl.py) on a build from master and the FindPeaksMD step took **30 seconds** I downloaded version 3.4 and the same algorithm took only **0.5 seconds** to run.

1. Fix the x60 decrease in performance. 
1. Add Performance tests to this algorithm so that we can spot any future regressions.

My testing was done on OSX 10.10

**Comment by peterfpeterson** [comment]
This is a duplicate of #12713.

**Comment by peterfpeterson** [comment]
[This logging statement](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/MDAlgorithms/src/FindPeaksMD.cpp#L165) calls a bit of code in `Instrument` that explicitly mentions it is slow.

**Comment by OwenArnold** [comment]
@peterfpeterson: For the record, we discussed this, and don't think this is a duplicate of #12713 as the comment above suggests.

**Comment by OwenArnold** [comment]
Already merged
