### ISSUE TITLE
WorkspaceSingleValue has 0 axes but 2 dimensions

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#12974]
Fix suggested by @OwenArnold: override `getNumDims()` to return 0.

**Comment by OwenArnold** [comment]
Another solution that doesn't involve further overriding would be to make getNDims call this https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/API/src/MatrixWorkspace.cpp#L833

Just a suggestion.

**Comment by SimonHeybrock** [comment]
You said dimensions is the more generic way and axes is more a relic from the pre-IMDWorkspace times, so maybe we should not use that feature in case someone ever finds the time to unify the interface. I think I'll go with your original suggestion.
