### ISSUE TITLE
Engg (EnggUtils): take bank numbers from grouping file

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13052]
At the moment this is being used for EnginX only and everything is hardcoded. In EnggUtils, get the numbers 1, 2... from the Grouping file. The aliases 'Nort' and 'South' would be associated by default to 1 and 2 for EnginX.

It looks like later on we will be adding group 3 as a "texture" group in EnginX, and possibly more.

(Also: change that part of the code towards a more general treatment of detector groups, so that it is more or less ready for other instruments: the instrument should be guessed from the workspace whenever possible). Beware that the naming conventions of grouping files seem to be instrument dependent: ENGINX_Grouping.xml, CHRONUS_Detector_Grouping_LF_608.xml, etc.

**Comment by FedeMPouzols** [comment]
@DavidFair, @DimitarTasev: this will be needed for other instruments to work well. We might get lucky because the next one in the queue (IMAT) will also have two diffraction banks. in principle 
But you see that the code is currently NOT doing the right thing. Much of the code in `EnggUtils` come from very early versions of the Engg system, keep your eyes open, as not all of `EnggUtils` needs to be in there but could be better integrated with the algorithms.

**Comment by DimitarTasev** [comment]
Closed via https://github.com/mantidproject/mantid/issues/17999
