### ISSUE TITLE
Cannot revert to default colour map after selecting custom one for colour fill plot.

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#13055]
Once selecting a custom colour map to use on a Colour Fill plot and applying,I then try to revert back to default colour map for my plot and mantid still uses the custom colour map that I had previously chosen.

**Comment by ElliotAOram** [comment]
Issue seems to have been resolved in Mantid version 3.4 or higher.

**Comment by NickDraper** [comment]
agreed
