### ISSUE TITLE
SystemTest for PlotAsymmetryByLogValue

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#13072]
It should include a test of the ability of PlotAsymmetryByLogValue to skip a missing file, which was implemented in ticket http://trac.mantidproject.org/mantid/ticket/11624.

**Comment by tom-perkins** [comment]
Linked: refactoring PABLV for testing #13152

**Comment by tom-perkins** [comment]
Linked: unit test for skipping missing file #12469
