### ISSUE TITLE
PredictFractionalPeaks dialog does remember previous settings

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#13119]
Reported by Pascal.

**Comment by OwenArnold** [comment]
Here's how you reproduce this: 
1) Make sure your managed user directories in Mantid point to the ExternalData/Testing/Data/DocTest
2) Run the following Code in MantidPlot:
```python
peaks = LoadIsawPeaks("TOPAZ_3007.peaks")
LoadIsawUB(peaks,"TOPAZ_3007.mat")
IndexPeaks(peaks)
```
3) Open PredictFractionalPeaks
4) Set the OutputWorkspace to predicted
5) Set the HOffset to -0.5,0,0.1
6) Run the algorithm
7) Open the PredictFractionalPeaks dialog and the HOffset property has been reset back to -0.5,0,0.5, not the -0.5,0,0.1 you last had!

We think that you should debug here https://github.com/mantidproject/mantid/blob/master/Code/Mantid/MantidQt/API/src/AlgorithmDialog.cpp#L172 to find out why the array property is not being remembered.
