### ISSUE TITLE
Create documentation for HFIR powder reduction GUI

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#13137]
Initialize a document for developer and instrument scientist.  
The reduction procedure should be illustrated, especially about how V-corr file is correctly applied in the workflow.

**Comment by NickDraper** [comment]
is this still current?

**Comment by wdzhou** [comment]
The documentation has been written and published.  FYI http://docs.mantidproject.org/nightly/interfaces/HFIRPowderReduction.html.

Issue is thus closed.
