### ISSUE TITLE
Better documentation for sample transmission calculator

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13153]
The documentation does not accurately describe that the parameters are per atom.

**Comment by SpencerHowells** [comment]
All parameters should be per atom. So calculated cross-sections from SetSampelMaterial should be per atom - this is not mentioned any more on the wiki page. The number density must therefore also be per atom.

**Comment by DanNixon** [comment]
@SpencerHowells Indeed, I think there just needs to be more documentation for this, and the unit for number density on the UI changed to match the documentation.
