### ISSUE TITLE
Find Possible Bad Defaults

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13156]
Leading on from #13119 lets have a look to see if there's any other algorithm usage which could be getting this wrong.

* As a temporary change make the ArrayProperty constructor that takes the string as the second argument private.
* Make a temporary named static convenience creational method on ArrayProperty with the same arguments as the destructor you just made private. (see Owen if you don't understand this)
* Compile mantid. This will not go well.
* Where the compiler breaks on usage of the old constructor, replace the usage with the new convenience creational method. Record where it broke.
* Repeat the previous step until mantid now fully compiles again.
* Report the list here.

**Comment by MattKing06** [comment]
I have created a more general fix for this issue in PR #13223. Creating a new a constructor in PropertyWithValue that now populates a vector with the values from a string.
