### ISSUE TITLE
SaveNXSPE does not produces correct detectors for MAPS, rings map

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#13171]
If MAPS reduces data using powder rings, (parker rings for maps), the combined detectors positions saved to nxspe file are incorrect. 
See image provided here:
 ![Invalid Maps Detectors](https://github.com/abuts/Fe/blob/master/bugs/MapsPowderBug.png), 
where right is correct image and left -- the image with detectors, produced by SaveNXSPE algorithm.

Sample NXSPE file, correct phx file with correct detectors positions and script used for reducing data to produce this nxspe file together with auxiliary information necessary for reduction can be downloaded from here:
ftp://ftp.nd.rl.ac.uk/scratch/abuts/Issue_13071/

The source data file itself should be downloaded from ISIS archive (MAPS/cycle_15_1)

**Comment by AndreiSavici** [comment]
For powder pattern you should use ```GenerateGroupingPowder```. It produces a map file and a par file. Use the par file in ```SaveNXSPE```

**Comment by abuts** [comment]
We are investigating -- the problem apparently not in SaveNXSPE -- something to to with 4-1 map changes. Need to identify when and why it have happened. Couple of experiments clearly need to be reprocessed.
I am taking this ticket and it will probably be invalid.

**Comment by abuts** [comment]
We investigated the issue and realized that it arises due to incorrect ring map (built on 4-to-1 processed file rather then the file, obtained from instrument). As such the issue have nothing to do with Mantid.
