### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13244]
https://github.com/mantidproject/mantid/blob/master/CONTRIBUTING.md looks outdated:

- it says "Some comments are part of the build server infrastructure (e.g. 'test this please')"
- it suggests as first step to fork the repository. Is this really what we mean?

**Comment by stuartcampbell** [comment]
Regarding forking the repo, yes that is indeed what we want people to do.  Basically, fork then submit pull requests.

**Comment by FedeMPouzols** [comment]
Does that include "external contributors"? At the moment I think it is not happening in practice.
