### ISSUE TITLE
When invoking Mantid using the -x flag, hide the script editor

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13270]
In the scripting window the script editing window can be hidden by dragging the bar separating it from the  output to the top of the window, it would be nice if this was the default view when Mantid is launched with a Python script via the `-x` flag since the output is usually what you would care about here rather than editing (or even viewing) the script.

**Comment by DanNixon** [comment]
Or at the very least the position of the split should be persisted in the Qt settings.

**Comment by NickDraper** [comment]
The split position persistance is the thing we should do here - changed the title
