### ISSUE TITLE
ConvFit plotted workspaces display wrong Y axis label

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13288]
From Ian Silverwood:

> If I plot results workspace from fitting (this is from convfit of multiple data sets), the y axis always displays as f1.f1.f0.Height, regardless of what is being plotted.

**Comment by DanNixon** [comment]
In fact this is just an error with plotting in general, even if you have the `_Results` workspace and just plot a single spectrum from it you still get the incorrect label.

**Comment by ElliotAOram** [comment]
This is a problem with the way units are held in a MatrixWorkspace. In order to properly fix this it will require a design proposal to be written for changing where units are stored in workspaces.
