### ISSUE TITLE
Improve error message when retrieve() fails to find a workspace in the ADS

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#13293]
This is one of the places where you can get an obscure exception message like
`Data Object search object peaks`  (when you try to retrieve a workspace by name: `peaks` but it doesn't exist.

This must be a `throw NotFoundError/NotFoundException` or similar in `AnalysisDataService::retrieve(std::string )`.

Try to give a more informative message!

**Comment by FedeMPouzols** [comment]
Forgot this note: what took us to this exception was `InstrumentWindow::overlay()` used on an invalid workspace name from a Python script..
