### ISSUE TITLE
LoadVesuvio cannot be loaded by MantidPlot

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#13309]
Starting MantidPlot now gives me a warning stating:
```
Failed to load plugin /mnt/data1/source/github/mantidproject/mantid/Code/Mantid/Framework/PythonInterface/plugins/algorithms/LoadVesuvio.py. Error: No module named LoadEmptyVesuvio
```

It's not clear why it can't find it as it is in the same directory.

**Comment by DanNixon** [comment]
On what platform, there is no error on Ubuntu for me.

**Comment by martyngigg** [comment]
This was Ubuntu too - maybe it's my setup. I'll look a little closer.

**Comment by DanNixon** [comment]
But I do get it on RHEL 6.

**Comment by DanNixon** [comment]
I can't see why this is happening. The easiest thing I can think of that will fix it is adding the path to the algorithm directories to the Python path when Mantid is launched.

**Comment by martyngigg** [comment]
I can't either. It should be adding the directory already while it starts up so that they are all importable

**Comment by DanNixon** [comment]
I'm starting to wonder if this is caused by something else, as the systemtests for the PR and nightly since you passed my PR making the change to `LoadVesuvio` have passed until 03/08, now the Vesuvio tests all fail with the same error.

**Comment by martyngigg** [comment]
Yes, that is odd. Something must have affected the path at start up

**Comment by martyngigg** [comment]
Looking closer I'm not sure the path is now affected on startup. We use the `imp` module to load the filepath directly to avoid the need to search. This may be the problem. Although it doesn't explain why it did work...

**Comment by DanNixon** [comment]
I'm guessing the difference between 2.6 and 2.7 somehow, since the only platform this seems to fail on (at least according to the systemtests) is RHEL6.

**Comment by martyngigg** [comment]
I'm on Ubuntu though and I still see the same issue

**Comment by martyngigg** [comment]
This is strange. On my machine the order that the python plugins are loaded is different to the Ubuntu build server even though the are exactly the same versions of Python. On the builder `LoadEmptyVesuvio` is loaded first and then when `LoadVesuvio` comes around it already has `LoadEmptyVesuvio` in `sys.modules` so there is nothing to do.

On my machine and the RHEL6 builder `LoadVesuvio` is loaded first and fails to find `LoadEmptyVesuvio` because the plugin directory is not on the path. There's no real reason why the plugin directory is not added to the path so I'll do that.
