### ISSUE TITLE
Add Fit systemtest

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#13348]
Add further Fit systemtest to expose the level of fitting we want to support within Mantid. This is systemtests in addition to those already provided by specific instrument workflows, i.e. generic systemtest of the kind provided already provided by `UnweightedLeastSquaresTest.py`. 

Here suggest to do this in systemtest `WeightedLeastSquaresTest.py` to complement those in `UnweightedLeastSquaresTest.py`

Either test in these two systemtests may also include not-happy path examples, i.e. example where fitting current is not supported

**Comment by MichaelWedel** [comment]
When I added the unweighted least squares cost function Roman pointed out to me that NIST has a kind of test suite for non-linear least squares codes. I implemented some of them in `UnweightedLeastSquaresTest.py`, checking values and errors. Maybe more of the NIST examples could be added as well?

**Comment by Anders-Markvardsen** [comment]
@MichaelWedel thanks for pointing this out

**Comment by Anders-Markvardsen** [comment]
Looking at this in more detail there are in addition to UnweightedLeastSquaresTest.py many instrument specific systemtests using fitting. As expected most of these are not calling Fit directly (an exception being VesuvioFittingTest.py). 

A suggestion is for this issue to add a WeightedLeastSquaresTest.py which try to expose the general level by which we would like to support weighted least squares fitting in Mantid. This systemtest will complement UnweightedLeastSquaresTest.py. These two systemtests could also be a place where we could add fitting examples which we would like to support but correctly don't.
