### ISSUE TITLE
Test the mediawiki doctests nightly

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#13355]
issue #13310 an pull request #13311 added doctests for mediawiki pages

This is to add them to the ?nightly automated build

It involves running the script 
``` 
python.exe TestWikiPython.py -o C:\Mantid\Code\Mantid\docs\source\mwTests
```

and then running the doctests job as normal.the path in C:\Mantid\Code\Mantid\docs\source\mwTests must be within the source directories of the sphinx help, but does not need to exist in advance.

Feel free to move the TestWikiPython.py script to another location if it makes more sense for it to be there, it is a standalone script, and should be ignorant of it's location.

The build servers will need there HTTP_Proxy environment setting set if necessary to get a network connection out to the mediawiki site.

**Comment by NickDraper** [comment]
@FedeMPouzols This might be a good intro task to get to know more of the build infrastructure.

**Comment by FedeMPouzols** [comment]
The plan is to add this command at the beginning of the *nightly* doctest builds so the special doctests added by `TestWikiPython.py` run together with the standard doctests.

**Comment by NickDraper** [comment]
Sounds good
