### ISSUE TITLE
Engg algorithms and GUI: miscellaneous additions and improvements

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13376]
Following on #13370, add/change the following in the Engg GUI (which might require small changes to the algorithms too):

- Add in the GUI settings tab a choice between
   - Use ceria peaks (with a lineedit displaying the peaks or the peaks file name)
   - Use custom peaks (also with the peaks / filename shown)

- - [X] #13853- In the GUI use the MWRun widget instead of raw numbers, all throughout.

- Make sure that the behavior of the algorithms is consistently: "ignore peaks out of range"

- Use some (first time) default folders - and create them if not found:
 - `C:\EnginX_Mantid\Calibration`
 - `C:\EnginX_Mantid\Data`
 - `C:\EnginX_Mantid\User`
 - `C:\EnginX_Mantid\User\<RBNumber>\Calibration` (where all the files that go to `C:\EnginX_Mantid\Calibration` for a particular user/RBNumber should also go.)

**Comment by shahrozahmed1** [comment]
This is has been fixed #14186, thus it can be closed.
