### ISSUE TITLE
Minimum width of algorithm browser widget is larger than it should be

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13372]
The minimum width is taken from that of the contents of the drop down menu which is now much larger that the aliases are also in there.

**Comment by DimitarTasev** [comment]
@DanNixon @NickDraper 
I have tried to replicate the issue and this is the result
![screenshot_1](https://cloud.githubusercontent.com/assets/9135965/16949979/c169b750-4db5-11e6-84da-6a4f1db0dbd5.png)

In the code [that initialises the Algorithm Browser Widget](https://github.com/mantidproject/mantid/blob/master/MantidQt/MantidWidgets/src/AlgorithmSelectorWidget.cpp#L35) there are no policies/settings for the width, and I think the algorithms browser wouldn't be very useful if it could get any smaller.

If you meant a different part/problem could you please direct me to it?

**Comment by DanNixon** [comment]
@DimitarTasev I'll try a new build and check, it's an old issue so it may not be applicable anymore (there may be a difference between platforms too as I only use Linux).
