### ISSUE TITLE
Add QENS peaks to CreateSampleWorkspace

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13383]
Add two additional default peak types; one for standard QENS, one for QENS with tunnelling side peaks.

**Comment by stuartcampbell** [comment]
Just wondering, do you have any more details on what a 'standard QENS' function actually is ?

**Comment by DanNixon** [comment]
The function I would have used for this is:
```
name=Lorentzian,FWHM=0.3,PeakCentre=$PC5$,Amplitude=0.8;name=Lorentzian,FWHM=0.1,PeakCentre=$PC5$,Amplitude=1;name=LinearBackground,A0=0.1
```

I agree defining a "standard" may be difficult, the main reason for the issue is to add the tunnelling example, the other I just want to add so I don't have to have the function defined in multiple tests that I want to replace the file loading in.
