### ISSUE TITLE
Change ask for help / question links to point to forum

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#13399]
This will cover both the application and the website.

All help will be provided by the forum from the next release; so the links need to direct people to forum.mantidproject.org.

App:
Help menu links

Website:
"Contact Us" link

**Comment by stuartcampbell** [comment]
Are we still going to list the email address as well?

**Comment by NickDraper** [comment]
Unless we can get the email to post to discourse then I'd like to stop advertising it.

Of course we will not get rid of it for quite some time, as people will remember it, and we don't want to lose and requests for help.
