### ISSUE TITLE
MDBoxBase incomplete copy constructor.

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#13397]
The copy constructor of `MDBoxBase` sets new extents, but does not call `calcVolume()`. I am pretty sure it should (and even the Doxygen comment claims that it should).

Add unit test that exposes bug, fix the bug.

**Comment by davidfair** [comment]
@SimonHeybrock I've looked into this issue, currently it copies the value computed by `calcVolume()` into `m_inverseVolume` which is copied into the new object. 
Is it worth recalculating this value on the new object or just copying the value as the array it is calculated from is also copied?

**Comment by SimonHeybrock** [comment]
@DavidFair You are right, I must have overlooked that, thanks for pointing it out. I am closing this then.
