### ISSUE TITLE
ISIS powder diffraction: instruments other than HRPD

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13409]
The examples provided with the scripts use HRPD files. That should be enough for a start (for example for #13405 and #13407).

Will they work also with GEM and POLARIS and PEARL, without errors/warnings?

If the answer is yes, then there should be additional test cases, for example as part of #13407, or extending it.

We need to get these in use and agreed for each of the intrsuments

**Comment by SpencerHowells** [comment]
The OSIRIS high angle detector bank also does powder diffraction

**Comment by stuartcampbell** [comment]
And an expertly designed detector bank it is! :smile:

**Comment by FedeMPouzols** [comment]
@SpencerHowells , @stuartcampbell : thanks for your feedback. Are the "Aziz scripts" used for that expertly designed bank of OSIRIS?

**Comment by stuartcampbell** [comment]
@FedeMPouzols @SpencerHowells I thought that there was some special indirect diffraction scripts - or at least that was how it used to be (Sp will know better).  Here we are going to try using the standard powder diffraction routines for our diffraction banks on indirect instruments.  Also don't forget that there are diffraction banks on IRIS as well - They don't get dedicated experiments, but probably should be processed the same way.

**Comment by DanNixon** [comment]
@stuartcampbell OSIRIS has it's own diffraction reduction that does vanadium corrections similar to other diffraction reduction workflows (AFAIK).

There is a general purpose indirect diffraction script but it is rarely used on OSIRIS. IRIS and TOSCA (and VESUVIO) just use the general purpose one.

@FedeMPouzols Maybe it would be worth talking to Sanghamitra about OSIRIS, she had a few issues with the current reduction workflow that she mentioned a while ago.

**Comment by FedeMPouzols** [comment]
So  @SpencerHowells and @DanNixon would like to have OSIRIS support. @DanNixon says "there is a difference in that to have the large d-range of other diffractometers you need to change wavelength on OSIRIS, hence multiple runs must be used for a single experiment". When we get to this, check the details with Franz Demmel.

**Comment by SpencerHowells** [comment]
VESUVIO will also want to do diffraction analysis.

**Comment by FedeMPouzols** [comment]
Scripts for PEARL are now included for v3.7: http://docs.mantidproject.org/nightly/api/python/techniques/PearlPowderDiffractionISIS-v1.html

**Comment by DavidFair** [comment]
@FedeMPouzols Is this issue still applicable or can it be closed?

**Comment by DavidFair** [comment]
This issue can be closed as the migration of various instruments is being tracked in #17831
