### ISSUE TITLE
ScriptWindow + Console MantidPlot launch

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13417]
We have a minor usability issue with the new changes. This occurs when you launch MantidPlot with an argument for the path of a script to open.

* Run MantidPlot like so ```MantidPlot.app/Contents/MacOS/MantidPlot {path_to_script}```
* MantidPlot opens with the ScriptWindow populated with the script set in {path_to_script}
* Now close MantidPlot
* Now run MantidPlot using the same first command again
* Now the script window has opened with two tabs pointing to the same script. 

I think there should be unique check on the paths for each script in the script window upon open. I think what's happening is that the new mechanism is living independently from the old console launch options.

**Comment by ElliotAOram** [comment]
@OwenArnold Do you know if this is MacOS specific, I can't seem to reproduce on Windows.
Regardless I agree that a check for unique file paths is a good idea!

**Comment by OwenArnold** [comment]
You're right, this doesn't happen on Windows
