### ISSUE TITLE
Add Dynamic PDF reduction algorithm

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#13438]
Add the DPDF reduction algorithm that has been developed into Mantid.

**Comment by stuartcampbell** [comment]
@jmborr If you don't have time, then if you give me all the stuff I can do this.

**Comment by jmborr** [comment]
@stuartcampbell  Get the python algorithm from [here](https://www.dropbox.com/s/nc0wj24h7yhr9nk/DPDFreduction.py?dl=0)

**Comment by stuartcampbell** [comment]
@jmborr Sorry I didn't get chance to do this - do you have time to do it now or would you still like me to ?

**Comment by jmborr** [comment]
I still would like you to do it, but let me know if you can't
