### ISSUE TITLE
LoadEventNexus cannot load the first spectra from a file

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#13457]
When loading a range of spectra with `LoadEventNexus`, select `SpectrumMin` and `SpectrumMax` values. If `SpectrumMin` is less than the number of monitors, you get an error message (`some of the selected spectra correspond to monitors`). This seems to happen regardless of the actual spectrum ID of the monitors.

As a consequence, it is impossible to load the first `n_monitor` spectra when selecting a range of spectra.

**Comment by NickDraper** [comment]
This is probably a clash in the seperation of the monitors to another workspace that occurs with LoadeventNexus.  However as it is not needed for any workflow at the SNS at present I'm going to archive this issue.
