### ISSUE TITLE
Calculate S(Q, w) from CASTEP

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13455]
This should use the method used by aClimax ("a-CLIMAX: a new INS analysis tool", Champion et al) for INS.

**Comment by DanNixon** [comment]
@ElliotAOram This should be pretty much working.

The only issue was a couple of Hydrogen peaks <500cm-1 being higher than they should be.

This is an effect of the peak broadening and is entirely expected given the way the peaks are broadened as a function of energy.

**Comment by martyngigg** [comment]
Closing old issue. This is in and verified and other work n Abins is continuing.
