### ISSUE TITLE
Imaging GUI: add enable ticks for saving files in the filters tab/Pre-/post-processing widget

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13469]
Ticks for the multiple options to save, as defined in  #13468. Include also options to give names and destination location, with sensible defaults

Under the main stack directory:

```
pre_filters/  sinograms/
              median_filter/
              roi/
              normalized/
...
```

When Savu becomes available we should consider using the names of the Savu plugins.

As in general with the tomo tool scripts, keep the default to save outputs as individual tiff files per slice.

Depends on #13468, #12809.

**Comment by DimitarTasev** [comment]
Closed via #19124 *All other issues concerning the Tomography GUI are now invalidated.*
