### ISSUE TITLE
LoadEventNexus interprets spectrum index as detector ID

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#13475]
`LoadEventNexus` has the optional `SpectrumMin`, `SpectrumMax`, and `SpectrumList` properties. For ISIS files this is really the spectrum (but there are other issues, see #13456 and #13457). For non-ISIS files, however, this is interpreted as the *detector ID*. This may be the desired behavior, but the documentation and GUI should be fixed.

**Comment by NickDraper** [comment]
For the SNS they do not have a concept of a spectrum ID (as they never group detectors in hardware), therefore the detector id does map to spectrum ID.

**Comment by NickDraper** [comment]
rst page updated (and mistakenly submitted directly to master using a key combination I was not aware of)

https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/LoadEventNexus-v1.rst

**Comment by SimonHeybrock** [comment]
@NickDraper Did you also update the GUI (field names and tool tips)?

**Comment by SimonHeybrock** [comment]
I will reopen this until it is fixed. This is also part of the 'spectrum number' cleanup.

**Comment by NickDraper** [comment]
Spectrum index is a valid concept in nexus files, and does map to those two concepts in this case.
