### ISSUE TITLE
Engg GUI: add support for saving OpenGenie ascii his files

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13488]
Nobody seems to know or remember this `his` format which I understand is just a binary dump of histogram data (with maybe? 2/3 data columns), similar to what is produced by `SaveGSS` and `SaveFocusedXYE`.

There would be alternatives or workarounds but if this turns out to be doable it will be convenient for interfacing with legacy OpenGenie routines.

**Comment by FedeMPouzols** [comment]
Ah ok, this clarifies a bit how they write these `his` files: https://github.com/stuartcampbell/opengenie-scripts/blob/master/ENGIN/FOCUS25.COM

**Comment by FedeMPouzols** [comment]
And there's definitely a solution for this. Saurabh just sent me an email: there's an ascii format of the 'his' files that the ENGIN-X OpenGenie scripts can load. That should be enough. It could become an algorithm `SaveFocusedOpenGenieAscii`.

**Comment by FedeMPouzols** [comment]
Renaming this from `Engg: figure out if/how to write focused data into OpenGenie 'his' files` to `Engg GUI: add support for saving OpenGenie ascii his files`.

**Comment by FedeMPouzols** [comment]
Reopening as this seems to have been closed from #13452 which is unrelated.

**Comment by shahrozahmed1** [comment]
This has been fixed in another issue/PR.
