### ISSUE TITLE
Need a CompactMD algorithm

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13508]
This should be relatively easy to do. All that the compact command does is find the edges where we have the first non-zero data and then will run CutMD to trim the workspace to that size and output it as a new workspace. Ask Owen to explain this further if needed. See the horace documentation for Compact [here](http://horace.isis.rl.ac.uk/Reshaping_etc#compact). This algorithms should work like that.

Caveats:

* Must only work on regular binned input workspaces. Start by assuming the inputs must be IMDHistoWorkspaces
* Should try to maintain the existing bin widths in each dimension as not to distort the data too much.

**Comment by MattKing06** [comment]
This issue is being blocked by #13796 as it uses IntegrateMDHistoWorkspace. Once #13796 has been merged, this algorithm can be developed and tested.

**Comment by OwenArnold** [comment]
@matthew-d-jones You should take a look at this completed algorithm as it falls under the Horace/Mantid/VATES commands.

**Comment by matthew-d-jones** [comment]
@OwenArnold Ok, thanks.
