### ISSUE TITLE
Unexpected units in axis label for I vs Q plots

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#13513]
Loading and processing the example data in the [ISIS Reflectometry documentation](http://docs.mantidproject.org/nightly/interfaces/ISIS_Reflectometry.html) results in "I vs Q" plots with units of A^-1-1 on the y axis.
![ivsqplot](https://cloud.githubusercontent.com/assets/13455433/9522152/008ebf44-4ccb-11e5-8258-fbaae0d12895.png)

**Comment by MattKing06** [comment]
After some investigation, I believe that this is the line causing the YAxis to be incorrectly labelled:
https://github.com/mantidproject/mantid/blob/master/MantidQt/API/src/PlotAxis.cpp#L114
