### ISSUE TITLE
ISIS energy transfer Plot Time not working

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#13527]
Franz reports the Plot Time option is not working, I think the issue is the Numpy type error with integer types.

**Comment by DanNixon** [comment]
@ElliotAOram This works for me, it could be an issue with Windows only (Franz has trouble on the instrument computer and Spencer has often had this problem on his Windows computer).

If you can't get it to fail then ask Franz to show you the failure.

**Comment by ElliotAOram** [comment]
I have been informed by Spencer and Franz that apparently this is no longer an issue. I have tested it myself on windows and can not produce any failures or unexpected results.
