### ISSUE TITLE
Implement a test for the QLines/Quest algorithms

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#13546]
The `QLines` and `Quest` workflow algorithms do not have tests and it has gone undetected that they no longer work.  The [documentation file](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/docs/source/algorithms/QLines-v1.rst) contains a piece of example Python code that should be used as a basis for a unit tests.

It will require #13545 to be fixed first.

**Comment by ElliotAOram** [comment]
Will be closed by #17091
