### ISSUE TITLE
SliceViewer documentation update

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13597]
The slice viewer documentation is [here](http://www.mantidproject.org/MantidPlot:_SliceViewer) on the Wiki. I recently added this feature #13466. To lock the aspect ratios.

1. Update the documentation on the SliceViewer page to reflect this (include images). A new subheading will be needed.
2. Update the release notes to point to the updated SliceViewer documentation.

**Comment by MattKing06** [comment]
[Documentation for SliceViewer with changes](http://www.mantidproject.org/MantidPlot:_SliceViewer#Locking_Aspect_Ratios)
[Release Notes for 3.5](http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes#nD_Visualisation_.28SliceViewer.29)
