### ISSUE TITLE
Fix auto-scale checkbox when switching to MDSlice

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#13606]
Follow up from #13595.

When switching from 1D view with auto-scale checked to an MDSlice view, the auto-scale checkbox is unticked when it should preserve the state between views.

**Comment by picatess** [comment]
The issue arises due to an `endRender` signal of a pqView which is intercepted by the `renderDone` method of the `MdViewerWidget`. 

It is a bit strange that this should only affect the MultiSliceView.

**Comment by picatess** [comment]
The difference occurs here:
https://github.com/Kitware/ParaView/blob/master/ParaViewCore/ServerManager/Core/vtkSMVectorPropertyTemplate.h#L248

In the case of the MultiSliceView the passed in values and the internal values seem to differ. In the other views they are the same. Not clear why, but this is probably again something PV internal. The entire process gets triggered by us setting the RGBPoints in the `colorMapChange` slot
