### ISSUE TITLE
Produce an error in ContainerSubtraction if Container does not have the same binning/energy range 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13609]
Containers should not be subtracted if they have mismatching energy range and/or different binning. There should be an error ensure this does not happen

**Comment by ElliotAOram** [comment]
Adding State Review required to this as this issue should now be solved. If the input files do not match in binning, there is an option to run RebinToWorkspace if the user declines this then the algorithm does not execute.

**Comment by MattKing06** [comment]
This has been fixed, and the functionality is as described in the comment above; so it can be closed.
