### ISSUE TITLE
ResNorm errors with _sqw files as vanadium input

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13620]
ResNorm should not be able to run with _sqw files which it is currently able to do so in the interface. This needs to be removed from the possible extension options.

**Comment by SpencerHowells** [comment]
As an extra check the workspace/file name should also be tested for a _red ending

**Comment by ElliotAOram** [comment]
This issue has been changed to 3.5 from 3.6 as it was not originally expected to be ready for the release but was.
