### ISSUE TITLE
Adding log values to a plot with the text tool need improving

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#13624]
Problems:

1. It takes a long time to generate the list of logs to display (much longer than bringing up the sample logs dialog)
1. Picking a time series log print each time step value onto the graph (we should give options available from the log statistics)

**Comment by DimitarTasev** [comment]
@NickDraper Can you suggest a way for the Dialogue to handle multiple workspaces imported into a single plot? Currently it is just showing the logs for the first workspace and completely ignores the rest, I am assuming it might be necessary to plot multiple workspaces, the previous context menu just appends all the logs one after another without indicating where one workspace stops and the others begin. 

I can do a similar thing, but it makes it hard to understand, and idea I have is to append the workspace name in a new column at the start, and re-work the loading code. The first column will be saying which workspace it is for the current log, however this might make the table a bit cluttered.
