### ISSUE TITLE
Handling errors produced by invalid input for ISIS SANS Interface

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#13645]
sans_bugfix
**These issues were found during Unscripted Testing**

**Run Numbers Tab**
- [ ] Error produced when trying to save file from 2D reduction to CanSAS format

**Reduction Settings Tab**
- [ ] Error produced when `Extra Length` field has negative input
- [x] Error produced when `Radius` field has negative input
- [x] Error produced when `Wavelength` field has negative input for Logarithmic
- [x] Verify that input is of numerical type for all necessary input

**Geometry Tab**
- [x] **Mantid Crashes when negative value is used for `Thickness` field**
- [x] **Mantid Crashes when negative value is used for `Height` field**
- [x] **Mantid Crashes when negative value is used for `Z-offset` field**

**Comment by picatess** [comment]
Started work on this. How can we hedge against bad values from the User file ?

* Geometry Tab*
* Patching line edit fields with validators
* z-offset should probably allow negative values --> need to investigate further here

**Comment by Mantid-Matthew** [comment]
This issue related to the parsing in the old GUI
