### ISSUE TITLE
Mantid Crash when using Geometry Tab in ISIS SANS

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#13646]
sans_bugfix
**This issue was found during Unscripted Testing**

**To reproduce**:
- Load ISIS SANS interface
- Select `SANS2DTUBES` as instrument
- Load necessary files from `\\olympic\Babylon5\Scratch\Anton\UnscriptedTesting\SANS_Material\SANS2D`
- After Loading, go to Geometry tab and press `Run` button (with Max Iterations = 10)
- After run has started, close SANS interface (Geometry Algorithm should continue)
- Open SANS Interface again and wait for Geometry algorithm to complete
- Once Geometry tab is enabled again, go to Geometry.
- Mantid should crash.

**Comment by AntonPiccardoSelg** [comment]
This will be fixed by #20797 .
