### ISSUE TITLE
Change fileName for raw_filename in logs for indirect

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13648]
**This issue has been raised by Spencer:**

It would be nice to have the log display the original file name as raw_filename rather than the currently used, more ambiguous, filename

**This should be fixed during the beta test period before 3.5**

**Comment by SpencerHowells** [comment]
Mantid style is raw_filename

**Comment by ElliotAOram** [comment]
Thanks @SpencerHowells just updated the description now.
