### ISSUE TITLE
Move MuonAnalysis documentation to mantid help system

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#13644]
Move the content of the wiki pages: http://www.mantidproject.org/MuonAnalysis to a new .rst file.

Also, review and add new functionality/improvements added to the interface that is not included there.

**Comment by tom-perkins** [comment]
As part of this, the link on http://www.mantidproject.org/Muon pointing to the MuonAnalysis wiki pages will need to be changed.

**Comment by tom-perkins** [comment]
#11731 can be done as part of this issue

**Comment by tom-perkins** [comment]
Increasing priority because the documentation will need to be updated when the changes from 
#15518 are merged in. Those updates can be combined with converting the documentation to rst format.

**Comment by raquelalvarezbanos** [comment]
@tom-perkins: I've created an issue https://github.com/mantidproject/mantid/issues/17119 to update the links once PR https://github.com/mantidproject/mantid/pull/17118 is merged and we have a new nightly build.
