### ISSUE TITLE
Error caused when switching instrument in Indirect Data Reduction Diagnostic

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13656]
If you run Diagnostics for a particular run on a particular instrument eg. 21360 on IRIS, if you then switch instrument to say OSIRIS, this will produce an error. It is unlikely that this will be done very often but should still be addressed.

**Comment by SpencerHowells** [comment]
I think this is because it runs immediately you do something. When the instrument is changed it tries to run using the existing run number. Remove the immediate running and just run when Run is clicked..
