### ISSUE TITLE
ISIS Reflectometry GUI options need documentation update

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#13663]
This was discovered when following the testing instructions for unscripted testing for the Reflectometry GUI on Ubuntu 14.04.

Compared to the documentation on the [Wiki](http://www.mantidproject.org/ISIS_Reflectometry_GUI#Options_Dialog), the "Options" dialog of the ISIS Reflectometry interface has different options now, the documentation should be updated regarding what these options mean. Screenshot of the dialog as found in the unscripted testing:

![01_isis_reflectometry_options_dialog](https://cloud.githubusercontent.com/assets/6361996/9907463/93213e62-5c8f-11e5-918e-bd8dfc3459d3.png)

Also, the first option was now checked by default, while the testing guide mentions it should not be checked.

**Comment by OwenArnold** [comment]
Updated documentation [here](http://www.mantidproject.org/ISIS_Reflectometry_GUI#Options_Dialog)

**Comment by MichaelWedel** [comment]
Updated documentation explains new options. Screenshot is still the original one, but since you mentioned that this interface is probably going to be deprecated it's not urgent/necessary to replace it.
