### ISSUE TITLE
Reducer for Bilby

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13739]
sans_bilby
Create a reducer for ANSTO bilby

**Comment by OwenArnold** [comment]
@AntonPiccardoSelg I don't expect much to happen with this

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew  This is a reduction system that was written for ANSTO and is still being developed. If you ever have to do work in this direction, speak to Owen and Nick

**Comment by gemmaguest** [comment]
Closing as they now have a reduction algorithm BilbySANSDataProcessor
