### ISSUE TITLE
ISIS Energy Transfer Loading Logs validation

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13746]
# Warning on loadLog

When loading in certain `.RAW` files in ISIS Energy Transfer the log  files are seemingly loaded correctly but produce a warning regardless that states:

"_You've passed a property (LoadLogFiles) to Load() that doesn't apply to this file type.
When trying to find the range of monitor spectra: non-consequent monitor ID-s in the monitor block. Unexpected situation for the loader_"

If it is the case that the log is loaded correctly, this error message should be suppressed. Otherwise it should fixed.

The current run numbers known to be producing this error are:
- 53664 (IRIS_graphite002)
- 55215 (IRIS_graphite002)
# Dialog box for 'Log not found'

When the logs for a run are not found, it produces a warning in the result Log. This can easily be missed with a low enough level of result log printing or if many runs are being loaded. As such it would be better to produce this warning in a dialog box

**Comment by SpencerHowells** [comment]
Also need the message when a log file is not found to be in a window rather than in the Results Log pane which the user will miss.
