### ISSUE TITLE
Multi-dataset fitting interface: editing local parameter values.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#13777]
Blocks #11929.

7. In the “Edit parameter values” pop up window where a parameter isn’t global, Tab steps from one box to another in left-right order so it’s necessary to press Tab twice in between values, if filling them all in. Return exits the dialog (instead of going to the next parameter as in the main window). Down arrow goes to the box below but doesn’t activate it ready for typing in a number.

8. Should it even be possible to select the left column with the fit parameter indices? Would this column be more useful if it showed workspace names and spectrum numbers as in the top right of the main window?

**Comment by abuts** [comment]
The changes do improve usability, though I may suggest number of similar one which  provide similar improvements (e.g. right click on graph behaving like on single fit interface)
But nice step forward.
