### ISSUE TITLE
Engg algorithms and GUI: more additions - save to different formats

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13783]
Following on other required improvements to the Engg GUI: #13376 (most of which if not all should be implemented first). Add these (some of which were left out of #13486):

- [x] #13854. Save focused result as GSAS file, XYE file, and .his (using SaveOpenGenieAscii)

- Make sure to follow the standard/updated ENGINX naming conventions for the output files: similarly as with the calibration files, every focus output should go to a general directory and a user/RBNumber specific directory, defaulting to: `C:\EnginX_Mantid\Focus` and `C:\EnginX_Mantid\User\<RBNumber>\Focus\` - inside both create: `\GSAS`, `XYE`, etc. for the different output formats. These directories are a parallel structure to the `Calibration` directories (see  #13376).

Default (and forced) name of the output focused files:
- `ENGINX_...<RUN_NUMBER>_..._bank_1` `.his`, `.gss`, `.dat`, etc. for banks 1, 2, etc.
- `ENGINX_...<RUN_NUMBER>_..._texture_1` `.his`, `.gss`, `.dat`, etc. for texture (pseudo)banks 1, 2, 3, 4, etc.
- `ENGINX_...<RUN_NUMBER>_..._cropped_1` `.his`, `.gss`, `.dat`, etc.  (where the index is incremented if a file with index 1 already exists, and so on).

**Comment by shahrozahmed1** [comment]
issue fixed under #13934 hence it can be closed
