### ISSUE TITLE
Engg algorithms and GUI: more additions - modes for multi-run focusing

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13784]
Following on other required improvements to the Engg GUI: #13376 (most of which if not all should be implemented first), and other improvements listed in #13783. Add these (which were left out of #13486):

- Combo box for the "multi-run focus mode" when you specify multiple runs. Two alternatives: `focus individual run files separately`, `focus sum of files`. This would improve with the next point:
- Context help to explain the advanced use of the multi-ranges of runs.

Note this requires the MWRun widgets to be added (#13376).

**Comment by shahrozahmed1** [comment]
Note: go first for the sequential multi-run processing, then the "sum of files" option is a lower priority.
For the "sum of files", consider algorithms like for example `Plus` and `MergeRuns`.

**Comment by FedeMPouzols** [comment]
Note: this will require changes in `EnggDiffractionPresenter::plotFocusedWorkspace` which now assumes that you are just plotting banks.

**Comment by FedeMPouzols** [comment]
This is not closed yet...
