### ISSUE TITLE
Event mode 'data viewer'

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#13794]
sans_feature
This issue is inspired by something I saw demonstrated in a presentation at SAS-2015 recently.

The synchrotron community don't have event mode data collection in the same sense that the neutron community do, but they do generate huge multi-frame datasets and it becomes impractical to reduce every frame of every dataset. Consequently, what they have started to develop are uncomplicated graphical displays that give the user an idea of which frames in a dataset have something different happening, for example, by plotting some number that describes the change in the scattering pattern from frame n to frame n+1 as a function of frame number.

Something along these lines, but as a function of run duration, would be a really useful way of probing event mode datasets!

**Comment by gemmaguest** [comment]
We should check whether there is wider interest in this as we could perhaps share resource

**Comment by smk78** [comment]
I hear @rprospero may have developed some scripts for doing something like this.

**Comment by smk78** [comment]
Sarah Rogers (ISIS) is looking into the wider requirements of this with other instrument techniques.
