### ISSUE TITLE
reference to ‘uint64_t’ is ambiguous in LoadFITS.cpp

### ISSUE THREAD

**Issue by leomrtns** [mantidproject/mantid#13802]
Hello, while compiling mantidnightly-3.4.20150918.2040, I found the following error: 
```
/usr/local_src/mantidnightly-3.4.20150918.2040-Source/Framework/DataHandling/src/LoadFITS.cpp:278:8: error: reference to ‘int64_t’ is ambiguous
```

Followed by a complaint about candidates from both include/stdint.h and include/boost/cstdint.hpp . I got the same error for uint64_t.

The issue was easily fixed by prefixing the types with "std::", that is, `std::uint64_t` and `std::int64_t` in this file. 

update (2015.09.30): I forgot to mention that this was on a Ubuntu 15.04 64bits w/ linux kernel 3.19.0-25-generic.

**Comment by FedeMPouzols** [comment]
Hi @leomrtns . Thanks for the report. This hadn't been caught by our build servers. I presume you were compiling with g++ 4.9.x?

**Comment by leomrtns** [comment]
Hi @FedeMPouzols thanks for the prompt action. Yes, I am using g++ 4.9.2. Other than that it compiled smoothly. (I also had to add a few paths by hand to `launch_mantidplot.sh` and change the executable name on it, besides copying `lib/paraview-4.3/` from the stable distribution, but I am sure this is due to some mistake on my part.)
