### ISSUE TITLE
Add a few missing (optional) variables in the files saved by SaveOpenGenieAscii

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13816]
This does not look very high priority, and it may not be needed. In principle the OpenGenie scripts for ENGINX are working well, but just complaining that these fields/variables are not found:

- xunits
- run_no
- spec_no
- title
- ylabel

Some of which are sometimes included in the logs. 

`spec_no` definitely needs to be provided as an optional (default: empty) input property (string type) to `SaveOpenGenieAscii`. It looks like "1201-1400". 

The others could be generated by `SaveOpenGenieAscii` using information from the workspace (or similarly named logs which are often found, like for example "run_number". But if we add these 5 variables that should be enabled/disabled via an input property. The 5 variables seem to be expected by the EnginX scripts in particular but are not always present as log entries in the run files tested.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols Could this possibly be merged to 3.5? as its only small update and could be useful not to have too many errors when you input the file to OpenGenie

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : unless the OG scripts fail without this update I'd be conservative and leave this PR for 3.6. In principle the version that was already merged for 3.5 is already usable, and as there are some last minute issues being fixed right now let's minmize changes and new builds unless absolutely necessary.
The EnginX scientists will be using nightly builds, as there's many updates coming soon. So in the worst case this would just imply a delay of a few days for them.
