### ISSUE TITLE
Ensure Mantid can be used on smaller laptops

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#13818]
See below, 
Some ultra protable laptops have limitied resolution.  
We need to ensure that all dialogs and interfaces can  can at least scale to 768 vertical pixels and display a scroll bar if needed.

----

Greetings:

Using MANTID on a laptop screen with resolution of 1366x768 is nearly impossible because the windows cannot resize smaller than a particular limit which is larger than 768 pixels [vertically] to deal with not having the screen real estate to show all of the available options on a variety of windows or dialog boxes.
As an experimental facilities user, I have a laptop with a smaller screen so that I can easily travel with it and it would be very helpful if there was a provision worked into MANTID that would allow window resizing smaller that what is currently available with the option to scroll within a dialog if the window needs to be resized smaller than the ‘ideal’ size.

I really like how MANTID is developing and would love to be able to transition to use it full time. As it stands right now, it is practically unusable on my laptop and therefore I am not able to use it while running experiments which is less than ideal.

Cheers,

Rick (P.W.) Mengyan, Ph.D.
Research Associate
Texas Tech University, Physics
Rick.Mengyan@TTU.edu / 806.834.0503 (Office)

**Comment by MikeHart85** [comment]
Using this issue to lay the groundwork for adding scrollbars to dialogs and provide an example with StartLiveDataDialog. 

Separate issues will be raised for other dialogs to facilitate testing and resolution of any issues that may come up with individual dialogs.
