### ISSUE TITLE
Indirect Bayes Quasi additional saved files

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13829]
The Quasi interface seems to produce:
 *  `_QLr.lpt`
 *  `_QLr.ql1`
 *  `_QLr.ql2`
 *  `_QLr.ql3`

Files in the save directory even if the `Save Result` option is not checked. It may be the case that this is not wanted however I will check if this is intended with Spencer and remove it if not

**Comment by SpencerHowells** [comment]
These are created by the Fortran program. Not that easy to change. Best to leave as is.

**Comment by ElliotAOram** [comment]
Okay, I thought that might possibly be the case. I'll close this issue.
