### ISSUE TITLE
Improve documentation of outputs from Fit when using multi-domains

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13824]
This is not detailed in the current RST of `Fit`. How do you get the outputs, especially when you're using it from a script? The indices used for the suffixes of the names of the output workspaces start with _0 or _1?
It also seems that the WorkspaceGroup is only created if the output property is assigned?

This could go below the section `Output`, for example a new section/subsection called `Output when fitting multiple functions`.

**Comment by FedeMPouzols** [comment]
A recent change that may be relevant when clarifying how `MultiDomainFunction` works and their capabilities: #16837.

**Comment by NickDraper** [comment]
Resolved by recent PR by anthony Lim adding examples
