### ISSUE TITLE
Fit Dialog: unexpected exception

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#13825]
Fit Dialog seems to be broken. If I add a workspace and a fitting function and click on Run, I get the following error message:

> One or more properties are invalid. The invalid properties are marked with a *, hold your mouse over the * for more information.

But no red star is shown, so there is no way of knowing which of the properties is invalid. If I click OK and hit Run again, the following exception is thrown:

> Sorry, MantidPlot has caught an unexpected exception:
> MultiDomainCreator expected, found class Mantid::CurveFitting:FitMW

I've tried different fitting functions, different datasets, etc, and none of the combinations I tried worked.

**Comment by LamarMoore** [comment]
I was able to get this to work by selecting the workspace MUSR00022725 and using the fit function General->MultiDomainFunction and adding General->ExpDecay. The fit dialog only seems to work with multi-domain functions.
