### ISSUE TITLE
Corrections for images from the MCP detector

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13838]
This is needed for energy selective experiments. Correct the shifts of the sensors/tiles, and the gaps between them. Code examples for how this is done at SNS have been provided by @JeanBilheux.

Requirements (may spawn more issues):
- Having these corrections as an algorithm would be handy.
- Other scripts/algorithms that aggregate energy bands need to use this to generate stacks of corrected images that can be directly passed on to reconstruction scripts.
- We'll also need standalone Python code that implements this for when we run the "many energy bands"=>"single stack" aggregation process on remote machines (SCARF).
- Should work on traditional workspaces and also for the new "Lean" MD workspaces when they become available.

**Comment by FedeMPouzols** [comment]
@DimitarTasev: implementing this requires feedback and some experiments from the instrument scientists.

**Comment by DanNixon** [comment]
This will be done as part of [`mantidimaging`](https://github.com/mantidproject/mantidimaging).
