### ISSUE TITLE
Engg GUI: use the MWRun widget 

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13853]
Spawned from #13367:

- In the GUI use the MWRun widget instead of raw numbers, all throughout.

This affects the Calibration tab (Vanadium and Calibration Sample Run #), and also the Focus tab.
At the same time we might reduce the number of  "Run #" widgets in the Focus tab.

Before implementing this, double-check with Saurabh how many "Run #" there should be in the focus tab.

**Comment by shahrozahmed1** [comment]
issue has been fixed under #13934 thus this can be closed
