### ISSUE TITLE
AddNote may not be right approach

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13867]
Addition of a Note was a user request for the purposes of annotating Workspace History. Take this example. I want to run this in a DataProcessing algorithm:

`ws1 = ws1 - ws1 * a/b`

I can do this using `createChildAlgorithm`, `Multiply`, `Minus` and `Divide` however in the workspace history that's going to look messy and confusing, so I want to annotate it to explain that i'm doing a background correction. Using `AddNote`, I want to leave something that only leaves a note in the workspace history, however AddNote is also creating a Log on the workspace as a side-effect. This isn't what I ideally want. What happens when I inspect the log and find the polluted with these timestamped variables? What do I use for the timestamp? If I choose to make the timestamp dynamically in my script, then run `GenerateIPythonNotebook` my IPython notebook content will be different each time. What happens when I run `CheckWorkspacesMatch` on my outputs, they will not be the same!

I don't think AddNote should be removed, as it can be useful. I just disagree about using this as a way of annotating workspace history. A proper implementation would be an algorithm that would allow the addition of notes and **only** affect the history, and not appear amongst other critical logs, not the sample properties, and should otherwise be ignored when scripts are processed.

**Comment by NickDraper** [comment]
#14042 should deal with a seperate issue that = cannot be used in any algorithm property, or at least if you do History will not work
