### ISSUE TITLE
Problems with FilterEvents UI

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13865]
The ability to FilterEvents via a UI is quite a useful one. Ideally, the FilterEvents UI should be made into a reusable component so that we can use it in other user interfaces and outside of MantidPlot. I'm sure @peterfpeterson would approve of this form of separation as well.

While trying to run this UI, i stumbled across a few basic problems.
- No demo on how this can be used. See SliceViewer documentation. This should be a separate page. @shahrozahmed1  has already provided a general rst documentation source for the UI.
- No vertical scroll bar.
- Fixed scaling so crop out areas of the screen when resizing
- No description of what the plot is on the screen. Presumably this is summing all spectra? What about monitors?
- Browsing/loading doesn't handle soft links on OSX (possibly other platforms too), so cannot use nxs files in the ExternalData directory

**Comment by peterfpeterson** [comment]
It was originally intended to be a reusable UI.
