### ISSUE TITLE
Spline Smoothing incorrect values

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13869]
Spencer reports that the values produced by the Spline Smoothing algorithm are incorrect. He has provided comparison files. With a MaxBreaks of more than ~30 the results are all zero for the data set Spencer provided. 
[derivs_new.pdf](https://github.com/mantidproject/mantid/files/8559/derivs_new.pdf)
[derivs_old.pdf](https://github.com/mantidproject/mantid/files/8560/derivs_old.pdf)

The ideal solution is to have it so that when the max breaks are set to 0, the spline smoothing runs as it did previously before the new implementation.

**Comment by shahrozahmed1** [comment]
![capture](https://cloud.githubusercontent.com/assets/13132173/10642322/04310f56-7815-11e5-9cb6-658494cac547.JPG)
Seems to works well on Mantid 3.4, which means that the changes made recently is the main reason behind this bug
