### ISSUE TITLE
Make extending qtiplot tables easier in python

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#13879]
From James Lord
http://forum.mantidproject.org/t/improvements-for-python-tables-and-plotting/75

Improvements for Python, Tables and Plotting 

2.The table.addRow() function is rather picky about its argument: it only accepts a Dict or a List and rejects a Tuple or a numpy array for example. That goes against the spirit of Python.

**Comment by MikeHart85** [comment]
I've amended addRow() to work with anything that behaves like a Python sequence, so it will now accept tuples and numpy arrays as well. I've also extended the exception handling code a bit to provide more descriptive messages if something goes wrong.

Bear in mind that, unlike lists and tuples, numpy arrays are homogeneous (all of their elements are the same type), whereas a table might have columns with different types. In this case attempting to add a numpy array may still fail. It will only work if the numpy array datatype is compatible with the datatypes of all of the table columns.
