### ISSUE TITLE
"Ask for help" bug on RHEL7

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#13909]
In MantidPlot, when clicking on Help->"Ask for Help", it is supposed to be opening the webpage of the mantid forum. On RHEL7 machines, it opens for a second, then the browser automatically shuts down. If I already have firefox open, a new tab is created, and everything is fine. I saw the same problem if I try to click on Help->Mantid Homepage.

You get the following error:
```
FrameworkManager-[Notice] Welcome to Mantid 3.5.20151007.1831
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
DownloadInstrument-[Notice] All instrument definitions up to date
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
```

**Comment by martyngigg** [comment]
@AndreiSavici Is this still an issue?

**Comment by AndreiSavici** [comment]
It still is

**Comment by martyngigg** [comment]
So it looks like this is a problem when trying to start firefox when using tcmalloc with LD_PRELOAD - https://bugzilla.mozilla.org/show_bug.cgi?id=866791

If I use chrome as the default then everything is okay. I'm not sure how to get around this...

**Comment by martyngigg** [comment]
I can also reproduce this on Ubuntu if I set Firefox as my default browser and launch MantidPlot through `bin/launch_mantidplot.sh`.
