### ISSUE TITLE
Deprecated call in simpleapi.py

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#13911]
In the new release we get this warning that goes into the error channel. That messes up the autoreduction process at SNS
```/opt/Mantid/bin/mantid/simpleapi.py:762: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise RuntimeError(e.message)```

**Comment by martyngigg** [comment]
Does it only come out on the console error channel? I wonder why we have just started seeing this now?

**Comment by martyngigg** [comment]
Duplicate of ~~#14333~~
