### ISSUE TITLE
Handle  -- Error Parsing duration in algorithm history -- Notification when loading data.

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#13936]
Newer data sets show the following warning:
`Error parsing duration in algorithm history entry.`

This appears a lot for SANS data but does appear to be a genuine issue. Martyn has an idea what the cause of this could be. 

To reproduce:
```python
ws = CreateSampleWorkspace()
file_name = "YOUR_PATH_HERE.nxs"
SaveNexus(Filename = file_name, InputWorkspace = ws)
ws_loaded= Load(file_name)
```
You should see the warning appear. It also appears for standard data from the ISIS repositories (generally with newer data).

**Comment by NickDraper** [comment]
The problem appears to be that Save Nexus saves a negative duration for itself in the algorithm History

Algorithm: SaveNexus v1
Execution Date: 2015-Oct-12 16:11:09
Execution Duration: -1 seconds
Parameters:
  Name: InputWorkspace, Value: ws, Default?: No, Direction: Input
  Name: Filename, Value: D:\data\YOUR_PATH_HERE.nxs, Default?: No, Direction: Input
  Name: Title, Value: , Default?: Yes, Direction: Input
  Name: WorkspaceIndexMin, Value: 0, Default?: Yes, Direction: Input
  Name: WorkspaceIndexMax, Value: 2147483647, Default?: Yes, Direction: Input
  Name: WorkspaceIndexList, Value: , Default?: Yes, Direction: Input
  Name: Append, Value: 0, Default?: Yes, Direction: Input
