### ISSUE TITLE
Move Indirect Common functions to GUI interface for Indirect 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13955]
Spencer has asked that the following checking routines be moved to the GUI as they are commonly used.
- [x] CheckXrange
- [x] CheckAnalysers
- [x] CheckHistZero
- [x] CheckHistSame

These are currently called in the algorithms themselves so instead will be required to be refactored out into the validation section of the interface code for algorithms that use them

**Comment by louisemccann** [comment]
Also for IndirectCommon remove unused functions and refactor functions that are only used once or twice
