### ISSUE TITLE
VSI minor bug with Splatter Plot

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#13967]
Try this.
- Run the SXD NaCl script
- Open the QLab workspace in the VSI
- Switch to splatter plot mode
- Overplot the integrated peaks workspace
- Zoom in and then hit the `Reset` view button. You get something like this:
  <img width="728" alt="screen shot 2015-10-14 at 09 54 51" src="https://cloud.githubusercontent.com/assets/1109536/10479090/d0f39bb0-7259-11e5-959e-ffd013057aeb.png">

**Comment by OwenArnold** [comment]
No rush with this. Can be done later on in the iteration.

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.

**Comment by Mantid-Matthew** [comment]
Closing as stale.
