### ISSUE TITLE
Indirect Corrections required Chemical formula on Can Details

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13970]
Currently if you select use can in the CalculatePaalmanPings tab, the Chemical Formula for Can Details does not have a star next to it indicating it is required.

**Comment by SpencerHowells** [comment]
Should read star indicates that value is required

**Comment by SpencerHowells** [comment]
More thoughts: a value is only required of course when there is the can option; Also the Number Densities must be non-zero.
