### ISSUE TITLE
Indirect Corrections new naming convention

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13972]
The naming convention for this was changed incorrectly. Spencer has said that the naming convention for the produced files should be:
ApplyPaalmanPings - irs26176_graphite002_Corrected_26174 (run with correction and can)
CalculatePaalmanPings - irs26176_graphite002_flt_abs

**Comment by SpencerHowells** [comment]
If no can then name is just  irs26176_graphite002_Corrected
