### ISSUE TITLE
ISIS Energy Transfer naming conventions

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13975]
The naming conventions for files produced with ISIS Energy Transfer are not consistent. It should be ensured that when raw files are loaded in, the workspace takes the form of:
`[**full instrument name**] + [run number] + _ + [analyser] + [reflection] + _red`
*This should all be lower case and any leading zeros should be removed*

An example of this would be:
`iris26176_graphite002_red`

Needs to be done for:
* [x] ISIS Energy Transfer
* [x] ISIS Calibration
* [x] Indirect Resolution
* [x] ISIS diagnostics
  * [x] Time Slice

**Comment by SpencerHowells** [comment]
Calib/Res may also need doing.
