### ISSUE TITLE
Input validator fails when workspace groups are used

### ISSUE THREAD

**Issue by mganeva** [mantidproject/mantid#13979]
To reproduce: create a group of workspaces and apply any Python algorithm which uses validators. For example:
ws1 = CreateSampleWorkspace(WorkspaceType="Histogram", NumBanks=1, BankPixelWidth=1, BinWidth=10, Xmax=50)
ws2 = CreateSampleWorkspace(WorkspaceType="Histogram", NumBanks=1, BankPixelWidth=1, BinWidth=10, Xmax=50)
group = GroupWorkspaces([ws1, ws2])
MaskAngle(group, MinAngle=0, MaxAngle=1)

The error message is:
ValueError: Invalid value for property Workspace (Workspace) "group": DataItem "group" is not of the expected type.
  caused by line 754 in '/backup/build/jcns-mantid/installed/bin/mantid/simpleapi.py'
  caused by line 715 in '/backup/build/jcns-mantid/installed/bin/mantid/simpleapi.py'

**Comment by FedeMPouzols** [comment]
At first glimpse this looked like a Python specific issue so I've assigned tentative labels. In principle it works well in C++ algorithms. We'll have to investigate a bit.
