### ISSUE TITLE
Indirect Data Reduction Progress Tracking

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13974]
Several of the algorithms in this tab appear not to have progress tracking:
* [x] ISIS Calibration
  * [x] ISISCalibration.py
  * [x] ISISResolution.py
* [x] ISIS Energy Transfer
* [x] ISIS Diagnostics

**Comment by SpencerHowells** [comment]
Also I(Q,t) and I(Q,t)Fit ?

**Comment by ElliotAOram** [comment]
I'll make a separate issue for those so I can try and keep them bundled in terms of interfaces.
