### ISSUE TITLE
ContainerSubtraction ScaleX and Minus for Shifted peaks

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#13993]
Alexander O'Malley reports:

> When subtracting 'empty' (the empty zeolite) from 'loaded' (dosed with ammonia) there is a negative  peak in the middle of the signal.

> This is not because 'empty' is more intense that 'loaded', but because there is a very small shift in the  peak center. which you can see when you plot groups on top of each other (group 5 shows this quite  well). The step I took was to use ScaleX (adding function to shift the peak along the X axis), and then subtract the shifted peak. however this does not appear to work. Upon using minus, it seems like it takes on the old values of the X axis, so the subtracted graph looks identical.

> This is illustrated best when subtracting the same peak from itself.. which should leave a very 
negative peak when shifted by 0.1 meV. But just gives a flat line, suggesting that something in the 
algorithm only uses one X axis. (even if i save a file and load it in as a new file the minus function still  ignores it..)

> Is there anything possible to change so I can subtract a shifted peak? 

This can be fixed with the following: 
* [x] Add a shift option to the ContainerSubtraction interface.
* [x] Scale the container in the x axis with the shift value (using ScaleX algorithm) 
* [x] Rebin the container to have the same number of bins as the Sample (using RebinToWorkspace algorithm) 
* [x] Then run the container subtraction algorithm with the adapted container workspace

**Comment by SpencerHowells** [comment]
Instead of 'Shift Container' have 'Shift x-values of container by adding'.
