### ISSUE TITLE
Allow ReflectometryReductionOne's ProcessingInstructions property values to be specified as workspace indices or spectrum numbers

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14000]
**Original reporter:** Jos at ISIS

## Overview ##
In `ReflectometryReductionOne` and related algorithms, `ProcessingInstructions` is currently specified as workspace indices, but scientists would like to be able to specify them as spectrum numbers.

We should ideally use [IndexProperty](http://developer.mantidproject.org/IndexProperty.html) to do this, although this has a different way of handling ranges to the current property. We need to check if we can change this. Currently, `ProcessingInstructions` allows a grouping pattern to be specified as per `GroupDetectors`. This allows multiple groups to be specified resulting in multiple summed output spectra. However, in practice there will only be one output spectrum, so we can perhaps remove this and replace it with `IndexProperty`. Out of the grouping pattern operators supported:
-  `:` and `,` should not currently be in use because they result in multiple groups
- `-` is the most commonly used operator and has the same meaning in `IndexProperty`
- `+` will need changing to `,` for `IndexProperty`.

Using `IndexProperty` will also make it easier to call `ReflectometrySumInQ` from `ReflectometryReductionOne`.

## Update ##

It is no longer a viable option to utilize IndexProperty, due to the fact that multiple groups are used by instrument scientists for diagnostic purposes.

## Context ##
For context, the original request was as follows:

For the `ReflectometryReductionOneAuto` algorithm there has been some confusion over what the `ProcessingInstructions` property values are, see #13828. They are currently workspace indices, not spectrum numbers or detector IDs.

The suggested change is to add the ability to prefix the values in the ProcessingInstructions property string with something to indicate whether the given values are workspace indices or spectrum numbers, e.g. ProcessingInstructions="sp=167-201" or ProcessingInstructions="wi=167-201".

It has been requested that the default, when values are supplied with no prefix, corresponds to what is displayed in the data cursor for the spectrum and slice viewers. Probably spectrum numbers (check this). It may be worth only adding the prefix functionality for the next release and informing users that the default will change from workspace indices to spectrum numbers in the following release.

The call stack for the application of ProcessingInstructions to GroupingPattern in GroupDetectors looks like this:

`ReflectometryReductionOneAuto` -> `ReflectometryReductionOne` -> `ReflectometryWorkflowBase` -> `GroupDetectors (v2)`

`GroupDetectors` should have `NumbersAs` PropertyWithValuestd::string which allows WorkspaceIndexes and SpectrumNumbers as options via a StringListPropertyValidator

**Comment by matthew-d-jones** [comment]
@OwenArnold Anything to add, or that I should clarify?

**Comment by OwenArnold** [comment]
@raquelalvarezbanos This might be a good ticket for you to pick up since yo will take over oversight of the Reflectometry Technique are for ISIS shortly.

**Comment by raquelalvarezbanos** [comment]
Thanks @OwenArnold I'll let you know when I start working on it.

**Comment by PranavBahuguna** [comment]
I'm pretty certain this has been addressed, closing now.

**Comment by OwenArnold** [comment]
This would benefit from the use of the workspace index property that @LamarMoore is working on currently.

**Comment by PranavBahuguna** [comment]
On closer inspection it seems that there is still work to be done in this regard. Reopening.
