### ISSUE TITLE
getComponentByName very slow under some circumstances.

### ISSUE THREAD

**Issue by MikeHart85** [mantidproject/mantid#14003]
Discovered while working on https://github.com/mantidproject/mantid/issues/13632.

CompAssembly::getComponentByName() typically performs a breadth-first search of the component tree. But when it encounters a rectangular detector, it switches to a depth-first approach and calls a specialized RectangularDetector::getComponentByName() function. This function may return early, cutting the depth-first search short, or it may carry on by calling the general getComponentByName() on itself. It decides what to do based on the length and content of the component name being searched for.

This an optimization that was added as part of https://github.com/mantidproject/mantid/issues/9538. 

However, in some circumstances it can lead to poor performance. If an instrument has many rectangular detector banks that are called (bank1, bank2, ..., bank 10, bank11, ...), such as MANDI, then searching for "bank17", for example, will incorrectly trigger a depth first search inside bank1 because "bank17" is longer than "bank1" and matches against the first five characters. The same will happen when searching for any "bankXY" when there exists also a "bankX".

The impact of this varies, but it can be quite pronounced. A test file used in https://github.com/mantidproject/mantid/issues/13632 loaded about 150 times faster (1 second instead of 2.5 minutes) when this behaviour was removed.

Part of the reason this has such a big effect on performance is that these depth searches will always miss and thus loop over all children. In some cases this can be quite a few. In one callgrind run, merely 38 depth search calls to getComponentByName() resulted in 2.5 million child components being processed. The most expensive parts of the loop, by far, were the call to CompAssembly::operator[] and the boost::dynamic_pointer_cast to check whether the IComponent is an ICompAssembly. 

Open questions / improvements to consider:
- Could the depth-first optimization be removed? What would the impact be?
- Should the search algorithm rely on component names following a particular pattern? Martyn mentioned there is no fixed convention.
- Are searches over millions of children a common occurrence? If so, could CompAssembly::operator[] be optimized? Could the dynamic_pointer_cast be avoided? Would it be possible to avoid having to loop over all children?

**Comment by OwenArnold** [comment]
@MikeHart85  Geometry is going to be completely re-done in the near future. This should be a consideration for that. But may not be worth fixing yet.
