### ISSUE TITLE
IDR Instrument default error message

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14067]
If the default instrument is set to WISH and you load the Indirect data reduction tab, an error is thrown stating invalid file run numbers. This should be investigated.

**Comment by SpencerHowells** [comment]
In the DR interface the instrument drop-down menu is generated by searching Facilties.xml for instruments at the default facility with 'technique' containing 'indirect geometry'. When the interface is being opened it should check that the default instrument is in this list. If not, stop with error message.
