### ISSUE TITLE
Indirect Resolution system test 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14063]
Indirect Resolution algorithm requires a system test to be written for it. It appears that there was not one put in when the algorithm was originally written.

**Comment by DanNixon** [comment]
https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py#L504

**Comment by ElliotAOram** [comment]
As Dan Nixon has pointed out this does in fact have a system test I must have missed it. This issue can therefore be closed.

**Comment by NickDraper** [comment]
closed
