### ISSUE TITLE
Auto grouping in the ALC interface

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#14085]
From James:

>I'm trying to analyse some recent CHRONUS data in the Muon ALC Analysis interface.

>I've set the default instrument to CHRONUS (just in case), browsed to the correct files for the start and end, selected a log value, etc. I put Grouping=Auto. But when I click "Load" I get an error "Couldn't load detector grouping".

>However loading the same runs into the Muon Analysis interface, it picks up the default grouping table automatically.

>Using "Custom" grouping in the ALC interface does work but I had to copy/paste the lists out of the Muon Analysis Grouping tab (typing in 600 numbers wasn't an option!)

**Comment by raquelalvarezbanos** [comment]
This is not a bug in the ALC interface. If I try:

> Load(Filename=r'CHRONUS00003422.nxs', OutputWorkspace='CHRONUS00003422', DeadTimeTable='deadtable', DetectorGroupingTable='detectortable')

No grouping information will be loaded, as this information is missing in the nexus file:

![chronus](https://cloud.githubusercontent.com/assets/8956985/10688798/c1dd7d50-796e-11e5-9ee1-c6c1e9c10b96.png)

There should be an entry called  "grouping", as in the following HIFI file:

![hifi](https://cloud.githubusercontent.com/assets/8956985/10688816/f60c03b2-796e-11e5-98e5-eaca74e8d9a5.png)

The MuonAnalysis interface is able to load the grouping because when it realizes there's no grouping information it (silently, no warning message is shown) reads the instrument definition file and loads the grouping from there.

**Comment by raquelalvarezbanos** [comment]
From James:

> Yes, it would be best if all three (normal Load, Muon Analysis Interface and ALC Interface) worked the same and found whatever grouping table was available.

Hence, the relevant bit of code in MuonAnalyisis must be moved to LoadMuonNexus.

**Comment by tom-perkins** [comment]
The same error is seen in the case when the file **does** contain a grouping entry, but that entry is all zeros. In this case the loaded grouping is null and MuonAnalysis uses the IDF grouping.
For example:
![grouping](https://cloud.githubusercontent.com/assets/15363125/12915609/50af51ce-cf24-11e5-8bb8-c41745cc53bb.PNG)

**Comment by tom-perkins** [comment]
Once PR #15191 is merged then the code from MuonAnalysis to load the grouping from the IDF will be in `API` and available for use here.
