### ISSUE TITLE
Workflow algorithm for Engg calibration

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14093]
It should take care of all the input files and calculations (or finding pre-calculated files), normalization, calibration, producing the diverse output files, plots, etc. The GUI / calibration tab should not deal with any workflow logic that can be included in this new workflow algorithm.

@shahrozahmed1 : assigning this to you, as it is a perfect opportunity to write an algorithm from scratch, which in addition will be a workflow algorithm, in Python.

I'm creating the issue now but I think it's better to wait a bit before doing this. We'll come back to it soonish.

**Comment by DavidFair** [comment]
I think this has been completed with `EnggCalibrate` and `EnggCalibrateFull` if I am incorrect please feel free to reopen this issue @FedeMPouzols or @shahrozahmed1
