### ISSUE TITLE
Workflow algorithm for Engg focusing

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14094]
Sibling of #14093, and the same idea applies here for the focusing tab: a workflow algorithm for focusing.

As with the calibration workflow algorithm, I think it's better to wait a bit before doing this. We'll come back to it soonish.

**Comment by DavidFair** [comment]
I think this has been completed with `EnggFocus` however if I am incorrect please feel free to reopen this issue @FedeMPouzols or @shahrozahmed1
