### ISSUE TITLE
Reload python functionality

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14100]
Python functionality request from Tim. We might need to do something about parsing sys modules:

```
Working with Jos and witnessing how he and the other Offspecians develop their reduction scripts is maddening.

To ease their pain, would it be possible to add a menu option to the script window in mantidplot to restart/reset the python kernel? Currently we’re killing and restarting mantidplot to effect the reset.
```

**Comment by martyngigg** [comment]
It's not too easy to "reset" the environment in MantidPlot as it currently stands.
I think this should be considered a poor usability feature of MantidPlot and something to bare in mind for the new workbench.
