### ISSUE TITLE
LoadFITS unit test runs forever in Debug mode under Ubuntu

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#14106]
The LoadFITS unit test seems to run forever on my Ubuntu machine in debug mode.

Visual Studio 2015 also flags an error when exiting [LoadFITS::readToWorkspace](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadFITS.cpp#L781) stating there is stack corruption.

It seems likely that these two things are related.

**Comment by FedeMPouzols** [comment]
Interestingly, this had been noticed by Coverity as a "memory - corruptions" issue.

**Comment by martyngigg** [comment]
@FedeMPouzols It's good to know that it can catch those things. I guess they will get easier to spot as we decrease the number of warnings.
