### ISSUE TITLE
LoadInstruments Defaults Cause Major Issues

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14124]
Now that we have the instrument service, user-editing of IDFs has actually become more complicated, because the instrument loading no-longer routes directly through the `instrument` directory as it always used to. As a result are now telling users to run `LoadInstrument` when they are developing and upgrading their IDFs so they know that the instrument they get is always the instrument def they're working on.

`LoadInstrument` has a Property called `RewriteSpectraMap`. Unfortunately, this defaults to True, and this is causing a lot of confusion because the spectra-detector map gets completely rewritten with it's own custom rules, which bear no link to the originally loaded data. We have recently seen this issue on OFFSPEC.

We want to change the default, but if we do that then we'll end up with nasty down-stream issues, that will be very frustrating to backtrace. We need to force failure and update at the point of use. So the fix is as follows.

* On LoadInstrument Delete the `RewriteSpecraMap` property.
* On LoadInstrument Introduce a new property called `OverwriteSpectraMap`
* Ensure that `OverwriteSpectraMap` is mandatory. 
* Everywhere possible make clear that `OverWriteSpectraMap` is a replacement for `RewriteSpectraMap` in the documentation
* Update everything in the Mantid repo code-base that breaks
* Update the release notes for this major change.

@martyngigg FYI

**Comment by martyngigg** [comment]
:+1:

**Comment by OwenArnold** [comment]
There's actually no need to change the property name. The new type is going to give us everything we need, so I'm going to change the name back to RewriteSpectraMap before I mark this as done.
