### ISSUE TITLE
MDImageWorkspace step 1: MDGeometry and its lean sibling

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14165]
Follow this [Design document](https://github.com/mantidproject/documents/blob/master/Design/Imaging_IMAT/Workspace_type_for_stacks_of_images.md), diagram in approach 1.

Starting from the top of the diagram, reorganize `MDGeometry`, and create `MDLeanGeometry` for step 2 which should add `IMDLeanWorkspace`. See what names to use. In principle all the interface related to transforms would not be brought into the `Lean` side.

This uses/depends on:
- [ ] #15418

**Comment by DimitarTasev** [comment]
Closing, reasons in https://github.com/mantidproject/mantid/issues/15437
