### ISSUE TITLE
Logging to console does not get more detailed than Notice

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#14176]
To reproduce add the following lines to your `.Mantid.user.properties` then run any algorithm.

```
logging.loggers.root.level=information
logging.loggers.fileFilterChannel.level=information
logging.loggers.consoleFilterChannel.level=information
```

The log file will have things at information, but the console will not.

It is unknown how/if this is related to the work done in #12928.

**Comment by NickDraper** [comment]
Example is wrong and that is the problem

For the two specific channels it is logging.channels.xxx not logging.loggers.xxx

**Comment by NickDraper** [comment]
So this works in the user.properties file

logging.loggers.root.level=debug
logging.channels.consoleFilterChannel.level= debug

**Comment by NickDraper** [comment]
No code changes - ready for review

**Comment by peterfpeterson** [comment]
Works for me with these changes.
