### ISSUE TITLE
RebinByPulseTimes progress bar not working well

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14174]
Rebin shows a very nice progress report, but RebinByPulseTimes does not seem to progress at all, which can be very misleading when doing lengthy rebins.

**Comment by OwenArnold** [comment]
@FedeMPouzols Could you help Lamar with this when he starts please.

**Comment by FedeMPouzols** [comment]
Sure. @LamarMoore let me know when you start with this. I'll explain what it is about.

**Comment by FedeMPouzols** [comment]
This was in the end a more complicated and general issue. I've opened a new one: #14249
So I'd close this one as mis-identified.

**Comment by NickDraper** [comment]
closed
