### ISSUE TITLE
Propergate Transfer Issues to Surface in Reflectometry GUI

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14193]
We recently added a new Mode to transfer files based on MeasurementId in the [Reflectometry GUI](http://docs.mantidproject.org/nightly/interfaces/ISIS_Reflectometry.html). Some finishing work needs to be done around this. See [here](https://github.com/mantidproject/mantid/pull/14051) for the last set of changes.

Make sub-issues for each of the following
1. The code in CustomInterfaces relating to the Refl gui should be moved into a subfolder like it is for the other GUIs 
2. The `Measurement` type needs to be renamed to renamed `MeasurementItem` because conceptually a group of `MeasurementItems` make up a whole `Measurement`. Likewise `MeasurementSource` should be renamed `

Both of the above issues will be dealt with in the same issue as they are both associated with restructuring the customInterface code for Reflectometry
- [x] #14255

All issues below will be dealt with separately:
1. \- [x] #14370 Familiarise yourself with the way that the measurement-based transfers work. See [here](https://cloud.githubusercontent.com/assets/1109536/10736252/d695b284-7c03-11e5-84b6-e7577a0e55e1.png) and [here](https://github.com/mantidproject/mantid/pull/14051) for examples. The `Measurement` records error information regarding any impossible transfer. We should set the column in the UI to highlight the failed transfer and record this information. I was thinking that the row in the transfer table should be highlighted orange, and should provide some way of explaining why the transfer failed. ![mockup](https://cloud.githubusercontent.com/assets/1109536/10905426/06759244-8212-11e5-9c03-ceed5aa83b31.png)
2. \- [x]  #14905 Would be nice if the transfer could be made async via the AlgorithmRunner. 
3. \- [ ] We need indirection between ReflMainViewPresenter and the AlgorithmManager, which runs ReflectometryReductionOneAuto. We don't always want to use the AlgorithmManager, so it would be better if that where hidden behind a service layer. 
4. \- [ ] Would be nice if the Row execution could be made async via the Algorithm Runner. Needs the step above to be completed first.

**Comment by OwenArnold** [comment]
@tom-perkins better that @MattKing06  does this on reflection.

**Comment by MattKing06** [comment]
Blocked by #14274

**Comment by gemmaguest** [comment]
I think the remaining tasks are done as part of the GUI restructuring but there may be uses of AlgorithmManager that can be tidied up more - I've added that to #26025
