### ISSUE TITLE
IPython dependency issue on OSX

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#14206]
When installing Mantid Nightly Build on a Mac the error shown in the image below appeared. It seems to be a dependency issue.
![ipython_issue](https://cloud.githubusercontent.com/assets/8955784/10878172/d01e7932-8143-11e5-9b18-14b4bb825ac4.PNG)

**Comment by quantumsteve** [comment]
`ornl-mac` had IPython 4.0 installed, which currently causes warnings (see #13481) and shouldn't be on a build server. IPython 3.2.1 has been installed on `ornl-mac`, which doesn't depend on the traitlets library and should fix this issue.
