### ISSUE TITLE
SofQW Progress Tracking

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14222]
The SofQW algorithm does not have any progress tracking. It requires both labels and numerical tracking.

*Appears to have progress tracking and be running in batch algo runner so not sure why this isn't working*

**Comment by SpencerHowells** [comment]
Can you add to Sample Logs the range of Q & w used.

**Comment by KarlPalmen** [comment]
Can you produce a use case, which is sufficiently slow to require this progress tracking?

**Comment by louisemccann** [comment]
Will solve SofQW lpg files in #17056
