### ISSUE TITLE
Revert to vanilla python in `mantidpython`

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#14234]
There is a use case in ORNL's autoreduction for `mantidpython` to revert to vanillia python. Since `ipython` already reverts to vanillia python logging when supplied `--classic`, just have the wrapper script invoke `python` when this argument is supplied. Note that the argument needs to not be supplied to python as it will generate an error.

**Comment by NickDraper** [comment]
Matthew can you pick this one up quite urgently
