### ISSUE TITLE
Engg GUI: Fix instrument prefix in the output calibration files

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14245]
After the instrument selector was changed to remove the dash from the ENGIN-X name this part of the code fails to recognize "ENGIN-X":
https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp#L606-L608
And the output files are flagged with the "UNKNOWN" prefix.

That if should probably accept both the short and long names of ENGIN-X. Would be good to add a vector of the supported instrument(s).
This is a small fix that can be done with any of the other Engg GUI issues being fixed.

**Comment by shahrozahmed1** [comment]
issue has been fix in the following branch #14191
