### ISSUE TITLE
Follow up work for ConvertToReflectometryQ

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14287]
Following fix to #14279

*  Make sure the polygon ordering fix is applied to the kikf and pipf modes. Currently done for the QxQy mode but not for the others.
* See the refactoring steps against the original issue PR. Apply those.
* In the documentation for the algorithm, Tim wants the theta-lambda plot that you can get from the first example included as an image. Something like this.
![screen shot 2015-11-05 at 09 20 35](https://cloud.githubusercontent.com/assets/1109536/10964341/8629c43c-839e-11e5-9cc6-3380af0d552b.png)

**Comment by OwenArnold** [comment]
@raquelalvarezbanos Can you decide if you're going to do any of this. Otherwise I think Matt would be more than capable of making these fixes.

**Comment by raquelalvarezbanos** [comment]
Hi @OwenArnold I agree Matt can make the fixes. I can help if you need help @MattKing06, just let me know
