### ISSUE TITLE
Add ISIS Powder Diffraction system test for Polaris

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#14303]
@FedeMPouzols  After discussion with Ron Smith, we discovered that the old version of the Powder Diffraction script is currently being utilised by the scientists for many instruments and for this reason scientists are also afraid of updating to the latest version of Mantid, as they think the old Powder Diffraction scripts may not be compatible with the new Mantid. 

The updated version of Powder Diffraction script #13471 integrated with Mantid has only been tested with HRPD. With the help of script provided by Ron Smith, enable the updated Powder Diffraction script to run Polaris and add a system tests which works with Polaris instrument.

**Comment by FedeMPouzols** [comment]
An initial step is to make sure that the example runs (or similar system tests) work well when in the .pref file the option `ExistingV` is set to `no`. This implies that additional calculations are done which require additional files. That was the step where the scripts were not working for POLARIS data. This is probably an issue for the other instruments as well. So the system tests will have to check both cases: `ExistingV` set to yes/no. `Yes` will tipically happen at the beginning of cycles, whereas `no` is the most common case.
