### ISSUE TITLE
Create a suitable file format for saving out bin selections in the Instrument View

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#14313]
The SANS group would like to mask bins for certain Pixels. This can now be selected in the Instrument View but not yet saved out. A suitable file format needs to be developed to store the spectra and bin information.

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew This is about creating time masks in the instrument view. This is something the the SANS team would like to do. Get more requirements from them please (I think especially Richard and Rob).

**Comment by Mantid-Matthew** [comment]
@DavidFair closaing as stale but worth being aware of.
