### ISSUE TITLE
Run Locator

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14324]
I'm not convinced that the archive search functionality is working nicely on all platforms. This is happening 

We should make this as robust as possible. We should take the user overridden mount points from UserCatalogInfo if possible and construct paths accordingly. 

The developer working on this should be working on linux of osx.

![screen shot 2015-11-06 at 12 23 25](https://cloud.githubusercontent.com/assets/1109536/10996981/571eef4e-8481-11e5-9a72-36ea94dfb34f.png)

**Comment by NickDraper** [comment]
Isn't this the FileFinder with archivesearch?
