### ISSUE TITLE
Text Axis not loaded properly from processed file

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#14327]
To reproduce:

* Make sure you have the system test data
* Start MantidPlot
* Run LoadNexusProcessed and `VesuvioFittingWithQuadraticBackgroundTest_V3.nxs` file in `build/ExternalData/Testing/SystemTests/tests/analysis/reference/`
* Double-click the workspace to show the matrix
* The last axis label will have some random characters in it

**Comment by martyngigg** [comment]
Thinking about it it's also possible this is a problem with the saving side. It's worth checking. The writing code is in https://github.com/mantidproject/mantid/blob/master/Framework/Nexus/src/NexusFileIO.cpp#L282 and the reading code is in https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadNexusProcessed.cpp#L1674

**Comment by picatess** [comment]
@OwenArnold  Don't know if this helps: This is a workspace I recently replaced. It is linked to this PR https://github.com/mantidproject/mantid/pull/13885 .The main difference to the previous system test data is the distribution flag which should be now set to true. Also, this is a very sensitive system test, the new system test data had to be generated on Ubuntu.

**Comment by martyngigg** [comment]
@picatess @OwenArnold This is definitely just a bug with loading the text axes in some way. The data itself seems to compare just fine.

**Comment by OwenArnold** [comment]
@picatess. Sorry to do this, but i've got to sort some things out for ANSTO immediately. Would you mind taking a look at this.
