### ISSUE TITLE
Investigate Removal of Data Search Directories

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14322]
I've seen an issue a couple of times on the Mac now. When you reinstall a new version of Mantid, it clears the data search directories entries. Does this affect other platforms?

**Comment by tom-perkins** [comment]
Tested on Windows 7 64-bit:
- Installed 3.5.0 over the top of existing 3.5.0. Data search directories were retained ok.
- Upgraded 3.5.0 to latest nightly 3.5.20151105.1804. OK
- Downgraded to 3.4.1. OK
- Started from 3.4.1, upgraded to 3.5.0. OK

**Comment by OwenArnold** [comment]
@tom-perkins Can you remote into the OSX test machine. Martyn can give you login details. Try there too.

**Comment by tom-perkins** [comment]
@OwenArnold @samueljackson92 Have either of you noticed this on the Mac with recent releases?

**Comment by martyngigg** [comment]
This is no longer an issue after switching to the drag and drop packaging.
