### ISSUE TITLE
SofQWMoments is producing incorrect values

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14330]
Jeff has reported that the values being produced in SofQWMoments are incorrect by a significant magnitude.

> The issue however is that since M2 is and integral involving S(Q,E), divided by another integral of S(Q,E), any constant factor should disappear. This value should therefore be unique and independent of any constant scaling facors in S(Q,E). It is this value which appears to be wrong and is approximately 1531 times bigger than I think it should be.

**Comment by SpencerHowells** [comment]
S(q,w) is an odd beast. Energy is in histograms while Q is point mode, so Q & w have differing 'units'.

**Comment by ElliotAOram** [comment]
No longer an issue
