### ISSUE TITLE
Easy Misuse of SansWideAngleCorrection

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14344]
sans_bugfix
[SansWideAngleCorrection](http://docs.mantidproject.org/nightly/algorithms/SANSWideAngleCorrection-v1.html) Allows you to provide a transmission workspace that has not been collapsed down to a single spectra. I [this](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/plugins/algorithms/SANSWideAngleCorrection.py#L56) is done on the assumption that there is a single spectra to process.

I also notice that:
- Validation is being done inside execute rather than in validateInputs overrides. 
- dataY, and such unsafe variants are being called on input workspaces. Not sure this is desired.

**Comment by OwenArnold** [comment]
@picatess some easy fixes to make the SANS reduction area easier to work with, and harder to misuse.

**Comment by Mantid-Matthew** [comment]
Closing as stale.
