### ISSUE TITLE
Avoid ICAT login

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14369]
Currently in the Refl gui, we are forced to login to ICAT to perform the searches. We may be able to avoid that using Freddies [webservice](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/ISISDataArchive.cpp#L27), with is used in the ISISArchiveSearch. 

Investigate if [this](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/inc/MantidDataHandling/ISISDataArchive.h) could be used as a way to circumvent the ICAT login procedure in the ReflectometryGUI.

Currently the [ICAT search provider](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/ReflCatalogSearcher.cpp) in the ReflectometryGUI requires a login. Basically can we use the webservice to fulfil [this interface](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/IReflSearcher.h) and [this](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/ReflTransferStrategy.h) one

**Comment by gemmaguest** [comment]
Closing as Stale because this has not been brought up by users and the current functionality is sufficient so we are unlikely to get around to it
