### ISSUE TITLE
Fix ISIS autoconfiguration script and separate it from root part of the script

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#14360]
ISIS configuration script is currently broken. 
This ticket is to:
1) Identify the reason for failure. 
2) Separate mantid part of the script from admin part to allow it to run without root access.

**Comment by NickDraper** [comment]
This needs completing and testing SOON if it is going to make the patch

**Comment by peterfpeterson** [comment]
This was fixed by #14385.
