### ISSUE TITLE
Remove raw pointers in ParaView Plugins and Vates API

### ISSUE THREAD

**Issue by picatess** [mantidproject/mantid#14390]
There are quite a few instances where we make use of raw pointers and `new` and `delete` in the ParaView Plugins and the VatesAPI (and the VatesSimpleGui). 

The task is to identify these instances and make use of smart pointers and `make_shared` where possible. Note that if we are dealing with pointers to VTK/ParaView data structures we should use VTK's smart pointer.

Note that using raw pointers also happens in the tests and would have to be chagned there as well.

Speak to @picatess before starting this task.

**Comment by tom-perkins** [comment]
To do:
- [ ] VatesAPI and tests - PR #14420 
- [ ] ParaView plugins
- [ ] Vates simple GUI
