### ISSUE TITLE
Crash with FilterEvents Dialog

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#14463]
When running mantidplot in debug mode using Visual Studio 2015, loading the Interfaces->Utility->FilterEvents dialog from the main menu results in an Access Violation when exiting the software (even if FilterEvents has been closed):

![image](https://cloud.githubusercontent.com/assets/15360272/11208943/fb351af8-8d15-11e5-961b-813eced40657.png)

**Comment by NickDraper** [comment]
Note: This only occurs when the debugger is attached.  Code compiled in debug or release and run separately does not show this issue.

**Comment by NickDraper** [comment]
Trying out the environment variable _NO_DEBUG_HEAP=1 does not affect this.
http://ofekshilon.com/2014/09/20/accelerating-debug-runs-part-1-_no_debug_heap-2/

**Comment by NickDraper** [comment]
As this only happens on shutdown, and then only when debugging this has been given a low priority.

**Comment by martyngigg** [comment]
This appears not to be an issue any longer.
