### ISSUE TITLE
Add Poisson cost function

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#14490]
The correct cost function formula for Poisson statistics should be (for bin contents=N, fitted mean count rate=y)
y<0: forbidden (infinite cost)
y>=0, N=0: cost function=2_y
y>=0, N>0: cost function=2_( (y-N) + N*(log(N)-log(y)) )

**Comment by Anders-Markvardsen** [comment]
Just looking at this ticket with Joe.

Fixing this might do what Joe needs for fitting a background.

As a comment why is there not a factor of 2 to much, at least when comparing to -log(lambda^N*exp(-lambda)/lambda!) using the stirling approximation.

Please inform Joe when this is fixed

**Comment by mantid-roman** [comment]
At the moment it works for functions of the form y = exp( f(x) ) or any other strictly positive function.
