### ISSUE TITLE
Kernel::Logger::is() not working as expected

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14524]
I'm not sure if this is a confusion but several algorithms send debug messages to the logger only if...
```
if (g_log.is(Kernel::Logger::Priority::PRIO_DEBUG)) ...
```
That doesn't seem to work as expected. Try to open Mantid, set for example `information` level, and check what you get from these ones for example:
```
auto prio1 = g_log.is(Kernel::Logger::Priority::PRIO_DEBUG);
auto prio2 = g_log.is(Kernel::Logger::Priority::PRIO_ERROR);
auto prio3 = g_log.is(Kernel::Logger::Priority::PRIO_INFORMATION);
auto prio4 = g_log.is(Kernel::Logger::Priority::PRIO_CRITICAL);
auto prio5 = g_log.is(Kernel::Logger::Priority::PRIO_FATAL);
```

All the `prio` values are `true` (checked on win7 and debian).

The documentation of `Logger::is` says `Returns true if at least the given log level is set`. Does that "set" mean "selected by the user" or "available"? It seems to behave as the second but the code elsewhere seems to be using as if it should behave as the first option.

Related to #14467, where the behavior of the logger here was really awkward: https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/src/CostFunctions/CostFuncLeastSquares.cpp#L410

**Comment by martyngigg** [comment]
It's supposed to behave like the as your first case so that you can avoid constructing an expensive log statements if it is not going to be used.

I've marked this high priority for this release as this is a regression that we've introduced somewhere and will impact on performance in some areas.

**Comment by NickDraper** [comment]
This might be interesting, when you set the level in mantid plot you are setting the level for that output channel.  The is will not know about the levels for channels, it will get the level of the root logger.  This is set in mantid to be the lowest of all of the channels (as it has to be for the channels to work).

So it might not always follow that this would follow a particular channel, but should follow the lowest of all of the channels.

**Comment by NickDraper** [comment]
It is possible that the tracking of the root logger level to the minimum level of the channels is not working perfectly
