### ISSUE TITLE
Remove bounding box descriptions from IDF?

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#14555]
With #14424 done, then it should be possible to remove bounding box descriptions from existing IDFs, e.g.  the OSIRIS IDF (OSIRIS_Definition.xml). 

To test for each IDF for which bounding box descriptions are present: 

1. Make a record of the load time before removing the bounding boxes
2. Make a record of how will it display in Instrument View
3. Remove the bounding boxes descriptions and repeat 1 and 2

If 1 and 2 are the same or better after removing the bounding boxes then:

    commit the modified IDF

if not:

    record such observations in a separate issue

Ensure the documentation in http://docs.mantidproject.org/nightly/concepts/HowToDefineGeometricShape.html#howtodefinegeometricshape is consistent with what is observed.

This is really a maintainance ticket but it also serves to further test before this release the fix in #14424 and to what extend bounding box descriptions may still be required

**Comment by MikeHart85** [comment]
I've noticed something strange while removing bounding boxes from OSIRIS instrument.

The load times of the LoadEmptyInstrument() algorithm are nearly identical for both version, with and without bounding boxes. When a new geometry cache needs to be generated, they take about 12.5 seconds (with a debug build). When a geometry cache is already present they are nearly instant.

However, there is a difference when you view the instrument for the first time after starting Mantid: 
- Using the original file, there is a significant delay during which the interface freezes for a few seconds before the instrument is shown
- Using the file with bounding boxes stripped out, the instrument shows up instantly

This is rather odd.
