### ISSUE TITLE
Importing a TBL file created from the v1 Refl GUI to the v2 gui should be easier

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14557]
Version 1 of the GUI (Max's) works of a TBL file. These can be saved and loaded and effectively remember the entries in the table.

In Version 2 of the GUI, we work off TableWorkspaces. However we also introduced the ability to import a TBL file from the menu. However the import does not fully complete the import. You have to do an import as one step and a load as another. We should just be able to Import the table in one-shot.
![screen shot 2015-11-24 at 10 04 49](https://cloud.githubusercontent.com/assets/1109536/11363617/dd6faaa6-9292-11e5-8562-89fef5f4b5a2.png)

**Comment by OwenArnold** [comment]
@raquelalvarezbanos This sounds like the kind of thing that Matt could do. So reassign to him if you like.

**Comment by raquelalvarezbanos** [comment]
@MattKing06 I reassigned this to you.
