### ISSUE TITLE
Document what Mantid reads from Nexus files

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#14561]
Add documentation which explains what information Mantid is reading as part of loading Nexus files. Perhaps most importantly the ISIS and SNS Nexus files.

This includes documenting LoadNexus and how it chooses which load algorithms to use. 

Add this documentation in the rst of the loaders.

**Comment by KarlPalmen** [comment]
Dear Anders

I had a quick look at the code that decides which Nexus loader to use and there appears to be two different ways this is done


(1)    A way used by Load, which uses the NexusDescriptor and calls the confidence methods of the loaders

(2)    A way used by LoadNexus, which does not have a confidence method and therefore, I do not think is ever called by Load.

Karl

**Comment by KarlPalmen** [comment]
This ticket is blocked by : 
 - [ ] #14572 
 - [ ] #14573

**Comment by KarlPalmen** [comment]
In the NexusFile document of concepts, there is a section about structure that just has text "to be completed". This section would be very useful for #14572 & #14573 as well as this issue.
So I'll create an issue for this.

**Comment by KarlPalmen** [comment]
Work is currently being done via issue #14940.

**Comment by KarlPalmen** [comment]
Now awaiting #16070 to be either closed or moved to release 3.8 .
