### ISSUE TITLE
Indirect Data Reduction update for ILL

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14578]
Spencer has provided me with some updated ILL IN16B reduction and calibration files. They should be able to just replace the currently used files although some small amendments may need to be made the the unit tests to allow for the use of GroupWorkspaces

*Edit - This issue will also cover adding the data selector for origin to the interface*

**Comment by SpencerHowells** [comment]
In ILLIN16BCalibration, under 'category' workflow should also have MIDAS.

**Comment by ElliotAOram** [comment]
This will be resolved by mantid developers at the ILL
