### ISSUE TITLE
Disable error bars in EnggDiff focusing plots by default

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14593]
In the Python `plotSpectrum` commands they are disabled with an optional parameter: `error_bars=False`.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols does that need to be included for type of plots ?

**Comment by FedeMPouzols** [comment]
I understood that they want error bars always disabled in the automatic plots. I thought that the default is actually disabled, but it seems to be behaving the other way around.
