### ISSUE TITLE
Usage example for LoadTOFRawNexus

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#14595]
The documentation needs a usage example.

Related issue #14577 .

**Comment by NickDraper** [comment]
We need an example for this, are there any suitable files at the SNS that are small enough to go into the usage data?

Assign on if this is to the wrong person.

**Comment by stuartcampbell** [comment]
@peterfpeterson Is this algorithm even used anymore ?

**Comment by KarlPalmen** [comment]
Yes I'd like to know this. If the answer is no, it would save me having to document the behaviour of this algorithm in more detail. I yes, I'd like the usage example to resemble this usage (but be smaller). It may be used for my documentation.

**Comment by KarlPalmen** [comment]
I found 3 uses as a child algorithm in release 3.6. There may be more uses in earlier releases.
