### ISSUE TITLE
IndirectQuickRun algorithm 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14616]
The MSG have asked for an algorithm that does the following:
- [ ] Loads in `.raw` or `.nxs` files
  - [ ] if files are `.raw` reduce them using data reduction
- [ ] Runs the files through the `Elwin` algorithm 
- ~~Optional run through `Iqt`~~

The purpose of this is to get an overview of data quickly and in an automated way.

_Iqt option removed as it's input can not be produced automatically_

**Comment by SpencerHowells** [comment]
Iqt is not a 'black-box', it needs thought about the input. If _red workspaces are created, just run Iqt.

**Comment by SpencerHowells** [comment]
Not at all happy with Iqt option! Iqt comes with a health warning - need to be careful with number of points, energy range and energy bin otherwise the result can be rubbish!! Itr is not a black-box and should NOT be automatic.

**Comment by ElliotAOram** [comment]
@SpencerHowells Probably best to exclude `I(Q,t)` from the algorithm completely in this case then.

**Comment by ElliotAOram** [comment]
This will also resolve #12270

**Comment by ElliotAOram** [comment]
I've commited the latest version of the algorithm (hopefully it should only require a test and documentation)

**Comment by SpencerHowells** [comment]
The algo name is too vague. Can you change it to IndirectEnergyWindowScan.

**Comment by louisemccann** [comment]
The EnergyWindowScan depends on a slightly modified version of MSDFit. This modified version outputs in a slightly different way, so plotting will need to be refactored.
