### ISSUE TITLE
Delete wiki pages for ALC interface

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#14624]
The documentation for the Muon ALC interface has moved to mantid\docs\source\interfaces\Muon_ALC.rst. 
The old wiki page:
http://www.mantidproject.org/Muon_ALC 
and its child pages: 
http://www.mantidproject.org/Muon_ALC:_Data_Loading http://www.mantidproject.org/Muon_ALC:_Baseline_Modelling
http://www.mantidproject.org/Muon_ALC:_Peak_Fitting
should be deleted now that they have been replaced.

Issue created from discussion in PR #14601.

**Comment by tom-perkins** [comment]
Removing assignment as only someone with sysop permissions on the wiki can do this.

**Comment by NickDraper** [comment]
All done

No PR as no code change
