### ISSUE TITLE
Embedded IDF corrections do not work on Linux

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#14644]
Set up Mantid search path to look as system tests data and run the script  below. 

It runs on Windows but  fails on Linux (tried RHEL7)
If you analyse the logs, one can see that system on windows finds LET embedded IDF corrections and applies them and on Linux it does not.  Further analysis would show that on Linux your monitor workspace have different (from what is expected) monitors spectra because the corrections are wrong. 

```python
from Direct.DirectEnergyConversion import DirectEnergyConversion
from Direct.PropertyManager  import PropertyManager

prop_man = PropertyManager('LET')
prop_man.sample_run = 14305
prop_man.det_cal_file = 'det_corrected7.nxs'
sample_ws = PropertyManager.sample_run.get_workspace()
prop_man.update_defaults_from_instrument(sample_ws.getInstrument())

#
mws = PropertyManager.sample_run.get_monitors_ws()
ei,mon1_peak,mon1_index,Tzero = \
            GetEi(InputWorkspace='SR_LET014305_monitors', Monitor1Spec=40966,Monitor2Spec=5506,
                  EnergyEstimate=3.4,FixEi=False)
print ' ei= ',ei,' mon1_peak_t= ',mon1_peak,' Mon1_index= ',mon1_index,' Tzero= ',Tzero                  


```

**Comment by KarlPalmen** [comment]
When fixed, I'll let @abuts know and he'll modify a system so that still works.
