### ISSUE TITLE
Ubuntu: Errors on start up with installed version

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#14660]
Running `/opt/mantidnightly/bin/MantidPlot` on the current nightly (3.5.20151130.1920) produces errors in the console:

```
> /opt/mantidnightly/bin/MantidPlot
/opt/mantidnightly/bin/MantidPlot: 30: /opt/mantidnightly/bin/MantidPlot: cannot open 1073741824: No such file
/opt/mantidnightly/bin/MantidPlot: 30: /opt/mantidnightly/bin/MantidPlot: [[: not found
```

It would seem that on Ubuntu `/bin/sh` points to `/bin/dash` and this doesn't support the `[[` operator - http://serverfault.com/a/52050.

**Comment by peterfpeterson** [comment]
Would a viable solution to change to `/bin/bash`, or is that not installed?

**Comment by martyngigg** [comment]
`bash` is installed and actually the default shell for a terminal. It's just that `/bin/sh` uses `dash`. I'm happy with just changing the shebang to `/bin/bash`.

**Comment by peterfpeterson** [comment]
Alternatively I can can change the `if [[ ${TCM_REPORT} < 1073741824 ]]; then` to `if [ ${TCM_REPORT} -le 1073741824 ]]; then`

**Comment by peterfpeterson** [comment]
The actual problem was that I was using `bash` rather than `sh`.
