### ISSUE TITLE
Indirect Data Reduction remove autoRun

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14688]
Several of the interfaces in IDR are reported to be automatically running algorithms when values in the property trees are changed. This is causing issue with inputting values and hence should be removed.

*The first step is to investigate which interfaces are doing it and on what inputs.*

**Comment by SpencerHowells** [comment]
Not just property tree values but sometimes changing anything eg run/file name,

**Comment by ElliotAOram** [comment]
* **`ISIS Calibration'**
  * Runs `ISISIndirectEnergyTransfer` on Change of Run number
  * This appears to be for the plot mini plot in Calibration
* **`ISISDiagnostic`**
  * Runs `TimeSlice` algorithm on change of run number and parameter change
* **`Moments`**
  * Change of file and parameter cause re-run of `SofQWMoments`
