### ISSUE TITLE
Plotting range errors in VSI

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14695]
The range of data displayed in VSI is sometimes not the full workspace. For example, the workspace extends -2 to 2 in each of three dimensions, but the plotted data in VSI is truncated to 0 to 2 or -0.5 to 2 in one or more dimensions. The incorrect, truncated range is also displayed in the "Information" tab.

This behaviour has been observed in Ubuntu and Windows with event and histo workspaces created with the following script. Note that it does not happen on every occasion and it may be necessary to restart VSI several times before you see the problem.

``` python

ws_mdhw = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='12')
FakeMDEventData(ws_mdhw, UniformParams='1000', RandomizeSignal='1')
ws_mdhw = BinMD(ws_mdhw,AlignedDim0='h,-2,2,12',AlignedDim1='k,-2,2,12',AlignedDim2='l,-2,2,12')
ws_masked_mdhw = CloneMDWorkspace(ws_mdhw)
MaskMD(Workspace=ws_masked_mdhw,Dimensions="h,k,l",Extents="-2,0,-2,0,-2,0")

ws_mdew = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='12')
FakeMDEventData(ws_mdew, UniformParams='1000', RandomizeSignal='1')
ws_mdew = SliceMD(ws_mdew,AlignedDim0='h,-2,2,12',AlignedDim1='k,-2,2,12',AlignedDim2='l,-2,2,12')
ws_masked_mdew = CloneMDWorkspace(ws_mdew)
MaskMD(Workspace=ws_masked_mdew,Dimensions="h,k,l",Extents="-2,0,-2,0,-2,0")

```

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve I am reassigning this to you. Please feel free to change this, if this is not appropriate.
