### ISSUE TITLE
decrease the number of pylint violations for top 10 reflectometer files

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#14702]
Four out of the ten files with most violations on jenkins pylint are from the the following directory: 
`scripts/Interface/reduction_gui/widgets/reflectometer/`, adding up 240 violations in total.
These files include `wks_utility.py`, `refm_reduction.py`, `relf_gui.py` and `base_ref_reduction.py`. Most of the common violation you will find are `invalid-name`, `line-too-long` and `unused-variable`, reduce as many pylint violations as possible on these files.

**Comment by MattKing06** [comment]
- [x] refl_gui.py
- [ ] base_ref_reduction.py
- [ ] wks_ultility.py
- [ ] refm_reduction.py
