### ISSUE TITLE
Additional lag between switching views.

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#14713]
After moving from ParaView 4.3 to 5.0.0-RC1, @picatess observed additional lag when switching views in the VSI.  The delay appears to be between the view first switching and the background color changing and only seems to affect Windows.

**Comment by AntonPiccardoSelg** [comment]
Cannot see a big lag as compared to Windows now, but that might be subjective. Since it is unlikely that this will be addressed, the issue will be closed.
