### ISSUE TITLE
Implement a Gaussian option for SmoothMD

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14731]
Currently only a "hat" option is implemented. Russell Ewings has mentioned that Gaussian is also important.

"Regarding the Gaussian smoothing (which should only apply to MDHisto workspaces, by the way) we define the width with an array that has the same number of elements as there are dimensions in the workspace. The nth element of this array corresponds to the full-width-half-maximum of the Gaussian along the nth dimension of the data. Crucially, this width is given in terms of number of bins, rather than Q or energy units. The truncation of the Gaussian is done when the value in the wings falls below 0.02 of the peak."

**Comment by quantumsteve** [comment]
@matthew-d-jones I like that you are adding Gaussian smoothing, but have a few questions

In general, a N-dimensional Gaussian is described by an N-dimensional matrix. Do you plan on transforming into find a basis where the multidimensional Gaussian function is linearly separable? 

How are you handing the case of nonorthogonal axes, such as a hexagonal crystal?
