### ISSUE TITLE
Check getcycle.py file in PowderISIS

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#14755]
There is not a lot going on inside the `getcycle.py` file right now, it would be ideal to check with Ron whether they required this file for anything particular. If yes then it needs to be documented what the file does and how. If the file is not necessary any more it can be removed, as it is not required for the diffraction process.

**Comment by DavidFair** [comment]
@FedeMPouzols This script seems to do something similar to using the "Search Data Archive" option - as noted in the issue I don't believe we use it anywhere so could it be removed?

**Comment by FedeMPouzols** [comment]
Yes, I think it is safe to remove this, as nobody has requested it and it uses the old manual way of finding files from the archive.
