### ISSUE TITLE
Make Import of TBL files via Reflectometry GUI more user friendly

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14758]
Follow on from  #14557

* Importing a table twice. On the second pass just replaces the existing one without warning. 
* Linked to the point above. No indication in the GUI of what the table currently being viewed is. Should be added to the title.
* Can we suggest (auto fill a workspace name)? May need to check uniqueness in the ADS.
* `showImportDialog` should have a comment relating to what `setModel` does.

**Comment by MattKing06** [comment]
Since the loadTBL dialog is created each time by the python-code runner:

```cpp
void QtReflMainView::showImportDialog() {
  std::stringstream pythonSrc;
  pythonSrc << "try:\n";
  pythonSrc << "  algm = "
            << "LoadReflTBL"
            << "Dialog()\n";
  pythonSrc << "  print algm.getPropertyValue(\"OutputWorkspace\")\n";
  pythonSrc << "except:\n";
  pythonSrc << "  pass\n";
  // outputWorkspaceName will hold the name of the workspace
  // otherwise this should be an empty string.
  QString outputWorkspaceName =
      runPythonCode(QString::fromStdString(pythonSrc.str()), false);
  this->setModel(outputWorkspaceName.trimmed());
}
```

I'm not sure if any previous entries for workspace names can be remembered for the auto-fill.
