### ISSUE TITLE
Display out-of-bounds of workspace and masked regions as background colour in 2D plots

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14780]
Masked data is displayed as _nan_ for MDWorkspaces and is plotted as white in the Slice Viewer. White also appears on the colourmap, so this is not ideal.

As agreed at the VATES meeting 14 Dec 2015, we should make these regions transparent, or at least appear transparent by matching the background colour of the plot (grey). However it is low priority.

Part of #12689

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew Again this might be a good issue to get you into the SliceViewer
