### ISSUE TITLE
Set masked data in MDWorkspaces to NaN

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14782]
Currently you can set masks in MDWorkspaces without loosing any data. You can therefore later remove or change the mask. However, it was decided in the VATES meeting 14 Dec 2015 that this does not need to be the case.

Set masked signal and errors to NaN. This should mean that many algorithms will simply "do the right thing" without us having to write code to handle masked data.

MDEventWorkspaces will set box values to NaN but not change the underlying event data, this avoids issues with file-backed workspaces.
MergeMD may therefore need to "reapply" masks as it alters the box structure. Actually it should already need to reconsider which boxes have the mask flag, but this should be checked.

How the NaN's are displayed in the Slice Viewer and 1D plots will be addressed in #14780 and #14781 respectively.

Part of #12689

**Comment by AndreiSavici** [comment]
I would use NaNs instead. SliceViewer uses transparent color for NaN

**Comment by matthew-d-jones** [comment]
NaNs display as white in the SliceViewer, which we want to avoid as it is on the colourmap. If it really counts as transparent then maybe there is a way to set the background colour to something other than white? In principle I also agree that NaNs would be preferable though.
I think MatrixWorkspaces use 0 for masked data so that many algorithms treat masked data in the correct way without having to explicitly code the behaviour. But perhaps the same would also be true if NaNs were used.
I will check all of these things before designing a solution and try to make sure that the solution is common across workspace types.
