### ISSUE TITLE
CutMD can cause crash due to running out of memory

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#14813]
To avoid crashes, the algorithm should calculate the memory it expects to require and ask the framework manager if that is available. There are tools to calculate expected sizes of histogram workspaces (possibly not yet for event workspaces?).

**Comment by matthew-d-jones** [comment]
Changes were made to CutMD since this issue was created which means that it is now much more unlikely to manage to run out of memory, however it is still theoretically possible.

**Comment by NickDraper** [comment]
No resource to progress in this area - archiving
