### ISSUE TITLE
Improve reporting of Fit progress

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#14839]
From a user, http://forum.mantidproject.org/t/fit-progress-indication/89:

_When a Fit is in progress and taking a long time, it would be useful to see the latest Cost Function in the progress bar, or somewhere on the dialog it is embedded in. In addition, maybe the parameters in the dialog / fit function pane could update every iteration or the fit curve overlaid on the data could be updated. I would then have an idea whether to let it continue, or cancel and retry with better guesses of the parameters. The actual percentage progress / estimated time is a bit arbitrary since it assumes it will go to the maximum allowed iterations._

@mantid-roman Is there something we do better here?

**Comment by mantid-roman** [comment]
We can try.
