### ISSUE TITLE
Create a flat projection surface for the Instrument View

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#14849]
The instrument is to be projected onto one of the planes: XY, XZ, or YZ.

**Comment by AndreiSavici** [comment]
Is this the same as http://docs.mantidproject.org/nightly/algorithms/ConvertAxesToRealSpace-v1.html ?

**Comment by mantid-roman** [comment]
No it is for the instrument view. It won't do rebinning, but allow detector picking and selection. It is similar to the spherical and cylindrical projections that we have there.

**Comment by OwenArnold** [comment]
This should be easy enough if the panels do not overlap. If there is overlap, do you think the view mode could try to at least keep the panels relative to each other in some way.

**Comment by mantid-roman** [comment]
Maybe it shouldn't be used for such instruments?

**Comment by OwenArnold** [comment]
Agreed, wouldn't make much sense for a spherical geometry. But for lots of SANS instruments it definitely makes sense and overlaps can occur.
