### ISSUE TITLE
Umbrella: Add workflow diagrams to algorithm documentation

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#14861]
Add workflow diagrams to the following algorithms
- [ ] ComputeSensitivity #14862 
- [ ] CreateTransmissionWorkspaceAuto #14863 
- [x] SofQW #14865 
- [x] AccumulateMD #14866
- [x] CreateMD #14867
- [x] CutMD #14868
- [x] SANSBeamFluxCorrection #14869
- [x] SANSStitch #14870
- [x] TOSCABankCorrection #14871
- [x] IndirectFlatPlateAbsorption #14872
- [x] IndirectCylinderAbsorption #14873
- [x] IndirectAnnulusAbsorption #14874
- [x] EVSDiffractionReduction #14875
- [ ] DetectorFloodWeighting #14876
- [ ] SNSPowderReduction #14877
- [x] MuscatSofQW #14878

**Comment by OwenArnold** [comment]
CreateMD -> Matthew D Jones
AccumulateMD -> Matthew D Jones
CutMD -> Matthew D Jones 

CreateTransmissionWorkspaceAuto -> Owen Arnold
DetectorFloodWeighting -> Owen Arnold

**Comment by ElliotAOram** [comment]
IndirectFlatPlateAbsorpton -> ElliotAOram
IndirectCylinderAbsorption -> ElliotAOram
IndirectAnnulusAbsorption -> ElliotAOram
EVSDiffractionReduction -> ElliotAOram

**Comment by NickDraper** [comment]
SNSPowderReduction -> Peter Peterson
