### ISSUE TITLE
FramworkManager::Shutdown is called twice

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#14888]
When closing Mantidplot FrameworkManager::shutdown is called twice.

once from MantidUI::shutdown and once from the python API wrapper.

Nothing in there at the moment is adversly affected by this, but it could cause problems in the future.

**Comment by martyngigg** [comment]
This hasn't been an issue for MantidPlot and Workbench is structured differently so there is no benefit to looking into this.
