### ISSUE TITLE
Q-E Coverage graphs for direct geometry instruments

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#14883]
To aid planning experiments it would be useful to have plots of the detector trajectories (in Q-E space) for a given incident energy for a given instrument. Assuming powder averaging, this would require only knowledge of the minimum and maximum detector angles (and any detector gaps).

We'd like to contribute a python algorithm which does this calculation and produces a workspace with the required Q- and E-data and plots it.

**Comment by stuartcampbell** [comment]
I notice that this is only for the ISIS instruments, can it be made generic please ?

**Comment by stuartcampbell** [comment]
@AndreiSavici or @yxqd can help with it for the SNS

**Comment by mducle** [comment]
Sure! I just had the info for the ISIS detectors available more readily. The necessary info is in the instrument definition files, so I'll just look them up now... I was just lazy I guess.

**Comment by stuartcampbell** [comment]
Excellent - Thank you.

**Comment by SpencerHowells** [comment]
Would also be of use to indirect geometry instruments especially for large energy transfers.

**Comment by NickDraper** [comment]
resolved by #14997
