### ISSUE TITLE
Umbrella: Decouple Instrument View from MantidPlot

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#14890]
The ESS team requested decoupling the Instrument View tool from the main MantidPlot code base with the hope of eventually using this separately from mantidplot.

This ticket is split into two stages:
- [ ] Stage 1 - Refactor the code base so the instrument view is a separate Mantid Widget #14911 
- [ ] Stage 2 - Implement a separate executable which launches the instrument view independently of mantidplot

**Comment by SimonHeybrock** [comment]
Alternatively, if not as a stand alone executable, having it as a widget that can be included in other Qt applications might be useful.

Also consider making it available from within Python, i.e., when importing the Mantid Python API, what is missing that keeps us from using/starting the Instrument View? Maybe this is the easiest starting point (and it would get us a long way)?

**Comment by MichaelWedel** [comment]
Before I forget it, the framework I saw being used to expose C++ code to python is called [Swig](http://www.swig.org/). I have never used it though, so I can not comment whether it's easier than any of the other options (sip, boost::python).

**Comment by martyngigg** [comment]
This is now possible from both C++ & Python without requiring MantidPlot or MantidWorkbench. The code is in a separate library with a Python wrapper inside the `mantidqt` package.
