### ISSUE TITLE
StretchedExpFT peak centre is not a parameter

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#14955]
Spencer has found a bug in StretchedExpFT:
> The peak centre/origin is not a parameter.
So in a convolution where sample & resolution are offset it doesn't get it correct.

**Comment by jmborr** [comment]
I ran out of the panic mode and we're back to Release 3.6

**Comment by jmborr** [comment]
[Relase notes](http://www.mantidproject.org/ReleaseNotes_3_6_Framework_Changes#Improved_2)
