### ISSUE TITLE
Symmetry operations bugs

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#14970]
I am trying to use symmetry operations to transform some coordinates, to use them in symmetrization algorithms
```
symOp = SymmetryOperationFactory.createSymOp("x,y,z+1")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-103640a8447c> in <module>()
----> 1 symOp = SymmetryOperationFactory.createSymOp("x,y,z+1")

RuntimeError: Error in parsing symbol x,y,z+1:
Failed to parse component string z+1: Could not parse entire string. in  on line 0

symOp = SymmetryOperationFactory.createSymOp("x,y,z+10/20")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-d00995784753> in <module>()
----> 1 symOp = SymmetryOperationFactory.createSymOp("x,y,z+10/20")

RuntimeError: Error in parsing symbol x,y,z+10/20:
Failed to parse component string z+10/20: Could not parse entire string. in  on line 0

symOp = SymmetryOperationFactory.createSymOp("x,y,z+5/3")
print symOp.transformCoordinates([1.,2.,3.])

[1,2,3.66667]
```

Here are the things that need to be fixed:
1. Be able to add an integer 1 or 2 to one of the components
2. Be able to use more than one digit
3. Need to have 5/3 be 1.6667, not 0.6667

**Comment by MichaelWedel** [comment]
I think all of these might be gone with PR https://github.com/mantidproject/mantid/pull/14913. I will verify this once I'm at my workstation.

**Comment by MichaelWedel** [comment]
Okay, all of these are parsed in the branch with the new parser, but the modulo operation is still in place. I'll try to see what happens if it's removed.

**Comment by MichaelWedel** [comment]
It is possible to move the modulo operation to where it's needed for `Group` to work properly (`operator*(const SymmetryOperation &other`). That solves most of the problem. But somehow I'm not entirely satisfied with this solution, all this modulo-stuff should happen strictly within `Group` where it's actually required, so I need to look at this a bit more.
