### ISSUE TITLE
Fitting GUI tool: trying to move Bk2BkExpConvPV pops up unexpected exception window

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14982]
- Plot your favorite spectrum. 
- Start the fitting tool with the "little peak" icon
- Add a `Bk2BkExpConvPV` peak function
- It will show a vertical red line in the center of the fitting range (blue vertical lines). 
- Try to move the center line.
- You'll get the panic red pop-up of "MantidPlot has caught an unexpected exception", with description "Bk2BkExpConvPV is not allowed to set FWHM."

**Comment by alicerussell1** [comment]
This is the same as #28153 and has been fixed.
