### ISSUE TITLE
Workflow diagram for SANSWideAngleCorrection

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#15001]
The ```SANSWidgeAngleCorrection``` algorithm requires a workflow diagram

**Comment by NickDraper** [comment]
@LamarMoore Can you use the github history to find the author of this and assign it to him.

**Comment by mdoucet** [comment]
Already exists https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/SANSWideAngleCorrection-v1.rst

**Comment by NickDraper** [comment]
SANSWideAngleCorrection is not a workflow algorithm and would not benefit from a workflow diagram.
