### ISSUE TITLE
Workflow diagram for TOFSANSResolutionByPixel

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#15004]
The ```TOFSANSResolutionByPixel``` algorithm requires a workflow diagram.

**Comment by NickDraper** [comment]
@LamarMoore Can you use the github history to find the author of this and assign it to him.

**Comment by mdoucet** [comment]
Already exists: https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/TOFSANSResolutionByPixel-v1.rst

**Comment by NickDraper** [comment]
Not a workflow algroithm, therefore would not benefit from a workflow diagram
