### ISSUE TITLE
I(Q,t) Tile plot further improvement

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15010]
Spencer has reported the following:
>Thought of a possible improvement.
By definition Iqt has values in the range 0 to 1, so could you set those limits on the y-values?
This will remove the possibility of the scale being bad due to rubbish at high t values.

**Comment by SpencerHowells** [comment]
For the x- values (time), using histogram 1 find the first value of x>0 where y>1. This can then be x-max for the plot.
