### ISSUE TITLE
Documentation for fitting minimizer

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15014]
Add code to allow adding rst document for fitting minimizers, in the same way to as is done for rst documentation for fitting functions. 

For this issue it is sufficient to include rst pages for 

Simplex
SteepestDescent
Conjugate gradient (Fletcher-Reeves imp.)
Conjugate gradient (Polak-Ribiere imp.)
BFGS (Broyden-Fletcher-Goldfarb-Shanno)
Levenberg-Marquardt (default)

borrowing e.g. text from http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html. Note the above listed minimizers are all from GSL, hence these minimizers have to reference this fact.

Have rst minimizer documentation show up below 'Fit Functions' on http://www.mantidproject.org/Documentation

Further minimizer rst pages may be created in seperate issues

**Comment by Anders-Markvardsen** [comment]
This could also be a challenging new starter ticket

**Comment by mantid-roman** [comment]
I am converting some top level `tex` doc from `ral_nlls` library to `rst` to see how hard it is.
