### ISSUE TITLE
Make tests to work against believe correct mimima in WeightedLeastSquaresTest.py

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15028]
Use something like

```
CalculateChiSquared('name=Gaussian,Height=0.0994414,PeakCentre=0.000375018,Sigma=4.96144e-06;name=Gaussian,Height=0.121684,PeakCentre=0.000165893,Sigma=2.13907e-05','Slice',WorkspaceIndex=0,Output='res')
```

to find what is believe to be the minimum you would like the fitting to find.

Then in tests in WeightedLeastSquaresTest.py change so that always test against 'true' solution, this will mean that differences will be likely better as least for now

**Comment by FedeMPouzols** [comment]
Current status: more discussions with SCD numerical analysis group would be advisable before going ahead with this.

**Comment by FedeMPouzols** [comment]
I think this issue needs revisiting after the developments in the last few months.
@tom-perkins, @Anders-Markvardsen
