### ISSUE TITLE
Further maintenance work on MaxEnt

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15036]
While working on #14675, I noticed the following:
1. The norms of the gradients `sgrad` and `cgrad` are used see [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/MaxEnt.cpp#L450-L451), but not [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/MaxEnt.cpp#L471-L472). In fact, using just `sgrad` and `cgrad`, or the normalized versions, `sgrad/|sgrad`| and `cgrad/|cgrad|`, does not seem to have a relevant effect on the final results.
2. [These](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/MaxEnt.cpp#L486-L487) normalizations don't seem to have any effect either (at least when `sgrad` and `cgrad` are not normalized, which is the case I tested).

This issue is to compare results with and without normalizations. If there is no significant difference, we should not use normalizations.

Finally, [this](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/MaxEnt.cpp#L612-L616) should be removed, and an exception thrown if we can't apply the bisection method (which means that something went wrong).

**Comment by NickDraper** [comment]
Anthony I'm assigning to you in case you already have a duplicate issue or just want to hold these on the back burner
