### ISSUE TITLE
Minor changes to powder planning tool

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#15039]
In issue #14883, a pllaning tool for |Q|,E coverage was created, for direct and indirect spectrometry. Here are some small problems:

1. One should be able to find it in the Interfaces->Direct and Interfaces->Indirect instead of Interfaces->Utility. I think this can be done by adding it twice in Framework/Properties/Mantid.properties.template

2. In the indirect tab there is an Emax option, but there is no Emin for direct. 

3. There are some numbers in calcQE that should be defined as mass of the neutron, Plank's constant, etc. An even more elegant solution it would be to use scipy.constants module

**Comment by mducle** [comment]
1. It seems that adding the entry twice to Mantid.properties.template doesn't (once for Direct/ and once for Indirect/ ) doesn't work - for me it gives two entries in the last mentioned folder. E.g. if I add "Direct/QECoverage.py Indirect/QECoverage.py" it gives two entries in Indirect, and if I add "Indirect/QECoverage.py Direct/QECoverage.py" it gives two entries in Direct. 

Maybe it's better to add the direct option as a tab in DGSPlanner, and the Indirect one as a tab in Indirect/Tools?
