### ISSUE TITLE
ProcessingInstructions for selecting region on 2D Detector

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#15052]
Specify ProcessingInstructions in ReflectometryReductionOne. Currently this is done using spectrum numbers. We should be able to specify a region of interest by specifying an upper and lower set of vertexes in 2D space. For example (x1, y1), (x2, y2).

**Comment by OwenArnold** [comment]
@quantumsteve @raquelalvarezbanos This is highlighed as a SSC item that would benefit both the SNS and ISIS.

**Comment by gemmaguest** [comment]
Closing as Stale because we are unlikely to get around to this. We are moving to graphical RoI selection instead.
