### ISSUE TITLE
Dedicated guidelines for how to best test new fitting functionality

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15078]
Guidelines for adding tests exist, but currently no dedicated guidelines for how to best tests new fit functions, minimizers and cost functions, including where this is recommended tests for both for robustness and performance for example.

This issue is to add such documentation, which such be referenced (or included) in the general testing guidelines page.

**Comment by FedeMPouzols** [comment]
Related: #15028.
