### ISSUE TITLE
Indirect Data Analysis ConvFit - Tidy up ConvFit UI code

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15105]
The ConvFit.cpp Interface code has become rather cluttered. It would be good to spend some time during the maintenance period to tidy this and improve readability.

**Comment by ElliotAOram** [comment]
Unfortunately these changes are somewhat out of date. I would try to merge this with master but if it has a large number of merge conflicts it might be easier to start from scratch

**Comment by louisemccann** [comment]
It might also be worth using this opportunity to reduce output
