### ISSUE TITLE
Horizontal scrollbar in script window.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#15103]
When there are long lines in the script window, it will not scroll to the end of them using the horizontal scroll bar.

**Comment by NickDraper** [comment]
this is a known issue with qscintilla and also affects notepad2.
http://superuser.com/questions/326394/notepad2-horizontal-scrolling-issue

**Comment by NickDraper** [comment]
There is a potential partial solution that I can try, as long as it does not affect performance too much.

**Comment by NickDraper** [comment]
Note: The end of long lines can always be reached using the End key or the scrollbar arrows.

**Comment by NickDraper** [comment]
The fix I tried was setting xxx on the scintilla component, but that does not work (it still acts that same as without the fix).


  //set QScintilla to track the max line length
  //the scroll width is adjusted to ensure that all of the lines currently 
  //displayed can be completely scrolled. 
  //This mode never adjusts the scroll width to be narrower.
  SendScintilla(SCI_SETSCROLLWIDTHTRACKING, 1);

I propose we leave this as a will not fix, with noting that pressing end or using the arrow keys is a work around.
