### ISSUE TITLE
Add tiny boilerplate/example custom interface that uses MVP pattern

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15121]
Including a dummy unit test.
To promote the use of MVP in Mantid interfaces.
This was suggested at the last developer workshop.

@raquelalvarezbanos

**Comment by FedeMPouzols** [comment]
@MattKing06 , @shahrozahmed1

**Comment by raquelalvarezbanos** [comment]
Not so easy but could be a good exercise for a new starter.

**Comment by NickDraper** [comment]
dropping this as an issue, we have worked full examples in a number of interfaces
