### ISSUE TITLE
Recognise McStas wavelength unit in LoadMcStas

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15137]
LoadMcStas also loads McStas histogram data, including intensity vs wavelength histogram. However the wavelength McStas unit, called Wavelength__AA_, is not currently translated into wavelength Mantid unit. 

This causes workaround code like this:

```
# load unit test mcstas test dataset
ws          =  Load('mcstas_event_hist.h5')
binning =  '0.5,0.005,15.0' 

mcstasMonitor  =  CloneWorkspace(mtd['lmonitor3.dat_ws'])
mcstasMonitor  =  ConvertToHistogram(mcstasMonitor)
mcstasMonitor  =  rebin(mcstasMonitor, binning)
# here work around code to create workspace with Mantid unit Wavelenght
monitor                =  CreateWorkspace(mcstasMonitor.dataX(0),     
                                   mcstasMonitor.dataY(0), 
                                   mcstasMonitor.dataE(0), 
                                   UnitX='Wavelength')
```

As part of this issue 
- modify LoadMcStas to recognise McStas label for wavelength and ensure that the created workspace has UnixX='Wavelength'.
- Modify LoadMcStasTest to ensure that e.g. unit of lmonitor3.dat_ws of dataset mcstas_event_hist.h5 is Wavelenght

**Comment by gemmaguest** [comment]
Closing as stale because we are unlikely to get around to this
