### ISSUE TITLE
Indirect Bayes Quasi - Reported to be giving incorrect values

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15133]
**Issue discovered during the 3.6 Beta test period**

Spencer has reported that the BayesQuasi algorithm is producing incorrect values. Apparently the values are correct using the `QLres_win64.pyd` for Mantid release 3.5.

I believe this issue is most likely linked to the changes made in #14476

**Comment by martyngigg** [comment]
@ElliotAOram I thought we checked with Spencer about those changes?

**Comment by martyngigg** [comment]
Closing manually as it was merged with the release branch
