### ISSUE TITLE
Expand fitting interface to support 2nd derivatives

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15210]
Open up the fitting interface to allow minimizers to use 2nd derivatives of fitting functions when specified in the fitting function

**Comment by NickDraper** [comment]
Do we have an example that needs this, as we should not do the extension until we do.

**Comment by Anders-Markvardsen** [comment]
The SCD Numerical group have the strong opinion that having support for 2nd derivatives could provide a major benefit where these can be provided analytically.

However I agree, let us see how the current testing and integration of SCD minimizer evolves first and where relevant this issue can be reopened
