### ISSUE TITLE
C++11 Use unordered containers where possible

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15287]
Check for places where we should be using `std::unordered_meow` instead of `std::meow` (`meow = {set,multiset,map,multimap}?`)

**Comment by matthew-d-jones** [comment]
Note, detector IDs are a major use of sets, but they are expected to be ordered in many places.

**Comment by matthew-d-jones** [comment]
I've split `map` to `unordered_map` into a separate ticket, to make this one a more manageable size.
