### ISSUE TITLE
C++11 use std::mutex

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15288]
Move Poco::Mutex, Poco::FastMutex, boost::mutex,... to std::mutex.

**Comment by picatess** [comment]
Scoping out the work:

__`Poco::Mutex` --> `std::recursive_mutex`__

[`Poco::Mutex`] (http://www.appinf.com/docs/poco/Poco.Mutex.html) appears to be recursive and hence maps into [`std::recursive_mutex`](http://en.cppreference.com/w/cpp/thread/recursive_mutex)

__`Poco::FastMutex` --> `std::mutex`__

[`Poco::FastMutex`](http://www.appinf.com/docs/poco/Poco.FastMutex.html) is not recursive and hence maps into [std::mutex](http://en.cppreference.com/w/cpp/thread/mutex)

__`Poco::ScopedLock` --> `std::lock_guard`__

[`Poco::ScopedLock`](http://www.appinf.com/docs/poco/Poco.ScopedLock.html) is a load-and-forget RAII-style lock which should map to [std::lock_guard](http://en.cppreference.com/w/cpp/thread/lock_guard)

**Comment by NickDraper** [comment]
Anton,  It is possible that Poco::Mutex was used in places when FastMutex would have sufficed.
