### ISSUE TITLE
Set a consistent policy for symbol visibility on all platforms. Currently on MSVC hides symbols by default.

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15283]
Currently on MSVC hides symbols by default.

Set [`CXX_VISIBILITY_PRESET`](https://cmake.org/cmake/help/v2.8.12/cmake.html#prop_tgt:LANG_VISIBILITY_PRESET) to `hidden` for gcc/clang and fix the builds.

**Comment by AntonPiccardoSelg** [comment]
As a first step two things were established:

1. `set(CMAKE_CXX_VISIBILITY_PRESET hidden CACHE STRING "")` was added to `CommonSetup.cmak`
2. `System.h` was altered to take the gcc and clang settings into account.

This results in issues relating setting the visibility attribute on explicit template instatiations: `warning: visibility attribute ignored` and `warning: attribute ignored in explicit instantiation`

This seems to have been a problem for a long time (~2004 until now):

gcc forums:
* [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=17470)
*  [here](https://llvm.org/bugs/show_bug.cgi?id=24815)
*  [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51930)
