### ISSUE TITLE
Resolve issues for CPPcheck 1.72

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15281]
http://builds.mantidproject.org/view/Static%20Analysis/job/cppcheck-1.72/

**Comment by raquelalvarezbanos** [comment]
I only spotted an unused member variable (https://github.com/mantidproject/mantid/pull/15340). Many of the issues that were picked up by cppcheck1.71 are not real issues (see for instance [this](http://builds.mantidproject.org/view/Static%20Analysis/job/cppcheck-1.72/1019/cppcheckResult/source.34/#480) or [this](http://builds.mantidproject.org/view/Static%20Analysis/job/cppcheck-1.72/1019/cppcheckResult/source.26/#56)). The remaining ones, I am not really sure, so I am leaving this ticket unassigned in case other developers want to work on this.

**Comment by quantumsteve** [comment]
@AndreiSavici How did you recommend changing the V3D and VMD wrappers that both provides better documentation from python and eliminates the cppcheck warnings?

**Comment by AndreiSavici** [comment]
See https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/mantid/kernel/src/Exports/Quat.cpp
```
      .def("__add__", &Quat::operator+, (arg("left"), arg("right")))
      .def("__iadd__", &Quat::operator+=, boost::python::return_self<>(),
           (arg("self"), arg("other")))
```
