### ISSUE TITLE
Add the [`-Wsuggest-override`] and fix warnings

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15284]
Add the [`-Wsuggest-override`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) flag when building with GCC 5.1 or later and fix resulting warnings. Consider doing the same for `-Wsuggest-final-types` and `-Wsuggest-final-methods`.

**Comment by BhuvanBezawada** [comment]
**Closing Issue**
The `-Wsuggest-override` flag is present when building with GCC 5.1 or later and there are no resulting warnings. 

**Extra notes**
Decided that the `-Wsuggest-final-types` and `-Wsuggest-final-methods` flags are not really required and it is probably best to just remove them.
