### ISSUE TITLE
C++11 use std::array if size known at compile time

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15291]
Are there places where std::array (size known at compile time)  is more appropriate than std::vector (size known only at runtime)?

**Comment by martyngigg** [comment]
@raquelalvarezbanos Is there still more work to do on this one or can we close it and I'll remove it from the maintenace tasks list?

**Comment by raquelalvarezbanos** [comment]
No that I know. Although I haven;t checked new code added since that PR was closed.

**Comment by martyngigg** [comment]
I think this is okay just covering the old stuff. Hopefully reviews of new code should catch those circumstances.

Let's close this and I'll remove it from the maintenance tasks list as done. Thanks.

**Comment by raquelalvarezbanos** [comment]
OK, thanks Martyn.
