### ISSUE TITLE
Fix bug in vtkMDHexFactory which causes 3D slices of higher dimensional workspaces to not contain any points

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#15295]
vtkMDHexFactory expects zero thickness slices to contain data, due to the strange implementation of MDPlanes before #15209. Previous to that PR it would actually return a slice 2 bins thick if the two MDPlanes defining the slice coincide with a bin boundary and 1 bin thick otherwise.

Defining the higher bound plane (the one with the -ve normal) as lying on the next highest bin boundary would solve the problem. NB, efficiency is important as the slicing procedure is repeated many times, for example to create a movie when the 4th dimension is time.

**Comment by martyngigg** [comment]
@matthew-d-jones Is this the cause of the performance test segfault?

**Comment by matthew-d-jones** [comment]
@martyngigg yes

**Comment by martyngigg** [comment]
Good that you found that. Is it possible to implement a standard unit test to show the bug rather than it showing up in the performances tests?

**Comment by matthew-d-jones** [comment]
Yes, will do.

**Comment by martyngigg** [comment]
:+1:
