### ISSUE TITLE
There is no documentation page for the fit function Bk2BkExpConvPV

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15353]
I can't find the RST page for this function: https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/src/Functions/Bk2BkExpConvPV.cpp
But there is this old wiki page for it: http://www.mantidproject.org/BackToBackExponentialPV

There is an RST page for `NeutronBk2BkExpConvPVoigt`, which should not be confused with `Bk2BkExpConvPV`.

**Comment by FedeMPouzols** [comment]
@Anders-Markvardsen : I think this is the case probably for more fit functions. I also came across this wiki page for example: http://www.mantidproject.org/CreateBackToBackParameters which I'm not sure is easy to find or linked from anywhere.

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols There is a link to http://www.mantidproject.org/CreateBackToBackParameters from http://docs.mantidproject.org/nightly/fitfunctions/BackToBackExponential.html
