### ISSUE TITLE
C++11 Use unordered_map where possible

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#15370]
Check for places where we should be using `std::unordered_map` instead of `std::map`.

The same procedure for other containers was carried out for #15287

**Comment by NickDraper** [comment]
completed by #15382

**Comment by SimonHeybrock** [comment]
That PR does not seem to include changes for `unordered_map`, so I guess this should be reopened.

**Comment by FedeMPouzols** [comment]
Note that one very core place where a change `std::map` => `std::unordered_map` probably makes sense is `DataService`, as discussed in #16967.

**Comment by NickDraper** [comment]
archived
