### ISSUE TITLE
EQSANSNormalisationAPI system test fails with Poco 1.6

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#15387]
After building Mantid with Poco 1.6.1, the system test `EQSANSNormalisationAPI` fails CheckWorkspacesMatch. So far it appears that the final X value (5.44 vs 5.45), , the spectrum number (0 vs 1), and the instrument parameter map differ. There may be more differences.

Our best guess is that the issue appears in `EQSANSLoad.cpp` with one of  the Poco functions.

**Comment by rosswhitfield** [comment]
[Here](http://builds.mantidproject.org/view/All/job/master_clean-archlinux/215/testReport/) are all the failing test running on Arch with poco `1.6`.
