### ISSUE TITLE
Convert code to an algorithm

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#15380]
The code in [MantidUI::createDetectorTable](https://github.com/mantidproject/mantid/blob/f659a809fd44851b75af5f1d86431e80e13d66a0/MantidPlot/src/Mantid/MantidUI.cpp#L1177) to an algorithm. Also, rename the columns for the angles to `polar` and `azimuthal` and drop the `Index` (read: workspace index).

**Comment by AndreiSavici** [comment]
See if PreprocessorDetectorsToMD is doing the job

**Comment by peterfpeterson** [comment]
That does appear to be close enough. We should give it a more sensible name though.
