### ISSUE TITLE
Give users page delete permission on the wiki

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15384]
From mediawiki help
https://www.mediawiki.org/wiki/Manual:User_rights

## Changing group permissions
A default MediaWiki installation assigns certain rights to default groups (see below). You can change the default rights by editing the $wgGroupPermissions array in LocalSettings.php with the syntax.

'''
$wgGroupPermissions['user']['delete'] = true /* or false */;
'''
Note Note: In a default installation $wgGroupPermissions will be set in DefaultSettings.php, but it is not present in LocalSettings.php. You will then need to add it in that file.

If a member has multiple groups, they get all of the permissions from each of the groups they are in. All users, including anonymous users, are in the '*' group; all registered users are in the 'user' group. In addition to the default groups, you can arbitrarily create new groups using the same array.

**Comment by martyngigg** [comment]
I've updated the settings but with

```
# Allow email-confirmed users to delete pages
$wgGroupPermissions['emailconfirmed']['delete'] = true;
```

instead as we only allow email-confirmed users to edit pages.
