### ISSUE TITLE
MDImageWorkspace step 0: add IMDLeanGeometry

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15418]
This was implicit in #14165. Splitting it into a separate issue/PR to keep the diffs small.
Add an interface for the basic stuff common to MDLeanGeometry and MDGeometry.
Follow [Design document](https://github.com/mantidproject/documents/blob/master/Design/Imaging_IMAT/Workspace_type_for_stacks_of_images.md), diagram in approach 1.

**Comment by martyngigg** [comment]
The 115418_MDImageWorkspace_step0_add_IMDLeanGeometry1 branch still exists but I have closed the PR to avoid clutter with other tasks that are being worked on.

**Comment by DimitarTasev** [comment]
Closing via https://github.com/mantidproject/mantid/issues/15437
