### ISSUE TITLE
MDImageWorkspace step 2: add IMDLeanWorkspace

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15419]
Inherits from Workspace and MDLeanGeometry (#14165)

Follow [Design document](https://github.com/mantidproject/documents/blob/master/Design/Imaging_IMAT/Workspace_type_for_stacks_of_images.md), diagram in approach 1.

Next step: IMDLeanHistoWorkspace, and MDLeanHistoWorkspace.

Uses/depends on:
- [ ] #14165

**Comment by DimitarTasev** [comment]
Closing, reasons in https://github.com/mantidproject/mantid/issues/15437
