### ISSUE TITLE
MDImageWorkspace: implement and expose to Python - umbrella

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15437]
An umbrella issue for MDImageWorkspace tickets and related ones.
- [ ] #15418 - IMDLeanGeometry
- [ ] #14165 - MDLeanGeometry
- [ ] #15419 - IMDLeanWorkspace
- [ ] ? IMDLeanHistoWorkspace
- [ ] ? MDLeanHistoWorkspace
- [ ] ? IMDImageWorkspace and MDImageWorkspace
- [ ] ? Expose to Python

**Comment by DimitarTasev** [comment]
TODO will be moved to an individual project as this will be a major change

**Comment by DimitarTasev** [comment]
This is unlikely to be implemented. The default data type for workspaces is double (64bits) which makes it very inefficient to deal with large stack of images.

The problem with having X and E dimensions can be solved by sharing an empty vector across.
The problem with having double as a default type remains to be solved, and might require templating _every_ workspace class.

I am closing this issue, if any works is to be done on this in the future the design has to be rethought and redone to account for the large datasets (~20GB), as it currently does not.
