### ISSUE TITLE
Super-WISH instrument definition

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15435]
From Pascal:

> I think I talked before about getting a super-WISH instrument definition so we could see all the reflections that we are missing. Ideally we would be able to load the actual WISH data onto it but it would havbe much more out of plane coverage. 
> One feedback from my users is that it would be nice to give the angles between reflections selected by clicking. This would be the actual angles and also in plane and out of plane angles.

**Comment by samueljackson92** [comment]
To further clarify this: this is basically just expanding the instrument definition file for WISH to include a fuller range of angles. Contact him for the specifics.

**Comment by samueljackson92** [comment]
With the above two PRs merged this is now finished.
