### ISSUE TITLE
Engg GUI: plot the two (n) vanadium curves, and the two (n) difc-zero fits in a multi-panel figure

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15447]
As planned in #13377:
- first, expose the two vanadium fit results
- then plot everything in a single multi-figure.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1 : I found this issue when checking my list of issues for 3.7.
So this would be a duplicate of the newer #16151 that you opened.

**Comment by DavidFair** [comment]
Closed in #16229 and being worked on in #12927 so closing this as duplicate.
