### ISSUE TITLE
Prototype L2, and Theta Cache

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#15501]
A Required experiment for the [Geometry Milestone](https://github.com/mantidproject/documents/blob/master/Design/Instrument-2.0/milestone1.md).

Attempt to lazy-calculate common information required for detector based calculations and cache it. 

The output of this will be some performance metrics and the performance test.

**Comment by OwenArnold** [comment]
<img width="256" alt="screen shot 2016-03-01 at 11 48 38" src="https://cloud.githubusercontent.com/assets/1109536/13426160/a40873fc-dfa3-11e5-9fad-4e964337c965.png">
Results show pretty much what I would expect. We also don't seem to pay much for the initial cache. Results shown are for the new Peformance test suite in `GeometryInfoTestPerformance`

**Comment by OwenArnold** [comment]
<img width="473" alt="screen shot 2016-03-02 at 12 47 37" src="https://cloud.githubusercontent.com/assets/1109536/13460780/1ac9ecc4-e075-11e5-9252-ba6899f92773.png"> Updated results with locking

**Comment by OwenArnold** [comment]
Caching does not appear to provide a large improvement when the l2 calculations are trivial. However, when several components appear in the path 4-or more, the ability to cache can save a large number of vector operations.

**Comment by OwenArnold** [comment]
@SimonHeybrock Any suggestions on other things to try along these lines?

**Comment by SimonHeybrock** [comment]
@OwenArnold I think it might make sense to consider this problem as 2 separate aspects:
1. The main contribution to the current high cost is creation of the instrument and detectors, and searching parameter maps, etc., for every single lookup. This should definitely be eliminated.
2. The cost of the actual geometric computation, e.g., calculation of distances between points in space.

**Comment by OwenArnold** [comment]
I'm closing this because this prototype has reached a dead-end. Interesting to do, but not worth further investigation. I'm instead focusing on the eliminated parameter map approach prototypes at present.
