### ISSUE TITLE
Crash when removing detector IDs in MuonAnalysis

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15514]
To reproduce:
- Open the MuonAnalysis interface and load a dataset
- Go to "Grouping Options" and remove the detector IDs in one of the groups in the "Group Table". Hit enter or click in the next group
- Mantid crashes

**Comment by tom-perkins** [comment]
Can't reproduce this bug any more - perhaps it has been fixed in the meantime.
When I remove the detector IDs in a group, it plots another group instead and does not crash.
