### ISSUE TITLE
SumSpectra wrong for weighted case

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#15525]
The weight factor for a bin is only factored in when there was *no* spectrum that had zero error in that bin:

`SumSpectra.cpp`:
```cpp
  if (m_calculateWeightedSum) {
    numZeros = 0;
    for (size_t i = 0; i < Weight.size(); i++) {
      if (nZeros[i] == 0)
        YSum[i] *= double(numSpectra) / Weight[i];
      else
        numZeros += nZeros[i];
    }
  }
```

**Comment by Jon-Taylor** [comment]
for example (using Mari run 19851)

Load(Filename='/Users/jonathantaylor/Dropbox/Glyde_March_2015/RawData/MAR19851.raw', OutputWorkspace='MAR19851')
SumSpectra(InputWorkspace='MAR19851', OutputWorkspace='weighted4', StartWorkspaceIndex=3, EndWorkspaceIndex=20, IncludeMonitors=False, WeightedSum=True)
weighted4=mtd['weighted4']
print weighted4.getRun().getLogData("NumAllSpectra").value
print weighted4.getRun().getLogData("NumMaskSpectra").value
print weighted4.getRun().getLogData("NumZeroSpectra").value



SumSpectra(InputWorkspace='MAR19851', OutputWorkspace='weighted5', StartWorkspaceIndex=4, EndWorkspaceIndex=20, IncludeMonitors=False, WeightedSum=True)
weighted5=mtd['weighted5']
print weighted5.getRun().getLogData("NumAllSpectra").value
print weighted5.getRun().getLogData("NumMaskSpectra").value
print weighted5.getRun().getLogData("NumZeroSpectra").value

Weighted4 is rubbish as one spectra in the list (the first one) is all zero so no weight is applied
![screen shot 2016-03-03 at 13 34 01](https://cloud.githubusercontent.com/assets/1134721/13494799/eb3991da-e146-11e5-929c-01f2206e90d0.png)
