### ISSUE TITLE
Review ReflectometryReductionOne workflow diagram

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15534]
While testing #15075 I noticed a couple of issues in the workflow diagram:
- Looking at the diagram it seems that we only apply transmission corrections if the input workspace is not in `lambda` (which I think is not correct)
- I find the transmission correction process a bit unclear
- The last step, after `ConvertUnits` should be `RotateSource` again (we are rotating the source back to its original position).

This issue is to review the workflow diagram and update it if necessary.

**Comment by MattKing06** [comment]
@OwenArnold would it be possible to ask you a few questions on this workflow diagram as I believe you have the most experience with the algorithm?

**Comment by raquelalvarezbanos** [comment]
@MattKing06: see issue #15565
