### ISSUE TITLE
Absorption for generic geometries -  Improve UI, handling can materials etc

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15543]
The UI should focus on letting the use select from a list of possible geometries of sample holders etc.  This may be central, central and filtered by instrument, or instrument specific (yet to decide).  The sample in a cynlindrical sample holder the sample depth would need to be entered, but most other things can be defined in advance.

There are some anvil shapes on this tickety for PEARL #3119

**Comment by martyngigg** [comment]
Contributing issues:
* #15770

**Comment by NickDraper** [comment]
Martyn, is this done now?
What is left?

**Comment by martyngigg** [comment]
Spencer has requested a few improvements (#17194 & #17801) but the core features are there. 

I think we can mark this done.
