### ISSUE TITLE
Implement VSI defaults for the sliceviewer & save state

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15548]
Anton did a lot of work applying good defaults for the color map ranges, initial data presented, normalization etc for the VSI.

Ensure this is also in place for the sliceviewer.  Talk to Anton about this, also ensure that the sliceviewer saves state position etc, so that if closed and reopened (and the data is still available) it returns to the same state.

**Comment by martyngigg** [comment]
The new sliceviewer has many fewer options. Closing while new sliceviewer gets road tested and it becomes more apparent if any per-technique/instrument defaults are required.
