### ISSUE TITLE
Detector space integration

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15546]
For Sam Jackson

Work with Laurent to bring detector space integration into Mantid

**Comment by samueljackson92** [comment]
We will need to get in contact with Laurent to move forward with this, but Pascal was able to offer so words about this at our meeting:

- Early work was done on this but swapped to Q space. He believes any existing algorithms are now probably broken.
- This is not necessarily essential for him, but will be highly desirable for getting newer instruments on board hence this should be high priority, but is likely to be a longer term project.
