### ISSUE TITLE
Add MaxEnt ComplexImage algorithm property

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#15553]
Add ComplexImage algorithm property to MaxEnt algorithm.

The present the entropy is calculated both for real and imaginary part. In some cases this is what you want but for example 1. if you wanted reconstruct a charge density from measured structure factors then you know that it is not physical to have imaginary charge density. 2. in some cases the Muon users know that the only real frequencies should be generated. 

Therefore add ComplexImage property which default to False if ComplexData is False, and defaults to True if ComplexData is True.

If ComplexImage is False then don't include the imaginary part of the image in calculating the entropy, and when calculating data from an image simply, and where a complex FFT is used, simply ensure that the imaginary part of the image is zero

This issue created during testing of #15494

**Comment by raquelalvarezbanos** [comment]
Thanks @Anders-Markvardsen, I'll fix this after #15265 (as I already started doing some work on that).
