### ISSUE TITLE
Engg GUI: add tab for single peak fitting

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15550]
A new tab for (single) peak fitting. The underlying functionality is already in the algorithm `EnggFitPeaks`. This is about adding a convenient interface integrated in the Engg GUI to run fits and display their results.

A mock-up for this was done in #15372. Follow the ideas from the discussion last week with ENGIN-X scientists.

**Comment by shahrozahmed1** [comment]
For the "pick peak" functionality, the [ALCPeakFitting interface](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Muon/ALCPeakFittingView.h) has good examples of use of the widgets that probably will cover all our needs: `QwtPlotCurve`, `MantidWidgets::PeakPicker`, and maybe `MantidQt::MantidWidgets::ErrorCurve`.
