### ISSUE TITLE
parameterize the QSettings subgroup for FitPropertyBrowser

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#15579]
`QVariant` settings for class `FitPropertyBrowser` are stored in  subgroup `"Mantid/FitBrowser/"`. When subclassing `FitPropertyBrowser`, `QVariant` settings should be permitted to be stored in a different subgroup.

One possible solution is to add a member `m_qsettings` for `FitPropertyBrowser` that could be initialized with a different string for the subclass.

**Comment by jmborr** [comment]
@FedeMPouzols @mantid-roman What do you think of this issue and the proposed solution? I plan to subclass `FitPropertyBrowser` but I want to store the `QSettings` in a different place than `"Mantid/FitBrowser"`

**Comment by mantid-roman** [comment]
I think that FitPropertyBrowser should be deprecated and FunctionBrowser should be used instead.

**Comment by jmborr** [comment]
@mantid-roman I briefly took a look. The main difference I noticed is the ability to set "global" parameters. Are there other differences with the FitPropertyBrowser?

**Comment by mantid-roman** [comment]
FitPropertyBrowser is a complete widget for fitting spectra from matrix workspaces. It's heavy, not very clean and difficult to change. FunctionBrowser on the other hand is a control for building functions only. It can be supplemented by FitOptionsBrowser (or its subclass) to set other fit properties. See MultiDatasetFit as an example of their use.

**Comment by jmborr** [comment]
Sounds good. I'll use these in place of FitPropertyBrowser. Thanks for pointing them out.
