### ISSUE TITLE
Integration of modelling packages

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15570]
Integration of modelling packages such as Rascal.

This was marked as low priority. No initial estimate was given as needs clarification from scientists (how many modelling packages, for instance).

**Comment by raquelalvarezbanos** [comment]
It is not clear that scientists want to integrate this into Mantid. They may just want to be able to import/export results (which I think they can currently do up to a point)

**Comment by gemmaguest** [comment]
Closing this as we don't plan to do it and we already plan to improve saving outputs (#24429)
