### ISSUE TITLE
EventList::sortPulseTimeTOF() wrong for weighted case?

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#15593]
`EventList.cpp` function `void EventList::sortPulseTimeTOF() const` (around line 1320):

```cpp
void EventList::sortPulseTimeTOF() const {
  // [...]

  switch (eventType) {
  case TOF:
    std::sort(events.begin(), events.end(), compareEventPulseTimeTOF);
    break;
  case WEIGHTED:
    std::sort(events.begin(), events.end(), compareEventPulseTimeTOF);
    break;
  // [...]
  }
}
```

The `WEIGHTED` case should probably read `std::sort(weightedEvents.begin(), weightedEvents.end(), compareEventPulseTimeTOF);`?

@martyngigg

**Comment by peterfpeterson** [comment]
I agree that this appears to be a real bug.

**Comment by martyngigg** [comment]
@SimonHeybrock Could I pass this over to you?
