### ISSUE TITLE
Data export to Origin

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15595]
The muon group raised this but it needs to be general.

Look at ways to make it easy to export Mantid graphs and data to origin.

QTIplot had some origin project saving code that we do not use and is quite old.  However it would be worth looking at it.

**Comment by tom-perkins** [comment]
Roadmap: No estimate yet as this needs discussion with scientists

**Comment by tom-perkins** [comment]
Roadmap target is release 3.9

**Comment by Anders-Markvardsen** [comment]
For temporary solution can save to ascii
