### ISSUE TITLE
Synchronize the  viewpoints of different tools

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15604]
Synchronize the  viewpoints of different tools (3D view, SliceView, ?Inst view, ?2D plots). 

Link the different views of the same data. This was one of the requirements from single crystal (Christina Hoffmann & Pascal). Much emphasis from Garrett, Pascal, Christina. 

Note: in discussions next day, a ""synchronize"" button was seen as a good option, as you don't always want continuous, real-time sync between plots."

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92 This is again something that Pascal would like to have. I think we have this event on the Roadmap for this year. Again, if assigning you is not appropriate, feel free to reassign.
