### ISSUE TITLE
Vesuvio: Agree scripts giving expected results

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#15663]
The change in normalization ranges that was implemented when trying to load 2/3 period data has resulted in the output parameter values being significantly different from before that change.

We need to discuss and agree with Matthew & Giovanni what the expectation is.

**Comment by ElliotAOram** [comment]
This is now okay to close. Matthew and Giovanni seem to be happy with the output after the normalization window change and as far as I am aware, are happy with load Vesuvio output in it's current state
