### ISSUE TITLE
Vesuvio - Change Vesuvio Specific algorithm to all start with Vesuvio 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15729]
Currently some of the Vesuvio algorithms are prefixed with EVS rather than Vesuvio. After a discussion with the instrument scientists for Vesuvio it has been decided that changing them all the start with the prefix Vesuvio will be more consistent and be less likely to confuse users.

* [x] EVSDiffractionReduction
* [x] CalculateGammaBackground
* [x] CalculateMSVesuvio

**Comment by martyngigg** [comment]
There are a couple of algorithms that are still specific to vesuvio but don't carry the prefix. We should probably normalize those too: 
* CalculateGammaBackground
* CalculateMSVesuvio

**Comment by ElliotAOram** [comment]
Great. I'll sort those out too! Thanks

**Comment by ElliotAOram** [comment]
External references to these algorithms will also need to be updated
