### ISSUE TITLE
Two unit tests unstable/failing on win7 debug: VesuvioCorrectionsTest, SliceViewerPythonInterfaceTest

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15732]
These two unit tests are persistently failing in the nightly win7 debug builds:
```
PythonAlgorithms_VesuvioCorrectionsTest_Debug (Timeout)
SliceViewerMantidPlotTest_SliceViewerPythonInterfaceTest_Debug (OTHER_FAULT) 
```
Investigate and fix if needed.

**Comment by DanNixon** [comment]
The Vesuvio correction algorithms do take a long time, I can only think the performance difference between release and debug is causing the timeout.

**Comment by FedeMPouzols** [comment]
A more specific issue has been openend for the SliceViewer test: #16694. VesuvioCorrections was turned into a system test and it's not an issue. This ticket can be closed.
