### ISSUE TITLE
Vesuvio - Vesuvio Resonance Algorithm

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15730]
The instrument scientist on Vesuvio have requested an option to load data and sum all the periods together with a normalisation by the monitor.

One implementation of this would be to add this a separate algorithm. Another option is to have it as another mode of operation in LoadVesuvio.

**Comment by martyngigg** [comment]
@ElliotAOram Doesn't the current algorithm already normalize by the monitor?

**Comment by ElliotAOram** [comment]
@martyngigg It does but I think the emphasis is more on just summing all the periods together (e.g. no differencing at the end). I think it'd be good if I understand the use case for this more before implementing. I'll talk to Matthew and Giovanni to find out more details.

**Comment by martyngigg** [comment]
@ElliotAOram I see. If that is the case then it seems like the best way is probably extending `LoadVesuvio`.  We could do that by simply having an extra Difference mode in the list of `None`?

**Comment by ElliotAOram** [comment]
I agree that sounds like the most sensible option.

**Comment by martyngigg** [comment]
I think we also need to think about refactoring the `LoadVesuvio` code into some separate classes/modules too. There is already quite a lot of different logic in there. With this option we'll basically have 3 possbible mode types:
* `FoilIn`/`FoilOut` mode for diffraction
* `Single`/`Double`/`Thick` modes for differencing
* `None` for plain summing

and I think it would be good to try and keep the code separate for doing these things.

**Comment by ElliotAOram** [comment]
I think that'll make things a lot clearer going forward. I'll write up an issue for this
