### ISSUE TITLE
Vesuvio - Refactor LoadVesuvio based on operations

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15733]
The `LoadVesuvio` algorithm is very large and contains a lot of logic that might be best separated for readability and maintenance.
Martyn has suggested separating these into modes of operation which seems like the most logical choice:
- FoilIn/FoilOut mode for diffraction
- Single/Double/Thick modes for differencing
- None for plain summing

**Comment by martyngigg** [comment]
With the current defined tasks for the year this does not seem like a good use of resource.
