### ISSUE TITLE
Scroll wheel button can be used to paste into the script output

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#15736]
### Expected behavior
Contents of script window cannot be changed by any means.

### Actual behavior
Text can be pasted into the output window.

### Steps to reproduce the behavior
- Run a script that outputs something
- Copy some text (from anywhere) into the clipboard
- Put the cursor into the output window and click the scroll wheel mouse button

### Platforms affected
Found on Ubuntu 14.04, probably all

**Comment by NickDraper** [comment]
Not reproducable on windows, this is a linux mouse shortcut
