### ISSUE TITLE
Umbrella Ticket for GroupDetectors 

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#15752]
I have witnessed 2 issues with GroupDetectors now but I am sure there will be more to find. 
This issue is an umbrella ticket to review GroupDetectors and how it is using the properties provided to it.

- [ ] #15749 Regarding "GroupingPattern" property
- [ ] #15750 Regarding "SpectraList" property

**Comment by MattKing06** [comment]
@raquelalvarezbanos FYI

**Comment by PranavBahuguna** [comment]
As #15750 is no longer open, this is no longer an umbrella ticket and will be closed as a result.
