### ISSUE TITLE
Fix some issues found in the Reflectometry GUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#15807]
While working on #14921 I noticed the following issues:
1. Open the interface and select the first row without adding any information (i.e. select and empty row). Then click on "Plot", the interface crashes. The same happens if you try to plot an empty group.
2. Rounding options do not seem to be working: I've tried loading POLREF00014963. The "Angle" column is populated with "1.500002" although in the reflectometry options > Rounding, the number of decimal places is set to 3. Warning options do work.
3. Items in the blacklist can be used in the reduction. For instance, if you type in ThetaIn=0.7 in the "Options" column, that value will be used instead the value provided in the column "Angle". The same happens for the rest of the properties.

**Comment by MattKing06** [comment]
Scientists have stated that the interface will need a redesign anyway as they wish to add more features to it, so this issue will no longer be needed.
