### ISSUE TITLE
Possible bug with dimension labelling in CutMD

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#15846]
Dimension labels in the output workspace from CutMD can contain eta, zeta and xi rather than h,k,l, even when the output is in RLU.
It should be checked whether this is intended behaviour.

See Andrei's comment in #15762.

**Comment by AndreiSavici** [comment]
This issue should be discussed in a VATES meeting. Some feedback from instrument scientist is needed (Toby?)
