### ISSUE TITLE
LoadSNSspec documentation (and code) is duplication of LoadSpec

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#15863]
`LoadSNSspec` seems to load histogram data, i.e., X-length is Y-length + 1. This is not documented (in fact the documentation seems to be a plain copy of `LoadSpec`, which loads point data, i.e., X-length is Y-length).

Looking at the code there is a large overlap of the two algorithms, and it should not be hard to reduce this.

**Comment by NickDraper** [comment]
Pete, what do you want to do about this?

**Comment by peterfpeterson** [comment]
It looks like these could/should be merged into a single algorithm with an extra parameter about whether the result should be a histogram or density.
