### ISSUE TITLE
ISIS sans GUI for new back end

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15876]
Pre requisiste: #15875

This is to create a new ISIS SANS gui for the refactored back end created in #15875 

Requirements:
1. This should be created seperately from the existing GUI
1. All operations (reduction, centre finding etc) should be able to output the python used to perform the operation (consider "Py" buttons and python notebook creation).
1. Batch processing should be the main mechanism for input, not single file analysis.

- [x] Create barebone GUI #19955
- [x] Add masking tab
- [x] Add "Add Runs"  tab
- [x] Add Beam Centre Finder tab
- [x] Add diagnostics tab

**Comment by gemmaguest** [comment]
@Mantid-Matthew, I've just noticed that the Python code generated by the Output Notebook option on the new SANS GUI gives this error when you run the notebook: `NameError: name 'SANSGuiDataProcessorAlgorithm' is not defined`.

**Comment by DavidFair** [comment]
Closing this as completed, we have a new ISIS SANS GUI written in Python for a while
Any additional issues should be opened separately
