### ISSUE TITLE
Quality Plan

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#15886]
Some sections of the [Quality Plan](https://github.com/mantidproject/documents/blob/master/Project-Management/QP.docx) are out of date. For example reference to `Trac` in section 2.5

Other potential issues:
- Lot of reference to Tessella internal QA documents be inaccessible
- Lots of specific references to Tessella project files that will be inaccessible 
- No mention of developer workflow (I wouldn't expect a lot of detail), just a link to the wiki page.

STFC would like In-kind projects to have quality plans and for **Data Streaming** and **LDV and Instrument Control** we need to cross reference to an accurate Mantid QP.

**Comment by NickDraper** [comment]
This is completed in npd/9416

**Comment by OwenArnold** [comment]
@NickDraper we should talk about this.
