### ISSUE TITLE
Stitch1D does not propagate x-errors

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#15881]
Reported at the SNS, but easy enough to verify if you provide InputWorkspace containing x-errorss. This is a Workflow Algorithm so sub-algorithms should handle modifications to x-errors. They should be propagated into the OutputWorkspace. Please check final implementation with @AntonPiccardoSelg as he has some experience getting this right.

**Comment by gemmaguest** [comment]
I think this should be looked at as part of #18824
