### ISSUE TITLE
SetSampleMaterial from LoadCIF

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#15891]
Since the sample material (except for isotopes) is declared in the CIF file, (optionally) execute `SetSampleMaterial` at the end of the algorithm.

**Comment by MichaelWedel** [comment]
Yes, that seems like a good idea. I'll take a look at the documentation for `SetSampleMaterial`. I suppose the chemical composition can be constructed directly from `CrystalStructure` (assuming the atoms are defined correctly). That way it would be directly available in the C++ layer as well as soon as a `CrystalStructure`-object is around.
