### ISSUE TITLE
ConvertUnits should set the EMode as a property on the workspace

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#15922]
Running `ConvertUnits` for `Direct` mode currently stores the `Ei` in the experimental logs but does not set the EMode on the ExperimentInfo object. It would be useful to be able to detect this at a later stage rather than requiring each algorithm to pass in the same parameters.

**Comment by SpencerHowells** [comment]
The Direct users use Ei and do not set Efixed either!  Lots of our routines then don't work. I've already had to point this out to Marina Ganeva for the TofTof data at Munich.
