### ISSUE TITLE
LoadNexusLogsTest to test loading of measurement info

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#15928]
LoadNexusLogs has a function loadAndApplyMeasurementInfo. This function is not called by the unit test. Add unit test to test this.

This has become a concern, because the behaviour of this function needs to be documented in issue #15607 .

**Comment by NickDraper** [comment]
@KarlPalmen I suggest you have a go at this yourself

**Comment by KarlPalmen** [comment]
Investigation of this function reveals that it is more private than a standard private function. It does not appear in any header file and is defined within an anonymous namespace. Therefore I conclude that no unit test is needed for this function.
