### ISSUE TITLE
Difference in boost Gaussian distributed random number generation

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15937]
### Expected behavior
- `boost::variate_generator<boost::mt19937 &, gaussian_double>` should produce the same random numbers between versions of boost.
### Actual behavior
- The random numbers generated are different depending on the version of boost hence different operating systems are producing different result for tests on algorithms that use the Guassian random generator
### Steps to reproduce the behavior
- Currently this is guarded against in the [VesuvioCalculateMSTest](https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/test/Algorithms/VesuvioCalculateMSTest.h#L43) as well as the VesuvioCorrectionsTest. The difference can be observed by removing these guards and running on OSs with different boost version.
### Platforms affected
- All platforms with varying versions of boost

_A comment in [VesuvioCalculateMSTest](https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/test/Algorithms/VesuvioCalculateMSTest.h#L42) seems to suggest this was introduced in boost version 1.56 or newer_

**Once boost versions are eventually updated in various operating systems / we are using more updated operating system then the checks in Vesuvio tests can be removed**

**Comment by martyngigg** [comment]
There is nothing we can do about this. The implementation of `boost::normal_distribution` was changed so selecting randomly from a normal distribution will produce varying results.

In reality this is not an issue though as sampling with enough points will ensure the space is still covered.
