### ISSUE TITLE
Add option on SofQW algorithms to replace NaNs on output

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#15947]
The output from `SofQW` can be used as input for further processing. The presence of NaNs can therefore cause issues in this processing and having the option to replace the NaNs with 0 would allow best of both worlds.

**Comment by PranavBahuguna** [comment]
@martyngigg : I've noticed that SofQW is related to several files including SofQW.cpp, SofQWCentre.cpp, SofQWNormalisedPolygon.cpp and so on. Which of these files do I need to actually modify?

**Comment by martyngigg** [comment]
@PranavBahuguna There are currently 3 different SofQW algorithms: `SofQWCentre`, `SofQWPolygon` & `SofQWPolygonNormalised`. `SofQW` is what is known as a "workflow algorithm" and simply runs one of the others depending on an input parameter.

For consistency the replacement should be applied on the output of all three so we should try to share code where possible.

**Comment by PranavBahuguna** [comment]
In addition for the output, should only y-values be checked or should the x and e-values be checked as well for NaNs?

**Comment by martyngigg** [comment]
In theory the error values should only be `nan` when the Y-values have become `nan`. It should be sufficient to then simply replace both `Y` & `E` values when a `NaN` Y value is encountered.

**Comment by PranavBahuguna** [comment]
One more question: Are there any particular datasets that cause NaNs to show up in the output workspace?

**Comment by martyngigg** [comment]
It's actually the algorithm itself that causes the NaN values to appear. They are used as markers for certain regions of the parameter space that cannot be accessed by the instrument. 

Another group would like to use this as input for other algorithms an need to be able to clean all of the NaNs out of the dataset for it to be usable.

**Comment by PranavBahuguna** [comment]
I understand the algorithm does this, but the current input dataset used for testing the SofQW class (IRS26173_ipg.nxs) does not produce any NaNs in the output workspace. In order to test the code, I need to use an input dataset that does produce NaNs in output workspace. Are there any particular datasets that does this?

**Comment by martyngigg** [comment]
The current test case for `SofQWNormalizedPolygon` should produce a NaN for the final spectrum in the workspace.

The other 2 algorithms are much less likely to produce a NaN so I would suggesting manually altering the data to include a NaN spectrum before running the test for these cases.

**Comment by AndreiSavici** [comment]
See comment in PR:

`Is there a reason why this should not be optional? The correct way is NaN, not 0. ) means that you measured at that point, NaN means that you could not.`

**Comment by martyngigg** [comment]
@AndreiSavici This definitely should be optional with the default to be `Off` - it says that in the initial comment. @PranavBahuguna Have you made it optional and added a flag for the user to control it?
