### ISSUE TITLE
Indirect Bayes Quasi - eMin/eMax range bars no longer automatically set 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15951]
### Expected behavior
* When data is loaded into BayesQuasi, the range bars for eMin and eMax should automatically be set to reasonable places for the data

### Actual behavior
* Range bars remain at the origin

### Steps to reproduce the behavior
* Open Bayes Quasi
* Load data
* Observe miniplot range bars

### Platforms affected
* Ubuntu (maybe other linux platforms) (not seen on windows)

**Comment by SpencerHowells** [comment]
It also happens on Windows for nightly build of 20/4/16.
