### ISSUE TITLE
Displaying a table alters content of string-columns

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#15960]
Run the following script in the script editor of MantidPlot (happens on current master, have not checked the release version yet):

```
a = CreateEmptyTableWorkspace()

a.addColumn('str', 'col1')
a.addRow({'col1': 'This is readable'})

print a.cell(0, 0)
```

As expected, the output should be:

```
This is readable
```

Display the resulting table workspace. The cell now reads `Thisisreadable`. All spaces have been removed.

I'm adding the High Priority label because this stops `PoldiIndexKnownCompounds` from working should a user ever have the idea to display any of the required input table workspaces.

**Comment by MichaelWedel** [comment]
Running in debug mode showed that this is the place where the string is changed:

```
void MantidTable::cellEdited(int row, int col)
```

**Comment by MichaelWedel** [comment]
After some more debugging and preserving spaces in the string in the above mentioned function I found that `TableColumn::read` does not work as expected with strings, because it uses `operator<<` to transfer the data from the argument to the stored string. But the operator only proceeds until it encounters a whitespace character, so that changed the text in the column to `This`.

With a template specialisation for `Table<std::string>::read` the detour via the streaming operator can be skipped and these problems go away.

This code has been there for some time, but maybe this `cellEdited`-function was not called before for some reason?

**Comment by MichaelWedel** [comment]
The bug does not seem to be in release 3.6, at least on the windows version.

**Comment by martyngigg** [comment]
@mantid-roman Could this change have come about from the changes surrounding Qt3?

@MichaelWedel This seems fine to me.

**Comment by mantid-roman** [comment]
@martyngigg I am not sure. I can have a look.

**Comment by martyngigg** [comment]
@mantid-roman Maybe just see if what @MichaelWedel is suggesting is okay, I think that will be fine.

**Comment by mantid-roman** [comment]
The changes look reasonable. I can test the PR when it's ready.
