### ISSUE TITLE
Vesuvio - VesuvioCommands system test failing on OSX and RHEL6

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15981]
### Expected behavior
* VesuvioCommandsTest should pass on all OS

### Actual behavior
* This system test is failing on OSX and RHEL6 (potentially others)

### Steps to reproduce the behavior
* Run system tests on OSX or RHEL6

### Platforms affected
* OSX, RHEL6

**Comment by rosswhitfield** [comment]
I was just looking at this myself, it also fails on Arch Linux.

Here is the diff required so it passes for me: :smile: 
```diff
--- a/Testing/SystemTests/tests/analysis/VesuvioCommandsTest.py
+++ b/Testing/SystemTests/tests/analysis/VesuvioCommandsTest.py
@@ -148,8 +148,8 @@ class SingleSpectrumBackground(stresstesting.MantidStressTest):
 
         _equal_within_tolerance(self, index_one_first, fitted_ws.readY(0)[0])
         _equal_within_tolerance(self, index_one_last, fitted_ws.readY(0)[-1])
-        _equal_within_tolerance(self, index_two_first, fitted_ws.readY(1)[0])
-        _equal_within_tolerance(self, index_two_last, fitted_ws.readY(1)[-1])
+        _equal_within_tolerance(self, index_two_first, fitted_ws.readY(1)[0], tolerance=0.13)
+        _equal_within_tolerance(self, index_two_last, fitted_ws.readY(1)[-1], tolerance=0.11)
 
         fitted_params = self._fit_results[1]
         self.assertTrue(isinstance(fitted_params, MatrixWorkspace))
```

But this should be tested on OSX and RHEL6

**Comment by ElliotAOram** [comment]
Thanks for looking at that @rosswhitfield much appreciated. Do you know if it is only the `SingleSpectrumBackground` test that is failing in VesuvioCommandsTest?
I'm hoping to find out what the difference is being caused by but I feel like it might be down to fitting

**Comment by rosswhitfield** [comment]
Yes just `SingleSpectrumBackground`

**Comment by ElliotAOram** [comment]
Test changes pass locally on:
* [ ] Windows
* [ ] RHEL6
* [ ] Ubuntu
