### ISSUE TITLE
Pearl powder diffraction system test with generated calibration files

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#15983]
Follow on to  #15913 

Now that pearl powder diffraction script has been merged and the system test which runs the `focus` functionality of the script using existing calibration files is also on its way, add a test case to the `PearlPowderDiffractionScriptTest` system test which runs `focus` with calibration files generated from script.

**Comment by FedeMPouzols** [comment]
A couple of comment sfrom reviewing #15966:

- The tests could also validate the output files against reference files as they did in some old tests: https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/PEARLSystemTest.py#L61
- Ideally the next tests should also check different "TT**" modes, as that parameter implies some changes in the calculations.
