### ISSUE TITLE
Indirect Elwin - Ungroup Elwin Output

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16007]
### Expected behavior
* The output from Elwin should have the option of not be grouped

### Actual behavior
* The output of the algorithm is added to a group

### Steps to reproduce the behavior
* Run the Elwin interface with any input files

### Platforms affected
* All

**Comment by SpencerHowells** [comment]
Perhaps this should be an option. When used in a temperature scan, the input could be dozens of runs. If ungrouped, it would really clutter up the Workspace pane with entries.

**Comment by ElliotAOram** [comment]
@SpencerHowells, good idea I'll implement as an option instead

**Comment by ElliotAOram** [comment]
This is now working but the branch will have to be merged with master and the release notes updated when they are available for 3.8 due to the code freeze.
