### ISSUE TITLE
Make AllTests does not build Python dependencies

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#16054]
Make AllTests should build everything required to run the tests. However, after doing `make AllTests` on a clean build of the code the Python tests fail with error:

```
import mantid.dataobjects as dataobjects
No module named dataobjects
```

The Python dataobjects dependency should be fixed in cmake.

**Comment by DTasev** [comment]
Still an issue, looking at it now. It needs to build all of `PythonInterface`, as building `dataobjects` only changes the error to `curvefitting` import
