### ISSUE TITLE
QxQz slicing issue

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16068]
Jos reported the following issue (please update him when this is fixed):

They have the following QxQz workspace:

[37513_qxqz.zip](https://github.com/mantidproject/mantid/files/250377/37513_qxqz.zip)

which looks like this on Slice Viewer:

![issue1](https://cloud.githubusercontent.com/assets/8956985/15043512/951269de-12c5-11e6-94f8-7fb1290170ab.png)

They have their own integration script:

![issue4](https://cloud.githubusercontent.com/assets/8956985/15043520/ae5baa5e-12c5-11e6-830d-baa106d76daa.png)

That produces a similar cut in shape but with different magnitude:

![issue2](https://cloud.githubusercontent.com/assets/8956985/15043550/cf9253e4-12c5-11e6-8f1a-1dd52992590c.png)

They have noticed that there is a Rebin2D step they were not expecting that could be the cause of this difference.

This issue is to clarify what Slice Viewer is doing differently from their script.

**Comment by gemmaguest** [comment]
The difference is that `Integration` is doing a sum of Y values * bin width because this is distribution data. Slice viewer uses `Rebin2D` which just sums Y values.
```
ws=Load(Filename='37513_qxqz.nxs', OutputWorkspace='37513_qxqz')

def QxQzcuts(name, qzmin=None, qzmax=None, outputname=None):
    if not outputname:
        if qzmin:
            outputname = name+'_cut_'+str(qzmin)+'-'+str(qzmax)
        else:
            outputname = name+'_cut_all'
    Transpose(InputWorkspace=name, OutputWorkspace=outputname)
    Integration(InputWorkspace=outputname, RangeLower=qzmin, RangeUpper=qzmax, OutputWorkspace=outputname)
    return Transpose(InputWorkspace=outputname, OutputWorkspace=outputname)

# The input is distribution data so Integration() sums Y values multiplied by bin width
QxQzcuts('37513_qxqz',0.03,0.05, '37513_qxqz_Integration')

# If we set it as non distribution it will just sum Y values - gives more similar results to Rebin2D below
ws.setDistribution(False)
wsInt=QxQzcuts('37513_qxqz',0.03,0.05, '37513_qxqz_Integration_non_dist')
ws.setDistribution(True)
wsInt.setDistribution(True)

# The sliceviewer creates the cut with Rebin2D as follows:
Rebin2D(InputWorkspace='37513_qxqz', OutputWorkspace='37513_qxqz_Rebin2D',
  Axis1Binning='-0.0005, 0.000002, 0.0005', Axis2Binning='0.03,0.02,0.05', UseFractionalArea=True)
```

**Comment by gemmaguest** [comment]
Closing as Stale because this is expected behaviour at the moment
