### ISSUE TITLE
Can't fit data from table with fit property browser

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16069]
### Expected behaviour
Should be able to use the "Fit function" window in MantidPlot to fit data from a TableWorkspace

### Actual behaviour
Dialog "Fit algorithm failed. Unknown property search object WorkspaceIndex."  
(More recently this has changed into an error message in the log)

### Steps to reproduce the behaviour
```python
tab = CreateEmptyTableWorkspace()
tab.addColumn("int", "x", 1)  
tab.addColumn("double", "y", 2)         
tab.addRow([20, 40])
tab.addRow([30, 60])
tabl = importTableWorkspace('tab', True)
```
Then plot a graph from the table and try to use the fit property browser ("Fit Function" window in MantidPlot) to fit something to it. 

### Platforms affected
All

---

This looks like it occurs in `doFit` in the FitPropertyBrowser. The function calls `getWorkspace()` which automatically converts the data to a MatrixWorkspace, but then does nothing with the workspace returned. It just passes the name of the original TableWorkspace to `Fit`.

**This is required soon for a course at ISIS - deadline 14th May**. (Use case: the results table generated from MuonAnalysis interface. The workaround is manually converting to a MatrixWorkspace).

**Comment by shahrozahmed1** [comment]
I built the branch again, it seems to crash whenever I click `peak fit toolbar` after plotting the graph.

![peakfittoolbar](https://cloud.githubusercontent.com/assets/13132173/15117443/79854e7e-15ff-11e6-9a7c-be1c3886e7be.png)

**Comment by shahrozahmed1** [comment]
@tom-perkins its quite odd because now I am not getting crash any more, only happens randomly..
