### ISSUE TITLE
Error propagation incorrect in DivideMD, MultiplyMD

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#16077]
### Expected behavior
I have two MD histogram workspaces, `a` and `b`, and I want to look at `a/b`
If I have a point in my LHSWorkspace where the signal and the error squared are 0, I expect that the error squared is 0. 

### Actual behavior
In the current implementation I get a `NaN`

### Steps to reproduce the behavior
```
d=CreateMDHistoWorkspace(SignalInput='0', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
n=CreateMDHistoWorkspace(SignalInput='1', ErrorInput='0', Dimensionality=1, Extents='0,1', NumberOfBins='1', Names='d1', Units='x')
out=d/n
print out.getErrorSquaredArray()
```
### Platforms affected
All

### Notes:
 - The same behavior was fixed  for `Divide` algorithm in 2010. See comments in [Divide.cpp, lines 47-50] (https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/Divide.cpp#L47-L50)
 - MultiplyMD has the same problem

**Comment by NickDraper** [comment]
Moving this to R3.8

**Comment by AndreiSavici** [comment]
Moving it back to 3.7. Error propagation is important enough to have it done correctly
