### ISSUE TITLE
Use a monospaced font by default in the script window

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#16089]
### Expected behavior

Code editors pretty much always use monospaced fonts by default. One would expect Mantid to follow this convention.
### Actual behavior

Default font is not monospaced.
### Steps to reproduce the behavior

Open the script window and type something.
### Platforms affected

All.

**Comment by NickDraper** [comment]
Need to make sure default is applied to current installs of Mantid as a one time operation.
The new font needs to be available on all OS's

**Comment by martyngigg** [comment]
The workbench font is not monospace but I don't think we should do anything to MantidPlot.
