### ISSUE TITLE
Scale sets up broken Dx?

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#16117]
No problems seen in the wild, but this looks wrong:

`Scale.cpp` line 82:

``` cpp
for (size_t index = 0; index < bufferWS->getNumberHistograms(); ++index) {
  outputWS->setDx(0, bufferWS->dataDx(0));
}
```

@AntonPiccardoSelg Have a look if this is relevant for you.

**Comment by AntonPiccardoSelg** [comment]
This seems wrong to me too. It should be  `outputWS->setDx(index, bufferWS->dataDx(index));` Will fix this and add a test for it

**Comment by AntonPiccardoSelg** [comment]
This has already been fixed
