### ISSUE TITLE
SaveAscii2 assumes that the X uncertainties are identical for all spectra

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#16121]
I am not aware of any issues seen in the wild, but in `SaveAscii2.cpp` the `writeSpectra` methods write the `Dx` data of spectrum 0 for all spectra, in all cases (i.e., not only for "common bins").

**Comment by NickDraper** [comment]
This has probably been missed as the Dx data is only rarely used, so probably was not tested for this alg.

**Comment by SimonHeybrock** [comment]
Closing, since I will not fix this.
