### ISSUE TITLE
SaveAscii2 assumes that workspaces without common bins store histogram data

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#16120]
I am not aware of any issues seen in the wild, but this looks suspicious:

`SaveAscii2.cpp` around line 300:

``` cpp
    if (!m_isCommonBins) // checking for ragged workspace
    {
      file << (m_ws->readX(*spectraItr)[bin] +
               m_ws->readX(*spectraItr)[bin + 1]) /
                  2;
    }
```

In other cases (i.e., for common bins), there is a check for `isHistogramData()`, but this seems to be missing here.

If anyone can confirm that this is incorrect, I can trivially fix it with the upcoming `HistogramData` module.

**Comment by SimonHeybrock** [comment]
I leave this unassigned since it is not clear that it will be me who will be working on introducing the Histogram type in this context (#15880).

**Comment by NickDraper** [comment]
@SimonHeybrock As you have #15880 you might as well hold this one as well.  It is better than leaving it unassigned as it is likely to get missed there, and gets in the way of me triaging other issues.

**Comment by SimonHeybrock** [comment]
It seems this has been fixed automatically by the `HistogramData` rollout a while ago.
