### ISSUE TITLE
Add options to the ColorBarWidget, labels and tooltips should not always be SliceViewer-centric

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16154]
The `ColorBarWidget` is a `MantidWidget` and is convenient in interfaces that are not necessarily used in the same context as the `SliceViewer`. The widget includes two "autoscale" tick boxes with labels, behavior and tooltips that are too specific to the `SliceViewer`. The widget is now used in the imaging interface which will need a bit of polishing. See #16131 for example.

- An option to change the tooltip texts, and maybe the label texts, will probably be good.
- An option to hide some or both tick boxes, simplifying the widget, could be considered.
- An option to modify the behavior of the tick boxes could be remotely considered but I think it won't be needed for imaging.

**Comment by DimitarTasev** [comment]
@FedeMPouzols I can't think of any proper way of doing it. The `ColorBarWidget` is always used within the generated `.ui` files, in this case within the `ui_ImageSelectCoRAndRegions.h` on `line 549`. 

As the only place the class is used is within the `.ui` file, there isn't a place to specify additional constructor arguments, or do any function calls that can change the state. Maybe there could be a way to wrap the `.ui` class inside another class, to allow for custom calls, but in my opinion this will make the code confusing and it might be very hard to do.

If you could suggest any other way to do it, I'll be happy to give it a shot.
