### ISSUE TITLE
Unscripted Testing ISIS Reflectometry

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#16169]
1. Read http://www.mantidproject.org/Unscripted_Manual_Testing
2. Comment against this ticket the OS environment you are testing against.
3. Don't spend more than a few hours on the testing as fatigue will kick in.
4. If you find errors in the possibly scant documentation, then correct them.
5. Close the this ticket once you are done.

If you find bugs:
- Search to see if an issue already exists
- create an issue if it is new
  - Urgent bugs or crashes should by against the current release, and assigned to a developer, then go and talk to the developer if possible.
  - Less urgent bugs should be against a subsequent release, and assigned if the correct developer is known.
### Specific Notes:

For testing procedures see http://www.mantidproject.org/Testing_ISIS_Reflectometry_GUI

**Comment by MattKing06** [comment]
After completed unscripted testing for the old Reflectometry interface, any issues found will be cataloged [here](https://github.com/mantidproject/mantid/issues/16227)

**Comment by raquelalvarezbanos** [comment]
While testing the interface I found a bug when plotting (https://github.com/mantidproject/mantid/issues/16169). I am not going to have time to have a look at it today (I am going to be in a course), so I am leaving it unassigned.

**Comment by raquelalvarezbanos** [comment]
Both interfaces seem to be working OK, I haven't found any issues.

**Comment by raquelalvarezbanos** [comment]
Everything seems OK. Both interfaces are working as I would expect.
