### ISSUE TITLE
SCD calibration issues

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#16199]
Fix issues found by instrument scientists testing SCDCalibratePanels

- [x] - When lattice parameters are entered, the calibration is worse.

- [ ] - Lattice should also be optimized and match input to 3-4 decimal places

- [ ] - Fix width, height, and t0 on first pass (t0 and l0 are correlated)

- [ ] - Label Row, Col and Tof spectra with # peaks and RMSD in mm

- [x] - Ignore peaks on edges

- [ ] - Check how depth and detd are used and if they are correct after optimization

- [ ] - Slow (4-5 minutes) for MANDI 

- [x] - XML output not correct from parallel region

**Comment by NickDraper** [comment]
Vickie,  Is this correctly aimed at R3.7?  Do all of the issues above need to be in that release?

**Comment by NickDraper** [comment]
Vickie can you give me an update on this or at least the parts that need to get into R3.7?

**Comment by NickDraper** [comment]
Any changes that need to get into release 3.7 need to be in a tested PR by the end of today.

**Comment by NickDraper** [comment]
Moved to R3.8 for the remaining aspects of this issue
