### ISSUE TITLE
Implement square scaling on the graphs and instrument window

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#1619]
This issue was originally [TRAC 771](http://trac.mantidproject.org/mantid/ticket/771)

Squares% goes 1, 4, 9, 16, 25, 35 .. % of maximum

**Comment by NickDraper** [comment]
This is the link you want

955b616

**Comment by matthew-d-jones** [comment]
This issue comprises 3 parts. One will be resolved in a different existing issue (#11422), I will create issues for the other two. Quadratic scaling should be possible in:
- standard 2D plots #11422 
- color fill plots
- instrument view

As "color fill plots" uses the "General Plot Options" window it should require little further work from #11422. For the instrument view changes will need to be made to the GUI, but the PowerScaleEngine created #11422 can be used.

**Comment by matthew-d-jones** [comment]
All component issues are resolved.
