### ISSUE TITLE
OFFSPEC IDF does not have slits defined

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16218]
Discuss this with scientists. They are currently trying to harmonize their IDFs across instruments, as part of this harmonization, slits should be defined for OFFSPEC. This is needed for instance to run `CalculateResolution` successfully on OFFSPEC data.

Also while investigating #16518 it was found the OFFSPEC parameter file did not contain any values for `Correction`. These should also be added if scientists need them.

**Comment by gemmaguest** [comment]
The new (experimental) IDF supplied by Jos should fix this
