### ISSUE TITLE
Unsaved changes are not checked for when Reflectometry (Polref) is closed

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#16249]
This bug was found during unscripted testing of the ISIS Reflectometry (Polref) interface.
### Expected behavior
- If the table is edited but not saved when closing the interface, we should ask the user whether they wish to save any changes to the table before closing the interface.
### Actual behavior
- No check, we just close it.
### Steps to reproduce the behavior
- Go to `Interface > Reflectometry > ISIS Reflectometry (Polref)`
- Enter values into the empty table
- Close the interface
- See that we do not raise any warnings to the user about unsaved changes.
### Platforms affected
- All.

**Comment by PranavBahuguna** [comment]
While the merge conflict has been fixed, the code necessary for starting the 'ask unsaved changes' at `QtReflRunsTabView::closeEvent()` never runs. I have little idea as to why this is so now.
