### ISSUE TITLE
Waterfall Graphs: "Fill Area" not filling area properly after reversing order

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16253]
Issue discovered during unscripted testing.

Load a dataset and plot some spectra using the "Waterfall Plot" option (for instance, I tried with "EMU00020711"). Click on "Reverse Order", then "Fill Area" and check "Enable Fill", areas under the curves are not displayed properly.

**Comment by raquelalvarezbanos** [comment]
[EMU00020711.zip](https://github.com/mantidproject/mantid/files/359185/EMU00020711.zip)

**Comment by DimitarTasev** [comment]
Could not replicate the issue. I have also tried with different data files, and still could not replicate. Following are the images of my result:

Loading "EMU00020711.nxs" and plotting spectra range 1-3 using "Waterfall Plot"
![step1](https://cloud.githubusercontent.com/assets/9135965/16796527/21c1b876-48db-11e6-8403-97014fb48bca.png)

"Reverse Order" has been clicked and you can see that the plots are reversed
![step2](https://cloud.githubusercontent.com/assets/9135965/16796529/231cbe50-48db-11e6-8e1b-0379622b6833.png)

"Fill Area" has been clicked and "Enable Fill" has been checked, the filled area looks normal
![step3](https://cloud.githubusercontent.com/assets/9135965/16796535/27ffcd72-48db-11e6-9aee-48e2d7c82762.png)

**Comment by DimitarTasev** [comment]
Is this still a valid issue? I could not replicate the issue, but it wasn't closed after being reviewed?

**Comment by NickDraper** [comment]
This cannot be reproduced anymore
