### ISSUE TITLE
Change tests of `CurveFitting` "functions" to be actual unit tests

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#16267]
### Expected behavior

We want to have unit tests that just test the unit aspect of the code. Including boundary conditions etc.

Complex tests of the complete fitting framework should move out tu the Fit unit testing or a system test.
### Actual behavior

Currently the unit tests for many of the functions test much more than the function itself, often performing optimised fits.

See [this comment below](#issuecomment-221586507) for a list of individual issues.

**Comment by FedeMPouzols** [comment]
@raquelalvarezbanos

**Comment by FedeMPouzols** [comment]
Dividing into blocks:

- Functions in the category "Muon": #16418.

**Comment by raquelalvarezbanos** [comment]
Functions in the category "Peaks": https://github.com/mantidproject/mantid/issues/16452

**Comment by FedeMPouzols** [comment]
@NickDraper: I just pushed this back to 3.9. This is 95% done, just the "QuasiElastic" functions need a bit of attention.

**Comment by gemmaguest** [comment]
Closing as stale because we are unlikely to get around to this
