### ISSUE TITLE
Move Windows Jenkins builds to use Ninja where possible

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#16265]
### Platforms affected
Windows

**Comment by lottiegreenwood** [comment]
After exploring this, it looks like there will be too many problems that need to be worked around for the end result to be worth it.
Found that when running 2 processes+ Ninja appeared to get 'permissions denied' errors when trying to access PCH files. Current workaround was running Ninja on one core only, but potential fix discussed [here](https://groups.google.com/forum/#!topic/ninja-build/DkNRElbw0Zo/discussion)
Another issue was found in MantidUtils.cmake - $TARGET_NAME was not being found, and it looked like the get_target_property function was not working correctly.
