### ISSUE TITLE
Algorithm DgsReduction resets default facility to SNS 

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#16260]
When following documentation steps for DGS Reduction outlined [here](http://www.mantidproject.org/Direct:DgsReduction), even if the default facility is set as ISIS prior to reducing MAR11001.raw, this error will occur:

```
Error in execution of algorithm DgsReduction:
Default facility must be set to ISIS in order for reduction to work!
RuntimeError: Default facility must be set to ISIS in order for reduction to work!
  at line 13 in '<Interface>'
  caused by line 849 in 'C:/MantidInstall/bin\mantid\simpleapi.py'
```

When using data files produced by the SNS, no such error happens.
### Platforms affected

appears on Windows7 64bit

**Comment by NickDraper** [comment]
As this is currently only used at the SNS this is low priority
