### ISSUE TITLE
Add curve to new layer in multlayer plot seems gets the scaling wrong on Ubuntu

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#16310]
### Expected behaviour

CurveDialog should allow us to add an existing curve to a new layer. The cloned curve should look exactly the same. Expected image is:

![screenshot from 2016-05-19 17 04 12](https://cloud.githubusercontent.com/assets/8955784/15400545/cbcc85da-1de3-11e6-8643-066eafdd0eb9.png)

### Actual behaviour

The cloned curve does not appear on the screen (depending on the data set). When changing the scaling of the axis, one can see that the curve was cloned but with an apparently incorrect scaling.  The curve looks like this:

![screenshot from 2016-05-19 17 08 32](https://cloud.githubusercontent.com/assets/8955784/15400709/5d34bbc8-1de4-11e6-8cc6-493d9ce09bbf.png)

### Steps to reproduce the behaviour

1. Load the workspace POLREF00014966 from the Unit tests
1. Ungroup it
1. Plot the first spectrum of the first period workspace
1. Add a new layer
1. Double click on the (2) icon 
1. Transfer the old curve
  * Confirm that the new curve has an incorrect scaling

### Platforms affected

I can only see this on Ubuntu. I checked a Nightly Build from 10/05 and it seems OK there.

**Comment by NickDraper** [comment]
Multi layer plot in reality are very rarely used

**Comment by NickDraper** [comment]
No plan to do anything on this at the moment - Archived
