### ISSUE TITLE
BASISReduction uses vanadium from previous run even when not requested

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#16313]
### Expected behavior
Normalization by Vanadium should not be used if property `DivideByVanadium` is set to `False`

### Actual behavior
Normalization occurs irrespective of the value of property  `DivideByVanadium` is a vanadium run number is set.

### Steps to reproduce the behavior
Perform a first reduction with  `DivideByVanadium` is set to `True`. Then, perform a second reduction with  `DivideByVanadium` is set to `False`. The second reduction will also carry out the normalization in spite of `DivideByVanadium` is set to `False`

### Platforms affected
All

**Comment by NickDraper** [comment]
This is up against R3.7, but it would need to be completed by tomorrow to make it.  Should this be moved to R3.8?

**Comment by jmborr** [comment]
I'm sorry, this has been fixed so the issue can actually be closed (
https://github.com/mantidproject/mantid/pull/16314)
