### ISSUE TITLE
DataProcessorUI: processing algorithms should not need to have all algorithms registered

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16414]
Pre-processing, processing and post-processing algorithms currently need to have the framework initialized and all algorithms registered. This shouldn't be necessary.

**Comment by raquelalvarezbanos** [comment]
This was suggested by Owen, ask him if you have any questions about this, or any question in general about the `Data Processor` widget.

**Comment by gemmaguest** [comment]
Closing as we are no longer using the data processor
