### ISSUE TITLE
Indirect Data Reduction Energy Transfer - Load Ascii files

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16419]
### Expected behavior
* Tosca data Files saved to Ascii with the functionality in the Indirect Data Reduction Energy Transfer can be loaded back into Mantid using LoadAscii

### Actual behavior
* Once a file has been saved to Ascii Mantid is unable to load it back in 

### Steps to reproduce the behavior
* Save TOSCA data as ascii using the Energy Transfer interface 

### Platforms affected
* All

**This is caused by TOSCA producing 7 column data and LoadAscii can only deal with 1 and 3**

**Comment by louisemccann** [comment]
This might be due to the fact that currently the EnergyTransfer Interface (and also Diffusion) use SaveAscii v1 whereas v2 seems to be optimized for LoadAscii
