### ISSUE TITLE
DGSPlanner won't start

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#16427]
Beta test issue from Jon Taylor.

DGSPlanner gives an error on startup.

```
ImportError: No module named externals
  at line 2 in '<Interface>'
  caused by line 2 in '/Applications/MantidPlot.app/scripts/DGSPlanner/DGSPlannerGUI.py'
  caused by line 11 in '/Applications/MantidPlot.app/scripts/DGSPlanner/InstrumentSetupWidget.py'
  caused by line 4 in '/Users/jonathantaylor/Library/Python/2.7/lib/python/site-packages/mpl_toolkits/mplot3d/__init__.py'
```

### Platforms affected

Seen on OSX.

**Comment by AndreiSavici** [comment]
This looks like some old version of matplotlib and/or mpl_toolkits, or incompatible ones. @quantumsteve noticed that Jon Taylor is using his own version of matplotlib, not the system version. @Jon-Taylor: play with your paths and matplotlib versions till you can run `from mpl_toolkits.mplot3d import Axes3D` without errors
