### ISSUE TITLE
Sample transmission calculator: Single bin not handled well

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#16428]
Beta-test bug from Jon Taylor.

### Expected behavior

Error dialog should be shown

### Actual behavior

Terminate/continue is displayed

### Steps to reproduce the behavior

* Open `Interfaces->General->Sample Transmission Calculator`
* Set Low=0.1,Width=0.1,High=0.2
* Set `ChemicalFormula=V`
* Hit Calculate.

### Platforms affected

All

**Comment by martyngigg** [comment]
@raquelalvarezbanos Do you have time to look at this for the release?

**Comment by raquelalvarezbanos** [comment]
@martyngigg Yes, I can have a look at it. Looks like an easy bug to fix, if that's the case I can fix it, if it turns out to be more complicated I may need help (that interface is new to me). I'll have a look now.

**Comment by martyngigg** [comment]
Thanks. Unfortunately the original author is not around but hopefully it won't be too complicated.

**Comment by raquelalvarezbanos** [comment]
Done, it was not too difficult. @martyngigg feel free to assign me other issues I can help with, I am working on maintenance tasks at the moment.

**Comment by martyngigg** [comment]
Thanks, @raquelalvarezbanos. I'll keep it in mind.
