### ISSUE TITLE
Algorithm EvaluateFunction fails badly if the startX, endX are wrong 

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16449]
### Expected behavior

When you run `EvaluateFunction`, passing wrong startX and endX (outside of workspace X range) should not be a terrible thing.
### Actual behavior

You can easily get an `std::bad_alloc` exception.
### Steps to reproduce the behavior

Try this example, modified from the first example given in the algorithm documentation: http://docs.mantidproject.org/nightly/algorithms/EvaluateFunction-v1.html

```
# Load a workspace
ws = Load('MUSR00015189')
# Evaluate a function
EvaluateFunction('name=ExpDecay,Height=56', 'ws_1', StartX=10e3, EndX=30e3, OutputWorkspace='out')
```
### Platforms affected

All, most likely.

**Comment by NickDraper** [comment]
current error message - needs to be improved
```
RuntimeError: vector<T> too long
  at line 4 in 'New script'
  caused by line 343 in 'C:\MantidInstall\bin\mantid\simpleapi.py'
```
