### ISSUE TITLE
Table row spacing is wider than it used to be

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16471]
The table row spacing is wider in the beta than it used to be in 3.6. This might be inconvenient for users on laptops or with smaller screens.

In addition, the rows have changed from being 0-indexed to being 1-indexed:

*Mantid 3.6.0:*
![tablerows-3-6-0](https://cloud.githubusercontent.com/assets/15363125/15613742/fbd6095a-242c-11e6-8506-4dc70869d860.PNG)

*Mantid 3.7 beta:*
![tablerows-3-6-nightly](https://cloud.githubusercontent.com/assets/15363125/15613905/bca16684-242d-11e6-8851-9b6f1e088f35.PNG)

(Reported on Windows, not sure if it's the same on other platforms)

**Comment by NickDraper** [comment]
Is this a problem?

**Comment by tom-perkins** [comment]
Only if you have a really small screen (I think this was something reported in the beta test). We should make sure that the change from 0-indexing to 1-indexing hasn't broken anything, though.

**Comment by tom-perkins** [comment]
This can probably be closed as it is not a problem for anybody
