### ISSUE TITLE
Reorganize unit tests of functions, category "Calibrate", "Calibration", and "Quantification"

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16481]
This is one chunk of #16267.
Move the test cases that use the algorithm Fit to the unit test file of Fit (FitTest). Add tests to test the function itself when necessary. Tidy up the includes wherever possible, as for example in #16470.

Calibrate functions:
- EndErfc, 
- ProductLinearExp, 
- ProductQuadraticExp, 
- SCDPanelErrors

Calibration functions:
- PeakHKLErrors

Quantification:
- ResolutionConvolvedCrossSection

**Comment by raquelalvarezbanos** [comment]
Only `EndErfc` needs to be changed.
