### ISSUE TITLE
Reorganize unit tests of functions, category "QuasiElastic"

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16482]
This is one chunk of #16267.
Move the test cases that use the algorithm Fit to the unit test file of Fit (FitTest). Add tests to test the function itself when necessary. Tidy up the includes wherever possible, as for example in #16470.

QuasiElastic functions:
- ~~ChudleyElliot,~~ 
- ~~DiffRotDiscreteCircle~~
- ~~DiffSphere~~
- ~~ElasticDiffRotDiscreteCircle~~ 
- ~~ElasticDiffSphere~~
- ~~FickDiffusion,~~ 
- ~~HallRoss,~~ 
- ~~InelasticDiffRotDiscreteCircle~~
- ~~InelasticDiffSphere~~
- ~~StretchedExpFT~~
- TeixeiraWater

**Comment by raquelalvarezbanos** [comment]
There's already a PR for this pending testing. Hence marking this back as 3.9.
