### ISSUE TITLE
ADS should return sorted object names

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16500]
See discussion in #16496.

At present, the ADS returns workspace names (via `getObjectNames()`) as an unordered set, which then has to be sorted. Sorting occurs in several separate places:
- WorkspaceProperty
- WorkspaceSelector
- "Add workspace" dialog in Multi dataset fitting interface
(and maybe more?)

It would be nicer if `getObjectNames()` returned an ordered collection (already sorted) instead.

**Comment by FedeMPouzols** [comment]
@NickDraper: another good candidate for a "anyone" ticket. @tom-perkins worked on this recently.

**Comment by NickDraper** [comment]
This will also need to remove the exisitng sorts in other places.
