### ISSUE TITLE
Indirect Corrections - Mass Density

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16516]
The interface should have the option in input either `Mass Density` or `Number Density` for the sample / container. 

The best way would be to have a drop down box to choose the desired option

This change will be present in the interfaces:
* [x] Calculate Paalman Pings
* [x] Absorption
* [x] Sample Transmission Calculator
* [x] Tools > Transmission

**Comment by SpencerHowells** [comment]
In the new SetSampleMaterial the parameter names are SampleNumberDensity (instead of just NumberDensity) and SampleMassDensity
