### ISSUE TITLE
Indirect IqtFitMultiple systemtest failure

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16515]
OSIRISIqtandIqtFitMultple system test is currently failing on master see [here](http://builds.mantidproject.org/job/master_systemtests-win7/190/testReport/junit/SystemTests/ISISIndirectInelastic/OSIRISIqtAndIqtFitMulti/) for jenkins output.
This appears to be due to the windows 7 build getting the results previously expected for Linux

**Comment by NickDraper** [comment]
Should this be for 3.8?

**Comment by ElliotAOram** [comment]
Can be closed as merged with release

**Comment by ElliotAOram** [comment]
Reopen so that a more permanent solution can be found.

It is possible that the data and/or fit function are not very good and should be replaced/improved

Spencer has suggested that the issue is that the resolution and sample are constructed from the same run in both the OSIRIS and IRIS case

**Comment by ElliotAOram** [comment]
Spencer and Sanghamitra have provided suitable run numbers to replace the ones currently being used.
## IRIS
* Sample = `iris26176_graphite002_red.nxs`
* Resolution = `iris26173_graphite002_res.nxs`

## OSIRIS
* Sample = `osiris97944_graphite002_red.nxs`
* Resolution = `osiris97935_graphite002_res.nxs`
