### ISSUE TITLE
MPI Algorithms broken in v3.7.1

### ISSUE THREAD

**Issue by rgmiller** [mantidproject/mantid#16539]
### Expected behavior
MPI framework build succeeds

### Actual behavior
Lots of errors compiling BroadcastWorkspace.cpp and GatherWorkspaces.cpp

At least some of the errors are caused by the fact the declareProperty() wants a unique_ptr now.  Then there are a bunch of "invalid use of incomplete type 'const class Mantid::API::MatrixWorkspace'" errors.  I don't know what that's all about yet.

### Steps to reproduce the behavior
Attempt to build the MPI framework:
module load openmpi-x86_64
scl enable devtoolset-2 "cmake -G 'Unix Makefiles' -DMPI_BUILD=ON -DCMAKE_SKIP_INSTALL_RPATH=ON -DINSTALL_ROOT=/sw/fermi/mantid-mpi $WORKSPACE/Framework"
scl enable devtoolset-2 "cmake --build . --target package -- -j$BUILD_THREADS"

### Platforms affected
Everywhere the MPI build is supposed to work (which I think is just the various Linux distros...)

**Comment by rgmiller** [comment]
Note: The MPI build did (and still does) work for v3.6.1.

**Comment by rgmiller** [comment]
Note: This is still broken in the 3.7.1 release.

**Comment by rgmiller** [comment]
The latest change should fix the compile problems we were having with newer versions of Boost.  This needs some testing, though to make sure I haven't any subtle math errors in GatherWorkspaces.

**Comment by VickieLynch** [comment]
I have tested that GatherWorkspaces works for EventWorkspaces and MatrixWorkspaces and the results with multiple mpi tasks matches the serial results.
