### ISSUE TITLE
Update Tomography interface documentation

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16549]
While having a look at the release notes, I noticed that the documentation for the ROI tab is outdated (there are now options to load an image, load a stack and play a sequence of images, as well as options for the color map). Not sure if the other tabs need to be updated too.

**Comment by FedeMPouzols** [comment]
@DimitarTasev: you had recently double-checked and updated the documentation (#17200). Is this still an issue or can it be closed?

**Comment by DimitarTasev** [comment]
@FedeMPouzols I'll take a look again, the picture for the ROI interface is outdated, I'll update it and push onto a branch
