### ISSUE TITLE
Update LoadILLIndirect.cpp for modified entries in new Nexus files for the instrument IN16b

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#16588]
### Expected behavior

Loading IN16b Nexus files

### Resolve discrepancies for new Nexus files

LoadIndirectILL.cpp starting from line 65ff:

     && descriptor.pathExists("/entry0/dataSD/dataSD")         // IN16B
     &&
      descriptor.pathExists(
          "/entry0/instrument/Doppler/doppler_frequency") // IN16B

In Nexus file: /entry0/dataSD/SingleD_data
At the moment no entry doppler_frequency

affects IndirectILLReduction.py when checking .hasProperty('Doppler.doppler_freq')

Perform tests with previous and new IN16b Nexus files

Next issue will be to load IN16b data using Load.cpp

### Platforms affected

All

**Comment by SpencerHowells** [comment]
There are 6 Issues waiting to be done for IN16 - 14173, 14179, 14578, 14649, 14650, 14653. These include using the new data format & extra calibration for peak centre.

**Comment by reimundILL** [comment]
Thank you for this important information.
