### ISSUE TITLE
Workspace history speedup

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#16591]
This issue is an in-depth look at the performance  problems seen in #16562. PR #16564 is a way to avoid the problem, but we need to find out why history lookup is slow. It seems related to finding the correct loader for files already loaded. The lookup time for a history of a workspace that was processed as part of the group exponentially increases with the number of workspaces in a group. This is unintuitive and has big performance penalty.

**Comment by NickDraper** [comment]
This is not to do with a group, it is down to the time creating an algorithm (from history) that has a Filename property that has a long (and lengthening) list of filename in it.

when you call LastAlgorithm(), an algorithm is created and reconsituted with the property values that it held from history.
Most of this is lightning fast, but when you set the Filename property, it:

1. splits the filename into individual files (like this case that had up to 60)
1. for each file finds the correct loader for it (or reports an error if none can be found).

The repeated second step is where things slow down.  However this is currently common code to when you are setting the property normally (not from history) where this validation is important.

**Comment by NickDraper** [comment]
If you keep the checks away from using lastAlgorithm (which instantiates the algorithm) and stick to the algorithm history records then this should remain lightning fast.
I'll put in a PR that does this.
