### ISSUE TITLE
GroupWorkspaces: better default option for input

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16600]
*Reported by James Lord*

The parameter *InputWorkspaces* for `GroupWorkspaces` defaults to whatever workspaces were grouped the last time the algorithm was run. These workspaces may not be present any more. It would be more helpful to use the selected workspaces, if any:

> I can select several workspaces in the ADS (workspaces) pane with 
> shift-click or ctrl-click. If I then run GroupWorkspaces, it would be 
> helpful if the "InputWorkspaces" box is filled in with them. But 
> instead it keeps an old default of workspaces I grouped at some point 
> in the past (which aren't there now). As I wanted to group a series of 
> sequentially numbered runs it was easier in the end to write a short 
> script in the Python Window than to type them all in.

**Comment by tom-perkins** [comment]
Setting as low priority as this can be easily done with the Group button

**Comment by NickDraper** [comment]
This also applies to the MergeRuns algorithm

**Comment by NickDraper** [comment]
Started the approach of creating a WorkspaceArryProperty, but this became very troublesome when you start to consider group workspaces, and would have affected much more code.

Starting again with the validator approach (similar to stringlistvalidator)
