### ISSUE TITLE
Engg GUI: extract the fitting tab into a widget of its own

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16618]
As part of #15371.

This is purely about moving code around so that the fitting tab becomes a standalone widget.
The widget should then be usable from the Engg GUI.
A bit of communication from the Engg GUI to the "calibration tab widget" might be required to grab the current calibration parameters, as those are defined by the calibration tab.
Later on the widget should be more flexible/reusable so that it can be reused for the new multi-peak/whole pattern fitting tab.

**Comment by shahrozahmed1** [comment]
@FedeMPouzols With #16629 PR, this should now be slightly more easier to implement.

**Comment by FedeMPouzols** [comment]
:+1: #16629 arrives with perfect timing.
