### ISSUE TITLE
History copies too many parameters for Fit

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16626]
This bug occurred when trying to fit a single workspace, then extract the history and use this to run the same fit on many runs with a script.

Errors seen when trying to run this script:
> You've passed a property (OutputParameters) to Fit() that doesn't apply to any of the input workspaces.
> You've passed a property (OutputNormalisedCovarianceMatrix) to Fit() that doesn't apply to any of the input workspaces.
> You've passed a property (OutputWorkspace) to Fit() that doesn't apply to any of the input workspaces.

The exported history includes these auto-generated parameters. These aren't parameters that the user should supply to `Fit`, rather the user should supply *Output* and these properties are auto-generated from it.

**Example:**

- Fit a workspace `ws1` and export the history, which appears as below. Note that it contains auto-generated parameters.
``` python 
Fit(Function='name=FlatBackground,A0=-0.00166986;name=LinearBackground,A0=0.70167,A1=1', InputWorkspace='ws1', Output='out', OutputCompositeMembers=True, StartX=0.5, EndX=9.5, OutputNormalisedCovarianceMatrix='out_NormalisedCovarianceMatrix', OutputParameters='out_Parameters', OutputWorkspace='out_Workspace')
```

- Change the input workspace in the above script to `ws2`, which hasn't been fitted yet, and try to run - see the errors above.

**Comment by NickDraper** [comment]
Ok,

So they are warnings, not errors in the log, it is down to these being dynamically created output workspace properties
