### ISSUE TITLE
Fix coverity issues in DataProcessorUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16638]
Report on new defects:

>
2 new defect(s) introduced to mantidproject/mantid found with Coverity Scan.
2 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan.
>
New defect(s) Reported-by: Coverity Scan
Showing 2 of 2 defect(s)

>
** CID 1356637:  Uninitialized members  (UNINIT_CTOR)
/home/builder/jenkins-linode/workspace/coverity_build_and_submit/MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp: 97 in MantidQt::MantidWidgets::GenericDataProcessorPresenter::GenericDataProcessorPresenter(const MantidQt::MantidWidgets::DataProcessorWhiteList &, const std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, MantidQt::MantidWidgets::DataProcessorPreprocessingAlgorithm, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char>>, MantidQt::MantidWidgets::DataProcessorPreprocessingAlgorithm>>> &, const MantidQt::MantidWidgets::DataProcessorProcessingAlgorithm &, const MantidQt::MantidWidgets::DataProcessorPostprocessingAlgorithm &)()

>
*** CID 1356637:  Uninitialized members  (UNINIT_CTOR)
/home/builder/jenkins-linode/workspace/coverity_build_and_submit/MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp: 97 in MantidQt::MantidWidgets::GenericDataProcessorPresenter::GenericDataProcessorPresenter(const MantidQt::MantidWidgets::DataProcessorWhiteList &, const std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, MantidQt::MantidWidgets::DataProcessorPreprocessingAlgorithm, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char>>, MantidQt::MantidWidgets::DataProcessorPreprocessingAlgorithm>>> &, const MantidQt::MantidWidgets::DataProcessorProcessingAlgorithm &, const MantidQt::MantidWidgets::DataProcessorPostprocessingAlgorithm &)()
91                                  "containing commas must be quoted. In case of "
92                                  "conflict between options "
93                                  "specified via this column and options specified "
94                                  "via the <b>Process</b> line edit, the former "
95                                  "prevail.");
96       m_columns = static_cast<int>(m_whitelist.size());
>     CID 1356637:  Uninitialized members  (UNINIT_CTOR)
>     Non-static class member "m_workspaceReceiver" is not initialized in this constructor nor in any functions that it calls.
97     }
98
99     /**
100     * Destructor
101     */
102     GenericDataProcessorPresenter::~GenericDataProcessorPresenter() {}

**Comment by MattKing06** [comment]
@raquelalvarezbanos I've already opened up an issue associated with the ParseKeyValueString here #16625

**Comment by raquelalvarezbanos** [comment]
Ah, OK, thanks Matt, I didn't see it, therefore this one can be closed.
