### ISSUE TITLE
Change Default of 'CorrectionDetectorPositions' in RROA

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#16648]
This is a sub-issue of #16455 
### Expected behavior
- Reflectometry scientists have expressed that they often want the position of detectors to stay the same and not be corrected by the algorithm
### Actual behavior
- This is only possible if the default of `CorrectDetectorPositions` is `False` or the desired value is specified by the user.

**Comment by PranavBahuguna** [comment]
Correction is now only done when the `ThetaIn` property for `ReflectometryReductionOneAuto2` algorithm isn't set. Closing now.
