### ISSUE TITLE
Spectrum Viewer plots wrong Y axis (if axis is replaced)

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16665]
#### Expected behaviour
If the Y axis of a workspace is replaced, plotting the workspace should use the new axis

#### Actual behaviour
Spectrum Viewer still uses the old axis values

#### Steps to reproduce the behaviour
```python
ws = CreateSampleWorkspace()
na = NumericAxis.create(200)
for i in range(200):
    na.setValue(i, (i-200.0))
ws.replaceAxis(1, na)
```
- Compare the results of right-clicking and choosing "Color Fill Plot" vs. "Show Spectrum Viewer"
- Color fill (correct):
![cfp](https://cloud.githubusercontent.com/assets/15363125/16191763/c2ebf528-36dd-11e6-9cdc-96d486d9edd4.PNG)

- Spectrum viewer (wrong):
![sv](https://cloud.githubusercontent.com/assets/15363125/16191759/bf1b6a3c-36dd-11e6-8999-b30741a5bca3.PNG)

**Comment by NickDraper** [comment]
Very niche issue in a niche tool.

Put as low priority for R3.9, by then we should have some usage data, we may find that this tool is never used.

**Comment by NickDraper** [comment]
archived for now
