### ISSUE TITLE
Fix WeightedLeastSquaresTest for GSL2

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16679]
Tests failing with GSL2: http://builds.mantidproject.org/job/master_systemtests-ubuntu-16.04/32/testReport/SystemTests/WeightedLeastSquaresTest/WeightedLeastSquaresTest/
Fix:
- SystemTests.WeightedLeastSquaresTest.WeightedLeastSquaresTest

This system test may also need revisiting now that we have more fitting tests in place.

**Comment by NickDraper** [comment]
Federico, It would be good to get this into the release, I've marked high priority for now, please give me an update when you can

**Comment by FedeMPouzols** [comment]
@NickDraper: as I'm working on related fitting tests stuff I'll keep this mind and see if I find a good fix for it. There are several other tests that fail, and some of them are proving really hard to fix, see for example #17245.

**Comment by rosswhitfield** [comment]
Fixed in #17642
