### ISSUE TITLE
CurveFitting MultiDomainFunctionTest fails with GSL2

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#16684]
This unit test `CurveFittingTest.MultiDomainFunctionTest.test_Fit_algorithm` fails sporadically when using GSL2 such as on Ubuntu 16.04. It's hard to reproduce but can be seen [here](http://builds.mantidproject.org/job/master_clean-ubuntu-16.04/119/)

**Comment by rosswhitfield** [comment]
This test is now skipped for GSL2 (see #17245) and should be un-skipped once fixed.

**Comment by NickDraper** [comment]
Roman, It would be good to get this into the release, I've marked high priority for now, please give me an update when you can

**Comment by rosswhitfield** [comment]
Fixed in #17639
