### ISSUE TITLE
Documentation for fit function DiffRotDiscreteCircle

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#16687]
Includes documentation for the elastic (ElasticDiffRotDiscreteCircle) and inelastic (InelasticDiffRotDiscreteCircle) parts

Adresses in part issue #16480

**Comment by jmborr** [comment]
@FedeMPouzols There is a problem when building the documentation:  `ElasticDiffRotDiscreteCircle`, `InelasticDiffRotDiscreteCircle`, and `DiffRotDiscreteCircle` are all implemented in `DiffRotDiscreteCircle.cpp` because the latter is a composite of the first two.

Building the documentation with:
`bin/MantidPlot -xq docs/runsphinx_html.py -R ElasticDiffRotDiscreteCircle`
will search for source ElasticDiffRotDiscreteCircle.cpp, but only DiffRotDiscreteCircle.cpp exists so no documentation is built.

**Comment by FedeMPouzols** [comment]
I see. I think that the recommended approach would be one separate file per function? @martyngigg? @NickDraper?

**Comment by martyngigg** [comment]
If they are visible enough to be distinct functions then yes they should be in separate files

**Comment by jmborr** [comment]
OK, I'll do that.
