### ISSUE TITLE
Fix POWGEN test that fails with GSL2

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#16682]
Tests failing with GSL2: http://builds.mantidproject.org/job/master_systemtests-ubuntu-16.04/21/testReport/SystemTests/CalibrateRectangularDetector_Test/PG3CCCalibration/

* SystemTests.CalibrateRectangularDetector_Test.PG3CCCalibration

**Comment by NickDraper** [comment]
Pete, It would be good to get this into the release, I've marked high priority for now, please give me an update when you can

**Comment by rosswhitfield** [comment]
Fixed in #17638
