### ISSUE TITLE
Fix TOPAZ tests that fail with GSL2

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#16683]
Tests failing with GSL2: http://builds.mantidproject.org/view/All/job/master_clean-archlinux/405/#showFailuresLink

* CrystalTest.OptimizeCrystalPlacementTest.test_basic

**Comment by rosswhitfield** [comment]
This test is now skipped for GSL2 (see #17245) and should be un-skipped once fixed.

**Comment by NickDraper** [comment]
Vicky, It would be good to get this into the release, I've marked high priority for now, please give me an update when you can
