### ISSUE TITLE
Fix ISIS Indirect Inelastic system tests for GSL2

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16681]
Tests failing with GSL2: http://builds.mantidproject.org/job/master_systemtests-ubuntu-16.04/21/testReport/

Fix the Indirect Inelastic related ones (or split into more issues/tickets):
- SystemTests.ISISIndirectInelastic.IRISIqtAndIqtFit
- SystemTests.ISISIndirectInelastic.OSIRISIqtAndIqtFit
- SystemTests.ISISIndirectInelastic.IRISConvFit
- SystemTests.ISISIndirectInelastic.IRISIqtAndIqtFitMulti
- SystemTests.ISISIndirectInelastic.OSIRISConvFit
- SystemTests.ISISIndirectInelastic.OSIRISIqtAndIqtFitMulti

**Comment by FedeMPouzols** [comment]
@ElliotAOram, @martyngigg: I'd guess you're the ones that have a better handle on these tests?

**Comment by SimonHeybrock** [comment]
@FedeMPouzols @ElliotAOram @martyngigg This is a long shot, but check out this issue regarding `CalculateFlatBackground`: #16651. The algorithm seems to be used in the ISIS indirect code, and the issue implies that the error bar are too small, so that might influence fitting.

**Comment by NickDraper** [comment]
Ask Spencer to help on this

**Comment by peterfpeterson** [comment]
The PR fixed this. GitHub didn't close it for some reason.

**Comment by rosswhitfield** [comment]
Fixed in #17608
