### ISSUE TITLE
Fix an issue during reducing HB3A 

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#16701]
A bug is found during reducing HB3A's data.  There are 2 tasks that will be related to this issue because HFIR is in the running cycle. 

1. Make the GUI more robust such that this type of exception can be handled, and will be skipped to next Pt. 

2. Fix the bug to cause the issue.

### Actual behavior

It occurs during peak integration of Experiment 487 Scan 30-250.  The error message is
```
Scan numbers are [182].
Keys for scanPt2ThetaDict: [(182, 19)].
scan 182 has Pt. as [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26].
Error in execution of algorithm CollectHB3AExperimentInfo:
Scan 182 Pt 1 cannot be found in scan-pt-2theta dict, whose keys are [(182, 19)].
  at line 129 in '/opt/mantidnightly/plugins/python/algorithms/CollectHB3AExperimentInfo.py'
```

### Steps to reproduce the behavior

1. Do survey of all the data
2. Calculate UB matrix
3. Define a region of interest
4. Integrate peaks

**Comment by VickieLynch** [comment]
:shipit:
