### ISSUE TITLE
Update Python algorithms & functions for compatibility with both Python 2 & 3 

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#16739]
A cheat sheet is available at http://python-future.org/compatible_idioms.html that details the differences between Python 2 & 3 code. Most of our incompatibilities fall in to one of three categories:

* `print` is now a function and requires parentheses in Python 3
* commas not allowed in `except` clauses.
* `dict.iteritems()` no longer exists 

We need to maintain compatibility with Python 2. See the [Python 3](http://www.mantidproject.org/Python_3) page on the wiki for more detail.

This is an umbrella issue. Please add your username to the list below and include this ticket number in your PR.

1. ~~@martyngigg #16814~~
2. ~~@FedeMPouzols #16993~~
3. ~~@rosswhitfield #16952~~
4. ~~@rosswhitfield #16953~~
5. ~~@MichaelWedel #17052~~
6. ~~@DavidFair #17575~~
7. ~~@DavidFair #17579~~
8. ~~@DavidFair #17595~~
9.  ~~@rosswhitfield #16976~~
10. @rosswhitfield

**Group 1**
PythonInterface/plugins/algorithms/AlignComponents.py
PythonInterface/plugins/algorithms/ApplyNegMuCorrection.py
PythonInterface/plugins/algorithms/BASISReduction311.py
PythonInterface/plugins/algorithms/BASISReduction.py
PythonInterface/plugins/algorithms/CalculateSampleTransmission.py
PythonInterface/plugins/algorithms/CalibrateRectangularDetectors.py
PythonInterface/plugins/algorithms/CheckForSampleLogs.py
PythonInterface/plugins/algorithms/CleanFileCache.py
PythonInterface/plugins/algorithms/CollectHB3AExperimentInfo.py
PythonInterface/plugins/algorithms/CompareSampleLogs.py
PythonInterface/plugins/algorithms/ComputeCalibrationCoefVan.py
PythonInterface/plugins/algorithms/ComputeIncoherentDOS.py
PythonInterface/plugins/algorithms/ConjoinFiles.py
PythonInterface/plugins/algorithms/ConjoinSpectra.py
PythonInterface/plugins/algorithms/ConvertSnsRoiFileToMask.py
PythonInterface/plugins/algorithms/CorrectLogTimes.py
PythonInterface/plugins/algorithms/CorrectTOF.py
PythonInterface/plugins/algorithms/CreateCacheFilename.py
PythonInterface/plugins/algorithms/CreateEmptyTableWorkspace.py
PythonInterface/plugins/algorithms/CreateLeBailFitInput.py
PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
PythonInterface/plugins/algorithms/LoadFullprofFile.py

**Group 2**
PythonInterface/plugins/algorithms/DakotaChiSquared.py
PythonInterface/plugins/algorithms/DNSComputeDetEffCorrCoefs.py
PythonInterface/plugins/algorithms/DNSFlippingRatioCorr.py
PythonInterface/plugins/algorithms/DNSMergeRuns.py
PythonInterface/plugins/algorithms/DPDFreduction.py
PythonInterface/plugins/algorithms/DSFinterp.py
PythonInterface/plugins/algorithms/EnggCalibrateFull.py
PythonInterface/plugins/algorithms/EnggCalibrate.py
PythonInterface/plugins/algorithms/EnggFitDIFCFromPeaks.py
PythonInterface/plugins/algorithms/EnggFitPeaks.py
PythonInterface/plugins/algorithms/EnggFocus.py
PythonInterface/plugins/algorithms/EnggVanadiumCorrections.py
PythonInterface/plugins/algorithms/ExaminePowderDiffProfile.py
PythonInterface/plugins/algorithms/Examples/ExampleSaveAscii.py
PythonInterface/plugins/algorithms/Examples/Squares.py
PythonInterface/plugins/algorithms/ExportExperimentLog.py
PythonInterface/plugins/algorithms/ExportGeometry.py
PythonInterface/plugins/algorithms/ExportSampleLogsToCSVFile.py
PythonInterface/plugins/algorithms/FilterLogByTime.py
PythonInterface/plugins/algorithms/FindEPP.py

**Group 3**
PythonInterface/plugins/algorithms/FindReflectometryLines.py
PythonInterface/plugins/algorithms/FitGaussian.py
PythonInterface/plugins/algorithms/GenerateGroupingSNSInelastic.py
PythonInterface/plugins/algorithms/GetEiMonDet.py
PythonInterface/plugins/algorithms/GetEiT0atSNS.py
PythonInterface/plugins/algorithms/GetIPTS.py
PythonInterface/plugins/algorithms/GetNegMuMuonicXRD.py
PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
PythonInterface/plugins/algorithms/IndirectTransmission.py
PythonInterface/plugins/algorithms/LiquidsReflectometryReduction.py
PythonInterface/plugins/algorithms/LoadCIF.py
PythonInterface/plugins/algorithms/LoadDNSLegacy.py
PythonInterface/plugins/algorithms/dnsdata.py
PythonInterface/plugins/algorithms/LoadEmptyVesuvio.py
PythonInterface/plugins/algorithms/LoadLogPropertyTable.py
PythonInterface/plugins/algorithms/LoadMultipleGSS.py
PythonInterface/plugins/algorithms/LoadNMoldyn3Ascii.py
PythonInterface/plugins/algorithms/LoadNMoldyn4Ascii.py
PythonInterface/plugins/algorithms/LoadSINQFile.py
PythonInterface/plugins/algorithms/LoadSINQ.py
PythonInterface/plugins/algorithms/LoadVesuvio.py

**Group 4**
PythonInterface/plugins/algorithms/LoadVisionElasticBS.py
PythonInterface/plugins/algorithms/LoadVisionElasticEQ.py
PythonInterface/plugins/algorithms/LoadVisionInelastic.py
PythonInterface/plugins/algorithms/LRAutoReduction.py
PythonInterface/plugins/algorithms/LRDirectBeamSort.py
PythonInterface/plugins/algorithms/LRPeakSelection.py
PythonInterface/plugins/algorithms/LRPrimaryFraction.py
PythonInterface/plugins/algorithms/LRReflectivityOutput.py
PythonInterface/plugins/algorithms/LRScalingFactors.py
PythonInterface/plugins/algorithms/LRSubtractAverageBackground.py
PythonInterface/plugins/algorithms/MaskAngle.py
PythonInterface/plugins/algorithms/MaskBTP.py
PythonInterface/plugins/algorithms/MaskWorkspaceToCalFile.py
PythonInterface/plugins/algorithms/Mean.py
PythonInterface/plugins/algorithms/MergeCalFiles.py
PythonInterface/plugins/algorithms/MSDFit.py
PythonInterface/plugins/algorithms/MuscatSofQW.py
PythonInterface/plugins/algorithms/NormaliseSpectra.py
PythonInterface/plugins/algorithms/PDToGUDRUN.py
PythonInterface/plugins/algorithms/PDToPDFgetN.py
PythonInterface/plugins/algorithms/PearlMCAbsorption.py

**Group 5**
PythonInterface/plugins/algorithms/PoldiCreatePeaksFromFile.py
PythonInterface/plugins/algorithms/PoldiLoadRuns.py
PythonInterface/plugins/algorithms/PoldiMerge.py
PythonInterface/plugins/algorithms/RefinePowderDiffProfileSeq.py
PythonInterface/plugins/algorithms/RefLReduction.py
PythonInterface/plugins/algorithms/ResNorm.py
PythonInterface/plugins/algorithms/RetrieveRunInfo.py
PythonInterface/plugins/algorithms/SANSSubtract.py
PythonInterface/plugins/algorithms/SANSWideAngleCorrection.py
PythonInterface/plugins/algorithms/SaveNexusPD.py
PythonInterface/plugins/algorithms/SavePlot1DAsJson.py
PythonInterface/plugins/algorithms/SaveVulcanGSS.py
PythonInterface/plugins/algorithms/SelectPowderDiffPeaks.py
PythonInterface/plugins/algorithms/sfCalculator.py
PythonInterface/plugins/algorithms/SNSPowderReduction.py
PythonInterface/plugins/algorithms/SortByQVectors.py
PythonInterface/plugins/algorithms/SortDetectors.py
PythonInterface/plugins/algorithms/SortXAxis.py
PythonInterface/plugins/algorithms/StatisticsOfTableWorkspace.py
PythonInterface/plugins/algorithms/StringToPng.py
PythonInterface/plugins/algorithms/SuggestTibCNCS.py

**Group 6**
PythonInterface/plugins/algorithms/SuggestTibHYSPEC.py
PythonInterface/plugins/algorithms/Symmetrise.py
PythonInterface/plugins/algorithms/TestWorkspaceGroupProperty.py
PythonInterface/plugins/algorithms/TOFTOFConvertTofToDeltaE.py
PythonInterface/plugins/algorithms/TOFTOFCropWorkspace.py
PythonInterface/plugins/algorithms/TOFTOFMergeRuns.py
PythonInterface/plugins/algorithms/UpdatePeakParameterTableValue.py
PythonInterface/plugins/algorithms/USANSSimulation.py
PythonInterface/plugins/algorithms/VesuvioCorrections.py
PythonInterface/plugins/algorithms/VesuvioPreFit.py
PythonInterface/plugins/algorithms/VesuvioResolution.py
PythonInterface/plugins/algorithms/VesuvioThickness.py
PythonInterface/plugins/algorithms/VesuvioTOFFit.py
PythonInterface/plugins/algorithms/ViewBOA.py
PythonInterface/plugins/algorithms/VisionLoadDetectorTable.py
PythonInterface/plugins/algorithms/VisionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/AddSampleLogMultiple.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/DetectorFloodWeighting.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ElasticWindowMultiple.py

**Group 7**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSAzimuthalAverage1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSDirectBeamTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/EQSANSNormalise.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/FlatPlatePaalmanPingsCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/HFIRSANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ILLIN16BCalibration.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectAnnulusAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectCalibration.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectCylinderAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectFlatPlateAbsorption.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectILLReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectResolution.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectTransmissionMonitor.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IqtFitMultiple.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/IqtFitSequential.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MolDyn.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MuscatData.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/MuscatFunc.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/NormaliseByThickness.py

**Group 8**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/PoldiDataAnalysis.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/Quest.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReactorSANSResolution.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/REFLReprocess.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/ResNorm2.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAbsoluteScale.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSAzimuthalAverage1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSBeamSpreaderTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSDarkRunBackgroundCorrection.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSDirectBeamTransmission.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSFitShiftScale.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSMask.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSStitch.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SavePlot1D.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMoments.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SwapWidths.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TimeSlice.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TOSCABankCorrection.py

**Group 9**
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransmissionUtils.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/USANSReduction.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/VesuvioDiffractionReduction.py
PythonInterface/plugins/functions/ChudleyElliot.py
PythonInterface/plugins/functions/DSFinterp1DFit.py
PythonInterface/plugins/functions/Examples/Example1DFunction.py
PythonInterface/plugins/functions/Examples/ExamplePeakFunction.py
PythonInterface/plugins/functions/FickDiffusion.py
PythonInterface/plugins/functions/GuinierPorod.py
PythonInterface/plugins/functions/Guinier.py
PythonInterface/plugins/functions/HallRoss.py
PythonInterface/plugins/functions/Lorentz.py
PythonInterface/plugins/functions/Porod.py
PythonInterface/plugins/functions/StretchedExpFT.py
PythonInterface/plugins/functions/TeixeiraWater.py

**Comment by martyngigg** [comment]
Group 1 was fixed in #16814

**Comment by rosswhitfield** [comment]
I've moved `PythonInterface/plugins/algorithms/dnsdata.py` from group 2 to 3 because LoadDNSLegacy is the only thing that uses it so I will fix it at the same time.

**Comment by rosswhitfield** [comment]
Is the plan to fix the unittests for python3 after all the algorithms have been made compatible? Or should I be trying to fix them in the same pull request?

**Comment by martyngigg** [comment]
I'd say try and fix them in the same pull request.

**Comment by mganeva** [comment]
Group 6: PythonInterface/plugins/algorithms/TOFTOFConvertTofToDeltaE.py is deprecated and can be removed in the next release.

**Comment by rosswhitfield** [comment]
@martyngigg We have some regression with the python 3 unit tests, I see a lot of them are now segfaulting when the previously didn't. It looks like the ones that use `validateInputs`. Any idea?

```
385 - PythonInterface_SimpleAPITest (SEGFAULT)
489 - PythonAlgorithms_AddSampleLogMultipleTest (SEGFAULT)
490 - PythonAlgorithms_AlignComponentsTest (SEGFAULT)
491 - PythonAlgorithms_ApplyPaalmanPingsCorrectionTest (SEGFAULT)
494 - PythonAlgorithms_CalculateSampleTransmissionTest (SEGFAULT)
497 - PythonAlgorithms_CompareSampleLogsTest (SEGFAULT)
498 - PythonAlgorithms_ComputeCalibrationCoefVanTest (SEGFAULT)
501 - PythonAlgorithms_DetectorFloodWeightingTest (SEGFAULT)
502 - PythonAlgorithms_IndirectCalibrationTest (SEGFAULT)
503 - PythonAlgorithms_CorrectTOFTest (SEGFAULT)
505 - PythonAlgorithms_CylinderPaalmanPingsCorrection2Test (SEGFAULT)
507 - PythonAlgorithms_DNSComputeDetEffCorrCoefsTest (SEGFAULT)
508 - PythonAlgorithms_DNSMergeRunsTest (SEGFAULT)
509 - PythonAlgorithms_DNSFlippingRatioCorrTest (SEGFAULT)
512 - PythonAlgorithms_EnggCalibrateTest (SEGFAULT)
513 - PythonAlgorithms_EnggFitDIFCFromPeaksTest (SEGFAULT)
515 - PythonAlgorithms_EnggFocusTest (SEGFAULT)
517 - PythonAlgorithms_ExportSpectraMaskTest (Failed)
522 - PythonAlgorithms_FlatPlatePaalmanPingsCorrectionTest (SEGFAULT)
526 - PythonAlgorithms_IndirectAnnulusAbsorptionTest (SEGFAULT)
527 - PythonAlgorithms_IndirectCylinderAbsorptionTest (SEGFAULT)
528 - PythonAlgorithms_IndirectFlatPlateAbsorptionTest (SEGFAULT)
529 - PythonAlgorithms_IndirectILLReductionTest (SEGFAULT)
530 - PythonAlgorithms_IndirectResolutionTest (SEGFAULT)
533 - PythonAlgorithms_ILLIN16BCalibrationTest (SEGFAULT)
534 - PythonAlgorithms_IqtFitMultipleTest (SEGFAULT)
535 - PythonAlgorithms_IqtFitSequentialTest (SEGFAULT)
536 - PythonAlgorithms_ISISIndirectDiffractionReductionTest (SEGFAULT)
537 - PythonAlgorithms_ISISIndirectEnergyTransferTest (SEGFAULT)
544 - PythonAlgorithms_LoadNMoldyn3AsciiTest (SEGFAULT)
545 - PythonAlgorithms_LoadNMoldyn4Ascii1DTest (SEGFAULT)
546 - PythonAlgorithms_LoadNMoldyn4AsciiTest (SEGFAULT)
547 - PythonAlgorithms_MaskAngleTest (SEGFAULT)
552 - PythonAlgorithms_MolDynTest (Failed)
553 - PythonAlgorithms_MSDFitTest (SEGFAULT)
556 - PythonAlgorithms_OSIRISDiffractionReductionTest (SEGFAULT)
557 - PythonAlgorithms_ResNorm2Test (SEGFAULT)
559 - PythonAlgorithms_SANSFitShiftScaleTest (Failed)
561 - PythonAlgorithms_SaveNexusPDTest (SEGFAULT)
562 - PythonAlgorithms_SavePlot1DTest (SEGFAULT)
565 - PythonAlgorithms_SimulatedDensityOfStatesTest (SEGFAULT)
571 - PythonAlgorithms_Stitch1DManyTest (Failed)
574 - PythonAlgorithms_SuggestTibHYSPECTest (Failed)
576 - PythonAlgorithms_SymmetriseTest (SEGFAULT)
577 - PythonAlgorithms_UpdatePeakParameterTableValueTest (Failed)
578 - PythonAlgorithms_SANSDarkRunBackgroundCorrectionTest (SEGFAULT)
580 - PythonAlgorithms_TimeSliceTest (SEGFAULT)
581 - PythonAlgorithms_TOFTOFConvertTofToDeltaETest (SEGFAULT)
582 - PythonAlgorithms_TOFTOFCropWorkspaceTest (SEGFAULT)
583 - PythonAlgorithms_TOFTOFMergeRunsTest (Failed)
584 - PythonAlgorithms_TOSCABankCorrectionTest (SEGFAULT)
585 - PythonAlgorithms_TransformToIqtTest (SEGFAULT)
586 - PythonAlgorithms_ExportSampleLogsToCSVFileTest (Failed)
587 - PythonAlgorithms_ExportExperimentLogTest (Failed)
589 - PythonAlgorithms_VesuvioDiffractionReductionTest (SEGFAULT)
590 - PythonAlgorithms_VesuvioPreFitTest (Failed)
591 - PythonAlgorithms_VesuvioResolutionTest (SEGFAULT)
592 - PythonAlgorithms_VesuvioThicknessTest (Failed)
593 - PythonAlgorithms_VesuvioTOFFitTest (Failed)
```

**Comment by martyngigg** [comment]
@rosswhitfield I'm not sure off the top of my head. There was an issue with `3` where you could no longer use a `dict` without holding the global interpreter lock and `validateInputs()` does return a `dict` instance. I wonder if this is to do with my changes around the exception propagation?

**Comment by rosswhitfield** [comment]
All the groups are now complete **but** we have new algorithms added since this issues was created. So ...

**Group 10**
PythonInterface/plugins/algorithms/AngularAutoCorrelationsSingleAxis.py
PythonInterface/plugins/algorithms/AngularAutoCorrelationsTwoAxes.py
PythonInterface/plugins/algorithms/ExportSpectraMask.py
PythonInterface/plugins/algorithms/LoadPreNexusLive.py
PythonInterface/plugins/algorithms/VelocityAutoCorrelations.py
PythonInterface/plugins/algorithms/VelocityCrossCorrelations.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch.py
PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSPatchSensitivity.py
