### ISSUE TITLE
Extend ConvertAxisByFormula to support geometry argument

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#16770]
### Expected behavior
Unit  conversions that cannot be done through ConvertUnits but can be defined using an equation can be applied to the data.

### Actual behavior
Currently we have ConvertUints that only supports predefined units and links between them, and ConvertAxisByFormula that cannot handle any geometry aspect in the transformation.

### Steps to reproduce the behavior

Ansto have a dataset for which there is no sensible L1, but want to convert from wavelength to Momentum Transfer.

This is likely to come up more at reactor sources.
@ianbush Heads up!

### Platforms affected
All

**Comment by NickDraper** [comment]
@AntonPiccardoSelg This is the ticket we discussed

**Comment by SpencerHowells** [comment]
I've been struggling with this for years dealing with ILL diffraction data! Converting from angle to Q & vice versa.

**Comment by NickDraper** [comment]
This should be ready for testing soon, I've just submitted the pull request.
