### ISSUE TITLE
Unsupported MAC OS Issue

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#16788]
_This issue is based on feedback I received on the Mantid training course held at the MLZ in Munich June 30 - July 1._

A user was unable to load Mantid 3.7 using the following system:
MacBook Air
OS 10.9.5

Mantid 3.6 worked with no issues.

After installation. Mantid was "Verifying" indefinitely. Is there a way to show a message once an OS is no longer supported?

**Comment by quantumsteve** [comment]
@LamarMoore Mantid 3.6 and 3.7 should still run on OS X 10.9.*. While I see some benefit to a version check, there may be another issue here to see if we can reproduce and resolve.
