### ISSUE TITLE
Spectrum Viewer display in Radians

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#16792]
*This issue is based on feedback I received on the Mantid training course held at the MLZ in Munich June 30 - July 1.*

The `Image Info` tab of the Spectrum Viewer contains angles in radians which has proven useless to some of the instrument scientists. They would prefer if angles were displayed in degrees as was the case in previous versions of Mantid.

Dr Marina Ganeva of MLZ stated:

*"Radians as units make this information completely useless, because the displayed angle in radians will be the same for 50 detectors."*

![image](https://cloud.githubusercontent.com/assets/15360272/16580238/5c346986-429b-11e6-89fa-863f3c16ffc8.png)

**Comment by AndreiSavici** [comment]
It is not in radians. I tried to run it on CNCS_7860, with largest two theta around 130 degrees, but on spectrum viewer I could not get a two theta greater than 0.05

**Comment by mganeva** [comment]
I've checked, for TOFTOF is the same: it is not radians. For radians the situation would not be that bad. However, degrees would provide much better accuracy.

**Comment by AndreiSavici** [comment]
https://github.com/mantidproject/mantid/blob/c3e2386103a6b7080489e65cc50e6383e149d2be/MantidQt/SpectrumViewer/src/MatrixWSDataSource.cpp#L289 needs to be rad2deg. Same on next line
