### ISSUE TITLE
Windows 7 installation issue

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#16793]
*This issue is based on feedback I received on the Mantid training course held at the MLZ in Munich June 30 - July 1.*

When installing MantidPlot on a fresh installation of Windows 7, users have issues selectively installing the security update mentioned on the MantidPlot download page. The update tool becomes unresponsive as it attempts to download and install a very large number of security updates.

**Comment by NickDraper** [comment]
I'm not sure what we can or should do about this.   If the version is heavily behind in security patches this could always be a problem.
