### ISSUE TITLE
ConvertUnits Sets EMode on failed run

### ISSUE THREAD

**Issue by EltayebAhmed** [mantidproject/mantid#16794]
### Expected behavior
ConvertUnits Should work fail each time if the emode is not specified for a conversion that needs it.

### Actual behavior
ConvertUnits fails on first trial, but sets deltaE-mode when working on in in place change, so it  Succeeds on Second trial. 

### Steps to reproduce the behavior
Terminal log Containing Behaviour 
File is 1642000.nxs is part of sample training data
[164200.zip](https://github.com/mantidproject/mantid/files/347442/164200.zip)
```
>>>ws3 = Load('164200.nxs')

>>>ws3 = ConvertUnits(ws3,Target = 'DeltaE')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-82-0c2849963340> in <module>()
----> 1 ws3 = ConvertUnits(ws3,Target = 'DeltaE')

C:\MantidInstall\bin\mantid\simpleapi.pyc in algorithm_wrapper(InputWorkspace,Target,EMode=None,EFixed=None,AlignBins=None, Version=1)
    879 
    880         try:
--> 881             algm.execute()
    882         except RuntimeError, e:
    883             if e.args[0] == 'Some invalid Properties found':

RuntimeError: ConvertUnits: error (see log)

>>>ws3 = ConvertUnits(ws3,Target = 'DeltaE')
>>>
```

### Platforms affected
Tested MantidPlot 3.7.1 on Windows 7

**Comment by NickDraper** [comment]
It also sets the unit, and would undo the bin width division of distribution data

**Comment by NickDraper** [comment]
## Units that perform validation

#### DeltaE

if (efixed == 0.0)
    throw std::invalid_argument(
        "efixed must be set for energy transfer calculation");

    throw std::invalid_argument(
        "emode must be equal to 1 or 2 for energy transfer calculation");

#### SpinEchoLength

  if (efixed == 0.0)
    throw std::invalid_argument(
        "efixed must be set for spin echo length calculation");
  if (emode > 0) {
    throw std::invalid_argument(
        "emode must be equal to 0 for spin echo length calculation");
  }
