### ISSUE TITLE
Fitting histogram data, not points

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16796]
From Mantid forum, http://forum.mantidproject.org/t/fitting-histogram-data-not-points/130

*For a histogram data set, at present, fitting evaluates the function at the centre of each bin. If the bins are large and the function has any significant curvature, the point value can differ from the average over the bin, which is what the data probably represents. If there are fast "wiggles" in the fit function these can really confuse the fit if the maximum or minimum happens to line up with the bin centre and has the right sign to appear to improve the fit.*

*Often it's easy to analytically integrate a fit function over a range of X values, so the correct average and its derivatives could be calculated with little extra effort.*

*Could a fit function declare that it knows about this, and is then passed an X array of bin edges to work with, and a flag to say so?*

*Alternatively a function could assume it is always working with a histogram and reconstruct the bin edges for itself (as ConvertToHistogram does) and then do the averaging. That assumes equal sized bins which is usually the case.*

*The attached script demonstrates the problem. It fits a Lorentzian to a generated Lorentzian plus a small amount of noise, with various degrees of binning. I've defined the bin-size-aware fit function for comparison with the built in one.*

[HistoAwareFits.py.txt](https://github.com/mantidproject/mantid/files/347712/HistoAwareFits.py.txt)

*The point-data function slightly over-estimates the amplitude if the bins are too big, significantly over-estimates the FWHM, and there can be scatter in the peak centre value depending on how the peak lines up with the bin boundaries.*

---

@mantid-roman Do you know if this would be possible to implement?

**Comment by mantid-roman** [comment]
@tom-perkins Yes it can be done.
