### ISSUE TITLE
ParaView fails to build with CMake 3.6

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#16830]
### Expected behavior

ParaView builds with CMake 3.6
### Actual behavior

HDF5 is not found.

```
21:43:39 CMake Error at /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
21:43:39   Could NOT find HDF5 (missing: HDF5_HL_LIBRARIES) (found version "1.8.16")
21:43:39 Call Stack (most recent call first):
21:43:39   /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
21:43:39   /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/FindHDF5.cmake:707 (find_package_handle_standard_args)
21:43:39   VTK/CMake/FindHDF5.cmake:6 (include)
21:43:39   VTK/CMake/vtkModuleMacros.cmake:844 (find_package)
21:43:39   VTK/ThirdParty/hdf5/CMakeLists.txt:1 (vtk_module_third_party)
21:43:39 
21:43:39 
21:43:39 -- Configuring incomplete, errors occurred!
```

ParaView fails to build

```
23:01:18 [  1%] Linking C shared library ../../../../lib/libvtkNetCDF-pv5.1.dylib
23:01:19 Undefined symbols for architecture x86_64:
23:01:19   "_H5DSattach_scale", referenced from:
23:01:19       _vtk_netcdf_nc4_rec_write_metadata in nc4hdf.c.o
23:01:19       _rec_reattach_scales in nc4hdf.c.o
23:01:19   "_H5DSdetach_scale", referenced from:
23:01:19       _vtk_netcdf_nc4_rec_write_metadata in nc4hdf.c.o
23:01:19       _rec_detach_scales in nc4hdf.c.o
23:01:19   "_H5DSget_num_scales", referenced from:
23:01:19       _read_dataset in nc4file.c.o
23:01:19   "_H5DSget_scale_name", referenced from:
23:01:19       _read_dataset in nc4file.c.o
23:01:19   "_H5DSis_scale", referenced from:
23:01:19       _read_dataset in nc4file.c.o
23:01:19   "_H5DSiterate_scales", referenced from:
23:01:19       _read_dataset in nc4file.c.o
23:01:19   "_H5DSset_scale", referenced from:
23:01:19       _vtk_netcdf_nc4_rec_write_metadata in nc4hdf.c.o
23:01:19 ld: symbol(s) not found for architecture x86_64
23:01:19 clang: error: linker command failed with exit code 1 (use -v to see invocation)
23:01:19 make[2]: *** [lib/libvtkNetCDF-pv5.1.1.dylib] Error 1
23:01:19 make[1]: *** [VTK/ThirdParty/netcdf/vtknetcdf/CMakeFiles/vtkNetCDF.dir/all] Error 2
23:01:19 make[1]: *** Waiting for unfinished jobs....
```
### Steps to reproduce the behavior

Build ParaView on a machine with CMake 3.6
### Platforms affected

Any with CMake 3.6 installed

**Comment by quantumsteve** [comment]
On OS X, FIndHDF5 works only after adding the hint -DHDF5_ROOT=/usr/local/opt/hdf5. 

Cherry-picking [this commit](https://github.com/Kitware/VTK/commit/351d0a6d1ce13daef7e52ed988f843aae0ff9fbf) appears to fix the linking errors.

**Comment by quantumsteve** [comment]
I updated our OS X buildscripts to workaround the issues I encountered building v5 and v5.1. 

 https://github.com/mantidproject/paraview-build/commit/e4832ad8d73a8536174108d87090f61b6c248557

https://github.com/mantidproject/paraview-build/commit/c4d9c70734fc2f7f9f8d84e71ddb12dc22457118

**Comment by quantumsteve** [comment]
@NickDraper @peterfpeterson This should also be checked on Windows and Linux

**Comment by quantumsteve** [comment]
CMake issue and merge request
https://gitlab.kitware.com/cmake/cmake/issues/16190
https://gitlab.kitware.com/cmake/cmake/merge_requests/34

VTK merge request
https://gitlab.kitware.com/vtk/vtk/merge_requests/1679

**Comment by peterfpeterson** [comment]
Do we need to wait until kitware moves forward before we suggest cmake 3.6 to developers?

**Comment by quantumsteve** [comment]
@peterfpeterson Mantid has the same issues with the new FindHDF5, which we'll have to work around (see #16829). We'd benefit from at least one early adopter on Windows, Linux, and OS X.

**Comment by quantumsteve** [comment]
I've worked around the build issues with CMake 3.6 on OS X and verified that the linking errors will be addressed in ParaView 5.1.1.

@NickDraper @peterfpeterson Would you please assign one or more people to verify we can still build ParaView with CMake 3.6 on Windows and Linux?

**Comment by peterfpeterson** [comment]
Works just fine on fc23

**Comment by NickDraper** [comment]
Anton can you check that we can still build ParaView with CMake 3.6 on Windows?

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve 
Using the builder scripts I built PV (5.1.0) with Cmake3.6.0 on Windows 7.

The build compiled without errors but with loads of warnings ( I think they are normally there). PV runs fine.

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve  After building PV (5.1.0) with Cmake3.6.0 on Windows 7 with an up-tod-ate third-party-folder, it still appears to be fine.

**Comment by peterfpeterson** [comment]
We're using cmake 3.8
