### ISSUE TITLE
Indirect Corrections - Use new sample geometry in Absorption algorithms

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16843]
### Expected behavior

Indirect Absorption algorithms:
- `IndirectCylinderAbsorption`
- `IndirectAnnulusAbsorption`
- `IndirectFlatPlateAbsorption`

should use the new sample geometry. These should be able to use the same tests that are currently being used (with some minor adaptation)
### Actual behavior

Currently still using old sample geometry
### Steps to reproduce the behavior

N/A
### Platforms affected

N/A

Spencer has suggested that these be implemented as version 2 of each of these algorithms for the time being to ensure that a working version is retained while the new corrections are tested.

**Comment by SpencerHowells** [comment]
The MonteCarloAbsorption algo has a new parameter Interpolation which should be set to 'CSpline'
