### ISSUE TITLE
Chained BinMD in SliceViewer

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#16860]
Pascal and Users found an issue while reducing WISH data on a recent experiment. I have been able to reproduce the issue with a simple python script. While a single `BinMD` call works fine, **Instrument Scientists will run an initial `BinMD` to improve statistics and identify features before running `BinMD` a second time to create a slice of interest, all using the SliceViewer.**

**This is a high-priority fix for the next Mantid Version**

1) Run this in MantidPlot
```python
# Lets create a fake MDWorkspace
mdworkspace = CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='H,K,L', Units='U,U,U')
# Add A Peak at H=0, K=0, L=1
FakeMDEventData(InputWorkspace=mdworkspace, PeakParams='100000,0,0,0,1')
# Add another peak at H=2, K=2, L=0
FakeMDEventData(InputWorkspace=mdworkspace, PeakParams='100000,2,2,0,1')
```
2) Now open the SliceViewer
```python
# Open SliceViewer and set the slice point to K=1, half-way between the two Peaks.
plotSlice(mdworkspace, xydim=['H','L'], slicepoint=[0,1,0]) 
```

3) Now Integrate over a region in K of thickness 1.00. I'm in Rebin Mode. Here's the plot I get. I can correctly see both Peaks (image below). 
![image](https://cloud.githubusercontent.com/assets/1109536/16801032/4795cb40-48f0-11e6-8b06-11c829b0b4af.png)
Furthermore, looking at the history of the generated slice `mdworkspace_rebinned` I can see that the OutputExtents are correct `-1.2,3,6,0,2,-1.2,1.2`, exactly as I specified in the SliceViewer.

4) Now open the SliceViewer again, but this time on the `mdworkspace_rebinned`. Cosmetically I get the correct view of the slice (below). However, note that **K=0, which is wrong/inconsistent, because in the first rebin, I took my slice at **K=1**

![image](https://cloud.githubusercontent.com/assets/1109536/16801206/30163594-48f1-11e6-9ea5-0c6beb0cfd0a.png)

5) Now hit the Rebin button. I now get the correct slice at K=0 (we can only see the first peak we added), but this does not correspond to the original view I had loaded.
![image](https://cloud.githubusercontent.com/assets/1109536/16801268/9be27134-48f1-11e6-874f-a3e81e3a9ead.png)
Also, although I have been allowed to enter Rebin mode, on the SliceViewer, it has not provided me with the ability to set the slice position or thickness I wanted. The thickness seems to be hard-coded to +/- 0.1 in this case looking at the history of the BinMD call.

## How I suspect this should be fixed.

1. We know that `BinMD` on the second-call will look at it's `MDHistogramWorkspace`, establish the original `MDWorkspace`, and perform the `BinMD` on that. For the second rebin, therefore in the SliceViewer, it seems to forget the extents that have already been applied in the first `BinMD`. I think the sliceviewer should ensure that `OutputExtents` are taken from the input `MDHistoWorkspace`, when performing a second BinMD call.  
2. In the case of performing this type of rebin, it should be possible for the user to specify the thickness, as they where able to in the first Rebin. That would stop the +/- 0.1 hardcoded thickness being fixed.
3. SliceViewer python tests should be added to cover these use cases.

**Comment by samueljackson92** [comment]
Quick discussion with Owen. There's some extra points here:
 - Thickness option appears to be hidden by the fact the K axis has only one bin. So this may not be an issue, but we should confirm.
 - K value is still not updated on interface despite initial fix.
 - Because slice point selector/thickness is not visible the bin is. But shows the incorrect value! We should update this to show the correct bin.
