### ISSUE TITLE
Changes to ISIS Reflectometry GUI (Polref)

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16868]
Scientists at ISIS have provided a new version of the GUI. A design document sent by Max can be found [here](https://github.com/mantidproject/documents/blob/master/Design/Reflectometry/Mantid_SuperGUI_v1.1.pptx). This is an umbrella ticket to add new features to the existing interface.

**Comment by raquelalvarezbanos** [comment]
Blocked by
- [ ] https://github.com/mantidproject/mantid/issues/16869

**Comment by gemmaguest** [comment]
I'm closing this issue because it is now only dependent on #17029, and we already have another umbrella ticket for that (#15566).
