### ISSUE TITLE
Incorrectly rendered latex formulae in VSI with matplotlib < 1.3

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#16873]
### Expected behavior

Equations should be displayed as expected.
### Actual behavior

On RHEL7:
![vsi-latex-rhel7](https://cloud.githubusercontent.com/assets/733773/16832958/cfe2159e-49a4-11e6-9a05-4b2648af0eac.png)

while on Ubuntu with mpl v1.3.1:
![vsi-latex-ubuntu](https://cloud.githubusercontent.com/assets/733773/16832994/03f58eec-49a5-11e6-82b9-f2bfafca1e92.png)
### Steps to reproduce the behavior

This will not produce the above picture but a simplified version that demonstrates the same error.

Run the following script:

``` python
CreateSimulationWorkspace(Instrument='mari', BinParams='-90,0.01,100', OutputWorkspace='mari')
AddSampleLog(Workspace='mari', LogName='ei', LogText='90.1', LogType='Number')
ConvertToMD(InputWorkspace='mari', QDimensions='Q3D', OutputWorkspace='mdws')
```

and open the `mdws` in the VSI. On RHEL 7 you notice that the superscript is not drawn correctly. It should be a -1 but instead a symbol is drawn.
### Platforms affected

I think this just affects those platforms with mpl < 1.3: RHEL 6, RHEL 7

I tried upgrading matplotlib with pip using `pip install --user --upgrade --no-deps matplotlib`, which installs it in the user's home directory. The equations are then rendered correctly.

**Comment by quantumsteve** [comment]
Stuart backported matplotlib 1.3.1 for RHEL 7 and put them on packages.sns.gov. @stuartcampbell Are they on copr or another more accessible location?

**Comment by quantumsteve** [comment]
Are there enough RHEL 6 machines left to justify an updated matplotlib rpm? What version does `pip install matplotlib` provide on RHEL 6?

**Comment by martyngigg** [comment]
We have only a few instrument cabin PCs that will be around until December. As there is a workaround it would probably be okay to just update the RHEL 7 packages.

**Comment by martyngigg** [comment]
@stuartcampbell Would it be possible to build `matplotlib` 1.5.1 packages for RHEL 7?

MSlice is going to need it and it will fix this issue too.

**Comment by stuartcampbell** [comment]
@martyngigg I've been trying to get 2.0 working...

**Comment by martyngigg** [comment]
@stuartcampbell How's it going?

**Comment by martyngigg** [comment]
@stuartcampbell I can see `matplotlib-1.5.2` in [mantid/mantid copr](https://copr.fedorainfracloud.org/coprs/mantid/mantid/package/python-matplotlib/). Are they ready to go or are they the ones that we were having trouble with?

**Comment by stuartcampbell** [comment]
@martyngigg To my knowledge they seem to work ok.  It was v2.0 that I was having issues with.

**Comment by martyngigg** [comment]
@stuartcampbell Thanks. Are we okay at putting the minimum matplotlib version to 1.5 for RHEL 7 then?

**Comment by stuartcampbell** [comment]
@martyngigg I think so, what tests should we do before pulling the 'trigger'?

**Comment by martyngigg** [comment]
At minimum we should run the above test with the VSI. I would then also try out some basic `matplotlib` stuff in and outside MantidPlot.

**Comment by martyngigg** [comment]
I've just tried this out on a RHEL7 box with the RPMs from copr. It looks good:

![vsi-latex-rhel7-mpl1 5](https://cloud.githubusercontent.com/assets/733773/20064023/1a49b486-a501-11e6-9e59-4f6edee7573b.png)

**Comment by martyngigg** [comment]
I have the changes at https://github.com/mantidproject/mantid/compare/master...matplotlib-1.5-el7. I'm going to put the RPMs from copr in the ISIS repo before opening the pull request. Do they need to be in the SNS repo too?

**Comment by martyngigg** [comment]
@stuartcampbell Should the dependency be `python2-matplotlib` or `python2-matplotlib`?
