### ISSUE TITLE
Extend MergeRuns to allow merging of sample logs

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#16928]
Currently MergeRuns just keeps the metadata from the first file in any merge. This is a problem at the ILL where some metadata should be averaged, summed, taken as min/max etc.

This issue should address this by extending MergeRuns to treat the metadata as expected. For any particular sample log the operation when merging needs to be defined. The instrument parameters file can be extended to include how to treat required sample logs.

If any sample logs that are given in the instrument parameters file are missing they should be skipped.

This is very similar behaviour to that in [TOFTOFMergeRuns](http://docs.mantidproject.org/nightly/algorithms/TOFTOFMergeRuns-v1.html). This ticket will provide an alternative to TOFTOFMergeRuns that should produce the same results.

TOFTOFMergeRuns also checks some parameters match in the files it is merging. These should also be configurable in the instrument parameter file.

**Comment by SimonHeybrock** [comment]
@ianbush I just read your comments regarding `TOFTOFMergeRuns` in the issue description. Would it now be possible to use `MergeRuns` internally in `TOFTOFMergeRuns`?
