### ISSUE TITLE
Indirect BayesQuasi - Refactor addition of Sample logs

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16966]
### Expected behavior
* The BayesQuasi algorithm should use the IndirectBayes.py script as little as possible. If any of the imports it currently uses (including but not limited to` QLAddSamplelogs`) are only used by BayesQuasi then refactor them into the algorithm. If other algorithms (check ResNorm2.py and [BayesStretch](https://github.com/mantidproject/mantid/pull/16944) ) use these imports we can discuss how it is best to deal with them. 

### Actual behavior
* Currently it imports the following:
```
from IndirectBayes import (CalcErange, GetXYE, ReadNormFile, ReadWidthFile, QLAddSampleLogs, C2Fw, C2Se, QuasiPlot)
```

### Steps to reproduce the behavior
* Code review

### Platforms affected
* All

**Comment by ElliotAOram** [comment]
Once you refactor the functions from IndirectBayes -> BayesQuasi make sure you delete the functions from IndirectBayes. The unit tests should then fail for any other algorithms depending on these (although I think it should be none!)

**Comment by SpencerHowells** [comment]
This algo reads ascii files in readAsciiFile & ReadWidthFile. Shouldn't we take this opportunity to change 'r' to 'U' in the handle call?

**Comment by ElliotAOram** [comment]
Good idea! @louisemccann can you also makes this change?

**Comment by SpencerHowells** [comment]
Do we still have Plot & Save in the algo rather than the gui?

**Comment by ElliotAOram** [comment]
@SpencerHowells yes I noticed this the other day. I must have forgotten to move it over when I initially rewrote this. I think given the size of the issue it might be worth creating a separate issue

**Comment by SpencerHowells** [comment]
I agree.

**Comment by ElliotAOram** [comment]
#17012
