### ISSUE TITLE
Improvements to the Reflectometry GUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17028]
This is an umbrella issue. Scientists have provided a design document that can be found [here](https://github.com/mantidproject/documents/blob/master/Design/Reflectometry/Mantid_SuperGUI_v1.1.pptx) for an improved version of the ISIS Reflectometry interface.

Sub-issues (add more as needed):
- [x] https://github.com/mantidproject/mantid/issues/16734
- [x] https://github.com/mantidproject/mantid/issues/16869
- [x] https://github.com/mantidproject/mantid/issues/16983
- [ ] https://github.com/mantidproject/mantid/issues/17029

**Comment by raquelalvarezbanos** [comment]
Umbrella issue. 

#16983 should be done for release 3.9
#17029 should be done for release 3.10

Therefore, marking this against release 3.10

**Comment by gemmaguest** [comment]
I'm closing this issue because it is now only dependent on #17029, and we already have another umbrella ticket for that (#15566).
