### ISSUE TITLE
HistogramData Rollout Framework/Algorithm P

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#17040]
HistogramData rollout based on new Histrogram interface introduced to mantid. This issue deals with files in Framework/Algorithm starting with the letter P and their associated unit tests. See here.

Files to be checked (and their associated unit tests):
Pause
PDDetermineCharacterizations
PDFFourierTransform
PerformIndexOperations
PhaseQuadMuon
PlotAsymmetryByLogValue
Plus
PointByPointVCorrection
PoissonErrors
PolarizationCorrection
PolynomialCorrection
Power
PowerLawCorrection

**Comment by martyngigg** [comment]
Closing as not worth consolidated effort in maintenance. Reveiwers can pick up and improve remaining code over time.
