### ISSUE TITLE
Add workflow diagram for the PEARL scripts

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#17046]
Add a workflow algorithm for these scripts: http://docs.mantidproject.org/nightly/api/python/techniques/PearlPowderDiffractionISIS-v1.html#pearl-powder-diffraction-ref
(similarly as it was done for the "CRY" scripts, although much simpler: http://docs.mantidproject.org/nightly/api/python/techniques/CryPowderDiffractionISIS-v1.html#cry-powder-diffraction-ref).

This requires going through the code, and understanding what are the input/output files and workspaces and how these are produced by the sequence of algorithms. The inputs and outputs should be clearly visible, and it should also show where the absorption correction happens in the workflow.

**Comment by DavidFair** [comment]
Initially just map out Focus algorithm to check core functionality

**Comment by FedeMPouzols** [comment]
The core routine is `pearl_run_focus`: https://github.com/mantidproject/mantid/blob/master/scripts/PearlPowderISIS/pearl_routines.py#L343
Let's focus on this one for a first diagram.

**Comment by FedeMPouzols** [comment]
Later on we could address `pearl_createvan`: https://github.com/mantidproject/mantid/blob/master/scripts/PearlPowderISIS/pearl_routines.py#L621.
