### ISSUE TITLE
ISplittersWorkspace is not a workspace

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#17051]
[ISplittersWorkspace](https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/ISplittersWorkspace.h) does not inherit any workspace types. [SplittersWorkspace](https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/inc/MantidDataObjects/SplittersWorkspace.h) inherits `ISplittersWorkspace` and [TableWorkspace](https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/inc/MantidDataObjects/TableWorkspace.h). The documentation hinted that this class was supposed to inherit [ITableWorkspace](https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/ITableWorkspace.h). This breaks [WorkspaceListProperty](https://github.com/mantidproject/mantid/issues/17035) which uses a template definition for workspace types.

**Comment by AndreiSavici** [comment]
@wdzhou might be interested in this issue
