### ISSUE TITLE
Extending the functionality of parameters in fit functions

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#17067]
A high priority here in SNS regarding QENS data has become global fitting, and in this context there's a non-trivial issue regarding the parameters of a fit function: Many a times the user wants to impose certain Q-dependence on the fit parameter rather than infer that dependence from a plot of the parameter versus Q, after the carrying out the fit.

One example: User wants a Fourier transforma of the stretched exponential with the relaxation time following a power-law. Now instead of \tau I have two fit parameters, and are Q-independent by design.

![capture](https://cloud.githubusercontent.com/assets/1136006/17303812/4feb0774-57f0-11e6-88ba-67df5e086e4e.GIF)

In the previous example, we cannot reuse the already existing `StretchExpFT` fit function, Instead, one would have to code from a whole new fit function. A possible solution is to expose `StretchExpFT` in python and then _dynamically_ instantiate a new fit function class that will integrate `StretchExpFT` and the previous Q-dependence. This new fit function would have parameters _p_4_ and _p_5_ instead of \tau.

**Comment by jmborr** [comment]
@mantid-roman @louisemccann @ElliotAOram @gvardany @martyngigg @stuartcampbell 
Dear all,
This is a design issue on the fit functions that is quite pressing for QENS data. Please take a look and share your ideas and comments about possible ways to solve.
Best,
.Jose

**Comment by stuartcampbell** [comment]
@martyngigg Isn't this in all practical sense the same as the model fitting parts of TobyFit ?

**Comment by martyngigg** [comment]
@stuartcampbell Yes I think so. There is some parametrized resolution portion convoluted with a specified user model. I don't think I see away around having to add/wrap `StretchExpFT` in some way though.

There are still many questions hanging over the TobyFit stuff. Not least would be that I'm not wedded to the particularly design as I think the way we wanted to go with being able to define the user model functions more simply in Python means somethings will have to change.

There is also the question of what we should be fitting. The current framework only understands MD events but should probably be able to accept histograms too.

**Comment by jmborr** [comment]
Not feasible in current C++ fitting framework without major refactoring. Maybe makes more sense to extend a model with the python interface
