### ISSUE TITLE
Invalid indices generated while using the Slice Viewer.

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#17084]
### Expected behavior

The code comment [here](https://github.com/mantidproject/mantid/blob/966c761c696da7845cedc4fe94af83758612dd9d/Framework/DataObjects/src/MDHistoWorkspace.cpp#L622) says so invalid indices should never occur.
### Actual behavior

In PR #17083, I found that an invalid index ( `= size_t(-1)` ) is being generated. I added checks to avoid the out-of-bounds memory accesses, but the larger issue still exists.
### Steps to reproduce the behavior

Check for invalid values of `linearIndex` while using the Slice Viewer or running `SliceViewerMantidPlotTest_SliceViewerPythonInterfaceTest`.
### Platforms affected

All

This was found in issue #16583.

**Comment by quantumsteve** [comment]
@matthew-d-jones Would you mind looking into this?

**Comment by matthew-d-jones** [comment]
@quantumsteve Sorry, I'm not working on Mantid now, but whoever works on this issue is welcome to talk with me about it on Slack, or in person if they are at ISIS.

**Comment by quantumsteve** [comment]
@NickDraper Please assign as appropriate.

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew Might be good to speak to Matthew Jones about this

**Comment by Mantid-Matthew** [comment]
Refers to old version of slice viewer.
