### ISSUE TITLE
Abragam function parameters

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17108]
See #17054:

The [documentation](http://docs.mantidproject.org/nightly/fitfunctions/Abragam.html) for the `Abragam` fitting function is not clear about what some of the parameters represent, and the form of the function is different to some expressions seen elsewhere (notably, it is different to WiMDA). 

To ask scientists at the next muon meeting:
- Confirm what the parameters are, in particular `sigma` and `tau` 
- Confirm the scientists are happy with the function's form and the difference to how it is implemented elsewhere

Once we have this information, update the documentation accordingly.

**Comment by tom-perkins** [comment]
Notes: 
- The function in the documentation does not match the code exactly. What we have is:
![abragam_mantid](https://cloud.githubusercontent.com/assets/15363125/17402229/0219ae2c-5a4a-11e6-9424-03bf34705980.png)

- Unclear whether it is supposed to be for transverse or longitudinal field
- `sigma` is not the decay rate (likely the width of local fields? `Delta` in other functions) and `tau` is probably the muon lifetime

**Comment by tom-perkins** [comment]
To do at next muon meeting. Time estimate to update docs is < 1 hour once we have the answers to these questions from the scientists.

**Comment by Anders-Markvardsen** [comment]
Contact Francis Pratt - recommendation from a muon meeting
