### ISSUE TITLE
`MuonAnalysis` documentation: update links to point to new .rst file

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17119]
When PR https://github.com/mantidproject/mantid/pull/17118 is merged, update the link on http://www.mantidproject.org/Muon to point to the new .rst file. The old [wiki page](http://www.mantidproject.org/MuonAnalysisHome) can then be removed.

**Comment by tom-perkins** [comment]
[x] PR merged

Note that the help ("?") buttons on the Muon Analysis interface currently bring up the wiki page. These need redirecting to the rst help pages too.
