### ISSUE TITLE
Engg:: EnggDiffFittingPresenter::fittingRunNoChanged refactor

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17131]
Currently checks for if the string `strFPath` is a file or list of files is checked in this function. This check should be moved to `MWRunFiles` where the check is already done and only files are returned. The code should then be refactored to remove any parts that worked on lists of files.

**Comment by shahrozahmed1** [comment]
`MWRunFiles` cannot be used as we are using focused file as input which has a name format of `ENGINX_194547_focused_bank_4.nxs`.
