### ISSUE TITLE
Create ExtractMonitorSpectra algorithm

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#17138]
This algorithm should behave similarly to `ExtractMonitorWorkspace`, but to be used where monitors and detectors are mixed within a workspace.

The algorithm should output the original workspace, with the same name, without monitors, and a new, separate workspace for the monitors.

The new monitor workspace should be set as the monitor workspace for the original workspace.

This allows the monitors to be separated, as for `LoadEventNexus`. However, for the ILL keeping the monitor workspace separate when initially loading causes problems for loading multiple files. This algorithm will also allow the monitor workspace to be separated at a chosen point (e.g. after loading or after background subtraction).

**Comment by NickDraper** [comment]
Eltayeb, this would be a good one to start with.

I suggest SeparateMonitorSpectra if it outputs both the data and the monitors as separate workspaces.
