### ISSUE TITLE
Engg:: If default instrument is not set calibration fails to find files

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17140]
If the default instrument is not set to EnginX on the start-up screen the interface will fail to select and instrument and subsequently fail to find the necessary files.

@FedeMPouzols We could either select EnginX by default or give an error informing the user they have not selected an instrument. Which behaviour would be best?

**Comment by FedeMPouzols** [comment]
Yes this is an assumption that is not well explained at present.
- The less intrusive alternative is to show a very visible message warning the user (for example at startup, in the `showEvent()`).
- The more instrusive alternative is to change the instrument to the one selected in the interface (Only ENGIN-X for now, but IMAT following soon), saving the instrument selected and restoring it when the interface is closed.
- The best alternative would be to make sure that the interface always inserts the instrument prefix conveniently when looking for files.

From the point of view of the third/best alternative, I think that the current status is that we are doing the right thing in the "MWRunFiles" widgets (using `setInstrumentOverride()` but doing it wrong in some algorithms (file loaders). This is related to the point of whether the code should be passing around run numbers or full file names.
