### ISSUE TITLE
ReflectometryReductionOne remove rebin in wavelength

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#17162]
This is split off from task 2 of #16455. Rebinning the detector workspace in wavelength is unwanted and should be removed (though `CropWorkspace` is fine). In addition, the `WavelengthStep` property is used solely with this portion of the code so it should be removed as well.

**Comment by PranavBahuguna** [comment]
@raquelalvarezbanos One of the system tests (OFFSPECReflRedOneAuto) makes use of the `wavelengthStep` parameter that has now been removed. The result is then compared to "OFFSPECReflRedOneAuto_good_v3.nxs". However without the wavelength rebin, the result from the system no longer matches this file. Should I edit the file so it does match without wavelength rebinning, or should I remove the test altogether if it no longer serves any purpose?

**Comment by raquelalvarezbanos** [comment]
@PranavBahuguna I would say that tests should not be removed unless there's a good reason to do so. In this case I think that what we should do is replace the reference file.
