### ISSUE TITLE
segfault when algorithm dialog opens when MD workspace is present

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#17165]
The problem doesn't exist at d1be85cb95a75b9ad7b3b0ae4255e861e773499b but does exist at 1e56170f874b7d5b1ff5d58e66d89e77c8d6ed0f therefore was introduced with #16967 

To reproduce:
* Load a MD workspace `mdws = LoadMD('MAPS_MDEW.nxs')`
* Open an algorithm dialog which **doesn't** take a MD workspace as input. _e.g._ `Plus`

Result is:
```
MantidApplication-[Fatal] Unexpected exception: basic_string::_M_create
MantidApplication-[Fatal] Continue working.
tcmalloc: large alloc 7021238724389208064 bytes == (nil) @ 
MantidApplication-[Fatal] Unexpected exception: std::bad_alloc
MantidApplication-[Fatal] Continue working.
bin/launch_mantidplot.sh: line 49: 23857 Segmentation fault      (core dumped) LD_PRELOAD=${LOCAL_PRELOAD} TCMALLOC_RELEASE_RATE=${TCM_RELEASE} TCMALLOC_LARGE_ALLOC_REPORT_THRESHOLD=${TCM_REPORT} LD_LIBRARY_PATH=${LOCAL_LDPATH} QT_API=pyqt $VGLRUN$INSTALLDIR/MantidPlot $*
```

MD algorithms work fine _e.g._ `PlusMD`

It looks like MD workspaces are being included in the list of possible InputWorkspaces when they shouldn't be.

@AndreiSavici and @VickieLynch can confirm the problem.

cc: @raquelalvarezbanos @FedeMPouzols @martyngigg as you were also involved in the pull request

**Comment by AndreiSavici** [comment]
I tried the following:
```
Load(Filename='CNCS_7860', OutputWorkspace='CNCS_7860_event')
ConvertToMD(InputWorkspace='CNCS_7860_event', QDimensions='Q3D', dEAnalysisMode='Elastic', QConversionScales='HKL', OutputWorkspace='b')
```
Then from the MantidPlot GUI I try to create another MD workspace, with a different name. Sometimes it works, sometimes it crashes. It depends on the name of the output workspace

**Comment by peterfpeterson** [comment]
This is **not** a MD specific issue. Another way to produce it:
42. `CreateEmptyTableWorkspace` with any name for the workspace
42. `Add` gui/dialog
42. :boom: with a message about `Attempt to free invalid pointer`
