### ISSUE TITLE
Engg:: Create script to convert peak CSV files to worksheets in Excel

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17185]
Following discussions with the instrument scientists they would like each peak to have its own worksheet within a workbook in Excel. To maintain compatibility we save the details of these peaks in individual CSV files so a file would be created per peak. 

A script will be needed to convert a large amount of the output csv files into worksheets. Attached is some links for potential methods of completing this:
`http://stackoverflow.com/questions/5705588/python-creating-excel-workbook-and-dumping-csv-files-as-worksheets`
`https://pypi.python.org/pypi/openpyxl`

**Comment by josephframsay** [comment]
Engineering scientists no longer appear to have any need for this piece of functionality
