### ISSUE TITLE
Set parameters from log: more flexible combinations

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17184]
See #16494: introduced option to set parameters to log value in Edit Local Parameters dialog (multi-dataset fitting).

Users would like to have greater flexibility here. For example, instead of setting a parameter to one log value like `Field_Z`, they may want to use a sum like `Field_Main + Field_Z`, or log value plus constant, or a conversion like field -> frequency. 

There should be some way to specify a combination of log values that will be used, perhaps a box to type into or a separate dialog to build the selected combination.

**Comment by tom-perkins** [comment]
It would be best to have the ties to log values in the fit function string itself. This would be more general and you'd also be able to change the data and use the same function without having to re-set all the parameter values to logs. See [`ConvertAxisByFormula`](http://docs.mantidproject.org/nightly/algorithms/ConvertAxisByFormula-v1.html) for an example of how this could be done.

**Comment by tom-perkins** [comment]
Priority for release 3.9: this has been asked for by scientists and would be useful to a number of users

**Comment by Anders-Markvardsen** [comment]
unclear to me to what extent this is a requirement driving by a muon need
