### ISSUE TITLE
ConvertUnits: TOF->Wavelength should truncate at lambda > 0

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#17195]
The following script demonstrates an issue with ConvertUnits (turning on data archive searching at ISIS will find the data):

``` python
ws1 = Load(Filename='MAR21335.raw', OutputWorkspace='MAR21335')
ws1 = ConvertUnits(ws1, Target='Wavelength', EMode='Direct', EFixed=60)
```

The final `ws1` workspace contains negative wavelength values which are unphysical and correspond to neutrons with TOF before those that have the correct Ei would have arrived at the sample.

The data should be truncated to lambda > 0.

**Comment by AndreiSavici** [comment]
There are many places where Convert Units will give unphysical results. Very common occurrence happens in conversion to energy transfer. One takes care of that by either cropping the output or rebinning.
