### ISSUE TITLE
Engg:: Implement unit tests for Save/Load DiffFittingAscii

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17206]
Now `SaveDiffFittingAscii` has been implemented we should look at implementing unit tests in the future. However we need the ability to load the output files too and the output format may be subject to change so implement unit tests for both once we finish finalising the details

Depends on:
- [ ]  #15907

**Comment by josephframsay** [comment]
No-one uses SaveDiffFittingAscii, and it is deprecated, so there's now not a lot of point putting unit tests on it
