### ISSUE TITLE
Engg:: Masking needs to happen at TOF not dSpacing

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17270]
The `ENGIN-X` instrument scientists have reported that currently there are gaps in the data at approx multiples of 10,000 TOF this could be because masking is being applied in TOF and not dSpacing probably in masking. Reorder the masking so that it happens during the first TOF before dSpacing conversion 

This can be seen on run: 251421

**Comment by DavidFair** [comment]
Whilst I can replicate these drops in 3.7.2 it appears to be fixed in the latest nightly build. 

- [ ] Verify that it is fixed in the latest builds with the scientists before closing

**Comment by FedeMPouzols** [comment]
I think this was fixed here: #16896. If so, this could be marked as "Review required" to close it.

**Comment by DavidFair** [comment]
As mentioned I think this has been fixed in #16896 so I'll close this issue as a duplicate
