### ISSUE TITLE
Assert failure in Indirect Corrections interface

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17326]
I noticed this while testing https://github.com/mantidproject/mantid/pull/17213.
### Expected behavior

Nothing should happen.
### Actual behavior

Assert failure.
### Steps to reproduce the behavior

See https://github.com/mantidproject/mantid/pull/17213 to find relevant files. Open Indirect -> Indirect Corrections -> Container Subtraction tab and load the files. Hit Run, some workspaces will be created in the ADS. If you delete those workspaces you'll get an assert failure.
### Platforms affected

Windows, debug mode.

**Comment by robertapplin** [comment]
This is no longer an issue.
