### ISSUE TITLE
Should SingletonHolder<T>::Instance()  use double-checked locking?

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#17364]
### Expected behavior

singleton can be called from multiple threads

### Actual behavior

I noticed that [SingletonHolder<T>::Instance()](https://github.com/mantidproject/mantid/blob/adabe9c92d3b45d8125c7d1bb5514552dd1e68b5/Framework/Kernel/inc/MantidKernel/SingletonHolder.h#L79) just has a single check on `pinstance`. Since it is called concurrently from multiple threads, should this be replaced with  [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking), `std::call_once`, or a static initializer?

### Platforms affected

All

**Comment by quantumsteve** [comment]
@martyngigg @peterfpeterson

**Comment by martyngigg** [comment]
There certainly should be some locking - I assumed there was.

`std::call_once` would seem a nice fit here - it does what we need and has a good name for this circumstance.

**Comment by peterfpeterson** [comment]
I'm not the right person to comment on this.
