### ISSUE TITLE
Memory not released when deleting workspace open in spectrum viewer

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17384]
### Expected behavior
When a workspace is open in the spectrum viewer and is deleted in Mantid the memory should be released.
### Actual behavior
The window for the spectrum viewer is closed and the workspace is removed from the ADS however the memory is not released.
### Steps to reproduce the behavior
Open a large workspace so the additional memory usage is visible for example under system test data:
`PG3_2538_event.nxs` (or rebin a workspace with an extremely small bin width).

Open the spectrum viewer for that workspace
Without closing the spectrum viewer delete the workspace
Observe that the memory is not released but the workspace is deleted. 

### Platforms affected
Windows - Probably All

**Comment by mantid-roman** [comment]
The simplest solution is to set to `true` the `Qt::WA_DeleteOnClose` attribute of the viewer window in `MantidUI::showSpectrumViewer()` method (line 803 of MantidUI.cpp).

**Comment by DavidFair** [comment]
This resolves the issue - thanks for the help. I'll open a PR with the changes
