### ISSUE TITLE
Refactor CompareSampleLogs

### ISSUE THREAD

**Issue by mganeva** [mantidproject/mantid#17405]
### Expected behavior
Experience shows, that sometimes numeric sample logs are represented as strings. However, users expect them to be compared as numbers (with certain tolerance).

The aim of the refactoring is to implement the behaviour expected by users, e.g. compare temperatures as numbers, even if they have type 'String'.

### Platforms affected
All

Please, assign me.

**Comment by FedeMPouzols** [comment]
@mganeva: unfortunately I think there's no support for assigning GitHub issues to "external" developers (not in the repository list). It seems that you'll be able to assign yourself only in your own fork.

**Comment by mganeva** [comment]
@FedeMPouzols: no problem. I just wanted to communicate, that I am working on it right now and there is no need to assign someone else to this issue. I hope, it is okay.

**Comment by soininen** [comment]
What about adding the 'State: In Progress' label?

**Comment by mganeva** [comment]
@soininen: I've submitted the pull request already and I am waiting for review. I think, that the label 'In Progress' is for that pull requests which should not be reviewed yet.
