### ISSUE TITLE
RRO workflow diagrams update

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#17418]
Due to #17162 making significant alterations to the ReflectometryReductionOne algorithm, the workflow diagrams for the algorithm should be similarly updated to reflect the new changes. As the changes were concentrated in the "Convert To Wavelength" stage, it is likely only that diagram needs to be changed.

Edit: CreateTransmissionWorkspace workflow diagrams will be updated as well.

**Comment by raquelalvarezbanos** [comment]
@PranavBahuguna Please update the release notes too with those changes.

**Comment by raquelalvarezbanos** [comment]
Another algorithm that will need to be updated is `CreateTransmissionWorkspace`.
