### ISSUE TITLE
Add functions for saving/loading a calibration table to Tube calibration

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#17410]
Tube calibration produces a workspace of peaks and a calibration table workspace. In ```tube.py``` we have already have functions ```readPeakFile``` and ```savePeakFile```. We should create the corresponding definitions for the calibration table.

This is a sub issue of #12678.

**Comment by samueljackson92** [comment]
This calibration module could use a set of unit tests. I've created #17411 to deal with that as a separate maintenance task.

**Comment by raquelalvarezbanos** [comment]
This was fixed in PR https://github.com/mantidproject/mantid/pull/17414
