### ISSUE TITLE
Improve tests for reflectometry algorithms

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17430]
See https://github.com/mantidproject/mantid/issues/17429

This issue is to improve unit tests for `ReflectometryReductionOne` and `CreateTransmissionWorkspace`.
- All the input properties should be covered by unit tests. This involves testing both `PointDetector` mode and `MultiDetector` mode. We can create our own workspaces, I don't think we need to use real data.
- Checks on workspace values should use real measures such as counts and bin edges rather than x and y. We should also derive values rather than hard-code them where possible. See the comments on PR #24693 for examples
- We should also improve system tests. In particular I would like to have a test that includes direct beam normalization, and monitor background subtraction. It is important to include multi period datasets in our system tests (see [here](https://github.com/mantidproject/mantid/pull/17658) where I accidentally broke one of the tests, the problem wouldn't have been picked if we were testing single period datasets).

**Comment by PranavBahuguna** [comment]
@raquelalvarezbanos I have been attempting to write tests for `CreateTransmissionWorkspaceTest::test_detector_position_correction_multi_detector()`. I found that while the first detector's position had changed, the other 3 detectors did not. After analysing `SpecularReflectionPositionCorrect`, I believe that algorithm completely lacks any code whatsoever for dealing with multiple detectors, and thus this seems to be quite a serious issue.

**Comment by raquelalvarezbanos** [comment]
@PranavBahuguna is there a PR for this?

**Comment by PranavBahuguna** [comment]
@raquelalvarezbanos Apparently not, should I create one?

**Comment by raquelalvarezbanos** [comment]
If it is ready for testing, yes please, create one.

**Comment by raquelalvarezbanos** [comment]
@PranavBahuguna Did you create a PR for this?

**Comment by gemmaguest** [comment]
We should check whether this is still relevant / useful

**Comment by gemmaguest** [comment]
Closing as stale because we are unlikely to get around to this
