### ISSUE TITLE
`NormalizeByIntegratedMonitors` in `ReflectometryReductionOne`

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#17449]
In `ReflectometryReductionOne`, the way in which we deal with no monitors is by creating a workspace and filling it with `1`s. This workspace is eventually used to divide detectors/monitors. However, before this division is performed, if `NormalizeByIntegratedMonitors` has not been set to `False` (it is `True` by default) we'll integrate the monitor workspace which will cause a division by a constant `!=1`, even if we didn't provide a montior index (i.e. we didn't intend to use monitors). I think this is a bug introduced when monitors were made optional.

The current workflow diagram is incorrect and does not show this problem. The arrow that goes from `Monitors? No` should end up in `RebinToWorkspace` rather than `Division(Detectors/Monitors/Unity)`.

**Comment by PranavBahuguna** [comment]
I do not think this is an issue anymore, closing.
