### ISSUE TITLE
LoadNexusProcessed failing if Y Axis is TextAxis and is an empty string

### ISSUE THREAD

**Issue by DimitarTasev** [mantidproject/mantid#17479]
### Expected behavior

The `VanCurvesWorkspace` is properly loaded into Mantid after selecting it through Load.
### Actual behavior

Nothing is loaded and the following error is produced in the Log:

```
Error in execution of algorithm LoadNexusProcessed:
Attempt to load from an empty dataset /mantid_workspace_1/workspace/axis2
Error in execution of algorithm Load:
Attempt to load from an empty dataset /mantid_workspace_1/workspace/axis2
```
### Steps to reproduce the behavior

Vanadium Workspace: ENGINX00246043.nxs
Input Workspace: ENGINX00249918.nxs

Run `EnggVanadiumCorrections` and save out the curves workspace then view Axis 2 in HDF view - it will be textType and contain no data within.
### Platforms affected

All

**Comment by DavidFair** [comment]
It looks like the issue is axis2 is not being saved out by `NexusFileIO` - specifically `sAxis` is a text type so has no units and at the check `  if (!sAxis->isText())` trys to access the data via `sAxis->label(i)` which holds nothing hence nothing is saved out.

**Comment by DavidFair** [comment]
I've talked to @DimitarTasev and he is happy to look into this in the mean time.
