### ISSUE TITLE
Clean up FABADA minimizer code

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#17509]
Improve to code of FABADA minimizer to ensure it of acceptable quality, conforms to coding standards and is well structured with small focused classes/methods/functions.

Work on this is best done after all urgent issues arising out of beta testing have be resolved.

**Comment by martyngigg** [comment]
Please make sure this includes things such as naming methods and variables in `camelCase` style for consistency with the rest of the code.

Also, in `FabadaMinimizer.cpp` there are several constants defined, such as `convergenceMaxIterations`. These should be capitalised with underscores: `CONVERGENGE_MAX_ITERATIONS` to distinguish them from local variable names.

**Comment by raquelalvarezbanos** [comment]
I'll take care of this issue. I noticed the style was not following standards, but given the proximity of the code freeze I needed to create a PR. I will fix all the issues with style during the maintenance period.

**Comment by KarlPalmen** [comment]
Thank you.

**Comment by raquelalvarezbanos** [comment]
Maintenance task. There's an open PR pending testing. I've been in contact with Bartoumeu and should be testing this soon. Therefore marking against release 3.9.
