### ISSUE TITLE
mantid-developer rpm doesn't work on RHEL6

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#17512]
`mantid-developer` requires `ninja-build` and `python-matplotlib-qt4` packages which don't exist on RHEL6

**Comment by stuartcampbell** [comment]
Aren't we dropping RHEL6 ?

**Comment by martyngigg** [comment]
Can we close this? As RHEL6 is not a priority now then I'm not sure if it's worth keeping the effort up for this to still work. If it's slightly more cumbersome to setup the build environment then so be it.
