### ISSUE TITLE
Engg:: Fix undefined behaviour in EnggDiffCalibSettings

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17528]
http://builds.mantidproject.org/view/Static%20Analysis/job/undefined_behavior_sanitizer/94/warnings24Result/package.-1316443316/source.-5768643920553774561/#24

It appears we aren't setting the value of the bool in the struct construction. We need to find where this struct is used and check all its member variables are initialized correctly

**Comment by FedeMPouzols** [comment]
It really looks like here: https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionViewQtGUI.cpp#L387-L388 they should assign `m_rebinCalibrate` and not `m_forceRecalcOverwrite`.
