### ISSUE TITLE
New WorkflowAlgorithm IndirectILLFixedWindowScans for IN16B

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#17559]
### Expected behavior

The aim is to implement a workflow algorithm for fixed window scans of the ILL IN16B instrument. Currently, only the workflow algorithm for quasi elastic scans QENS (https://github.com/mantidproject/mantid/issues/16753) is implemented. Inelastic and elastic fixed-window scans have Nexus file entries, where the velocity is 1 and energy is 0 (inelastic) or unequal zero (elastic).

Previous work is done by Spencer Howells for ILLElasticScans.

Make use of https://github.com/mantidproject/documents/blob/master/Project-Management/ILL/WorkspaceAlgorithmRunner.md and SelectNexusFilesByMetadata (https://github.com/mantidproject/mantid/pull/17361)
### Platforms affected

All

**Comment by SpencerHowells** [comment]
I've already done some algos
[IndirectILLElasticScan.zip](https://github.com/mantidproject/mantid/files/484824/IndirectILLElasticScan.zip)

**Comment by reimundILL** [comment]
Proceed work on branch https://github.com/mantidproject/mantid/tree/16753_newIndirectILLReduction
