### ISSUE TITLE
Fix "ISO C++ forbids converting a string constant to 'char *'" warnings

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#17564]
These warnings pop up when compiling with gcc 5.4.0 in a few calls to the `NXgetattr()` function.

**Comment by quantumsteve** [comment]
@soininen I [fixed these issues upstream](https://github.com/nexusformat/code/pull/430) and they should go away with NeXus v4.4.3.

**Comment by soininen** [comment]
@quantumsteve Very good! I'll close this issue then.
