### ISSUE TITLE
Multi-dataset fitting: points from unscripted testing

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17567]
_From unscripted testing with Mantid 3.7.20160921.821, #16179_
1. Consider making _CreateOutput_ mandatory for sequential fits. If you turn it off, the output is not plotted and it is not clear that selecting the option is what you need to do to fix this. 
2. Seems to call the function over the whole range of the data - `StretchExp` gave warnings for negative X even when the fitting range was all positive X.

**Comment by AnthonyLim23** [comment]
@NickDraper should this issue be closed?

**Comment by NickDraper** [comment]
Yes
