### ISSUE TITLE
Cancelling LoadEventNexus algorithm leaks memory

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#17565]
### Expected behavior
On cancelling a load any space reserved should be released
### Actual behavior
Loading a large file and cancelling it mid load will cause that memory to not be released
### Steps to reproduce the behavior
Open a large file such as `ENGINX00250165` and cancel the load algorithm mid load. The memory will not be released
### Platforms affected
All

**Comment by DimitarTasev** [comment]
@DavidFair I removed the milestone, not sure how high priority this is, but the change is small
