### ISSUE TITLE
QtiPlot fitting bugs

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17562]
_Found during unscripted testing on Mantid 3.7.20160921.821_

Bugs seen in QtiPlot fitting:
1. In the last step (_Custom Output_), generate a parameters table. The X column ("Parameters") does not have the parameter names. The value and error columns are ok.
   ![params](https://cloud.githubusercontent.com/assets/15363125/18712901/6021c106-8008-11e6-93a8-7f5a4e432a4a.PNG)
2. Fit with a user-defined function. I always get the error ``Invalid function-, variable- or constant name: "".` 
   After this error appeared, the Fit Wizard could not be closed and I had to close Mantid. ![invalidfn](https://cloud.githubusercontent.com/assets/15363125/18713039/d778feae-8008-11e6-9c61-cdbf1e47ed82.PNG)

Marking as low priority because we have Mantid's fitting framework to do this. I don't know how many people use QtiPlot fitting.

**Comment by NickDraper** [comment]
Qtiplot fitting is deprecated, these issues will not be done
