### ISSUE TITLE
Reducing GCC Compiler Warnings

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#17593]
Work on reducing GCC compiler warnings from [Maintenance](https://github.com/mantidproject/documents/blob/master/Project-Management/TechnicalSteeringCommittee/reports/MaintenanceTasks.md) document:
- Fix GCC 6 compiler warnings

**Comment by martyngigg** [comment]
@DimitarTasev The maintenance document has you assigned to this. Did you plan in looking at it for `3.10`? If so could you update the milestone, please?
