### ISSUE TITLE
fit function to model QENS data with Teixeira water

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#17597]
A fitfunction to model the Q-dependence of the FWHM from a lorentzian fit is already implemented in fit function TeixeiraWater. This fit function is the Lorentzian with its FWHM given by the Teixeira model, in order to directly fit QENS data.

**Comment by SpencerHowells** [comment]
I have a Bayes version of this, but it's in Fortran and I'm having problems getting it to work! This would be a big improvement and we could also use the Fabada Bayes fitting package.

**Comment by SpencerHowells** [comment]
Can this read the Q values from the workspace to do a sequential fit?

**Comment by jmborr** [comment]
@SpencerHowells You mean something like the `WorkspaceIndex` property that was included in [InelasticDiffSphere](https://github.com/mantidproject/mantid/blob/master/Framework/CurveFitting/src/Functions/InelasticDiffSphere.cpp) ?

**Comment by SpencerHowells** [comment]
Yes I think so - it's what Dan did.

**Comment by jmborr** [comment]
@SpencerHowells I've sent a question regarding this to Slack because I don't understand why there should exists an attribute named `WorkspaceIndex` without a corresponding attribute `WorkspaceName`.

**Comment by SpencerHowells** [comment]
For sequential fit we use the algo PlotPeakByLogValue which has a property PassWSIndexToFunction

**Comment by jmborr** [comment]
@SpencerHowells  Ah, that is the answer I was looking for. Thanks a lot.
