### ISSUE TITLE
Update the concepts page on FittingMinimizers with more minimizers and datasets

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#17594]
This concerns several additions to the [minimizers page](http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html
) that should be included in the upcoming release 3.8:
- Include the "Trust region" minimizer (the one currently called DTRS) as a new alternative (one new column in the tables).
- In addition to the traditional NIST benchmarks/tables included in release 3.7, include comparison tables for neutron datasets (and less important, some CUTEst problems).

The tables are generated with the scripts being added in #15952.

**Comment by NickDraper** [comment]
has been merged-  closing
