### ISSUE TITLE
Modernize more code to use c++11

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#17600]
Modernize more code to use c++11. Specifically functions now found in `<string>`. `atoi` should move to `std::stoi`, `atof` should move to `std::stod`

**Comment by martyngigg** [comment]
@lottiegreenwood Were you planning on picking this back up for the `3.10` maintenance?

**Comment by lottiegreenwood** [comment]
Yes, I should finish it off then

**Comment by martyngigg** [comment]
Excellent, thanks. I'll update the maintenance document
