### ISSUE TITLE
Simultaneous instrument download & version checking fails on startup

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#17611]
### Expected behavior

When `CheckMantidVersion` & `DownloadInstrument` are enabled then they should both complete successfully on startup.

### Actual behavior
This is a snippet from the results log when set to debug on startup with `CheckMantidVersion=1` & `DownloadInstrument=1` in the properties file:

```
DownloadFile : https://api.github.com/repos/mantidproject/mantid/contents/instrument to file: /home/dmn58364/.mantid/instrument/github.json
Sending https GET request to: https://api.github.com/repos/mantidproject/mantid/releases/latest
Sending https GET request to: https://api.github.com/repos/mantidproject/mantid/contents/instrument
Unable to find proxy.host in the properties file
Internet Connection Failed - cannot update instrument definitions.
InternetError: Connection and request failed SSL Exception: Cannot create SSL_CTX object: error:140A90A1:lib(20):func(169):reason(161)
Answer from web: 304 Not Modified
Answer from web: 304 Not Modified
Current Mantid Version: 3.7.20160810.2155
Most Recent Mantid Version: No new versions since Wed, 10 Aug 2016
```

Occasionally the instrument download will succeed but then the version check will fail.

This can be seen with the current nightly build.

### Steps to reproduce the behavior

* Install nightly `mantid` on Linux or OS X
* Check that both instrument updating & version checking are not disabled in `~/.mantid/Mantid.user.properties`
* Start MantidPlot

### Platforms affected

Linux & OS X

**Comment by rosswhitfield** [comment]
Fixed in #17612
