### ISSUE TITLE
Missing detector IDs after EVentWorkspace resize support was removed

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#17634]
Just pasting the Slack log here for reference:

17:45 Pete Peterson This apparently doesn't keep the behavior the same. https://github.com/mantidproject/mantid/commit/84382740f9b812c4442158e62223609e543c7275 :disappointed:
17:46 ﻿⁠⁠⁠⁠m_eventBuffer->getDetectorIDToWorkspaceIndexMap(true)﻿⁠⁠⁠⁠ now returns an empty ﻿⁠⁠⁠⁠detid2index_map﻿⁠⁠⁠⁠
17:53 Pete Peterson The number of detector ids in the workspace isn't crazy, it is just missing the map
17:55 I need to get ﻿⁠⁠⁠⁠padSpectra﻿⁠⁠⁠⁠ back into things https://github.com/mantidproject/mantid/blob/v3.7.2/Framework/DataObjects/src/EventWorkspace.cpp#L575	
GitHub
mantidproject/mantid
mantid - Main repository for Mantid code
18:02 Pete Peterson I get it now. The initial workspace (created in ﻿⁠⁠⁠⁠SNSLiveEventDataListener::initWorkspacePart1﻿⁠⁠⁠⁠) has no concept of instrument. Then in ﻿⁠⁠⁠⁠SNSLiveEventDataListener::initWorkspacePart2() ﻿⁠⁠⁠⁠ there is no map to copy.
08:10 Simon Heybrock Hi Pete!
08:10
slackbot BOT psqrd is currently in Do Not Disturb mode and may not be alerted of this message right away. If it’s urgent, click here to send a notification now. Keep in mind, if the recipient has all notifications turned off, they will only get your message when they’re back online.
How does Do Not Disturb work? Learn more in this Help Center article: Do Not DisturbOnly visible to you
08:11 Simon Heybrock I think I know what the issue is: I had (wrongly) assumed that ﻿⁠⁠⁠⁠EventWorkspace﻿⁠⁠⁠⁠ behaves like ﻿⁠⁠⁠⁠Workspace2D﻿⁠⁠⁠⁠, i.e., sets default detector IDs on creation.
08:12 I actually have an open pull request that provides easier means of workspace creation that would help here, but I assume you need this as a fix for the release, so this is not an option.
08:14 I would suggest to just manually set the detector IDs for now.
08:15 That is, what you need is not what ﻿⁠⁠⁠⁠padSpectra﻿⁠⁠⁠⁠ does, but only the initialization of detector IDs, everything else (size of the workspace and spectrum numbers should be set up correctly).
08:18 You can either use a manual loop after the workspace has been created to call ﻿⁠⁠⁠⁠m_eventBuffer->getSpectrum(i)->setDetectorID(detids[i])﻿⁠⁠⁠⁠, or use ﻿⁠⁠⁠⁠MatrixWorkspace::rebuildSpectraMapping﻿⁠⁠⁠⁠. (edited)

**Comment by rosswhitfield** [comment]
Fixed in #17635
