### ISSUE TITLE
No data shown in scatter plot mode 

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#17640]
Currently nothing is shown when loading an event workspace and opening VSI. Swapping between views also does not work.

### Expected behavior
Data should be shown.

### Actual behavior
Data is not shown.

### Steps to reproduce the behavior
Observed using ```MDEvent_ellipPeaks_new``` which @AntonPiccardoSelg has a copy of.

### Platforms affected
All.

**Comment by AntonPiccardoSelg** [comment]
This issue arises for any MDEvent Workspace. It is sufficient to switch the views in order to make the data invisible.

**Comment by martyngigg** [comment]
This was merged to the release branch.
