### ISSUE TITLE
3D polygon plot is centred in the window

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#1764]
This issue was originally [TRAC 916](http://trac.mantidproject.org/mantid/ticket/916)

I ran the SANS 2D analysis and plotted a 3D polygon plot. The graph looked fine and zooming works but initially the cube containing the data was not centred within the window, it was pushed over the right as if the lower left-hand corner was being placed at the centre of the window

**Comment by NickDraper** [comment]
This is too old to be useful
