### ISSUE TITLE
Crystal Field - intensity should be in mBarn/Sr rather than Barn.

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#17652]
ISIS data in absolute normalisation is given in mBarn/Sr/meV - so the integrated peak areas should be in mBarn/Sr. The crystal field module currently outputs its integrated intensity (cross-section) in Barn. This should be multiplied by 1000 and divided by `pi` to be in agreement with absolutely normalised data from ISIS instruments.

**Comment by NickDraper** [comment]
has been merged - closing
