### ISSUE TITLE
Fix performance regression in Qxy.

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#17670]
15:53 anton_piccardo-selg Hi Simon,
I am currently following up a user report that Qxy has degraded drastically in performance. The reduction time has degraded on my laptop by a factor of about 6 to 7. I traced the source of the performance bottleneck and it appears that the constructor of ﻿⁠⁠⁠⁠GravitySANSHelper﻿⁠⁠⁠⁠ is causing the issue.  The actual problem is in fact getting the ﻿⁠⁠⁠⁠SpectrumInfo﻿⁠⁠⁠⁠ here: https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/Qxy.cpp#L195:L196 .  I initially thought that adding ﻿⁠⁠⁠⁠ThreadedContextCheck::Skip﻿⁠⁠⁠⁠ might help, but it does not improve the situation. I have not looked into ﻿⁠⁠⁠⁠SpectrumInfo﻿⁠⁠⁠⁠ yet, I thought you are most likely to know what might be going on.
GitHub
mantidproject/mantid
mantid - Main repository for Mantid code
16:05 anton_piccardo-selg The actual time bottleneck is this here: https://github.com/mantidproject/mantid/blob/master/Framework/API/src/SpectrumInfo.cpp#L23:L24 . For every call to ﻿⁠⁠⁠⁠workspace->spectrumInfo()﻿⁠⁠⁠⁠ a new ﻿⁠⁠⁠⁠SpectrumInfo﻿⁠⁠⁠⁠ object is created and it essentially gets the detector IDs every time. Is there a way that ﻿⁠⁠⁠⁠SpectrumInfo﻿⁠⁠⁠⁠ operates less costly? Is there a reason to change GravitySANSHelper or was it just part of the general roll-out?
GitHub
mantidproject/mantid
mantid - Main repository for Mantid code
(edited)
16:13 Simon Heybrock Hi Anton.
16:15 It was just part of general rollout.
16:16 Creation of a new ﻿⁠⁠⁠⁠SpectrumInfo﻿⁠⁠⁠⁠ was a necessity since we had to wrap the current instrument. It was not intended to stay like this for good, but only until we have Instrument-2.0 (which may be a long time).
16:17 anton_piccardo-selg Ok
16:17 Simon Heybrock I am just having a look if this can be fixed in Qxy, or if we need to revert the rollout in this case.
16:20 Yes, I think I just screwed up there. The call to ﻿⁠⁠⁠⁠inputWS->spectrumInfo()﻿⁠⁠⁠⁠ should have been outside the loop. (edited)

**Comment by martyngigg** [comment]
Merged to release branch so automatic issue closure doesn't work.
