### ISSUE TITLE
Fix Mantid crash when closing many workspaces via MantidDock

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#17729]
Rob mentioned that closing about 200 workspaces at once via MantidDock causes a crash. 

**Solution**
Avoid deleting the workspaces via the `DeleteWorkspace` algorithm and clear them instead directly from the ADS.

**Comment by martyngigg** [comment]
Merged to release branch automatic closing does not work.

**Comment by martyngigg** [comment]
The fix has actually changed the behaviour of delete in MantidPlot and needs to be addressed differently.

**Comment by NickDraper** [comment]
Reimplemented using a simple but effective approach following further reports from Vesuvio and reflectometry instruments
