### ISSUE TITLE
HistogramData rollout: algorithms 82-86

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#17722]
HistogramData rollout: algorithms

This issue is part of the HistogramData rollout, see #17641.
Algorithms covered in this issue are:

```
Framework/CurveFitting/src/Algorithms/VesuvioCalculateMS.cpp
Framework/CurveFitting/src/FitMW.cpp
Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
Framework/CurveFitting/src/FunctionDomain1DSpectrumCreator.cpp
Framework/CurveFitting/src/Functions/BivariateNormal.cpp
```

**Comment by DanNixon** [comment]
No idea why this is still open, all the referenced commits are already in `master`.

**Comment by NickDraper** [comment]
all the referenced commits are already in `master`.
