### ISSUE TITLE
Add Workspace attribute to TeixeiraWaterSQE fit function

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#17730]
Same as in InelasticDiffSphere, for use with the indirect analysis interface.

**Note**: this is a temporary fix. The long-term solution is to inherit from a base-class  for fit functions that depend on `Q`. This base class would implement the setWorkspace method to retrieve the `Q` for each spectrum. This base class will implement Michael Wedel's interface `IFunction1DSpectrum` for fit functions operating on a domain of type `FunctionDomain1DSpectrum`.  when you pass the `FunctionDomain1DSpectrum` to calculate the function values, the fit function will know which value of `Q` to use thanks to the workspace index property of `FunctionDomain1DSpectrum`.

**Comment by jmborr** [comment]
@spencerhowells done

**Comment by SpencerHowells** [comment]
Looking forward to using it!

**Comment by jmborr** [comment]
Irrelevant once #18101 is closed. Then TeixeiraWaterSQE will inherit from FunctionQDepends
