### ISSUE TITLE
ISIS reduction: Custom filename should overwrite custom function for file name. 

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#17844]
When users deploy ISIS reduction script, they can provide custom function, which calculates file names to save reduction results from incident energy, instrument run number and other properties of interest to user or just custom file name to save these results. 

If both are provided, custom function currently overrides custom file name.  

I got custom request to change this behaviour to opposite e.g. custom file name overwrites custom function.

**Comment by AndreiSavici** [comment]
Branch merged into master a while ago, but the PR had no `Fixes ...`
