### ISSUE TITLE
Read Selected Information from Saved ParameterMap

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#17870]
Eventually we need to be able to move data from ParameterMap to SpectrumInfo/DetectorInfo and vice versa.

In terms of scanning instruments, we need to have positions and rotations stored in the DetectorInfo. We need a way to be able to read this information out of the ParameterMap (and resave it when required).

**Comment by SimonHeybrock** [comment]
After having looking at this more closely I am not sure we actually need to interact with the ParameterMap, since it does not seem to be saved directly. More details are described here: https://github.com/mantidproject/mantid/issues/18228.

**Comment by SimonHeybrock** [comment]
I think this is really covered by some of the other issues we have opened and partially already dealt with. I am closing this, please reopen if you think this is not the case.

**Comment by OwenArnold** [comment]
@SimonHeybrock. It makes to close this.
