### ISSUE TITLE
MantidUI Interface Breakdown

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#17894]
This comes from the work associated with #17315  where the WorkspaceDock was redesigned using the MVP pattern. An interface to MantidUI called MantidDisplayBase was created which contained all the methods required by the WorkspaceDock. It would be nice to split up the responsibilites using something similar to the mixin architecture.

**Comment by OwenArnold** [comment]
Examples suggestions might be things like `PlotableWorkspaceView`, `SaveableWorkspaceView`. We can talk about this at the time of implementation.

**Comment by martyngigg** [comment]
This all sounds very valuable in improving the general maintenance of the MantidPlot code.

There are currently early discussions around the future of MantidPlot itself. Ideas are floating around about writing a new python-based workbench that would becomes MantidPlot's successor but this is by no means certain.

I would therefore advise not putting too much effort into this type of refactoring work until these decisions are more concrete - it would be shame to waste the effort.

**Comment by OwenArnold** [comment]
@martyngigg Good point.

**Comment by martyngigg** [comment]
These ideas should still be transferable though, if a new application is the decided route .
