### ISSUE TITLE
PlotSurface and contour from group broken

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#17896]
### Actual behavior

After the dialog box you get this error
![image](https://cloud.githubusercontent.com/assets/1017173/19763237/1d9f5246-9c35-11e6-93e9-0d69d191a965.png)
### Steps to reproduce the behavior

Right click on a group with more than 2 members.
Click ok on the dialog box
### Platforms affected

All

**Comment by tom-perkins** [comment]
The error appears for histogram workspaces, but it works OK for point data workspaces.
