### ISSUE TITLE
Debug assertion when loading workspace with non-ASCII characters in sample logs

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#17927]
The data set LARMOR00013038 creates a Debug assertion. The message is:

![debug_assertion](https://cloud.githubusercontent.com/assets/8955784/19921951/41f57eca-a0d8-11e6-9164-714c5b735b2a.PNG)

The origin is the a non-ASCII character which is being queried [here](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadNexusLogs.cpp#L601).
The `iscntrl` function of ` std::replace_if(values.begin(), values.end(), iscntrl, ' ');`  gets a character `ch` as an input and ["is undefined if the value of `ch` is not representable as unsigned char and is not equal to EOF".](http://en.cppreference.com/w/cpp/string/byte/iscntrl)

### Steps to reproduce the behavior
Load the dataset LARMOR00013038 into a debug build on Windows.

### Platforms affected
Windows Debug. Did not see it on Ubuntu.

**Comment by BhuvanBezawada** [comment]
**Closing Issue**
This error no longer occurs.

**Extra Info**
Issue must have been fixed via fixing another issue in the past. `std::replace_if` sanitises any characters which are control characters or negative.
