### ISSUE TITLE
Unable to save project if an interface window is open

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#17932]
When attempting to save a mantid project when an interface is open the following error is produced:
![error](https://cloud.githubusercontent.com/assets/12883435/19924759/439465fe-a0e5-11e6-9be2-d8c02b3d3b05.png)
If `Continue` is clicked a project folder is created but mantid is unable to re-load the project.
If this cannot be resolved it would be helpful if the error message was clearer.
### Steps to reproduce the behaviour
Open an interface eg Indirect > Data Reduction run `26176` 
Leaving the interface open, File > Save Project As...

**Comment by gvardany** [comment]
The same has been reported from ILL users.
