### ISSUE TITLE
Generalise ConvertSpectrumAxis versions 1 + 2

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#17931]
### Expected behavior

`ConvertSpectrumAxis` shall work for a `MatrixWorkspace`.

### Actual behavior

When calling `ConvertSpectrumAxis` for a distribution, the `InputWorkspace` validator gives this message: `The workspace must contain histogram data`.

### Steps to reproduce the behavior

Run algorithm `CreateWorkspace` and set `Distribution` to `True`. Then run algorithm `ConvertSpectrumAxis`. A minimum example (take care, no instrument defined):
``` Python
# Create a test workspace with only one column
X = np.zeros(5)
Y = range(5)
E = np.ones(5)
CreateWorkspace(DataX=X, DataY=Y, DataE=E, NSpec=5, OutputWorkspace='test_1', Distribution=True)
# Convert the spectrum axis
ConvertSpectrumAxis(InputWorkspace='test_1', OutputWorkspace='out', Target='Theta')
```
Returns:
``` Python
ValueError: Invalid value for property InputWorkspace (MatrixWorkspace) "test_1": The workspace must contain histogram data
```

### Platforms affected

All

**Comment by martyngigg** [comment]
My commit `3fb3306` was erroneously attached to this issue and has now been corrected.
