### ISSUE TITLE
Double clicking in the workspace window causes Mantid to crash

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#17955]
### Expected behavior
Double clicking within the 'workspaces' window should not cause Mantid to crash

### Actual behavior
Double clicking within the 'workspaces' window, however, does cause Mantid to crash

In debug it states a debug assertation has failed, and a vector subscript is out of range.

### Steps to reproduce the behavior
Build master in debug and double click within the 'workspaces' window

### Platforms affected
Windows 7, occurs on the latest nightly release

**Comment by NickDraper** [comment]
Martyn can you have a look at this please

**Comment by martyngigg** [comment]
I have moved this back to v3.9 as this is a recently introduced bug in https://github.com/mantidproject/mantid/pull/17339 when refactoring the widget.
