### ISSUE TITLE
New algorithm ConcatenateWorkspaces

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#17977]
### Expected behavior

Some algorithms exist that combine workspaces 'vertically', for example `AppendSpectra` or `ConjoinWorkspaces` or `ConjoinSpectra`.

A way to append, combine or concatenate spectra 'horizontally' is to call a sequence of algorithms (`Transpose`, `CreateWorkspace`, `AppendSpectra`, `Transpose`).

I have seen now three places in Mantid, where a new algorithm `ConcatenateWorkspaces` can improve the readability of the code and makes code shorter in general.

For example, when treating elastic and inelastic fixed-window scans, several workspaces with only one column but many spectra need to be concatenated. Or, if we plan to call `ExtractSpectra` (takes `XMin` and `XMax`) twice to split one workspace, and do something with the data independently, there might be the need to put these spectra back together. 

### Platforms affected

All

**Comment by gvardany** [comment]
This is replaced by issue #19721 .
