### ISSUE TITLE
Add documentation and rename Damping minimizer

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18003]
This issue is to rename Damping minimizer to Damped Gauss-Newton and add an .rst file for it.

- As a first step, ask Roman if he sees any reason why Damping should not be renamed to "Damped Gauss-Newton".
- If he agrees with the new name:
  - We need to update: http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html
  - Check with Roman that the link to Gauss-Newton algorithm in the above .html file is correct.
  - We need to manually update the name in the function browser.

**Comment by KarlPalmen** [comment]
Issue #15014 will provide a stub document for this. I had difficulty finding the code for this, because it did not have GaussNewton in the name and I had to ask @mantid-roman to identify it.

**Comment by KarlPalmen** [comment]
Document is now found at http://docs.mantidproject.org/nightly/fitminimizers/GaussNewton.html arising from the merger of #15014 .
