### ISSUE TITLE
Add documentation for Levenberg-MarquardtMD

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18002]
This issue is to add an .rst file for Levenberg-MarquardtMD minimizer.

The first step is to speak to Roman to see if he can provide any link we can use as a starting point to document the minimizer and its implementation in Mantid.

**Comment by KarlPalmen** [comment]
Issue #15014 will provide such an rst file. This issue is to add details of its implementation in Mantid.

**Comment by KarlPalmen** [comment]
Oops! I didn't see the MD in the issue title! Issue #15014 has only added the non-MD Levenberg-Marquardt minimizer.
