### ISSUE TITLE
Add documentation for Trust region minimizer

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18004]
This issue is to add an .rst file for the Trust region minimizer.

- Before doing any work on this, ask Anders about this issue.

**Comment by Anders-Markvardsen** [comment]
Tyrone from SCD Numerical Group suggests we describe the trust region minimizer as:

This minimizer is a hybrid Gauss-Newton_ /Quasi-Newton_ method, solved within a trust-region_.  

It is a re-implementation of (a subset of the functionality of) the RALFit_ nonlinear least-squares solver.

.. _Gauss-Newton https://en.wikipedia.org/wiki/Gauss%E2%80%93Newton_algorithm
.. _Quasi-Newton https://en.wikipedia.org/wiki/Quasi-Newton_method
.. _trust-region https://en.wikipedia.org/wiki/Trust_region
.. _RALFit https://github.com/ralna/RALFit

**Comment by KarlPalmen** [comment]
Thank you for the information.
