### ISSUE TITLE
SANSWideAngleCorrection does not work for all scenarios

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18042]
Regarding SANSWideAngleCorreciton, Anna wrote:

>We found out that this algorithm does not work for Empty beam scattering reduction, which we are doing all the time.
Log made denominator 0, so we have to turn the correction off from time to time.
Otherwise we are applying it all the time.

**Comment by AntonPiccardoSelg** [comment]
This needs further clarification with Anna from ANSTO

**Comment by smk78** [comment]
ISIS SANS do not understand Anna's comment but have not investigated further.

**Comment by DavidFair** [comment]
I'm going to close this as stale then since this hasn't made progress since 2017
If this is something Anna/anyone else is still seeing feel free to re-open
