### ISSUE TITLE
Sign of fit height parameter depends on order of x values.

### ISSUE THREAD

**Issue by granrothge** [mantidproject/mantid#18051]
### Expected behavior
         The height parameter in a fit to a Gaussian should have the sign the same as the data. 
### Actual behavior
        By default, fitting a Gaussian to data with x in decreasing order will yield a negative height
### Steps to reproduce the behavior
If you run the following script, you will see that the Height will be negative in the second case and positive in the first case.  Also If you turn off normalization in the plots this goes away.  The suspicion is that it is normalizing by the right bin minus the left bin rather than the absolute value of the difference.

x=np.arange(-10,10,0.5)
xc=(x[1:]+x[:-1])/2.
y=np.exp(-(xc**2)/20.)+1
err=np.sqrt(y)
w=CreateWorkspace(x,y,err)
y=100*y
err=np.sqrt(y)
w=CreateWorkspace(x,y,err)
w2=CreateWorkspace(-x,y,err)
Fit(Function='name=LinearBackground,A0=-200,A1=1.75578e-12;name=Gaussian,Height=-200,PeakCentre=2.31197e-13,Sigma=3.16228', InputWorkspace='w2', Output='w2', OutputCompositeMembers=True)
Fit(Function='name=LinearBackground,A0=200,A1=-2.02278e-15;name=Gaussian,Height=200,PeakCentre=-1.15625e-16,Sigma=3.16228', InputWorkspace='w', Output='w', OutputCompositeMembers=True)

### Platforms affected

Should be all. Only checked RHEL7

**Comment by AndreiSavici** [comment]
The problem occurs when one uses the fitting GUI interface and the plotting option is to use distribution (divide by bin width)
