### ISSUE TITLE
MuonAnalysis results table: sample log averaging is wrong

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#18061]
#### Expected behaviour
When creating a results table in MuonAnalysis, if a time series log is selected for one column, the values in that column should be the time average over the run. (This average should automatically deal with pauses, aborted/restarted periods, etc). 

This averaging can readily be implemented using the methods already in `TimeSeriesProperty`.

#### Actual behaviour
The average does not use the methods on `TimeSeriesProperty`, but reimplements its own averaging. It will only be correct if the log values are evenly spaced in time, which is often not the case. It does not deal with pauses or aborted/restarted runs.

#### Steps to reproduce the behaviour
See [here](https://github.com/mantidproject/mantid/blob/ef0e24d7fa83bf33b566a31b7c2d3fb7eff0faf7/MantidQt/CustomInterfaces/src/Muon/MuonAnalysisResultTableTab.cpp#L494-L510) for how the averaging is done at the moment.

Problem was reported with HIFI runs 108370-108380 and log value `SEPTUM_A_CURR`.

(N.B. Need to wait for #17905 to be merged, as this fixes the methods on `TimeSeriesProperty` to deal correctly with filtering. It might be useful to use `LogFilterGenerator` from #17925.)

#### Reported by
James Lord, Mantid 3.8, Windows

**Comment by NickDraper** [comment]
The code that needs changing is C:\Mantid\Code\MantidQt\CustomInterfaces\src\Muon\MuonAnalysisResultTableTab.cpp lines 512-530 and a bit more neatening up.

you should then be able to use code like this
``` python
stats = log.getStatistics()
time_ave = log.timeAverageValue()
```

You will need to check this actually works though!
