### ISSUE TITLE
SplineInterpolation :: do linear interpolation when only two points are given

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#18097]
`SplineInterpolation` rightly throws an error when trying to interpolate 2 points with cubic spline. Generalisation would be relevant to do linear interpolation for the case of 2 points with a warning message instead of error.

**Comment by reimundILL** [comment]
GSL can return the number of points required by the interpolation. That would be nice for validating the input of the algorithm (   unsigned int gsl_interp_type_min_size (const gsl_interp_type * T), unsigned int gsl_interp_min_size (const gsl_interp * interp)   )

**Comment by reimundILL** [comment]
LinearBackground::functionDeriv1D seems never been used and looks incorrect. However, it was there and I think this method is good for completeness of the code.
