### ISSUE TITLE
Harmonize advanced plotting options

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#18159]
### Current behavior

We have a few plotting options that are "advanced"
 1. waterfall plots - option on plot spectrum dialog
 2. tiled plots - option on plot spectrum dialog
 3. Plot Surface from group - option on workspace group context menu if 3 or more members 
 4. Plot Contour from group - option on workspace group context menu if 3 or more members
![image](https://cloud.githubusercontent.com/assets/1017173/20796466/1ddaffda-b7ce-11e6-9090-25c60d14f645.png)

As you can see the approaches are a bit varied as to how you get to them (and the last two can be hard to find),but there is a lot of similarity in the dialog box they create.
![image](https://cloud.githubusercontent.com/assets/1017173/20796502/514e5790-b7ce-11e6-94b9-48cf290335d0.png)

![image](https://cloud.githubusercontent.com/assets/1017173/20796489/46d48d7a-b7ce-11e6-9360-b07d8e956132.png)

### Actual behavior
We want to harmonize all of this without disrupting the well known and used plot Spectrum (+- errors) usage.

We want to replace the context menu options with 
 1. Plot Spectrum ...
 1. Plot Spectrum with errors ...
 1. Plot Special ...
 1. Color Fill plot (leave as before)

The two plot spectrum options had special behaviour if the workspace contained only one spectrum in that it would not show the dialog box and just plot immediately.  We want to retain that.

We want to harmonize the dialog box that the other options use, and plot special should be able to be used for waterfall and tiled plots as well as the surfaces and contours, and there is no reason it cannot also be used for normal plots.  Here is a suggested mockup.

![mockup](https://cloud.githubusercontent.com/assets/1017173/20797039/134bcc36-b7d1-11e6-8be1-0afea1f4622b.png)

The same dialog could be used for Plot Spectrum, just with the group box hidden and the form shrunk appropriately.

You might want to have a second level of context menus under plot special, they should just fill the plot type out in the dialog box for you.

All of the underlying plotting for this should already be in place. The only new aspect is allowing waterfall plots to be labelled using a log value or custom labels.  The default label approach or [workspace]-sp[wpectrum no] should be maintained as an option.

### Platforms affected
All

**Comment by KarlPalmen** [comment]
I'd appreciate an example file to load that produces `Plot ... from Group` in the right click menu. The MUSR files I tried, which have a group of 2 don't produce this is the right click menu.

**Comment by KarlPalmen** [comment]
I find I can produce such a workspace by running the GroupWorkspace algorithm.

**Comment by raquelalvarezbanos** [comment]
Hi @KarlPalmen, for real datasets try with `POLREF00003014`, it's a POLREF run with 32 periods which can be found in `\ExternalData\Testing\Data\SystemTest\`

**Comment by KarlPalmen** [comment]
Think you @raquelalvarezbanos .

**Comment by KarlPalmen** [comment]
Through further efforts, I have found that the disharmony between the two dialog boxes that need to be merged runs deep into the code and so will be postponing this issue into the following release.

**Comment by NickDraper** [comment]
This script might be helpful to create temperature range data to test the Plotting against a workspace against a temperature range
``` python
base = CreateSampleWorkspace(Function='Powder Diffraction', NumBanks=1, BankPixelWidth=1)

wsNames = []
for t in range (10,110,10):
    wsName = "temp" + str(t)
    wsNames.append(wsName)
    MultiplyRange(base,75,99,t/100.0,OutputWorkspace=wsName)
    AddSampleLog(wsName,"Temp",str(t),"Number","Kelvin")
TestGroup = GroupWorkspaces(wsNames)
```
