### ISSUE TITLE
Update fit benchmarking tables before release

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#18151]
Updating the tables in http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html, http://docs.mantidproject.org/nightly/concepts/FittingMinimizersComparisonDetailed.html#minimizers-unweighted-comparison-in-terms-of-accuracy-cutest and http://docs.mantidproject.org/nightly/concepts/FittingMinimizersComparisonDetailed.html#minimizers-unweighted-comparison-in-terms-of-accuracy-cutest and http://docs.mantidproject.org/nightly/concepts/FittingMinimizersWeightedComparisonDetailed.html#minimizers-weighted-comparison-in-terms-of-run-time before release

* To include any new fitting test problems added and tested with the systemtest FittingBenchmarks
* Now we have tests against real neutron data problems - reorganised the concept page such tests with weights are at the forefront, the one users care most about, and non-weight test results can become a curiosity in the background
* Have a link to tables created for previous releases. This is so that an user of older release can see what minimizers worked best for that release
* Please pay special attention to the neutron_data WISH problem, which with #17654 still are given noticeable different results from those of the 3.8 results
* Optionally, add text to NaN cases - with output from minimizer saying why it did not work

**Comment by Anders-Markvardsen** [comment]
No further fit examples added to 3.9 hence move to 3.10

**Comment by AnthonyLim23** [comment]
We do have two comparisons: http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html and http://docs.mantidproject.org/nightly/concepts/FittingMinimizersWeightedComparisonDetailed.html which were last updated for v3.8.0. I wonder if anybody knows where Fede's script for generating them went. I didn't find them in mantid's repo. merge into one page

**Comment by Anders-Markvardsen** [comment]
The steps are to run:

1. https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/FittingBenchmarks.py but edited to run all the benchmarking tests

2. Manually copy and paste the new results tables into folder for that release

3. Manually update, 3 files I think it is, with the new release number

4. This is deliberately not automated because when updating the tables you may also need to update the top of http://docs.mantidproject.org/nightly/concepts/FittingMinimizers.html to say which minimizer is recommended are now recommended with the a given release - only if different of course. If not different this is not needed.

Writing this thinking... When we do change the recommended minimizer we should state from which release this applies

**Comment by Anders-Markvardsen** [comment]
This issue was moved to mantidproject/fitbenchmarking#6
