### ISSUE TITLE
Expose WorkspaceGroup constructor  in Python

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18161]
Currently there is no way to create a `WorkspaceGroup` in Python without using `GroupWorkspaces` which places my workspace into the ADS. Once the workspace is on the ADS, it is there essentially forever. This is not desirable. We need a way to create a `WorkspaceGroup` without going through the ADS.

**Comment by TWJubb** [comment]
Closed as a more recent duplicate of this issue exists (#23448)
