### ISSUE TITLE
Provide visual display of fit benchmarking results 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#18173]
Extend the fit benchmarking scripts introduced with #17654 to generate visual display of data from the benchmarking tables. 

Initially suggest limiting this to 1D fit problems and neutron_data fitting problems. Have an .rst file automatic created, where for each 1D fit problem a section is created with contains

* Title of fit problem 
* a plot of the data
* (a plot of the initial starting guess)
* a plot of the solution found
* Python lines of code representing the fit problem before the fit started, and for someone to copy and paste for rerunning

Add link for each fit problem to the problem name.

**Comment by Anders-Markvardsen** [comment]
Could the plotting be done entirely with matplotlib?

**Comment by AnthonyLim23** [comment]
I will have a look into it, but I suspect that the answer is yes. The only thing I am not sure on is adding links. 

I can make a simple plot and data classes which we can use to plot. Are all of the problems 2D (x,y and error)?

**Comment by Anders-Markvardsen** [comment]
Yes all plot simple x, y and error

**Comment by AnthonyLim23** [comment]
What is the best way to run the code?

**Comment by AnthonyLim23** [comment]
a way to add links to individual data points. It does need to be a svg file to work

```
import numpy as np
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

f = plt.figure()
s = plt.scatter([1, 2, 3], [4, 5, 6])
s.set_urls(['http://www.bbc.co.uk/news', 'http://www.google.com', None])
f.canvas.print_figure('scatter.svg')
```

**Comment by Anders-Markvardsen** [comment]
I have attached script+fit problem data with code+data copied and pasted from systemtest FittingBenchmarks.py and which you use to run fit benchmarking separately

[FitMinimizerTesting.zip](https://github.com/mantidproject/mantid/files/1155618/FitMinimizerTesting.zip)

the script to run is runScripts.py

**Comment by AnthonyLim23** [comment]
If you run the following code, then you will get a nice bar plot:

```
from plotHelper import *

#generate a plotting item
fig = plot()

#gen some data
x = [1,3,2,4]
y =['a','b','c','d']
E = []
for k in range(len(x)):
        E.append(1.0)
#create first data object
inputData = data('test',x,y,E)
#inputData.showError=True

#create second data set 
y=['d','g','e','a']
x = [3,2,1,2]
#y=[]
#E=[]
#for k in x:
 #       y.append(-k)

moreData=data("negative",x,y,E)
moreData.colour="blue"
#moreData.markers="D"
fig.addData(inputData)
fig.addData(moreData)

fig.makeYBarPlot()
```

**Comment by AnthonyLim23** [comment]
I have done an example plot below

![fitplot](https://user-images.githubusercontent.com/25006392/28371888-1cde4092-6c96-11e7-9eeb-b993328a4984.png)

alternatively:
     1. We could have a logscale main plot and a smaller range for an insert (e.g. up to 5)
     2. We could have two plots (log and not log) one on top of the other
     3. We could have the two plots side by side and share a y axis

**Comment by AnthonyLim23** [comment]
I have code which can now detect if it should be a log or linear scale and it produces the following: 
[comparison_weighted_v3.8_runtime_nist_average..pdf](https://github.com/mantidproject/mantid/files/1162663/comparison_weighted_v3.8_runtime_nist_average.pdf)
[comparison_weighted_v3.8_acc_nist_average..pdf](https://github.com/mantidproject/mantid/files/1162665/comparison_weighted_v3.8_acc_nist_average.pdf)
