### ISSUE TITLE
Fix some issues in Reflectometry GUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18185]
This refers to the old reflectometry GUI. Issues were reported by Max:

- Processing creates a <runno>_IvsQ workspace which is re-binned according to the setting, but we'd like to have the un-binned IvsQ workspace too and the re-binned one should be called <runno>_IvsQ_binned, like it used to.
- "Transfer" button doesn't work.
- "Save Workspaces" dialog doesn't populate the path correctly, it's missing a slash, e.g.: U:Skoda

**Comment by PranavBahuguna** [comment]
Regarding the first issue (retrieving unbinned ws), what should be done about grouping? Should the unbinned workspaces be grouped too? If not, should the group workspace for binned workspaces keep its name to "..._IvsQ", or should that change to "..._IvsQ_binned"?

**Comment by raquelalvarezbanos** [comment]
I think the only possibility to get the unbinned output is to run `ConvertUnits` on the `IvsLam` workspace that `ReflectometryReductionOneAuto` outputs.

**Comment by PranavBahuguna** [comment]
What should I do about the grouping issue?

**Comment by raquelalvarezbanos** [comment]
Is the output `IvsLam` grouped?

**Comment by PranavBahuguna** [comment]
Yes. My issue was whether or not we should group the original un-binned workspaces as well as the binned ones.

**Comment by raquelalvarezbanos** [comment]
For the binned workspaces: I think that should be done automatically (`ReflectometryReductionOneAuto` will take care of that).

For the un-binned workspaces: I think if the `IvsLam` workspace is a workspace group, if we just run `ConvertUnits` on it a workspace group will be produced.

Let me know if I am wrong.

**Comment by raquelalvarezbanos** [comment]
Not sure why this wasn't closed when https://github.com/mantidproject/mantid/pull/18239 was merged.
