### ISSUE TITLE
Add specific missing unit tests

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#18215]
We are missing unit tests on a few algorithms, this ticket is to deal with these ones:

 1. CalculateSlits
 1. LoadSampleDetailsFromRaw
 1. UnwapMonitor
 1. MaskDetectorsIf
 1. CrossCorrelate
 1. LoadInstrumentFromNexus

You can use github to identify the authors (Blame is often easier than history) and talk to them if the code / documentation is not good enough.

Submit each as a separate pull request

**Comment by gemmaguest** [comment]
Unit tests have now been added for all of these algorithms.
