### ISSUE TITLE
Intercept data from ParameterMap for Instrument-2.0 transition

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#18228]
Instrument-2.0 will store certain information such as mask flags and position information in class like `SpectrumInfo` and `DetectorInfo`. Currently this data is stored in `ParameterMap` (only offsets for positions).

For compatibility with legacy files we need to be able to intercept data that is being written to `ParameterMap`, reroute insertion of this data to new destinations, and inject this data when saving a `ParameterMap`.

The following locations have been identified as relevant:

- Loading parameters from an IDF: This is done by several load algorithms. Uses `ExperimentInfo::populateInstrumentParameters()`, which in turn calls `ExperimentInfo::populateWithParameter()`. Redirecting information seems to be straight forward.

- `LoadNexusProcessed`: Uses `ExperimentInfo::readParameterMap()`. Can filter and redirect data (`tokens[1]` is the parameter type, `tokens[2]` is the parameter name). Seems straight forward.

- `LoadMD`: Uses `MDBoxFlatTree::loadExperimentInfos`. This redirects either directly to `ExperimentInfo::readParameterMap()` (see above), or creates `FileBackedExperimentInfo`, which will eventually also calls that method. Seems straight forward.

- `SaveNexusProcessed`: Uses `ExperimentInfo::saveExperimentInfoNexus()`, which calls `Instrument::saveNexus()`. We can solve this one by creating a copy of the instrument, insert data from `DetectorInfo` into the parameter map of the temporary instrument, and call `saveNexus()` on that. Seems straight forward.

- `SaveMD2`: Uses `ExperimentInfo::saveExperimentInfoNexus()`, see above.

@ianbush @OwenArnold: I had a look at the mechanism we discussed, it seems to be surprisingly easy, basically all changes are within `ExperimentInfo`. Can you think of any other cases? Did I overlook anything?

**Comment by OwenArnold** [comment]
@SimonHeybrock. No nothing else comes to mind.

**Comment by SimonHeybrock** [comment]
Before we do this we need to address the following:

- Code using `ExperimentInfo::replaceInstrumentParameters()` and `ExperimentInfo::swapInstrumentParameters()` needs to be able to also replace data that is then in `DetectorInfo`. `CopyInstrumentParameters` is the only client, so this is easy.

- `ExperimentInfo::getInstrument()` and `ExperimentInfo::setInstrument()` needs to somehow also track data in `DetectorInfo`.
