### ISSUE TITLE
Waterfall & Tiled plots to be selected by drop-down list

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#18256]
Currently Waterfall and Tiled plots are selected by separate check boxes. It does make sense to select both and therefore it makes sense to instead select between three (1D plot, Waterfall plot, Tiled plot).

This issue is part of #18159, within which additional options will later be added to this drop-down list.

**Comment by KarlPalmen** [comment]
While testing this, I found out that if one is plotting several spectra from a group workspace, a tiled plot will have one tile per group member each with several spectra plotted. In such a circumstance the user might want to plot these as waterfall plots as is possible at present.

**Comment by martyngigg** [comment]
@KarlPalmen Can we have another option in the list that is only present in this type of circumstance named something like "Tiled Waterfall"?

**Comment by KarlPalmen** [comment]
I'll look into this "Tiled Waterfall" for group workspace possibility.

**Comment by KarlPalmen** [comment]
I've found out from recent test build of Mantid that if you set both the Waterfall and Tiled checkboxes in such a situation, the tiled plot does not have any waterfall plotting done. Therefore this issue can proceed and Martyn's suggestion can be carried out as part of any work to make tiled waterfall plots available for workspace groups.
