### ISSUE TITLE
Performance regression related to #17905

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#18291]
Changes made to the code in #17905 have resulted in a performance regression. See stats [here](http://builds.mantidproject.org/view/Tests/job/master_performancetests/Master_branch_performance_tests/APITest.MatrixWorkspaceTestPerformance.test_move_bank_and_read_positions_SpectrumInfo_x10.htm) and [here](http://builds.mantidproject.org/view/Tests/job/master_performancetests/Master_branch_performance_tests/APITest.MatrixWorkspaceTestPerformance.test_rotate_bank_and_read_positions_SpectrumInfo_x10.htm).

**Comment by Anders-Markvardsen** [comment]
Will be targeted for 3.10

**Comment by NickDraper** [comment]
Hard to see now how bad the loss of performance was as the graphs have moved on to the new baseline.

Haven't hear any specific comments on the log filtering performance from users of developers, so suggesting we accept the new baseline seeing as Tom left us.

Reopen if you disagree.
