### ISSUE TITLE
Wrapper for Python getDetector method

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#18317]
To ensure existing Python scripts still work after `DetectorInfo` becomes responsible for storing parameters, such as masking, we need a wrapper for the `Instrument.getDetector()` Python method.

Initially this needs to work for `IDetector::isMasked`, eventually it will wrap other things like positions, rotations etc.

A deprecated warning should be thrown when using `Instrument.getDetector()`, but otherwise scripts should work as they would have previously.

**Comment by SimonHeybrock** [comment]
@ianbush Note that you need to cover two cases of exported `getDetector` methods:

- `Instrument::getDetector`: forward calls to `DetectorInfo` .
- `MatrixWorkspace::getDetector`: forward calls to `SpectrumInfo`.
