### ISSUE TITLE
Masking by component in MaskDetectors

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#18327]
Currently [`MaskDetectors`](http://docs.mantidproject.org/nightly/algorithms/MaskDetectors-v1.html) supports only index-based masking. There is, however, need for component name based masking as well.

**Comment by rosswhitfield** [comment]
Have a look at [MaskBTP](http://docs.mantidproject.org/nightly/algorithms/MaskBTP-v1.html). It doesn't work with component name by with bank/tube/pixel numbers, it might do what you want with a little work.

**Comment by soininen** [comment]
@rosswhitfield Thanks for the tip! `MaskBTP` is too instrument-specific for our needs, however, although I might take another look at it with regards to the IN5 instrument at ILL. Implementing component masking in `MaskDetectors` didn't require that much effort, either, even though masking for example ranges of tubes like with `MaskBTP` in not possible.
