### ISSUE TITLE
Provide 2nd version of LoadNXCanSAS and SaveNXcanSAS

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18336]
The NXcanSAS definition has been release and there are some changes to the attribute names. This means our loader and saver needs to be updated. In order to have backwards compatibility, we need to create slightly updated versions.

**Comment by AntonPiccardoSelg** [comment]
NXcanSAS has been slightly modified by the CanSAS consortium. We need to create a second version of the loader.

We have to wait though until a schemer tool has been written by the consortium such that we can easily verify our work.

**Comment by AntonPiccardoSelg** [comment]
Waiting for Steve to come back with news

**Comment by AntonPiccardoSelg** [comment]
Ask Steve about the schemer

**Comment by smk78** [comment]
Pete Jemian at APS has a validator on beta release: http://punx.readthedocs.io/en/latest/

**Comment by smk78** [comment]
Follow up: punx may require

conda install lxml h5py numpy requests
pip install punx

**Comment by prjemian** [comment]
The relevant documentation for NXcanSAS is here: http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html

There are important differences from the draft version of the standard.

**Comment by prjemian** [comment]
@smk78: punx requirements here: http://punx.readthedocs.io/en/latest/install.html#required-packages

**Comment by gemmaguest** [comment]
Related to #28586
