### ISSUE TITLE
Investigate ParaView's matplotlib view

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#18341]
ParaView's [matplotlib view](https://blog.kitware.com/matplotlib-view-coming-in-paraview-4-1/) provides a way to include high-quality 2D figures alongside 3D views in ParaView. We should try this features and investigate how it would be best used in the VSI. 

Given the need to rewrite much of the current SliceViewer to make it compatible with Qt5, we should look into this and other opportunities to further combine these two interfaces.

**Comment by martyngigg** [comment]
@quantumsteve I was going to close this issue as it feels like we've taken a different direction now?
