### ISSUE TITLE
Refactor `Stitch1DMany`

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18378]
The code of `Stitch1DMany` is getting too complicated, partly because of the new property `ScaleFactorFromPeriod`. This issue is to have a look at the code and see if it can be simplified. Specifically, if we could replace property `ManualScaleFactor`, which is currently a number, with a vector, that would make things a lot easier. I need to check with scientists that this change is OK. In addition, we should validate the properties as soon as possible and throw better error messages.

**Comment by gemmaguest** [comment]
Raquel did check this with the scientists and they are OK with this change, so we can go ahead with this work.
