### ISSUE TITLE
Reflectometry interface (Polref): make processing instructions work properly

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18399]
This issue is similar to https://github.com/mantidproject/mantid/issues/18208.

### Expected behavior

Users should be able to enter processing instructions like this: `3, 4` in the `Settings` tab.

### Actual behavior

An error message is shown (`Invalid key value pair, '4'`) which is not very useful.

### Steps to reproduce the behavior

Open Reflectometry (Polref) interface, set instrument to `INTER` and enter the following data in the table:
- Run(s): 13460
- Angle: 0.7
Then go to `Settings` and enter `3, 4` in `ProcessingInstructions`.

### Platforms affected

All.

**Comment by PranavBahuguna** [comment]
Should I apply this to all other quoted setting values (such as direct beam)?

**Comment by raquelalvarezbanos** [comment]
Yes, similar properties will have the same problem.
