### ISSUE TITLE
Scope out what needs to be done to remove vms_compat

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18461]
`vms_compat` seems to be a legacy system. We need to ask Freddie how to get rid of it for more modern loaders.

### Files which use `vms_compat`

* LoadEventNexus.cpp
* SaveISISNexus.cpp
* UpdateInstrumentFromFile.cpp
* LoadIISISNexus2.cpp
* CreateSimulationWorkspace.cpp
* LoadNexusMonitors2.cpp
* LoadISISNexus2.h
* SaveISISNexus.h

##### LoadEventNexus.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `readInstrumentFromISIS_VMSCompat` |  `NAME`| Exists as `name` on top level|
| `loadSpectraMapping` | `UDET`   | Is array of detector IDs.|
| `loadSpectraMapping` | `SPEC`   | Is array of spectrum numbers|.
| `loadSampleDataISIScompatibility` | `SPB` | related to geometry|
| `loadSampleDataISIScompatibility` | `RSPB` | related to geometry|

In addition `IXvms` is checked in several locations.

##### SaveISISNexus.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `write_isis_vms_compat` |  `IXvms`| |
| `write_isis_vms_compat` |  `ADD`| |
| `write_isis_vms_compat` |  `CODE`| |
| `write_isis_vms_compat` |  `DAEP`| |
| `write_isis_vms_compat` |  `DELT`| |
| `write_isis_vms_compat` |  `FORM`| |
| `write_isis_vms_compat` |  `HDR`| |
| `write_isis_vms_compat` |  `LEN2`| |
| `write_isis_vms_compat` |  `MDET`| |
| `write_isis_vms_compat` |  `MODN`| |
| `write_isis_vms_compat` |  `MONP`| |
| `write_isis_vms_compat` |  `NAME`| |
| `write_isis_vms_compat` |  `NDET`| |
| `write_isis_vms_compat` |  `NFPP`| |
| `write_isis_vms_compat` |  `NMON`| |
| `write_isis_vms_compat` |  `NPER`| |
| `write_isis_vms_compat` |  `NSER`| |
| `write_isis_vms_compat` |  `NSP1`| |
| `write_isis_vms_compat` |  `NTC1`| |
| `write_isis_vms_compat` |  `NTRG`| |
| `write_isis_vms_compat` |  `NUSE`| |
| `write_isis_vms_compat` |  `PRE1`| |
| `write_isis_vms_compat` |  `RUN`| |
| `write_isis_vms_compat` |  `SPEC`| |
| `write_isis_vms_compat` |  `TCM1`| |
| `write_isis_vms_compat` |  `TCP1`| |
| `write_isis_vms_compat` |  `TIMR`| |
| `write_isis_vms_compat` |  `TITL`| |
| `write_isis_vms_compat` |  `TTHE`| |
| `write_isis_vms_compat` |  `UDET`| |
| `write_isis_vms_compat` |  `ULEN`| |
| `write_isis_vms_compat` |  `USER`| |
| `write_isis_vms_compat` |  `VER1`| |
| `write_isis_vms_compat` |  `VER2`| |
| `write_isis_vms_compat` |  `VER3`| |
| `write_isis_vms_compat` |  `VER4`| |
| `write_isis_vms_compat` |  `VER5`| |
| `write_isis_vms_compat` |  `VER6`| |
| `write_isis_vms_compat` |  `VER7`| |
| `write_isis_vms_compat` |  `VER8`| |
| `write_isis_vms_compat` |  `VER9`| |
| `write_isis_vms_compat` |  `NTNL`| |
| `write_isis_vms_compat` |  `NTLL`| |
| `write_isis_vms_compat` |  `VER9`| |
| `write_isis_vms_compat` |  `VER5`| |
| `write_rpb`  | `CRPB` ||
| `write_rpb`  | `IRPB` ||
| `write_rpb`  | `RRPB` ||
| `write_spb`  | `CSPB` ||
| `write_spb`  | `SPB` ||
| `write_spb`  | `ISPB` ||
| `write_spb`  | `RSPB` ||
| `write_vpb`  | `IVPB` ||
| `write_vpb`  | `RVPB` ||

##### UpdateInstrumentFromFile.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `updateFromNeXust` |  `IXvms`||
| `updateFromNeXust` |  `UDET`||
| `updateFromNeXust` |  `LEN2`||
| `updateFromNeXust` |  `TTHE`||
| `updateFromNeXust` |  `UT01`||

##### LoadIISISNexus2.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `exec` |  `NSP1`||
| `exec` |  `UDET`||
| `exec` |  `SPEC`||
| `loadRunDetails` |  `HDR`||
| `updateFromNeXust` |  `IRPB`||
| `updateFromNeXust` |  `RRPB`||
| `loadSampleData` |  `SPB`||
| `loadSampleData` |  `RSPB`||
| `loadSampleData` |  `RRPB`||

##### CreateSimulationWorkspace.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `loadMappingFromISISNXS` |  `NDET`||
| `loadMappingFromISISNXS` |  `SPEC`||
| `loadMappingFromISISNXS` |  `UDET`||

##### LoadNexusMonitors2.cpp

| Method                  |     vms entry           | Comment  |
|-------------------------|-------------------------|----------------|
| `loadSampleDataISIScompatibilityInfo` |  `IXvms`||
| `loadSampleDataISIScompatibilityInfo` |  `SPB`||
| `loadSampleDataISIScompatibilityInfo` |  `RSPB`||
| `fixUDets`                                              | `IXvms` ||
| `fixUDets`                                              | `UDET` ||
| `fixUDets`                                              | `SPEC` ||

**Comment by FreddieAkeroyd** [comment]
I will write you a table of the equivalents from elsewhere in the file

**Comment by AntonPiccardoSelg** [comment]
@FreddieAkeroyd  Thank you!

**Comment by AntonPiccardoSelg** [comment]
@NickDraper I assume this might be become relevant soon. Therefore I have assigned this to you instead of a simple unassign

**Comment by NickDraper** [comment]
@StephenSmith25 This might be helpful to see the bigger picture
