### ISSUE TITLE
Release image for 3.9

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#18501]
Could you create a nice release image of the non orthogonal slice viewer and add it to the release notes.

**Comment by lottiegreenwood** [comment]
![releaseimage](https://cloud.githubusercontent.com/assets/8983317/22201258/c11456c8-e15a-11e6-89e6-456a8dcd68ec.PNG)
![releaseimage1](https://cloud.githubusercontent.com/assets/8983317/22201259/c114b636-e15a-11e6-9226-b600744f1ed0.PNG)

let me know if you have a preference to with/without all sliceviewer options included
