### ISSUE TITLE
Mantid creates unhandled exception when date-time format is wrong in ICat

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18529]
We are getting an unhandled exception when passing an invalid date to iCat
![image](https://cloud.githubusercontent.com/assets/8955784/22248850/7279767c-e238-11e6-8fb4-56e89cc2a0ed.png)

### Expected behavior

When passing an invalid DateTime string we expect (maybe) a handled execption.

### Actual behavior

An unhandled execption is thrown.

### Steps to reproduce the behavior

1. Log into iCat
2. Add the following selection:

![image](https://cloud.githubusercontent.com/assets/8955784/22248958/e54604c2-e238-11e6-9c6c-c39d4b18d2f0.png)

3. Press search

### Platforms affected
At least Windows 7

**Comment by NickDraper** [comment]
Improve error handling in this UI
