### ISSUE TITLE
Monitor information not displayed in Show Detectors

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18530]
Spectra which are monitors are not displayed correctly in the table which is produced by `Show Detectors`

![image](https://cloud.githubusercontent.com/assets/8955784/22249717/ffa4bb3a-e23b-11e6-886e-dbf6d7140c54.png)

### Expected behavior

Should show inforamtion about the monitors.

### Actual behavior
Shows no information about the monitors.

### Steps to reproduce the behavior

1. Load a workspace with monitors
2. Right-click and select `Show Detectors`.
  Confirm that there are no meaningful entries for the monitors

### Platforms affected

At least Windows 7

**Comment by martyngigg** [comment]
I'll look into this. We should try not to ship the beta with this broken
