### ISSUE TITLE
Can revive ungrouped WorkspaceGroup in Python script

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#18534]
Run the script below and you will see the issue. It is not necessarily a bug but it deserves an investigation.

### Expected behavior

Should not be able to bring the group workspace back from the "dead". Expecting an exception mentioning that it. 

### Actual behavior

We can bring the group workspace back to life.

### Steps to reproduce the behavior

Run this:
```python
# CAREFUL: This script deletes everythign in the ADS. 
for element in mtd.getObjectNames():
    if mtd.doesExist(element):
        DeleteWorkspace(element)

# Create a group ws
ws = CreateSampleWorkspace()
group_ws = GroupWorkspaces([ws])

# Ungroup it
UnGroupWorkspace(group_ws)

# Bring it back from the dead
AnalysisDataService.add("back_again", group_ws)
```

### Platforms affected

At least Windows 7

**Comment by NickDraper** [comment]
UngroupWorkspaces removes the group workspace from the ADS, but as it is also held by the python variable it is not deleted.  Therefore it can still be used while that variable remains in scope.

Closed as this is a propbably desirable effect of python variables holding the lifetime of workspaces.
