### ISSUE TITLE
TofConverter cannot convert to Nu(Thz)

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#18553]
### Expected behavior
If the 'Convert To:' has 'Nu(Thz)' selected, then when convert is pressed a number should appear in the converted value box. 
### Actual behavior
For all input units (including Nu(Thz)) the error message
 'local variable OutputVal referenced before assignment' 
appears in a pop-up box, if  'Convert To:' is set to Nu(Thz). 

Input units of Nu(Thz) and any other option for 'Convert To:' produce sensible results. 
### Steps to reproduce the behavior
Enter an input value and select the units (any will do). In the 'Convert To:' box select Nu(Thz) and fill in any other relevant boxes. Then press convert and the pop-up box will appear with the error message. 
### Platforms affected
Windows 7.

**Comment by NickDraper** [comment]
Add error message for unsupported units, or event better remove them from the list

**Comment by KarlPalmen** [comment]
I found out that TofConverter is a utility interface.
