### ISSUE TITLE
Save to AscII crashes Mantid

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#18565]
### Expected behavior
The workspace is saved as an AscII file. 
### Actual behavior
Mantid crashes, the file is (sometimes) produced but it is empty. 
### Steps to reproduce the behavior
I have loaded and clicked save AscII for the two files in the zip file. Only occurs when WriteXError is ticked. 
[EQSANS_6071_event.zip](https://github.com/mantidproject/mantid/files/732038/EQSANS_6071_event.zip)
[164198.zip](https://github.com/mantidproject/mantid/files/732041/164198.zip)
### Platforms affected
Windows 7

**Comment by AndreiSavici** [comment]
Merged into master
