### ISSUE TITLE
Muon Analysis fails in simultaneous fit after change of instrument and fitting function

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#18566]
### Expected behaviour
In the muon analysis 'unscripted' tests group 2, in test 7, one should be able to fit `LinearBackground`. 

### Actual behavior
Mantid throws an unexpected exception complaining about a non-existent parameter.

### Steps to reproduce the behaviour
Run test 1 then test 7 in 
http://docs.mantidproject.org/nightly/interfaces/MuonAnalysis_test_guides/Muon_Analysis_test_group_2_fitting.html#muon-analysis-testguide-2-fitting-ref

### Platforms affected
Window 7 at least

**Comment by raquelalvarezbanos** [comment]
@KarlPalmen Could you double check this? I am not able to reproduce this bug.

**Comment by KarlPalmen** [comment]
It works OK on a recent build I used for test pull requests. I think you need to download the nightly build required for the unscripted testing. I'll try it again with a new download.

**Comment by raquelalvarezbanos** [comment]
OK, let me know. I was using the latest nightly build (version 3.8.20170125.1917)

**Comment by KarlPalmen** [comment]
I tried exactly the same nightly build and found out one needs to tick the checkboxes for both the periods as shown in the second illustration for test 7, for it to fail.

**Comment by raquelalvarezbanos** [comment]
Not sure what's happening, it seems to work for me...

**Comment by KarlPalmen** [comment]
... with the periods 1 and 2 both checked?

**Comment by KarlPalmen** [comment]
It also fails on my recent build for PRs, when I made sure I ticked both periods.

**Comment by raquelalvarezbanos** [comment]
Yes... with periods 1 and 2 both checked it seems to work... although fit results are not updated in the graph, but that is a different story. Below is what I have (I am afraid it is a bit small but you can open the image in a new window):

![muonanalysisunscriptedtesting](https://cloud.githubusercontent.com/assets/8956985/22332269/f4f82e00-e3c7-11e6-9ef9-381efb5bfd63.png)

**Comment by KarlPalmen** [comment]
I get this other story, if I do not run test 1 beforehand. I see `Cannot open fileError in logging framework: Cannot open file` in my cmd.exe window, but not my Mantid result log.

**Comment by KarlPalmen** [comment]
I think the other story is correct behaviour, because displaying several fits together would be tricky. Individual fits are available in the workspaces created and seem OK to me.

**Comment by KarlPalmen** [comment]
Given that this occurs only after changing an instrument in the course of work, which is an unlikely use case, I'm inclined to make this milestone 3.10 rather than 3.9 .

**Comment by raquelalvarezbanos** [comment]
I agree. I'll move it to 3.10 and leave it unassigned. Thanks for testing the interface Karl.
