### ISSUE TITLE
Indirect Absorption GUI : improve the layout of the options

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#18577]
This is a follow-up of the PR #18282 .

GUI view should be upgraded to look like attached.

Make sure the unit is specified for each input. e.g. it is not clear that sample angle is in degrees.

Optionally, most of the validation of the input properties should also be handled in GUI, before passing to the underlying algorithms.

![screen shot 2017-01-26 at 09 53 05](https://cloud.githubusercontent.com/assets/16865759/22336286/f09896e6-e3e1-11e6-8108-d2d9e0a3a925.png)

**Comment by louisemccann** [comment]
Could also use the opportunity to get the default beam parameters in the interface
