### ISSUE TITLE
Indirect I(Q,t)Fit - incorrect plot options menu

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#18570]
The Indirect I(Q, t)Fit plot options menu displays 'Beta' twice for the stretched exponential options
![image](https://cloud.githubusercontent.com/assets/12883435/22332728/4a1393fa-e3ca-11e6-8f34-2a0627e95d40.png)
Intensity plots A0
Tau plots Intensity
Beta1 plots Tau
Beta2 plots Beta

### Steps to reproduce the behavior
Interfaces>Indirect>DataAnalysis>I(Q,t)Fit
Load an `_iqt` workspace
Choose Streched Exponential for fit type
Press Run
Check Plot Output menu

### Platforms affected
All

**Comment by SpencerHowells** [comment]
Check the Exponential option as well. This too needs Background on the menu.

**Comment by louisemccann** [comment]
@SpencerHowells that should have added Background to all options
