### ISSUE TITLE
Group TOF workspaces

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18675]
The Reflectometry GUI produces a TOF workspace for each run. These workspaces should be grouped as the old GUI does.

**Comment by PranavBahuguna** [comment]
In the `GenericDataProcessorPresenter` the `TOF` runs are being generated by a preprocessor that takes input from run numbers from the `Run(s)` column and runs the `Plus` algorithm on them, generating output workspaces with the `TOF` prefix.

Grouping these runs will not be trivial as there is currently no mechanism in the GDPP for obtaining these output runs and running a `GroupWorkspaces` algorithm on them.

**Comment by gemmaguest** [comment]
I think we can do this in the algorithm `ReflectometryISISLoadAndProcess`. We can probably just hard code the group name to `TOF` and place the TOF workspaces into it when we load them. I think this is what the old GUI did.

- If the workspaces are already loaded I think we should probably group them as well - it seems that this is what the old GUI did.
- If there is already a `TOF` workspace group then we just add the additional workspaces into it.
- If there is already a workspace called `TOF` which is not a workspace group then we should prbably throw an error.
- If the input TOF workspace for a run is already a group we'll end up with something like the following where we lose the original grouping. We should check this is ok with scientists (this fails in the old GUI):
![image](https://user-images.githubusercontent.com/12895056/59184623-6e011300-8b66-11e9-99eb-d70573108959.png)
