### ISSUE TITLE
Rename Reflectometry (Polref) GUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18673]
Agree with scientists on a better name for this interface. Maybe just `ISIS Reflectometry`.

**Comment by gemmaguest** [comment]
We agreed that we would name the new interface `ISIS Reflectometry` and rename the old one to `ISIS Reflectometry (old)`

**Comment by PranavBahuguna** [comment]
Makes sense, especially given that the new interface could use instruments other than just POLREF anyway.
