### ISSUE TITLE
SpectrumInfo and DetectorInfo rollout: Peaks to PeaksWorkspace

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#18687]
This issue is part of the SpectrumInfo and DetectorInfo rollout, see https://github.com/mantidproject/mantid/issues/17743.
Algorithms covered in this issue are:
```
Framework/DataObjects/.../Peak.cpp
Framework/DataObjects/inc/MantidDataObjects/Peak.h
Framework/DataObjects/.../PeakTest.h
Framework/DataObjects/.../PeaksWorkspaceTest.h
```

**Comment by OwenArnold** [comment]
This isn't straight forward at the moment. We should have a better idea how to do this once positions are in the `DetectorInfo`. I'm also going to have a look at what would be required to update the `InstrumentRayTracer` use the instrument view.

**Comment by SimonHeybrock** [comment]
@OwenArnold Yes, we will need an equivalent of `InstrumentRayTracer`. I suspect we need a lot more basic functionality in `Beamline` before that could be done?
