### ISSUE TITLE
Reflectometry GUI does not output combined transmission run in wavelength

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18707]
The reflectometry GUI should output combined (stitched) transmission run in wavelength. This doesn't happen when transmission runs are specified via the `Settings` tab.

**Comment by PranavBahuguna** [comment]
The issue at heart here seems to be that in `GenericDataProcessorPresenter.cpp`, specifying trans runs in the table allows them to be obtained by `getPreProcessingOptions() - the code then calls `prepareRunWorkspace()` which creates a stitched ws name of the trans runs. If trans runs are specified in the `Settings` tab only however, those trans runs will not be preprocessed and thus stitched.
