### ISSUE TITLE
MPI Serialisation for HistogramData types

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#18717]
Implement serialisation as a part of histogram rollout on `GatherWorkspaces` and `BroadcastWorkspace`.

Plan for work:
- [ ] Have _meaningful_ performance results before any changes are done to the algorithms
  - [ ] Implement performance tests if necessary
- [ ] Implement serialisation for the HistogramData types. 
  - Have a look at `boost::serialisation`.
  - This should be implemented in `MPISerialization.h`
- [ ] Refactor `BroadcastWorkspace` and `GatherWorkspaces` to use HistogramData with the new serialisation functions.
- [ ] Run the performance tests and note if there are any significant differences.

**Comment by DimitarTasev** [comment]
The `BroadcastWorkspace` and `GatherWorkspaces` were found to not compile without changes on the latest [master](https://github.com/mantidproject/mantid/tree/bd129b92d39b528aaf10047e5b7b03f877c548a0)
