### ISSUE TITLE
Mantid python does not unwrap range any more

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#18730]
### Current behaviour
 Currently if ones assigns range to a variable in python reduction script, it is unwrapped into list. 

### Actual behaviour 
Some internal changes in mantid python, made for compliance with Python 3, changed this behaviour so if one assigns range to a variable, in fact you assigning an iterator. Direct inelastic reduction scripts fail as expect list or string as input.

Probably best way ahead in this situation (bearing in mind  future changes to Manitd) is to modify script to accept iterator.

**Comment by AndreiSavici** [comment]
If you need list, just use `list(range(n))`

**Comment by abuts** [comment]
I will, but number of existing scripts will break and some users will be unhappy. This is why this changes are necessary.
