### ISSUE TITLE
Make VSI popups Modal

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#18733]
Spotted by Jon Taylor

### Expected behavior
Dialogs on the VSI should be able to come in front of the main VSI window

### Actual behavior
They are hidden behind

### Steps to reproduce the behavior
Open VSI and click something that generates a dialog. For example, setting the rotation point.

### Platforms affected
OSX

**Comment by AndreiSavici** [comment]
Merged into master
