### ISSUE TITLE
Indirect Transmission - plot has wrong axis

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#18749]
> There is a bug in plotting transmission. Please see below : The can and sample results are just opposite in the mini plot and the workspace plot. Also the Y-axis shouldn’t be A-1 but “Transmission”.

![trans1](https://cloud.githubusercontent.com/assets/12883435/22737426/ea356d10-edfa-11e6-95d9-7e39b5634223.jpg)
![trans2](https://cloud.githubusercontent.com/assets/12883435/22737427/ea389116-edfa-11e6-9472-a60c3037d527.jpg)

**Comment by SpencerHowells** [comment]
Change green to blue as well.
