### ISSUE TITLE
Removing ties of fixed parameters doesn't work.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#18779]
### Expected behaviour

Removing a tie from a fixed parameter in the GUI should untie it.

### Actual behaviour

The fixed parameter remains fixed.

### Steps to reproduce the behaviour

1. Start the function fit browser. Use any data set and function.
2. Fix a parameter (right click on the parameter name, option "Fix").
3. Remove the tie (right click - Remove Tie).
4. Fit.

The value of the parameter doesn't change as if it remains fixed.

### Platforms affected

All.

**Comment by AndreiSavici** [comment]
Merged into master
