### ISSUE TITLE
Indirect->Analysis, Indirect->Corrections :: Forbid selection of group workspaces.

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#18792]
The above mentioned custom interfaces crash when a group workspace is chosen. These interfaces are not supposed to operate on workspace groups, so the data selectors should explicitly forbid the group workspaces using the new feature in PR #18241.

Steps to reproduce the crash:

1. Set ILL/IN16B as facility/instrument.
2. Go to `Indirect Data Reduction -> ILL Energy Transfer`
3. Select the **090661.nxs** file in unit tests `ILL/IN16B` folder and click run.
4. Go to `Indirect Data Analysis -> ConvFit` 
5. In the first selector there, select the **WorkspaceGroup** produced in the reduction step.

**Comment by gvardany** [comment]
@louisemccann Can you confirm that none of these tabs is supposed to work on WorkspaceGroups?

**Comment by louisemccann** [comment]
@gvardany that is correct for corrections. For analysis, I think Elwin does, but it doesn't use a workspace data selector.
Could you also remember to use the Indirect Inelastic Label?

**Comment by SpencerHowells** [comment]
None of our routines use a group selector. ElWin creates a Group to reduce the number of entries in the Workspace menu. If we were to use a Group in the interface what would it do? Would it run on all members of the Group (risky scientifically!) or enable selection of a member.

**Comment by gvardany** [comment]
It depends what you would want, but for the moment it is not foreseen and Mantid just crashes, so it would be nice to prevent it.

**Comment by SpencerHowells** [comment]
Just stopping a crash is fine by me. Go ahead.
