### ISSUE TITLE
Buttons to expand/collapse all groups

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18825]
Scientists mentioned they would like to additional buttons in the Reflectometry interface to be able to expand/collaps all the groups in the table.

**Comment by gemmaguest** [comment]
This is low priority but may make it into 3.10 as it is an easy win

**Comment by raquelalvarezbanos** [comment]
Just for information: the class that is creating the "actions" (also called "commands" in the code) is `DataProcessorTwoLevelTreeManager`. Two new actions will have to be created and class `ReflRunsTabPresenter` will have to be modified accordingly (see `ReflRunsTabPresenter::pushCommands()`, not sure if other classes may need to be modified too). The new actions will take a reference to the `GenericDataProcessorPresenter` (see for instance [AppendRowCommand](https://github.com/mantidproject/mantid/blob/master/MantidQt/MantidWidgets/inc/MantidQtMantidWidgets/DataProcessorUI/DataProcessorAppendRowCommand.h)) which can then act on the view with methods `QTreeView::expandAll()` and `QTreeView::collapseAll()`.

**Comment by raquelalvarezbanos** [comment]
If you ever have any questions/doubts about the `DataProcessorUI` widget the person to ask is Owen.

**Comment by PranavBahuguna** [comment]
Should there be two separate buttons for expanding and collapsing all groups respectively, or should both be handled by the same button?
