### ISSUE TITLE
Formalise live data display

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18828]
Add a button to the `ISIS Reflectometry` GUI to start live data monitoring
- It should run `ReflectometryReductionOneAuto` as a post processing algorithm
- It should use the instrument defined on the GUI
- It should get the angle and slits of the live run for use in RROA
- Properties on the Settings tab on the GUI should override the other inputs to RROA if they are specified. There are two groups on the GUI and it's unclear which should be used. It doesn't really matter so it will be fine to just assume that we always use Group1, as long as we make this clear.
- Ideally there should be an indicator on the GUI that live data is running
- Ideally live data monitoring should be restarted automatically if it drops out (which happens quite frequently when the data size changes)

We can get theta from ibex instruments using epics support in mantid. Reflectometry instruments are not on ibex yet but the controls team can install an additional process that will make the same variables available, e.g. this has been done for polref.
```
from epics import caget
title=caget('IN:POLREF:DAE:TITLE',as_string=True)
theta=caget('IN:POLREF:CS:SB:Theta',as_string=True)
print "Title:",title
print "Theta:",theta
```

**Comment by gemmaguest** [comment]
The scientists each have their own small scripts that they use for this, which they are currently happy with, so this is a low priority.
