### ISSUE TITLE
Make it possible to select different corrections based on selected monitors

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18821]
Scientists would like to be able to select different polynomial/exponential corrections depending on the monitor of interest. Currently there's only one set of corrections defined in the parameter file.

Some examples of current entries in the parameters file for the different types of correction are shown below. These should be changed so that they are linked somehow to the monitor index.  `ReflectometryReductionOneAuto` should then look up the correct set of parameters depending on the value of `IOMonitorIndex`.

These values can also currently be overridden by properties on `ReflectometryReductionOneAuto` - ***is this still required or can these properties be removed?***

```
  <parameter name="correction" type="string">
    <value val="exponential"/>
  </parameter>

  <parameter name="C0">
    <value val="36.5688"/>
  </parameter>

  <parameter name="C1">
    <value val="0.188676"/>
  </parameter>
```

```
  <parameter name="correction" type="string">
    <value val="polynomial"/>
  </parameter>

  <parameter name="polystring" type="string">
    <value val="35.5893,-24.5591,9.20375,-1.89265,0.222291,-0.0148746,0.00052709,-7.66807e-6"/>
    <!--<value val="28.0051,-19.396,7.5629,-1.624,0.1986,-0.013783,0.00050478,-7.56647e-6"/>-->
  </parameter>
```

```
  <parameter name="correction" type="string">
    <value val="none"/>
  </parameter>
```

**Comment by gemmaguest** [comment]
This should be easy so may make it into 3.10 if we have time. Christy can explain what needs to be done.

**Comment by gemmaguest** [comment]
This has been pushed back to v3.14 due to other work taking priority

**Comment by gemmaguest** [comment]
I'm removing the milestone until we review priorities because it turns out this is more complicated than initially envisaged.

**Comment by gemmaguest** [comment]
Closing as Stale because we are unlikely to get around to this any time soon. Most of what we need is already there and the final parts sound quite complex and low priority.
