### ISSUE TITLE
Filtering of runs in the reflectometry GUI

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18827]
Allow filtering of runs as illustrated in the design document sent by Max:

![gui-filtering-of-runs](https://cloud.githubusercontent.com/assets/8956985/22885036/876ae3ce-f1ef-11e6-94ef-7be1515335c2.png)

Ask him if you have any questions.

**Comment by gemmaguest** [comment]
Max has mentioned again that filtering on title/angle would be really useful. It could be regex based like the workspace list filter.

**Comment by gemmaguest** [comment]
Filtering has been implemented on the restructured GUI
