### ISSUE TITLE
Q error bars

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18824]
Reflectometry scientists would like to be able to handle Q error bars.

@gemmaguest has added some information following initial discussions with Christy [here](https://github.com/gemmaguest/documents/tree/Q_resolution_design/Design/Reflectometry/Q_resolution)

**Comment by gemmaguest** [comment]
This depends on:
- [ ] #18442 `NRCalculateSlitResolution`
