### ISSUE TITLE
Input workspaces can be forwarded to child algorithms for writing, without locking.

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#18862]
There does not seem to be a mechanism to prevent passing an input workspace to a workspace property of a child algorithm with `Direction::InOut` or `Direction::Output`. Apart from causing modifications of the input, the main problem is as follows:

- `Algorithm` locks input workspaces for reading. There can be multiple readers.
- Locking for child algorithms is skipped (it is assumed that correct locking has been done for the inputs/outputs of the parent, or workspaces are internal to the parent). That is, there will be no attempt made at write-locking the workspace (this attempt would block if there are other readers, so we would be safe).

The consequence is a broken locking mechanism that can lead to crashed, or worse, unpredictable results of another algorithm being run at the same time.

Examples can be found in `DiffractionEventCalibrateDetectors`.

**Comment by martyngigg** [comment]
I seem to remember a long time ago that there was talk, by Roman I think, that input properties should only be able to give access to `const` objects. The idea either got rejected for some reason or never followed through.

Would this be solved if we had such a concept? If inputs could not be modified then the parent doing the locking would be okay wouldn't it?

**Comment by SimonHeybrock** [comment]
@martyngigg I think that is not enough since you can pass the workspace by-name to the child algorithm?

**Comment by martyngigg** [comment]
As long as the name goes through the `WorkspaceProperty` wouldn' the `const`-only then apply to the child as well so that it couldn't modify it?

You are right with the name though that it could always be retrieved from the global `ADS`  :disappointed:

**Comment by SimonHeybrock** [comment]
Right, that is exactly what is happening here: https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/DiffractionEventCalibrateDetectors.cpp#L143 :(
