### ISSUE TITLE
SpecularReflectionPositionCorrect2 crashes with invalid detector name

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#18905]
### Expected behavior
If an invalid `DetectorComponentName` is provided to [`SpecularReflectionPositionCorrect2`](http://docs.mantidproject.org/nightly/algorithms/SpecularReflectionPositionCorrect-v2.html) it should throw an error.

### Actual behavior
Segmentation fault.

### Steps to reproduce the behavior
The following script demonstrates the problem:
```
inter = Load(Filename='INTER13460')
inter_new = SpecularReflectionPositionCorrect(inter, TwoTheta = 2*0.49, DetectorComponentName='lineardetector')
```

### Platforms affected
Probably all (confirmed on Windows & Ubuntu)

**Comment by PranavBahuguna** [comment]
A similar bug occurs if an invalid sample component name is given. I have fixed this too.
