### ISSUE TITLE
HistogramData rollout: algorithms <EnggDiffFittingPresenter.cpp to MuonAnalysisHelperTest.h>

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#18937]
This issue is part of the HistogramData rollout, see https://github.com/mantidproject/mantid/issues/17641.
Algorithms covered in this issue are:

MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp
MantidQt/CustomInterfaces/src/MantidEVWorker.cpp
MantidQt/CustomInterfaces/src/MultiDatasetFit/MDFDataController.cpp
MantidQt/CustomInterfaces/src/MultiDatasetFit/MDFDatasetPlotData.cpp
MantidQt/CustomInterfaces/src/SampleTransmission.cpp
MantidQt/CustomInterfaces/src/SANSPlotSpecial.cpp
MantidQt/CustomInterfaces/src/SANSRunWindow.cpp
MantidQt/CustomInterfaces/src/Tomography/ImageROIViewQtWidget.cpp
MantidQt/CustomInterfaces/src/Tomography/ImggFormatsConvertViewQtWidget.cpp
MantidQt/CustomInterfaces/src/Tomography/TomographyIfaceViewQtGUI.cpp
MantidQt/CustomInterfaces/test/ALCBaselineModellingModelTest.h
MantidQt/CustomInterfaces/test/ALCBaselineModellingPresenterTest.h
MantidQt/CustomInterfaces/test/ALCPeakFittingModelTest.h
MantidQt/CustomInterfaces/test/MuonAnalysisDataLoaderTest.h
MantidQt/CustomInterfaces/test/MuonAnalysisHelperTest.h

**Comment by martyngigg** [comment]
Closing as not worth consolidated effort in maintenance. Reveiwers can pick up and improve remaining code over time.
