### ISSUE TITLE
Ability to select a workspace in the ADS as the transmission run

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#19005]
This is something scientists would like to have.

In the new reflectometry GUI, if you have a workspace loaded in the ADS called for example `TOF_13460`, you can enter `TOF_13460` in the table, and the interface will pick the run from the ADS instead of loading into Mantid. This also works for transmission runs, so the table, will be able to reduce the following:

![ws_names](https://cloud.githubusercontent.com/assets/8956985/23361923/0c64f4e2-fceb-11e6-8e07-61ce0bdb8fc2.png)

just by retrieving the workspaces from the ADS. However, this is not possible if you specify the transmission run from the `Settings` tab. This issue is to add this functionality.

**Comment by PranavBahuguna** [comment]
I think the PR for #18707 might automatically solve this issue since it allows the transmission runs in the `Settings` tab to be used in preprocessing (where runs can be obtained from ADS directly instead of loading them) without reuse in processing.

**Comment by PranavBahuguna** [comment]
PR #19111 fixes this issue.
