### ISSUE TITLE
Improved way of working with fit function in Python 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#19010]
By implementing https://github.com/mantidproject/documents/blob/master/Design/Fit%20functions%20in%20python.md 

Function evaluation and plotting are excluded from this issue.

**Comment by KarlPalmen** [comment]
Issue #20279 has been created to enable ``castToComposite`` to be removed. It does so by tackling the root cause of the problem arising from the fact that ``ProductFunction`` etc. are not really exported to python.
