### ISSUE TITLE
Default facility and instrument setting issue

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#19020]
When altering the facility through the config service, the instrument stays the same. Similarly when altering the instrument, the facility stays the same.
This seems counterintuitive and error prone.
There are few places at least, where this causes a problem, since one can get a different result when asking the facility from an instrument, or from the config service directly.
These cases (e.g. file prefix in `MultiFileNameParser`) can be cured, but it is probably better to change the `ConfigService` itself, to change both properties in sync.

The snippet below exercises the ambiguous state that one could find himself at.
```
print config['default.facility']
print config['default.instrument']
config.setFacility('ILL')
print config['default.facility']
print config['default.instrument']
print config.getInstrument().facility().name()
```

**Comment by gvardany** [comment]
@martyngigg Do you think this is reasonable?

**Comment by martyngigg** [comment]
@gvardany You're right this seem confusing. What do you propose? Should we just clear the `default.instrument` when setting the facility?

**Comment by gvardany** [comment]
That's one possibility, do you think the 'empty' instrument will not cause problems? Alternatively, one could do similar to what first time setup GUI does, i.e. when changing the facility it sets the instrument to the first (alphabetically) instrument belonging to it.

**Comment by martyngigg** [comment]
On very first setup both default strings are actually empty so it shouldn't cause problems. First in the list is also a reasonable approach though I think.

**Comment by gvardany** [comment]
This is not particularly urgent.
