### ISSUE TITLE
`Clear Model` doesn't remove background fit functions

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#19039]
### Expected behavior
`Clear Model` should clear all of the fit functions. It should not make removed functions reappear.

### Actual behavior
`Clear Model` does not clear background fit functions. If you manually remove a background function, `Clear Model` makes it reappear.

### Steps to reproduce the behavior
- Follow Example 1 from here: http://www.mantidproject.org/MBC_Exercise_Intelligent_Fitting
- In the Fit Function browser, click on `Setup -> Clear Model`.
- Under Functions, `f0-Gaussian` disappears, but `f0-LinearBackground` remains.
- Right-click on `f0-LinearBackground` and click `Remove`. It now disappears.
- Click on `Setup -> Clear Model` again. `f0-LinearBackground` now reappears.

**Comment by NickDraper** [comment]
This is an interaction with the automatic background addition, that can be turned off in settings
