### ISSUE TITLE
Crash with instrument view and masking

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#19037]
### Expected behavior
Mantid should not crash.

### Actual behavior
Mantid crashed when viewing the instrument for a masked workspace

### Steps to reproduce the behavior
Unfortunately I have not been able to reproduce this. Here is what the user was doing at the time:

- The user ran through Example 2 here: http://www.mantidproject.org/MBC_Exercise_Connecting_Data_To_Instrument
- On the very last step (step 15) they changed the view to Full 3D. They clicked and dragged in the view to rotate it. At this point, mantid crashed.

### Platforms affected
This was seen on Windows 7 using MantidPlot v3.9.0

**Comment by NickDraper** [comment]
Not sen again in R3.10 testing, closing for now
