### ISSUE TITLE
Bad IDF causes segmentation fault

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#19056]
The following IDF causes Mantid to crash - the dummy gaps have overlapping spectra IDs which could cause the exception. 
[IMAT IDF.zip](https://github.com/mantidproject/mantid/files/817581/IMAT.IDF.zip)

This can be triggered by using `LoadInstrument` which forces it to reparse to specified IDF

**Comment by DavidFair** [comment]
#19552

**Comment by josephframsay** [comment]
We now get a friendly error message for this IDF, fixed by #20686
