### ISSUE TITLE
Script Mantid Python Window doesn't expand user variables in Linux

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#19068]
Quick sample code that will fail to find the workspace, in shell:
`touch ~/test.nxs` or use an existing file with a `~` character at the start of the path. 

Then in Mantid
`ws = Load(Filename=~/test.nxs)` this should find the file then fail. Currently it just fails as the file is not found.

The issue could be in the algorithms, because they are the ones responsible for expanding the path (I think)

**Comment by DTasev** [comment]
I have removed the Bug label, but I am not sure what label to put for a missing feature.

As for the expansion, I agree it should follow `os.path.expanduser`, as this is what I expected would happen.

**Comment by martyngigg** [comment]
I think it makes most sense for this behaviour to be added in the `FileProperty` using the rules laid down in https://docs.python.org/2/library/os.path.html#os.path.expanduser. This is then nice and easy to unit test too.
