### ISSUE TITLE
PredictPeaks predicts peaks on masked detectors

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#19066]
### Expected behavior
No peaks on masked detectors
### Actual behavior
peaks are there
### Steps to reproduce the behavior
PredictPeaks for corelli data with masking

**Comment by samueljackson92** [comment]
@VickieLynch I believe this will be fixed by the changes in #19207 for Corelli. For an instrument with rectangular detectors I think we only need to check the detector returned. I think I could just add that into #19207 quite easily.
