### ISSUE TITLE
Rebin in sliceviewer does not remain toggled when changing dimensions

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#19090]
### Expected behavior
If viewing data in the sliceviewer, whilst using automatic rebin, when changing dimensions from x=q1 and y=q2 to x=q1, y=q3 and then reverting back to the original x=q1 and y=q2 the automatic rebin should remain toggled. 
Currently it stops the rebinning.

**Comment by martyngigg** [comment]
Applies to the old sliceviewer that will be removed with MantidPlot.
