### ISSUE TITLE
DPDFReduction: improve interpolation to remove gaps in intensities in S(E, theta)

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#19102]
Example: the following reduction
```
DPDFreduction(RunNumbers="88708-88711", CleanWorkspaces=False,
    Vanadium="/SNS/ARCS/shared/autoreduce/vanadium_files/van88344.nxs",
    EmptyCanRunNumbers="88781",
    EnergyBins=1.5,
    MomentumTransferBins=0.1,
    OutputWorkspace="slices_QE")
```
produces the following S(E, theta)=`S_theta_E_normalized`:

![screenshot](https://cloud.githubusercontent.com/assets/1136006/23728168/75ec0fbe-0429-11e7-9085-4707cd43268b.png)

histograms 272 and 379 have many zeroes (blue dots). However, these histograms will not be corrected because the current interpolation requires a whole row of zeros. These spectra contain energy values with non-zero intensity.

Solution: for every histogram, count the number of energy values with zero intensity, then divide by number of energy values in order to obtain the fraction of zeros. Then, make a plot of these zero_fraction versus histogram number:

```
import numpy as np

def count_zeros(workspace, out_name):
    zero_fraction=list()
    n_histograms = workspace.getNumberHistograms()
    for index in range(n_histograms):
        y = workspace.dataY(index)
        zero_fraction.append(1.0 - (1.*np.count_nonzero(y))/len(y))
    dataX = range(n_histograms)
    dataY = zero_fraction
    CreateWorkspace(DataX=dataX, DataY=dataY, NSpec=1, OutputWorkspace=out_name)

count_zeros(mtd["S_theta_E_normalized"], "zero_fraction")
```

Plotting `zero_fraction`:

![screenshot2](https://cloud.githubusercontent.com/assets/1136006/23728350/51459eb8-042a-11e7-832a-f9e0dac9b50d.png)

If we trim the lower and upper 10% of the histograms, we see three peaks. We can identify the corresponding histogram numbers by finding those indexes for which their zero fraction is more than `mean(zero_fraction)+2*std(zero_fraction)`. Once found, we can apply the interpolation scheme of DPDFReduction to these histograms.

**Comment by samueljackson92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hello](https://trello.com/c/FamFkOsI/96-hello)
