### ISSUE TITLE
Remove background from MD workspace

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#19162]
Testing new method to remove background for peak integration

**Comment by samueljackson92** [comment]
@VickieLynch This sounds interesting. Do you have any more details on your upcoming method?

**Comment by VickieLynch** [comment]
@samueljackson92 We have matlab code working to remove a Poisson distribution (background) in a 3D box containing the peaks.  Will implement in mantid with this issue.

**Comment by VickieLynch** [comment]
Implemented in IntegratePeaksProfileFitting
