### ISSUE TITLE
Process Raw/Nexus sample shape information properly

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#1921]
This issue was originally [TRAC 1073](http://trac.mantidproject.org/mantid/ticket/1073)

Currently LoadRaw and LoadISISNexus read a few simple fields about the geometry and store them away on the sample object.  This is used to calculate sample volume in the SANS script.

Several steps to this one:
 1. Alter loadRaw and LoadISISNexus to convert the geometry info into a proper sample object and store on the sample class, at the sample position.
 1. Edit the SANS script to use the mantid defined geometry
 1. Ensure that load/savenexusprocessed carry through the sample geometry
 1. Alter the CreateSampleShape alg.
  1. Rename to EditSampleShape
  1. allow it to load up the existing defined shape.  You may need to make objects and therefore surfaces know how to create the xml string that defines them.

**Comment by NickDraper** [comment]
This has aged out of usefullness and replaced by geometry 2.0
