### ISSUE TITLE
Implement different processing instructions for transmission runs

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#19226]
**Original reporter**: Jos at ISIS

## Description ##
Jos has mentioned that they would like to apply different processing instructions for the transmission runs. To do this we will:
- Add a new property to `ReflectometryReductionOneAuto`, e.g. `TransmissionProcessingInstructions`. This should be used to pass through to the `ProcessingInstructions` property of `CreateTransmissionWorkspace` if it is given.
- Allow a default to be specified in the parameters file.
- If not given and no default is specified, I think the safest thing is to use `ProcessingInstructions` as before *(check this with Jos)*

The following issues should be fixed first:
- [x] #19252 Fix a bug passing processing instructions to `CreateTransmissionWorkspace`
- [x] Ideally #14000 should be done first to specify processing instructions as spectrum numbers instead/as well as workspace indices, so the new property can use the same method.

## Context ##
For context, below is a summary of the emails that were originally exchanged in identifying this requirement:

From Jos:

> Hi Raquel, Gemma,
> I’ve been playing about, and have found something a bit weird, a symptom of which I had seen before. I have an offspec run with good stats (39898, run at 1.0 degrees), and a direct beam (39904). Normally we would define a large range of pixels to catch all of the beam for the direct beam (transmission). When I set the processing instructions to 390-420 the resulting IvsQ (and binned) is infinite. When I set the processing instructions to 400-408, this makes them finite, but with high error bars and weird scaling. 
I would have expected the transmission to be summed in lambda across the pixel range, then this transmission would be used to divide through the reflectivity signal, but this is clearly not what is happening. Do you have any ideas about this? Kind regards,

From me:

>Hi Jos,
> I think I’ve found the issue: ReflectometryReductionOneAuto has an input property named “StrictSpectrumChecking”, which is true by default, and according to documentation, it checks that the spectrum numbers in the input workspace match the spectrum numbers in the transmission workspace. But looking at the code it seems that it is doing something else: before normalizing the detector workspace by the transmission run, if “StrictSpectrumChecking” is true, the algorithm gets the spectrum map of the detector workspace –which only has one element mapping spectrum number 391 to workspace index 0, as the detector workspace has been already summed in wavelength – and uses it to create new processing instructions. Because the spectrum map only has one one element {391 : 0}, the new ProcessingInstructions that are passed to CreateTransmissionWorkspaceAuto are 390. I am not sure why it does this. You can check that this is what is happening if you check the history of the IvsQ workspace: for CreateTransmissionWorkpsaceAuto I get that ProcessingInstructions were 390, instead of 390-420.

The problem is [this](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryReductionOne2.cpp#L257-L265) block of code, which was copied from version 1 of the algorithm (see [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryReductionOne.cpp#L730-L740)).

From Jos:

> Ideally, what would happen would be that there are different processing instructions for the direct beam as from the reflected beam. This is because the direct beam droops under gravity and so we set a large range in order to catch all of the neutrons. The reflected beam has the gravity somewhat cancelled because it bounced from the surface (though at some point we will come to try correcting this), so generally we don’t want as large a range.
I think that actually it might be possible to put the multidetector transmission processing instructions into the parameter file, since they really don’t change much. Max, your thoughts/objections on this?
Anyway, I think that as a general principle, we want to integrate over the entire direct beam for the TRANS, and select what we integrate over for the reflected beam. I don’t think that we mind too much exactly how it is executed.

**Comment by raquelalvarezbanos** [comment]
The question to ask scientists is if we need a second `ProcessingInstructions` property in `ReflectometryReductionOneAuto`. Then `ReflectometryReductionOneAuto` can look into the parameter file for the value of this property and pass it on to `ReflectometryReductionOne` as it does with other properties such as `WavelengthMin` etc.

**Comment by raquelalvarezbanos** [comment]
As a temporary fix I will fix processing instructions of the transmission run in https://github.com/mantidproject/mantid/issues/19252.

**Comment by Pasarus** [comment]
Some of this is implemented in: #23431

**Comment by gemmaguest** [comment]
This was done as part of #14000
