### ISSUE TITLE
EnabledWhenProperty accept multiple conditions

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#19257]
Modify `EnabledWhenProperty` to accept multiple conditions. 
Edit: `VisibleWhenProperty` too - thanks @rosswhitfield 

We should add a method which chains two EnabledWhenProperty objections together and provides `and` `not` or `or` methods.
We need to allow the Python API to also access this method too

**Comment by rosswhitfield** [comment]
You should do the same thing for `VisibleWhenProperty`.
