### ISSUE TITLE
Global fitting via scripts is broken

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#19256]
Pull request [#18362](https://github.com/mantidproject/mantid/pull/18362)  has broken the global fitting scripts in the [script repository](https://github.com/mantidproject/scriptrepository/tree/master/indirect_inelastic/models).

Benchmark data  and script to test this:  
[fit_irs26176_with_Teixeira.py](https://github.com/mantidproject/scriptrepository/blob/master/indirect_inelastic/models/TeixeiraWaterSQE/v3.9/fit_irs26176_with_Teixeira.py)  
[irs26173_graphite_res.nxs](https://github.com/mantidproject/scriptrepository/blob/master/indirect_inelastic/models/TeixeiraWaterSQE/irs26173_graphite_res.nxs)  
[irs26176_graphite002_red.nxs](https://github.com/mantidproject/scriptrepository/blob/master/indirect_inelastic/models/TeixeiraWaterSQE/irs26176_graphite002_red.nxs)

(This test will later be included as a system test. See #19249)

**Comment by jmborr** [comment]
@mantid-roman I'm trying to find out what went wrong, but I'd appreciate it if you could give me a hand.

**Comment by mantid-roman** [comment]
I'll have a look

**Comment by jmborr** [comment]
thanks a lot!

**Comment by mantid-roman** [comment]
@jmborr Could you explain what is broken?

**Comment by mantid-roman** [comment]
I think I know what happened. Sorry it was my fault. The fitting parameters should be OK but the computed spectra are wrong. The fix is in the patch release and in `master`.

**Comment by jmborr** [comment]
wow, that was fast. Can you please tell me the sha1 ID for the commit to master so that I can learn what needed to be fixed?

**Comment by mantid-roman** [comment]
This is the pull request: https://github.com/mantidproject/mantid/pull/19161

**Comment by jmborr** [comment]
I just compiled master, they're working fine now :smile:

**Comment by jmborr** [comment]
Fixed with #19161
