### ISSUE TITLE
Mantid incorrectly loads dragged file with multiple dots in filename

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#19275]
### Expected behavior
Mantid should correctly determine the filename when loading a file dragged in by the user
### Actual behavior
If you have two files such as 
`Mantid3.8Result.nxs`
`Mantid3.9Result.nxs`
And proceed to load the both only one workspace with the name
`Mantid3` 
Will be produced
### Steps to reproduce the behavior
Create two files with multiple dots in their name such as the above
Attempt to load both by dragging into Mantid
Only one workspace will be produced when using the names above 
### Platforms affected
Windows - Possibly All

**Comment by Mantid-Matthew** [comment]
@DavidFair was tempted to close as stale but decided to punt this back to you instead.
