### ISSUE TITLE
Fitting interfaces stopped handling ties to a constant when loading a function from the clipboard

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#19281]
Example: The fit function string `name=LinearBackground,A0=0,A1=0,ties=(A0=0)`:

1. Produces a function without the tie when loaded into interface **Fit Function**. One can later add the tie manually by invoking **Fix** or **Tie** from  parameter A0 pull-down menu
2. Produces a function without the tie when loaded into interface **Multi dataset fitting**. Trying to manually fix parameter A0 in the interface  by invoking **Fix** or **Tie** results if segfault and shuts down Mantid with the following error:
```
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt4/QtCore/qvector.h, line 359
Aborted (core dumped)
```

Tested on Ubuntu 1604 with **master** branch with build 3.9.20170331.1511

**Comment by jmborr** [comment]
@mantid-roman Hi Roman, I suspect this has to do the recent change regarding the lack of a ParameterTie for a fixed parameter.

**Comment by mantid-roman** [comment]
Yes. I'll have a look.

**Comment by jmborr** [comment]
@mantid-roman Is this proves to be too much of a fuss, would you consider rolling back the changes and let parameter fixes instantiate parameter tie references? To me there's nothing conceptually wrong assigning a tie to a parameter.

**Comment by jmborr** [comment]
looks good to me
:shipit:
