### ISSUE TITLE
Improve ctest support with multi-configuration generators

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#19303]
### Expected behavior

CMake recently added `$<CONFIGURATION>` which can be used for setting ctest variables that depend on the build configuration (Debug, Release, etc.).

http://stackoverflow.com/questions/9467510/how-to-pass-ctest-configuration-type-using-add-test-in-cmake

https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=07934636

### Actual behavior

Mantid implements a workaround for python tests and MSVC. The added functionality could both make this much simpler and work with more build configurations like RelWithDebInfo.

https://github.com/mantidproject/mantid/blob/844e45473e35096d6a948fd7d573a285b19284db/buildconfig/CMake/FindPyUnitTest.cmake#L27

Workarounds should be added for the the `Xcode` generator on MacOS.

### Platforms affected

Windows, MacOS

**Comment by quantumsteve** [comment]
I successfully used this variable to [set the PythonPath for SpinWaveGenie's test suite](https://github.com/SpinWaveGenie/SpinWaveGenie/blob/0b423e0b6c247a38c95d9fb28703ef918a9b0f10/pythonapi/test/CMakeLists.txt#L13)

`$<CONFIGURATION>` seems to give the same result for multi-configuration and single-configuration builds.

**Comment by martyngigg** [comment]
This is good. I remember this being a pain when I first set did those tests.
