### ISSUE TITLE
Create mock ups for QuickRun GUI

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#19318]
Create either a Balsamiq or Qt Designer mock up of the interface and tabs.

Discuss these with scientists to get general agreement that the design is okay.

Part of roadmap issue #18216

**Comment by martyngigg** [comment]
@louisemccann Please attach the mock ups to this issue so that we can keep track of them and have a history that they were done.

**Comment by louisemccann** [comment]
![samplechanger](https://cloud.githubusercontent.com/assets/12883435/24797002/565886d0-1b87-11e7-9d29-26d1857f22cf.png)
![sqwmomentsscan](https://cloud.githubusercontent.com/assets/12883435/24796999/56581146-1b87-11e7-97c8-125fbec9ea91.png)
![diffractionscan](https://cloud.githubusercontent.com/assets/12883435/24797000/56585fca-1b87-11e7-9cef-9cd2a9c255ad.png)
![energyscan](https://cloud.githubusercontent.com/assets/12883435/24797001/56585980-1b87-11e7-804a-257e9cfae624.png)

Initial mockups in Balsamiq

**Comment by martyngigg** [comment]
Thanks. Let's keep this issue up to date as we get feedback and update them so that we should converge on a design.
