### ISSUE TITLE
Extending Abins to replace a-CLIMAX

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#19322]
The Abins algorithms have been merged with the main mantid code base. Further extensions are required so that they can be used to replace a-CLIMAX on TOSCA.

Tasks:
* add calculations of S(Q,E) from DFT phonons
* add neutron transmission capabilities (this is for Vesuvio)
* GUI for users

This work will be carried out by SCD at ISIS.

**Comment by Anders-Markvardsen** [comment]
According to Sanghamitra this issue has been completed.  neutron transmission capabilities is for Vesuvio.

Abins is now used by most of Tosca's users
