### ISSUE TITLE
Performance regression caused by changes to IndexInfo

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#19339]
See, e.g., `ConvertSpectrumAxis` and `DiffractionFocussing2` here: http://builds.mantidproject.org/view/All/job/master_performancetests2/Master_branch_performance_tests/.

Caused by https://github.com/mantidproject/mantid/pull/19186.

Some slowdown was expected, but this is too much -> investigate.

**Comment by OwenArnold** [comment]
I've taken a look at `ConvertSpectrumAxis` with a profiler. It looks like the majority of the time is being spent in `setInstrument` constructing `API::DetectorInfo` and `API::ComponentInfo`, (both taking the same amount of time).

**Comment by OwenArnold** [comment]
Looking at `DiffractionFocussing2` it seems that `IndexInfo` is the offender.

**Comment by SimonHeybrock** [comment]
@OwenArnold For `DiffractionFocussing2`, I notice that `LoadEmptyInstrument` is taking a very long time? It is outside the test cases so does not affect the performance test.
