### ISSUE TITLE
DataProcessorTableWidget improvements

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#19354]
Several scientists have suggested improvements for the DataProcessorTableWidget.

- [ ] Table should have a row numbers
- [ ] The row which is currently being reduced should be highlighted.
- [x] There should be a mechanism to stop a reduction
- [ ] The positioning of the table cell text fields should be less awkward
- [x] There should be a mechanism where pressing 'tab' selects the next table cell

**Comment by gemmaguest** [comment]
Closing as we are no longer using the data processor widget and the job tree view fixes most of these issues that are still a requirement
