### ISSUE TITLE
Add algorithm property types for lattice centering, point and space group

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#19442]
Many algorithms in `Crystal` offer options for specifying lattice centering, point group, potentially also space group. These algorithms generally implement some variation of:

1. Find all possible values for the option (lattice centerings, point groups, space groups)
2. Create `string` property with `ListValidator`
3. Take string input, create object from string using unspecified mechanism

Instead of continuing to implement this by copy/pasting from other algorithms, there should be a property type that can be used with no further action from the developer implementing the algorithm. Ideally, all that's necessary in `exec` should be:

```cpp
PoinGroup_sptr pg = getProperty("PointGroup");
```
The property should also be flexible in the sense that most properties in algorithms now use the "name" of a centering, for example `All-face centered`, but it is much shorter to type `F`. In order not to break stuff, the properties should accept both variants.

**Comment by martyngigg** [comment]
The algorithms that required it now take some form of reflection condition.
