### ISSUE TITLE
Clean up of API::Infos in ExperimentInfo

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#19441]
Follow on from Issue #19385 & PR #19403. Some things were not addressed there that should be dealt with.

**Mandatory**

* Remove check for `API::DetectorInfo` in `ExperimentInfo::getInstrument`
* Add default constructor for `API::ComponentInfo` and use in `ExperimentInfo`. Make similar to `API::DetectorInfo` usage
* Remove the need to construct `DetectorIDs` from `Instrument` twice in `API::DetectorInfo`
* Remove old constructor from `API::DetectorInfo` whereby the map is constructed internally. This is no longer used.

**If Possible**

* Use `InfoComponentVisitor` to create the detector id map instead of getting the information from `Instrument`.

**Comment by SimonHeybrock** [comment]
Regarding `DetectorIDs`, we can maybe reconsider storing detector IDs in `Beamline::DetectorInfo`. That would automatically remove repeated construction.
