### ISSUE TITLE
WorkspaceIndex range property for PDFFourierTransform

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#19455]
Current PDFFourierTransform algorithm requires input workspace containing only one histogram. Extend this algorithm to sequentially carry out the Fourier transform in multi-histograms workspaces, including a related property to allow User to select range(s) of workspace indexes for the Fourier transform to be applied

**Comment by LamarMoore** [comment]
@jmborr and @peterfpeterson I am currently working on a `WorkspacePropertyWithIndex` which should satisfy the above requirements. See the issue [here](https://github.com/mantidproject/mantid/issues/19130)

**Comment by jmborr** [comment]
not needed for the moment
