### ISSUE TITLE
Crystal Field documentation

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#19498]
More detailed documentation for the Crystal Field module has been requested - specifically including worked examples (in the `Interfaces` category along with the current documentation page). Also, some scientific background should be provided in a `Concepts` page.

**Comment by AnthonyLim23** [comment]
@mducle does the latest addition to the documentation cover this or do we need to add some more?

**Comment by mducle** [comment]
Ah doh! No, there still needs to be some more documentation - so this still needs to be kept open. Sorry.
