### ISSUE TITLE
Indirect Corrections - Container - Cannot load data

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#19507]
The Indirect>Corrections>container Subtraction interface is unable to load data produced by the Indirect>Data Analysis >Elwin interface
The Container Subtraction interface also converts all workspaces to have units of wavelength, this is no longer necessary.
Sample Data:
[osi104369-104389_graphite002_red_elwin_elf.zip](https://github.com/mantidproject/mantid/files/985975/osi104369-104389_graphite002_red_elwin_elf.zip)

**Comment by SpencerHowells** [comment]
This should await the new MC absorption algos, in particular the version for Elastic window data.

**Comment by SpencerHowells** [comment]
Container subtraction without corrections doesn't need to convert to wavelength.
