### ISSUE TITLE
LoadNexusProcessed with a PeaksWorkspace is very slow

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#19522]
Loading a peaks workspace from a nexus file appears to be very slow. For me it takes almost 5 minutes to open a file with ~325 peaks and a WISH instrument. This should not be the case when the data being loaded is actually quite small.

### Expected behavior
Loading a nexus file with a peaks workspace should be fast

### Actual behavior
It's incredibly slow.

### Steps to reproduce the behavior
Run Load on the attached file.

[24954_allpeaksbyhand.nxs.zip](https://github.com/mantidproject/mantid/files/989101/24954_allpeaksbyhand.nxs.zip)

### Platforms affected
All.

**Comment by KarlPalmen** [comment]
Without the change, the file attached to the issue, took between 3 or 4 minutes to load. With the change it took a small number of seconds.
