### ISSUE TITLE
Plotting 0 on log axis shows 0.1

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#19529]
If there is a spectrum that is entirely made of 0 values, plotting the spectrum on a log scale will give a show that log(0) is at 0.1
For example:
**Regular plot**
![image](https://cloud.githubusercontent.com/assets/12883435/25906337/44f833f2-359c-11e7-9ce8-fb7b758e23f2.png)
**log(y)**
![image](https://cloud.githubusercontent.com/assets/12883435/25906374/63d840c8-359c-11e7-8709-04093af56f55.png)

**Comment by martyngigg** [comment]
We do have to make some decision of what to do `log(0)` as it is undefined but choosing `0.1` does seem confusing here, especially when the curve is part of a combined plot and it makes it seem that there is a value that doesn't exist.
