### ISSUE TITLE
Muon multiple fitting labels are wrong for single fits

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#19544]
### Expected behavior
If the user wants to do a single fit (e.g. fwd and period 1) in the multiple fitting GUI in muon analysis then the label and workspace names should match the data used (i.e. fwd and 1). 
### Actual behavior
If the user has multiple fitting in muon analysis and selects (does not need to fit) a simultaneous fit (e.g. fwd and bwd groups), then selects a single fit. When the fit is run the labels and workspaces are wrong. 
### Platforms affected
all

**Comment by rosswhitfield** [comment]
Fixed in #19545
