### ISSUE TITLE
EXED contains duplicate detector IDs

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#19551]
The recently added EXED [IDF](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/EXED_Definition.xml) tries to reuse detector ids...this is likely not doing what the author expected.

The ID list for monitors is being used twice once [here](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/EXED_Definition.xml#L25), and then again in the range [here](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/EXED_Definition.xml#L94). The second attempt leaves an parasitic detectors - part of the full in-memory instrument but cannot actually be referenced since it's ID are invalid. See (`Instrument::markAsDetector` ) if you're interested in seeing how the detector ends up orphaned.

After fixing, much of this can be sanity checked by eye. 

1. ID Lists should contain unique detector id ranges.
1. ID Lists should be used only once within a given IDF.

This is blocking the rollout of Instrument 2.0 features.

**Comment by NickDraper** [comment]
This issue has a PR so doesn't need the Review Required Label, we ten to use that for issues that are being closed without a PR, for example duplicates, or issues we propose not to fix.  So I've removed the label.
