### ISSUE TITLE
IN16 contains duplicate detector IDs

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#19550]
The IN16 [IDF](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/IN16_Definition.xml) tries to reuse detector ids...this is not doing what the author expected.

ID 19 is used twice because it appears once as a monitor ID [here](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/IN16_Definition.xml#L69), and then again in the range [here](https://github.com/mantidproject/mantid/blob/4743fbe0cef54e50b48212cd39c0b1f09da9a556/instrument/IN16_Definition.xml#L114). The second attempt leaves an parasitic detector - it is part of the full in-memory instrument but cannot actually be referenced since it's ID is invalid. See (`Instrument::markAsDetector` ) if you're interested in seeing how the detector ends up orphaned.

After fixing, much of this can be sanity checked by eye. 

1. ID Lists should contain unique detector id ranges.
1. ID Lists should be used only once within a given IDF.

This is blocking the rollout of Instrument 2.0 features.

**Comment by gvardany** [comment]
I guess you are referring to `IN16` here, if so it is an old instrument and is dismounted. I will double check that and remove it from mantid.

**Comment by OwenArnold** [comment]
@gvardany `IN6_Definition.xml` is the one that's causing the problems. Thanks for helping with this.

**Comment by SpencerHowells** [comment]
I would like to keep this definition so that users can analyse old data. It looks like a typo for the monitor. The detectors are 1-28 so the monitor should be 29.

**Comment by gvardany** [comment]
I can confirm that at ILL, old IN16 instrument data is not treated with mantid. So up to you to keep this IDF or to fix the typo `19->29`.

**Comment by OwenArnold** [comment]
As it's such a minimal change. I'll go ahead ad make the update. I'll follow @SpencerHowells instructions for this.
