### ISSUE TITLE
Moderator file for Q resultion calculation in ISIS SANS only works for caseinsensitive search

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#19589]
The moderator file is converted to upper case letters in `isis_reduction_steps.py`. On linux the file finder will not find it when `casesensitive=On` has been set.

This issue has come up while testing #19554 

To reproduce:

Please find sample data here: smb://olympic/babylon5/Scratch/Anton/SteveFiles
Make sure that the data is added to your Mantid path.
Make sure that `casesensitive=On` in your Mantid.xxx.properties file

1. Open the ISIS SANS GUI and select LOQ as the instrument
2. Load the user file: `USER_LOQ_171B_M4_Alexander_8mm_Changer_MAIN.txt`
  * Confirm that the an error appears stating that the moderator file cannot be found.

**Comment by Mantid-Matthew** [comment]
This issue is replicated and fixed here #21037
