### ISSUE TITLE
Tidy up of single crystal peak integration 

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#19605]
This is an issue to clean up the code from the PR #19533. This mostly comprises of documentation.  Please see the PR for the comments.

**Comment by samueljackson92** [comment]
There is some extra refactoring that should be done here. There is duplicated functionality between some methods in Integrate3DEvents and also between the two ellipsoid integration algorithms.

**Comment by AnthonyLim23** [comment]
@DannyHindson do you think we should keep this or close it?

**Comment by DannyHindson** [comment]
I think we can close this. I'll close it now
