### ISSUE TITLE
MantidPlot crash when leaving a dialog open

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#19669]
MantidPlot crashes on close with segmentation fault when one leaves the auto-generated GUI of a python algorithm open.

### Expected behaviour
MantidPlot should close normally.

### Actual behaviour
Segmentation fault on close

### Steps to reproduce the behaviour
1. Open MantidPlot.
2. Open the auto-generated GUI of any python algorithm
3. Close MantidPlot while the algorithm dialog is open

### Platforms affected
Discovered on OS X, but probably ALL.

**Comment by jmborr** [comment]
@martyngigg Would you take a look to this, please?

**Comment by martyngigg** [comment]
@jmborr I'll take a look tomorrow. I think I understand the problem so hopefully it should't be too hard to fix.
