### ISSUE TITLE
StartLiveData docs fail to build for facilities other than ISIS and SNS

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#19673]
### Expected behavior

All documents should build regardless of facility set.

### Actual behavior

If your default facility does not have any live listeners (e.g. facilities other than ISIS or SNS) `StartLiveData-v1.rst` fails to build.

### Steps to reproduce the behavior

Start Mantid, set the default facility to the ILL. Try to build the documentation.

### Platforms affected

All.

**Comment by NickDraper** [comment]
This also causes an unexpected exception in the GUI when the StartLiveData GUI is opened.

"Attempted to access live listener for D17 instrument, which has no listeners"
