### ISSUE TITLE
Links for offline help not working. 

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#19678]
In MantidPlot help (offline documentation). The following links will go to an index page, however the links in that index page go to a not found error. 

Algorithms
Concepts 
Interface
Fit Functions

Interestingly the links to the algorithms in the release notes work.

**Comment by AnthonyLim23** [comment]
@NickDraper  who would be the best person to speak to about this bug?

**Comment by martyngigg** [comment]
Further investigation shows that this seem to be a Windows problem. My Ubuntu build does not show the bug.
