### ISSUE TITLE
Indirect - Calculate Paalman Pings CTD on plot

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#19693]
Copied from #19638 

Crash of Mantid in the Indirect Corrections -> Calculate Paalman Pings. 

I used irs26176_graphite002_red.nxs from the unit test folder. 
- Set the chemical formula to V then run the algorithm. 
- When it completes in the output options I left the Plot Ouput to Wavelength
- Hit Plot. This causes Mantid to Crash.

**Comment by louisemccann** [comment]
I am unable to replicate this issue
