### ISSUE TITLE
Question mark button in the title bar of dialogs does nothing.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#19717]
### Expected behavior

On my windows machine MantidPlot algorithm dialogs have a [?] button in the title bar next to the close [x] button. It is supposed to give help on the GUI elements of the dialog...

### Actual behavior

... but it doesn't work.

### Steps to reproduce the behavior

Open an algorithm dialog.

### Platforms affected

Windows 10

**Comment by NickDraper** [comment]
Ideally let's make this work and link it to our help, otherwise let's hide it.
