### ISSUE TITLE
Indirect Bayes - Closing interface while running causes crash

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#19718]
### Expected behavior

- In all three tabs of the interface, if the user closes the window before running has finished, it should either exit gracefully or they should be prevented from closing until running has finished.

### Actual behavior

- When user closes window while running, Mantid crashes.

### Steps to reproduce the behavior

- Open the Indirect Bayes interface and go to any of the three tabs (`ResNorm`, `Quasi`, `Stretch`).
- Enter files for Sample and Resolution (e.g. `irs26173_graphite002_red.nxs` and `irs26176_graphite002_red.nxs` respectively).
- Click `Run` then close the interface immediately - this should cause Mantid to crash.

### Platforms affected

Windows, likely others.

**Comment by SpencerHowells** [comment]
Quasi & Stretch both use Fortran program and only run on Windows. Closing an interface will not stop the Fortran. The interaction with the Fortran may be there problem.

**Comment by SpencerHowells** [comment]
Checked this out on Quasi. All the fitting works - log says BayesQuasi successful. It then crashes - I assume when it tries to return to the interface to deal with Plotting & Saving.
