### ISSUE TITLE
Line/arrow drawing in MantidPlot

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#19716]
### Expected behavior

When drawing a line or an arrow in a graph (MantidPlot) I would expect to see their current positions or at least some indication that drawing is happening. 

### Actual behavior

When you drag the mouse nothing happens. The line appears after the mouse button is released.

### Steps to reproduce the behavior

Draw a line or arrow.

### Platforms affected

Saw it on Windows.

**Comment by NickDraper** [comment]
Probably being replaced in M4, wontfix for now
