### ISSUE TITLE
Synchronization overhead in LoadNexusProcessed 

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#19727]
### Expected behavior

Execution time in parallel loops should decrease with the number of core. 

### Actual behavior

Lots of time is spent waiting on a mutex in `EventWorksapceMRU::deleteIndex`. Is there anything more we can do about this?

![image](https://cloud.githubusercontent.com/assets/5920552/26513722/0418d9f8-423b-11e7-8f65-1d5c357fac02.png)

### Steps to reproduce the behavior

I found this in #19726 by running LoadNexus on CORELLI data. @rosswhitfield @AndreiSavici Do we have a similar file in SystemTestData or StandardTestData?

### Platforms affected

All

**Comment by quantumsteve** [comment]
Removing the locks [here](https://github.com/mantidproject/mantid/blob/b472472dcbe0a22a8fadc5cd18ba99fd5dddd9b2/Framework/DataObjects/src/EventWorkspaceMRU.cpp#L142) and [here](https://github.com/mantidproject/mantid/blob/b472472dcbe0a22a8fadc5cd18ba99fd5dddd9b2/Framework/DataObjects/src/EventWorkspaceMRU.cpp#L146) increases performance by a factor of two. There are a separate set of mutexes and locks in MRUList.h.

Since the number of threads is fixed at runtime, is such lock-free access to these vectors safe or easy made safe?

**Comment by SimonHeybrock** [comment]
I might be possible, with at least one other change: ensuring that `data` is always allocated. I think if we manage to remove the `mutable` from `m_bufferedDataY` and `m_bufferedDataE` we should be fine?

**Comment by SimonHeybrock** [comment]
Looking a bit closer, it might be more tricky: For the case of multiple algorithms accessing the same workspace, we need to ensure that we can run, e.g., `findY` and `deleteIndex` at the same time. In `findY` a pointer to the element is obtained (`MRUList::find`), and then a shared pointer is extracted. Currently the locks in `EventWorkspaceMRU` ensure that the element is not removed between the call to `MRUList::find` and copying the `shared_ptr` held by the obtained element.
