### ISSUE TITLE
Fixes/improvements to ISIS SANS Interface

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#19772]
This is a list of issues and suggestions for improvements that came up during the unscripted testing for the ISIS SANS Interface (#19649).

**Unhandled exceptions**
- [x] In the `Diagnostics` tab, enter `LOQ74014.nxs`, then click `Horizontal Integral`. You get an unexpected exception with the error message `Workspace2D::getSpectrum, histogram number 8 out of range 8`
- [x] In the `Add Runs` tab, enter an asterix (`*`) or double quote character (`"`) and click `Add`. You get unexpected exception: `Bad path syntax`. 
- [ ] On the `Masking` tab, I entered various combinations of invalid text (usually a comma or dash) in the first and/or second box under `User Mask` several times and clicked `Display Mask`. Sometimes (not consistently) I got a couple of unexpected exceptions with the error message `Instrument view: workspace doesn't exist`.
- [ ] After repeating the above tests on the `Masking` tab several times, I then closed all of the instrument windows that had been opened, and I got the error `Discarding OpenGL error` repeated many times in the log. I could not reproduce that error again.

**Errors/warnings**
- [ ] After starting a reduction in batch mode, quickly click on `Single run mode` and click `Load Data`. You then (usually) get an error `Error reported by Python script, more information maybe found in the scripting console and results log`. Loading data while a reduction is in process should probably be disabled.
- [ ] On the `Reduction Settings` tab, enable `QResolution` and enter some invalid text in e.g. in the `A1` box. Go back to the `Run Numbers` tab and click `1D Reduce`. You get various different errors/warnings from Python depending on the text you entered (e.g. `j` => `name 'j' is not defined`; `-` => `invalid syntax`; `""` => `Could not convert A1 to float` (warning)). We should validate the format of the input upfront and give a more sensible error message.
- [ ] In the previous example, these errors/warnings still occur even if you disable the `QResolution` option, which implies they are still being used even when greyed out, which doesn't seem right.
- [ ] On the `Geometry` tab, I changed `Beam Centre` to `HAB` and clicked `Run`. I got this error in the Geometry tab:
    `Incorrect number of parameters returned from function, check script.`
  And this message in the log:
```
    File "<Interface>", line 2
      print(i.ReductionSingleton().get_beam_center('front')[0]);print(i.ReductionSingleton().get_beam_center('front')[1];print('C++runReduceScriptFunctionC++')
    SyntaxError: invalid syntax
```
- [ ]  In the `Diagnostics` tab, enter the path to the sample file `LOQ74044.nxs`, then click `Time Integral`. You get an error about parsing the input string (even though no string was specified). If you enter a valid `Region` then it's ok (so perhaps that's a required argument, in which case it would be better for the error message to be more explicit).
- [ ]  In the `Diagnostics` tab, enter the path to the sample file `LOQ74044.nxs`, tick `Apply Pixel Mask`, and then click `Time Integral`. As well as the above-mentioned error, you also now get this error in the log: `TypeError: parse_instruction() takes exactly 3 arguments (2 given)`.

**Minor annoyances**
- [ ]  The tab order of widgets is quite random. In particular, it would be nice to be able to tab consistently between adjacent text boxes, e.g. the two `Q range` boxes on the `Reduction Settings` tab.
- [ ]  When reduction is running, some tabs are greyed out, so that you can't click on them to edit the settings (which makes sense). However, this means you can't even view the settings. It would be better if you could still click on the tab but have all the contents greyed out.

### Platforms affected
Windows 7, maybe all

**Comment by Mantid-Matthew** [comment]
This is a list of issues with the old SANS GUI which is going out of support so closing for now.
