### ISSUE TITLE
Instrument view crash when overlaying a peaks workspace

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#19784]
### Expected behavior

Trying to drag and drop a peaks workspace onto a 3D view opens a warning dialog asking to switch to a 2D view. Click OK. Continue working.

### Actual behavior

After closing the dialog mantid crashes.

### Steps to reproduce the behavior

1. Open a 2D instrument view with some workspace.
1. Go to Pick tab and select "Add a single crystal peak" tool.
1. Add a peak by first clicking on the instrument image then on the miniplot in the bottom left corner.
1. A table workspace named "SignleCrystalPeaksTable" is created.
1. Switch the view to 3D.
1. Drag the peaks workspace to the view.
1. A dialog should show. Click OK.
1. Crash

### Platforms affected

Saw it on windows and ubuntu.

**Comment by NickDraper** [comment]
Fix works nicely, low risk code change

:shipit:
