### ISSUE TITLE
Remove nexus python dependency

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#19796]
[SANSUtility.py](https://github.com/mantidproject/mantid/blob/master/scripts/SANS/SANSUtility.py) uses both `h5py` and the nexus python api (`nxs`). Change the calls to the latter to use the former (i.e. everything should use `h5py`). The bits that need to be redone are to remove lines 30-36, then redo the functions [`can_load_as_event_workspace`](https://github.com/mantidproject/mantid/blob/master/scripts/SANS/SANSUtility.py#L1523) and [`get_measurement_time`](https://github.com/mantidproject/mantid/blob/master/scripts/SANS/SANSUtility.py#L1768).

**Note:** Make sure to branch off of `release-v3.10` so it can be merged into the release.

**Comment by yxqd** [comment]
@AntonPiccardoSelg Could you point me to a test script that test this module so I can make sure my changes work? Thanks.

**Comment by AntonPiccardoSelg** [comment]
@yxqd The tests for `get_measurement_time` function is indirectly covered via [this](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/SANSFileChecking.py). `can_load_as_event_workspace` does not seem to be covered. I will create a couple of test cases as a PR.

**Comment by yxqd** [comment]
Thanks @AntonPiccardoSelg 

* get_measurement_time: $ cd /.../build; ./systemtest -R SANSFileChecking
* can_load_as_event_workspace: $ cd /.../build; ctest -R SANSUtility
