### ISSUE TITLE
Fix erorrs and warnings in ISIS SANS GUI that came up during beta testing

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#19790]
See here #19772 for the errors and warnings in the ISIS SANS GUI.

The items to tackle are:

**Errors/warnings**
- [x] After starting a reduction in batch mode, quickly click on `Single run mode` and click `Load Data`. You then (usually) get an error `Error reported by Python script, more information maybe found in the scripting console and results log`. Loading data while a reduction is in process should probably be disabled.
- [ ] On the `Reduction Settings` tab, enable `QResolution` and enter some invalid text in e.g. in the `A1` box. Go back to the `Run Numbers` tab and click `1D Reduce`. You get various different errors/warnings from Python depending on the text you entered (e.g. `j` => `name 'j' is not defined`; `-` => `invalid syntax`; `""` => `Could not convert A1 to float` (warning)). We should validate the format of the input upfront and give a more sensible error message.
- [ ] In the previous example, these errors/warnings still occur even if you disable the `QResolution` option, which implies they are still being used even when greyed out, which doesn't seem right.
- [ ] On the `Geometry` tab, I changed `Beam Centre` to `HAB` and clicked `Run`. I got this error in the Geometry tab:
    `Incorrect number of parameters returned from function, check script.`
  And this message in the log:
```
    File "<Interface>", line 2
      print(i.ReductionSingleton().get_beam_center('front')[0]);print(i.ReductionSingleton().get_beam_center('front')[1];print('C++runReduceScriptFunctionC++')
    SyntaxError: invalid syntax
```
- [ ]  In the `Diagnostics` tab, enter the path to the sample file `LOQ74044.nxs`, then click `Time Integral`. You get an error about parsing the input string (even though no string was specified). If you enter a valid `Region` then it's ok (so perhaps that's a required argument, in which case it would be better for the error message to be more explicit).
- [ ]  In the `Diagnostics` tab, enter the path to the sample file `LOQ74044.nxs`, tick `Apply Pixel Mask`, and then click `Time Integral`. As well as the above-mentioned error, you also now get this error in the log: `TypeError: parse_instruction() takes exactly 3 arguments (2 given)`.

**Comment by Mantid-Matthew** [comment]
This is a list of issues with the old GUI which is going out of support so closing for now.
