### ISSUE TITLE
AbinsModules to Python 3

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#19816]
Convert the AbinsModules to be compatible with python 3. These are group 15 in #18550 

The files are: 
`scripts/AbinsModules/AbinsConstants.py
scripts/AbinsModules/LoadCASTEP.py
scripts/AbinsModules/GeneralData.py
scripts/AbinsModules/AtomsData.py
scripts/AbinsModules/SData.py
scripts/AbinsModules/CalculateDWSingleCrystal.py
scripts/AbinsModules/CalculateS.py
scripts/AbinsModules/GeneralDFTProgram.py
scripts/AbinsModules/FrequencyPowderGenerator.py
scripts/AbinsModules/CalculatePowder.py
scripts/AbinsModules/LoadCRYSTAL.py
scripts/AbinsModules/InstrumentProducer.py
scripts/AbinsModules/AbinsData.py
scripts/AbinsModules/IOmodule.py
scripts/AbinsModules/DWSingleCrystalData.py
scripts/AbinsModules/KpointsData.py
scripts/AbinsModules/AbinsParameters.py
scripts/AbinsModules/Instruments/TwoDMap.py
scripts/AbinsModules/Instruments/ToscaInstrument.py
scripts/AbinsModules/Instruments/__init__.py
scripts/AbinsModules/Instruments/Instrument.py
scripts/AbinsModules/__init__.py
scripts/AbinsModules/PowderData.py
scripts/AbinsModules/AbinsTestHelpers.py
scripts/AbinsModules/SingleCrystalData.py
scripts/AbinsModules/CalculateSingleCrystal.py`

**Comment by dymkowsk** [comment]
Hi I just saw your issue. I am preparing a pull request which should solve this issue. It is currently in my branch  AbinsPython3.

**Comment by AnthonyLim23** [comment]
:1:

**Comment by dymkowsk** [comment]
I submitted a new pull request:
https://github.com/mantidproject/mantid/pull/19837

**Comment by peterfpeterson** [comment]
This was done in #19837.
