### ISSUE TITLE
Clean up code in MultipleFileProperty

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#19831]
#19826 was merged in time for the release but comments on the code are valid and need to be addressed.

I think other clean ups would be worthwhile such as making some variables, `constexpr` rather than constructing them each time through the methods, e.g. [here](https://github.com/mantidproject/mantid/blob/0488b194c4a00d1b7046d689c7cd076ef9d85844/Framework/API/src/MultipleFileProperty.cpp#L247).

**Comment by peterfpeterson** [comment]
It turns out you [can't use `constexpr` with `std::string`](https://stackoverflow.com/questions/27123306/is-it-possible-to-use-stdstring-in-a-constexpr) ... at least in c++11.

**Comment by martyngigg** [comment]
Ok. We could just make them static local variables. C++11 did at least guarantee threadsafe initialization of such things.
