### ISSUE TITLE
Add QResolution/X-Error option to CreateWorkspace

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#19856]
Anna wrote:
> And the most important, can you please update CreateWorkspace, so we can add ErrorX into the new one?

We should allow a XError option which should also be exposed to Python.

**Comment by AntonPiccardoSelg** [comment]
This was requested by ANSTO, speak to Anna about this

**Comment by gemmaguest** [comment]
See also #13680
