### ISSUE TITLE
Seperate out slow system tests from PR builds

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#19864]
Discover slow system tests, label them, and exclude them from PR builds.  Still run them for release and master builds

Slack Channel
dev2017_faster_builds

Slow tests spreadsheet
https://docs.google.com/spreadsheets/d/1uzAhnFM9Q8jMmrOzaZ32oBx_SDIdojKUgps9-EXpslo/edit#gid=0

Branch
https://github.com/mantidproject/mantid/tree/Dev2017_flag_and_skip_slow_tests

**Comment by DavidFair** [comment]
Added a check in the system test script ran by Jenkins: 
If the name does not contain *pull_requests* (i.e. we are the master or release build) we run the slow system tests, otherwise we skip them.

**Comment by NickDraper** [comment]
Potential slow tests identified, marked on spreadsheet, these have not been labelled in the system test code yet.

**Comment by NickDraper** [comment]
Added a flag for enabling slow system tests to be run. Slow tests are not run by default. A boolean parameter isSlow has been added to the stressting.MantidStressTest to mark where a test is slow.

**Comment by NickDraper** [comment]
change to "--exclude-in-pull-requests"

**Comment by NickDraper** [comment]
will need to return specific exit code, see eg __verifyMemory in stresstesting.py

**Comment by louisemccann** [comment]
@DavidFair you need to re-do your build script changes

**Comment by DavidFair** [comment]
I'm going to revert my changes - talking to @peterfpeterson we can pass extra args (i.e. `--exclude-in-pull-requests`) on Jenkins which is the preferred method.

**Comment by DTasev** [comment]
When the final solution is decided on, I'm happy to change the top X slow algorithms to have the `slow` flag (or whichever name we set upon - `excludeInPullRequests`, etc..)
