### ISSUE TITLE
Update SaveNistDAT and deprecate from ISIS SANS GUI

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#19882]
Steve wrote:
>I have been conversing some more with the guys at NIST.
 
>Having looked at their Igor code they say that it is only supressing the writing of Nan’s. It does write points with I = 0. So can we amend SaveNISTDAT to follow suit, please?
 
>But we then had a strategy discussion and agreed that now we have NXcanSAS it would make sense for they, and Mantid, to deprecate the future use of their format. So please could you ALSO remove the checkbox on the SANS GUI for NIST2D Qxy (but leave the routine in Algorithms); ie, so that the only checkboxes are NXcanSAS, CanSAS & RKH?

Hence we need to create a new version of SaveNISTDAT and the NistDAT option from the ISIS SANS GUI

**Comment by Mantid-Matthew** [comment]
Resolved in #22631
