### ISSUE TITLE
V2D and V3D are missing negate operators

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#19958]
The negation `V?D operator-() const;` methods and Python exports could be added to `V2D` and `V3D` classes.

**Comment by SimonHeybrock** [comment]
Note that we will slowly move to using `Eigen` instead of custom vector classes (e.g., `Eigen::Vector3d` instead of `Kernel::V3D`), but as far as I know there are no concrete plans on when this might be rollout out in which parts of the framework.
