### ISSUE TITLE
Inconsistent use of number density

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#19962]
In a number of places within Mantid number density is used inconsistently, between number of atoms per cubic Angstrom and number of formula units (molecules) per cubic Angstrom. This issue proposes to standardise everywhere to atoms per cubic Angstrom.

Changes required:
 * The documentation for the parameter `SampleNumberDensity` needs correcting in `SetSampleMaterial`.
* `SetSampleMaterial` needs a comment to clarifiy the two different `rho` calculations https://github.com/mantidproject/mantid/pull/12758/files#diff-7e6895aa1590493fe92220f55c3d630bR305.
 * `Material.cpp` needs to be clear in the doxygen that it is atoms per cubic Angstrom.
 * `MaterialBuilder` needs to set the atomic number density in `Material`. Doxygen should be fixed so that everything refers to atoms per cubic Angstrom.
 * Tests that will break:
   * `KernelTest.MaterialBuilderTest.test_Number_Density_Set_By_Formula_MassDensity`
   * `KernelTest.MaterialXMLParserTest.test_MassDensity_Attribute`
   * `CalculateSampleTransmissionTest.CalculateSampleTransmissionTest.test_mass_density`
   * `IndirectTransmissionTest.IndirectTransmissionTest.test_mass_density`
   * `SampleTest.SampleTest.test_material`

Related - the `Zparameter` is sometimes inconsistently defined between atoms in a unit cell and formula units in a unit cell. This should be standardised to formula units per unit cell.
 * `ZParameter` doxygen in `MaterialBuilder`

We need to look for anywhere else these issues might be lurking too.

**Comment by peterfpeterson** [comment]
One of the places that needs to be checked is [here](https://github.com/mantidproject/mantid/pull/12758/files#diff-7e6895aa1590493fe92220f55c3d630bR262)

**Comment by peterfpeterson** [comment]
Also, this would be a good time to add a "packing fraction" (set/get) and "effective density" (set only) to the `Material`/`Sample` object(s).

**Comment by ianbush** [comment]
@peterfpeterson I agree those things would be good to add, but I would rather keep this PR to the bug/docs fixes. Those changes would be good in a PR following on from this.
