### ISSUE TITLE
Evaluation and plotting of fit functions in python.

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#20005]
Implement function evaluation and plotting described in the design document:
https://github.com/mantidproject/documents/blob/master/Design/Fit%20functions%20in%20python.md

**Comment by KarlPalmen** [comment]
Evaluation will be done in issue #20420.

**Comment by KarlPalmen** [comment]
The evaluation has been completed and the plotting will be done in this issue.

**Comment by KarlPalmen** [comment]
This script works and plots ``sq`` as expected:
```
ws = CreateWorkspace(DataX=[0,1,2,3,4,5], DataY=[5,5,5,5,5,5])
sq = Polynomial(n=2, A0=0, A1=0, A2=1)
outWs = sq(ws)
sqvals = outWs.readY(1)
print sqvals
sqws = CreateWorkspace(DataX=[0,1,2,3,4,5], DataY=sqvals)
plot("sqws",0)
```
