### ISSUE TITLE
Move DetectorInfo into InfoComponentVisitor

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#20002]
This is a grouping or related items taken from the umbrella Item listed here: #19964

* `InfoComponentVisitor` to create `DetectorInfo` as well as `ComponentInfo` (1 from umbrella list)
* `Beamline::DetectorInfo` and `Beamline::ComponentInfo` should be created together. Construction should be as safe as possible as both have a runtime dependency on each other (2 from umbrella list)
* Remove work-around code in ComponentInfo::getPos etc, that tries to deal with current staged creation of the `..Info` objects. (7 from umbrella list)
* Possibly link these items via some other structure to ensure that lifetime rules (internal pointer ownership of each) make better sense. This is is a design aspect that falls out of the above. I am proposing a grouping called `Beamline` (agreed name for Instrument 2.0), that holds and provides well established semantics for `ComponentInfo` and `DetectorInfo`.

**Comment by SimonHeybrock** [comment]
I think this has been dealt with differently, closing?
