### ISSUE TITLE
Ensure Sample Shape details are loaded and saved in Mantid Nexus files

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#20015]
Ensure the the Sample shape is saved and loaded in Mantid intermediate nexus files.  This includes and changes for triangular mesh based sample shapes (#12827).

To test:

1. Create a workspace
1. Set a sample shape (using a Triangualar based mesh, or SetSampleShape)
1. SaveNexus
1. LoadNexus
1. The Loaded workspace should still have the SampleShape set as defined earlier

**Comment by KarlPalmen** [comment]
If MeshObject.getXML() is implemented SaveNexus, then work on this issue will deal with loading this saved shape.
