### ISSUE TITLE
Improve FindSXPeaks 

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#20052]
SXPeaks currently finds the strongest peaks per spectrum and returns a peak list. The background calculation is based on data in the current spectrum. We want to:

* add an absolute background for all spectra
* add a peak finding strategy which finds all peaks above a certain strategy
* (maybe handles the peak reduction better)

In addition the algorithm does not handle `WISH` and `ALF` data. This needs to be fixed.

**Comment by samueljackson92** [comment]
Reading about the problems uncovered with FindPeaksMD + the fact that ConvertToMD for one WISH file takes ~10mins makes this a good idea. 

It would be good to know how long it takes to search for peaks in each spectrum when you have as many as WISH. If this is very slow you could maybe cut down the search space by doing something like:
 - Integrate all spectra
 - Arrange integrated pixels spatially in 2D (like we do with a cylindrical mapping in the instrument view)
 - Find peaks + a radius in this 2D space.
 - Only perform 1D peak search only along spectra that fall in this radius.

That may or may not be slower than a brute force search.

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92 Thanks for commenting. I have training today, but I will be back on Monday. Let's talk about some of your suggestions then.
