### ISSUE TITLE
ISIS Reflectometry: Allow autoreduction button to pause reduction

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#20071]
~(Wait for PR #20041 to merge first before starting this)~

Currently when the `autoreduce` button is clicked, it will start autoreduction and disable itself. Pausing autoreduction can only be done through the `pause reduction` button in the toolbar. What we want is for the autoreduction button to have a similar capability:

- When clicked, the button should change its 'play' icon to a 'pause' icon and stay enabled.
- Clicking the autoreduction button while runs are processing should pause reduction in the same way the `pause reduction` button in the toolbar should. When this happens, the icon should revert back to the `play` icon.

**Comment by gemmaguest** [comment]
This is addressed in PR #22443 (this adds a separate Pause button rather than toggling the state, which is fine)
