### ISSUE TITLE
ISIS Reflectometry: Exclude transmission run from processing

### ISSUE THREAD

**Issue by PranavBahuguna** [mantidproject/mantid#20089]
When autoreduction is started, all runs including the transmission run are selecting for processing. When it attempts to process the transmission run however, it throws an error as it has an angle of zero (all valid runs must have an angle greater than zero).

This transmission run should probably be excluded from the list of runs to be processed. It would also be worth talking to the instrument scientists about any other runs (such as `Alignment check`) that should also be excluded from processing.

**To test:**

- Login to the ICAT catalog
- Open the ISIS Reflectometry interface, change instrument to `POLREF` and enter id `1520249`.
- While you can run autoreduce until you reach the last run to see the error, it is faster to simply search and transfer all runs and process the last row 'Transmission' - it will throw an error as it has an angle of zero.

**Comment by gemmaguest** [comment]
Following discussion with Max, there doesn't seem to be a good way to identify which runs to exclude - they should be sensibly named but we can't necessarily rely on it. They don't actually care whether these runs get reduced as long as they don't cause errors which stop the autoreduction.

**Comment by gemmaguest** [comment]
This will be fixed by PR #22443 which excludes runs with an invalid angle
