### ISSUE TITLE
MWRunFiles widget - '.' character results in an uncaught exception

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#20093]
### Expected behavior
There should be no exception prompt until the user runs the algorithm with invalid field entries.

### Actual behaviour
The MWRunFiles widget generates an exception when a sole '.' character is entered into it.

### Steps to reproduce the behaviour
1. Access any interface with an MWRunFiles widget (e.g. all Indirect > Data Analysis and Indirect > Data Reduction interfaces).
2. Enter a '.' into the widget.
3. Press enter or click out of the widget.

### Platforms affected

**Comment by robertapplin** [comment]
This should probably be fixed because it causes a crash and is very easy to replicate
