### ISSUE TITLE
McStas concept page

### ISSUE THREAD

**Issue by jamesphysics** [mantidproject/mantid#20148]
It is possible to read data between Mantid and McStas and there exist algorithms in Mantid to do this (http://docs.mantidproject.org/nightly/algorithms/LoadMcStas-v1.html) as well as similar documentation by the McStas team on how to output Mantid friendly data in McStas (https://github.com/McStasMcXtrace/McCode/wiki/McStas-and-Mantid).

However there does not yet exist a documentation page within the Mantid concepts that can explain what McStas does, where to find more information on McStas, and how to make the most of the work done to integrate these two packages from the aspect of a Mantid user.

Done as a supplement to #11945

**Comment by trnielsen** [comment]
For starting this process you could look at our McStas-Mantid paper: https://arxiv.org/abs/1607.02498

It is also referenced in the LoadMcStas doc in Mantid.
