### ISSUE TITLE
Parse the instrument tree in the base instrument

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#20163]
Parsing the instrument tree in the base instrument when it is being added to the IDS has two big advantages when loading more than one workspace with the same instrument:
- We avoid repeated parsing of the same tree.
- Data in instruments (`DetectorInfo` and `ComponentInfo`) will be shared between workspaces. Previously this was the case only for workspaces that were created from a parent workspaces, but not indenpendently created workspaces with the same instrument. Note that if there are parameters that modify the instrument sharing will still be (partially) broken.

This corresponds to item 8) in #19964.

**Comment by SimonHeybrock** [comment]
@OwenArnold I believe we implemented this, correct?

**Comment by OwenArnold** [comment]
@SimonHeybrock correct
