### ISSUE TITLE
BFGS empty matrix for fit benchmark

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#20196]
in fit benchmarking running: GEM63437_focused_bank3.nxs with BFGS causes an error: 

IndexError: Matrix is empty.

This error seems to come from the fitting function that has been chosen.

**Comment by Anders-Markvardsen** [comment]
Is this a bug only when the user selects minimizers = ['BFGS', 'Damped GaussNewton']  or do you also see it when you see all the minimizers

**Comment by AnthonyLim23** [comment]
I have been talking to Roman about it. He says that it is BFGS and Conjugate gradient (Polak-Ribiere imp.)

He has also tracked the error down to void DerivMinimizer::initialize

**Comment by AnthonyLim23** [comment]
Talking to Roman it the least squares file used the wrong command in one line it had `evalDeriv` instead of `evalHessian`

I have made the change to the code and I am going to run all of the system tests to make sure nothing as broken.

**Comment by Anders-Markvardsen** [comment]
uummm odd that this only affected BFGS though.... let me know how you would like me (or someone else) to test this

**Comment by AnthonyLim23** [comment]
the BFGS uses a Hessian matrix to decide the direction of the minimisation. I think the error meant that the Hessian was not constructed.
