### ISSUE TITLE
ISIS_Powder - Use AbsorptionCorrections for samples instead of MayersSampleCorrection

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#20219]

**Comment by martyngigg** [comment]
@DavidFair Could you provide a better description here including a reason why?

`MayersSampleCorrection` can just calculate absorption if you disable the MS option so why use two separate ones?

**Comment by DavidFair** [comment]
@martyngigg I didn't add a description as we were just splitting this work out from another branch.
Currently ISIS_Powder has support for absorption corrections on arbitrary samples, this incorrectly uses Mayers Sample Correction for both Vanadium runs and all other materials.

Now we check if we are focusing a Vanadium. If so we use MayersSampleCorrections in the script otherwise we use AbsorptionCorrections.

**Comment by martyngigg** [comment]
@DavidFair Thanks for the clarification.

The absorption part of `MayersSampleCorrection` should work for arbitrary samples. It's just the MS correction part that only applies to isotropic scatterers.
