### ISSUE TITLE
Convert instrument view miniplot to matplotlib

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#20240]
As part of the the preparation work for the new workbench we need to convert the miniplot within the instrument view to be a matplotlib-based widget in C++.

This will involve writing a small set of classes in C++ to wrap `matplotlib` and shield developers from the intricacies of dealing with the Python C api.

**Comment by ianbush** [comment]
Unfortunately I have not had enough time to tackle this. I will unassign myself for someone else to pick up.

**Comment by martyngigg** [comment]
The current development branch is extremely out of date. I'm going to split it up and get it merged in smaller chunks.
