### ISSUE TITLE
Export CurveFitting layer to Python

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#20279]
As part of #19971 there is a need for better access to Fit internals from Python.

A current problematic use case is where something like `f = FunctionFactory.createFunction("ProductFunction")` returns a Python object whose type is `IFunction` rather than `ProductFunction` so a check like `isinstance(f, CompositeFunction)` fails when it should succeed. We had a similar issue with the workspaces and so exported the `dataobjects` layer to resolve this - I propose we do something similar here and export the classes to Python.

A crucial difference in how I think we should export this layer is that we **don't** export it as a public API so that we avoid possible future issues with moving `mantid` to be more scipy-styled library. We can treat anything in it as internal and don't have to worry about renaming.

I think the following is required:

* add a directory called `_plugins` to [Framework/PythonInterface/mantid](https://github.com/mantidproject/mantid/tree/43fc616926a32863f37e37f4a107413a0de6dee6/Framework/PythonInterface/mantid)
* add an `__init__.py` that looks similar to the [dataobjects init](https://github.com/mantidproject/mantid/blob/43fc616926a32863f37e37f4a107413a0de6dee6/Framework/PythonInterface/mantid/dataobjects/__init__.py) but it only contains a line `from . import _curvefitting` and not the last line
* then add a similar layout to the `dataobjects` directory with a `CMakeLists.txt` , a directory called `src` that contains the `Exports` directory and files with the Python exports plus an `curvefitting.cpp.in` file. Most of this should be able to be copied and changed from the dataobjects directory

@mantid-roman @jmborr @KarlPalmen Please let me know if you see a problem with this.

**Comment by KarlPalmen** [comment]
The following script should work when the issue is resolved
```
p = FunctionFactory.createFunction("ProductFunction")
print len(p)
g = FunctionFactory.createFunction("Gaussian")
p.add(g)
p.add(g)
print p
```
