### ISSUE TITLE
Issues with KeyboardInterrupt with Mantid Python run from windows shell

### ISSUE THREAD

**Issue by ThomasLohnert** [mantidproject/mantid#20322]
Consider the following python script:

```
# from mantid.simpleapi import *
import time

try:
    while True:
        print "looping"
        time.sleep(2)
except KeyboardInterrupt:
    print "interrupt"
```

1. When I run the script from the windows console like: 
`/Mantid-install/bin/mantidpython.bat --classic script.py` 
then trying to interrupt it with Ctrl+C has no effect. Responsible is this bit on line 57 of `mantidpython.bat`: 
`start "Mantid Python" /B /WAIT `
1. When removing that bit (keeping `%_PYTHON_EXE%%ArgsExceptFirst%`) and running the script, KeyboardInterrupt works fine.
1. Now uncommenting the first line in the above script to import `mantid.simpleapi` leads to KeyboardInterrupt being picked up, but crashing the console with:

```
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
KERNELBASE.dll     00007FFF0B9C6634  Unknown               Unknown  Unknown
KERNEL32.dll       00007FFF0C728102  Unknown               Unknown  Unknown
ntdll.dll          00007FFF0F19C5B4  Unknown               Unknown  Unknown
```

**Comment by gemmaguest** [comment]
Sorry for the spurious refs, I got the issue number mixed up with #20332
