### ISSUE TITLE
Review object/surface intercept testing code

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#2033]
This issue was originally [TRAC 1186](http://trac.mantidproject.org/mantid/ticket/1186)

Currently the track interception methods contain some magic values that used to shift points, i.e. in the Object::calcValidType method
  const Geometry::V3D shift(uVec*Surface::getSurfaceTolerance()*25.0);
The value of 25 seems arbitrary and shouldn't need to be this large, a value of just over 1 should suffice. 

The interception methods are rather sensitive to these values a review of this code is necessary to improve their accuracy.

**Comment by NickDraper** [comment]
This issue has aged out of usefullness, and my become irrelevant with geometry 2.0
