### ISSUE TITLE
Crystal Field: python wrapper for CrystalFieldFunction function

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#20358]
Write a new python wrapper class for CrystalFieldFunction.

**Comment by mantid-roman** [comment]
Start your branch form 19341_crystal_field_multisite

**Comment by MatthewBowles** [comment]
@mantid-roman I've started this, could you quickly check [the code here](https://github.com/mantidproject/mantid/compare/19341_crystal_field_multisite...20358_CrystalFieldFunction_wrapper) to make sure I'm on the right lines? Let me know what needs to be changed and/or what to do next. Thanks.

**Comment by mantid-roman** [comment]
It looks great. Could you create a test file and write some unit tests for the new class?
