### ISSUE TITLE
Engineering Diffraction Analysis Interface - Initial dialog box

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#20421]
Upon loading the Engineering diffraction interface (Interfaces > Diffraction > Engineering Diffraction)
The user is presented with the following dialogue box:
![image](https://user-images.githubusercontent.com/13132128/30269663-874ab26a-96e1-11e7-9da8-23f2f4fe53d7.png)
This dialogue can not be closed and the instruction do not inform the user that in order to use the interface (and close the dialogue box) you need to add an RB number to the input field.
A discussion should be had about how to make this clearer to the user. Options to consider are:
* Tooltip on input field
* Entering the RB number into the dialogue box
* Using the red `*` notation for required/incorrect parameter that is used in algorithms

**Comment by josephframsay** [comment]
Addressed in PR #20993 (issue #20979). Possibly can be closed?

**Comment by ElliotAOram** [comment]
@josephframsay agreed they are duplicate
