### ISSUE TITLE
Engineering Diffraction Analysis Interface - Search data Archive

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#20423]
### Expected behavior
* When loading the interface, the load time should be the same if the `search data archive` is checked or unchecked. 

### Actual behavior
* When loading the interface with `search data archive` checked, the load time is significantly longer than that of when the options is unchecked.

### Steps to reproduce the behavior
* Attempt to open the Engineering diffraction interface (Interfaces -> Diffraction -> Engineering Diffraction) with the `Search data archive` options unchecked and checked. Difference in load time will be obvious.

### Platforms affected
Found on both Ubuntu (python v3) and Windows (python v27)

**Comment by samueljackson92** [comment]
This was investigated as part as part of #20954. It seems that for that particular file the URL query is slow to respond. There's not much we can do about that on our end.
