### ISSUE TITLE
Cannot sort peaks workspace by sigma/I column in slice viewer

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#20441]
As the name suggests, it does not seem possible to sort by this column in the slice viewer. For other columns it appears to be possible. This column is actually quite a useful one to sort by.

It is probably just a case of enabling it somewhere.

**Comment by ElliotAOram** [comment]
Investigation into this shows that the `Int/SigInt` value in the SliceViewer is created on the fly when the peaks workspace is added (using the overlay peaks functionality).

The sorting for the data in the SliceViewer uses the `SortPeaksWorkspace` algorithm and changes the underlying data in the PeaksWorkspace which is then used to update the table in the sliceViewer. As this is this case, it is not currently possible to sort the data.

A possible solution for this would be to add the additional data (`Int/SigInt`) to the PeaksWorkspace either during integration or when it is added to the SliceViewer. A change such as this should be discussed with other members of the team as (although ideally it shouldn't) changing the number of columns in a PeaksWorkspace could have repercussions else where (e.g. saving/loading etc.).
