### ISSUE TITLE
SystemTests.ISISDirectInelastic MAPS/MARI failing for python 3

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#20440]
There are 3 remaining failing systemtests for python 3, see [here](http://builds.mantidproject.org/job/master_systemtests-ubuntu-16.04-python3/203/testReport/)
```
SystemTests.ISISDirectInelastic.MAPSDgreduceReduction
SystemTests.ISISDirectInelastic.MARIReductionAutoEi
SystemTests.ISISDirectInelastic.MARIReductionMonSeparate
```
They all fail with `Workspace ??? not equal to its reference file`

**Comment by ElliotAOram** [comment]
Note: The above commit resolves issues for both `MARIReductionAutoEi` and `MARIReductionMonSeparate`

**Comment by ElliotAOram** [comment]
The values for `Ei` in the sample logs of the reference files matched the python 2.7 version of the value returned from `str(ei)`. When investigating further, giving `format` a higher precision (up to 15 decimal places) it suggested that the `Ei` in the reference files was not correct past 9dp. In the example of the `MAPSDgreduceReduction` test, the `Ei` value in each file was:

| File | Ei value |
| :-: | :-: | 
| Reference file | 152.60479834399999 |
| Test output using `str()` | 152.60479834399999 |
| Test output using `format()` | 152.60479834443578 |

As the values are not accurate, the reference files for all 3 test cases have been updated to match the new `format()` output.
