### ISSUE TITLE
Add a technique page for ISIS Reflectometry

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#20485]
The documentation for the individual reflectometry algorithms is good, but the terminology can be confusing, especially as there have been inconsistencies in the way e.g. `theta` and `twoTheta` are used (#20327). We should add a page to the Techniques category giving an overview of the instruments' set up, terminology used, relevant algorithms etc.

**Comment by soininen** [comment]
There is also the 'Techniques' category where this type of document might fit.
