### ISSUE TITLE
Python3 ComputeIncoherentDOS unit test

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#20612]
The `ComputeInchoerentDOS` unit test is not present in the CMakeList, adding it to the list passes with python 2.7 (confirmed locally on RHEL7 and Ubuntu) but is fails in Python 3 with the error:
```
======================================================================
550: ERROR [0.051s]: test_computeincoherentdos (ComputeIncoherentDOSTest.ComputeIncoherentDOSTest)
550: ----------------------------------------------------------------------
550: Traceback (most recent call last):
550:   File "/home/osboxes/git/mantid/Framework/PythonInterface/test/python/plugins/algorithms/ComputeIncoherentDOSTest.py", line 49, in test_computeincoherentdos
550:     ws_DOS = ComputeIncoherentDOS(ws)
550:   File "/home/osboxes/build/mantid/bin/mantid/simpleapi.py", line 1019, in algorithm_wrapper
550:     algm.execute()
550: RuntimeError: Only the variables Qmin and Qmax is allowed in QSumRange.
550:   at line 107 in '/home/osboxes/git/mantid/Framework/PythonInterface/plugins/algorithms/ComputeIncoherentDOS.py'
```
The issue in Python 3 should be resolved and the unit test added back into the CMakeList

**Comment by mducle** [comment]
Ok. So the problem is that the scope of variables in a list comprehension in Python3 is different from that in Python2 - in Python3, functions within a list comprehension can't see class variables, which the `evaluate*` functions in `ComputeIncoherentDOS` rely on. I've changed the code to work around this.
