### ISSUE TITLE
About MantidPlot Links Don't Work

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#20624]
### Expected behavior
The links to the Revision, Homepage, Citation and Release doi should open the browser on the appropriate page.

### Actual behavior
On Fedora 26 firefox this results in a browser crash. On Ubuntu nothing happens.

### Steps to reproduce the behavior
1. Open the about menu (`Help -> About MantidPlot`)
2. Click on any of the links.

### Platforms affected
- Fedora 26
- Ubuntu

**Comment by NickDraper** [comment]
passed on windows

**Comment by NickDraper** [comment]
ignore the last comment - wrong issue!

**Comment by martyngigg** [comment]
We put a fix in for the Firefox crash in some cases some time ago: #13909. Perhaps use of the wrapper needs to expand to other places?
