### ISSUE TITLE
Deprecate TOFTOFMergeRuns

### ISSUE THREAD

**Issue by mganeva** [mantidproject/mantid#20648]
The TOFTOF data reduction workflow has been changed to use MergeRuns (PR #20635) and TOFTOFMergeRuns  can be deprecated in 3.12 and removed in one of the later releases.

The following should be done:
1. Warning in the documentation, that algorithm is deprecated and MergeRuns should be used instead.
2. The same warning in the `PyExec` method.
3. The MergeRuns unit test that uses TOFTOFMergeRuns algorithm should be updated.

milestone: 3.12

**Comment by JoachimCoenen** [comment]
> The MergeRuns unit test that uses TOFTOFMergeRuns algorithm should be updated.

Does that mean it should be removed or the warnings from PyExec suppressed or expected, or...?
