### ISSUE TITLE
Indirect - ConvFit - Miniplot - Incorrect Plotting

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#20697]
The mini-plot in the ConvFit interface is incorrectly plotting the fit function and the fitting range is being reverted when changing the spectrum, even after manually setting the range.

**Comment by SpencerHowells** [comment]
The miniPlot is incorrect the current preview is ok.

**Comment by brandonhewer** [comment]
@SpencerHowells I believe the miniplot is the preview plot, it is named previewPlot within the code. I'll change this to avoid confusion though.

**Comment by SpencerHowells** [comment]
@brandonhewer So why are they different? Does the miniPlot need refreshing?

**Comment by brandonhewer** [comment]
PR Merged
