### ISSUE TITLE
Sample Transmission Calculator - Wavelengths can be negative

### ISSUE THREAD

**Issue by MatthewBowles** [mantidproject/mantid#20706]
### Expected behaviour

When a wavelength range is entered, there should be validation to prevent negative values from being entered.

### Actual behaviour

There is only validation to prevent negative values on the width parameter, not the low and high parameters.

### Steps to reproduce the behaviour

-Open Sample Transmission Calculator (interfaces -> general)
-Enter valid chemical formula (e.g. H2-O) and bin width
-Set both Low and High values for the wavelength range as negatives
-Observe lack of errors

### Platforms affected
Seen on Windows 7

**Comment by SpencerHowells** [comment]
Wavelengths cannot be negative!!

**Comment by SpencerHowells** [comment]
@MatthewBowles Negative wavelengths are a physical impossibilty!! If you want to make any change make it impossible to input negative values.

**Comment by MatthewBowles** [comment]
@SpencerHowells Yes, I have already edited this issue to reflect this.
