### ISSUE TITLE
LoadLiveData does not time out

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#20746]
After testing the fix for #20703 it was noticed that `LoadLiveData` never times out if it can't connect to the server. Mantid is left in a state that requires a user to kill it rather than being able to quit cleanly.

The bug can be reproduced with the same testing instructions that were used for producing #20703.

**Comment by NickDraper** [comment]
Attempted to reproduce with offspec and disabling the network card:

Produced these warnings, but did not crash or hang:
```
error reading command (getdat)
Unable to read DATA from DAE 130.246.37.30
Error in execution of algorithm MonitorLiveData:
Unable to read DATA from DAE  in 130.246.37.30
```

**Comment by NickDraper** [comment]
repeated with pulling out the network cable earlier before the first dataset was created. 

Then no crash or hang, but you get an uncancellable algorithm
![image](https://user-images.githubusercontent.com/1017173/31950640-edf56334-b8d3-11e7-8c50-31ac08f2de71.png)

**Comment by NickDraper** [comment]
Attempt 3:
Pulling the plug just after the first dataset gives a stuck algoirthm again, but let me search through the threads to see what we were stuck on.

line 100 of isisds_command.cpp
``` C++
static int recv_all(SOCKET s, void *buffer, int len, int flags) {
  char *cbuffer = reinterpret_cast<char *>(buffer);
  int n, ntot;
  ntot = 0;
  while (len > 0) {
    n = recv(s, cbuffer, len, flags);   //< THIS LINE IS THE PROBLEM
    if (n <= 0) {
      return n; /* error */
    }
    len -= n;
    cbuffer += n;
    ntot += n;
  }
  return ntot;
}```

**Comment by NickDraper** [comment]
After setting a timeout on the socket you get an error message like this:
```
Loading live data chunk 0 at 15:47:18
error receiving command NTC1 (getpar)
Unable to read NTC1 from DAE 130.246.37.30
Error in execution of algorithm MonitorLiveData:
Unable to read NTC1 from DAE  in 130.246.37.30
```
Not perfect, but much better and no hanging algrorithms

**Comment by NickDraper** [comment]
This unfortunately times out on long but otherwise successful operations as well as genuine network failures.  Darn

**Comment by NickDraper** [comment]
so a default timeout of 120 sec, but it should attempt to read it from the config service (just don't put it in the file by default)
