### ISSUE TITLE
OSIRISDiffractionReduction - No output produced in _dRange workspace

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#20763]
In Interfaces > Indirect > Diffraction, running the interface in OSIRIS diffonly mode (calling the OSIRISDiffractionReduction algorithm) and supplying a Manual D-Range, results in the _dRange output workspace having no data (all zeroes).

This can be produced with any of the Sample Run Numbers 119977-119988 (supplied as Range or List), Vanadium Run Numbers 119963-119974 and enabling Manual D-Range and supplying a list of values.

**Comment by AnthonyLim23** [comment]
cal file is osiris_041_RES10.cal

**Comment by AnthonyLim23** [comment]
3,4,5,6,7,8,9,0,1,2,3,4

**Comment by brandonhewer** [comment]
PR Merged

**Comment by brandonhewer** [comment]
PR Merged
