### ISSUE TITLE
Clean up some maths in docs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#20834]
some docs have errors in compiling maths. e.g. 
http://docs.mantidproject.org/nightly/fitfunctions/MsdGauss.html
http://docs.mantidproject.org/nightly/fitfunctions/MsdPeters.html
http://docs.mantidproject.org/nightly/fitfunctions/MsdYi.html

**Comment by AndreiSavici** [comment]
See #20833
