### ISSUE TITLE
String constraints validator documentation

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#20832]
In PR #20368, StringContainsValidator was exposed to python. However, it lacks a documentation page :(
In the release notes, there is already an entry for the validator, just need to add a link to the documentation page.

Should be part of 3.11 release

**Comment by martyngigg** [comment]
Good spot, Andrei. The builds are already done for 3.11 but it will at least get to the web documentation when it's put in master.

@KarlPalmen Can you have a look at this, please?

**Comment by KarlPalmen** [comment]
The only documentation I can find about _any_ validator is in the python course https://www.mantidproject.org/Extending_Mantid_With_Python which describes workspace validators at
https://www.mantidproject.org/Workspace_Validators and combining validators at
https://www.mantidproject.org/Combining_Validators. 

I therefore feel that this issue should from part of a project in improve documentation about _all_ validators, if we want this.

**Comment by martyngigg** [comment]
@KarlPalmen Andrei is referring to the pages at http://docs.mantidproject.org/nightly/api/python/mantid/api/index.html

As we have to fix a problem with the release notes links I will add the skeleton file for this too.

**Comment by KarlPalmen** [comment]
Found document source in ...\docs\source\api\python\mantid\api\ .

**Comment by KarlPalmen** [comment]
When I was working on  issue #19010 , I was unaware of http://docs.mantidproject.org/nightly/api/python/mantid/api/index.html and when I asked @mantid-roman where to put the documentation, he advised ``Concepts``, so I put it there. 
I found a search facility at the Python API http://docs.mantidproject.org/nightly/api/python/index.html and cannot find that documentation, when I search ``fitFunctions``.

**Comment by KarlPalmen** [comment]
A further thought is that http://docs.mantidproject.org/nightly/api/python/mantid/api/index.html is only for the C++ interface and not for any wrappers.
