### ISSUE TITLE
QT5 frequency domain analysis issue

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#20840]
Table_uilts.py line 55

You are using a method that has been removed
``` python
         version=QtCore.QSysInfo.WindowsVersion
```
in Qt5 you need to use 
``` python
QSysInfo::productVersion()
```
which should apparently return "10" for windows 10

You might also want to check 
``` python 
QSysInfo::productType()
```
which should return "windows"

**Comment by AnthonyLim23** [comment]
now its https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/utilities/table_utils.py#L144 

@Matt-Cumber could you add this to your list?
