### ISSUE TITLE
HFIR Powder Diffraction 

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#20889]
when you open HFIR Powder diffraction reduction a warning about the file location is generated. 

But, it then opens ok. When I try to load data I get an error message 

```
File "C:/Users/BTR75544/MantidInstall/scripts\HFIRPowderReduction\HfirPDReductionGUI.py", line 650, in doLoadData
    status, datafilename = self._uiDownloadDataFile(exp=expno, scan=scanno)
  File "C:/Users/BTR75544/MantidInstall/scripts\HFIRPowderReduction\HfirPDReductionGUI.py", line 2143, in _uiDownloadDataFile
    status, errmsg = urllib.downloadFile(fullurl, srcFileName)
AttributeError: 'module' object has no attribute 'downloadFile
```

**Comment by AnthonyLim23** [comment]
![image](https://user-images.githubusercontent.com/25006392/31388106-d83d412a-adc4-11e7-9106-69c35b298d4e.png)

**Comment by peterfpeterson** [comment]
There appear to be two issues
1. The warning dialog looks scary, but probably is just informational
2. The missing function on `urllib`

For the latter, I cannot easily test it, but it looks like the offending call should be replaced with `urllib.urlretrieve(fullurl, srcFileName)`
