### ISSUE TITLE
Global fitting example no longer runs

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#20948]
http://docs.mantidproject.org/v3.8.0/concepts/Fitting.html

**Comment by AnthonyLim23** [comment]
@VickieLynch I have just fixed a similar bug. The fit algorithm now returns a single object. You should have something like:

```
stats = Fit(....)
costFunctionVal= stats.OutputChi2overDoF
```

**Comment by NickDraper** [comment]
It would work in Mantid 3.8.0, but not in recent versions, but the example in more recent version has been updated in the documentation. e.g. http://docs.mantidproject.org/v3.11.0/concepts/Fitting.html

There is nothing to fix here.
