### ISSUE TITLE
Add algorithm for gravity correction for 2DWorkspaces

### ISSUE THREAD

**Issue by vreimund** [mantidproject/mantid#20963]
A general algorithm for neutron gravity correction is missing.
In particular, the ILL instrument Figaro requires gravity corrections for its reduction workflow.

The `OutputWorkspace` is a copy of the `InputWorkspace` but TOF x axis values and scattering angles are modified (counts may move to different spectra, bins may vary)

**Comment by reimundILL** [comment]
![diff](https://user-images.githubusercontent.com/19187274/46599577-fd41bc80-cae7-11e8-9f2b-b5a3f89e0b07.png)

**Comment by reimundILL** [comment]
Gravity correction with g * 300:
![factor300gc](https://user-images.githubusercontent.com/19187274/46599591-06cb2480-cae8-11e8-9969-f20dbc8ef5e8.png)

**Comment by reimundILL** [comment]
Corresponding input workspace:
![in](https://user-images.githubusercontent.com/19187274/46599640-219d9900-cae8-11e8-83bb-0ef6c1bcb672.png)
