### ISSUE TITLE
Replace self.createChildAlgorithm with simple API function calls.

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#21008]
Following PR #20668 , python algorithms can be cleaned up to use simple API without any behavioural changes.

### Platforms affected

**Comment by martyngigg** [comment]
As discussed we want to move this out of the way for Release 6 as it's just a developer tidy up and it's possible some createChildAlgorithm calls are doing something more than not just using the ADS

**Comment by joseph-torsney** [comment]
Not stale!
