### ISSUE TITLE
ISIS Reflectometry: Change reduction workspace names.

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#21004]
The Reflectometry GUI/DataProcessorWidget currently produced names with prefixes rather than suffixes. This doesn't match the behaviour of the old Reflectometry Interface.

- [ ] The instrument scientists have requested that the naming convention is changed to match the old Reflectometry Interface.
- [x] Additionally they have requested that the names of individual slices be changed to include the time period as a range.

**Comment by gemmaguest** [comment]
I'm closing this because Max has said that it's fine to keep the naming convention with prefixes rather than suffixes. This actually gives them a useful distinction between workspaces generated from the GUI, which uses prefixes, vs their own scripts, which use suffixes.
