### ISSUE TITLE
Indirect - VESUVIO - Parallelization of VesuvioCalculateMS

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#21034]
The VesuvioCalculateMS Algorithm, currently does not utilise the parallelization features in OpenMP.
Going forwards, this will be useful, for providing a significant increase in performance, when VesuvioCalculateMS is used more frequently in upcoming additions to Vesuvio analysis in Mantid.

**Comment by Mantid-Matthew** [comment]
@AnthonyLim23 Closing this as superseded by more recent discussions.
