### ISSUE TITLE
Slice viewer not disabled for workspaces with only one spectrum.

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#21087]
### Expected behaviour
It shouldn't be possible to open the slice viewer for a workspace containing only one spectrum.
Similar to how the Color Fill Plot option is disabled.

### Actual behaviour
Opening the slice viewer for a workspace with only one spectrum produces either:
- A slice viewer with a completely grey plot area. 
- In the case for workspaces generated by the old sans GUI, a crash.

### Steps to reproduce the behaviour
1. Open the old SANS GUI with the `MaskFile.txt` from `loqdemo` (ISIS sample data).
2. Select `Batch Mode`
3. Open the `batch_mode_reduction.csv` file to load the runs into the table.
4. Run 1D Reduce
5. In the workspaces dock attempt to open `74024_trans_sample_2.2_10.0` in the slice viewer.
6. Crash.

### Platforms affected
Windows 10, probably all.

**Comment by Mantid-Matthew** [comment]
Slice viewer re-write invalidates this.
