### ISSUE TITLE
Add options to preprocessor adding in SANS GUI V2

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#21097]
The old SANS GUI allows adding with several different options. There is a drop-down menu with three options each of which creates or disables other options. These options need to be maintained in the adding in the new GUI. 

This ticket needs to be done after #21096

**Comment by edwardb96** [comment]
The original implementation planned for this turned out to be incompatible with the current designs of the DataProcessorWidget and SANS GUI. PR #21221 Implements this functionality in a style similar to the old SANS GUI.
