### ISSUE TITLE
SANS Gui: Make batch mode fields editable

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#2109]
sans_feature
This issue was originally [TRAC 1262](http://trac.mantidproject.org/mantid/ticket/1262)

The batch mode table on the SANS GUI needs to be made editable so that items can be added without requiring a CSV file or errors can be more easily corrected.

**Comment by AntonPiccardoSelg** [comment]
This will not happen in the old GUI. The new GUI however does have this feature
