### ISSUE TITLE
Add Preprocessor to sans GUi to allow runs to be added from within data processor widget

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#21096]
Currently the ISIS SANS GUI V2 has no functionality to add workspaces together. The method used by the reflectometry GUI using a pre-processor has been judged to be a nice way to do this.

This ticket therefore covers implementing this pre-processor adding on the SANS GUI.

**Comment by edwardb96** [comment]
The original implementation planned for this turned out to be incompatible with the current designs of the DataProcessorWidget and SANS GUI. PR #21221 Implements this functionality in a style similar to the old SANS GUI.
