### ISSUE TITLE
Multi dataset fitting: inconsistent parameter ties displayed in function browser

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#21092]
### Expected behavior

When fixing a parameter for a single spectrum the fit parameter browser/tree should only show the fixed value when the spectrum in question is shown.

### Actual behavior

It shows it for all spectra (including those that have other constraints, e.g. ties).

### Steps to reproduce the behavior

- Load a dataset with multiple spectra (I used IRS26176)
- Add two peak functions (I used two Lorentzian)
- For all spectra tie the peak centre of the second to the peak centre of the first
- For the first spectrum only fix the peak centre of the second Lorentzian

### Platforms affected

Tested on Ubuntu 16.04

**Comment by mantid-roman** [comment]
@DanNixon What did you do exactly to set ties and fix the parameter?
