### ISSUE TITLE
Add a deprecation warning to ISIS Reflectometry (old) interface

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#21103]
We have agreement that the old ISIS reflectometry interface can be removed after 1 year, so we need to add a deprecation warning to the interface to make this plan clear to our users.

Follow the deprecation guidelines here:
http://www.mantidproject.org/Deprecate_functionality_in_Mantid#Interfaces

**Comment by gemmaguest** [comment]
We should add the deprecated warning in v3.13 and aim to remove the old GUI by March 2019. We don't know what the version number will be because it depends on when Mantid 4 will be released, so we can just put the date instead.
