### ISSUE TITLE
CalculatePaalmanPings GUI crash

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#21157]
The GUI tab crashes if a file containing a workspace group is supplied.

Steps to reproduce:
1. Navigate to Interfaces->Indirect->Corrections->CalculatePaalmanPings Tab.
2. Choose the attached nexus file in the first input file field. (first rename it to get rid of '.zip')
3. Count to 5 -> 💣 

The problem is that it tries to get the instrument from the group workspace directly.

[16658_166445_red.nxs.zip](https://github.com/mantidproject/mantid/files/1457331/16658_166445_red.nxs.zip)

**Comment by SpencerHowells** [comment]
Why would you want to run on a group? What varies for the components? Sample or temperature or what? What would the program do, scientifically, for the individual components?

**Comment by gvardany** [comment]
We agreed earlier that it should not run for a group. The issue is just to prevent the crash with a nicer error popping up. The different items in the group are for different doppler energies in our case.

**Comment by SpencerHowells** [comment]
Just checking. We already have it as Issue #19209 & I’d asked Brandon to give a message that groups cannot de used.

**Comment by gvardany** [comment]
I have forgotten about that one. It seems the same, but it can be that the same problem exists both in the algorithm and the GUI tab layer, one should test both at the end.

**Comment by SpencerHowells** [comment]
Good point. We'll do both as suggested.

**Comment by gvardany** [comment]
@SpencerHowells What is your timescale to work on this? Or should I attack this now? This is reported by a user, so it would be nice to treat it timely.

**Comment by SpencerHowells** [comment]
@brandonhewer What is the answer for Gagik?

**Comment by brandonhewer** [comment]
@gvardany Indeed, the necessary checks were supposed to be added in the original PR:
https://github.com/mantidproject/mantid/pull/20373

I don't mind taking a look at this immediately, I imagine the timescale will only be a couple of days at most.

**Comment by gvardany** [comment]
Thanks for agreeing to work on this. I would suggest to walk through all the indirect monte carlo and paalman pings algorithms and GUI tabs, and harmonise their behaviour for workspace groups. The algorithms can respond with an error explaining the reason in validation step.
