### ISSUE TITLE
Multi-dataset fitting interface: output parameters in columns

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#21173]
After a simultaneous fit create a table workspace with parameter values organised similar to the output from `PlotPeakByLogValue` algorithm. The parameters are put into columns: two columns per parameter, one column for the value and the other for the error. Each row corresponds to a dataset. The table workspace must be ready for plotting: the user selects a column and can plot it.

**Comment by SpencerHowells** [comment]
@mantid-roman Great! Thanks.
