### ISSUE TITLE
JumpFit - Plot Result and Plot Guess produce error messages

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#21204]
In the Interfaces > Indirect > Data Analysis > JumpFit interface, both plot result and plot guess produce errors (the mini-plot is therefore not updated). 

These errors follow from the result workspace not being created and added to the ADS.

**Comment by SpencerHowells** [comment]
@brandonhewer  After loading data the x-limits in the miniPlot are wrong. Can you fix as well.

**Comment by brandonhewer** [comment]
@SpencerHowells This bug seems to appear across many Data Analysis Interfaces. I'll create another issue for solving across all of them.
