### ISSUE TITLE
ISIS Powder - Add beam parameter definition

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21268]
**New feature**
**This issue will close #20892**

Its should be possible for users to define the beam parameters (shape of the beam) as this may change and is required for later analysis steps.
The proposed way to do this is to add is as an option to the abstract instrument. This information can be stored as a map:
```
beam_parameters = {width: w, 
                   height: h}
```
At present only rectangle and square beam shapes are used but this could be further updated later as required.

**Comment by ElliotAOram** [comment]
Additionally in investigating this issue. set_sample_details has almost the same implementation in `hrpd.py` `polaris.py` and`gem.py` it should be possible to move this functionality to the `abstract_inst.py` parent to avoid code duplication.

**Comment by SpencerHowells** [comment]
We’ve put the beam dimensions into the IPF. It can then be the default value in interfaces such as absorption corrections.

**Comment by ElliotAOram** [comment]
Good point Spencer, although I don't think the powder instruments use any IPFs currently. There are similar files in place however that maybe (in order to standardise things across techniques) could be candidates for becoming IPFs... I'll make a note to look into this (probably once we start looking into a GUI)
