### ISSUE TITLE
Indirect - Absorption Corrections - Apply Monte Carlo Corrections Interface

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#21316]
There is currently no interface for applying the absorption corrections created from within the Calculate Monte Carlo Absorption interface.

The ApplyPaalmanPings interface should be changed to a more general interface for applying absorption corrections.

**Comment by SpencerHowells** [comment]
@brandonhewer This Interface always uses corrections so does not need an option Use corrections. For no corrections the Subtraction Interface would be used.
