### ISSUE TITLE
ConFit Tab does not guess correctly the energy range for BASIS files

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#21323]
In the picture below the lower energy range is automatically set to zero instead of the minimum energy value. 

![screenshot](https://user-images.githubusercontent.com/1136006/33509710-fa01d8ee-d6d1-11e7-8d4c-02b45920950f.png)

**Comment by SpencerHowells** [comment]
@jmborr Is this in a recent build? It may well be 1 of the issues Brandon is sorting out.

**Comment by jmborr** [comment]
@SpencerHowells That's correct, it happens in mantid nightly, but not in the latest release

**Comment by jmborr** [comment]
corrected as part of the big overhaul of the interface
