### ISSUE TITLE
ISIS Powder Polaris PDF mode 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21350]
Having `mode="PDF"` when setting up the Polaris instrument in isis_powder should propagate the default values (such as `pdf_focused_cropping_values`) to the create_vanadium and focus methods. Additionally, it would be nice be able to enter `"pdf"` or `"PDF"` and for a warning to be displayed in the results log if the mode entered is not recognised.
we should check it is still possible to override these in create_vanadium/focus e.g.:
* set mode of inst to pdf
* run vanadium with in rietveld mode
* run focus in pdf using default instrument values from set up

**Comment by josephframsay** [comment]
coupled with this is the uncomfortable truth that if we do `focus(mode="pdf", ...)` (as opposed to `"PDF"`), the rietveld parameters are used
