### ISSUE TITLE
Cut diagnosis MaxEnt output workspaces to shown only up to converged  

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#21392]
Change Maxent to output EvolChi and EvolAngle to

* Only to up convergence or if fails until max number of iterations
* With x-axis label 'number of iterations' instead of other label such as 'Time'
* With y-axis likewise showing what is plotted instead of e.g. 'asymmetry'
* For all usage examples add check on number of iterations
* Add unit test where reach max number of iterations, (warning to user that did not converge)

Noticed while testing #21079

**Comment by AnthonyLim23** [comment]
I have had a quick look at this and there are two options:

1. We keep the code very similar to as it is now (generates a ws with enough space for every iteration). Then at the end we trim the workspace down.

2. We only define the output workspace at the end. We create with the correct data and use vectors to determine the length etc. 

I personally like the second option best.
