### ISSUE TITLE
Output Notebook doesn't work on SANS v2 GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#21519]
On the new SANS GUI, the IPython Notebook generated when you tick Output Notebook gives an error when you try to run it about `SANSGuiDataProcessorAlgorithm` not being found. We should either fix this, or disable the option (longer term it would be good to be able to remove unused functionality from the interface, but in the short term we could just give a 'not implemented' error).

The output generated by this option is probably not that useful for SANS users anyway, so disabling it is probably the best bet, as it is not currently in use.  Alternatively we could look at using the `GenerateIPythonNotebook` algorithm instead, but this would require a bit of work because it does not work on a batch/group of workspaces at the moment, and the output includes e.g. full path names of files.

### Steps to reproduce the behavior
- Open the `ISIS SANS v2 experimental` interface
- Load the MaskFile.txt and batch_mode_reduction.csv inputs from the sample data.
- Tick `Output Notebook` and click `Process`
- Launch the generated notebook in IPython and try to run it.

### Platforms affected
All

**Comment by TTitcombe** [comment]
no longer an issue as SANS has switched to using JobTreeView widget
