### ISSUE TITLE
Sample transmission using Monte Carlo

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#21534]
There is a user request for an algorithm which calculates the sample transmission using [`MonteCarloAbsoprtion`](http://docs.mantidproject.org/nightly/algorithms/MonteCarloAbsorption-v1.html). This could be done using a fake instrument with a single detector in the beam after the sample and feeding the workspace to `MonteCarloAbsorption`.

**Comment by SpencerHowells** [comment]
@soininen good idea! Could update the existing interface. Also use algo SimpleShapeMonteCarloAbsorption.
