### ISSUE TITLE
Rebin data by 2 or more points

### ISSUE THREAD

**Issue by MargheF** [mantidproject/mantid#21547]
"Rebin" algorithm in Mantid rebins the data by indicating a width in the "params". What if the experimental points are not equidistant. Thus, rebin calculation would be only possible by indicating 
a number of points to rebin. Is it possible to create this feature in Mantid algorithm?

**Comment by SimonHeybrock** [comment]
@MargheF `Rebin` allows for more flexible points as well, see (the last) example in http://docs.mantidproject.org/nightly/algorithms/Rebin-v1.html#example-rebin-param-strings.

More precise control of the bin edges should be possible by using `RebinToWorkspace` (see http://docs.mantidproject.org/nightly/algorithms/RebinToWorkspace-v1.html). A corresponding workspace with custom bin edges could for example be created with `CreateWorkspace`.
