### ISSUE TITLE
LoadSampleShape algorithm extended to support OFF Geometry format

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#21553]
Make the LoadShape algorithm in #12828 also support loading the another triangular based mesh geometry format, here the OFF format. https://en.wikipedia.org/wiki/OFF_(file_format)

In this issue make LoadShape support the know wikipedia format. A separate will be created to handle the new proposed nexus OFF format.

**Comment by matthew-d-jones** [comment]
I can provide more information and other examples when you get to this, but here is a simple, example NeXus file containing an icosahedral sample:
https://www.dropbox.com/s/l0vywkf3ujnptyw/icosahedron_sample_example.nxs?dl=0
![icosahedron](https://user-images.githubusercontent.com/13455433/34945408-2bee7762-f9fb-11e7-96ba-bf1e03461e56.png)

**Comment by KarlPalmen** [comment]
I note that the OFF format in the Nexus file provided by @matthew-d-jones differs from the text format described in Wikipedia. It has 3 lists: 
* A list of vertices
* A list of vertex indices referring to previous list
* A list of indices referring to previous list giving start of each face in that list

**Comment by OwenArnold** [comment]
@KarlPalmen regarding the question you left on #21369. The nexus geometry parsing code is not yet ready to be merged into master, however if you wish to branch from it, you can go-ahead and do so. Note that `NexusGeometryParser` is designed to create a complete instrument geometry. That being said, you should have a look at `NexusGeometryParser::parseNexusShape` as this will read the H5 Group and return an IObject for the shape.

**Comment by KarlPalmen** [comment]
This would require `NexusGeometryParser::parseNexusShape` to be added to `NexusGeometryParser.h` alongside `NexusGeometryParser::createInstrument`?

**Comment by OwenArnold** [comment]
@KarlPalmen unless you are planning on starting this immediately. I would like to think a bit longer about how to sensibly arrange the Nexus Geometry code. What are your timescales? When do you need this by?

**Comment by KarlPalmen** [comment]
Timescale is about 1 week. I'm waiting for this issue here to be reviewed and would respond to such a review first.

**Comment by OwenArnold** [comment]
@KarlPalmen I've made some quick changes to get you going. See https://github.com/ScreamingUdder/mantid/blob/c5f4a11251eb8b7bf2761809b81d12952d85c17e/Framework/NexusGeometry/inc/MantidNexusGeometry/NexusShapeFactory.h#L56-L59 

You would still need to work off my branch.

**Comment by KarlPalmen** [comment]
This work requires the branch of #12828 merging into its base branch, because it is an extension of the `LoadShape` algorithm, which has been created there.

**Comment by KarlPalmen** [comment]
Once such merger has occurred, I'll add a new function `readOFFshape` to `LoadShape` that takes the Nexus file pointer as argument and goes to the sample, opens it, then to the shape opens it and reads the three data blocks, then after checking them calls `nexusShapeFactory.createFromOFFMesh` with the these 3 data blocks in the arguments.

**Comment by OwenArnold** [comment]
@KarlPalmen I would check with @Anders-Markvardsen what his intention is with this issue, as he has authored the description. I may be that this `LoadShape` algorithm is required to read a single shape specified in a single OFF file and apply it somewhere to an existing component in an existing instrument. In other words, Anders might intend that this algorithm does not read the hdf5 Nexus Geometry files.

**Comment by KarlPalmen** [comment]
OK I'll send him an E-mail to check this. This example file provided by @matthew-d-jones is Nexus file, that is like an ISIS nexus file except it has an instrument with just a name and a sample containing the shape in 3 data blocks that apparently match the 3 arguments of `nexusShapeFactory.createFromOFFMesh`.

**Comment by Anders-Markvardsen** [comment]
Hi @KarlPalmen. Based on the discussion above I would limit the scope of this issue to extend loadshape to read a single OFF file and the OFF format as described on wikipedia. 

As a side, from Karl's comment above, @matthew-d-jones I find it worrying that the OFF format used in nexus files differs from that of the OFF format on wikipedia. Is there a good reason for this?

**Comment by matthew-d-jones** [comment]
@Anders-Markvardsen @KarlPalmen 
The issue title mentions the NeXus OFF-based format and the description instead mentions the OFF format, this is confusing.

The NeXus `NXoff_geometry` is based on the OFF format and is very close to it. The difference is an extra dataset which indexes into a flattened dataset containing the vertices for each of the faces. This avoids the need for a ragged-edged faces dataset, which is desirable as ragged-edged datasets are difficult to work with and best avoided in HDF5 files.
This will be described in the NeXus manual (there is a PR waiting), here is a pdf of the design page, section 1.2.2.3 is the relevant one.
[nexus_manual.pdf](https://github.com/mantidproject/mantid/files/1833088/nexus_manual.pdf)

**Comment by KarlPalmen** [comment]
It was my guess that faces of varying number of vertices could be supported, but ragged datasets were to be avoided.

**Comment by KarlPalmen** [comment]
It would be much quicker for me to load an ASCII OFF file. I have not yet figured out how to use the Nexus/HDF objects to load a Nexus file. Code in other Nexus loading algorithms is too complicated to be helpful.

**Comment by KarlPalmen** [comment]
Pull request #22016 needs merging, before coding work on this issue can proceed.
