### ISSUE TITLE
MaxEnt: allow calculated data to be modified and one reconstruction for all spectra 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#21577]
Extend this algorithm to allow the calculated data (from the Fourier transform of the image) to be modified before comparing with the observed data in the chi-squared expression.

Introduce two three algorithm properties:

* DataConstAdj. Complex array with dimensions: number of spectra times number of data 
* DataLinearAdj. Complex array with dimensions: number of spectra times number of data 
* PerSpectrumReconstruction. Boolean which default to true

Using the notation in MaxEnt then d_m^c is the calculated data for the m'th data point. To refer to the m'th data point for the k'th spectrum then refer to this as d_k(m)^c. Then adjust these as follows before calculating chi-squared:

modified_d_k(m)^c = DataConstAdj[k,m] + d_k(m)^c * DataLinearAdj[k,m]

When PerSpectrumReconstruction = True the behaviour is as is currently the case. When PerSpectrumReconstruction = False one image is used to fit against all spectra simultaniously, for an example of this see chi-squared expression for MuonMaxent. The chi^2 value is then:

chi^2 = \sum_{k,m} \frac{ ( d_k(m) - modified_d_k(m) )^2}{\sigma_k(m)^2 }

The reconstructed workspace (time domain) should always return N spectra.

**Comment by KarlPalmen** [comment]
Dear @Anders-Markvardsen & @AnthonyLim23   Should `PerSpectrumReconstruction` be `perSpectrumImage`, because if false, it would still per spectrum reconstruction, but using one image and with reconstructions differening only from each other by application of the adjustments?

**Comment by AnthonyLim23** [comment]
yes, I think `perSpectrumImage` is a better name

**Comment by KarlPalmen** [comment]
I've thought more carefully about this and realise I still do not fully understand what is required wher perSpectrumImage is set false. In particular I don't understand what is meant by "one image is used to fit against all spectra simultaniously". Does this mean a single fitting and that reconstructed images are then created by apply the adjustments for each spectrum afterwards? Or does it mean a separate fitting is done with each spectrum with the image somehow made the same. I never grasped the MuonMaxEnt algorithm.

**Comment by KarlPalmen** [comment]
It looks like the Chi squared is calculated as though to spectra were concatenated, but the image is calculated with the sum of a spectra. This cannot be handled by the existing `MaxentCalculator` class.

**Comment by KarlPalmen** [comment]
A talk with Anders confirms that the Chi square is calculated as though the spectra were concatenated into one spectrum.

**Comment by KarlPalmen** [comment]
I'll go ahead of plan to create new class to run in place of `MaxentTransformFourier' and inheriting from it. The class will take data as concatenated spectra, while having a single image. The spectra in data will be added together when transforming to image. When transforming to data a concatenated copies of the reconstructed data will be created (one fpr each spectrum) and the adjustements will be applied to them.

The spectra in the data are concatenated so they can be handled by the existing Chi squared calculations in `MaxentCalculator`.
