### ISSUE TITLE
Create MatrixWorkspace Viewer for Workbench

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#21593]
Add a viewer widget for displaying the data of a `MatrixWorkspace`. The concept should be similar to that found in `MantidPlot` but its design should follow the MVP pattern as done for various widgets in `mantidqt.widgets`.

The widget should be developed as part of the `mantidqt` package and be independent of the workbench. It should be possible to show the widget from a standalone python script as in [`samplelogs`](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/samplelogs/__init__.py).

The workbench will access the functionality through the workspace context menu in [workspacewidget](https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/plugins/workspacewidget.py).

----------------

Requirements:
- [x] Window title is `<workspace_name> - Mantid`
- [x] Display X/Y/E in tabs
- [x] Spectra for monitors and masked detectors should be in different colours:
  - Monitors: banana yellow
  - Masked spectra: grey
- [x] Row labels are `<id>-<spectra number>`
- [x] Column labels are `<id>-<bin value+unit>`
- [x] Monitor spectra mouse over shows text `This is a monitor.`, masked spectra mouse over shows `This is a masked spectrum`
- [x] Right click on row has `Copy` & `View detectors table`
  - [x] Copy
  - [x] View detectors table
- [x] Icons for Copy & View
- ~Action for `View Detectors Table`?~

**Comment by DTasev** [comment]
The action performed on `View detectors table` needs to be discussed -> MantidPlot opens a new table. What should the MatrixWorkspaceDisplay do? Two cases need to be handled -> running standalone and running within the workbench. Additionally, the workbench will be able to open the detectors table as well through `Show Detectors` context option in the workspace viewer
