### ISSUE TITLE
Add ILL training materials

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#21605]
This PR will add a section in the sphinx documentation for ILL training sessions. There should be four separate issues following this one, with branches based off the ones for this issue to cover the planned training, similar to the courses below.

[Mantid Basic Course](http://www.mantidproject.org/Mantid_Basic_Course)
[Python In Mantid](http://www.mantidproject.org/Python_In_Mantid)

Approximate plan:

**1. Introduction**
* Structure for training session
* Downloading and installing (release, nightly), setting up data directories, usage data, supported platforms
* Sources of help - CS group, online forums, training materials on website, algorithm documentation, API documentation
* Bug reporting - please do it!
* Structure of Mantid - Python API written in C++/Python, MantidPlot as current GUI, new workbench coming eventually

**2. Basics of MantidPlot**
- [x] Loading data from NeXus files, loading multiple files (important for ILL)
- [x] Viewing the workspace data, monitors, masking
- [x] 1D plotting of a spectrum/spectra or a bin
- [x] 2D plots (color fill plot, spectrum viewer)
- [x] InstrumentViewer
- [x] Plotting multiple curves (overplot, tile)

**3. More on Mantid(Plot) - Verena**
* Workspaces - basic types, historgram/point data, count/distribution
* Workspace groups 
* Detector table - spectrum numbers, workspace indexes, detector IDs
* Algorithms - how to use (input validation, workspace/file selection), dialogs, workspace history
* Saving out workspaces to NeXus, other formats
* Interfaces - where to find, fitting as example?

**4. Python and Mantid - @soininen**
* How to use - from mantid.simpleapi import *`, script window
* Running an algorithm
* Generating a script from history
* Getting workspaces in MantidPlot `mtd['name']`
* Iterating over workspaces in a workspace group
* Very basic workspaces data access via NumPy arrays
* Possibility to write own algorithms (mention only)

**Comment by gvardany** [comment]
@soininen @verena I have just added a bullet to your parts concerning workspace groups, I think this is also important to teach.

**Comment by reimundILL** [comment]
`Generating a script from history` can be covered when talking about workspace histories. It is just the clipboard content containing Python code.
