### ISSUE TITLE
FitFunction TeixeiraWater lacks Planck constant

### ISSUE THREAD

**Issue by MargheF** [mantidproject/mantid#21619]
FitFunction "TeixeiraWater" models the Q dependence of the QENS line width (Gamma (hwhm)) as
hwhm = xvals * xvals * length / (tau * (1 + xvals * xvals * length))
where xvals is Q and length is L^2

Shouldn't be like that:
hwhm = hbar * xvals * xvals * length / (tau * (6 + xvals * xvals * length)) ?

HWHM contains hbar as it's presented in FitFunction "TeixeiraWaterSQE".
Also, if diffusion coefficient D=L^2/(6*tau), then 6 goes in place of 1.

**Comment by jmborr** [comment]
@samueljackson92 I think you wrote this function, right? Could you please address this issue?

**Comment by samueljackson92** [comment]
I think I added it, but that it was originally written by @SpencerHowells, who may want to comment? I agree that it does look like the diffusion constant is incorrect here.

**Comment by MargheF** [comment]
A lack of Planck constant is possible to overcome by dividing Gamma into hbar. However, as diffusion coefficient D=L^2/(6*tau), then 6 goes in place of 1 in original:
hwhm = xvals * xvals * length / (tau * (1 + xvals * xvals * length))
Could you, please, modify this? I am not allowed to change the script.
Also, is the fitting parameter "L" a length (i.e. square root of the "length" in the formula)?

**Comment by SpencerHowells** [comment]
@MargheF @I have contacted our QENS scientists to confirm this is what they want. Then we can update.

**Comment by MargheF** [comment]
@samueljackson92 Thank you for fixing definition of fit function. **Is the change already effective?** Sorry, I am not very good with programming; could you, please, give me a hint on this line:
expected = [3.74985938e-05,   3.73599004e-03,   2.72727273e-01,   9.74025974e-01]
**What's "expected"?** Was hbar introduced to the fit function? Also, fitting parameter "L" is square root of length**2 or is it actually length**2?
Thank you very much!
