### ISSUE TITLE
Incomplete Algorithm time reporting.

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#21626]
`Algorithm` does not include property validation and other setup code in the reported time. This can lead to large confusing discrepancies between observed and logged time.

**Comment by OwenArnold** [comment]
@SimonHeybrock I think the problem you describe is related to this #20445.

**Comment by SimonHeybrock** [comment]
@OwenArnold I tried the example and the reported time still looks not complete. Probably due to things happening in `simpleapi` before the C++ `Algorithm::execute` is called. So I think I cannot claim to have fixed that issue (only partially).

**Comment by SimonHeybrock** [comment]
@OwenArnold Now this is weird. If I set the log level to `information`, the reported timings of `CreateWorkspace` look actually correct. However, setting it to `debug` Mantid freezes for about 2 minutes to execute the script, but does not report the time. Note that there is basically no debug output, so I have no idea why it suddenly takes so long?

**Comment by SimonHeybrock** [comment]
Correction: There are basically no debug output *lines*, but there are a couple very long ones containing the unwrapped `range(1000000)`. Apparently this is causing the issue.

Conclusion: I am fixing #20445, the long runtime with debug output is unrelated (and probably parts of the problem reported in #20443).

**Comment by OwenArnold** [comment]
Yes, looking at other algorithms. The sum of timings match the reported total. I do not see this for `CreateMDWorkspace`
