### ISSUE TITLE
Workbench doesn't build with latest sip version on OSX 10.12 

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#21656]
### Expected behavior
Workbench builds according to wiki directions.

### Actual behavior
Building fails in `make`, with the error

```
sip: /Users/soininen/Sources/mantid/qt/python/mantidqtpython/mantidqtpython_def.sip:591: %Docstring already given for class
```

### Steps to reproduce the behavior
Update to the latest version of `sip` and switch to this version with `brew`
```
brew install sip --build-from-source
brew switch sip 9.14.7
```

### Platforms affected
OSX 10.12

**Comment by martyngigg** [comment]
Fixed in #21676
