### ISSUE TITLE
Function browser in Convfit does not show all fit parameters for the background

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#21705]
(In Mantid nightly version)

Here's a snapshot of the `convfit` tab selecting a `Fit Linear` background:

![screenshot](https://user-images.githubusercontent.com/1136006/35887873-c50b74d0-0b63-11e8-9ae6-5c5461c5b61a.png)

In the function browser, parameter `A0` is shown, but parameter `A1` is missing. User cannot change its value.

**Comment by SpencerHowells** [comment]
@jmborr We are doing a complete re-write of the DataAnalysis interface PR #21607

**Comment by jmborr** [comment]
This is being addressed in PR #21607
