### ISSUE TITLE
Help: Document comparing Multiple scattering absorption (and other absorption) corrections in Mantid

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#21701]
Anders made a start on something similar to this with a summer student last year, get what you can from him.
#20072

**Comment by SpencerHowells** [comment]
This MUST contain the Monte Carlo absorption corrections & Pahlman-Pings formulism

**Comment by peterfpeterson** [comment]
The multiple scattering version is at http://docs.mantidproject.org/nightly/concepts/MultipleScattering.html
