### ISSUE TITLE
Incorrect angle used in conversion to Q in RRO

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#21742]
In `ReflectometryReductionOne2`, when we do summation in lambda we use [GroupDetectors](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryWorkflowBase2.cpp#L408) to sum in lambda across a set of detectors of interest. 

The resulting summed workspace has a single spectrum with detector angle taken from the centre of the detectors of interest. The range of detectors of interest is often centered on the scattering angle `twoTheta`, but not always, so the final detector angle is somewhat arbitrary. 

This angle gets used by `ConvertUnits` in the conversion to `Q` and therefore we get different X values depending on the set of detectors used. Instead, the correct angle to use in the conversion to `Q` is half the scattering angle `twoTheta`. Even when the range of detectors is notionally centered on the "twoTheta pixel", the pixel's centre may not be exactly at `twoTheta` anyway, so the angle is still slightly wrong.

There are a few approaches we could take, but from discussion with scientists we have agreed to correct the position of the detector group as an extra step in `ReflectometryReductionOne`. It should be corrected to the angle provided by the `ThetaIn` property, if this is given. If `ThetaIn` is not given, no correction should be done. Ideally this correction would be done in a separate algorithm because it would also be useful for ILL.

Note that this should only be done when summing in lambda. The key steps of the `ReflectometryReductionOne` algorithm when summing in lambda start [here](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/ReflectometryReductionOne2.cpp#L606).  `makeDetectorWS` calls `GroupDetectors`. Then some normalisations by monitors and transmission runs are done. The new correction should be done after these normalisations, before the result of `makeIvsLam` is returned. The result of this function is then converted to Q using `ConvertUnits`.

Note that we have an algorithm called `SpecularReflectionPositionCorrect` which corrects detector positions, but this works on instrument component names so I don't think it can be used for a detector group. It may be useful to take a look at it, though.

## To test
```
import math

def printResults(name, thetaIn):
  ws=mtd[name]
  print "Expected theta:  ", thetaIn
  print "Actual theta:    ", ws.detectorTwoTheta(ws.getDetector(0)) * 180 / math.pi / 2

# OFFSPEC example - TOF workspace detectors are NOT in the correct position on load so ARE corrected by RROA
LoadISISNexus(Filename='OFFSPEC44684', OutputWorkspace='TOF_44684')
LoadISISNexus(Filename='OFFSPEC44683', OutputWorkspace='TRANS_44683')
ReflectometryReductionOneAuto(InputWorkspace='TOF_44684', ProcessingInstructions='390-410', ThetaIn=0.3, CorrectDetectors='1', DetectorCorrectionType='RotateAroundSample', WavelengthMin=1.2, WavelengthMax=14, I0MonitorIndex=1, MonitorBackgroundWavelengthMin=15, MonitorBackgroundWavelengthMax=20, MonitorIntegrationWavelengthMin=2, MonitorIntegrationWavelengthMax=14, FirstTransmissionRun='TRANS_44683', MomentumTransferStep=0.02, ScaleFactor=1, OutputWorkspaceBinned='IvsQ_binned_44684', OutputWorkspace='IvsQ_44684', OutputWorkspaceWavelength='IvsLam_44684')
printResults('IvsQ_binned_44684', 0.3)

# INTER example - TOF workspace detectors ARE in the correct position on load so are NOT corrected by RROA
LoadISISNexus(Filename='INTER00043583', OutputWorkspace='TOF_43583')
ReflectometryReductionOneAuto(InputWorkspace='TOF_43583', CorrectDetectors='0', AnalysisMode='MultiDetectorAnalysis', ProcessingInstructions='45-69', ThetaIn=1.3, MomentumTransferStep=-0.0001, ScaleFactor=1, OutputWorkspaceBinned='IvsQ_binned_43583', OutputWorkspace='IvsQ_43583', OutputWorkspaceWavelength='IvsLam_43583')
printResults('IvsQ_binned_43583', 1.3)
```

**Comment by SimonHeybrock** [comment]
Note sure if and how this is relevant for what you discuss here, but not that `twoTheta` obtained from `SpectrumInfo` is the *average twoTheta*, NOT the *twoTheta of the average*. That is, if you have a group of two detectors at (x,y,z) and (-x,y,z) the `twoTheta` of the group is NOT zero, as one could expect from looking at the average position (0,y,z).
