### ISSUE TITLE
Filtering of monitor events broken in LoadEventNexus

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#21755]
It appears that monitor events are no longer filtered by time if that is requested. I think this was broken in #15667. The old behaviour used the same time filtering for the main data and monitors. Now that `LoadNexusMonitors` is doing the loading it ignores the filter times.

In addition the 4 properties `FilterMonByTofMin`/`FilterMonByTofMax`/`FilterMonByTimeStart`/`FilterMonByTimeEnd` do not seem to do anything at all in the code.

Finally,  ticking the option `MonitorAsEvents` & `LoadEventMonitors` results in zero events in the monitor workspace - these options are also quite confusing in how they are supposed to related to each other. Should `MonitorAsEvents` be deprecated?

### Expected behavior

```python
LoadEventNexus(Filename='/home/dmn58364/Code/mantidproject/mantid/builds/debug/ExternalData/Testing/Data/SystemTest/LET00006278.nxs', OutputWorkspace='LET00006278', LoadMonitors=True, MonitorsLoadOnly="Events")
FilterByTime(InputWorkspace='LET00006278_monitors', OutputWorkspace='LET00006278_monitors',
StartTime=0, StopTime=60)
```

should be equivalent to:

```python
LoadEventNexus(Filename='/home/dmn58364/Code/mantidproject/mantid/builds/debug/ExternalData/Testing/Data/SystemTest/LET00006278.nxs', OutputWorkspace='LET00006278', LoadMonitors=True,  MonitorsLoadOnly="Events", FilterByTimeStart=0, FilterByTimeStop=60)
```

### Actual behavior

The number of events in the monitor workspace remains constant regardless of the filtering options. I think by default the monitors should be filtered by the same time as main data *unless* one of the `FilterMon*` options is provided.

**Comment by martyngigg** [comment]
cc @peterfpeterson

**Comment by NickDraper** [comment]
@wdzhou If this is actively being worked on and is likely to be available in the next few days then move this back to 3.12

**Comment by NickDraper** [comment]
Neither  high priority under the new guidelines, or in progress under anyone's definition

**Comment by NickDraper** [comment]
This has been superceeded by the work done by @peterfpeterson

**Comment by peterfpeterson** [comment]
This is still needed. #22606 did not add this functionality back into `LoadNexusMonitors`.
