### ISSUE TITLE
Catalog search on date range fails

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#21770]
### Expected behavior
Catalog search on a date range should work

### Actual behavior
I got an unexpected exception "Error interpreting string as a date/time" when doing a catalog search on a date range in the nightly build (3.11.20180214.1811). It seems ok in v3.11.0.

![catalog_search_crash](https://user-images.githubusercontent.com/12895056/36319567-3b813ff8-133b-11e8-902b-1b754494ff6a.png)

### Steps to reproduce the behavior
- From the Catalog menu, log in
- From the Catalog menu, select Search
- Enter the instrument INTER and the date range 01/02/2017 to 13/02/2017
- Click Search. Mantid reports an unexpected exception.

### Platforms affected
Ubuntu 16.04, maybe others

**Comment by peterfpeterson** [comment]
If the catalog search goes through python, this is definitely an issue resulting from #21322. Changing the string to something that is [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) will likely fix this.
