### ISSUE TITLE
Documentation updates from dev meeting

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#21786]
### Date stamp at bottom of algorithm page
* Source date
* Docs date

### Documentation link
* The link at the top of each page should bring you to http://docs.mantidproject.org/nightly/

### Clean up  http://docs.mantidproject.org/nightly/ 
* Beginners guides
* Examples
* Concepts
* Low-res figures

### NB
*I have been going carefully through many of the examples and tutorials recently and I think that there is a **much** larger issue around obsolete/unfindable documentation. I hope that I can carry on with this beyond the release of 3.12!

**Comment by DanNixon** [comment]
I have the source Git timestamp working, let me know what format you want it displayed in and I'll have a PR ready.

**Comment by keeeto** [comment]
Oh, that's much better than the one I put it, which I think is just when Sphinx last built. I already made a PR on this. Do you want to update the existing PR, or put in a new one? 

I went with standard %b %d, %Y (Month day, Year) format.

**Comment by DanNixon** [comment]
I can do it as a separate one if you like.

Note mine does the date of the last commit that edited algorithm, fit function, etc sources for displaying in the source links at the bottom of the pages.

I did try and do a similar one for the documentation pages themselves that could be applied to all documentation pages but didn't get too far with it.

**Comment by keeeto** [comment]
That sounds great. I wouldn't worry about the documentation too much. Note Karl's contention with the date formatting on the PR. We will go with '%Y-%m-%d' (YYYY-mm-dd) format instead.

**Comment by DanNixon** [comment]
Cool, I'll get it done next week now.
