### ISSUE TITLE
Fix Monitor Background Colour in the MantidPlot Matrix View

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#21821]
PR  #21668 causes the MatrixView to shade the cells containing monitor data with a black colour, the same colour as the text within them. The data table view should be modified to shade the cells with a lighter colour whilst keeping the tooltips visible.

## Platforms
Linux only.

**Comment by gvardany** [comment]
Seems this is my bad at PR #16939

**Comment by gvardany** [comment]
I wonder if this depends on some linux configurations, I just tried with Ubuntu 16, the monitors show up fine.
