### ISSUE TITLE
Tie/fix/constrain in multi fitting

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#21829]
In the multi fitting function browser (muon and general) adding a tie/constraint/fix will be added to all of the workspaces (even if it is not global)

**Comment by NickDraper** [comment]
@AnthonyLim23 @brandonhewer As the two biggest users of multidata fitting we need some input here as to what the desired solution should be.

**Comment by AnthonyLim23** [comment]
I just had a chat with @brandonhewer about it. We think that:

1. If you tie/fix/constrain in multi fitting it should only apply to the current workspace (unless it is global) 
2. If you want to tie/fix/constrain all of them without making it global then to use the dialog box you get from clicking "..."
