### ISSUE TITLE
Indirect - CalculateMCAbsorption Interface - Incorrect structure

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#21870]
The structure of the Indirect > Interfaces > Corrections > CalculateMCAbsorption interface is currently not as intended:
- In the ```Beam Details``` group box, the Height should be on the left, Width on the right
- In the ```Shape Details``` group box, the Sample Height should be on the first line for all shapes

**Comment by SpencerHowells** [comment]
@brandonhewer for cylinder inner radius of outer cylinder is outer radius of sample. For annulus outer radius of inner cylinder is inner radius of sample & inner radius of outer cylinder is outer radius of sample.

**Comment by martyngigg** [comment]
Closed with merge of #21928
