### ISSUE TITLE
Indirect - Abins - Documentation is missing references

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#21899]
Currently, the Abins documentation is missing references.

The following pages:
http://docs.mantidproject.org/nightly/algorithms/Abins-v1.html
http://docs.mantidproject.org/nightly/concepts/DynamicalStructureFactorFromAbInitio.html#dynamicalstructurefactorfromabinitio

Require the following to be stated:
```
If abINS is used as part of your data analysis routines, please cite the following reference:
K. Dymkowski, S. F. Parker, F. Fernandez-Alonso and S. Mukhopadhyay,  “AbINS: The modern software for INS interpretation” , Physica B, doi:10.1016/j.physb.2018.02.034 (2018).
```

**Comment by NickDraper** [comment]
I assume this PR closed this issue
