### ISSUE TITLE
Tooltip background colour is too dark on RHEL7

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#21921]
This was introduced by #21668 and #21832

Release is fine
![tooltip_3 11](https://user-images.githubusercontent.com/5595210/36860296-da147cbc-1d4e-11e8-8078-6a600413ed8f.png)

Nightly is unreadable
![tooltip_nightly](https://user-images.githubusercontent.com/5595210/36860295-da084a8c-1d4e-11e8-8d5e-98a53c1f5920.png)

**Comment by NickDraper** [comment]
@mantidproject/gatekeepers  Just a reminder, now we are on the release branch Fixes or closes does NOT close the associated issue when you merge the pull request.
Can everyone try to close the issue manually when merging PR's for the release branch.
