### ISSUE TITLE
Cannot plot log value in Filter-Events GUI

### ISSUE THREAD

**Issue by SimonHeybrock** [mantidproject/mantid#21935]
In the `Filter Events` interface:
1. Load file (e.g, `CNCS_7860_event.nxs` from the traning course data), click `Use`.
2. Select an item in `Sample Log` drop down menu, click `Plot`:

```
Traceback (most recent call last):
File "/opt/mantidnightly/scripts/FilterEvents/eventFilterGUI.py", line 710, in plotLogValue
    t0ns = t0.totalNanoseconds()
AttributeError: 'numpy.datetime64' object has no attribute 'totalNanoseconds'
```

OS: Ubuntu 16.04.

**Comment by NickDraper** [comment]
@peterfpeterson Is ther someone in the US that can take a look at this?

**Comment by peterfpeterson** [comment]
@AndreiSavici is this something that could be "easily" fixed using the new log-plotting code that just got merged in?
