### ISSUE TITLE
Pearl Focus runs issue

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21937]
Nick Funnell reports a difference between the old PEARL focusing routines vs the new ones implemented in ISIS_Powder.
The initial estimation of the origin of the difference is the vanadium normalisation.
The changes made in this issue will most likely involve updating the system tests

**Comment by NickDraper** [comment]
Waiting for input from Nick Funnell

**Comment by ElliotAOram** [comment]
This is believed to be an input issue rather than something that we are required to change. @josephframsay is checking this with Nick Funnell and will close this issue if this is the case.

**Comment by josephframsay** [comment]
As far as I can tell, this issue came up because absorption corrections had not been applied to the vanadium. Will reopen if the problem persists for Nick, but I think this is probably a non-issue
