### ISSUE TITLE
Grouping tab in FDA

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#21957]
add a grouping tab to the FDA. This may require the load, save and clear grouping to become algorithms.

**Comment by AnthonyLim23** [comment]
widget 1:
[loadGrouping.pdf](https://github.com/mantidproject/mantid/files/2327311/loadGrouping.pdf)

widget 2:
[groupTable.pdf](https://github.com/mantidproject/mantid/files/2327330/groupTable.pdf)

widget 3:
[pairTable.pdf](https://github.com/mantidproject/mantid/files/2327351/pairTable.pdf)

**Comment by AnthonyLim23** [comment]
changes to above designs:

1. the guess alpha button will be inside the alpha cell's of the table
2. At the bottom of the grouping tab will be an update all button

**Comment by TWJubb** [comment]
![groupingtab 2](https://user-images.githubusercontent.com/33163693/45553330-86d4d600-b82b-11e8-8f14-3e85fa28905f.png)

**Comment by TWJubb** [comment]
Current state of the grouping tab; the "Update All" button is not yet implemented (as it requires new algorithms to be completed, see #23407). However the tables should function as per the current interface.
