### ISSUE TITLE
ISIS SANS GUI v2 Diagnostics: Incorrect detector name in workspace name

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#21976]
Discovered during testing #21865. This is not critical.

The output workspace produced from the diagnostic integral procedures have the internal name of the detector rather than the more common name displayed in the detector selection box as shown in the following image: 

![screenshot from 2018-03-07 11-00-54](https://user-images.githubusercontent.com/733773/37089033-308104c4-21f7-11e8-9166-6eff7d0a11a8.png)

To reproduce:
* open ISIS SANS v2
* select SANS2D
* load a user file
* switch to the diagnostics tab
* enter a run number
* click any of the integral buttons

**Comment by Mantid-Matthew** [comment]
This is done
