### ISSUE TITLE
ISIS SANS Gui v2: Sum runs list displays the incorrect number

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#21970]
### Expected behavior

On ISIS SANS GUI v2 typing "74044,74045" into the Sums box should produce a list of these 2 entries.

### Actual behavior

74044 is displayed twice but the hover text suggests the second points at the correct file:

![screenshot from 2018-03-06 17-06-24](https://user-images.githubusercontent.com/733773/37046814-241377f8-2161-11e8-8b34-7c17606d2dac.png)

### Steps to reproduce the behavior

* Open ISIS SANS GUI v2
* Go to Sum Runs tab
* Enter "74044,74045" and press "Add"

### Platforms affected

All

**Comment by Mantid-Matthew** [comment]
This was an issue with the file provided for testing whereby the 74045 data set provided was actually 74044 just renamed.
