### ISSUE TITLE
ISIS SANS v2: Diagnostics hangs if user file is not for the correct instrument

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#21977]
Discovered during testing #21865. This is not critical for this 3.12.

If the loaded user file does not match the instrument selected then the diagnostics hangs the GUI while processing.

To reproduce:

* open ISIS SANS v2
* select LOQ instrument
* load user file "USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger_REAR.txt"
* switch to the diagnostics tab
* enter a LOQ run number
* click any of the integral buttons

**Comment by TTitcombe** [comment]
PR #24128 determines instrument from user file, so you cannot have a discrepancy between selected instrument and user file instrument
