### ISSUE TITLE
ISIS Indirect Unscripted Testing :: Data Reduction > Calibration

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21979]
* If you click `Plot Result` after checking `Create RES File` option with input file of `iris26173`, you get the following error message:
 
![image](https://user-images.githubusercontent.com/13132128/37035279-f517c304-2143-11e8-8227-61d33dcd0937.png)

**Comment by brandonhewer** [comment]
Issue already opened here: https://github.com/mantidproject/mantid/issues/21969
