### ISSUE TITLE
ISIS Indirect Unscripted Testing :: Bayes > Stretch

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21981]
* If you increase the `Current Spectrum` spinner and then add a workspace with fewer spectra than the `Current Spectrum` spinner you get an unexpected exception:
  * `Unexpected exception: Workspace index is out of range, cannot plot.`

**Comment by brandonhewer** [comment]
Issue already opened here: https://github.com/mantidproject/mantid/issues/21968
