### ISSUE TITLE
ISIS Indirect Unscripted Testing :: Data Reduction > Symmetrise

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21980]
* Use `irs26176_graphite002_red` (reduced with default options) and drag the green sliders inwards to about +/-0.25. When you hit run you get an unhandled exception:
   * `Unexpected exception: Unable to find workspace type with name '__Symmetrise_temp': data service  search object __Symmetrise_temp`

**Comment by ElliotAOram** [comment]
Copy of test data can be found here: #21893

**Comment by martyngigg** [comment]
This no longer seems reproducible on the current version of the release branch on both mine and @ElliotAOram's machine.
