### ISSUE TITLE
ISIS Indirect Unscripted Testing :: Corrections > Calculate Monte Carlo Abs

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#21983]
You are able to supply the interface with 0 for mass density. Is this behaviour correct? 

When you run this in CalcPaalmanPings, you get a warning about it (even though it obsecured by other output) in calc monte carlo, no warning is produced (we should probably warn users what is going on more clearly)

*Marked as low priority comparative to other indirect issues for 3.12*

**Comment by ElliotAOram** [comment]
Copy of test data can be found here: #21893

**Comment by NickDraper** [comment]
No need for this in R3.12, it can wait until after
