### ISSUE TITLE
Paraview Segfault Centos 7

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#22019]
Paraview Segfaults when loading an MdWorkspace created using mantid on Centos 7. This was discovered using the nightly build for release 3.12

**Comment by NickDraper** [comment]
@quantumsteve and this one please

**Comment by LamarMoore** [comment]
Works with RHEL 7 out of the box and works on CENTOS 7 with usage reporting switched off (potentially a libjsoncpp issue due to the nightly being built on RHEL 7 and paraview being built on CENTOS 7). Closing this issue.
