### ISSUE TITLE
Paraview not Picking up Mantid Plugins on Windows 10

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#22021]
Self explanatory. After setting `PV_PLUGIN_PATH` to the correct location (where the mantid paraview plugins are stored), paraview seems to be unable to pick up all of the plugins save one. There is no way to load a nexus file in paraview.

**Comment by NickDraper** [comment]
@quantumsteve Steve can you take a look at this one?

**Comment by martyngigg** [comment]
This works for me on my Windows 10 laptop with the latest installer and ParaView-5.4.1. @LamarMoore  is going to try again tomorrow.

**Comment by LamarMoore** [comment]
Works for me now on Windows 10. There was an issue with the PATH environment variable (there was another HDF5 library which was loaded before the mantid installed versions).
