### ISSUE TITLE
Add Function on graph right click does not work with Muon multi dataset fitting

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#22022]
### Expected behavior
The graph bright click option for adding a function should add the function to the dialog in the Muon Analysis GUI

### Actual behavior
The added function is ignored when the Mujon gui is set to multiple fitting.  Adding the function by clicking on the dialog box still works.  Also the graph right click works in single fitting mode.

### Steps to reproduce the behavior

1. Open muon analysis
1. Load some data (e.g. HIFI00108376)
1. Go to the settings tab and make sure that the multiple fitting box is ticked
1. Go to data analysis tab
1. Add a fitting function by right clicking on the graph and selecting something from add peak, add background or add other function.
1. The function is not added to the muon gui
1. Add a fitting function by right clicking on the muon gui and selecting something from add function,
1. This should work

**Comment by AnthonyLim23** [comment]
we should disable the options as the y do not work (no idea how best to do this one)

**Comment by NickDraper** [comment]
@roman can you have a look at this one
