### ISSUE TITLE
Indirect data analysis I(Q, t) Fit validation of input 

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#22029]
The file format checker only shows `*_iqt.nxs` files, but if you can bypass this (give full file path / select all files option in file tree). If you use the `*_red.nxs` file, check `Stretched Exponential`  and click `Run` mantid crashes to crash reporter.

`Unexpected exception: Selected value -0.547613 is < the lower bound (0)`

Whilst this interface is not designed to be used in this way, we should still ensure that some validation stops users from seeing this.

**Comment by SpencerHowells** [comment]
@ElliotAOram one possibility is to check that the workspace has x-unit as time. And perhaps also that x > 0.

**Comment by ElliotAOram** [comment]
These both seem like sensible checks I'll push this to @brandonhewer for now, but let me know if you don't have enough time and I might get time next week to have a look!

**Comment by SpencerHowells** [comment]
@brandonhewer x could be 0 so the check is that x < 0

**Comment by SpencerHowells** [comment]
@brandonhewer wrong symbol! Check if x<0 then error
