### ISSUE TITLE
Crash & Muon data analysis multi fit is including, but not show auto background functions

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#22023]
### Expected behavior
Auto background may not be desirable for muon data, so it should either be disabled, or at least shown in the GUI

### Actual behavior
If you have an auto background selection it is silently added to the function you have chosen in the muon data analysis gui

Auto background functions are listed in the single fit muon gui

### Steps to reproduce the behavior
view->preferences
Mantid->curve Fitting
set auto background = LinearBackground, click OK
Open muon analysis
Load some data (e.g. HIFI00108376)
Go to the settings tab and make sure that the multiple fitting box is ticked
Go to data analysis tab
Note that nothing is in the function list
Click Fit -> Fit
CRASH -> continue
Open the workspace HIFI00108376 .......... _ Parameters
Note the A0 and A1 parameters from the linear background function
![image](https://user-images.githubusercontent.com/1017173/37203787-c96310de-2386-11e8-87ab-b281db88b7f8.png)

**Comment by NickDraper** [comment]
@AnthonyLim23 Another new moun issue

**Comment by AnthonyLim23** [comment]
I think I know what is causing the other bug. So hope to get that fixed today or early Monday. If no one else has taken this by then I will have a look at it

**Comment by AnthonyLim23** [comment]
they tend not to use auto background. So this is less important

**Comment by AnthonyLim23** [comment]
make sure we clear the functions when changing interface
