### ISSUE TITLE
PhaseQuad can add results to the wrong group workspace

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#22031]
### Expected behavior
The results should go in the right group workspace

### Actual behavior
If you run another file through Muon Analysis after opening the Frequency analysis gui then the PhaseQuad will use the new workspace, but store the results into the group workspace of the old one.

### Steps to reproduce the behavior
1. Start the Muon Analysis interface
1. Load MUSR00068389
1. Start the Frequency domain GUI
1. Set the workspace to be PhaseQuad
1. Go back to the Muon Analysis interface
1. Load MUSR00068675
1. Go back to the Frequency domain GUI
1. Click calculate FFT
1. The PhaseQuad;FFT workspace is added to the MUSR00068389 group workspace, but it is based from

![image](https://user-images.githubusercontent.com/1017173/37215156-1594619c-23af-11e8-9c06-213e78ec74f9.png)

**Comment by AnthonyLim23** [comment]
get workspace from muon analysis and use that to get group ws. Add it it to the output name too
