### ISSUE TITLE
No prompt to save changes on closing ISIS Reflectometry

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22051]
### Expected behavior

When closing the interface after editing data, a prompt to save/discard/cancel should appear, if the changes have not been saved already.

### Actual behavior

The interface just closes, without saving the changes.

### Steps to reproduce the behavior

* Open ISIS Reflectometry.
* Edit some of the cells in the table
* Close the interface

### Platforms affected

OSX
Windows

**Comment by gemmaguest** [comment]
May be fixed by #26533
