### ISSUE TITLE
Indirect - Calculate Monte Carlo Absorption - Interface is missing interpolation and MaxScatterPtAttempts option

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#22054]
The ```Interfaces > Indirect > Corrections > Calculate Monte Carlo Absorption``` interface is missing a field for selecting the interpolation type to use in the calculation of the absorption corrections. The interface is also missing the ```MaxScatterPtEvents``` option.

An ```Interpolation``` drop-down menu should be included under the Monte Carlo options groups, providing the options ```Linear``` and ```CSpline```. A spinner should be included under the same group, to provide the ```MaxScatterPointsAttempts```.

**Comment by SpencerHowells** [comment]
@brandonhewer it is also missing the new parameter MaxScatterPointsEvents. Default values for all the MC values should be in the IPF not hard wired.

**Comment by SpencerHowells** [comment]
@brandonhewer it’s MaxScatterPtAttempts. Sorry!
