### ISSUE TITLE
Uncaught exception when masking in instrument view

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22087]
### Expected behavior

When attempting to apply a mask to data over part of the ToF range Mantid should not throw an uncaught exception warning. Either the mask should be applied, or a warning should be thrown.

### Actual behavior

Mantid throws an uncaught exception warning.

### Steps to reproduce the behavior

* Open some data eg `INTER00013460` from the training data.
* Open instrument view.
* Reduce ToF so that it does not include the full range.
* In the draw tab, choose any mask shape and draw on the view.
* Click `Apply to Data`

### Platforms affected

Windows
OSX
Linux

**Comment by KarlPalmen** [comment]
How does one reduce ToF so that it does not include the full range?

**Comment by KarlPalmen** [comment]
I've figured out, it is the time range at the bottom of the instrument view window and have reproduced the bug.
