### ISSUE TITLE
Incorrect rounding in SumOverlappingTubes

### ISSUE THREAD

**Issue by quantumsteve** [mantidproject/mantid#22093]
### Expected behavior

Use `std::lround` and `boost::math::iround` to fix warnings from [misc-incorrect-roundings](http://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/misc-incorrect-roundings.html)

### Actual behavior

system test `PowderDiffILLDetScanReductionTest` fails when a naive rounding formula is replaced with `boost::math::iround`. (The naive formula fails when the integer is < 0)

### Steps to reproduce the behavior

1. Apply attached patch
2. Build mantid
3. run system test `PowderDiffILLDetScanReductionTest`

### Platforms affected

all

[SumOverlappingTubes.txt](https://github.com/mantidproject/mantid/files/1813141/SumOverlappingTubes.txt)

**Comment by gvardany** [comment]
Does the unit test of `SumOverlappinTubes` also fail?

**Comment by quantumsteve** [comment]
No, `SumOverlappinTubes` still passes. The issue only occurs when `angleIndex < 0`, which happens in `PowderDiffILLDetScanReductionTest`.
