### ISSUE TITLE
Double ki/kf correction in DirectEnergyConversion ?

### ISSUE THREAD

**Issue by gmonet** [mantidproject/mantid#22123]
The doc for the algorithm "[DetectorEfficiencyCor-v1](https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/DetectorEfficiencyCor-v1.rst)" says that data are multiplied by ki/kf at the end of the correction but there is no trace of this operation in the [c++ source code](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/DetectorEfficiencyCor.cpp). 
Moreover, some interfaces (ConvertToEnergy (Direct)) actually do CorrectKiKf operation after DetectorEfficiencyCor...

**Comment by AndreiSavici** [comment]
The data is multiplied with 1/k_f in the code. Since k_i is a constant, it is the same operation

**Comment by gmonet** [comment]
Well... In this case, i don't understand why there is a correction by k_i/k_f in the [DirectEnergyConversion ](https://github.com/mantidproject/mantid/blob/master/scripts/Inelastic/Direct/DirectEnergyConversion.py) script ([line 1798](https://github.com/mantidproject/mantid/blob/master/scripts/Inelastic/Direct/DirectEnergyConversion.py#L1798)) although there is a correction of the efficiency of the detector [line 1731](https://github.com/mantidproject/mantid/blob/master/scripts/Inelastic/Direct/DirectEnergyConversion.py#L1731) :/

**Comment by gmonet** [comment]
In instrument parameters :
https://github.com/mantidproject/mantid/blob/546b2eccbaf236fd217ccbd21573f88aa0272103/instrument/MARI_Parameters.xml#L390-L398
Did i miss something ? :(

**Comment by gmonet** [comment]
My bad, we actually need to correct data by the detector efficiency AND to multiply by ki/kf.
The documentation of DetectorEfficiencyCor-v1 is, maybe, misleading.
