### ISSUE TITLE
Floating point uncertainties yield NaNs for UnitCell calculations

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#22134]
Try:
```
ol=OrientedLattice(5.45,5.45,5.45)
print(ol.recAngle(0.,4.,0.,0.,4.,0.))
```
The angle between a vector and itself should be 0. Due to numerical errors, the function calculates `acos( 1.0000000000000002)`. Since the argument is greater than 1, the output is NaN

**Comment by NickDraper** [comment]
This was present in R3.11
