### ISSUE TITLE
Handling of missing / bad runs in SANS GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#22141]
The `ISIS SANS v2 experimental` GUI takes a long time to find and attempt to process run LOQ74044 if the data is loaded from the archive rather than the local sample data. There are also a lot of errors, which seem to originate with a bad log file. The whole GUI locks up while attempting to find the runs in the archive.

The error is perhaps expected but perhaps could be handled better, e.g. quit earlier if a bad log file is found? It would also be good to give some indication of what is going on when searching for the runs in the archive, and to avoid lockup up the whole GUI if possible.

To reproduce:
- Make sure your search directories are empty
- Open the GUI
- Load the mask file and batch file from the ISIS loqdemo sample data
- Click Process

You can also see the log file error by loading the file from the archive, e.g.:

```
Load(Filename='/mnt/archive/ndxloq/instrument/data/cycle_99_4/LOQ74044.raw', OutputWorkspace='LOQ74044')
```

```
Error in execution of algorithm LoadLog:
File/mnt/archive/ndxloq/instrument/data/cycle_99_4/LOQ74044.log is not a standard ISIS log file. Expected to be a file starting with DateTime String format.
```

**Comment by Mantid-Matthew** [comment]
This issue is dealt with by #22511
