### ISSUE TITLE
Indirect - ConvFit - Mantid Crashes on Ubuntu and Redhat when fit is run with more than a single fit function

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#22179]
In the Interfaces > Indirect > Data Analysis > ConvFit interface, running the fitting routine with a composite function (e.g. One Lorentzian and a Delta Function) results in a crash on Ubuntu and Red Hat systems.

The exception ```Function index (2) out of range (2)``` is thrown within CompositeFunction.

This bug is not repeatable on Windows (7 or 10), Fedora or Ubuntu 16.04.

**Comment by NickDraper** [comment]
Is this genuinely high priority (i.e. actually stopping someone doing work? with no work around).

If it is then add a comment stating who is impacted and how, otherwise please remove the high priority label.

**Comment by brandonhewer** [comment]
This is no longer an issue -- it was working on all tested versions of Ubuntu but now Ubuntu 14.04 is also no longer supported.
