### ISSUE TITLE
clang-tidy: modernize-loop-convert

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#22183]
Issue to use clang tidy to replace imperative `for` loops with range based for loops where appropriate

**Comment by TTitcombe** [comment]
modernize-loop-convert has three confidence options for evaluating the riskiness of auto-fixing loops.
PRs #25274 and #25273 run clang-tidy modernize-loop-convert on Mantid under the default confidence option.
However, there are still many instances remaining of loops which can be converted to range-based.
Our current method of using clang-tidy through cmake does not easily allow us to set these optional flags, so another way of running clang-tidy must be used, with MinConfidence=risky, to catch the remaining cases.
