### ISSUE TITLE
CompositeFunction index out of range in ConvFit

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#22196]
The typical model of two Lorentzians plus a background results in a bug in the ConvFit tab when trying to fit

![convfit_bug](https://user-images.githubusercontent.com/1136006/37882208-2d586d60-306f-11e8-9995-32c19b86d260.png)

**Comment by SpencerHowells** [comment]
@jmborr already reported in #22179

**Comment by SpencerHowells** [comment]
@jmborr already reported in #22179

**Comment by jmborr** [comment]
Problem already being addressed in #22179
