### ISSUE TITLE
DirectILLReduction: binning of twotheta angles in OutputSofThetaEnergyWorkspace

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#22223]
The *OutputSofThetaEnergyWorkspace* can have up to 9000 histograms in case of IN5. There should be some way of rebinning the twotheta angles.

**Comment by AndreiSavici** [comment]
You can use `GenerateGroupingPowder`

**Comment by soininen** [comment]
@AndreiSavici Thanks for the hint! `GenerateGroupingPowder` indeed looks interesting, although I thought that Mantid calculates the group theta angles correctly nowadays; also, I'm not sure about saving the grouping file to disk as this plays poorly with algorithm history if temporary files are used. Anyway, I think I'll give it a go.
