### ISSUE TITLE
Mantid loads incorrect default file rather than 'file not found'

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22232]
**Original Reporter** Jos Cooper ISIS; please report back when the issue is resolved.

### Expected behavior

If a request to load a non-existent file is made the loader should complain that 'file does not exist'.

### Actual behavior

Mantid chooses a default file and loads that instead.

### Steps to reproduce the behavior

In Mantid:

* Open the 'Load' dialog; choose 'File'.
* In the 'File' box enter garbage (a name you know does not exist on any default path).
* Give a name for 'OutputWorkspace'.
* Click 'Run'.
* A new workspace with the given name will appear, containing some data .

### Platforms affected

OSX/Windows

**Comment by martyngigg** [comment]
I think I see what is happening here. It is using the last file it found, which must be cached somewhere. I tested this by loading an existing file, going back to the dialog and adding rubbish names to the file/workspace boxes and it then loaded that previous file. This was on Linux so I think it's a general issue too.
