### ISSUE TITLE
Instrument view shows now a gap between left and back SANS detectors

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#22242]
LoadEmptyInstrument D33:

Release 3.12:

![release3-12-sansd33view](https://user-images.githubusercontent.com/19187274/38240319-965f78b4-372f-11e8-8d2f-8e7cbd19f907.png)

Master:

![mastersansd33view](https://user-images.githubusercontent.com/19187274/38240326-9b9bf53c-372f-11e8-9c1e-f6b86e7d5dd3.png)

Expected behavior:
- no zickzack in particular when detector defines rectangular pixels in xy plane
- there should not be a gap between the left and back detector (it suggests that the IDF is wrong!)

**Comment by OwenArnold** [comment]
@reimundILL Thanks for bringing this to our attention. How urgent is the fix required in Master for this?

**Comment by gvardany** [comment]
@OwenArnold It is not critical for D33, but maybe other rectangular detectors are also skewed.

**Comment by reimundILL** [comment]
The instrument view was my IDF verification tool for D33. I trust it in terms of updating the IDF. Just let me know when I can have a look at it again. Thanks for your investigations.
