### ISSUE TITLE
Change Algorithm doc landing page to categories

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#22254]
This is to change the landing page for documentation to be the base category list

it will also:

1. contain a link to the full alphabetical list on the first landing page.
1. neaten up the list handling when there are few items to list.

**Comment by NickDraper** [comment]
So i didn't get any further,

It fails with this message
```
6>  AttributeError: 'str' object has no attribute 'name'
```

but I haven't been able to track it down yet

**Comment by keeeto** [comment]
This is starting to come together - there is currently an issue in that subcategory pages are now taking on the over-arching category format. I'll look at this after lunch.

**Comment by keeeto** [comment]
I think that some of the category names could be made more descriptive - eg "Crystal" and "Background" are terms that could be any number of things.
