### ISSUE TITLE
Replace DataProcessorWidget with BatchWidget

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#22263]
This is an umbrella issue for the incremental replacement of the `DataProcessorUI` framework with a new `Batch` widget within the Reflectometry and SANS interfaces. See more detail [here](https://gist.github.com/edwardb96/a90f58b7b3f578f01503bb25c64866a2)

- [x] Create `JobTreeView` a modified MVP style view constructed from a subsclassed `QTreeView` and `QStandardItemModel`.
- [x] Store settings from tabs in a reduction configuration model #23043

**Comment by gemmaguest** [comment]
The child issues are now complete
