### ISSUE TITLE
Mantid Crashes if one Attempts to Display Mask a Second Time

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#22288]
### Expected behavior
If one runs through the steps of the test of #22268 then after displaying mask, press the display mask button again. The instrument display should be shown again over the interface window.
### Actual behavior
Mantid crashes.
### Steps to reproduce the behavior
Described in Expected Behaviour. PR #22268 need not be merged.
### Platforms affected
Windows 7 at least

**Comment by Mantid-Matthew** [comment]
This is no longer replicatable
