### ISSUE TITLE
Crash on opening Sumspectra Dialog

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#22326]
### Expected behavior
No segfault crash

### Actual behavior
Opening the SumSpectra dialog can crash Mantid.

### Steps to reproduce the behavior
Load LARMOR28540
Try to open the SumSpectra dialog -> Segfault

Note: it runs fine if you do it via python

### Platforms affected
Seen on windows at least, reported by Rob Dalgleish

**Comment by NickDraper** [comment]
Martyn can you take a look at this please

**Comment by martyngigg** [comment]
So it looks like this is a problem with any `WorkspaceGroup` that you have selected when you start the `SumSpectra` dialog.
