### ISSUE TITLE
SANS GUI failing to find added files

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#22378]
When an added file is saved without being preceded by the correct instrument name the new SANS GUI cannot find the file from the run number-add. 

The fix for this should ensure that the standard file names suggested for added files gave the instrument name preappended but also as the name is editable by users put checks in place to allow the correct file to be found if it is not preceded by the instrument name.

**Comment by NickDraper** [comment]
Closed until such time as more information is added to this issue
