### ISSUE TITLE
Manual testing documentation 

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22412]
This is not a bug. There is a need to develop acceptance tests for different areas of the code. These tests will be designed and agreed with instrument scientists and will represent a minimal set of functionalities that *must* work properly for the code to be acceptable. 

In future these tests will form part of the release procedure and will *have* to pass in order to go to release.

**Comment by NickDraper** [comment]
Reopened as this is related to an unmerged branch with some progress.
