### ISSUE TITLE
Crystal field parameters not updating in fitting procedure

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22466]
**Original reporter:** Raimundo Serrano; please report to Keith Butler when this issue is resolved.

### Expected behavior

Fitting the crystal field parameters with physical properties as an input should result in updated crystal field parameters.

### Actual behavior

Running a fit does not update the parameters of the crystal field model.
**Note** running a fit _without_ the physical properties as an input works correctly.

### Steps to reproduce the behavior

[Script and data needed to reproduce the problem: Archive.zip](https://github.com/mantidproject/mantid/files/2034348/Archive.zip)

Running the script generates a new workspace `fit_result_Parameters`, with the updated model parameters.

Inspecting this workspace, if the fitting has worked the parameters B20, B40, B60, B66 should have been modified and should have an error associated with them. In this case they have not changed from the original values and have no error associated.

### Platforms affected

OSX, Windows

**Comment by mantid-roman** [comment]
Thanks @mducle. I'll open a PR then.
