### ISSUE TITLE
Multi-dataset fitting error when adding Crystal Field function

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22474]
**Original reporter:** Raimundo Serrano; please report to Keith Butler when this issue is resolved.

### Expected behavior

Adding a Crystal Field function in the Fitting GUI should be possible.

### Actual behavior

Adding a Crystal Field function in the Fitting GUI results in an uncaught exception error.

### Steps to reproduce the behavior

* Load the dataset below in Mantid:
[INS-Low-Q-Er-50K.dat.zip](https://github.com/mantidproject/mantid/files/2038701/INS-Low-Q-Er-50K.dat.zip)

* Plot the spectrum
* Click fitting tool icon
* On the plot, right-click and choose _Add Other Function_
* Choose _CrystalFieldFunction_
* The unexpected exception dialog appears

### Platforms affected

OSX, Windows

**Comment by mantid-roman** [comment]
Should be fixed by PR #25232
