### ISSUE TITLE
Workbench Plotting: Allow drag and drop on to existing figures

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#22501]
MantidPlot has the following behaviour w.r.t to drag-and-drop behaviour of workspaces on to figures:

* drag a workspace on to a plot either plots the workspace immediately on the same figure if it has 1 spectrum or brings up the plot selection dialog if it has more than 1 spectra
* the new plot curve will have errors plotted if the existing curves have them
*  it allows 1D curves to be overplotted onto image plots

We should replicate the first two points but not the last. For 2D plot if you drag it on to an existing figure it should just replace it.

Dragging multiple 1D workspaces on to a 1D plot should add curves from each workspace. Dragging multiple 2D workspaces onto a 2D plot should warn and ask the user to make a single selection.

**Comment by ElliotAOram** [comment]
Note this was raised again in the ESS user workshop May 2019

**Comment by martyngigg** [comment]
Is this not done in https://github.com/mantidproject/mantid/pull/23250? I'm not sure why this didn't get closed...
