### ISSUE TITLE
Indirect - ISISEnergyTransfer - Custom Detector Grouping Option

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#22533]
In the Indirect > Data Reduction > ISISEnergyTransfer interface, in the 'Modes' drop-down menu, under 'Detector Grouping', a new option should be included; 'Custom'.

This option should bring up a line edit widget next to the drop-down menu and allow the user to enter a grouping pattern in the same manner as the 'GroupingPattern' property of the GroupDetectors (v2) algorithm.

The existing ISISIndirectEnergyTransfer (Python) algorithm should be modified to allow a grouping pattern to be passed to it.

Finally, the 'Default' option in the 'Detector Grouping' menu may be removed.

**Comment by SpencerHowells** [comment]
The 'Detector Grouping' option 'Default' can also be removed. It serves no purpose.
