### ISSUE TITLE
Add numpy `dtype` exports to PropertyWithValue

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#22553]
The current exports of `PropertyWithValue`do not provide a way to export the type of the property. This leads to us having to write gross pieces of code such as the following:

```python
        if isinstance(prop, (FloatPropertyWithValue, FloatTimeSeriesProperty, FloatArrayProperty)):
            return "f"
        if isinstance(prop, (IntPropertyWithValue, Int32TimeSeriesProperty, Int64TimeSeriesProperty)):
            return "i"
        if isinstance(prop, (BoolPropertyWithValue, BoolTimeSeriesProperty)):
            return "b"
        if isinstance(prop, StringPropertyWithValue):
            return "S{}".format(len(prop.value))
        raise RuntimeError("Unrecognised property type: \"{}\". Please contact the development team with this message".
                           format(prop.type))
```

Instead I propose we expose a new function called `dtype` that returns a numpy friendly string format for the `dtype`. [See here](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.dtype.html) for the docs of the numpy function.

**Comment by josephframsay** [comment]
If I may take liberties, from the point of view of #22554 there's one extra thing that will be needed for this change to be used in `ExportSampleLogsToHDF5` (and one thing that would be nice).

The necessary thing is that we'll also need to be able to get the dtype of a `TimeSeriesProperty`. In `ExportSampleLogsToHDF5` this is the same as if the log were a scalar (ie `IntTimeSeriesProperty` has dtype `i`, not array of `i` or anything like that).

The nice-to-have is that `ExportSampleLogsToHDF5` also has to check whether the log is a `TimeSeriesProperty`, which it currently does with another great big `if isinstance(blah ...)`. This might be beyond the scope of this issue, but I think it's another thing that would be generally useful?

@samueljackson92 thoughts?

**Comment by samueljackson92** [comment]
@josephframsay Sounds like you want a `isTimeSeries()` method on the `Property` export. That seems like an entirely sensible suggestion.
