### ISSUE TITLE
Indirect - Vesuvio - Add method for calculating cumulative angle-averaged data to the VesuvioTOFFit Algorithm

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#22577]
The method for calculating cumulative angle-averaged data is currently only available in the vesuvio driver script (commands.py), this should be moved to the VesuvioTOFFit algorithm (in VesuvioTOFFit.py).

**Comment by Mantid-Matthew** [comment]
@AnthonyLim23 closing this as I assume it is superseded by your more recent discussions abut Vesuvio.
