### ISSUE TITLE
Instrument View issues on macOS High Sierra

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#22591]
Instrument view with `OpenGL` enabled suffers on macOS 10.13. 

### Expected behavior
Instrument viewer should open without errors.

### Actual behavior
Instrument viewer throws errors. Few examples below:

<img width="1680" alt="screen shot 2018-06-15 at 12 25 38" src="https://user-images.githubusercontent.com/16865759/41465311-d048c376-709d-11e8-9150-baaf7627cbcd.png">
<img width="1680" alt="screen shot 2018-06-15 at 12 24 56" src="https://user-images.githubusercontent.com/16865759/41465312-d05f50e6-709d-11e8-9f06-cf70a8bd1706.png">

### Steps to reproduce the behavior
1. Install mantid nightly or 3.12.1 on macOS 10.13. The errors appear even with 3.11.
2. LoadEmptyInstrument (any would do, for example TOPAZ).
3. Open the instrument view

### Platforms affected
macOS 10.13 (maybe also 10.12?), fine on 10.11 though

**Comment by mantid-roman** [comment]
It could be helpful to know which gl command issued the initial error.

**Comment by quantumsteve** [comment]
Have you tried building Mantid on 10.13? Does the same issue exist?

**Comment by OwenArnold** [comment]
For information, i am running version 10.12.6 Sierra and have not been able to reproduce these issues.

**Comment by LamarMoore** [comment]
@gvardany Have you monitored your GPU when loading the instrument? I noticed a similar error situation yesterday when I ran out of GPU memory.

**Comment by gvardany** [comment]
Good points, I haven't monitored the GPU neither tried building on 10.13 yet. Will keep you posted.

**Comment by gvardany** [comment]
I've just tried to build on 10.13 itself, and the problems are gone.

**Comment by gvardany** [comment]
No longer relevant.
