### ISSUE TITLE
Changes required for running reflectometry reduction

### ISSUE THREAD

**Issue by vreimund** [mantidproject/mantid#22612]
When trying to run a reflectometry reduction for D17 (e.g. using water normalisation), existing difficulties may be resolved.

- check WaterReference input for ReflectometryILLPreprocess, a separate algorithm may be needed
- multiple file loading in ReflectometryILLPreprocess: giving four files, two files get loaded and then a `Unknown property search object InputWorkspace` gets returned.

**Comment by reimundILL** [comment]
`WaterReference` input is fine.
