### ISSUE TITLE
Add filename parameter to ISIS Powder scripts

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#22638]
**Original reporter:** @DavidFair

We need to add a filename parameter so an external service can run the reduction with a filename, instead of relying on the file finding mechanisms built into Mantid.

To do:
- [ ] Add a filename parameter which can be used instead of run number
- [ ] Update the scripts to not try to pad / modify the file number
- [ ] Update documentation with this new flag

For a later issue
- [ ] Completely remove and rewrite the calibration mapping file handling. It is overly complex and unmanageable for new developers
- [ ] Ensure we can specify a filename to a vanadium run instead of a run number

**Comment by josephframsay** [comment]
We decided that this change is not the right way to approach the issue, which appears to be an issue with autoreduction nodes, not `isis_powder`. It's not in keeping with rest of the design of `isis_powder` (nuts-and-bolts such as file paths should be hidden away from the users as much as possible), and it's not a requirement any users need - hopefully the issue can be resolved at the autoreduction end
