### ISSUE TITLE
Move ONCAT token out of properties file

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#22669]
#22635 introduced code for ONCAT to mantid. It currently stores the user token in the `Mantid.local.properties`. The token should be moved to a separate location in (on linux and mac) `~/.ssh/` where such things are normally located. I do not know where the appropriate place is on windows. This can still be abstracted/handled my `ConfigService` it is just where it is stored.

**Comment by PeterParker** [comment]
TODO:

* [ ] - Revert 2876556ae87f8f31fe7fe4de82cf3b4d080b0542, which would no longer be necessary once the tokens are moved elsewhere.
