### ISSUE TITLE
Reduction GUI crashes whn sample setup contains invalid characters

### ISSUE THREAD

**Issue by JoachimCoenen** [mantidproject/mantid#22684]
### Expected behavior
Reduction GUI starts up with or w/o an error message or at least lets the user change the instrument, when the startup of an instrument specific widget fails

### Actual behavior
Reduction GUI doesn't start up, but instead logs an error message: "ValueError: invalid literal for int() with base 10: '69634,69635,69636,69637' at line 10 in '<Interface>'..."
that makes changing the instrument impossible
 
### Steps to reproduce the behavior
Go to  `Interfaces`&rarr;`Direct`&rarr;`DGS Reduction`. Choose facility `ISIS` and instrument `MERLIN` and click `OK`.
If a reduction dialog appears immediately (w/o selecting a facility and instrument): 
Go to  `Tools`&rarr;`Change instrument...`. Choose facility `ISIS` and instrument `MERLIN` and click `OK`. Then close the (blank) reduction dialog and reopen it using `Interfaces`&rarr;`Direct`&rarr;`DGS Reduction`

### Platforms affected

Ubuntu, ...?

**Comment by NickDraper** [comment]
This GUI is not used at ISIS or the SNS
