### ISSUE TITLE
MonitorLiveData sometimes hangs on errors

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#22690]
**Original reporter:** Jos at ISIS

### Expected behavior
MonitorLiveData should exit cleanly on error

### Actual behavior
If an error occurs, MonitorLiveData sometimes does not exit cleanly. It looks like it is still running but it does nothing. If you try to cancel it from the Algorithm progress dialog, the button changes to `Cancelling` but then hangs and the algorithm never exits. If you try to quit MantidPlot, it hangs and you have to kill it.

Possibly related to #19040

### Steps to reproduce the behavior
It's intermittent but I've seen this by starting live data as per the instructions in #20702 while an Offspec experiment is running. Leave it running for a long time and at some point the data size will probably change. This gives an error which usually causes MonitorLiveData to exit cleanly, but sometimes the algorithm is left hanging.

### Platforms affected
I saw this on Ubuntu. Jos has reported similar problems on Windows.

**Comment by NickDraper** [comment]
Should be fixed by #27077
