### ISSUE TITLE
SANS Mask Fails to load on OSX

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22702]
This has been marked as high priority as it prevents the SANS GUI from being used on OSX.

**Original reporter:** n/a

### Expected behavior

SANS GUI should load up the mask file.

### Actual behavior

SANS GUI throws an error when trying to load the mask file
```
RuntimeError: Invalid input for tube calibration file (TUBE_SANS2D_BOTH_31681_25Sept15.nxs ).
Please do not run a reduction as it will not successfully complete.

  at line 3 in '<Interface>'
  caused by line 3261 in '/Users/keithbutler/src/mantid-git/mantid/scripts/SANS/isis_reduction_steps.py'
  caused by line 3288 in '/Users/keithbutler/src/mantid-git/mantid/scripts/SANS/isis_reduction_steps.py'
  caused by line 4015 in '/Users/keithbutler/src/mantid-git/mantid/scripts/SANS/isis_reduction_steps.py'
```

**NB** the line numbers relate to the version of `isis_reduction_Steps.py` on master branch at the moment:

```
3258         file_handle = open(user_file, 'r')
3259         for line in file_handle:
3260             try:
3261                 self.read_line(line, reducer)
```

### Steps to reproduce the behavior

* Get the SANS2D data from `//olympic/babylon5/Scratch/Matthew Andrew/SANS2DSAMPLE`
* Open the old SANS GUI
* Set `User File` to point at `USER_SANS2D_154E_2p4_4m_M3_Xpress_8mm_SampleChanger_REAR.txt`
* Click `Load Mask`
* An error message should appear

### Platforms affected

OSX

**Comment by Mantid-Matthew** [comment]
This issue appears to be resolved by insuring that the Mantid search directories are set up correctly. The error messages in this instance are very unhelpful however. As this has been the case for a while and the error messages in the new GUI have improved I am closing this for now.
