### ISSUE TITLE
Project Recovery - Sanitise filesystem characters

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#22780]
A workspace with a name containing `: * ?` characters cannot be saved. This should be sanitised

For example a workspace named after a file path would fail to save.

**Comment by ianbush** [comment]
Just to clarify it is more than those characters and sanitising workspace names may be difficult https://stackoverflow.com/a/1976050.

Perhaps the name could be in the `.py` file instead, and the filenames can be something like `000001.py, 000002.py...`?.
