### ISSUE TITLE
Sorting does not work within Workspace Groups in MantidPlot

### ISSUE THREAD

**Issue by BhuvanBezawada** [mantidproject/mantid#22805]
**Original reporter:** [username facility]/[nobody]. 

### Expected behaviour 
Workspace Groups should have the option to be sorted.

### Actual behaviour 
Sorting only occurs outside groups in the main list of Workspaces.

### Steps to reproduce the behaviour 
Load a few files into the WorkspaceDock and then group them.
Use the sort button to try and sort the files in the group.
The files within the group would not have been sorted.

### Platforms affected 
All

**Comment by NickDraper** [comment]
We first have to answer the question of whether we think that the contents of workspace groups should be sorted, and what would that look like with respect to top level workspaces.
I think that accepting that sorting will only affect the top level of the tree might be perfectly acceptable.
