### ISSUE TITLE
Engineering diffraction GUI archive search checks too many extensions

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#22806]
**THIS ISSUE IS BLOCKED BY https://github.com/mantidproject/mantid/issues/21231**

In the Engineering Diffraction GUI when searching the archive for a specified file a long list of file extensions is searched. This leads to long timeouts whilst the Archive is searched for files of several different types. The extensions which need to be searched for are .nxs, .raw and .s. Changing the search to only look for these extensions should shorten the time before the GUI gives up on searching for files entered incorrectly by users. 

The GUI also seems to reattempt the search on all extensions if it fails the first time. Investigating why this is would also be useful. 

===To Replicate===

Instructions on how to use the Engineerng diffraction GUI can be found here http://docs.mantidproject.org/nightly/interfaces/Engineering%20Diffraction%20Test%20Guide.html.

With the ISIS data archive enabled go to the focus tab enter a non existent run number and click focus. All the buttons on the GUI should be disabled. If you set the logging level to debug you should be able to see repeated calls being made to the data archive with a variety of different extensions.

**Original reporter:** matthew.andrew@stfc.ac.uk

**Comment by Pasarus** [comment]
So this seems to be a lot more complicated than first thought.
It requires a change to the FileFinder.cpp file specifically in findRuns() to call the non-default findRun() function. Basically findRuns() is called and it default runs findRun() which does not take in any file extensions, thus calling all of the default file extensions causing this issue. Once the issue https://github.com/mantidproject/mantid/issues/21231 is resolved it will most likely be an easier fix.
