### ISSUE TITLE
Cosmetic Improvements to Mantid GUI

### ISSUE THREAD

**Issue by BhuvanBezawada** [mantidproject/mantid#22810]
**Original reporter:** [nobody]. 

This is not a bug report, but refers to several cosmetic improvements that would improve the GUI of Mantid.

### About MantidPlot Window

- [ ] Release doi links to the homepage - should be to the download page
- [ ] Question mark symbol appears in the toolbar of the dialog. It has no functionality and so it should not be there

### Toolbar

- [ ] Clicking on the open new project icon does nothing.
- [ ] The `Copy` button is not greyed-out, but doesn't work unless there is a workspace open (not clickable)

### Dialogs

- [ ] Border around the script interpreter
- [ ] Load recent under the `Load` options in Workspaces  
- [ ] Consistent border padding on all dialogs, e.g. Workspaces/Algorithms

**Comment by NickDraper** [comment]
These are minor changes to mantid plot and will not be done as this is being superceded by the workbench
