### ISSUE TITLE
Update SANS Documentation

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#22816]
A lot of the current sans documentation is out of date and still on the old wiki. This should gradually be updated revalidated with scientists and moved to the new sphinx documentation.
**Original reporter:** steve

**Comment by Mantid-Matthew** [comment]
Haveing asked around the wiki does have one advantage which is that scientists can edit the pages themselves. I therefore need to speak to the relevant scientists before deciding how to go ahead with this.

**Comment by DavidFair** [comment]
I spoke to Steve (@smk78) regarding to issue and I'll quickly recap here the outcomes:

- The Mantid wiki for SANS is very outdated, referring only to the old GUI and obsolete information. This will be removed
- In it's place the documentation will move into .rst files so we can keep it up to date as updates progress. This reduces the burden on both ourselves and instrument scientists
- We greatly welcome any documentation they wish to contribute, and I've discussed three ways which come to mind:

1. Scientists who feel comfortable and want to use Sphinx and .rst with Github accounts will be allowed to open pull requests to contribute their documentation
2. They can type up documentation in an alternative format if they prefer and pass it onto the SANS team who will convert it over.
2. Alternatively they could submit an email or issue with some text they would like add to the documentation and that will also be added.

It's important to stress that the documentation moving into .rst files is not meant to be a barrier. We encourage feedback from a "user perspective" and hope this change will significantly reduce the barrier of maintaining a separate wiki section
