### ISSUE TITLE
Indirect cannot load workspaces

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#22827]
### Expected behavior

Indirect interface should be able to load workspaces in `MSD`/`ConvFit`

### Actual behavior

Loading workspaces in `MSD`/`ConvFit` results in unexpected errors or even hard crashes

### Steps to reproduce the behavior

* Open Indirect > Data Analysis Interface
* Load `irs26176_graphite002_red.nxs` as described in [the documentation.](http://www.mantidproject.org/Indirect:Indirect_Data_Analysis)
* Click `Run`
* This generates three new workspaces, with _elf, _eq1, and _eq2 as their suffixes.
* Move to the `MSD` tab
* In the `Input` menu, select `Workspace`
* This should throw the unexpected exception dialog
* Try changing value in the interface, this should throw the unexpected exception dialog 

### Platforms affected

All

**Comment by brandonhewer** [comment]
Fixed by PR #22624
