### ISSUE TITLE
Update Inelastic Documentation

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22837]
**Original reporter:** Anthony Lim

The documentation for the inelastic interface is a bit out of date.

Some of these documents have been removed from the 

### Using Elwin

* This documentation is up to date, but needs example data

### Indirect Data Analysis

* This documentation needs updated screenshots
* The online instructions state that MSD operates on the eq_2 workspace. However, the interface only gives the option of loading eq workspace.

**Comment by AnthonyLim23** [comment]
need to update for simultaneous fitting too

**Comment by AnthonyLim23** [comment]
@Harrietbrown some more doc updates

**Comment by Harrietbrown** [comment]
Not Stale, Was on holiday when the notification was commented
