### ISSUE TITLE
Indirect data reduction fails

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#22858]
* You will need : `IRS21360.raw ` from the ISIS-Data set
* Open `Indirect` > `Data Reduction`
* Settings:
    * `Instrument` : `IRIS`
    * `Analyser` : `Graphite`
    *  `Reflection` : `002`
    *  `Run Files` : `21360` - note, if the file location is not on the Mantid path, then browse manually
    *  Click `Run`

```
No registered converter was able to produce a C++ rvalue of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > from this Python object of type NoneType
  at line 257 in 'C:/Users/BTR75544/nightly/MantidInstall/plugins/python/algorithms\WorkflowAlgorithms\ISISIndirectEnergyTransfer.py'
  caused by line 590 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
  caused by line 670 in 'C:/Users/BTR75544/nightly/MantidInstall/scripts/Inelastic\IndirectReductionCommon.py'
Unknown error starting next batch algorithm
Got error from algorithm "ISISIndirectEnergyTransfer"
Stopping batch algorithm because of execution error
```

**Comment by ElliotAOram** [comment]
@brandonhewer this failure is seen as a result of the `Custom` grouping mode being the default option in the gui. 
If left blank this then gets converted to `None` by the `_str_to_none` function in IndirectCommon. 
It is then passed to the grouping algorithm. Which does not expect the `None` type.
For fixing this, is it safe to assume if the custom option is left blank then we should just do no grouping (e.g. in this case `0-50`)

**Comment by SpencerHowells** [comment]
@ElliotAOram @brandonhewer I think 0-50 default is the best

**Comment by SpencerHowells** [comment]
@ElliotAOram We’ve got 0-50 wrong! It’s the min/max detector number as given in the gui. In this case 3-53.

**Comment by NickDraper** [comment]
Sam, can you pick this up from elliot for today
