### ISSUE TITLE
SANS algorithms missing unit tests

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#22867]
The following SANS algorithms don't seem to have any unit tests:

- [ ] SANSAbsoluteScale
- [ ] SANSAzimuthalAverage1D
- [ ] SANSBeamFinder
- [ ] SANSBeamSpreaderTransmission
- [ ] SANSDirectBeamTransmission
- [ ] SANSSensitivityCorrection

**Comment by mdoucet** [comment]
@ricleal and @jmborr, you might want to look into this since you're about to make changes to the workflow. Note that all of these are tested in system tests.
