### ISSUE TITLE
StartX in MSD Fit of Inelastic allows bad input values causes unexpected exception

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#22879]
### Expected behavior

Inputting a value for `StartX` that is greater than `EndX` should not be allowed

### Actual behavior

* One can enter greater values for `StartX` than `EndX` and run the fitting - resulting in an error.
* If one does this with `Plot Guess` checked, it results in an unexpected error and the error dialog. 

### Steps to reproduce the behavior

* Open `Indirect` > `Data Analysis`
* Go to the `MSD` tab
* Load in the data file below
* Choose `Fit type`:`Gaussian`
* Check the `Plot Guess` box
* Set `StartX`:`4.00`
* An unexpected error is thrown
[irs26176_graphite002_elwin_eq.nxs.zip](https://github.com/mantidproject/mantid/files/2184041/irs26176_graphite002_elwin_eq.nxs.zip)

### Platforms affected

All

**Comment by AnthonyLim23** [comment]
we had a similar problem in the ALC last release and the solution was to swap the values

**Comment by ElliotAOram** [comment]
The best solution to this issue would be to make a change in the fit property browser that `startX` can never be more than `endX`. Anthony made a good point that if a user enters a `startX` that is more than `endX`, you could swap the two values. This is in my mind the best solution, but you do need to be careful about initialisation.

**Comment by SpencerHowells** [comment]
@ElliotAOram I would prefer a check that startX<endX. These values are linked to vertical lines in the miniPlot so swapping might cause a problem there.

**Comment by ElliotAOram** [comment]
@SpencerHowells What's your preferred approach if a user attempts to make `startX` larger than `endX`? Should `startX` not change and we give a warning?

**Comment by SpencerHowells** [comment]
@ElliotAOram not change & give a warning.
