### ISSUE TITLE
Project Recovery - Full automated recovery

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#22878]
Add fully automated recovery. This includes

- Adding a *Yes* option to the recovery dialog box
- Opening the script editor and automatically executing the `OrderedWorkspaceHistory` script
- Re-opening any GUIs once the script finishes
- Removing any extra workspaces which were produce in the course of this

**Comment by martyngigg** [comment]
@DavidFair Could you add a bit more detail in to the issue to describe exactly what we mean by "fully automated recovery"? This is mainly for historical reference now.

**Comment by DavidFair** [comment]
Added - I completely forgot about coming back to add the description once I created the issue
