### ISSUE TITLE
Create a loader for DNS PSD event data

### ISSUE THREAD

**Issue by mganeva** [mantidproject/mantid#22871]
Request from DNS instrument scientists: `LoadDNSEvent` algorithm to load the data from the new PSD detector to a Mantid `EventWorkspace`.

The event data are in qmesydaq listmode (binary) format.

@thomueller  will work on it.

**Comment by mganeva** [comment]
@thomueller will work on it now

**Comment by martyngigg** [comment]
Fixed by #33301
