### ISSUE TITLE
Refine Stitch1D for point data

### ISSUE THREAD

**Issue by vreimund** [mantidproject/mantid#22921]
Sometimes, point data which do not overlap shall be stitched in order to simplify the reduction output, i.e. one workspace. In particular, Stitch1D throws in that case a RuntimeError
```
Stitch1D-[Error] Error in execution of algorithm Stitch1D:
Stitch1D-[Error] Stitch1D cannot have a StartOverlap > EndOverlap. StartOverlap: 0.052642825, EndOverlap: 0.044180824
Stitch1DMany-[Error] Error in execution of algorithm Stitch1DMany:
Stitch1DMany-[Error] Stitch1D cannot have a StartOverlap > EndOverlap. StartOverlap: 0.052642825, EndOverlap: 0.044180824
```

Maybe there is a way to only report the error once and not twice.

The corresponding image is

![comp](https://user-images.githubusercontent.com/19187274/42688617-47806650-869d-11e8-8a00-f4f7360fb8cf.png)

The actual work around is (simplified)

```
try:
    reduced = mtd[redSet[0]]
except KeyError:
    try:
        Scale(InputWorkspace=refl2, OutputWorkspace=refl2, Factor=factor)
        reduced = ConjoinXRuns(InputWorkspaces=[refl1, refl2])
    except ValueError:
        reduced = mtd[refl1]
```

**Comment by reimundILL** [comment]
This warning reads suspicious:
```
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.0400, Min is 0.0526, Max is 0.0436 . Forced to be: 0.0526
Stitch1D-[Warning] EndOverlap is outside range at 0.0600, Min is 0.0526, Max is 0.0436 . Forced to be: 0.0436
Integration-[Warning] Upper integration limit 0.0436363 for workspace index 0 smaller than the lower limit 0.0526497. Setting integral to zero.
Integration-[Warning] Upper integration limit 0.0436363 for workspace index 0 smaller than the lower limit 0.0526497. Setting integral to zero.
Divide-[Warning] Division by zero: the RHS is a single-valued vector with value zero.
Stitch1D-[Warning] Calculated scale factor is: -nan. Check that in both input workspaces the integrated overlap region is non-zero.
Stitch1D-[Notice] Scale Factor Y is: -nan Scale Factor E is: -nan
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.02 seconds
```

**Comment by reimundILL** [comment]
There seem to be a bug: in `Stitch1D` user inputs `StartOverlap` and `EndOverlap` will never be considered:
- startOverlapBeyondRange and endOverlapBeyondRange are always true
- it will be always intersectionMin or intersectionMax no matter what input the user given

**Comment by reimundILL** [comment]
The `StartOverlap` is minimum 2, `EndOverlap` is maximum 7:
Workspace consists of different regions: lhs, overlap, rhs
-> changing the `EndOverlap` to 5, 6, 7 should result in stepwise earlier start of rhs region (5's).
-> increasing the `StartOverlap` stepwise should result in a stepwise later start of the overlap region.

**Comment by reimundILL** [comment]
The latter change breaks `Stitch1DManyTest`
- test_three_workspaces
- test_groups_with_single_workspace
- test_two_groups_with_three_workspaces_scale_factor_from_period
- test_groups_containing_single_workspaces_scale_factor_from_period
