### ISSUE TITLE
Bug in plotSpectrum with distribution flag

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#23006]
* Open MantidPlot
* Ensure that your 2D plot settings `Normalise Histogram to Bin Width` is set ON
* Run the following (or on any other histogram workspace)
```
sxd = Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767', LoadMonitors='Exclude')
wav = ConvertUnits(sxd, Target='Wavelength')
plotSpectrum(wav, [0], distribution=1)
plotSpectrum(wav, [0], distribution=0)
```
* Both plots are identical. i.e. distribution flag is ignored.
* Now uncheck the setting in Mantid plot and repeat. **This time the distribution flag is used**

This is probably caused by this: https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/Mantid/MantidUI.cpp#L3541

**Comment by NickDraper** [comment]
Moved out of this release.

This is still important, but should be merged to master, not Release-next
