### ISSUE TITLE
Crash doing Show Detectors on a workspace without an instrument

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23018]
### Expected behavior
Mantid should not crash. I'm not sure if Show Detectors menu option should be available for this workspace

### Actual behavior
Mantid crashes

### Steps to reproduce the behavior
- Set up mantid to use the parameters file from #22997 and start mantid
- Run this script:
```
Load(Filename='OFFSPEC00044913', OutputWorkspace='OFFSPEC00044913')
ExtractPolarizationEfficiencies(InputWorkspace='OFFSPEC00044913_1', OutputWorkspace='efficiencies_1')
```
Right-click on `efficiences_1` and select Show Detectors. Mantid crashes.

### Platforms affected
Ubuntu 16.04, probably all

**Comment by gemmaguest** [comment]
I get similar behaviour with `LoadILLPolarizationFactors` in v3.12.1. Run the [usage example](http://docs.mantidproject.org/nightly/algorithms/LoadILLPolarizationFactors-v1.html#usage), right-click on `pol_factors` and Show Detectors and mantid crashes.

**Comment by mantid-roman** [comment]
Any workspace without attached instrument will make mantid crash

**Comment by gemmaguest** [comment]
Ah, yes. `CreateWorkspace` followed by Show Detectors crashes too.

**Comment by AndreiSavici** [comment]
Merged into release-next
