### ISSUE TITLE
AlgorithmDialog should not call validateInputs on group

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23021]
When you open an algorithm dialog on a group, validateInputs gets called on the WorkspaceGroup when it tries to do the validation for the dialog. However, when you execute the algorithm, validateInputs gets called on the individual members of the group. This makes it confusing and difficult to manage, e.g. in issue #22933 there is no obvious way to handle the WorkspaceGroup for the IndexProperty. It would make more sense if validateInputs was only ever called on the group members.

### Steps to reproduce the behavior
Follow the instructions in #22933 

### Platforms affected
All

**Comment by rosswhitfield** [comment]
Some algorithms validate the input as a WorkspaceGroup, _e.g._ `Stitch1DMany`

I think you need to do something like our original solution (#60) that validateInputs just return if it receives a WorkspaceGroup in algorithms that have this problem.

**Comment by gemmaguest** [comment]
It would be great if this could be made less error-prone somehow. I found another bug caused by the same confusion (#23061). In that one we also have the opposite problem in that we'd like to disallow WorkspaceGroups, but if we do that in validateInputs then it doesn't get called (on the group) when being run from a script.
