### ISSUE TITLE
ISIS Reflectometry Interface - Runs Table Theta Auto-fill

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23036]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

It is potentially possible to load theta based on run numbers entered into the table as they are
entered. Below is a python script which demonstrates this. Loading the file using the hdf library
or the C++ equivalent (`NeXusFile.h` or similar), is considerably faster than using mantid to load the
file as a workspace and then examining the logs.

```py
import h5py
filename = "foo"
data = h5py.File(filename, "r")
print(data['raw_data_1']['selog']['Theta']['value'][0])
```

This should be possible by hooking into the implementation of `RunsTablePresenter::notifyCellTextChanged`.

While working on this it may be appropriate to reconsider the restrictions on theta matches when merging
runs from ICat during autoprocessing and whether we should also try and get theta from the file.

**Comment by gemmaguest** [comment]
Closing because this is low priority and we are unlikely to get around to it. It was a developer suggestion rather than a request from users.
