### ISSUE TITLE
ISIS Reflectometry Interface - Handle name generation for sliced workspaces.

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23034]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

In `SlicedReductionWorkspaces.cpp` there is a pair of functions which are used to generate
the workspace names (`workspaceNamesForSliced`, `postprocessedWorkspaceNameForSliced`). They currently lack an implementation, this is partially due to a lack of
information around the correct behaviour of the `SlicingByEventLog` slicing. Should the workspace
names and/or time slices be based on the list of values provided or the times where the event log
shows these values?

This issue is to correctly implement these functions.

**Comment by gemmaguest** [comment]
This is no longer required because slicing is no longer being done in the GUI - it will be done in a dedicated algorithm instead
