### ISSUE TITLE
ISIS Reflectometry Interface - Display per-theta defaults in runs table

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23039]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

It would be good to display the per-theta defaults which will be used for each row in the
`JobTreeView` table. This can be achieved by using the methods provided in the `JobTreeView`
framework to set the content text, (another method may need to be added to set the foreground text colour).

Flags for tracking whether the value has been modified by the user should *not* be added to the reduction
configuration (this information is not necessary for reduction, nor do we wish to save it) or the
Batch/Cell.h class, instead a separate data-structure should be added to the `RunsTablePresenter`.

**Comment by gemmaguest** [comment]
Closing because this is low priority and we are unlikely to get around to it. It was a developer suggestion rather than a request from users.
