### ISSUE TITLE
Mantid crash fitting Muon data

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#23031]
**Original reporter:** Thomas Jubb

### Expected behavior

Mantid should not crash - it does not crash in the previous version of Mantid.

### Actual behavior

Mantid hard crashes

### Steps to reproduce the behavior

There are two *different* routes that produce *different* crashes:

* Open the Muon Data Analysis interface
* Go to the home tab and select instrument MUSR
* Ensure that you have access to the archive
* Load run 62260
* In the Data Analysis tab “TF Asymmetry Mode” should be ticked
* Set the “Groups/Pairs to fit” to “Custom”
* A pop-up should appear and make sure that only “fwd” is ticked
* Close the pop-up
* Add a “Flat Background” and “GausOsc” functions.
* Run a fit

----

* Open the Muon Data Analysis interface
* Go to the home tab and select instrument MUSR
* Ensure that you have access to the archive
* Load run 62260
* In the Data Analysis tab “TF Asymmetry Mode” should be ticked
* Set the “Groups/Pairs to fit” to “Custom”
* A pop-up should appear and make sure that only “fwd” is ticked
* Close the pop-up
* “GausOsc” function only.
* Run a fit

### Platforms affected

OSX, Windows

**Comment by AnthonyLim23** [comment]
bug fix 1:

using one group and one period in multi fit mode would crash

**Comment by AnthonyLim23** [comment]
bug fix 2:

Check the function in ConvertFitFunctionForMuonTFAsymmetry

**Comment by AnthonyLim23** [comment]
bug fix 3:

zero for normalization gives an error
