### ISSUE TITLE
ISIS Reflectometry Interface - Instrument Presenter Tidying

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23043]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

This is largely a rewrite similar to Experiment settings. The view components and interfaces can,
at least in part be adapted from those used in the original settings tab. Unlike `ExperimentPresenter` there
are less complications surrounding validation as most of this is performed within the widgets
themselves (see #23046 handling of empty/default values, and #23049 improve constraints)

To get more of an idea in the steps involved here, see the section on MVP and Architecture above and
look at the most recent changes to `22263_refl_gui_instancing`/ the implementation of the new
`ExperimentPresenter`.

*Estimated time*: 1-2 weeks.
*Required for*: Processing.

**Comment by gemmaguest** [comment]
Fixed by PR #23630
