### ISSUE TITLE
ISIS Reflectometry Interface - Set correct constraints for instrument and experiment setting inputs.

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23049]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

Use of a `QSpinBox` requires setting the number of decimal places, minimum and maximum values. The current implementation uses fairly relaxed constraints with 2.d.p. The proper values should be established for all numeric inputs and then set appropriately in the views.

For this the `.ui` files can and should be used if the min/max/dp is fixed and known at compile time. If it is
determined dynamically it should probably be determined in the presenter and passed in and set via
methods on the view.

We should also check whether a min/max constraint should be set on the angle and whether we want to set any constraints on the values entered in the stitch params and Options column.

**Comment by gemmaguest** [comment]
Closing because this is low priority and we are unlikely to get around to it. It was a developer suggestion rather than a request from users.
