### ISSUE TITLE
ISIS Reflectometry Interface - Handle Cross Presenter Communication

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23041]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

It is desirable to keep the code behind individual tabs in the GUI relatively modular. However, it
is sometimes necessary for the presenters to communicate events about their internal state to other
tabs.

Specifically:
- [x] When slicing is enabled/disabled the `ReductionJobs` model should be sliced or unsliced according to the the slice settings. This requires sending a call from `EventPresenter` to `RunsTablePresenter` via `BatchPresenter` - no longer required because slicing has been moved out of the GUI logic into an algorithm.
- [x] When ad-hoc processing is started/stopped all tabs in the batch need to be informed so that editing can be disabled.
- [x] When autoprocessing start/stop is requested the `MainWindowPresenter` needs to give permission such that only one autoprocessing instance can run at any one time. *No longer required because the new batch structures means we can allow autoprocessing in each batch*
- [x] Instrument Synchronization. It may be better to handle this indirectly through the default instrument config property and a `ConfigPropertyObserver`. However this would have to be replaced if we want to support different batches using different instruments. For now I have kept the original inter-presenter communication.

Rather than using the `IMainWindowPresenter` interface for all of these it may make more sense to create separate interfaces for each of these notification categories. This could make the creation of mock objects for testing easier.

**Comment by gemmaguest** [comment]
Fixed by PR #24384
