### ISSUE TITLE
Pick detector has stopped working on Instrument View

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#23079]
### Expected behavior
I should be able to pick a detector and the miniplot gets fixed on that particular detector.

### Actual behavior
It does not get fixed.

### Steps to reproduce the behavior
 - Open the instrument view
 - Change to the pick tab
 - Choose the detector picker
 - Attempt to pick a detector.

### Platforms affected
All

**Comment by martyngigg** [comment]
I believe this works as intended. The right-click "Store Curve" option is there to keep curves should it be necessary.
