### ISSUE TITLE
Mantid crashes on viewing ARGUS instrument hierarchy

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#23081]
### Expected behavior
ARGUS instrument hierarchy can be viewed in instrument view instrument tab.

### Actual behavior
Crashes when one attempts to open instrument hierarchy.

### Steps to reproduce the behavior
Load an ARGUS file, view its instrument, go to instrument tab, click on instrument name to view hierarchy of components. 

### Platforms affected
Windows 7 at least

**Comment by AnthonyLim23** [comment]
\\ISIS\inst$\NDXARGUS\Instrument\data\cycle_15_4\ARGUS00060892.nxs
