### ISSUE TITLE
Slice Viewer: Adding peaks workspace in non-orthogonal view adds them to wrong position

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#23085]
### Expected behavior
Regardless of how I overlay peaks workspaces in the slice viewer I should be able to see the peaks position in the correct position.

### Actual behavior
If I open the slice viewer, overlay a peaks workspace, then change to non-orthogonal view I get sensible output:

![screen shot 2018-07-25 at 08 24 41](https://user-images.githubusercontent.com/2487781/43185578-3933bd36-8fe4-11e8-9e03-9d4803aba895.png)

If I open the slice viewer, then change to non-orthogonal view, then overlay a peaks workspace *after* I've changed the peaks get put in the wrong place:

![screen shot 2018-07-25 at 08 25 24](https://user-images.githubusercontent.com/2487781/43185615-4eb23a02-8fe4-11e8-9db2-467eb16eeb70.png)

### Steps to reproduce the behavior
Here's a script to reproduce the data I used. The peaks workspace is attached below:
[peaks.nxs.zip](https://github.com/mantidproject/mantid/files/2226937/peaks.nxs.zip)

```python
Load(Filename='SXD30895.raw', OutputWorkspace='SXD30895')
Load(Filename='peaks.nxs', OutputWorkspace='peaks')
CopySample(InputWorkspace='peaks', OutputWorkspace='SXD30895', CopyName=False, CopyMaterial=False, CopyEnvironment=False, CopyShape=False)
ConvertToDiffractionMDWorkspace(InputWorkspace='SXD30895', OutputWorkspace='md', OneEventPerBin=False, OutputDimensions='HKL', LorentzCorrection=True)
```
Once the script is run, Follow the instructions above on the `md` workspace.

### Platforms affected
All

**Comment by martyngigg** [comment]
@NickDraper Do we have an issue for the non-orthogonal axes on sliceviewer in workbench? I'd like to reference this so we have a test case for when implementing the peaks on non-orthogonal axes in the workbench sliceviewer.
