### ISSUE TITLE
Instrument View: applying mask shapes from a table no longer works

### ISSUE THREAD

**Issue by samueljackson92** [mantidproject/mantid#23080]
### Expected behavior
I should be able to save mask shapes to a table workspace, then reapply them to a new instrument view

### Actual behavior
For mask shapes only (not group or ROI) I nothing happens when I drag the table workspace from the ADS to the Instrument View

### Steps to reproduce the behavior
 - Open the instrument view
 - Change to the draw tab
 - Draw a mask
 - Save shapes to table
 - Close & reopen the Instrument view
 - Drag the table workspace over the view.

### Platforms affected
All

**Comment by aybamidele** [comment]
Can't reproduce
