### ISSUE TITLE
LoadMonitors is not documented in the Load/LoadILLTOF 

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mantid#23090]
### Expected behavior
Documentation for Load/LoadILLTOF should have the `LoadMonitors` parameter.
### Actual behavior
It's not there
### Steps to reproduce the behavior
`Load(Filename='164198.nxs', LoadMonitors=True, OutputWorkspace='data')` runs correctly
### Platforms affected
All

**Comment by NickDraper** [comment]
LoadIllTOF does not support LoadMonitors, which is why it is not in the documentation.

When you call it via Load you get the following warning ing the log

```
You've passed a property (LoadMonitors) to Load() that doesn't apply to this file type.
```
