### ISSUE TITLE
Clarify ReflectometryILLConvertToQ and ConvertToReflectometryQ differences

### ISSUE THREAD

**Issue by ianbush** [mantidproject/mantid#23105]
To make it easier for users to understand which algorithms they should use `ReflectometryILLConvertToQ` and `ConvertToReflectometryQ` should reference each other in the documentation, and briefly describe the differences (`ReflectometryMomentumTransfer` should probably also be included in the differences).

**Comment by soininen** [comment]
I'll work on this.
