### ISSUE TITLE
Muon - Crash Caused By Grouping Tab

### ISSUE THREAD

**Issue by TWJubb** [mantidproject/mantid#23120]
**Original reporter:** nobody

Steps to reproduce the crash
----------------------------

- Open MuonAnalysis (Interfaces->Muon->Muon Analysis).
- Go to Settings tab, make sure "Load All Groups" and "Load All Pairs" are both checked.
- Go back to the Home tab, select EMU as the instrument, hit the Load Current Run button.
- Go to the Grouping Tab, change "Asymmetry" to "Counts" under the grouping table.

On Windows this causes Mantid to throw an exception and terminate

**Comment by AnthonyLim23** [comment]
This is unlikely to happen in a real work flow. The ``load all`` options exist to help load data in to the Frequency domain analysis, which deals with asymmetry.
