### ISSUE TITLE
Tiled plot crashes in I(QT) Widget of Indirect Data Analysis

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#23183]
**Original reporter:** Saghamitra

### Expected behavior

Mantid should not freeze or crash.

### Actual behavior

Mantid freezes or crashes

### Steps to reproduce the behavior

* In Indirect > Data Analysis go to MSD tab
* Load data `iris26184_multi_graphite002_elwin_eq.nxs` - available in the zip below
* Choose Fit Type = Gaussian
* Choose Run
* After the run choose Plot Data
* This should result in an uncaught exception error - this is documented in another issue (#23164)
* Choose `Do not share information` and `Continue working`
* Go to the I(Q,T) window and load
    * Sample: `iris26184_multi_graphite002_red.nxs`
    * Resolution: `irs26173_graphite002_res.nxs`
* Choose Run - this process gets stuck and Mantid hangs
* Note the process does not hang if one does not have the first error in the MSD interface

[Archive.zip](https://github.com/mantidproject/mantid/files/2257638/Archive.zip)

### Platforms affected

All

**Comment by SpencerHowells** [comment]
@keeeto @robertapplin what happens when you run I(q,t) on its own? Ie not after a crash. This should establish whether it is a problem in I(q,t) or a consequence of the crash.

**Comment by keeeto** [comment]
@SpencerHowells - it runs fine without the previous crash. 
I think that fixing #23164 should cover this one too.

**Comment by robertapplin** [comment]
This has been fixed by #23441
