### ISSUE TITLE
save state of ALC interface

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#23207]
Save the state of the ALC interface

**Comment by AnthonyLim23** [comment]
we would like to be able to do this. @robertapplin do you think it would be difficult to adapt https://github.com/mantidproject/mantid/pull/30544 to work with project save?

**Comment by robertapplin** [comment]
It would probably be possible

**Comment by AnthonyLim23** [comment]
we want to keep this open
