### ISSUE TITLE
Remove non-sync scan from DetectorInfo

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#23238]
[DetectorInfo](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfo.h#L125) currently supports two modes of scanning detectors.

1. Time intervals are bespoke per detector. 
2. Time intervals are global. This is the synchronised (sync) scan.

**We only need to support the latter**. The ILL do not use the former, and the latter is more memory efficient. This means that bits of the API such as [this](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfo.h#L125) and the mechanisms behind them can be removed. Remember to remove from both `Geometry::DetectorInfo` and `Beamline::DetectorInfo` [here](https://github.com/mantidproject/mantid/blob/master/Framework/Beamline/inc/MantidBeamline/DetectorInfo.h)

@SimonHeybrock might be able to provide more detail on this. We should also get a review from the ILL on this.

**Comment by SimonHeybrock** [comment]
@OwenArnold Do we have a solution for the case of monitor data that does not distinguish between scan intervals? Do we need a solution?

**Comment by OwenArnold** [comment]
@SimonHeybrock good point, we probably need one. I'm not sure that one exists.
