### ISSUE TITLE
Monitor should be spcified by number i.e. M3/M4  not spectrum number

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#23308]
The monitor to use for a reduction should be specified by selecting M3/m4 rather than a spectrum number as several of the monitor spectrum numbers are odd and hard to remember.

**Comment by Mantid-Matthew** [comment]
Having investigated this I need to speak to the scientists some more. The transmission spectrum is specified in the user file. To convert this to a monitor number I then need to know the monitor to spectrum mapping. You can't know for certain the monitor to spectrum mapping until after some data is loaded however as you need a date to know which IDF to use.

**Comment by smk78** [comment]
On review, several members of the SANS Group expressed concern about this and would like more more information about how it is planned to be implemented. What happens if they change monitor spectrum numbers, or if they use a ROI of several spectra for the transmissions, for example?

**Comment by smk78** [comment]
Requires further discussion between the SANS Group & @DavidFair
