### ISSUE TITLE
Muon - Load Widget

### ISSUE THREAD

**Issue by TWJubb** [mantidproject/mantid#23324]
This issue links to #20943, #23322, #23323

The new loading widget for the Muon GUI is built as a two-tiered MVP pattern, this isue tackles the top level MVP, which holds within it two widgets #23322, #23323.

To avoid concurrancy issues, or extra code to keep these widgets synchronized with the data they have loaded, they will share an underlying model; this way the widget which performs a change only has to notify the parent widget of the change, the parent widget then notifies all widgets to update their view. This brings the additional benefit of being able to add/remove loading sub-widgets without affecting the functionality of the rest of the widget.

~~The widget will be fully multi-threaded, with an option to show a progress bar when loading multiple files.~~ *This functionality was removed in favour of single threading via the thread_model.py class*

The user can explicitly choose load a single file (single file mode) or multiple files (mutltiple file mode).

With thorough unit tests this widget should be very stable and robust against accidental misuse. 

Although essentially a container for smaller widgets which perform the actual loading, there will be some independent functionality in this widget. The functionality it will have : 
- A Checkbox to choose between single/multiple file mode, defaulted to single file mode to match the current GUI (multiple file mode is also in the current GUI, however is not made explicitly clear to the user)
- A combo-box which allows a selection of specific load behaviours in multiple file mode. For example, the user may want to load 100 runs and add them all together (so called co-add mode). I will not implement this in this issue, but allow for it to be implemented at a later stage.

**Comment by AnthonyLim23** [comment]
After discussion with muon group; we should place the file widget below the load run widget
