### ISSUE TITLE
Muon - Update Python Code to qtpy

### ISSUE THREAD

**Issue by TWJubb** [mantidproject/mantid#23335]
The new Muon GUI being developed in python should use `PyQt5`, but remain compatible with `PyQt4`, and for that reason we should use `QtPy` (https://pypi.org/project/QtPy/).

This issue requires the updating of all relevant Muon GUI files to `QtPy`

**Comment by AnthonyLim23** [comment]
dont need to update (will delete these later):
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/dummy_label/dummy_label_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/context_example/context_example_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/dummy/dummy_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/MuonAnalysis/dock/dock_widget.py


files to update:
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/grouping_table_widget/grouping_table_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/home_runinfo_widget/home_runinfo_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/message_box.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/load_file_widget/view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/mock_widget.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/thread_model.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/load_run_widget/load_run_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/home_plot_widget/home_plot_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/load_widget/load_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/home_grouping_widget/home_grouping_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/help_widget/help_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/home_instrument_widget/home_instrument_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/dock/dockable_tabs.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/dock/dock_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/checkbox.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/run_selection_dialog.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/pairing_table_widget/pairing_table_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/utilities/table_utils.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/home_tab/home_tab_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis_2.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/Transform/transform_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/Transform/transform_widget.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/TransformSelection/transform_selection_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/TransformSelection/transform_selection_widget.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_widget.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_widget.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/MuonAnalysis/load_widget/load_widget_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/Peaks/peaks_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/PeriodicTable/periodic_table.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/PeriodicTable/periodic_table_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/PeriodicTable/PeakSelector/peak_selector_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/ElementalAnalysis/Detectors/detectors_view.py
https://github.com/mantidproject/mantid/blob/master/scripts/Elemental_Analysis.py
https://github.com/mantidproject/mantid/blob/master/scripts/Frequency_Domain_Analysis.py
https://github.com/mantidproject/mantid/blob/master/scripts/Frequency_Domain_Analysis_Old.py
