### ISSUE TITLE
Remove ILL training from documentation

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#23409]
The ILL specific training (everything in `docs/sources/tutorials/ill_training`) should be removed from the source tree. It is just a very short version of Mantid Basic Course and there is no need to duplicate the information.

**Comment by keeeto** [comment]
@soininen If you like I can roll this in with the PR that you were reviewing? #23363

**Comment by soininen** [comment]
@keeeto That's a nice idea.

**Comment by soininen** [comment]
Issue was fixed in PR #23363
