### ISSUE TITLE
Live data monitor hangs in nightly

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23406]
**Original reporter:** nobody

### Expected behavior
The live data monitor should not hang

### Actual behavior
The live data monitor hangs and cannot be cancelled. This seems dependent on the update interval - for me it's ok if 10 seconds but hangs if 60 seconds.

### Steps to reproduce the behavior
- Set the facility to TEST_LIVE
- Set the instrument to ISIS_Histogram
- Run FakeISISHistoDAE and then start live data (settings in screenshots below - note the interval is 60 seconds)
- Wait 60 seconds until you see the `Loading live data chunk` message. It never gets any further (whereas in v3.13.0 it progresses to run `LoadInstrument`).
- Try to cancel the algorithm from the algorithm progress dialog. It says `Cancelling` but never exits. 

![bad_cast_dae](https://user-images.githubusercontent.com/12895056/44925157-70b41980-ad45-11e8-99fd-5d35aa9cf72e.png)

![bad_cast_live_data](https://user-images.githubusercontent.com/12895056/44925188-980ae680-ad45-11e8-8d77-f80c0299b398.png)

### Platforms affected
Seen on Ubuntu 16.04 in nightly at commit bed0955f. The problem doesn't occur in v3.13.0

**Comment by NickDraper** [comment]
fixed by #27077
