### ISSUE TITLE
Muon - Grouping Table Widget

### ISSUE THREAD

**Issue by TWJubb** [mantidproject/mantid#23436]
The new Muon GUI has a "Grouping/Pairing" tab (see #21957), which will be structured as a nested MVP pattern, the top level MVP will be the tab itself, essentially a thin container which contains sub-widgets and facilitates communication between them.

This issue requires the grouping table sub-widget, written in MVP. It will replicate the functionality of the current grouping table.

*This comment will be updated with required functionality as the code develops.*

See also #23437

**Comment by AnthonyLim23** [comment]
In terms of functionality I think the following would be good:

1. A parent widget (in the tab) that contains a combo box of instruments, when we change this and select a run it loads the appropriate default grouping into the table (child)
2. When a valid group is added/edited we send it to the parent and get the parent to print it to screen.

**Comment by AnthonyLim23** [comment]
After discussion with the Muon group we should add an excluded detectors list (these will be removed from the grouping table prior to processing but will still be displayed). It has been suggested that we replace `N dets` with `total number of detectors` and add another column called `number of included detectors` (we can change the names)
