### ISSUE TITLE
Indirect - Monte Carlo Errors Slow in Data Analysis I(Q,t) 

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#23474]
### Actual Behaviour
The errors for the Monte Carlo method on the `I(Q,t)` Tab of Indirect Data Analysis take a long time to be calculated.

### Expected Behaviour
- An option to 'turn off' the calculation of Monte Carlo Errors should be available.
- A progress bar to tell you how far through the Monte Carlo calculation you are

### Steps to reproduce the behavior
1. `Interface`->`Indirect Data Analysis`->`I(Q,t)` Tab
2. Load Data
3. Set `Number of Iterations` to 300
4. Click `Run` - Slow!

### Platforms affected
All

**Comment by SpencerHowells** [comment]
Also add a Progress Bar for The MC part showing which spectrum is being calculated.
