### ISSUE TITLE
Indirect - Wrong units in MSD Fit Plot Result

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#23493]
**Original reporter:** Spencer

### Expected behavior
The units on the x axis when you click `Plot Result` on the `MSD Fit` tab should be in temperature.
There should be a drop-down list of parameters next to the `Plot Result` button.

### Actual behavior
The units on the x axis are in q value (or just empty).

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect Data Analysis`->`MSD Fit` Tab
2. Load in the data below
3. Select `Gaussian` as the Fit type
4. Click `Run` and wait for it to finish
5. Click `Plot Result`
6. X axis units are wrong

**Data Files**
[osi104367-104371_graphite002_red_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2393408/osi104367-104371_graphite002_red_elwin_eq.zip)

### Platforms affected
All

**Comment by SpencerHowells** [comment]
Can you change the Plot Result button to a drop-down list of parameters at same time.
