### ISSUE TITLE
Segmentation fault with SliceViewer

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#23562]
I've tried to generate some fake MD workspace for an issue, but when I try to look at the workspace with SliceViewer MantidPlot just crashes.
**Original reporter:** [username facility]/[nobody]. 

### Steps to reproduce the behavior
Run the following:
```python
mdws = CreateMDWorkspace(Dimensions=2, Extents='-10,10,-10,10', Names='A,B', Units='U,U')
for x in range(2):
    FakeMDEventData(InputWorkspace=mdws, PeakParams='500000,'+str(x)+',0,3')
```
then use SliceViewer to look at the data.

If I run `FakeMDEventData` only once, everything is fine.

### Platforms affected
Tried it on my Ubuntu 18.04 build, and on RHEL7 both the 3.13 release and the nightly

**Comment by DavidFair** [comment]
I've just double checked this issue against the current master and it appears to be fixed

**Comment by peterfpeterson** [comment]
Still doesn't work for me

**Comment by AndreiSavici** [comment]
I still have the same issue, both in Ubuntu 18.04 and on the RHEL 7 analysis cluster

**Comment by AndreiSavici** [comment]
But it works in the new workbench/ new sliceviewer

**Comment by DavidFair** [comment]
So it's Mantid Plot / Slice viewer which segfaults?
Sorry about closing this prematurely, should have checked both workbench / plot

**Comment by NickDraper** [comment]
Ok that is clarified, but if it is only mantidplot I'll remove it from this milestone

**Comment by martyngigg** [comment]
This appears to be an issue in the framework when it tries to compute a line plot array. Stacktrace:
```
Thread 1 "MantidPlot" received signal SIGSEGV, Segmentation fault.
0x00007fffede323d5 in Mantid::DataObjects::MDEventWorkspace<Mantid::DataObjects::MDLeanEvent<2ul>, 2ul>::getLinePlot (this=0x7fff7400ff40, start=..., end=..., normalize=Mantid::API::VolumeNormalization)
    at ../../Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.tcc:825
825	        if (!box->getIsMasked()) {
(gdb) bt
#0  0x00007fffede323d5 in Mantid::DataObjects::MDEventWorkspace<Mantid::DataObjects::MDLeanEvent<2ul>, 2ul>::getLinePlot(Mantid::Kernel::VMDBase<float> const&, Mantid::Kernel::VMDBase<float> const&, Mantid::API::MDNormalization) const (this=0x7fff7400ff40, start=..., end=..., normalize=Mantid::API::VolumeNormalization) at ../../Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.tcc:825
```
The `box` pointer is null -> :boom:

**Comment by martyngigg** [comment]
The fix is a simple pointer check so I'm going to push this as crashing is not good for users.
