### ISSUE TITLE
IndirectILLReductionQENS to support different axes for sample and container

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#23629]
Turns out it can happen that the container and the sample data are taken with different doppler maximum energies. The algorithm currently forbids this, but should be extended. It should `RebinToWorkspace` the container to sample workspace, and vanadium container to vanadium workspace.

**Comment by SpencerHowells** [comment]
Should the Rebin range be common to both sample & container? Eg, Emax would be the minimum of Emax-sample & Emax-container
