### ISSUE TITLE
Instrument view throws uncaught exception (ZOOM)

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#23633]
**Original reporter:** Diego Alba Venero (ISIS)
### Expected behavior
One should be able to pick any section of instrument view with no difficulty

### Actual behavior
Mantid throws an unhandled exception when picking some sections of the instrument

### Steps to reproduce the behavior
* Load the file below
[4475.nxs.zip](https://github.com/mantidproject/mantid/files/2420399/4475.nxs.zip)
* Open the instrument view
* Switch the viewpoint to cylindrical Y
* Change to the `Pick` tab
* Select the `Draw a rectangle` tool
* Try to draw a rectangle in the view
* Mantid throws an exception

### Platforms affected

Windows, OSX

**Comment by Mantid-Matthew** [comment]
This issue is no longer replicatable.
