### ISSUE TITLE
Muon - Muon Analysis 2.0 Home Tab, Grouping Tab, Load Widget

### ISSUE THREAD

**Issue by TWJubb** [mantidproject/mantid#23642]
This issue will be attached to a branch containing the Home Tab, Grouping Tab and Load Widgets for the new Muon analysis interface. 

Smaller branches will be created from this branch to hold small PR's which will be merged sequentially into master.

Entries marked with ❗️ should be reviewed first, as they either have no dependencies or their dependencies are already merged.

List of PRs
===========

### New Muon Algorithms

There are four new muon algorithms; their functionality reproduces the over-sized `MuonProcess` algorithm, by splitting it up into smaller, more conceptually distinct chunks. This will fulfil the user requirement of being able to use the Python script window to reproduce the workflows used in the interface. It will also make the interface code much more readable and maintainable in the future.

- ~Pre-requesites : PR #23677~
- ~MuonPreProcess : PR #23678~
- ~MuonGroupingCounts : PR #23679~
- ~MuonGroupingAsymmetry : PR #23680~
- ~MuonPairingAsymmetry : PR #23681~

### Core Code and Utilities

Commonly used functionality shared between different widgets are refactored into their own modules/classes where appropriate. There are also several core class created to help with the new interface (for example encapsulating data into well documented classes; but also grouping all the data together into one place, the context).

The primary aim for this code is to be readable and stable; so `isinstance` checks are often present. Design patterns are used if necessary (for example the observer pattern necessary to tab to tab communication); but generally the code is kept as simple as possible.

- ~Muon Workspace Handle : PR #23644~
- ~Load Utilities : PR #23645~
- ~Groups and Pairs : PR #23643~
- ~Observer Pattern : PR #23647~
- ~Muon Context : PR #23648~
- ~Minor changes to the existing utilities : PR #23650~

### Load Widgets

The load widget handles loading files and/or instrument runs into the interface. To create a more modular widget; there are two small widgets which handle loading files via a browse button and loading files by their run number. These sit inside an overall parent load widget. Common functionality has been separated into utility modules.

- ~Load utilities : PR #23670~ 
- ~Load runs : PR #23412  PR #23672~ 
- Load files : ~PR #23371~ PR #23671 
- Load widget : ~PR #23425~ PR #23673 

### Grouping Tab Widgets

The grouping tab handles group and pair creation; and processing the raw data accordingly. Like the load widget; there are two smaller widgets (one for the group table and one for the pair table) which sit inside a parent widget, and which handles higher level functionality that affects both groups and pairs (such as creating workspaces, loading/saving the grouping information).

- Grouping Table : PR #23651
- Pairing Table : PR #23652
- Grouping Tab : PR #23653

### Home Tab Widgets

The home tab handles the same functionality as the home tab of Muon Analysis 1.0.

- Home Tab Instrument Widget : PR #23654
- Home Tab Grouping Widget : PR #23655
- Home Tab Plot and Run Info Widgets : PR #23656
- Home Tab : PR #23657
- Help Widget : PR #23658

### Embedding Widgets into Interface

The final step is to add the widgets into the interface itself so that it can be opened from the interfaces menu in MantidPlot. This requires connecting up the observer/subscribers which are seen throughout the widget code.

- PR : #23659 

Summary 
=======

[InterfaceDesign.pdf](https://github.com/mantidproject/mantid/files/2446698/InterfaceDesign.pdf)

![interfacedesign](https://user-images.githubusercontent.com/33163693/46480581-6922dd00-c7e9-11e8-8f73-a7d0b008801b.png)

![corecodestructure](https://user-images.githubusercontent.com/33163693/46480693-a5eed400-c7e9-11e8-8b47-f60bbae2c41c.png)

**Comment by keeeto** [comment]
After spending some time testing this I think that on the whole it works nicely. There are a few issues that could be cleared up

- [ ] Blue lines on interface in OSX (see figure at the end)
- [ ] The deadtime printed on the screen does not update after changing the loaded file
- [ ] An 'are you sure' dialog would be useful for the clear buttons
- [ ] Grouping tab allows numbers outside the range, this causes an error in the log, but remains in the GUI
- [ ] Failure to save a grouping file does not throw an error dialog
- [ ] Saving the grouping file requires explicit inclusion of `.xml`, this should be default
- [ ] Changing the value of alpha in the grouping tab switches `group/pair` from 'long' back to 'fwd' in the main window
- [ ] Load current run could be greyed out when unavailable
<img width="655" alt="screen shot 2018-10-02 at 16 07 54" src="https://user-images.githubusercontent.com/3697636/46357726-609d9b80-c65d-11e8-9a38-877e387437bd.png">

**Comment by TWJubb** [comment]
Comments from an instrument scientist : 

- [ ] GUI automatically sets splitter to minimize the empty vertical space.
- [ ] GUI opens with horizontal space automatically minimized.
- [ ] Bug : Instrument combo box should change to newly selected instrument immediately (rather than waiting for data to be loaded).
