### ISSUE TITLE
Preferences GUI for new workbench

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#23725]
With a clean mantid (no settings file), the default facility is not set. Some algorithms (e.g. DgsReduction) require the facility to be set.

To test: delete the `.mantid` folder in the user directory (or the equivalent on operating systems other than linux), and run `DgsReduction` on the `CNCS_7860` data from doctests.

**Comment by martyngigg** [comment]
Lets start with some minimal options organized into some sensible pages on the dialog
* facility/instrument selection
* visible algorithms/interfaces
* ask on close for saving projects

Spyder has quite a nice page-per-area ![page-per-widget layout](http://www.maths.lth.se/na/courses/NUMA22/media/spyder.png)

**Comment by martyngigg** [comment]
This could also be a good place to put things like the default editor content selection in #24580.
