### ISSUE TITLE
Add custom GUIs to workbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#23762]
1. Add new menus with existing registration mechanism (properties file) ~~#23761~~
2. Convert some number of custom interfaces to be qt4/qt5 compatible. This will show that they can work in workbench
  * reducers ~~#23927~~
 * `Frequency_Domain_Analysis.py` #21670 and `Elemental_Analysis.py` #23335
  * `ISIS_Reflectometry_Old.py`, `ISIS_SANS_v2_experimental.py`, 
  * C++ based guis
3. Create the registration mechanism [detailed here](https://github.com/mantidproject/documents/blob/master/Design/Workbench/design-classes.md#user-interface-registration)

**Comment by martyngigg** [comment]
We have done what we intend to do
