### ISSUE TITLE
Storing ParameterMap in NeXus files

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#23804]
The `ParameterMap` is currently string-serialised and stored in an `NXnote`: 
https://github.com/mantidproject/mantid/blob/0e1508d62cca12737f6b026a37d705118b952142/Framework/Geometry/src/Instrument/ParameterMap.cpp#L1105

The "correct" way to do this in NeXus would be to have an `NXparameters` class in each of the instrument components:
http://download.nexusformat.org/sphinx/classes/base_classes/NXparameters.html#nxparameters

For example, parameters associated with a detector would go in an `NXparameters` in the relevant `NXdetector`.

**Comment by zjttoefs** [comment]
Storing numbers as text in NXnote can certainly not be ideal, even for Mantid's own purposes.

NXparameters is a valid way of encoding arbitrary values. 

An alternative way would be to use NXcollection http://download.nexusformat.org/sphinx/classes/base_classes/NXcollection.html
that comes with the guarantee that there will be no validation or standardisation on what you want to put inside.

Both are better than strings in a note.
