### ISSUE TITLE
DirectILL: S(2theta, TOF)

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#23808]
**Original reporter:** Jacques Ollivier/ILL

For visualization purposes, the IN5 scientists would like to conveniently get the S(2theta, TOF). This could be realized by an algorithm which does the following steps:
1. `ConvertToConstantL2`
2. `ConvertSpectrumAxis` (spectrum numbers to theta)
3. `GroupDetectors` (group over Debye-Scherrer cones, width should be user-specifiable, defaulted to a nice instrument specific value)

**Comment by AndreiSavici** [comment]
Note that there is the [GenerateGroupingPowder](http://docs.mantidproject.org/nightly/algorithms/GenerateGroupingPowder-v1.html) that you might be able to use

**Comment by soininen** [comment]
@AndreiSavici I just remembered a similar commit from you on another issues and was going to mention `GenerateGroupingPowder` to the description :) I'll have a look at it, thanks for the reminder!
