### ISSUE TITLE
Crop OutputWorkspace of RROA

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23817]
**Original reporter:** Jos at ISIS

When processing a group of runs with the ISIS Reflectometry GUI, the individual run outputs from `ReflectometryReductionOneAuto` should be cropped before being stitched. Note however that they shouldn't be rebinned when being used for stitching, so we can't just use the `OutputWorkspaceBinned` output from RROA.

`OutputWorkspaceBinned` already gets cropped when the rebin is done, so we just need to crop `OutputWorkspace` to `MomentumTransferMin` and `MomentumTransferMax`.

We might need to version this change - check with Jos.

The flow diagram on the algorithm documentation may need updating, although the rebin step is not currently shown and the diagram could perhaps do with being split up/simplified.

**Comment by gemmaguest** [comment]
This has just been highlighted by scientists as being higher priority so I would like to take a look to see if we can get it into this release, if it's low risk (which I expect it to be)

**Comment by NickDraper** [comment]
Gemma can you make sure Jos knows that this is included in the release
