### ISSUE TITLE
Indirect - Bayes - ResNorm tab adjustments

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#23828]
**Original reporter:** Spencer

### Expected behavior
- Prevent extra Fit plot when you click `Plot` in the output options
- Include ability to load Sqw files for Vanadium
- SampleLogs – copy & add file-names for sample & resolution

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Bayes`->ResNorm tab

### Platforms affected
All

**Comment by SpencerHowells** [comment]
SampleLogs – copy & add file-names for sample & resolution
