### ISSUE TITLE
Make axis views in Instrument view consistent with Viz programs

### ISSUE THREAD

**Issue by mareuter** [mantidproject/mantid#2384]
This issue was originally [TRAC 1537](http://trac.mantidproject.org/mantid/ticket/1537)

The predefined axis views should operate in the same mode as ''VisIt'' and/or ''ParaView''. Both programs agree that the direction of the predetermined view is away from the observer. Also, the locations of the other axes should be aligned to the way these programs work. They both agree on the orientations for Z and Y, but not X, so for that one any choice will do. Also, the programs specify their labels with the signs in front, so we should make them consistent (i.e. +Z). Here are the orientations for the axes:

 * +Z: +Y up, +X left
 * -Z: +Y up, +X right
 * +Y: +Z up, +X right
 * -Y: +Z up, +X left
''ParaView''
 * +X: +Z up, +Y left
 * -X: +Z up, +Y left
''VisIt''
 * +X: +Y up, +Z right
 * -X: +Y up, +Z left

**Comment by NickDraper** [comment]
This is not a user requirement, and not worth the effort
