### ISSUE TITLE
Calculate vanadium absorption for POWGEN

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#23887]
Compare ADP for SiO2 when using `AbsorptionCorrection` (or the appropriate child) or `MonteCarloAbsorption` (or the appropriate child) with `CalculateCarpenterSampleCorrection`.

The example reduced data files will be:
1. The current reduction workflow (`CalculateCarpenterSampleCorrection` on vanadium, nothing for sample)
2. The current reduction workflow (`CalculateCarpenterSampleCorrection` on vanadium, nothing for sample), but with properly wavelength binned vanadium
2. `CylinderAbsorption` for the vanadium, nothing for sample (uses `AbsorptionCorrection` base class)
3.  `CylinderAbsorption` for the vanadium and sample, through `AbsorptionCorrection` for the container  (uses `AbsorptionCorrection` base class)
4. `SimpleShapeMonteCarloAbsorption` for the vanadium, nothing for sample (uses `MonteCarloAbsorption`)
5. `SimpleShapeMonteCarloAbsorption` for the vanadium, sample, and container (uses `MonteCarloAbsorption`)

In principle, these techniques can be pre-calculated (especially for the vanadium and containers) so performance will be less of an issue.

Bonus items for vanadium comparison. Since currently only the Carpenter equation does multiple scattering in an easy to use way for elastic. Therefore, there will need to be some extra comparisons of the correction for vanadium.

**Comment by SpencerHowells** [comment]
@peterfpeterson Attached is a review of absorption I did when Martyn was writing the MC code.
[Absorption_corrections.pdf](https://github.com/mantidproject/mantid/files/2524334/Absorption_corrections.pdf)
I also wrote the user friendly algorithm SimpleShapeMonteCarloAbsorption to do FlatPlate, Cylinder or Annulus.
