### ISSUE TITLE
JobTreeView multiple + signs in input leads to uncuaght exception

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#23974]
**Original reporter:** @Mantid-Matthew  

### Expected behavior

You should be able to enter any text you want in the cells

### Actual behavior

If you enter a long string containing two plus signs such as 

`sssssssss+dddddddddddddddddddddddddddddddddddd+ddddddddddd` an unexpected exception is thrown.

**Edit**
I don't believe the issue is that the string contains two plus signs. If you enter any data in a row you __can__ get a crash
E.g. load up SANS v2 interface, without loading a userfile click on "Output Name" and type "testname"
Then **press enter** (don't click away) and it will segfault

The issue is the action of pressing enter, not the data you entered

### Platforms affected
Windows, Ubuntu

**Comment by TTitcombe** [comment]
The cause of the uncaught exception is that `QModelIndex filteredModelIndex.model()` is neither a `nullptr` or equal to `QAbstractItemModel model`, in `StrictQModelIndices::fromFilteredModel`
