### ISSUE TITLE
Muon Algorithm tidying up once all merged

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#24010]
There are currently 4 Muon algorithms going through review. They ideally all want to reference each other in their seeAlso methods as in the text of their documentation however doing so before they are all merged leads to documentation errors. 

This issue is a reminder to go back once they are all merged and ensure that they all reference each other correctly.

**Comment by AnthonyLim23** [comment]
the algorithms are (and need to reference each other)
http://docs.mantidproject.org/nightly/algorithms/MuonPreProcess-v1.html
http://docs.mantidproject.org/nightly/algorithms/MuonGroupingCounts-v1.html
http://docs.mantidproject.org/nightly/algorithms/MuonGroupingAsymmetry-v1.html
http://docs.mantidproject.org/nightly/algorithms/MuonPairingAsymmetry-v1.html
