### ISSUE TITLE
Project saving segfaults when a workspace group contains a workspace of the same name

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#24100]
### Expected behavior

I think you should be able to have a group workspace contain a workspace of the same name or at least this behavior is not currently forbidden by Mantid. Given that workspaces and group workspaces are actually stored in a flat structure it perhaps should be and this may just be a case of this case breaking a whole load of things.

### Actual behavior

Mantid will segfualt when project saveing is attempted

### Steps to reproduce the behavior

Run this script and wait for project saving to attempt

```
dataX = [0, 1, 2, 3, 4, 5] * 4
dataY = [10, 20, 30, 20, 10] + \
        [20, 30, 40, 30, 20] + \
        [30, 40, 50, 40, 30] + \
        [40, 50, 60, 50, 40]
print(dataY)
input_workspace = CreateWorkspace(dataX, dataY, NSpec=4)

input_workspace = GroupWorkspaces(input_workspace)
```

**Comment by Pasarus** [comment]
Just spoke with Nick and currently the ADS is a flat hierarchy, which means that no two items should have the same name... i.e. it should not be allowed for a WorkspaceGroup and a Workspace2D for example to have the same name, or any two objects inside the ADS.
