### ISSUE TITLE
Clean/Dirty Install Smoke Tests

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#24119]
# Clean/dirty install smoke tests

Please run these tests on the compiled package of Mantid; **not a locally compiled version**.

When reporting back please include:

- Your OS
- Your facility/location
- If you have other package versions of Mantid installed (yes/no)

If you have any questions please don't hesitate to contact the creator of this issue.

### Dirty install

* Make sure that you have several versions of Mantid installed
	* Last release
	* A nightly
	* If possible an old release
* Install the latest version of the new Mantid
- [ ] Check that Mantid boots up correctly

### Clean install

* Remove all existing Mantid versions and associated files
* Windows:
	* Uninstall the program
	* Clear shortcuts from desktop
	* Clean out the registry
		* Load regedit (Command Prompt > regedit)
		* Find `HKEY_CURRENT_USER > SOFTWARE > Mantid` delete it
* OSX:
	* Remove the application
	* Remove the `~/.mantid directory`
	* Remove `~/Library/Preferences/org.mantidproject.MantidPlot.plist`
* Linux
	* Remove the package: `/opt/Mantid`
	* Remove `~/.config/Mantid`
	* Remove `~/.mantid/`

* Re-install the latest version of the new Mantid
- [ ] Check that Mantid boots up correctly

**Comment by DTasev** [comment]
I'll do the install smoke testing on Windows and Ubuntu 16.04

**Comment by keeeto** [comment]
Thanks @DTasev !!

**Comment by DavidFair** [comment]
I'll pick this up for this release

Windows / Ubuntu / RHEL7 (all completely clean and dirty)

**Comment by DavidFair** [comment]
This works for the above platforms on release 4.2

**Comment by DanielMurphy22** [comment]
Testing on MacOS Mojave. On Mac, Mantid does NOT save a nightly as a separate application. Any reinstall just overrides the previous.
