### ISSUE TITLE
Mantid Basics Course Updates

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24213]
**Original Reporter**: @TTitcombe Tom Titcombe
A few small touch up for the online Mantid Basics Course:
- The [nightly docs](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/index.html) feel more difficult to navigate than the [main course](http://www.mantidproject.org/Mantid_Basic_Course). The nightly docs could benefit from having a contents link on each page
- ["Getting Set up" ](http://www.mantidproject.org/MBC_Getting_set_up) provides a screenshot to the old downloads page to show where to find training files. [The layout has changed](http://download.mantidproject.org/)
- ["MBC Interfaces"](http://www.mantidproject.org/MBC_Interfaces) contains a screenshot of the old Interfaces tab on MantidPlot
- Similarly, the Muon Analysis interface has changed, and the "A Simple Walkthrough" section is slightly outdated
- This is the same in the [nightly docs](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/algorithms_workspaces_and_histories/05_interfaces.html#interfaces)
- The link to "Download as PDF" at the bottom of the [Basic Course](http://www.mantidproject.org/Mantid_Basic_Course) does not work

**Comment by NickDraper** [comment]
This will be updated as part of the change to focus on the workbench rather than mantidplot
