### ISSUE TITLE
ORNL SANS - Allows negative number entry in Reduction Options

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24226]
### Actual behavior
In `ORNL SANS` -> `Reduction Options` tab you are allowed to enter negative numbers for Absolute scale factor,  Sample aperture diameter and Number of Q bins. I believe this shouldn't be allowed and could cause problems.
Beam Radius on the `Detector` tab can also be negative and a double - however it is in pixels.
The other tabs also allow invalid negative data for some properties.

### Steps to reproduce the behavior
1.`Interfaces`->`SANS`->`ORNL SANS`->`Reduction Options` tab
2. Enter a negative number for any of the options stated above

### Platforms affected
All

**Comment by mdoucet** [comment]
I'm not sure that the current status/use of this GUI is. Ricardo probably knows.

**Comment by ricleal** [comment]
As far as know nobody at the ORNL uses the interfaces to reduce data.
The current ORNL SANS code in mantid has low priority in terms of maintenance.
