### ISSUE TITLE
SANS Python Testing fails on ImportErrors

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24223]
Unit testing the Python SANS fails on master

### Expected behavior
Tests should pass

### Actual behavior
A lot of tests fail on `ImportError: No module named sans.foo.bar`
Tests fail if `import mantid` not present

### Steps to reproduce the behavior
On master, run `ctest --output-on-failure -R PythonSANS`

### Platforms affected
At least ubuntu 16.04 and 18.04

**Comment by TTitcombe** [comment]
@Mantid-Matthew

**Comment by martyngigg** [comment]
So I think the problem here is a missing `site.py` file in the `bin` directory. It is currently only generated when doing a build with `ENABLE_WORKBENCH=ON` and it was not spotted that the file is not generated with this off.
