### ISSUE TITLE
SANS - Unexpected error when drawing an ellipsis on the instrument view

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24239]
### Actual behavior
An unexpected error occurs

### Steps to reproduce the behavior
1. Open Interfaces > SANS > SANS v2
2. Choose Load User File; from the ISIS sample data in the loqdemo
folder, choose Maskfile.txt
3. Choose Load Batch File; from the ISIS sample data in the
loqdemo folder, choose batch_mode_reduction.csv
4. In the Settings tab:
- Go to Mask
- Click Display Mask
5. In the instrument view, in the Render tab:
- Click Full 3D and select `Side by Side`
6. Go to the Pick tab
7. Select draw an ellipsis, and try drawing an ellipsis. There is an error

I guess this may happen for the other drawing tools too.

### Platforms affected
All - I assume

**Comment by TTitcombe** [comment]
This is not an issue in the workbench
v. low priority assigned to this issue

**Comment by TTitcombe** [comment]
Closing as a low priority issue for Mantidplot only, which is being deprecated
