### ISSUE TITLE
SANS GUI Crashes Mantid

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#24230]
**Original reporter:** [username facility]/[nobody]. 

### Expected behavior

It should be possible to close the GUI without crashing Mantid.

### Actual behavior

If the GUI is closed before the initial loading has finished, Mantid crashes. This issue seems to have existed in previous versions of Mantid, therefore I suspect it is quite niche. It does, however, seem quite serious to me.

### Steps to reproduce the behavior

* Open Mantid
* Open Interfaces > SANS > SANS
* Quickly close the GUI (before the files have loaded up, a few seconds)
* Mantid crashes

### Platforms affected

OSX, Windows at least

**Comment by TTitcombe** [comment]
As this is a bug with old SANS GUI which has not been reported by users, and that we are moving towards deprecation of this GUI, this is a low priority issue.

**Comment by Mantid-Matthew** [comment]
As the old GUI is now deprecated I am closing this issue
