### ISSUE TITLE
Instrument View for MAR data crashes MantidPlot

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mantid#24246]
When I load MAR test data and try to use instrument view, Mantid Crashes

### Steps to reproduce the behavior
Open MantidPlot
Load the data below
Try to show the instrument view

### Platforms affected
Found on windows 10 using
[MAR22017_Ei10.00meV.nxs.zip](https://github.com/mantidproject/mantid/files/2648494/MAR22017_Ei10.00meV.nxs.zip)

**Comment by nvaytet** [comment]
maybe this is related to #24025 ?

**Comment by aybamidele** [comment]
@nvaytet Perhaps it is, but unlike #24025, with the test data I have used, I am unable to see the instrument view

**Comment by jclarkeSTFC** [comment]
Not a problem in 6.10
