### ISSUE TITLE
Understand usage report error in stand alone Mantid

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#24264]
`UsageService.isEnabled()` returns `False`, even though `mantid.config['usagereports.enabled']` is 1.

This means that the usage reporting is enabled in Mantid, but for some reason, it is not being picked up by the `UsageService.isEnabled()` function.

**Comment by samueljackson92** [comment]
Not sure who's taking over error reporter responsibility, so I'm assigning to @NickDraper for now.

**Comment by NickDraper** [comment]
This seems to work at least in R4.2

```
UsageService.isEnabled()
Out[2]: True

mantid.config['usagereports.enabled']
Out[3]: '1'

```
