### ISSUE TITLE
FilterEvents Inconsistent Bounding Behaviour

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24274]
**Original reporter:** @TTitcombe 

### Expected behavior
With the sliders to control start time and end time, if the  start time slider has been set (to e.g. 0.5), the end time slider cannot move lower than 0.5 (and vice versa).

The sliders to control the maximum and minumum values (present to the right of the plot, and in the `Filter by log` tab at the bottom of the interface) should behave the same way.

Similarly, if you type 0.5 in the stopping time box, you can type any number up to and including 0.5 in the starting time box. If you type a number in starting time greater than 0.5, it will set at 0.5 once you click away. Minimum and maximum value should be expected to behave the same way

### Actual behavior
If you set the minimum value slider to 0.5, the maximum value slider can move all the way to 0, even though the numeric value itself will not go below 0.5

If you set the maximum value (in Filter by log) at 0.5, if you type 0.5 in the minimum value box, it will default to 0.462 (the gap between min and max values seems dependent on the max value).

Finally, set the minimum value to some positive number, e.g. 0.5. If you decide that you want a maximum value of 0.7 you must delete the minimum value first. As soon as you type in max value it default to 0.506, and you cannot delete the digit 5 in order to type 7, as it will default back to 0.506.

### Steps to reproduce the behavior
Interfaces -> Utility -> FilterEvents
You do not have to load any data, just start moving the sliders, and typing in the `starting time`, `stopping time`, `minimum value`, and `maximum value` boxes.

### Platforms affected
At least ubuntu

**Comment by RichardWaiteSTFC** [comment]
In the course of manual testing (#34948) I have not been able to reproduce this issue: I can no longer get max < min for using sliders or edit boxes.
