### ISSUE TITLE
Persistent error warning in F(Q) fit 

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#24297]
### Expected behavior

When loading incorrect data types to F(Q) fit an error message should be thrown. When then choosing browse again this message should not show up.

### Actual behavior

The message does not go away unless you manually delete the file name from the box.

### Steps to reproduce the behavior

**OSX only**
* Get the data sets provided with this Pull Request: #23221
* Open `Interfaces` > `Indirect` > `Data Anaylysis`
* Go to the `F(Q)` tab
* Load the bad data
* Attempt to click browse after the error message has been shown
* Manually deleting the file path solves this

### Platforms affected

OSX only

**Comment by AnthonyLim23** [comment]
@Matt-Cumber could you check if this still exists?
