### ISSUE TITLE
Indirect Data Analysis GUI is Squished

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24369]
**Original reporter:** @TTitcombe ISIS

### Expected behavior
Readable buttons and text

### Actual behavior
When I open up F(Q) Fit tab, "Plot Spectrum" text is incomplete, "Fit Single Spectrum" and "Plot Current Preview" buttons overlap one-another. 
You have to make the window full screen in order to read everything fully
![image](https://user-images.githubusercontent.com/32938439/50215606-7167ce80-037b-11e9-8ca3-f9141dcf1c10.png)

Additionally, the y axis on the lower mini plot overlaps, making reading of values difficult.

The solutions would be:
- [ ] Use icons for buttons which are being squished (allowing smaller buttons)
- [ ] Add Tooltips to the Icon buttons

### Steps to reproduce the behavior
1. Interfaces -> Indirect -> Data Analysis -> F(Q) Fit tab
(Discovered on Ubuntu 18)

### Platforms affected
All - similar squishing can happen on all platforms

**Comment by robertapplin** [comment]
Closed because too low priority
