### ISSUE TITLE
Editor doesn't point at correct line being executed

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#24449]
Current mantidplot installs a trace function so [this line](
https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/PythonScript.cpp#L57) emits the line number and the editor properly points at what is executing. 

In mantidworkbench the equivalent is [this line](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/codeeditor/execution.py#L157) which does not point at the correct line.

**Comment by martyngigg** [comment]
I would argue that the workbench code is working as intended, pointing at a block but not a line, but I will accept the tracing function is  more accurate. We should check the performance though before running with it as it involves a callback on every single line of Python code that is executed.

**Comment by peterfpeterson** [comment]
There are two parts on this one: it isn't always pointing at the correct block; the code I'm working with has a loop over files/materials and is 55 lines long. Pointing at the `for` isn't precise enough. Once the code has been converted to production, the loop should be much smaller.
