### ISSUE TITLE
Create a script from a matplotlib figure 

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#24478]
Add a button or menu item to workbench figures that saves a script that would recreate a figure as it currently exists on the screen. Much of the work that went in to saving plots within projects, #24336, might be able to be reused here. The script created should be a simple flat script that a user might type by hand and it is *not* intended to be a full history of actions applied to the figure.

**Comment by NickDraper** [comment]
Estimate is for line plots
