### ISSUE TITLE
Script rendering in Workbench 

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#24520]
**Original reporter:** [Lamar Moore ISIS]. 
### Actual behavior
Scripts loaded into the workbench end up with strange rendering of the text. Does not seem to happen for the script template (new scripts created in Mantid).

### Steps to reproduce the behavior
**File->Open Script** open any script.

### Platforms affected
Tested on Windows 10 with a 4K monitor.

**Comment by martyngigg** [comment]
An example of the screwed up rendering:
![image](https://user-images.githubusercontent.com/733773/51317052-79845e00-1a4e-11e9-9e12-3b1b58b88c8f.png)
