### ISSUE TITLE
Indirect ConvFit - Plotting options for FABADA PDF data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24534]
**Original reporter:** Spencer

### Expected behavior
There should be plotting options for the output FABADA PDF data within the ConvFit interface.
Creating a more generic design (MVP) for the output options may be a good solution/addition.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` interface
2. Load the data below
3. Fit type is `TeixeiraWater`. FlatBackground and DeltaFunction
4. Select `FABADA` as the minimizer
5. Make sure that PDF is checked
6. Set the Fit String to be `0`
7. Click Run and wait

There should be a _PDFs workspace among the output workspaces. The ConvFit interface should have options for the plotting of this.

### Platforms affected
All

**Comment by SpencerHowells** [comment]
@robertapplin needed for IqtFit as well
