### ISSUE TITLE
Workbench plot toolbar bug

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#24537]
### Expected behavior
The user must always be able to access the toolbar in the plot window. 

### Actual behavior
The toolbar can be lost forever or detached from the plot and live on its own.

### Steps to reproduce the behavior
1. Right click on an empty space of the toolbar and untick the tick-box with an empty label. The toolbar hides and there is no way (an obvious one at least) to get it back.
2. Grab the toolbar by the handle at its left and drag it out. Then close the plot window. The toolbar remains floating.

### Platforms affected
Observed on windows but it's probably the same for all.

**Comment by DTasev** [comment]
Discovered another issue that causes a crash: click the `Fit` button, then do `Right Click -> Fit Function` 3 times, the last one should cause a crash. It seems like the `Fit` button, and right click show to not use the same code path, and something goes out of sync. It might be related to this issue
