### ISSUE TITLE
QENSFitSequential: incomplete diagram

### ISSUE THREAD

**Issue by reimundILL** [mantidproject/mantid#24541]
To be investigated (visible on nightly):

Three boxes are not connected in the diagram:

![qensfitsequential](https://user-images.githubusercontent.com/19187274/51374157-69c65180-1b02-11e9-945d-d4388777d1e7.png)

**Comment by reimundILL** [comment]
@robertapplin Great work, but still one block unconnected?

![qensfitdiagram](https://user-images.githubusercontent.com/19187274/52707296-aa8d7b00-2f87-11e9-9375-085034293418.png)

**Comment by robertapplin** [comment]
@reimundILL I couldn't find a suitable place for this block. It seems to be more of a description of one of the other blocks and so I'd say keeping it unconnected should be fine

**Comment by reimundILL** [comment]
Thanks for this explanation. Then I'll close this issue.
