### ISSUE TITLE
Cell editing focus lost on Error

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24543]
**Original reporter:** nobody

### Expected behavior
When editing a cell in JobTreeView, pressing enter will append a new row and begin editing at the cell below

### Actual behavior
in SANS, data entered into the `Sample Scatter` column is send to FileFinder. If data is passed in which cannot be interpreted as a run, a new row will be appended, but the the current cell will remain highlighted as an error has been mis-handled 

### Steps to reproduce the behavior
1. Interfaces -> SANS -> SANS v2
2. Double click on the cell under `Sample Scatter` (leftmost)
3. Type in some random string and press enter
4. The row will turn blue and the mantid log will tell you that it cannot find the run you just entered. Additionally, a new row should be appended by the cell in the new row will not be in edit mode.

### Platforms affected
All

**Comment by gemmaguest** [comment]
Fixed by the changes in release 4.2.0 where loading data as the user enters input has been stripped out.
