### ISSUE TITLE
Investigate possible speedup of MonteCarloAbsorption if scattering cross sections were cached in Material

### ISSUE THREAD

**Issue by soininen** [mantidproject/mantid#24552]
`MCInteractionVolume::calculateAbsorption()` asks for the total scattering and absorption cross sections from `Material` for each simulated neutron path segment. The corresponding methods in `Material`, `totatScatteXSection()` and `absorbXSection()`, calculate the answers each time a call is made. It could be investigated if caching the cross sections improved the execution times of `MonteCarloAbsorption`.

**Comment by SpencerHowells** [comment]
@soininen Good idea
