### ISSUE TITLE
Indirect Elwin - Ability to enter Run numbers like Energy Transfer

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24570]
**Original reporter:** Spencer

### Expected behavior
In the Elwin interface, it would be useful to be able to enter Run numbers when loading in data. This will make it easier to have multiple input.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`Elwin` interface

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
can you show me this please

**Comment by robertapplin** [comment]
@SpencerHowells Would this use the run numbers to calculate EnergyTransfer before running Elwin?

**Comment by SpencerHowells** [comment]
@AnthonyLim23 This is an old Issue for the current ElWin which use reduced data files. The idea was to be able to input run-numbers like EnergyTransfer and it would create the reduced file names. In my 'incredible plan' the current Elwin would move to the new Manipulation interface & the Reduction interface would have a version which uses raw data & start off by running EnergyTransfer.

**Comment by AnthonyLim23** [comment]
@SpencerHowells can we close this in place of the planned reorganisation?

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Yes- will be in reorganisation
