### ISSUE TITLE
Algorithm to wrap reciprocal space pystog functions

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#24575]
The algorithm should have an input workspace, output workspace, input workspace function type (`S`, `F`, `FK`, `DCS` but names can be changed as appropriate) and call all the functions [line 40 to 208](https://github.com/neutrons/pystog/blob/master/pystog/converter.py#L40-L208). When needed, the scattering information should be taken from the sample object of the workspace.

This requires #24442 to be done first.

**Comment by marshallmcdonnell** [comment]
Proposed name of the algorithm `PDConvertReciprocalSpace`
