### ISSUE TITLE
Kafka topic documentation 

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#24607]
This issue is a side-topic from https://github.com/DMSC-Instrument-Data/kafka_histo_streamer/pull/9 where it was found that the information on how the topic names are formed is hard coded and undocumented (outside ESS confluence)

1. Update the FacilitiesInfo so that the topic name post-fix can be specified at the facilities level.
2. Update `StartLiveData` to give mention of the default and configuration options for the above.
3. Update KafkaListener (concepts) along the same lines as (2)

**Comment by matthew-d-jones** [comment]
Ticket superseded by #26702
