### ISSUE TITLE
Indirect Interfaces Re-organisation and creation of Data manipulation interface

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24610]
**Original reporter:** Spencer

### Expected behavior
The Indirect interfaces could do with some re-organisation. Re-organising the interfaces could make it easier to share widgets between interfaces thereby allowing for parts of the interfaces to be re-written in an MVP style and unit tested.

It is probably best to do this re-organisation before the interfaces are ported to the Workbench.

### The organisation
Data Reduction : Energy Transfer, Calibration, Diagnostics, Transmission 

Data Manipulation : Symetrise, Sqw (using Red), Moments, Elwin & Iqt

Data Analysis: MSDFit, IqtFit, ConvFit, FQFit

### Platforms affected
All

**Comment by Mantid-Matthew** [comment]
This issue has become irrelevant over time.
