### ISSUE TITLE
TWD/MWD - Selection-aware context menu

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantid#24632]
The context-menu generated in MantidPlot seems to be related to the selection, rather than the location of the right click. The one in the Workbench is aware of the click, not the selection, which is confusing.

There are 3 types of selection:
- Spectrum
- Bin
- Cell

### Expected behavior
When a row is selected, trying an action on the column will show on status bar "no column selected".

### Actual behavior
It does the action on nothing, as no columns are actually selected. The logic should be refactored to check both for selection & for the correct selection of columns/rows.

**Comment by TTitcombe** [comment]
1. Bring up the data for a table
2. Select a cell within a row
3. Right click on the row header (which contains the spectrum number) without selecting it
4. Try to plot
5. An empty plot should show up with a warning in the logger
6. If you select the row header and then right click and plot, it works fine
