### ISSUE TITLE
Allow Complex Binning For QXY alg

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24659]
**Original reporter:** nobody

For Q_XY limits, one can have a simple string of start, stop, step

`QXY.cpp` is incapable of taking in complex bins, e.g. a comma separated list of bins with different widths, unlike `Q1D2.cpp`. The ISIS SANS users would like to be able to complete complex binning in 2-D reductions.

This is quite low priority for the amount of work it would require. 

### Steps to reproduce the behavior
1. Interfaces -> SANS -> SANS v2
2. Click load user file and select the following file
[sans2d_user_file.txt](https://github.com/mantidproject/mantid/files/2816933/sans2d_user_file.txt)
This should fail

### Platforms affected
All

**Comment by TTitcombe** [comment]
Speaking to the scientists, complex QXY binning would rarely be required. This is a low priority item.

**Comment by RichardHeenan** [comment]
Though log(Qx) linear(Qy) or linear(Qx) and log(Qy) are OK,  doing log(Qx) Log(Qy) gives weird looking results.
Would be nice to reduce in linear(Qx) linear(Qy) then double the bin box at a certain Q, to 2x2 steps, then double it again further out in Q still to 4x4 steps.  (If we were clever we might manage a 3x3 intermediate as well.)
However the plotting then becomes a bit of a nightmare, but the workaround would be to simply set all the sub-pixels in the 2x2 and 4x4 boxes to the same values.
