### ISSUE TITLE
Bug in rotations in NeXus geometry loading

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#24652]
### Expected behavior
For `NXtransformations` of "rotation" type, the "units" attribute should be consulted to see if the value is in radians or degrees.
Units attribute is "deg" or "degrees", or "rad" or "radians".

### Actual behavior
I think it always assumes rotation is in radians.

### Steps to reproduce the behavior
See files `V20_degrees.nxs` and `V20_radians` from `//olympic/Babylon5/Public/Matthew Jones/` and check rotation of the detector.
The files can be loaded into Mantid using `LoadEmptyInstrument`.
The radians file has a rotation value of `pi/2` and units attribute of `rad` and looks correct in the Instrument View in Mantid. The degrees file uses a value of `90.0` and units of `deg` and looks incorrect in the Instrument View.

### Platforms affected
Observed on Ubuntu 18.04, but likely independent of platform.

**Comment by OwenArnold** [comment]
Test script
```python
def print_det_rotation(workspace):
    comp_info = workspace.componentInfo()
    print(comp_info.rotation(comp_info.indexOfAny('DENEX delay line detector')))

ws1 = LoadEmptyInstrument("/Users/spu92482/Downloads/V20_radians.nxs")
ws2 = LoadEmptyInstrument("/Users/spu92482/Downloads/V20_degrees.nxs")

print_det_rotation(ws1)
print_det_rotation(ws2)
```
Should produce the same result
