### ISSUE TITLE
Indirect Data Analysis Mask Bins Bug

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24663]
### Description
Several things need to happen in relation to Mask bins on the Indirect Data Analysis interface:
- [x] Consistent naming of Mask bins should be applied. The `Exclude` column in the Multiple Input table is the same as `Mask Bins` seen under the miniplots.  Both of these should be changed to say `Mask Energies`
- [x] The `Mask Bins` under the miniplot will round to the nearest decimal point. This should possibly allow greater precision - the suggestion is 3 decimal places (See line 227 in IndirectFitData.cpp)
- [ ] There is a bug described below that needs fixing

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Load in the two workspaces below
3. Enter `1.2, 3.4` for the `Mask bins` under the miniplots and press enter.
4. This value subsequently disappears (but is still in the data table). Clicking the excluded region in the data table will make it disappear from here too

### Platforms affected
All

**Comment by Mantid-Matthew** [comment]
@Harrietbrown This looks related to what we discussed about the ranges specified in the table being ignored.
