### ISSUE TITLE
Indirect Data Analysis - Energy range doesn't change when switching between workspaces

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24664]
**Original reporter:** Spencer

### Actual behavior
The energy range in the mini-plots is not changing when switching between two workspaces with differing energy ranges.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Go to Multiple Input and load the data below
3. Click Run and wait.
4. Select the OSIRIS workspace using the combobox
5. The energy range does not change in the mini-plots! Notice that the EndX and StartX in the data table is now -0.9 to 2.1 (which is correct), but this is not reflected in the mini-plot

**Data Files**
[ConvFit Files.zip](https://github.com/mantidproject/mantid/files/2817435/ConvFit.Files.zip)

### Platforms affected
All

**Comment by Mantid-Matthew** [comment]
@Harrietbrown This looks related to the issue where the energy ranges in the table are ignored. Feel free to close is a duplicate. Assigning to you for now.
