### ISSUE TITLE
Indirect Data Analysis - Multiple input Table shows spectra of selected workspace only

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24660]
**Original reporter:** @SpencerHowells

### Expected behavior
It has been decided that the Data Table in the Multiple Input tab of Indirect Data Analysis should only show the spectra associated with the workspace currently selected.

### Actual behavior
At the moment it shows the spectra of all the workspaces loaded into the interface.

There is also a bug which may be fixed by implementing the expected behavior above: The startX and endX in this Multiple Input table is also changed for all workspaces when choosing which workspace should be selected. This means the startX and endX is wrong for the non-selected workspaces. To replicate this see below:

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab (and MSDFit, IqtFit, F(Q)Fit)
2. Select Multiple Input and Load the workspaces below
3. Choose between the workspaces using the combobox above the mini-plots. The startX and endX of the non-selected workspace will change to an incorrect value

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2817030/irs26176_graphite002_red.zip)
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2817031/irs26173_graphite002_red.zip)
Same Resolution for both:
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2817032/irs26173_graphite002_res.zip)

### Platforms affected
All

**Comment by Mantid-Matthew** [comment]
@Harrietbrown I am closing this issue as it seems like we have moved away from this being a requirement. In particular if we are moving away from only displaying the plots from one workspace at a time and shifting into working in FitDomainIndex where possible this will cease to apply. It also hasn't come up again in the year plus since it was created. But thought it was worth you being aware of it.
