### ISSUE TITLE
Indirect Data Analysis - EndX and StartX go back to default when switching between workspaces

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24662]
### Expected behavior
When you choose an endX and startX for a spectra, this should remain the endX and startX for that spectra unless you try change it again.

### Actual behavior
The endX and startX for a spectra will go back to the default value when you switch between the workspace you have selected.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Go to Multiple Input and add the workspaces below
3. For the iris workspace, adjust the startx and endx using the sliders on the miniplot.
4. Switch to the osiris workspace using the combo box above the miniplots
5. Switch back to the iris workspace. The startx and endx have changed back to the default values!

**Data Files**
[Data Files.zip](https://github.com/mantidproject/mantid/files/2817266/Data.Files.zip)

### Platforms affected
All

**Comment by Mantid-Matthew** [comment]
@Harrietbrown Another issue to-do with startX and EndX not working in the table.

**Comment by robertapplin** [comment]
I noticed during unscripted testing that this also happens on Elwin.

**Comment by robertapplin** [comment]
This can no longer be replicated on the fitting tabs by me or @Harrietbrown . However, a similar problem still exists on Elwin
