### ISSUE TITLE
Refactor tabbing in new Muon GUI

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#24678]
The tabbing in the new muon GUI needs to be refactored and simplified.

**Comment by AnthonyLim23** [comment]
is this done?

**Comment by AnthonyLim23** [comment]
is this done?

**Comment by Mantid-Matthew** [comment]
This is not yet done.

**Comment by Mantid-Matthew** [comment]
This is closely related to #26613
