### ISSUE TITLE
Manage Directories Opens Multiple Times

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24730]
**Original reporter:** @Pasarus 

### Expected behavior
Only able to open Directory Manager Once

### Actual behavior
Can open as many tabs as you want

### Steps to reproduce the behavior
In MantidPlot or Workbench, click Manage directories multiple times
Multiple GUIs will appear

### Platforms affected
All

**Comment by martyngigg** [comment]
I can reproduce this in MantidPlot but not in Workbench. In Workbench I get the dialog as modal so I can't interact with the rest of the application. Can you still reproduce this on the workbench?

**Comment by TTitcombe** [comment]
I still see this on workbench if you go to SANS -> ISIS SANS and click the manage directories button near the top right of the gui

**Comment by martyngigg** [comment]
Ah I see. I forgot SANS has its own button. The general one from the file menu in workbench is okay so I guess the SANS ones just needs to be set modal?
