### ISSUE TITLE
Workbench: comment the line where the cursor is when no selection

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#24849]
### Expected behavior
Pressing `Ctrl+/` comment-line shortcut should comment out the line on which the cursor is currently, if there is no selection.

### Actual behavior
It does nothing, to comment out the line you need to select at least 1 character and then press `Ctrl+/`.

### Steps to reproduce the behavior
Move the cursor on any line, press `Ctrl+/`.

**Comment by hsautessella** [comment]
Do you think it would be worth refactoring the code that performs the commenting into its own class? This would keep the `PythonFileInterpreter` class shorter and make it easier to write some tests for the commenting functionality.

**Comment by DTasev** [comment]
Yeah, I think it would benefit to have it in a separate class
