### ISSUE TITLE
Plot buttons not disabled in ISIS reflectometry

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24979]
### Expected behavior
Should not be able to plot when rows have not been processed

### Steps to reproduce the behavior
Interfaces -> Reflectometry -> ISIS Reflectometry
Load a table
The "Plot selected runs" and "plot selected group" buttons above the table are not disabled. Clicking them results in an error

**Comment by gemmaguest** [comment]
Duplicate of #22034
