### ISSUE TITLE
Processing error in ISIS Reflectometry Old

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#24977]
### Steps to reproduce the behavior

In the old interface
Load INTER_NR_test2.tbl
Process
You get the following error
![image](https://user-images.githubusercontent.com/32938439/53736109-b67ea580-3e80-11e9-84c7-6adadf1cfb35.png)

### Platforms affected
Ubuntu 18

**Comment by gemmaguest** [comment]
It looks like this is to do with the fact the IvsLam workspace is now only output when the Debug flag is set. It should be easy to fix.
