### ISSUE TITLE
Rename Workspace group crash

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#24978]
### Expected behavior
Renaming a workspace group to a name of one of its members should remove that member from the group, if it's the only member simply ungroup. Or maybe it should be a forbidden operation.

### Actual behavior
Mantid eventually crashes.

### Steps to reproduce the behavior
Run the script:
```
ws = CreateSampleWorkspace()
ws_group = GroupWorkspaces([ws])
RenameWorkspace(ws_group, 'ws')
print(mtd.size())
print(mtd['ws'])
```
If the crash doesn't happen straight away you can see that the workspace window clears but workspace "ws" still exists.

### Platforms affected
Seen on Windows.

**Comment by Pasarus** [comment]
This is a bug to do with the ADS. I am aware of it and have a task to complete this during the Maintenance period. https://github.com/mantidproject/mantid/pull/24283 and the initial report was for project recovery but the cause is the same: https://github.com/mantidproject/mantid/issues/24100
