### ISSUE TITLE
Indirect unscripted testing bugs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#24983]
Let me know if some of these are not worth fixing. 

The reduction tab jumps back to the top of the GUI when run is pressed. - annoying but not breaking anything.

For the second test at step 10 I end up with 51 spectra not 50

In the last part of the second test the contour plot seems to be empty (all zeros)

For the I(Q,T) I got the error

float division by zero
  at line 81 in 'C:/Users/BTR75544/nightly/MantidNightlyInstall/plugins/python/algorithms\WorkflowAlgorithms\TransformToIqt.py'
  caused by line 162 in 'C:/Users/BTR75544/nightly/MantidNightlyInstall/plugins/python/algorithms\WorkflowAlgorithms\TransformToIqt.py'```
using  26184 to 5 with both  sample and resolution selected
![image](https://user-images.githubusercontent.com/25006392/53743040-e08c9380-3e91-11e9-9434-85153240a218.png)

**Comment by robertapplin** [comment]
The test should say 51 spectra rather than 50 - this is the case in the Mantid version 3.13.
The other two issues couldn't be reproduced by me or @AnthonyLim23

**Comment by SpencerHowells** [comment]
@AnthonyLim23 @robertapplin For I(q,t) it looks as if the 2 data sets are incompatible. 1 is graphite002 & the other is graphite004. It shouldn’t allow that.
