### ISSUE TITLE
VSI made to crash

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#24996]
1. Run a script like the SXD_NaCl.py [here](https://github.com/mantidproject/mantid/blob/master/scripts/Vates/SXD_NaCl.py) script 
2. Show VSI (r-click) menu option in workspace list on the `QLab` workspace
3. Go to splatter plot mode
4. Drag-drop the integrated peaks workspace from the MantidPlot workspace list onto the VSI
5. From the Peaks menu in the VSI select the "Show All Peaks in Table" option. Crashes VSI.

Issue discovered on OSX testing the nightly build from 4th March

**Comment by NickDraper** [comment]
Roman can you take a look at this?

**Comment by mantid-roman** [comment]
OK

**Comment by mantid-roman** [comment]
Fixed
