### ISSUE TITLE
ISIS SANS v2 - Mantid Crashes when invalid mask file is loaded and used

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mantid#25007]
Mantid Crashes when an invalid mask file is inputted in the mask tab of ISIS SANS v2 
### Steps to reproduce the behavior
Open the ISIS SANS interface in Interfaces -> SANS -> ISIS SANS v2 experimental
Load a user file and batch file and click 'Process All'
On the left hand click settings and go into the Mask tab
Input a random text file or even a nexus file, and click Add
At the bottom of the window, click Display Mask
A blank instrument window is created and soon afterwards Mantid freezes and crashes
### Platforms affected
Windows 10

**Comment by TTitcombe** [comment]
Closing because I and @robertapplin cannot replicate
