### ISSUE TITLE
ISIS SANS v2 - Show instrument option crashes Mantid

### ISSUE THREAD

**Issue by aybamidele** [mantidproject/mantid#25006]
ISIS sans v2 crashes when one attempts to show instrument view

### Steps to reproduce the behavior
Open the ISIS SANS interface in Interfaces -> SANS -> ISIS SANS v2 experimental
Load a user file and batch file and click 'Process All'
In the workspaces tab, right-click the first_time_rear or first_time_front workspace and click Show instrument.
A blank window shows and Mantid Crashes.
### Platforms affected
Windows

**Comment by TTitcombe** [comment]
Closing because I and @robertapplin cannot replicate
