### ISSUE TITLE
Do not open same file in multiple tabs

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#25004]
When running `mantidworkbench -x <filename>`, currently the workbench will open it in a new tab. This can leave a user with several tabs all looking at the same file.

**Comment by Pasarus** [comment]
This is actually possible in MantidPlot if you just continually open them in the script window. What is interesting is if you restart MantidPlot only one of them will open back up.

I brought this up with @hsautessella and I think it is intended?

**Comment by hsautessella** [comment]
When starting workbench it will restore whatever tabs were open when it was last closed. So if a user had multiple instances of the same file open, both instances will be restored.

Is the wanted behaviour to not allow multiple instances of the same file (as Sam said, this is possible on MantidPlot), or to not allow multiple instances on startup, or to not allow an extra instance to be created via the `-x` flag if the same file is being restored?

**Comment by peterfpeterson** [comment]
On problem was that workbench wasn't (a few days ago) allowing to save changes to the file if it was open in multiple tabs. I didn't like the behavior as I frequently (for development/testing) create a script and `mantidworkbench -x script` then poke about. I had 10+ tabs open with the same file before I first noticed it.

**Comment by hsautessella** [comment]
It should be straightforward to have it so that multiple instances of the same tab won't be restored, mimicking the MantidPlot behaviour, if you'd like me to do that?

**Comment by peterfpeterson** [comment]
Since it is in the same area. Can you also print a warning (rather than error) if a file that was open last time no longer exists?

**Comment by hsautessella** [comment]
I've created a PR for the issue, but as far as I can tell we already print a warning and not an error: 
https://github.com/mantidproject/mantid/blob/26f4f3052304176d0c2bda0d7d8cf2bfe02866a7/qt/applications/workbench/workbench/plugins/editor.py#L132-L134
