### ISSUE TITLE
Move AlgorithmProgress from Python to C++

### ISSUE THREAD

**Issue by DTasev** [mantidproject/mantid#25063]
**Original reporter:** 
Jos ISIS

### Expected behavior
Algorithms run as fast as in MantidPlot.

### Actual behavior
Algorithms run ~10x slower due to the progress bar being updated too slowly. The AlgorithmProgress meeting will be moved to C++

**Comment by martyngigg** [comment]
@Pasarus is going to take over and add the cancel buttons to the details dialog as @DTasev is off on training for a few days.
