### ISSUE TITLE
Indirect Data Analysis - Fit Spectra doesn't update when red workspace changes size

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#25074]
### Expected behavior
The Fit Spectra in ConvFit and IqtFit should change if the selected reduced workspace has its size changed. An alternative would be to add a validation check when Run is clicked to make sure that the reduced workspace still has the right number of spectra.

### Actual behavior
An error appears.

### Steps to reproduce the behavior
1.`Indirect`->`Data Reduction`
2. Run number 26176
3. Click `Run`
4. Open `Data Analysis` and go to ConvFit
5. Load in the reduced workspace produced and the res file below (don't Run)
6. Go back to Data Reduction, change the SpecMin and specMax to be a smaller range. Click Run
7. Go back to Data Analysis.
8. Set Fit type to be `One Lorentzian`
9. Click  `Run` and there should be an error because the Fit Spectra goes out of range

[iris26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2945513/iris26173_graphite002_res.zip)

### Platforms affected
All

**Comment by SpencerHowells** [comment]
@robertapplin MSDfit only has 1 spectrum
