### ISSUE TITLE
Bring SNAP_Background_Peak_Clipping into mantid

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#25076]
Create peak striping algorithm from `/SNS/SNAP/shared/Mantid_algorithms/SNAP_Background_Peak_Clipping.py` and refactor `SNAPReduce` to use the new algorithm. The new algorithm should have a more generic name.

**Comment by ckendrick** [comment]
Background papers on the algorithm:

[2008-1131.pdf](https://github.com/mantidproject/mantid/files/5220467/2008-1131.pdf)
[background_elimination.pdf](https://github.com/mantidproject/mantid/files/5220468/background_elimination.pdf)
[Peak_Clipping_Document.pdf](https://github.com/mantidproject/mantid/files/5220469/Peak_Clipping_Document.pdf)
[SophisticatedAnalysis.pdf](https://github.com/mantidproject/mantid/files/5220470/SophisticatedAnalysis.pdf)
