### ISSUE TITLE
Radius limits close to each other lead to Beam Centre Finder producing uncaught exception

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#25081]
**Original reporter:** @Mantid-Matthew . 

### Steps to reproduce the behavior

* These steps use the loqdemo data from the ISIS Sample data
* Load MaskFile.txt as the user file and batch_mode_reduction.csv as the batch file
* Go to the Beam Centre Tab change the upper radius limit to 70 and click run
* An uncaught exception is produced
* If you click run again the system is caught in a very long calculation

**Comment by gemmaguest** [comment]
Fixed by PR #25066
