### ISSUE TITLE
Checks in muon maxent

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#25085]
In the MaxEnt transform when 0 is entered as the lagrange multiplier for chi^2 it return an uncaught exception
Uncaught error when 0 is used for inner iterations
Uncaught error when 0 is used fir last good time

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/plugins/algorithms/MuonMaxent.py#L40

**Comment by AnthonyLim23** [comment]
add a check first < last good time

**Comment by AnthonyLim23** [comment]
I will take this

**Comment by gemmaguest** [comment]
Fixed by PR #25152
