### ISSUE TITLE
unscripted testing muon GUI bugs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#25086]
If you input two negative values into the group asymmetry range in grouping tab when data is loaded, this causes Mantid to close. Only happens if the numbers are in the correct order if the first number is bigger you get the expected error message.

In the grouping tab if you change detector ID to a 0 it deletes the group - I would expect it to just return an error

**Comment by Mantid-Matthew** [comment]
Replica of #25083
