### ISSUE TITLE
Inner and Outer interations wrong way around in Maxent

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#25102]
**Original reporter:** James Lord 

In the transform tab of the frequency domain analysis GUI for Maxent the inner and outer iterations options seem to be the wrong way around with inner iterations affecting the number of outer iterations and vice versa.

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_view.py#L231
