### ISSUE TITLE
Changing power scale on instrument view in workbench does not update view

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#25122]
**Original reporter:** Steve King, ISIS. 

### Expected behavior

Changing power in power scale should update the instrument view.

### Actual behavior

If you are in Show Instrument view and you change the type of mapping to “power”, the colour scale updates but as you change the power value the instrument view itself doesn’t update.

### Steps to reproduce the behavior

* show the instrument;
* change the type of mapping to power
* the colour scale updates but as you change the power value the instrument view itself doesn’t update.

If you enter a value a few too many times Mantid crashes…

### Platforms affected
All

**Comment by martyngigg** [comment]
It turns out I have some time to look at this myself.

**Comment by AndreiSavici** [comment]
Fixed in PR #25155
