### ISSUE TITLE
Unmanaged plots are deleted in workbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#25135]
How to re-create the issue:
1. Create a workspace (doesn't matter how)
2. Create a plot
```python
fig, ax = plt.subplots()
ax.plot((1, 3), (10,10))
fig.show()
```
3. Delete the workspace
4. Wonder why your plot disappeared

**Comment by AndreiSavici** [comment]
Issue reproduced in Ubuntu 18.04, with Python3 build
