### ISSUE TITLE
Some scripts from MantidPlot don't work in workbench

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#25140]
**Original reporter:** James Lord, ISIS. 

### Expected behavior

Scripts that ran in MantidPlot should run in the workbench.

### Actual behavior

Spurious “Syntax error: unexpected indent” with scripts which work OK in MantidPlot. The offending line is some way into the script and is not the first at that indent level. For example my “AnalyseThresholdScans9.py” which is on the Script Repository under Muon if you want a look. It has tab indents. If I run “Tabs to Spaces” it does run OK. (It already had some but perhaps not all required import statements at the top) 

### Steps to reproduce the behavior

Try to run [AnalyseThresholdScans9.py](https://github.com/mantidproject/scriptrepository/blob/master/muon/AnalyseThresholdScans9.py)

### Platforms affected

Windows and Ubuntu 18.04
Py2 and 3

**Comment by TTitcombe** [comment]
While investigating this issue: search for `doChildAlg` in the script editor and then run the script. The error will change to `NameError: name 'doChildAlg' is not defined ................... in line from mantid.kernel import *`
