### ISSUE TITLE
Can't open Workbench when switching between py2 and py3 builds

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25146]
There is an error when switching to a py2 build and previously running `launch_mantidworkbench.sh` on a py3 build: `unsupported pickle protocol`. The manual fix is to delete `.config/mantidproject/mantidworkbench.ini`

### Steps to reproduce the behavior
Run `launch_mantidworkbench.sh` in a py3 build. Close and attempt to run the same script in a py2 build

### Platforms affected
Ubuntu (18)

**Comment by marshallmcdonnell** [comment]
I actually ran into the exact same thing yesterday. In talking with @peterfpeterson, he suggested just a try-except line where it loads the state back in. 

I have a proposed fix in branch `25416_pickled_state`. Just testing before PR submission.

**Comment by peterfpeterson** [comment]
Please create this as a PR for the [release](https://github.com/mantidproject/mantid/projects/17). Read: branch from `release-next`.

**Comment by gemmaguest** [comment]
Fixed by PR #25154
