### ISSUE TITLE
Algorithms in second-level of algorithms list in workbench are in random order

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#25141]
**Original reporter:** James Lord, ISIS. 

### Expected behavior

Algorithms and subcategories at the second level of algorithm list are sorted properly.

### Actual behavior

The algorithms and subcategories at the second level (e.g. the next level down below Arithmetic, Muon, etc) are jumbled in a random order. 

### Platforms affected

Seen on Windows but suspect all.

**Comment by AndreiSavici** [comment]
Merged PR #25150  fixed the issue
