### ISSUE TITLE
Frequency Domain Analysis does not re-enenable if error occurs during processing

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#25175]
In the new Frequency domain GUI main options in the GUI are disabled during loading or processing. If an error occurs in these processes the GUI can remain disabled as the error pathway skips the enabling step.

For example if you try and load more than 100 runs at a time an error is thrown but the GUI remains permanently disabled.

**Comment by AnthonyLim23** [comment]
do you need help with this?
