### ISSUE TITLE
Project recovery error with different named instances of MantidPlot

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#25197]
Project recovery fails if multiple instances of MantidPlot with different executable names are running (e.g. nightly vs unstable). To reproduce:

- Load a file in a MantidPlot **nightly** instance and wait till project recovery has saved something.
- Open a MantidPlot **unstable** instance. You get the error `Project Recovery: Load failed attempted to find potential unused pid but none were found after successful check`.

This doesn't happen on Windows because the executables have the same name. I'm not sure about Mac. It also doesn't happen with workbench.

I'm not sure how important this is to fix as it's just MantidPlot and is probably quite unlikely for users to hit.

**Comment by Pasarus** [comment]
This is an edge case for users and doesn't affect workbench so this is probably not going to be fixed.
