### ISSUE TITLE
Indirect data reduction transmission crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#25191]
Go to the interfaces and select `data reduction` from `indirect`
Change to the transmission tab
Change the instrument to IRIS
Enter the sample file as 26184
Enter 26179 as the background file - it may now hard crash at any point
Press run - will definitely crash

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Never crashed for me & doesn't do it now with last night (14/3/19) build. S's message refers to bad log file. Is this a problem with archive server?

**Comment by AnthonyLim23** [comment]
I just crashed it with a fresh nightly.

**Comment by Pasarus** [comment]
To reproduce this error you must ensure that you are searching the archive for it. It seems to be an archive/filefinder error.
