### ISSUE TITLE
launch_mantidworkbench dependency deprecation warnings

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25216]
If you run `launch_mantidworkbench.sh` (py2 or py3) lots of deprecation warnings from dependency packages will be posted to the logger.

This should be suppressed so the users do not see error messages we cannot control

**Comment by martyngigg** [comment]
We do only turn on the deprecation warnings for developers: https://github.com/mantidproject/mantid/blob/97a0f9ee30ea0a4d2977eceef23726d6336d5926/buildconfig/CMake/LinuxPackageScripts.cmake#L211 so users won't see them. It would be good if we could suppress them from 3rd party packages though as we can't do anything about them.
