### ISSUE TITLE
Indirect Data Analysis multiple files hard crash

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#25260]
**Original reporter:** @Mantid-Matthew  

When Fitting multiple data in the Indirect Data Analysis interface if steps are taken in specific order mantid hard crashes.

### Steps to reproduce the behavior

Get the data from this PR #25250

1.Interfaces->Indirect->Data Analysis->ConvFit
2. Go to MultipleInput tab and click Add Workspace, add the first set of data then close the dialog reopen it and add the second set of data. Select All Spectra each time.
3. Select One Lorentzian as Fit type
4. Click Run and wait

**Comment by robertapplin** [comment]
Instead of a hard crash, I get a runtime error:
![image](https://user-images.githubusercontent.com/40830825/54623480-7c59fa00-4a63-11e9-9f96-e94c126f0dbb.png)
This is on windows.

**Comment by NickDraper** [comment]
Is there any progress on this?

**Comment by NickDraper** [comment]
Actually the PR for this looks done and merged.  I'll close the issue, but reopen it if you disagree.
