### ISSUE TITLE
Indirect - Opening Data Reduction causes uncaught exception when HFIR is the selected facility

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#25290]
### Expected behavior
No error. Perhaps when the data reduction interface is opened and a relevent facility hasn't been selected then the facility should be changed to a relevant one?

### Actual behavior
Opening Data Reduction when the faility has been set to `HFIR` causes:
![image](https://user-images.githubusercontent.com/40830825/54747483-fb1b7800-4bc6-11e9-906e-2277c06fc947.png)

### Steps to reproduce the behavior
1. Set  `HFIR` as default facility
2. Open Indirect->Data Reduction
Error!

### Platforms affected
All I assume

**Comment by SpencerHowells** [comment]
@robertapplin better to check that an appropriate instrument exists & if not give message to that effect
