### ISSUE TITLE
 Indirect-VESUVIO: Implementation of CAAD fitting and constrained fitting with boundary conditions

### ISSUE THREAD

**Issue by sanghamitra-mukhopadhyay** [mantidproject/mantid#25317]
Fitting of VESUVIO spectra requires the application of CAAD method (cumulative fitting of sums of normalised detectors) during fitting. 
This fitting also requires the option of application of constrains along with other boundary conditions suitable for individual detectors.

**Comment by martyngigg** [comment]
@sanghamitra-mukhopadhyay Can I assume that this was opened in error?

**Comment by sanghamitra-mukhopadhyay** [comment]
Sorry, I wanted to put the following ticket for Vesuvio:

Implementation of CAAD fitting and constrained fitting with boundary condition.

**Comment by martyngigg** [comment]
Thanks. If you click the `...` next to the smiling face in the first box you can edit the original box and the "Edit " button next to "New issue" means you can edit the title.
