### ISSUE TITLE
Workbench: Poor scaling with different monitor scaling in windows

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#25372]
### Expected behavior
Workbench to appear "normal" 

### Actual behavior
On a system with a laptop and a monitor, it gets confused about scaling and just appears ugly.
Monitor: 1920*1080, scaling 100%
Laptop (Nick's Surface): 2736*1824, scaling 200%

Workbench on the Monitor
![image](https://user-images.githubusercontent.com/1017173/54930811-dbaa8500-4f0f-11e9-9671-d49e26711e2c.png)

Workbench on the laptop
![image](https://user-images.githubusercontent.com/1017173/54930835-e9600a80-4f0f-11e9-92cf-76c3ccfa0b96.png)

As a guess it appears to take the scaling from the laptop (primary screen), and uses it even though the window initially appears on the desktop.  Wehn you move the window to the laptop it gets even more confused.

If you launch it when the laptop it is not connected to the other screen it all looks normal.

### Steps to reproduce the behavior
See above 

### Platforms affected
Windows 10

**Comment by NickDraper** [comment]
This might be helpful
https://stackoverflow.com/questions/39823918/how-to-approach-development-of-new-qt-5-7-high-dpi-per-monitor-dpi-aware-applic

**Comment by hsautessella** [comment]
This has been (crudely) fixed by #26266 and a new issue #26301 has been raised with some updated information around the new issues that #26266 raises. Should we close this?

**Comment by martyngigg** [comment]
I agree. Let's close this in favour of #26301
