### ISSUE TITLE
Port ISIS Reflectometry GUI to Workbench

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#25383]
Todo List:

- [x] Sip exposure of highest level widget:
https://github.com/mantidproject/mantid/blob/isis_reflectometry_alternative_table/qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowView.h#L27
- [x] Finish import/exporting of the Interface Manager and the various supporting factories if nessercary
- [x] Qt5/Matplotlib plotting for workbench likely using MplCpp current way of doing this unknown discovery should be completed.
- [x] "JobTreeView" plotting for MantidPlot/Qt4 isolated plot methods to work with original GUI in MantidPlot
- [x] Make a cpp capable library for Qt5 and workbench #25596

Plot capability list:
- Over-plotting of all selected rows in the `JobTreeView`
- Workspaces plotted from the equivalent named in the ADS
- Use Log(x), Log(y) numbered axis for the plots of Reflectometry data by default

**Comment by gemmaguest** [comment]
Here are some simple tests for various combinations of using the plot buttons.

### First, set up some processed rows
- Open the `ISIS Reflectometry` interface, select `INTER`.
- From the Reflectometry menu, select Import table and choose `INTER_NR_test2.tbl` from the ISIS sample data.
- Click `Process` and when finished expand all groups. All rows should now be green.

### Test the first button ("plot runs")
- Select a single row within a group and then click plot runs. You get a single curve:
![image](https://user-images.githubusercontent.com/12895056/55162331-82d12b80-515f-11e9-8dd0-3a49809f1bf9.png)

- Select two rows and click plot runs. You get two curves on one plot:
![image](https://user-images.githubusercontent.com/12895056/55162520-f115ee00-515f-11e9-8dec-858213b44066.png)

- Select a group and click plot runs. You get all of the curves from the group on one plot:
![image](https://user-images.githubusercontent.com/12895056/55162568-068b1800-5160-11e9-81f1-d1a1915ef2df.png)

- Select one row from the first group and two rows from the second group. You should get three curves:
![image](https://user-images.githubusercontent.com/12895056/55162805-7ef1d900-5160-11e9-8a78-c1985b377c20.png)

- Select one row from the first group and the overall group for the second group. You should get three curves:
![image](https://user-images.githubusercontent.com/12895056/55162881-a779d300-5160-11e9-8977-0c863f116e61.png)


### Test the second button ("plot group")
- Select a row or rows within a group and click plot group. Nothing should happen (ideally this should be disabled).

- Select a group and click plot group. You should get a single curve (for the stitched result):
![image](https://user-images.githubusercontent.com/12895056/55162725-52d65800-5160-11e9-9c48-ebdda990ad04.png)

- Select two groups and click plot group. You should get two curves:
![image](https://user-images.githubusercontent.com/12895056/55162761-65509180-5160-11e9-96d4-9085292fd215.png)

- Select one row from the first group and the overall group for the second group. The row should be ignored and one curve plotted for the second group:
![image](https://user-images.githubusercontent.com/12895056/55162950-c7a99200-5160-11e9-8481-6873c3831ffc.png)

**Comment by gemmaguest** [comment]
Here is a suggested implementation for getting the selected workspace names for plotting. Feel free to adjust this if you think there is a better way.

- For groups, we want to plot the `Group::postprocessedWorkspaceName()` and for rows, `Row::reducedWorkspaceNames().iVsQBinned()`
- Create functions `RunsTable::selectedGroups()` and `::selectedRows()`, returning a `std::vector` of `Group` or `Row`.
- These should iterate through `m_selectedRowLocations`
- For each `RowLocation` get its `path()`. 
- The `Item`s are available via `reductionJobs()`:
  - Add functions to `ReductionJobs` to get a `Group` or `Row` from a `RowPath`.
  - Note that the path is a vector containing one int for a group (which is the group index in `m_groups`) and two ints for a row (the group index, and then the row index within the group - i.e. the index in `Group::rows()`).
  - We could consider making `RowPath` a proper class with some helper functions e.g. `isGroup()`, `isRow()`, `groupIndex()`, `rowIndexInGroup()`. These could make the calling code much more readable.
  - When requesting groups, ignore `RowPath`s that are not groups.
  - When requesting rows, if the `RowPath` is a group then iterate through its child rows and include them.
  - Note that rows are optional and should be excluded if not initialized (this represents an invalid row on the GUI).
