### ISSUE TITLE
Is DAEserv dead code?

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#25456]
`/tools/DAEserv` looks unmaintained and lacks any documentation to tell anyone what it is or how to use it.

It looks like a fake ISIS live data source from many moons ago but that is a guess form ~1min of looking at the code.

If it is no longer actively needed it should be removed.

**Comment by NickDraper** [comment]
This is a simulator for ISIS DAE, but was what we used before we created the algorithms that can act like a fake DAE.
I'll put in a PR to remove it.
