### ISSUE TITLE
MuonPairingAsymmetryTest failure on Jenkins builds

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25481]
MuonPairingAsymmetryTest is failing on multiple Jenkins builds. The error is ```Invalid value for property InputWorkspace (WorkspaceGroup) from string "pairWS": Workspace "pairWS" was not found in the Analysis Data Service```

A Jenkins log for the failure is: http://builds.mantidproject.org/job/pull_requests-rhel7/28701/consoleFull

### Platforms affected
This test failure has been seen on:
RHEL7 - frequently
OSX - frequently
Ubuntu + Python 3 - infrequently

It has not been seen on Doc tests or Windows

**Comment by DTasev** [comment]
Possibly closed by https://github.com/mantidproject/mantid/pull/25344
