### ISSUE TITLE
Colourfill plot on reduced SANS2D data gives an error

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#25521]
Matthew Andrew has an example of a reduced SANS2D dataset with ragged bins that does not plot in workbench with the colorfill option.

We need to grab the file and diagnose and fix the error.

**Comment by hsautessella** [comment]
This seems not to be a problem in the current nightly. Possibly fixed here: #25052?

**Comment by martyngigg** [comment]
@Mantid-Matthew Would you be able to confirm that this is now fixed?

**Comment by Mantid-Matthew** [comment]
I think this can now be closed yes
