### ISSUE TITLE
SANS Processed Nexus files require "add" in name

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25539]
**Original reporter:** Rob ISIS

In SANS, Processed Nexus files require an "-add" suffix to the name. This is an incorrect check to make as there are times non-added processed nexus files will be used in SANS.

The behaviour of loading these files should change so that it first tries to treat is as nxs and then attempts to treat it as a process nexus.

The idea of adding a more relevant suffix to signify the type of file being used had been floated, but this will need to be confirmed.

**Update:** This requires a demonstration from Rob as I cannot replicate. Check with Rob the priority of this.

**Comment by smk78** [comment]
Also see https://github.com/mantidproject/mantid/issues/21223

**Comment by DavidFair** [comment]
Closed by #31134
