### ISSUE TITLE
Workbench: Double-click workspace opens plot by default

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#25548]
Workbench currently opens the data view when double clicking on workspaces. There is a general consensus that most of the time a plot would be preferred. This issue is to change the default for double-clicking to attempting to plot a workspace rather than show the data directly.

Note that this requires #25547  to be done first.

There are many considerations to take into account here:
* for a single spectrum `MatrixWorkspace` then the 1D plot can be created straight away without user intervention;
* for a multi-spectrum `MatrixWorkspace` then the dialog that we have currently for spectrum selection will need to be shown but will also need to include an option to be reworked slightly to include an option to colorfill plot the workspace.

**Comment by DTasev** [comment]
4633ae0 adds the double click to plot, what remains to be done:
- Expand the plot dialog to have a colorfill option, only when called from double click
