### ISSUE TITLE
Workbench: Code commenting works incorrectly with inconsistent line endings

### ISSUE THREAD

**Issue by hsautessella** [mantidproject/mantid#25577]
### Expected behavior
Commenting code in a script with inconsistent line endings (e.g some lines end in `\n` and some in `\r\n`) should work correctly.

### Actual behavior
Commenting code with inconsistent line endings will comment more lines than selected.

### Steps to reproduce the behavior
[test.zip](https://github.com/mantidproject/mantid/files/3111764/test.zip)
- Attached is a file with inconsistent line endings.
- Load the file into Workbench and try commenting some lines.
- Selecting a single line will comment multiple lines and selectling all lines will raise an error

**Comment by martyngigg** [comment]
use a regex to find them

**Comment by thomashampson** [comment]
Removing the stale label because I can't reproduce this on Linux or Windows.
