### ISSUE TITLE
SliceViewer Colorbar

### ISSUE THREAD

**Issue by rosswhitfield** [mantidproject/mantid#25598]
The new SliceViewer (#25569) for workbench just uses the standard matplotlib colorbar, that should be removed and replaced with something more custom, just like is in the instrument view:

![colorbar](https://user-images.githubusercontent.com/5595210/56760773-e86a0500-6769-11e9-9cad-30dbb40945c7.png)

You should be able to set the limits, toggle auto-scaling and choose the intensity function (Linear, Log or Power)

When the Power options is selected a box that the power factor to set should appear, look the the colorbar in the workbench instrument view.

**Comment by martyngigg** [comment]
[ColorbarWidget.cpp](https://github.com/mantidproject/mantid/blob/master/qt/widgets/mplcpp/src/ColorbarWidget.cpp) has the meat of these changes. The class api is not great as I needed to conform to the API of the Qwt-based one to slot into the instrument view easily. If we create a python-based one for sliceviwer I would be tempted to import that one back into C++ here once we remove MantidPlot and Qt4.
