### ISSUE TITLE
Indirect Reduction - Load Detailed Balance automatically from Sample Logs

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#25647]
### Expected behavior
It would be helpful if the detailed balance stored in the sample logs was automatically loaded into the Energy Transfer interface automatically when a run number has been loaded.

### Actual behavior
It's value is currently defaulted to 300k.

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Reduction`->ISISEnergy Transfer
2. Instrument `IRIS`, Analyser `graphite`, Reflection `002`
3. Run number `60000` and press enter.
4. The detailed balance should change to be `245.253K`
5. Change Run number to `26176`. A default detailed balance of `300K` should be set

### Platforms affected
All

**Comment by SpencerHowells** [comment]
@robertapplin run 26176 does not have sample temperature in Log so will test for default. Use any run from 72462 to 72564 for Log value.
