### ISSUE TITLE
Investigate SANS reduction speed

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25723]
Attempts have been made to speed up the ISIS SANS reduction under certain scenarios:
1. #23973 Keep workspaces as event workspaces as long as possible
2. #22897 Perform operations on event workspaces before event slicing 

These improvements involve changing the reduction workflow and so result in slightly different output data. However, the workflow contains many independent pieces, so there undoubtedly inefficiencies that do not result in material changes.

The entire sans reduction workflow - as soon as "process all" is clicked - should be profiled, to identify bottlenecks.

Areas to consider are:
1. The high level operations are performed in SANS python algorithms, e.g. `SANSMask`. Each of these arrange and prepare the data, and call the relevant C++ algorithms to perform heavy lifting. This means there is a lot of crossing over from python to C++, and back, during a reduction.
2. The sans state object, is serialized, de-serialized, and validated in many SANS algorithms. The repeated validation is almost certainly unnecessary, but serializing, de-serializing may be necessary to pass the object through algorithm properties
3. The sans state object is passed around in its entirety through the SANS algorithms, despite each algorithm requiring only a small subset of the parameters. If we re-address how to pass the sans state information, we can a) pass a smaller object, b) do away with the repeated serialization in point 2
4. Individual operations within `SANSReductionCore`. It has previously been highlighted, that moving, converting to wavelength, and converting to q are some of the more costly steps.

**Comment by gemmaguest** [comment]
Also consider LoadISISNexus when looking at this #10848 but we don't believe that to be the biggest problem
