### ISSUE TITLE
Normalisation of fit results in workbench

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#25727]
### Expected behaviour
In workbench the fit parameters should correspond to the scaling on the plot
### Actual behaviour
The fit parameters automatically rescale to bin width, while the plot is not rescaled to bin width
### Steps to reproduce the behaviour
- Use Workbench
- From the sample data from the Mantid tutorial load GEM38370_Focussed.nxs
- Plot spectrum number 5
- set axis range to between `2` and `2.25`
- open fit
- add peaks corresponding to approximately `2.11`, `2.14` and `2.19`
- add linear background.
- press fit.
- Fit parameters have been normalised while the plot has not.
![workbench_fit_rescaling](https://user-images.githubusercontent.com/49688535/57917734-336cc900-788d-11e9-9483-057e86f70ecd.png)
### Platforms affected
All.

**Comment by AndreiSavici** [comment]
I think there is a deeper issue here. You are not plotting counts, you are plotting counts/Angstroms. And you don't know it, andyou cannot even change the preference in the workbench. I've change the preference in Mantidplot, and here is my image (with similar fit parameters)
![GEM38370_Focussed-1](https://user-images.githubusercontent.com/1128952/57934697-403dec80-788e-11e9-91fd-044c10adaf35.png)

**Comment by hsautessella** [comment]
You're right about the units, I've been working on a PR that addresses this (#25556) and also another PR that will give the option to normalize/un-normalize on the plot's context menu (similar to the option in MantidPlot). 

I believe there is a plan to add a setting to not normalize by bin width by default, but I don't think an issue has been raised for it yet. In the mean time you can turn off normalizing by bin width by setting `config['graph1d.autodistribution'] = 'Off'`.
