### ISSUE TITLE
InstrumentActor::draw on OSX. 

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25786]
Open the `InstrumentView`, issue seen in MantidPlot, but might affect MantidWorkbench too.

`InstrumentActor::draw invalid frame buffer operation`

Seen on v 10.13, but might affect others.

Someone good with OpenGL should look at this.

**Comment by DanielMurphy22** [comment]
I do not get this error message for MantidPlot or WB version 5.0
