### ISSUE TITLE
Mask bins x values out of range

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#25785]
### Expected behavior
If you provide a value that is out of the x range of the workspace when using the MaskBins algorithm, it should produce an error or warning that no changes have been made.

### Actual behavior
The algorithm executes with no indication of error.

### Steps to reproduce the behavior
* Load HRP39182.RAW from the Mantid Training data set
* Run MaskBins with `XMin = 10000` and `XMax=11000`
* Observe that this runs without warning and produces a workspace that is identical to the original

### Platforms affected
* All

**Comment by DanielMurphy22** [comment]
While the range specified 10000-11000 is actually within the xrange of the workspace, running say 100-11000 as the limits for MaskBins produces the same result as the first bin edge is at 10000. Technically all the data within this range has been masked, even if part of the range was outside of the xrange of the ws. 

If you used 100-1000 as the limits for the Mask, then you get back the same workspace with no mask applied. 
I think this is rather small, and potentially this is even the desired behaviour: say if a cropped workspace then has a mask applied to it, which is now outside its range.
