### ISSUE TITLE
Wireframe on RectangularDetector InstrumentView

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25789]
* Load an instrument with RectangularDetectors into the `InstrumentView`
* switch to wire-frame visualisation

Only shows 2 edges of square. Should really show edges for all `RectangularDetectorPixels`

**Comment by DanielMurphy22** [comment]
I seem to be able to get all 4 edges![Screenshot 2020-04-29 at 15 09 34](https://user-images.githubusercontent.com/55980573/80605802-733fa880-8a2b-11ea-9c6e-a7539e74fa96.png)
The Wireframe view seems quite glitchy when moving the cursor in a locked Full3D direction such as Z- (at least on Mac). The behaviour seems very similar between MantidPlot and Workbench.
