### ISSUE TITLE
Linear Background Remain After Fit Clear

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25793]
Seen in `MantidPlot`, but may affect Workbench too, clearing the fit leaves `LinearBackground` functions in place under the composite fit function.

Using the Fit Dialog.
* Add a Gaussian
* Add a `LinearBackground`
* Fit
* Clear the fit

`LinearBackground` survives

**Comment by DanielMurphy22** [comment]
This bug does not exist in WB, but is still in MantidPlot 5.0. I don't see it getting fixed as it isn't show stopping.
