### ISSUE TITLE
Rewrite Mantid Courses Against Workbench

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25796]
Might require that more plotting functionality (SliceViewer etc) is available first. The courses need to be updated and re-written against `MantidWorkbench` - this would be a useful avenue for showing off the workbench and discontinuing `MantidPlot`.

Look at other tickets marked "Workshop" as part of this

**Comment by NickDraper** [comment]
While doing this we should change the interface we introduce people to from the Muon interface to something else, SANS?

**Comment by ConorMFinn** [comment]
Completed by #27694

**Comment by NickDraper** [comment]
reopening as we also need to update the Python in Mantid course as well.
