### ISSUE TITLE
SANS batch table needs Excel like shortcuts

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#25791]
Reported by user during ESS Mantid Workshop 28th May 2019. Judith (LOKI) reported.

Wanted to tab between cells, wanted excel like shortcuts. I suggest also contacting Judith (ESS, I'll provide email) to get specific requirements. The ESS plan to use the ISIS reduction guis.

**Comment by DavidFair** [comment]
So most of the excel like shortcuts are there (i.e. copy paste row etc)

I'm going to close this issue as a duplicate / fixed since we have individual issues for the table such as tabs in #27028

However, if we get more feedback from users / training workshops please feel free to open issues.
