### ISSUE TITLE
Results table upgrade

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#25814]
This issue is to deal with the minor comments from PR #25805 and the following:

1. Disable the create results table button if a fit is running
2. ~~Automatically set the table columns to x/y (needs stuff exposing to python)~~

**Comment by AnthonyLim23** [comment]
3. disable the Output results button if no workspaces are selected

**Comment by Mantid-Matthew** [comment]
Number 2 above is already done

**Comment by Mantid-Matthew** [comment]
Closing as either resolved or have not been brought up in last year.
