### ISSUE TITLE
Fitting tab in muon analysis 2 can accept start times larger than end times

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#25821]
### Expected behavior
In the Muon Analysis 2 fitting tab if the fit start time is greater than the end time it should return an error.

### Actual behavior
The two are interchangeable, if the start time is larger it plots as normal between the two bounderies. An error is only returned if the two are equal.

### Steps to reproduce the behavior
1. Open Workbench
1. Open Interfaces --> Muon --> Muon Analysis 2
1. load current ESU run
1. Go to fitting.
1. set a flat background function.
1. set the time start to larger than the time end and click fit.
1. The fitting program fits as if the time start and time end have been switched.

### Platforms affected
Windows.

**Comment by Matt-Cumber** [comment]
Instead of producing an error here, just switch the numbers round on the GUI instead of doing it quietly in the background
