### ISSUE TITLE
Muon Analysis 2 crashes when canceling load group

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#25823]
### Expected behavior
In muon analysis 2 when closing the load grouping dialog box it should return to the regular muon analysis 2 window.

### Actual behavior
Clicking cancel on the load grouping dialoge box will crash muon analysis 2

### Steps to reproduce the behavior
1. Open Workbench
1. Open Interfaces --> Muon --> Muon Analysis 2
1. load current ESU run
1. Go to the Grouping tab.
1. Click load
1. Click cancel 

### Platforms affected
windows

**Comment by Mantid-Matthew** [comment]
This has been fixed in #26443
