### ISSUE TITLE
Hard crash on help navigation

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25908]
There is a hard crash in workbench's help window when you navigate to a page while you're looking at an image.

### Steps to reproduce the behaviour
In workbench, press F1 to bring up the mantid help page. Search for a page with an image e.g. `ISIS SANS`, and click on the link to bring up the page. Click on an image in the page to maximize it. Then click on any link in the search area to the left of the help window. Workbench hard-crashes

### Platforms affected
Ubuntu 18.04

**Comment by hsautessella** [comment]
This isn't an issue on Windows as you can't open images in the same way you can in Ubuntu. I'll look into it

**Comment by hsautessella** [comment]
This is also happening in MantidPlot
