### ISSUE TITLE
Workbench SliceViewer GUI bugs

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#25900]
**Original reporter:** Duc Le / ISIS

There are two issues with the SliceViewer GUI.

### Expected behavior

1. Changing the colour axis limits using the edit boxes above and below the colorbar will update the main plot with the new colour axis limits.

2. The lineplots (along either x- or y-axes and integrating over the other axis) should work after they have been toggled on, then off, and back on again.

### Actual behavior

1. Changing the colour axis limits using the edit box updates the limits of the colorbar itself but not the main plot. The main plot colour limits only updates when another graphic operation (such as zooming, toggling the lineplots, or changing the colormap [pan and toggling the grid does not update the colour limits]).

2. Toggling the lineplots on for the first time on a new SliceViewer window works as expected. Toggling it off then removes the lineplot as expected. However, then toggling the line plots on again shows the line plot axes, but the line plots themselves are not shown. 

### Steps to reproduce the behavior

1. Right click on a `MatrixWorkspace` or `Workspace2D` and click on `Show SliceViewer`. Change the upper colour limit using the text boxes (either below the colormap combo box or above the plot type combo box). Verify that the main plot does not update. Zoom into a region of the plot and then click the "Home" button. Verify the plot now has the new colour axis limits.

2. Click on the graph button (between the grid and save buttons) to toggle the line plots. Move the mouse over a region in the main colour plot, and verify that 1D line plots are shown in the line plot axes, which change as you move the mouse. Toggle the line plots off. Toggle the line plots on again, check that the line plots axes are recreated. Move the mouse over some region in the main colour plot and verify that the 1D line plots are no longer shown.

### Platforms affected

Presumably all but only checked on Red Hat 7, with Mantid 4.0.20190607.1611

**Comment by martyngigg** [comment]
It looks like this is limted to RHEL 7.
