### ISSUE TITLE
Fix broken SANSILLReduction unit test

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#25915]
4e4ffc7e331d610b593d84f92b3206f275606a5b disabled a unit test that was [failing on all build servers](https://builds.mantidproject.org/job/master_incremental/4579/). Re-enable the test, figure out why it is failing, and fix it.

**Comment by gvardany** [comment]
Git bisect points to fc57517a9643c337c2a6a01d988ce3923ea0f012 as the first bad commit.
Indeed, 84793429bf86cbc7736b3bb007e519b53b3078db is still fine.
@peterfpeterson Any idea how that innocent change can cause the output of `CalculateTransmission` not have instrument attached?

**Comment by gvardany** [comment]
It turns out that after implementing `__len__`, the instrument, which is a component assembly, gets boolean evaluation as a container, so empty container leads to False:
From [what is False](https://thomas-cokelaer.info/tutorials/python/boolean.html):
```
Objects from classes that implements __len__ to return False or zero
```
Any idea how to resolve this?

**Comment by peterfpeterson** [comment]
We could implement `__bool__` explicitly for instrument to return what one would expect

**Comment by gvardany** [comment]
Yes we should. I fixed the broken test however to use `isinstance`.
