### ISSUE TITLE
Mantid Setup Window - Do not show again box doesn't work 

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#25926]
### Description
The checkbox at the bottom left of the Mantid setup screen called `Do not show again until next release` does not work. Even when ticked, the setup screen always appears whenever opening mantid.

### Platforms affected
Windows and maybe others

**Comment by DanNixon** [comment]
You have to have a facility and instrument set. I noticed this a few times before I realised that was required.

I'm not sure this is a sensible requirement though? Facility is likely needed for archive search to function correctly, but instrument is probably not important.

**Comment by robertapplin** [comment]
I agree I am not sure about this requirement. Maybe the option should be invisible if the instrument or facility is not set?

**Comment by DanNixon** [comment]
If Mantid is deemed to be not configured if no facility is selected then we shouldn't allow a user to close this window without selecting one.

I think not selecting an instrument should be allowed. AFAIK most of Mantid either doesn't care, can determine from data or will ask more locally about the instrument.
