### ISSUE TITLE
workbench help crashes

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#25944]
Open workbench and open one of the GUI's (e.g. Muon Analysis 2 or Indirect correction) and click the help button. Workbench crashes.

**Comment by martyngigg** [comment]
I tried this on Ubuntu and I don't get a crash so it must be a Windows issue?

**Comment by hsautessella** [comment]
I'm not able to re-create a crash on either of my Windows 10 machines. I just get the "Missing page" message opening in the help window
