### ISSUE TITLE
Remove old SANSSingleReduction algorithm

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25986]
PR #25887 introduced a new algorithm for ISIS SANS reduction optimised for event slicing. Current behaviour is for this algorithm to only be used if `compatibility mode` is switched off, event slices are requested in the reduction, and `event slice optimisation` is selected.

We need to confirm with the scientists if the new algorithm produces acceptable results.

Once this has been done, we should remove `SANSSingleReduction v1` and `SANSReductionCore`, and all reductions should go through `SANSSingleReduction v2`, `SANSReductionCorePreProcess` and `SANSReductionCoreEventSlice`. 

`SANSSingleReductionTest` tests output from version 1 to stored workspaces, and compared output from v1 and v2. The tests should be updated to compare output from v2 to stored workspaces.

Before actually removing this we should make the new one the default.

**Comment by rbauststfc** [comment]
This is blocked by #37836, and may no longer be needed depending on the outcome of that issue.
