### ISSUE TITLE
ISIS Reflectometry GUI fixes and improvements

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26025]
This epic contains remaining work and issues relating to the reflectometry GUI restructuring in #26016. Child issues have been created for all of the individual tasks and assigned milestones if relevant for higher priority items. Lower priority items do not yet have a milestone.

**Comment by NickDraper** [comment]
Is everything for R4.1 in this issue done now?  Should the remains of this umbrella issue move to R4.2?

**Comment by gemmaguest** [comment]
@NickDraper It was just documentation left so I've created #26282 for that and moved this to 4.2
