### ISSUE TITLE
Workbench method hint highlights the wrong parameter

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#26036]
When you begin to type in an algorithm to the Workbench script editor, a hint will pop up showing you what parameters the algorithm expects. The parameter the hint thinks you're on is highlighted, however this can be incorrect.
 
### Steps to reproduce the behavior
In the Workbench script editor, begin to type:
`foo = CreateWorkspace(DataX=[` and you should see the hint with **DataX** highlighted as your current parameter.

Then type `10, ` i.e. provide the list of x data with its first element. After the comma, the highlighted parameter moves to **DataY**, even though you're still on the DataX parameter. This continues as you add more elements to DataX

**Comment by NickDraper** [comment]
Not going to fix this one
