### ISSUE TITLE
SliceViewer crash when opened using MAR training data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#26116]
###Expected behavior
No crash. 

### Actual behavior
Crashes the Workbench.

### Steps to reproduce the behavior
1. Load `MAR11060.raw` from the TrainingCourseData.
2. Right click the loaded workspace and select `Show SliceViewer`. There is a crash.

### Platforms affected
Found on Windows

**Comment by quantumsteve** [comment]
Can't reproduce the issue with `master` on Ubuntu 18.04

**Comment by NickDraper** [comment]
Duplicate of #26235
