### ISSUE TITLE
Documentation for new MUON GUI and elemental analysis

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26114]
Release notes too!

- [ ] new muon gui
- [x] elemental analysis #26242
- [ ] release notes

**Comment by AnthonyLim23** [comment]
elemental analysis docs are https://github.com/mantidproject/mantid/pull/26242

**Comment by AnthonyLim23** [comment]
muon GUI are done and closed

release notes are https://github.com/mantidproject/mantid/pull/26236 are you happy with them?

**Comment by NickDraper** [comment]
covered by other specific issues - closing this one
