### ISSUE TITLE
Workbench Reflectometry GUI crashes after cutting empty row

### ISSUE THREAD

**Issue by hsautessella** [mantidproject/mantid#26110]
### Expected behavior
The GUI shouldn't crash when processing a run after cutting an empty row.

### Actual behavior
The GUI hard crashes Workbench.

### Steps to reproduce the behavior
- Open the Reflectometry GUI in Workbench
- Create a group and a row within it
- Set the run number to 13460 and the angle to 0.5
- When entering the angle press enter to after entering the number, this creates an empty row below it
- Select the empty row and click the cut button
- Now click process at the bottom-right side of the GUI
- Workbench crashes

### Platforms affected
Tested on Windows 10

**Comment by gemmaguest** [comment]
After discussion with @hsautessella it looks like this has been fixed on master
