### ISSUE TITLE
Muon Analysis 1 results table

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#26120]
### Expected behavior
Results table in muon analysis 1 should output table of log values, converting the type into a string as needed

### Actual behavior
When creating table using sample_temp or run_number, mantidplot returns a type mismatch error

### Steps to reproduce the behavior
1. Open mantidplot
1. Open muon analysis
1. Load EMU 20918
1. Go to Data Analysis tab
1. Add a flat background and Abragam to fitting browser
1. Fit
1. In runs load EMU 20918-20
1. Without changing any settings use Fit again
1. Go to results table
1. Check run_number and sample_temp, and check both fitting results
1. Create Table

### Platforms affected
Tested on windows.

**Comment by AnthonyLim23** [comment]
I think I understand why this happens. The second fit is on a co-added set of runs, the old GUI outputs the logs as a range (if they are not the same for all of the runs that have been co-added). Whereas the first fit was on a single run and has just a numerical value.

**Comment by AnthonyLim23** [comment]
here we set the column types https://github.com/mantidproject/mantid/blob/master/qt/scientific_interfaces/Muon/MuonAnalysisResultTableCreator.cpp#L130

here we set the row values:
https://github.com/mantidproject/mantid/blob/master/qt/scientific_interfaces/Muon/MuonAnalysisResultTableCreator.cpp#L508

I think its the second one thats gone wrong as it only checks the current log value and not the column type. However, changing this could lead to problems in the first link if it is not checking every ws for a given log value.
