### ISSUE TITLE
QtiPlot plotSpectrum() function error bars

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#26139]
### Expected behavior
According to the 1D plots [documentation](https://www.mantidproject.org/MantidPlot:_1D_Plots_in_Python) the plotSpectrum() function should provide error bars on the graph in this layout: 
`graph_spec = plotSpectrum("RawData", 0, True)`
### Actual behavior
No error bars are produced due to the error bars parameter being the 4th one, rather than the 3rd as assumed in the documentation (which is for distribution). 
### Steps to reproduce the behavior
1. Execute this code in the Python Window:
```
from pymantidplot.qtiplot import plot

w = Load("MAR11060")
graph_spec = plotSpectrum("MAR11060", 0,True)
```
2. This code will produce error bars:
```
from pymantidplot.qtiplot import plot

w = Load("MAR11060")
graph_spec = plotSpectrum("MAR11060", 0,True,True)
```
### Platforms affected
Tested on Ubuntu 18.04.1

**Comment by martyngigg** [comment]
Fixed on wiki. No code changes required.
