### ISSUE TITLE
MantidPlot: 'about' help button removal 

### ISSUE THREAD

**Issue by ciaranightingale** [mantidproject/mantid#26134]
Expect button to open a help document when 'question mark' is clicked however when a document is not available a red stop sign appears and requires another click to disappear.
Tested on multiple machines running Windows 10 64 bit, Linux Ubuntu.

The steps to reproduce are:
- Open MantidPlot
- Open Help->About MantidPlot
- Click the question mark button in the top right hand corner

Nick has recommended removing the help button.

**Comment by giovannidisiena** [comment]
Fixed for WorkBench, still needs completing for MantidPlot
