### ISSUE TITLE
Change deprecation notice for old reflectometry GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26130]
The `ISIS Reflectometry (old)` interface has a deprecation notice stating it will be removed in July 2019. I'm going to leave it in till the next release so this date should be pushed forward (or, perhaps better, replaced with the version number it will be removed in, which will be 4.2.0). 

This is because the new GUI has had a lot of work in 4.1.0 and I want to be sure it meets users needs before removing the old one.

**Comment by Pasarus** [comment]
Already completed in an earlier PR.
