### ISSUE TITLE
Instrument view miniplot save to workspace no longer works

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26136]
**Original reporter:** Pascal ISIS

### Expected behavior
You can save an integrated plot from the instrument view miniplot to a workspace

### Actual behavior
Clicking "Save to workspace" does nothing

### Steps to reproduce the behavior

Observed with WISH data. Load a file, show the instrument. 

Choose the "pick" tab, choose an ellipse, the integrated intensity appears and in the window where it appears, when we right click and select "Save Plot to workspace" that bit doesn't work for us.

### Platforms affected
All

**Comment by ConorMFinn** [comment]
Also observed with GEM, HRPD, MARI. Works as expected on SXD and LOQ instruments.

**Comment by PhilColebrooke** [comment]
I've also found that using the "Add single crystal peak" tool and doing "Save plot to workspace" causes a hard crash in Workbench.

**Comment by martyngigg** [comment]
@ConorMFinn @PhilColebrooke Thank you for the additional information here. I'll look into the bug with save plot to workspace when a shape is not selected.
