### ISSUE TITLE
Indirect data reduction allows plot raw with invalid input file

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26149]
When providing an invalid Run No the Plot raw button can be pressed.

### Expected behavior
The button should be deactivated (like the run button)

### Actual behavior
Can be pressed and `Unexpected exception: Invalid value for property Filename (list of str lists) from string "": No file(s) specified.
Continue working.` returned

### Steps to reproduce the behavior
- Interfaces->Indirect->Data reduction->ISIS calibration
- enter invalid Run No (eg. a1)
- press plot raw

### Platforms affected
Tried on Ubuntu 18

**Comment by robertapplin** [comment]
The solution to this is to remove the `Plot Raw` button, as it is not needed. It just plots the raw data in the PreviewPlot, however this is done anyway when a file has finished loading.
