### ISSUE TITLE
Indirect Corrections crashes MantidPlot

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26157]
MantidPlot crashes without warning if in the Indirect Corrections->Apply Absorption Corrections one provides a non-correction file as Corrections

### Expected behavior
The interface should return an error

### Actual behavior
A segmentation fault happens and MantidPlot crashes

### Steps to reproduce the behavior
- Interfaces->Indirect->Corrections->Apply Absorption Correction
- Select a file (works with irs26174_graphite002_red in sample data) to add as Sample
- Add a random file as Corrections
- Press Run

### Platforms affected
Tested on Ubuntu 18

**Comment by SpencerHowells** [comment]
Either the file must end _Corrections ie always restrict name or check that the file is a GroupWorkspace with the first member ending _ass

**Comment by LolloB** [comment]
I just tried it on workbench and it crashes as well.
