### ISSUE TITLE
Trivially exportable citations including DOIs(EPIC)

### ISSUE THREAD

**Issue by DanNixon** [mantidproject/mantid#26159]
Refer to https://github.com/mantidproject/documents/pull/67.

See issues in the epic

This has been extended from the original design document to carry raw data DOIs through the end to end system and make sure that interfaces and processing scripts export the citations in a _citations.txt file at the end of processing, both within autoreduction and interfaces within Mantid.

**Comment by AnthonyLim23** [comment]
Not sure where it is best to put this. We need to make sure that:

Arithmetic algorithms should combine the citations from the two input workspaces.

**Comment by DanNixon** [comment]
@AnthonyLim23 I'm assuming the same consideration was already taken for algorithm history reporting.

**Comment by AnthonyLim23** [comment]
it would be nice to get this done
