### ISSUE TITLE
Background range can be set in Data Analysis Elwin even if background is disabled

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26182]
When not subtracting the background, the Background range can still be modified.

### Expected behavior
Background Range should be disabled when Background Subtraction is not ticked.

### Actual behavior
The range can still be modified.

### Steps to reproduce the behavior
- MantidPlot->Interfaces->Indirect->Data Analysis->Elwin
- Load an input file
- Untick Background subtraction

### Platforms affected
Tested on Ubuntu 18

**Comment by robertapplin** [comment]
Fixed in #26198
