### ISSUE TITLE
Calculate Paalman Pings crashes the workbench

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26183]
In the calculate Paalman Pings tab, when loading a file that ends in _sqw selecting a chemical formula and running the algorithm, the workbench crashes  due to an unhandled exception:
`what(): Invalid value for property InputWorkspace (MatrixWorkspace) from string "iris26176_graphite002_iqt": The workspace must have units`

### Expected behavior
An error message should be displayed if the input file is invalid.

### Actual behavior
The algorithm fails and the workbench crashes.

### Steps to reproduce the behavior
- workbench->Interfaces->Indirect->Corrections->Calculate Paalman Pings
- As input select a _sqw file (eg. ExternalData/Testing/Data/SystemTest/BASIS_59689_divided_sqw.nxs)
- Input a chemical formula (eg. H2-O)
- Click Run

### Platforms affected
Tested on workbench for Ubuntu 18

**Comment by SpencerHowells** [comment]
A _iqt file is illegal! The filter should be to only access _red files.

**Comment by LolloB** [comment]
The filter also show _sqw files which also crash the workbench with exception `what(): Instrument has no efixed parameter`

**Comment by SpencerHowells** [comment]
BASIS is a SNS instrument. I don't know how they reduce their data to sqw but it seems that they do not set a value for efixed in the workspace. This is a basic Mantid parameter required to convert time-of-flight to energy transfer and is used by ISIS & ILL instruments.
