### ISSUE TITLE
Loading large numbers of runs in Muon Analysis

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#26195]
If you attempt to load more than 100 runs in the Muon Analysis GUI an exception is thrown saying that it can only load a maximum of 100 at any one time. This exception is not caught and makes it to the last chance error handler.

This needs to be investigated and either the limit should be removed or the exception should be handed more gracefully.

**Comment by LolloB** [comment]
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/utilities/run_string_utils.py#L17

**Comment by LolloB** [comment]
When loading runs 62022-122 the first check in run_string_to_list() passes but another one fails later only after all the runs have loaded, a popup appears and an error returned.
