### ISSUE TITLE
After Release Update windows build servers to windows 10

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26219]
Also remove references to the nightly build being suitable for windows 7 or 8

It is still fine to build against the windows 7 API (but not essential)

**Comment by martyngigg** [comment]
Increased estimate as there will be some degree of waiting for FIT to rebuild the machines

**Comment by martyngigg** [comment]
Remove VS2019 blocker as actually we will want both VS2017 & VS2019 on so a patch is possible.

**Comment by martyngigg** [comment]
No code changes required. All machines are now running Windows 10.
