### ISSUE TITLE
Investigate vs2019 cmake integration and workflow

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26218]
vs 2019 has better integration with cmake than earlier versions offered.
Investigate what this could allow for us, and if it is worth moving from the current vs workflow.

**Comment by hsautessella** [comment]
I reached a bit of a dead end with this. Possibly worth abandoning for now.

For the following, make sure you have the `C++ Tools for Windows` extension installed.

### Attempting to open an existing Mantid build as a CMake project on VS:
- Open VS via `visual-studio.bat` in the build folder
- Go to 'File'->`Open`->`CMake`. Navigate to your build folder and open the top level CMakeCache.txt.
After a while Visual Studio gives up on reading the cache, giving the following output:
```
1> CMake generation started for configuration: 'Mantid'.
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted includes paths.
1> Extracted code model.
1> Target info extraction done.
1> Error: Parsing error during CMake response. Timeout: C:\Program Files\CMake\bin\ctest.exe --show-only=json-v1 -C Debug did not finish after 1m 0s, 0ms
```

### Attempting to create a new build as a CMake project
- Open VS. On the "Get started" screen, select `Continue without code` 

- Go to 'File'->`Open`->`CMake`. Navigate to the source directory and open the top level CMakeLists.txt

- Wait as Visual Studio tries an analyse the file. You will eventually see the warning below pop up.
<img src=...>

- In the main toolbar locate the Configuration drop-down menu (it's to the left of the "Select Startup Item" button). Click the arrow and select `Manage Configurations...`

- Add a new configuration. You can choose Release or Debug, but your toolset should be msvc_x64_x64.

- Near the bottom click `Show advanced settings`. In here select `Visual Studio 16 2019 Win64` as the generator.

- Alternatively, click `Edit JSON` in the top right corner. This is the configuration I used:

```json
{
      "name": "x64-Release",
      "generator": "Visual Studio 16 2019 Win64",
      "configurationType": "Release",
      "buildRoot": "${projectDir}\\..\\build",
      "installRoot": "${projectDir}\\..\\install",
      "cmakeCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "variables": []
    }
```

- Save and you should see a notice saying that your CMake settings have changed and asking if you'd like to generate; do so.
- After waiting a while for thigns to generate I get the following error:

```
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Error: Timeout: c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\ctest.exe --show-only=json-v1 -C Release did not finish after 1m 0s, 0ms
```

Perhaps I'm missing something that will fix these problems but, at present, it doesn't seem worth moving away from the current Windows workflow.

Closing this issue for now.
