### ISSUE TITLE
Windows build of google test has whitespace errors

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26212]
### Expected behavior
Builds should pass

### Actual behavior
They do not:
https://builds.mantidproject.org/job/pull_requests-win7/31125/

### Steps to reproduce the behavior
Cause a clean_external_products build on jenkins

### Platforms affected
Windows on Jenkins

**Comment by DavidFair** [comment]
Just deleted google-test / re-ran cmake locally (akin to what Jenkins does) and can't reproduce

I guess this was either an upstream issue, or a Jenkins node whose copy of Google test got corrupted
