### ISSUE TITLE
Muon Analysis 2 crashes when loading after fit

### ISSUE THREAD

**Issue by BassoLorenzo** [mantidproject/mantid#26229]
### Expected behavior
The specified data runs should be loaded

### Actual behavior
An exception is raised:
`RuntimeError: wrapped C/C++ object of type FigureWindow has been deleted`

### Steps to reproduce the behavior
- `workbench->Interfaces->Muon->Muon Analysis 2`
- set instrument to EMU
- load runs `62260-62265`
- `Muon Analysis->Fitting` select `simultaneous fit`
- select a function and run the fit
- Reload the data

### Platforms affected
Tested on workbench for Ubuntu 18

**Comment by AnthonyLim23** [comment]
@LolloB do you still get this crash? I cannot reproduce it on 4.1
