### ISSUE TITLE
Review / update release notes

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26232]
Shared issue for us all to use for release note update PR's

**Nick**
- [x] Main Page
- [x] Framework
- [x] Mantidplot
- [x] Mantid Workbench

**Gemma**
- [x] Relfectometry
- [x] SANS - Matthew

**Anthony**
- [x] Direct Inelastic
- [x] Inirect Inelastic
- [x] Muons

**Martyn**
- [x] Diffraction

**Comment by AnthonyLim23** [comment]
I think the direct are ok, if we remove the warning

**Comment by martyngigg** [comment]
I'm about to edit/review the diffraction ones so I can remove that
