### ISSUE TITLE
ALC crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26250]
Open workbench
Set default instrument to EMU
Open ALC
For first enter 94183
for Last enter 94185
Click Load
Go to baseline modelling
Add a fitting function and region
Do a fit
Go to peak fitting and do a fit
Go back to data loading
Then for first and last browse to some HIFI data
Click Load
Mantid will load the data and then through an error.

**Comment by AnthonyLim23** [comment]
this was not present in v 4.0

**Comment by Pasarus** [comment]
This is the error I am getting:
![image](https://user-images.githubusercontent.com/24723609/60885641-f1865080-a247-11e9-96db-32981924d216.png)

and if I load again immediately afterwards it causes a segfault

**Comment by robertapplin** [comment]
I have found the fix for this @Pasarus . Are you ok with me creating a PR to fix this?

**Comment by Pasarus** [comment]
@robertapplin If you are working on an issue on the project board could you assign yourself next time? also it would be great so I don't need to continue.

**Comment by AnthonyLim23** [comment]
thats the bug
