### ISSUE TITLE
Indirect Settings - Extra settings options

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#26274]
### Description
The Indirect Settings GUI should be re-designed so there are two sections: 
- An Input Data section: this sections deals with settings related to the input data you want to load.
- A Plot Options section: this sections allows you to customize your plots

This will mean that these common options can be removed from the other interfaces (Load History on Elwin, Load logs on ISISEnergyTrans, Calib, etc.)

**Input Data Section**
- [X] Restrict Input Data By Name
- [ ] Load History
- [ ] Load logs

**Plot Options Section**
- [X] Plot error bars
- [ ] Error bar styles (matplotlib allows a large number of customize-able properties)
- [ ] Line styles
- [ ] Frequency of ticks on the side of graphs, etc.

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
are these mini-plots?

**Comment by robertapplin** [comment]
This is referring to the external plotting, (so not the mini-plots within the interface). External plots are usually triggered using the `Plot Current Preview` button (which plots the spectra currently visible in the mini-plots), and using the output plotting options.
