### ISSUE TITLE
Workbench: Investigate exceptions raised in a triggered Qt Slot

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantid#26290]
### Expected behavior
Exceptions in Qt slots should trigger the custom `sys.excepthook` as normal exceptions.

### Actual behavior
They seem to segfault. 

More info: https://stackoverflow.com/questions/18740884/preventing-pyqt-to-silence-exceptions-occurring-in-slots.

Issue encountered in https://github.com/mantidproject/mantid/issues/26288, at commit 57fd9925ea065a2f1e881a75768699dc8af7f22d

### Steps to reproduce the behavior
Follow https://github.com/mantidproject/mantid/issues/26288

### Platforms affected
Seen on Ubuntu 18, should affect all

**Comment by hsautessella** [comment]
Related to  #25420?
