### ISSUE TITLE
Link not working in algorithm documentation

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#26306]
### Steps to reproduce the behavior
Open any algorithm documentation, either the built-in or the online documentation
Go to the bottom and click on `Categories: Algorithm Index` 
It will go to a nonexistent page. The online version points to [https://docs.mantidproject.org/nightly/algorithms/categories/AlgorithmIndex.html](https://docs.mantidproject.org/nightly/algorithms/categories/AlgorithmIndex.html) instead of [https://docs.mantidproject.org/nightly/algorithms/categories/Algorithm Index.html](https://docs.mantidproject.org/nightly/algorithms/categories/Algorithm%20Index.html) Note the extra space between algorithm and index

**Comment by NickDraper** [comment]
@AndreiSavici thanks for spotting this :+1:
