### ISSUE TITLE
Move axis operations from CurvesTabWidgetPresenter to FigureErrorsManager

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantid#26330]
Some of the functions in `CurvesTabWidgetPresenter` operate only on matplotlib axes, and will be better located in `FigureErrorsManager`, as an external class that is used for the operation within the presenter.

The `FigureErrorsManager.add_error_bars_menu` function can also be moved in a different class - it also creates Qt UI elements that shouldn't be in the class that manages errors on figures.

Should be done after #25617

**Comment by hsautessella** [comment]
Deassigning myself as I won't get to this in this maintenance period
