### ISSUE TITLE
Workbench Fit Parameters are not updating, and no Fit is plotted

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#26333]
### Expected behavior
The Fit curve and difference for the selected spectrum should be plotted, and the parameters in the FitPropertyBrowser should be updated when changing between the workspace indices.

Changing between the workspace indices should also display the Fit and difference curves for the selected spectrum.

### Actual behavior
No fit is plotted. The parameters are not updated.

### Steps to reproduce the behavior
1. Workbench
2. Load the data below
3. Right click the workspace and plot the first index
4. Click `Fit`
5. Select `Lorentzian` and `Flat Background`
6. `Fit`->`Sequential Fit`->`Ok`
No fits plotted, and parameters won't update.

**Data**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3391843/irs26176_graphite002_red.zip)

### Platforms affected
All

**Comment by robertapplin** [comment]
Occasionally we see that 2 spectra are plotted after doing a Fit. I think these are the fit curve and difference for the selected spectrum.

**Comment by alicerussell1** [comment]
After looking into this I have found that the sequential fit dialog depends on the mantidplot UI so the signals are not being passed to the fit browser. When you load the dialog box in workbench it gives the message `QObject::connect: Cannot connect MantidQt::MantidWidgets::SequentialFitDialog::needShowPlot(Ui::SequentialFitDialog *, MantidQt::MantidWidgets::FitPropertyBrowser *) to (null)::showSequentialPlot(Ui::SequentialFitDialog *, MantidQt::MantidWidgets::FitPropertyBrowser *)`.

**Comment by martyngigg** [comment]
I have added a [release note](https://github.com/mantidproject/mantid/tree/release-next) to the workbench in 4.1 to state that this is a known issue.
