### ISSUE TITLE
Import error in workbench

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26357]
### Expected behavior
Import should work

### Actual behavior
Import doesn't

### Steps to reproduce the behavior
Follow the steps on this forum post (https://forum.mantidproject.org/t/beta-test-import-error/543)

### Platforms affected
Windows 10

**Comment by NickDraper** [comment]
This was a problem with .pyc files on a dropbox share being generated on one computer, and used on another.  The stored paths were then wrong.

Not a mantid problem

**Comment by Pasarus** [comment]
This was found to be an issue with the user having .pyc files for his script from a different PC.
