### ISSUE TITLE
Indirect data reduction crash when plotting

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26385]
Open workbench
Open the Indirect reduction GUI
Go to Energy transfer tab and enter run 59057 (IRIS)
Click plot. 
Mantid will throw a runtime error and never exits

**Comment by AnthonyLim23** [comment]
we should just disable the plot button until after run has completed

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Don't understand this. I use my standard calibration run iris26173 to run Calibration. Back in EnergyTransfer I select the file & leave the run blank. When I click on Plot a message box pops up saying I must select a run file.

**Comment by AnthonyLim23** [comment]
@SpencerHowells I enter a run, but dont press the run button. It seems to fall over due to not having data to plot

**Comment by SpencerHowells** [comment]
@AnthonyLim23 I get a plot of iris26176_grp spec 0

**Comment by AnthonyLim23** [comment]
only seems to happen with IRIS

**Comment by AnthonyLim23** [comment]
it seems to be a problem with the loader for the files around 59057

**Comment by SpencerHowells** [comment]
Does MantidPlot fail as well?
