### ISSUE TITLE
Closing Indirect interfaces causes mantid to crash

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26396]
When `Indirect Bayes` or `Indirect Corrections` are closed immediately after loading a file, MantidPlot will crash with the error message:
> Segmentation fault (core dumped)

If something is done (eg. a button pressed, tab changed etc.) before closing then the crash does not occur.

### Expected behavior
The window should close successfully.

### Actual behavior
MantidPlot crashes.

### Steps to reproduce the behavior
1. `Interfaces->Indirect->Bayes` (or `Corrections`)
2. Load some data (eg. irs26173_graphite002_red, irs26173_graphite002_res)
3. Without touching anything else, close the window

### Platforms affected
Tested on Ubuntu 18.04

**Comment by AnthonyLim23** [comment]
I can't get this on windows. @Mantid-Matthew can you reproduce this?

**Comment by DTasev** [comment]
I can't replicate this on Ubuntu 18 compiled at eca4d2834cc

**Comment by NickDraper** [comment]
This works fine for me on Windows 7 with the release candidate, so I'm going to close this one for now.
