### ISSUE TITLE
Peak selector lines in Indirect Bayes move only in one direction

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26393]
### Expected behavior
Peak selector lines should be dragged in both direction like in the other interfaces.

### Actual behavior
The `EMin` line only moves to the right, the `EMax` only to the left. When they reach the same position they get "stuck" and they can only be moved back by resetting the numerical value.

### Steps to reproduce the behavior
1. `Interfaces->Indirect Bayes->ResNorm`
2. Load some data for vanadium and resolution (eg. irs26173_graphite002_red.nxs, irs26173_graphite002_res.nxs)
3. Drag the peak selector lines

### Platforms affected
Tested on Ubuntu 18.04

**Comment by AnthonyLim23** [comment]
is anyone currently working on this?

**Comment by NickDraper** [comment]
All works fine now, even crossing the lines
