### ISSUE TITLE
Hiding internal Fit functions

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26398]
The PeakParameterFunction seems to be an internal function that should never be used explicitly by users, in fact it crashes Mantid if you try,

It is used in IPeakFunction, and currently creates it from the FunctionFactory.  We need to consider how to handle these "internal" functions that are not intended for our users. Should we?

1. Remove these functions from the FnFactory, and just handle the creation of them ourselves?
1. Add the concept of Hidden Functions in a similar way to hidden algorithms? (we have had indirect and muon suggest they would like this), but if we want users to use it we have to think about a UI as well.
1. Have an explicit blacklist on the Factory (I'm not a fan of this as it separates the code from the Fn itself)

**Comment by martyngigg** [comment]
Option 2 but no UI, just have the setting in the .properties file
