### ISSUE TITLE
Reduce SANSStitch workflow graphs complexity to fix warning

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26406]
### Expected behavior
No warnings on building `docs-html`

### Actual behavior
Get this warning:
```
reading sources... [ 46%] algorithms/SANSSolidAngleCorrection-v1
reading sources... [ 46%] algorithms/SANSStitch-v1
Warning: Unable to reclaim box space in spline routing for edge "subtractCanLAB" -> "valQLAB". Something is probably seriously wrong.
reading sources... [ 46%] algorithms/SANSSubtract-v1
reading sources... [ 46%] algorithms/SANSWideAngleCorrection-v1
```

### Steps to reproduce the behavior
Do a clean `docs-html` target build

### Platforms affected
Ubuntu

**Comment by DavidFair** [comment]
This is still an issue, looking at it we need to tidy down the graph as DOT is having problems routing the line of this edge

**Comment by Pasarus** [comment]
@gemmaguest @DavidFair Is this issue still a problem if not I would like to close.

**Comment by DavidFair** [comment]
I've not run into it since and everyone forgot about it, so lets stale it
