### ISSUE TITLE
Smoke Testing Umbrella issue

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26415]
This is to keep track of the coverage of smoke tests during the release cycle.
Please tick and add your name against an item when you are taking it.
Please make sure you use the installers from the release pipeline https://builds.mantidproject.org/view/Release%20Pipeline/

Reset for the release candidate build on Monday
Reset and cut down for final tests

## Clean/Dirty Install Smoke Tests: #26408
 - [x] Windows @NickDraper
 - [x] OSX: @martyngigg 
 - [x] Linux: @DTasev (U16.04, U18.04, CentOS7) 

## Interface Smoke Tests: #26411
 - [x] Windows @NickDraper
 - [x] OSX  @martyngigg
 - [x] Linux

**Comment by martyngigg** [comment]
Mac is missing the C++ interfaces for workbench. #26420 created.

**Comment by NickDraper** [comment]
Reset for the release candidate build on Monday

**Comment by NickDraper** [comment]
Reset and cut down for final tests
