### ISSUE TITLE
HFIR open project raises exception when closing dialog window

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#26419]
### Expected behavior
When closing load project window in HFIR 4Circle Reduction mantid should not rise an exception.
### Actual behavior
Closing the open project (or any save/load dialog window) HFIR expects to be given a string to load even if open is not clicked
### Steps to reproduce the behavior
1. Open workbench
1. Open Interfaces --> Diffraction --> HFIR 2Circle Reduction
1. go to File --> Open Project
1. close the Choose Project File.
### Platforms affected
Seen on Windows, but probably everywhere

**Comment by NickDraper** [comment]
I've just verified that this was also the case for r4.0 so this is not a step backwards

**Comment by NickDraper** [comment]
@peterfpeterson This is an issue we have found during smoke testing that was also present in the last release.  My temptation is to say that we push it out of this release, however if someone at ORNL wanted to fix it, (and it was very low risk to do so). then if you could get a fix in and merged before the builds run tonight it could be included.

**Comment by wdzhou** [comment]
@NickDraper @peterfpeterson Till Nov. 3rd, no one in ORNL will use this interface.  So I think it better to put it to the next release.
