### ISSUE TITLE
Interface smoke tests

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26411]
# Interface/misc smoke tests

Please run these tests on the compiled package of Mantid; **not a locally compiled version**.

When reporting back please include:

- Your OS
- Your facility/location
- If you have other package versions of Mantid installed (yes/no)

If you have any questions please don't hesitate to contact the creator of this issue.

## Checklist/directions

- [x] Mantid opens without errors or warnings 
- [x] Every option in `Interface` opens a GUI 
- [x] Load some test data 
- [x] Catalogue opens  [directions here](https://www.mantidproject.org/Catalog_Search) 
- [x] Saving/loading projects works  [directions here](https://www.mantidproject.org/MantidPlot:_The_File_Menu#File-.3E_Save_Project_as...)

**Comment by NickDraper** [comment]
Tested and passed on windows 7 mantidplot

**Comment by NickDraper** [comment]
Tested and passed on IDAaaS mantidplot and workbench

**Comment by Harrietbrown** [comment]
Tested and passed on windows 7 mantidplot and workbench

**Comment by ConorMFinn** [comment]
Tested and passed on Ubuntu 18.04 || MantidPlot and Workbench

**Comment by alicerussell1** [comment]
Tested on Windows 10 mantidplot and workbench - no unknown issues found

**Comment by martyngigg** [comment]
Tested on OSX 10.12 after latest changes for embedded help - all looks good.

**Comment by NickDraper** [comment]
tested on windows 7 mantidplot and workbench

**Comment by martyngigg** [comment]
Tested on RHEL 7 and all looks fine.

**Comment by DTasev** [comment]
Testing on Ubuntu 18.04
