### ISSUE TITLE
Fitting Smoke Tests

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26410]
# Fitting smoke tests

Please run these tests on the compiled package of Mantid; **not a locally compiled version**.

The check boxes should correspond to headings in the documentation (linked). Just follow the corresponding directions.

When reporting back please include:

- Your OS
- Your facility/location
- If you have other package versions of Mantid installed (yes/no)

If you have any questions please don't hesitate to contact the creator of this issue.

## Checklist/directions

* Fitting to data [directions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/fitting_data/01_fitting_models_to_data.html#fitting-models-to-data)
	* Simple fit [ ]
	* Activating the fitting tools [ ]
	* Selecting the fitting range [ ]
	* Other Fit Function Settings properties [ ]
	* Setting up a fit model [ ]
	* Adjusting fit function parameter [ ]
	* Saving a model [ ]
	* Tying and constraining fit parameters [ ]
	* Execute your fit [ ]
	* Inspecting a fit result [ ]
* Additional options [directions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/fitting_data/02_fit_model_choices.html#fit-model-choices)
	* Non peak model + background [ ]
	* User defined function [ ]

**Comment by giovannidisiena** [comment]
Tested on Ubuntu 18.04 VM with no issues.  Other package versions of Mantid installed (yes)

**Comment by ciaranightingale** [comment]
Windows 10, ISIS, no issues found.

**Comment by giovannidisiena** [comment]
**All Tests Passed | Plot and Workbench**
**OS:** Ubuntu 18.04
**Facility:** ISIS
**Other Versions:** Yes

**Comment by hsautessella** [comment]
##### Windows 10, ISIS. Installed alongside a Nightly and an Unstable build.

No major issues found on MantidPlot or Workbench.
