### ISSUE TITLE
Remove handling code in SANS Utility for bad proton charges

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#26436]
There is currently some specific code (from #25571), in the SANSUtility class for handling runs with a bad proton charge log when they are added. Once a more general method of dealing with corrupted files is added this handling case should be removed.

**Comment by smk78** [comment]
This surely cannot be specific to ISIS SANS? Though it is possible that we may be 'more susceptible' to it.

Freddie Akeroyd should be consulted too.

**Comment by gemmaguest** [comment]
I'm going to close this as stale because it's unlikely a more general fix will be added and the current fix doesn't do any harm.
