### ISSUE TITLE
Adding a fit and functionlize algorithm for pre-Placzek correction work

### ISSUE THREAD

**Issue by marshallmcdonnell** [mantidproject/mantid#26454]
**To Do**
Before the recoil (ie Placzek) correction can be calculated for a workspace, the incident spectrum must first be calculated and then, secondly, the incident spectrum must be fit and functionalized. This latter step is to get a smooth, functional form of the incident spectrum and find derivatives of the functional form, both necessary to calculated the origin Placzek correction.

The initial work for the first step (calculating the incident spectrum) is already complete and the issue and PR for that are down below. This is to help if any of the scripts in that work can help to determine the inputs of this work.

Currently, python scripts exists that take different inputs for the incident spectrum but all give back out the functional form of the incident spectrum and its first derivative using different methods:
 - Cubic spline using `scipy.interpolate.splrep` and `scipy.interpolate.splev` is found [here](https://github.com/marshallmcdonnell/mantid_total_scattering/blob/7d71668a2bddfcf2440634f68d3590041d8e8abc/total_scattering/inelastic/incident_spectrum.py#L32-L36)
 - Cubic spline via Mantid is found [here](https://github.com/marshallmcdonnell/mantid_total_scattering/blob/7d71668a2bddfcf2440634f68d3590041d8e8abc/total_scattering/inelastic/incident_spectrum.py#L39-L62)
 - A curve fit of the analytical function from Spencer Howells's work (for references, see the Issue and PR below in *Related Previous Work*) using `scipy.optimize` is found [here](https://github.com/marshallmcdonnell/mantid_total_scattering/blob/fix_placzek/total_scattering/inelastic/incident_spectrum.py#L65-L95)
 - Cubic spline using `scipy.interpolate.UnivariateSpline` with input weights calculated using Gaussian convolution is found [here](https://github.com/marshallmcdonnell/mantid_total_scattering/blob/7d71668a2bddfcf2440634f68d3590041d8e8abc/total_scattering/inelastic/incident_spectrum.py#L98-L111)

The last option (cubic spline w/ gaussian convolution) is the one I have found to do "the best" (ie fits with little "fiddling", best fit, etc.) but only tested for NOMAD diffractometer's incident spectrum so far.

The python script found [here](https://github.com/marshallmcdonnell/mantid_total_scattering/blob/fix_placzek/total_scattering/inelastic/incident_spectrum.py) is a "hacky", proto-type for developing this algorithm.

**(Should) Return**
A group workspace with a variable number of workspaces (initially, incident spectrum and workspaces for each derivative returned). 

**Related Previous Work**

 - work to get a general efficiency calculator to calculated incident spectrums
Issue: https://github.com/mantidproject/mantid/issues/24432
PR: https://github.com/mantidproject/mantid/pull/24451

**Comment by martyngigg** [comment]
Functionally complete.
Moved to 4.2 S2 to complete testing, validation+docs
