### ISSUE TITLE
Muon Analysis Fabada fit can never work

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#26478]
The Fabada fit method requires a certain number of max iterations to work. Currently in Muon Analysis we do not have the number of Max iterations as a changeable option and the default value does not allow Fabada to run. This means that there is no way to run a fit with the Fabada option from the GUI.

**Comment by AnthonyLim23** [comment]
I have never seen any muon scientists use FABADA, is this a request from them or something we noticed?

**Comment by Mantid-Matthew** [comment]
This is something we noticed. The simplest fix is simply to remove FABADA as an option
