### ISSUE TITLE
Frequency Domain Analysis should set sensible fitting limits

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#26475]
Currently in the frequency domain analysis GUI the maximum fitting range defaults to 15, this is far to small for the normal frequency ranges which occur. What the best way to determine a default fitting range is should be investigated and then implemented.

**Comment by AnthonyLim23** [comment]
We should probably use the context to determine the start and end values. Then we can have a check in the context to see if it is frequency data and if it is return the new fitting range. We would need to be careful to make sure we only use the 'new' range when the data switches between time and frequency data. It should not replace the range if we just change the data (but its from the same domain).

**Comment by AnthonyLim23** [comment]
also should put a check in for #25821
