### ISSUE TITLE
LoadPSIMuonBin: Handle what is best when it comes to each spectra having individual T0

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26496]
PSI data is provided with a T0 for each spectrum.

We should come up with a solution for either handling it and actually providing support for it in the long term.

In the short term, we should at least pick the max value out of the array instead of the first value. This is handled at LoadPSIMuonBin.cpp:180.

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/LoadPSIMuonBin.cpp#L184

**Comment by AnthonyLim23** [comment]
numberOfHistograms
