### ISSUE TITLE
Workbench: Toggling normalisation on Muon Analysis 2 plots throws exception

### ISSUE THREAD

**Issue by hsautessella** [mantidproject/mantid#26505]
### Expected behavior
Toggling normalisation on plots created in the Muon Analysis 2 GUI should not throw an error.

### Actual behavior
It does.

### Steps to reproduce the behavior.
- Open workbench and the Muon Analysis 2 GUI.
- Switch instrument to MUSR and load run number 62260.
- Right-click the resulting plot and toggle the normalisation.
- The error reporter will pop-up.

The issue is caused by Muon figures having the creation arg `autoscale_on_update` that `FigureInteraction._toggle_normalization` is not aware of, and does not remove before passing the kwarg to Matplolib to redraw the line. Matplotlib then throws an error.

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
this has been fixed
