### ISSUE TITLE
Workbench: Can't save existing project with new name

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#26513]
### Expected behavior
You should be able to save an existing project with a new name.

### Actual behavior
Workbench closes without saving.

### Steps to reproduce the behavior
1. In Workbench, open an existing project.
2. Make a change to the project, e.g. load another workspace.
3. Click the X in the corner to close Workbench.
4. When asked if you want to save before closing, click Yes.
5. When asked if you would like to overwrite the project. click No.

Workbench also closes if you click the X in the corner of the last dialog, when it would be better if it only closed the dialog and Workbench stayed open.

### Platforms affected
Presumably all.

**Comment by gemmaguest** [comment]
There's another related problem: if you get as far as the Save As dialog (either when saving an existing project or a new one) and click Cancel, then Workbench closes. Would it be better if it just closed the dialog without closing Workbench?

**Comment by PhilColebrooke** [comment]
> There's another related problem: if you get as far as the Save As dialog (either when saving an existing project or a new one) and click Cancel, then Workbench closes. Would it be better if it just closed the dialog without closing Workbench?

I've also had a go at fixing that, see #26519
