### ISSUE TITLE
Add Options and SlitCalculator for reflectometry GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26533]
The ISIS Reflectometry GUI used to have a menu option to open an options dialog and slit calculator. This should be re-added.

## Options dialog
This depends on PR #26835, which has done the work to add the Tools menu and an outline notification function and test for the presenter (see the TODOs in the code from that PR). You can apply this patch to add the Options dialog into the Tools menu and to connect the slot in the view:  [0001-Revert-Remove-Options-Dialog-from-the-menu.zip](https://github.com/mantidproject/mantid/files/3630680/0001-Revert-Remove-Options-Dialog-from-the-menu.zip)

Then the main remaining task is to implement the new Options dialog.

The dialog allows control of:
- the precision shown in the table
- whether warnings should be shown for:
  - table changes will be lost
  - you're about to process only a subset of a group
  - you're about to process all rows in the table

The warnings above should also be added (the only one currently implemented is to warn on losing table changes when starting autoprocessing, but we should also warn when closing the GUI)

~~There is potentially a bug where AutoProcess does not ask you if it is ok to overwrite a single group and row as that is effectively an "empty" table~~ - no longer a problem.

- [x] We can largely copy the layout from `DataProcessorOptionsDialog.ui` but the old dialog is too tied to the data processor to be  useful. 
- [x] The new dialog should be owned by `MainWindow`, with communication via presenters.
- [x] We'll need to load settings when the reflectometry interface is opened (i.e. when the dialog is constructed), similarly to `QDataProcessorWidget::loadSettings`, and save them when requested from the dialog.

### Slit Calculator
PR #26835

Note that this requires the current instrument, which should be synced across tabs, hence the dependency on #26536. The existing slit calculator dialog can be used so we just need to add a menu option and notifications to open it. Note that it also needs to be updated after the instrument changes.

**Comment by giovannidisiena** [comment]
Confirmed: AutoProcess **does** ask before overwriting "empty" table.

I have observed that if you pause and then click AutoProcess again it no longer asks, however if you click Search and then AutoProcess the warning reappears. Is this expected behaviour?

**Comment by giovannidisiena** [comment]
> Confirmed: AutoProcess **does** ask before overwriting "empty" table in the latest Nightly build.
> 
> I have observed that if you pause and then click AutoProcess again it no longer asks, however if you click Search and then AutoProcess the warning reappears. Is this expected behaviour?

Also note #26981

**Comment by gemmaguest** [comment]
When you pause and resume it does not change the table, so this is correct - it's only when you change the search criteria that the table is (or may be) changed, so you get the warning

**Comment by gemmaguest** [comment]
Changed milestone to 4.3 because this requires related work to the ISIS Reflectometry GUI which is not implemented yet
