### ISSUE TITLE
Plot legend shows spectrum number rather than label

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26552]
### Expected behavior
The plot legend shows spectrum numbers

### Actual behavior
The labels from the workspace should be used instead

### Steps to reproduce the behavior
- Do a fit, e.g. as per the instructions in #25727 
- The labels are `GEM38370_Focussed_Workspace: spec 2` instead of `GEM38370_Focussed_Workspace-Calc` as they were in MantidPlot

![fit_markers_over_legend](https://user-images.githubusercontent.com/12895056/62364055-7a776b80-b518-11e9-88ca-d1d5f1503b9d.png)

### Platforms affected
Ubuntu, probably all

**Comment by martyngigg** [comment]
We need to make sure that this covers the non-fitting case where the *spec X* should be used when it has a non-text axis.
