### ISSUE TITLE
Fix C++ Exercise documentation

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#26568]
### Expected behavior
- EX01 explains what is expected of hyphenated words. 
- EX02 is consistent with its use of area.

### Actual behavior
- Unclear and inconsistent.

### Steps to reproduce the behavior
1. Visit [page](https://www.mantidproject.org/New_Starter_C%2B%2B_introduction)

### Platforms affected
All

**Comment by PhilColebrooke** [comment]
I've edited the Wiki so this issue is now fixed.
