### ISSUE TITLE
Allow data selection and function changeing during TF asymmetry mode

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#26570]
Currently when TF asymmetry mode is selected the ability to change the function structure or change the data selection are disabled. These should be enabled. There are a couple of complicating factors here. The first is that if the function structure is changed incorrectly by a user it will invalidate later workflows so we need to warn of this and handle is gracefully. The second is that if the data is changed we need to update out list of initial N0 estimates, it has been agreed that the original estimates here can be kept as they are just the start points to a fit but need to ensure that the vector sizes all remain consistent

**Comment by AnthonyLim23** [comment]
@ciaranightingale this something to be in mind when you work on the fitting tab. It would be nice if you could fix this too.
