### ISSUE TITLE
Drag drop workspace from files not working in Workbench

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#26608]
Tried with the latest nightly on OSX. Tried with a nexus file. Nothing happened, no file loaded. Drag-drop does work on MantidPlot in the same distribution.

**Comment by martyngigg** [comment]
Thanks, @OwenArnold. I've marked it for the core team's backlog

**Comment by NickDraper** [comment]
This works if you drop it into the workspaces toolbox
