### ISSUE TITLE
FDA plot type FFT All causes crashes

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#26602]
### Expected behavior
When changing plot type on frequency domain analysis to `Frequency FFT All` the plot should be updated propperly. 
### Actual behavior
When changing plot type to FFT All when multiple runs are loaded FDA raises an error
### Steps to reproduce the behavior
1. open workbench
1. open Frequency domian analysis
1. load runs 62260-62261
1. go to the transform tab.
1. turn off `Imaginary Data` and then calculate FFT
1. go to home tab, and change plot type to `Frequency FFT All`
1. an error is raised.
### Platforms affected
tested on windows

**Comment by AnthonyLim23** [comment]
ah ok, I think I know what this is

**Comment by AnthonyLim23** [comment]
I just had a go on my nightly and it worked. On master I have a bug, @Mantid-Matthew can you reproduce this in nightly or master?
