### ISSUE TITLE
FDA plotting freqency Im doesn't plot line for FFT calculated without Im data

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#26616]
### Expected behavior
Plot type 'Frequency Im` in FDA whould plot any Im line associated with the associated FFT
### Actual behavior
When using plot type 'Frequency Im` in frequency domain analysis for FFT done without imaginary data, FDA doesn't plot anything despite there being an Im line in `Frequency FFT All`
### Steps to reproduce the behavior
1. open workbench
1. open frequency domain analysis
1. load run musr 62260
1. go to transform tab
1. uncheck `Imaginary data` and click `calcualte FFT`
1. go to the home tab.
1. in plot type choose `Frequency FFT All`, there should be three lines, an Re, Im, and mod line
1. change plot type to 'Frequency Im`, there are no lines despite there being an Im componant to the FFT
### Platforms affected
checked on windows and linux

**Comment by AnthonyLim23** [comment]
I think I just fixed this in the process of writing unit tests
