### ISSUE TITLE
FDA updates to guess

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26624]
The `update_selected_frequency_workspace_guess` at https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_presenter.py#L90

should be updated (along with test) to match 
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_presenter.py#L98

Also update the GUI to not automatically select time domain and frequency domain data at the same time.

To test:
You will need access to the ISIS data Archive to test this PR
- Open Frequency Domain Analysis
- Load MUSR 62260
- Go to transform tab and do an FFT and MaxEnt (will need to change the combo box)
- Go to the fitting tab and add Guassian as a fit function.
- Go to select data and select several different frequency data sets to fit
- Do a fit
- In the load bar type 62260-70 to load several runs
- Switch to sequential fit and check that the same work spaces are selected to be fit as previously.

**Comment by ciaranightingale** [comment]
This is on hold because when you change the runs the FFTs don't exist.
