### ISSUE TITLE
VSCode Documentation Icons Need Updating

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#26633]
### Expected behavior
Documentation should match VSCode
### Actual behavior
They do not match since most recent VSCode update. 
### Steps to reproduce the behavior
Open VSCode and [this](http://developer.mantidproject.org/VSCode.html) documentation.
See they do not match.
### Platforms affected
All

**Comment by AnthonyLim23** [comment]
Remove the icons and put a link to VSCode. Have a description instead.
