### ISSUE TITLE
LoadPSIMuonBin: Dirty Sample Logs

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#26646]
### Expected behavior
The number of Label Spectra should be equal to the number of spectra

### Actual behavior
It is not

### Steps to reproduce the behavior
Load a PSI Data from the unit tests deltat_tdc_dolly_1529. 
Check the sample logs, there should be only 4 things called "Label Spectra N" where N is a number between 0 and 15. It should be, 0, 1, 2, 3.
It is not.

### Platforms affected
All

**Comment by Pasarus** [comment]
@AnthonyLim23 Whats the status of this do you know?

**Comment by AnthonyLim23** [comment]
still needs doing
