### ISSUE TITLE
ISIS SANS GUI Diagnostic tab crashes when no data entered

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#26661]
Currently on the diagnostic tab of the ISIS SANS GUI, if no or incorrect data is input an uncaught exception is thrown. As a result of this error the GUI also gets stuck in a disabled state. The code should be updated so that it gracefully handles bad inputs and resets itself upon throwing an error.

**Comment by gemmaguest** [comment]
Closing as stale because this will not impact users so we are unlikely to get time to fix it
