### ISSUE TITLE
Add Placzek correction

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26688]
After #26454 work has been completed the full Placzek correction algorithm needs to be implemented.

Confirm with Marshall the exact steps required for the correction and implement.

**Comment by marshallmcdonnell** [comment]
The code to implement the "basic" Placzek correction with input L1, L2s, ant two theta angles as lists required for the correction are here:

**Comment by marshallmcdonnell** [comment]
The references are buried in the code comments (here)[https://github.com/marshallmcdonnell/mantid_total_scattering/blob/9f762d9e72149bcc87c5d1958aff83aa4c5c2c61/total_scattering/inelastic/placzek.py#L151-L157] for the articles that this implementation is based on.

**Comment by martyngigg** [comment]
Thanks Marshall! This is for us to get started.
