### ISSUE TITLE
Editing position of marker label in workbench

### ISSUE THREAD

**Issue by LolloB** [mantidproject/mantid#26725]
There should be a way to edit the position of the labels of a marker in workbench plots.

**Comment by AnthonyLim23** [comment]
we should also have an option to fix the position of a line (user cannot drag it, but can change it from the settings)

**Comment by PhilColebrooke** [comment]
I'm wondering if a different term should be used instead of marker because "marker" is already used in the figure options to refer to markers for points on a curve.
