### ISSUE TITLE
Prevent groups of groups

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26735]
We should add in a mechanism to prevent the user or developer from creating groups of groups in the ADS. 

This work should be done after #26733

**Comment by AnthonyLim23** [comment]
we should keep this open to prevent problems

**Comment by AnthonyLim23** [comment]
@martyngigg would this make a good induction 2 issue?

**Comment by martyngigg** [comment]
I think this is quite involved for an induction issue as it's not clear on how we want to go about it. If we come up with the mechanism first then I think it would be a good induction issue.
