### ISSUE TITLE
Workbench plotting to normalise by counts

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26749]
Currently workbench either has no normalisation or by bin width. This is to add a by counts option. Care will need to be taken as:

1. For raw counts the normalisation is just the sum of the y values
2. For normalised by bin width the normalisation constant is the integral of the line.

**Comment by NickDraper** [comment]
Would normalise to unity or to one be an easier label to understand

**Comment by AnthonyLim23** [comment]
I think `normalise to counts`. Otherwise normalise to 1 would not be true in the case of unbinned data.

**Comment by NickDraper** [comment]
normalise to total [signal]

**Comment by AnthonyLim23** [comment]
I think this is worth keeping
