### ISSUE TITLE
Crash adding LARMOR transmission runs

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26741]
It has been reported that adding transmission runs for a LARMOR reduction crashes Mantid. We should check with Rob whether this is still a problem and for an example reduction.

**Comment by gemmaguest** [comment]
Removed milestone as we are waiting for scientist input on this

**Comment by smk78** [comment]
Rob D tested this in Workbench on IDAaaS today. He says it seems to be fixed so I am closing the ticket.
