### ISSUE TITLE
Changes to FileResource in Geometry Tests

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#26743]
Important changes required for `FileResource`
   1. Has no implementation file
   1. Cannot switch easily to a debug/preserve file mode.
   1. Naming clash with `ScopedFile` already in TestHelpers - We are confusing the community

**Comment by TakudzwaMakoni** [comment]
Check what has been done here. This will need to be merged first https://github.com/mantidproject/mantid/pull/26734

Specifically NexusGeometrySave provides the append mode in that PR, but it is not properly tested.

Essentially do 1 and 3 for now but wait for 2.
