### ISSUE TITLE
Remove the fit button from the plot toolbar when more than one curve is plotted

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#26768]
Fitting isn't possible when multiple curves are plotted so the fit button should only be shown when the figure has one curve. Make sure that the button is added if all but one curve is removed via the figure options.

**Comment by NickDraper** [comment]
This is when you have a tiled plot, so only allow fitting if there are more than one set of axes

**Comment by AnthonyLim23** [comment]
Assuming its a tiled plot, it should work, we still want to fit to the data. Preferably giving a multi-fit GUI instead. 

At the moment it does single, if you click continue the fit works. However, its is just added to the first axis.
