### ISSUE TITLE
Muon Analysis 2 Crash When Fitting

### ISSUE THREAD

**Issue by ciaranightingale** [mantidproject/mantid#26788]
**Original reporter: James**
### Description of Work
When adding ExpDecayOsc and a third order polynomial to muon data, Mantid crashes.

### To Test
- Open Muon Analysis 2 GUI
- Load Current Run
- In the fitting tab, right click and add function
- Under Muon, add ExpDecayOsc function
- Under Background add Polynomial 
- Under Polynomial change n to 3
- Click Fit
It will crash.

**Comment by AnthonyLim23** [comment]
@ciaranightingale talk to Matthew and add an estimate
