### ISSUE TITLE
Groups given to ReflectometryISISLoadAndProcess input run list cause crash

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#26797]
### Expected behavior
We should ~~not~~ allow groups to be given to the `ReflectometryISISLoadAndProcess` algorithm input run list _without causing mantid to crash_. ~~This could be solved by extracting the child workspaces.~~
### Actual behavior
Workbench crashes if a group is given to the algorithm as an input run, as discovered by @DavidFair while testing #26699.
### Steps to reproduce the behavior
- Open `ISISReflectometry` interface
- Insert run `13460` and angle `0.5`
- Process
- Rename `TOF` group to something else, say `TOF_1`
- Open `ReflectometryISISLoadAndProcess` algorithm
- List `TOF_1` in input runs
- Observe crash

Error message points to `ReflectometryReductionAuto3` line `979`.

**Comment by gemmaguest** [comment]
This appears to be fixed in v6.0.0
