### ISSUE TITLE
Investigation needed

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#26805]
This line looks like a bug to me https://github.com/mantidproject/mantid/blob/master/Framework/NexusGeometry/src/NexusGeometrySave.cpp#L408. Am I mistaken? Shouldn't this be 3. Not sure why we don't get test failures around this?

Could you please investigate or explain?

**Comment by TakudzwaMakoni** [comment]
if my understannding is correct, the dataset contains the magnitude of the vector. the unit vector is stored as an attribute `vector`?

https://github.com/mantidproject/mantid/blob/2ffc539e39bb827978cf81a20fdff9af21f57ecc/Framework/NexusGeometry/src/NexusGeometrySave.cpp#L423

**Comment by TakudzwaMakoni** [comment]
maybe something to do with static casting hsize_t? i have had compiler warnings relating to that before

**Comment by OwenArnold** [comment]
Correct
