### ISSUE TITLE
Algorithm History - Unroll does not expand copy to clipboard

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#26826]
**Original reporter:** ISIS/Rob - Contact @DavidFair 

### Expected behavior
Running an algorithm with children, and unrolling the algorithm history should copy all child algorithms (without the parent) to the clipboard

### Actual behavior
Clicking unroll will expand it in the GUI, but script to clipboard will only copy the parent, not it's children. I'm unsure if this also affects script to file.

### Steps to reproduce the behavior
TODO - The user demonstrated this, but I'm waiting to receive some essential files to replicate this in the SANS GUI.
An alternative algorithm which uses children could be used in the interim.

### Platforms affected
All

**Comment by PhilColebrooke** [comment]
This has been merged now so you can let your person know @DavidFair 😁
