### ISSUE TITLE
Update ISIS Powder Polaris functionality to compute Total Scattering PDF with bank merging

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26834]
In order for Helen to be able to test the Total Scattering functionality we need to be able to run it alongside their standard powder scripts.

Apparently the current `Polaris` class has a [polaris.py](/mantidproject/mantid/blob/master/scripts/Diffraction/isis_powder/polaris.py#L51) already has a `create_total_scattering_pdf` method but the [`merge_banks`](/mantidproject/mantid/blob/master/scripts/Diffraction/isis_powder/polaris_routines/polaris_algs.py#L85) functionality just raises an exception.

There is also a [system test](/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/ISIS_PowderPolarisTest.py#L176) to show how to use the functionality.

As a user I want to be able to call the `create_total_scattering_pdf` method on the Polaris object and have it produce the PDF with `merge_banks=True`.

**Comment by Harrietbrown** [comment]
This was fixed by #26987
