### ISSUE TITLE
Create Minimal Calibration Tab for new ISIS Engineering tab

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26846]
As a user I want a Python-based GUI with a simple Calibration Tab that can perform a new calibration given a vanadium run number or filename and a calibration sample run number or filename. There should be an option to plot the output of the calibration at the end.

Add no other functionality at this point. The design should use MVP and there should be accompanying unit tests written as you go.

Come up with a design for the screen a basic code layout before coding and discuss it.

**Comment by ConorMFinn** [comment]
Do we still want this to generate files in the users file system, or is that something to add later?

**Comment by martyngigg** [comment]
I think we can generate the files as well. They consider that part of the calibration.
