### ISSUE TITLE
Muon analysis 2 load multi period current run

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26843]
If the current run is multi period muon analysis 2 fails, complaining about the number of good frames being zero. We need to set it to 1 within the GUI to allow analysis.

**Comment by AnthonyLim23** [comment]
I have a saved nxs file that can reproduce this error

**Comment by AnthonyLim23** [comment]
we should change the load muon nexus algorithm

**Comment by NickDraper** [comment]
This has been fixed in data acquisition and is no longer needed in mantid.
