### ISSUE TITLE
Bug in parsing NeXus geometry meshes

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#26841]
There is at least one bug around here:
https://github.com/mantidproject/mantid/blob/5fa751ee1434a83c200cfc777f4b253dbaccc0f1/Framework/NexusGeometry/src/NexusGeometryParser.cpp#L461

- Code seems to assume that all faces in the mesh are mapped to a detector ID, this does not have to be the case.
- It looks like it may assume that the number of vertices is the same for all faces in the mesh, this is also not necessarily the case.
- offsets datasets have to exist? This should not be the case when `detector_shape` is defined, detectors 3 and 4 in the example file.

**Comment by OwenArnold** [comment]
@matthew-d-jones do you have particular test files to exercise these problems?

**Comment by matthew-d-jones** [comment]
Example file is on the network drive at `olympic/Babylon5/Public/Matthew Jones/DETGEOM_example_bug.nxs`
