### ISSUE TITLE
Create new Python-based Engineering GUI for ISIS

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26847]
See #15371 for explanation of why we are not continuing with the current one.

We need to create a GUI with the same functionality but along the way improve the UI/UX over the current one has it had a lot of quirks and problems. We will focus on each tab in turn:
* Calibration
* Focus
* Fitting
* Pre-processing
* GSAS-II refinement

**Comment by DannyHindson** [comment]
Closing this and will track via the (small number) of individual remaining issues
