### ISSUE TITLE
ALFView renaming

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#26904]
At present ALFView's code does not always follow the coding standard. This issue is to fix that. However, we will need to first determine if the GUI is useful to any other areas, as this may alter our choice of name.

**Comment by AnthonyLim23** [comment]
need to rename:
ALFView -> ALFInstrumentViewer
ALFView_view -> ALFInstrumentView
ALFView_model ->ALFInstrumentModel
ALFView_presenter ->ALFInstrumentPresenter

need to move the following to https://github.com/mantidproject/mantid/tree/429bd5b007b3639268cd77f3b0535f75cc9a76f0/qt/widgets/common/inc/MantidQtWidgets/Common
BaseInstrumentModel
BaseInstrumentPresenter
BaseInstrumentView
PlotFitAnalysisPaneModel
PlotFitAnalysisPaneView
PlotFitAnalysisPanePresenter

**Comment by AnthonyLim23** [comment]
@DanNixon does this seem like a better set of names/locations for these files?

**Comment by DanNixon** [comment]
I'd keep the full GUI name in the component names, i.e.
ALFView_view -> ALFInstrumentViewerView
ALFView_model ->ALFInstrumentViewerModel
ALFView_presenter ->ALFInstrumentViewerPresenter

**Comment by AnthonyLim23** [comment]
I was trying to avoid things such as ViewerView as it looks confusing

**Comment by DanNixon** [comment]
> I was trying to avoid things such as ViewerView as it looks confusing

Breaking a naming convention is in itself confusing.

**Comment by AnthonyLim23** [comment]
true.
