### ISSUE TITLE
Workbench - Add Option To Change Font Size

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#26915]
MantidPlot has an option to change font and size throughout the application.
This is especially important for users who struggle to read smaller fonts, have specific font requirements (such as dyslexia) or who have issues clicking some of the smaller text buttons.

These options do not exist in workbench.
### Expected behavior
There should be an option in the preferences menu to change the font and text size
### Actual behavior
No such option exists

**Comment by DanielMurphy22** [comment]
This behaviour is now in Workbench!!! 🙌 

You can hold Ctrl + Scroll in and out of the Script Editor and the Messages Box.

As for all other text, I believe editing this got added when @alicerussell1 added Settings to WB. Under FIle>Settings>General>General>Main Font within the Font Widget you can select your font size. It will only kick in when you next restart Mantid. 

I went for size 144, which makes it hilariously difficult to revert...

![Screenshot 2020-04-28 at 11 57 47 (2)](https://user-images.githubusercontent.com/55980573/80480337-5d0cec00-8948-11ea-979d-0e47aa58e2eb.png)

**Comment by DavidFair** [comment]
Thanks, I'll let the SANS team know.

I think 144pt is perfect, provided you want to load, delete, execute (something) and know that Python is idle. We could call it Mantid minimal 😆.

Is there a note next to the font settings that a restart is required to apply these settings?

**Comment by DavidFair** [comment]
Also from your screenshot were not scaling the log messages to the font size too, whilst the editor is scroll zoomable, I double users expect to have to also zoom in their logs too

**Comment by DanielMurphy22** [comment]
> Is there a note next to the font settings that a restart is required to apply these settings?

No but here's an issue recommending this: #28612 

> Also from your screenshot were not scaling the log messages to the font size too, whilst the editor is scroll zoomable, I doubt users expect to have to also zoom in their logs too

I quite like being able to scroll to alter the font size of the log messages. If this were made part of the font size setting then this could prevent someone from altering the messages font size if they don't want to restart WB! But I guess you need to know to hold Ctrl + Scroll

**Comment by alicerussell1** [comment]
> Is there a note next to the font settings that a restart is required to apply these settings?

There is a note in the tooltip for any of the settings that require a restart but I'm not sure people actual read those
