### ISSUE TITLE
Make IPython custom shell compatible with IPython >= 7.1

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#26924]
### Actual behavior:
Any command in the IPython console of MantidPlot results in the following error:
```
TypeError                                 Traceback (most recent call last)
TypeError: our_run_code() got an unexpected keyword argument 'async_'
```
Similarly, any command in the IPython console of the Workbench results in the following error:
```
TypeError                                 Traceback (most recent call last)
TypeError: async_run_code() got an unexpected keyword argument 'async_'
```

### Cause:
[IPython.core.interactiveshell.run_code()](https://ipython.readthedocs.io/en/7.1.0/api/generated/IPython.core.interactiveshell.html?highlight=run_code#IPython.core.interactiveshell.InteractiveShell.run_code) for IPython >= 7.1 is not a function by an `asyncio` coroutine

Other useful links:
- [our_run_code()](https://github.com/mantidproject/mantid/blob/master/MantidPlot/ipython_widget/mantid_ipython_widget.py#L39)
-  [async_run_code()](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/jupyterconsole.py#L74).

**Comment by jmborr** [comment]
@martyngigg Hi Martin,

Turns out that the ipython widget of MantidPlot and the Workbench breaks for IPython >= 7.1 because method `run_code` has become an `asyncio` coroutine.

This commit seems to fix the issue for MantidPlot but not for the Workbench. I'm quite ignorant of `asyncio` so I'd appreciate it if you can give me a hand with this.

**Comment by martyngigg** [comment]
Hi Jose. I've just tested out your fix on my machine with Python 3/IPython 7.8 and it seems to execute correctly in both MantidPlot and Workbench. What error are you seeing in Workbench?

**Comment by jmborr** [comment]
See the below screenshot (please ignore the HDF5 related error). It only happens on entering the first command, it is initializing some object. After that there's no more error messages.

I'm using Python 3/IPython 7.7.0

![Selection_009](https://user-images.githubusercontent.com/1136006/66067893-8da7b700-e51a-11e9-899d-ac9e69935821.png)

**Comment by martyngigg** [comment]
I think this is a warning that can be safely ignored and has been fixed in a later version of `qtconsole`: https://github.com/jupyter/qtconsole/pull/313. I was able to replicate your error inside a virtualenv and once i had done `pip3 install -U qtconsole` the error went away.
Are you able to upgrade `qtconsole`?

**Comment by jmborr** [comment]
> I think this is a warning that can be safely ignored and has been fixed in a later version of `qtconsole`: [jupyter/qtconsole#313](https://github.com/jupyter/qtconsole/pull/313). I was able to replicate your error inside a virtualenv and once i had done `pip3 install -U qtconsole` the error went away.
> Are you able to upgrade `qtconsole`?

Hi Martyn,
Sorry for the very late reply, very busy with other things but yes, the warning has gone away after upgrading `qtconsole`.

**Comment by martyngigg** [comment]
Hi Jose. I think this means that the PR is okay to go?

**Comment by jmborr** [comment]
Yes, but the two Ubuntu build servers continue to fail with what it looks like an unrelated problem:

```
stderr: fatal: unable to access 'https://github.com/mantidproject/mantid.git/': Received HTTP code 503 from proxy after CONNECT
```
It's up to you if you still think it's OK to approve this PR

**Comment by martyngigg** [comment]
Have you fixed the Python 2 issue?

**Comment by jmborr** [comment]
> Have you fixed the Python 2 issue?

oohhh you're right, I forgot! I'll get down to it
