### ISSUE TITLE
User defined peak height on fitting GUI not accounting for normalisation by bin width on Mantid Workbench only

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#26935]
### Expected behavior
When a user adds a peak to fit to a plot with the GUI, the height returned to the function should by the ymax*bin_width (as the units of the y-axis of the plot are counts/bin_width e.g. counts/meV)
 
### Actual behavior
In mantid workbench the normalisation of the counts by the bin width is not accounted for and therefore the initial guess for the height is different from expected.

### Steps to reproduce the behavior
Fit any peak (e.g. gaussian) to data in a workspace, select the fitting tab, right-click to add a peak, choose height, fwhm etc. then plot initial guess.

![UserSuppliedValues](https://user-images.githubusercontent.com/55979119/66049698-ce57fe00-e523-11e9-9119-542a52c49c4b.PNG)
![EvaluatedInitialGuess](https://user-images.githubusercontent.com/55979119/66049697-ce57fe00-e523-11e9-88f0-b749a01130b4.PNG)

### Platforms affected
mantid workbench

**Comment by NickDraper** [comment]
Daniel please check if this is in the current version

**Comment by DanielMurphy22** [comment]
In Mantid WB v4.2 this seems to work correctly!
