### ISSUE TITLE
Seperate the ISIS and Mantid YUM repo

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26943]
For release 4.3 we need to delay the release to ISIS by a couple of weeks after the Mantid release, otherwise all the iDAaaS machines will update during the cycle.

The idea is to create a new YUM repo perhaps called Mantid and move the automatic releases and download page to use that.

Then the ISIS repo will be used whenever we choose to deploy to ISIS, in a similar way that the SNS does.

**Comment by NickDraper** [comment]
@ElliotAOram Does this work with or have an impact on Autoreduction?

**Comment by martyngigg** [comment]
Rather than maintain two separate repos we have requested that auto updates of the main mantid release to be disabled on IDAaS and the cabin machines at ISIS.
