### ISSUE TITLE
Merged Can and Sample workspaces not output with SaveCan option

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#26949]
**Original reporter:** ISIS/Steve

### Expected behavior
The merged sample and can workspaces should be output before subtraction when `SaveCan` is enabled

### Actual behavior
Only the merged workspace after subtraction is output

### Steps to reproduce the behavior
- Use the ISIS Sample Data
- Go to the settings page and enable merged runs
- Tick the save can on the main page and re-run, note that nothing is output

Looking at the code with Matthew it looks like this can easily be added to SansStitch:377

**Comment by gemmaguest** [comment]
Closing as I think this is already fixed. There is an output group called `unsubtracted_can_and_sam` which is produced when `SaveCan` is checked.

@DavidFair Could you check this with Steve?
