### ISSUE TITLE
Investigate reflectometry algorithms for consolidation in IDF

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#26971]
It would be good to understand how [`ConvertUnits`](https://docs.mantidproject.org/nightly/algorithms/ConvertUnits-v1.html), [`ConvertUnitsUsingDetectorTable`](https://docs.mantidproject.org/nightly/algorithms/ConvertUnitsUsingDetectorTable-v1.html), [`MoveInstrumentComponent`](https://docs.mantidproject.org/nightly/algorithms/MoveInstrumentComponent-v1.html), [`UpdateInstrumentFromFile`](https://docs.mantidproject.org/nightly/algorithms/UpdateInstrumentFromFile-v1.html), [`SpecularReflectionCalculateTheta`](https://docs.mantidproject.org/nightly/algorithms/SpecularReflectionCalculateTheta-v2.html) and [`SpecularReflectionPositionCorrect`](https://docs.mantidproject.org/nightly/algorithms/SpecularReflectionPositionCorrect-v2.html) algorithms work in relation to TOF distance as this may be a cause of systematic error on some of the reflectometry instruments.

**Comment by gemmaguest** [comment]
I'm going to close this because we are unlikely to do this investigation unless we have more evidence that there are errors in current algorithms. Perhaps this is something we will look at more in relation to the Q error bars work.
