### ISSUE TITLE
Plot update after running Algorithm to produce workspace with fewer spectra

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#26996]
James Lord using Workbench (4.1). This issue doesn't exist in Mantidplot, there the plot correctly reupdates showing only the spectra now in the altered workspace.

- Running an algorithm which will overwrite a workspace with one with fewer spectra in it, and if that workspace has a plot of all spectra open, gives some interesting error reports. The plot is unchanged and it’s not certain if the workspace was updated properly so I closed the plot and re-ran the algorithm.

| I can roughly reproduce this with SumSpectra(). In the data, there is now only one spectrum and this is plotted 9 times in the already opened plot window. In settings, trying to rename one of the other curves throws up an Unexpected Error report.

**Comment by DannyHindson** [comment]
Call stack showing error from running SumSpectra
![WorkbenchErrorCallStack](https://user-images.githubusercontent.com/56295817/67217304-6a3aa280-f41c-11e9-97cc-801d0310014e.PNG)

Run time error "Could not find spectrum number in any spectrum" is raised in C++ code in MatrixWorkspace.cpp
