### ISSUE TITLE
Workbench Fit slider bug

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#26999]
**Original reporter:** Spencer Howells

There is an annoying/frustrating bug in the Plot>Fit gui.
I expand the window sideways & use the slider to increase the width of the fit/parameter box in order to read the info in that box.
However, when I then click anywhere in the widow the fit box snaps back to its starting/default position.

This is a pity because I have found it much nicer/easier to use than the Mantidplot version.

**Comment by AnthonyLim23** [comment]
retest this bug.
