### ISSUE TITLE
Defined Spectrum Name does not appear in Legend

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27000]
James Lord using Mantid Workbench 4.1

Plotting multiple spectra: in the Legend they are labelled as “spec-1”, “spec-2” etc rather than taking values/names from the spectrum axis as in MantidPlot.

See attachments for Data with the Workbench plot and then the MantidPlot plot.

![Workbench](https://user-images.githubusercontent.com/55980573/66579479-cd9f1780-eb74-11e9-93b9-6bcb14b4e97f.png)
![Plot](https://user-images.githubusercontent.com/55980573/66579487-d0017180-eb74-11e9-8ec0-10450edfc0db.PNG)

**Comment by SpencerHowells** [comment]
@PhilColebrooke the first screenshot also shows another bad bug. The energy value is given to only 1 decimal place! It should be at least 4 if not 5 or 6 as it is in the MantidPlot version.

**Comment by PhilColebrooke** [comment]
@SpencerHowells Thanks, I'll make a separate issue for this now.
