### ISSUE TITLE
Workbench: Issues with show data window for Sqw workspaces

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27013]
**Original reporter:** Spencer Howells

### Expected behavior
* [Energy values] should be at least 4 if not 5 or 6 [decimal places] as it is in the MantidPlot version.
* in a Sqw workspace (for example) the spectra have Q values as a histogram. The value for Q given in the row label is that for the bin lower edge not its centre; there is also no unit. It also looks as if the Y values are bin edge not centre.

### Actual behavior
* ~~Energy values are shown to only one decimal place.~~ Fixed in #27270 
* Values for binned Y axes are shown using lower bin edge and not bin centre and there is not unit.

### Steps to reproduce the behavior
1. In Workbench and MantidPlot, load [11001_deltaE.zip](https://github.com/mantidproject/mantid/files/3723661/11001_deltaE.zip) and show data.
2. See that the top row in MantidPlot shows -10.995meV, -10.985meV, ... and Workbench only shows -11.0meV, -11.0meV, ...

### Platforms affected
All.

**Comment by SpencerHowells** [comment]
@PhilColebrooke This type of file S(q,w) doesn't format properly in Workbench show data..
[iris26176_graphite002_sqw.zip](https://github.com/mantidproject/mantid/files/3723769/iris26176_graphite002_sqw.zip)
The Q values for histograms should be the centre of the bins as in MantidPlot. Workbench gives the lower bin edge value.
