### ISSUE TITLE
Workbench __future__ imports still uses old functionality

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27019]
James Lord has been testing Workbench Mantid 4.1 functionality.

He has tested from __future__ import (print_function, division, unicode_literals) 

and as these 3 do not work correctly, it seems that 'absolute_import' is likely not to work either.

See below for details:

1.	The “from future import print_function” for Python 3 preparations isn’t working as advertised. If I use print (“the answer is”,x) I get a tuple in the messages window such as (‘the answer is’,42.0). It’s as if the future statement is used for syntax checking, rejecting bare print statements, but then turns itself off.

***YES Works in Plot, **not** in Workbench***

2.	To follow up, this works under standard Python 2.x, even using …/MantidInstall/bin/python.exe, but NOT in Workbench (gives a syntax error):
from __future__ import print_function
myprint=print
myprint ( "the answer is", 42 )

***YES Works in Plot, **not** in Workbench***

3.	And it appears the other __ future__ statements are broken too.
“division” doesn’t make 1/3 return 0.33333 (it’s still integer 0 as in plain Python 2.7).

***YES Works in Plot, **not** in Workbench***

4.	unicode_literals is broken too. String literals are not Unicode unless I add the “u” prefix. If I attempt to save a script with a non-ascii character in a string literal, such as £ (with or without a source code encoding indicator as in PEP263) I get an error traceback indicating it was trying to use ascii encoding and the error reporting dialog. And if I put in the encoding indicator and then try to run the (unsaved) script I get a syntax error.

***YES save in Workbench throws up an Error report! Mostly only seems a problem when saving!***

**Comment by AnthonyLim23** [comment]
I mentioned this to @hsautessella the other day, Im not sure if he had a chance to look into it.

**Comment by DavidFair** [comment]
So print correctly rejects kwarg usage (e.g. `print bar`) however the future imports are definitely not working

Here is a reproducer

``` 
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from __future__ import (absolute_import, division, print_function, unicode_literals)


if (1/3) == 0:
    print("Broken")
else:
    print("Fixed if no brackets printed")
```

I also think we need a Python 3 build too. As there is this assumption that by using future imports Mantid (on Python 2) will behave identically to a Python 3 build. Whilst we hope this is true there may be other subtle differences not covered by future imports too.

**Comment by hsautessella** [comment]
I've been away the last couple of days so haven't looked at this yet. I should be able to have a look next week
