### ISSUE TITLE
SANSILLIntegrationTest Failure due to Default Facility Setting

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#27022]
### Expected behavior
The passing of the test should not depend on the Facility from the general settings. 
### Actual behavior
The test fails if the Facility is not set to ILL. 
### Steps to reproduce the behavior
1. Launch workbench/plot
2. Set the facility to ILL.
3. Run `ctest -R SANSILLIntegrationTest`
4. See the test pass.
5. Re-open Mantid and set the facility to any other.
6. Re-run `ctest -R SANSILLIntegrationTest --output-on-failure`
7. See the test fail, unable to find the file for the run number.
### Platforms affected
Observed on Ubuntu 18.04

**Comment by DavidFair** [comment]
Moving to maintenance sprint, as this currently only affects developers locally
