### ISSUE TITLE
Supress figurePatch Matplotlib warnings on every plot

### ISSUE THREAD

**Issue by hsautessella** [mantidproject/mantid#27057]
### Expected behavior
Deprecation warnings should not be printed to the message display every time you plot something.

We should either change the functions we use as advised (if the versions of Matplotlib we use support this), or suppress the warnings, as they are irrelevant to users.

### Actual behavior
When you plot something the following warnings are displayed as errors in the message window:
```
The figurePatch function was deprecated in version 2.1. Use `.Figure.patch` instead.
The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
```
### Steps to reproduce the behavior
Run the following to create a plot
```python
GEM38370_Focussed = Load("GEM38370_Focussed.nxs", OutputWorkspace="GEM38370_Focussed")

fig, ax = plt.subplots(figsize=[10.447, 4.7766], subplot_kw={'projection': 'mantid'})
ax.errorbar(GEM38370_Focussed, specNum=5)
ax.legend().draggable()
plt.show()
```

I believe the warnings come from the patches used in our interactive markers.

### Platforms affected
Tested on Windows. Probably a problem on Ubuntu 18, but not RHEL (RHEL uses an **old** version of Matplotlib)

**Comment by NickDraper** [comment]
Tried and failed to reproduce this on windows, perhaps we have fixed it with the python 3 work?
