### ISSUE TITLE
Fix file clean up in unit tests. 

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#27058]
Recently a node ran out of space because `/tmp` filled up with files/directories from unit/system tests that are not cleaning up after themselves.

**Comment by DannyHindson** [comment]
Have found these problems so far:
1) the system test runner doesn't call tearDown() on the system tests in the same way that the unit test runner does. So some system tests had a tearDown method that was never called. Have changed the runTest method on these tests to call tearDown explicitly as had been done on one or two of the other system tests already
2) the test_project.py unit test created 3 temp directories each containing a .mtdproj file and it wasn't clearing them up
3) the test_projectrecovery.py unit test created 3 empty temp directories and wasn't clearing them up
4) MergeCalFilesTest.py was creating 10-15 temp directories on each run and wasn't clearing them up
