### ISSUE TITLE
Trying to load a run before it exists means it can never be loaded

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#27055]
**Original reporter:** Najet/ISIS

### Expected behavior
If you try to load a run that does not exist yet then it will fail as expected. If you re-try to load it later when it does exist, it should work.

### Actual behavior
Runs are not found the second time around even when they now exist.

### Steps to reproduce the behavior
This needs verifying and will need to be tested at ISIS, but the description of the steps as I understand them are:
- Open the ISIS SANS interface
- Find an upcoming run number where the run hasn't completed yet
- Try to load it and see that it fails
- Wait until the run is complete and check that the file is available on the archive
- Re-try to load it and see that it still fails even though it should be able to find it

### Platforms affected
Windows, possibly all

**Comment by DavidFair** [comment]
This is part of a collection of associated bugs related to how we generate and track states internally, which can manifest manually using the table or using batch files (which worked the last time Mantid opened).

I'm sure this is a duplicate, but cannot find it so I'll use this as the primary issue, and link older issues back into this.
