### ISSUE TITLE
Instrument View crash over remote desktop connection

### ISSUE THREAD

**Issue by matthew-d-jones** [mantidproject/mantid#27064]
**Original reporter:** Freddie Akeroyd/ISIS

### Expected behavior
Be able to stream event data using `KafkaEventListener` for the "electronics" instrument and display it in the Instrument View over a remote desktop connection to Windows.

### Actual behavior
MantidPlot crashes when try to open Instrument View.
Reports "load library error 126" on crash.
Apparently works correctly when not over remote desktop.

### Steps to reproduce the behavior
- Add this to ISIS facility part of Facilities.xml:
```
<instrument name="electronics">
  <livedata>
    <connection name="kafka_event" address="livedata.isis.cclrc.ac.uk:9092" listener="KafkaEventListener" />
  </livedata>
</instrument>
```
- Use KafkaEventListener (must be on ISIS network) to consume data from "electronics" instrument.
- Try to open the Instrument View.

Note, "electronics" is a test setup of new electronics on MARI. The instrument name in the data stream should be reported as MARI and thus the MARI instrument should be loaded by "KafkaEventListener" for geometry information. Perhaps this is not working as intended?

### Platforms affected
Windows 10, Mantid version 4.1

**Comment by DanielMurphy22** [comment]
Seems like the same issue so referencing: #27159
