### ISSUE TITLE
Clicking cancel in the save script dialog closes MantidPlot

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27078]
### Expected behavior
MantidPlot doesn't close.

### Actual behavior
MantidPlot closes.

### Steps to reproduce the behavior
1. In MantidPlot, open the script window and type something.
2. Click the X in the top right corner of the main window.
3. When the dialog appears asking if you want to save the script, click Cancel.

### Platforms affected
All.

**Comment by PhilColebrooke** [comment]
Also if you click Save As... and then click Cancel in the window for selecting a file name, MantidPlot closes.

**Comment by martyngigg** [comment]
Closing as wontfix as this relates to MantidPlot
