### ISSUE TITLE
Warn if instrument defined in Facilties.xml does not contain a technique tag

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27085]
Found by myself and Martyn Gigg

When defining a new instrument in the Facilities.xml file (Under AppData/Roaming/mantidproject/mantid/instrument/, search %APPDATA%)
the instrument definition would not appear in the Mantid GUI unless the technique tag was inserted.

Worth deciding if we actually need to require the technique tag:
1) If not, then making it possible for an instrument to be defined without one and for it to appear in Mantid.
OR
2) If so, then providing an warning which explains why the newly defined instrument hasn't been loaded, and telling users to include a technique tag.

Some code used:
```

  <instrument name="electronics">
    <technique>Test Listener</technique>#it won't load the instrument with this line removed
    <livedata>
      <connection name="kafka_event" address="livedata.isis.cclrc.ac.uk:9092" listener="KafkaEventListener" />
    </livedata>
  </instrument>

```

**Comment by SpencerHowells** [comment]
@martyngigg We use the technique tag regularly to find indirect or direct instruments when starting a GUI for example.

**Comment by martyngigg** [comment]
@SpencerHowells Thanks for the information. Daniel and I just spent ~20 minutes trying to figure out why a new instrument in the `Facilities.xml` wouldn't load. The safest thing is probably to warn that the instrument description was not loaded with a reason to avoid this confusion for the future.
