### ISSUE TITLE
Prepare release notes for 4.2. Last support for Python 2!

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#27100]
All of the release notes need reviewing and tidying up in preparation for v4.2 including adding any additional screenshots we require. We also need to add a main release image for the index page.

This is the main issue for making minor tweaks. Any significant work can be separate issues and linked to this EPIC.

**Comment by gemmaguest** [comment]
I've spotted some things that could do with improving in the reflectometry release notes following #27301 so I'll do a PR to fix them.
