### ISSUE TITLE
Multiple instances of workbench interfaces should not be allowed

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#27112]
### Expected behavior
The reflectometry GUI should ideally be allowed to only open once, see #26981.

It has been agreed that this behaviour was standard for the cpp interfaces in MantidPlot and should be implemented into workbench for all interfaces.

### Actual behavior
Multiple instances are currently allowed

### Steps to reproduce the behavior
- Open reflectometry interface
- Open another

### Platforms affected
All

**Comment by NickDraper** [comment]
Reopened as comment in #27322 suggest that this is no longer working in the release branch

**Comment by Harrietbrown** [comment]
Closed by #27357
