### ISSUE TITLE
IN16B reduction improvements

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#27148]
- [x] Fix the Indirect reduction GUI crashing systematically both for QENS and FWS
- [x] When normalised to the monitor, the output must be a distribution
- [x] Allow for user defined integration ranges in IFWS
- [x] Remove the sample log merge warnings before the first cycle with BATS, i.e. 01.01.2018.
- [x] Amend CalculateMonteCarloAbsorption to allow for fixed window scans
- [x] Fix CalculateMonteCarloAbsorption for the inner and outer container parts
- [x] The first set of analysers of IN16B are not focused in the sample position, but in the midpoint between the sample and the detector center. Current IDF does not take this into account, resulting higher than expected Q values for the first PSD tube. This needs to be fixed only for detector at 25.1 degree and only for doppler mode.
- [x] Add the second order correction to energy channel -> deltaE conversion in Doppler mode. (see email from MA)
- [ ] Think of removing the automatic suffixes from the algorithms, but maybe leave in the GUI?
- [ ] Implement the EPP fitting also for SDs in BATS mode.
- [ ] Discuss periodictable in the TSC

**Comment by NickDraper** [comment]
@gvardany Can you update this now that the PR is merged, and if the rest of the work will not be in this release please change the milestone.
