### ISSUE TITLE
Indirect reduction > remove automatic suffixes

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#27149]
Indirect ILL reduction automatically appends suffixes to the workspace name after what is requested by the caller. This was originally implemented to accomodate better the requirements of the indirect interfaces. But running from scripts this does not make much sense, moreover, creates more confusion.
There should be a possibility to switch this behaviour off, without breaking the backwards compatibility.

**Comment by SpencerHowells** [comment]
@gvardany the interfaces have a tool for switching the option on/off so anything new should be compatible with that

**Comment by gvardany** [comment]
Yes, exactly. That's why we can now offer an option not to append anything in the algorithms either.
