### ISSUE TITLE
MantidPlot: in the find and replace dialog in the script editor, entering the same word in the Find field but with a different case reverts back to the previous case

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27156]
### Steps to reproduce the behavior
1. In MantidPlot, press F3 to show the script editor and press Ctrl+F to open the find and replace dialog.
2. In the Find field input "find test" and in the Replace field input "replace test" and click Replace All.
3. Now in the Find field input "FIND TEST" and in the Replace field input "REPLACE TEST" and see that when each field loses focus, they change to lowercase.

This means that a user is unable to do a find and replace on a particular word and then do another find and replace on the word with different capitalisation.

### Platforms affected
Found on Windows, presumably all. MantidPlot only.

**Comment by martyngigg** [comment]
Closing as wontfix as it's an improvement to MantidPlot not reported by users.
