### ISSUE TITLE
ISIS Indirect Help Appears Behind Settings

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#27163]
### Expected behavior
Clicking the help button in the Indirect settings menu should allow the help to be browsed freely. 
### Actual behavior
The Settings menu for the Indirect GUI is modal, so even if the help button is pressed, the help cannot be used until the settings menu is closed. 
### Steps to reproduce the behavior
1. Open any of the Indirect interfaces in plot or workbench.
2. Click the settings button in the bottom left.
3. Click the help button in the bottom left of the newly opened menu.
4. Attempt to interact with the help window. 
### Platforms affected
Observed on Ubuntu 18.04

**Comment by DannyHindson** [comment]
The settings window is set to ApplicationModal meaning that all other windows in the application including the help window are disabled while the settings window is open. I think this should be set to WindowModal instead (similar to how the main settings window works in Workbench - where the help link works).

For WindowModal to work there needs to be a parent set up on the Settings screen (QWidget). Will see if I can get this working
