### ISSUE TITLE
Group Workspaces Button in Workbench Not Working

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27175]
### Expected behavior
The Group / Ungroup Workspaces buttons should work correctly

### Actual behavior
Hitting group or ungroup does nothing

### Steps to reproduce the behavior
- Create two sample workspaces
- Select both
- Hit group above
- Nothing happens
- Manually group by running GroupWorkspaces alg
- Hit ungroup button
- Nothing happens

### Platforms affected
All? (Tested on Ubuntu)

**Comment by ConorMFinn** [comment]
I couldn't re-create this on the most recent nightly. (Ubuntu 18.04)

**Comment by alicerussell1** [comment]
I can't re-create it on windows 10 either

**Comment by DavidFair** [comment]
I seem to be the only one with this issue after getting Matthew to test it too, so I'm closing
