### ISSUE TITLE
Workbench and Mantidplot remembers the values of variables after executing a script

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27185]
**Original Reporter:** James Lord

### Expected behavior ###
When I run a script it should start with a “clean” interpreter. Variables from the last run should not reappear unless they are set, and I should get a “name ‘x’ is not defined” error if I use a value before setting it, for example if I delete or comment out the line where it used to be set.

### Actual behavior ###
Variables defined in the script are recycled, causing different behaviour if the script is re-run after editing, compared to loading it later into a fresh tab and running.
Also modules loaded in an earlier run of the script persist if I comment out the “include” line. reload(module) doesn’t work very well if I’ve just edited the module in another tab, the traceback text-of-offending-line refers to the new version while my script actually called an earlier one.

### Steps to reproduce the behavior ###
Enter and run the following:

```
x=1
print (x)
```
and then comment out or delete the line “x=1” and run again.

What's intriguing is that MantidPlot does not show this behaviour despite having a 'Clear Variables' option which would suggest otherwise.

### Platforms affected ###
Mantid Workbench 4.1 on Windows, possibly others.

**Comment by NickDraper** [comment]
@martyngigg, @DanielMurphy22  What do you think about this one?

This is not how Mantidplot worked and would be s change that would trip as many people up as the current behavior.

It would make the ability to run just the selected lines very different indeed.

Personally I'm not sure we should make this change.

**Comment by DanielMurphy22** [comment]
> Personally I'm not sure we should make this change.
I think I agree. Running small lines of code within a script is presumably what users do very often when creating a script. There's draw-backs to both ways, but I agree being able to run a small section of code is more valuable than having it clean everytime.

Unless there was an easy way to tell the difference between running a whole script or a small part, could just clean before running the whole script? But this may be too hands-on.

**Comment by NickDraper** [comment]
I'm happy that we clean before running the whole script, that makes sense.

**Comment by martyngigg** [comment]
For executing the whole script I agree we should clean the environment first. For executing a selection we can't as it needs to remember variables in that case.
