### ISSUE TITLE
No script output when Workbench is first opened

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27184]
### Expected behavior
Running a script produces output in the log.

### Actual behavior
Output will only start to appear when a new script tab is opened.

### Steps to reproduce the behavior
1. Open Workbench, and write ```print(100)``` in the script editor.
2. Press Ctrl+Enter to run and there is no output.
3. Right click the messages tab and go to View->All Script Output and now the output appears.
4. Right click the messages tab and go to View->Active Tab Output and the output disappears.

It would seem that Workbench is unaware that the initial tab is the active tab when Workbench is first opened, as script output works as intended once a new tab is opened.

### Platforms affected
Found on Windows, presumably all. Workbench only.

**Comment by DavidFair** [comment]
I think this is still an issue, locally in a branch which contains 7324db3 this still does not work

- Ensure that the log view is set to active tab
- Close/Open Workbench
- In the first tab enter `print("a")`
- Run it and note that nothing is printed

**Comment by PhilColebrooke** [comment]
I am unable to reproduce this problem on any OS :(

**Comment by PhilColebrooke** [comment]
Your computer be wack, David
