### ISSUE TITLE
Direct Inelastic reduction bug

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#27207]
### Expected behavior

Old reduction python script runs in nightly

### Actual behavior

Script fails with errors:

1. `TypeError` due to string variables being unicode by default now rather than plain strings
2. `UnboundLocalError` due to a bug in the reduction scripts (possibly introduced by #27011 ).

### Steps to reproduce the behavior

Download the script in this zip:

[let.zip](https://github.com/mantidproject/mantid/files/3794057/let.zip)

and run it in IDAaaS. This will give the `UnboundedLocalError`. If one of the `str('xxx')` lines (e.g. line 67) is changed to remove the string conversion, the script will fail with the `TypeError`.

### Platforms affected

Tested in Workbench on IDAaaS (RHEL7). MantidPlot does not suffer the `TypeError` issue but still sees the `UnbounedLocalError`.

**Comment by martyngigg** [comment]
Closing as auto-close doesn't work for merging to non-default branch.
