### ISSUE TITLE
IndirectDataAnalysis IqtFit StretchExp calculates start values from the data. Exp(1) should also do it.

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#27200]
In the Iqt fit tab there are two possible fitting functions which can be added. An exponential and a stretched exponential. Of these the stretched exponential is automatically populated with reasonable values whereas the exponential is not. This should be updated so they are both populated with reasonable values.

**Comment by RichardWaiteSTFC** [comment]
I can't work on this today, but the relevant file is
mantid\qt\scientific_interfaces\Indirect\IndirectFunctionBrowser\IqtFunctionModel.cpp
The function setStretchExponential calls an additional function estimateStretchExpParameters when the box is checked. The relevant exponential function setNumberOfExponentials (which doesn't take a boolean input but the number of exp functions) needs to do a similar thing. For a single exp it is easy to estimate the parameters (see estimateStretchExpParameters).
