### ISSUE TITLE
Restrict ISIS Reflectometry batch save/load to .json

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#27224]
### Expected behavior
We should filter the file types available to be loaded into the reflectometry GUI so that it is consistent with what is saved out

### Actual behavior
It is possible for users to choose from any file type when loading

### Steps to reproduce the behavior
- Open ISIS Reflectometry
- Batch -> Load
- Observe "All Files" in the dialog
- Attempt to load anything that is not plain text
- Observe handled exception

### Platforms affected
All

**Comment by gemmaguest** [comment]
Fixed by #27233
