### ISSUE TITLE
Muon AlC interface crashes

### ISSUE THREAD

**Issue by alicerussell1** [mantidproject/mantid#27221]
### Expected behavior
If you enter the first set of data, tick `Auto` and press `Load` it should load the data

### Actual behavior
Hard crash

### Steps to reproduce the behavior
Set the default instrument to EMU, and turn on the data archive
`Interfaces`->`Muon`->`ALC`
Enter some valid data for the first run and tick the `Auto` box
Press `Load`
It crashes

### Platforms affected
Tested on windows but probably all

**Comment by alicerussell1** [comment]
I had another look at this since you couldn't reproduce it, it seems that it only crashes when I have `//emu/data/` in manage user directories. It also causes a crash in the previous release.

**Comment by StephenSmith25** [comment]
I tried the same on Ubuntu 18.04, and added the //emu/data folder to the user directories. It also causes Mantid to crash, so this appears to be the issue. I'll look into it.
