### ISSUE TITLE
Fit Function Window gets Stuck Popped Out in "I(Q, t) Fit" tab on Workbench

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#27247]
### Expected behavior
The widget cannot be popped out on workbench. 
### Actual behavior
Once the widget has been popped out of the main interface, it cannot be moved and clicking the button again (which would return the widget to the main GUI in plot) does nothing.
### Steps to reproduce the behavior
1. Open Workbench
1. `Interfaces` -> `Indirect`-> `Data Analysis`
3. `I(Q, t) Fit` tab
4. Click the separate window button in the top right corner of the fit function widget.
### Platforms affected
Button only appears on

**Comment by SpencerHowells** [comment]
@ConorMFinn If I remember correctly this is a general problem on the Workbench with docking. The miniPlot widget appears to have it disabled ie no icon. I think we decided to temporarily disable it on all tab - see eg ConvFit tab.

**Comment by SpencerHowells** [comment]
@ConorMFinn Using Ubuntu the undocked widget does not move around. This is a bug in Qt.

**Comment by Mantid-Matthew** [comment]
This was in fact a generic issue with all the tabs when the IndirectDataAnalysis GUI was ported to workbench. The decision was made to remove the ability to pop out the sub widgets for now which is what should be done here.

**Comment by gemmaguest** [comment]
Fixed by #27296
