### ISSUE TITLE
Add Alias and metadata to GeneratePythonScrpit

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27275]
Three small changes to the same algorithm

1. Add an Alias for the Algorithm as ExportHistory
1. Add a commented header to the start of the output specifying that it is from Mantid and the version of Mantid
1. Add in the required includes to allow the script to be used in workbench or outside of Mantid.

**Comment by DanielMurphy22** [comment]
Looks like this may fix #25782
