### ISSUE TITLE
Indirect DataAnalysis Jump fit given wrong name

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#27282]
In the IndirectDataAnalysis interface if you do a fit on the Jump fit tab the resultant fit workspace has same name as the input convolution fit workspace. The result workspace from the fit however is correctly named with the jump fit information. The *_workspace group and output from this fit should be renamed to match the *_Result group from this fit.

**Comment by SpencerHowells** [comment]
As the tab is now called FqFit the ws name should have Fq instead of jump.
