### ISSUE TITLE
IndirectDataAnalysis IqtFit fitting multiple datasets naming issue

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#27284]
In the IndirectDataAnalysis Iqt fit tab there is the option to load spectra from multiple workspaces to fit. The resultant fitted workspaces in the *_Workspaces group are then given names like Multiqtfit* whereas they should have the workspace they came from specified. For comparison the workspaces in *_Results have names like MultiqtFit_1E_iris26176_graphite002_iqt_s0_Result which is correct

**Comment by Harrietbrown** [comment]
Closed by #27328

**Comment by Mantid-Matthew** [comment]
Re-opening as same issue regressed and need to link to new pull request.
