### ISSUE TITLE
Copying and Pasting Cells in SANS GUI resets selection to top left

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27299]
### Expected behavior
On copy and paste the selected row should be the pasted row

### Actual behavior
The row selection moves to the top left instead

### Steps to reproduce the behavior
Copy a row, then paste. Notice how the selection moves to the top left

**Comment by DavidFair** [comment]
This is an issue in 4.1 and hasn't regressed since 4.2, so I'm pushing it out of this release

**Comment by smk78** [comment]
Leide checked this issue in Workbench 5.0.0 and said it was resolved.
