### ISSUE TITLE
Further release notes improvements

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27307]
- [x] Need more text and images for AlfView (including either a link to it's docs, or a short step by step of how to use it.
- [x] check scaling of images, consider aligning some to the left
- [x] Diffraction - see photos?
- [x] summarizing paragraph on main
- [x] indirect check formating of *``**The Indirect Data Analysis GUI has been added to the Workbench**``*
- [x] workbench check formatting of *``The Script Repository - Download from 'File > Script' Repository to a folder of your choice!``*
- [x] workbench check formatting of *"View" option, allowing you to filter Messages output by script - Right-click in the Messages Display and hover over "View" to see the options. *
- [x] workbench check  'See associated image' at end
- [x] Muon "See associated Image " at end
- [x] Refl check formatting of * Live data monitoring update intervals can now be user-specified. *
- [x] refl "See associated Image " at end
- [x] sans check formatting of * The "visual noise" of the General and Q, Wavelength settings tabs has been reduced. *
- [x] sans check formatting of the removed list, but we should also mention why they have been removed.
- [x] sans "See associated Image " at end

**Comment by gemmaguest** [comment]
Reflectometry fixes on #27311
