### ISSUE TITLE
Notifications for Algorithm Error

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27305]
James Lord via the Mantid Forum: https://forum.mantidproject.org/t/error-dialog-boxes/588

Currently if an Algorithm fails (but the inputs passed their individual validators) there is an error message in red in the Messages Window. While developers see this, Users may have this hidden or covered by plots and so the Algorithm failure is unnoticed.

Proposed ideas around this include:
- A pop-up to notify and explain the error (potentially tedious).
- A notification system to do the same as above.
- Something red appearing in the Algorithms Window (the progress bar could go red or the entire Window!) This approach assumes a user can at all times see the Algorithm Window. 

-Worth discussing would this replace or complement the error in the Messages Window
-Would any of this apply to similar errors from scripts?

**Comment by NickDraper** [comment]
It looks like Qt has us covered for cross-platform notifications.

https://doc.qt.io/qt-5/qsystemtrayicon.html#icon-prop

This works [tested on windows, just popping this code in main.cpp in mantidplot]
```C++
    #include <QSystemTrayIcon>

    QSystemTrayIcon sysTrayIcon(&app);
    sysTrayIcon.show();
    sysTrayIcon.showMessage("Mantid",
                            "Mantid is waking up, give it a second ...",
                            QSystemTrayIcon::Warning);
    sysTrayIcon.showMessage("Mantid",
                            "This is a critical message",
                            QSystemTrayIcon::Critical);
```

It needs checking as to how it acts on other OS's, and we should consider where and when we should use it.
This should be done early in a dev cycle as we may uncover many situations where these are popping up when we don't want them to.

Imagine the situation where we are fitting 1000 spectra and 500 of them fail for some reason  (does Fit error when it does not converge?).
