### ISSUE TITLE
Consistency of Iqt Fit output workspace naming

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#27324]
### Expected behavior
I(Q,t) fit returns  two groups of workspaces: one to hold the results (one workspace per run) and another to hold the spectrum data, fit and difference (one for each spectra). Ideally there would be consistent naming convention of workspaces when they are fitted with sequentially and simultaneously and it would be clear which workspaces belonged to which spectra/run.

### Actual behavior
The output workspace names are very different for sequential and simultaneous fitting. The output workspaces from sequential fitting of spectra from one run (left) and two runs (right) are below
 
![image](https://user-images.githubusercontent.com/55979119/68481275-aea4ab80-022e-11ea-8577-1986cd2c11bf.png)

The workspaces corresponding to each spectra are labelled with a spectrum number but no run number, and the result workspace names are subtly different (aside from the MultiIqtFit prefix) there is an additional "Fit_seq" in the single run case.

The output workspaces from simultaneous fitting of spectra from one run (left) and two runs (right) are below
 
![image](https://user-images.githubusercontent.com/55979119/68481508-4c987600-022f-11ea-9a88-00f2dc4347f0.png)

for the case of fitting spectra from multiple runs the workspaces are now labelled sequentially not by spectrum number.

### Steps to reproduce the behavior

(1) Run the following to load data

from mantid.simpleapi import *
Load(Filename='irs26174_graphite002_red.nxs', OutputWorkspace='irs26174_graphite002_red')
Load(Filename='irs26173_graphite002_res.nxs', OutputWorkspace='irs26173_graphite002_res')
TransformToIqt(SampleWorkspace='irs26174_graphite002_red', ResolutionWorkspace='irs26173_graphite002_res',
ParameterWorkspace='irs26174_graphite002_TransformToIqtParameters', OutputWorkspace='irs26174_graphite002_iqt')
Load(Filename='irs26176_graphite002_red.nxs', OutputWorkspace='irs26176_graphite002_red')
Load(Filename='irs26173_graphite002_res.nxs', OutputWorkspace='irs26173_graphite002_res')
TransformToIqt(SampleWorkspace='irs26176_graphite002_red', ResolutionWorkspace='irs26173_graphite002_res',
ParameterWorkspace='irs26176_graphite002_TransformToIqtParameters', OutputWorkspace='irs26176_graphite002_iqt')

(2) Open the Indirect data analysis interface > I(Q,t) Fit tab
(3) Load some spectra from the available workspaces and attempt to fit (e.g an exponeontial).

This is related to issue #27284 (which is currently being fixed temporarily by renaming the workspaces from the results workspaces in IndirectFitOutput.cpp. However a more general fix is required to sensibly name the output workpaces at the point the fit is done to address inconsistencies between simultaneous and sequential fitting.

**Comment by RichardWaiteSTFC** [comment]
The naming seems to be done inside QENSFitSequential.cpp

**Comment by AnthonyLim23** [comment]
@RichardWaiteSTFC does your fix mean we can close this issue?

**Comment by RichardWaiteSTFC** [comment]
The fix does now name workspaces sensibly after they have been created, but I opened this issue in case at a later point we might want to change how the workspaces are named initially (i.e. when they are created I think in the two .cpp files i mention above).

**Comment by SpencerHowells** [comment]
@RichardWaiteSTFC @AnthonyLim23 we need to have a thorough look at the naming
