### ISSUE TITLE
TOF correction for diffraction event data

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#2733]
This issue was originally [TRAC 1886](http://trac.mantidproject.org/mantid/ticket/1886)

New algorithm for Mantid that corrects the event data for moderation time delay incurred by neutrons as a function of wavelength. Implement same corrections that are in Jason Hodges's Fortran code.  Then focussing should become a simple linear relationship for all pixels.

**Comment by NickDraper** [comment]
Is this really needed?, the tickect has existed for 6 years without development even starting, I propose we close this ticket as a wontfix.
