### ISSUE TITLE
Disallow Save Ascii for TableWorkspaces

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27363]
**Original reporter:** [ISIS]/[James Lord]

### Expected behavior

A TableWorkspace should be able to be saved as an ASCII file

### Actual behavior
It cannot

### Steps to reproduce the behavior
Load a Table Workspace, select that Workspace and from the drop-down Save menu in the Workspaces Window, select ASCII.

In v4.1 an error window for an unexpected exception is thrown:
![4_1](https://user-images.githubusercontent.com/55980573/68753024-32c6ac80-05fc-11ea-8ac6-6e407bee9f7f.PNG)
In the most recent nightly 08-11-2019, an error reporter appears or it has been seen to hang and hard crash.

Currently it only accepts a MatrixWorkspace for exporting to ASCII, not a TableWorkspace.

### Platforms affected
v4.1 and Nightly
Plot and Workbench

**Comment by NickDraper** [comment]
Note this is only from the save button in the workspaces toolbox!
