### ISSUE TITLE
Create Multithreaded Macro to Set OpenMP Max Threads to the Value From the Config

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#27375]
Due to some issues with how secondary threads on Linux don't seem to carry over their OpenMP configuration from the main thread, there should be a macro in the `MultiThreaded.h` file that allows you to set the properties of the current thread to what is in the config. 

It would also make sense to investigate why this happens at all, and if it can be stopped, before implementing the Macro.

Currently, the setting is done by the Framework Manager.

(this will also fix https://jira.esss.lu.se/browse/DAM-1349)

**Comment by DanNixon** [comment]
Ideally, more investigation as to why this is a problem in the first place should be done before this is implemented.

**Comment by DanNixon** [comment]
As per the OpenMP spec, *nthreads-var* (the ICV that is set by `omp_set_num_threads()` and friends) is scoped to the data environment, which looks to be scoped to thread (i.e. non-OMP thread, it would be inherited in that case).

As a result, calls to `omp_set_num_threads()` only affect the current and subsequent data environments within the current thread.
The `MaxCores` entry in the properties file likely never worked and that is validated by my own findings and reports from users.

The "best" solution would be to call `omp_set_num_threads()` on each createion of a new data environment that we control via the macros in `MultiThreaded.h` (i.e. on each new `parallel` region).

**Comment by DanNixon** [comment]
Looking more finds this minimal example of why what we do doesn't work: https://stackoverflow.com/questions/56361293/overriding-omp-num-threads-from-code-for-real

**Comment by ConorMFinn** [comment]
> The "best" solution would be to call `omp_set_num_threads()` on each createion of a new data environment that we control via the macros in `MultiThreaded.h` (i.e. on each new `parallel` region).

I just want to be clear on this. As part of the macros that create an environment (such as `PARALLEL_FOR_IF`) there should be a call(?) to the macro that sets the number of threads to the value in the config?

**Comment by DanNixon** [comment]
> > The "best" solution would be to call `omp_set_num_threads()` on each createion of a new data environment that we control via the macros in `MultiThreaded.h` (i.e. on each new `parallel` region).
> 
> I just want to be clear on this. As part of the macros that create an environment (such as `PARALLEL_FOR_IF`) there should be a call(?) to the macro that sets the number of threads to the value in the config?

Yes, although not ideal this is what we'll have to do to make the macros behave as they are supposed to.

If there is a case where the old behavior is actually desired then the `PRAGMA_OMP` macro may be used.
