### ISSUE TITLE
plt.show() not showing matplotlib figures in workbench

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#27374]
### Expected behavior
The following script would show a figure window in workbench

    ws=Load(Filename="GEM40979.raw", SpectrumMin=431, SpectrumMax=750)
    ws=SmoothData(InputWorkspace=ws, NPoints=20)
    plt.plot(0.5*(ws.readX(0)[:-1]+ws.readX(0)[1:]), ws.readY(0), '-og')
    plt.show()

### Actual behavior
A figure is generated but it isn't shown. You either have to select show on the plot menu (as shown in screenshot) 
![image](https://user-images.githubusercontent.com/55979119/68777470-9ca97b00-0629-11ea-929f-6c66a94e7c32.png)

or use
    plt.gcf().show()

### Steps to reproduce the behavior
(1) Run the script above
(2) See if figure is visible

### Platforms affected
Workbench 4.1 and nightly as of 08-Nov-19

**Comment by DanielMurphy22** [comment]
May be an IDaaS Issue!

**Comment by DanielMurphy22** [comment]
Yes its still an issue on IDaaS, not an issue on Windows

**Comment by NickDraper** [comment]
Also an issue in Direct CentOS machines according to Pascal

**Comment by NickDraper** [comment]
This does happen on windows as well
