### ISSUE TITLE
Edit Axis Colorbar Min to 0 

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27380]
### Actual behavior
Editing colourbar minimum value to 0 or negative value produces error reporter
### Steps to reproduce the behavior
Double-click on the tick mark labels on a colorfill colorbar, to open "Edit Axis". Change Min to 0 or a negative number and an error reporter and lots of error messages appear. Worth making this impossible or at least not causing a soft crash like this!
### Platforms affected
Workbench all versions, including latest Nightly

**Comment by PhilColebrooke** [comment]
This is only the case when the scale has been set to logarithmic, a negative/zero min value causes no issue if the scale is linear.

Another issue I've just found with the colorbar is that it isn't possible to set the min/max value to negative in the images tab of the figure options, when this should be allowed if the scale is linear.

Essentially when changing the min/max axis values there needs to be a check for whether the scale has been set to linear or logarithmic, and disallow negative inputs only in the latter case.
