### ISSUE TITLE
Add ability to manually specify phasetable and phaseqad names

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#27409]
Currently in Muon Analysis phasequad and phasetable names are automatically generated but would be nice to have the option to changes these names.

**Comment by AnthonyLim23** [comment]
We should allow the user to specify the name (like a pair)

**Comment by AnthonyLim23** [comment]
This might be done as part of #29611

**Comment by Matt-Cumber** [comment]
Phasetable names has been added with #30966
