### ISSUE TITLE
Add deadtime and other correction in before calculating phasequad in Muon Analysis

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#27408]
Currently the phase quad workspace is calculated from the raw workspaces without any of the corrections which are normally done. This should be updated to so that this workflow includes the deadtime correction and all other corrections done in the standard muon analysis workflow.

**Comment by Mantid-Matthew** [comment]
This should also be done for phasetables if it is not done so already

**Comment by AnthonyLim23** [comment]
This also includes cropping the result from first good to last good

**Comment by Matt-Cumber** [comment]
This may have been completed or partly completed @AnthonyLim23

**Comment by AnthonyLim23** [comment]
I dont think it is done
