### ISSUE TITLE
Close Interface Hard crash!

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27420]
Hard crash when closing Interface
### Steps to reproduce the behavior
The most reproducible version of this crash I've found is open workbench, open the ALFview interface, maybe change between cylindrical and spherical and leave the interface open for ~30 seconds. Close the interface and Mantid hard crashes, with no error reporter, but a Mac Error report
### Platforms affected
Mac Workbench, 18th 4.2 release candidate

**Comment by martyngigg** [comment]
I *think* this is a bug in Qt on macOS. I found a similar stack trace reported in [QTBUG-70064](https://bugreports.qt.io/browse/QTBUG-70064) from qtquickcontrols. Upgrading to 5.13.1 on macOS seems to stop the crash when closing the instrument view after switching between render modes.
