### ISSUE TITLE
MSlice can't open if a custom algorithm has been defined

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#27439]
### Expected behavior
If a user has defined their own algorithm MSlice should be able to be opened.
### Actual behavior
If a custom algorithm has been defined in mantid, MSlice will produce an unexpected error when oppening it stemming from a KeyError in searching for the custom algorithm.
### Steps to reproduce the behavior
1. open mantid (either plot or workbench)
1. run this script:
```
from mantid.kernel import *
from mantid.api import *

class PrintNumber(PythonAlgorithm):
	def PyInit(self):
		self.declareProperty('Nsteps',1000)
		
	def PyExec(self):
		Nsteps = self.getProperty("Nsteps").value
		print(Nsteps)

AlgorithmFactory.subscribe(PrintNumber)
```
3. open MSlice
### Platforms affected
Found in Windows, Presumably all.

**Comment by mducle** [comment]
Fixed in MSlice.
