### ISSUE TITLE
Shortcut equivalence for Workbench, eg Ctrl+W

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27449]
**Original reporter:** [MANTID]/[@PhilColebrooke ]

### Expected behavior
Shortcuts in MantidPlot should work in Workbench
### Actual behavior
Some such as Ctrl+W to close a script editor tab do not (yet Ctrl+N to open one does...)
### Steps to reproduce the behavior
Open Plot and Workbench and look at which shortcuts (Usually highlighted in the drop-down menu) work in Plot and not Workbench
![Screenshot (17)](https://user-images.githubusercontent.com/55980573/69250191-21a31000-0ba7-11ea-9c08-ca4496a291ce.png)

### Platforms affected
Workbench all

refs #24115 

See comment below

**Comment by mducle** [comment]
Also in the editor, the shortcuts are different - e.g. `Ctrl+/` in Workbench vs `Ctrl+M` in MantidPlot to comment lines - they should also be made consistent.

**Comment by DanielMurphy22** [comment]
Here is a short list of some MantidPlot shortcuts. Ctrl+Shift+L (to clear all memory in Mantid) has been highlighted to me recently as a rather useful one.
