### ISSUE TITLE
Implement Plot advanced ... into workbench

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27450]
This is implementing the Plot Advanced functionality into workbench as the equivalent to that in Mantidplot.

Brief features: (not necessarily complete):
1. 1D plots
1. Waterfall plots
1. Tiled Plots
1. Contour plots (3 or more workspaces selected, including counting children of groups and multiselection)
1. Surface plots (3 or more workspaces selected, including counting children of groups and multiselection)
1. Plotting against log values, custom values and workspace name
1. with or without error bars where applicable
1. sensible validation and feedback about the number of custom values needed.

The original issue for creation of this is #18159 and it mentions some useful datasets and python scripts for testing.

**Comment by DavidFair** [comment]
> 7. with or without error bars where applicable
Plotting with error bars, as a right click menu rather than going to the plot options s has been directly mentioned by at least 3 members of the SANS group. 
Any reduced data is always plotted with error bars, and having to go into options each time is a barrier to adoption for workbench.
