### ISSUE TITLE
ConvertUnits Documentation

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27458]
**Original reporter:** [PSI]/[Thomas Mueller]

ConvertUnits incorrectly has Degrees listed as a convertible unit

https://forum.mantidproject.org/t/strange-behavior-of-convertunits/591/5

Changing the documentation is one thing, but also worth considering is that there are unofficially two levels of units: Those that are TOF convertible and those that are not. Is having them listed in the same place in the Unit Factory but treated differently (as we currently do) the correct way to be doing things?

**Comment by NickDraper** [comment]
Suggested steps
1. create a ConvertibleUnit class inheriting from Unit
1. Add a templated method to the Unit Factory to return only classes that match the provided class template.
1. Change validator in ConvertUnits to use that.
1. Grep code for UnitFactory::Instance().getKeys() to find other potential use areas.
1. Add unit tests ensuring exclusion of unconvertible classes
