### ISSUE TITLE
Workbench Sliceviewer: non-orthogonal axes

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27464]
As a user of the sliceviewer, with data in the HKL frame, I want to have an option to toggle non-orthogonal axes in the view such that the axes are aligned with the axes in the crystal coordinate system.

The peaks workspace display should have the peaks transformed appropriately.

The line viewers should show the integrated intensity along the respective reciprocal lattice vectors.

It would be acceptable that the minimal viable product disables the line and peaks viewer in non-orthogonal mode.

Useful matplotlib links:
  - https://matplotlib.org/examples/axes_grid/demo_curvelinear_grid.html
  - https://matplotlib.org/gallery/images_contours_and_fields/affine_image.html?highlight=affine%20image

**Comment by martyngigg** [comment]
I've have done some initial investigation into this. Matplotlib seems to provide facilities for drawing both the image and axes grid with some transform applied. The code to compute the required ["skew" matrix](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/NonOrthogonal.cpp#L108) already exists and can be lifted and placed into an appropriate location that is easily callable from Python.

Once the transform is known then the peaks coordinates can be transformed easily.

The line viewer needs to use `BinMD` with the correct basis vectors and the integrated signal will be given.

My estimate break down:
 - 3 days to get the transform code into the appropriate place with appropriate tests
 - 3 days to use the transform and ensure the data/axes are displayed correctly on the view with several data sets with different normalisations.
 - 2 days for peaks viewer + tests
 - 3 days for line viewer + tests

This brings my total estimate to 11 days. I'm tempted to round this to 15 to allow for things I've not thought of.

**Comment by NickDraper** [comment]
So to give this some bounds it sounds like 11 days minimum, 15 most likely and something like 25 maximum?

**Comment by martyngigg** [comment]
I would be happy with that.

**Comment by DanielMurphy22** [comment]
Some MantidPlot issues worth checking aren't part of this new non-orthogonal sliceviewer:

Poorly cropped: #27962 and #22203
Doesn’t zoom on the area selected #27961
2D cuts Mantid vs Horace: [Image Comparison](https://www.mantidproject.org/Vates_Validation#Set_of_2D_cuts_for_non-orthogonal_lattice) #11368

**Comment by martyngigg** [comment]
Estimate to add peaks overlay in non-orthogonal view.
