### ISSUE TITLE
Workbench Features to allow migration from Mantidplot

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27475]
EPIC issue capturing the feature needed to allow all groups to migrate from Mantidplot.

(you need Zenhub to see the contents of this issue)

Epic for nice to haves #28734

**Comment by AndreiSavici** [comment]
Issue #28650 is dealing with building Mantid on systems with Qt5 only

**Comment by martyngigg** [comment]
@peterfpeterson The only two remaining items are ORNL items: #28490 & #28491. Can I transfer this to you to take forward?

**Comment by AndreiSavici** [comment]
And Step Scan Analysis. That's on our TODO list

**Comment by martyngigg** [comment]
Thanks. I've removed our ISIS team label to indicate we won't be considering it for work scheduling.

**Comment by martyngigg** [comment]
It looks like the final two issues for this were killed by the stale bot. Should we close this and you can schedule your remaining items separately when they are a priority for you?
