### ISSUE TITLE
ISIS Reflectometry GUI batch number increments even if previous batch no longer exists

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#27500]
### Expected behavior
The batch number displayed should only increment if the previous batch exists, rather than every time a new batch is requested.

### Actual behavior
The batch number does not correspond to the actual number of batches, possibly caused by #26669 in response to #26534.

### Steps to reproduce the behavior
- Open ISIS Reflectometry
- Batch -> New
- Close `Batch 2`
- Batch -> New
- Observe it is now called `Batch 3`

### Platforms affected
All

**Comment by gemmaguest** [comment]
It's worth asking scientists whether they care about this. I expect it will be low priority and might be a bit fiddly to fix so I'll ice-box this for now.

**Comment by gemmaguest** [comment]
Closing because this is low priority and we are unlikely to get around to it. It was a developer suggestion rather than a request from users.
