### ISSUE TITLE
NxCanSAS written when both selected

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27521]
**Original reporter:** ISIS/Steve

### Expected behavior
When NxCanSAS is not selected in the SANS GUI we should not write it

### Actual behavior
It is written regardless

### Steps to reproduce the behavior
- Select Both (memory and file) save types
- Check CanSAS and RKH
- Uncheck NxCanSAS
- Process data

**Comment by smk78** [comment]
Leide checked this issue in Workbench 5.0.0 and said it was resolved.

**Comment by smk78** [comment]
Just checked Workbench in Mantid 6.0.0. This is resolved.
