### ISSUE TITLE
Bring OSX packaging in line with other platforms

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27524]
Currently OSX does not package separate builds for unstable and nightly installs, additionally we have not added a space between Mantid and Plot

We should tackle both at the same time on the platform

**Comment by DanielMurphy22** [comment]
Removing MantidPlot label so this doesn't get closed after we drop MantidPlot

**Comment by martyngigg** [comment]
Closing as a duplicate of #27453
