### ISSUE TITLE
Switch to having compability mode off by default on SANS

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27532]
After an issue with event workspaces not tracking bin masks correctly was resolved we should switch to using the updated version by default

**Comment by DavidFair** [comment]
I've followed up with the scientists on Zoom - they are double checking the data against a standard sample

**Comment by smk78** [comment]
So in MantidPlot 5.0 and Workbench 5.0, what is the default for compatibility mode, On or Off?

**Comment by smk78** [comment]
LARMOR, SANS2D & ZOOM have all agreed that Compatibility Mode is now obsolete and so it _can_ be OFF by default. We also note that the new TOML User File parser does not support COMPATIBILITY in anticipation of this. Accordingly I am closing this issue.
