### ISSUE TITLE
Unicode not supported for Column access to TableWS

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27555]
**Original reporter:** [ISIS]/[James Lord]

This is something that should be fixed automatically when we move to Python 3.

### Expected behavior
Can access a table column as a list with the syntax MyTable.column[“Column header”], even if writing code that is Python 3 compatible
### Actual behavior

```
TypeError: No registered converter was able to produce a C++ rvalue of type int from this Python object of type unicode
  File "<string>", line 14, in <module>

```
### Steps to reproduce the behavior

Create a table (for example a results table from Muon Analysis)
Open a new script tab in Workbench. Add the following after the standard headers (change the actual table and column names as appropriate):
```
tab=mtd["ResultsTable"]
colY=tab.column("workspace_name")
print (colY)
```
Note that removing the “unicode_literals” from the future statement makes the script work as intended.
### Platforms affected
Workbench 4.2

**Comment by martyngigg** [comment]
This is no longer an issue with Python 3 as Boost.Python knows how to deal with unicode automatically.
