### ISSUE TITLE
Remove Fit algorithm Dialog 

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27563]
**Original reporter:** [James Lord]/[ISIS] on [Mantid Forum](https://forum.mantidproject.org/t/fit-dialog-in-workbench/614)

**Due to the issues mentioned below, the Fit Dialog should be deprecated and then removed. The Fit algorithm obviously should not be deprecated!**

To reproduce:
Load data e.g. `EMU00020884.nxs`
Open the Fit Dialog by executing the `Fit` algorithm.
Right-click in the Property / Value box and add a function e.g. `ExpDecay`.

- Tick the `create output` and `Keep Open` boxes and run the fit twice. The second time produces this error: `Property with given name already exists search object OUTPUTNORMALISEDCOVARIANCEMATRIX `.

- Adding ties to the Property/value box works fine, but trying to input a Tie in the input box on the right doesn't work. I have tried syntax like `Height = 2`, or `f0.Height=2` as suggested in the [Fit Docs](https://docs.mantidproject.org/nightly/algorithms/Fit-v1.html#setting-ties).

- _Usability/ Nice to have_ Fit interface should remember the last inputs. Setting StartX and EndX on the Dialog, related to a certain workspace, then re-entering the Dialog (maybe you've already done a fit but didn't keep open. The suggestion is that reopening to the same assigned workspace should remember your last StartX and EndX inputs. I think this last point is particularly up for discussion as you may want those parameters reset upon re-entering the dialog.

### Platforms affected
In 4.2 and still in 5.1.1

**Comment by DanielMurphy22** [comment]
@martyngigg should I label this up for Maintenance?

**Comment by martyngigg** [comment]
@DanielMurphy22 Yes, please.

**Comment by sf1919** [comment]
I've had a quick look at this one as I'm working on fitting functions for the Muon scientists and have some questions.

Where are the Create Output and Keep open boxes to tick?

Is the second issue still an issue? There have been some recent fixes to ties (#31600 and #31740) that may have resolved this?

**Comment by DanielMurphy22** [comment]
<img width="717" alt="Screenshot 2021-11-25 at 10 00 34" src="https://user-images.githubusercontent.com/55980573/143420596-128c8cb6-a265-4523-a4c7-3481d0f23d4b.png">
If you execute the algorithm `Fit` then you get this dialog which is custom for this one algorithm. It's not been updated in a long time and as stated above there are a few issues. I can check to see if these tie fixes help for this dialog. Most of the reason to remove it is that users access fitting through the Fitpropertybrowser rather than this dialog.
