### ISSUE TITLE
Muon Analysis loading files

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#27593]
Open muon analysis
Set the search paths to include a dir with some files in, turn off search archive
Disconnect from the internet
Type the run number into the run box for your run
The path will be wrong - it may also be the wrong data

**Comment by AnthonyLim23** [comment]
I have looked into this some more and have a test file. 

If you go to manage user directories and turn off the archive. and add the path to the test file. 

The set the GUI to MUSR and search for 62250, it will load some data
The data will be longitudinal, however the test file has been edited to be transverse field (works if loaded directly). 

It appears that something is not giving priority to the local paths.

**Comment by AnthonyLim23** [comment]
it is the muon GUI that is doing this as the same thing does not happen when loading via Mantid's generic load.

**Comment by AnthonyLim23** [comment]
I have had a look into this and the line causing the problem is https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/utilities/muon_file_utils.py#L74

we will need to use file finder. We will also need to remove the use of file finder from increment step

**Comment by giovannidisiena** [comment]
I have noticed that if you put a breakpoint in `handle_load_current_run` and hit the enter key then the current run loads, however the breakpoint is never hit. If you click the widget then the breakpoint is hit but there are issues with loading.

**Comment by ConorMFinn** [comment]
Fixed by #28135
