### ISSUE TITLE
Figure Window Placement

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27599]
**Original reporter:** [James Lord]/[ISIS]

In MantidPlot successively plotted spectra appear offset from eachother, whereas in Workbench they appear centrally ontop of eachother on the screen. 
While this is a matplolib default worth deciding if there is a fix we can make to aid workflow.

Should the Workbench figures appear offset? Or should there be an option for defining where on the screen plots appear? Currently this can be done in a script ([See Mantid help Forum Post](https://forum.mantidproject.org/t/matplotlib-figure-placement-on-screen/616/4)).

**Comment by RichardHeenan** [comment]
I have the same question, 40 plots stacked directly on top of each other in middle of screen, very annoying as have to minimise or move all 40 of them.

**Comment by RichardHeenan** [comment]
Hiding some plots in the widget helps in some circumstances.

fig.canvas.manager.window.move(400,100) does work, but has to be called before plt.show(), calling afterwards causes a hang, "Firgue not responding", and hangs Mantid
Now need to find out the valid range of coords for current canvas.
