### ISSUE TITLE
Investigate better criteria for exclusion of peaks near edge of detector in IntegrateEllipsoids

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#27616]
WISH scientists say peaks that are on the detector are excluded when IntegrateIfOnEdge=False in IntegrateEllipsoids.

(1) Ask Pas/Fabio on WISH for data where this is known to be an issue
(2) See if peaks can be integrated if only part of background shell is on edge of detector (do some volume normalisation?)

**Comment by DannyHindson** [comment]
No longer required
