### ISSUE TITLE
Grey out HKL range if using PredictFractionalPeaks with modulation vector

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#27623]
### Actual behavior
When using the algorithm PredictFractionalPeaks with modulation vector(s) rather than HKL offsets, the HKL min/max are ignored. If this is the desired behaviour it is confusing that the user can still view and change the min/max values.

![image.png](https://images.zenhubusercontent.com/5dbffa7381092200013ab2b9/4384d2df-2e87-43a3-96f9-3d8f526a8e1d)

### Expected behavior

Grey out the HKL min/max if MaxOrder > 0 and at least one ModVector provided.

### Steps to reproduce the behavior
(1) Load in some peaks e.g.
```
LoadNexusProcessed(Filename='TOPAZ_3007.peaks.nxs', OutputWorkspace='peaks')
LoadIsawUB(InputWorkspace='peaks', Filename='TOPAZ_3007.mat')
IndexPeaks(PeaksWorkspace='peaks')
```
(2) Execute PredictFractionalPeaks in GUI

**Comment by martyngigg** [comment]
I've unassigned myself as I think this should just go into the pool of work for SX and then be picked up and prioritised at the next sprint planning meeting.

**Comment by DannyHindson** [comment]
Complete
