### ISSUE TITLE
Muon analysis GUI unexpected logger warning

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#27632]
In the Muon analysis GUI, if the plot type is changed to counts while a pair is plotted the following warning will appear in the logger on Windows:
```
  File "C:\Users\BTR75544\work\dev\mantid\scripts\Muon\GUI\Common\plotting_widget\plotting_widget_presenter.py", line 133, in handle_plot_type_changed
    self._view.plot_selector.setCurrentText(ASYMMETRY_PLOT_TYPE)
AttributeError: 'QComboBox' object has no attribute 'setCurrentText'
```
This issue does not occur on Ubuntu 18.04
### Steps to reproduce the behavior

1. Open the Muon Analysis GUI
2. Load some data e.g MUSR 2223
3. Try to change the plot type to counts
4. An error will appear in the logger

### Platforms affected
Windows

**Comment by AnthonyLim23** [comment]
this has been fixed
