### ISSUE TITLE
Upgrade to Flake8 - Python 3 version

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27683]
Currently we are using Python 2 Flake 8 on the build servers

Whilst this ensures we currently write compatible code, once the full migration to Python 3 is complete we will not be able to write new constructs (such as those found in #27682) without updating to the Python 3 version

**Comment by martyngigg** [comment]
@DavidFair I think we have finished this now?

**Comment by DavidFair** [comment]
Yea, good find on this issue
