### ISSUE TITLE
Python 3: Minor issues 

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#27717]
This issue is to collect and fix minor problems that are found with Python 3 builds before they become the default.

- [x] Upon opening Workbench I get this error in the log: "is" with a literal. Did you mean "=="?. - Python 3.8
- [X] ~~A warning after plotting and opening figure options: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python. an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python. (Python 3.8)~~ #27721

**Comment by martyngigg** [comment]
The issue with `"is" with a literal. Did you mean "=="` is not critical as it a warning from the compiler and once the complication has been done it disappears.

**Comment by NickDraper** [comment]
Is with a literal fixed in #27902
