### ISSUE TITLE
Sliceviewer optional Rebin

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27729]
**Original reporter:** [Jos Cooper]/[ISIS] on [Mantid Help Fourm](https://forum.mantidproject.org/t/sliceviewer-in-workbench/627)

The Sliceviewer in Workbench currently does not perform any type of rebin before displaying the data. MantidPlot does for Spectrumviewer and both SpectrumViewer and Sliceviewer in MantidPlot open Eventworkspaces.

This means that in WB:
- EventWorkspaces (one large bin) cannot be viewed.
- Event data that is rebinned, with PreserveEvents ticked, causes the Sliceviewer to run slow. 

If opening the Sliceviewer performed a Rebin which didn't preserve events, then both issues would be solved.

*Worth Noting*
- Users would like to zoom in so try not to ruin resolution on the rebin
- This rebin could be an option in the Sliceviewer Interface for users that don't want to rebin!

To reproduce these issues, use OFFSPEC00050000.nxs from the archive, as mentioned on the Mantid Forurm post.

**Comment by NickDraper** [comment]
This has been resolved by #27741, all event workspaces are now loaded with 500 linear bins by default.
