### ISSUE TITLE
Slice viewer not working with matplotlib 3.1

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27736]
### Steps to reproduce the behavior
Load a Workspace, right-click it and select 'Show Slice Viewer'

```
The buttons attribute was deprecated in Matplotlib 3.1 and will be removed in 3.3.
Could not open slice viewer for workspace 'ws'.
```

### Platforms affected
Windows only

**Comment by PhilColebrooke** [comment]
@martyngigg

**Comment by martyngigg** [comment]
@PhilColebrooke Thanks for raising this. I'll take a look.
