### ISSUE TITLE
Disable Plotting options for EventWorkspaces?

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27731]
Currently in MantidPlot the Rightclick options Plot Spectrum, Plot Spectrum with Errors and Plot Advanced are all greyed out, when related to an EventWorkspace which is just one large bin.

In Workbench, you can perform these plots but the Plots are empty. 
There are a few options here. 
- Grey out as we doin Mantid Plot
- Suggest to the user that they perform a rebin
-  Just perform a rebin on their data (probably still with some advisory note)

This can be investigated by checking the CNCS_7860_event.nxs from the Training course Data or Usage Data.

As the Advanced plotting options are still being added to Workbench, this is something that may need to be altered when they are completed. refs #27450

**Comment by NickDraper** [comment]
Teo parts to this one:
1. Disable plotting options for workspaces with a single bin (the plots would be useless)
1. Add better default binning to LoadEventNexus
