### ISSUE TITLE
Muon Analysis 2 single and simultaneous fitting 

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#27746]
The users of the Muon Analysis 2 GUI have reported that the fitting tab is difficult to use for their most common workflows.

This issue is to improve the functionality of the fitting tab within this GUI for single and simultaneous fits. Sequential fitting with be addressed in a separate issue.

**Comment by AnthonyLim23** [comment]
This includes removing the sequential fitting to a new tab (add issue).
