### ISSUE TITLE
Python 3: Fix remaining tests under Python 3.7/3.8/matplotlib 3.1

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#27744]
#27742 attempted to turn on Python 3 support by default but shows that tests are currently broken running under Python 3.7 or Python 3.8 and also matplotlib 3.1.

This issues is to fix these tests.

**Comment by DavidFair** [comment]
To Do:
- [ ] **python.WorkflowAlgorithms.BayesQuasiTest.BayesQuasiTest (Failed)**
- [ ] python.WorkflowAlgorithms.BayesStretchTest.BayesStretchTest (Failed)
- [ ] MantidQtWidgetsCommonTestQt5_QtJSONUtilsTest (Failed)
- [ ] MantidQtWidgetsMplCppTestQt5_ColorsTest (Failed)

I've bolded the one I'm currently working on

**Comment by DavidFair** [comment]
@martyngigg `MantidQtWidgetsMplCppTestQt5` is related to how we use sip, [possibly a fix?](https://stackoverflow.com/questions/51693993/pyqt5-error-pycapsule-getpointer-called-with-incorrect-name) but unsure how it fits in to how were configuring

**Comment by martyngigg** [comment]
@DavidFair Thanks for looking at that. I thought I had taken the sip configuration into account in https://github.com/mantidproject/mantid/blob/27744_Fixup_py3_test_failures/qt/widgets/common/src/Python/Sip.cpp#L27. We have to support both situations where sip is bundled inside PyQt and not. Are we missing something there?

**Comment by martyngigg** [comment]
We now have 3 system tests that are failing:
- [ ] SANSILLReductionTest.ILL_D33_LTOF_Test
- [ ] SANSILLReductionTest.ILL_D33_Test
- [ ] SANSILLReductionTest.ILL_D33_VTOF_Test

The results match quite closely but are not identical. It is not clear why.

**Comment by martyngigg** [comment]
@gvardany alerted me to changes he has made in #27734 and merging these changes with this branch causes the above SANS ILL tests to pass. This means no further work should be required now.
