### ISSUE TITLE
Update MantidVersion to 5.0

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#27754]
We need to make sure the release notes are renamed to v5.0 too.

This would actually be easier to do after creating the release branch and on it so it can simply be merged to master.

**Comment by martyngigg** [comment]
This was done in [f5f261fec14eaff66276d0e40fa767518b545111](https://github.com/mantidproject/mantid/commit/f5f261fec14eaff66276d0e40fa767518b545111).
