### ISSUE TITLE
Load MantidPlot projects into Workbench

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#27766]
Some users have not switched to workbench as they are unable to load their work from MantidPlot. 

We should have some sort of conversion, so MantidPlot projects can be loaded into workbench.

**Comment by martyngigg** [comment]
It was agreed at the IMSSC that we would first simply make sure it's easy to load just the workspaces from a MantidPlot project file and then add documentation describing how users can work with old projects.
