### ISSUE TITLE
Can't open figure options on sample logs plot

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#27770]
### Steps to reproduce the behavior
1. Load deltat_tdc_dolly_1529.bin.md5 in the unit test data.
2. Right click and select Show Sample Logs
3. Scroll down and click Temp_ChannelA.
4. Double-click the plot so it pops out.
5. Click the cog in the toolbar.

**Comment by Harrietbrown** [comment]
This bug also prevents opening the context menu by right clicking on the plot.
