### ISSUE TITLE
Investigate peak finding in NSX tool

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#27781]

**Comment by RichardWaiteSTFC** [comment]
Have tested an intial workflow which is briefly: integrate detector banks over a range of TOF/d, use blob finding in NSXTool (in 2D not 3D as in GitLab), for each 'blob' group pixels and find peaks in TOF spectra (either with simple threshold on counts, or by convoluting with second-derivative of gaussian).

![image](https://user-images.githubusercontent.com/55979119/74727905-c5996780-5239-11ea-9bcf-149645125808.png)
