### ISSUE TITLE
SaveASCII error in non-histogram data

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#27797]
**Original reporter:** Jue Liu at ORNL

Using `SaveASCII` on data that has the same number of x-values as y-values, generates an ascii file where the x-values are shifted by the space between the first two points.

This should be done similar to #27945

**Comment by wdzhou** [comment]
2020.09.02: Triaged to ORNL RSE diffraction backlog [issue 65](https://code.ornl.gov/sns-hfir-scse/diffraction/diffraction-backlog/-/issues/65)
