### ISSUE TITLE
Add option to FindUBUsingFFT to constrain certain lattice vectors to quadrants of Q-space

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#27821]
As a user I want to find self-consistent UB matrices for a series runs with different goniometer angles that  (i.e. to make sure one axis hasn't flipped sign, or two symmetrically equivalent axes haven't been permuted).

**Comment by DannyHindson** [comment]
@RichardWaiteSTFC - just going through some diffraction issues that are in GitHub but not assigned to a milestone (good Fri afternoon activity!). Can this one be closed now? Sounds like it's the python algorithm you created?

**Comment by RichardWaiteSTFC** [comment]
Yes good spot this has been done, so I'll close it!
