### ISSUE TITLE
Matplotlib deprecations

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27862]
Currently Worbench is on Matplotlib 3.1.

List of Deprecated functions, which will be removed:

- The get_cmap function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.get_cmap instead.

- The gridOn function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use Tick.gridline.get_visible instead.

- The set_clim function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_clim instead.

Worth checking this list: https://matplotlib.org/3.1.0/api/api_changes.html

Also here's a non-MPL one:

- Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

refs: #27863

**Comment by NickDraper** [comment]
The apparent warnings we were seeing were resolved in #27907
