### ISSUE TITLE
plotSpectrum() in Workbench

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27870]
**Original reporter:** Jos Cooper

### Expected behavior
In MantidPlot from a script you can produce a plot with the command plotSpectrum('ws')
### Actual behavior
In workbench no such command exists

Also add in plotBin()

**Comment by NickDraper** [comment]
sample code for testing
```python
mar = Load("mar11060")
mar2 = mar+mar
plotSpectrum(mar,1)
plotBin(mar,1)

plotSpectrum([mar,mar2],1)
plotBin([mar,mar2],1)
plotSpectrum([mar,mar2],[1,2,3])
plotBin([mar,mar2],[1,2,3])



plotSpectrum(["mar","mar2"],[1,2,3])
```
