### ISSUE TITLE
Get tooltips from ReflectometryISISLoadAndProcess

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#27889]
In the ISIS Reflectometry in `QtBatchView` we are still using `ReflectometryReductionOneAuto` to get the tooltips rather than `ReflectometryISISLoadAndProcess`. If we change it we will break the `Encoder` and `Decoder` unit tests because C++ tests cannot use python algorithms. The code needs to be reorganised to avoid creating the algorithm, or the tests rewritten in python. The fix needs to be added in `QtBatchView.cpp` and the column properties updated in `PerThetaDefaults.h`.

This only affects tooltips for a couple of the properties (the first and second transmission runs, which are documented as single inputs rather than lists) so is not an urgent fix.

### Steps to reproduce
This will only become apparent after PR #27854 because these fields are not used otherwise.
- Open the ISIS Reflectometry interface
- Go to the Experiment tab
- Hover over the cell in the transmission runs column
- Note that its description matches that from [ReflectometryReductionOneAuto](https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOneAuto-v3.html) rather than [ReflectometryISISLoadAndProcess](https://docs.mantidproject.org/nightly/algorithms/ReflectometryISISLoadAndProcess-v1.html?highlight=reflectometryisisloadandprocess).

**Comment by giovannidisiena** [comment]
@gemmaguest I don't think we can access the documentation without the creating an instance of the algorithms however it is possible for C++ tests to start the Python environment using `PythonInterpreterGlobalFixture`
https://github.com/mantidproject/mantid/blob/2f7908d5c762530dd875e2833e616748fa706898/qt/widgets/mplcpp/test/MplCppTestInitialization.h#L19 hence Python algorithms in C++ tests 🐍
