### ISSUE TITLE
Update Beam Centre Model Rmin/max based on HAB/LAB

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#27893]
Different instruments want a different `r_min` and `r_max` value depending on the instrument and bank selection within `beam_centre_model`

I've asked Steve to find out from each instrument what their optimals would be, so we can include them for all

**Comment by DavidFair** [comment]
We need to re-check this after the scientists have explored how various sizes interact following #27966

**Comment by smk78** [comment]
On review, the SANS Group would like to specify the r_min, r_max, and iteration_step in the User File. So also see https://github.com/mantidproject/mantid/pull/28513

**Comment by smk78** [comment]
Given that the radius limits have been propagated in the new TOML user files
```
[detector]
  radius_limit = {min = 0.035, max = 0.419}
```
the linked issues here need review.
