### ISSUE TITLE
Python script errors

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#27923]
Reported by James.

The Workbench script editor is still broken for most scripts with a non-trivial number of lines and any indentation, such as one that defines an algorithm. Fortunately there are work arounds which run the code without Workbench being able to mangle it such as: import sys; sys.path.append(“/my/scripts/directory”); import my_alg_script

for example:

Muon/CopyLogsToHist8.py
Muon/AnalyseThresholdScans9.py
Muon/DetectorRateTimeSeries2.py

These all have (consistent) Tab indentation but I get the same errors for each file if I run “Tabs to Spaces” first.

CopyLogsToHist8 and DetectorRateTimeSeries2 give 
SyntaxError: unindent does not match any outer indentation level
while AnalyseThresholdScans9 thinks for a long time and then gives
SyntaxError: unexpected indent
on line 12.

p.s. In AnalyseThresholdScans, if I add print (“I got this far”) just after the import statements at the top, that does get printed to the messages window and it goes on to crash with the syntax error at the same line in the code that follows (it’s now line 13 because of the insertion). This isn’t intuitive: I thought Python normally syntax checks the whole script at the start before executing the first line?

**Comment by DanielMurphy22** [comment]
All of these indentation errors look the same as this issue: #27713 
As for the syntax error crash, it may be related to: #27245 
These two issues are both in the same umbrella: #27559
