### ISSUE TITLE
Plot guess incorrect

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27937]
Found during transfer of Mantid Basic Course to Workbench

### Expected behavior
Plot guess after fitting should look basically the same as the calculated fit!
### Actual behavior
Plot guess a lot smaller
![github](https://user-images.githubusercontent.com/55980573/74457529-447c5200-4e80-11ea-8423-8a0ea660a0f3.png)
### Steps to reproduce the behavior
Load GEM63437_focussed from trainingcoursedata, plot the 3rd workspace. Fit a linearbackground and an IkedaCarpenterPV peak to the peak around 8830 microseconds. Display the Plot guess and then run the Fit, it worked before the fit but not after!  This could be a normalisation issue, but this data isn't normalisable!
### Platforms affected Workbench, 4.2 Nightly
This was wrong in 4.2, correct in 4.1!

**Comment by NickDraper** [comment]
@alicerussell1 this looks like it might be normalisation again
