### ISSUE TITLE
Sliceviewer zoom Non-orthogonal Axis

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27961]
**Original reporter:** Pas Manuel / ISIS

### Expected behavior
Zooming in Sliceviewer in non-orthogonal axis mode should zoom in on the area selected 
### Actual behavior
Zooming doesn't always work
### Steps to reproduce the behavior
Open Sliceviewer on an MD workspace of a Hexagonal reciprocal space. Enter Non-orthogonal axis mode. Try zooming in on the area you want.

This relates to the fact that you cannot unlock the aspect ratios for the Non-orthogonal view (from the drop-down menu "View" in sliceviewer)
### Platforms affected
MantidPlot 4.2 Nightly and 4.0 checked

**Comment by martyngigg** [comment]
Closing this as won't fix as it's always been like this and the workbench replacement does this properly.
