### ISSUE TITLE
Abins deprecation warning

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27972]
Found when testing for this issue on the [forum](https://forum.mantidproject.org/t/adding-the-same-lines-to-axes-in-a-different-order-affording-incorrect-plots/648)
### Expected behavior
Abins is used a lot, and we don't want any deprecation warnings
### Actual behavior
Get deprecation warning : `dataset.value has been deprecated. Use dataset[()] instead.`
### Steps to reproduce the behavior
run this:
```
benzene_wrk = Abins(AbInitioProgram="CASTEP", VibrationalOrPhononFile="benzene.phonon",
                    QuantumOrderEventsNumber="1")
for name in benzene_wrk.getNames():
    print(name)
```
you will need this file on your path
[benzene.zip](https://github.com/mantidproject/mantid/files/4224960/benzene.zip)

https://discourse.julialang.org/t/dont-understand-what-h5py-people-are-thinking/26387

refs #27863 
### Platforms affected
Workbench Nightly since Py3 (Seen on 4.2.20200211.2150)

**Comment by ajjackson** [comment]
Good spot, will sort it

**Comment by ajjackson** [comment]
Have tracked this down. Only appears with recent versions of h5py, I couldn't see the warnings with the ubuntubionic development docker image until that library was updated with Pip.

These warning messages are pretty unhelpful as they don't give their origin, but it seems that they all come from a couple of places in AbinsModules.IOmodule .
