### ISSUE TITLE
Powder Diffraction Reduction change instrument has invalid options

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28039]
### Expected behavior
When oppened for the first time or when choosing to change the instrument on the Powder Diffraction Reduction GUI a dialog box opens with several options. these options should all be valid
### Actual behavior
In the dialog box for facility you can select `MLZ`, `ISIS`, or `HFIR`. none of these have any instruments associated and if chosen will just open up the dialog again and ask untill you select a valid option.
Also selecting cancel will close the whole gui instead of closing the dialog box like one would expect.
### Steps to reproduce the behavior
1. open workbnch
2. `Interfaces->Diffraction->Powder Diffraction Reduction`
3. If this is your first time opening the gui the dialog box should open, if not go to `Tools->Change Instrument`
4. Select `SNS` and `NOM`. the gui should open normaly.
5. `Tools->Change Instrument`
6. Select `MLZ`, there is no instrument option
7. Click OK, the gui goes blank and the dialog open again.
8. Try with `ISIS` or `HFIR`, the same result should happen.
9. Go back to `SNS` and `NOM`.
10. Open the change instrument dialog.
11. Click cancel, instead of closing the dialog it closes the gui.
### Platforms affected
Windows

**Comment by RichardWaiteSTFC** [comment]
ISIS powder reduction is handled with a script (not via the GUI) - I believe the same is true of MLZ, but need to check this. If both ISIS and MLZ don't have instruments using this reduction gui I will remove the facility from the drop-down options
