### ISSUE TITLE
Multi-dataset fitting does not overplot in sequential fitting

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28051]
When attempting to perform a sequential fit in `Multi-dataset fitting` the fit function and difference are not plotted in the gui as they should.

1. Open Mantid Plot.
2. Load some multiple specta data.
3. `Interfaces->General->Multi-dataset fitting`.
4. Add the workspace to the gui, make sure to add all spectra.
5. Add a flat background
6. Change fitting to Sequential.
7. Click fit, the background is not ploted as it should.

**Comment by alicerussell1** [comment]
I am closing this as it we have looked into it and the fit is only not plotted if `Create Output` is set to False - which makes sense as the plot is done from the outputted workspace.
