### ISSUE TITLE
Settings appear off screen

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28061]
### Expected behavior
If I open the settings dialog then it will be visible on the screen.
### Actual behavior
It default to the centre of the Mantid Workbench window (which may be off the screen)
### Steps to reproduce the behavior
Drag the Mantid Workbench window down to the bottom of the screen and open settings
Now Mantid is unusable and has to be force quit through the task manager.

Another window that is "similarly generated" (I think) is Figure options. but it cannot be generated off screen (but could theoretically be dragged off!)
### Platforms affected
Presumably all versions Workbench. Tested WB 4.2.20200211.2150 Windows

**Comment by ConorMFinn** [comment]
This issue isn't a problem on Ubuntu 18.04. The settings appear as a separate window in an accessible location.
