### ISSUE TITLE
No option to show hidden axis in MantidPlot

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#28068]
### Expected behavior
If a user hides an axis on a plot there should be an option to show it again.

### Actual behavior
After hiding an axis it is not possible to show it again.

### Steps to reproduce the behavior
Plot any spectrum and hide an axis

### Platforms affected
All

**Comment by NickDraper** [comment]
Acknowledged, but as this is a deprecated interface, and this has not been reported by any users, just the dev team testing then we won't be fixing this at the moment.

Actually you can get access to show a menu again as long as you haven't hidden the last axis.  You can click on any existing axis, and then have access to show/hide all of the axes.
