### ISSUE TITLE
Plotting not working in mslice

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#28076]
When you try and display a slice or plot a cut in mslice you get the error messaged below. This looks like it is related to the moving around of plotting functions again.

```
AttributeError: module 'mantid.plots.plotfunctions' has no attribute 'errorbar'
```

```
AttributeError: module 'mantid.plots.plotfunctions' has no attribute 'pcolormesh'
```

**Comment by martyngigg** [comment]
@Mantid-Matthew Is this mslice or the sliceviewer?

**Comment by martyngigg** [comment]
No worries. I found the issue.

**Comment by martyngigg** [comment]
The fix needs testing first in the mslice repo. Pull request mantidproject/mslice#520 contains the fix - could you review that first?
