### ISSUE TITLE
Additional 'none' item in the legend of 1D plots

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#28090]
If the legend of a 1D plot is modified on Ubuntu an extra 'none' entry will appear in the legend. 

Its possible the legend needs to be redrawn using ax.legend() followed by fig.canvas.draw(). For instance, the following steps remove the extra entry. 

(1) Plot the data and add errors, and then go to the IPython window and do:

`fig = plt.gcf()`
`ax = plt.gca()`
`ax.legend()`
`fig.canvas.draw()`

Edit: This also occurs in fitting
![image](https://user-images.githubusercontent.com/56431339/75330873-af169000-5879-11ea-9910-412b65e7f074.png)

### Steps to reproduce the behavior
(1) Load some data
(2) Plot a spectra
(3) Add errors
(4) An extra none entry will appear in the legend 

### Platforms affected
Appears to be limited to workbench on Ubuntu.

**Comment by DanielMurphy22** [comment]
Think its creating a Legend Title with the word `None` when it should be '' and so not displayed

**Comment by DavidFair** [comment]
Quick speculation, could be an erroneous str cast like so

```
a = None
a = str(a)
plot(..., a)
```
