### ISSUE TITLE
AlgorithmManager: Only retain running algorithms

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#28093]
The key `algorithms.retained` in the ConfigService is used to control how many `AlgorithmProxy` objects are retained by the `AlgorithmManager`. This behaviour is no longer required and the `AlgorithmManager` should only need to retain a handle to running algorithms for cases such as backgound LiveData algorithms.

The first step in this issue is to only have `AlgorithmManager` retain running algorithms. A bonus step would be to remove the need for the `AlgorithmProxy` class completely but this can be treated as a second-order issue.

**Comment by NickDraper** [comment]
#28093 has a good test case of a script that runs lots of algs v.fast, try to load another file while the script is running.  At the moment the load alg can fall off the end of the retained algs list while it is running and then is v prone to crashes.
