### ISSUE TITLE
Workbench 1D plot log axis scaling errror

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#28100]
If you first change the axis type(e.g x-axis) to log by double clicking on the axis markers and then use the right-click menu to change the axes to log-log, the graph struggles to find appropriate scaling for the axis. For instance:

![image](https://user-images.githubusercontent.com/56431339/75329317-5645f800-5877-11ea-8362-fceeced5d9fb.png)

### Steps to reproduce the behavior
(1) Plot a spectra
(2) Double click on x axis, and change to log
(3) Right click on graph and change axis to log x / log y
(4) Axis scaling is completely off

### Platforms affected
Tested with Workbench on Ubuntu

**Comment by DanielMurphy22** [comment]
Similar to #27759
