### ISSUE TITLE
Tile plot not fully recovered by project recovery

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#28110]
### Expected behavior
Tile plots should be recovered by project recovery.

### Actual behavior
Only one plot on the tile plot is recovered, see below:
[print.pdf](https://github.com/mantidproject/mantid/files/4256121/print.pdf)

### Steps to reproduce the behavior
Follow 4: http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html

### Platforms affected
Workbench on Ubuntu 18, possibly all but unable to test on Windows (see #28075)

**Comment by martyngigg** [comment]
@giovannidisiena Do you know if this worked in 4.3?

**Comment by giovannidisiena** [comment]
@martyngigg no, it doesn't appear to be a regression.

**Comment by ConorMFinn** [comment]
The functionality for project recovery loading was designed to only support figures with a single axes. Supporting multiple axes would be a feature change so it may be better to fix this as a maintenance issue?

**Comment by martyngigg** [comment]
@ConorMFinn  I think you're right at this stage we should keep changes to a minimum. By all means do the work now but it should probably go on master unless the changes required are trivial.
