### ISSUE TITLE
ConvFit fit issues

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#28123]
There seems to be two cases  in which convfit has some issues.

- If you do a fit with a resolution file which has more than one spectra the correct spectra resolutions are not assigned to the correct spectra in all cases.
- If you so a multiple input convfit with certain data there seems to be a 0 index error. I am not sure what is going on here and need to investigate.

**Comment by SpencerHowells** [comment]
@Mantid-Matthew Have you got the data where the first problem occurs?

**Comment by Mantid-Matthew** [comment]
@SpencerHowells If you want to replicate the first problem load inna non single spectrum resolution file and then select to not fit the first couple of spectra. The first couple of entries from the resolution file will still be used.
