### ISSUE TITLE
SANS Beam Centre Finder only working on LAB

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#28122]
**Original reporter:** ISIS/Steve

### Expected behavior
- The main-detector and HAB selection should be respected and iterate over the respective banks

### Actual behavior
- Converging on the beam centre on the main-detector then selecting the HAB will result in the same result, without any iterations. This is because it is re-centring the main-detector, not HAB

**Comment by ConorMFinn** [comment]
Fixed by #28128
