### ISSUE TITLE
Limit the notification service to prevent repeat notifications

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28126]
### Expected behavior
repeated errors with the same message should only be notified once every few seconds

### Actual behavior
You get one notification per error, even when in a tight loop

### Steps to reproduce the behavior

``` python

for i in range(10):
    Pause(1)
    Segfault(DryRun=True)

```
### Platforms affected
Mantidworkbench

**Comment by ConorMFinn** [comment]
Fixed by #28129
