### ISSUE TITLE
Crash on loading file and running script executing lots of algs v.fast

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28143]
**Original reporter:** 
very similar to: refs #27594 

### Expected behavior
Should be able to run a script and load a file at the same time
### Actual behavior
Workbench and plot crash
### Steps to reproduce the behavior
run this script (should take around 13 seconds, increase the for loop if you need longer!)
while its running load a file such as HRP39182.RAW or GEM40979.raw (should be anything!)
(in MantidPlot you may need to get the load dialog ready before starting the script)
[Append_spectra_issues.zip](https://github.com/mantidproject/mantid/files/4266956/Append_spectra_issues.zip)
### Platforms affected
Workbench and Plot Nightly before 5.0 release 4.2.20200225.1733

**Comment by NickDraper** [comment]
so running this script does not affect Loading
``` python

for i in range(1000):
    Pause(0.1)
```

**Comment by NickDraper** [comment]
this is also fine, with loading mar11060
``` python 

for i in range(10):
    ws = Load("GEM40979.raw") 
    ws2 = Load("HRP39182.RAW")
```

**Comment by NickDraper** [comment]
but I can get it to crash with the script in the description

**Comment by NickDraper** [comment]
Ok, so this is due to the sheer number of algorithms being run in the script, which is 10*200*200.

If you increase algorithms.retained in the properties file from 50 to 500, the problem goes away ...

**Comment by NickDraper** [comment]
This should be used as a test case for #28093
