### ISSUE TITLE
Muon loader doesn't always load logs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#28155]
Try to load MUSR 91350 and the Steer_... logs will be missing. The error:

```
Error in execution of algorithm LoadMuonLog:
Property with given name already exists search object SAMPLE_TEMP
Unable to successfully run LoadMuonLog Child Algorithm
Unable to successfully run LoadMuonLog Child Algorithm
```

is produced

**Comment by NickDraper** [comment]
The first step here is to work out what is happening and is this something special about just this file.

What to do as a solution can only be decided after that.

**Comment by AnthonyLim23** [comment]
I have asked for a file, the one above does not work. I did see the error the other day. It seems the alg just dies if it gets unexpected information. Leaving a half populated logs for a workspace

**Comment by AnthonyLim23** [comment]
I had a look into this. The run is MUSR 81380. It does have two different entries from `Sample_Temp`. The first is loaded outside of this algorithm and is a single value (I assume the mean). The second is loaded as part of this algorithm and is a time series. 

Looking at other runs that do not fail suggest that the correct one is the single value.
