### ISSUE TITLE
Unconnected SLOTS in indirect interface

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#28178]
### Expected behavior
Signals and slot connections should match

### Actual behavior
The following warning is emitted when opening the interface
```
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::JumpFit::updateAvailableFitTypes() in ../mantid/qt/scientific_interfaces/Indirect/JumpFit.cpp:64
Object::connect:  (sender name:   'cbParameterType')
Object::connect: No such slot MantidQt::CustomInterfaces::IDA::JumpFit::updateAvailableFitTypes() in ../mantid/qt/scientific_interfaces/Indirect/JumpFit.cpp:66
```

### Steps to reproduce the behavior
- Open the Indirect interface

**Comment by Harrietbrown** [comment]
Which indirect interface is doing this?

**Comment by DavidFair** [comment]
Data analysis

The warning doesn't appear in the log, but will appear in the console where Mantid is running
