### ISSUE TITLE
Progress Arrow on wrong line when executing a section of a script

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28266]
Speak to @martyngigg 
### Expected behavior
Progress Arrow should show the lines it is executing 
### Actual Behavior
Doesn't always get it right, such as in the case detailed below
### Steps to reproduce
In a script, highlight one or many lines and execute them, the progress arrow displays at the top of the script (eg. If you ran one line in the middle of your script (could be line 5), it will display a green arrow on line 1)
### Platforms affected
Workbench 4.2.29022020

**Comment by Harrietbrown** [comment]
Fixed by #28278
