### ISSUE TITLE
Invalid completion when variable assigned to plot

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28267]
Speak to @martyngigg 

### Expected behavior
Completion should not throw an error and error reporter for what is an innocent line.
### Actual behavior
If a plot is closed the completion handle for the script is invalidated and throws an error reporter
### Steps to reproduce the behavior
run this entire script
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

ws = CreateSampleWorkspace(Function='Powder Diffraction')
plot1 = plotSpectrum(ws,1,error_bars=True)
```
Then highlight the `ws = ...` line and execute just it.
### Platforms affected
Workbench 4.2.29.02.2020

**Comment by Harrietbrown** [comment]
Fixed by #28277
