### ISSUE TITLE
Plot Settings Show errorbar crash

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28286]
**Original reporter:** Steve King

### Expected behavior
Settings for Plots should work correctly with plots and Figure Options
### Actual behavior
Not in this case
### Steps to reproduce the behavior
In Settings > Plots set the marker as anything but None (say as point)
Then plot a spectrum and show error bars.
get an error reporter and many errors.
### Platforms affected
Tested on 29022020 Nightly

**Comment by PhilColebrooke** [comment]
#27401
