### ISSUE TITLE
Unhandled exception when you enable filled areas on a waterfall plot twice and open the fill options dialog

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#28308]
If you run this script:
```
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
ax.plot([0,1],[0,1])
ax.plot([0,1],[0,1])
ax.set_waterfall(True, fill=True)
ax.set_waterfall_fill(True)
fig.show()
```
It fails on the `ax.set_waterfall_fill(True)` line but by this point the figure has been created. If you go to the Plots widget and set the figure to visible, the waterfall plot wrongly has two sets of fills. When you open the fill dialog (paint-bucket icon in toolbar), you get an unhandled exception.

Just need a check in `set_waterfall_fill` to not do it if there are already fills.

**Comment by Harrietbrown** [comment]
Fixed by #28321
