### ISSUE TITLE
Harmonise Window behaviour

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28306]
**Report to Jos Cooper**

After #27883, it was noticed that Windows behave somewhat differently across different OSs. 

This issue is to try to harmonise the behaviour of all pop-up windows in Mantid Workbench to the intended behaviour (what this is should be discussed).

The difficulty here is that different platforms use different window mangers, which treat separate windows differently.

At the moment, the fix in #28222, results in Plots being on top of everything (instrument viewer, settings) on Mac, and Linux windows not being minimisable.

**Comment by DanielMurphy22** [comment]
An odd current behaviour, is that on Mac, while plots are currently not maximisable after the #28222 fix, if you produce a plot on Mac WB and click the generate a script button, and choose script to clipboard, then the maximise green button appears in the corner of the figure! It can be disabled again by clicking "Fit"

**Comment by DanielMurphy22** [comment]
One option could be for all the interfaces to be always on top, a bit like plots, as has been implemented for the EngDiff GUI:  #29071

**Comment by DanielMurphy22** [comment]
Jos mentioned on the [Forum](https://forum.mantidproject.org/t/interfaces-hide-behind-workbench-window/690) that plotting from the reflectometry gui hides the interface behind the main window. Foxing this issue should also solve this!
![plot_hides_interface](https://user-images.githubusercontent.com/55980573/93895391-adb22680-fce7-11ea-89ee-df3dbbaa17b4.gif)

**Comment by martyngigg** [comment]
For release 6 sprint 3 the focus is purely on improving the behaviour of the ISIS Reflectometry interface w.r.t plotting. Wider improevments will wait for the interface reorganization and dropping MantidPlot.
