### ISSUE TITLE
Smoke Testing Umbrella Issue

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28319]
This is to keep track of the coverage of smoke tests during the release cycle.
Edit this Issue and Mark beside your OS on the Test you are going to complete.

eg. Windows  - @DanielMurphy22

## Clean/Dirty Install Smoke Tests: #28313 
 - [x] Windows @NickDraper @Harrietbrown @ConorMFinn @DannyHindson  @DanielMurphy22 
 - [x] OSX  @DanielMurphy22 
 - [x] Linux @ConorMFinn 
 
## Fitting Smoke Tests: #28314 
 - [x] Windows @Harrietbrown 
 - [x] OSX 
 - [x] Linux @DannyHindson 
 - [ ] IDaaS  

## Interface Smoke Tests: #28315 
 - [x] Windows @Harrietbrown 
 - [x] OSX @DanielMurphy22 
 - [x] Linux @ConorMFinn 
 - [x] IDaaS  @NickDraper

## Plotting Smoke Tests: #28316 
 - [ ] Windows @PhilColebrooke 
 - [x] OSX  @DanielMurphy22 
 - [x] Linux  @giovannidisiena 
 - [ ] IDaaS  

## Python Smoke Tests: #28317 
 - [x] Windows @giovannidisiena 
 - [x] OSX  @DanielMurphy22 
 - [x] Linux  @ConorMFinn 
 - [ ] IDaaS  

## Workspace/Algorithm Smoke Tests: #28318 
 - [x] Windows @Harrietbrown 
 - [x] OSX  @gvardany 
 - [x] Linux  @ConorMFinn 
 - [ ] IDaaS

**Comment by gvardany** [comment]
I’m getting an Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created. message in terminal for workbench on macOS.

**Comment by martyngigg** [comment]
We noticed this too but it's not currently doing any harm and most users won't see it. @DanielMurphy22 I think we created an issue for this didn't we?

**Comment by DanielMurphy22** [comment]
Didn't create a separate issue for this, just mentioned it at the bottom of #27244 (In this case the user was running mantid from the command line.
We can make a separate issue for this.
