### ISSUE TITLE
Muon and Frequency Domain Analysis GUIs Not Opening in Plot

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#28346]
### Expected behavior
GUIs should open
### Actual behavior
They do not, showing errors:
Frequency Domain Analysis:
```
AttributeError: 'FrequencyAnalysisGui' object has no attribute 'resizeDocks'
 at line 29 in '<Interface>'
 caused by line 100 in '/opt/mantidnightly/scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis_2.py'
```
Muon Analysis:
```
AttributeError: 'MuonAnalysisGui' object has no attribute 'resizeDocks'
  at line 29 in '<Interface>'
  caused by line 95 in '/opt/mantidnightly/scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py'
```
Could be something not available in qt4?
### Steps to reproduce the behavior
- Open plot
- Attempt to open either interface
### Platforms affected
Tested on Ubuntu 18.04. Also observed on Windows.

**Comment by PhilColebrooke** [comment]
https://github.com/mantidproject/mantid/blob/10b34d7ac0bd8c7560a764c187318e3546c1b5f9/scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py#L95

@StephenSmith25
