### ISSUE TITLE
Investigate MC Absorption for composite shapes

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#28341]
It looks like the absorption corrections for container inner and outer parts are simulated separately and then multiplied. 
Better would be to define both parts into the same sample geometry as a composite CSG object. See the email from MA for the details.

**Original reporter:** [ILL]/[Appel]

**Comment by SpencerHowells** [comment]
@gvardany Good idea

**Comment by gvardany** [comment]
This is fixed.
