### ISSUE TITLE
Monte Carlo Absorption v2

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#28353]
Currently MonteCarloAbsorption algorithm outputs one correction workspace corresponding to the self attenuation of the ensemble of the sample and [optionally] its environment. Better would be to calculate all 4 terms following the Paalman & Pings formalism (https://docs.mantidproject.org/nightly/algorithms/ApplyPaalmanPingsCorrection-v1.html).

This means a v2 of `MonteCarloAbsorption`, and v2 of `CalculateMonteCarloAbsorption`.
`SimpleShapeMonteCarloAbsorption` will be out of use then.

**Comment by SpencerHowells** [comment]
@gvardany This should not be changed until PP version is available. At present Applying the corrections checks the number of histograms to establish whether to use PP formulism or my approximate method when doing MC.
