### ISSUE TITLE
EnggVanadiumCorrections Needs Fixing for Dead Detectors

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#28359]
**Original reporter:** Saurabh (ISIS)

When dividing by curves to perform an efficiency correction/pixel summing(?), dead detectors can result in divide by 0 errors. 

It has been suggested that we use an existing Vanadium run (194547) to do this division as the result should not be dependant on the specific workspace being corrected. This could be a separate input with the supplied run number as a default. 

There should also be some sort of check for divide by zero errors to give a warning rather than simply stopping the algorithm if they do still occur.

**Comment by DannyHindson** [comment]
Closing because Saurabh wasn't able to get further information on this from the user who reported it to him
