### ISSUE TITLE
Soft crash on loading incorrect batch file

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28368]
This occurs when loading a mask.txt or data.nxs file as a batch file in ISIS SANS interface. The file type for the mask file field is restricted to .txt which makes it less likely that there will be a mix up. But for the batch file there are no restrictions and trying to load and process the wrong file as a batch file is not handled gracefully.

### Expected behavior
Loading a the wrong file in the field Batch file in the ISIS SANS interface should inform the user of the error and handle it gracefully
### Actual behavior
Currently there is an error reporter! and the errors are unhelpful. They can be ValueError or UnicodeDecodeError
### Steps to reproduce the behavior
Load mask file or .nxs in the Batch file field on ISIS SANS interface
### Platforms affected
found in testing for 5.0 release

**Comment by gemmaguest** [comment]
It looks like we don't filter batch files for .csv so it would be good to do that too
