### ISSUE TITLE
Inverstigate polaris correction for choppered data.

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28362]
Helen Playford has found that POL98533 (chopper on) and POL97947 (Chopper off) have a significant unexpected offset. In appearance it resembles a flat background that is present in POL98533 but not POL97947. thie background is almost perfectly in line with the self scattering correction. This means that when the correction is removed POL97947 does not fluctuate around 0 like POL98533.

This issue is to investigate the source of this offset and put in measures to correct it.

**Comment by DannyHindson** [comment]
Helen confirmed this was caused by mismatch V runs so no longer an issue
