### ISSUE TITLE
Colourfill plot context menu scales strangely

### ISSUE THREAD

**Issue by giovannidisiena** [mantidproject/mantid#28364]
### Expected behavior
Colourfill plots should look the same when changing options through the figure options and context menu.

### Actual behavior
The plots are scaled differently and the home button does not work as expected after using the context menu.

![Screenshot from 2020-03-12 14-43-15](https://user-images.githubusercontent.com/22510773/76534587-97dac380-6471-11ea-820a-068e61e4ef8d.png)
![Screenshot from 2020-03-12 14-45-46](https://user-images.githubusercontent.com/22510773/76534593-990bf080-6471-11ea-885e-33f0564f6ef8.png)

### Steps to reproduce the behavior
- Load `MARI11060`
- Open two colourfill plots
- Change both the axis scales to log via the figure options one `plot1`
- Right click on `plot2` and click `Axes->log x/log y`
- Compare and try home button
- Do the same but for the colour bar scale

### Platforms affected
Ubuntu, possibly all

**Comment by NickDraper** [comment]
Found in smoke testing, but not important enough to delay the release.
