### ISSUE TITLE
create more detailed MatchAndMergeWorkspaces method for combining detector banks

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28361]
Currently `MatchAndMergeWorkspace` merges using user defined ranges of max and min values to cut off the detectors. This PR would improve this mehtod to make a more automatic method that would judge cut off points based on the data within the workspace itself.

**Comment by Harrietbrown** [comment]
Current match and merge is actualy dooing as much as should be expected to weighting. But stich marks have been found around the edged of the workspace limits.

**Comment by Harrietbrown** [comment]
the stitch marks come from choice of q_lims combines with the correction used. there does not seem to be a way to fix that.

**Comment by DannyHindson** [comment]
Not possible to improve further
