### ISSUE TITLE
Crash - close plot, run script declaring a function

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28424]
**Original reporter:** James Lord / ISIS

(what I was calling JL_18032020 and JL_20032020)

Investigated with @alicerussell1 

Crash after closing plot and running script which declares a function

### Steps to reproduce the behavior
Plot MAR11060, spectrum 1.
Then close the plot.
Run this script (you may have to run it 2 or 3 times)
```
from mantid.api import *
import numpy

class Example1DFunction(IFunction1D):

    def init(self):
        self.declareParameter("C", 0.0)

    def function1D(self, xvals):
        # Access current values during the fit
        c = self.getParameterValue("C")

        return c*numpy.sqrt(xvals)

FunctionFactory.subscribe(Example1DFunction)
```
Below the script editor it will say "Running" and then mantid will crash
### Platforms affected
Workbench all, tested mostly on 5.0 on Windows 10

**Comment by NickDraper** [comment]
So this appears all to be about notifications from the FuinctionFactory, all FitPropertyBrowsers (there's one for each plot in workbench) subscribe to an update notification.  But when the graph has been deleted the notification is still going to the now deleted object and causing a crash.

**Comment by DanielMurphy22** [comment]
I've emailed James now this has been resolved
