### ISSUE TITLE
Workbench can't count the number of new script tabs 

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#28445]
### Expected behavior
Every new tab should go
New tab
New tab (1)
New tab (2)...etc.

### Actual behavior
We get
New tab
New tab
New tab (1)
New tab (1)
New tab (2)
New tab (2)

### Steps to reproduce the behavior
Open workbench and hit CTRL+N a lot

**Comment by ConorMFinn** [comment]
I was unable to reproduce this on Ubuntu 18.04

**Comment by DavidFair** [comment]
Kubuntu 18.04, so we should be seeing the same thing
This is on a clean build of master from today (2020-03-30)
![gif](https://user-images.githubusercontent.com/1817032/77894842-c6c4a800-726d-11ea-8b2c-911df64bedd6.gif)

**Comment by martyngigg** [comment]
@DavidFair I am also unable to reproduce this on Ubuntu 18.04 with GNOME on the latest nightly from our apt repos.

**Comment by martyngigg** [comment]
I don't quite understand why it would be Kubuntu-specific though...

**Comment by DavidFair** [comment]
Maybe it's how I'm creating them, I'm holding CTRL and tapping N, without letting go of the CTRL key?

**Comment by ConorMFinn** [comment]
I was doing the same and couldn't recreate it, does Kubuntu handle tabs in some subtly different way?

**Comment by DavidFair** [comment]
Possibly, I guess as the reporter and only replicator it falls on me to investigate

**Comment by martyngigg** [comment]
https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/widgets/codeeditor/multifileinterpreter.py#L67 is where the counting happens. It's not immediately obvious why that's wrong...
