### ISSUE TITLE
Doing a focus in the engineering diffraction interface on Windows in debug causes Mantid to freeze

### ISSUE THREAD

**Issue by PhilColebrooke** [mantidproject/mantid#28455]
Interfaces -> Diffraction -> Engineering Diffraction
Enter Vanadium # 307521, Calibration Sample # 320691, and click Calibrate.
Go to Focus tab, enter Sample Run # 307521, and click Focus.

Only happens on Windows and only with the debug build.

**Comment by DannyHindson** [comment]
Have been able to reproduce this. Mantid takes a v long time writing the sample logs out for some of the logs - this happens in sample_run.getPropertyAsSingleValue in scripts\Engineering\gui\engineering_diffraction\tabs\focus\model.py

There are about 12 logs with more than a million entries in ENGINX00307521.nxs (eg ADC1_0) and these are taking 30-60 seconds each to process.

Will have a look at whether it's possible to speed this up
