### ISSUE TITLE
Also output Batch File name in CanSAS1D and NXcanSAS

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#28458]
Currently SaveCanSAS1D and SaveNXCanSAS write the User File name to the SASprocess field in the metadata.

If the data being output was generated by processing a Batch File we should also write the Batch File name for enhanced traceability.

**Comment by DavidFair** [comment]
Adding some info here so that other devs can pick this up too:

Looking at the source file `SaveCanSas1D2.cpp:215` we save the user file as a term in `SASprocess` whose spec is found here:
http://www.cansas.org/formats/canSAS1d/1.1/doc/element_SASprocess.html

We need to add a new field @smk78 do you have any preference on this XML tag naming since it's effectively free-form?

I'm thinking `batch_file` as follows:

```xml
<SASprocess>
    <term name="user_file">user_file_name.txt</term>
    <term name="batch_file">batch_file_name.csv</term>
```

I'm also not sure if the batch file is added to the logs so we'd need to do that too, but that should be relatively simple from the SANS side

**Comment by smk78** [comment]
I'm happy with that XML tag naming!

**Comment by smk78** [comment]
Looking at the testing I have performed over the last week or so using 5.0.20200909.1539 and 5.0.20200914.1537 I note that not one of the CanSAS1D xml files (I haven't checked the NXcanSAS) contains a batch file entry.

I am attempting to check with the latest nightly, but are we sure this issue was fixed?

**Comment by gemmaguest** [comment]
It's there for me! But I'll double check on Windows.

![image](https://user-images.githubusercontent.com/12895056/93579551-84fff900-f996-11ea-8ccd-d24fc6a22306.png)

**Comment by gemmaguest** [comment]
This is fine for me in the latest Windows nightly build too - both CanSAS1D and NXcanSAS contain `user_file` and `batch_file` entries. I am using the training course loqdemo.

**Comment by DavidFair** [comment]
I've just tested:

- Last nights nightly on Windows / Linux on two different machines
- A latest build of `release-next`

And it seems to be working?

@smk78 is it worth checking that the save is set to file or both and the files aren't existing ones from previous testing?
Otherwise I'm stumped.

**Comment by smk78** [comment]
Well that's odd! @DanielMurphy22 pointed me at your Jenkins server for a 'current' nightly and when I do this
![image](https://user-images.githubusercontent.com/10938679/93587063-2f7d1980-f9a1-11ea-9fe8-46973d7a6cb9.png)
I get this
```
			<name>Mantid generated CanSAS1D XML</name>
			<date>18-Sep-2020 11:19:03</date>
			<term name="svn">5.0.20200917.1709</term>
			<term name="user_file"></term>
			<term name="batch_file"></term>
			<term name="sample_trans_run">108174</term>
			<term name="sample_direct_run">108173</term>
			<term name="can_trans_run">108175</term>
			<term name="can_scatter_run">108177</term>
			<term name="can_direct_run">108173</term>
```
and
```
			<name>Mantid generated CanSAS1D XML</name>
			<date>18-Sep-2020 11:19:03</date>
			<term name="svn">5.0.20200917.1709</term>
			<term name="user_file"></term>
			<term name="batch_file"></term>
			<term name="sample_trans_run">108174</term>
			<term name="sample_direct_run">108173</term>
			<term name="can_trans_run">108175</term>
			<term name="can_scatter_run">108177</term>
			<term name="can_direct_run">108173</term>
```
Here are the User and Batch file I was using
[startup202.zip](https://github.com/mantidproject/mantid/files/5244927/startup202.zip)

What is going on?!

**Comment by smk78** [comment]
Also see https://github.com/mantidproject/mantid/issues/28847

**Comment by smk78** [comment]
> @smk78 is it worth checking that the save is set to file or both and the files aren't existing ones from previous testing?
> Otherwise I'm stumped.

![image](https://user-images.githubusercontent.com/10938679/93589402-a9fb6880-f9a4-11ea-926b-6aa601367451.png)

![image](https://user-images.githubusercontent.com/10938679/93589502-cb5c5480-f9a4-11ea-944b-0b13d04339a5.png)

And the date/SVN in my output above shows you I'm looking at recently generated files!

**Comment by smk78** [comment]
Oooo... this is interesting. You will notice that the reductions above were merged reductions. If I change the User File to one that only reduces the LAB, the User File appears in both the CanSAS1D output and the NXcanSAS!
```
			<name>Mantid generated CanSAS1D XML</name>
			<date>18-Sep-2020 11:51:06</date>
			<term name="svn">5.0.20200917.1709</term>
			<term name="user_file">USER_LOQ_202A_M3_Team_LOQ_8mm_Changer_MAIN_LIN.txt</term>
			<term name="batch_file"></term>
			<term name="sample_trans_run">108176</term>
			<term name="sample_direct_run">108173</term>
			<term name="can_trans_run">108173</term>
			<term name="can_scatter_run">108179</term>
			<term name="can_direct_run">108173</term>
```
But the batch file is still missing.

**Comment by smk78** [comment]
I may have found something.

This latest nightly lets you export the table to a Mantid-generated batch file again. So I did that. Now when I reload that exported batch file it shows up in the files.
```
			<name>Mantid generated CanSAS1D XML</name>
			<date>18-Sep-2020 12:02:47</date>
			<term name="svn">5.0.20200917.1709</term>
			<term name="user_file">USER_LOQ_202A_M3_Team_LOQ_8mm_Changer_MAIN_LIN.txt</term>
			<term name="batch_file">exported_batch_file.csv</term>
			<term name="sample_trans_run">108176</term>
			<term name="sample_direct_run">108173</term>
			<term name="can_trans_run">108173</term>
			<term name="can_scatter_run">108179</term>
			<term name="can_direct_run">108173</term>
```
unless you do a merged reduction
```
			<name>Mantid generated CanSAS1D XML</name>
			<date>18-Sep-2020 12:06:26</date>
			<term name="svn">5.0.20200917.1709</term>
			<term name="user_file"></term>
			<term name="batch_file"></term>
			<term name="sample_trans_run">108176</term>
			<term name="sample_direct_run">108173</term>
			<term name="can_trans_run">108173</term>
			<term name="can_scatter_run">108179</term>
			<term name="can_direct_run">108173</term>
```
Arrgghhh.

**Comment by smk78** [comment]
Here are the two Batch Files I was using (you have the two User Files in the earlier upload). Why are these causing different behaviour in the output fields when both load and Mantid will process both?
[startup202-b.zip](https://github.com/mantidproject/mantid/files/5245136/startup202-b.zip)

**Comment by DavidFair** [comment]
So the difference is that your using a custom mask file - this is why the batch file and user file isn't being copied through (an easy fix for the same reason as the 2D button)

I'm just looking at how `merged` interacts....

**Comment by smk78** [comment]
Testing Nightly 5.0.20200922.1715 this seems to be working. Also tested the loading of the CanSAS1D (XML) and NXcanSAS (HDF5) output with this field in SasView 5.0.3. They load and display correctly.
