### ISSUE TITLE
Indirect Data Analysis minor fixes

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#28484]
The following have been identified as issues still remaining with the Indirect Data Analysis GUI.

MsdFit
====
- [x] msdFit - default values not taken from data
- [x] Msd, Beta & Sigma parameters need constraint >0
- [x] Change ws names to eg runname_msdFit_seqGauss_s0...

ConvFit
=====

- [x] Not all functions in QE folder
- [ ] Check that WS number & Q change when spectrum changed
- [ ] Lor doesn't get res from IPF
- [ ] Carry over Lor1 paras when changing to 2 Lor?
- [x] Delta centre not displayed in small window
- [x] Delta height constraint >0
- [x] Check all functions for constraint
- [x] ws names to include seq/sim
- [x] Make number of Lor a spinner

IQTFit
====
- [ ] Use same method to estimate default parameters as used by F(q) and Msd fitting tabs 

FqFit
===
- [x] constraints on all
- [x] better default values?
- [ ] WS is renamed _FWHM which is confusing
- [ ] Allow functions to take FWHM

**Comment by gemmaguest** [comment]
Re-opening because I believe the PR was only a partial fix

**Comment by Harrietbrown** [comment]
Not stale
