### ISSUE TITLE
Move all GUI code out of scripts and to the `qt` directory

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#28493]
Major improvement will be reducing running system tests on GUI-only changes.

**Comment by martyngigg** [comment]
It would be nice to implement some or all of the [original design](https://github.com/mantidproject/documents/blob/master/Design/Workbench/design-classes.md) that provided a common interface and startup file structure for all of the Python interfaces in workbench.

**Comment by gvardany** [comment]
Inventory of python plugin interfaces can be found [here](https://docs.google.com/spreadsheets/d/1kNR-nEGEyHbPdGheW-xOn5elNlYvPhI18lqm83xdC_8/edit#gid=0)

**Comment by peterfpeterson** [comment]
This was done during the maintenance period after the 6.2 release.
