### ISSUE TITLE
The ResimulateTracksForDifferentWavelengths property in the MonteCarloAbsorption algorithm has no impact.

### ISSUE THREAD

**Issue by mattgriffin-stfc** [mantidproject/mantid#28504]
### Expected behavior
Setting the `ResimulateTracksForDifferentWavelengths` property in the `MonteCarloAbsorption` algorithm to true should generate tracks for every wavelength.

### Actual behavior

The option has no effect, tracks are not re-simulated and the first generated for a wavelength is always reused.

### Steps to reproduce the behavior

This is due to a hard-coded `false` value on lines 263-266 in [MonteCarloAbsorption](https://github.com/mantidproject/mantid/blob/master/Framework/Algorithms/src/MonteCarloAbsorption.cpp). 
```
// Configure strategy
MCAbsorptionStrategy strategy(
    *beamProfile, inputWS.sample(), efixed.emode(), nevents, nlambda,
    maxScatterPtAttempts, useSparseInstrument, interpolateOpt, false, g_log);
```
Replacing false with the option value (`resimulateTracksForDiffWavelengths`) fixes the problem.
```
// Configure strategy
MCAbsorptionStrategy strategy(
    *beamProfile, inputWS.sample(), efixed.emode(), nevents, nlambda,
    maxScatterPtAttempts, useSparseInstrument, interpolateOpt, resimulateTracksForDiffWavelengths, g_log);
```

**Comment by DannyHindson** [comment]
Thanks a lot @mattgriffin-stfc for spotting this. I've just made the change you suggested to fix this (see pull request #28573). Needs to go through our peer review process before it ends up in the nightly build
