### ISSUE TITLE
Replace SANS Masking Start / Stop pair of lists with list of pairs

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#28510]
Currently the `StateMaskDetectors.py` stores masking values with ranges as two integers representing the start and stop value.

This relies on the position of said values not moving in the list, and requires us to regenerate at the opposite end. Instead we should replace fields like `range_horizontal_strip_start` and `range_horizontal_strip_stop` with a list of tuples that represent the same thing

**Comment by smk78** [comment]
Would this make processing of masks run faster (thumbs up) or slower (thumbs down)?

**Comment by smk78** [comment]
Re-opening this as it was intended as a reminder to the developers.
