### ISSUE TITLE
Make Q values update correctly in FunctionBrowser

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#28529]
Currently Q values do not update in the function browser when the dataset being observed is changed. This is due to a the FunctionBrowser not handling attritubute updating. This needs to be resolved so the Q values used are resolved correctly.

**Comment by Harrietbrown** [comment]
an example of how to see where this is coming from:

go into conv fit and load data
fit with Tashirawater
show full function
see the Q value and workspace index in the fit browser is wildly off

**Comment by StephenSmith25** [comment]
This should wait until I've made the changes to setting/getting attributes in composite function. Also, I've already made a start on this last sprint and got it so it shows the correct Q Values, so if you're picking this up I can show you where I got.

**Comment by Harrietbrown** [comment]
Thanks, I am just going through issues to get a list of urgent things to fix before the maininance work.
