### ISSUE TITLE
Fix data loading in FQ fit

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#28527]
Currently the way data is loaded in FQ fit is inconsistent and confusing.

When the data is loaded it is converted from FWHM to HWHM behind the scenes. It is also not possible to load more than one spectra from a single workspace in multiple input mode. 

This leads to a secondary issue where the names for all output workspaces have HWHM maxima appended as this is the workspace actually fitted but this is confusing when an EISF fit is done.

**Comment by AnthonyLim23** [comment]
@Mantid-Matthew and @StephenSmith25 what would be the desired behaviour? 

To convert to a FWHM and append that to the name?
