### ISSUE TITLE
zoom in 3D plots

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#28534]
zooming in on a 3D plot causes the surface to spill over the axis. 

![3dplot](https://user-images.githubusercontent.com/25006392/79763628-3df4d580-831c-11ea-9639-f6749a0cc7cc.jpg)

**Comment by SpencerHowells** [comment]
The same thing happens when the axis limits are reduced.

**Comment by DanielMurphy22** [comment]
In #28632 zooming in on 3D plots was disabled. The axes limits can still be altered in the double-click menus and figure options. If the limits overspill was handled correctly, I would argue this issue should be closed.

Oddly, there is no overspill for surface plots, **but it is not handled correctly for wireframe plots.**
