### ISSUE TITLE
NaN's in sample logs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#28535]
I have been told that if a sample log contains a NaN this can causes problems when loading. I have been told of an error that says

"format of file not supporting NaN's"

We should talk to Freddie about this,

**Comment by NickDraper** [comment]
So i edited a nexus file to put a NaN into the log values of a few logs
``` python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
import h5py


root = r"/raw_data_1/selog"
with h5py.File(r"E:\buildarea\ExternalData\Testing\Data\UnitTest\ENGINX00228061_log_alarm_data.nxs",
            "a") as f:
                selogs = f[root]
                log_index = 0
                new_values = np.arange(3.0,8.0,2.0)
                for log in selogs:
                    if log.startswith("cryo"):
                        print(log)
                        #open the log values
                        value_log = f["{0}/{1}/value_log".format(root,log)]
                        value_array = f["{0}/{1}/value_log/value".format(root,log)]
                        new_values[0] = np.nan
                        value_array[...] = new_values
```
Verified the file in HDFView.

This seems to load fine into Mantid workbench.  the value in the log viewer is ok, and the print to the log on double click works as well.

![image](https://user-images.githubusercontent.com/1017173/81689070-e5fc4b00-9451-11ea-8b3a-53046ff547b8.png)
