### ISSUE TITLE
Indirect workflows for sample changer

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#28533]
We should investigate how to improve the indirect workflow and allow for

groups
calibration
resolution

**Comment by SpencerHowells** [comment]
Rob & I worked it all out. Why resolution?

**Comment by AnthonyLim23** [comment]
this is so we can make new workflow algorithms for the full analysis. Then the GUI can just run one algorithm depending on the options selected.

**Comment by SpencerHowells** [comment]
This routine should only do a reduction. Any fitting should ALWAYS we done separately, NOT as a black box.

**Comment by AnthonyLim23** [comment]
it will be a different routine.
