### ISSUE TITLE
Indirect fitting functions missing

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#28530]
Some of the Indirect fitting functions are missing from the function browser. Investigate where they have gone

**Comment by AnthonyLim23** [comment]
@Mantid-Matthew could we have some more detail please?

**Comment by Mantid-Matthew** [comment]
There are some functions which are not appearing correctly in the GUI. Talk to Spencer Howells to find out which ones.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 These are complicated functions which Stephen looked at. Needs to be re-thought.

**Comment by AnthonyLim23** [comment]
@SpencerHowells do we want to keep this open or do we know what to do next?

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Please keep open. I have some ideas to discuss.

**Comment by AnthonyLim23** [comment]
@SpencerHowells could you arrange a time to discuss your ideas?

**Comment by Harrietbrown** [comment]
The three missing functions are DiffSphere, DiffRotDiscreteCircle, IsoRotDif
These are imutable composit functions, that can not be edited, and therefore can not be added to the browser. A solution would be to make a new function that simply call this composit.
