### ISSUE TITLE
Add Tests to Mainwindow

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28542]
The mainwindow class in workbench is getting large, without any testing. 

Adding testing here is a good bug prevention task to be tackled in either Maintenance or else developer time which is "sacrificed" to this end.

**Comment by martyngigg** [comment]
The first task here is to identify the most sensible set of unit tests to add around `mainwindow.py`. We then need to decide how to carve up the functionality into separate classes/modules. Tasks here are to do some up front thinking and then come chat with @martyngigg.
