### ISSUE TITLE
Add Automated Test for launching MantidWorkbench

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28544]
In line with #28543, running a test which simply checks that Workbench can open and close correctly in each OS would be very valuable.

It would make most sense to have this as a system test.

**Comment by DanielMurphy22** [comment]
We should look at adding some sort of startup test for Workbench in the system tests. We'll just need to make sure we can easily disable them for framework only builds.

_Originally posted by @martyngigg in https://github.com/mantidproject/mantid/pull/28048#issuecomment-590387119_

**Comment by martyngigg** [comment]
We currently have [GUIStartupTest.py](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/analysis/GUIStartupTest.py). This needs to be modified, renamed to `WorkbenchStartupTest.py` and be able to function on each platform.
