### ISSUE TITLE
Investigate Converion of octree to quadtree in NSXTool for eventual use in Mantid

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#28558]
Recent work has generalise the peak finding in NSXTool to work for TOF-integrated detector banks, however the octree code that is used to detect collisions with nearest neighbours is broken and needs to be fixed.

**Comment by DannyHindson** [comment]
This is paused pending the outcome of the machine learning pilot into peak finding on WISH
