### ISSUE TITLE
Problems with the workbench log viewer

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28569]
1. Cannot read micro sec log units and generates warnings #28623
1. We should have an option to show both the filtered and unfiltered data #28622
1. If you move down the table with the down key then the graph and stats do not update #28619
1. duration is 0 based to the start of the file, not the start of the run (compare to mantidplot) #26222 is related (on investigation, this works fine as long as the log has values before the start of the run)
1. Collapse the plot tab if the workspace is not event and the log is not time series. (from Gagik) #28634
1. Highlight data with invalid value filters #28631
1. an unhandled exception occurs when the figure options are clicked on a plot created by double clicking from the sample logs #27770 
1. scripts generated from plots extracted from the sample logs do not run  (axes.plot is missing ExperimentInfo=ts_logs.run(), FullTime=False, LogName="C9_SLAVE_FREQUENCY") #28635

**Comment by NickDraper** [comment]
Handy file for testing multi-period data:
- POLREF00004699.nxs

**Comment by NickDraper** [comment]
> If you could add this, would be awesome:
> 5) Collapse the plot tab if the workspace is not event and the log is not time series.

@gvardany Can I just check what you are after here?  Do you want:
1. The whole stats and graph section to be hidden if none of the logs are time series
1. The graph to disappear and the stats section expand if a selected log is not time series
1. Both the graph and stats section to disappear if the selected log is not time series

**Comment by NickDraper** [comment]
Note to self:
For colouring the cells of the logs table
``` python
from qtpy.QtGui import QColor
from qtpy.QtCore import Qt

            item.setData(QColor(Qt.red), Qt.BackgroundRole)
            item.setData(QColor(Qt.blue), Qt.ForegroundRole)

#or from the model
model.setData(model.index(0,0), QColor(Qt.red), Qt.BackgroundRole)
```

**Comment by NickDraper** [comment]
@gvardany 
Looking at this file as an example UnitTest/ILL/D22/192068.nxs
I think that option 1 would make the most sense.
![image](https://user-images.githubusercontent.com/1017173/80804983-ac545600-8bae-11ea-8301-6b59b7be0942.png)

**Comment by gvardany** [comment]
And what if just one log is time series? Will they reappear when selecting that log? (D22 does not scan but the scanning detectors have one or two series logs).

**Comment by NickDraper** [comment]
> And what if just one log is time series? Will they reappear when selecting that log? (D22 does not scan but the scanning detectors have one or two series logs).

Take a look in #28634, I've done it at the moment that the presence of the stats and graph section will disappear if none of the logs would benefit from it, so it only one or two will it will be present.
