### ISSUE TITLE
New sliceviewer: Line plots don't quite line up with data when zoomed in

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#28579]
### Expected behavior

Peak in line plot should line up with center of data pixel.

### Actual behavior
See image discovered in #28506.

![image](https://user-images.githubusercontent.com/1017173/79441537-46bd7280-7fcf-11ea-89b1-e192dd46f181.png)

### Steps to reproduce the behavior

Use script in referenced pull request and zoom to location in image.

### Platforms affected
All

**Comment by RichardWaiteSTFC** [comment]
During testing of #28653 it was found that the intensity of the bin doesn't match the intensity inferred from the colorscale (see screenshot) which looks like it is related to this issue
![image](https://user-images.githubusercontent.com/55979119/81315949-e1ffb000-9082-11ea-8727-323c4b84f0a6.png)
