### ISSUE TITLE
Update SaveNXcanSAS & LoadNXcanSAS to NXcanSAS v1.1

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#28586]
### Nature of the issue
The NXcanSAS v1.0 definition requires a field called _radiation_ in its use of the (optional) NeXus NXsource group. No such field exists in the NXsource definition, although there is a field _type_ which provides the same information.

Since there exist data files written to the NXcanSAS v1.0 specification, it is too late to change the NXcanSAS definition.

### Agreed Resolution
It is agreed to mark the _radiation_ field as deprecated.

This paragraph is to be added to the NXcanSAS documentation for the radiation field:

> This field contains a value from either the NXsource/probe or NXsource/type field. Thus, it is redundant with existing NeXus structure.

Existing data files with the _radiation_ field will not be changed but data files written after this revision should use the _probe_ and/or _type_ fields instead.

This change will be formally identified as NXcanSAS v1.1

### Further Information
https://github.com/nexusformat/definitions/issues/765

**Comment by smk78** [comment]
Attachment includes a 1D and 2D example of data written in NXcanSAS v1.1 (generated by SasView developer build of ticket1527 branch).

[sasview-nxcansas-v1p1-examples.zip](https://github.com/mantidproject/mantid/files/4557995/sasview-nxcansas-v1p1-examples.zip)

**Comment by gemmaguest** [comment]
Related to #18336

**Comment by gemmaguest** [comment]
We will drop support for writing v1.0 but keep ability to read both
