### ISSUE TITLE
Colorfill plot: x label cut off

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28608]
**Original reporter:** SANS group / rob Dalgliesh

### Expected behavior
WB plots should open well scaled
### Actual behavior
This can be hard with mpl
The x label was cut off in Windows 10 for the label q(A^-1)
### Steps to reproduce the behavior
I think this is most liekly to find for colorfill plots on Windows
### Platforms affected
WB 5.0

**Comment by NickDraper** [comment]
@DanielMurphy22 I'm having trouble reproducing this with the current code, could you have a go as well and see if you can come up with an example?

**Comment by DanielMurphy22** [comment]
> @DanielMurphy22 I'm having trouble reproducing this with the current code, could you have a go as well and see if you can come up with an example?

I've had a quick go with no luck. I wonder if this depends on the size of your screen. I had thought 3D plots would be at more risk for this sort of thing but the one's I've checked are fine. Colorfill plots still have the diagonal axis numbers which I remember they disliked.

**Comment by NickDraper** [comment]
Yes, the diagonal labels are on a different issue.  I even tried scaling up the values in the X axis but still could not reproduice this.
![image](https://user-images.githubusercontent.com/1017173/83257800-0136bc80-a1ad-11ea-9cef-2f88c40dbc7a.png)
![image](https://user-images.githubusercontent.com/1017173/83257809-0562da00-a1ad-11ea-83c0-b90b2a917e45.png)

**Comment by NickDraper** [comment]
Ah, it looks like there is a sweet spot, 
![image](https://user-images.githubusercontent.com/1017173/83257866-21667b80-a1ad-11ea-8bdd-c7ea337429c8.png)
but this would be solved by the labels being horizontal.

**Comment by NickDraper** [comment]
Should be solved by #28601
