### ISSUE TITLE
Plot Background Colour

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28607]
**Original reporter:** SANS group / Steve King

In MantidPlot you could change the background colour of a plot, this should be in WB.

You can currently do something like this with plot.style.use('dark_background')

This may involve mpl rcparams and may be leaning towards a Style file #27535

**Comment by ConorMFinn** [comment]
Discussions with the scientist that requested this addition sugguest that the option should be added as part of the figure options for individual plots.
