### ISSUE TITLE
Zoom Tool Right-click WB

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28610]
**Original reporter:** SANS group / Rob Dalgliesh

### Expected behavior
In WB, right-clicking on the plot should reset the axes (same as home button)
### Actual behavior
Currently with the zoom toolbar button selected, left-click and drag zooms in, right-click and drag zooms out. right-click and NO drag does nothing --> it should reset the axes
### Platforms affected
WB 5.0

**Comment by martyngigg** [comment]
We should make sure this also works consistently with the sliceviewer as the sliceviewer cannot currently zoom out in steps at all and needs to. We want the code to support this to be in a mixing style class that can be applied to any Axes instances.
