### ISSUE TITLE
Unicode WS axis labels Hard Crash

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28654]
**Original reporter:** [James Lord](https://forum.mantidproject.org/t/unicode-in-workspace-axis-labels/615)

### Expected behavior
Since Migration to Python 3, the code below should work.
### Actual behavior
It runs but you get a very hard crash of Mantid when you "Show Data"
### Steps to reproduce the behavior
Run this code:
```
W=CreateWorkspace(DataX=[0,1,2],DataY=[3,7,5],DataE=[0.2,0.3,0.1],NSpec=1)

lbl=W.getAxis(0).setUnit("Label")
lbl.setLabel("Time",u"\u00B5s") # microseconds
W.setYUnitLabel(u"Distance in \u00C5") # Angstrom symbol
```
Now "Show Data" of the Workspace
Many Many Error reporters...!
### Platforms affected
I found this on Workbench 5.0 on Mac, but presumably effects all platforms

**Comment by thomashampson** [comment]
It doesn't crash on Windows, but the micro symbol doesn't display properly in the table
![image](https://user-images.githubusercontent.com/8058899/112612652-13a67480-8e17-11eb-8dea-2442dfe27ed0.png)

**Comment by thomashampson** [comment]
Although there is a pending pull request with a fix for this problem, in the meantime a small modification of the script will circumvent the issue:
```
from mantid.simpleapi import *
from mantid.kernel import UnitLabel

W=CreateWorkspace(DataX=[0,1,2],DataY=[3,7,5],DataE=[0.2,0.3,0.1],NSpec=1)

lbl=W.getAxis(0).setUnit("Label")
lbl.setLabel("Time", UnitLabel("microseconds", "\u00B5s", "\u00B5s")) # microseconds
W.setYUnitLabel(u"Distance in \u00C5") # Angstrom symbol
```
