### ISSUE TITLE
Capture Stacktrace for C++ segfault

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28662]
The stacktrace in Mantid Error reports has been very useful. We should add this boost library: https://www.boost.org/doc/libs/1_65_1/doc/html/stacktrace.html to be able to grab a stacktrace from a segfault in a C++ library

**Comment by martyngigg** [comment]
Another option, on Linux, to think about including is to somehow have the error reporter capture the output from the workbench process that gets written to dmesg. This would allow us to capture other things like errors from the OOM killer.
