### ISSUE TITLE
Algorithm Dialog functions should be removed from Autocompletion

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28669]
When converting the Python In Mantid Course, I have been removing the Algorithm Dialog references, but Algorithm Dialogs are still part of Autocompletion.

Type `LoadDia` into Workbenhc script editor and see that LoadDialog is recommended! 

Workbench 5.0
This should probably be fixed for 5.2, when MantidPlot is deprecated.

**Comment by martyngigg** [comment]
We should do this now as the functions require MantidPlot.

They need to be removed from `mantid.simpleapi` and then they will be removed from the autocomplete.

**Comment by martyngigg** [comment]
There are also some handwritten functions such as `def LoadDialog` that will also need to be removed and some unit tests will need updating to removing checking the functions exist.
