### ISSUE TITLE
SliceViewer: Dynamic rebinning on zoom

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28689]
When a user zooms into a MD workspace it should dynamically rebin the view to reveal more data, similar to what was done in the mantidplot sliceviewer.

Some of the options for the old sliceviewer and rebinning are not in scope for this issue:
1. Turning on and off rebinning (just have it always on for md workspaces)
1.  rebin this slice now button
1. Freezing a region at a specific binning

**Comment by martyngigg** [comment]
This should fix #28579
