### ISSUE TITLE
Rewrite the Sample Transmission Calculator for the workbench

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28691]
This is a pretty simple GUI, rewrite it in python following MVP with tests
![image](https://user-images.githubusercontent.com/1017173/82057297-0844d180-96bb-11ea-8728-091a86fc412e.png)

**Comment by AnthonyLim23** [comment]
@NickDraper the documentation suggest the GUI is a bit more complex then the image you have https://docs.mantidproject.org/v3.7.1/interfaces/SampleTransmissionCalculator.html
