### ISSUE TITLE
Save1DPlot-alg legend option

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28724]
after testing pr: #28716 

### Expected behavior
As you can set the SpectrumNames as an option parameter, you should be able to have a legend in the output plot.
### Actual behavior
No legend possible as far as I can see.
### Steps to reproduce the behavior
Set your desktop as the default save directory in Manage User Directories
```
ws = Load('MAR11015')
SavePlot1D(ws, 'plot_image', SpectraList = [0,1,2,3,4,5,6,7,8,9,10,11,12], SpectraNames = ['A','B','C','D','E','F','G','H','J','I','K','L','M'], PopCanvas = True, YLabel = 'Hello / Greet')
```

A fix here should really implement a legend = True/False parameter to choose.

### Platforms affected
All since 4.0 at least

**Comment by PhilColebrooke** [comment]
Currently there's a check that the number of spectra being plotted is less than 10, in which case a legend is drawn:
https://github.com/mantidproject/mantid/blob/7f98855f630e7f101c82df3a405e15780c5acadc/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SavePlot1D.py#L268

I'm guessing that having a legend with more than ten entries means it no longer fits on the plot. You are correct that if you provide SpectraNames they aren't used though.
