### ISSUE TITLE
FDA useful

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#28742]
We want to make FDA useful again.

1. Plot will show time domain data on home and grouping tabs
2. Plot will show phasequad once a phasequad is made
3. Plot will show FFT/Maxent for transform, fitting and results
4. Fitting is only for frequency and we will not need TFAsymmetry mode

**Comment by Mantid-Matthew** [comment]
After a meeting on the workflows which need to be supported here the following clarifications and requirements are appropriate. This describes the normal workflow for a single run.

- All of the data from a single run will be turned into a single maxent or FFT workspace. For simplicity these two approaches should be treated as interchangeable with identical options for inputs as far as possible. 
- Currently Maxent does not have any options to specify the groups you wish to split the data into before performing the maxent calculation. This option is important for noisy data which muon data normally is so should be added.
- Currently the only way to perform a FFT transform on the whole data set is to create a phasequad workspace first. Whether it is possible to perform an FFT analysis on all groups simultaneously needs to be investigated.
- The phase table name should have the groups used to calculate it removed. As this information isn't relevant after the calculation and causes ongoing confusion. There is a need to distinguish between different periods however.
- After performing a transformation into frequency space a common next step is to do some peak shape analysis. This cannot currently be achieved in the GUI. This most likely requires the addition of a peak shape analysis tab but further requirement gathering is required here.
- For FFT on the transform and fitting tabs display the modulus of the FFT by default. The y label should be amplitude and it should re-scale.
- For Maxent on the transform and fitting tabs should display the field. The y label should also be amplitude.
