### ISSUE TITLE
MuonAnalysis ties not respected

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28770]
**Original reporter:** James Lord

Ties are not respected in the case outlined below

### Steps to reproduce the behavior
- Open Workbench
- Open Muon Analysis Interface and load EMU62260
- In the fitting tab add the functions “FlatBackground” and “ExpDecayOsc”. 
- set f1.Lambda to 0 and then fixed it.
- Run the Fit and notice that the tie was not obeyed, but reset to the newly fit value!
### Platforms affected
Workbench Nightly 5.0.20200522.1617

**Comment by AnthonyLim23** [comment]
it seems to work for simultaneous fit. If you then go back to single fit it works too
