### ISSUE TITLE
Harmonise Masking Approaches, removing reversible masking

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28776]
The cunfusion caused by having two masking approaches was discussed at the TSC 02/06/2020, and it was agreed that we should harmonise on the more widely used non-reversible masking.  Please see the minutes for more details.

The tasks in this issue are:
1. Check with the ESS and ILL whether this will cause problems as they were not present at the meeting. (@gvardany , @SimonHeybrock please let me know if this will cause problems with your established workflows).
1. Adjust MaskDetectorsIf and MaskInstrument to clear the data after masking (update the docs too)
1. Remove the ClearMaskedDetectors algorithm.

**Comment by gvardany** [comment]
This is exactly how it should be. If one needs to undo the masks, he has to start from raw data again. I'd just add a point that maybe in the dev-docs somewhere we should make it clear that at least any new C++ algorithm must respect both detector and bin masks, by checking their flags.

**Comment by SimonHeybrock** [comment]
> The tasks in this issue are:
> 
>     1. Check with the ESS and ILL whether this will cause problems as they were not present at the meeting. (@gvardany , @SimonHeybrock please let me know if this will cause problems with your established workflows).
> 
>     2. Adjust MaskDetectorsIf and MaskInstrument to clear the data after masking (update the docs too)
> 
>     3. Remove the ClearMaskedDetectors algorithm.

I am not aware of problems with current workflows (and we will mostly be using scipp anyway).

To add to your list:
- LoadNexusProcessed
- Any other load algorithms for file types that support masks.
