### ISSUE TITLE
Instrument view: Negative values not displayed

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28788]
**Original reporter:** James Lord

### Expected behavior
The data (even negative) is represented by the colorbar
### Actual behavior
Any detectors with negative data values are greyed out, despite the colorbar trying to fit the correct range.
### Steps to reproduce the behavior
```
LoadMuonNexus(Filename=r'\\chronus\data\CHRONUS00009705.nxs', OutputWorkspace='CHRONUS00009705.nxs', DeadTimeTable='CHRONUS00009705.nxs_deadtime_table', DetectorGroupingTable='__notUsed')
RenameWorkspace(InputWorkspace='CHRONUS00009705.nxs', OutputWorkspace='Raw1')
 
LoadMuonNexus(Filename=r'\\chronus\data\CHRONUS00009706.nxs', OutputWorkspace='CHRONUS00009706.nxs', DeadTimeTable='CHRONUS00009706.nxs_deadtime_table', DetectorGroupingTable='__notUsed')
RenameWorkspace(InputWorkspace='CHRONUS00009706.nxs', OutputWorkspace='Raw2')
 
Minus(LHSWorkspace='Raw1', RHSWorkspace='Raw2', OutputWorkspace='Subtracted')
```
Right-click and Show Instrument on the `Subtracted` workspace

### Platforms affected
Found on Workbench 5.0.20200522.1617

**Comment by NickDraper** [comment]
Looking into this:  The grey colouring is due to this code:
InstrumentRenderer.cpp line366:
``` C++
  for (size_t det = 0; det < counts.size(); ++det) {
    if (!isMasked(det)) {
      const double integratedValue(counts[det]);
      if (integratedValue > -1) {
        const auto &color = rgba[det];
        m_colors[det] =
            GLColor(qRed(color), qGreen(color), qBlue(color),
                    static_cast<int>(255 * (integratedValue / vmax)));
      } else
        m_colors[det] = invalidColor;
    } else {
      m_colors[det] = maskedColor;
    }
  }
```

**Comment by NickDraper** [comment]
Just need to find out why -ve values are considered invalid?

**Comment by NickDraper** [comment]
Is it only this code?
InstrumentActor.cpp line 437:
```C++
double InstrumentActor::getIntegratedCounts(size_t index) const {
  auto i = getWorkspaceIndex(index);
  if (i == INVALID_INDEX)
    return -1.0;
  return m_specIntegrs.at(i);
```

**Comment by NickDraper** [comment]
As a quick and dirty brutal test: I commented out the check if the value was negative in the InstrumentRenderer about, and the result is that it can show negative values:
![image](https://user-images.githubusercontent.com/1017173/83772759-9dfccc80-a67b-11ea-9d05-9f6d2b0fa6a1.png)

**Comment by NickDraper** [comment]
The pick miniplot does not work though:
![image](https://user-images.githubusercontent.com/1017173/83773206-28453080-a67c-11ea-9776-ce670be19c22.png)
