### ISSUE TITLE
Bug in SofQW3 / Rebin2D

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#28812]
**Original reporter:** ISIS/Tatiana

### Expected behavior

Rebinning a workspace with `Rebin2D` is consistent in both the calculated intensity (y-values) and errors.

### Actual behavior

Errors from successive rebinning tends to zero.

### Steps to reproduce the behavior

Run this script:

```
Load(Filename='LET36360_1.05meV_rings.nxspe', OutputWorkspace='LET36360_1.05meV_rings')

wth = ConvertSpectrumAxis('LET36360_1.05meV_rings', Target='Theta')
w2d = Rebin2D(wth, '-0.4, 0.005, 0.4', '10, 1, 130', UseFractionalArea=True)
w1d1 = Rebin2D(w2d, '-0.4, 0.005, 0.4', '10, 120, 130', UseFractionalArea=True)
w1d2 = Rebin2D(wth, '-0.4, 0.005, 0.4', '10, 120, 130', UseFractionalArea=True)
print(np.min(w1d1.readE(0)))
print(np.min(w1d2.readE(0)))
print(np.median(np.abs(w1d1.readY(0) - w1d2.readY(0))))

wqw = SofQW3('LET36360_1.05meV_rings', QAxisBinning='0, 0.05, 1.4', Emode='Direct')
w1d3 = Rebin2D(wqw, '-0.4, 0.005, 0.4', '0, 1.4, 1.4', UseFractionalArea=True)
w1d4 = SofQW3('LET36360_1.05meV_rings', QAxisBinning='0, 1.4, 1.4', EAxisBinning='-0.4, 0.005, 0.4', Emode='Direct')

print(np.min(w1d3.readE(0)))
print(np.min(w1d4.readE(0)))
print(np.median(np.abs(w1d3.readY(0) - w1d4.readY(0))))
```

`w1d1` and `w1d2` should be identical. Whilst the signal is, the errors are vastly different.
Likewise, `w1d3` and `w1d4` should be similar (not quite identical because `SofQW`) and again the signal matches closely but the errors are widely off. The larger error value is the correct value. The smaller error from the multiple rebinning is incorrect. 

If this script is run under Mantid 5 or nightly, the following output is obtained:

```
0.02900204863863185
2.6077565358139827
3.0730973321624333e-12
0.04905749422459495
2.6269120264368175
0.00033740675986315694
```

If this script is run under Mantid 4.2, the following output is obtained:

```
2.60775653581
2.60775653581
2.95452551313e-12
2.62696776745
2.62691202644
0.000337406759867
```

This is the correct behaviour.

The datafile can be obtained here: 
[LET36360_1.05meV_rings.zip](https://github.com/mantidproject/mantid/files/4753551/LET36360_1.05meV_rings.zip)

But the behaviour should be the same for any 2D workspaces.

### Platforms affected

All.

**Comment by martyngigg** [comment]
Thanks for reporting this, Duc. We'll take a look.
