### ISSUE TITLE
Colorfill imshow data flipped?

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28811]
Found for scripting **contour plots** when updating PythonInMantid course.

### Expected behavior
Colorfill and Imshow methods should produce similar looking plots, and if not then why?
### Actual behavior
Currently there seems to be a flip top-bottom (reverse order of the spectra)
### Steps to reproduce the behavior
Run this script:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
nrows, ncols = 5, 5
signal = np.arange(0,nrows*ncols)
x = np.arange(0,2*ncols+1,step=2)

data = CreateWorkspace(DataX=x, DataY=signal, NSpec=nrows,UnitX='TOF')
figC,axC = plt.subplots(subplot_kw={'projection':'mantid'})
c=axC.imshow(data)
axC.set_title('Imshow')
cbar=figC.colorbar(c)
plt.show()
```
Then right-click and produce a colorfill of the workspace 'data'.

It seems that imshow may be "wrong" here, and that pcolormesh gets the same answer as using the Workbench GUI.

### Platforms affected
Workbench 5.0.20200529.1413, Release 5.0 and 4.2

![Screenshot 2020-06-09 at 15 26 12](https://user-images.githubusercontent.com/55980573/84159969-95363d00-aa65-11ea-825b-5bccf536d881.png)

**Comment by PhilColebrooke** [comment]
When a colorfill plot is created by right-clicking on a workspace and doing Plot -> Colorfill, the `imshow` function is called with the argument `origin='lower'`:
https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/plotting/functions.py#L245

When you do `ax.imshow` in a script without specifying the value for `origin`, the default value of `'upper'` is used.

This is why the two plots are flipped; the one created from a script has the origin in the top-left corner of the axes and the other in the bottom-left.
