### ISSUE TITLE
Time conversion from simple string to ISO in LoadNexusLogs

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#28821]
### Expected behavior

Provide `Types::Core::DateAndTime` with correct time format, e.g. `ISO8601` when setting start and end time of a run in `LoadNexusLogs::readStartAndEndTime`. 

### Actual behavior

Time is read in any format and validated in `Types::Core::DateAndTime` . If the format that is not either `ISO8601` or `POSIX`, but dd-MMM-yy hh:mm:ss used in ILL NeXus files, an error is raised.

### Steps to reproduce the behavior

Run `LoadNexusLogs` algorithm on ILL data, e.g. `ILL/D7/418000.nxs` available in unit tests data.

### Platforms affected

All platforms.

**Comment by SpencerHowells** [comment]
@darominski we are seeing a similar problem at ISIS
