### ISSUE TITLE
Legend Font Size Setting

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28851]
**Original reporter:** @smk78 Steve King

The font size on plot legends can be too large. It is currently set to 10, but it was suggested that 8 would work better. This can be changed in the plot options menu, but for doing so for every plot could become annoying.

To solve this issue: 
- Add an entry to File > Settings > Plots for Legend Font Size. 
- As a compromise, this should be preset to 9.
- make sure this works in harmony with the figure options menu from plots.

**Comment by smk78** [comment]
I really do mean change it to 8. As 9 is still quite big as this shows!
![image](https://user-images.githubusercontent.com/10938679/85392138-09cbaa00-b543-11ea-81fb-c09a8d70b96c.png)
