### ISSUE TITLE
Make Indirect Corrections UI work with new PaalmanPingsMonteCarloAbsorption algorithm

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#28855]
The Indirect Correction user interface has a tab called "Calculate Monte Carlo" that currently calls the CalculateMonteCarloAbsorption algorithm. This algorithm has been superseded by the PaalmanPingsMonteCarloAbsorption algorithm. This task is to update the UI to move over to the new algorithm.

As discussed with Spencer

**Comment by AnthonyLim23** [comment]
can we have a chat about this?

**Comment by AnthonyLim23** [comment]
Looks like the new alg has some new properties:
```
NumberOfWavelengthPoints
```

The old GUI has the following properties, but the new one does not:
```
SparseInstrument
NumberOfDetectorRows
NumberOfDetectorColumns
ContainerRadius
```

**Comment by AnthonyLim23** [comment]
its ok to swap out
