### ISSUE TITLE
The sliceviewer should not plot monitors

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#28894]
Just like the colorfill plots now exclude monitors, so should the sliceviewer, to be consistent.

**Comment by NickDraper** [comment]
@alicerussell1 Will this be sorted with the work you have been doing in consolidating the colour fill and slice viewer.

**Comment by alicerussell1** [comment]
Yes it should be fixed by #28924 - I'll leave the issue open until this is finished so I remember to check this.

**Comment by alicerussell1** [comment]
Fixed by #28924
