### ISSUE TITLE
Eng Diff UI fitting exporting and loading fit results in .hdf5

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#28942]
As a user I want to be able to save fits (and meta data) to file and have the ability to load these fits in to use as an initial guess for subsequent fits (e.g. varying by temperature or pressure).

UPDATE Aug 2020: Need to load log files into a table for each run fitted, group workspaces etc. and save in n native mantid format.

**Comment by DannyHindson** [comment]
Closing this because smaller, individual issues created for the required functionality
