### ISSUE TITLE
Speed up looping over wavelengths for SANS

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#28987]
At the moment reductions iterating over multiple wavelength slices are very slow because the looping is performed _outside_ of Q1D. As there is an increased operational need at ISIS to perform more regular wavelength overlap checks (eg, for signs of multiple scattering, but also for future autovalidation), and to facilitate the simulation of the ESS Loki instrument, this looping should be moved _inside_ Q1D.

This will not be a simple task and, because it touches the heart of the ISIS SANS data reduction, it will need very careful testing and validation to ensure that the new procedure replicates the existing output.

This now a quite urgent task.

**Comment by RichardHeenan** [comment]
I can see a possible half way house that avoids a rewrite of Q1D, (I have a demo script)  by adding the wavelength loops when Q1D is called. 
A series of rebins of the workspaces that are passed to Q1D can do the wavelength ranges very fast, though the solid angle calcs are likely repeated, the wavelength to Q calculation is unique each time. (OK we need to check that the sum of ranges in the numerator and denominator are as obtained for doing the full wavelength range).
Look at
scripts/SANS/isis_reduction_steps.py around line 2765 calls Q1D with wavepixeladj (from ~2736) included for the angle dependent transmission. Set up the list of ranges in here, call Q1D in a loop, sort out the naming of the results workspaces, then take the numerator/denominator ratios.

scripts/reduction/instruments/sans/sans_reduction_steps  around line 590 seems to do the same, but must be older, as no wavepixeladj   Much in this directory is now deprecated? (DavidFair knows more!)
