### ISSUE TITLE
Set default Imshow origin to lower

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#28997]
See #28811 and #28870  for further explanation 

While documentation and script generation helps to ensure that users set origin = 'lower'
if a user runs a script with imshow and origin is not set by the user, then the default `upper` is chosen. This issue is to force the origin to be `lower` if the user hasn't set it (within Mantid reset the MPL default to `lower`.

Steps to reproduce the behavior
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
nrows, ncols = 5, 5
signal = np.arange(0,nrows*ncols)
x = np.arange(0,2*ncols+1,step=2)

data = CreateWorkspace(DataX=x, DataY=signal, NSpec=nrows,UnitX='TOF')
figC,axC = plt.subplots(subplot_kw={'projection':'mantid'})
c=axC.imshow(data)
axC.set_title('Imshow')
cbar=figC.colorbar(c)
plt.show()
```
Platforms affected
All Workbench

**Comment by StephenSmith25** [comment]
#28924 and #28870 have fixed issues this caused.
