### ISSUE TITLE
Improve unit test for ConvertToMatrixWorkspace

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#2899]
This issue was originally [TRAC 2052](http://trac.mantidproject.org/mantid/ticket/2052)

At the moment the test is just a copy of ```CloneWorkspace()```, it really needs to test that the histogram representation of an event workspace is being copied out correctly.

 - - - - 
Keywords: Maintenance

**Comment by Anders-Markvardsen** [comment]
Add unit test to ConvertToMatrixWorkspaceTest that shows that the histogram representation of an event workspace matches that of the histogram in the created MatrixWorkspace from this algorithm

**Comment by martyngigg** [comment]
It would seem that this has been done at some point. However, the test can still be improved. It uses a file and that can be removed in favour of an in-memory workspace.
