### ISSUE TITLE
Crash Plotting after Sliceviewer

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29005]
This was found by new students in the ISIS Mantid team during the Mantid Basic Course

### Expected behavior
Sliceviewer and normal plots close cleanly and there is no crash!
### Actual behavior
It is possible to open and close the sliceviewer, try to plot a few spectra and then Mantid hard crashes
### Steps to reproduce the behavior
These steps do not work every time. If they do not crash Mantid, then go through the steps a second time!

- Load MAR11060 from TrainingCourseData
- Load EMU00020884.nxs from TrainingCourseData
- Open the sliceviewer on the MAR11060 workspace
- CLOSE sliceviewer
- Plot spectra 1-10 tiled of the EMU00020884 workspace

### Platforms affected
Mac and Windows latest nightly/master 5.0.20200714.1059

Mac Python crash report: [crashMBC.txt](https://github.com/mantidproject/mantid/files/4924577/crashMBC.txt)

**Comment by SpencerHowells** [comment]
@DanielMurphy22 it also crashes on my workspace iris27126_graphite002_red
