### ISSUE TITLE
Support setuptools >= 49.0.0

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#29010]
Since this issue was created, it has been found by a user on the forum: https://forum.mantidproject.org/t/mantid-5-1-crash-at-start-on-unbuntu-18-04/703

### Expected behavior

Running `bin/mantidpython` followed by `import mantid` should succeed.

### Actual behavior

If setuptools >= 49.0.0 then Python has not added any paths from .pth files to sys.path and `mantid` cannot be found.

It is related to the fact that we rely on the `site.py` file `setuptools` used to create to bootstrap the paths in the `.pth` files but removed in [v49.0.0](https://setuptools.readthedocs.io/en/latest/history.html#v49-0-0). Related issue: https://github.com/pypa/setuptools/issues/2165

### Steps to reproduce the behavior

```
$ bin/mantidpython
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mantid                                    
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-002efd284d2a> in <module>
----> 1 import mantid

ModuleNotFoundError: No module named 'mantid'

In [2]:
```

### Platforms affected
Currently macOS but any that installs setuptools v >= 49.0.0

**Comment by DavidFair** [comment]
Ran into this on Ubuntu 18.04 - this resulted in errors importing the error reporter, `mantidqt` and `mantid`.

After downgrading to setup tools 48.0.0 the any egg files in `build/bin` need to be removed and regenerated to fix the issue
