### ISSUE TITLE
Fit background function crash

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29033]
**Original reporter:** Found by @joseph-torsney 
@alicerussell1 was able to reproduce

### Expected behavior
No crash adding fit functions to plots
### Actual behavior
Crash when trying to add a fitting function by typing in the search bar
### Steps to reproduce the behavior
- Load any data, plot a spectrum and click 'Fit' to open the fitting tools
- Right click on the plot (does not crash when adding via clicking on fit browser), Click one of the `Add ...` options. Then type in the function selection box.
### Platforms affected
Found on Ubuntu Virtual Machine: workbench 5.0.20200715.650 on Ubuntu 18.04.3 LTS

### StackTrace
```
       Traceback (most recent call last):
 File "/opt/mantidnightly/lib/mantidqt/widgets/fitpropertybrowser/addfunctiondialog/view.py", line 59, in keyPressEvent
   self.lineEdit().keyPressEvent(event)
RuntimeError: no access to protected functions or signals for objects not created from Python
```

**Comment by StephenSmith25** [comment]
This was fixed by #29625
