### ISSUE TITLE
Error when opening ISIS SANS in debug

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29048]
### Expected behavior
The ISIS SANS gui should open in debug mode
### Actual behavior
When running workbench in debug mode from pycharm, opening ISIS SANS raises an error. but this does not happen when running normaly
### Steps to reproduce the behavior
1. run workbench in debug mode from pycharm
2. open ISIS SANS. a long error should be raised.
### Platforms affected
Windows

**Comment by DavidFair** [comment]
I believe this was fixed by https://github.com/mantidproject/mantid/pull/29513
