### ISSUE TITLE
Sliceviewer Figure Options

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29074]
We should change the figure options in the Sliceviewer to be the same as Colorfill plots

Currently the (matplotlib default) Figure Options don't really work for Sliceviewer, including the (Re-)Generate Automatic Legend tickbox that produces an unexpected error.

### Steps to reproduce the behavior
Open Sliceviewer on any workspace (say SANSLOQCan2D.nxs)
Open Figure Options and tick the (Re-) Generate Automatic Legend tickbox

### Platforms affected
Workbench all

**Comment by martyngigg** [comment]
Most of the options don't work so we'll just remove the button. The ability to set log X/Y axes is not really useful for this view and the old sliceviewer didn't have it. We can look at using the mantidqt plot options in the future if it is required.

Re-adjusting estimate.
