### ISSUE TITLE
Muon tile plot bug

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29079]
Load chronos 9707 into muon analysis
Change the grouping file to the custom one
Select up, down, top, bottom for analysis
Select tiled plot
Two of the groups are on one tile

![image](https://user-images.githubusercontent.com/25006392/88903234-43cb5280-d24b-11ea-8e47-517689af8bdc.png)

**Comment by Matthew-Andrew** [comment]
This has been resolved.
