### ISSUE TITLE
Grey out inspect background button of Eng Diff UI fitting until valid

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#29099]
Grey out the "inspect background" button in the fitting tab until the pre-requisites are met (row selected with background subtraction run).

**Comment by DannyHindson** [comment]
Just realised this issue doesn't have much detail. Will try and add some more detail later on about when the button should be enabled\disabled but just to get you started, this is the button that this issue refers to:
![image](https://user-images.githubusercontent.com/56295817/91542440-c8c28e00-e915-11ea-90cf-dd8193e1d210.png)
