### ISSUE TITLE
Investigate IntegrateEllipsoid inaccurate integration for weak peaks

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#29101]
TOPAZ scientists have noticed IntegrateEllipsoids can give anomalous results for weak peaks - have compared to IntegratePEaksMD and think that there might be an issue - but haven't identified where. Perhaps a good starting place would be to have better tests with a better way of generating fake peaks of known covariance  (with/without counts = errors = 1) - for example see recent changes to IntegratePEaksMD tests.

**Comment by DannyHindson** [comment]
Issue raised by SNS

**Comment by RichardWaiteSTFC** [comment]
![image](https://user-images.githubusercontent.com/55979119/99965776-40754d00-2d8d-11eb-8f17-91ad19f10666.png)
Issue with integrateEllipsoids not integrating weak peaks

**Comment by DannyHindson** [comment]
Closing because we're not using IntegrateEllipsoids at ISIS and this was possibly fixed in #31049
