### ISSUE TITLE
Multiple groups appearing on one plot

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#29110]
In the Muon Analysis GUI sometimes multiple groups appear in one plot. To see this create a set of groups one of which is called `up` and then tile by group/pair. If you remove all plots except `up` and then re-add them you will find all the groups overplotted on one graph. This is beacuse under the hood the GUI uses string comprehension to decide which group goes on which axes and `Group` contains `up` as a substring so all the plots end up on one plot axis.

**Comment by AnthonyLim23** [comment]
#29079
