### ISSUE TITLE
Update the plot titles in muon GUI's

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29126]
The muon GUI's currently use the run number to label the subplots or the lines. We want to update this to have the title from the WS followed by the run number. e.g. `Ti at 1K and 5T (45631)`

If no title is present just use the run number.

**Comment by martyngigg** [comment]
As this is assigned during a sprint can I remove the induction label?

**Comment by Matt-Cumber** [comment]
Un-assigned myself and going to leave as induction as I picked this from the ice box towards the end of last sprint but never got round to doing it
