### ISSUE TITLE
'About Mantid Workbench' window opens on every launch, even after checking 'Do not show again'

### ISSUE THREAD

**Issue by joseph-torsney** [mantidproject/mantid#29120]
### Expected behavior
The 'About Mantid Workbench' window should not show next time workbench launches after checking 'Do not show again until next release' checkbox.

### Actual behavior
The window shows again

### Steps to reproduce the behavior
1. Launch Workbench
2. Check 'Do not show again until next release' on the About window
3. Close and relaunch workbench
4. The About window appears

### Platforms affected
Tested on Ubuntu 18, likely to affect all.

**Comment by martyngigg** [comment]
So this seems to be a problem is `default.facility` is not set in the properties file at all. The code first checks if you have not set a facility and doesn't care about the checkbox. We actually ship with `default.facility = ISIS` in the shipped properties file so I think this is a little niche.

Did you have a line `default.facility = ` in either `bin\Debug\Mantid.properties` or `bin\Debug\Mantid.user.properties`?

I'm going to close this as niche enough that we understand what to do.
