### ISSUE TITLE
Mantid crashes when cancel is clicked during MaxEnt on Frequency domain analysis 

### ISSUE THREAD

**Issue by tolu28-coder** [mantidproject/mantid#29145]
### Expected behavior
When cancel is pressed on frequency domain analysis gui when calculating MaxEnt, calculation should stop.

### Actual behavior
When cancel is pressed on frequency domain analysis gui when calculating MaxEnt, Mantis crashes.

Error Message
MuonMaxent: Execution cancelled by user.
Traceback (most recent call last):
  File "C:\Users\Tolu\Documents\Mantid\mantid\scripts\Muon\GUI\FrequencyDomainAnalysis\MaxEnt\maxent_presenter_new.py", line 99, in handleFinished
    self.calculation_finished_notifier.notify_subscribers(self._maxent_output_workspace_name)
AttributeError: 'MaxEntPresenter' object has no attribute '_maxent_output_workspace_name'

### Steps to reproduce the behavior
1. Open Frequency Domain Analysis gui.
2. Load Appropriate data.
3. Calculate MaxEnt then click on cancel , mantid crashes.

### Platforms affected
Confirmed on Windows, assumed to work on other platforms as well.

**Comment by AnthonyLim23** [comment]
for data use MUSR 62260
On the transform tab change drop down to MaxEnt
Change the number of data points to a high number (this will make it slow, so better chance to cancel)

**Comment by AnthonyLim23** [comment]
Its definitely in the GUI, the cancel works ok when running the MuonMaxEnt algorithm
