### ISSUE TITLE
Remove deprecated EnggDiff GUI

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#29150]
Old EnggDiff GUI in `\qt\scientific_interfaces\EnggDiffraction` is marked as deprecated in the `EnggDiffractionViewQtGui.h`, removal would help to avoid confusion with the new interface files in `\mantid\scripts\Engineering\gui\engineering_diffraction`

**Comment by martyngigg** [comment]
This can be part of the MantidPlot removal process as this version does not exist for MantidWorkbench.

**Comment by martyngigg** [comment]
Setting this to 6.1 as users won't see it anyway so no rush for the release but it would be a good maintenance task.

**Comment by clayton-tom** [comment]
This appears to have been completed under the removal of MantidPlot related code
