### ISSUE TITLE
SliceViewer: zoom on non-orthogonal view decreases extent of binned data plotted

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#29165]
Zooming on the non-orthogonal sliceviewer does not act as one would expect. On the orthogonal view as you zoom the view fills with more of the data but with the nonorthogonal view the data in the view seems to remain constant:

![nonortho-zoom](https://user-images.githubusercontent.com/55979119/89420344-79c87500-d72a-11ea-955e-636a2b4d437a.png)

# Steps To Reproduce

The following script produces a workspace that allows angles to be played with:

```python
from mantid.simpleapi import *

SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
mdws = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767',
                                       OutputDimensions='HKL')
```

* Open in the sliceviewer
* Click non-orthogonal view
* Zoom in on a position by scrolling

**Comment by RichardWaiteSTFC** [comment]
Have found that when the viewing axes are set to (x,y) = (K,L) in non-orthogonal view, zooming or selecting a peak in the table will cause an exception that also seems to be related the axes limits.
![image](https://user-images.githubusercontent.com/55979119/89904758-3c0f9480-dbe1-11ea-90d9-ecf2bece095b.png)

**Comment by RichardWaiteSTFC** [comment]
In process of testing in issue #30035, I have discovered that if you pan the view you can bring the data back into the binned region - it's just that the extent of the plotted data is reduced with the zoom
