### ISSUE TITLE
Muon Analysis Fitting tab not reenebaled on phase quad error

### ISSUE THREAD

**Issue by Matthew-Andrew** [mantidproject/mantid#29197]
When there is an error in the calculation of the phase table or phase quad calculation the fitting tab is not correctly re-enabled. An easy way to get an error in the phase table calculation is to only have one group in the grouping tab which will then mean that a phase table calculation is attempted with a missing group.

**Comment by AnthonyLim23** [comment]
should we only enable it if there is more than 1 group?

**Comment by Mantid-Matthew** [comment]
I think this is more of a generic issue where if there is any error in the calculation the the signal to enable disabled tabs is not sent. It actually handles things quite gracefully otherwise.

**Comment by Matthew-Andrew** [comment]
I suspect this is due to the error callback not re-enabling the GUI.
