### ISSUE TITLE
Raw Data Explorer Widget

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#29249]
A new file browser like widget is required in workbench to facilitate loading, inspection and comparison of large amounts of raw data files.
Types of visualizations to be supported: 1D plots (spectrum, bin), colorfill, sliceviewer, instrument viewer.
It should allow to execute common pre-defined operations (a. k. a. previews) on run-by-run basis, such as transform, convert axes, certain types of grouping etc.
The other rationale is that for an occasional lambda user it is not intuitive to figure out which kind of visualization is relevant for the given raw data. For example, plotting monochromatic SANS data is meaningless, it's the instrument viewer that is relevant. But the newbie might not realise that immediately.

**Comment by martyngigg** [comment]
Can I roll this over to 6.2?
