### ISSUE TITLE
Bug for adding multiple copies of a spectra in indirect fq fit

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29244]
In indiect data analysis on the f(q) fit on the multiple spectra option you can add multiple copies of a single spectra to the table. if you then switch to a different workspace and back the duplicates are removed. there should be a check to prevent duplicated being added.

**Comment by AnthonyLim23** [comment]
is this likely to get done for this release?

**Comment by Harrietbrown** [comment]
It's unlikly to be done for this release.

**Comment by AnthonyLim23** [comment]
@Harrietbrown whats the status on this?

**Comment by Harrietbrown** [comment]
It was not considered significant enough to be done befroe the refactor, so it has beenin the icebox

**Comment by martyngigg** [comment]
Can I move this to 6.1S1?
