### ISSUE TITLE
Unscripted Testing: Sliceviewer

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29327]
You have been assigned unscripted testing. The hope is to catch as many problems with the code before release, so it would be great if you can take some time to give a serious test to your assigned area. Thank you!!

The general guide to unscripted testing:

* The tests must be performed on the installer versions of the final release candidate. Not on local compiled code.
* Serious errors involving loss of functionality, crashes etc. should be raised
as issues with the current release as a milestone and an email sent to the project manager immediately.
* Minor and cosmetic issues should be raised as issues against the forthcoming
releases.
* First try things that should work, then try to break Mantid, e.g. entering invalid values, unexpected characters etc.
* Don't spend more than a few hours on the testing as fatigue will kick in.
* If you find errors in the documentation, please correct them.
* Comment against this ticket the OS environment you are testing against.
* Close the this issue once you are done.

**The new slice viewer in Workbench!**

**Comment by RichardWaiteSTFC** [comment]
Have made the following new issues #29345, #29347, #29348, #29354 as well a reproducing known issues #29136, #29087,#29165, #29258 
Briefly I tested for both MDEvent and MDHisto workspaces:
(1) Viewing 2D,3D and 4D MD data - (changing bins and sliders)
(2) Panning, home, Zooming/Dynamic rebinning - both by selecting region with mouse and scrolling
(3) Toggling tracking of cursor
(4) Toggle gridlines
(5) Experiment with line plots and box integration
(6) Changing viewing axes
(7) Peak overlay (multiple peaks workspaces, integrated peaks, sorting table, zooming on peaks, changing axes with peaks shown, peak overlay should not be shown for 2D data)
(8)  Repeat (1-7) for data with non-orthogonal axes
(9) Play around with window - resizing, adjusting peak table size
(10) Saving plot
(10) Delete/rename underlying workspaces (at present sliceviewer does not update)
