### ISSUE TITLE
For nightly or unstable packages use the appropriate icon in Windows task bar

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29326]
When a user runs a nightly build package on Windows it would be helpful if the taskbar icon represented this as it does on macOS.

This task is to ensure the taskbar icon (most likely the application icon) on Windows represents either the nightly or unstable build if one of those is being used. When multiple versions are open this should help reduce confusion about which package is being used.

**Comment by martyngigg** [comment]
@AnthonyLim23 For the icon, do you mean the `.exe` icon or the desktop shortcut? Could you include a screenshot here?

**Comment by AnthonyLim23** [comment]
![image](https://user-images.githubusercontent.com/25006392/92376654-cffa5080-f0fa-11ea-9652-1431f59e8555.png)

and it crashed when I closed it...

**Comment by martyngigg** [comment]
Ah okay. So it's the taskbar icon. Thanks.

**Comment by martyngigg** [comment]
@AnthonyLim23 I couldn't see in the code where we change this so I downloaded a nightly from June and it appears to be the same:
![screenshot-nightly-june](https://user-images.githubusercontent.com/733773/92508212-243b2880-f200-11ea-98f0-e01439cc6143.png)

Do remember it behaving differently? I think it is probably a good idea to use different icon but if we haven't regressed can we drop the "High Priority" label and see if we get time to look at it and assess risk?

**Comment by AnthonyLim23** [comment]
I thought I had seen it show up at nightly at some point. It may have been plot. I will remove the high label

**Comment by martyngigg** [comment]
Thanks. I checked MantidPlot too and I couldn't see it. Let's keep this one for a future sprint.
