### ISSUE TITLE
Unhandled expection in Engineering Diffraction Fitting

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#29339]
Found during unscripted testing. In the fitting tab of Engineering diffraction both TOF and d-spacing appear as in the workspace selection menu. If you have TOF data plotted and switch this workspace to d-spacing and click the fit button you'll get an unhandled exception, which brings up the error reporter. Ideally, the workspace selection menu should only allow you to pick from the plotted data.

### Steps to reproduce the behavior
 Create some data as per #28393

- Go to fitting and load one of the focussed files.
- Plot the data and open the fit pane
- Add a fit function
- If you changed the selected workspace and press fit you'll get the exception.

### Platforms affected
All

**Comment by RichardWaiteSTFC** [comment]
Just to check this doesn't occur if the workspace are all added to the plot and your selecting between them in the fitprop browser - it is when you remove the from the plot using the checkbox in the table?

**Comment by StephenSmith25** [comment]
Yep its all fine if the workspaces are plotted. Maybe I had just got the GUI into a bad state, as I was messing around with it for a while. So may be worth seeing if the same happens for you.

**Comment by RichardWaiteSTFC** [comment]
No I've come across this error before, thanks for reminding me/catching it. There were so many other things to sort out it wasn't a high priority, but that's not the case now. FYI I think if you put the data back on the plot it works again - maybe you could check this too? It is quite easy to get it into a confused state atm. I haven't decided on the best way to deal with it, maybe you have some ideas? The options as I see it are (1) Close and re-open the fitproperty browser every time the plot updates so when it re-opens you have an up to date list of the workspaces, but this disrupts the user's workflow, you loose the parameters you'd set etc. (2) same as above but close and re-open when the input workspace is removed from plot (3) catch the error and issue a warning (4) fix the code in fitpropertybroswser that crashes - I think in this case keep track of the normalisation.

**Comment by StephenSmith25** [comment]
Yep was all good once I had the data back on. Might be a hassle but ideally the plot and combo box should be in sync. Presumably you're using fitpropertybrowser.py? As it seems the method `_get_allowed_spectra` should be handling this for us.
