### ISSUE TITLE
Indirect ISIS Calibration - background and rebinning ranges do not update after changing reflection

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29344]
### Expected behaviour
The binning range and background range of the resolution should be set automatically. This does not happen if you change the Reflection after entering Input Runs. When changing the reflection, these ranges should probably be updated.

### Actual behaviour
The binning range and background range is given a width of zero, which is not helpful!

### Steps to reproduce the behaviour
1. `Interfaces`->`Indirect`->`Data Reduction`->`ISIS Calibration` tab
2. Enter run numbers `59057-59059`, wait for them to load
3. Check `Create RES File`
4. Change reflection to `004`
5. Click `Run`
6. This message appears in the log:
![image](https://user-images.githubusercontent.com/40830825/92454210-2c6f7580-f1b8-11ea-98f6-3fb9be297311.png)

### Platforms affected
Tested on windows nightly build

**Comment by robertapplin** [comment]
I think this is a low priority bug, so I am not sure if it should be fixed for this release. @SpencerHowells what do you think?

**Comment by SpencerHowells** [comment]
@robertapplin Low priority. The reflection should be changed before loading data.

**Comment by SpencerHowells** [comment]
@robertapplin More thoughts. The run is different for the 2 reflections so if you change a reflection you should change the run.
