### ISSUE TITLE
Sliceviewer exception when zooming in non-orthogonal view

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#29345]
When zooming (by mouse or double-clicking on a peak in table) in non-orthogonal view in sliceviewer there is an exception.
![image](https://user-images.githubusercontent.com/55979119/92461825-9c362e00-f1c1-11ea-9734-d3f2697815d7.png)

### Steps to reproduce the behavior
(1) make a MD workspace with ono-orthogonal axes
```
from mantid.simpleapi import *

SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
mdws = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputDimensions='HKL')
```
(2) Open it in sliceviewer and set view to non-orthogonal
(3) Try to zoom

### Platforms affected
Nightly 05/09/20

**Comment by martyngigg** [comment]
Closing as auto close when merging with release-next doesn't work.
