### ISSUE TITLE
Missing detector name on SANSLoad

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29358]
### Expected behavior
Outputs from the ISIS SANS gui's `sum runs` tab should output nxs files that can be processed by the runs tab.
### Actual behavior
instead `SNSLoad` fails with the following message:
```
SANSLoad started
Missing detector at 16734
Missing detector at 16735
Missing detector at 17084
Missing detector at 17085
Missing detector at 17434
Missing detector at 17435
Missing detector at 17784
Missing detector at 17785
Missing detector at 17786
Missing detector at 17787
Missing detector at 17788
Missing detector at 17789
Missing detector at 17790
Missing detector at 17791
Error in execution of algorithm SANSLoad:
StateMoveDetectorISIS: The provided inputs are illegal. Please see: {"Missing detector name": "detector_name: None\nMake sure that a detector name was specified.", "Missing short detector name": "detector_name_short: None\nMake sure that a short detector name was specified."}
  at line 141 in 'C:/MantidNightlyInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSLoad.py'
  caused by line 333 in 'C:/MantidNightlyInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSLoad.py'
  caused by line 44 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_sans_instrument_component.py'
  caused by line 367 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_workspaces.py'
  caused by line 409 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_workspaces.py'
  caused by line 102 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
  caused by line 84 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
  caused by line 62 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
  File "C:\MantidNightlyInstall\scripts\SANS\sans\gui_logic\models\batch_process_runner.py", line 106, in _load_workspaces_on_thread
    load_workspaces_from_states(state.all_states)
  File "C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 221, in load_workspaces_from_states
    workspaces, monitors = provide_loaded_data(state, True, workspace_to_name, workspace_to_monitor)
  File "C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\batch_execution.py", line 452, in provide_loaded_data
    load_alg.execute()

StateMoveDetectorISIS: The provided inputs are illegal. Please see: {"Missing detector name": "detector_name: None\nMake sure that a detector name was specified.", "Missing short detector name": "detector_name_short: None\nMake sure that a short detector name was specified."}
  at line 141 in 'C:/MantidNightlyInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSLoad.py'
  caused by line 333 in 'C:/MantidNightlyInstall/plugins/python\algorithms/WorkflowAlgorithms/SANS/SANSLoad.py'
  caused by line 44 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_sans_instrument_component.py'
  caused by line 367 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_workspaces.py'
  caused by line 409 in 'C:\MantidNightlyInstall\scripts\SANS\sans\algorithm_detail\move_workspaces.py'
  caused by line 102 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
  caused by line 84 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
  caused by line 62 in 'C:\MantidNightlyInstall\scripts\SANS\sans\state\StateObjects\StateMoveDetectors.py'
```
### Steps to reproduce the behavior
1. Open Interfaces->ISIS SANS
2. Choose Load User File, Maskfile.txt
3. Choose Load Batch File, choose batch_mode_reduction.csv
4. Go to the `sum runs` tab
5. Enter 74044, 74019 in the top line
6. Click Add at the side
7. Enter LOQ74044-add as Output file
8. Click Select Save Directory and select a directory in your managed paths
9. Click Sum at the bottom
10. Go back to the Runs tab
11. Change the first column of both rows to LOQ74044-add
12. Click Process All
13. This results in an error.
### Platforms affected
Found in windows

**Comment by gemmaguest** [comment]
Reproduced on Ubuntu. This is a regression in the new GUI since v5.0.0 so needs to be fixed.

**Comment by gemmaguest** [comment]
@smk78 Neither Harriet nor I can reproduce this now. I'm a bit worried it's an "only fails the first time" type of bug. Can you let me know if you see anything strange with the sum runs functionality?

**Comment by gemmaguest** [comment]
I just had the same error but unrelated to sum runs. I think it is to do with editing values on the gui in general - I had edited the max radius on the `Q, Wavelength, Detector Limits` tab and then clicked process. Somehow, the user file field had been cleared, which I suspect is why there was an error when it tried to process. I don't know how it got cleared and again can't reproduce it now.

**Comment by smk78** [comment]
I have been totally unable to reproduce Harriet's error, with the caveat that although I've been using LOQ data I've also been using a different User File, Batch File, and runs.

I have tried all sorts of things: summing immediately after firing up Workbench, after having done some previous reductions, checking Process Selected vs Process All, specifying LOQxxxxxx-add vs just xxxxxx-add. It all works as expected. I even tried changing max radius as Gemma comments. All still fine.

But, I have spotted something.

All the tests I did were just with a User File specified at the top of the Interface; the User File fields in the table were empty. So I set a different User File in the table and then did Process All. It worked... but the workspaces contained the result I would have expected from the top User File, not the one in the table!

So then I changed the top User File to be the same as that in the table and did Process All. Now I had to get a different result right? Wrong! I got the same result! To be clear, the initial (top) User File specified merged-detectors with radius and Q-limits to suit. The User File in the table was main-detector only with different radius and Q limits. And when I checked settings were for the second User File and not the first. It's like the program has a memory of what it was doing and hasn't realised things have changed. I also note that the Merge Fit/Shift values that appeared in the Options box in the table from the first User File are still there, even though they are not invoked by the second User File.

And, as I just demonstrated to Gemma, if you clear all user files (so none specified at all) you can still happily reduce data!

I'm wondering if this is in some way tied up with the tri-state logic problem?

**Comment by martyngigg** [comment]
I can confirm that I can reproduce the error the first time and then not for subsequent attempts, even after restarting workbench.

**Comment by gemmaguest** [comment]
This is similar to an error that was reported a while ago and then disappeared: #26740

Although it may be a coincidence, this does seem like it could well be related, in which case it's a problem that's been around for a while so not something we've broken in this release.

**Comment by gemmaguest** [comment]
Removing the high priority label because this looks like something that may have been around for a while and goes away after the first time. It's still worrying though so I would like to get it in to the release if possible (or at least understand it more).

**Comment by martyngigg** [comment]
Removing assignment and moving to icebox. If we get more time to investigate and can get someone to reproduce it before release then we can try and get something in.
