### ISSUE TITLE
Sliceviewer swapping axes plots data incorrectly

### ISSUE THREAD

**Issue by joseph-torsney** [mantidproject/mantid#29352]
### Expected behavior
Clicking the buttons to swap which value is displayed on each axis should swap what is displayed on each axis, and the data should be plotted correctly.

### Actual behavior
This is easier to explain with pictures...
1. This is how the plot looks initially 
![image](https://user-images.githubusercontent.com/68589504/92475830-ed501d00-f1d5-11ea-868c-81629258142d.png)

2. After clicking to swap the axes once, the axes are correct but the data is plotted incorrectly, the max value on the `Spectrum` axis is the same as the max value on the `Time of flight` axis (if you drag the plot to the right).
![image](https://user-images.githubusercontent.com/68589504/92476015-356f3f80-f1d6-11ea-9ca7-a29ec3a823e4.png)

3. Swapping the axes again swaps the labels but not the actual plot
![image](https://user-images.githubusercontent.com/68589504/92476059-4750e280-f1d6-11ea-991a-0b9d01e15f82.png)

4. Swapping the axes again plots the data correctly, but the range on the axes appear incorrect
![image](https://user-images.githubusercontent.com/68589504/92476150-6a7b9200-f1d6-11ea-9ca6-4ddffd007aa3.png)

5. Swapping the axes again gets us back to the correct state, and to step 1.
![image](https://user-images.githubusercontent.com/68589504/92476463-e83f9d80-f1d6-11ea-9f3b-77fa0437db7b.png)

### Steps to reproduce the behavior
See above

### Platforms affected
Tested on windows

**Comment by Matt-Cumber** [comment]
There is also a weird visual glitch to these buttons on Mac (at least for me) for example:
**Using the MAR11015 dataset**

All buttons can be pressed at the same time
![image](https://user-images.githubusercontent.com/46685490/92479363-57b78c00-f1db-11ea-9b18-4f95daa5db18.png)

Or all off
![image](https://user-images.githubusercontent.com/46685490/92479407-69009880-f1db-11ea-8deb-28bbe6974638.png)

Or they are half on
![image](https://user-images.githubusercontent.com/46685490/92479438-73229700-f1db-11ea-9df1-3529b7b5b512.png)

**Comment by joseph-torsney** [comment]
Could be related to #29400

**Comment by Matt-Cumber** [comment]
Regarding my previous comment, if you swap the axis by pressing the button once then click off Mantid onto your desktop or another application, then click back on Mantid the visual bugs sort themselves out. Still doesn't look quire right though 😕

**Comment by clayton-tom** [comment]
Merging with #29400
