### ISSUE TITLE
Unhandled TypeError exception plotting from Data table

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#29355]
I've only found the issue and been able to reproduce on unfocused GEM files, specifically GEM40979 from the Training Course Data. Focused GEM files and other ws2Ds I've tried seem fine.

Confirmed regression from 5.0 (windows)

### Steps to reproduce the behavior
1. Load GEM40979
2. Show Data
3. Select one or more columns
4. Right click, plot bin

### Platforms affected
Discovered on windows, assumed on all

**Comment by clayton-tom** [comment]
Also happened with SXD23767

**Comment by martyngigg** [comment]
@clayton-tom Could you provide details of the error message that is created. 

I'm not sure I would count this as high priority unless we know it's a regression from last release? If not then I'm happy to keep it on the board but I think we should remove the "High Priority" label as that's only for things that should hold up the release.

**Comment by martyngigg** [comment]
Closing as auto close when merging with release-next doesn't work.
