### ISSUE TITLE
Project Recovery progress bar is not working

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#29369]
### Expected behavior
It works

### Actual behavior
It doesn't

### Steps to reproduce the behavior
- Open workbench
- Run:
```
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
mdws = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputDimensions='HKL')
```
- Wait 60 seconds for project recovery to save a checkpoint (Or wait for it to say it's done in the logger under debug)
- Crash workbench using your preferred method (Segfault algorithm is a good one)
- Open workbench
- Click yes to start recovery
- Progress bar doesn't increment like it should

### Platforms affected
All.

### How to fix
The way python code is executed changed and migrated to C++ the sig_progress signal in PythonFileInterpreter is not correctly connected to the C++ side. A method should be created to connect them and a method to disconnect them should be made, then project recovery should connect sig_progress with the C++ CodeEditor Widget, do its thing, then on gui exit ensure a disconnect occurs, to avoid excess computation during normal script execution

**Comment by gemmaguest** [comment]
Fixed by #29383
