### ISSUE TITLE
Reflectometry UI crashes after loading sample data .json file

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#29367]
Mantid Workbench crashes about ~20 seconds after loading the INTER_NR_test.json file into the Reflectometry UI (from the ISIS sample data set http://sourceforge.net/projects/mantid/files/Sample%20Data/SampleData-ISIS.zip/download)

Go to Interfaces, Reflectometry, ISIS Reflectometry
Go to Batch, Load and load the INTER_NR_test.json file. Wait ~20 seconds. Mantid Workbench crashes

Checked with Gemma and she's can reproduce:

_Yes, this crash is a genuine problem. It's actually because the sample data is slightly out of date and contains only 9 columns on the experiment settings table when there are now 10. It should be backwards compatible with old files, though, so this should work. The crash is happening in the encoder which is why it's taking a while - it's happening when project recovery takes a snapshot._

**Comment by martyngigg** [comment]
Closing as auto close when merging with `release-next` doesn't work.
