### ISSUE TITLE
Mantid applications menu item not created on Ubuntu

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#29364]
The Mantid Workbench icon isn't appearing in the Ubuntu applications menu after install of the latest nightly build (folllowing screenshot shows icon that is now missing). 

![image](https://user-images.githubusercontent.com/56295817/92585615-1aabd200-f28d-11ea-9306-f8a713b0df6b.png)

This is because the following file:

installers\LinuxInstaller\launcher-template.desktop.in

contains a C++ comment\header which means it's not parsed properly. Maybe this was added when the CSNS update was made to this header across lots of files. I think the fix is simply to remove the comment

**Comment by martyngigg** [comment]
Closing as auto close when merging with release-next doesn't work.
