### ISSUE TITLE
Muon analysis results table

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29409]
In results table the output no longer has the y errors set in the table columns

https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/results_tab_widget/results_tab_model.py#L276

it might be that the value has changed at
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/results_tab_widget/results_tab_model.py#L33

**Comment by AnthonyLim23** [comment]
Load data
Do a fit
go to results table
Tick a few sample logs
Produce the results table
Check the errors are marked up correctly

**Comment by Harrietbrown** [comment]
So this does not look like an issue with muon itself. it's a bug with the displaying of the table itself.

**Comment by Harrietbrown** [comment]
Closed by #29434
