### ISSUE TITLE
Units on SANS GUI are wrong

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#29415]
**Original reporter:** @smk78 

PR #28513 changed some of the units of values on the SANS GUI but the labels have not been updated to match. We should ideally change units back to their originals (mm rather than m) but could also consider updating the labels if the former is not possible.

- The units are now stored internally in metres for almost all units. This should be kept because it is more consistent for the programmer to deal with.
- Any conversion should be done at the final stage before displaying on the view. User-entered values in mm should be immediately converted to m for storage in the model. 
- Some hard-coded values are not stored in metres. Ideally these should also be stored in metres and converted for the view to be consistent with other values, but this may be better done as a maintenance step after release 5.1.
- Note that the beam centre finder results window shows values in mm. These units should probably be the same as the inputs (ideally both mm)
- We are displaying up to 19dp in some cases - this should be limited - see Steve's comment below.

### Steps to reproduce the behaviour
- Open the ISIS SANS GUI
- Load the MaskFile.txt user file from the loqdemo subdirectory in the training data
- Check the values on the screenshots and compare to the results in v5.0.0. The values are out by a factor of 1000 even though the units on the GUI are the same.

### Suggestions
- The values that have changed from mm to m are shown in the screenshots (please sanity check in case there are more)
- Note that Z offset does not have units in its label. Ideally this should be added.
- The hard-coded values stored in mm are the beam centre radius limits. There may be other hard-coded values also stored in mm.
- It looks like the best place to do the conversions would be in `_set_on_view` and `_set_on_state_model` in `PresenterCommon`. This is used by `RunTabPresenter` and `SettingsAdjustmentPresenter`. Note that `BeamCentrePresenter` has its own version of these functions that perhaps could be consolidated (but I'm not sure if there's a reason it doesn't use the base presenter).

![sans_general](https://user-images.githubusercontent.com/12895056/92890555-1f988f00-f40f-11ea-910a-c8ad9d23436e.png)

![sans_adjustment](https://user-images.githubusercontent.com/12895056/92890581-26bf9d00-f40f-11ea-9b9d-0df7ea264967.png)

![sans_q](https://user-images.githubusercontent.com/12895056/92890596-29ba8d80-f40f-11ea-83a8-7447bcd2e27f.png)

![sans_beam](https://user-images.githubusercontent.com/12895056/92890567-245d4300-f40f-11ea-974f-3577df3faae2.png)

**Comment by smk78** [comment]
> The values that have changed from mm to m are shown in the screenshots (please sanity check in case there are more)

You got the lot!

**Comment by smk78** [comment]
Can we also do something about the displayed precision of some values, please.

I would suggest that for anything being displayed as m or mm, 1 d.p. will be adequate _except_ for beam centre coordinates where mm to 3.d.p. would be useful.
