### ISSUE TITLE
Implement "Clear all memory" in Workbench

### ISSUE THREAD

**Issue by smk78** [mantidproject/mantid#29423]
@smk78 asks on behalf of a tester: Is there a reason why the "File" > "Clear all memory" option in MantidPlot, which removed all workspaces and plots in one fell swoop, has not been ported to Workbench?

**Comment by martyngigg** [comment]
Thanks @smk78. This was an oversight on our part as we'd been focusing so much on the big-ticket items. We'll take a look.

**Comment by martyngigg** [comment]
This feature should simply do:
* show a dialog question box and ask a user if they want to clear all workspaces, instruments etc
  * if yes then arrange a call to `FrameworkManager.Instance().clear()`
  * if no then do nothing.

Please add a test in [mainwindowtest.py](https://github.com/mantidproject/mantid/blob/ccb734b1e026dfae9e4e30ba29ecbb2cb0901a1b/qt/applications/workbench/workbench/test/mainwindowtest.py)

**Comment by gvardany** [comment]
This was a requirement also for us. Could you also add a button in the workspace widget (next to Delete), called Clear that will trigger the same action?

**Comment by Matt-Cumber** [comment]
> This was a requirement also for us. Could you also add a button in the workspace widget (next to Delete), called Clear that will trigger the same action?

@martyngigg I'm happy to also add this if that is okay with you. I shall create a separate issue though as the original has been approved and merged

**Comment by martyngigg** [comment]
As long as we can do that without disturbing too much code. The File menu item was easy to adding without disturbing other things. The workspace widget is more involved. I'm happy for a new PR to be created but we need to make sure it is not too risky.

@gvardany Did you have an issue open already?

**Comment by martyngigg** [comment]
Another question. `Clear` on the workspaces widget feels like it should only delete workspaces as the button is attached to that widget.

**Comment by smk78** [comment]
> Another question/comment. `Clear` on the workspaces widget feels like it should only delete workspaces as the button is attached to that widget?

But you're getting a dialog box telling you what's about to be cleared. Personally I wouldn't be surprised to see plots of data that's being deleted to vanish too (it's what we do in SasView); I would expect that.

**Comment by gvardany** [comment]
No issue, apparently it was only in my notes. It is true that the button should clear only the ADS via mtd.clear(), and perhaps not the instrument data service. I don't think there is any risk as long as there is a dialog to confirm.

**Comment by martyngigg** [comment]
@smk78 Yes quite right, people get the option. I was meaning that as @gvardany said we clear more than the workspaces/plots with `Clear All` as we cache things like instrument definitions. If we're happy it clears workspaces (the dependent windows will be deleted automatically anyway just like when you delete a single one) then I think that's fine.

Maybe we should then clarify the message for clear all ...

**Comment by martyngigg** [comment]
I've created #29457 to look at this. We can work on it but if it looks to risky and will disturb too much code then it'll have to move to next release with workaround being select all with Ctrl+A and pressing Delete.

**Comment by martyngigg** [comment]
Closing this as the implementation here is complete.
