### ISSUE TITLE
Muon Analysis Error when loading a run after using FDA

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29428]
**Original reporter:** James Lord

### Expected behavior
Data should be loaded without an error message appearing in the logger.

### Actual behavior
The following error message appears in the logger when loading data:
![image](https://user-images.githubusercontent.com/40830825/92945434-2ba34180-f44d-11ea-97fd-b003d431a17d.png)

### Steps to reproduce the behavior
1. Set default instrument to `HIFI`
2. `Interfaces`->`Muon`->`Frequency Domain Analysis`
3. In the runs box, type `169778` and hit enter. Wait for data to load.
4. Keep FDA open. Go to `Interfaces`->`Muon`->`Muon Analysis`
5. In the runs box, type `169824` and hit enter.
6. The error message above appears in the logger. However, the data appears to load anyway.

### Platforms affected
Found on windows nightly build.

**Comment by AnthonyLim23** [comment]
This is the same bug as #28865

**Comment by Harrietbrown** [comment]
This issue looks like it would be more work to fix than would be worth during the release sprint, and the error message does not interfere with the running of the gui so it can be left for now.
