### ISSUE TITLE
QE coverage - Legend not changing color

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#29447]
### Expected behavior
In QE coverage interface, when changing color of the curve I expect that the color of the legend changes as well, similar to regular plots

### Actual behavior
It does not

### Steps to reproduce the behavior
Open QE coverage interface, either in mantidplot or mantidworkbench. Draw any curve. Change color of the curve.

### Platforms affected
Tested on RHEL7 and Ubuntu 20.04

![image](https://user-images.githubusercontent.com/1128952/93106647-8ff91780-f67e-11ea-8dee-82bcbf1fa244.png)

**Comment by martyngigg** [comment]
It looks like this is not going to make it for 6.4
