### ISSUE TITLE
Issues with Training Courses

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29455]
Found by @sf1919 

- [x] [getName method has been replaced with name](https://docs.mantidproject.org/nightly/tutorials/python_in_mantid/algorithms_and_workspaces/02_ws_types.html)
- [x] #29315 

Python In Mantid
- [x] Add a comment in the solution C (ILL) to explain how to know which Efixed and Emode parameters to set: https://docs.mantidproject.org/nightly/tutorials/python_in_mantid/solutions/01_pim_sol.html#pim-sol

**Comment by sf1919** [comment]
In the Overall Example Script on https://docs.mantidproject.org/nightly/tutorials/python_in_mantid/further_alg_ws/02_scripting_workspaces.html there is a line commented out - `#plotSpectrum(data,[1,2,3],error_bars=True, waterfall=False)` . Does this need to be there? There's nothing in the Output that suggests it needs to be there.

**Comment by sf1919** [comment]
In Declaring Array Propertie (https://www.mantidproject.org/Declaring_Array_Properties) all the links in the Validation section (e.g. FloatArrayLengthValidator) return 404 errors.

**Comment by DanielMurphy22** [comment]
https://www.mantidproject.org/Python_Exercise_Two_Solution
