### ISSUE TITLE
Save unmerged LAB/HAB workspaces when doing merged reduction

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#29454]
From the discussion on #29389:

> > ```
> > * [ ]   2. If you do a DET/BOTH reduction you get the LAB and HAB workspaces and, if you have asked for output files, these get written out. If you do a DET/MERGED reduction you get the LAB, HAB and Merged workspaces, but only the Merged workspace is written out. Whilst there is a sort of logic to this, it is mighty irritating if you want to save all three files! What is DET/ALL supposed to do?
> > 
> > * [ ]  3. The detector dropdown selector offers ALL, but the (old) User File command is BOTH (DET/ALL actually fails). It would be good to standardise on one or other and implement that in the TOML parser.
> > ```
> 
> Yes it looks like All and Both are the same - I'm not sure what it is in the TOML schema but we can tweak this or update the gui to match, whichever you prefer. This should be a job for the next release, though.

I've been discussing these with the SANS Group and we would like to:

- keep the behaviour of DET/BOTH as is
- modify the behaviour of DET/MERGED so that all 3 files are written by default (if output to file/both is selected) but the LAB/HAB files are to be written to a \unmerged subfolder
- do away with DET/ALL

**Comment by DavidFair** [comment]
This should also write the sample and can (if any) workspaces too
Re-opening as the SANS group has run into this confusing behaviour again
