### ISSUE TITLE
Workbench on Linux can't use colour codes above C9 in matplotlib

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#29461]
Whenever a piece of code attempts to utilize a color code greater than C9 i.e. C10 matplotlib throws an error when it is on a version below 3. So on our current supported Linux distributions the code throws, but not on Windows or MacOS.

Ways to fix include updating matplotlib to be inline with current Windows and MacOS versions. 

### Steps to reproduce the behavior
- Set default instrument to HIFI
- Interfaces->Muon->Muon Analysis
- Load 169779-169790

### Platforms affected
Ubuntu and RHEL7

**Comment by AnthonyLim23** [comment]
looks like we need to add a check in this function https://github.com/mantidproject/mantid/pull/29091/files#diff-c3e5fbca4b580462a30bc31dbe6f4176R17

then reset to 0 (repeat the colours)
