### ISSUE TITLE
MSlice crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29477]
MSlice can cause a crash by cancelling some options https://github.com/mantidproject/mslice/issues/542

**Comment by martyngigg** [comment]
@robertapplin Could you use this issue to attach to your pull request that updates the mslice SHA?

**Comment by robertapplin** [comment]
Not sure why the stale bot is commenting on a closed issue ...

**Comment by martyngigg** [comment]
I'm not either. I had this yesterday.

**Comment by martyngigg** [comment]
I've made a comment on the relevant issue in stale issue detector repo.
