### ISSUE TITLE
Sliceviewer 2D matrix transposition squashes image

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#29487]
### Expected behavior
When transposing a WS2D on sliceviewer (changing axes) the image should fill the axes (which appear to scale correctly)

### Actual behavior
It does not, the image appears squashed against either the x or y axis

### Steps to reproduce the behavior
1. Load a 2D workspace such as MAR1160
2. Open the sliceviewer
3. Transpose the image by changing the dimension for the x/y axes

### Platforms affected
Confirmed on windows, assumed on all

**Comment by gemmaguest** [comment]
Fixed by #29512
