### ISSUE TITLE
Instrument view mini-plot not updating

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29491]
Open some data in instrument view
Go to the pick tab
Try to pick a detector
The mini-plot and details do not update (looks empty)

**Comment by martyngigg** [comment]
@AnthonyLim23 Could you add what file/instrument the test was done on? I just tried quickly with a GEM processed file and the standard pixel selection seems to update as expected for me. Is it one of the other tools?

**Comment by AnthonyLim23** [comment]
I used EMU 20844, just double checked and most do work. A few detectors have nothing, so its probably the data. I will close the issue

**Comment by martyngigg** [comment]
Lovely. Thanks for checking.
