### ISSUE TITLE
Update ALC Data Loading 

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#29500]
**Original reporter:** Stephen Cottrell

This issue is to rework the data loading section of the ALC interface to add instrument selector, path, and add watcher functionality to auto

**Comment by AnthonyLim23** [comment]
Add an instrument option

**Comment by Matt-Cumber** [comment]
Warning box if runs > 200

**Comment by Matt-Cumber** [comment]
colour code status messages

**Comment by Matt-Cumber** [comment]
attempting to find files message needs to be clearer
