### ISSUE TITLE
Sliceviewer data table text not contrasting enough

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29522]
@LamarMoore @martyngigg is this worth putting in this release?? We could just make this text black??

**Original reporter:** Spencer on the Forum: https://forum.mantidproject.org/t/grey-level-in-ubuntu/689

Grey text in the interactive data table in the new workbench sliceviewer is okay on Windows,
![Screenshot 2020-09-18 at 11 22 11](https://user-images.githubusercontent.com/55980573/93587256-82ef6780-f9a1-11ea-8601-5f77ad7d3b92.png)

 but much harder to read on MacOS/Linux (Not contrasting enough)

![Screenshot 2020-09-18 at 11 20 35](https://user-images.githubusercontent.com/55980573/93587243-7e2ab380-f9a1-11ea-969f-ffb36326af9d.png)
![Screenshot 2020-09-18 at 11 21 02](https://user-images.githubusercontent.com/55980573/93587259-8551c180-f9a1-11ea-9926-90abe44d9c23.png)

**Comment by SpencerHowells** [comment]
@DanielMurphy22 @LamarMoore @martyngigg this occurs everywhere. See also the info when you click on the ws
![image](https://user-images.githubusercontent.com/12933461/93590126-e24f7680-f9a5-11ea-9fd2-3665a8edf864.png)

**Comment by martyngigg** [comment]
@SpencerHowells We're not explicitly setting this so it must be the Qt style defaults for the type of item that is displayed. I'd prefer not to make a wholesale change at this point for the application but the table in the sliceviewer is actually doing it more by accident than design and I think we can at least target a small fix for that for this release.

**Comment by martyngigg** [comment]
We also need to be careful messing with styles as it's possible other Linu distros set different styles and what we set for a specific colour might clash. We can look into it though.
