### ISSUE TITLE
QENS data analysis plot preview

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29538]
The plot current preview button in QENS data analysis produces a single plot with 3 lines (data, fit, diff). However, it should produce 2 subplots one with data and fit, the second is just the difference. This would then mirror the preview.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 The original miniPlot followed the format used in the Fit guis - the 3 lines. This had limited options for modifying the plot so the Plot Current Preview button was introduced to provide a plot which the users could change to their heart’s content. Someone then forced through the change to the split plot. This is entirely personal preference. I think it looks messy & I prefer the 3 (or more) curves on the same scale. It gives a better indication of relative intensities. It is still used in Bayes>Quasi.
