### ISSUE TITLE
Option for child algorithms showing themselves in the history

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#2955]
This issue was originally [TRAC 2108](http://trac.mantidproject.org/mantid/ticket/2108)

It should be possible for child algorithms to show themselves in the history for a workspace in addition to, or in place of the parent (caller's choice) .

**Comment by NickDraper** [comment]
This was done as part of the ability to unroll nested history done in version 3.2

**Comment by peterfpeterson** [comment]
I agree
