### ISSUE TITLE
Sometimes crash from Indirect reduction

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29554]
For indirect they have 2 methods of storing their data; nxs and raw. The raw files are accompanied by the following files status, ICPrevent, ICPStatus and ICPdebug. 

It is possible to crash workbench when these additional files are not present. However, it is not 100% reproducible (there is something else going on). I can reproduce it on my laptop but not my desktop

Turn off the data archive
Open indirect data reduction
Load the raw file (with the other files missing) using browse of the run bar
If it is going to crash it will here

**Comment by AnthonyLim23** [comment]
This issue was in version 5

**Comment by SpencerHowells** [comment]
@AnthonyLim23 the clue is in the phrase ‘with the other files missing’! The user must put them there.
