### ISSUE TITLE
Ties set through EditLocalParameterDialog not respected in Muon Analysis

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#29573]
**Original reporter:** [ISIS/Peter Baker]

### Expected behavior
If you set a tie in Muon Analysis using the EditLocalParameterDialog it should be active once you perform a fit.
### Actual behavior
The tie is not translated into the final fit function, meaning the tie is not respected
### Steps to reproduce the behavior

- Open Muon Analysis
- Load any data
- Go to the fitting tab
- Add a fit function
- Click the ellipsis (...) which is at the end of each parameter line in the function browser
- Set a tie
- Do a fit, the tie won't be respected

### Platforms affected
Presuambly all.

**Comment by AnthonyLim23** [comment]
This is now fixed
