### ISSUE TITLE
Documentation for avoiding colour blind problems

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29590]
We should add some documentation on how to choose colours to avoid problems with colour blind people not being able to see the results/GUI.

We could make this part of the GUI standards
We could make a standard ourselves

**Comment by SpencerHowells** [comment]
@AnthonyLim23 I think Rob Mcgeevy is colour blind!

**Comment by AnthonyLim23** [comment]
this is an interesting read https://usabilla.com/blog/how-to-design-for-color-blindness/#

We might have to prioritise this with the new regulations about apps and websites from the public sector.

**Comment by martyngigg** [comment]
This is not going to get done for 6.1 so I'm moving it over for 6.2.
