### ISSUE TITLE
IndexPeaks try to refactor to reduce likelihood of out of  range bugs

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#29609]
Validate user input to say only take in modulation vector if max order > 0 - with the default being if the user doesn't supply modvector/maxorder combo then just use whatever mod info is in the lattice

This issue came out of a PR https://github.com/mantidproject/mantid/pull/29597 (and PRs linked therein)

**Comment by DannyHindson** [comment]
Putting in icebox because low priority for ISIS (WISH) and we believe this is on the SNS's radar for scheduling in their team
