### ISSUE TITLE
Fitting with BivariateGoussian Crashes Workbench

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29623]
### Expected behavior
After attempting to fit with BivariateGoussian, even if the fit fails you should be able to fit with a different function
### Actual behavior
When fitting with BivariateGoussian an error is raised and if you attempt to fit again mantid is crashed
### Steps to reproduce the behavior
1. Load MAR11015
2. plot a single spectra
3. open the fitting browser
4. add BivariateGaussian function
5. Try to fit an it will fail with an error message
6. Remove function and add a flat background.
7. click fit agian and mantid will Crash
### Platforms affected
Found in windows.

**Comment by DanielMurphy22** [comment]
This is a problem in the nightly, and release 5.0. I'd just like to add that when I ran BivariateGaussian with a LinearBackground I got this output: 
```
Error in execution of algorithm Fit:
cannot reshape array of size 2656 into shape (50,50,2)
  at line 98 in 'C:/MantidInstall/plugins/python\functions/BivariateGaussian.py'
```

**Comment by Harrietbrown** [comment]
That was the error message I reffered to in step 5
