### ISSUE TITLE
Final issues before refactoring of QENS

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#29649]
This epic is an list of issues that need to be sorted before we can begin the big refactoring of QENS.

- [x] #24662 
- [x] #24664 
- [x] #28104 
- [x] #28529 
- [x] #28991 
- [x] #29254

**Comment by AnthonyLim23** [comment]
These all seem to be done, so I am closing the issue

**Comment by Harrietbrown** [comment]
Agreed, these issues are all completed
