### ISSUE TITLE
Plot context menu: Legend Show/Hide 

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29679]
**Original reporter:** Steve King @smk78 

(Small feature request)

Show/hide legend on a plot can take a while (Figure Options  > Legend > Hide Legend > Apply/Ok).

Adding a `Legend > Hide/Show` option to the right-click context menu would speed up the user experience.

**Comment by DanielMurphy22** [comment]
@smk78 Just thought I'd point out that something pretty similar was implemented, so that you can hide a legend by double clicking on it: https://github.com/mantidproject/mantid/pull/30751

**Comment by smk78** [comment]
Oh yes! Thanks @DanielMurphy22 , I missed that feature in the release notes! You do however have to go through settings to get it back again which is not quite as convenient as this ticket would be (eg, if you are comparing different datasets on the same graph but need to keep referring to the legend). But every little helps!
