### ISSUE TITLE
Add the Frequency Domain Analysis Interface to the PythonInterfacesStartupTest

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29773]
### Expected behavior
The startup script for the Frequency Domain Analysis interface (`Frequency_Domain_Analysis.py`) should be executed as part of the `PythonInterfacesStartupTest` system test.

### Actual behavior
The FDA interface is currently excluded from this system test because it crashes when you attempt to open it from this system test. This crash needs to be fixed so we can remove the `Frequency_Domain_Analysis.py` script from the excluded scripts list. **Be warned this might be a difficult/confusing issue to fix**

https://github.com/mantidproject/mantid/blob/d862e3e6045351abbfd5df4c6bfb32bd849bc723/Testing/SystemTests/tests/qt/PythonInterfacesStartupTest.py#L18

- While you are there, the `Engineering_Diffraction.py` script is showing errors when run, but the test isn't failing. These errors can be fixed in a similar way (by closing the interfaces after opening).

### Steps to reproduce the behavior
1. Remove the FDA interface script from the excluded list in the `PythonInterfacesStartupTest` system test.
2. Run the test. A crash will occur when trying to open the FDA interface.

### Platforms affected
Probably All, but found on windows.

**Comment by martyngigg** [comment]
With the High Priority label, may I ask if this is intended to hold up the release if it weren't fixed?

**Comment by robertapplin** [comment]
No I don't think this should hold up the release
