### ISSUE TITLE
Fit only TOF data in EngDiff UI

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#29829]
### Expected behavior
Want to restrict users to fit only in TOF and create an additional table should be created to hold the peak centres (called different things in different peak functions) converted to d-spacing (using the calibrated difc,tzero etc.).

### Actual behavior
Can fit both d-spacing and TOF

**Comment by DannyHindson** [comment]
Closing because the linked PR has been completed\closed
