### ISSUE TITLE
ALF UB refinement from multiple runs

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#29835]
As an ALF user I want to be able to take multiple runs at many different goniometer angles (detector is small so there is typically too few peaks to make a decent UB in a single run). 

Russell Ewings used the following python script ([ALF_VisualizeMerged_event.txt](https://github.com/mantidproject/mantid/files/5466077/ALF_VisualizeMerged_event.txt)) to merge the runs into a single MD workspace in Qsample - but this is a slow memory intensive process and it was not possible to find the peaks in the merged MD using FindPeaksMD (bug relating to nans - separate issue to follow).

This issue is to find a quick and reliable way to do this.

Report to: Russell Ewings

**Comment by RichardWaiteSTFC** [comment]
I have made the following python script ([ALF_test_workflow_find_peaks.txt](https://github.com/mantidproject/mantid/files/5466089/ALF_test_workflow_find_peaks.txt)) and demonstrated it to Russell. It lops over the run workspace (matrix not MD), uses FindSXPeaks to get the larger Bragg peaks and then uses the goniometer rotations (already on the workspace from Russell's script) to transform all the peaks into Qlab of the first run (nominal 0 for the goniometer). It works successfully and the user can then refine a UB accross multiple runs by running an algorithm such as FindUBUsingLatticeParameters (see script)  which allows them to predict peaks on any given run in the sequence.
