### ISSUE TITLE
Clean up after documentation tests

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#29867]
### Expected behavior
When building docs and running doctests, I expect that tests clean up after being run

### Actual behavior
I get the following extra files in the build `docs` folder:
```
b3lyp.hdf5
benzene.hdf5
benzene_wrk_C.dat
benzene_wrk_C_total.dat
benzene_wrk_H.dat
benzene_wrk_H_total.dat
ColCalcvsTheor.nxs
ConvertMultipleRunsToSingleCrystalMDTest.mat
experimental_wrk.dat
fittedpeaks.dat
myplot.json
RowCalcvsTheor.nxs
Test.DetCal
test_intermediateWavelength.xml
TofCalcvsTheor.nxs
wrk_C.dat
wrk_C_total.dat
wrk_H.dat
wrk_H_total.dat
wrk_Na.dat
wrk_Na_total.dat
wrk_N.dat
wrk_N_total.dat
wrk_O.dat
wrk_O_total.dat
wrk_verbose_atom_1.dat
wrk_verbose_atom_1_total.dat
wrk_verbose_atom_2.dat
wrk_verbose_atom_2_total.dat
wrk_verbose_H.dat
wrk_verbose_H_total.dat
wrk_verbose_total.dat
ZODS.h5
```
### Steps to reproduce the behavior
Build `docs-html` and `docs-doctests`

### Platforms affected
All

**Comment by ajjackson** [comment]
Quite a few of those files come from Abins. It is a normal side-effect to write them, so the solution is to add `testcleanup` blocks that delete them.

I will put that together, but one problem is that I don't actually get all the workspace outputs when I run this locally; just the .hdf5 cache files. I can put code in to delete them from `cwd` anyway, but have a suspicion it won't catch them if they end up written somewhere else...

**Comment by ajjackson** [comment]
I see you have added the hd5 cleanup in https://github.com/mantidproject/mantid/pull/35679 but nothing for the .dat files. Are you still seeing them, or perhaps they were a side-effect of some non-typical test/cleanup failure?

**Comment by AndreiSavici** [comment]
I don't see any more files left. Now I just need to fix a few more tests
