### ISSUE TITLE
Rewrite SaveMDWorkspaceToVTK and LoadVTK

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#29868]
As part of the transition to Workbench, we usually don't build VATES any more. This means that 
`SaveMDWorkspaceToVTK` and `LoadVTK` are no longer available. As part of #29863, the documentation is no longer pointing to the algorithm pages. We need these algorithms to visualize data in Paraview. @martyngigg suggested that we can skip the VTK library when implementing the desired functionality.

**Comment by martyngigg** [comment]
@AndreiSavici Do you think we need `LoadVTK`? According to the usage stats no one has ever used `LoadVTK`.

Also I wonder if it might be worth instead using [PyVTK]( https://pypi.org/project/PyVTK/) and providing scripts/algorithm that someone could download instead of maintaining the save code ourselves? The total usage numbers since v4.0 is only 70...

**Comment by AndreiSavici** [comment]
I don't think I've seen anyone use LoadVTK. Scripts would work, but we need to write a nice page for that. And the save algorithm could just write an error message, pointing users to that page. @rosswhitfield might have an oppinion

**Comment by rosswhitfield** [comment]
Never used LoadVTK, I think that's safe to go.

SaveMDWorkspaceToVTK is useful but we need to make sure we get the non-orthogonal axis correct if it is rewritten or an alternative is provided. We could also possibly do something simple like SaveVTK except for MD workspace.

**Comment by granrothge** [comment]
Just went looking for SaveMDWorkspacetoVTK and was surprised it was gone. Especially since SaveVTK is still there. I agree with Ross the LoadVTK can go. @martyngigg I think the demand for this will grow.

**Comment by martyngigg** [comment]
@granrothge Sorry for not spotting this comment earlier.

`SaveVTK` is some first attempt we made to write out vtk files manually with out the VTK libraries. It seems to have been used a total 6 times in its entire life. I think it might be an idea to just delete it without warning for release 6.1 as I don't think it works as we want and it probably should have gone last time. Thoughts?

For `SaveMDWorkspacetoVTK` there is no demand for it at ISIS currently so I can't offer time to do this. @AndreiSavici @peterfpeterson Is this something you can schedule on your end?

**Comment by martyngigg** [comment]
I'm moving this back to 6.2 to atleast reflect reality that it won't be in this release.

**Comment by martyngigg** [comment]
I've rolled this again but I'm afraid there is no appetite for it from ISIS so I can't give it any time I'm afraid.

**Comment by martyngigg** [comment]
Same comment again as there is no appetite for it from ISIS so I can't give it any time I'm afraid.
@peterfpeterson @AndreiSavici Any apetite from your side for this or shall we close this?
