### ISSUE TITLE
Indirect data analysis: Full function view removes fit curves

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#29888]
### Expected behavior
You should be able to view the full function without removing the fit data from the plot
### Actual behavior
The fit is removed when the tickbox is checked.
### Steps to reproduce the behavior
- Open the indirect GUI
- Go to ConvFit - load sample and resolution
- Add a Lorentizan
- Do a fit 
- View the full function and the fit will be cleared from the plot

**Comment by martyngigg** [comment]
Fixed by #31484
