### ISSUE TITLE
Muon fitting refactor

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29892]
The muon fitting is very complex and needs simplifying. To refactor this we will:
- Abstract the fitting layout in the fitting tab to make it more 'general'. 
- [ ] There will be a 'basic' fitting layout which can be reused for `Model Analysis` later down the line. This will **not** have `Select Workspaces` or `Simultaneous fit over`.
- [ ] There will be a 'general' fitting layout that is used for all the normal fitting in the fitting tab. This will inherit the 'basic' layout.
- [ ] There will be a 'TFAymmetry' layout for a special kind of fitting with a normalisation factor. This will inherit the 'general' layout.

- After this abstraction and refactor we can remove the TF Asymmetry checkbox completely.
- Switching between TFAsymmetry and normal fitting can be done via a combobox. A complex looking function will no longer be used in the function tree.

The fitting tab and TF Asymmetry tab will both need to work with Single and Double Pulse data.

**Comment by AnthonyLim23** [comment]
As a base line:

The fitting tab will have an option to select the "mode" (we will only consider fitting here, TF asymm will be done in later issue)
The TF-Asymmetry option will be removed from the table
The code will be simplified and stripped back in a way that can be easily overloaded.
It will work with sequential fitting
If double pulse is selected on the home tab, it will do a double pulse fit (I will add an example)

**Comment by AnthonyLim23** [comment]
I’ve had a chance to perform some measurements on boron using ARGUS in both single pulse and double pulse so we can compare the fitting of double pulse and single pulse data in Mantid. The details are below:

Double Pulse
•	71796 – TF20
•	71797 – ZF (50 MEv)
•	71798 – LF20 (25 MEv)

Single Pulse
•	71799 – TF20
•	71800 – ZF (50 MEv)
•	71801 – LF20 (15 MEv – I ran out of time)

**Comment by robertapplin** [comment]
This is a diagram of what the new file structure will look like for the fitting tab.

![image](https://user-images.githubusercontent.com/40830825/106913734-39a77680-66fc-11eb-9023-5c4207de5e10.png)

**Comment by AnthonyLim23** [comment]
looks good. We will also need to add the appropriate contexts. You can probably just create multiple (using inheritance again) fitting contexts. 

The context contains the information from the tab. In theory we should be able to populate the whole GUI by just looking at the contexts.

**Comment by robertapplin** [comment]
File structure diagram 2.0

![image](https://user-images.githubusercontent.com/40830825/107033556-61a2e280-67ad-11eb-8c67-0429741e57d1.png)

**Comment by robertapplin** [comment]
![fitting-tab-structure](https://user-images.githubusercontent.com/40830825/107034514-b7c45580-67ae-11eb-97ec-1275a1a52e3b.PNG)

**Comment by AnthonyLim23** [comment]
For single pulse:
1.	Set time zero to 0.493
2.     Load Argus 71799
3.	Calculate alpha
4.	Load the next run
5.	Do a fit with a StaticKuboToyabeTimeExpDecay and FlatBackground
6.	A = 0.12, Delta = 0.56, Lambda = 0.12 and A0 = 0.09

For double pulse (set on home tab of muon analysis):
1.	Set time zero to `from data file`
2.     Load Argus 71796
3.	Calculate alpha (it is slightly different to single pulse)
4.	Load the next run
5.	Do a fit with a StaticKuboToyabeTimeExpDecay and FlatBackground
6.	A = 0.12, Delta = 0.55, Lambda = 0.13, A0 = 0.09

**Comment by robertapplin** [comment]
Final file structure diagram
![image](https://user-images.githubusercontent.com/40830825/109330644-cf45aa00-7853-11eb-9ade-02fb396394d2.png)

dotted arrow means 1 `has a` 2
full arrow means 1 `inherits from` 2

**Comment by robertapplin** [comment]
I will probably create a design doc or something to detail the changes made to this fitting stuff

**Comment by AnthonyLim23** [comment]
in the TFAsymmetry widget can we have a tick box to fix the value?

**Comment by robertapplin** [comment]
Fix the value of what? I think it would be best to do that separate to the refactor

**Comment by AnthonyLim23** [comment]
> Fix the value of what? I think it would be best to do that separate to the refactor

ah sorry. A tick box to say we want to fix the normalisation to its current value
