### ISSUE TITLE
Add warnings to muon analysis results table

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#29891]
If a sample log is not available in all of the selected workspaces, it should be highlighted in red and the corresponding workspaces in orange.

**Comment by AnthonyLim23** [comment]
this is a nice usability improvement

**Comment by AnthonyLim23** [comment]
we will need some data with warnings, the sample log viewer in mantid does indicate if any have occured.

**Comment by AnthonyLim23** [comment]
for the colours and looking for warnings https://github.com/mantidproject/mantid/pull/28631

for an example of how to colour text https://github.com/mantidproject/mantid/pull/29234

**Comment by AnthonyLim23** [comment]
EMU00112724.nxs_v2  should have an error in Temp_Blade_Cernox

**Comment by sf1919** [comment]
Awaiting further discussion at next Muon Steering Group meeting
