### ISSUE TITLE
Colorfill plot sometimes produces a secondary workspace

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#29900]
### Expected behavior

A colorfill plot in workbench should not produce any other data

### Actual behavior

A separate workspace is generated along with logging that integration was run

### Steps to reproduce the behavior

Load any smaller 2D workspace and plot a colorfill plot.

### Platforms affected
All

**Comment by martyngigg** [comment]
@StephenSmith25 I guess this is because of the changes we made to use the maxpooling?
Would you be able to take a look at this as a priorty over the window on top stuff?

**Comment by StephenSmith25** [comment]
Yeah, my bad - didn't spot it was spitting out a workspace until a couple of days ago 🤦‍♂️ . I had already added a `StoreInAds=False` flag in the colorbar scale PR, but is there a way I can suppress the Integration message, if so I'll create a PR for it shortly.

**Comment by martyngigg** [comment]
No problem. I should have caught that in the review :)
All of the functions have an `EnableLogging` keyword so you can just set `EnableLogging=False`.

Quick question: Is it expected that `Integration` is run twice?

**Comment by StephenSmith25** [comment]
I'm thinking this only occurs when you first open the colorfill (or sliceviewer) as we open it with a default size and then rescale it based on the screen size (/resolution). If you zoom in you'll notice it only integrates once when doing the resampling.
