### ISSUE TITLE
SANS: Allow QXY to have different Qx and Qy rebin strings

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#2991]
sans_feature
This issue was originally [TRAC 2144](http://trac.mantidproject.org/mantid/ticket/2144)

Implement a rectangular 2D Qx-Qy workspace type for SANS2D

This also needs to be supported in the interface.

**Comment by AntonPiccardoSelg** [comment]
This is currently not supported but it should be easy to do. The main thing is to have backwards compatibility with older user files.

**Comment by Mantid-Matthew** [comment]
I am closing this for now pending chcking with instrument scientists whether it is still required.
