### ISSUE TITLE
Fit Script Generator - Ability to generate a Sequential Fit script

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29911]
### Description
The Fit Script Generator interface needs to be able to generate simple fit scripts.

The next steps for developing this interface is:
- Ability to generate a `Sequential` fitting script (with ties and constraints) using the data stored within the model. This will be made possible by completing #30198 
- To do this we should create a new algorithm `GeneratePythonFitScript`
- The Sequential fit can be done by looping over the `Fit` algorithm and passing in the previous function to the next fit.
- Note that each domain MUST have the same fit function when doing a Sequential fit. It doesn't make sense for different domains to have different functions

Before generating a sequential fitting script we should check that each fit function is the same. If it isn't we should show a warning message but then continue to generate a fit script:
```
Note that each domain MUST have the same fit function, including ties and constraints, for a sequential fit. This is 
not the case for the fit functions you have provided.

The sequential fit script will be generated using the fit function in the first domain.
```

**Comment by Pasarus** [comment]
Would it be possible to get some test instructions for this PR?
