### ISSUE TITLE
Fit Wizard - Design/layout ideas

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29912]
### Description
A basic design/layout for the Fit wizard interface should be thought-up/drawn before work begins on its creation.

Any ideas/designs can be added as a comment in this issue.

**Comment by robertapplin** [comment]
![fit-wizard-design-2](https://user-images.githubusercontent.com/40830825/98668056-398b1b00-2347-11eb-9acc-4d7937d5fe9a.png)

**Comment by robertapplin** [comment]
@AnthonyLim23 What do you think about this initial design. Anything that needs changing?

**Comment by AnthonyLim23** [comment]
it looks good. When we meet the scientists (should be soon), I would like you to present it. They can then give feedback.

**Comment by robertapplin** [comment]
Closed because this design was agreed. The design has been implemented in #30068 so this issue is no longer required. Future changes to the design can be raised in separate issues
