### ISSUE TITLE
RuntimeError in figuremanager when renaming a workspace

### ISSUE THREAD

**Issue by joseph-torsney** [mantidproject/mantid#29947]
### Expected behavior
With a plot open, after renaming the workspace for the plot, the window and axes titles should update to match the new name.

### Actual behavior
The workspace is indeed renamed, but the plot is not updated and the following runtime error occurs
```
Error occurred in handler:
Traceback (most recent call last):
  File "C:\Users\ggk63474\programming\mantid\qt\applications\workbench\workbench\plotting\figuremanager.py", line 51, in wrapper
    func(*args, **kwargs)
  File "C:\Users\ggk63474\programming\mantid\qt\applications\workbench\workbench\plotting\figuremanager.py", line 143, in renameHandle
    for ws_name, artists in ax.tracked_workspaces.items():
RuntimeError: dictionary keys changed during iteration
```

### Steps to reproduce the behavior
1. Load a workspace
2. Plot a spectrum
3. Run `rename` on the workspace

### Platforms affected
Found on Windows

Whilst working on #29258, I am seeing that when `rename` runs, both the `SliceViewerADSObserver`s `renameHandle` and `replaceHandle` are fired. Maybe something similar is happening with the figuremanager's observer, and the `replaceHandle` is changing that dictionary?

**Comment by joseph-torsney** [comment]
Remote debugger connected to both `replaceHandle` and `renameHandle` of `FigureManagerADSObserver`!

**Comment by samtygier-stfc** [comment]
I can reproduce on Windows but not Centos7
