### ISSUE TITLE
SANS: Implement an option for summing in multi-period reductions

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#2996]
sans_feature
This issue was originally [TRAC 2149](http://trac.mantidproject.org/mantid/ticket/2149)

Allow users to enter a period string like 

```
 1-4,4,5,6-9
```

This would mean

 Sum periods 1-4 and process as a single period
 process periods 4 and 5 individually
 sum 6-9 and process

This should work in script commands and the UI (single and batch mode).

**Comment by Mantid-Matthew** [comment]
I am closing this now and will recheck with scientists on whether it is still needed.
