### ISSUE TITLE
Indirect Reduction Save Custom Detector Grouping

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#29984]
**Original reporter:** @SpencerHowells

### Description
Indirect Data Reduction needs the ability to save a custom grouping of detectors to a `.map` file in order for it to be easily loaded back into the interface.

This will require:
- Adding a button next to the Custom Grouping option that will save the grouping when clicked.
- Converting the custom group string into a `GroupingWorkspace`
- Modification of the `SaveDetectorsGrouping` algorithm to allow the saving of `.map` files.

### Platforms affected
All

**Comment by robertapplin** [comment]
@SpencerHowells does indirect ever use `.xml` files for detector grouping files, or is it only ever `.map`?

**Comment by SpencerHowells** [comment]
@robertapplin the only feedback/comments I’ve had is from some of our scientists is that they use the .map because a text file is easier to use. We also think that for that reason it would be best for the users.
