### ISSUE TITLE
Muon Editing Constraints crash

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29994]
**Original reporter:** Peter Baker / ISIS

### Expected behavior
Editing constraints on parameters in Muon Analysis is handled smoothly.
### Actual behavior
After a simultaneous fit, editing constraints can crash and close workbench
### Steps to reproduce the behavior
- In the Muon Analysis Interface, load 3 consecutive runs e.g. `EMU 62250-62252`
- In the fitting tab, set the fit to simultaneous (and I also changed Run to Group)
- Right-click and add some fit function e.g. `MuonExpDecay`
- Right-click and fix one of the parameters
- Click `Fit`
- Now right-click on the fixed parameter and select `Constraints > Custom`
- Set LowerBound to something, I chose `9`. Hit enter.
- Mantid now hard crashes (closes).
### Platforms affected
I assume all, found on Windows, Workbench 5.1.0, but I can confirm its also a problem on 5.1.1

Steps from Peter:
```
I think this was:
-          Load three consecutive muon runs into Muon Analysis interface
-          Conduct simultaneous fit with all parameters fixed apart from the fields, which were fixed individually
-          Right click on a parameter, choose Constraints -> Custom.

I think it crashed at that point but I might have provided the constraints before it crashed.
```

**Comment by Matt-Cumber** [comment]
Looks like trying to change constraints in general causes a hard crash
