### ISSUE TITLE
Instrument view closes whenever any workspace is deleted

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#30005]
### Expected behavior
Deleting a workspace should not affect an unrelated instrument view.

### Actual behavior
When any workspace is deleted, any instrument view currently open is closed.

### Steps to reproduce the behavior
- Create two workspaces.
- Show the instrument view of one of them
- Without closing the instrument view, delete the other workspace.
- The instrument view is now gone

Alternatively, 
```
from mantidqt.widgets.instrumentview.api import get_instrumentview

ws = CreateSampleWorkspace()

# setup the instrument view
iview = get_instrumentview(ws)

iview.show_view()

a_completely_unrelated_workspace = CreateSampleWorkspace()
DeleteWorkspace(a_completely_unrelated_workspace)
```

### Platforms affected
Tested on Ubuntu 20

**Comment by KedoKudo** [comment]
A solution is found (see https://code.ornl.gov/sns-hfir-scse/spectroscopy/spectroscopy/-/issues/62 for more details) and scheduled to be implemented by a dev team member within the current iteration.
The associated branch will be 
- https://github.com/mantidproject/mantid/tree/30005_instrument_view_close_error for `ornl-next`
- https://github.com/mantidproject/mantid/tree/30005_instrument_view_close_error_master for `master`

> Note: the two branches do not contain the fix yet.  A team member will implement the fix at a later date.
