### ISSUE TITLE
Replace EnggCalibrate/Full algorithms with PDCalibration

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#30048]
PDCalibration is an existing C++ implementation that is widely used (and well tested) that performs a large chunk of the Calibration currently done in python in the EnggCalibrate and EnggCalibrateFull algorithms. The output of PDCalibrate is also compatible with other algorithms for unit conversion which should replace usages of ConvertUnits in the Engineering UI code.

**Comment by DannyHindson** [comment]
@RichardWaiteSTFC - I've just moved this issue that Tom's working on into the new sprint. I think you said you had a python script that describes the required calibration workflow. Please could you zip it up and attach it here?

**Comment by RichardWaiteSTFC** [comment]
Thought I'd link this here so we don't forget - #30796 suggests small change to proposed workflow in script (i.e. don't use EditInstrumentGeometry)
