### ISSUE TITLE
LoadElementalAnalysisData fails if directory contains a . character

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#30041]
### Expected behavior

`LoadElementalAnalysisTest` & `LoadPartialElementalAnalysisTest` should pass for all valid directories.

### Actual behavior

The [Ubuntu system tests](https://builds.mantidproject.org/job/master_systemtests-ubuntu-18.04/402/) have the data in a directory like `/jenkins_workdir/workspace/master_systemtests-ubuntu-18.04/ExternalData/Testing/Data/SystemTest`. When [LoadElementalAnalysisData.py](https://github.com/mantidproject/mantid/blob/master/Framework/PythonInterface/plugins/algorithms/LoadElementalAnalysisData.py#L83) attempts to deconstruct the filename it does so with the whole path and the `.` in the directory gives an extra item in the list and the `TYPE_KEYS` lookup fails.

The deconstruction should first just take the filename part of the path and then do the processing.

### Steps to reproduce the behavior

I was able to reproduce this by creating a temporary directory with a `.` in it:

```
cd <mantid_build_dir>
mkdir temp.dir
```

copying all of the `ral*.dat` files from `ExternalData/Testing/Data/SystemTest` into it along with `Testing/SystemTests/tests/framework/reference/ElementalAnalysisLoad.nxs` & ``Testing/SystemTests/tests/framework/reference/PartialElementalAnalysisLoad.nxs and running the tests as:

(on Windows)
```
systemtest -C BUILD_CONFIG -d %CD%\temp.dir -R LoadElementalAnalysis
```
where BUILD_CONFIG is the build type last built.

(on Linux/mac)
```
systemtest -d ${PWD}\temp.dir -R LoadElementalAnalysis
```

### Platforms affected
All

**Comment by SpencerHowells** [comment]
@martyngigg There is also a problem with a space. On Windows it will occur if you use the default folder ‘My PC’.

**Comment by martyngigg** [comment]
@SpencerHowells Thanks for finding that.
