### ISSUE TITLE
Global updates in muon analysis

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30054]
When doing a simultaneous fit in muon analysis (after a fit), updating one of the globals and then changing group will cause the parameter to reset. 

This might also occur in indirect. @robertapplin could you please check?

**Comment by robertapplin** [comment]
I could not replicate this in Indirect

**Comment by robertapplin** [comment]
Replicated in Muon Analysis by:
1. `MUSR` run `62260`
2. Fitting tab. Click Simultaneous fit
3. Add `GausOsc` function
4. Make `Sigma` Global
5. Click `Fit` and wait
6. Change the visible dataset using `>>`
7. Update the Sigma parameter.
8. Change visible dataset again. The global parameter resets.
