### ISSUE TITLE
Muon Analysis - Global Parameter Slightly different across datasets after fit

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30058]
### Expected behavior
A global parameter should be the same across all fitted datasets.

### Actual behavior
The global parameter is very slightly different when switching between datasets.

### Steps to reproduce the behavior
1. `Muon Analysis` interface
2. `MUSR` instrument. Runs `62260-62261`
3. `Fitting` tab. Add `GausOsc` function.
4. Tick Simultaneous Fit
5. Mark `Sigma` parameter as `Global`
6. Click `Fit` and wait
7. Switch between Run numbers. The `Sigma` is very slightly different. After switching Run numbers the first time, the sigma will remain the same when you switch back to `62260`.

![image](https://user-images.githubusercontent.com/40830825/100092787-8b0ace00-2e4e-11eb-8811-ce75f173e37f.png)

![image](https://user-images.githubusercontent.com/40830825/100092839-9e1d9e00-2e4e-11eb-8da9-7708d66c68f2.png)

### Platforms affected
Found on windows, all I assume.

**Comment by AnthonyLim23** [comment]
Ah this is ok. The simultaneous fit is over the run (fwd, bwd, top, bottom) for a given run. The 2 screen shots are of different runs.
