### ISSUE TITLE
Ragged workspace double click crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30071]
If you create a ragged workspace then double click on it in workbench, Mantid will give a terminate message box.

**Comment by martyngigg** [comment]
Hmm. I thought, @robertapplin fixed this in #29589? Is it a different error?

**Comment by robertapplin** [comment]
I think this is a different error than was fixed in #29862 . In #29862 it was erroring when right clicking the ragged workspace and selecting colorfill plot

**Comment by AnthonyLim23** [comment]
It does seem to be different

**Comment by martyngigg** [comment]
My apologies, I got the pull request link wrong. I fixed the issue link above to refer to the one where we did the padding for the display.
@AnthonyLim23 Do you expect someone in your team to be able to take a look at this?

**Comment by AnthonyLim23** [comment]
Not got anything planned yet. @robertapplin do you think you could fix it?

**Comment by robertapplin** [comment]
Yep I'll have a look

**Comment by robertapplin** [comment]
@AnthonyLim23 @martyngigg What is the expected behaviour for a matrixworkspace? To plot colorfill?

**Comment by AnthonyLim23** [comment]
I thinks its plot

**Comment by martyngigg** [comment]
Was it not to bring up the dialog to ask what to plot? We don't know what they want to do yet: 1d, 2d plot but the dialog has all of the options.

**Comment by robertapplin** [comment]
Yes I think your right. We want the dialog which asks what to plot
