### ISSUE TITLE
TF Asymetry causes an error with simultaneous fit over in muon analysis.

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30149]
TF Asymetry causes a failure when the function is changed. most ways of doing this are dissabled but but using the simulatinous check box you can produce this error.

1. open muon analysis.
2. load MUSR62260.
3. go to fitting tab.
4. add a flat background.
5. check `TF Asymmetry Mode`.
6. check `Simultaneous fit over`.
7. change combo box from `run` to `Group/Pair` This produces an error.

> To be consistent with the rest of the behaviour for TF Asymmetry mode we should not allow the user to change the simultaneous fit options. Part of the problem is the function form changing. We can do this by doing a check when things are changed and if TF asymmetry mode is on we can give a warning and reset it.

Anthony

**Comment by AnthonyLim23** [comment]
we should also prevent the user from changing if it is over run or groups/pairs while in TF-Asymmetry mode too
