### ISSUE TITLE
Co-add in Muon Analysis is broken in multiple ways

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30148]
Found in Manual testing the co-add function in Muon analysis produces multiple errors or bugs

1. open muon analysis
2. load EMU20889-20900 and check co-add
3. go to the fitting tab and check `Simultaneous fit over` this raises an index error

--

1. open muon analysis
2. load `EMU20918-20920`
3. in fitting add a flat background
4. fit, it won't be a good fit but that is expected
5. check co-add
6. click fit, you get an error that the function is empty depite having a background.

--

Results table can only have the result from a single fit, so combining ones for co-add and single fits can't be done.

--

When you co-add runs the Sequential Fitting tab uses the run number for only the first run. overwriting single fits

**Comment by AnthonyLim23** [comment]
In muon analysis:
1. The sequential fitting tab has the wrong run numbers
2. In the fitting tab selecting the simultaneous option and pressing fit causes an error
