### ISSUE TITLE
Plot Settings Error Every Resets On GUI To 1 When Applied

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30155]
The value for error every is correctly saved in the back end it is just not correctly displayed.

### Expected behavior
The value in the GUI should stay as what the users selected

### Actual behavior
The value on the GUI is reset to 1 even if the correct value is applied to the plot

### Steps to reproduce the behavior
1. Load some data
2. Plot a spectrum
3. Open plot settings
4. In Curves, unhide error bars and update error every to something different to 1, then click apply
5. Notice the plot updates but the value on the GUI is 1 again
6. If you try click apply again without doing anything nothing happens, suggesting the value is not actually 1 even if 1 is shown

### Platforms affected
all presumably (found on Mac)

**Comment by DanielMurphy22** [comment]
I cannot reproduce this on Windows, but I can on Mac so setting it to Mac only. This is very odd.

**Comment by DanielMurphy22** [comment]
This is not broken in 5.1.1 so we'll see if we can fix for this release!

**Comment by DanielMurphy22** [comment]
To whoever gets assigned to fix this, look at the error report from Malcolm on 23/12/2020 and decide if this is linked or not. He may have gotten Mantid into an odd state, but the property `errorevery` features front an centre in the stacktrace.

**Comment by Matt-Cumber** [comment]
has been fixed by #30359
