### ISSUE TITLE
Changing Scale For A Waterfall Plot Does Not Update All Curves

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30154]
### Expected behavior
All curves should use the same axis, like 1D plots

### Actual behavior
Only updates the first curve 

### Steps to reproduce the behavior
1. Load some data
2. Plot multiple spectra
3. Right click and change plot type to waterfall
4. Change axis scale
5. Check what happens with plot type as 1D for what should happen

### Platforms affected
all presumably

**Comment by DanielMurphy22** [comment]
Good find. This was also broken in 5.1.0.

**Comment by Matt-Cumber** [comment]
Still exists
