### ISSUE TITLE
Phasequad and co-add

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30169]
Phasequad should work with co-add

**Comment by AnthonyLim23** [comment]
@Matt-Cumber how long do you think this fix would take?

**Comment by Matt-Cumber** [comment]
> @Matt-Cumber how long do you think this fix would take?

The problem is the co-added string cannot be converted to a run number, but I haven't looked at what code needs to change yet. I would estimate 1 day at the moment
