### ISSUE TITLE
Prevent overplotting if axis type is different

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#30204]
This issue was observed in #30161
### Expected behavior
You shouldn't be able to overplot a spectrum plot over a bin plot as the axes are not compatible. 
### Actual behavior
You can.
### Steps to reproduce the behavior
Load some data
Click show data
Select a column of the data and click plot bin
Now right click on the workspace and overplot a spectrum
The plot will update, but the previous bin plot will not be correct
### Platforms affected
All.

**Comment by gvardany** [comment]
I'd just add here that you should be able to overplot a bin plot over another bin plot.
