### ISSUE TITLE
Rebin functionality in Elemental Analysis GUI

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#30214]
The Grouping Tab in the Elemental Analysis GUI (#29382) requires additional functionality to create Rebin workspaces using information provided through the rebin and rebin_options column of the table. This follows on from PR #30199 .

In addition to this the user dialog input boxes for undertaking a rebin need to be reworded to make it clear the rebin will create a new, separate workspace and not affect the raw data.

The Grouping MVP could further be tidied up by replacing the Observers with GenericObservers.

**Comment by sf1919** [comment]
@tolu28-coder - were you able to tackle these issues when you took over work on the Initial PR for the Elemental Analysis Grouping Tab (#30199)?

**Comment by tolu28-coder** [comment]
Yes i was able to add the rebin functionality and add the generic observers

**Comment by sf1919** [comment]
Did you also reword the dialog input boxes to avoid confusion about how it works?

**Comment by sf1919** [comment]
If you could do that so we can close this issues that would be fantastic. I'll assign this one to you in the meantime.
