### ISSUE TITLE
Fit algorithm assumes m_minimizer->costFunctionVal() == chi_sq

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#30226]
At the moment, the fit algorithm always creates a output chi sq property based on the final value of the cost function, accessed through the minimizer. The issue is that the cost function value does not necessarily represent chi square, for instance in possion fitting. An immediate consequence of this is that running the two Levenberg minimizers with 2 iterations and fixed parameters, will produce different chi square values, despite almost identical fitting parameters. 
### Expected behavior
Both LM minimzers should give the same chi-sq value if they are effectively fitting the same function.
### Actual behavior
They don't
### Steps to reproduce the behavior
Create some test data with:
```
# Create a data set
x = np.linspace(0,1,100)
delta = np.random.uniform(-0.1,0.1, size=(100,))
y = 2 * x + 1 + delta
e = 0.1*np.sqrt(y)
ws = CreateWorkspace(DataX=x, DataY=y, DataE=e)
```
Now plot and fit the data with a linear background. Note the chi-sq value and fit parameters. Fix one of the parameters and change max iterations to two. Change to the LM-MD minimzer. Run the fit. You'll note that chi_sq has basically halved, while the parameters have barely changed.

This issue occurs as for the plain LM minimzer we leave it to GSL to find chi-sq value, whereas for our LM minimzer we assume that the cost function value is chi-sq, but it’s not. This underestimation of the chi-sq value will affect the calculated fit confidence bands.

### Platforms affected
All

**Comment by martyngigg** [comment]
Closing this as the correctness of the answer is not affected and it is how the system works.
