### ISSUE TITLE
Indirect interfaces display issues

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30221]
### Description
The following indirect interfaces are squashed:
- Diffraction
- Corrections

It might depend on screen resolution.

### Platforms affected
Found on Windows, probably all

**Comment by SpencerHowells** [comment]
@robertapplin Corrections could do with a slider on the right so that the gui height can be reduced for small screens.

**Comment by Harrietbrown** [comment]
I'm not seeing and squashing in the deffraction interface as it already has a scroll area. corrections however i can see the squashing when i lower my resolution
