### ISSUE TITLE
Mantid crash in IPython on Windows

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30297]
Go to the IPython window in workbench

type `from mantid.kernel` then press tab to auto complete
CRASH!

![image](https://user-images.githubusercontent.com/25006392/104038533-2670bc00-51cd-11eb-942a-7beb379cf99b.png)

**Comment by martyngigg** [comment]
This is a duplicate of #11286 and only affects Debug builds so I'm going to close this one.
