### ISSUE TITLE
Colourfill plot with bin width normalisation causes project save to fail

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#30315]
### Expected behavior
If project recovery runs while a colourfill plot with bin width normalisation set, it should save the interface successfully.

### Actual behavior
It does not. `Unknown error occurred. Full detail: Object of type Normalize is not JSON serializable`

Edit: this also seems to happen even after closing the plot

### Steps to reproduce the behavior
Plot a colorfill plot, right click -> normalisation -> bin width, wait for project recovery to trigger and check the logger

### Platforms affected
Confirmed on windows, assumed on all

**Comment by martyngigg** [comment]
Fixed by #30350
