### ISSUE TITLE
Revise Indirect Data Analysis documents

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30325]
We have been made aware that there are users doin QENS that are not aware that they can make use of our indirect tools. this issue is to revise the documentation of the interface to try and make it more clear what it is capable of.

Report to @SpencerHowells

**Comment by AnthonyLim23** [comment]
I think we should just add a few docs to the direct part that link to the indirect docs

**Comment by Harrietbrown** [comment]
as part of this I should look into #22837

**Comment by AnthonyLim23** [comment]
@Harrietbrown and @SilkeSchomann have we done this or do we have more left to do?

**Comment by AnthonyLim23** [comment]
if we have some time can we work on these for the release?

**Comment by Harrietbrown** [comment]
Elements to focus on for this issue are:

Create interface structure doc for Inelastic data Manipulation like what we have for Indirect Data Analysis https://github.com/mantidproject/mantid/blob/main/dev-docs/source/IndirectDataAnalysisFileStructure.rst

How to add a fit function in data analysis tabs

How to use the workspace data table widget.
