### ISSUE TITLE
Default load path on Fitting tab not correct if run number used during Focus

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#30333]
The default path in the "Focused Run Files" on the fitting tab is missing a "User" level if the last focus had an RB number specified. This gave a "file not found" message when hitting Load

On Windows for example, the Focus creates files in this folder if a run number is used:

C:\Users\iao46725\Engineering_Mantid\User\\\<run number>\Focus\

**Comment by martyngigg** [comment]
Can I just check if we would still like to get this into 6.0?

**Comment by DannyHindson** [comment]
> Can I just check if we would still like to get this into 6.0?

I'd like to get the fix done in this release sprint and into the nightly build but I don't think its essential that it goes into the release. @RichardWaiteSTFC, @clayton-tom - do shout if you disagree
