### ISSUE TITLE
Remove github api key

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#30357]
The following was sent by our friends at GitHub
```
As a precautionary measure, we have revoked the token. You will need to generate a new token for the app to authenticate to GitHub.
Here are a couple of steps you can do to ensure your account security has not been compromised:
* Review any unauthorized applications, and remove any you don't recognize:
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-oauth-apps
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-github-apps
* Review your security log to ensure that no malicious activity has occurred: https://docs.github.com/articles/reviewing-your-security-log/
The commit in question is at https://github.com/mantidproject/mantid/blob/eaf776a0c1d54961b8d470f43a9122b6c69d51f2/Framework/Kernel/CMakeLists.txt
Please feel free to contact us at https://github.com/contact if you have any questions or concerns.
Thanks,
GitHub.com
```

The effect is that `DownloadInstrument` fails. #30347 changes that the code will correctly fall-back to using an unauthenticated connection.

Current design to fix the problem (needs updating):
* Remove the key from it's current location
* Move key to be provided by `ConfigService` as `GitHubToken`. User/system can supply new key through `ConfigService`
* If `ConfigService` doesn't have a token, an empty string will be returned
* `GitHubAPIHelper` will interpret empty string to mean only try unauthenticated web calls
* Default key is inserted in templated file through cmake variable. The variable will be supplied through an environment variable injected during the build. The default key (in cmake) is an empty string.

**Comment by martyngigg** [comment]
Fixed by #30566
