### ISSUE TITLE
Automatic plots with drill

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#30393]
- [ ] plots - first create mini-modules for standard plots like [directtools], then integrate them in drill post processing (https://docs.mantidproject.org/nightly/techniques/DirecttoolsPythonModule.html)
- [ ] implement generation of scripts - a snippet of code that loads the rundex into json, loops over its entries and calls *AutoProcess in it
- [ ] Implement load/save of rundex together with the project (save the rundex, and its path in the project.mantid)

**Comment by martyngigg** [comment]
@tweber-ill @MathieuTillet @gui-co I don't know if anyone at ILL has sight of this issue now as it looks like Gagik created it but it's not assigned...
