### ISSUE TITLE
Reset View button makes the user unable to move the camera

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#30394]
In the instrument viewer, using the reset view button in certain circumstances makes the user unable to move the camera.
### Expected behavior
After resetting the view, the user should be able to drag and move as usual on the render tab
### Steps to reproduce the behavior
- Open an instrument in the instrument viewer
- Set the view to Full 3D
- Go to the draw tab and check `Draw Rectangle`
- Go back to the render tab and click `Reset view`
- Try moving around

**Comment by SilkeSchomann** [comment]
Fix merged into release-next
