### ISSUE TITLE
ErrorReporter: handle large text inputs better

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#30402]
For the errorreporter, there are problems when the character limit for a textBox (3200) or stacktrace (10000) is exceeded. This has been found by recent linode app errors (see slack channel).

### textBox
Currently trying to send a report with text > 3200 characters fails with status 500:
![Screenshot 2021-01-18 at 16 15 45](https://user-images.githubusercontent.com/55980573/104941710-511bfb00-59ab-11eb-984c-4a956774962b.png)

This is okay, but it would be better to tell the user that the word limit for the textBox has been exceeded. 

### stacktrace
However, for a stacktrace > 10,000 characters, it is probably worth taking the start and end (most useful bits) of the stacktrace and leaving the middle.

Worth linking this to a broader issue: https://github.com/mantidproject/mantid/issues/28083

**Comment by ConorMFinn** [comment]
This could do with being resolved. Copying, say, a stack trace from the MacOS error reporter can easily exceeed the 3200 character limit and the error reporter reports the server error and closes without letting the user amend their message. This isn't great UX and could result in useful crash information never making it to us.

**Comment by DanielMurphy22** [comment]
Reopening as just received the same error in the linode-app-errors Slack channel: `django.db.utils.DataError: value too long for type character varying(3200)`

**Comment by jhaigh0** [comment]
Is there a good way to create a long error message to test this?

**Comment by ConorMFinn** [comment]
If you mean for writing unit tests, you can just do `test_string = "x" * 10001`. If you need it outside, you could run a little python script to add that to the clipboard:
```
import subprocess 
subprocess.run("clip", text=True, input="x"*10)
```
I think it's `clip` for windows, it's `pbcopy` on mac

**Comment by DanielMurphy22** [comment]
If you're looking to live test MantidWorkbench, I think the following is possible: 
Pretty sure when the errorreporter appears for the user we have created a stacktrace.txt file in appdata. This is read into the Show details dialog on the errorreporter. When the errorreport is sent, this locl file is renamed stacktrace_sent.txt
https://github.com/mantidproject/mantid/blob/main/qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py
