### ISSUE TITLE
ALC File Search Speed Improvements

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30408]
Currently if a user wanted to load say 200 runs, the interface would search for all 200 runs. Instead of doing this, it has been suggested we only need to search for the start and end files of a range and any comma separated files, e.g. Entering `62260-5,62267,62269,62271-75`

Previous search would be for all **13** files, instead we want to only search for **6** files; 62260, 62265, 62267, 62269, 62271, 62275. 

This should hopefully have big performance improvements particularly when entering large ranges which can reduce searches of tens or hundreds of files to just 2. This will only work on the assumption that the files in between the start and end runs of ranges all have the same directory such that we can construct the rest of the paths. 

I have put together some of the potential changes that could/should be made:
1. Instead of using the standard filefinderwidget, would want to potentially create an alc specific one 
2. Should be hesitant at creating a whole new widget as the current filefinder handles multithreading and archive searching, so maybe just inheriting is the way forward
3. You would then want to override the function `findFilesGetSearchText` to return the reduced number of files (see example above). Make sure to check what format is needed for the search. A problem with this is knowing which files are part of a range and which are not, as we would need to ensure the start and end files have been found in the same directory. separate ranges or files can be loaded from different directories to allow for comparing different cycles (PlotAsymmetryByLogValue would need to be changed as there is a check all files are in same directory currently)
4. There will be a problem when calling `getFilenames` on the filefinderwidget, as the filesfound will no longer be all the files wanting to be loaded, so from the files found you would have to construct the rest of the files to be loaded
5. Once you have constructed all the files the rest should be the same, load times should not change

By creating a new widget for finding files it may be easier to solve #30067

I tried loading MUSR62260-62460 and to search for the files took ≈50 seconds, so any changes made should aim to be significantly faster than this

**Comment by AnthonyLim23** [comment]
The other GUI's wont use this as they process the data immediately. 

Sounds like a nice set of changes and the inheritance should cut down on the amount of work. It should also be easier to plug in too. 

Could you add an estimate for how long you think this will take?
