### ISSUE TITLE
Sliceviewer ADS observer issues

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#30426]
This epic is an umbrella for issues to do with the sliceviewer and ADS updates. I'd like to collect all info about these (including closed issues and PRs) in one place to make sure we don't break things that have already been fixed. You'll need the ZenHub browser plugin to see the full info.

1. Firstly, the ADS observer was added:
  *Issue* #29258
  *PR* #29980
1. There was a problem where an algorithm that was refreshing the Sliceviewer would try to run another algorithm. A delayed_refresh was added to let the algorithms complete before the Sliceviewer was updated:
  *PR* #30242 
1. An additional 1msec delay was needed to fix this on all OS's:
  *PR* #30261 
1. Additional handling was added for when peaks workspaces are modified:
  Issue #30308
  *PR* #30375 
1. The delayed refresh caused a race condition where the view could be closed before the refresh was called. A workaround was added to check the view still exists before continuing with the refresh, but this was quite hacky:
 Issue #30406
 *PR* #30457 
1. Workspace locking was added to refresh_view to avoid a workspace being modified in another thread while Sliceviewer was using it. This PR also removed the delayed_refresh. The reason stated in one of the commits was "it is no longer required now qappthreadcall is non-blocking"
  *Issue* #31367
  *PR* #32204 
1. As part of some other work to refactor Sliceviewer, commit [c4887d3e74f](https://github.com/mantidproject/mantid/commit/c4887d3e74f) improved the fix for the race condition. While no longer strictly necessary, this better version of the check made sense to keep.
1. A deadlock situation could occur if an algorithm running in the python interpreter locked a workspace, and caused an ADS update where Sliceviewer refresh would try to lock the same workspace in the same thread.
 *Issue* #33882
 *PR* #33968
1. The non-blocking QAppThreadCall caused a race condition where running an algorithm with multiple output workspaces could mean that the workspace name got overwritten in the replace-handle before the refresh was called.
  *Issue* #34125

**Comment by martyngigg** [comment]
@gemmaguest I think we've covered all of the issues here now? Can I close this one?

**Comment by gemmaguest** [comment]
> 
> 
> @gemmaguest I think we've covered all of the issues here now? Can I close this one?

Fantastic, yes, thanks! :+1:

**Comment by gemmaguest** [comment]
The latest child issue is now closed so this is all complete
