### ISSUE TITLE
Simple group subtraction in Muon Analysis

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#30420]
This issue is to add simple subtractions for groups in the MA GUI's. This will assume groups and only groups.

**Comment by AnthonyLim23** [comment]
Instead of using the more expensive MuonGroupingAsymmetry we can just subtract the asymmetry groups directly. I have verified this gives the same result and it matches the old GUI too. Can also rebin afterwards, the operations of subtraction -> rebin and subtraction commute.

**Comment by martyngigg** [comment]
Fixed by #30465
