### ISSUE TITLE
Make sure all Qt4 tests are also ran in Qt5

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30423]
With the removal of mantidplot all Qt4 tests are not being ran, we need to make sure that all previous tests that we still need to be ran are being run in Qt5 as well

**Comment by Harrietbrown** [comment]
`MantidQtWidgetsPlottingTest` and `MantidQtWidgetsSliceViewerTest` are not in Qt5 at the moment.

**Comment by Harrietbrown** [comment]
It has also been noted that in `MantidQtScientificInterfacesTestQt5` the cmake list has a different list of test files for qt4 and qt5

**Comment by peterfpeterson** [comment]
From [scripts/test/CMakeLists.txt](https://github.com/mantidproject/mantid/blob/master/scripts/test/CMakeLists.txt#L30-L37):
* SANSBatchModeTest.py
* SANSCentreFinderTest.py
* SANSCommandInterfaceTest.py
* SansIsisGuiSettings.py
* SANSReducerTest.py
* SANSReductionStepsUserFileTest.py
* pythonTSVTest.py

**Comment by Matt-Cumber** [comment]
ALC tests will be covered by #30466

**Comment by martyngigg** [comment]
> `MantidQtWidgetsPlottingTest` and `MantidQtWidgetsSliceViewerTest` are not in Qt5 at the moment.

Neither of these should need porting as they'll be dropping in favour of the Qt5 alternatives.

**Comment by martyngigg** [comment]
> It has also been noted that in `MantidQtScientificInterfacesTestQt5` the cmake list has a different list of test files for qt4 and qt5

Do we know if there are more missing than the ALC ones?

**Comment by martyngigg** [comment]
I'm going to remove the "High Priority" label as we wouldn't hold the release up for it. The indirect tests are in now and that was a big chunk and Matt is dealing with the ALC ones. Let's put this as a maintenance task that might be best addressed as the Qt4 targets are removed where we can spot what files are just deleted.

**Comment by martyngigg** [comment]
> From [scripts/test/CMakeLists.txt](https://github.com/mantidproject/mantid/blob/master/scripts/test/CMakeLists.txt#L30-L37):
> 
>     * SANSBatchModeTest.py
> 
>     * SANSCentreFinderTest.py
> 
>     * SANSCommandInterfaceTest.py
> 
>     * SansIsisGuiSettings.py
> 
>     * SANSReducerTest.py
> 
>     * SANSReductionStepsUserFileTest.py
> 
>     * pythonTSVTest.py

I don't know much about these. @DavidFair Would you be able to comment at all?

**Comment by DavidFair** [comment]
AFAIK these should be running in Qt4 and Qt5 as most of the other SANS GUI tests are and there shouldn't be anything preventing them running, however they predate me. Does this mean they aren't running on Qt 5 then?

Really they should be with the other SANS GUI tests rather than separate but that's a different problem of organisation.

**Comment by peterfpeterson** [comment]
Look at the `CMakeLists.txt` that Martyn pointed out. Those tests are currently only run in qt4. I don't know if it is because they don't work under qt5 currently, but that file suggests they didn't always work with qt5. This may be a simple job of removing the `if (ENABLE_WORKBENCH)` and fixing what is broken.

**Comment by martyngigg** [comment]
Thanks for checking @DavidFair. I'll have a quick look today at just putting them in the Qt5 bunch and hopefully things will run 🤞🏻

**Comment by martyngigg** [comment]
It looks good. The pythonTSV test is the only Qt4-only one and that's a MantidPlot thing anyway.

**Comment by martyngigg** [comment]
For me to keep track.

Items to look at:
  - qt/scientific_interfaces/CMakeLists.txt: Missing tests in the Qt5 list
  - qt/widgets/plotting: Missing Qt5 test target

Old sliceviewer has been completed removed so should no longer exist anyway.
