### ISSUE TITLE
EngDiff UI fitting tab error when loading focussed data not having expected logs present

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#30427]
### Expected behavior
If focussed data did not have one or more log values selected in the settings, then the would be some warning shown and the log value would be filled with NaN in the tables generated when loading.

### Actual behavior
Tries to calculate the averaged value and prints an error to the log (the log tables are still filled with NaN entries).

### Steps to reproduce the behavior
(1) Open the fitting tab in the EngDiff UI
(2) Load in run 193749 in this file [ENGINX_193749_bank_1.zip](https://github.com/mantidproject/mantid/files/5842530/ENGINX_193749_bank_1.zip)

**Comment by martyngigg** [comment]
Fixed by #30428
