### ISSUE TITLE
Sliceviewer not plotting data correctly when axes transposed

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#30446]
### Actual behavior
Depending on the level of zoom and whether the peak is centred in the plot, when the axes are swapped the peak is shifted.

### Steps to reproduce the behavior
(1) run this script to generate fake data and a peak at (1,1,1)
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='Q_lab_x,Q_lab_y,Q_lab_z', Units='U,U,U',
                       Frames='QLab,QLab,QLab',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
FakeMDEventData(ws, EllipsoidParams='1e+06,1,1,1,1,0,0,0,1,0,0,0,1,0.01,0.04,0.02,1', RandomSeed='3873875')
# add peak
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
SetUB('peaks', 1,1,1,90,90,90)
pk = p.createPeak([1,1,1])
p.addPeak(pk)
```
(2) Open sliceviewer and overlay the peaks workspace
(3) Zoom in on the peak and swap the X and Y axes - the peak might shift (it seems to be more obvious if the peak is not centred in the plot)

![image](https://user-images.githubusercontent.com/55979119/105395757-fc7cb800-5c16-11eb-99ef-74710cdf8529.png)

**Comment by martyngigg** [comment]
Fixed by #30473
