### ISSUE TITLE
Set the column limit of C++ source to 120 characters

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#30447]
Currently, the column limit of C++ source is set by the LLVM style. That is 80 characters.

[Results from a poll in Slack/Mantid/General](https://mantid.slack.com/archives/C02J4MMGA/p1611107121015900) have a majority going for 120 characters

Clang [File configuration](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)

Refs #30265

**Comment by martyngigg** [comment]
Can we close this now as I think this has been sorted with the `pre-commit` move?

**Comment by jmborr** [comment]
Sure, I had forgotten all about it !
