### ISSUE TITLE
ALC Data Loading Layout Changes

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30443]
**Original reporter:** Stephen Cottrell / ISIS

The ALC has recently had changes to the layout for this release, since beta testing it has been agreed to revert some of these changes and introduce a new group box for log values to reduce the clutter of the data box. Additionally some kind of message that the plot can be right-clicked for plot settings should be added

**Comment by martyngigg** [comment]
Fixed by #30458
