### ISSUE TITLE
ALC Baseline Modelling Interface StartX/EndX Bug

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30442]
**Original reporter:** Stephen Cottrell / ISIS

### Expected behavior
You should not be able to move startx/endx beyond first and last good data limits, which is the current case for the general fitting window in workbench

### Actual behavior
You can move the limits beyond first and last which doesn't make sense for the fit and can result it not being able to drag them anymore without manually resetting them

### Steps to reproduce the behavior
1. Open ALC
2. Load some data (HIFI71480-500)*
3. Change log to field_main
4. Change max time to 12
5. Load data
6. Go to baseline modelling interface
7. Add polynomial fit function n=2
8. Add a section
9. Drag startx and endx beyond the first and last data values
10. This should not be possible
11. Click fit
12. You might now have one of the markers not be able to be dragged anymore

*Reduced amount of data used in beta test

### Platforms affected
all

**Comment by martyngigg** [comment]
Fixed by #30454
