### ISSUE TITLE
Record individual function usage statistics

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#30451]
It would be good to record the individual function usage statistics - At the moment we have circa. 130 functions, so it would be beneficial if we could reduce the bloat by removing unused functions.

**Comment by SpencerHowells** [comment]
@StephenSmith25 This needs to be done with care. Usage of functions depends on the science that has been done by the users which is unpredictable. Instrument scientist will need to be consulted.

**Comment by StephenSmith25** [comment]
Not to worry, any actions taken will be carefully considered and I'll make sure the relevant parties are consulted. This was just motivated by having to write documentation this week for several undocumented functions, which nobody knew anything about - not even the scientific group in that area. I believe taking stock of what we have and what's being used will be a helpful statistic to have.
