### ISSUE TITLE
Spectra Index error in indirect FqFit with EISF and Width

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30464]
Switching between Width and EISF in the add multiple dialogue in FqFit can produce a warning.

1. Open indirect, 
2. go to fqfit,
3. multiple input,
4. add workspace,
5. load file wioth both eisf and width, switch to eisf and add spectra. 
5. a warning pops up about spectra index

**Comment by AnthonyLim23** [comment]
@Harrietbrown does this need to be fixed for this release?

**Comment by martyngigg** [comment]
The assumption is this is not a priority for 6.1 but we can reassess later.

**Comment by Harrietbrown** [comment]
This issue seems to have been fixed by another PR. I am going to close it.

**Comment by Harrietbrown** [comment]
This is still an issue that should be fixed for release.

1.	open f(q) fit
2.	go to multiple input
3.	load data with both Width and EISF but only add the width
4.	change the function to something
5.	remove the spectra
6.	try to add the EISF data and you are unable as the list of entries is blank
7.	reloading the workspace will show the list of available eisf but adding gives an error related to the spectra index
8.	if you try and change the function after adding an EISF mantid crashes

**Comment by martyngigg** [comment]
@Harrietbrown Is this for 6.1? Can we set the milestone if so?

**Comment by Harrietbrown** [comment]
Yes thanks for reminding me

**Comment by gemmaguest** [comment]
Fixed by #31423
