### ISSUE TITLE
Missing fields in SaveCanSAS1D and SaveNXcanSAS

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#30474]
### Expected behavior
SaveCanSAS1D and SaveNXcanSAS should include `sample_scatter_run` in the `SASprocess` block

### Actual behavior
`sample_scatter_run` is missing

### Steps to reproduce the behavior
You'll need the training data.
- Open the ISIS SANS interface
- Click `Load User File` and select `MaskFile.toml` from the `loqdemo` subdirectory in the training data.
- Click `Load Batch File` and select `batch_mode_reduction.csv`
- Ensure the default save directory is set to something sensible
- Ensure CanSAS and NXCanSAS are ticked under Save Options
- Select the first row in the table and click `Process Selected`
- Open the saved `first_time_HAB_1D_2.2_10.0.xml` file in a text editor and note that in the SASprocess bock the required field is missing
- Open `first_time_HAB_1D_2.2_10.0.h5` in HDFView and note that in SASprocess->sasnote the required field is missing

### Platforms affected
All. This is an existing bug in 5.1.1

**Comment by gemmaguest** [comment]
@smk78 It looks like `can_trans_run` is also missing from SaveNXcanSAS?

**Comment by smk78** [comment]
Actually, it looks like can_trans_run is there, but under <sasprocess> top level and not <sasprocess\sasnote>.
![image](https://user-images.githubusercontent.com/10938679/105752792-a4f48a00-5f3f-11eb-840c-a1be9656f2a9.png)
[issue30474.zip](https://github.com/mantidproject/mantid/files/5869008/issue30474.zip)
I can't immediately think why they should be in different locations...
