### ISSUE TITLE
FIGARO reduction refactoring

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#30480]
Once implemented figaro reduction stopped working some time ago due to various updates in the nexus format as well as the workflow that was reworked for D17. Workflow needs to be revisited to enable again processing of figaro data:

- [x] IDF double check
- [x]  Loader to support newest data (both direct and reflected beams, both upwards and downwards reflections)
- [ ] Pre-process, both direct and reflected beams, supporting 3 angle calibration methods (detector, sample, user)
- [ ] Sum foreground, both for incoherent and coherent methods
- [ ] Convert to Q, including resolution calculation (coherent and incoherent)
- [ ] Check auto process, including gravity correction

**Comment by darominski** [comment]
The relevant issue for this work now is #33582 .
