### ISSUE TITLE
Muon Analysis - Autoscale y does not always show a margin

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30496]
**Original reporter:** James Lord

### Expected behavior
Autoscale y should scale the y axis of the plot within the current x limits. There should also be a margin around the y scale so that it is easier to read the plotted data.

### Actual behavior
The margin is not present on the upper part of the plot. Sometimes the autoscaling seems arbitrary.

### Steps to reproduce the behavior
1. Muon Analysis
2. Load Current Run
3. Make sure `Autoscale y` is ticked. There is no margin at the top of the plot.

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #30501
