### ISSUE TITLE
Add string only keys to more Singletons

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#30503]
As a follow on to #30487, keys to strings in more singletons. This is for things in [kernel](https://github.com/mantidproject/mantid/pull/30487/files#diff-1557027ce2591fd3c258d8a6b36ec251c42df9c26e55a22e876f2c87ec44cc48L61-L64) and [api](https://github.com/mantidproject/mantid/pull/30487/files#diff-51cbb5f08b393d04bd9b83cef2209372e5061e588398a687f181c2fe3fce82eeR26-R34).

`api/_aliases.py`:
* `AnalysisDataService` #30487
* `AlgorithmFactory`
* ~~`AlgorithmManager`~~
* ~~`FileFinder`~~ - it’s not a store
* ~~`FileLoaderRegistry`~~ - not used in python
* ~~`FrameworkManager`~~
* `FunctionFactory`
* ~~`WorkspaceFactory`~~ - not a store
* ~~`CatalogManager`~~ - not used much

`kernel/_aliases.py`:
* ~~`UsageService`~~ - not a store
* `ConfigService`
* `PropertyManagerDataService`
* `UnitFactory`

**Comment by martyngigg** [comment]
I guess we're probably not going to do do this for 6.1?

**Comment by martyngigg** [comment]
@peterfpeterson I'm going to push this back again. Let me know if you'd like to work on it.
