### ISSUE TITLE
Muon ALC - Exported workspaces have no history

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30529]
**Original reporter:** James Lorde

### Expected behavior
The exported workspaces should probably have history if possible.

### Actual behavior
The exported workspaces don't have history.

### Steps to reproduce the behavior
Follow similar steps to #30528 . Export the data. Try to Show History, it says there is none.

Not important enough for the upcoming release.

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
this is because everything is done with child algorithms. We can just set up the algorithms ourselves and set `storeInADS(False)`
