### ISSUE TITLE
Muon ALC - Loading second batch of runs doesn't load them

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30527]
**Original reporter:** James Lorde

### Expected behavior
The data should be loaded when `Load` is clicked.

### Actual behavior
The data isn't loaded until you click `Load` for a second time. Also the Log is being reset.

### Steps to reproduce the behavior
1. Open Muon ALC interface
2. Instrument is HIFI. Runs 83929-49
3. Click `Load`
4. Select log `sample_mgn_field`
5. Enter a new batch of runs 83951-71
6. Click `Load` 
7. The files are found, but not loaded. You have to click `Load` again for them to load. Also the log is changed back to `run_number`.

### Platforms affected
Found on windows, probably all.

**Comment by martyngigg** [comment]
Fixed by #30536
