### ISSUE TITLE
Muon Analysis crash after switching around start and end X

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30525]
**Original reporter:** James Lorde

### Expected behavior
A fit should be performed ok.

### Actual behavior
There is a crash in James' demonstration. For me it uses the old start and end X so it says the x-range is invalid.

### Steps to reproduce the behavior
1. Go to Muon Analysis
2. Select HIFI instrument and run `83934`
3. Go to `Fitting Tab`
4. Add functions `Chebyshev` and `ExpDecayOsc`
5. Set `EndX` = 0.0, `StartX` = 15.0
6. Set the `n` parameter in Chebyshev to 2
7. Set the Frequency parameter in ExpDecayOsc to 0.6
8. Click `Fit`. An invalid x-range warning appears correctly.
9. Switch the `EndX` = 15.0 and `StartX` = 0.0
10. Click `Fit` again and crash, or same warning appears!

### Platforms affected
All I assume

**Comment by AnthonyLim23** [comment]
@Matt-Cumber I thought you made it automatically switch the values if min was greater than max?

**Comment by Matt-Cumber** [comment]
> @Matt-Cumber I thought you made it automatically switch the values if min was greater than max?

I have just been trying this on master, the startx and endx switch for me and I don't get any warnings

**Comment by robertapplin** [comment]
Have you tried release-next? I get this warning 
![image](https://user-images.githubusercontent.com/40830825/106442648-6d23a000-6473-11eb-883d-2ff81e3a36c8.png)

**Comment by robertapplin** [comment]
The second time the warning shouldn't appear because I have switched them around to be correct

**Comment by robertapplin** [comment]
@Matt-Cumber This is referring to the `StartX` and `EndX` within the Chebyshev function itself, not the Time Start or Time End

**Comment by Matt-Cumber** [comment]
> @Matt-Cumber This is referring to the `StartX` and `EndX` within the Chebyshev function itself, not the Time Start or Time End

Ah right that will be why then @AnthonyLim23

**Comment by AnthonyLim23** [comment]
ah ok, so that is an issue with the fitting function then?

**Comment by robertapplin** [comment]
I think the issue is the Chebychev function is stored in the fitting tab code and is not being updated when start/end x is changed. So it is always using the original start/end x

**Comment by Matt-Cumber** [comment]
Fixed by #30555
