### ISSUE TITLE
Crash when Show Detectors on TOSCA raw data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30547]
**Original reporter:** Svemir

### Expected behavior
There should be no crash. It should show detectors.

### Actual behavior
There is a crash.

### Steps to reproduce the behavior
1. Load the data below into mantid
2. Right click and `Show Detectors`
3. Crash!

[TOSCA26911.zip](https://github.com/mantidproject/mantid/files/5903445/TOSCA26911.zip)

### Platforms affected
Found on windows.

**Comment by martyngigg** [comment]
Fixed by #30548
