### ISSUE TITLE
SANS: Save the content of the UI to a user file

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3058]
sans_feature
This issue was originally [TRAC 2211](http://trac.mantidproject.org/mantid/ticket/2211)

Allow users to save the content of the UI to a new user file.

We would have to think about how we keep the original notes & comments in the file. Perhaps the whole previous files at the end, all commented out? Or can you be more clever? 

Possibly taking the original file as a base and editing the values in place (may be harder for mask lines).

**Comment by AntonPiccardoSelg** [comment]
Alternatively we could save the states in a file (which we currently do in the `Diagnostic Tab`). Then we can load these states. We just need to tweak our deserialisation a bit. Should be doable. 

Writing the settings into a user file seems more involved. If this is the way the users want to go ahead however, then we should not start work on this before we have designed and implemented the new user file format

**Comment by Mantid-Matthew** [comment]
This is highly likely to be implemented during the joint reflectometry/SANS user file update detailed here #18826

**Comment by gemmaguest** [comment]
Replaced by #18826
