### ISSUE TITLE
Issues from D16 hot commissioning

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#30589]
- [ ] Change the default view to side by side (but flipped?)
- [x] Default mask (usually the edges) should be applied to all the scan positions
- [x] Beam stop mask should be applied to all the scan positions that have a shadow of the beam stop (up to about gamma=10), however the masked region itself will be different obviously for each of gamma position
- [x] When doing theta dependent transmission (flat sample), mask few pixels around 90 degree to avoid divergence
- [x] Use monitor 2 for normalisation, monitor 1 counts 0s
- [ ] Make parameter scan work also for SANS/WANS, which loads to histogram data

**Comment by darominski** [comment]
D16 does not exist anymore, so this issue is not relevant. The commissioning for D16B will be handled by a separate issue.
