### ISSUE TITLE
SANS: Improve UI - Python integration

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3060]
sans_code
This issue was originally [TRAC 2213](http://trac.mantidproject.org/mantid/ticket/2213)

The Python variable space needs to â€œkeep upâ€ with changes to parameters set in the gui. Then clever bits of Python to do plots etc will all keep working. We wonâ€™t want to transfer data back the other way from Python to the gui.

We should update each value in the python evnt after the control has lost focus and validated. Rather than performing all of the python command on the Reduce buttons alone.

**Comment by AntonPiccardoSelg** [comment]
This ticket does not seem relevant any longer. The old guy will be supported but will not receive enhancements
