### ISSUE TITLE
Documentation: latex errors for some algorithms in qthelp 

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#30679]
### Expected behavior

The qthelp documentation should be consistent with documentation available online and all latex formulae ought to be parsed without errors.

### Actual behavior

An issue was found during smoke testing in D7AbsoluteCrossSections, where multiple multi-line latex formulae caused errors and were not created properly. The issue was not observed for documentation available online, where the same formulae are parsed correctly.

### Steps to reproduce the behavior

1. Using recent mantid package, either v6.0 or nightly, open workbench.
2. In algorithms widget, find D7AbsoluteCrossSections, initiate help through `?` button.
3. Observe latex errors for multi-line formulae for XYZ method, and other formulae below.

### Platforms affected
workbench

**Comment by DanielMurphy22** [comment]
![Screenshot 2021-02-09 at 16 10 06 (2)](https://user-images.githubusercontent.com/55980573/107638189-2437cc80-6c67-11eb-8fa1-b9c6a6c14af8.png)
