### ISSUE TITLE
Remove validation on SampleAngle parameter in PaalmanPingsMonteCarloAbsorption algorithm

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#30699]
It should be possible to enter a negative angle for the SampleAngle parameter when setting up a flat plate geometry using the PaalmanPingsMonteCarloAbsorption algorithm. At the moment there is a validation on this parameter that prevents this so that should be removed

**Comment by martyngigg** [comment]
Fixed by #31384
