### ISSUE TITLE
Cannot Change Normalisation Of Plot Once Renamed

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#30739]
### Expected behavior
You should continue to be able to change the normalisation of the plot

### Actual behavior
The plot gets stuck in whatever normalisation it was before the rename

### Steps to reproduce the behavior
Load in some data
Plot spectra
Right click and change normalisation to check it works
Rename the workspace in the ADS
Now try to change normalisation again

### Platforms affected
all

**Comment by martyngigg** [comment]
Fixed by #31337
