### ISSUE TITLE
Instrument View: Display additional informational cursor information for assembly selections

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#30738]
As a user of the instrument view I want to know the counts over a whole tube of an instrument but the selection pane In pick mode tab on the instrument view shows details of the pixel the cursor is positioned over only.

The information displayed always uses the single pixel over which the cursor hovers, regardless of the pick mode activated, e.g. tube selection. It has been highlighed by users that this can be a little misleading as the plotting pane shows the sum in the case of tube selection for example. The following image shows an example:

![WISH-pixel-info-tubes](https://user-images.githubusercontent.com/733773/108678983-c6677800-74e3-11eb-9082-463c9c4cc91d.png)

This task is to add information to selection pane giving addtional details on the sum of the counts the cases where multiple pixels are selected in the plotting pane.

**Comment by thomashampson** [comment]
I propose that we rename "Counts" to "Pixel counts" and add an extra line with "Tube counts" when the user is in tube selection mode.

**Comment by martyngigg** [comment]
This sounds like a sensible suggestion to me.
