### ISSUE TITLE
TOPAZ: Problem with peak intensity assignment for satellite peaks

### ISSUE THREAD

**Issue by jmborr** [mantidproject/mantid#30737]
Issue created following [SCD157](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/157), later superseeded by [SCD229](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/229)

Report after tracing the error
===================

Summary
----------
Using a `Tolerance=1` along with `MaxOrder=0`  in algorithm `IndexPeaks` means that _all_ peaks are understood as main peaks. No peak is understood as a satellite peak, and the real satellite peaks are assigned the same set of integer HKL indexes as their corresponding main peaks, and they are assigned no modulation vector.
Later, all events are scanned and each event is mapped to a particular set of integer HKL indexes. Since a satellite peak and its main peak have the same set of integer HKL indexes, they both end up being associated to the same set of events contributing to their intensity.

Details
-------
Indexing peaks with the following call to algorithm `IndexPeaks`:
```python
IndexPeaks(PeaksWorkspace='TOPAZ_39037.nxs_peaks', 
           Tolerance=1, 
           ToleranceForSatellite=0.10000000000000001, 
           RoundHKLs=False)
```
and with default values for the following properties:
```
ModVector1	Input	dbl list	0,0,0	Modulation Vector 1: dh, dk, dl
ModVector2	Input	dbl list	0,0,0	Modulation Vector 2: dh, dk, dl
ModVector3	Input	dbl list	0,0,0	Modulation Vector 3: dh, dk, dl
MaxOrder	Input	number	0	Maximum order to apply Modulation Vectors. Default = 0
```
Results in the following two peaks relevant to our discussion, among others:   
<img src="https://user-images.githubusercontent.com/1136006/109089893-0abf6780-76e0-11eb-94aa-724b390f0543.GIF" width=500>
Peak 160 is a modulated peak with modulation vector  `(0.5, 0.05, 0)` from main peak 162 with HKL `(1, 1, 0)`. However, **peak 160 is not flagged with modulation info because `Tolerance=1` and `MaxOrder=0`**. For all purposes, its treated as an unmodulated, main HKL peak.

Later when integrating peaks with algorithm `IntegrateEllipsoids`, [each peak is assigned integers HKL's](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp#L407) by rounding to the nearest integer. As a result, Peak 160 and Peak 161 both have the same HKL `(1, 1, 0)`. Both peaks are assigned modulation indexes MNP `(0, 0, 0)`. These HKL and MNP indexes are used to [construct a "key" value by the integrator object](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L763) so both peaks share **the same "key" value**.

The integrator goes through the list of events, [looking one at a time](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L1000). The Q-vector of each event is used [to derive a "key" value](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L1046). Remember we have no modulation vectors so the Q-vector is mapped only to a set of integer HKL indexes. After going through the list of events, we end up with each "key" value being [mapped to a list of events](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L1019). 

In the final step, [we iterate over the peaks](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp#L510) and [invoke the event integrator for each peak](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp#L554). The integrator looks at the HKL and MNP indexes of the peak and [construct its "key" value](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L509), which is used [to retrieve the list of events](https://github.com/mantidproject/mantid/blob/master/Framework/MDAlgorithms/src/Integrate3DEvents.cpp#L518) from the previous constructed mapping.  Since both Peak 160 and Peak 161 have the same "key" value, they end up with the same list of events contributing to their intensity.

**Comment by zjmorgan** [comment]
Switching to a user story to address enhancement to change the line
`event_Q.second = event_Q.second - peak_it->second`

Need a complexity to put in the associated GitLab issue once it is back online.
