### ISSUE TITLE
Fix tight_layout in EngDiff Ui fitting plot making figure smaller due to large legend

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#30795]
### Actual behavior
When the figure is refreshed tight_layout is enforced but the legend (which is typically quite large due to long workspace names)  often results in the plot being made smaller.

### Expected behavior
Perhaps the legend should be ignored when enforcing tight_layout (i.e. toggle visibility)? Maybe plot legend outside of axes on bottom or top?

**Comment by DannyHindson** [comment]
Hard to reproduce on Mac - perhaps easier to see on Windows

**Comment by DannyHindson** [comment]
Not a priority
