### ISSUE TITLE
Instrument view crashes when right clicking plot in "pick" tab

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#30811]
### Description
Instrument view will crash if the plot in the "Pick" tab is right-clicked after stored curves are removed by clicking the erase tool.

### Expected behavior
Context menu should appear.

### Actual behavior
Instrument viewer crashes.

### Steps to reproduce the behavior
1. Load a workspace, open the instrument view and navigate to the "Pick" tab
2. Store at least one curve on the plot by right clicking a pixel and choosing "store curve"
3. Click the eraser tool, which will remove the stored curves
4. Right click the plot

The plot does not need to be empty to cause the crash, you can store more curves after clicking the erase tool and still reproduce the crash.

### Platforms affected
Windows 10, not tested on any other platforms yet.
Also present in v5.1.0 of Mantid Workbench.

**Comment by joseph-torsney** [comment]
Unassigning myself as the vscode debugger causes my linux vm to crash and I can't use instrument viewer on the remote desktop! May come back if I sort out vscode but anyone else feel free to pick this up in the meantime
