### ISSUE TITLE
Export fails on drill

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#30813]
Exporting in drill fails under certain circumstances.
This could be related to the fact, that the ws is a group, so you can't get its history directly.
Also there must be a check if history exists, and if it is not empty.
In any case failure of exports shouldn't result into crying mantid.

### Steps to reproduce the behavior
Start drill. Set datasearch directory to current cycle internalUse of D11.
Put 000560 as sample, check OutputPanels in global settings.
Click process > 💣

**Comment by gui-co** [comment]
This is due to the fact that there is apparently no history in panel workspaces. The history is used to check that the output type is compatible with the selected export algorithm.

**Comment by gvardany** [comment]
I see, the reason for this is that panels are not output workspaces of the algorithm, but they are generated when there is a checkbox. I think this can be fixed if we declare the output properties at runtime. However, in the save side, cases when there is no history, or no last item in it should be properly guarded.
