### ISSUE TITLE
Implement a widget for workspace calculator

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#30827]
ILL users requested a calculator for quick calculations of workspaces that include 4 basic operations:summation, subtraction, multiplication, and division. Also, scaling of both LHS and RHS workspaces by a float number was requested.

### Platforms affected
Workbench on all platforms

**Comment by SpencerHowells** [comment]
@darominski What is wrong with the algorithms Plus, Minus, Multiply, Divide & Scale?

**Comment by gvardany** [comment]
Spencer, this is just a convenience widget that does 3 operations with one click: scale both operands and run a binary operation. Even if this is a one-liner in python, the widget is for those users allergic to code.

**Comment by SpencerHowells** [comment]
@SpencerHowells Gagik, you don't need to know Python I regularly use the alg dialog window. I also have the interface Inelastic>corrections>Subtraction which also does ScaleX to do a shift. Also gives instant plots of result!

**Comment by darominski** [comment]
@SpencerHowells I agree one does not need to know Python to use Mantid, however this feature is intended to improve the experience of users currently reluctant to directly interact with algorithms through dialogs or write scripts to perform these quick operations on workspaces. This is the way we intend to use to ease their transition into using Mantid.

**Comment by SpencerHowells** [comment]
@darominski I thought that might be the case. We also have trouble with users reluctant to use Mantid properly. Wouldn't algebraic manipulation be easier eg w = 2*w1 - w2/3 ?
