### ISSUE TITLE
IndirectData Analysis IqtFit only fits streached exponentials for the first spectra

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#30828]
**Original reporter:** Spencer

When running a fit in sequential mode in IqtFit it only runs the fit in the first spectra. in all others it leaves the paramiters as 1.0

**Comment by AnthonyLim23** [comment]
I assume this needs fixing for the release

**Comment by Harrietbrown** [comment]
This seems to be working now but I will be keeping an eye on it.
