### ISSUE TITLE
Issue with flux processing in SANSILLAutoProcess

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#30840]
Processing flux does not work in SANSILLAutoprocess because of a typo in the code

**Comment by gvardany** [comment]
I have opened this https://github.com/mantidproject/mantid/issues/30839

**Comment by MathieuTillet** [comment]
Are we sure it is the same bug ? Is there a way to test that ?

**Comment by gvardany** [comment]
If there is FluxRun and AbsorberRun, it fails with an error that absorber_names don't exist or something. Can you try just this? If not I can make a concrete example?

**Comment by MathieuTillet** [comment]
Ok, then it's the same thing - the typo was on absorer_names, and now it can run just fine.
