### ISSUE TITLE
User feedback to PolDiffILLReduction technique

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#30863]
Following the user feedback certain modifications to the `PolDiffILLReduction` and `D7AbsoluteCrossSections` algorithms and to the relevant documentation of the technique are needed:

- [x] Instrument calibration coming from YIG calibration is not specified in the examples of the `PolDiffILLReduction` nor the `PolarizedILLDiffraction` technique documentation
- [x] Sample height, beam height and beam width are not parameters commonly known: their value should be fixed so it does not impact attenuation calculation, if possible.
- [x] The density choice between number density and mass density is not clear enough.
- [x] The unit for Y-axis of polarization correction is incorrect
- [x] Flipping ratio plots should be made available for instrument scientist, along with polarization correction value
- [x] The algorithm crashes when processing vanadium in `PolDiffILLReduction` with the property `OutputTreatment` set to 'Average'
- [x] Add option to turn off the normalisation for diagnostic purposes
- [x] `D7AbsoluteCrossSections` does not provide expected results when either 'Sum' or 'Average' are specified for the `OutputTreatment` property
- [x] There is an issue in calculating cross-sections of magnetic samples: the magnetic component cross-section looks inverted, which leads to issues in incoherent scattering cross-section.
- [x] Check the error propagation throughout the algorithm.

**Comment by gvardany** [comment]
Please add an item to double check the error propagation throughout.

**Comment by darominski** [comment]
Closed with the linked PR.
