### ISSUE TITLE
Resize cursor for instrument viewer

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#30891]
### Expected behavior
As a user, when manipulating a shape in the instrument view (either "pick" of "draw" tab), if I hover over the corner handles I expect the cursor to change to a `Qt::SizeFDiagCursor` or `Qt::SizeBDiagCursor`.

### Actual behavior
Currently there is no feedback from the UI to tell me I'm hovering over a corner handle. The `Qt::SizeAllCursor` is used for both moving and resizing, which can make resizing rectangles a bit cumbersome.

### Steps to reproduce the behavior
Load a workspace and open the instrument viewer. Go to the "pick" or "draw" tab and draw a rectangle and resize it.

**Comment by thomashampson** [comment]
@SilkeSchomann reopening stale issue after you mentioned it would be a nice UI improvement

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resize cursor for instrument view](https://trello.com/c/ovn8aV1R/22-resize-cursor-for-instrument-view)
