### ISSUE TITLE
Add support to load SHARP data

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#30902]
Support should be added for loading ILL instrument SHARP's nexus raw-data. The data structure for TOF and non-TOF data taking workflows is expected to follow the one in IN5 and PANTHER, both of which are already implemented in `LoadILLTOF2`. The data scan workflow is also in line with the new scan type of IN5 and PANTHER, and should be implemented as part of the same solution (PR #30783).

**Comment by gvardany** [comment]
Closed with the linked PR.
