### ISSUE TITLE
Remove duplicate WISH system test files

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#30908]
Different versions of the following files exist in both the Testing\Data\SystemTest and Testing\SystemTests\tests\framework\reference:

WISH40503-5_6no_absorb_raw.nxs.md5
WISH40503-5_6raw.nxs.md5
WishAnalysis.nxs.md5

This is a bit confusing because it's possible to update the ones in the "reference" folder and they have no effect because the files in there don't get used at the moment. I think the files should be in the Testing\SystemTests\tests\framework\reference because they're used in the validate method of the WISH system tests. 

So the actions required are to delete the files from Testing\Data\SystemTest and bring the files in the reference folder up to date

**Comment by DannyHindson** [comment]
@RichardWaiteSTFC - while doing my big ConvertUnits change I came across a few things in the system tests that caused by a few problems and need tidying up. I'm about to tidy up this issue which is that there are some duplicate WISH files in GitHub for the system tests. Are you happy for me to go ahead remove these duplicates?

**Comment by RichardWaiteSTFC** [comment]
> @RichardWaiteSTFC - while doing my big ConvertUnits change I came across a few things in the system tests that caused by a few problems and need tidying up. I'm about to tidy up this issue which is that there are some duplicate WISH files in GitHub for the system tests. Are you happy for me to go ahead remove these duplicates?

Yes of course, thanks for doing that. I wasn't ware there were two folders - so in what scenario would one put a file in Testing\Data\SystemTest rather than Testing\SystemTests\tests\framework\reference?

**Comment by DannyHindson** [comment]
> > @RichardWaiteSTFC - while doing my big ConvertUnits change I came across a few things in the system tests that caused by a few problems and need tidying up. I'm about to tidy up this issue which is that there are some duplicate WISH files in GitHub for the system tests. Are you happy for me to go ahead remove these duplicates?
> 
> Yes of course, thanks for doing that. I wasn't ware there were two folders - so in what scenario would one put a file in Testing\Data\SystemTest rather than Testing\SystemTests\tests\framework\reference?

Well I've not read this in our documentation anywhere so this is my own take - but it seems to be the case that the files that are checked at the end of a system test in the validate method are stored in Testing\SystemTests\tests\framework\reference and any other files such as those used as inputs to a test go in Testing\Data\SystemTest
