### ISSUE TITLE
Make FitOptionsBrowser more flexible

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30992]
### Description
This issue is to refactor the Fit Options Browser to make it more flexible and maintainable. We also want to ensure it has the correct design and is configurable so that all areas can use the same widget. The aim is to eventually replace the `FitPropertyBrowser` which has had much of its functionality already split into the `FunctionBrowser` and `FitOptionsBrowser`.

**Discovery**
- [ ] Determine the current capabilities of the FitOptionsBrowser

**Design Tasks**
- [ ] Find the areas where `FitPropertyBrowser` is currently used (e.g. EngDiff)
- [ ] Find the required functionality which is used within the `FitPropertyBrowser` for fit options (which isn't already incorporated in the `FitOptionsBrowser`)
- [ ] Decide on a plan to implement this in the `FitOptionsBrowser` (might just be a list of technical tasks to complete)

**Technical Tasks**
A list of tasks we need to complete are:
- [ ] Refactor `FitOptionsBrowser` to make it more maintainable and add tests (the `BasicFitOptionsBrowser` and its tests can be a starting point for this)
- [ ] Add a method to `FitOptionsBrowser` that allows certain properties to be hidden.
- [ ] Add a method to `FitOptionsBrowser` that can be used to hide sub-properties of the `Minimizer` property
- [ ] Remove the `BasicFitOptionsBrowser`. This was probably not the best solution to allow flexibility of properties.

Then (perhaps in a separate PR):
- [ ] Hide the unneeded properties in the `FitOptionsBrowser` for the Fit Script Generator
- [ ] Use FitOptionsBrowser and FunctionBrowser to replace `FitPropertyBrowser`

**Comment by martyngigg** [comment]
Can I ask that we come up with and agree a design for this going forward before we write any code? I'm concerned that we want to plan something so we can phase out the older `FitPropertyBrowser` and replace it with something more configurable and maintainable but we need to make sure it can work everywhere we use it.

**Comment by robertapplin** [comment]
Yes I will look into how we might want to design this. I might just need to do a bit of discovery of what the `FitOptionsBrowser` can currently do because Roman already replaced the `FitPropertyBrowser` used in indirect with a FunctionBrowser and FitOptionsBrowser so I would assume it already does most of the things we need it to do. But I will do some discovery and see what comes out of that

**Comment by robertapplin** [comment]
It looks like I will add some options to the `BasicFitOptionsBrowser` which are not just fit options but also options for what to include in a fit script (for instance the plotting option described here #31955 ). So the `BasicFitOptionsBrowser` will probably be renamed to `FitScriptOptionsBrowser`. In which case the need to make the `FitOptionsBrowser` more flexible might be postponed as its not immediately required

**Comment by robertapplin** [comment]
Closed because the `BasicFitOptionsBrowser` has been renamed and diverged in nature to be the `FitScriptOptionsBrowser` in #31974
