### ISSUE TITLE
Tidy up WISH SX reduction script and implement new features added to IntegratePeaksMD

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31010]
Issue to implement new features:
- Ellipsoid Integration using IntegratePEaksMD with centroid
- Work on estimating radius for each individual peak

Tidy up the script so is more user-friendly - easier to change options etc.

**Comment by DannyHindson** [comment]
WISH reduction class created. Close once Richard adds a zip of the reduction class

**Comment by RichardWaiteSTFC** [comment]
Put on script repo with PR
https://github.com/mantidproject/scriptrepository/pull/12
