### ISSUE TITLE
EPIC: NR 2D toolkit - graphical selection of ROIs

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#31069]
Umbrella issue to gather requirements for data reduction for 2D NR detectors at ISIS, in particular regarding graphical selection of regions of interest.

This high level issue covers several items on the technical working group [roadmap](https://github.com/mantidproject/roadmap/projects/1?query=is%3Aopen+sort%3Aupdated-desc)

### Summary of main steps
These are the initial steps being implemented to create a minimal viable product. There will be many refinements and additions to follow.

- [x] #32034 
- [x] #33037 
- [x] #34240
- [x] #34108
- [ ] #34220
- [x] #34238
- [x] #34279

### Test instructions

Test builds are available [here](https://builds.mantidproject.org/job/build_packages_from_branch/59/)

As more functionality is added these instructions will be updated with the latest workflow:

- Ensure this workspace is loaded or is in your load path: [INTER45455_inst.zip](https://github.com/mantidproject/mantid/files/7504266/INTER45455_inst.zip)
- Open the ISIS Reflectometry GUI
- Select the Preview tab.
- Type in `INTER45455_inst`, set the angle to `1`, and click Load. The instrument view plot should display the data. Click the rectangle-select button above it and select a region. The segments will be summed and the result plotted on the second plot (spectrum vs TOF).
- Click the rectangle-selection button on the second plot and select a region for the signal. A reduction will now be performed on the selected spectra and the result plotted on the 1D plot. 
  - You can see the counts better on the second plot if you set the color scale to SymmetricLog10, although there's a bug with autoscaling (un-tick and re-tick to get it to work).
  - Note that the reduction is quite picky and may fail; if so you will get a warning in the log. It's best to select a region around spectra 20-30.
- Click the drop-down on the rectangle select button and also select a transmission region and one or more background regions. The 1D plot should update with each change.
- Click the Export button above the 1D plot. This should export the workspace `preview_reduced_ws` to the ADS. Right-click it to show the history. The inputs for [Background|Transmission]ProcessingInstructions should correspond to the ranges of spectra you selected.
- Click the Apply button; the regions of interest should be populated in the Experiment Settings tab's lookup table.
- On the Runs tab, in the first child row in the table, enter run as `inter45455_inst` and angle `1`. Click Process. 
- Compare the `preview_summed_ws` (from the Preview reduction) with `IvsQ_45455` (from the batch reduction). They should be the same.

![image](https://user-images.githubusercontent.com/12895056/177387459-df2a1e43-33e1-4203-8c6e-b844680ee85e.png)

## Vision
The vision is to have a graphical tool with multiple interactive plots for selecting different regions of interest and performing reduction on the fly. It is hoped that the tool may also be useful for other facilities and techniques such as GISANS. However, it may turn out that reduction implementations differ too widely to create a generic tool that would be suitable for many instruments.

See the slides put together by scientists at ILL and ISIS here: [2D Detectors Schematic_TS_Max.pdf](https://github.com/mantidproject/mantid/files/6816951/2D.Detectors.Schematic_TS_Max.pdf)

The initial requirement at ISIS is to get this working for 2D detectors for INTER. It should also be usable by linear detectors at ISIS (excluding the initial horizontal integration step).

As a rough indication it might look something like this, although we probably want a cut down version of each plot type to avoid unnecessary clutter:

![NR_InstViewPlus](https://user-images.githubusercontent.com/12895056/113894716-3003c300-97c0-11eb-8811-4f5bba1693c1.png)

## Workflow
- Apply preprocessing such as detector calibration, subtract 2D instrumental background, flood correction, divide by 2D direct beam. (Question: should this all be done before it is displayed on the instrument-viewer plot?)
- Use an InstrumentView-like plot to inspect the detector image and select the lateral extent of the region to process.
- Integrate horizontally to generate a spectrum/pixel vs. TOF workspace/detector image.
- Display this in a SliceViewer-like plot where we can add ROIs for specular, (multiple) background regions and possibly transmitted beam.
- Display a 1D plot of integrated (or fully reduced?) data based on the selected ROIs.

### Generic behaviour
- Integrating horizontally: we considered implementing this in the instrument viewer but it would require implementing the knowledge about which pixels to sum together from scratch. We decided to use the algorithm `SmoothNeighbours` which can already do this. We have limited it to rectangular mode with summing in one direction for now because it is unclear what it should do in other cases. We have wrapped this is our own algorithm to add these restrictions and to allow extension in the future. The working name for this is `ReflectometryISISSumBanks` although it is not clear what a "bank" is in this context so we may change this for the first production release.
- If we need to run a full reduction to produce the final 1D plot this will be very specific to the implementation for a particular instrument. This could be made somewhat generic if we can provide a single algorithm name and set of properties that will be run to perform the reduction. However, there would be some prerequisites for such an algorithm, namely how the ROI is to be specified, e.g. by specifying a filename. Attempting to make this generic could add a lot of complexity. For ISIS Reflectometry we can easily perform the reduction and embed the individual plots on the GUI so will go with that for now.

### Algorithm changes
- We will need to support much more complex ROIs than the current grouping pattern strings support (including wavelength dependent background regions). It is probably best to save ROIs to a file and make our algorithms accept that file as input.
- `ReflectometryISISLoadAndProcess` currently accepts grouping pattern strings but could be changed to accept a file.
- We need to think how we will use more complex background regions for ISIS NR because this because it is not currently supported in our reduction workflow. The algorithm that will need to implement this is `ReflectometryBackgroundSubtraction` (a child of `ReflectometryISISLoadAndProcess`). However, the initial implementation is likely to only need a simple grouping pattern string as it does now, so the only change initially might be to move this to a file rather than passing as a string input property.
- A new algorithm to load and pre-process the 2D datais needed to be added. We have called this `ReflectometryISISPreprocess`.

### Reproducibility
- ROI selections need to be savable as part of a script or reduction configuration for reproducibility. For use on GUIs they should also be restored as part of project recovery in case of a crash. On the ISIS Reflectometry GUI, they should be saved as part of the Batch Save (possibly as part of the same .json file; or if saved as a separate file we need to consider how to ensure it is always available as part of that reduction configuration)
- From discussions with Andrew, the use case for using the tool outside of the GUI would be as an initial setup step. The output from the tool needs to be in a format that could then be used by a "final" script that contains the reproducible reduction. Again, the best option is probably to save to an ROI file as long as user scripts call an algorithm such as `ReflectometryReductionOneAuto` that can be made to support such a file.
- Outputting ROIs to workspaces in the ADS is tempting but complicates reproducibility because we need to ensure the workspace is available. This is why I'm leaning towards saving direct to a file. However there may be precedent for using the ADS so we can consider this if it is more intuitive.

### Plot functionality
- We would not need the full InstrumentViewer to be embedded but would want a cut down version. The selection tools are probably sufficient for ISIS NR for now, but we would need to add a new option to extract the integrated ROI in the required format.
- We need to decide whether to embed SliceViewer or use (and improve) preview plots. SliceViewer may contain too much functionality in its current form and if we do use it we may wish to modularise it to avoid a cluttered interface.
- SliceViewer allows selection of a single ROI at the moment but the output is to a workspace, so we need to think about how we specify multiple ROIs and add method(s) to extract them in the required format. This is probably something we want to build modularly on top of sliceviewer and control from the parent component, rather than make a part of sliceviewer's default behaviour (e.g. in the same way multiple range selectors can be added to a preview plot by a parent component, and the parent component decides how many to add and what those regions mean). This may be complex to reconcile with the existing selection functionality and there is more opportunity for things to break.
- An alternative would be to use the ContourPreviewPlot instead. This is already available in C++ and RangeSelectors could be added easily (they are currently available for PreviewPlot but not ContourPreviewPlot). From a user perspective the implementation is not important but a main aim is consistency between SliceViewer and whatever plot we use on the new tool. ContourPreviewPlot is currently very basic and looks very different to sliceviewer, but it could be improved to make it more consistent.
- For the 1D plot, we could embed standard plots or use PreviewPlot. Again we should aim for consistency between the two. PreviewPlots are very basic at the moment but it could be more widely beneficial to make them more functional and consistent with standard plotting in Workbench.

### Extended functionality
- Allow for overplotting of functions/1D workspaces to aid in visual display/identification of constant Q, bendiness, OSS, Zeeman, etc.
- It may be useful to have other properties that are adjustable on the tool, for example a slider to adjust the Q resolution to use for producing the live reduced 1D plot. This again is getting very specific to the particular reduction implementation and would be difficult to do generically. This is not a high priority initially but the design should allow flexibility should additional features like this need to be added in the future.

### Standalone tool vs modular components
Different techniques/facilities may want to see different axes/arrangements of the plots. We need to investigate what these are and whether we need to be able to dynamically switch between them on a single tool. As an alternative to creating a single tool to generically handle every case, it could be better to focus on providing flexible, separate components for each plot type that can be easily integrated into other instrument/technique-specific parent tools. This would provide greater flexibility because we would not then have any constraints on the arrangement of the plots or the processing that happens between each plot.

Integrating such selection tools on the ISIS Reflectometry GUI would be straightforward, for example:
- The parent loads the data and performs 2D preprocessing.
- It passes the resulting workspace to the InstrumentViewer plot.
- The InstrumentViewer notifies the parent that an ROI has been changed.
- The parent gets the integrated workspace from the InstrumentViewer and updates the SliceViewer plot with the result.
- The SliceViewer plot notifies the parent when an ROI has been changed.
- The parent gets the ROIs from the SliceViewer, performs the reduction and updates the 1D plot with the result.
- The plots could be added to a single tab within the Reflectometry GUI. We could add other components to meet our specific needs, e.g. a dQ/Q slider.

This may be the best way to go for integration with the ISIS Reflectometry GUI regardless of whether we also implement a standalone tools. In either case, the individual components should be made modular as this is good practice anyway.

Alternatively there could be a combination where e.g. the InstrumentViewer->SliceViewer portion is a single tool that can then be combined with a separate technique-specific 1D plot.

### Agree output format for ROIs
We need to decide whether saving ROIs to a file is the right way to save and pass around ROIs. If so, I suggest developers will then come up with a suggested format to be agreed with scientists (and other interested facilities/techniques).

**Comment by rbauststfc** [comment]
The key functionality is now being successfully used. There are a number of follow-up issues, but I think we can now consider the epic completed and close this issue.
