### ISSUE TITLE
Add tests for IntegratePeaksMD validation

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31198]
To be discussed, this issue is to add tests for the validation in IntegratePeaksMD. The most recently added part can be seen here: https://github.com/mantidproject/mantid/pull/31087#discussion_r618139048 

Yet to be discussed is whether all validation needs tests.

In a separate point, but related to the same PR linked above, does SetValueWhenProperty need tests?

**Comment by martyngigg** [comment]
As this is maintenance I'm moving the milestone to 6.2

**Comment by martyngigg** [comment]
Moving to 6.3 as it's maintenance
