### ISSUE TITLE
Update NexusV2 and PSI Muon Loaders

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31206]
As part of #30939 the nexusv1 loader was updated to include extra period information. We want the v2 loader and PSI loader to have the same sample logs added. Consider #29715 when doing this issue

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/pull/30939/files#diff-847a2c8551110acd076ad966813f19b2b9f370d58e02270c484896330c6fdd61R234
