### ISSUE TITLE
muon display problems

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31234]
On nightly I do not have the x or y boxes (beneath the plot) for selecting the plotting range. 

![image](https://user-images.githubusercontent.com/25006392/116216984-1f9c9380-a741-11eb-97b4-844914f10e3b.png)

**Comment by Matt-Cumber** [comment]
This is strange, looks okay on Mac
![image](https://user-images.githubusercontent.com/46685490/116217698-c97c2000-a741-11eb-83e3-2336474763bf.png)

**Comment by AnthonyLim23** [comment]
could you look on windows?

**Comment by Matt-Cumber** [comment]
Still looks okay to me, could be a display size thing

**Comment by AnthonyLim23** [comment]
@sf1919 how does yours look?

**Comment by sf1919** [comment]
Which GUI are you using?

**Comment by Matt-Cumber** [comment]
Muon Analysis or FDA

**Comment by sf1919** [comment]
Ok I have tried both Muon Analysis and FDA on both my laptop and my other screen and all of them show the same as they do for Anthony. In fact the Autoscale y and Errors appear slightly cropped.

![Screenshot (112)](https://user-images.githubusercontent.com/55837273/116223477-76a56700-a747-11eb-98d7-e9ba2bc0bfa2.png)


FYI I'm running Windows 10 on 4K laptop and extra screen.

**Comment by AnthonyLim23** [comment]
@sf1919 and @Matt-Cumber could you two work together on this to make sure it works on Windows and mac (we can make a mac installer)? I will test it on Linux during the review.

**Comment by AnthonyLim23** [comment]
Im updating this to cover general display problems as I have found another one on the fitting tab - the text is truncated 

![image](https://user-images.githubusercontent.com/25006392/116243715-23d7a980-a75f-11eb-97b3-f72bb6569367.png)

**Comment by martyngigg** [comment]
Fixed by #31311
