### ISSUE TITLE
Indirect FQFit - Crash when loading result data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31247]
### Expected behavior
The data should be loaded ok.

### Actual behavior
The interface hangs and eventually crashes.

### Steps to reproduce the behavior
1. Indirect Data Analysis interface
2. Go to FQFit tab
3. Load the data below.
4. Hangs and then crash
[irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip](https://github.com/mantidproject/mantid/files/6390047/irs26176_graphite002_red_Conv_seq_2L_0-50__Result.zip)

### Platforms affected
Found on windows, probably all

**Comment by SpencerHowells** [comment]
@robertapplin It needs result from ConvFit with delta function. So file should have eg *_Delta1L*

**Comment by SpencerHowells** [comment]
@robertapplin The Fit function menu should also be input type specific. Single Input is ok.

**Comment by robertapplin** [comment]
> @robertapplin It needs result from ConvFit with delta function. So file should have eg __Delta1L_

I see, I'll try find a way to stop the crash for non-Delta result data

**Comment by robertapplin** [comment]
> @robertapplin The Fit function menu should also be input type specific. Single Input is ok.

I have looked at the fit function menu and I have found that it is showing the correct functions for each parameter type. Is this not working for you only for Multiple Input?

**Comment by SpencerHowells** [comment]
@robertapplin Yes. It is only wrong for Multiple. Single is fine.

**Comment by robertapplin** [comment]
> @robertapplin Yes. It is only wrong for Multiple. Single is fine.

For reference this now has its own issue #31251

**Comment by martyngigg** [comment]
Fixed by #31252
