### ISSUE TITLE
Sequential fitting log values

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31242]
Sequential fitting is not copying the correct log values. All of the fits have the first fit's log values 

Load EMU 20918-20
Add a fit function
Do a sequential fit
Go to results table
Tick the run_number option
Click `Output results`
Look at the table workspace and notice that all of the runs have the same logs

**Comment by AnthonyLim23** [comment]
a good example for this is here https://developer.mantidproject.org/Testing/MuonInterface/MuonTesting.html#superconducting-copper-test

**Comment by martyngigg** [comment]
Fixed by #31336
