### ISSUE TITLE
Indirect ISIS Diagnostics - The plot sliders have gone missing

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31249]
### Expected behavior
There should be sliders on the first plot of Indirect ISIS Diagnostics to adjust the background range.

### Actual behavior
These sliders are missing.

### Steps to reproduce the behavior
1. Indirect -> Data Reduction -> ISIS Diagnostics
2. Follow the instructions in this example workflow
https://docs.mantidproject.org/nightly/interfaces/indirect/Indirect%20Data%20Reduction.html#isis-diagnostics-example-workflow

The sliders are missing. Needs to be investigated.

### Platforms affected
Found on windows, probably all

**Comment by SpencerHowells** [comment]
@robertapplin I'm not seeing sliders for Peak either. Use 2 ranges needs to be True for background.

**Comment by martyngigg** [comment]
Fixed by #31274
