### ISSUE TITLE
Muon results table update

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31257]
The sample log names are not updated when changing them.

Open muon analysis
Load some dat
Do a fit
On the result tab, select `run number`
Click `Output Results`
Open the ResultsTable from the ADS - it should look ok
Untick the `run number` and select `run_start`
Click `Output Results Table`
The ResultsTable will have `run number` as the header but the value will be the start time

**Comment by Matt-Cumber** [comment]
Only happens if you leave the table open and output a new table if the same name

**Comment by AnthonyLim23** [comment]
user do that :(

**Comment by martyngigg** [comment]
Fixed by #31309
