### ISSUE TITLE
Not All Plot Settings Loaded From Project Save

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31253]
### Expected behavior
Loaded plot should be identical as before

### Actual behavior
The plots are not identical

### Steps to reproduce the behavior
In settings change major and minor tick size
Load some data and create a plot
Save the project
Close mantid
Open mantid and load the project you just saved
The plot that is loaded will not have the same settings

### Platforms affected
all

**Comment by sf1919** [comment]
Is #31259 related to this?

**Comment by joseph-torsney** [comment]
I think they're the same part of the codebase, but the fix I almost have working for this doesn't seem to fix #31259

**Comment by sf1919** [comment]
Thats a shame! Thought I'd mention it in case we could sort out two issues with one fix!

**Comment by joseph-torsney** [comment]
Good spot and thank you as wasn't aware of it! Maybe there's a more harmonious solution that will fix both

**Comment by gemmaguest** [comment]
Fixed by #31284
