### ISSUE TITLE
Scientific Formatting on Plotting not saving

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#31259]
As seen in Manual testing #31111 

### Expected behavior
When changing the Tick format on the axis of a plot to "Scientific Format" this should still be set as this format when project is saved and reopened.

### Actual behavior
Unless the "Log" checkbox is ticked, the plot axis is defaulting to Decimal format when the project is saved and reloaded.

### Steps to reproduce the behavior
- Load a file
- Plot one or more of the spectra from it. 
- Double click on either the x or y axis to edit the axis. 
- In the dialog that appears change Tick Format to Scientific Format. Plot axis will then change to Scientific Format. 
- Save the project and re-open it,
The tick labels will revert to decimal format.

### Platforms affected
All

**Comment by martyngigg** [comment]
@thomashampson As you've been close to this code recently, would you be able to see how big a fix this would be?

**Comment by thomashampson** [comment]
I've split this into two issues: this one and #31374

**Comment by thomashampson** [comment]
The following matplotlib command is used to set scientific tick format without setting a log scale:

```
from matplotlib.ticker import LogFormatterSciNotation

axes.xaxis.set_major_formatter(LogFormatterSciNotation())
```
