### ISSUE TITLE
Indirect FQFit - Multiple Input allows all fit functions in function menu

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31251]
**Original reporter:** @SpencerHowells

### Description
All fit functions are being allowed in the fit function menu of FQFit when in Multiple Input. When a EISF spectrum is selected then only the EISF function should be allowed. Vice versa for the Width spectra.

The solution to this is not obvious as the parameter combobox is currently not available for Multiple Input, and Multiple Input allows you to load in parameters of different types (Width and EISF at the same time).

I think the problem is that a multiple fit across domains of different parameter types (Width and EISF) doesn't make sense. So maybe we only allow one parameter type to be loaded into Multiple Input at only one point in time? And then this will allow us to restrict the functions in the function menu

### Steps to reproduce the behavior
1.Indirect->Data Analysis-> FQFit tab
2. Click Multiple Input
3. Add Workspace
4. Load the data below and select Width, and ok.
5. Add Workspace again and load the data below. This time select EISF, and click Ok.
6. Check the fit function menu, all fit functions are available.

[irs26176_graphite002_red_Conv_seq_1LDelta_0-50__Result.zip](https://github.com/mantidproject/mantid/files/6390743/irs26176_graphite002_red_Conv_seq_1LDelta_0-50__Result.zip)

### Platforms affected
All

**Comment by robertapplin** [comment]
I put this in Milestone Release 6.1 for now, but I'm not sure how easy this change will be to do properly. Seeing as this isn't causing a major error or crash it might be an idea to push this back to the next release so we have more time

**Comment by SpencerHowells** [comment]
@robertapplin You are correct to say that it should only load one parameter type

**Comment by AnthonyLim23** [comment]
@Harrietbrown is this still present after your changes?

**Comment by Harrietbrown** [comment]
Yes it is still here, I have discussed this with Spencer. It is quite a minor ease of use change that would actualy require a lot more effort to fix. at least untill the refactor si sorted.
