### ISSUE TITLE
Zooming Out On Plot Causes Exception

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31255]
### Expected behavior
There should be some limit on zooming out

### Actual behavior
There is an exception when zooming out which brings up the error reporter. This gets mantid stuck reproducing the error reporter unless mantid is quit

### Steps to reproduce the behavior
Load some data
Plot the data
Continuously zoom out (very far out)

### Platforms affected
all

**Comment by thomashampson** [comment]
For me it breaks when the axis limits reach the maximum size of a double. Manually setting the axis range to +/- 1e305 before zooming out saves a lot of time when trying to reproduce the error.

**Comment by martyngigg** [comment]
Fixed by #31394
