### ISSUE TITLE
Improve error handling message for file not found

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#31261]
As noted in Manual Testing #31111 

### Expected behavior
When running python scripts in the Script Editor, if file cannot be found because the path doesn't exist or the filename doesn't exist the error message should be clear enough that the error is because the file cannot be found.

### Actual behavior
The error message that appears is 
`File "<string>", line 7, in <module> File "C:\MantidNightlyInstall\bin\mantid\simpleapi.py", line 141, in Load msg = 'Problem setting "Filename" in {}-v{}: {}'.format(name, algm.name(), algm.version(), -`.

### Steps to reproduce the behavior
1) Clear the directories in Manage User Directories and add a path that doesn't exist on your machine. Then try the following script in the Script editor
`ws1 = Load('MUSR15189')`

or

2) Trying loading a file you know doesn't exist on your system e.g. x and then run the following in the script editor
`ws1 = Load('x')`

### Platforms affected
Windows 10

**Comment by martyngigg** [comment]
Thanks. This looks to have crept in this release.

**Comment by martyngigg** [comment]
Fixed by #31280
