### ISSUE TITLE
C++ Interfaces do not open, using Floating Window Behaviour

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31265]
### Expected behavior
All interfaces open, no matter which Additional Windows Behaviour is chosen in Workbench Settings
### Actual behavior
Some interfaces don't open when Additional Windows Behaviour is set to floating (it is on top by default)
### Steps to reproduce the behavior
Open MantidWorkbench and open File > Settings
In general settings, change Additional Windows Behaviour to `Floating`
Now try to open `Interfaces > ISIS Reflectometry`

The following list of interfaces fail to open:
ALFview
ISIS Reflectometry
StepScanAnalysis
I think all CPP interfaces

### Platforms affected
Found on Ubuntu current release-next build 6.0.20210427.2323, I think effects all OSs

A "Quick Fix" seems to be forcing the if statement [here](https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/app/mainwindow.py#L356-L360) to be applied to all CPP interfaces, not just Indirect Data Analysis. Sadly, this does not work as it results in the "On Top" behaviour not working!

It seems that replacing 
```
if submenu == "Indirect":
                # always make indirect interfaces children of workbench
                interface.setParent(self, interface.windowFlags())
else:
                interface.setParent(parent, flags)
```
with
```
if parent:
                interface.setParent(parent, flags)
```
may work.

Also consider if a system test can be written to set Additional Windows Behaviour to Floating and then try to open all the interfaces.

**Comment by martyngigg** [comment]
Fixed by #31302
