### ISSUE TITLE
Tiled plot generates broken script.

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31267]
### Expected behavior
Generating a plot script from a tiled plot should result in a script that reproduces the plot.

### Actual behavior
The script does not run because there are missing indexes on the axes object (see snippet below).

```
axes[0][0].plot(EMU00020884, color='#1f77b4', label='EMU00020884: spec 1', wkspIndex=0)
axes.tick_params(axis='x', which='major', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes.tick_params(axis='y', which='major', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes[0][0].set_xlabel('Time ($\\mu s$)')
axes[0][0].set_ylabel('Counts ($\\mu s$)$^{-1}$')
```

### Steps to reproduce the behavior
- Load a workspace (e.g. EMU00020884.nxs from training course data).
- Open the plot 1D dialog by either double clicking the workspace or right clicking and selecting "Plot->Spectrum..."
- Enter "1-4" in the spectrum numbers box.
- Change plot type to "Tiled" and press OK.
- Click the script button on the toolbar and select "script to clipboard".
- Paste the script into the python script editor and close the plot.
- Attempt to run the script, it will fail.

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #31346
