### ISSUE TITLE
SliceViewer missing Help button

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#31262]
As noted in Manual Testing #31111 

### Expected behavior
SliceViewer GUI should have a ? button linking to relevant help

### Actual behavior
There is no ? button in SliceViewer

### Steps to reproduce the behavior
Load a file and then open SliceViewer.

### Platforms affected
Windows 10

**Comment by martyngigg** [comment]
Thanks for spotting this. I don't think the SliceViewer ever actually had one - I've just checked 6 and it's missing.

As it's not a regression then we can put it in the core backlog for future sprints as it's new feature.
