### ISSUE TITLE
Sliceviewer not transforming sphere to non-orthog frame

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31275]
### Expected behavior
Spherical integration shape would be projected onto non-orthog axes (i.e. would not appear spherical in non-orthog view) - like is done for the ellipsoid integration regions.

### Actual behavior
It is not transformed - see screenshot below that compares a spherical shape peak (red) and an ellipsoid peak shape with all axes the same length (green).

![image](https://user-images.githubusercontent.com/55979119/116526441-83ee5d00-a8d1-11eb-9a2a-14de05c0b540.png)

Should we deprecate sphere shape and use more general ellipsoid shape under the hood in sliceviewer (or throughout mantid)?

### Steps to reproduce the behavior
(1) Run this script
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
# FakeMDEventData(ws, PeakParams='1e+06,0,1,0,0.5', RandomSeed='3873875')
FakeMDEventData(ws, EllipsoidParams='1e+05,0,1,0,1,0,0,0,1,0,0,0,1,0.01,0.04,0.02,1', RandomSeed='3873875')
p = CreatePeaksWorkspace(InstrumentWorkspace='ws', NumberOfPeaks=0, OutputWorkspace='peaks')
SetUB(p, 1,1,2,90,90,120) # need to set again as not carried over
pk = p.createPeakHKL([0,1,0]) 
p.addPeak(pk)
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=0.6, BackgroundInnerRadius=0,
    BackgroundOuterRadius=0, PeaksWorkspace='peaks', OutputWorkspace='peaks_int_sphere', 
    Ellipsoid=False, UseOnePercentBackgroundCorrection=False)
IntegratePeaksMD(InputWorkspace='ws', PeakRadius=[0.6,0.6,0.6], BackgroundInnerRadius=0,
    BackgroundOuterRadius=0, PeaksWorkspace='peaks', OutputWorkspace='peaks_int_sphericalEllips', 
    Ellipsoid=True, UseOnePercentBackgroundCorrection=False)
```
(2) Open slicceviewer and overlay both peak tables `peaks_int_sphere` and `peaks_int_sphericalEllips` - they should look the same
(3) Switch to non-orthog view - now they look different

**Comment by martyngigg** [comment]
Fixed by #31288
