### ISSUE TITLE
GUI grid controls don't update when running plot script

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31279]
### Expected behavior
When a plot is generated from a script the "Grid on/off" toolbar button should be "on" if grid lines are on. The tick boxes in the "Edit axis" dialog should be ticked too.
![image](https://user-images.githubusercontent.com/8058899/116537922-c5393980-a8de-11eb-8346-a7fca9f777a5.png)

### Actual behavior
When creating a plot from a script, the states of the GUI controls are default (off) even when gridlines are on.
![image](https://user-images.githubusercontent.com/8058899/116537996-e00bae00-a8de-11eb-87cd-f34619d714e7.png)

### Steps to reproduce the behavior
- Load a workspace and create a 1D plot.
- Turn gridlines on by clicking the toolbar button.
- Generate a script from the plot by clicking the script button and selecting "Script to clipboard".
- Paste the script into the python script editor and close the plot.
- Run the script to recreate the plot.

The grid toolbar button will be toggled off, and the checkboxes in the "Edit axis" dialog will be unchecked.

### Platforms affected
All

**Comment by clayton-tom** [comment]
I started work on this in draft PR #31369 , which contains a solution for the grid checkbox on the double click menu, but decided with Martyn that some proposed changes to fix the issue with the toolbar icon were too extensive to go in 6.1 at this stage. Whoever picks this up next sprint feel free to make use of what I've done so far
