### ISSUE TITLE
Sliceviewer table coords not correct for non-orthogonal view

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31273]
### Expected behavior
The cursor coords in the table would recognise the non-orthogonal transform.

### Actual behavior
They don't and are incorrect - sin the below screenshot we should have (x,y) = (0,3)
![image](https://user-images.githubusercontent.com/55979119/116525437-6c62a480-a8d0-11eb-8960-0d9b066ceaf3.png)

### Steps to reproduce the behavior
(1) Generate non-orthog data
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-5,5,-5,5,-5,5',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='50')
expt_info = CreateSampleWorkspace()
ws.addExperimentInfo(expt_info)
SetUB(ws, 1,1,2,90,90,120)
```
(2) Open in sliceviewer and switch to non-orthog view

**Comment by gemmaguest** [comment]
Fixed by #31457
