### ISSUE TITLE
Slicepoint of sliceviewer pinned to bin centers not re-calling BinMD

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31285]
### Expected behavior
When entering a value for the center of the integrated dimension in sliceviewer it would call BinMD (for MDHisto workspace)
![image](https://user-images.githubusercontent.com/55979119/116556183-1d7b3600-a8f5-11eb-818d-81d47ea597db.png)

### Actual behavior
Presently it just plots the slice at the nearest  bin center along that dimension

**Comment by martyngigg** [comment]
Moving to next release as it's a change in behaviour that we don't want to risk now that testing has been done.

**Comment by RichardWaiteSTFC** [comment]
@martyngigg - I would like to re-open this and take a look for 6.3, but perhaps there is something more urgent?

**Comment by martyngigg** [comment]
@RichardWaiteSTFC I'm happy with that. There isn't anything more urgent yet.

**Comment by martyngigg** [comment]
Fixed by #33203
