### ISSUE TITLE
Mantid notebook does not start

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31299]
### Expected behavior
When running the "Mantid Notebook" shortcut, a browser should appear with a jupyter notebook:
https://docs.mantidproject.org/nightly/concepts/PythonNotebook.html?highlight=jupyter
https://www.mantidproject.org/Using_IPython_Notebook

### Actual behavior
A command prompt appears but nothing else appears to happen.
![image](https://user-images.githubusercontent.com/8058899/116677990-bb780a80-a9a0-11eb-962c-184bf091ab00.png)

### Steps to reproduce the behavior
Run the "Mantid Notebook" shortcut from the desktop.

### Platforms affected
Windows.

**Comment by martyngigg** [comment]
Fixed by #31334
