### ISSUE TITLE
Allow viewing of background when calculated but not applied in fit tab of EngDiff UI

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#31296]
From @Pasarus https://github.com/mantidproject/mantid/issues/31116

This is a regression - previously the user would be able to subtract the background, enabling the view background button for that run, and this would remain enabled even if the user unchecked the subtract background button.

I think this is best fixed as part of the changes to the data structures in the fitting data model that were not included in the EnggUI project save PR

**Comment by RichardWaiteSTFC** [comment]
On loading the background is subtracted, so to reproduce this issue

1. Load focussed data (see previous PRs)
2. Unsubtract background
3. Try to click Inspect background button
