### ISSUE TITLE
Add Systemtest to check floating interfaces launch 

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31303]
As noted in #31265 there should be a system test to check that all interfaces open when the Additional Window Behaviour is set to `Floating`. 

Currently the test only checks when it is set to `On Top` as this is the default. This issue is to add this test.

**Comment by DanielMurphy22** [comment]
I do think this is worth adding!

**Comment by robertapplin** [comment]
This is still worth adding

**Comment by sf1919** [comment]
Not stale

**Comment by jhaigh0** [comment]
@robertapplin do you know if when this issue says "Currently the test..." it is referring to `CppInterfacesStartupTest.py`?

**Comment by robertapplin** [comment]
> @robertapplin do you know if when this issue says "Currently the test..." it is referring to `CppInterfacesStartupTest.py`?

Yes I think its referring to both `CppInterfacesStartupTest` and `PythonInterfacesStartupTest`
