### ISSUE TITLE
Hard crash when overlaying peaks in sliceviewer due to sorting of invalid data

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31301]
A difficult to reproduce bug where sometimes overlaying a peaks table in sliceviewer will cause mantid to crash and throw up many error reporters.

The stack trace is 
```
Name: Not provided  Email: Not provided
        Additional text:
        Not provided
        Stack Trace:
        Traceback (most recent call last):
  File "/opt/mantidnightly/lib/mantidqt/widgets/sliceviewer/peaksviewer/view.py", line 29, in lessThan
    return left < right
 TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'       Using: workbench 6.0.20210424.659 on CentOS Linux 7 (Core)
```

It's not clear why the data being compared are NoneType - the peak table look to be valid (and are created the same way as other tables that do not cause a crash)

**Comment by martyngigg** [comment]
Fixed by #31304
