### ISSUE TITLE
muon fitting change run

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31312]
Open Muon Analysis
Load MUSR 62260
Go to fitting tab
Click simultaneous
Add a GausOsc function
Share Frequency (set to 1) and Sigma
Do a fit

Notice that the A and Phi values are different for each group
Load the next run (62261)
Notice that the A and Phi values are now all the same.

We should preserve the values for each group/pair

**Comment by martyngigg** [comment]
Fixed by #31322
