### ISSUE TITLE
Add empty background removal possibility to ISIS direct inelastic reduction

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#31327]
**Original reporter:** [STFC]/[<ross.stewart@stfc.ac.uk>]

New instruments have guides, which produce specific constant background during experiment.  The background is not affected by sample and can be measured on empty instrument

If this background is indeed measured, it can/should be removed from the results of inelastic data reduction

**Comment by AnthonyLim23** [comment]
@SpencerHowells I thought we already took this sort of thing into account or am I mistaken?

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Our Indirect QENS instruments have no empty background (or didn’t when we began) so we don’t need to do it. Our Reduction has it as an option & the plan is to remove it because it is never used. I don’t know about TOSCA.

**Comment by abuts** [comment]
@AnthonyLim23; @SpencerHowells  -- this is entirely for direct inelastic. This is the background removal from empty instrument caused by guides and we have just measured it. Do not think its relevant to anything else.
