### ISSUE TITLE
Project Save Doesn't Work With A Colour Fill Plot

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31338]
### Expected behavior
To be able to save a color fill plot and re-open

### Actual behavior
The warning message below is shown: `Unknown error occurred. Full detail: Object of type LogNorm is not JSON serializable`
If this message is missed and you close workbench, trying to load the project does not work

### Steps to reproduce the behavior
Load some data
Create a colourfill plot
Save the project with the plot open
Close workbench
Open workbench and try to load the project

### Platforms affected
all

**Comment by gemmaguest** [comment]
Fixed by #31386
