### ISSUE TITLE
Update all external links in codebase

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#31340]
The code contains many external links to www.mantidproject.org. We aim to shrink the size of `www` domain. All user docs should go to `docs` folder and developer docs to `dev-docs` folder in the code. This will also allow the offline help to be more useful.

This task is to assess all of the `www.mantidproject.org` links in the codebase and 
- if the docs are on the wiki and are relevant user/dev docs then move them to the codebase
- if a new page exists on the user docs then simpy update the link.

## Create Docs Versions of Wiki Pages
- [x] [CreateBackToBackParameters](https://www.mantidproject.org/CreateBackToBackParameters)
- [x] [CreateIkeadaCarpenterParameters](https://www.mantidproject.org/CreateIkedaCarpenterParameters)
- [X] [Scripting_SANS_Reductions](https://www.mantidproject.org/Scripting_SANS_Reductions)
- [X] [BinMD_Coordinate_Transformations](https://www.mantidproject.org/BinMD_Coordinate_Transformations)

## Remove links or find correct files they should link to

- [x] https://www.mantidproject.org/Release_Notes_3.5.1 File: v3.5.2/index.rst Line 11
- [x] http://www.mantidproject.org/CreateBackToBackParametersGSAS File: BackToBackExponetional.rst Line: 36
- [x]  http://www.mantidproject.org/Nearest_Neighbours File: SpatialGrouping-v1.rst Line: 23
- [x] http://www.mantidproject.org/SpecialWorkspace2D File: MaskDetectors-v1.rst Line 118, 122 SaveMask-v1.rst Line 36, 39
- [x] http://www.mantidproject.org/MD_Transformation_factory File: ConvertToMD-v1.rst Line 15, ConvertToMDMinMaxGlobal-v1.rst Line 46, 47
- [x] http://www.mantidproject.org/Indirect_Instrument_Definition_Options FIle: InstrumentDefinitionFile.rst Line 899
- [x] https://www.mantidproject.org/MBC_Live_Data_Simple_Examples File: StartLiveData-v1.rst Line 24

**Comment by Matt-Cumber** [comment]
Links which lead to 404 page not found error, keeping this updated:

Link :http://www.mantidproject.org/CreateBackToBackParametersGSAS
File: BackToBackExponetional.rst Line: 36

Link:  http://www.mantidproject.org/Nearest_Neighbours
File: SpatialGrouping-v1.rst Line: 23 

Link: http://www.mantidproject.org/MantidPlot:_SliceViewer
File: BinMD-v1.rst Line 127, 150
File: MDWorkspace Line 102

Link: http://www.mantidproject.org/SpecialWorkspace2D
File: MaskDetectors-v1.rst Line 118, 122
File: SaveMask-v1.rst Line 36, 39

Link: http://www.mantidproject.org/MD_Transformation_factory
File: ConvertToMD-v1.rst Line 15
File: ConvertToMDMinMaxGlobal-v1.rst Line 46, 47

**Comment by Matt-Cumber** [comment]
Un-assigning myself as started the new sprint and will most likely not get to work on this again

**Comment by martyngigg** [comment]
Available as Conor is currently on rotation to another group
