### ISSUE TITLE
Muon Model Fitting Tab Epic

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31349]
### Description
Muon Scientists would like to be able to perform a fit of:
fit parameter vs fit parameter
sample log vs fit parameter
sample log vs sample log

within the Muon Analysis interface. These fit parameters will be stored in a results table generated by the results tab after performing a fit. 

To create this Model Fitting tab the first few steps are clear:
1. Move the cyclic dataset selector combobox to the BasicFittingWidget (from the GeneralFittingWidget)
2. Create a new Model Analysis tab by creating a ModelAnalysisWidget that inherits from the BasicFittingWidget
3. Add two comboboxes to the ModelAnalysisWidget for selecting X and Y fit parameters or sample logs.
4. Might need to create a context for holding the resulting fit data?

**Comment by AnthonyLim23** [comment]
you will also need to add a pane for the plotting of the data

**Comment by AnthonyLim23** [comment]
also yes to 4.

**Comment by robertapplin** [comment]
Ok, like an external plot pane?

**Comment by AnthonyLim23** [comment]
yep. So at the moment we have "data" and "fit". We will add a new one (we can call it "Model" or "Results" or something)
