### ISSUE TITLE
Sliceviewer line plots not respecting Track Cursor status

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31355]
### Expected behavior
That the line plots would be shown at the position of the cursor - if the cursor is not tracked (i.e. the check box in unticked) then the cursor position is only updated when the user clicks inside the plot, I think most people would expect the line plots to behave similarly. This would make it easier for people to take screenshots/export images.

### Actual behavior
It doesn't respect the status of the Track Cursor checkbox, it always plots lines at the current position

**Comment by martyngigg** [comment]
Fixed by #31377
