### ISSUE TITLE
Fix MemoryWidget not stopping thread on keyboardinterrupt

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#31351]
When you use Ctrl+C for example, to create an KeyboardInterrupt exception on python, it seems to largely be ignored by the Memory Widget's thread for updating, and just continues to create new threads and ignore the keyboard interrupt.

This should be fixed as it breaks the expected behavior for programs on UNIX.

I think it's to do with either 1. The QTimer thread not adequately being stopped when a keyboard interrupt is passed, which leaves it to start ANOTHER QTimer thread that ignores it, until you manage to push an interrupt through when it's in the middle of the python code to update the Widget, or 2. The QTimer is not being adequately told to stop on Workbench exit.

I recommend you review how we handle this on Workbench for Project Recovery as that background thread seems to be tidied up nicely.

**Comment by martyngigg** [comment]
Fixed by #31442
