### ISSUE TITLE
Floating/On top doesn't behave on macOS

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#31387]
The additional window behaviour floating/on top doesn't work as expected on macOS.

### Steps to reproduce the behavior
Set to on top (default).
Start an interface that has its own menu.
See that the menu is still that of the workbench.

Set to floating.
Start another interface and it will have the menu of the previous one?

**Comment by SpencerHowells** [comment]
@gvardany I've been directed to https://docs.mantidproject.org/nightly/workbench/windowbehaviour.html 
It affects interfaces on Linux
