### ISSUE TITLE
Muon Analysis - Results table add the Group/pair in its own column

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31381]
**Original reporter:** James Lord

### Description
James mentioned it would be useful if they could add the Group/Pair of a fit result to the results table to make it easier to read what the result is for rather than looking in the middle of a workspace name.

### Steps to reproduce the behavior
1. Perform a few simultaneous fits on Muon Analysis across Group/Pairs
2. Output a results table on the Results tab. 
3. They want to be able to tick Group/Pair in the results tab to add a Group/Pair column

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
Do we want to just makes this a sample log? It will then automatically appear in the results table tab. We can default it to be selected and do some stuff to make sure its at the top of the table.

**Comment by robertapplin** [comment]
> Do we want to just makes this a sample log? It will then automatically appear in the results table tab. We can default it to be selected and do some stuff to make sure its at the top of the table.

Yes that sounds like a good idea to me

**Comment by AnthonyLim23** [comment]
I believe we copy the sample logs from the original workspace that we fit to. So we should add the sample log in the following 3 (that define the group/pair):
https://docs.mantidproject.org/nightly/algorithms/MuonGroupingAsymmetry-v1.html 
https://docs.mantidproject.org/nightly/algorithms/MuonGroupingCounts-v1.html 
https://docs.mantidproject.org/nightly/algorithms/MuonPairingAsymmetry-v1.html

this may need us to manually clean up the diffs in the GUI back end
