### ISSUE TITLE
Muon Analysis - Fit status and chi squared is not cached when undoing a fit

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31417]
### Description
The fit status and chi squared is not being cached when a fit is performed. This means its value cannot be reset after doing `Undo Fit`.

### Steps to reproduce the behavior
1. Muon Analysis, MUSR 62260-1
2. Fitting tab, Add a Gaus Osc function
3. Do a fit. Step to the next dataset, do another fit.
4. Click `Undo Fit` and the fit function, fit status and chi squared should be reset for the selected dataset.
5. Step backwards to the previous dataset and the fit status and chi squared for this has also been reset. We don't want this as Undo Fit should only undo the latest fit.

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #31418
