### ISSUE TITLE
Muon Analysis - TF Asymmetry error confuses the fitting tab

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31411]
### Description
The fitting tab of Muon Analysis can get a bit confused when updating the dataset names when in TF Asymmetry mode and a pair or diff is added to the dataset combobox. We need to check for TF Asymmetry mode compliance when the dataset names in the combobox are updated.

At the moment an error is displayed in the message log and other parts of the fitting tab will get messed up without this check.

### Steps to reproduce the behavior
1. Muon Analysis, MUSR 62260-1
2. Grouping tab, add a pair and tick Plot/Analyse
3. Fitting tab, add a GausOsc
4. Tick Simultaneous fit
5. Change the fit specifier to Group/Pair
6. Select TF Asymmetry mode
7. Untick Simultaneous fit (or change the fit specifier to be Run). There is an error in the log! The fitting tab is now confused.

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
If you load your run with groups and pairs as described above
Add a fitting function
Set the simultaneous fit by to "group/pair" and make sure that a group is selected
Set to TF Asymmetry mode, its ok
Go to sequential fitting and do fit all - oh dear...

**Comment by AnthonyLim23** [comment]
Maybe we should  just deselect the TF asymmetry mode if any pairs are selected.

**Comment by AnthonyLim23** [comment]
I thought we only calculate the function when run is pressed? 

I meant if the user set TF mode in the fitting tab, then goes select a pair for analysis. We create a pop up saying that we have switched to normal fitting.

**Comment by robertapplin** [comment]
> I thought we only calculate the function when run is pressed?
> 
> I meant if the user set TF mode in the fitting tab, then goes select a pair for analysis. We create a pop up saying that we have switched to normal fitting.

It calculates it when the data is loaded because we need to find a suitable normalisation

Ahh sorry I didn't read it very well, I can add a message like that

**Comment by martyngigg** [comment]
Fixed by #31413
