### ISSUE TITLE
Indirect scroll bars

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31426]
For users on laptops we should have scroll bars on:

Bayes interface
Reduction (transmission and S Q, Omega tabs)
Data analysis

**Comment by SpencerHowells** [comment]
@Matt-Cumber Data Analysis has already been customised at user request for tablets & small screens. The miniPlot & Fit Browser can be undocked so that the main window can be reduced in height.

**Comment by Matt-Cumber** [comment]
@SpencerHowells This may be true for the fit tabs but what about the Elwin tab and the I(Q, t) tabs, these could use scroll bars for users with smaller screens

**Comment by martyngigg** [comment]
Fixed by #31452
