### ISSUE TITLE
Indirect Q values dont match

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31427]
The Q values in the plot and detectors do not match.

Open indirect data reduction GUI
switch to `OSIRIS`
In the run bar enter `108538-9`
Tick the sum files box
In the grouping section, select `groups` and set the number to 15
Press run

In the S Q, omega tab
change from browse to workspace
you can then select the one you have just made
set:

-  Qlow to 0.2
- Q widt to 0.1
- Qhigh to 1.7

press run
plot all of the spectra, the Q values are the numbers at the end of the name on the legend
right click and pick `show detectors`, a table will appear. The Q values do not match the plot.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 @robertapplin This often confuses the user. SofQW indeed does rebinning. Also the q values input correspond to the bin edges not centre.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 @robertapplin In a -red file the q value also depends on the energy. When we plot versus q it is q-elastic (zero energy). For Sqw the q,w values for each bin in the red ws is put into the appropriate q,w bin of Sqw. This means that the q,w bin has contributions from several angles. For Sqw it is the true q value. This routine has been used for a decade & also by Direct.

**Comment by SpencerHowells** [comment]
@robertapplin There are SofQW alg docs & Her Manual but they don’t specifically mention that there are multiple angles. Users don’t have need to know. Strictly speaking the corrections progs shouldn’t use Sqw ws because they work in detector angle. But that’s a different issue. Just close this.

**Comment by AnthonyLim23** [comment]
From talking to @SpencerHowells 

The Sqw interface Help file says

Q Low, Q Width & Q High
Q binning parameters that are passed to the SofQW algorithm. The low and high values can be determined using the neighbouring contour plot.
Perhaps we should also say that these define the bin edges.
Also on the gui it should say ‘Q bin definition’ or something.


What we could do is make a minor mod in the detector table. There is a column headed Q which only appears for indirect geometry. This should probably say ‘Q elastic’.

**Comment by Harrietbrown** [comment]
@SpencerHowells, so am I understanding right that all cases of Q in detector tables should be `Q elastic` or only the output `_sqw` workspace?

**Comment by AnthonyLim23** [comment]
we should also be sure that this doesnt break any of the analysis later down the line

**Comment by SpencerHowells** [comment]
@Harrietbrown @AnthonyLim23 In the Detector table all spectra are Q elastic. There is and there never has been anything wrong with the Sqw workspace. Do not touch. It is just information that needs to be improved for those who don not understand how SofQW works.

**Comment by Harrietbrown** [comment]
@SpencerHowells Yes but Q is in both the input detector tables and the detector table for Sqw output. are both to be labeled elastic or only the output?

**Comment by SpencerHowells** [comment]
@Harrietbrown To avoid confusion is it possible to only show Q for _red workspaces?

**Comment by Harrietbrown** [comment]
I will see what can be done.

**Comment by SpencerHowells** [comment]
@Harrietbrown Had some more thoughts. Have it Q elastic for both. For Sqw the value lies within the Q range of the bin

**Comment by AnthonyLim23** [comment]
Is this change getting a bit risky for breaking workflows?

**Comment by Harrietbrown** [comment]
I expect it will likly require us to make changes where ever we have been getting Q from the detector table. I don't know how often that is. Are there instances where we would require it to be `Q inelastic` or just `Q`? because if I am changing it for _sqw and _red I would like to know how many other cases there are of this?

**Comment by AnthonyLim23** [comment]
I think we should make this maintenance

**Comment by SpencerHowells** [comment]
@Harrietbrown There is NOTHING wrong with any of our programs. We only need to change information. The Detector table is only information and is not used anywhere. It is just users not knowing how the programs work!!

**Comment by AnthonyLim23** [comment]
If it is just a table, that is never used anywhere else (other than for users to inspect) its ok for this release.

**Comment by Harrietbrown** [comment]
OK, so you want the _red and _sqw workspaces to have detector tables that list the Q column and `Q elastic` instead?

**Comment by SpencerHowells** [comment]
@Harrietbrown Yes, Just change to Q elastic for both.
