### ISSUE TITLE
spooky action at a distance with muon GUI's

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#31435]
Open the FDA GUI and load some data

Open the muon analysis GUI load MUSR 62260-2
Go to the fitting tab and add a function
Go to sequential fitting and do fit all
Close the FDA - crash

I think this is probably the ADS observers again. 

At first we just want to investigate why this happens. The fix might be too complex for this release.

**Comment by Matt-Cumber** [comment]
After some investigating with the remote debugger it looks to be a problem when calling [unsubscribe](https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/contexts/muon_context_ADS_observer.py#L77-L81) on the muon_context_ADS_observer from the [closeEvent](https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis_2.py#L405-L410) slot in `frequency_domain_analysis_2.py`. It seems to fall over when calling `observeReplace`. My hunch is that at the same time this is executing, the method [addOrReplace](https://github.com/mantidproject/mantid/blob/master/Framework/API/src/AnalysisDataService.cpp#L105) has been called by the fit running in the background which causes some confusion. But this would need more investigation and potentially be too complex for this release now, so moving for the next release.

**Comment by AnthonyLim23** [comment]
If you open MA and load some data, then open FDA and load the same data. The string of the workspace is passed to MA's remove workspace and causes errors (if you remove the check). See https://github.com/mantidproject/mantid/pull/31925

**Comment by martyngigg** [comment]
It's marked as maintenance so I've moved this to 6.4 as we usually do for maintenance tasks.
