### ISSUE TITLE
More multiple scattering tidy up

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#31443]
I've spotted a few more minor issues having done some more tests on the new CalculateMultipleScattering algorithm:

- the y axis on the calculated spectra should have a label "Scattered weight" rather than "Scattered intensity". You have to multiply by the input flux to get the scattered intensity
- the interpolation takes a non-trivial amount of time if you're running with a sparse instrument (especially on a debug build). The progress doesn't reflect this and just sits at 100% for a while with the same "Calculating corrections" message. The message could be changed to "Interpolating" to give a better idea of what's going on. Might be hard to get the progress % more accurate though
- One of the formulae on the documentation page is wrong I think. The integral of Q.S(Q)dQ should equal 2k^2 and not k^2
- The incident intensity I<sub>0</sub> would be better labelled I<sub>0</sub>(lambda) in the section about applying the correction so it's more clear that the profile of the weight vs lambda doesn't necessarily equal the profile of the uncorrected intensity vs lambda
- the logic in q_dir is perhaps not quite right. I think it should be randomly selecting q values in the range 0 to 2k but it's actually selecting them in the range 0 to "max q value in S(Q) profile" which can be a smaller range. I think it's written in this way to cater for S(Q,w) for inelastic instruments where the max q can be greater than 2k. Perhaps use q<sub>min</sub> to q<sub>min</sub> + 2k as the range? q<sub>min</sub>=0 for elastic but this approach would extend to inelastic where q<sub>min</sub> non-zero. I noticed this when investigating a feature visible in most spectra which is that the weight has a sharp rise from a small value at low lambda:

![image](https://user-images.githubusercontent.com/56295817/117962141-cd4d9c00-b316-11eb-8b39-1ff1ad1e110b.png)

- the default value for the NumberScatterings parameter is currently "1". This would be better set to 2 since 1 implies no multiple scattering

**Comment by gemmaguest** [comment]
Fixed by #31542
