### ISSUE TITLE
Muon Analysis - Crash when switching between tabs

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31454]
**Original reporter:** Aidy

### Description
A crash is occurring when switching between tabs on Muon Analysis.

```
Stack Trace:
       Traceback (most recent call last):
 File "C:\MantidNightlyInstall\scripts\Muon\GUI\Common\dock\dockable_tabs.py", line 87, in detach_tab
   self.attached_tab_names.remove(name)
ValueError: list.remove(x): x not in list
```

### Steps to reproduce the behavior
1. Open Muon Analysis
2. Furiously click on the Results tab. One of your clicks must hit the results tab when it becomes unattached in order to trigger a mouse drag event.

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #31455
