### ISSUE TITLE
Muon Analysis - Allow TF Asymmetry fitting for the differences between groups

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31456]
**Original reporter:** Peter Baker

### Description
We think it would be useful to be able to do TF Asymmetry fitting for the difference between groups.

### Platforms affected
All

**Comment by AnthonyLim23** [comment]
I have just spoken to Peter. The method used here does not produce an expected result. What they meant to do was to normalise the individual groups first and then take the difference. This is what they meant by TF Asymmetry with group differences (which is the functionality we already have).
