### ISSUE TITLE
Muon Analysis Autoscale Y Turned Off When Grouping Updated And Tiled Plot

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31478]
### Expected behavior
Autoscale y should remain on if the state was on before updating the grouping

### Actual behavior
Autoscale y is turned off

### Steps to reproduce the behavior
Load EMU110795
In grouping tab clear all groups etc.
Add two groups, once called one and one called four
Make sure both are plotted, then change the plot to a tiled plot by Group/Pair
Make sure autoscale y is on
Change the Detector IDs of group four to 4 (notice autoscale y turned off)
Turn it back on
Change the periods of four to 2 (notice autoscale y turned off)

This is a little annoying

### Platforms affected
all, presumably (tested on windows)

**Comment by gemmaguest** [comment]
Fixed by #31487
