### ISSUE TITLE
ALC Axis Labels On All Interfaces/Tabs

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31479]
### Expected behavior
It was requested by a user to add axis labels to all plots throughout the ALC interface not just on data loading. Axis labels were added to the data loading tab in this pr https://github.com/mantidproject/mantid/pull/29897

**Comment by Matt-Cumber** [comment]
Also look at including the same fix for run number and scientific notation on all tabs as well

**Comment by AnthonyLim23** [comment]
I think Tom was looking at the scientific notation stuff for the general plotting.
