### ISSUE TITLE
Include Units With Sample Logs Muon Analysis And ALC

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31482]
Within the NeXus files some logged values have associated units which are stored as an attribute. This should be seen when creating a plot against the log. For example, in the ALC interface if doing a plot of the log of the HIFI main field, the plot should say something like "Field_Main (G)" with the units in brackets instead of just "Field_Main"

**Comment by AnthonyLim23** [comment]
has this been fixed by https://github.com/mantidproject/mantid/pull/31957

**Comment by AnthonyLim23** [comment]
@Matt-Cumber has this been fixed?

**Comment by Matt-Cumber** [comment]
The plot in ALC doesn't have units, which would be nice to have
