### ISSUE TITLE
Script Repo fails setup on MacOS

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31486]
### Expected behavior
Setting up the script repo in a new folder works seemlessly
### Actual behavior
Cannot connect to the server on MacOS
### Steps to reproduce the behavior
In Workbench, go to File > Script Repo
Click OK, then in the file browser, create a new folder, select it and click Open.
![Screenshot 2021-05-17 at 11 21 11](https://user-images.githubusercontent.com/55980573/118476583-9821bf00-b705-11eb-8ef8-066a506894b2.png)
Note the link to _antidproject with no M!
### Platforms affected
MacOS, Catalina and Big Sur, recent nightly and release 6.0

@StephenSmith25 could NOT reproduce, but @Matt-Cumber could!

**Comment by martyngigg** [comment]
Adding High Priority as we should not release with it in this state.

I just want to confirm we have checked it works on Linux & Windows?

**Comment by martyngigg** [comment]
@DavidFair I think this could be to do with the server...

**Comment by DanielMurphy22** [comment]
It works for me on Linux and Windows, I've only seen it broken on MacOS, but it very well could be a server problem. Do you see this problem on MacOS @DavidFair ??

**Comment by martyngigg** [comment]
It looks like we have an issue with the Jenkins [job](https://builds.mantidproject.org/job/sync_scripts_download/842/console). It was calling `python` straight but changing that to `python3` shows another issue in the link.

**Comment by martyngigg** [comment]
> It works for me on Linux and Windows, I've only seen it broken on MacOS, but it very well could be a server problem. Do you see this problem on MacOS @DavidFair ??

That's odd. Maybe we have two problems...

**Comment by DavidFair** [comment]
I'm getting the same error here on Catalina with the latest nightly 
Using wget I think I know why the problem is difficult to pin down, it depends on if you have IPv6 as wget / similar fails back to IPv4

Could @Matt-Cumber check if he has IPv6 [here](https://test-ipv6.com/), and equally anyone who it does work for check that they don't have it to confirm the theory

**Comment by Matt-Cumber** [comment]
> Could @Matt-Cumber check if he has IPv6 [here](https://test-ipv6.com/), and equally anyone who it does work for check that they don't have it to confirm the theory

Running that check I fail with `No IPv6 address detected` and `Connections to IPv6-only sites are timing out. Any web site that is IPv6 only, will appear to be down to you.`

**Comment by DavidFair** [comment]
And it failed for you too?
Well that possibly blows the IPv6 theory out of the water :thinking:

**Comment by DavidFair** [comment]
Ah but the VPN will use your home connection wherever it can, so it will access via IPv6 is my hunch

I've just asked @StephenSmith25 to run the test locally too

**Comment by DavidFair** [comment]
Stephen doesn't have IPv6 I'm 90% certain this is the offender as were not doing [happy eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) correctly and anyone on site won't notice it as business adoption of IPv6 is....well slow...

So this is almost certainly a server issue that's existed for a while but only coming to boil as more ISPs are migrating end-users
