### ISSUE TITLE
ISIS SANS Reduction broken

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#31485]
**Original reporter:** @smk78 

### Expected behavior
- Reduction should reduce

### Actual behavior
- All reductions fail due to a None type being passed in where a WS should be, this is a regression since the start of the release

### Steps to reproduce the behavior
- Use the LOQ demo example

**Comment by DavidFair** [comment]
Caused by 76fac4a58f04323d558ab3bb972ab53e042299b6

Fixed by https://github.com/mantidproject/mantid/pull/31477 as it's the same underlying cause (hence I didn't notice it): our data structures get out of sync so the reduction backend wasn't aware of rows loaded from the front-end

**Comment by gemmaguest** [comment]
Fixed by #31477
