### ISSUE TITLE
Peak function in fit browser/interactive tool gets out of sync with peak function in settings

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31504]
### Expected behavior
Changing the peak function in the workbench settings when a plot and fit browser are open would update the peak function in the interactive tool that adds a peak to the plot such that the next peak a user adds would be the one selected in the settings.

### Actual behavior
It is not updated, it adds the original peak function (i.e. the last one selected in the right-click menu in the interactive tool) and overwrites the peak function just set in the workbench settings

### Steps to reproduce the behavior
(1) Create a workspace
```
ws = CreateSampleWorkspace(Function="User Defined",   UserDefinedFunction="name=LinearBackground, 
    A0=0.3;name=Gaussian, PeakCentre=5, Height=10, Sigma=0.7",  NumBanks=1, BankPixelWidth=1, XMin=0, XMax=10, 
    BinWidth=0.1, WorkspaceType="Event")
```
(2) Plot a spectrum, open the fit browser and add a peak - note the function (e.g. Gaussian)
(3) keep the plot open and change the default peak function in the workbench settings  (File>Settings>Fitting>Default Peak Shape)
(4) Add a peak on the plot (it won't have changed to the new peak function)
(5) Check in the workbench settings, the peak function will have been overwritten with the one from the fit browser

### Platforms affected
Found windows

**Comment by thomashampson** [comment]
After offline discussions, we're not sure what the expected behaviour should be. See the closed PR for more discussion:
#31509
