### ISSUE TITLE
Smoke Testing Updates for 6.1 release

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#31518]
The first point is the only really important one, to try to get IDAaaS testing off the ground this release! The rest are just nice to have. Feel free to ask me for more explanation on any of these!
- [x] Add instructions for how to install a release candidate on Mantid Preprod environment on [IDAaaS test](https://isis-test.analysis.stfc.ac.uk/#/login) (ask @martyngigg what he wants public here, maybe testers should contact the QA manager for instructions?)
- [x] Include[ link to install instructions for .deb](https://download.mantidproject.org/ubuntu.html) Ubuntu umbrella 
- [x] Remove the original [create_issues.py,](https://github.com/mantidproject/documents/blob/master/Project-Management/Tools/RoadmapUpdate/SmokeTesting/create_issues.py) as we now use create_issues_OS.py 
- [x] You can probably also remove the "umbrella" Excel sheet, but double check this!
- [x] Update SmokeTesting [ReadMe](https://github.com/mantidproject/documents/blob/master/Project-Management/Tools/RoadmapUpdate/SmokeTesting/README.md) as you wish!

**Comment by robertapplin** [comment]
Fixed by https://github.com/mantidproject/documents/pull/93
