### ISSUE TITLE
FindPeaks from fit browser not finding 'easy' peaks 

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31544]
FindPeaks doesn't seem to be finding easy peaks - on real spectra it often misses the strongest peaks.

### Steps to reproduce the behavior
(1) Make a workspace with a fake peak
`ws = CreateSampleWorkspace(Function="User Defined",   UserDefinedFunction="name=LinearBackground, A0=0.3;name=Gaussian, PeakCentre=5, Height=10, Sigma=0.7",  NumBanks=1, BankPixelWidth=1, XMin=0, XMax=10,  BinWidth=0.1, WorkspaceType="Event")`
(2) Plot and open fit browser
(3) Click Setup > Find Peaks 

![image](https://user-images.githubusercontent.com/55979119/119147243-4e0d4600-ba43-11eb-8fc9-c144b36764f6.png)

No peaks are found!

**Comment by wdzhou** [comment]
@RichardWaiteSTFC Eventually you are going to fix the `FindPeaks` algorithm which can never find peak? 👍
