### ISSUE TITLE
ALC Axis Scale Not Saved

### ISSUE THREAD

**Issue by Matt-Cumber** [mantidproject/mantid#31554]
### Expected behavior
The selected scale should remain the same and be used when plotting new data

### Actual behavior
After changing the scale, plotting new data uses the default linear scale instead but the alternate scale is still show to be chosen

### Steps to reproduce the behavior
Open ALC
Search for a data file (e.g. HIFI110542)
Click Load
The data should be plotted, right click the plot and change the x-axis scale to log, the plot should be updated
Now load HIFI110543
The x-axis will be on linear scale
Right click the plot and see that the x-axis still says log even though it is linear

### Platforms affected
all

**Comment by martyngigg** [comment]
Fixed by #31556
