### ISSUE TITLE
Problem in Transfit algorithm

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#31551]
**Original reporter:** Chris Ridley

Chris seems to have identified a problem with the transfit algorithm. Excerpt from email:

_Sadly there seems to be an issue. The values are quite different from what I get from the code I originally put together. For example, take a look at run PRL115780. If I run this with defaults, 290K in calibration, and then measurement mode, I get 506K +- NaN on my laptop (mac), and 506K +- 111 on the instrument machine. If I run the original code on my laptop and the instrument PC with the same run number, I get 279K +- 36. The sample is sitting at room temperature, so the value should be around 290K. The original Fortran is giving 300 +- 12, which is close enough to the new code not to be concerned with._

**Comment by martyngigg** [comment]
Fixed by #31574
