### ISSUE TITLE
ALC crash when changing plot axis scale

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#31571]
### Expected behavior
Changing between linear and log axis scales in the ALC Analysis interface plot should not cause a crash.

### Actual behavior
It does crash.

### Steps to reproduce the behavior
- Open the Muon->ALC interface
- Load HIFI run 110542 from the ISIS archive
- Right click the plot and change both x and y axes to log scale
- Change only the y axis back to linear scale
It will crash

### Platforms affected
All

**Comment by gemmaguest** [comment]
Fixed by #31580
