### ISSUE TITLE
Ubuntu Smoke Tests: Release 6.1

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31650]
* Follow the instructions [here](https://download.mantidproject.org/ubuntu.html) to install the .deb for Ubuntu

**Before testing**:
- Check this master issue relates to the OS you will test on.
- Find an unassigned testing issue below and assign yourself.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment on the testing issue with any issues you came across.
- If no issues were found, or they are now all resolved, please close the testing issue.

If you have any questions please contact the creator of this issue.

## 6. Ubuntu Workspace/Algorithm Smoke Tests  :man_astronaut: :woman_astronaut: :space_invader: #31649

**Comment by gemmaguest** [comment]
All child issues are now closed :+1:
