### ISSUE TITLE
Cannot save plots in Project Save

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#31655]
### Expected behavior
Project saving should save out plot windows, and re-open them

### Actual behavior
Plotting windows are not saved

### Steps to reproduce the behavior
- Load in some data, we used OSIRIS but it would be worth checking with multiple
- Run Project Save to somewhere, there will be an error about `tickDir`
- Reload Mantid, this emulates what a user is likely to do and checks we aren't relying on something that is around if you simply clear memory
- Load in said project, the plotting window should appear

This appears to break both colour fill and 1d plotting, possibly more?

### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #31663
