### ISSUE TITLE
Conda: Bring Conda style into line with other OS styles

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#31651]
Add the same style sheet to all of Linux, which will set the style for most things including, background, icons, font, text size, progress bar style, and more.

The difference is caused by a lack of the libqgtk3.so library in `CONDA_ENV/plugins/platformthemes`, so the project will need set the style for all Linux OSs, which will ensure consistency at the very least.

**Comment by martyngigg** [comment]
It looks like there is an issue with the changes that altered the icons as it has caused a bug:

* Open workbench
* Open multiple scripts or create at least 2 new ones
* Try to close any of the last tabs with the cross on the tab
* It will close the first tab instead

I have reverted the change until it can be dealt with
