### ISSUE TITLE
Blank Engineering Diffraction UI saves in project save if previously opened in session 

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#31670]
Found by @Pasarus 
### Expected behavior
If an interface is not open when project save triggers, it should not save

### Actual behavior
It does, and when loaded an empty EngDiffUI opens

### Steps to reproduce the behavior
1. Open the interface, close it
2. Save the project
3. Load the saved project

### Platforms affected
All

**Comment by RichardWaiteSTFC** [comment]
Is this a duplicate of #31653?

**Comment by Pasarus** [comment]
It is.
