### ISSUE TITLE
Index out of range error in slice viewer with transposed axis

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#31675]
### Expected behavior
- Transposed workspaces (where TOF is in Y) should be handled

### Actual behavior
- Multiple index errors are produced as the mouse is moved
- On Mac OSX swapping axis does not update the button, this is likely a missing call to `paint` or equivalent when the button changes

### Steps to reproduce the behavior
- Load `CNCS_23937` or any workspace where the number of spectra != TOF range
- Set TOF into `y` and spectra to `x`
- Move mouse into top right, notice on the table that spectra and TOF are flipped incorrectly
- When your mouse goes OOB relative to the original (untransposed axis) you will get errors

This affects both Event and Histogram workspaces 
### Platforms affected
All

**Comment by martyngigg** [comment]
Fixed by #32219
