### ISSUE TITLE
Plot Advanced window log options squashed

### ISSUE THREAD

**Issue by clayton-tom** [mantidproject/mantid#31680]
See below, the log options on the plot advanced window are squashed and potentially difficult to read.
![image](https://user-images.githubusercontent.com/68227228/120447124-2b075e00-c382-11eb-9093-e924591eb78f.png)

### Platforms affected
Confirmed on IDaaaaas and OSX, assumed on all

**Comment by martyngigg** [comment]
Fixed by #32362
