### ISSUE TITLE
EngDiff UI crashes on IDAaaS when removing runs

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31687]
UI crashes when you remove runs and if you subsequently try to load those same runs again in the same UI window 

### Platforms affected
IDAaaS

**Comment by DannyHindson** [comment]
@RichardWaiteSTFC - do you remember which tab in the UI this crash related to? Was it removing and reloading files on the Fitting tab using the "Remove All" and "Load" buttons?

**Comment by RichardWaiteSTFC** [comment]
> @RichardWaiteSTFC - do you remember which tab in the UI this crash related to? Was it removing and reloading files on the Fitting tab using the "Remove All" and "Load" buttons?

It was the fitting tab, using the remove selected or remove all and then loading the same runs - the bug for remove all might have been fixed by #32000?

**Comment by DannyHindson** [comment]
I've done some tests with a build before\after the changes in #32000 and I think that's fixed it so I'll close this issue. I was able to reproduce a crash before the changes by:

a) loading some data onto the fitting tab
b) hitting clear in the workspace widget (this clears the table in the Fitting tab as well as the main ws list)
c) hitting "Remove All" back on the fitting tab

This gave the following error that Tom's changes fix:

![image](https://user-images.githubusercontent.com/56295817/125593279-c9f51b3f-d394-4847-a99e-999da2bdd7c8.png)
