### ISSUE TITLE
Implement output individual function fits in other QENS Fitting tabs

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#31705]
**Original reporter:** @SpencerHowells

In the Convolution tab in QENS Fitting there is an option to Output Composite Members. This option should be available in other tabs. This option also is disabled when the fitting type is made simultainious and should be made to work for that case.

The Output Composite Members is found in the Fit Options Browser (below the Function Browser)

**Acceptance Criteria**
- [ ] Its possible to use the Output Composite Members on  I(Q, t) tab

**Comment by SpencerHowells** [comment]
@Harrietbrown ConvFit should have Output Composite Members & Convolve Members. IqtFit just Output Composite Members. Other 2 neither.

**Comment by SpencerHowells** [comment]
@Harrietbrown Keep this opne please

**Comment by SpencerHowells** [comment]
@Harrietbrown keep open please

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement output individual function fits in other IDA fit tabs](https://trello.com/c/iidtNsIX/15-implement-output-individual-function-fits-in-other-ida-fit-tabs)

**Comment by SpencerHowells** [comment]
This should only be added to the IqtFit gui. Not needed in MSD or F(Q)
