### ISSUE TITLE
Clang OSX build warnings

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#31732]
If you build mantid with the latest version of AppleClang (I'm guessing llvm clang as well) you'll get build warnings. This issue is to resolve all the warnings.

**Comment by martyngigg** [comment]
Moved to maitenance that happens while preparing 6.3 but will land in 6.4

**Comment by martyngigg** [comment]
There is 1 compiler warning and many linker warnings in the latest [pipeline build](https://builds.mantidproject.org/job/main_nightly_deployment_prototype/311/execution/node/40/log/?consoleFull)

**Comment by martyngigg** [comment]
The build seems to be clean now. Closing.
