### ISSUE TITLE
Support sphere as simple shape in SetSample

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#31745]
Sometimes crystalline samples are approximated with spheres for quick calculation of attenuation corrections.
While `SetSample` allows for arbitrary CSG objects, it could also support a Sphere as a predefined simple shape, like cylinder.

**Comment by RichardWaiteSTFC** [comment]
This looks like a duplicate of #32892 (or rather that issue duplicates this) - but has more info. Can you confirm?

**Comment by gvardany** [comment]
Yes, they are the same, we can close this one.
