### ISSUE TITLE
Make Muon Analysis GUI adjust to screen resolution

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#31755]
### Expected behavior
The GUI for Muon Analysis should adjust size of labels, buttons, text boxes etc depending on user's screen resolution.

### Actual behavior
During testing for #31601 it was identified that some buttons on the fitting tab of Muon Analysis were barely visible on a 4K screen. During discussions of this it was noted that previous fixes for 4k display screens (e.g. #31311 ) now cause display issues for non-4k displays because of the use of fixed sizes. Implementing dynamic size adjustments may be a better way forward than continually making small fixes that may not work for everyone. 

### Steps to reproduce the behavior
Open the Muon Analysis GUI and note
for non-4K screens:-
- labels and buttons to the left hand side of the fitting tab have an unusual amount of space allocated to them as opposed to those to the right. In the example below note the Workspace information is truncated
![image (1)](https://user-images.githubusercontent.com/55837273/121508584-a8b01700-c9dd-11eb-8255-f9effd8db852.png)

for 4K screens:-
- the ```>>``` and ```<<``` buttons on the Fittings Tab are so small you can't see the arrows and therefore it is hard to tell which direction they are pointing in. See the buttons on the 'Select Workspace' line in the image below
![Screenshot (141)](https://user-images.githubusercontent.com/55837273/121509069-2d9b3080-c9de-11eb-9425-a40e5d2dbf1e.png)

There are likely other display screen issues that would be fixed by implementing an automatic adjustment for display screen resolutions.

### Platforms affected
Windows 10 - other platforms may be affected & this needs further investigation

**Comment by robertapplin** [comment]
Thank you for opening this @sf1919
