### ISSUE TITLE
Tidy up constants in LeadPressureCalc algorithm

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#31832]
Address feedback from Martyn on https://github.com/mantidproject/mantid/pull/31784. Pushed that PR through to get fix out to Chris Ridley quickly

Pull out constants as module level variables in CAPS

**Comment by martyngigg** [comment]
This isn't required for the release so I'll set it as maintenance.

**Comment by DannyHindson** [comment]
Closing because constant names line up with same names used in documentation so clearer to keep as is
