### ISSUE TITLE
Workspace calculator throws errors when clearing ADS

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31863]
### Expected behavior
Clearing the ADS (or otherwise deleting a workspace) would not cause workspace calculator to throw an error. 

### Actual behavior
It looks like the calculator populates itself automatically with a workspace and when clearing the ADS it throws an error (even when the widget is not visible - it looks like it's being run on clear).
```
The LHS input workspace does not exist.
The RHS input workspace does not exist.
The LHS input workspace does not exist.
The RHS input workspace does not exist.
```
If you only delete the workspace in the calculator it doesn't throw an error - but neither does it remove the workspace from the calculator so clicking Go will throw an error.

### Steps to reproduce the behavior
(1) Make a workspace
`ws = CreateSampleWorkspace(Function="User Defined",   UserDefinedFunction="name=LinearBackground, A0=0.3;name=Gaussian, PeakCentre=5, Height=10, Sigma=0.7",  NumBanks=1, BankPixelWidth=1, XMin=0, XMax=10,  BinWidth=0.1, WorkspaceType="Event")`
(2) Check the calculator widget - it looks like this
![image](https://user-images.githubusercontent.com/55979119/123066915-67216200-d408-11eb-8c1a-94870113fdba.png)
(3) Clear ADS

**Comment by DannyHindson** [comment]
@darominski - please can you take a look at this? It seems like the new widget generates errors in the log if the user clears all the workspaces, even if they've hidden the workspace calculator widget. I think the widget should probably quietly clear the lhs or rhs dropdown without creating an error if the dropdowns contain a workspace that gets deleted.

**Comment by darominski** [comment]
Yes, absolutely. I am not sure why does the `WorkspaceSelector` moves from its default state (empty) to selecting one of the workspaces in the ADS. In any case, I propose to supress the error logs altogether. The related PR id is: #31867 .
