### ISSUE TITLE
Muon Analysis - Extend Fitted line beyond data points option

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31876]
### Description
The ability to extend the fitted line on a plot beyond the data points has been requested by Muon scientists. This would be useful in model fitting where there are a small number of data points, and they want to see the trend of the line beyond these data points. This is **not** a fitting feature, but rather a plotting feature. 

This is basically an extension of the `Plot Guess` feature. The `Plot Guess` feature should therefore be extended by:
- Adding a line edit to allow users to enter the number of steps to use when calculating the guess.
- Plot guess should also just plot the data within the x extends of the plot rather than the x extents of the fit.

To do this, `Plot Guess` should be moved to the `Fit Pane`. This makes sense as it is a plotting feature not a fitting feature, and so separating it from the Fit widgets is a good idea. When Plot Guess is unticked, the `Number of Points` lineedit should be hidden.

There were some suggestions at the Muon project group meeting to rename it to `Plot Fit Function` instead of `Plot Guess`.

**Comment by AnthonyLim23** [comment]
This is on hold

**Comment by AnthonyLim23** [comment]
Will need to talk to Francis and Steve about the design. It might be worth replacing the `plot guess` with a new:

`<tick box> plot function with <line edit> data points`

and take the range from the start and end x on the fitting pane. I suggest a mock up of this to ask if its ok
