### ISSUE TITLE
By default populate browse bar in EngDiff fitting tab with range of runs last focussed

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#31906]
Presently it points to last focussed run

**Comment by clayton-tom** [comment]
The last ws and path for this are kept in the members `self._last_path` and `self._last_path_ws` in the focusing model, and the Observable that passes this to the fitting tab is `focus_run_notifier` L27 in the focus presenter. Hopefully should be able to modify this to save the list of runs parsed from the user input and load these instead
