### ISSUE TITLE
Misplaced colorfill plot Z-axis scale 

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#31946]
### Expected behavior

Colorfill plot Z-axis scale and labels used to be placed outside the frame of the plot. 

### Actual behavior

Currently, the scale and labels are plotted inside the frame, overlapping the data and greatly diminishing readability.

### Steps to reproduce the behavior

1. In workbench, create a default sample workspace using `CreateSampleWorkspace`
2. Plot as colorfill, observe that the scale and labels are placed inside the plot frame

### Platforms affected
Tested on current nightly on Ubuntu 18.04

**Comment by martyngigg** [comment]
We just spotted this too. I can confirm that reverting the changes in #31375 restores the proper axes layouts. On my Mac I also saw an error: `This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.`
