### ISSUE TITLE
ILL SANS v 2.0

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#31943]
The current SANS workflow is built such that it works both for TOF and monochromatic modes.
While it is optimal for TOF, it is not optimal for monochromatic, since the x-axis dimension is not utilized at its best.
One could use that dimension to store time frames for kinetic monochromatic, sample environment parameter scans and multiple different samples in case of standard SANS.
This will greatly reduce the number of workspaces and groups that are created/deleted in the process.
This will also eliminate the redundancy of the in-memory instrument object being copied for each sample and result in vast memory usage reduction, which will in turn speed up the runtime due to avoiding allocation and deallocation of the memory for the instrument clones.
The downside of this (and the original reason why it wasn't done in the first place), is that certain child algorithms required in the workflow need to be reworked to accept also 2D workspaces, where the x-unit is not the wavelength, but is just an integer frame index. This doesn't just mean disabling the validators; a TOF SANS workspace, for example, should be integrated to a single I(Q), whereas a kinetic mono SANS workspace should be integrated to a stack of I(Q)s, one per frame. This will allow outsourcing, for example, the loop over samples to the C++ child algorithms, rather than in the master python workflow, which is what is done currently and proves to be slow. Some child algorithms will need to process the input 2D workspace frame-wise, i.e. bin-by-bin, and produce individual outputs by stacking them along the spectrum axis of the output workspace. 

 The changes required are as follows:

- [x] Deprecate the `SANSILLAutoProcess` (don't remove it yet, as it will be the only option for TOF SANS for the time being)
- [x] Deprecate the `SANSILLReductionv1`

**Loader**

- [x] See the issues [here](https://github.com/mantidproject/mantid/issues/31996). These are all small speed-ups, but one of them is a breaking change, so will require a v2. https://github.com/mantidproject/mantid/pull/32155

**Child algorithms** 

- [x] Refactor/extend the following algorithms to take 2D, but monochromatic inputs, where x-axis is just an integer index; the wavelength can be taken from the sample logs:
- - [x] Stitch @gvardany  #31425
- - [x] Add an option LinearizeAxis to ConjoinXRuns  
- - [x] CalculateDynamicRange (to take the constant lambda as input)
- - [x] ApplyTransmissionCorrection (with an input transmission workspace) 
- - [x] Q1DWeighted (including the wedges) @MathieuTillet PR #32061
- - [x] DeadTimeCorrection integrates all the frames before calculating the correction, this is correct for TOF, but for monochromatic it should calculate the corrections frame-wise. @darominski  PR #32047

**Workflow**

- [x] Devise a new algorithm `SANSILLMultiProcess` based on the old one, but able to reduce an *entire* experiment in one go, to avoid loops in the python side. The new one should take multiple samples at multiple distances (including kinetic), stack all samples in singe 2D workspaces (per distance), correct those workspaces for all the instrumental effects and then pass to the integration. The main difference is going to be in the process sample and process transmissions sections. In the same passage sort out the details as below:  @gvardany 
- - [x] New `SANSILLReduction-v2` with the new way of merging
- - [x] Revise the beam center correction to take into account the parallax effect
- - [x] For D22, subtract the tilt angle from 2theta before putting into the parallax correction formula
- - [x] Revise the solid angle correction method for D22B front panel with tilt - change to `GenericShape`?
- - [x] Revise the parallax correction formula for all the instruments (email from Charles)

**Drill** 

- [x] Add a feature to drill to make a single algorithm call on the whole sample group (or multirow selection) by appending the contents of specified columns, putting `,`  as delimiter. The current way of working should remain as well. Each algorithm should define in the configuration whether it has to be called row-by-row or group-by-group. It should define also the names of the columns that need concatenation if doing group-by-group. @gui-co 

**Instrument Viewer**

- [x] Make the slider of the instrument viewer discrete if the axis is dimensionless, i.e. has no units. This means that both the extent of the slider bar, the position and the width of the slider button must be discrete integers. The minimum width must be one, which should be the default. The default position should be at index 0. Mind, that the workspaces can be point data or histogram data.  @MathieuTillet 

**Exports**

- [x] Make sure the savers can work with multi-spectrum reduced data producing individual files, one per spectrum. It should be possible though to save all into a single file, too. @gui-co  https://github.com/mantidproject/mantid/pull/32168
- - [x] SaveAscii2
- - [x] SaveCansas1D

**Comment by martyngigg** [comment]
I was just moving uncompleted feature issues over to 6.4 but I notice this one has all tasks marked as done so is it ready to be closed?

**Comment by gvardany** [comment]
Nope, it's ready to be reviewed :)
