### ISSUE TITLE
Refactor PSIBackgroundSubtraction to be useable by the Corrections tab

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31967]
### Description
A couple of changes/additions are required for the `PSIBackgroundSubtraction` algorithm to be used by the corrections tab in Muon Analysis and FDA. Backwards compatibility does not need considering as this algorithm is barely used.

- [ ] Currently, the default function is a FlatBack + Exp Muon Decay with no option to remove the Exp Muon Decay. We need to be able to only have a FlatBack.
- [ ] We need to be able to pass in a fit function (e.g. FlatBack) with parameter values that are not default. This is not possible at the moment.
- [ ] The algorithm should return the fitted function, because we need the background value (`A0`) and the `A0 Error`
- [ ] The algorithm should not do the subtraction itself but calculate the background value before returning it.

Maybe we don't even need the PSIBackgroundSubtraction algorithm anymore and just need to use the Fit algorithm?

**Comment by AnthonyLim23** [comment]
I think it is possible that we could get rid of the algorithm and use a combination of fit and minus. 

The bit of functionality you will need to be careful to replicate is the estimates for the start and end x values.

**Comment by AnthonyLim23** [comment]
@robertapplin should we close this?

**Comment by robertapplin** [comment]
Yes I think so
