### ISSUE TITLE
Workspace Calculator causes a crash when generating lots of workspaces

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31965]
### Expected behavior
Generating a large number of workspaces shouldn't cause a crash from the workspace calculator.

### Actual behavior
If I generate a large number of workspaces from a script or a GUI the workspace calculator causes a crash. It appears to happen during a resize event.

![image](https://user-images.githubusercontent.com/40830825/124461144-2cb0b100-dd88-11eb-9ba3-933fa88cc81c.png)

### Steps to reproduce the behavior
1. Open Workbench and run the script below.
2. While the script is running you can switch to the WorkspaceCalculator view and see that the embedded `WorkspaceSelector`'s keep resizing.
3. Eventually there will be a crash. Re-run the script if there isn't

```py
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

for i in range(500):
    CreateSampleWorkspace(OutputWorkspace="ws" + str(i))
```

Initially I found this crash when generating workspaces from the Muon Analysis interface.

### Platforms affected
Found on windows

**Comment by robertapplin** [comment]
@darominski would you know how to fix this?

**Comment by darominski** [comment]
I am looking into this. I can reproduce this issue on Ubuntu 18.04, albeit there the number of workspaces that are created before things go wrong is much larger, always above 8000. Then, there is a segfault in `QStandardItem *QStandardItem::child(int row, int column = 0) const`, but its origin seems to be the same.

`WorkspaceCalculator` uses `WorkspaceSelector` widget and it is always listening to ADS. It seems that there are more workspaces than a WorkspaceSelector can handle. I would like to test it against workspace selectors in different widgets as well. One way to address this issue would be to limit the maximal number of items the `WorkspaceSelector` holds, e.g. to 200-300. This approach seems to work fine in my tests with number of workspaces up to 20k. The cost is the limitation of functionality: the auto-completion and selecting of workspaces that are created when the counter is above the limit does not work (they are not added to the model, naturally), but when there are typed-in, it is possible to retrieve the desired workspace.

The other solution would be to ensure that when a widget is not visible from workbench, then it is not listening to any events. I must say am not sure how to approach it from this direction at the moment.

**Comment by martyngigg** [comment]
> The other solution would be to ensure that when a widget is not visible from workbench, then it is not listening to any events. I must say am not sure how to approach it from this direction at the moment.

I think this would be preferable. Can we use either the show/hide/closeEvent methods to subscribe/unsubscribe to the events as needed?
