### ISSUE TITLE
Use new Muon function to get Counts workspace names

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#31997]
### Description
This is a maintenance issue to use the `get_group_counts_workspace_names` function found in `muon_group_pair_context.py` in other parts of the Muon code instead of just replacing the 'Asymmetry' with 'Counts' in the name.

**Comment by AnthonyLim23** [comment]
need to update it here https://github.com/mantidproject/mantid/pull/32037/files#diff-2f8db9304df57f208967d37ad78ed0b3b40348eadd4eb1156a107a6a57480702R33

**Comment by AnthonyLim23** [comment]
this is a nice induction task
