### ISSUE TITLE
Colorfill plots y-axis misaligned and ignores one spectrum

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#32040]
**Original reporter:** Rob Dalgliesh /ISIS

### Expected behavior
Colorfill plots used to show the spectra with their middle point lined up with the number label on the y axis (See left hand plot on the image below)
### Actual behavior
Now Colorfill plots one less spectrum than the total, and displays the spectra edges aligned with the number labels (this maybe be a coincidence).
### Steps to reproduce the behavior
To produce the correct plot: (Quite the optical illusion from @AndreiSavici )

``` python
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
from mantid import plots
 
x=np.arange(100)
xs=np.zeros((6,100))
ys=np.zeros((6,99))
es=ys*0
for i in range(6):
    xs[i]=x
    ys[i]=np.sin(x[:-1]+i)
ws=CreateWorkspace(xs,ys,es,6)
 
fig, ax =plt.subplots(subplot_kw={'projection':'mantid'})
ax.pcolormesh(ws)
fig.show()
```

To show the problem, simply right-click on the created workspace, and select Plot > Colorfill.

You should see plots like this:

![Screenshot 2021-07-19 at 11 14 32](https://user-images.githubusercontent.com/55980573/126145675-4b5a6d49-db33-4d42-84f0-70f4d690cc65.png)

### Platforms affected
I THINK this was broken since release 6.1, all OS

**Comment by RichardWaiteSTFC** [comment]
I think pcolor-like functions always plot with the bin center at the bottom left? Obviously it shouldn't be truncating by a spectrum though.
