### ISSUE TITLE
Remove dependency on VTK and Qt in Mantid Framework (OpenCascade)

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#32086]
**Describe the outcome that is desired.**
The Mantid Framework should not utilize GUI libraries, but unfortunately is dependent on multiple GUI libraries right now, because it is dependent on a small part of OpenCascade. Removing OpenCascade as a dependency should be the resolution to this problem.

**Does the outcome relate directly to a problem? Please describe.**

OpenCascade is large and has multiple large dependencies that the Framework does not require, in order to function.

**Describe any solutions you are considering**

1. Remove OpenCascade as a dependency and rely on a smaller none-GUI based library that is yet to be found to perform the same function.
2. Adopt the OpenCascade code, that we depend on, directly into Mantid and maintain it. Adopting the code should have little problems as it is only a small amount of code.

**Additional context**

**Comment by jclarkeSTFC** [comment]
After investigation, adopting the Open Cascade code into the repository would add somewhere between 400 and 1200 files (due to all the various dependencies), which we thought was excessive. See #36427.
