### ISSUE TITLE
Add slider to resize height of plot widget and cursor info box (XYZ, detectorID etc.) on LHS of instrument view

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#32118]
**Is your feature request related to a problem? Please describe.**
WISH find it difficult to read the RTP of the cursor as too much space is given to the plot widget, which then has a elongated aspect ratio.

**Describe the solution you'd like**
Add a slider to adjust the heights of these widgets

**Comment by RichardWaiteSTFC** [comment]
Re-opening this as WISH specifically requested it. Putting milestone 6.4 so doesn't get lost.

**Comment by jhaigh0** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [32118](https://trello.com/c/rgUwfDPg/5-32118)
