### ISSUE TITLE
PolDiffILLReduction: TOF mode

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#32157]
The data reduction for polarized diffraction on the D7 ILL instrument has three major workflows, for powder samples, single crystal samples, and when the measurement is in the TOF mode. The two latter modes of data reduction have been already implemented and are undergoing validation by the responsible scientists. The support for reducing TOF mode data is required for complete support for the D7 instrument at the ILL.

The reduction needs to include:
- Support for 2D TOF workspaces with correct normalisation by monitor or time
- Elastic peak calibration using vanadium measurement
- Calculation of time-dependent and time-independent background contributions and proper subtraction of it
- Frame-overlap correction
- Detector-analyser energy efficiency correction

**Comment by martyngigg** [comment]
Fixed by #32206
