### ISSUE TITLE
Run CMake formatter

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#32150]
**Describe the outcome that is desired.**
Formatting of the cmake files has become inconsistent. This issue is to run a cmake formatter on all of the CMakeFiles.

**Comment by martyngigg** [comment]
We should include this in the pre-commit hook too or it will just drift over time again. As it's maintenance I'm putting it in the next full release milestone as we usually do.

**Comment by martyngigg** [comment]
The pre-commit hook now as this so this will get done over time and I don't think a big format is necessarily required
