### ISSUE TITLE
Monitor normalisation in BATS

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#32230]
**Original reporter:** ILL/Appel

**Describe the bug**

The monitor normalisation in BATS mode on IN16B should happen in wavelength rather than energy.
This is due to the fact that the Energy in ConvertUnits is treated as elastic energy and does not take the energy transfer into account even if the mode is Indirect. This corresponds to what documentation says, however, it is counter-intuitive.

**Comment by martyngigg** [comment]
Fixed by #32235
