### ISSUE TITLE
FDA Sequential fitting filter bug

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32249]
**Describe the bug**
An exception occurs when changing the Filter By option in FDA without fit data having been created on the transform tab.

**To Reproduce**

1. Open up the FDA interface
2. Load MUSR 62260
3. Go to Sequential Fitting tab and attempt to change `Filter by` option

**Platform/Version**
Found on windows in master

**Comment by AnthonyLim23** [comment]
@robertapplin does this bug still exist?

**Comment by robertapplin** [comment]
Yes I am working on a fix for it now
