### ISSUE TITLE
SliceViewer Nonortho Cursor Image Info Signal is -

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#32318]
**Original reporter:** Manual Testing: https://github.com/mantidproject/mantid/issues/32281#issuecomment-905466044

**Describe the bug**
There is no signal in the cursor Image info widget in the non-orthogonal view. This signal is just displayed as `-`.

**To Reproduce**
 - Put the TrainingCourseData in ManageUSerDirectories (or be connected to the ISIS data archive).
 - Run this script:
```
from mantid.simpleapi import *

# SXD23767.raw is available in the TrainingCourseData from the downloads page
SXD23767 = Load(Filename='SXD23767.raw', LoadMonitors='Exclude')
# Set some UB with angles we can play with
SetUB(SXD23767, 1,1,2,90,90,120)
SXD_MD_nonortho = ConvertToDiffractionMDWorkspace(InputWorkspace='SXD23767', OutputDimensions='HKL')
```
- Right-click on the `SXD_MD_nonortho` workspace and click Show Sliceviewer
- Click the trifold non-orthogonal projection toolbar button and hover the cursor over the image
- Notice that the Signal value in the cursor image info widget is `-`.

**Expected behavior**
The signal is displayed in the widget as it is for orthogonal view ( or if we don't want to then remove the signal column for MD workspaces).

**Screenshots**
<img width="851" alt="Screenshot 2021-08-25 at 13 39 18" src="https://user-images.githubusercontent.com/55980573/130791955-d0126b76-5f03-4858-966b-99b3cf01eb7c.png">

**Platform/Version (please complete the following information):**
 - OS: Rhel7 (IDAaaS) and Windows 10
 - Mantid Version pre-beta 6.2, and releases 6.1 and 5.1.1

**Comment by RichardWaiteSTFC** [comment]
I think this might be deliberate, because it's set at DBL_MAX when non-orthog view is enabled it calls `_on_cursor_at_mesh` rather than `_on_cursor_at_axesimage`.
https://github.com/mantidproject/mantid/blob/77ea7fe3ace7c873f672a2f2663aef3eb5eab75e/qt/python/mantidqt/widgets/sliceviewer/imageinfowidget.py#L76-L89

**Comment by sf1919** [comment]
If this is deliberate should this one be closed? @thomashampson @RichardWaiteSTFC

**Comment by thomashampson** [comment]
@DanielMurphy22 had the suggestion of removing the signal column if it's not applicable for this case.
