### ISSUE TITLE
SANS OS Error not caught at createFileInformation

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#32310]
Found during unscripted testing
**Describe the bug**
Trying to load a nxs file with the layout we don't expect will throw. This is expected but as we don't catch the `OSError` it will trigger a sad Mantid

**To Reproduce**
- Open LOQ Data
- Grab LOQ000001.nxs
- Enter 1 in the table and tab

**Expected behavior**
Should gracefully handle this

**Comment by martyngigg** [comment]
Fixed by #32326
