### ISSUE TITLE
ISIS SANS Feature Usage is incorrect

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#32312]
**Describe the bug**
In ISIS SANS we incorrectly have feature usage registered in the `__init__` method of some presenters. This means that simply opening the GUI counts as a feature invocation incorrectly

A simple grep for `FeatureType.Feature, ["ISIS SANS` will show the locations.

These should be moved down to places where we know the method is being used (e.g. a load or a mandatory step).

**Comment by martyngigg** [comment]
Fixed by #32316
