### ISSUE TITLE
SliceViewer z-axis autoscale lag

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32359]
**Describe the bug**
In the sliceviewer, autoscaling of the z(colour)-axis lags behind zoom operations by one. However, it seems to work fine for event workspaces.

**To Reproduce**
1. Load workspace and open the slice viewer.
2. Make sure "Autoscaling" is ticked (bottom right of the SliceViewer window).
3. Zoom into a region of low occupancy using the "zoom to rectangle" tool.
4. The limits of the z-axis will remain the same until you perform another zoom operation, e.g. scroll once into the plot.
5. Click the home button to reset the x- and y-axis limts.
6. The limits of the z-axis will not update to account for the range of the data until you click the home button **again**.

**Expected behavior**
z-axis should recale correctly after each zoom operation.

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version 6.1

**Additional context**

**Comment by gemmaguest** [comment]
See comment on #33214.

Note that I see exactly the same problem with both matrix and event workspaces.

**Comment by thomashampson** [comment]
This has been fixed
