### ISSUE TITLE
EngDiffUI fitting tab not catching errors from invalid input to background subtraction alg

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#32353]
**Describe the bug**
if you enter values in Niter or XWindow that are too small you get a sad mantid.
Found during manual testing #32271

**To Reproduce**
Follow Test 6 in https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html

**Expected behavior**
Would have a warning that invalid xwindow and Niter values had been chosen

**Comment by martyngigg** [comment]
Fixed by #32354
