### ISSUE TITLE
Conda package of texlive doesn't work

### ISSUE THREAD

**Issue by StephenSmith25** [mantidproject/mantid#32373]
**Describe the bug**

The conda package of texlive doesn't work, see https://github.com/conda-forge/texlive-core-feedstock/issues/19. It doesn't look like a fix will come, so we should use a system version of texlive if we are building the docs, e.g on ubuntu the following packages satisfied our latex requirements:

`sudo apt-get install texlive dvipng texlive-latex-extra`

**To Reproduce**

Build the dev-docs-html target in a conda environment. There will be errors. Rebuild it, and you'll notice the file `/dev-docs/html/ISISSANSReductionBackend.html` has errors in its latex math blocks.

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Conda on OSX and Linux

**Additional context**

**Comment by martyngigg** [comment]
Our current docker images have texlive installed so I'm not sure we have anything to do here. Putting the docs build in the pipeline is captured in #33021.
