### ISSUE TITLE
Slower loading of runs in Muon Analysis and Frequency Domain Analysis

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#32379]
**Original reporter:** Peter Baker ISIS

**Describe the bug**
During Beta testing it was taking longer to load runs in the Muon Analysis and Frequency Domain Analysis GUIs than in version 6.1. This is the initial loading of the run and creates a single plot. It is also noticeable that changing Instrument on the Home Tab is slower too in comparison to v.6.1. The stack trace doesn't seem to suggest that loading is taking any longer but it definitely feels like it is.

**To Reproduce**
Open Mantid v 6.1
Open Muon Analysis or Frequency Domain Analysis
Load MUSR 62260 or EMU 85022

Compare with 
Opening Mantid Nightly
Open Muon Analysis or Frequency Domain Analysis
Load MUSR 62260 or EMU 85022

**Expected behavior**
Runs load as fast as in previous versions

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - Mantid Version: 6.1.20210831.1435

**Additional context**
Changes to Load were made recently as part of #32021 which might be linked to this issue?

**Comment by martyngigg** [comment]
Fixed by #32419
