### ISSUE TITLE
Absolute units wrong in DirectILLReduction

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#32384]
**Describe the bug**

In `DirectILLReduction`,  [_absoluteUnits invokation](https://github.com/mantidproject/mantid/blob/34a591f251cc2edf65d83f802cb258a577bbb3ea/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLReduction.py#L500) doesn't match its [definition ](https://github.com/mantidproject/mantid/blob/34a591f251cc2edf65d83f802cb258a577bbb3ea/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLReduction.py#L24)

Using that option obviously doesn't work.

**To Reproduce**
Use the algorithm with AbsoluteUnits=On

**Comment by martyngigg** [comment]
Fixed by #32883
