### ISSUE TITLE
Missing help page for Indirect Data Analysis

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32403]
**Describe the bug**
Help button on Inelastic Data Analysis window opens the help window with the following message:
**Missing page - qthelp://org.mantidproject/doc/interfaces/indirect/Indirect Data Analysis.html**

**To Reproduce**
1. Go to Interfaces>Indirect>Data Analysis
2. Click the help button at the bottom

**Expected behavior**
Relevant help page should appear.

**Comment by thomashampson** [comment]
Should it be pointing to this instead?
`qthelp://org.mantidproject/doc/interfaces/indirect/Inelastic Data Analysis.html`

**Comment by martyngigg** [comment]
Fixed by #32462
