### ISSUE TITLE
phasequad crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32402]
**Original reporter:**  James

**Describe the bug**
When switching between phasequad tables the muon GUI crashes. 

**To Reproduce**
Load MUSR 62260
Go to the phase table tab
Click "calculate phase table"
Give it a name (e.g. one)
Change on of the groups
Click "calculate phase table" again 
Give it a different name (e.g. two)

Below change the "phase table" combo box to the other option - crash

The crash occurs because the function it is calling no longer exists. We need to change https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/phase_table_widget/phase_table_presenter.py#L239
to call https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/contexts/muon_context.py#L255

**Comment by martyngigg** [comment]
Fixed by #32415
