### ISSUE TITLE
Indirect Data Anaysis fit tab table values unreadable

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32414]
**Describe the bug**
The StartX and EndXFit table values are unreadable in the Fit tabs of the Inelastic Data Analyis interface, except when the column widths are increased to fit the entire float. The value is only visibile if the entire float fits inside the box, otherwise it will say "0...." or "1....".

**To Reproduce**
1. Go to Interfaces > Indirect > Data Analysis
2. Go to the "I(Q, t) Fit" tab
3. Click "Add Workspace" and load some data (e.g. mantid-build/ExternalData/Testing/Data/UnitTest/iris26176_graphite002_iqt.nxs)
4. Enter a workspace index or tick "all spectra" and click "Add" then "Close"
5. Drag the range sliders around on the mini plot and examine the StartX and EndX values in the table

**Expected behavior**
Boxes should display as many characters as possible before the "..."

**Screenshots**
Current behaviour:
![image](https://user-images.githubusercontent.com/8058899/132498314-f31c1b95-f763-4db3-8077-850608b02820.png)
Correct behaviour:
![image](https://user-images.githubusercontent.com/8058899/132498398-1c5c3be9-2595-40e4-99cd-c3b80860b158.png)

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - Mantid Version: occurs on latest build of release next (6.1.20210907.1448) but not on a ~1 week old nightly (6.1.20210831.1435).

**Comment by SpencerHowells** [comment]
@thomashampson @Harrietbrown is dealing with a bug in the StartX/EndX values in PR #32394

**Comment by Harrietbrown** [comment]
I am not getting this issue in my build, 
![image](https://user-images.githubusercontent.com/49688535/132640043-cb6fb093-d340-46cf-b75e-ac90d74e0d4d.png)
I am not sure what is happenign for you

**Comment by thomashampson** [comment]
This seems to only occur on my locally built version of release-next, and not on the deployed nightly version. Therefore I'll mark it as closed because it won't affect any users.
