### ISSUE TITLE
Indirect Data Analysis crashes Mantid if wrong file is loaded

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32416]
**Describe the bug**
In the Elwin tab of the Indirect Data Analysis interface, if you load data that it isn't expecting, it will cause Mantid to crash.

**To Reproduce**
1. Open the interface: Interfaces > Indirect > Data Analysis
2. Staying on the Elwin tab, click "Browse" to open the file dialog.
3. Change the file extension filter to "All files (*)"
4. Load, for example, EMU00020884.nxs from the training course data
5. Mantid will crash without any stack trace

**Expected behavior**
Trying to load data that isn't expected should be handled more gracefully.

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - Mantid Version 6.1 onwards (and probably earlier)

**Comment by SpencerHowells** [comment]
@thomashampson EMU is not an inelastic neutron instrument so it’s not surprising that it crashes! Check the IDF so that it says inelastic & if not give error message that it’s invalid instrument.

**Comment by SpencerHowells** [comment]
@thomashampson In the Browse dialog it searches for files with the suffix _iqt to prevent users trying to read stupid data. If the user chooses to ignore this then it’s their problem.

**Comment by SpencerHowells** [comment]
@sf1919 If this needs to be done then it has to be in every tab in every interface!

**Comment by Harrietbrown** [comment]
> @sf1919 If this needs to be done then it has to be in every tab in every interface!

Only for cases where it causes a hard crash without an error report screen.

**Comment by SpencerHowells** [comment]
@Harrietbrown This occurred when reading an EMU muon file so it is rubbish for our interfaces - all of them. You will need to check for this every where. This is getting stupid!! Who in their right mind would think of reading EMU for neutrons!

**Comment by SpencerHowells** [comment]
@Harrietbrown @sf1919 Just had a look at it. If I load an IRIS raw file it comes back with an error message that says that efixed has not been defined. This is what you expect if it is incorrect data - either it is not inelastic neutron or efixed was not defined when creating the file. However if you try to delete the workspace Mantid crashes.

**Comment by SpencerHowells** [comment]
@Harrietbrown @sf1919 Next look. I loaded a _red file & it plotted Ok. Again though I cannot remove it & it hangs. Eventually I managed to close the tab without crashing Mantid.

**Comment by sf1919** [comment]
Closed by #32483
