### ISSUE TITLE
Unit Test for correctly handling changed Phasequad Data

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#32423]
**Describe the outcome that is desired.**
A unit test is needed for Muon Phasequads that checks that it will correctly deal with a change in the Phasequad data - for example when changing instrument the Phasequad data will be cleared or when switching between Phasequad tables.

**Describe any solutions you are considering**
A unit test that specifically tests ```handle_phase_table_changed``` in ```phase_table_presenter.py``` (see https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/Common/phase_table_widget/phase_table_presenter.py#L227) may resolve this issue.

**Additional context**
This was identified as an issue during PR #32415

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/main/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/phase_table_widget/phase_table_presenter.py#L227
