### ISSUE TITLE
Instrument view crashes mantid when folding the side menu

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#32432]
**Current behavior**
Reducing the instrument viewer side menu when pick tab's miniplot is visible will cause mantid to throw an error, then crash.

**To reproduce**
- Load a file and open the instrument viewer. Go to the pick tab. Make sure the miniplot is visible.
- Reduce the side menu so that it disappears. An error should appear.
- Click on the plot. Mantid should crash.

**Platform/version**
- Tested on Ubuntu 18.4 on the current master and on the pre 6.2 frozen version.

**Comment by thomashampson** [comment]
Removing stale label because this was fixed by https://github.com/mantidproject/mantid/pull/34747
