### ISSUE TITLE
On some files, ConvertAxesToRealSpace crashes Mantid

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#32434]
Running ConvertAxesToRealSpace on files it is not meant to handle raises an uncaught exception that causes a segmentation fault and crash Mantid.

**To reproduce**
- Load a monochromatic file like `./ExternalData/Testing/Data/SystemTest/ILL/D16/003682.nxs`.
- Run `ConvertAxesToRealSpace` on this. As far as I can tell, parameters do not matter, but it crashes at least for `VerticalAxis : y` and `HorizontalAxis : 2theta`. This doesn't make much sense anyway, the end result being a crash.

**Expected behavior**
The algorithm should not run, or at least throw a proper, managed error.

**Platform / version**
Tested in the current master and pre 6.2 frozen branch.

**Comment by martyngigg** [comment]
Fixed by #33351
