### ISSUE TITLE
Opening the instrument viewer on a workspace that is being replaced freezes Mantid

### ISSUE THREAD

**Issue by MathieuTillet** [mantidproject/mantid#32433]
Opening the instrument viewer on a workspace while it is being replaced - and the loading is underway - will make Mantid stop responding.

**To reproduce**
- Load a relatively big workspace (so that loading takes at least a couple of seconds)
- Re-load this file (or any other, as long as the destination workspace has the same name as the one currently loaded)
- While it is loading, open the instrument viewer on the workspace. Mantid will then freeze and will need to be killed.

**Platform / version**
Found on Ubuntu 18.4, in the current master and the pre 6.2 frozen branch.

**Comment by martyngigg** [comment]
Fixed by #33357
