### ISSUE TITLE
Make Elwin Tab components dockable

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#32437]
The new load widget for the Elwin Tab takes up a lot of space causing the plotting area to be smaller than desired. 

**Describe the solution you'd like**
One solution that has been suggested is to make the components of the Elwin Tab dockable (like MSD Fit, I(Q, t) Fit, ConvFit, F(Q) Fit).

**Comment by sf1919** [comment]
@Harrietbrown @AnthonyLim23 Do we still want to make the components dockable or has the issue of the load widget taking up a lot of space been resolved in #32475?

**Comment by Harrietbrown** [comment]
Is the new workspace input tab able to completly replace the file input now? if so it would be best to remove that tab and that would help fix the space issue.
