### ISSUE TITLE
ALC crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32441]
Start Mantid and open ALC
Load HIFI 77776-77786, plot versus sample_magn_field, use dead time correction from file
Go on to Baseline Modelling, add section and drag the right edge to about -5, add function LinearBackground, fit.
Go into Peak Fitting add a Chebyshev , the grey line extends from (0,0) to the top of the screen
Click/hold on it and get a left/right arrow. Drag. Crash.

**Comment by AnthonyLim23** [comment]
I think this is related to the peak not being added correctly

**Comment by AnthonyLim23** [comment]
It does crash for any peak function

**Comment by martyngigg** [comment]
Fixed by #32494
