### ISSUE TITLE
MSlice issues

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32447]
This is note of the 3 MSlice issues that are to be considered for this release:

https://github.com/mantidproject/mslice/issues/630 - auto-generated slice scripts no longer run successfully 
https://github.com/mantidproject/mslice/issues/628 - Mantid crashes when trying to generate a script from a cut (linux)
https://github.com/mantidproject/mslice/issues/629 - MSlice opens to the wrong tab

**Comment by SilkeSchomann** [comment]
There will be also fixes for the following three bugs:
https://github.com/mantidproject/mslice/issues/627
https://github.com/mantidproject/mslice/issues/626
https://github.com/mantidproject/mslice/issues/544

The first two were found during manual testing for this release, the last one is duplicated by the second part of https://github.com/mantidproject/mslice/issues/626
