### ISSUE TITLE
Chebyshev Start and End X values get reset in Muon Analysis

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32451]
**Original reporter:** James Lord

**Describe the bug**
The Start and End X in the Chebyshev function get reset to -1 and 1 after doing a fit.

**To Reproduce**
1. Muon Analysis. Load HIFI 77766-67
2. Tick Simultaneous fit by. Choose `Group/Pair`. There should now be two datasets in the dataset combobox
2. Fitting tab, add Chebyshev with n=4 and ExpDecayOsc with Frequency =1
3. Change the StartX and EndX in the Chebyshev function to 0 and 15
4. Do a fit. The StartX and EndX in the Chebyshev function get reset to -1 and 1.

**Platform/Version (please complete the following information):**
Windows

**Comment by DavidFair** [comment]
Fixed by #32463
