### ISSUE TITLE
Model Fitting fit range negative number not allowed

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32450]
**Original reporter:** James Lord

**Describe the bug**
The Start and End X in Model fitting appears to get confused after a while of switching between parameters. The negative sign `-` also cant seem to be entered for some reason.

**To Reproduce**
1. Load HIFI 77766-77786
2. Fitting tab, tick simultaneous fit
2. Fitting tab, add Chebyshev with n=4 and ExpDecayOsc with Frequency =1
3. Sequential fit all with `Initial parameters for each fit` checked
4. Create results table
5. Go model fitting and select f1.Phi as the x parameter. The start X is negative, but trying to change it to another negative number will not be allowed.

**Platform/Version (please complete the following information):**
Windows

**Comment by martyngigg** [comment]
Fixed by #32466
