### ISSUE TITLE
Frequency Domain Analysis Automatic Transformations

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32452]
**Requested by**
James Lord

**Is your feature request related to a problem? Please describe.**
When Transforming data in the Transform tab in FDA, often the scientists wants to perform the same transform operation on a number of datasets. James requested for this to be done automatically so he doesn't have to keep clicking 'Transform' for each dataset.

Also, when selecting the 'Real' part in the transform tab, he wants the corresponding imaginary part to automatically be selected.

**Comment by AnthonyLim23** [comment]
For FFT's we are going to change it to have the group/pair define the Re and Im parts (assuming that each transform is for the same run). So then we can do a batch transform. 

The Im part is only defined for a phasequad. Otherwise including an Im part gives bad results.
