### ISSUE TITLE
Model Analysis fit parameters sometimes have wrong units

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#32453]
**Original reporter:** James Lord

**Describe the bug**
Sometimes the wrong units are used for fit parameters in the model fitting tab. This is because it will check the `UnitFactory` for a unit to the parameter name and use that unit if it finds one. This unit isn't always correct however, and so we should avoid doing this.

In the future we will need to get the units of the fit parameters from somewhere, I am open to suggestions.

**To Reproduce**
1. Load MUSR 62260
2. Add function GausOsc
3. Sequentially fit all
4. Go to results tab and create the table
5. Select Phi on the x or y axis. It has units of degrees when it should be radians.

**Expected behavior**
Use no units if plotting a fit parameter because there is no easy way to tell what units to use.

**Comment by AnthonyLim23** [comment]
The scientists have said that "we should aim to have units". We need to discuss what to do with wrong units
