### ISSUE TITLE
IDA fitting tabs do not use the first point when fitting

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#32478]
In the Indirect Data Analysis fitting tabs the fit results do not cover the first point in the data even is startX is equal to the start value in the data. this can also happen with the last point as well.

**Comment by AnthonyLim23** [comment]
@Harrietbrown do you think this worth fixing for the release?

**Comment by Harrietbrown** [comment]
It is probably worth having a go at.

**Comment by Harrietbrown** [comment]
This is a result of the IqtFit algorithm converting the workspace to a histogram before processing it. It is not clear why it does that but at first glance it does not seem nessarcery. I do not think it would be a good idea to put it in at this point in the release since we are not certain on if it is not making another issue. so I will move it inot the next milestone.
