### ISSUE TITLE
X axis scale reset when changing Muon Analysis Tab

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#32473]
**Original reporter:** Aidy

**Describe the bug**
When changing the Start and End X values of a plot whilst on the Home Tab if you change to the Fitting Tab, the Sequential Fitting Tab or the Results Tab the plot returns to the original plot as loaded and does not use the new Start and End X values

**To Reproduce**
1. Open Muon Analysis
2. Load MUSR85100
3. Change Start X and End X (e.g. 3.0 and 8.0 as used in screenshot below)
4. Click on the Fitting Tab, then Sequential Fitting Tab then Results - for all three the plot reverts to original Start X of 0.0 and End X of 15.0
5. Return to Home Tab and the Start X and End X are back to the values entered at step 3.

**Expected behavior**
The Start and End X values, as specified by the user, should also be used in Fitting Tab etc.

**Screenshots**
Screenshot after step 3 (see above)
![Screenshot (32)](https://user-images.githubusercontent.com/55837273/132870297-da658dd1-80f3-4632-b38f-87d0a1ef2672.png)

Screenshot after Step 4 (see above)

![Screenshot (33)](https://user-images.githubusercontent.com/55837273/132870325-b8b72576-f0ad-4234-abea-da622f258feb.png)

**Platform/Version (please complete the following information):**
- Windows 10
- Mantid Version: 6.1.20210909.1507

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/master/scripts/Muon/GUI/MuonAnalysis/plot_widget/muon_analysis_plot_widget.py#L118 is that bit of code that should make them match, clearly its not working correctly
