### ISSUE TITLE
LoadEventNexus is labelling event lists as sorted when they're not

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#32495]
If you run LoadEventNexus without compression, it labels all the event lists as sorted on pulse time even if they're not

I noticed this when doing some work on slicing up an event file for the POLARIS instrument. They want to use the FilterByTime algorithm to slice up some event mode data files that were captured over a 15 minute period into smaller ~30 second chunks. The sample used to capture these data files was undergoing a reaction during the 15 minute period so they want to analyse the difference in behaviour over time.

LoadEventNexus sets the sort order in two stages. It first sets up all the event lists for all the spectra with sort order PULSETIME_SORT initially before any data is loaded. This comment explains why:
```
  // Set all (empty) event lists as sorted by pulse time. That way, calling
  // SortEvents will not try to sort these empty lists.
  for (size_t i = 0; i < m_ws->getNumberHistograms(); i++)
    m_ws->getSpectrum(i).setSortOrder(DataObjects::PULSETIME_SORT);
```

The idea seems to be that later on the spectra that actually get some events loaded have their sort order overwritten by the following code in ProcessBankData.cpp:
```
  //------------ Compress Events (or set sort order) ------------------
  // Do it on all the detector IDs we touched
  if (compress) {
    for (detid_t pixID = m_min_id; pixID <= m_max_id; ++pixID) {
      if (usedDetIds[pixID - m_min_id]) {
        // Find the the workspace index corresponding to that pixel ID
        size_t wi = getWorkspaceIndexFromPixelID(pixID);
        auto &el = outputWS.getSpectrum(wi);
        if (compress)
          el.compressEvents(alg->compressTolerance, &el);
        else {
          if (pulsetimesincreasing)
            el.setSortOrder(DataObjects::PULSETIME_SORT);
          else
            el.setSortOrder(DataObjects::UNSORTED);
        }
      }
    }
  }
```
I think the problem is that the surrounding if (compress) statement shouldn't be there. I guess if the events are actually sorted on pulse time in the nexus file then this bug doesn't matter. It's only when the code should be going into the branch where the sort order is set to UNSORTED that the problem exists

**Comment by martyngigg** [comment]
Fixed by #32499
