### ISSUE TITLE
NormaliseSpectra changes every values to NaN when spectrum contains a single NaN

### ISSUE THREAD

**Issue by gui-co** [mantidproject/mantid#32510]
**Describe the bug**

`NormaliseSpectra` algorithm changes all values to NaN if a single NaN is present in the spectrum.

This is due to the use of [`numpy.amax`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) here:
https://github.com/mantidproject/mantid/blob/2dd89c6a52bb0167cebf8d51faac11bc005999bc/Framework/PythonInterface/plugins/algorithms/NormaliseSpectra.py#L47

**Expected behavior and solution**

`NormaliseSpectra` should ignore the NaNs. Switching to [`numpy.nanmax`](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html) should solve the problem.

**To Reproduce**

* create a workspace
* change one value in each spectrum to NaN
* apply `NormaliseSpectra`
* observe the data

Here is a test script:
```python
from mantid.simpleapi import CreateSampleWorkspace, NormaliseSpectra
import numpy as np

ws = CreateSampleWorkspace()
for sp in range(ws.getNumberHistograms()):
    dataY = ws.dataY(sp)
    dataY[0] = np.nan
    
ws2 = NormaliseSpectra(ws)
```

**Comment by martyngigg** [comment]
Fixed by #32511
