### ISSUE TITLE
Muon phasequad bugs

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32519]
Reported by James

There are a few bugs:
1. Rebinned phasequads have the wrong amplitude. It is better to rebin the raw data
2. Does not select the phasequad correctly in a sim fit

**Describe the bug**

**To Reproduce**
Set binning 4
Load MUSR run 62260
Create a phase table e.g. top, bottom
Create a Phase Quad from it
De-select the plain groups in the Grouping tab leaving only the Phase Quad for fitting
Go to Fitting. Note the phase quad amplitude in the plot pane is about 4 times what it should be
Select ExpDecayOsc. Set Simultaneous over Run. Make A, Frequency, Lambda be Global
Un-select “Fit to Raw Data” below
Try a fit. Get “Unknown property search object InputWorkspace_2”
Go back to Phase Table. Create a 2nd phase table e.g. bkwd, fwd
Try selecting it. Crash

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by AnthonyLim23** [comment]
also noticed that the BG corrections are not being applied to phasequad either

**Comment by DavidFair** [comment]
Fixed by #32536
