### ISSUE TITLE
SANS Beam Centre Finder Not Using Front Value

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#32541]
**Original reporter:** @smk78 

**Describe the bug**
The Beam Centre finder should use the values for the initial front position from the user file (see https://github.com/mantidproject/mantid/blob/master/scripts/SANS/sans/gui_logic/presenter/beam_centre_presenter.py#L129)
Instead it's using just the rear positions twice

**To Reproduce**
- Load the following file 
[USER_LOQ_211G_M4_STEVE_TESTING_TOML__M4_main_log.txt](https://github.com/mantidproject/mantid/files/7195747/USER_LOQ_211G_M4_STEVE_TESTING_TOML__M4_main_log.txt)
- Go to beam centre finder
- Notice both values are set to the same rear value

**Comment by martyngigg** [comment]
Fixed by #32546
