### ISSUE TITLE
Unit conversion error in EngDiff UI fitting

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#32658]
Saurabh was testing with :
CeO2 :  328199
Vanadium : 327702
Set1 : 329602-329639 (I suspect last 3-4 runs are not good but it would be good to test something that fails gracefully)

**Steps to reproduce**
I only used the first 20 or so runs. As soon as I went beyond the first 4 peaks, Mantid would crash.

-  Then I tried keeping the number of peaks to 4 but fitting peak #5 – peak#8 (higher peak number being lower d-spacing) : crashed again.

-  I tried peak#6-peak#8 : this worked. Tried Peak #5 only : also worked. See if you can reproduce this behaviour.

**Comment by DannyHindson** [comment]
I can reproduce this doing a serial fit on some of the runs mentioned. It gives me this stack track. I guess the exception needs catching and a warning logged either in the engineering UI code or inside UnitConversion.run:

![image](https://user-images.githubusercontent.com/56295817/135231722-26310aa3-854e-4e90-a404-ae653e87d71c.png)
