### ISSUE TITLE
NSIS packaging doesn't allow long file paths

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#32676]
**Describe the bug**
Windows builds are failing because there is a limit of 260 characters on the length of file paths.

**To Reproduce**
Attempt to build the NSIS package in a build directory with a relatively long path length, e.g. set the cmake build dir to `C:\workdir\mantid_NSIS_dev\really_long_build_directory_directory_name`

**Expected behavior**
Package should build with long file paths.

**Platform/Version (please complete the following information):**
 - OS: Windows 10

**Comment by DavidFair** [comment]
Whilst we are doing this, if possible could we see if we can fix spaces in path names too? Since it should touch all the same locations
