### ISSUE TITLE
Multiple lines plotted when reloading focused file in Eng Diff GUI's Fit Tab

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#32690]
**Describe the bug**
If a second load is run with the same data, two additional, duplicate, lines are added to the plot for each workspace. 

**To Reproduce**
1. Open eng-diff GUI
2. Produce focused files using these instructions: https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html#id5
3. Load created files into the Fitting tab
4. Make sure `Add to Plot` is checked.
5. Run load again

**Expected behavior**
There should be one line on the plot for each workspace loaded that has the `Plot` checkbox ticked. 

**Screenshots**
Shown here, three workspaces producing nine lines on the plot:
![image](https://user-images.githubusercontent.com/47181718/135823343-7a3b4f3d-ed85-4130-a931-c4114fcf91db.png)

**Platform/Version (please complete the following information):**
 - OS: Seen on Windows 10 and Ubuntu 16.04, assume all. 
 - Mantid Version 6.2

**Comment by warunawickramasingha** [comment]
This issue is no longer creatable on Windows or on IDAaaS environments and hence closing.
