### ISSUE TITLE
Check the EngDiff manual testing page is up to date

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#32872]
Check this page is up to date https://docs.mantidproject.org/nightly/interfaces/diffraction/Engineering%20Diffraction.html
Does it cover the texture analysis and any recent UI changes? 
If we have the test files in the SystemTest data then we should mention that.

ref: [Manual Testing](https://github.com/mantidproject/mantid/issues/32352#issuecomment-910132038)

**Comment by DannyHindson** [comment]
Closing - covered in #33245
