### ISSUE TITLE
Design GUI for Vesuvio analysis

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#32887]
At the moment there is no GUI available for the Vesuvio analysis script. The VesuvioAnalysis algorithm has an execution dialog, but as the functionality of VesuvioAnalysis will be extended it would be beneficial for the user to have a GUI for the Vesuvio analysis.

The GUI has to enable the user to set input parameters for the analysis with the possibility to save a set of parameters for future use.

**Comment by AnthonyLim23** [comment]
you might be able to reuse some of the muon GUI if you go the Python route
