### ISSUE TITLE
sequential button bug

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#32978]
In the muon GUI the sequentially fit all button does not rescale correctly, the others do. I suspect this is just a missing option on the widget

**Comment by AnthonyLim23** [comment]
I have had a look and I cannot recreate this and as far as I can tell the settings on the 2 buttons are identical. @sf1919 can you reproduce this?

**Comment by sf1919** [comment]
Yes but only on a 4K laptop where recommended resolution is 3840 x 2160.

![Screenshot (144)](https://user-images.githubusercontent.com/55837273/142585968-81829404-9d3b-4085-969f-6fb623aec53d.png)

**Comment by AnthonyLim23** [comment]
ah, thats not what I expected. I thought it would be the height that was too small
