### ISSUE TITLE
Crash when loading data with event arrays size 0

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#32972]
**Original reporter:** Rob Dalgliesh @FreddieAkeroyd 

**Describe the bug**
Loading data with event arrays of size 0 crashes MantidWorkbench

**To Reproduce**
- Open Workbench
- Try to Load this data file from the archive: `cycle_21_2/LARMOR00060202.nxs`
- Workbench closes

**Expected behavior**
Data is not loaded, useful error message and MantidWorkbench can stay open!

**Platform/Version (please complete the following information):**
 - OS: Found on IDAaaS and Windows
 - Mantid Version Seen on version 6.1 until the current nightly

**Comment by FreddieAkeroyd** [comment]
For background, this will happen if if a run is saved in event mode when there has been no accelerator pulses (e.g. out of cycle but not running in test clock mode). The frame count will be zero and any arrays that have per frame information (such as the event data arrays) will be stored in the nexus/hdf5 file with size 0. This may cause issues both loading the neutron data, but also possibly with other e.g.  sample environment data if it looks for a frame list  to help generate averages or slices
