### ISSUE TITLE
String logs not being displayed correctly in model analysis

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33012]
Load some data into the muon GUI (e.g. emu 96116-8)
Go to fitting and add a function
Go to sequential and fit all
Select the analysis group name log
Create a results table
Go to model analysis
Numbers are displayed instead of the string labels for workspace name and analysis group name.

**Comment by martyngigg** [comment]
@AnthonyLim23 I've just been going over some stray issues from 6.4S3. Is this one valid any more?

**Comment by AnthonyLim23** [comment]
this is still a problem and should probably get fixed.
