### ISSUE TITLE
Review path usage in the ConfigService

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#3308]
This issue was originally [TRAC 2460](http://trac.mantidproject.org/mantid/ticket/2460)

Our handling of paths in the ConfigService is a little out of control.

In most circumstances we try to not use windows style paths and this has led to problems in circumstances where this has been missed. For example http://trac.mantidproject.org/mantid/ticket/2445.

The only issue with windows-style paths is when they appear in the Mantid properties file. At this point Poco transforms valid escape sequences and we can't do anything about this.

What we can do is only care about this slash handling on loading/saving the file, i.e when read in the paths would be stored in native format but when written out we would use either a forward slash or backward slash.

 - - - - 
Keywords: CODEREVIEW

**Comment by NickDraper** [comment]
This is 5 years old and has not caused any recent problems.
