### ISSUE TITLE
Split Activation Fitting function

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#33090]
**Is your feature request related to a problem? Please describe.**
At present the Activation Fit Function requires users to input a suitable string for the Unit as it calculates differently depending on whether its K or meV. However the user is unhappy with this solution as inputting an invalid string will only give an error once the Fit button has been clicked (this is because it is a fitting function not a GUI so input cannot be checked prior to this). Whilst the documentation is clear about which units can be used and the resulting error message also informs users which they should use we have been asked to come up with an alternative way of providing this fitting function.

It should be noted that the function may also need to be expanded to include other units.

**Describe the solution you'd like**
To use a helper function (see #33085 ) that provides the necessary calculations to two separate fitting functions, one for K and one for meV. This ensures the user chooses the correct function from the start and reduces the number of parameters they need to update.

**Describe alternatives you've considered**
It is not possible to use a drop down menu for selecting units because this is a Fitting Function not a GUI. 

The user suggested using a code ( 1 = K and 2 = meV) and somehow prevent the user from inputting any other numbers. However this could lead to confusion as users would have to know which number to use for which unit. This would have to be included in the documentation but the original solution also relied on users making use of the documentation which didn't work.

**Additional context**
PR for the Activation Fit Function - #32899

**Comment by martyngigg** [comment]
I agree that the numbers are just as error prone anyway.

Would it be possible to use the [`setAttributeValue`](https://github.com/mantidproject/mantid/blob/70a086e5c0813aad79dcf56a665fc96ce3e37ec8/qt/widgets/common/src/FunctionTreeView.cpp#L1957) method and override this in the function. This could be caught earlier than running fit I think. It doesn't actually return a value at the moment so could return something like `boost::optional<std::string>` to provide an error string that could be shown in the view?

Happy to chat further about this.
