### ISSUE TITLE
Saved focussed data doesn't appear to be correctly calibrated in EngDiff UI

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33129]
**Describe the bug**
Saved focussed data doesn't appear to be correctly calibrated in EngDiff UI: the North and South bank spectra should line up in TOF and d-spacing post calibration.

After a run is focussed the resulting workspace looks like this (zoomed in on one peak)
Saved focussed data doesn't appear to be correctly calibrated in EngDiff UI
![image](https://user-images.githubusercontent.com/55979119/146046506-008134e3-e42b-41af-add6-a61f0c00369b.png)

But loading the data into the fit browser produces this
![image](https://user-images.githubusercontent.com/55979119/146046748-29e6869e-6c3c-4dd4-a095-198c4a32ec9e.png)

**To Reproduce**
Follow steps in manual testing docs to calibrate and focus data in tyhe EngDiff Ui
https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html

**Expected behavior**
the North and South bank spectra should line up in TOF and d-spacing.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by DannyHindson** [comment]
I just tried this on my Windows install using main and I see the same thing. I created a fresh calibration using 30738 and then focussed using sample 305761 and V 307521 and got this from the fit tab:

![image](https://user-images.githubusercontent.com/56295817/146201115-64280cd4-455e-4d46-a865-56f38213db6e.png)

The bank 2 peak seemed to be offset to the left in the plots produced on the focus tab for me as well

**Comment by RichardWaiteSTFC** [comment]
Closed via #33153
