### ISSUE TITLE
isis reduction script does not allow removing wb only

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#33139]
**Original reporter:** [ISIS]/[Ross Stewart]

**Describe the issue**
The current implementation of ISIS reduction script prohibits removal of empty background if `wb_background` only is specified. 
This is done in assumption that removal of `wb_background` only does not make a sense as sample background would be bigger then `wb_background`. Apparently it is not the case so removal of `wb_background` only is requested.
So, Ross requested the possibility to remove the `wb_background` only

**Comment by mducle** [comment]
Fixed by #33140
