### ISSUE TITLE
macOS package: An additional include directory has appeared when expanding the dmg

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#33206]
**Describe the bug**
An extra `include` directory now appears when you open the macOS `.dmg` to copy the bundle to `/Applications`

**To Reproduce**
1. Download the current macOS build from Jenkins clean jobs 
2. Open the .dmg and the screenshot below is presented.

**Expected behavior**
There is just the MantidWorkbench application and the link out to the Applications directory.

**Screenshots**
![macOS-installer-include-directory](https://user-images.githubusercontent.com/733773/148229096-14f2dc7e-1882-4be0-a28b-f2fe3ce811c4.png)

**Platform/Version (please complete the following information):**
 - OS: macOS
 - OS Version: All
 - Mantid Version: Current nightly

**Additional context**

**Comment by DavidFair** [comment]
Just an FYI `share` is also included, you need to drag a box towards the right of the window to see it too

**Comment by martyngigg** [comment]
Thanks. It appeared more obviously on the command line.
It was difficult to convince cmake not to install them so I've just gone with deleting them in the post-install step now. Long-term this method will disppear with conda
