### ISSUE TITLE
IDA crash when removing 

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#33218]
**Describe the bug**
When you remove data from the Indirect data analysis fitting tabs for the second time it causes a crash.

**To Reproduce**
1. open IndirectDataAnalysis go to IQTFit tab,
2. load some data with multiple spectra
3. remove one spectra
4. remove another spectra. this causes a crash.

**Comment by martyngigg** [comment]
Fixed by #33220
