### ISSUE TITLE
ISIS calibration inconsistent with scaling 

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#33212]
**Describe the bug**
This bug was present in the previous release.

In Indirect Data Reduction the ISIS calibration tab allows for calib files to be scaled by factor. The handeling of this is inconsistent. be default if this is not checked it normalises the calibration file to 1.0, and if 1.0 is selected for the scale by factor it outputs the same as the default. but if any other value is chosen it does not normalise the date first. so having 0.9 in the scaling does not normalise the data to 0.9.

**To Reproduce**

1. Go to Indirect Data Reduction
2. Input 26173
3. Enable `Scale by factor`
4. Click Run.
5. check `_calib` matrix it should be normalized to 1
6. change scale to 0.9
7. click Run
8. check calib file, it is not normalised

**Expected behavior**
The calibration workspace should scale to the value given.

**Comment by martyngigg** [comment]
Fixed by #33344
