### ISSUE TITLE
Soft Crash Error Report does not send

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33219]
Found in #33200 

**Describe the bug**
The error reporter, generated on a soft crash (workbench doesn't close), will not send with "Yes, share info". This maybe related to the problem stopping the "Show More details" button in the bottom right of the Error Reporter from working.

**To Reproduce**
- Open Workbench
- Load the file Training_Exercise3a_SNS.nxs from the Trainingcoursedata
- Execute the algorithm NormaliseToMonitor
- The error reporter will appear. Try to click Show more details (a pop-up window should appear, but now does not)
- Click "Yes, Share info". It will fail reporting a bad request 400

**Expected behavior**
-Show more details pop-up works and sending error reports with "Yes, Share Info" works too!

**Screenshots**
![Screenshot 2022-01-06 at 11 46 47 (2)](https://user-images.githubusercontent.com/55980573/148383339-c3a0e6fe-6a78-43ab-8c0f-f95bb13e32b2.png)
 explain your problem. -->

**Platform/Version (please complete the following information):**
 - OS: IDAaaS Centos7 (also found on nightly on Windows)
 - Mantid Version  6.2.20220103.659

**Comment by DanielMurphy22** [comment]
The breaking change is these 3 lines here: https://github.com/mantidproject/mantid/pull/33056/files#diff-bf1a2e80801b922a0520f50d5ab63455cfdfd8b13f06ce5592a140ac42238b8fR49-R51

**Comment by martyngigg** [comment]
Fixed by #33243
