### ISSUE TITLE
Plotting to scripting does not save canvas colour

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#33225]
**Describe the bug**
Plotting script does not save out the canvas background

**To Reproduce**
- Plot a workspace
- In the settings, change the canvas colour
- Save the script to clipboard / file
- Re-run, the canvas colour is not preserved

**Expected behavior**
The canvas colour should be preserved

**Platform/Version (please complete the following information):**
All

**Comment by martyngigg** [comment]
Fixed by #33294
