### ISSUE TITLE
Tiled plots missing script button

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#33226]
**Describe the bug**
Tiled plots do not have a script to clipboard/file toolbar button if the number of plots isn't a square number.

**To Reproduce**
Plot a tiled plot with e.g. 7 spectra. The Plot script toolbar button will be msissing.

**Expected behavior**
All tiled plots should have a script toolbar button.

**Screenshots**
![image](https://user-images.githubusercontent.com/8058899/148415745-f5134ca8-1a2d-475e-878e-40377694a736.png)

**Platform/Version (please complete the following information):**
- All

**Comment by jhaigh0** [comment]
The problem is [here](https://github.com/mantidproject/mantid/blob/main/qt/applications/workbench/workbench/plotting/toolbar.py#L231) where we enable script generation only if all axes has a curve plotted.
