### ISSUE TITLE
Cannot delete an empty WorkspaceGroup

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#33221]
**Describe the bug**
An empty workspace group cannot be removed from the ADS, but can be "ungrouped" to delete it

**To Reproduce**
Run the following
```python
from mantid import api
group = WorkspaceGroup()
mtd.addOrReplace("group", group)
```

Try to delete this by using the delete key or button. Neither works but ungroup does.
Additionally `DeleteWorkspace` fails with "Empty group passed as input", this may be related.

**Expected behavior**
- The workspace group should be removed should be removed from workbench
- `DeleteWorkspace` should accept the empty group workspace

**Platform/Version (please complete the following information):**
All

**Comment by martyngigg** [comment]
Fixed by #33282
