### ISSUE TITLE
Error reporter loading .csv in ISIS SANS with transposed data/column names

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#33238]
**Describe the bug**
The top level `try except` for loading CSV does not handle the cases where columns are transposed (so a new column appears where data is)
This causes the error reporter to appear

**To Reproduce**
- Open ISIS SANS Interface
- Click Batch file
- Open the following CSV TODO

**Expected behavior**
A clear error should be printed

**Comment by martyngigg** [comment]
Fixed by #33278
