### ISSUE TITLE
Renaming workspace does not change sliceviewer window title

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33239]
**Describe the bug**
Found during manual testing of sliceviewer #33201
Renaming workspace does not change sliceviewer window title

**To Reproduce**
(1) Make a workspace
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-3,3,-3,3,-3,3',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='10')
```
(2) Open in sliceviewer
(3) Rename workspace in ADS

The title of the window doesn't change (but it is pointing to the correct workspace - e.g rebinning still works and you can also scale the data and it will update the color scale limits)

**Expected behavior**
It would update the title of the window (which is the workspace name)

**Screenshots**

**Platform/Version (please complete the following information):**
 - Mantid 6.2 nightly 4 Jan

**Comment by martyngigg** [comment]
Fixed by #33253
