### ISSUE TITLE
Initial value of spinbox for integrated dimensions incorrect for MDHisto workspaces in sliceviewer

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33234]
**Describe the bug**
Spin box containing centre of slicepoint is incorrectly initialised at 0 for MDHisto workspaces with no underlying MDEvent workspace - but the slider shows the slice is the first bin center.

![image](https://user-images.githubusercontent.com/55979119/148558119-2e9da3c1-cbad-4afb-9afa-46a69a7432c1.png)

**To Reproduce**
(1) Make the workspace
```
ws = CreateMDWorkspace(Dimensions='3', Extents='-3,3,-3,3,-3,3',
                       Names='H,K,L', Units='r.l.u.,r.l.u.,r.l.u.',
                       Frames='HKL,HKL,HKL',
                       SplitInto='2', SplitThreshold='10')
BinMD(InputWorkspace='ws', AxisAligned=False, 
    BasisVector0='H,r.l.u.,1.0,0.0,0.0', 
    BasisVector1='K,r.l.u.,0.0,1.0,0.0', 
    BasisVector2='L,r.l.u.,0.0,0.0,1.0', 
    OutputExtents='-3,3,-3,3,-3,3', OutputBins='30,30,30', 
    NormalizeBasisVectors=False, OutputWorkspace='ws_histo')
DeleteWorkspace(ws)
```
(2) Open `ws_histo` in sliceviewer
(3) Check the slidier is at first bin center but the spin box says 0

**Expected behavior**
- Slider and spin box would agree with each other - i.e. spin box would show first bin center (this is the behaviour of MDEvents where the code assumes 100 bins along integrated dimensions for the purpose of making a slider with discrete steps)

E.g. here is what `ws` looks like in sliceviewer
![image](https://user-images.githubusercontent.com/55979119/148558954-b1fae37b-305c-4ddb-af59-3c0fe11d3f07.png)
Checking the history of the `ws_svrebinned` the slice is integrated at the minimum of the range along that dimension.

**Platform/Version (please complete the following information):**
Tested on windows (but presumably all)
Found in this PR #33203 - but confirmed on installed nightly from 4 Dec

**Comment by martyngigg** [comment]
Fixed by #33203
