### ISSUE TITLE
Model fit table not updating in EngDiff UI

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33248]
**Describe the bug**
Found during manual testing for 6.3 release - #33191
Model fit table not updating in EngDiff UI

**To Reproduce**
(1) Load a focused spectrum into the EngDiff UI fitting tab
(2) Zoom in on a peak in the data
(3) Open fit browser clicking Fit in figure toolbar
(4) Right click and Add Peak 
(5) Execute Fit in browser
(6) Check `model `table in `_fits` group of workspaces in ADS
(7) It should have the model string and fit status in a row corresponding to the spectrum fitted but it still has the default null values.

**Expected behavior**
It should have the model string and fit status in a row corresponding to the spectrum fitted 

**Platform/Version (please complete the following information):**
 - Nightly 6.2 (4 Jan) windows

**Comment by martyngigg** [comment]
Fixed by #33268
