### ISSUE TITLE
Inspect background plot in EngDiff UI not updating when parameters changed in table

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33246]
**Describe the bug**
Found during manual testing for 6.3 release - #33191
Inspect background plot inn EngDiff UI not updating when parameters (for EnggEstimateFocusedBackground) changed in UI table

**To Reproduce**
(1) Load in a focused spectrum into the fitting tab of EngDiff UI spectrum
(2) Click any cell in the UI table to select the row
(3) Click Inspect Background button (a separate figure window should open)
(4) Zoom in on the Red curve in the top subplot (this is the estimated background)
(5) In the table change the Niter column to be 1 - the red curve will not have changed (but it should have!)
(6) Click Inspect Background button again - a new plot should open and the background curve should have more prominent peaks in it where there are peaks in the data.

**Expected behavior**
The background curve in the top subplot (and the subtracted data in the bottom subplot) should update when these parameters are changed (NIter, XWindow, SG).

**Platform/Version (please complete the following information):**
 - Nightly 6.2 (4 Jan) windows

**Comment by martyngigg** [comment]
Fixed by #33317
