### ISSUE TITLE
Add legend to Inspect background plot in EngDiff UI

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33247]
**Describe the bug**
Found during manual testing for 6.3 release - #33191 
Add legend to Inspect background plot in EngDiff UI

**To Reproduce**
(1) Load in a focused spectrum into the fitting tab of EngDiff UI spectrum
(2) Click any cell in the UI table to select the row
(3) Click Inspect Background button (a separate figure window should open)

**Expected behavior**
Would have a legend

**Comment by martyngigg** [comment]
Fixed by #33317
