### ISSUE TITLE
Sliceviewer ROI not resetting shape correctly when enlarged to cover the line plot axis

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33264]
**Describe the bug**
Sliceviewer, enabling line plots and dragging a ROI box over it will try to use the spectrum / TOF values on the line plot causing weird ROI box behaviour

**To Reproduce**
(1) Load `MAR11060.raw` 
(2) Open in sliceviewer
(3) Enable ROI
(4) Draw a box covering a tall narrow rectangle on RHS of plot that covers most of y-range (see screenshot)
(5) Enlarge ROI by dragging bottom edge onto the line plot
(6) The edge of the box jumps to what appears to be whatever the max. y limit is on the lineplot

![image](https://user-images.githubusercontent.com/55979119/148933576-da8b5bad-549f-4468-a317-b4e5efeaa9e9.png)

**Expected behavior**
It would not let user drag ROI exceeding data range

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid 6.2 nightly (4 Jan)

**Additional context**
Found during manual testing of workbench #33187

**Comment by martyngigg** [comment]
Fixed by #33346
