### ISSUE TITLE
Documentation Updates of Manual testing

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33261]
Documents Repo PR: https://github.com/mantidproject/documents/pull/102
- [x] Clean up documents RoadmapUpdate folder and double check the surviving spreadsheets
- [x] Update documents repo with approach used for ensemble testing
- [x] figure out how to use multiple assignees in the Github API
 - [x]  Update Sample transmission link in spreadsheet to https://docs.mantidproject.org/nightly/interfaces/general/Sample%20Transmission%20Calculator.html
 - [x] update sliceviewer link 
 - [x] update mslice link
 - [x] update TOF converter link: https://github.com/mantidproject/mantid/issues/33189#issuecomment-1006698983

Mantid Docs PR: https://github.com/mantidproject/mantid/pull/33367
 - [x] Mantid Basic Course updates https://github.com/mantidproject/mantid/issues/33197
 - [x] test_errorreport_presenter.py L36 uses " rather than @ 
 - [x] https://github.com/mantidproject/mantid/issues/33186 top 2 comments
 - [x] update error reporter testing page: Testing docs
   - [x] do not include the "Remember Me" functionality
   - [x] do not include Show More details!
   - [x] do not ask to type in the textbox
   - [x] should ask to type odd characters including " in the textbox, name, email

**Comment by DanielMurphy22** [comment]
I was testing multiple assignees!

**Comment by martyngigg** [comment]
Fixed by #33367
