### ISSUE TITLE
DiffractionFocus moves towards the fold

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#3326]
This issue was originally [TRAC 2479](http://trac.mantidproject.org/mantid/ticket/2479)

Rather than have a separate configuration file for grouping/masking than the rest of mantid, migrate towards the common grouping and masking files/workspaces that the rest of mantid is working with (http://trac.mantidproject.org/mantid/ticket/2474). There will likely be need for an algorithm that converts the grouping/masking columns of the existing ```.cal``` file to the new common format.

**Comment by NickDraper** [comment]
The current approach is acceptable to instrument scientists
