### ISSUE TITLE
Indirect Data Reduction ISIS calibration does not set correct resolution propperties when run is changed

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#33267]
**Describe the bug**
ISIS Calibration in Indirect Data reduction has a bug where the rebinning for the resolution properties are set to inccorect values when changing loaded runs.

**To Reproduce**

1. open Indirect Data Reduction
2. go to ISIS Calibration
3. in `Input runs` load 55878-55879
4. click run
5. change the loaded runs to 59057-59059
6. see in the resolution Properties, the start and end of the background as well as the low and high in rebinning are all 1.882

**Comment by martyngigg** [comment]
Fixed by #33378
