### ISSUE TITLE
Shrunk comboboxes on About MWorbench menu MacOS

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33265]
Found in https://github.com/mantidproject/mantid/issues/33187#issuecomment-1009877468

**Describe the bug**
If there is no facility set, the About Mantidworkbench first time setup page has shrunk comboboxes for the facility and instrument, meaning the user cannot see the instrument they have set.

**To Reproduce**
Open MantidWorkbench on MacoS
in settings (MantidWorkbenchNightly in top bar > Preferences) set the facility to nothing
close the settings and open the MantidWorkbenchNightly in top bar > About MantidWorkbench menu
The comboboxes are shrunk. Try to set a facility and instrument and the comboboxes are still shurnk

**Expected behavior**
Comboboxes are wide enough on launch of this menu

<img width="368" alt="148932434-78682e35-0c9e-4545-8623-087f720ce394" src="https://user-images.githubusercontent.com/55980573/148937768-f33e234e-52e5-49f4-a607-b2d85bc812e4.png">

**Platform/Version (please complete the following information):**
 - OS: MacOS
 - OS Version: BigSur
 - Mantid Version nightly 4th Jan 2022

**Comment by martyngigg** [comment]
Fixed by #33329
