### ISSUE TITLE
Update Project Recovery testing docs

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33271]
Update the instructons here: http://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html

Suggestions were found in manual testing: https://github.com/mantidproject/mantid/issues/33199

- Rewrite section 3 to use an ISIS file (rather than TOPAZ) and put the new file in the ISIS Sample Data
- Add comment to also open Engineering Diffraction in section 4

**Comment by AnthonyLim23** [comment]
The easiest way would to be:

Open muon analysis
Load any data set
Let project recovery run
Crash mantid
Recover script and make sure its runs (if it doesnt have the extra bits in load the script fails)
