### ISSUE TITLE
Project Recovery should notify user the setting requires restart

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33272]
Found in https://github.com/mantidproject/mantid/issues/33199

**Describe the bug**
Project recovery needs workbench to restart before any settings relating to it actually updated. Supposedly, there used to be a message in the messages box and a tooltip in settings, both of which were not observed when testing on Centos 7

**To Reproduce**
Open workbench
open File settings or MantidWorkbench > Preferences
change one of the project recovery settings, e.g. dis/enable project recovery. Note there is no tooltip for these settings and on closing the settings there is no relevant message in the messages toolbox.

**Expected behavior**
Tooltip and message appear.

**Platform/Version (please complete the following information):**
 - OS: Centos 7 / IDAaaS
 - Mantid Version nightly 04012022 ( i think!)

**Comment by martyngigg** [comment]
Fixed by #33334
