### ISSUE TITLE
Mantid hard crash when renaming workspace that has been fitted in EngDiff UI

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33281]
**Describe the bug**
Mantid hard crash when renaming workspace that has been fitted in EngDiff UI

![image](https://user-images.githubusercontent.com/55979119/149108882-88d5f536-ae5a-4f99-b951-7da3f778b64d.png)

**To Reproduce**
(1) Load focused spectrum in fitting tab of EngDiff UI
(2) Plot
(3) Open fit browser and perform fit
(4) Rename the `_bgsub` workspace

**Expected behavior**
No crash - would be able to continue using the interface

**Comment by RichardWaiteSTFC** [comment]
This might be related to #33244?

**Comment by martyngigg** [comment]
Fixed by #33299
