### ISSUE TITLE
Unhandled Ex When Changing Plot and SubBG Options With Fit Window Open 

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#33295]
**Describe the bug**
Mantid throws when either of these checkbox options are changed with the fit browser open. 

**To Reproduce**
1. Open the Eng Diff GUI and navigate to the fitting tab
2. Load some focused data (see https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html for instructions)
3. Plot the data
4. Click the fit button to open the fit browser
5. Check/Uncheck either of plot or sub-bg

**Expected behavior**
No errors

**Screenshots**
![Screenshot 2022-01-12 at 17 24 15](https://user-images.githubusercontent.com/47181718/149190529-f7bc9f1a-5756-4a9a-a66c-12a71e4d86b0.png)

**Platform/Version (please complete the following information):**
 - OS: Ubuntu, not windows
 - OS Version: 18.04
 - Mantid Version 6.3

**Comment by DavidFair** [comment]
I've tested this locally with a different / the same file as Conor and cannot reproduce it

**Comment by ConorMFinn** [comment]
Unable to be reproduced on two other systems, both windows and another ubuntu machine. Seems to be some weird quirk of my system.
