### ISSUE TITLE
Try to add a peak outside of the plot area causes ugly error

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#33304]
Plot a spectrum and open fit property browser
Right click on plot and select Add Peak
Click outside of the plot eg where yellow mark is:

![image](https://user-images.githubusercontent.com/56295817/149489163-faca8dbb-5221-4a0b-9a9f-f7c8cfde8fbb.png)

Get following error. Doesn't crash Mantid but looks a bit messy\ugly:

![image](https://user-images.githubusercontent.com/56295817/149489208-43994f0e-4a50-4095-92d4-5c05da7e9019.png)

This also happened in 6.2. I've put it against the 6.3 milestone for now but if we run out of time perhaps not essential

**Comment by martyngigg** [comment]
Fixed by #33352
