### ISSUE TITLE
Elwin add data for workspaces should be able to accept more than one workspace at a time

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#33319]
In elwin typical usage would involve adding a large number of workspaces, this can be added individualy but it is time consuming. a way of adding multiple workspaces at once would be useful.

One solution would be to enable the adding of group workspaces

**Acceptance Criteria**

- It should be possible to add many workspaces at one time using the Elwin Add Workspace Dialog

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Elwin add data for workspaces should be able to accept more than one workspace at a time](https://trello.com/c/Gl7attjf/19-elwin-add-data-for-workspaces-should-be-able-to-accept-more-than-one-workspace-at-a-time)

**Comment by AnthonyLim23** [comment]
not stale
