### ISSUE TITLE
Muon results table reselect fits

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33315]
In muon analysis you can unselect a workspace for the results table. If you then re-do the fit, the workspace is not reselected for the results table.

Open muon analysis
Load some data
Go to fitting and add a fit function
Do a fit
Go to the results tab
In the bottom table, unselect the workspace
Go back to the fitting tab and press fit
Go to the results tab
The workspace is still unselected, even though the fit is "new"

see https://github.com/mantidproject/mantid/pull/33002

**Comment by martyngigg** [comment]
Fixed by #33347
