### ISSUE TITLE
Observer for results table in muons

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33318]
If the user creates a results table, then goes to model analysis and looks at the data. If they spot a mistake (e.g. the sample log is wrong) then they will correct it in the table workspace. This does not trigger an event that causes the workspace to be updated. We will need to add an ADS observer onto the results tables. I think it only needs to be on the currently selected table, as changing table should cause it to update.

Open muon analysis
Load some data
Do a fit
Go to results table and output a table
Go to model analysis
Open the results table from the ADS
Change a number and close the table
The GUI does not update the plot

**Comment by sf1919** [comment]
The ADS Observers do not appear to be called for TableWorkspaces.
