### ISSUE TITLE
Maxent plot observer missing

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33333]
In the muon GUI the maxent plot is missing an observer to update the dual plot when the freq plot units are changed. So they can get out of sync.

See https://github.com/mantidproject/mantid/pull/33119/files#diff-3a1cc6c9f1a743dabdb4133b9f19f73111c860d13eb6e27dc9414a1914fa719fR100

**Comment by martyngigg** [comment]
Fixed by #33360
