### ISSUE TITLE
Incorrect detector size in LoadNXSPE giving errors in SofQW3

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#33370]
**Original reporter:** R. Stewart / ISIS

**Describe the bug**

When using [MSlice](https://github.com/mantidproject/mslice) on some datafiles and for certain step sizes a "beating" or "aliasing" effect is observed, but not for other equivalent data. In some cases, this effect is inherent in the data and step size used and should be addressed by MSlice determining an appropriate default step size.

However, in some cases it is the result of a bug in the `LoadNXSPE` algorithm. For example:

![mantid_sqw_nxspe_alias_bug](https://user-images.githubusercontent.com/14106963/150805946-8e9275bf-fea6-4524-9f32-f245280fb878.png)

Here the cuts were produced using the same parameters with the `SofQWNormalisedPolygon` algorithm but on two different input data source - a reduced NeXus `.nxs` and NXSPE file respectively. The two files were producing using the same [reduction algorithms](https://github.com/mantidproject/mantid/blob/main/scripts/Inelastic/Direct/DirectEnergyConversion.py) - the only difference is that in one case `SaveNexus` was used and in the other case `SaveNXSPE` was used.

The bug is because `LoadNXSPE` uses a [fixed size detector](https://github.com/mantidproject/mantid/blob/bda448eb838c6afc307092c47aa2215d6d9f7a3f/Framework/DataHandling/src/LoadNXSPE.cpp#L276) which is always set to be a sphere of 1cm radius. However, this is actually often smaller than the physical detector size. Now the `SofQWNormalisedPolygon` algorithm actually calculates the `2theta` extends of each spectrum from the detector size. Since the detector size loaded from `.nxspe` files are smaller than the physical size, there artificial "gaps" in the scattering-angle representation of the data. When converted into Q-space by `SofQWNormalisePolygon` this leads to the aliasing behaviour shown in the picture above.

The NeXus `.nxs` files saves the original detector size so the `2theta` extents calculated by `SofQWNormalisedPolygon` is correct, and no aliasing is seen.

**To Reproduce**

Run this script:

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

datadir = '//olympic/Babylon5/Public/duc/Ross nxspe files'
reffile = 'LET73024_rings_3.70'
step_size = 0.01166

wnxs = Load(datadir+'/'+reffile+'.nxs')
q_nxs = SofQW3(wnxs, EMode='Direct', QAxisBinning='0,%f,5' % (step_size), EAxisBinning='-0.5,10,0.5')
q_nxs = Transpose(q_nxs)
SaveNexus(q_nxs, datadir+'/'+'q_nxs.nxs')

wnxspe = Load(datadir+'/'+reffile+'.nxspe')
q_nxspe = SofQW3(wnxspe, EMode='Direct', QAxisBinning='0,%f,5' % (step_size), EAxisBinning='-0.5,10,0.5')
q_nxspe = Transpose(q_nxspe)
SaveNexus(q_nxspe, datadir+'/'+'q_nxspe.nxs')
```

and plot the generated `q_nxs` and `q_nxspe` workspaces. The data are on the babylon system `\\olympic\Babylon5\Public\duc\Ross nxspe files` - the `.nxs` file is 65MB, and the `.nxspe` file is 2MB.

**Expected behavior**
The two q-cuts look similar without the beating / aliasing in the cut from the `.nxspe` datafile.

**Platform/Version (please complete the following information):**
 - OS: Windows 10, Scientific Linux 7 (DAaaS system).
 - Mantid Version: nightly / master

**Comment by martyngigg** [comment]
Fixed by #33373
