### ISSUE TITLE
Mantid crashes when running an absorbption correction in Indirect

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#33384]
**Original reporter:** Spencer Howells

**Describe the bug**
In the Apply Absorption Corrections tab in the Indirect Corrections GUI, pressing the run button after loading a sample and corrections makes Mantid disappear (when using Windows). When using Ubuntu the same action causes a segmentation fault.

**To Reproduce**
1. Open Indirect -> Corrections
2. Open the Apply Absorptions Corrections Tab
3. Load a sample file
4. Load a corrections file
5. Press Run
6. Windows users will see Mantid close, Ubuntu users will get a segmentation fault.

**Expected behavior**
Pressing the run button should not crash Mantid or cause a segmentation fault.

**Platform/Version (please complete the following information):**
Tested by user on Windows and Ubuntu (versions not supplied)

Tested by @sf1919 on Windows 10 using Mantid v6.2.20220124.1600

**Comment by sf1919** [comment]
In discussion with user it was suggested that the lack of a check for the number of histograms in the sample and corrections being equal was the cause of the issue. This was not the case and the issue lies elsewhere.

**Comment by martyngigg** [comment]
Fixed by #33395
