### ISSUE TITLE
Duplicate window doesn't work with graphs

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#3339]
This issue was originally [TRAC 2492](http://trac.mantidproject.org/mantid/ticket/2492)

-Open MantidPlot
-Load a workspace
-Choose Plot Spectrum from r-click menu and click ok on default
-Plot is shown
-Click on duplicate window icon on top toolbar

Cloned plot is scaled and titled and labelled and has legend set up correctly. Although actual plot data is missing from cloned plot.

**Comment by NickDraper** [comment]
We should just remove the menu option

**Comment by NickDraper** [comment]
Duplicate works for 1d graphs, 2d graphs and is disabled for several other situations, this looks fine now to me.
