### ISSUE TITLE
Create tests for Apply Absorption Corrections 

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#33396]
**Describe the outcome that is desired.**
Create test(s)n for the Indirect Apply Absorption Corrections interface in order to check for errors. It was recently identified as part of work for #33384 that a test might have prevented the bug from happening when a larger cross-Mantid piece of work was undertaken.

**Describe any solutions you are considering**
Create suitable test(s).

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create tests for Apply Absorption Corrections](https://trello.com/c/TwzZxzNS/26-create-tests-for-apply-absorption-corrections)
