### ISSUE TITLE
Integration with RebinnedOutput workspaces

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#33407]
**Original reporter:** R. Stewart / ISIS

**Describe the bug**

There is a maths error in the way in which the `Integration` algorithm handles `RebinnedOutput` workspaces which have fractional weights *Fi*. Taking a spectrum with *n* bins within the integration range, `Integration` is meant to sum up the **counts** within the range. For a `RebinnedOutput` the counts are defined by:

<img src="https://latex.codecogs.com/svg.image?C_i&space;=&space;Y_i&space;F_i" title="C_i = Y_i F_i" />

where *Yi* and *Fi* are the values stored in the `Y` and `F` vectors of the workspace. The current calculations compute:

<img src="https://latex.codecogs.com/svg.image?\left.&space;\sum_{i=0}^n&space;C_i&space;\middle/&space;\sum_{i=0}^n&space;F_i&space;\right." title="\left. \sum_{i=0}^n C_i \middle/ \sum_{i=0}^n F_i \right." />

However, if we take the limiting case where there are no bins with fractional weights and all the *Fi* values are unity, then we are actually computing:

<img src="https://latex.codecogs.com/svg.image?\left.&space;\sum_{i=0}^n&space;Y_i&space;\middle/&space;n&space;\right." title="\left. \sum_{i=0}^n Y_i \middle/ n \right." />

So the computed integrals are actually smaller by a factor *n* (the number of bins being integrated over) than they should be. We should thus multiply (normalise) the integrated output by the number of bins.

However, this does not properly account for regions of the data where there is no overlap, where the *Fi* values are defined to be zero. In the `Integration` algorithm, these bins (which previously had Y values of `NaN`) have their values [set to zero](https://github.com/mantidproject/mantid/blob/715ccc45baa79904e33d433678ef1384b1c5792d/Framework/Algorithms/src/Integration.cpp#L382) and included in the sum, *but they should not be included in the normalisation* because they have by definition *Fi*=0. The normalisation factor is thus the number of non-zero-fraction bins rather than the number of bins.

**To Reproduce**

This maths error is most clearly seen in the following vanadium measurement, where there is only intensity in the elastic line, so logically if we integrate over the elastic line then the integral (as long as it covers the full elastic energy window) should be independent of the integration range.

The data file is here: [LET73024_3.70meV.nxspe.zip](https://github.com/mantidproject/mantid/files/7966616/LET73024_3.70meV.nxspe.zip), and this script will plot a 2D spectrum in Q-E (Momentum-Energy): [Note that the call to `SofQW3` produces a `RebinnedOutput` workspace with fractional bins].

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np

ws = Load('LET73024_3.70meV.nxspe')
ws_rebinnedoutput = SofQW3(ws, QAxisBinning='0,0.01,2', EAxisBinning='-3,0.02,3', EMode='Direct') 
fg, ax = plt.subplots(subplot_kw={'projection': 'mantid'})
ax.pcolormesh(ws_rebinnedoutput, norm=LogNorm() )
fg.show()
```
![integration_bug_2d](https://user-images.githubusercontent.com/14106963/151712607-71eb5523-9507-4a95-8d72-135650a5b566.png)

As can be seen, outside of the range [-0.5, 0.5]meV the intensity is almost zero, so logically integrating from [-1,1]meV or [-2,2]meV should produce the same integrals. However, running this script after the previous:

```python
fg, ax = plt.subplots(subplot_kw={'projection': 'mantid'})
for ii, irange in enumerate([0.5, 1, 2]):
    ws_int = Integration(ws_rebinnedoutput, -irange, irange, OutputWorkspace=f'ws_int_{ii}')
    ws_int = Transpose(ws_int, OutputWorkspace=f'ws_int_{ii}')
    ax.errorbar(ws_int)
ax.set_ylim(0, 20)
fg.show()
```
![integration_bug_1d](https://user-images.githubusercontent.com/14106963/151712660-1cac6a52-a34d-48b1-b0a7-dd61991a4ad1.png)

shows that not only does the different integration range give different values these values are also incorrect insofar as the data represents an absolute units measurement so that the integral should equal the cross-section of Vanadium - which is 406 mbarns / steradian. In the original call to `SofQW3` we used 0.02 meV bins so the [-0.5, 0.5] integration should have 50 bins and we see that multiplying the result by 50 gives approximately 450 mbarns/sr, which is close to the expected value (absolute intensity measurements are subject to systematic errors due to the absolute units corrections and are often only ~10% accurate).

In contrast, running the above loop with `Integration(ws, ...` instead of `Integration(ws_rebinnedoutput, ...` gives curves which lay on top of each other with values around 450 mbarns/sr as expected.

**Expected behavior**

The integrated values for a elastic line measurement should not depend on the integration range if the range is larger than the elastic window, and the integrated values of an absolute units measurements should be close to the expected cross-section of the materials measured.

**Screenshots**
N/A

**Platform/Version (please complete the following information):**
 - OS: All (tested on SL7 and Windows 10)
 - Mantid Version: Nightly (`6.2.20220127.1718`)

**Additional context**

**Comment by martyngigg** [comment]
Fixed by #33408
