### ISSUE TITLE
Unify package location definitions

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33442]
Discover and investigate new ways for package version definitions, currently, we label current package versions in up to 7 places.

- Each recipe in the recipes repository
   - mantid
   - mantidqt
   - mantidworkbench
- The global pinnings for the recipes repository
- Each of the developer environment.yml files
   - win
   - linux
   - osx

Avenues to investigate:
- Unify recipes repository location just using the global pinnings
- Potentially generate the developer environment.yml files locally based on the global pinnings in the recipes repo using a shell script (pre-req of git on windows for sh.exe)

**Comment by thomashampson** [comment]
Reopening this because there is a new idea for how to resolve it.

**Comment by thomashampson** [comment]
actually I'll just create a new issue.
