### ISSUE TITLE
Ensure IDAaaS is updated to provide support for basic and advanced users

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33453]
Update IDAaaS to use the latest release via Conda-forge and nightly via Mantid, communicate with IDAaaS support to ensure that the correct versions are used, and IDAaaS is prepped for the conda switch on Linux.

    Discuss the potential for a shortcut to a terminal that is inside the mantid conda environment

**Comment by martyngigg** [comment]
The switch to conda was done in ral-facilities/daaas-ansible-workspace/#742 (note this is a private repository). Closing this as we don't currently consider a shortcut to terminal necessary.
