### ISSUE TITLE
Update deployment pipeline for supporting release packages using env vars.

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33451]
- Ensure that it is uploaded to the main channel on Mantid, instead of the nightly labelled channel.
- Ensure the versioning changes in conda-recipe are release aware perhaps adding a permanent tag?
- Windows signing needs to be handled i.e. not deployed automatically.
- Adapt the current deployment strategy for release to include either 1. Release candidates or 2. A new job that deploys manually like the previous system (Use option 2 unless decided otherwise)
- How do we handle documentation?

**Comment by martyngigg** [comment]
We're going to have to do some of this manually again this time.

**Comment by thomashampson** [comment]
I think this is already implemented, but will have to check.

**Comment by thomashampson** [comment]
This has been implemented
