### ISSUE TITLE
User function crash

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33505]
Report to user
Adam Berlie

If you add a user function while plot guess is displayed then press fit Mantid crashes

1. Load some data, e.g. EMU00020884 from training course data
2. Plot a spectrum
3. Open the fit browser
4. Add a flat background
5. Display the plot guess
6. Add a user function and set the forumla (see [here ](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/fitting_data/03_fit_model_choices.html) for help)
7. Run the fit and Mantid will crash.

**Comment by thomashampson** [comment]
I've updated the description because I couldn't reproduce the crash without some key information.

**Comment by thomashampson** [comment]
We had some people come to the office to report this too, so it's probably worth fixing.

**Comment by sf1919** [comment]
This also occurs when undertaking the following steps on v6.7

1. Open Mantid
2.  Open Muon Analysis GUI
3. Select EMU as instrument (if not already the default)
4. Load `EMU00020884.nxs` from the Training Course Data set
5. Click on the fitting tab
6. Add a Fitting function (e.g, Dynamic Kubo Toyabe)
7. Tick Plot guess
8. Untick plot guess
9. Add another fitting function
10. Click plot guess

Mantid then crashes.

**Comment by AnthonyLim23** [comment]
It looks like the original issue has been fixed (since it was in the main fitting of Mantid, i.e. not in the muon GUI). 

The new issue seems to only happen in the muon GUI. I have been unable to replicate it in
1. The main fitting window
2. Indirect data analysis
3. Enginex
4. ALC

so here is probably a good place to start looking 
https://github.com/mantidproject/mantid/blob/main/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py#L456
