### ISSUE TITLE
Grid lines turn on unexpectedly on 3D plots when changing axis format.

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#33508]
**Describe the bug**
When changing the axis tick format in a 3D plot with gridlines switched off, the gridlines will turn back on again.

**To Reproduce**
1. Load a workspace and plot a 3D surface plot
2. Turn off gridlines using the toolbar button
3. Double click an axis value to bring up the "Edit axis" dialog
4. Change the tick format to Scientific Format and click OK.
Grid lines will turn back on (and the toolbar button will have an incorrect state).

**Expected behavior**
Grid lines should stay off.

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version: 6.1 onwards confirmed

**Comment by DonaldChung-HK** [comment]
In `propertiesdialog,py` , `AxisEditor.changes_accepted`, `axes.grid(visible=self.ui.gridBox.isChecked(), axis=self.axis_id, which=which)` it seems like `visible` for `axes.grid` will be True regardless of input if other arguments are supplied so even if `self.ui.gridBox.isChecked()` is `False` the grid line will still show after executing the function.
`
