### ISSUE TITLE
Create standalone packages on Windows

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33524]
-  Ensure install can run successfully in Windows
      - Enable Windows to install C++ dependencies
      - Enable Windows to install a working python in a conda env in the install location
  - Setup CPack to handle Windows packaging the install

Remaining work
- [x] NSIS script to call uninstall before installing in same directory - Sam
- [x] modern UI for NSIS - Sam
- [x] #33634 - Sam
- [x] #33736
- [x] desktop shortcuts - Tom
- [x] icons - Sam

**Comment by martyngigg** [comment]
All work has been completed.
