### ISSUE TITLE
Debug builds on Windows inside a conda environment

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33525]
Presently it is not possible to compile in Debug mode using our conda environments using MSVC as it requires Debug compiled packages. These are not currently provided by conda-forge.

It is possible to compile all of them ourselves in a systematic manner, upload them somewhere, and use them ourselves. This is a big task as in each case EVERY dependency of EVERY dependency will need to be compiled using Debug mode in MSVC if we do this ourselves.

- [x] #33526 

Big questions:
- How to support libnexus? Absorb it into mantid?
- How to unite the locations we define packages, one core location that has Jinja templates for conda and others for debug libraries?

**Comment by thomashampson** [comment]
No longer needed now that we have the DebugWithRelRuntime build config
