### ISSUE TITLE
Investigate different possibilities for Debug in Windows via Conda and new package management

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33526]
- [ ] Conan - Already made debug libraries (With integration inside of CMake) (I am guessing this is the best option)
  - [ ] Github third party repo (Not this, we want to move away from this generally)
  - [ ] Conda hosted debug packages (Limited by 3GB storage)

Discarded candidates
~~Windows Package Manager 1.0 (winget)~~ In it's infancy
~~Chocolatey (Aimed mostly at final packages and doesn't have much support for development packages)~~ Mentioned in it
~~Scoop (has a limited scope but possible to make our own scope inside of it, but we may have to carry a heavy maintenance burden)~~ Mentioned in it
~~npackd (Similar to scoop)~~ Like Scoop
~~MSYS2 (MinGW/Clang only)~~ Have to change compiler

Likely candidates:
- Conan (Scipp utilizes conan as part of it's CMake)
    Needed for Conan:
    - Libnexus
    - lib3mf
    - PyQt5
- Conda (Heavy maintenance burden, and limit on storage, but it will use only one package management solution)

Aim:
Further, investigate a project with a conda environment with Conan being called from CMake to deliver debug packages on Windows.

After investigating each option, update the epic to include a plan for implementing the best option for this.

**Comment by DavidFair** [comment]
We should check if Conan doesn't include PyQt5 (which is a popular enough project) because of resource issues or philosophical ones

**Comment by thomashampson** [comment]
No longer needed now that we have the DebugWithRelRuntime build config
