### ISSUE TITLE
Stop system test process overwriting MaxCores setting if it doesn't complete properly

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#33542]
The system test process currently temporarily sets MultiThreaded.MaxCores=2 in the Mantid.user.properties file. Perhaps it achieves this by temporarily swapping in a special Mantid.user.properties.systest - can't remember.

Anyway - if you ever kill a run of the system tests (Ctrl-C it) then the temporary setting stays.

This can result in Mantid taking a long time to run algorithms eg absorption correction algorithms.

This issue is to investigate whether the system test process can achieve the aim of setting MaxCores=2 in a way that doesn't leave this behind if the system process is killed or doesn't complete properly for some reason

**Comment by thomashampson** [comment]
I think this is also a part of this issue #33440
