### ISSUE TITLE
Offer plotting in QSpace in Indirect Diffraction

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#33551]
**Is your feature request related to a problem? Please describe.**
When using Indirect Diffraction GUI there is the option to plot a spectrum after successfully loading a run on diffspec. At the moment the plot produced is in d-space. Users would like the option to have the results in Q-Space.

**Describe the solution you'd like**
Provide users with the ability to choose whether their plot is in d-space or Q-Space and produce the relevant plot.

**Additional context**
Requested by Users

**Comment by sf1919** [comment]
@AnthonyLim23 I'll leave this one for you to decide on.

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offer plotting in QSpace in Indirect Diffraction](https://trello.com/c/gdtWpgi3/20-offer-plotting-in-qspace-in-indirect-diffraction)
