### ISSUE TITLE
ReflectometryBackgroundSubtraction dialog crashes if workspace group present in ADS

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#33627]
I've just spent some time investigating an obscure crash in the docs build on Jenkins in a PR (https://github.com/mantidproject/mantid/pull/33609) where I had added a new usage example to one of the correction algorithms (DiscusMultipleScatteringCorrection). The crash was caused by the fact that I had forgotten to clear down the ADS at the end of the new usage example and the algorithm had left behind a workspace group in the ADS. 

This was causing the doc build on ReflectometryBackgroundSubtraction to crash later on because it couldn't display the algorithm dialog. The crash happens in ReflectometryBackgroundSubtraction::validateInputs when validating the "ProcessingInstructions" parameter. Somewhere in the code it tries to cast the input workspace to a MatrixWorkspace and throws an unhandled exception if the cast doesn't succeed - which I guess it doesn't if the input is a workspace group.

The cause of the problem wasn't v clear from the Jenkins logs so I think it would be useful if the dialog for ReflectometryBackgroundSubtraction would still display even if a workspace group is in the ADS (which I guess gets used as the default input workspace if it's lying around).

I've added the missing mtd.clear() to my new usage example to fix this on my PR so no major hurry - or I can pick up in the next maintenance cycle perhaps if you agree this is useful

@gemmaguest, @DavidFair - just put in this issue relating to one of the reflectometry algorithms. Is this one of yours and if yes is this something you'd be happy to pick up at some point?

**Comment by gemmaguest** [comment]
@DannyHindson Yikes that doesn't look good. Yes it's one of ours so we'll take a look, thanks for investigating it that far.
