### ISSUE TITLE
Use SXD2001 method of extracting errors from 3D profile fitting

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#33630]
3D profile fitting we have developed for SXD gets an error from a Monte-carlo approach fitting simulated datasets (the error from the fit, even scaling the covar matrix by variance of residuals underestimates sigma by factor ~2-3). The Monte-carlo method is slow and still underestimates error of weak reflections.

SXD2001 uses the errorbars on the data points to get sigma of intensity, in addition SXD2001 also adds the integration of the difference curve to the fitted peak intensity (and the corresponding error to sigma - adding in quadrature). In addition all points with y = e = 0 are assinged e = 1 (which will also increase the sigma of the peak relative to the present Monte-carlo approach).

Compare to SXD2001 when refining NaCl

**Comment by RichardWaiteSTFC** [comment]
Have replaced error in empty bins with 1 - but this is overwritten when ReplaceSpecialValues - so have used avg. error on non-zero bins in that quarter of each spectrum (used quarter as zero bins occur primarily at each end of the spectrum low and high lambda where little flux, these regions have larger errors as well). Haven't added the difference curve to the 3D profile fitted intensity, but just replacing empty bin errors fixed the majority of the discrepancy between I/sig in SXD2001.

**Comment by DannyHindson** [comment]
Currently in stand alone script that implements the 3D profile integration. Not yet implemented as algorithm because of lmfit dependency - could be implemented with scipy.optimize
