### ISSUE TITLE
Replace mantidworkbench.cpp with a python implementation and exe from that.

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33634]
Presently we use an unideal implementation for MantidWorkbench.exe production on windows, the main offending file is mantidworkbench.cpp this functionality needs to be replaced in python. 

The main notable behaviour is error reporter still opening post segmentation fault. Creation of exe from python? Work it out!

**Comment by martyngigg** [comment]
Fixed in #33742
