### ISSUE TITLE
Indirect: data manipulation GUI

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33676]
This issue is to move the following tabs into a new "data manipulation" GUI:
from data analysis:
- Elwin 
- I(Q,t) 

from reduction:

- symmetrize
- S(Q,omega)
- moments

**Comment by Harrietbrown** [comment]
Right now the symmetrize, S(Q,omega), and moments tabs all use the indirectDataReductionTab, they can not be changed while they are still in the Indirect Data Reduction so this is the issue where that will be changed.
