### ISSUE TITLE
SANS GUI won't open if you have a v0 toml file previously loaded

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#33718]
**Describe the bug**
If you had previously loaded a v0 toml file in the SANS GUI, it will remember it the next time you open the GUI. After the version was bumped to v1, v0 is no longer supported and throws an error. This is expected; however, currently the error is not handled, causing an alarming warning and stopping the SANS GUI from being able to be opened.

Note that as a workaround to get the GUI to open you can remove or rename the file it is trying to load.

**To Reproduce**
- In a version of Mantid prior to this PR, open the ISIS SANS and load the user file from `loqdemo/Maskfile.toml` in the TrainingCourseData. (first check in the file that `toml_file_version = 0` and temporarily edit it to set it to that if not).
- It should load ok. Close the GUI and exit Mantid.
- Now build Mantid from this PR and restart.
- Try to open the SANS GUI. It throws an unhandled exception.

![image](https://user-images.githubusercontent.com/12895056/161109604-05ca196a-2360-45f1-b4c5-fb7c0b415319.png)

**Expected behavior**
You should get a warning that the v0 file is not supported, but the SANS GUI should open ok. The user file should be empty.

**Platform/Version (please complete the following information):**
 - OS: all
 - OS Version: all
 - Mantid Version regression on main caused by #33660

**Comment by smk78** [comment]
Nice catch @gemmaguest !
