### ISSUE TITLE
Enable mantid notebook in Windows conda standalone package

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#33812]
This has been disabled temporarily because it wasn't working. It needs to be re-instated and function the same as with the previous release.

The uninstaller should also function correctly after notebook is opened and closed (i.e. no python processes left behind).

**Comment by martyngigg** [comment]
A quick try on the command line suggests that the right thing to do is run:
```python
python -m jupyter notebook
```
to get it started.

I think we might need to install the `notebook` conda package in addition inside the Windows conda build.

**Comment by martyngigg** [comment]
Fixed by #33888
