### ISSUE TITLE
Tube calibration and direct beam generator scripts

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#33821]
**Is your feature request related to a problem? Please describe.**

ISIS SANS have some historical scripts for direct beam generation and tube calibration that are essential to the reduction. The scripts need to be updated and tests added so that they can be maintained by the Mantid team. The scripts are not well understood so this needs to be done before Richard retires at the end of 2022.

**Describe the solution you'd like**
- The scripts currently need to be edited by users for each experiment, making them difficult to use and error-prone. As a minimum they need to be parameterised to make usage easier and so that a canonical version of the scripts can be maintained.
- Tests need to be added to verify behaviour and ensure bugs are not introduced. 
- Documentation needs to be added.
- Ideally we would like to convert the scripts to Mantid algorithms so that they can be added to the Mantid repository but depending on the complexity this may not be possible.

**Additional considerations**
- If the scripts cannot be converted to Algorithms we should consider whether they could be added to the Mantid Script Repository, or maintained in a separate repository. This may depend on what other scripts SANS are using and how they are maintained.
- Consider whether the scripts contain functionality that is duplicated in Mantid and if so whether we can re-use existing Mantid algorithms instead.
- Consider whether it is possible/useful to extract functions from scripts into child Algorithms in Mantid. 

See also:
- [x] #28986
- [x] #10892
- [x] #27386

**Comment by rbauststfc** [comment]
Closing as all the linked issues have been completed. Smaller, follow-up issues have been created and will be tracked separately.
