### ISSUE TITLE
SANS GUI: Ability to process data directly from the DAE

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#3385]
sans_feature
This issue was originally [TRAC 2538](http://trac.mantidproject.org/mantid/ticket/2538)

From Ann Terry:

We've also noticed another similar thing in that we can load data from the DAE into the workspace, but how would we specify the same thing on the SANS gui?

In principle we can skirt round the issue by creating a sav file and loading that but one of the problems is that sav files don't get deleted (or at least they didn't use to) and so if you abort a run and then restart it, you could make a mistake and load a sav file from the previous run if you hadn't overwritten it. Loading directly from the DAE means this can't happen and is also very quick at the moment.

This probably needs to be discussed with the SANS guys first to pin down exactly how they want this to work.

**Comment by Mantid-Matthew** [comment]
This ticket is now very old and the introduction of live data into mantid supersedes it so am closing.
