### ISSUE TITLE
GIL and ADS observer deadlock with workspace groups

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#33863]
**Original reporter:** Max at ISIS

**Describe the bug**
There is still a hang similar to #33664 where Mantid can get into a deadlock where:
- A python algorithm is running and holds the GIL. This algorithm calls into code that causes an ADS update without releasing the GIL.The ADS notification waits on a Poco lock to notify its observers.
- Meanwhile another thread is already doing a Poco notification and has that lock; but that notification causes a call into python which requires the GIL, ending in deadlock.

The problem is that the first thread is not releasing the GIL before calling into the C++ code that does the ADS update.

A fix was added in PR #33756 to ensure DataServiceExporter calls that cause ADS notifications release the GIL. However we are seeing the same problem with the exports for [WorkspaceGroup](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/mantid/api/src/Exports/WorkspaceGroup.cpp#L86) so a similar fix needs to be added there for any WorkspaceGroup methods that cause ADS updates (I think this comprises `add`, `addWorkspace` and `remove`). 

**To Reproduce**
At the moment I can only reproduce this in the reflectometry GUI with live data and batch processing running. This requires the ISIS archive to be enabled and also requires live data to be running on an ISIS reflectometry instrument so needs to be done in cycle during an experiment. However, testing the below with batch processing only would also exercise the affected code to ensure nothing is broken after we fix this, even if it's hard to reproduce the problem.

- Open the ISIS Reflectometry interface
- Go to the Batch->Load menu and load this [json file](https://github.com/mantidproject/mantid/files/8653732/python_hang_batch.zip)
- Click Start Monitor. This starts the live data monitor and after a while should result in two workspaces - `TOF_live` and `IvsQ_binned_live` if valid live data is running and can be reduced. Open sliceviewer on the former and a line plot on the latter. If this fails, skip this step.
- Click Process to start processing the runs in the table. They should gradually turn green as processing completes.
- Leave everything running. I find the deadlock normally occurs within a minute or so.

**Expected behavior**
It should  be possible to run multiple python algorithms simultaneously that cause ADS updates (including via WorkspaceGroup modifications) without crashing or deadlock. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12895056/167458126-b19ed607-a343-4e8a-b198-868b93eb2910.png)

**Platform/Version (please complete the following information):**
 - OS: seen on IDAaaS and Ubuntu 20.04, but probably all
 - Mantid Version 6.3.0 and also the nightly including after PR #33756

**Comment by martyngigg** [comment]
Fixed by #33867
