### ISSUE TITLE
Add a new fitting process based on GoFit to the CEF Python interface

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#33864]
GOFit is a global optimization package that was developed to improve fitting especially for Crystal Field problems. 
The package consists of C++ algorithms with python interfaces. To make GOFit easily available the aim is to add a new fitting process similar to two_step_fitting to the Crystal Field Python interface and document on [Crystal Field Python Interface](https://docs.mantidproject.org/nightly/interfaces/direct/Crystal%20Field%20Python%20Interface.html) how to use it.

GOFit has three different algorithms, Multistart, Alternating and Regularisation. During tests with these algorithms Regularisation performed best for Crystal Field problems so it should be used as a default. However, it would be beneficial to have all three options available.

**Comment by jfowkes** [comment]
@robertapplin happy to modify the GOFit interface if required.
