### ISSUE TITLE
Font + font menu have changed on Linux Tar package on Ubuntu

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#33875]
When installing for manual testing, found on the mantidworkbenchnightly-6.3.20220510.2145.xz tar file for Linux

**Describe the bug**
The default font has changed. This could be intentional and may be required to support all flavours of Linux. The new font seems to be Sans Serif and the old one was Ubuntu Default. See the images below for the comeparison. It's a big change to the feel of the interface and we may need to actively choose a new font to support all Linux systems.

- Note also that the font menu is different on the different versions (the old one uses the Ubuntu native font selector)

**Screenshots**
On an old nightly:
![Screenshot 2022-05-11 at 13 52 20](https://user-images.githubusercontent.com/55980573/167855183-517d34b3-bab6-4c48-8a83-e99468db5676.png)

New tar installed version:
![Screenshot 2022-05-11 at 13 51 18 (2)](https://user-images.githubusercontent.com/55980573/167855255-7e685bd2-b700-4123-91d7-3b5ce9bcb21a.png)

**Platform/Version (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mantid Version 6.3.20220510.2145

**Comment by DannyHindson** [comment]
Have just come across this font issue again while doing 6.5 smoke testing. I see what's described above but in addition I also get this error on startup of workbench:

![image](https://user-images.githubusercontent.com/56295817/196163738-7fd281e1-8f13-4c7e-9882-c3f0a82eb91d.png)

and further when I change the font from Sans Serif to something else (eg the font called "Ubuntu" - I don't have "Ubuntu Default") then it seems like only some of the text gets updated to the new font. This is after having changed the font and restarted workbench:

![image (1)](https://user-images.githubusercontent.com/56295817/196164057-495b05c5-18da-4d1e-b303-aea9e9bf69ba.png)

So the font used for the menu has updated but some of the other text is stuck as Sans Serif

**Comment by martyngigg** [comment]
I have just come across something similar on a completely unrelated project. When you get a second could you try running

```sh
export FONTCONFIG_PATH=/etc/fonts
mantidworkbench/bin/mantidworkbench
```
to see if that fixes the issue?

**Comment by DannyHindson** [comment]
That didn't work for me. Although this did:
```
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
```
Using that on my Ubuntu VM, I no longer get the Fontconfig error on start up and the fonts look correct

**Comment by martyngigg** [comment]
> That didn't work for me. Although this did:
> 
> ```
> export FONTCONFIG_FILE=/etc/fonts/fonts.conf
> ```
> 
> Using that on my Ubuntu VM, I no longer get the Fontconfig error on start up and the fonts look correct

Interesting. The file is there but the environment variable is not set for some reason. At least that is something to go on.

**Comment by MialLewis** [comment]
Just noting that we had a user complain about the new font.

**Comment by martyngigg** [comment]
It looks like I'm still subscribed to this issue so I got the notification and I just thought I'd record here that for me on IDAaaS I seem to see better fonts. This is the Nightly on an ALF IDAaaS instance for me:

![image](https://user-images.githubusercontent.com/733773/222427209-aa39c0e9-b702-49ce-bc7d-a4f063d09e5a.png)

I don't recall doing anything special but maybe I have some config files or something in my home directory... 🤔

**Comment by martyngigg** [comment]
I also don't get the `fontconfig` error that Danny noted above when starting with

```sh
/opt/mambaforge/bin/conda run -p /opt/mantidworkbenchnightly mantidworkbench
```

I hope this might be helpful!

**Comment by jhaigh0** [comment]
Default font looks okay now. Will reopen if we get complaints again
