### ISSUE TITLE
Default list of files on Engg fitting tab is cumulatively populated with all previously focussed files

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#33879]
The load edit box on the Engg UI fitting tab should be set to the last files focussed on the fitting tab:

![image](https://user-images.githubusercontent.com/56295817/167901459-5f2e6cc8-a67f-4ca0-985a-a853e2bac663.png)

If a user performs multiple focus actions the edit box should only contain the last run or runs focussed. At the moment it contains a cumulative list of all runs previously focussed.
This is obvious if you run a focus with a texture calibration active followed by a focus on just the North\South banks. You get 20 + 2 files defaulted into the fitting tab load edit box

Initial investigation suggests this is problem - list is initialized to blank in init rather than on each call to focus_run:
```
class FocusModel(object):
    # model shares code with the EnginX auto reduction script - code is kept in EnggUtils.py
    def __init__(self):
        self._last_focused_files = []

    def get_last_focused_files(self):
        return self._last_focused_files

    def focus_run(self, sample_paths: list, vanadium_path: str, plot_output: bool, rb_num: str,
                  calibration: CalibrationInfo, save_dir: Optional[str] = output_settings.get_output_path()) -> None:
        full_calib = load_full_instrument_calibration()
        focused_files = EnggUtils.focus_run(sample_paths, vanadium_path, plot_output, rb_num, calibration, save_dir,
                                            full_calib)
        self._last_focused_files.extend(focused_files)
```

**Comment by martyngigg** [comment]
Fixed by #33927
