### ISSUE TITLE
Docs Missing on New Packaged Nightlies

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#33881]
**Describe the bug**
On the new packaged versions (the ones on babylon) the opening the docs finder shows the finder but is completely blank, missing all docs. 

On Ubuntu specifically (CentOS is just blank), doing this will crash workbench to desktop.  

**To Reproduce**
1. Launch workbench
2. Open docs through Help -> Mantid Help
3. Open docs from any of the `?` buttons.

**Expected behavior**
The relevant documentation should be shown and it should be possible to navigate to all docs from the window that pops up. 

**Screenshots**
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/47181718/168020009-2a0da693-6e1a-4846-b867-122593f42895.png">

**Platform/Version (please complete the following information):**
 - OS: All (Ubuntu has a crash)
 - Mantid Version: (Conda?) Packaged Nightlies

**Comment by SilkeSchomann** [comment]
The conda package for Windows crashes whenever the help menu is accessed, regardless whether it is via the menu or ? or from the about page.

**Comment by martyngigg** [comment]
Fixed by #33922
