### ISSUE TITLE
Muon docs update

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#33904]
This is a list of changes needed to the muon docs for testing from https://github.com/mantidproject/mantid/issues/33834

**General**
Add link to feature flag doc

**ALC**
Change from marker to add section

**MUSR**
plot selector 
list the wrong globals
Change "select data" to "display parameters for"

**PSI**
Change from 0.007 to 0.006

**EMU**
Move the line about external plots
Remove bit on stepping through the plots in superconducting 

**FDA**
The default FFT settings have changed
Phasequad is added in a different way
Maxent output names need updating

**HIFI**
Change to selected groups

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [muon manual test update](https://trello.com/c/vdvROqhC/20-muon-manual-test-update)

**Comment by MohamedAlmaki** [comment]
Most updates are done. But I need clarification on the following:

**General**
Do you mean the muon feature flags do? if yes, where to add it?

**MUSR**
what are the wrong globals?

For **EMU**, **FDA**, and **HIFI**, I'm not sure what should be done.

**Comment by AnthonyLim23** [comment]
> I did some of the updates, but I need clarification on the following:
> 
> **General** Do you mean the muon feature flags do? if yes, where to add it?
 on this page https://developer.mantidproject.org/Testing/MuonAnalysis_test_guides/Muon%20Analysis%20Unscripted%20Testing%20Guide.html we should add some information about the feature flags (giving access to the model analysis) and a link to the doc, in the preamble.

> 
> **MUSR** what are the wrong globals?
> 
- the globals should be Sigma and Frequency


> For **EMU**, **FDA**, and **HIFI**, I'm not sure what should be done.
for EMU:

1. In the Ionic diffusion test, the last 2 lines (about external plotting) and the image should be moved to the bit between "expected values" and "go to the fitting tab"
2. Remove the line "Using the > button, step through a couple files (Plot should update each time)"


For FDA (frequency domain analysis)
1. Do the first test and update the doc (some workspaces will no longer be made).
2. Do the test and add to change the doc to reflect the workflow (having to  tick the add to plot etc.)
3. Do the Maxent test and update the doc to reflect the new workspace names. 

For HIFI
1. delete the lines: To see all of the data press the select plot data button and select 134028 in the pop-up and Keep the pop-up open
