### ISSUE TITLE
Marker label becomes detached from marker when zooming

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#33907]
**Describe the bug**
When I add a vertical or horizontal marker to a plot and then zoom out using the scroll wheel, the label for the marker becomes detached from its line (as if it uses a different coordinate system).

**To Reproduce**
1. Load any data
2. Plot a spectrum
3. Right click the plot and add a vertical marker
4. Zoom out using the scroll wheel. The marker label becomes detached from the line, a bit like this:
![image](https://user-images.githubusercontent.com/40830825/168301644-929162ce-f5a9-465b-899f-f969cfcf3f85.png)

**Expected behavior**
The marker label should stay next to the marker.

**Platform/Version (please complete the following information):**
 - Found on windows

**Comment by robertapplin** [comment]
Added to Milestone 6.4 for now. Feel free to move it out if it isn't important to fix for this release

**Comment by jhaigh0** [comment]
Just to keep track; the markers also become detached when panning using middle mouse (but not when using the dedicated pan tool in the toolbar).
