### ISSUE TITLE
LaTeX not available when building online developer documentation

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#33969]
The online developer documentation does not display LaTeX formulae correctly anymore: https://developer.mantidproject.org/Testing/MSlice/MSliceTestGuide.html

**Screenshots**
![image](https://user-images.githubusercontent.com/74243814/169863134-26998e50-51af-4693-8dda-c712d0af0349.png)

**Comment by MialLewis** [comment]
Can we add to this that LaTeX also appears unavailable in the online user docs, I imagine it's the same issue (found during testing #34944)?
