### ISSUE TITLE
Ubuntu Plotting Smoke Tests  :chart_with_upwards_trend: :bar_chart:

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34075]
* Follow the instructions [here](https://download.mantidproject.org/ubuntu.html) to install the .deb for Ubuntu

**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :chart_with_upwards_trend: :bar_chart:

* 1D plotting:[instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/03_displaying_1D_data.html#displaying-1d-data)
 - [x] Simple plot 
 - [x] Another way to plot 
 - [x] Adding curves to existing plots 
 - [x] Also, test out [waterfall](https://docs.mantidproject.org/nightly/plotting/WaterfallPlotsHelp.html#waterfall-plots) and [tiled]( https://docs.mantidproject.org/nightly/plotting/1DPlotsHelp.html#tiled-plots)
 - [x] Check Toolbar buttons

* 2D plotting: [instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/04_displaying_2D_data.html#displaying-2d-data)
 - [x] Plot all spectra 
 - [x] Change colour map 
 - [x] [Contour plot](https://docs.mantidproject.org/nightly/plotting/ColorfillPlotsHelp.html#contour-plots) (under 3D menu) 
 - [x] Check Toolbar buttons

* [3D plotting](https://docs.mantidproject.org/nightly/plotting/3DPlotsHelp.html):
 - Load some data eg `LOQ7041` from the ISIS sample data
 - [x] 3D surface
 - [x] 3D wire frame  
 - [x] Check Toolbar buttons

 ## Sliceviewer
 - [x] Overly long instructions (don't spend  long!) and data [here](https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html). In particular try editing the data in a workspace while it is open in Sliceviewer!

**Comment by darominski** [comment]
In the sliceviewer:
1. When the lineplots are toggled, toggling the grid has no effect.
2. Saving a Y cut is not possible for an `EventWorkspace`, e.g. `CNCS_7860`, which is not mentioned in the example as expected behaviour. There are no issues saving the X cut, or both cuts for a `MatrixWorkspace` such as using `MAR11060`.

**Comment by thomashampson** [comment]
The sliceviewer grid toggling issue is a regression since 6.3 and is present on Windows too.

**Comment by DanielMurphy22** [comment]
Raised the issue here: https://github.com/mantidproject/mantid/issues/34083

Please close this testing issue if there are no other problems!
