### ISSUE TITLE
Zoom on plot on MacOS shows box in wrong place

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34079]
Found in Smoke testing: https://github.com/mantidproject/mantid/issues/34059#issuecomment-1154934444

**Describe the bug**
The zoom box is a little up and left of where I'm zooming.

**To Reproduce**
Download release candidate
open a plot of any data
click the zoom tool in the toolbar and drag a box
is it in the correct place?

**Screenshots**
![Screenshot 2022-06-14 at 10 15 51](https://user-images.githubusercontent.com/55980573/173542720-a22681fe-732f-4bc7-82e8-10bc07da885c.png)

**Platform/Version (please complete the following information):**
 - OS: MacOS
 - OS Version: Monteray
 - Mantid Version6.4 release candidate

**Additional context**
Only happens on a connected second screen!

**Comment by DanielMurphy22** [comment]
Found again in manual testing for release 6.6

**Comment by martyngigg** [comment]
I won't get time for this I'm afraid.

**Comment by DanielMurphy22** [comment]
We should check if this is the case in standalone matplotlib outside of workbench

**Comment by martyngigg** [comment]
Just for the record that while we discussing this we found that we are overriding the zoom rectangle behaviour in https://github.com/mantidproject/mantid/blob/main/qt/applications/workbench/workbench/plotting/mantidfigurecanvas.py#L19
