### ISSUE TITLE
ALF View is not loading data

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34085]
ALF view is not loading the data into the GUI correctly. The calculation looks correct and the data looks the same when opened for the ADS

The GUI should show something similar to (just look for the correct colour plot I am not sure the number is correct as it doesnt match instrument view)

![image](https://user-images.githubusercontent.com/25006392/173560057-86440797-89c4-4560-8795-aef3cfced118.png)

Open ALF view
Enter 80510, press enter
The instrument image should update - but it doesnt

To get it to work you need to press the "reset" button on the d-spacing. We should automatically do it when data is loaded https://github.com/mantidproject/mantid/blob/main/qt/widgets/instrumentview/src/BaseCustomInstrumentPresenter.cpp#L50

**Comment by martyngigg** [comment]
Fixed by #34095
