### ISSUE TITLE
Add calibration to reflectometry GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34111]
As part of the work to support 2D detectors, the ability to apply a calibration to data when performing a batch reduction is required in the ISIS reflectometry GUI. This will probably require a way to specify the calibration file in the GUI (although we should consider whether this might be better elsewhere, e.g. the parameters file or similar depending on how frequently it changes). Once this input is added to the GUI it will just need passing through to the workflow algorithm ReflectometryISISLoadAndProcess for batch processing, or the preprocessing algorithm ReflectometryISISPreprocess for Preview Tab processing.

**Comment by rbauststfc** [comment]
I think we will also need to pass the calibration file input value to `ReflectometryReductionOneLiveData`?

**Comment by rbauststfc** [comment]
Yes, I've added it to the list of child properties in the algorithm in PR #34706. So for this issue I think it would just be making sure that the calibration file path is being passed in to `ReflectometryReductionOneLiveData` from the GUI.
