### ISSUE TITLE
Latex math fails to render in user documentation

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34118]
**Describe the bug**
The user documentation in mantid fails to render latex maths expressions and you get a large latex warning box instead. It's ok on the online docs; this is just inside mantid.

**To Reproduce**
- Open the ISIS Reflectometry interface and click the question mark icon to open the help.
- Click the Viewing Results section in the contents
- There is a large orange box showing a latex warning

![image](https://user-images.githubusercontent.com/12895056/174282512-9226ba3b-38e1-4bee-a082-f4979d9b9e67.png)

**Expected behavior**
It should render microseconds correctly as per the online docs:

![image](https://user-images.githubusercontent.com/12895056/174282639-3df3d937-3cc9-493b-83a1-697f00b8a27f.png)

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Seems to happen on all conda linux packages
 - OS Version:
 - Mantid Version 6.4.0

**Additional context**
The full warning text is:
```
System Message: WARNING/2 (\mu s)

latex exited with error [stdout] This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013) restricted \write18 enabled. entering extended mode (./math.tex LaTeX2e <2011/06/27> Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo aded. (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls Document Class: article 2007/10/19 v1.4h Standard LaTeX document class (/usr/share/texlive/texmf-dist/tex/latex/base/size12.clo)) (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty (/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def (/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu) (/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu) (/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu))) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty For additional information on amsmath, use the `?' option. (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) ! LaTeX Error: File `anyfontsize.sty' not found. Type X to quit or <RETURN> to proceed, or enter new name. (Default extension: sty) Enter file name: ! Emergency stop. <read *> l.8 \usepackage {bm}^^M No pages of output. Transcript written on math.log.
```

**Comment by martyngigg** [comment]
This appears to work on some machines so it's not a code issue but a setup of the builder so bumped to next sprint.
