### ISSUE TITLE
CaChannel import fails on idaaas

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34126]
**Original reporter:** Max at ISIS

Description
---

The ISIS reflectometry GUI has live data functionality that relies on the CaChannel library. The import currently fails on idaaas reflectometry instances with the default installed CaChannel version.

To Reproduce
---

- Run `import CaChannel` in a script or the python interpreter.
- You get this error:

```
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)  File "/home/gg1082848/Desktop/cachannel.py", line 1, in <module>    # import mantid algorithms, numpy and matplotlib  File "/usr/local/lib/python3.6/site-packages/CaChannel/__init__.py", line 3, in <module>    from .CaChannel import CaChannel, CaChannelException  File "/usr/local/lib/python3.6/site-packages/CaChannel/CaChannel.py", line 18, in <module>    from . import ca  File "/usr/local/lib/python3.6/site-packages/CaChannel/ca.py", line 13, in <module>    from caffi.ca import *  File "/usr/local/lib/python3.6/site-packages/caffi/__init__.py", line 3, in <module>    from . import ca  File "/usr/local/lib/python3.6/site-packages/caffi/ca.py", line 146, in <module>    @ffi.callback('void(*)(struct exception_handler_args)')  File "/usr/local/lib64/python3.6/site-packages/cffi/api.py", line 397, in callback_decorator_wrap    error, onerror)
```

Note that the following environment variable needs to be set for CaChannel to work on IDAaaS. We should get the IDAaaS team to set this up by default on the reflectometry instruments. In the meantime it can be tested by setting this in a terminal and starting Mantid from the terminal: 
```
export EPICS_CA_ADDR_LIST=’127.255.255.255 130.246.39.152:5066’ 
```

Note that you will get a timeout if the instrument is not currently running so it is best to test this during cycle. However, the import should still work so we can still test this.

Additional context
---
I think it is a clash with the `ffi.h` file in our conda environment. It works fine running from python directly, e.g.:
```
python3 
>> from CaChannel.util import caget 
>> caget(‘IN:OFFSPEC:CS:SB:Theta’) 
```

I am hoping we can fix this by including cachannel in our dependencies. There is a conda package available from the [paulscherrerinstitute](https://anaconda.org/paulscherrerinstitute/cachannel) channel. It can probably then be removed from IDAaaS (we should at least let them know it is no longer a requirement for us).

**Comment by martyngigg** [comment]
Changes are currently up on ral-facilities/daaas-ansible-workspace#755.

**Comment by DanielMurphy22** [comment]
Can this be closed?

**Comment by gemmaguest** [comment]
Max says live data is still not working for him but I'm not sure why. I'll add a new issue for that but link back to this in case it's related.
