### ISSUE TITLE
Option to auto-save row outputs as well as group outputs

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34130]
In the ISIS reflectometry GUI, there is an option to `Save as ASCII on completion` on the Save ASCII tab. This saves the main output for a group on the Runs tab after processing. This is either:
- the reduced row output, if the group contains a single row
- the stitched group output, if the group contains multiple rows

For the latter, users would also like the option to auto-save the individual row outputs, as well as the group outputs. This could be done via an additional check box on the Save ASCII tab. It should be disabled by default. I think we would simply need to loop through the child rows of the group and output each row's output workspace as well as the group's output.

**Comment by rbauststfc** [comment]
@gemmaguest when the new checkbox is selected that only has an effect if auto-save has also been selected. Would we like to have some extra logic to disable/grey out the new checkbox when auto-save is de-selected, to make the relationship between the two clear? Or do you think that's not needed?
