### ISSUE TITLE
Indirect Data Anaylsis crash when removing all data

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#34176]
**Original reporter:** ISIS/Hamish Cavaye

**Describe the bug**
Selecting all data (e.g. by ctrl+a) and clicking "Remove" in any of the Fit tabs of the Indirect Data Analysis interface will crash Mantid.

**To Reproduce**
1. Open the Indirect Data Anaylsis interface (Interfaces->Indirect->Data Analysis)
2. Go to e.g. the ConvFit tab
3. Click Add Workspace and load some data (I loaded irs26173_graphite002_red.nxs and irs26173_graphite002_res.nxs from the "usage data") and tick the "All Spectra" box, then click "Add", and close the data selection dialog.
4. Click somewhere in the Data Input widget and select all data with `ctrl+a`
5. Click the "Remove" button. This will cause Mantid to crash

**Expected behavior**
Data should be removed without Mantid crashing

**Platform/Version (please complete the following information):**
 - OS: Tested on Windows 10
 - Mantid Version 6.4.0

**Comment by sf1919** [comment]
Sounds a lot like #32848 (which went stale).
