### ISSUE TITLE
Indirect spectrum numbers are not right

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34183]
Use the indirect data reduction GUI
- Type run 96141
- in the detector grouping section, set the value to "groups" and then 5 (edited) 
- press run
- in the ADS right click and select "show detectors"
- The first row will have 0 for both the index and spectrum number. Version 3.11 will have 0 and 1 respectively.

This change is to revert the behaviour back to be the same as 3.11

https://github.com/mantidproject/mantid/commit/8e51384989d6d14b54353c8e29950ecbd9c37904

**Comment by AnthonyLim23** [comment]
Spencer has said "My simple solution to all this would be when creating the ws set spectrumNo = index+1"

**Comment by SpencerHowells** [comment]
Should start at 1

**Comment by sf1919** [comment]
@AnthonyLim23 I think there are some instructions missing - which GUI is this for?

**Comment by AnthonyLim23** [comment]
indirect reduction

**Comment by sf1919** [comment]
It's not just the spectrum numbers that are wrong. For some reason we have 6 groups and the final dectector number in the final group is 53 not 52. I think a bit more digging is required to see how it ended up like this.

v3.11 

![Screenshot (198)](https://user-images.githubusercontent.com/55837273/177559591-caca1a74-68de-402c-96e7-21f58fb583d7.png)


v6.4
![Screenshot (199)](https://user-images.githubusercontent.com/55837273/177559602-f7a3a69b-38af-44b8-a228-6199af303bc7.png)
