### ISSUE TITLE
Add support for the 2nd order Placzek correction term to POLARIS total scattering

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34196]
The POLARIS total scattering data reduction workflow currently calls the CalculatePlaczekSelfScattering algorithm. Version 2 of this algorithm has been created by the ORNL team and this includes a more accurate calculation of the Placzek correction because it includes the ability to calculate a first and second order term whereas v1 only calculates the first order term. The user is able to specify whether to include the second order term via an "Order" parameter on the algorithm.

This task is to switch the POLARIS total scattering workflow over to using the v2 algorithm and add the ability to specify how many terms to use in the calculation and to see what difference it makes to the results.

Just switching from v1 to v2 while only including the first order term shouldn't make any difference to the results

**Comment by sf1919** [comment]
Blocked by #34193
