### ISSUE TITLE
Add Texture to EngDiff GSASII tab

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34268]
**Describe the solution you'd like**
The new Engineering Diffraction GSASII tab will not initially be able to handle texture analysis. This is a feature which should be added in release 6.6. This may be a simple task as the interface can already handle files with multiple spectra / multiple instrument files. My current thoughts on this task:
- Consider how to load multiple .gss / .prm files (or have all texture regions encompassed in one .gss and one .prm file)
- Use texture as the calibration grouping to decide how to save output. Currently the focus tab uses this to decide whether to save in both the save location and the rb number directory or just the rb directory.
- Plotting should be rather simple, I suspect this will work as currently designed so spectrum number 1 will be plotted with it's refinement curves and then there is a combobox to change to another region / spectrum
- Worth discussing all this with saurabh, I have a note that Richard thought the user may wish to define fitting range limits in dSpacing (or multiple of dmin) rather than TOF, but this may not be required.
- Also check with Saurabh if "Sequential" fitting (not really sequential but using the results of the fit of the first spectrum as input for all the other spectra) should be used for texture?

**Describe alternatives you've considered**

**Additional context**

**Comment by RichardWaiteSTFC** [comment]
Closing as texture analysis is now to be done outside mantid - not using GSAS-II
