### ISSUE TITLE
Upgrade conda to require qt 5.15

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#34265]
**Describe the outcome that is desired.**
By the end of this work the codebase should be able to run with Qt 5.15. This should hopefully solve #34081 without us needing to change our code.

**Describe any solutions you are considering**
Update the developer and package conda-recipes to require Qt 5.15 as a minimum. 

**Additional context**
5.15 is the final Qt 5 release. It is in support mode and still receiving bugfixes. We cannot yet move to Qt 6 until conda-forge make it available.

**Comment by robertapplin** [comment]
Upgrading our Qt version should also fix some of the unreliable test failures on the `model_fitting_view_test`, `tf_asymmetry_fitting_view_test`, `general_fitting_view_test` and `basic_fitting_view_test`.

https://sequana.readthedocs.io/en/master/faqs.html#qt-version
https://github.com/GNS3/gns3-gui/issues/2819
