### ISSUE TITLE
New/updated reduction for Si analyser OSIRIS data

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34301]
the new analyser will improve the time resolution from ps to ns. So we will need some new reduction. It is currently unclear if that is an update/extension to the current one or a new reduction.

**Comment by SpencerHowells** [comment]
@AnthonyLim23 The reduction works in energy ie meV. Does this refer to the time-of-flight input and just a question of units?

**Comment by AnthonyLim23** [comment]
My understanding is that its the time of flight

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Si analyser](https://trello.com/c/SDoLkxFa/29-si-analyser)

**Comment by AnthonyLim23** [comment]
This needs us to update the algorithm, IPF and IDF

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update algorithm](https://trello.com/c/8SlMq3P5/11-update-algorithm)
