### ISSUE TITLE
New fit functions for OSIRIS Si analyser

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34303]
This may involve creating new fit functions or just adding some that we already have to the analysis GUI

**Comment by SpencerHowells** [comment]
@AnthonyLim23 Why do we need new fit functions? That's science! Only need to lokk at whether a res workspace can be used. This requires the resolution to be nearly constant with angle.

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Si analyser](https://trello.com/c/SDoLkxFa/29-si-analyser)
