### ISSUE TITLE
Add Empty Container scaling for OSIRIS

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34309]
The new OSIRIS Scripts contain basic processing of data from the OSIRIS insruments #34257
This Issue is to add the abillity to scale the empty runs for correction by a value given by the user.

**Comment by SpencerHowells** [comment]
@Harrietbrown We already have the Interface Corrections>Subtract Container to scale both x & y. A proper container subtract should involve PaalmanPings absorption corrections which can also be done using Interface Corrections.

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add other corrections for OSIRIS Scripts](https://trello.com/c/Gaa1ZRb2/16-add-other-corrections-for-osiris-scripts)
