### ISSUE TITLE
Manual Testing Workbench

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34350]
You have been assigned manual testing. The hope is to catch as many problems with the code before release, so it would be great if you can take some time to give a serious test to your assigned area. Thank you!!

The general guide to manual testing:

* The tests must be performed on the installer versions of the final release candidate. Not on local compiled code.
* Serious errors involving loss of functionality, crashes etc. should be raised
as issues with the current release as a milestone and an email sent to the project manager immediately.
* Minor and cosmetic issues should be raised as issues against the forthcoming
releases.
* First try things that should work, then try to break Mantid, e.g. entering invalid values, unexpected characters etc.
* Don't spend more than a few hours on the testing as fatigue will kick in.
* If you find errors in the documentation, please correct them.
* Comment against this ticket the OS environment you are testing against.
* Close the this issue once you are done.

### Specific Notes:

https://developer.mantidproject.org/Testing/Core/Core.html

**Comment by Harrietbrown** [comment]
the directory for MantidPython is incorect for Linux and Ubuntu. we can not find it in these OS

**Comment by Harrietbrown** [comment]
generate a raged worksapce

```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
ws = CreateWorkspace([0,1,2,3,4,2, 3,4,5,6],[0,1,2,3,4,3,4,5,6,7], NSpec=2)
min = 1
max = 6
for j in range(0,2):
    x =[]
    y =[]
    data = ws.readY(j)
    k=0
    for v in ws.readX(j):
        if v >= min and v<=max:
            x.append(v)
            y.append(data[k])
        k+=1
    tmp = CreateWorkspace(x,y)
    ConjoinWorkspaces(ws, tmp, CheckOverlapping=False)
```
show data
select all the columns
right click and selecting copy causes an error

**Comment by Harrietbrown** [comment]
when showing data on a workspace right clicking on a column and selecting `copy bin to table.` causes an error.

**Comment by Harrietbrown** [comment]
on ubuntu 22 in the instrument viewer on the draw tab, select the `select tube/bank` option and choose ROI. if you click twice on two different tubes it crashes.

**Comment by DanielMurphy22** [comment]
All issues raised
