### ISSUE TITLE
Latex content not displaying in algorithm docs

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34371]
eg the documentation for DiscusMultipleScatteringCorrection shows several of the following types of error

![image](https://user-images.githubusercontent.com/56295817/190110051-225e50cc-f903-42c5-ac56-550a0310e61f.png)

This is on Windows. Daniel has checked on Mac and same problem there

**Comment by thomashampson** [comment]
I think this is the same as #34118, which should be resolved when we update our Linux builders with new docker images.

**Comment by martyngigg** [comment]
I can confirm this works on the latest nightly on macOS. Could someone check Windows?

**Comment by DannyHindson** [comment]
I've got the nightly with label 6.4.20220920.0829 installed on Windows (which I think is the latest one) and the latex in the docs is displaying fine now

**Comment by martyngigg** [comment]
Excellent. I'm going to close this one as I think it was a machine problem.
