### ISSUE TITLE
Docs Updates

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34377]
~~https://github.com/mantidproject/mantid/issues/34359#issuecomment-1245442421
https://github.com/mantidproject/mantid/issues/34359#issuecomment-1245498654~~

**Comment by DanielMurphy22** [comment]
https://github.com/mantidproject/mantid/issues/34357#issuecomment-1248311915

**Comment by DanielMurphy22** [comment]
https://github.com/mantidproject/mantid/issues/34533#issuecomment-1280666930

**Comment by DanielMurphy22** [comment]
https://github.com/mantidproject/mantid/issues/34516#issuecomment-1280617951

**Comment by DanielMurphy22** [comment]
https://github.com/mantidproject/mantid/issues/34537#issuecomment-1280608573

**Comment by DanielMurphy22** [comment]
To install mantidworkbench via conda must add conda-forge to channels. Should add to smoke testing instructions https://github.com/mantidproject/mantid/issues/34528#issuecomment-1280603760

**Comment by DanielMurphy22** [comment]
Some of these updates dealt with here: https://github.com/mantidproject/documents/pull/106

The only outstanding docs update for QA is should the Redhat and Ubuntu Smoke testing be merged as they are catered by the same installer now? @martyngigg

**Comment by martyngigg** [comment]
> The only outstanding docs update for QA is should the Redhat and Ubuntu Smoke testing be merged as they are catered by the same installer now? @martyngigg

Yes if we could merge those and just label it Linux from now on as it will cover both of those flavours.
