### ISSUE TITLE
Help interface does not function on Ubuntu 22

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34380]
During mannual testing it was found that in Ubuntu 22.04 the help interface is empty. We also recived an internal error attempting to open it to the release notes from the welcome page.
![image](https://user-images.githubusercontent.com/49688535/190365713-2390f70a-04aa-4af8-bda0-5294e7fe7037.png)

**To Reproduce**
1. either from a clean install welcome page or go to `help->About Mantid Workbench`
2. open the release notes

**Platform/Version:**
 - OS: Ubuntu
 - OS Version: 22.04

**Comment by DanielMurphy22** [comment]
As this is not a problem on Ubuntu 18.04, which isn't yet a supported OS, I think it should not be fixed urgently for this release.

**Comment by AndreiSavici** [comment]
I was able to build (and use) the documentation on Ubuntu 22.04. I had to install `python3-sphinxcontrib.qthelp`. Note that I'm not using the conda development environment.

**Comment by jclarkeSTFC** [comment]
The help is now working with 6.8 on Ubuntu 22.04
