### ISSUE TITLE
Two rebin algorithms

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#34385]
**Describe the bug**
The algorithm list inlcudes a lower case rebin v1 as well as the Rebin v1 ( they open the same dialog). There is also a lower case "load" algorithm and upper case "Load". We should investigate why this is happening

![image](https://user-images.githubusercontent.com/40830825/190429914-7786babc-c184-4788-893c-8b369ba79c93.png)

**Platform/Version (please complete the following information):**
All - definitely ubuntu and mac

**Comment by jhaigh0** [comment]
Just as a note to self / the future. This is where they come from https://github.com/mantidproject/mantid/commit/3133d77f44a4e7824490d9ce25ebbbd67e2b482c
