### ISSUE TITLE
Indirect Manual test docs update

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34407]
The Indirect Manual Testing documentation needs to be updated as the unexpected Yunit found in the Elwin Eq2 is actually correct: https://github.com/mantidproject/mantid/issues/34348#issuecomment-1247875726

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Indirect manual test update](https://trello.com/c/oJ594J1R/17-indirect-manual-test-update)
