### ISSUE TITLE
Workspace history copy script does not import mantid.simpleapi

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34428]
When generating the history for a workspace and copying it to a script the script does not contain the import of `mantid.simpleapi` that the script will require to run. when importing the script into mantid it is less of an issue because the script editor will ask if you want to add it to the top, but ideally it should include the imports needed to run.

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [workspace history script missing import mantid.simpleapi](https://trello.com/c/R8KhhIs2/21-workspace-history-script-missing-import-mantidsimpleapi)

**Comment by MohamedAlmaki** [comment]
This is resolved in #34438 
right? @Harrietbrown

**Comment by Harrietbrown** [comment]
You are correct.
Fixed by #34438
