### ISSUE TITLE
Slow startup of mantidworkbench

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#34445]
This is observed on RHEL7

* Startup of mantidworkbenchnightly v6.4.0 - rpm - 10s
* Startup of mantidworkbenchnightly v6.4.20220920.0829 - central conda location owned by system account - 2m17s
* Startup of mantidworkbenchnightly v6.4.20220920.0829 - central conda location owned by system account as system account - 11s
* Startup of mantidworkbenchnightly v6.4.20220920.0829 - central conda location owned by system account after the system account has run it once 10s
* Startup of mantidworkbenchnightly v6.4.20220920.0829 - user conda location owned by user - 21s (subsequent is 14s)

It is very unclear what the difference is between these. I understand that there will be some difference between rpm and a conda install, but there isn't an obvious reason why it should be so different based on where the conda install is.
**To Reproduce**

For example
1. Get out a stopwatch
2. Fire up `mantidworkbench`

**Platform/Version (please complete the following information):**
 - OS: Observed on RHEL
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

[ORNL version of the issue](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/452)

**Comment by peterfpeterson** [comment]
Before and after starting workbench in conda, the only directory that changes is `/opt/anaconda/envs/<name>/var/cache/fontconfig` which gains a number of cache files.

**Comment by peterfpeterson** [comment]
To print out the modified time and name of everything in a subtree that has been modified in the last 12 hours (.5 days) use
```sh
find /opt/anaconda/envs/<name>/lib/python3.8/site-packages/ -type f -daystart -mtime -0.5 -printf "%Tm-%Td %TH:%TM %p\n"
```

**Comment by peterfpeterson** [comment]
Reinstalling the 2020-09-20 nightly build automatically happened this morning. Startups were slow again. Starting as the user that installed it, then looking for new files revealed 
```
find /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/ -type f -daystart -mtime -0.5 -printf "%Tm-%Td %TH:%TM %p\n"
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/numpy/__pycache__/__config__.cpython-38.pyc
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/scipy/__pycache__/__config__.cpython-38.pyc
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/mantid/kernel/__pycache__/packagesetup.cpython-38.pyc
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/mantidqt/dialogs/__pycache__/spectraselectordialog.cpython-38.pyc
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/mantidqt/utils/qt/__pycache__/__init__.cpython-38.pyc
09-28 15:25 /opt/anaconda/envs/mantid-dev/lib/python3.8/site-packages/mantidqt/widgets/embedded_find_replace_dialog/__pycache__/view.cpython-38.pyc
```
Starting as the installing user made it fast again.

**Comment by peterfpeterson** [comment]
The plot thikens.... after workbench is up, openning the File->settings dialog is slow... the first time

**Comment by peterfpeterson** [comment]
@AndreiSavici tracked the slow startup of settings to [this line in settings/plots/model.py](https://github.com/mantidproject/mantid/blob/main/qt/applications/workbench/workbench/widgets/settings/plots/model.py#L16) and verified it by setting the line to `font_list = []`.

**Comment by AndreiSavici** [comment]
Unfortunately, this seems also an issue that is node specific. On analysis node18 is slow, on node 19 is fast. 

It seems like the issue is with handling of fonts. In `mainwindow.py`, the first occurrence of `set_splash` is slow, in particular the `showMessage` function. If I commented that out, I run into slow issues in `fonts.py`, the line `fontdb = QFontDatabase()`

In addition to the matplotlib font issue above, this should point out to the cause of the issue

**Comment by peterfpeterson** [comment]
There is a "fix." Remove `~/.cach/fontconfig` and the GUI will start quickly. However, at ORNL with the shared filesystem for user home areas, this needs to be done each time you change nodes.

**Comment by AndreiSavici** [comment]
It seems like Qt had some issues with fonts. See https://bugreports.qt.io/browse/QTBUG-78064

**Comment by martyngigg** [comment]
I'm just leaving a paper trail for the future. As discussed on Slack the ORNL wrapper scripts will remove `~/.cache/fontconfig` on startup to alleviate this.

It is worth us doing the Qt 5.15 upgrade post release and seeing if this fixes the issue.
