### ISSUE TITLE
Show History dialog > Script to File does not add .py extension

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34451]
Found testing an algorithm history PR: https://github.com/mantidproject/mantid/pull/34438#pullrequestreview-1123623118

**Describe the bug**

Save Script As menu does not auto add .py extension when opened from Show History dialog > Script to File 

**To Reproduce**
- Open MantidWorkbench and run CreateSampleWorkspace
- Right-click on the workspace and select Show History
- click Script to File, then type in a filename (importantly I did not put .py in my filename, but the filetype is set to .py) and then click Save. 
- The file is saved without the .py extension so it cannot be searched for when trying to open a script in MantidWorkbench. 

**Expected behavior**
Currently If I use the main workbench File > Save Script As then it will successfully add the .py extension to the file for me. Script to file from the algorithm history should do the same

**Screenshots**
![Screenshot 2022-09-28 at 13 42 39](https://user-images.githubusercontent.com/55980573/192784399-e49173ae-ca99-4bd1-9f25-2aba64fec5c5.png)

**Platform/Version (please complete the following information):**
 - OS: Found on Ubuntu 18.04
 - Mantid Version before release 6.5

**Comment by DonaldChung-HK** [comment]
It is likely that this problem only occurs in Linux as `QFiledialog` will call up the native file dialog in Mac and windows which will add the extension based on filter selected.
