### ISSUE TITLE
Refactor Indirect getInstrumentDetail function to make it safer

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#34488]
**Describe the outcome that is desired.**
There is a widely used function in indirect data reduction called `getInstrumentDetail` which throws runtime_errors when validation fails, and these errors are often uncaught. This isn't very safe, and could be dealt with in a more safe manor.

**Describe any solutions you are considering**
I have considered using `std::optional` to return `std::nullopt` when an instrument detail cannot be found. This should then be handled from each location that calls `getInstrumentDetail`. We could then put one `try-except` claus around the validation method and display a message box before returning `std::nullopt`.

**Steps to reproduce**
`getInstrumentDetail` is used extensively in the Indirect Data Reduction interface to do things such as getting the instrument, analyser and reflection.

To understand the problem, it is easiest to grep for the instances of the `getInstrumentDetail` function and see where it is being called from. https://github.com/mantidproject/mantid/blob/6e9015ceec5ec5843291a72221438fce7919300d/qt/scientific_interfaces/Indirect/IndirectDataReductionTab.cpp#L96

**Comment by Harrietbrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Indirect getInstrumentDetail function to make it safer](https://trello.com/c/wH80agKL/28-refactor-indirect-getinstrumentdetail-function-to-make-it-safer)

**Comment by AnthonyLim23** [comment]
can we have some steps to reproduce this?
