### ISSUE TITLE
Remove the installation of CCache from the OSX and Linux images

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#34496]
**Description**
Remove the installation of CCache from the OSX and Linux images as it is no longer needed.

CCache is now installed via the conda environment yaml files. This has been done in #34494.

Doing this makes it easier to update the version of CCache.

**Comment by robertapplin** [comment]
This is still relevant

**Comment by SilkeSchomann** [comment]
This as been done for the Centos7Slim image (https://github.com/mantidproject/dockerfiles/pull/82).

**Comment by ConorMFinn** [comment]
I don't think OSX has an Image as such, so I think this issue can be closed by mantidproject/dockerfiles#82
