### ISSUE TITLE
Mean algorithm doesn't check input parameters

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#34545]
**Describe the bug**
When running the Mean algorithm from a dialog, if you enter information incorrectly in the input workspaces box it will crash Mantid.

**To Reproduce**
1. No need to load any data
2. Open the Mean algorithm dialog from the algorithm widget
3. Enter something silly in the Workspaces edit box (anything that isn't a currently loaded workspace will do)
4. Enter something in the OutputWorkspace box
Mantid will crash

**Expected behavior**
Input parameters should be checked before attempting to run the algorithm

**Platform/Version (please complete the following information):**
 - OS: found on IDAaaS (not tested yet on Windows)
 - OS Version:
 - Mantid Version: 6.5.0-rc, 6.4.0, not tested on anything earlier

**Comment by sf1919** [comment]
Related to #34476 ?

**Comment by jhaigh0** [comment]
> Related to #34476 ?

Yes, the workspace names aren't validated in `Mean.validateInputs()` before calling `mtd[name]`. `MeanTest.py` shows the current expect behaviour is a run-time error.
