### ISSUE TITLE
Add right click menu item to workbench show sample shape

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34563]
Reported by Spencer et al.

Make matplotlib sample shape plotting available via a simple menu item (Eg right click menu on a workspace) without requiring user to copy and paste python code into a script window

**Comment by DanielMurphy22** [comment]
Possibly beyond the scope of this, but should the plot update if the underlying sample shape is updated? e.g. from a future call to RotateSampleShape https://github.com/mantidproject/mantid/issues/34565 ?

**Comment by DannyHindson** [comment]
> Possibly beyond the scope of this, but should the plot update if the underlying sample shape is updated? e.g. from a future call to RotateSampleShape #34565 ?

Yes this be a good feature - probably a "nice to have" if it's difficult to achieve. It would support the iterative alignment we discussed earlier where someone is visually aligning a sample by rotating it several times.
