### ISSUE TITLE
Investigate ability to arbitrarily rotate mesh sample shapes

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34565]
For WISH single crystal sample initial orientation

**Comment by RichardWaiteSTFC** [comment]
As a user I need to be able to define the initial orientation of the sample wrt the beam and instrument - the sample shape will then be rotated by the goniometer before being used in the calculation of various attenuation corrections.

This issue would be to make a new algorithm called something like `RotateSampleShape` - it would change the orientation of a sample on a workspace and would have to work for CSG shapes (e.g. cylinders, flat plates etc.) and mesh files.

The user can then visualise the shape to ensure they are happy with it by right-clicking on the workspace >  Show Sample Shape

**Comment by RichardWaiteSTFC** [comment]
`RotateSampleShape` would probably use the same syntax as `SetGonometer` to define the rotations to apply to the shape

**Comment by RichardWaiteSTFC** [comment]
In `SetSample` it already rotates a sample CSG shape by the rotation matrix if the goniometer matrix - `RotateSampleShape` would essentially change the rotation matrix applied

**Comment by RichardWaiteSTFC** [comment]
Here is some code to demonstrate the workflow and a shape being rotated by the goniometer
```
ws = CreateSampleWorkspace()
SetGoniometer(Workspace=ws, Axis0="45,1,1,0,1")
SetSample(ws,
          Geometry={'Shape': 'Cylinder', 'Height': 4.0,
                    'Radius': 1.0,
                    'Center': [0.,0.,0.]},
          Material={'ChemicalFormula': '(Li7)2-C-H4-N-Cl6',
                    'NumberDensity': 0.1})
# would call RotateSampleShape here!

print(ws.sample().getShape().getShapeXML()) # search for <goniometer in this string
# <type name="userShape"> <cylinder id="sample-shape"> <centre-of-bottom-base x="0" y="-0.02" z="0"/> <axis x="0" y="1" z="0"/><height val="0.04"/> <radius val="0.01"/></cylinder> <goniometer a11="0.853553" a12="0.146447" a13="0.500000" a21="0.146447" a22="0.853553" a23="-0.500000" a31="-0.500000" a32="0.500000" a33="0.707107"/> </type>
```
![image](https://github.com/user-attachments/assets/fdeafef1-0f4b-4851-9898-3abd0af71501)
