### ISSUE TITLE
Issues with recent Sphinx versions (above 5.1.1)

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#34584]
**Describe the bug**
- Saving/referencing math images files in the wrong place
- Website search

**To Reproduce**
Remove the 5.1.1 sphinx pin and build the docs package (5.3.2 is definitely not working).

**Expected behavior**
- Latex math should render correctly in our documentaion
- Search should work on our websites

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by sf1919** [comment]
Waiting for v6 of Sphinx to be released before trying to remove the pin - https://www.sphinx-doc.org/en/master/changes.html

**Comment by sf1919** [comment]
Looks like the earliest v6 will be released is 01/12/22 - https://github.com/sphinx-doc/sphinx/issues/10920

**Comment by sf1919** [comment]
Requires pygments to be `>=2.12`, but this can only be achieved if cppcheck is v2.8 or higher.

**Comment by sf1919** [comment]
Blocked by https://github.com/mantidproject/mantid/issues/33510
