### ISSUE TITLE
Remove redundant Code for Old OS/Package Management Support  

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#34586]
**Describe the outcome that is desired.**
Cleaner CMake without baggage of support for RHEL7/Ubuntu 18.04 now they have been dropped

**Describe any solutions you are considering**

At a minimum this should cover:
- [ ] Remove Windows ThirdParty CMake links
- [ ] Remove RHEL7 packaging rules
- [ ] Check with ILL if they still use the debian packaging in the Singularity images
- [x] Remove pre-conda build scripts for Jenkins

**Comment by sf1919** [comment]
@quantumsteve and @peterfpeterson - how far does #37156 resolve this issue?

**Comment by peterfpeterson** [comment]
#37156 is actually part of the cleanup that wasn't mentioned on the list. It is towards the same goal though.

**Comment by thomashampson** [comment]
I think this is already all cleaned up
