### ISSUE TITLE
Show ROIs as ranges rather than lists

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34606]
On the ISIS Reflectometry interface Preview tab, when you apply the selected instrument viewer ROI to the Experiment settings, each individual selected detector gets listed in the table, creating a very long string. We should consolidate contiguous ranges of detectors into a grouping pattern string instead, e.g. `1-5, 10-12` instead of `1,2,3,4,5,10,11,12`. There may be some string utilities in Kernel or elsewhere we could use to help with this.

See also #34326

**To reproduce**
- Open the ISIS Reflectometry interface
- On the Preview tab, enter run `INTER45455_inst` and click Load (see this issue for the data: #31069)
- Select a region on the instrument viewer plot and click Apply
- Go to the Experiment tab and check the `ROI Detector IDs` field in the table - it lists every detector individually.

**Comment by ConorMFinn** [comment]
This appears to have been done by another PR, though I'm struggling to find which one it is. Any idea @gemmaguest?

**Comment by gemmaguest** [comment]
@ConorMFinn It works for the ROIs from sliceviewer but not for the detector IDs from instrument viewer, I think?

**Comment by ConorMFinn** [comment]
Ah! I see, forgot that section got put in as well. Thanks!
