### ISSUE TITLE
Edit axis ranges in SliceViewer

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#34608]
**Is your feature request related to a problem? Please describe.**
Unable to precisely specify axis limits directly in SliceViewer.

**Describe the solution you'd like**
An axis editor dialog where you can specify axis ranges, accessed via double clicking the axis similarly to the other plots.

**Comment by RichardWaiteSTFC** [comment]
When viewing MDEvent workspaces the user selects the number of bins across the extent of the axes - so when the user specifies the axes limits it should trigger a rebin event (I think `on_dimensions_changed` or similar)

**Comment by jhaigh0** [comment]
Hopefully can use the same code which controlls the region zoom tool.
