### ISSUE TITLE
Add option for negative reflection to indirect Symmetrize

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34633]
In the indirect Symmetrize tab we use the Symmetrize alg to reflect the positive range onto the negative, it has been requested that we implement a method so that instead we can reflect the negative onto the positive. 

A method to implement this is to run ScaleX multiplying by -1 and then SortXscale,

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Label for option in sample changer](https://trello.com/c/hdN0QZQY/16-label-for-option-in-sample-changer)

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Negative option for indirect symetrize](https://trello.com/c/1z6SEVVv/26-negative-option-for-indirect-symetrize)
