### ISSUE TITLE
Dockable widgets in Indirect Data analysis can not be put back vertically

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34637]
In the Indirecty Data Analysis fit tabs we utalise dockable widgets, there should be able to be put back where they were removed from. 
however if you remove the data selector (normaly stored above the other widgets) and try to place it back it will only go back next to the other widgets horizontally. this issue is to find a solution that will always allow for widgets to be replaced vertically.

**Comment by AnthonyLim23** [comment]
could this be an induction issue?

**Comment by Harrietbrown** [comment]
It could well be, so long as they have had the qt tutorial

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dockable widgets cannot be put back vertically](https://trello.com/c/hGxLoOPz/25-dockable-widgets-cannot-be-put-back-vertically)
