### ISSUE TITLE
Remove ResNorm

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34659]
The ResNorm algorithm uses the quasielasticbayes package. However, the module contains "licence software", so we should not use it. The ResNorm algorithm does have a version 2, and version 1 is unused. So this issue is to remove it 

https://github.com/mantidproject/mantid/blob/dfa6d374579bbae1fecabd9d469a0c182d14db70/Framework/PythonInterface/plugins/algorithms/ResNorm.py#L96

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove ResNorm](https://trello.com/c/w9cecp02/19-remove-resnorm)

**Comment by MohamedAlmaki** [comment]
I've removed the algorithm python file and its directory from CMakeLists.txt. Do I need to remove the IndirectImport and quasielasticbayes also?

**Comment by AnthonyLim23** [comment]
Those files are used elsewhere. You can check by using grep to see where the imports are used.
