### ISSUE TITLE
Move Indirect Data Manipulartion to Inelastic

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#34676]
The new Indirect Data Manipulation interface from#34656 is usable by both indirect and direct inelastic users. this issue is to move into its own `Inelastic` catagory and rename the files and docs appropriatly.

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/pull/34656/files#diff-b306a279ec176fd698bf2b17251183cdb6926a3b34c07eeffd4b2fadf775a452R1 will need updating
