### ISSUE TITLE
MPL 3.6 miscellaneous

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34699]
A few changes I made when I upgraded to MPL 3.6 locally. There may be a better code solution than what I've put here so do not blindly copy!

qt/python/mantidqt/mantidqt/widgets/codeeditor/completion.py
-    from matplotlib.cbook import MatplotlibDeprecationWarning
+   from matplotlib import MatplotlibDeprecationWarning

change `cm.cmap_d.keys()` to `cm._gen_cmap_registry().keys()` twice in qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py 
and once in Framework/PythonInterface/mantid/plots/utility.py

**Comment by jhaigh0** [comment]
yes I've changed that to `colormaps.keys()` which I think is what they want you to use now
