### ISSUE TITLE
Add fields to support sparse workspace features in Indirect, Corrections UI

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34716]
The "Calculate Monte Carlo Absorption" tab in the Indirect, Corrections UI calls the PaalmanPingsMonteCarloAbsorption algorithm to perform an absorption correction. This algorithm supports a sparse workspace feature which calculates the correction on a subset of the detectors on an instrument and then uses interpolation to return a result for the remaining detectors. This speeds up the calculation on instruments with a lot of detectors.

This change is to add the sparse workspace fields to the UI so the users can take advantage of this feature. The following screenshot of the algorithm dialog for PaalmanPingsMonteCarloAbsorption shows the required fields:

![image](https://user-images.githubusercontent.com/56295817/201308780-2a986835-fdfa-4e06-93f8-8ac483122471.png)

Requested by Spencer Howells

**Comment by AnthonyLim23** [comment]
this is a harder induction issue

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add fields to support workspace features in indirect corrections GUI](https://trello.com/c/slQulEzY/23-add-fields-to-support-workspace-features-in-indirect-corrections-gui)
