### ISSUE TITLE
Save Directory - Browse button should default to Last navigated save directrory

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3472]
This issue was originally [TRAC 2625](http://trac.mantidproject.org/mantid/ticket/2625)

From Dean Whittaker (d.whittaker@bath.ac.uk):

I suppose this is more a feature request. When saving a file (in my case an "include" file for detectors to turn into a map file) it always jumps to some default directory instead of the directory I was last in - obviously if I last saved a file in a directory, it is likely the next file I save will also go there.. Also, it can't follow shortcuts. Instead it tries to save over the top of them. Surely I should double click a shortcut and it'll take me to the relevant folder, not assume that I want to save my file as "merlin.lnk" (for example).

From Nick Draper:

Thanks for the feedback, I'm sure we can improve the automatically selected directory in when using the browse button.  Navigating through shortcuts may be more of a challenge as that is very much down to the underlying tools we are using to create the user interface, and I suspect we will get different behaviour on different operating systems.  We will take a look though, I've created a work ticket so a member of the development team to look into these issues for the next release.

In the mean time you can change the Default Save Directory (look under File->Manage Directories), that is the directory the browse button is defaulting to.

Suggestion:

We should default to the last navigated save directory first with the default save as a backup.  Don't save the last navigated directory between runs of Mantidplot.

**Comment by shahrozahmed1** [comment]
Seems to be already fixed as the browse button is navigating to the previous save directory

**Comment by FedeMPouzols** [comment]
This works well for me on debian and win7. It was definitely fixed elsewhere since the issue was first reported.
