### ISSUE TITLE
Remove obsolete reference to CaChannel documentation 

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34730]
As per the comment on this PR, there is some documentation about CaChannel referenced in a Mantid warning that has been moved. #34690

The instructions are now obsolete and I think the webpage is no longer necessary anyway because installation is as simple as `conda install -c paulscherrerinstitute cachannel`. The warning could simply inform the user of this installation method directly. 

This is only relevant to ISIS reflectometry and is not a problem on IDAaaS where CaChannel is pre-installed in the Mantid conda environment; however it will be hit by developers testing live data PRs, and potentially by users on Windows, although most reflectometry users now use IDAaaS.

**Comment by rbauststfc** [comment]
Resolved as part of #35049.
