### ISSUE TITLE
Memory increase when Cropping workspace

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#34735]
**Original reporter:**
Pascal Manuel

**Describe the bug**
There is possibly a memory leak when using the CropWorkspace algorithm. The memory usage goes up after the workspace is cropped, but if anything you'd expect it to go down.

**To Reproduce**
1. `Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767')`
2. Note the memory usage is 1.5 GB
3. Execute CropWorkspace with XMin=1000 and XMax=12000. Set the output name equal to the input name.
4. After it has run, note the memory usage is now 2.1 GB . Why has this gone up!
5. Delete the workspace and the memory usage returns to a normal level

**Expected behavior**
If anything, the memory usage should slightly decrease when cropping a workspace

**Platform/Version (please complete the following information):**
- Replicated in Mantid Version 6.5 on windows

**Comment by martyngigg** [comment]
Would it be easy to check if you do another operation, times the whole workspace by 2, causes the memory to drop?

Also, did this happen in 6.4?

**Comment by martyngigg** [comment]
> This happens on 6.5
> 
> Multiplying the cropped workspace by 2 does not cause the memory to drop. It stays at 2.1 GB

Ah interesting. This is slightly different to other behaviour we have observed. For the version I was hoping to understand if 6.4 showed this behaviour so we know if this is a regression or not. Would you be able to check?

**Comment by robertapplin** [comment]
> Ah interesting. This is slightly different to other behaviour we have observed. For the version I was hoping to understand if 6.4 showed this behaviour so we know if this is a regression or not. Would you be able to check?

The same behaviour is in 6.4. Also I tried deleting the workspace in 6.4 but the memory usage stays at 2.1 GB

**Comment by martyngigg** [comment]
> > Ah interesting. This is slightly different to other behaviour we have observed. For the version I was hoping to understand if 6.4 showed this behaviour so we know if this is a regression or not. Would you be able to check?
> 
> The same behaviour is in 6.4. Also I tried deleting the workspace in 6.4 but the memory usage stays at 2.1 GB
>
> Loading the workspace again then puts the memory up to 3.4 GB, and cropping the workspace will put it up to 4.0 GB
> 
> There is no change in memory usage when multiplying the workspace by 2

Ok. So we have at least fixed the deletion issue but something is obviously lingering around.

**Comment by jhaigh0** [comment]
Using the vs diagnostic tool I've narrowed the increase from the original issue down to the function `ExtractSpectra::execHistogram()`
```
void ExtractSpectra::execHistogram() {
  auto size = static_cast<int>(m_inputWorkspace->getNumberHistograms());
  Progress prog(this, 0.0, 1.0, size);
  for (int i = 0; i < size; ++i) {
    if (m_commonBoundaries) {
      m_inputWorkspace->setHistogram(i, slice(m_inputWorkspace->histogram(i), m_minX, m_maxX - m_histogram));
    } else {
      this->cropRagged(*m_inputWorkspace, i);
    }
    propagateBinMasking(*m_inputWorkspace, i);
    prog.report();
  }
}
```
The increase happens gradually, so I would guess it's either `m_inputWorkspace->setHistogram` or `propagateBinMasking` that's causing the increase. `size` is about 45000 which means each of the iterations is causing an increase of about (2.1-1.5) / 45000 ~= 0.000013 GB = 13 KB
![image](https://user-images.githubusercontent.com/35813666/211590784-74f6e59b-1b8d-4ef3-9297-a3eabc53ea20.png)

**Comment by jhaigh0** [comment]
Comparing heap snapshots at the beginning and end of that function looks like this
![image](https://user-images.githubusercontent.com/35813666/212664801-409c62c0-49b4-4536-9470-6cdeb64a7a6e.png)
So an increase in the number of X Histograms, interestingly.

I think it will be something happening in `slice()`

**Comment by jhaigh0** [comment]
Okay, think I've got something...

Looking at `SXD23767.raw` itself, every X histogram has identical data. So what I think is happening is that all the X histograms are pointing to one place in memory but when `slice()` is run it is copying a slice of the histogram into 45,104 new histograms, duplicating lots of data.

Happening on line 26 of `Slice.cpp`
```
auto xEnd = histogram.xMode() == Histogram::XMode::Points ? end : end + 1;
sliced.mutableX().assign(histogram.x().begin() + begin, histogram.x().begin() + xEnd);
```

In a debugging session, I added in `auto x = histogram.x()` to `slice()` and checked the memory address over two consecutive calls (they appear to be the same)
```
&x
0x000000868f18bdb8 {...}
    Mantid::HistogramData::detail::FixedLengthVector<Mantid::HistogramData::HistogramX>: {m_data={ size=1587 } }
    Mantid::HistogramData::detail::Offsetable<Mantid::HistogramData::HistogramX>: {...}
    Mantid::HistogramData::detail::Scalable<Mantid::HistogramData::HistogramX>: {...}
&x
0x000000868f18bdb8 {...}
    Mantid::HistogramData::detail::FixedLengthVector<Mantid::HistogramData::HistogramX>: {m_data={ size=1587 } }
    Mantid::HistogramData::detail::Offsetable<Mantid::HistogramData::HistogramX>: {...}
    Mantid::HistogramData::detail::Scalable<Mantid::HistogramData::HistogramX>: {...}
```
