### ISSUE TITLE
EPIC: Improve stability of preview tab

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34745]
The ISIS Reflectometry insterface Preview tab has been a little unstable. We need to stress test it more with loading different types of data, doing lots of selections etc.

Known issues:

- [x] #34865
- [X] Crash when doing lots of selections and editing/deleting regions on the instrument viewer (not reproduced as yet)
   - This is fixed as part of #34865 
- [x] The `?` button on the regionselector does nothing https://github.com/mantidproject/mantid/pull/34918

**Comment by ConorMFinn** [comment]
All found issues fixed
