### ISSUE TITLE
Add extra suffix to PDF output workspace to contain PDF type

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#34750]
When generating multiple pdf's from a single focussed dataset (eg different pdf types) it would be useful if the output workspace didn't have the same name. At the moment I have to manually rename the output workspace to keep the different outputs.

So either of these would be useful (or both):
a) adding PDF type to the output workspace name
b) allow the call to create_total_scattering_pdf to take an output name parameter.

**Comment by RichardWaiteSTFC** [comment]
Think this relates to POLARIS scripts - I have the configs files, cal files etc.  here if it helps
[POLARISPowderDiffraction.zip](https://github.com/mantidproject/mantid/files/14361834/POLARISPowderDiffraction.zip)

I have a script (but it's not for producing PDFs sorry) - I would look at Danny's old PRs/issues for some scripts to test
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

from isis_powder import polaris, SampleDetails

config_file_path = r"C:\Users\xhg73778\Downloads\POLARISPowderDiffractionFolderSmall\polaris_config_example.yaml"
polaris = polaris.Polaris(config_file=config_file_path, user_name="test", mode="PDF")

sample_details = SampleDetails(height=4.0, radius=0.2985, center=[0, 0, 0], shape='cylinder')
sample_details.set_material(chemical_formula='Si', packing_fraction=0.6)
polaris.set_sample_details(sample=sample_details)

polaris.create_vanadium(first_cycle_run_no="125706", multiple_scattering=True, 
                         do_absorb_corrections=True, mayers_mult_scat_events=1)                  

polaris.focus(run_number="125754,125755", input_mode='Summed', do_absorb_corrections=False,
              do_van_normalisation=False, van_normalisation_method="Relative",
              keep_raw_workspace=False)  # input_mode='individual', input_mode='Summed'
```
