### ISSUE TITLE
C++ version of Meier

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#34798]
The Meier function is currently written in Python. It has had some problems due to the spin value only being able to take half integer values causing fits to behave erratically. Looking at the original code it would be better suited to C++ for performance. This has 2 main parts: 

- Rewrite the code to C++
- Change spin from being a parameter to an attribute

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [C++ version of Meier](https://trello.com/c/iROfzvyd/31-c-version-of-meier)

**Comment by MohamedAlmaki** [comment]
I just catch this bug when I was reimplementing the function, see [line 68](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/functions/Meier.py#L68).

**Comment by MohamedAlmaki** [comment]
I've implemented and refactored the function in C++. Also, changed the spin from a parameter to an attribute. But in I'm not sure how to implement the test_do_fit unit test in C++ (see [test](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/test/python/plugins/functions/MeierTest.py#L31)). There is no equivalent help function in C++ like in Python to do this unit test. Also, there is no C++ function that is tested using a fit unit test. Most unit tests in C++ are used to just test the input and output of the function.

**Comment by AnthonyLim23** [comment]
> I just catch this bug when I was reimplementing the function, see [line 68](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/functions/Meier.py#L68).

what bug was this?

**Comment by AnthonyLim23** [comment]
> I've implemented and refactored the function in C++. Also, changed the spin from a parameter to an attribute. But in I'm not sure how to implement the test_do_fit unit test in C++ (see [test](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/test/python/plugins/functions/MeierTest.py#L31)). There is no equivalent help function in C++ like in Python to do this unit test. Also, there is no C++ function that is tested using a fit unit test. Most unit tests in C++ are used to just test the input and output of the function.

For "simple" functions we can easily calculate what the result should be. So can test the function evaluation directly. For more difficult examples it can be difficult. However, in this case you probably want to check that the spin has not changed value.

Have you tried calling the fit algorithm in the test?

**Comment by MohamedAlmaki** [comment]
> > I just catch this bug when I was reimplementing the function, see [line 68](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/functions/Meier.py#L68).
> 
> what bug was this?

Sorry, I mean [line 64](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/functions/Meier.py#L64). It should be "append" not "apend"
