### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#34830]
**Describe the bug**

1. There is no build testing for bugs in usage examples (used to be the doctest on Ubuntu build)
2. The developer documentation does not describe how to build/run the doctests. https://developer.mantidproject.org/Standards/AlgorithmUsageExamples.html and https://developer.mantidproject.org/Standards/DocumentationGuideForDevs.html#documentationguidefordevs point to each other (circular reference)
3. There is no documented way to run a single usage test

**Comment by peterfpeterson** [comment]
[doctest documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html)
