### ISSUE TITLE
Superplot shrinks on some data

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#34876]
**Describe the bug**
It is possible to shrink the actual plot to have no width (see screenshot).
This doesn't happen for all data, but it does for: 
[ENGINX_305761_307521_bank_1_TOF_bgsub.zip](https://github.com/mantidproject/mantid/files/10267136/ENGINX_305761_307521_bank_1_TOF_bgsub.zip)

**To Reproduce**
Load in the data above, and right-click in the workspaces toolbox in the new workspace. Select Plot > Superplot. Now there are 2 ways to cause the bug:
- A) Keep ticking and unticking the "Normalise by max" checkbox 
- B) Select the workspace/curve in the table, click "Add" in the bottom right of the plot window. Back in the table click on either of the two workspace/curve entries and now use your up and down arrow keys to switch back and forth between them.

In both cases the plot starts to shrink to the right of the window. Maybe the left margin keeps increasing or tight layout keeps being re-applied.

**Expected behavior**
Plots take up most of the plot window and do not display this shrinking behaviour.

**Screenshots**
![Screenshot from 2022-12-20 09-45-04](https://user-images.githubusercontent.com/55980573/208635843-2a5c57df-642f-49d6-b6e6-058c02bfb0dd.png)

**Platform/Version (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mantid Version current main

**Comment by gui-co** [comment]
Thanks for the bug report, I will have a look.
