### ISSUE TITLE
Reflectometry GUI not working with Project Recovery

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#34965]
**Describe the bug**
When using Project Recovery during manual testing (see Test 4 in https://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html) the Reflectometry GUI is not recovered. This seems to be a regression as the testing documentation suggests Reflectometry and Engineering Diffraction are the only GUIs this works for and Engineering Diffraction is recovered.

**To Reproduce**
1. Follow test 4 instructions in https://developer.mantidproject.org/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.html 

**Expected behavior**
Reflectometry GUI should be recovered

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mantid Version [e.g. 6.0.0]: 6.5.20230115.2237

**Additional context**
Found during manual testing (#34957)

**Comment by rbauststfc** [comment]
After re-testing we found that the ISIS Reflectometry GUI was opened as expected on project recovery, it was just minimised so we hadn't noticed.
