### ISSUE TITLE
Opening a python script twice will open two tabs

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#34979]
**Describe the bug**

When you open a script in mantid that is already open in the editor, it will be opened in a new tab and not in the same tab.

**To Reproduce**
1- Open a script from some directory
2- The script will be opened in a new tab
3- Open the script again from the same directory
4- You will see a second tab is opened

**Expected behavior**
The script should be opened in the same tab.
**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10 Enterprise
 - Mantid Version: 6.6.20230115.2237

**Additional context**

**Comment by MohamedAlmaki** [comment]
@thomashampson @jhaigh0 
Do you think this issue is important?

**Comment by jhaigh0** [comment]
I think it could be a good induction issue to go with #33369

**Comment by thomashampson** [comment]
This would be a nice improvement
