### ISSUE TITLE
On the help "Algorithm Decriptions" interface there are two sections for F and P

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantid#34972]
On the help "Algorithm Descriptions" interface there are two sections for F and P. This corresponds to those sections spilling over from one column to another on the webpage (https://docs.mantidproject.org/v6.5.0/algorithms/categories/AlgorithmIndex.html), and thus in that instance requiring an additional heading.

**To Reproduce**
1) In workbench, use the `Help` dropdown menu to open the `Algorithm Descriptions` interface.
2) Under `General Algorithms` select `Algorithm Index`
3) Scroll down and observe that `F` and `P` are listed twice.

**Expected behaviour**
Ideally the second heading would be removed when viewed from inside workbench and the two sections combined.

**Comment by thomashampson** [comment]
We'll close this because it doesn't really cause any problems.
