### ISSUE TITLE
Add common commands to matrix workspaces in Python

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3498]
This issue was originally [TRAC 2651](http://trac.mantidproject.org/mantid/ticket/2651)

This could be implemented in:
1. PythonAPI\src\workspaceproxies.cpp
2. PythonAPI\MantidFramework.py

I suppose implementing it in C++ and exposing it is the best way.

The following options are uncontraversial (although only work on matrix workspaces):
1. Clone
2. Transpose
3. Rebin  (possibly also RebinToWorkspace, rebunch and regroup)
4. ConvertUnits
5. Crop
6. Save (SaveNexus)
7. Rename

These might be worth while:
1. Mask.Extract (ExtractMasking)
2. Mask.ApplyWS (Maskdetectors using a MaskedWorkspace)
3. Mask.Apply (Maskdetectors specified detectors or spectra)
4. Mask.ApplyBins (Maskbins)
5. Integrate
6. Sum (SumSpectra)
7. Merge (MergeRuns)
8. ReplaceSpeacialValues
9. SolidAngle
10. Scale

These I'm not too sure about:
1. Load (Overwriting existing data, not the best way)
2. Delete (it would be deleting itself and therefore rensering it's own handle invalid)

These would only work within Mantidplot (Martyn set's a magic flag):
1. Display (shows the matrix)
2. Plot (1D or colour map depending on  dimensionality)
3. DisplayInstrument
   We could make plot work standalone if MatplotLib was available.

The names I have suggested are just suggestions, have a think about the overall user experience.

**Comment by martyngigg** [comment]
This is very old and not something we plan to take forward.
