### ISSUE TITLE
Check for Algorithm and ParameterName conformance in alg registration

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3499]
This issue was originally [TRAC 2652](http://trac.mantidproject.org/mantid/ticket/2652)

Algorithm and Parameter Names should be PascalCase. Neither should contain spaces or underscores.

We should check that on algorithm registration, both for C++ and Python algorithms.  Non-Conformant algorithms should emit a warning log message, but still work as best they can.

This is probably best implemented in the API\AlgorithmManager class (as it creates an instance of each algorithm and is involved in registration)

**Comment by peterfpeterson** [comment]
There is already a system test which does this [CodeConventions](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Testing/SystemTests/tests/analysis/CodeConventions.py).

wontfix
