### ISSUE TITLE
Segfault algorithm does not crash Mantid on Mac

### ISSUE THREAD

**Issue by jhaigh0** [mantidproject/mantid#35008]
**Describe the bug**
@ConorMFinn and @martyngigg have experienced that the Segfault algorithm is not crashing Mantid on Mac. Instead, in a message to say the algorithm has completed successfully is printed in the console.

**To Reproduce**
*On MacOS*

 - Run the Segfault algorithm with Dry Run turned off

**Expected behavior**

- Mantid should crash after the algorithm has run

**Platform/Version (please complete the following information):**
 - OS: macOS
 - OS Version:
 - Mantid Version:

**Comment by martyngigg** [comment]
I found a simple fix but I think it can go on `main`.
