### ISSUE TITLE
Move the privacy policy from the archive page to the main docs.

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#35017]
The privacy policy, which is linked to on the About MantidWorkbench menu and on the error reporter, exists on the old archived webpages with screenshots from MantidPlot. This privacy policy should be moved to the main docs and have new screenshots.

_Originally posted by @DanielMurphy22 in https://github.com/mantidproject/mantid/issues/34945#issuecomment-1384073580_

**Comment by martyngigg** [comment]
I have an overarching docs clean up I've been doing where I've included this so I'll pick this up.

**Comment by DanielMurphy22** [comment]
Cool, tell us if you need any help with the docs cleanup!

**Comment by martyngigg** [comment]
Thanks. A review will be helpful. I think I should have something to open tomorrow.

**Comment by martyngigg** [comment]
I've opened #35049 that should clear up everything such that it's either current or points to archive.mantidproject.org if necessary.
