### ISSUE TITLE
Fake Live Data crash for incorrect path

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#35048]
https://github.com/mantidproject/mantid/issues/34954#issuecomment-1385697957

Found during [Manual Testing](https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html) so may not be affecting users.

**Describe the bug**
When the path to the fileeventdatalistener.filename property is wrong, and you try to select the ADARA_FileReader instrument in Load LiveData, MantidWorkbench crashes and closes

**To Reproduce**
Follow the live data testing section ADARA Fake Event
 and set the following lines in your Mantid.user.properties file.
```
fileeventdatalistener.filename=REF_L_32035_neutron_event.dat
fileeventdatalistener.chunks=300
```
If the file path is set incorrectly, such as just the filename or with "/home/username/Desktop/Data/REF_L_32035_neutron_event.dat" (rather than the correct "/Users/username/Desktop/Data/REF_L_32035_neutron_event.dat")...
When you try to Load > Live Data MantidWorkbench will crash and close
**Expected behavior**
It does not crash and offers a useful error message.

**Platform/Version (please complete the following information):**
 - OS: macOS Monterey
 - Mantid Version 6.6 manual testing nightly 15th Jan

**Comment by jhaigh0** [comment]
When I run the `LoadLiveData` algorithm I don't see ADARA_FileReader in the instrument list.
![image](https://user-images.githubusercontent.com/35813666/219359464-088535df-9fb9-425f-b1c2-2511283314e3.png)

Do I need to change to a different facility?

**Comment by DanielMurphy22** [comment]
Change your facility to `TEST_LIVE`. Sorry the instructions aren't great, it mentions this in the manual testing instructions.

**Comment by jhaigh0** [comment]
Still should be solved
