### ISSUE TITLE
LoadEMU

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#35118]
LoadEMU should not include the monitors. 

run the script below and check that the data does not include any monitors: 
```

ws = LoadEMU('EMU0006330.tar');

print("Number of spectra: {}".format(ws.getNumberHistograms()))
```

**Comment by AnthonyLim23** [comment]
Older versions of mantid has this algorithm causing a crash

**Comment by AnthonyLim23** [comment]
Im closing this as it is EMU at ORNL and not ISIS as I thought

**Comment by AndreiSavici** [comment]
@AnthonyLim23 EMU is at ANSTO, not at ORNL
