### ISSUE TITLE
Upgrade OpenSSL to 3.0.8

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#35194]
**Describe the outcome that is desired.**
All versions of OpenSSL v1.1.1 are being deprecated in September 2023. We need to move to a newer version of OpenSSL that is supported - v3.0.8 potentially.

**Additional context**
This may need considerable work to make code base compatible with upgraded version of OpenSSL

**Comment by MialLewis** [comment]
To note, it looks as if it's our `qt` pin which is preventing us from upgrading to `3.0.8`.

**Comment by sf1919** [comment]
Once this work has been completed the version of OpenSSL that we use in our Linux docker containers will also need to be upgraded - https://github.com/mantidproject/dockerfiles/issues/70

**Comment by sf1919** [comment]
Full details of EOL - https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
