### ISSUE TITLE
Issue displaying plot in Mantid Basic Course

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#35214]
The plot underneath this paragraph doesn't appear in the published version of the Mantid basic course: https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/connecting_data_to_instruments/06_sample_logs.html#algorithms 

The page just  incorrectly displays (Source Code). However, when the docs are built locally (with the `DOCS_PLOTDIRECTIVE` CMake option turned on) the plot does seem to appear:

![Plots](https://user-images.githubusercontent.com/38210467/219018592-d84d5219-c8b4-4efe-8f23-36bda040c0e7.PNG)

I've only tested this on a local Windows build. We should investigate why this plot isn't being generated in the published version of the docs.

Note that the explanation for the 0 relative time start in the paragraph above the plot is confusing, so this should be clarified as part of updating this if possible.

**Comment by jhaigh0** [comment]
When I've tested building the docs on both Windows and Ubuntu, the plot appears as it should do. Very strange one.

**Comment by rbauststfc** [comment]
Thanks for taking a look @jhaigh0, have you been building locally? I think I found the local build was OK, but for some reason the plot doesn't appear when published, so maybe an issue somewhere in the Jenkins build/publishing pipeline (in which case this might be one for Dev Ops)?

**Comment by jhaigh0** [comment]
Yes just locally on my laptop and then on a VM. I think you might be right

**Comment by jclarkeSTFC** [comment]
It looks like the published docs now have the plots, should we close this?

**Comment by rbauststfc** [comment]
Great, yes, we can close this now that it seems to be working OK.
