### ISSUE TITLE
Move to Python 3.10

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#35228]
Python 3.12 will be released in October 2023. We sould expect that conda-forge will Drop Python 3.8 support when 3.12 is out, similar to this announcement:
https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7
Things that are pinned and blocking the upgrade to python 3.10:
- [x] setuptools  #33118 
- [x] cppcheck
- [x] ipykernel
- [x] numpy

**Comment by AndreiSavici** [comment]
Why not move to an even more advanced version of python? Ubuntu 22.04 is shipped with 3.10. There are some deprecation warnings, but almost everything else works fine

**Comment by jhaigh0** [comment]
https://builds.mantidproject.org/job/build_packages_from_branch/271/
