### ISSUE TITLE
MacOS Interface Smoke Tests  :facepalm:

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#35244]
We must test both the .dmg installer package and install direct from conda.

* To install via conda:
  - Use Intel Conda and make sure conda-forge is added to channels
```
mamba create -n test_mantid_6.6
mamba activate test_mantid_6.6
mamba install -c mantid/label/rc1 mantidworkbench --yes
workbench # to launch
```

**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :facepalm:

## ISIS only, if possible, so catalogue access can be tested

- [x] MantidWorkbench opens without errors or warnings 
- [x] Every option in `Interface` opens a GUI 
- [x] Load some test data 
- [x] Access Catalogue through algorithms (use Facilities account, same as for IDAaaS): [CatalogLogin](https://docs.mantidproject.org/algorithms/CatalogLogin-v1.html) and [CatalogGetDataFiles](https://docs.mantidproject.org/algorithms/CatalogGetDataFiles-v1.html)
- [x] Saving/loading projects works 
 - [x] Alter preferences in [File > Settings](https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/useful/01_save_settings.html#settings) and check they are obeyed

**Comment by ConorMFinn** [comment]
Triple Refl Interface:
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/47181718/219688291-d7e43a48-c406-4e28-bf1a-974950198a52.png">

1. Save a project with a refl GUI open
2. Close workbench
3. Open workbench
4. load project
5. may load multiple Refl GUIs
6. able to open an additional refl GUI
