### ISSUE TITLE
Waterfall plot: error with zero offsets

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#35257]
**Describe the bug**

There is an issue in the waterfall plotting when the offsets are both set to 0 and a return key is pressed. In effect, a runtime error is created with the following traceback: 

```
File "lib/python3.8/site-packages/mantidqt/widgets/waterfallplotoffsetdialog/presenter.py", line 27, in <lambda>
    self.view.x_offset_spin_box.valueChanged.connect(lambda: self.update_x_offset())
  File "lib/python3.8/site-packages/mantidqt/widgets/waterfallplotoffsetdialog/presenter.py", line 42, in update_x_offset
    self.ax.update_waterfall(new_x, self.view.get_y_offset())
  File "lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 1128, in update_waterfall
    self.set_waterfall_fill(False)
  File "envs/test_mantid_6.6/lib/python3.8/site-packages/mantid/plots/mantidaxes.py", line 1209, in set_waterfall_fill
    raise RuntimeError("Cannot toggle fill on non-waterfall plot.")
RuntimeError: Cannot toggle fill on non-waterfall plot.
```

**To Reproduce**

1. Load some data, e.g. `MAR11060.raw`
2. Plot a couple of spectra with `Plot type` set to `Waterfall`
3. Open Offset Amount Dialog and modify the two offset value to 0. Press return key.
4. Observe the issue.

**Expected behavior**

It should be possible to create a waterfall plot with no offset.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04
 - Mantid Version 6.6.0.rc1

**Additional context**

**Comment by gemmaguest** [comment]
Reproduced in v6.4.0 Ubuntu

**Comment by jhaigh0** [comment]
So just having a look at this and if you remove the check [from here](https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/mantid/plots/mantidaxes.py#L1206) then when recreating the test, the plot just reverts to a regular plot. I think this makes sense in a kind of way, but maybe quite unexpected for your waterfall plot to turn into a regular one (toolbar options disappear).
