### ISSUE TITLE
Add error message to SANS GUI for loading data files with non-ASCII characters in path

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#35301]
**Original reporter:** Gregory Smith @ ISIS

**Describe the bug**
When trying to reduce ISIS SANS2D data in the ISIS SANS Reduction GUI, reduction was not successful on Windows. We think this was because the file path contained non-ASCII characters. When using the file loading dialog it lets you know that it can't parse the file name, but the SANS reduction doesn't give any useful information. It would be good if we could just load these files.

**To Reproduce**

_When using LoadNexus algorithm directly:_
1. Move a .nxs file into a directory containing a non-ascii character, e.g. ü.
2. Try to load the file.

_In ISIS SANS GUI:_
1. The issue was originally seen for a reduction that required an add (summed runs) Nexus file. Speak to Rachel to get data for an example reduction.
2. Save the example batch file, user file and add files to a folder that includes a non-ASCII character in the name (e.g. pressing `ALT+0228` should give you an `ä`).
3. In the ISIS SANS interface, load the user and batch file. The runs table should be populated. Click one of the process buttons to process a row in the table.
4. The row should turn blue, indicating a file could not be found, but no useful error message is provided. Note that hovering over the row gives message "Ended up in added branch where it's neither processed or raw?" in a tooltip, which may or may not help when investigating.

**Expected behavior**
File will load as normal, or a useful error message is provided.

**Comment by thomashampson** [comment]
@rbauststfc I think it's quite a big code change to support this in general. Would it be possible in the meantime to give the user some feedback in the SANS GUI when this happens?

**Comment by rbauststfc** [comment]
Thanks for looking into it @thomashampson, we'll add this issue to our SANS to-do list then. Jonathan confirmed that you're not planning to keep an issue open for the underlying fix, so we'll close this issue once we've made our change.
