### ISSUE TITLE
Changing font on linux from the settings menu sends setting menu to back

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantid#35329]
**Describe the bug**
When changing the font on Linux via the settings menu, the settings menu gets sent behind the workbench gui. This gives the impression that the workbench gui has frozen, whereas it is just waiting for the settings window to close.

**To Reproduce**

1. `File` > `Settings`
2. Under general click the `Select Font` button next to `Main Font`.
3. Observe the `settings` window gets kicked behind the workbench gui

**Expected behavior**
`Select Font` window opens on top of the `settings window`, which remains in front of the workbench gui.

**Platform/Version (please complete the following information):**
Linux

**Comment by jclarkeSTFC** [comment]
This still happens in Ubuntu 22.04
