### ISSUE TITLE
SANS Diagnostics labeling of plots

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3532]
This issue was originally [TRAC 2685](http://trac.mantidproject.org/mantid/ticket/2685)

Labelling of output workspaces â€“ 
 * Rather than _H1, _H2 in order generated, label output workspace with actual file name, detector, and then actual range string, preceded by H or V   and whether masked  e.g. LOQ61400mainH60-H68_tmask
 * All H and V plots have â€œX axisâ€ as the label in plots, can we change this to â€œrow or columnâ€.

**Comment by picatess** [comment]
This issue has been fixed (here)[https://github.com/mantidproject/mantid/pull/12962]
