### ISSUE TITLE
Sans Diagnostics: load current files

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#3533]
sans_feature
This issue was originally [TRAC 2686](http://trac.mantidproject.org/mantid/ticket/2686)

As well as â€œbrowseâ€ for a raw or nxs file (which can be tedious as we have lots of files) can we have a drop down for the currently loaded raw or nxs â€“ but this likely wonâ€™t work as Mantid may have edited them down to a single detector bank ???

**Comment by Mantid-Matthew** [comment]
I am closing this issue for now but will check with instrument scientists and reopen if still required.
