### ISSUE TITLE
Refl GUI Resizing to Very Wide When Many Trans Runs In Exp Settings

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#35354]
**Original reporter:** Becky Welbourn

**Describe the bug**

The gui becomes much too wide when a new batch is created with a long line of runs in the Exp Settings. This is unlikely to be the root cause, but is the best way to reproduce the issue. 

**To Reproduce**
1. Open the Refl GUI
2. Load a batch with lots of trans runs (ask @ConorMFinn for file)
3. Process one of the runs
4. Add a new batch

There may be other ways to reproduce this, but this is the most reliable one I've found.

**Expected behavior**

The GUI should remain resizable, or at least be of a size where it fits onto a standard screen.

**Comment by rbauststfc** [comment]
Need to test this given recent Qt changes (#35434) to see if it still exists.
