### ISSUE TITLE
Preview Tab: Angle Should be Collected From Loaded Workspace/Logfile

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#35350]
- [x] ~The angle should be set on the GUI and in the underlying models automatically from the loaded workspace. It looks like there might already be some code that's trying to do this (see `PreviewPresenter::notifyLoadWorkspaceCompleted`) so we may just need to better understand what this is doing and check that it's working correctly.~ This does appear to be working OK.
- [ ] Determine if the ability to change the angle value is actually useful (rather than just displaying it in the GUI). Becky and Max may need a chance to use the tab properly before deciding if the flexibility to change the angle is still needed. We should hold off putting time into removing the input until the scientists are confident they don't need it, as the way it is now doesn't cause a problem.

**Comment by rbauststfc** [comment]
I'm going to close this as I think there's no harm in allowing the angle to be changed and there may be occasions where the flexibility is useful. I don't think it's a good use of our time to remove the functionality now that it's there.
