### ISSUE TITLE
TimeSeriesProperty::filterByTime returns unexpected results when there are missing log entries

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#35361]
**Original reporter:** Becky from Reflectometry at ISIS

**Describe the bug**

A couple of issues have been noticed in the filtering within method `TimeSeriesProperty::filterByTime`:

- [ ] When `start` and `stop` values are passed in that fall outside the available range they are treated as "extremes" and no filtering is applied. For example, imagine a series with time values `[10:00, 10:30, 11:00, 11:30, 12:00]`. If a filter `start=09:00` and `stop=09:30` was passed in then the code would currently return all available values, when it would seem to be more accurate for no values to be returned. We also get the same behaviour if the start and stop times fall after the available range of values, i.e. `start=12:30` and `stop=13:00` would currently return all values instead of none.
- [ ] When there are values missing from the middle of the time series and the filter `start` and `stop` values fall within this gap, the code returns a single value from the series when we would expect nothing to be returned. For example, imagine a series with time values `[10:00, 10:30, 11:00, 14:00, 14:30]`. If filter `start=12:00` and `stop=13:00` was passed in then the code would return the value for time 11:00, even though I think we would expect the behaviour to satisfy the condition `start time <= times returned <= stop time`, which would mean no values were returned.

This behaviour was noticed because Becky was performing some time slicing of runs that included a beam off period. In the beam off period it seems that `proton_charge` values are not logged (why this happens is being investigated by Controls). Becky was expecting to see that slices that fell within the beam off period would show 0 values for the `proton_charge` log entries and 0 for the `gd_prtn_chrg` (which is the sum of all the `proton_charge` log entries for the slice). However, the actual values she was seeing were non-zero, due to the behaviour of the code in `TimeSeriesProperty::filterByTime` described above.

**To Reproduce**

This can be reproduced by running algorithm `FilterByTime` (which calls `TimeSeriesProperty::filterByTime`) against workspaces with beam off periods at the beginning, middle or end of the run, and using filter values that fall within the beam off period:

1) Beam off period at end of run: call `FilterByTime(InputWorkspace=INTER69444, OutputWorkspace=INTER69444_offAtEnd, StartTime=250, StopTime=1500)`
2) Beam off period in middle of run: call `FilterByTime(InputWorkspace=INTER69262, OutputWorkspace=INTER69262_offInMiddle, StartTime=2800, StopTime=11600)`
3) Beam off period at start of run: call `FilterByTime(InputWorkspace=INTER69308, OutputWorkspace=INTER69308_offAtStart, AbsoluteStartTime=2023-02-10T11:32:00, AbsoluteStopTime=2023-02-10T11:33:00)` - note that we need to use absolute start and stop times for this as the relative times are calculated relative to the first beam pulse, meaning it's not possible to filter within the beam off period here unless absolute times are used.

For all tests we would expect the `gd_prtn_chrg` value to be 0. I'm not sure if we would expect the `proton_charge` log to contain no entries or all 0 entries. I've done a quick test and leaving it with no entries causes Mantid to crash when trying to view the Sample Logs for the filtered workspace from the right click menu, so this will need investigating. Method `TimeSeriesProperty::splitByTimeVector` has similar filtering issues, but does sometimes correctly return 0 (see #35375) so we could look at how that's handled.

**Suggested code changes**
We need to check where this is being used and whether there is a reason why the filtering is behaving as it is currently. If we conclude that the code can be changed then I think the following changes to the logic would be needed to get the filtering to behave as expected:

- start value before the time series range (i.e. method `findIndex` returns -1) should keep all values.
- end value before the time series range (i.e. method `findIndex` returns -1) should remove all values.
- start value after the time series range (i.e. method `findIndex` returns size of vector) should remove all values.
- end value after the time series range (i.e. method `findIndex` returns size of vector) should keep all values.
- to ensure that returned values satisfy condition start <= returned times <= stop, in the part of the code that handles the start value, add a step that checks `m_values[istart + 1].time()` when `useprefiltertime` is false. If this value is greater than the end value then we can probably assume that our range falls within a period of missing log entries and remove all values from the log.

**Comment by AnthonyLim23** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add absorption correction](https://trello.com/c/yZ9LzGRn/1-add-absorption-correction)
