### ISSUE TITLE
Add support for a gauge volume into the MonteCarloAbsorption algorithm

### ISSUE THREAD

**Issue by DannyHindson** [mantidproject/mantid#35371]
Engineering diffraction instruments are able to restrict the volume inside the sample where scattering occurs (at least scattering on tracks that reach the detectors) using a radial collimator. This volume will be referred to as a gauge volume in the rest of this description.

In order to support this the MonteCarloAbsorption algorithm would require an extra feature where a gauge volume can be specified. The algorithm should restrict scattering to happen in this volume. The attenuation on simulated paths should still be calculated using the full sample volume.

This feature already exists on the `AbsorptionCorrection` (implemented in AnyShapeAbsorption.cpp) and `PaalmanPingsAbsorptionCorrection` algorithms. These algorithms rely on a helper algorithm called `DefineGaugeVolume` to define the additional shape using the CSG shape representation. Then there is some code inside the algorithm that checks if this has been run:
```
  auto integrationVolume = std::shared_ptr<const IObject>(m_sampleObject->clone());
  if (m_inputWS->run().hasProperty("GaugeVolume")) {
    integrationVolume = constructGaugeVolume();
  }
```
I think a similar approach can be used with MonteCarloAbsorption.

The MonteCarloAbsorption algorithm already supports the user specifying a beam profile. The beam profile may be smaller than the sample cross section. Not totally sure how this feature should interact with a gauge volume if specified. Perhaps the two can coexist in the sense that you can randomly select a track start point on whatever beam profile is specified and then generate the scatter point randomly in the gauge volume. In reality it may be that the gauge volume has the same cross section as the beam profile. So if a user supplies a gauge volume but not a beam profile, perhaps the beam profile should default to be the cross section of the gauge volume.

**Code Changes**

I'll spell out the approach here in more detail than usual since I won't be around for the implementation.

The MonteCarloAbsorption algorithm uses a couple of other classes rather than doing all the work inside the MonteCarloAbsorption class:
- MCAbsorptionStrategy
- MCInteractionVolume

The logic around where scatter points are generated lives in MCInteractionVolume. This class already has a property called m_activeRegion which sounds like it's what we need. A situation where this is smaller than the sample volume is already supported so the code to generate scatter points in one volume and calculation attenuation across a separate\larger volume already exists so that's good news. This was created to support a beam profile that's smaller than the sample. The only problem with this is that it has type BoundingBox. So if we decide to reuse this property for the gauge volume we restrict the gauge volume to be a cuboid.

The m_activeRegion is currently used to store a reduced scattering volume that comes from specifying a beam profile. The m_activeRegion is set in the function `MCAbsorptionStrategy::setActiveRegion` so if we ever change m_activeRegion to be equal to a supplied gauge volume this logic would probably be in the same function. 

The use of the BoundingBox class to implement m_activeRegion is already looking a bit shaky because we now support a circular beam profile. Despite this the scattering volume is still taken to be a cuboid which is too large. So there is an argument that m_activeRegion should be generalised to be a CSGObject both to fix this and to make MonteCarloAbsorption behave the same way as its numerical\deterministic cousin AbsorptionCorrection. This would involve modifying the functions `CSGObject::generatePointInObject` and `RandomPoint::bounded` which currently take an activeRegion parameter of type BoundingBox to instead take a CSGObject. It could be a useful implementation approach to first implement the gauge volume as a cuboid before moving on to support a general CSG shape.

**Comment by RichardWaiteSTFC** [comment]
- `IObject::generatePointInObject` is parent interface to csg and mesh shapes and will need some modification to support CSG (but might gave to declare it as `const IObject &activeRegion` rather than `CSGObject`)
- Gauge volume should only be CSG (not mesh)
- Inside `generatePointInObject` there is a call to `RandomPoint::bounded` that assumes cuboid - essentially needs another check that point in bounding box of gauge volume is in sample and in gauge volume
- FYI `generatePointInObject` is called in a loop over all components in environment and sample etc. which calls `generatePointInObjectByIndex`
