### ISSUE TITLE
Remove readline linux pin to <8.2

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantid#35406]
**Describe the outcome that is desired.**
Remove `readline` linux pin from `<8.2` in `mantid-developer-linux.yml`,

**Describe any solutions you are considering**
In the `qt/python/mantidqt/mantidqt/widgets/test/test_jupyterconsole.py`, `import readline` is used in order to prevent a segfault. This is also done here: https://github.com/mantidproject/mantid/pull/31921/files with useful discussion about the cause.

Since `readline` version `8.2` has been put on `conda-forge`, the `import readline` line itself is causing a different segfault. In order to resolve this we have had to pin it to `<8.2`: https://github.com/mantidproject/mantid/pull/35405

It looks like we could remove the `readline` pin by removing the `ipykernel` pin so that `import readline` is no longer needed.

**Comment by thomashampson** [comment]
Now that we've removed the ipykernel pinning this should be investigated.
