### ISSUE TITLE
Replace quasielasticbayes

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#35442]
We need to replace the quasielasticbayes package, it is an old Fortran code that is difficult to maintain (near impossible for Python 3.8 and higher) and only works on limited OS's. The quickBayes package is designed to be a replacement. 

1. Deprecate the Fortran code
2. Add the quickBayes package to Mantid
3. Create two new algorithms that use the quickBayes package
4. Create new docs and unit tests

**Comment by AnthonyLim23** [comment]
https://github.com/mantidproject/mantid/blob/main/Framework/Algorithms/src/MaskInstrument.cpp#L24

**Comment by AnthonyLim23** [comment]
The deprecation will be added as another issue https://github.com/mantidproject/mantid/issues/35917

**Comment by thomashampson** [comment]
@AnthonyLim23 can we close this one now?
