### ISSUE TITLE
Jupyter console broken

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#35461]
**Describe the bug**
Jupyter console does not seem to be working very well on recent Conda installs (including on IDAaaS). Trying to run anything at all results in this kind of error:
```
        Stack Trace:
        Traceback (most recent call last):
  File "/opt/mantidworkbench6.6/lib/python3.8/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/opt/mantidworkbench6.6/lib/python3.8/site-packages/qtconsole/jupyter_widget.py", line 193, in _handle_execute_reply
    super()._handle_execute_reply(msg)
  File "/opt/mantidworkbench6.6/lib/python3.8/site-packages/qtconsole/frontend_widget.py", line 468, in _handle_execute_reply
    if not self.kernel_client.iopub_channel.closed():
AttributeError: 'QtInProcessChannel' object has no attribute 'closed'
```
Afterwards it is completely unuseable.

I have narrowed this down to an upgrade of our qtconsole dependency. It seems to have broken with v5.4.2, I think due to this PR:
https://github.com/jupyter/qtconsole/pull/574

**To Reproduce**
1. Install mantidworkbench into a new Conda environment.
2. Type anything (e.g. `i = 1`) into the Jupyter console and press return. It will pop up the error reporter.

**Expected behavior**
It should work.

**Platform/Version (please complete the following information):**
 - OS: Any
 - Mantid Version: any installed from Conda with `qtconsole==5.4.2`

**Additional context**
This will likely be fixed by this open PR in the qtconsole repo https://github.com/jupyter/qtconsole/pull/575 but in the meantime we should pin to 5.4.1 so that the nightly version works.

**Comment by peterfpeterson** [comment]
@zjmorgan pointed this out at ORNL as well. 

Notes from @AndreiSavici is that v6.6 vs nightly are using

v6.6: Jupyter QtConsole 5.4.0, IPython 8.11.0. 
In nightly: Jupyter QtConsole 5.4.2, IPython 8.12.0

The bug that exists in v5.4.2 is fixed in [this PR](https://github.com/jupyter/qtconsole/pull/575)
