### ISSUE TITLE
Nightly not publishing to GitHub

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#35477]
**Describe the bug**
Nightly packages are not being publish on GitHub - https://github.com/mantidproject/mantid/releases

**To Reproduce**
Example of a nightly failing in this way - https://builds.mantidproject.org/view/Nightly%20Pipelines/job/main_nightly_deployment_prototype/541/

Link to specific console log for this failure - https://builds.mantidproject.org/view/Nightly%20Pipelines/job/main_nightly_deployment_prototype/541/execution/node/588/log/

**Expected behavior**
The Nightly pipeline should publish completed packages to both Conda forge and GitHub. At present packages are only being published through GitHub. It was assumed that clearing up the old nightly packages would resolve this but so far it has not.

**Platform/Version (please complete the following information):**
N/A

**Additional context**
A separate Issue has been raised for cleaning up old nightly packages #35472

**Comment by thomashampson** [comment]
I think we didn't update the Jenkins settings after generating a new token. That has been done now.
