### ISSUE TITLE
IndexPeaks not rounding HKL of satellite peaks

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#35513]
**Describe the bug**
IndexPeaks not rounding HKL of satellite peaks to the nominal HLK given the modulation vector
`HKL = peak.getIntHKL() + modHKL * peak.getIntMNP()`
Instead it rounds the HKL to integers

**To Reproduce**

(1) Run this script
```
sxd = LoadEmptyInstrument(InstrumentName='SXD', OutputWorkspace='sxd')
peaks = CreatePeaksWorkspace(InstrumentWorkspace=sxd, NumberOfPeaks=0, OutputWorkspace="peaks")
SetUB(peaks, UB="0.25,0,0,0,0.25,0,0,0,0.1")
# add peaks at integer and half-integer H
for h in [0.5,1,1.5,2]:
    peaks.addPeak(peaks.createPeakHKL([h, 0, 1]))
# change a lattice parameter slightly
SetUB(peaks, UB="0.26,0,0,0,0.25,0,0,0,0.1")
# index
IndexPeaks(PeaksWorkspace='peaks', Tolerance=0.1, ToleranceForSatellite=0.1, 
           CommonUBForAll=True, ModVector1='0.5,0,0', MaxOrder=1, 
           SaveModulationInfo=True)
```

The log should say 

```
All runs indexed 4 peaks out of 4 of which, 2 main Bragg peaks are indexed with tolerance of 0.1, 2 satellite peaks are indexed with tolerance of 0.1
```

(2) Open the peak table (HKL of satellite peaks are integers despite being indexed)
![image](https://github.com/mantidproject/mantid/assets/55979119/16961f4c-c5c3-42a6-bc05-d6e64e4830dc)

**Expected behavior**
It should look like this 
![image](https://github.com/mantidproject/mantid/assets/55979119/e5be453a-a79e-40e2-89f7-3fcfc7dcdf79)

**Comment by zjmorgan** [comment]
With my other PR, running your test I now obtain.
![image](https://github.com/mantidproject/mantid/assets/13754794/a69c4086-9f1e-4186-bf85-e1d3073c5e28)
