### ISSUE TITLE
Report Usuage Data Text Box Needs Improvement

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#35573]
**Describe the bug**
The text and title in the dialog box that appears when disabling the usage data is somewhat unclear:

![image](https://github.com/mantidproject/mantid/assets/47181718/9a448416-cb7a-4f76-bb51-db5414ff4c14)

The title says "Report Usage Data", which if you only read the title suggests you should click `Yes` to have usage data on.

The main body text asks if you want to *disable* the usage data. Which means you should click `No` to have usage data on. 

**To Reproduce**
1. Help -> About Mantid Workbench (MantidWorkbench -> About Mantid Workbench on macOS)
2. Untick the `Send Usage Data` checkbox. 

**Expected behavior**
The title of the box should be changed to match the text within, or the main text of the box should be changed to match the title.

**Platform/Version (please complete the following information):**
 - OS: all
 - OS Version: n/a
 - Mantid Version: 6.6

**Additional context**

**Comment by ajjackson** [comment]
The final 'Please click "No".' is my favourite part, after reading that I have no idea what the buttons will do.
