### ISSUE TITLE
Update manual testing docs for sliceviewer

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#35572]
Found during testing of #35551 

- For 4D MD workspace, if you have a non-momentum viewing axis, the peak overlay won't update the slice point
- The peak actions don't work with a non-momentum viewing axis
- For the 3D MDHistoWorkspace in the instructions, it is not possible to open the SliceViewer
- For the CutViewer instructions, the non-orthogonal view should not be disabled
- For step 19, you need to move the cut representation

**Comment by sf1919** [comment]
The screen shot for CutViewer Tool step 8 may be wrong. I get the following
![Screenshot (280)](https://github.com/mantidproject/mantid/assets/55837273/d520680a-b6b4-4282-9cd1-f97dce3feb9b)

**Comment by sf1919** [comment]
Trying to follow the ADS observer for peak overlay and do not appear to be able to rename the file in the ADS
