### ISSUE TITLE
Matplotlib deprecation warning in sliceviewer

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#35580]
**Describe the bug**
Found during manual testing #35551

**To Reproduce**
This deprecation warning on step 3 of the 3rd test in the Specific Tests section of manual testing docs  (Multiplying the workspace from the IPython console)
https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#ads-observer-for-workspace

```

Passing the angle parameter of __init__() positionally is deprecated since Matplotlib 3.6;
the parameter will become keyword-only two minor releases later

```

**Comment by jhaigh0** [comment]
@RichardWaiteSTFC Just to check, is it the line `mtd['md_3Dim'] *= 2` that was causing the deprecation warning? It doesn't seem to do for me.

**Comment by RichardWaiteSTFC** [comment]
Yes that's the line that triggered the warning (with sliceviewer still open) - it might have been in non-orthogonal view (just thinking about the angle parameter in question)?

**Comment by jhaigh0** [comment]
Ah okay, I'll try following the instructions a little ore exactly this time.

**Comment by thomashampson** [comment]
@RichardWaiteSTFC I've tried following the test instructions and fiddling with other things and I can't reproduce the depreciation warning.
