### ISSUE TITLE
GenerateIPythonNotebook Notebook Validation not Working

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#35582]
@ajjackson Would you be able to fill this in with some details? Thanks. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by ajjackson** [comment]
I can't edit your post, but platform is IDAaaS with conda install of Mantid nightly and `notebook` installed into the same environment with mamba.

To reproduce:
```python

from mantid.simpleapi import *

CreateSampleWorkspace(OutputWorkspace='demo-workspace')
RenameWorkspace(InputWorkspace='demo-workspace', OutputWorkspace='demo-renamed')

GenerateIPythonNotebook(InputWorkspace='demo-renamed', Filename='test-notebook.ipynb')

```

Opening this with `jupyter notebook test-notebook.ipynb` immediately shows a warning about the format needing to be updated.
![Screenshot from 2023-05-18 15-19-32](https://github.com/mantidproject/mantid/assets/2511383/48d4f80e-4125-481a-9329-4f7014e0d4cb)

About a minute later, with no further interaction, this validation failure message appears:
![Screenshot from 2023-05-18 15-22-30](https://github.com/mantidproject/mantid/assets/2511383/284f86a2-0752-48fd-a0d0-bf6c6bf62f68)
