### ISSUE TITLE
LaTeX not rendering in MSliceTestGuide

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#35589]
**Describe the bug**
Angstroms symbols don't appear to be rendering properly here. 

**To Reproduce**
1. Go here: https://developer.mantidproject.org/Testing/DirectInelastic/MSliceTestGuide.html

**Expected behavior**
Angstroms should be shown as the symbol rather than this red text

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/47181718/36354523-21b2-49aa-8e3b-285420f44c37)

**Comment by AndreiSavici** [comment]
Depending on preferences, add
```
.. only:: html

  :math:`\renewcommand\AA{\overset{\circ}{A}}`
```
or 
```
.. only:: html

  :math:`\renewcommand\AA{\text{Å}}`
```
at the beginning of the file
