### ISSUE TITLE
Exporting Column/Row Headers in Show Data Working Strangely

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#35583]
**Describe the bug**
In a Show Data window, right clicking a column header to plot a bin or a row header to plot a spectrum does not plot the whole bin/spectra unless it is clicked to select the whole bin/spectra first. This isn't very intuitive.

**To Reproduce**
1. Load some data
2. Select some cells
3. Right click a row's header
4. Export that row
5. See that the selected cells were the ones exported, not the row that was right clicked. 

**Expected behavior**
The row or column that is right clicked should be the bin/spectra that is exported to a ws. 

**Platform/Version (please complete the following information):**
 - OS: All

**Comment by jhaigh0** [comment]
It's also weird that you have to select a whole row(s) to then export them to a table workspace. Feels like you should be able to export any NxM selection of cells.
