### ISSUE TITLE
Jenkins Plugin Review

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#35692]
**Product Owner:** Sarah Foxley

An investigation into the plugins being used for our Jenkins CI and packaging pipelines. We want to ensure the plugins we have installed are being used, are not deprecated, and have no security vulnerabilities.

## Benefit hypothesis ##
- Improved security for our Jenkins CI and packaging pipelines.
- Improved operational efficiency for the DevOps team during Jenkins maintenance.
- Easier to upgrade the Jenkins Core => Less reliance on the Jenkins Backup and Restore system.

## Acceptance criteria ##
1. The number of Jenkins plugins with security vulnerabilities installed is zero. 

2. The number of unused Jenkins plugins installed is zero. 

3. The number of deprecated Jenkins plugins installed is zero. 

4. A document exists with clear and simple justifications for using the Jenkins plugins we have installed.

**Comment by robertapplin** [comment]
## Stories ##
- [ ] https://github.com/mantidproject/mantid/issues/35695

**Comment by sf1919** [comment]
Can this one now be closed @robertapplin ?
