### ISSUE TITLE
Valid data in tabulated function

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/mantid#35716]
I have done some more testing and it still does not work for LET data. However, this is because the resolution function contains NAN's and it is never checked as a result. I will look at this in another issue

_Originally posted by @AnthonyLim23 in https://github.com/mantidproject/mantid/issues/35655#issuecomment-1601028047_
            

The tabulated function sits underneath the resolution function. When we select ignore invalid data for a fit it only checks the data we are fitting to and not the data in a tabulated function. We will need to add a check to the tabulated function that will replace invalid values with a 0. 

https://github.com/mantidproject/mantid/blob/main/Framework/CurveFitting/src/Functions/TabulatedFunction.cpp#L319

use something like https://cplusplus.com/reference/algorithm/replace_if/

**Comment by peterfpeterson** [comment]
I haven't looked at the full context of this, but [ReplaceSpecialValues](https://docs.mantidproject.org/nightly/algorithms/ReplaceSpecialValues-v1.html) is meant to make this sort of replacement "obvious" to the user.

**Comment by AnthonyLim23** [comment]
This has come from LET, their resolution workspace has some NAN's. They want to use the indirect inelastic data analysis GUI, which can read things in as a file (so the user would not be able to use ReplaceSpecialValues). However, for this issue I could do the following:

1. Edit the GUI to check for special values in the resolution and to run ReplaceSpecialValues if any are found
2. Add a warning message to use "ReplaceSpecialValues" if any special values are found in a tabulated function. I did not know we had this algorithm, so I suspect most users do not. 
@peterfpeterson what do you think?

**Comment by peterfpeterson** [comment]
`ReplaceSpecialValues` is used a fair amount in PD, but I can understand that not everybody knows about all the algorithms. I think a hybrid of your two suggestions might be best: log a warning that there are special values *and* replace them.

**Comment by AnthonyLim23** [comment]
I am just adding the warning and replacement in the indirect GUI. Then we wont be changing the behaviour of the tabulated function
