### ISSUE TITLE
Mistake in the EISF for confined diffusion in cylinder geometry

### ISSUE THREAD

**Issue by fucaline** [mantidproject/mantid#35719]
**Describe the bug**
The implemented EISF for the diffusion of a particle confined in a cylinder:  [https://github.com/mantidproject/mantid/blob/a239c0e279a85ef726c0e007caa84af0a7c09398/Framework/PythonInterface/plugins/functions/EISFDiffCylinder.py](url) does not follow the theoretical expression given in ref1: Dianoux et al. [Mol. Phys. 46:1129-37, 1982](https://doi.org/10.1080/00268978200101121).

- In EISFDiffCylinder.py: A0=[j0(QLcos(theta))]^2
- In ref1: A0=[j0(QLcos(theta)/2)]^2

- In EISFDiffCylinder.py: B0=[3*j1(QRsin(theta))/(QRsin(theta))]^2
- In ref1: B0=[2*J1(QRsin(theta))/(QRsin(theta))]^2

where J1 is an ordinary Bessel function of first kind, and j1 a spherical Bessel function.
Do j1 and J1 have been confused? Or 2*J1(x) have been approximated by 3*j1(x)?

Also, the description in the documentation page is incorrect: https://docs.mantidproject.org/nightly/fitting/fitfunctions/EISFDiffCylinder.html

- L and R have been exchanged
- A0 does not correspond to what is implemented in EISFDiffCylinder.py

**Comment by robertapplin** [comment]
Keep open

**Comment by robertapplin** [comment]
@fucaline Thanks for reporting this, and sorry we've taken so long to get back to you! I am investigating this now

So far I have read through the paper and found the equation they are using for the A0 parameter. I get it to be the same as that implemented in EISFDiffCylinder.py   i.e.  A0=[j0(QLcos(theta))]^2 . These are my workings, can you spot if I have made a mistake?

```
Assuming z = LQcos(\theta), and using equation 2b in the paper with p=0 I get

A_0(z) = \frac{2(1 - \cos(z))}{z^2}

I then use the cosine of half-angle identity \cos\left(\frac{x}{2}\right) = \sqrt{\frac{1 + \cos(x)}{2}} to get:

1 - \cos(z) = \frac{1}{2} \cdot (z \cdot j_0(z))^2

I substitute this into the A_0(z) equation, and I get:

A_0(z) = j_0(z)^2
```

**Comment by robertapplin** [comment]
These are my workings for B0. From the paper we have:
![image](https://github.com/mantidproject/mantid/assets/40830825/2d6a301e-758b-4f9b-a872-6bc2cb77acd2)

We can then use the following formula
![image](https://github.com/mantidproject/mantid/assets/40830825/b521c302-b286-45bd-81a2-1cf969a87840)

to find J_1 in terms of j:
![image](https://github.com/mantidproject/mantid/assets/40830825/5af5c92f-3784-40b9-9f67-a2a594da9895)

Substitute this into the B0 equation and we get:
![image](https://github.com/mantidproject/mantid/assets/40830825/987ce963-9379-4bd0-9371-0889633885e2)


The j_{3/2}(z) can be calculated using `scipy.special.spherical_jn`
