### ISSUE TITLE
Windows Plotting Smoke Tests  :chart_with_upwards_trend: :bar_chart:

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#35728]
We must test both the .exe installer package and install direct from conda.

* To install via conda:
  - Use Intel Conda and make sure conda-forge is added to channels
```
mamba create -n test_mantid_6.6
mamba activate test_mantid_6.6
mamba install -c mantid/label/rc1 mantidworkbench --yes
workbench # to launch
```

**Before testing**:
- Check this testing issue relates to the OS you will test on.
- If unassigned, please assign yourself as for a normal Github issue.
- Please run these tests on the release package of Mantid; **not a locally built version**.

**Afterwards**:
- Comment below with any issues you came across.
- If no major issues were found, please **close this testing issue**.
- Check the main issue for this OS for other unassigned smoke tests.

If you have any questions please contact the creator of this issue.

 :chart_with_upwards_trend: :bar_chart:

* 1D plotting:[instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/03_displaying_1D_data.html#displaying-1d-data)
 - [x] Simple plot 
 - [x] Another way to plot 
 - [x] Adding curves to existing plots 
 - [x] Also, test out [waterfall](https://docs.mantidproject.org/nightly/plotting/WaterfallPlotsHelp.html#waterfall-plots) and [tiled]( https://docs.mantidproject.org/nightly/plotting/1DPlotsHelp.html#tiled-plots)
 - [x] Check Toolbar buttons

* 2D plotting: [instructions](http://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/loading_and_displaying_data/04_displaying_2D_data.html#displaying-2d-data)
 - [x] Plot all spectra 
 - [x] Change colour map 
 - [x] [Contour plot](https://docs.mantidproject.org/nightly/plotting/ColorfillPlotsHelp.html#contour-plots) (under 3D menu) 
 - [x] Check Toolbar buttons

* [3D plotting](https://docs.mantidproject.org/nightly/plotting/3DPlotsHelp.html):
 - Load some data eg `LOQ7041` from the ISIS sample data
 - [x] 3D surface
 - [x] 3D wire frame  
 - [x] Check Toolbar buttons

 ## Sliceviewer
 - [ ] Overly long instructions (don't spend  long!) and data [here](https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html). In particular try editing the data in a workspace while it is open in Sliceviewer!

**Comment by sf1919** [comment]
Following the instructions for 2D Plotting and following the instructions for changing to logarithmic scale in a Colorfill plot. It seems like changing it from the gear menu is independent of changing it my right clicking on the plot. When you do one after the other then it claims it is still the previous value and changes the plot again.

**Comment by sf1919** [comment]
Don't seem to be able to right click and get a menu on a contour plot

**Comment by sf1919** [comment]
I couldn't find the file `LOQ741` - I used `LOQ74014` instead

**Comment by sf1919** [comment]
Thought I'd found an issue but it seems the test instructions needs updating! #35572
