### ISSUE TITLE
Update smoke testing information for plotting tests

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#35752]
**Describe the outcome that is desired.**
The LOQ file listed in #35728 doesn't seem to exist. Should be replaced with `LOQ74014` . Also need to check the plotting test on other operating systems.

**Additional context**
Found during smoke testing

**Comment by jhaigh0** [comment]
Put something here
https://github.com/mantidproject/documents/pull/113

**Comment by sf1919** [comment]
This can now be closed as it's been resolved in the documents repo (see links above).
