### ISSUE TITLE
Figure options in 3D surface plot not accepting colorbar limits

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#35750]
**Describe the bug**
Figure options do not accept color axis limits (and possibly other settings)

**To Reproduce**
(1) Load a workspace
(2) Plot > 3D > Surface > Figure Options (cog) > image tab > change colorbar max limit

Gives red error message related to path at top of window
![image](https://github.com/mantidproject/mantid/assets/55979119/59d2153d-15a9-4405-9b0e-504a9a68c7bf)
If you keep clicking OK it gets worse...
![image](https://github.com/mantidproject/mantid/assets/55979119/d94a441d-57e9-413e-b328-122f7f9348d3)

**Expected behavior**
No Error message, would accept input

**Comment by jclarkeSTFC** [comment]
I couldn't reproduce this on Windows or Linux, was it happening with a particular file?

**Comment by jclarkeSTFC** [comment]
I think this is the same problem as in #36264 and #36108, I can reproduce consistently using the instructions in #36264.
