### ISSUE TITLE
Remove importlib_resources pin

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mantid#35798]
**Describe the outcome that is desired.**

To fix a failing `euphonic` system test, `Testing/SystemTests/tests/framework/SimulatedDensityOfStatesEuphonicPackaging.py`, `importlib_resources` has been pinned to `5.12.0`.

Given that `euphonic` is now on `conda-forge`, it is thought that this system test could no longer be needed.

If @ajjackson agrees, the test and pin needs to be removed.

**Comment by ajjackson** [comment]
As mentioned in 35798, it looks like this pin is genuinely required to support the old version of Euphonic used in Mantid. Really it should be in the Conda-forge Euphonic recipe for that version.

The best way forward on Mantid side would be to update the Euphonic dependency, which requires a few compatibility tweaks. I'll crack on with that?
