### ISSUE TITLE
Add documentation for building packages

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#35829]
**Describe the outcome that is desired.**
Developers should know how to build packages from branch using Jenkins.

**Describe any solutions you are considering**
Documentation needs to be added to developer site.

**Comment by thomashampson** [comment]
It might be appropriate to add it to the end of this document?
https://developer.mantidproject.org/Packaging.html

**Comment by sf1919** [comment]
I think this still needs doing
