### ISSUE TITLE
Potential Issue with ViewBOA highlighted by assert statement.

### ISSUE THREAD

**Issue by jhaigh0** [mantidproject/mantid#35847]
**Describe the outcome that is desired.**
To look into the failing assert statement [here](https://github.com/mantidproject/mantid/blob/main/Framework/API/src/MatrixWorkspace.cpp#L636) when running `ViewBOA(2014, 61, 6)` in a debug build of Mantid.

Is this an underlying problem with the algorithm or an edge case not considered by the assert statement?

**Comment by robertapplin** [comment]
Duplicate issue: https://github.com/mantidproject/mantid/issues/35888

**Comment by peterfpeterson** [comment]
I need some help figuring out the right behavior. In "release" builds, the doctest that was copied into #35888 passes. The question is whether the number of input values should always equal the number of output values or whether the doctest has enshrined the wrong behavior.

Copying the "offending" code taken from [ViewBOA alg docs](https://docs.mantidproject.org/nightly/algorithms/ViewBOA-v1.html):
```py
import numpy as np

ViewBOA(2014, 61, 6)

lamdba_distribution = mtd['histogram61'].readY(0)
lambda_values = mtd['histogram61'].readX(0)

print("The wavelength spectrum is described by {} points.".format(len(lamdba_distribution)))
print("The range covered is {0} - {1} Angstrom.".format(round(lambda_values[0], 4),round(lambda_values[-1], 4)))
print("The maximum is located at {} Angstrom.".format(round(lambda_values[np.argmax(lamdba_distribution)], 4)))
```
