### ISSUE TITLE
Sum Runs Incorrectly Adding Monitors in ISIS SANS Interface

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#35880]
**Original reporter:** Diego Alba Venero @ ISIS

**Describe the bug**
The Sum Runs widget seems to be adding up wrong. It appears to be adding the final monitor to itself rather than all the monitors from the run list. 

**To Reproduce**
1. Load a Zoom user file into the ISIS SANS GUI
2. Switch to Sum Runs
3. Load 34133-34136
4. Sum
5. Load the saved file into workbench and check the monitor/normal workspaces. 

**Expected behavior**
All data workspaces and monitors are added up correctly.

**Comment by rbauststfc** [comment]
Steve has confirmed that we should continue investigating this to determine the precise behaviour and the conditions under which any issues are occurring. Depending on the outcome of the investigation, this could potentially be an important issue to resolve, so we have agreed that the investigation should be completed as a priority.

**Comment by rbauststfc** [comment]
Thanks very much for looking into this one @ConorMFinn. I know that you found there actually was no issue here, and our SANS scientists have now confirmed that. It seems that the history is just confusing, and we've agreed that this will be resolved as part of #34372, so I'll close this issue.
