### ISSUE TITLE
Improve the Usability of Scaled Background Subtraction in the ISIS SANS Interface

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#35939]
**Is your feature request related to a problem? Please describe.**
Following testing by the SANS instrument scientists, a number of minor issues have arisen that need to be resolved before this can be effectively rolled out to users. 

**Describe the solution you'd like**
These issues would need to be addressed:

- [x] #35958
- [x] #35953 
- [ ] Scaled Reduction Information Should Be Stored in the Output Metadata. The information we need to add is the scale factor and background workspace that was removed.
  - ~This should be done as part of #35506~ _We have now agreed this will be done as a separate PR. Time estimate: 5 days_
- [x] #35997
- [ ] ~Non-matching Keys & Values in the ISIS SANS Options Column Should Produce a Warning~ _not required as the Options column is no longer being used for supplying scaled background subtraction settings. A separate issue should be opened if this is needed for other reasons - currently the Options column doesn't seem to be used to enter values._
   - [x] ISIS SANS Should Error if the BackgroundWorkspace Could Not be Found in the ADS (this now happens, but ideally it might be good if the error message was a bit more specific)
- [x] #36535

**Additional context**
The above should likely be sorted in terms of priority before committing to getting all/any of this in to the next release.

**Comment by smk78** [comment]
I would suggest the order of priority should be (highest to lowest):

- [ ] BackgroundWorkspace Should be Able to Use Value Given in an "Output Name" Cell
- [ ] Scaled Reduction Information Should Be Stored in the Output Metadata
- [ ] Non-matching Keys & Values in the ISIS SANS Options Column Should Produce a Warning
   - [ ] ISIS SANS Should Error if the BackgroundWorkspace Could Not be Found in the ADS
- [ ] Failed Processing in ISIS SANS Should Always Stop the Progress Bar
