### ISSUE TITLE
Remove unnecessary options for IRIS and OSIRIS in ISIS Energy Transfer 

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#36000]
**Is your feature request related to a problem? Please describe.**

As part of the preparation for adding the silicon analyzer for OSIRIS into the ISIS Energy Transfer, it is necessary to restructure the UI to display only the relevant options for OSIRIS. At present, the interface shows many options that are not commonly used by scientists. A meeting was held with scientists to identify relevant OSIRIS options.
**Describe the solution you'd like**

Using the current refactored UI, the presenter should control which section to be shown.

**Comment by SpencerHowells** [comment]
@MohamedAlmaki Also IRIS

**Comment by MohamedAlmaki** [comment]
Ok, I will change IRIS also
