### ISSUE TITLE
Crash from using EISFDiffSphereAlky fit function

### ISSUE THREAD

**Issue by jhaigh0** [mantidproject/mantid#36076]
Discovered during #36045

**Describe the bug**
Mantid is crashing when trying to use `EISFDiffSphereAlky`. From where the C++ breaks I think it could be a python 3.10 thing.

This is a regression.

**To Reproduce**
- Open `Interfaces` -> `Indirect` -> `Data Analysis`
- Go to the `F(Q) fit` tab
- Change `Fit Type` to `EISFDiffSphereAlky` and observe crash

**Expected behavior**
Should be able to use it as normal.

**Platform/Version (please complete the following information):**
Tested in Ubuntu and Windows.

**Comment by jclarkeSTFC** [comment]
This also happened with `BivariateGaussian` in a fitting window. In both cases it was one of the declared attributes of the algorithm seemingly triggering the problem.

**Comment by MohamedAlmaki** [comment]
@robertapplin is this still in progress?
