### ISSUE TITLE
Improve validation in FilterEvents dialog

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36073]
A couple of issues were found during manual testing of the `Interfaces->Utility->FilterEvents` dialog for release 6.8 (#36050). It would be good to check validation generally in the dialog, but these were the specific issues found:

- [x] **Crash when trying to enter 1.25e-7 into the Filter By Log tab Minimum Value field:**

1) Open the dialog
2) In the Filter By Log tab at the bottom, attempt to enter `1.25e-7` in the `Minimum Value` field. When you type the letter `e`, Mantid should throw the following error and ask if you want to terminate the application:

```
File "C:\MantidNightlyInstall\bin\lib\site-packages\mantidqtinterfaces\FilterEvents\eventFilterGUI.py", line 445, in set_minLogValue
newminY = float(self.ui.lineEdit_5.text())
ValueError: could not convert string to float: '1.25e'
```

- [x] **Crash if using a TOF correction to sample (in the Advanced Setup tab) that is not compatible with the workspace:**

1) Open the dialog
2) Browse to the `CNCS_7860_event.nxs` file from the training data. Click the `Load` button to load the data.
3) In the Advanced Setup tab at the bottom, select `Direct` from the `TOF Correction To Sample` field (for this dataset the `Elastic` correction would have been the correct choice).
4) On the Filter By Time tab, click the `Filter` button. The following error should be thrown and you will be asked if you want to terminate the application:

```
Error in execution of algorithm FilterEvents:
Inelastic instrument detector 0 of spectrum 0 does not have EFixed
Traceback (most recent call last):
File "C:\MantidNightlyInstall\bin\lib\site-packages\mantid\simpleapi.py", line 1069, in call
algm.execute()
RuntimeError: Inelastic instrument detector 0 of spectrum 0 does not have EFixed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\MantidNightlyInstall\bin\lib\site-packages\mantidqtinterfaces\FilterEvents\eventFilterGUI.py", line 939, in filterByTime
self.splitWksp(splitws, infows)
File "C:\MantidNightlyInstall\bin\lib\site-packages\mantidqtinterfaces\FilterEvents\eventFilterGUI.py", line 1027, in splitWksp
api.FilterEvents(
File "C:\MantidNightlyInstall\bin\lib\site-packages\mantid\simpleapi.py", line 1076, in call
raise RuntimeError(msg) from e
RuntimeError: FilterEvents-v1: Inelastic instrument detector 0 of spectrum 0 does not have EFixed
```

**Comment by thomashampson** [comment]
We found that the minimum and maximum value boxes would cause mantid to throw an error if a minus was entered into them. Also if you type loads of numbers into the max box so that it goes above int max.
