### ISSUE TITLE
Buttons misaligned in the Elwin tab

### ISSUE THREAD

**Issue by jhaigh0** [mantidproject/mantid#36072]
**Describe the bug**

In the Inelastic data manipulation interface Elwin tab, we thought the bottom row of buttons including `Plot Current Preview` should be under the plot to match where it is found in other Inelastic tabs.

This isn't a regression, just caused a bit of confusing in manual testing. 

**Expected behaviour**
Buttons should be moved up to under the plot 

**Screenshots**
![267301567-b07160c4-7efa-4e70-9e3d-253b812e0c09](https://github.com/mantidproject/mantid/assets/35813666/a95b4926-b656-4dd6-9ea5-c44e636007f8)

**Comment by SpencerHowells** [comment]
@jhaigh0 Good idea
