### ISSUE TITLE
Changing x-axis from log to linear does not update plot curve

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36098]
**Describe the bug**
The plot curve will not be correctly updated when setting the x-axis to log scale then back to linear scale in a spectrum plot.

**To Reproduce**
1. Load a workspace and plot a spectrum.
2. Open the axis editor dialog by double clicking the numbers on the axis.
3. Set axis to log and click OK.
4. Open the axis editor dialog again, set to linear and click OK.
5. The range will be correct, but the plot curve looks like it hasn't been updated.

**Expected behavior**
Plot should update correctly.

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/8058899/29c3756a-4ffc-4b8e-8f6b-0762341b8099)

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: 6.7, maybe earlier?

**Comment by jclarkeSTFC** [comment]
Updating to matplotlib 3.7.3 fixes this problem (on Windows at least).
