### ISSUE TITLE
Welcome message missing from messages widget

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36095]
**Describe the bug**
When launching mantid workbench, the welcome message is not displayed. This is a regression since the last release. Note that if you launch from within the terminal, the `notice` level message is printed there.

**To Reproduce**
Open mantid workbench

**Expected behavior**
Welcome message displayed, e.g:
```
Welcome to Mantid 6.7.0
Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid6.7
All instrument definitions up to date
```

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/8058899/bf4500b1-0587-4143-a397-ff0093a8ef0b)

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version 6.7 nightly used in manual testing.

**Comment by jclarkeSTFC** [comment]
Merged PR #36126
