### ISSUE TITLE
Update ISIS SANS manual testing docs

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#36114]
The following points need to be updated in the ISIS SANS manual testing docs:
- In the User Files section, step 4 is unclear and `MaskFile.txt` cannot be located in the sample data.
- In the Processing section, the file format of the output in instruction 6 is h5 not nxs (4 h5 workspace)

**Comment by rbauststfc** [comment]
In addition to the items included in the description, for the last couple of release periods we've had questions raised about the auto-switching save option functionality in the GUI. We should ask our SANS scientists to do some thorough testing of this functionality and confirm if the issues raised are bugs or intended behaviour. Anything that our scientists confirm to be intended behaviour should be explained to some extent in the manual testing instructions to avoid future confusion.
