### ISSUE TITLE
Auto Switching in save options is not working as expected in ISIS SANS Reduction GUI 

### ISSUE THREAD

**Issue by warunawickramasingha** [mantidproject/mantid#36115]
**Describe the bug**
**Please read [this comment](https://github.com/mantidproject/mantid/issues/36115#issuecomment-1853720297) for the change required by this issue.**

In ISIS SANS Reduction GUI, when switching the reduction options between 1D and 2D, the save options are expected to automatically switch between CanSAS and NXcanSAS. However after ticking and unticking RKH (1D/2D) option, the above behaviour is not observed

**To Reproduce**
1. Get the Training data from the downloads page on the Mantid Project website.
2. Open Interfaces > SANS > ISIS SANS.
3. Click Manage Directories. This opens Mantid’s main dialog for managing search paths. Ensure the Training data directory is in the search directories.
4. If you haven’t set one up yet, add a folder to save test data into later.
5. Set the default save directory in Manage Directories
6. Click OK on the manage-directories dialog and ensure the Save Path on the SANS GUI (below batch file) displays the correct save path.
7. Click Load User File; from the Training data in the loqdemo folder, choose MaskFile.toml.
8. Click Load Batch File; from the Training data in the loqdemo folder, choose batch_mode_reduction.csv.
9. Switch between 1D and 2D at the bottom of the screen, it should automatically switch between CanSAS and NXcanSAS
10. tick and untick RKH option and observe step 9.

**Expected behavior**
Switch between 1D and 2D, it should automatically switch between CanSAS and NXcanSAS

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: 6.7

**Comment by rbauststfc** [comment]
We should discuss this with SANS to confirm the expected behaviour before starting work on this.

**Comment by warunawickramasingha** [comment]
> We should discuss this with SANS to confirm the expected behaviour before starting work on this.

This issue was raised while following the test instructions for https://developer.mantidproject.org/Testing/SANSGUI/ISISSANSGUITests.html#id4
