### ISSUE TITLE
`ConvertDiffCal` signed mode incorrectly invalidating for offset<=-1

### ISSUE THREAD

**Issue by rboston628** [mantidproject/mantid#36121]
**Describe the bug**

The algorithm `ConvertDiffCal ` was recently edited to accept a signed offset mode, using the logarithmic formula

$DIFC_{new} = DIFC_{old} * (1 + |BinWidth|)^{-offset}$

which is appropriate to full-spectrum calibrations.  This formula is incapable of producing a negative value of $DIFC_{new}$.

In relative/absolute offset mode, the formula to update is

$DIFC_{new} = DIFC_{old}/(1 + offset)$,

which could produce negative $DIFC_{new}$, and therefore the original code had the check, [L144-L148](https://github.com/mantidproject/mantid/blob/c4e33c67c9f732ebdd27d7308133024df8a675b2/Framework/Algorithms/src/ConvertDiffCal.cpp#L144), which throws an error for offsets which could lead to negative $DIFC$ value:

``` cpp
double getOffset(const OffsetsWorkspace_const_sptr &offsetsWS, const detid_t detid) {
  const double offset = offsetsWS->getValue(detid, 0.0);
  if (offset <= -1.) { // non-physical
    std::stringstream msg;
    msg << "Encountered offset of " << offset << " which converts data to negative d-spacing for detectorID " << detid
        << "\n";
    throw std::logic_error(msg.str());
  }
  return offset;
}
```

This check was accidentally used when implementing the new signed mode, leading to invalid errors being thrown when trying to use this method.  See [L190](https://github.com/mantidproject/mantid/blob/c4e33c67c9f732ebdd27d7308133024df8a675b2/Framework/Algorithms/src/ConvertDiffCal.cpp#L190):

``` cpp
double updateSignedDIFC(const OffsetsWorkspace_const_sptr &offsetsWS, const size_t index, const double oldDIFC,
                        const double binWidth) {
  const detid_t detid = getDetID(offsetsWS, index);
  const double offset = getOffset(offsetsWS, detid); // calls the above method, which throws an error!
  const double newDIFC = oldDIFC * pow(1.0 + fabs(binWidth), -1.0 * offset);
  return newDIFC;
}
```

**To Reproduce**

1. Create an offsets workspace with offsets <= -1.  
2. Try to run this algorithm in absolute mode.  It should throw an error, because this creates an unphysical situation.  
3. Now try to run in *signed* mode.  It should *NOT* throw an error, but it will.  

This is the bug.

**Expected behavior**

When run in signed mode, the algorithm should be able to handle offsets of any size.  There is no risk of creating negative $DIFC$ in this mode.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: all
 - OS Version: all
 - Mantid Version 6.8.0

**Additional context**

This can be very easily fixed, but perhaps the real fix is to invalidate when $DIFC_{new}$ is calculated, and not when the offsets are retrieved.

**Comment by sf1919** [comment]
Has this been fixed by #36163 ? Can this issue be closed?
