### ISSUE TITLE
Algorithm required for calculating efficiency of ISIS SANS polariser

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36139]
A new algorithm is required to calculate the efficiency of the supermirror polariser. This is required for the Polarised SANS reduction at ISIS and is included in the MVP for the epic.

The algorithm will be used in advance as part of commissioning to calculate the polariser efficiency from a calibration measurement and save the result as a Nexus file. To help ensure that nothing has gone wrong with the experimental setup, the scientists also want to call this algorithm as part of the reduction workflow to calculate the efficiency from the actual experiment measurements and compare it to the commissioning reference file, so it may not be necessary for the algorithm to always save it's output to file.

### Maths

Polarization:

$$
\huge P_{SM} = \frac{T_{00} - T_{01}}{2P_{cell}(T_{00} + T_{01})} = \frac{T_{00} - T_{01}}{2(2\epsilon_{cell} - 1)(T_{00} + T_{01})}
$$

Efficiency (this is the equation that the algorithm should implement):

$$
\huge \epsilon_{SM} = \frac{1}{2} + \frac{T_{00} - T_{01}}{4(2\epsilon_{cell} - 1)(T_{00} + T_{01})}
$$

Error calculation:

$$
\huge \sigma_{\epsilon_{SM}} = \sqrt{|\frac{\delta \epsilon_{SM}}{\delta T_{00}}|^2 * \sigma^2_{T_{00}} + |\frac{\delta \epsilon_{SM}}{\delta T_{01}}|^2 * \sigma^2_{T_{01}} + |\frac{\delta \epsilon_{SM}}{\delta \epsilon_{cell}}|^2 * \sigma^2_{\epsilon_{cell}}}
$$

where:

$$
\huge \frac{\delta \epsilon_{SM}}{\delta T_{00}} = \frac{T_{01}}{2(2\epsilon_{cell} - 1)(T_{00} + T_{01})^2}
$$

$$
\huge \frac{\delta \epsilon_{SM}}{\delta T_{01}} = \frac{-T_{00}}{2(2\epsilon_{cell} - 1)(T_{00} + T_{01})^2}
$$

$$
\huge \frac{\delta \epsilon_{SM}}{\delta \epsilon_{cell}} = \frac{T_{01} - T_{00}}{2(2\epsilon_{cell} - 1)^2(T_{00} + T_{01})}
$$

### Workflow
- Inputs: 
  - He3 Analyser Efficiency from #36140
  - Measured transmission through instrument. Expect to use the same transmission run (empty cell) as for the flipper efficiency calculation, so will have four spin states even though only two are used in the final calculation.

We need to calculate errors explicitly and not rely on the default Mantid error calculation for this algorithm.

**Comment by dehoni** [comment]
Extract supermirror polarisation from beamline polarisation determined with a supermirror +3He setup. The performance of the 3He analyser is known (characterisation with unpolarised beam, fitting the time dependence parameter + analytical equation to obtain performance for a given time stamp ). 
Simple ratio between transmission measurements and polarisation efficiecy of He analyser cell.

def calculate_polariser(strname,PHe,Error_PHe time, lamdata): 
        Tpara(time,lamdata, idealise,no="0")    #estimated transmission for wanted spin state through 3He analyser for time stamp of measurement
        TparaPSM=mtd['T_para_eff_ws_0'] #measured transmission through the instrument at time
        Tanti(time,lamdata, idealise,no="0")    # same for unwanted spin state
        TantiPSM=mtd['T_anti_eff_ws_0']
        P_analyser= (TparaPSM-TantiPSM)/ (TantiPSM+TparaPSM)
        Divide(LHSWorkspace=PA, RHSWorkspace=P_analyser, OutputWorkspace='PSM_'+strname)
