### ISSUE TITLE
New math functions required for hyperbolic trigonometry

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36137]
Required to support the Polarised SANS reduction at ISIS.

From Dirk:
It will be important to check the errors as part of the acceptance criteria for this issue. The error calculation should be quite sensitive for the hyperbolic functions close to diverging extreme values for arccosh and arctanh, which will be required. It is the similar issue as for [AsymmetryCalc](https://docs.mantidproject.org/nightly/algorithms/AsymmetryCalc-v1.html) for Muons.

## Context

The intention is that these functions will be used for fitting to `acosh`, `cosh`, `atanh`, and `tanh`. 

## Implementation

Given this, it's possible that making use of [UserFunction1D](https://docs.mantidproject.org/nightly/algorithms/UserFunction1D-v1.html) will do instead. It's possible this issue can be closed once we've had a chance to start on the creation of the depolarised transmission calculation (#36383).

If not, creating some new fit functions will be required.

**Comment by dehoni** [comment]
The time evolution of the transmission and polarisation of a polarised 3He analyser follows analytical expressions that involve hyperbolic functions. At least "arccosh" will be needed to calculate the opacity to measure the optical performance of the 3He cell.
The functions will be applied on a Mantid workspace defined and is can be defined as:
def arctanh(x):
    mtd['plus_ws']=1+x
    mtd['minus_ws']=1-x    
    Logarithm('plus_ws',OutputWorkspace='plus_ws')
    Logarithm('minus_ws',OutputWorkspace='minus_ws')
    Minus('plus_ws','minus_ws',OutputWorkspace='arctanh_ws')
    return 0.5*mtd['arctanh_ws']
    DeleteWorkspace('plus_ws')
    DeleteWorkspace('minus_ws')
    
def tanh(x):
    x=2*x
    Exponential(x,OutputWorkspace='exp')
    mtd['minus_ws']=mtd[exp]-1
    mtd['plus_ws']=mtd[exp]+1
    Divide('minus_ws','plus_ws',OutputWorkspace='tanh_ws')
    DeleteWorkspace('minus_ws')
    DeleteWorkspace('plus_ws')   

def arccosh(x):
    Power(x,Exponent=2,OutputWorkspace='ws')
    mtd['ws']=mtd['ws']-1
    Power('ws',Exponent=0.5,OutputWorkspace='ws')
    mtd['ws']=mtd['ws']+x
    Logarithm('ws',OutputWorkspace='ws')
    return mtd["ws"]

**Comment by cailafinn** [comment]
https://docs.mantidproject.org/nightly/algorithms/UserFunction1D-v1.html?highlight=userfunction1d

**Comment by cailafinn** [comment]
No longer required, functions provided by UserFunction1D & efficiencies being calculated directly.
