### ISSUE TITLE
Algorithm required for calculating ISIS SANS analyser efficiencies

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36140]
An algorithm is required to calculate the efficiency of the 3He analyser based on one measurement. This calculation will make use of hyperbolic functions created under issue #36137.

The algorithm will need to take a list of run numbers and also the transmission/opacity calculated from #36383. It will output the polarisation efficiency as a function of wavelength, for each run.

Under issue #36142, a step will be added later in the overall Polarised SANS workflow to take into account the time of each run to find the time-dependent polarisation efficiency.

This is required for the Polarised SANS reduction.

## Calculations
  - Calculate the efficiency of the cell, `P`, from `(Tnsf-Tsf)/(Tnsf+Tsf)` using data from a run, where `Tnsf = T00 + T11` and `Tsf = T01 + T10`.
  - We can then fit `P = tanh(μ * pHe)` to get `pHe`.
    - P is the measured efficiency for the given data
    - pHe is the analyser efficiency

## Workflow Steps

- [ ] Inputs: 
    - [ ] Run number to load
    - [ ] Period positions (++ and +- needed for this step)
    - [ ] `p * d` and `T_E` (Fit params from Transmission Calc)
- [ ] Load input run
- [ ] Calculate `P` using the above equation
- [ ] Fit `P = tanh(μ * pHe)` to get `pHe`
- [ ] Outputs:
  - [ ] Single spectra output for wavelength-dependent efficiency
  - [ ] Fit Params (`pHe`)

**Comment by dehoni** [comment]
In order to get later corrected data in absolute units, it should output the transmission of the wanted and unwanted spin state through the device as a function of wavelength, for each run. Having this the polarization efficiency is easy to calculates.
