### ISSUE TITLE
Algorithm required for determining relative time between measurement in Pol-SANS

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36141]
A new algorithm is required that can determine the relative time between measurements, for use in the ISIS Polarised SANS reduction.

Requirements for this still need to be gathered.

**Comment by dehoni** [comment]
The code finds the time stamp of the measurement relative to the start of the lifetime. The transmission and polarisation of the 3He gas is then calculated for that time stamp based on the parameters established earlier in the calibration for the 3He cell.

**Comment by rbauststfc** [comment]
Closed as a duplicate of #36142
