### ISSUE TITLE
Algorithm required to calculate the efficiency of the ISIS SANS spin flipper

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36144]
An algorithm is required to calculate the efficiency of the two spin flippers. This is required for the Polarised SANS reduction at ISIS. Calculating the efficiency of just one of the spin flippers is required for the epic MVP, as SANS are currently only using a single flipper in their setup. They would like the flexibility to support two in the future, though, so the full scope implementation will calculate the efficiency of two flippers.

The algorithm will be used in advance as part of commissioning, rather than calculating the flipper efficiency during the normal polarised SANS reduction workflow. A calibration measurement will be taken and the algorithm will be used to calculate the flipper efficiency and save the result as a Nexus file. This is not expected to vary between experiments, so the file can ultimately be read into the reduction workflow from the user file.

## Math
 `Ixx` represents the configuration of the flipper.

Polarisation:

$$
\Huge P_F = \frac{(\frac{I_{00} - I_{10}}{I_{00} + I_{10}})}{(\frac{I_{11} - I_{01}}{I_{11} + I_{01}})}
$$

Efficiency:

$$
\huge \epsilon_{F} = \frac
{T_{00} - T_{01} + T_{11} - T_{10}}
{2(T_{00} - T_{01})}
$$

This applies if there is only one flipper, according to Wildes 2006.

## Workflow
- [x] Input: 
  - [x] One GroupWorkspace containing 4 periods, assignments of these 4 periods. 
  - [x] Optional output filename/path
- [ ] Perform the above equation.
- [ ] Output:
  - [ ] Output the resulting workspace to the ADS
  - [ ] If the filename is given, output to the directory in ManageUserDirectories
  - [ ] If a full path if given, output there. 

Requirements for this still need to be gathered.

**Comment by dehoni** [comment]
There is only one algorithm to determine the efficiency of a flipper on the incoming instrument site. We will take care that we expose a variable that shows if the instrument is in a flipper on/off state via a block in IBEX. The efficiency is calculated by simple linear combination and ratios of worksheets.
Below is a code example to calculate the Flipper efficiency PF and the combined polarizer and analyzer efficiency PA. PA will be used further in #36139.
def calculate_beam_polarisation(strname): 
        strname=str(rnum)+"_trans"
        output1=Plus(strname+"_"+nsf1,strname+"_"+nsf2)
        output2=Plus(strname+"_"+sf1,strname+"_"+sf2)         
        output5=Minus(strname+"_"+nsf2,strname+"_"+sf1)
        output6=Minus(strname+"_"+nsf1,strname+"_"+sf2)
        output7=Plus(strname+"_"+nsf2,strname+"_"+sf1)
        output8=Plus(strname+"_"+nsf1,strname+"_"+sf2)        
        PA=Divide(LHSWorkspace=output5, RHSWorkspace=output7, OutputWorkspace='PA_'+strname)
        PF=Divide(LHSWorkspace=output6/output8,RHSWorkspace=PA, OutputWorkspace='PF_'+strname)
