### ISSUE TITLE
Policy for using pip packages in Mantid

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36152]
**Description**

I'm not aware if we have an explicit policy on what should be done when we want to use a pip package in Mantid (specifically for a conda install). The current general feeling surrounding this is:
1. We do not want to include a pip package as a dependency in our conda recipes. Reason: there is no guarantee of compatibility between the two package managers, and using them simultaneously may lead to issues down the line when trying to resolve a pipeline failure due to a dependency problem.

2. It then makes little sense to push this dependency problem downstream by attempting to install the missing pip packages in our DAaaS workspace configuration repo. It seems like bad practise to install dependencies of a software in a completely detached way like this

**Potential solution**

We should strongly encourage our dependencies to be built into conda packages and uploaded to conda-forge. In the case where we **need** to use a pip package, we should make it clear that we do not take responsibility for the automatic install of this dependency, and it should be installed by a user. We would therefore need to ensure the following:
- It should be possible to pip install into the Mantid conda environment on IDAaaS (doesn't seem to be possible atm) @MialLewis 
- We should provide documentation on how to pip install into the Mantid conda environment @robertapplin 
- We should display warnings in the code which link to this documentation page when someone tries to use a pip package which isn't installed @robertapplin 

From the top of my head, Mantid has the following pip dependencies `quasielasticbayes` , `quickBayes`, `gofit`

**Comment by robertapplin** [comment]
As part of updating documentation, I will be working on these issues:
- https://github.com/mantidproject/mantid/issues/36149 (targeted at release-next)
- https://github.com/mantidproject/mantid/issues/35835 (targeted at main as its dev docs)

**Comment by AnthonyLim23** [comment]
Its not possible to add quickBayes until gofit is on conda https://github.com/conda-forge/staged-recipes/pull/23976 so we could do with a workaround. At this rate it is unlikely for quickBayes to be on conda before release.

**Comment by MialLewis** [comment]
Do you know where we are with putting `gofit` on conda-forge - is it something we can do instead of relying on the `gofit` team?

**Comment by AnthonyLim23** [comment]
I just know the link that I shared. They are happy to look after it, the slow down is conda forge

**Comment by jfowkes** [comment]
@MialLewis the `gofit` conda-forge package has been ready for over a week, we are awaiting a review from the conga-forge team so that it can be merged...

**Comment by MialLewis** [comment]
> @MialLewis the `gofit` conda-forge package has been ready for over a week, we are awaiting a review from the conga-forge team so that it can be merged...

I saw that, frustrating! I added something to `conda-forg`e last year and it was reviewed on the same day!

**Comment by jfowkes** [comment]
Yeah I think we added the wrong label (`python` instead of `python-c`) and there doesn't seem to be away to change how it's tagged which probably doesn't help!

**Comment by robertapplin** [comment]
Closing because this is complete -  we have pip policy documentation
