### ISSUE TITLE
Add Documentation for MagnetismReflectometryReduction

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/mantid#36161]
**Describe the outcome that is desired.**
A documentation page should be available for the algorithm so the ? button doesn't redirect to a 404 page. 

**Describe any solutions you are considering**
None

**Additional context**

**Comment by sf1919** [comment]
As there is a link to the missing documentation from the release notes then I'm switching this to 6.8 milestone as it definitely needs to be done before release!
