### ISSUE TITLE
Investigate SANS2D Instrument View Cylindrical Y 

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36205]
**Original reporter:** Najet Mahmoudi, Stephen King

**Describe the bug**
The cylindrical Y rendering on Mantid 6.7 and nightly is not what is expected for SANS2D's two detectors.

**To Reproduce**

1. Open Workbench
2. Open `Manage User Directories` and turn on Data archive
3. Load the following file 
```
//isis.cclrc.ac.uk/inst$/NDXSANS2D/Instrument/data/cycle_23_3/SANS2D00081862.nxs
```
4. Right click the workspace and `Show instrument`
5. Change the top option to "Cylindrical Y"
6. Check the result against an earlier version of Mantid (It works in Mantid v6.6) 

**Screenshots**
At the moment they see:
![image](https://github.com/mantidproject/mantid/assets/40830825/9be9ca46-c38c-49bb-8199-624fa483326c)

It is usual this:
![image](https://github.com/mantidproject/mantid/assets/40830825/523798c7-345b-446f-bb3e-d80237fd4715)

**Platform/Version (please complete the following information):**
 - OS: Found on Windows, but I assume its the same on all others
 - Mantid Version 6.7 and nightly

**Comment by robertapplin** [comment]
The issue exists in v6.7 so is not a regression that needs considering for v6.8

**Comment by rbauststfc** [comment]
Having a quick look on IDAaaS, one difference between 6.6 and 6.7 is that a new "Maintain Aspect Ratio" option was added to Render -> Display Settings in the Instrument Viewer. If you uncheck this new option in 6.7 the size of the detectors seem to start matching what is rendered in 6.6.

**Comment by rbauststfc** [comment]
I'm not sure why, but when I test this on IDAaaS I see slightly different differences to the screenshots above. I get the following:

6.6:
![6 6](https://github.com/mantidproject/mantid/assets/38210467/2403c559-9e33-4a66-a386-b0c5b6808a36)

Nightly:
![6 7_default](https://github.com/mantidproject/mantid/assets/38210467/9464fba8-1927-474c-859d-e65a542621b7)

Nightly (with Maintain Aspect Ratio unticked):
![6 7_noaspectratio](https://github.com/mantidproject/mantid/assets/38210467/8b19641f-4e49-4784-b485-d118fbb00dd2)

**Comment by RichardWaiteSTFC** [comment]
I think the `Maintain Aspect Ratio` option was added for SXD so that the square detector arrays appeared square...It seems it is enabled/True by default, but I think it should be False by default and workbench should remember the setting next time you open the instrument view (which it doesn't - it always reverts to default). Would that work for everyone else?

**Comment by smk78** [comment]
Thanks for investigating @robertapplin , @rbauststfc and @RichardWaiteSTFC . We were unaware of the `Maintain Aspect Ratio` option.

The SANS2D detectors are also approximately square so maybe there is a sort of logic to leaving the option True, although we would untick it to use the view for the purpose we intended (eg, creating masks).

As an aside on Mantid on IDAaaS doing it's own thing, is was using it last week and the 3D View was always greyed out!

**Comment by RichardWaiteSTFC** [comment]
> As an aside on Mantid on IDAaaS doing it's own thing, is was using it last week and the 3D View was always greyed out!

@smk78 The 3D view on IDAaaS requires OpenGL to be enabled (you can do this in the display settings in instrument view or in the workbench settings (General tab, Instrument section) - maybe it's worth checking is set correctly?

**Comment by rbauststfc** [comment]
@smk78 I just stumbled across this issue again - is there anything further that you need from us on this, or could this ticket be closed now?

**Comment by smk78** [comment]
Just testing Instrument View on W10/x64 with Mantid 6.10.0 I can sometimes* get the CylindricalY view I expect, so from that perspective I will close this ticket.

*and raise some odd behaviour I am seeing with mantidhelp.
