### ISSUE TITLE
Indirect Settings Usage statistics are misleading

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36230]
**Describe the bug**
The usage statistics for the Indirect Settings interface stored by the Usage Reporter are misleadingly high. I believe this is because whenever an IndirectInterface instance is created, a IndirectSettingsInterface is also created immediately (even if Indirect Settings hasn't been open). We should only create an Indirect Settings interface if the settings button is clicked - and this should fix the misleadingly high usage statistics.

**To Reproduce**
Log on to the Usage reporter
Search for the usage statistics for the IndirectSettings interface
It is roughly the total of all Indirect interfaces put together

**Expected behavior**
The usage statistics for the IndirectSettings interface should only record the number of times the interface was opened.

**Comment by MialLewis** [comment]
I was looking at the usage reporter the other day, and notice that the `GeneratePythonScript` algorithm has supposedly been used  56 billion times...
