### ISSUE TITLE
GSAS-II tab in EngDiffUI doesn't let user change TOF limits for fit

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#36318]
**Original reporter:** Tung Lik (ENGINX)

**Describe the bug**
GSAS-II tab in EngDiffUI doesn't let user change TOF limits for fit

**To Reproduce**
Not reproduced yet...

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by warunawickramasingha** [comment]
This issue is not re-creatable and hence closing. 
However, during the investigation, #36568 was raised after contacting the instrument scientist.
