### ISSUE TITLE
Move Data Manipulation GUI files

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36323]
**Describe the outcome that is desired.**
We would like to move the files used for the Data Manipulation GUI to the `qt/scientific_interfaces/Inelastic/Manipulation` folder location. This includes moving the test files for this interface to a `qt/scientific_interfaces/Inelastic/Mantipulation/test` location. 

The desired structure for the new Inelastic category is

```
qt/scientific_interfaces/Inelastic
    -> Analysis/
        *.cpp
        *.h
        -> test/
    -> Manipulation/
        *.cpp
        *.h
        -> test/
```

**Comment by adriazalvarez** [comment]
I have made this a part of #35665 for easing that issue. So we can close this one now.
