### ISSUE TITLE
Move Data Corrections to new category

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36355]
**Is your feature request related to a problem? Please describe.**
The Data Corrections interface in the Indirect category can be used for all instruments relating to indirect, direct and diffraction. It therefore makes sense that the category in which this interface sits should be changed. As part of this, the interface files should be moved to a new folder along with any test files (although I don't know if any tests exist for the GUI parts of this interface).

**Describe the solution you'd like**
One option might be to create a new interface category called 'Corrections'. Another option might be to move the Corrections interface into the 'Inelastic' and 'Diffraction' categories. I might prefer the second option because the categories tend to be based along the line of techniques (although this is not always the case as we have a 'General' category).

**Acceptance Criteria**
- The Corrections interface and its files have been moved to the `Inelastic/Corrections` folder
- The Corrections interface is accessible from the `Inelastic` interface categories
- The Corrections file names, and contents of the files, use the term `Inelastic` instead of `Indirect`

Its been decided that moving the Corrections interface to the Diffraction interface category as well will not add much benefit at present because they do their corrections in their reductions scripts. If this changes in the future then we can think about doing this again.

**Comment by SpencerHowells** [comment]
@robertapplin I agree that the second option might be best
