### ISSUE TITLE
One input table row per workspace in Elwin

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36372]
**Is your feature request related to a problem? Please describe.**
The workspace input table for the Elwin tab on the Data Manipulation interface is inappropriate for scans involving 100's of spectra, because it will show each spectra on a different row. In this tab, there is no benefit from having separate rows for each spectra. We should consider making it possible to have one row to represent all the spectra in the same workspace.

Note that in the other tabs that use the workspace input table, it **is** necessary to have separate rows for each spectra, so that you can specify different fitting ranges.

We will also want to be able to modify which spectra from the workspace are loaded.

**Describe the solution you'd like**
We should add a configuration option to the workspace input table that allows you to say if you want all the spectra for one workspace to be in a single row. The default behaviour should be to have one row per spectra.

**Comment by SpencerHowells** [comment]
I lilke having the option. When this tab works properly we could then remove the other one.
