### ISSUE TITLE
Algorithm required for calculating transmission of the analyser

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36383]
An algorithm is required to calculate the depolarised transmission of the helium gas in the analyser. The algorithm will take two calibration runs (with four periods each) and use these to calculate the opacity as a function of wavelength. The output of this algorithm is intended to be passed to #36140 for calculating the polarised efficiency of the analyser.

The algorithm will make use of relevant hyperbolic functions that will be created under #36137.

This is required for the Polarised SANS reduction at ISIS.

## Context:
- At the end of an He3 cell’s life, the depolarised transmission though it needs to be calculated. 
- To do this, it is completely depolarised, and two calibration runs/workspaces are created:
  - One with the depolarised helium in the cell (referred to in the meeting as “dep”)
  - One with an empty cell containing nothing (referred to as “MT”)
- The pair of runs are created for each cell used.
- The input may contain 1, 2, or 4 periods. The signs (++, +-, -+, --) refer to the polarisation direction of the [polariser and flipper], and the [analyser] respectively. Which is which must be determined by looking at the `SPIN_FLIPPER` sample log and the Intensity, as there is no way to store the polarisation direction of the analyser. Cross polarisation (+-, -+) will result in a strong drop in intensity (beyond a certain wavelength (~3.5 Angstroms)). 

### Monitor setup
- `|P| |F| 3 |Sam| 6 |He3| 4   5|Det|`
  - M3 is in the correct position
  - M4 is optional, and may be removed. It may also need moving. 
  - M5 is in the middle of the detector, and is useless if M4 is in place. 
  - M6 is not currently present, and is part of future development work. 
- Monitors (1-5) follow the workspace positions, (M1 = WSIndex 0, etc.)
- Monitor 4 is normalised by monitor 3 to account for changes in the incoming beam. 

### Current Script:
- There are a couple of MoveComponent operations required due to the movement of monitors. This will not be needed for the final data as the monitors will be in the correct positions.

### New Implementation:
- Polarisation information needs to be determined. (I.e. which of the workspaces is each polarisation orientation)
- M4 needs to be normalised by M3 to account for changes in the incident beam.
- The algorithm should take these two runs and produce a workspace of wavelength against transmission.
- This is done by:
  - Dividing the “`dep`” workspace by the “`MT`” workspace.
  - When depolarized, `pHe = 0` therefore `T(λ) = T_E(λ) * exp(-μ)`.
  - We can then perform a fit to obtain `T_E` and `p * d` where `μ = 0.0733 * p * d * λ`.
    - The `0.0733` is a factor to allow the conversion between wavelength (λ) and the absorption cross-section. 

## Technical Decisions to Make
- [x] C++ vs Python
  - C++ is better suited to dealing with workspace groups (which is likely how the different periods will be handled) and is faster, so is probably the choice we're going to go with. 
- [x] Input workspaces from the examples seem to contain 8 spectra. Which of these are important?

## Workflow Steps
- [x] Input: Two workspaces, 
    - [x] `dep` (depolarised)
    - [x] `mt` (empty cell)
    - [ ] Input Validation of these workspaces
        - Wavelength, single spectra. Both have the same number of bins and bin width.  
- [x] Divide (see above)
- [x] Fit UserFunction1D (`Formula=T_E * exp(-0.0733 * pxd * x`) (As the workspace x values are wavelength (λ))
   - [x] Starting values `te=0.9` `pxd=12.6`
- [x] Output: 
  - [x] Fit params: `p * d` (`pxd`), `T_E` (transmission of empty cell)

**Comment by jclarkeSTFC** [comment]
The analyser they installed this afternoon had a length of 5 cm and a pressure of 850 mBar, could be useful for benchmarking p*d results.
