### ISSUE TITLE
ConvFit 1L and Flat Background Fit Regression

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36623]
**Describe the bug**
There is a regression when doing a ConvFit on the Inelastic Data Analysis interface using one Lorentzian and a Flat Background.
This gives a poor result in the nightly, but it previously gave a good result in v6.8.

**To Reproduce**

1. Open Inelastic Data Analysis interface
2. Go to the ConvFit tab
3. Load the following data
4. Select 1 Lorentzian and a Flat Background
5. Click Run
6. The fit is poor:
![image](https://github.com/mantidproject/mantid/assets/40830825/9061d2d7-b458-40cb-9a0c-f96d620af97f)

**Expected behavior**
![image](https://github.com/mantidproject/mantid/assets/40830825/cd25b4dd-3d64-49de-972f-b306e13d8c67)

**Platform/Version (please complete the following information):**
 - OS: Windows and Linux. Probably osx too

**Comment by SpencerHowells** [comment]
@robertapplin Seems to be Ok on latest nightly  ...01.08

**Comment by SpencerHowells** [comment]
@robertapplin Done more testing. Started with 1L+bgd and ran Ok. Changed to StretchedExpFT and it ran OK. Went back to 1L+bgd but it didn't calulate start parameters. I did the single spectrum fit and that was Ok and thereafter the sequence was Ok.
