### ISSUE TITLE
Crash with attempt at opening Rebin dialog

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#36689]
**Describe the bug**

Workbench disappears with no error reporter

**To Reproduce**
- Load ZOOM 22699
- Type `Rebin` into the algorithm box in the bottom left, select the `Rebin` algorithm, press enter

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mantid Version 6.8 and latest 6.9 debug build

**Comment by cailafinn** [comment]
Closed via 
- #36768
