### ISSUE TITLE
Missing signal warning on Data Analysis Interface.

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#36710]
**Describe the bug**

There is a QObject missing signal warning on the view of the Data Analysis interface, likely caused by the refactoring of the presenter. 

**To Reproduce**

1. Open workbench from conda. 
2. Open Data Analysis interface
3. Warning should be issued on the console. 

**Expected behavior**

The warning should not be there.

**Platform/Version (please complete the following information):**
 - OS: Windows10
 - OS Version:
 - Mantid Version 6.9

**Additional context**

Added to 6.10 milestone, as it is not a critical issue for next release.

**Comment by robertapplin** [comment]
Looks like this is fixed by #36624

**Comment by adriazalvarez** [comment]
Yes, probably. I'll closed it then once the other is merged.

**Comment by sf1919** [comment]
I've changed the milestone as it will go into v6.9

**Comment by sf1919** [comment]
Can this now be closed?

**Comment by adriazalvarez** [comment]
Fixed by #36624
