### ISSUE TITLE
Sliceviewer: Log colourbar scale option not disabled outside data. 

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#36724]
**Describe the bug**
Manual testing instructions say
> "Zoom in to a region outside the extent of the data, check the Log colorscale option is disabled."

This does not occur. 

**To Reproduce**
https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html

1. Load some data
2. Open the sliceviewer
3. Move the view outside the data
4. Switch to log
5. This should not be possible. 

**Expected behavior**
Either log scaling should be disabled or the manual testing instructions should be updated. 

**Platform/Version (please complete the following information):**
 - OS: macOS
 - OS Version: 14 Sonoma
 - Mantid Version 6.8

**Comment by jhaigh0** [comment]
This is fixed by this pr https://github.com/mantidproject/mantid/pull/37486
