### ISSUE TITLE
Unhandled exception when plotting live data from fake histogram instrument

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36726]
**Describe the bug**

Found during manual testing for the 6.9 release (#36702). Trying to open a plot on a workspace that is being updated with data from the fake `ISIS_Histogram` instrument causes an unhandled exception. In Mantid version 6.8 this would log an error message but not trigger the unhandled exception, so it appears to be a regression.

**To Reproduce**

Go through the following steps from the live data manual testing instructions to get the live data running:

1) https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html#set-up-the-test-facility
1) https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html#isis-histogram
1) https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html#starting-a-live-data-session (just steps 1 and 2 here)
1) https://developer.mantidproject.org/Testing/LiveData/LiveDataTests.html#live-histogram-data

Then, with live data running, right click on the workspace in the ADS and try to open a plot (select a single spectrum to plot). This should cause an unhandled exception.

**Expected behavior**

In previous versions an error was logged but it didn't cause the unhandled exception.

**Platform/Version (please complete the following information):**
 - Mantid Version - introduced since version 6.8.

**Comment by thomashampson** [comment]
For me this is throwing an unhandled exception in 6.8

**Comment by GuiMacielPereira** [comment]
Unassigning this from myself since I could not reproduce this issue on Linux (Pop_OS! 22.04).
