### ISSUE TITLE
Wrong format of output workspace in Data Manipulation Interface

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#36725]
**Describe the bug**

The issue occurs when selecting multiple workspace in input file of the Elwin tab in the Data Manipulation interface. Once the algorithm is run, the output workspace in the workspace don't have the correct name format. It seems to be appending a suffix at the beginning of the name. 

**To Reproduce**

1. Open `Inelastic -> Data Manipulation` interface and `Elwin` tab. 
2. On Input Field edit, click browse and multi-select files `irs26173_graphite002_red.nxs` and `irs26176_graphite002_red.nxs`. 
3. Click `Run` button. 
4. On the ADS, resulting workspaces (`_elf`  , `_eq` and `_eq2`) are named incorrectly, starting with the suffix `_red-267667173`

**Expected behavior**

Workspace name formatting should be corrected  (as in the attached screenshot) and the suffix shouldn't be at the beginning of the name. 
**Screenshots**

Incorrect format: 
![image](https://github.com/mantidproject/mantid/assets/146007827/b43e0a44-960a-4bb7-b553-a8c6b965530a)

Correct format: 
![image](https://github.com/mantidproject/mantid/assets/146007827/8d3728c7-d66e-4928-b4d5-3df8ba26e626)

**Platform/Version (please complete the following information):**
 - OS: Windows 10
 - Mantid Version 6.8 Latest Nightly

**Comment by robertapplin** [comment]
Fixed by  #36751
