### ISSUE TITLE
Not possible to un-fix parameters in fit browser

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36722]
**Describe the bug**
Not possible to remove the tie of a fixed variable in the fit property browser. It used to be possible to right click on a parameter and click "remove tie". Now it is not.

**To Reproduce**
1. Open the plot and the fit browser.
2. Add a Gaussian
3. Expand "f0-Gaussian"
4. fix one of the parameters
5. now try to un-fix it

For example
6. Click on '....'
7. Scroll down to '....'
8. See error
-->

**Expected behavior**
Context menu should allow you to remove the tie.

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/8058899/9d475274-adfd-4d40-85bc-0d24f33377e7)

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: introduced in 6.7

**Additional context**

**Comment by sf1919** [comment]
Fixed by #36752
