### ISSUE TITLE
plotSpectrum() hang

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36727]
**Describe the bug**
Running a script that contains the `plotSpectrum()` function can cause workbench to hang.

**To Reproduce**
Run this script a few times until it breaks:
```
RawData = Load("MAR11015")

# Assign original plot to a window called graph_spce
graph_spec = plotSpectrum(RawData, 0)

# Overplot on that window, without clearing it
plotSpectrum(RawData, 1, window=graph_spec, clearWindow=False)

```

also when running script B from this page - https://docs.mantidproject.org/nightly/tutorials/python_in_mantid/solutions/03_pim_sol.html#pim-sol

**Expected behavior**
No hang

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: manual testing nightly for 6.9 release: https://github.com/mantidproject/mantid/releases/tag/v6.8.20240123.1153

**Additional context**
Found while testing #36694 
I cannot get it to hang in 6.8

**Comment by sf1919** [comment]
Fixed by #36765
