### ISSUE TITLE
Unhandled Exception With Certain Colourmaps in the Sliceviewer

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/mantid#36723]
**Describe the bug**
An unhandled exception occurs when the normalisation is changed with certain colourmaps. 

**To Reproduce**

1. Start workbench
2. Load some data (MAR11060 from the training course data works well)
3. Right click and open sliceviewer
4. Change the colormap to `gist_rainbow`
5. Change the normalisation option (to or from `None`)
6. Unhandled Exception occurs.

**Expected behavior**
No errors occur. 

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Noted on macOS
 - OS Version: Sonoma (14)
 - Mantid Version: Present since 6.8 at least.

**Comment by jclarkeSTFC** [comment]
This also happens in Windows with Mantid 6.10
