### ISSUE TITLE
Fix workbench testing documentation

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#36731]
The information about this issue is incorrect. We no longer have groups 1-4 and the documentation that is linked also talked about grouped tests and the documentation not being up to date after v6.2

_Originally posted by @sf1919 in https://github.com/mantidproject/mantid/issues/36694#issuecomment-1907864454_

**Comment by perenon** [comment]
In [this page](https://developer.mantidproject.org/Testing/Core/Core.html) (referenced in the main documentation) the link to "3D and volumetric data" goes directly to [matplotlib documentation](https://matplotlib.org/stable/plot_types/3D/index.html#d-plots)

Also, the data used in [this section](https://docs.mantidproject.org/nightly/tutorials/python_in_mantid/plotting/01_basic_plot_scripting.html#d-surface-and-wireframe-plots) `PG3_733.nxs` does not appear in the standard Mantid Training Data

**Comment by jclarkeSTFC** [comment]
The issue name has been changed from "Groups 1-4" to "Core" in this PR (https://github.com/mantidproject/documents/pull/123), not yet merged at the time of writing.

The link that goes to the matplotlib documentation, that seems okay to me, is there somewhere in the Mantid docs that is more suitable?

The `PG3_733.nxs` file is in the Usage Examples folder, I could add a line to the docs saying where it is, unless all of the files used for these examples are supposed to be in a particular folder? In that case I cold just change which file is used for that plot to one that's in the SampleData-ISIS folder.
