### ISSUE TITLE
Engineering diffraction window disappears

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#36745]
Following the manual testing instructions (https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html), when doing test 7, point 6, performing a fit through Fit > Fit closed the Eng Diff tab. When the tab was opened again, the fit had been successful and no data was deleted.

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mantid Version 6.8.20240123.1153

**Comment by jclarkeSTFC** [comment]
I got this to happen in 6.8

**Comment by jclarkeSTFC** [comment]
I've just tried this in 6.9 and couldn't reproduce it

**Comment by warunawickramasingha** [comment]
Thanks James for updating. I also tried to re-create this in 6.9 but couldn't. Hence closing the issue.
