### ISSUE TITLE
GSAS II crash

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#36747]
Following the manual testing instructions (https://developer.mantidproject.org/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.html), when doing test 11, point 8, with the range 20000-45000, Mantid crashed due to a missing file error. The first run we did with GSAS II worked fine, but after changing the limits it didn't work again.

**Platform/Version (please complete the following information):**
 - OS: IDAaaS Rocky
 - OS Version: 8?
 - Mantid Version 6.8.20240123.1153

**Comment by warunawickramasingha** [comment]
This issue can be re-created on Mantid-6.6, 6.7 and 6.8 as well on IDAaaS. It occurs since GSAS-2 tool is not creating `<project_name>_cell_parameters_Fe_gamma.txt` file for the provided TOF range.

**Comment by warunawickramasingha** [comment]
#36772 was raised to investigate why the reflection files are not generated for some TOF ranges only on IDAaaS environments in comparison to the other OS such as Windows, and Linux which successfully created the output files for the same TOF range.

**Comment by warunawickramasingha** [comment]
Manually closing the issue since the fix is already merged and the GitHub action for auto-closing has not closed.
