### ISSUE TITLE
ILL SimpleScanViewer does not work with new version of matplotlib

### ISSUE THREAD

**Issue by perenon** [mantidproject/mantid#36758]
**Describe the bug**
ILL SimpleScanViewer does not work with new version of matplotlib. It crashed with 
```
  File "[...]/qt/python/mantidqtinterfaces/mantidqtinterfaces/simplescanviewer/rectangle_selection.py", line 53, in _release
    if self._drawtype != "none" and (
AttributeError: 'RectangleSelection' object has no attribute '_drawtype'
```

**To Reproduce**
1. Click Interfaces > ILL > SimpleScanViewer
2. Click "Browse" and select the file `Testing/Data/UnitTest/ILL/D16/025786.nxs`
3. Draw a rectangle in the plot, try to move it. The error should happen

**Expected behavior**
The error should not happen

**Platform/Version (please complete the following information):**
Found during manual testing of Mantid 6.9.0 on macOS 12.6 and ubuntu 22.04

**Comment by robertapplin** [comment]
Fixed by https://github.com/mantidproject/mantid/pull/36759
