### ISSUE TITLE
Access Violation when opening and using multiple AddWorkspaceDialog's

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36756]
**Describe the bug**
There is a bug when opening multiple `AddWorkspaceDialog's from the Inelastic Data Analysis interface, Data Manipulations interface and the Fit Script Generator interface. If you close the second dialog you open and then click `Add` on the first dialog, there is an access violation because the raw pointer for the dialog is now invalid.

**To Reproduce**

1. Open Inelastic Data Analysis interface
2. On any of the tabs, click `Add Workspace`
3. Click `Add Workspace` again so that you now have two dialogs open
4. Close the second dialog you opened
5. Click `Add` on the first dialog you opened
6. Access violation!

**Expected behavior**
It should be possible to open multiple dialogs without an access violation occuring

**Platform/Version (please complete the following information):**
 - OS: All

**Comment by sf1919** [comment]
Can this now be closed?

**Comment by robertapplin** [comment]
Fixed by https://github.com/mantidproject/mantid/pull/36624
