### ISSUE TITLE
Ability to provide custom and file detector grouping to `OSIRISDiffractionReduction` algorithm

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36762]
**Description**
We want two new options for the `OSIRISDiffractionReduction` algorithm: the ability to provide a custom grouping string for grouping the detectors, and the ability to provide a grouping file to the algorithm. We also want the ability to provide a number of groups. These properties should be implemented the same way as the corresponding properties we see for the ISIS Energy Transfer algorithm to keep consistency.

**Acceptance criteria**
- It should be possible to choose the GroupingMethod to be 'Custom', and to then provide a string to be used for detector grouping for the `OSIRISDiffractionReduction` algorithm
-  It should be possible to choose the GroupingMethod to be 'File', and to pass in a file to the algorithm.
-  It should be possible to choose the GroupingMethod to be 'Groups', and to pass in a number of groups to the algorithm.

**Comment by adriazalvarez** [comment]
It seems is possible to do grouping using a calibration file. Need more info on how this algorithm imp. is different from 'ISISIndirectDiffractionReduction'.
