### ISSUE TITLE
Calling ADS.clear() with the argument separately within atexit.register causes error message

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mantid#36794]
When calling atexit.register with a lambda no positional argument is allowed:

After closing Mantid the following error message is displayed in the console:
`TypeError: <lambda>() takes 0 positional arguments but 1 was given`

In addition, a failing system test on MacOS seems to be caused by this as well.

**Comment by sf1919** [comment]
I think this one can be closed?

**Comment by thomashampson** [comment]
Yes, it wasn't closed automatically becauase there was a # missing in the PR description.

**Comment by thomashampson** [comment]
fixed by #36791
