### ISSUE TITLE
Change dQ/Q unit in ISIS Reflectometry ORSO file

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#36805]
In the ORSO file output by `SaveISISReflectometryORSO` we set the `value_is` value of error column `Qz` (resolution or dQ/Q) to `sigma`, however this is not the correct description of the resolution distribution that we calculate at ISIS. Long term the calculation itself will be changed (under a separate issue), but for now the unit should be left blank in the ORSO file.

**Comment by sf1919** [comment]
@thomashampson I think this should have closed. Have we made the fixes for auto closing on `release-next`

**Comment by SilkeSchomann** [comment]
@rbauststfc Can we close this issue now?

**Comment by rbauststfc** [comment]
@SilkeSchomann, yes, this can definitely be closed. I'll do that now.
