### ISSUE TITLE
Update docs to use mamba instead of conda

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#36829]
Original reporter: Robert Dalgliesh

Using `conda` to solve environments tends to be slow, and it provides no information about what it's doing. Sometimes it also has problems. We should update the docs to say to use `mamba` instead, which does a much better job, is faster, and tells you what's going on.

**Additional context**

We just had a support issue relating to `conda` not solving and not providing much information about what went wrong.

**Comment by sf1919** [comment]
This issue has been solved & user contacted so can be closed. The other issue (#36178) will remain open.
