### ISSUE TITLE
Cannot export cuts from 3D MDHistoWorkspace

### ISSUE THREAD

**Issue by zjmorgan** [mantidproject/mantid#36852]
**Describe the bug**

Trying to export ROIs results in an error with 3d workspaces.

**To Reproduce**
1. Run this script
```python
from mantid.api import IMDHistoWorkspace

ws=CreateMDHistoWorkspace(Dimensionality=3,Extents='-3,3,-10,10,-4,4', \
                        SignalInput=range(0,1000),ErrorInput=range(0,1000),\
                        NumberOfBins='10,10,10',Names='Dim1,Dim2,Dim3',Units='MomentumTransfer,EnergyTransfer,Temperature')
```
2. Open slice viewer
3. Select ROI tool
4. Try to export cuts/slices with keyboard

**Expected behavior**

The workspace should be created. It works for 2d workspaces.

**Screenshots**

![image](https://github.com/mantidproject/mantid/assets/13754794/85e68cca-4261-4fd1-a977-71350383508c)
![image](https://github.com/mantidproject/mantid/assets/13754794/c67e5867-a4d0-4653-bd04-d43ecfa117da)

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by RichardWaiteSTFC** [comment]
Possible duplicate of #36084?

**Comment by sf1919** [comment]
If it is a duplicate is there a reason why it's suddenly high priority?

**Comment by zjmorgan** [comment]
It is a duplicate

**Comment by sf1919** [comment]
I would definitely add the `Reported by User` label to the other issue as a minimum.
