### ISSUE TITLE
Investigate options to improve user interaction with file finding when searching through a long list of directories

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#36923]
# Investigate options to improve user interaction with file finding when searching through a long list of directories

**Describe the outcome that is desired.**

A "quick-enough" search through a potentially large list of directories for a given filename.

**Does the outcome relate directly to a problem? Please describe.**

When the list of search directories for data files becomes large (100s) then finding files becomes time consuming. This has become an issue on the IDAaaS platform at ISIS where now that the archive is disconnected the instrument scientists have a potentially 100s of directories in their search paths. This has 2 issues:

- managing the directories is very challenging and it will only get worse;
- file searching can be very expensive as it has to check many directories, especially as runs get older as the list as the most recent at the front.

**Describe any solutions you are considering**

Some solutions considered, in no particular order:

1. Add an option to allow for recursive searching in selected managed data search paths.
   This was suggested by Fabio from WISH. I initially dismissed it as walking the filesystem
   every time would be expensive but maybe if we create some sort of index it would be fine.

   - This would help in the situation such as IDAaaS where all files for an instrument
     live in a hierarchical directory structure such as `/data/instrument/instrumentname/`.
     A user can just add the single top-level directory and Mantid would search for it.
   - I think this would have to also be implemented with some type of indexing where
     we pre-index and create a map of filenames to filepaths so we don't have to walk
     the filesystem every time. The index will need to be kept up to date though.
     Perhaps a filesystem-watcher like [this](https://github.com/e-dant/watcher/tree/release)
     or [these](https://github.com/e-dant/watcher/tree/release?tab=readme-ov-file#comparison-with-similar-projects)
     can be used?
   - A UI checkbox is simple but some method for recording this in the
     `Mantid.properties` file (`datasearch.directories`) would be necessary as the
     default should stay as a non-recursive search.
   - This solution has the advantage that its general and will help in other cases
     not just IDAaaS.

3. Discuss with IDAaaS whether they could maintain some sort of index when files
   are added/moved/deleted.
   - It would not need to be complicated, maybe just something in a JSON file that
     could be loaded.
   - The file would have to be continuously reloaded as it changed.
   - This would be an IDAaaS-specific solution.

4. Discuss with either IDAaaS or instrument controls how Mantid might be able to
  make a REST call, similar to how the [ISISDataArchive](https://github.com/mantidproject/mantid/blob/d3b894308e58898c38f8fed0ddd0bbf0d90dddaf/Framework/DataHandling/src/ISISDataArchive.cpp#L4)
  works, where we ask where a give run is.

   - It's likely this doesn't exist and complications with incorrect RB numbers mean
     we can't just contact the scheduler like IDAaaS does as the files may have moved.
   - If the service existed this is would simplify code on the Mantid side but it's
     likely very difficult to get this created.
   - This would be an IDAaaS-specific solution.

**Comment by thomashampson** [comment]
This was implemented by https://github.com/mantidproject/mantid/pull/37187
