### ISSUE TITLE
Inelastic Bayes Quasi crash with OSIRIS data

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36969]
**Describe the bug**
There is a crash on the Inelastic Bayes fitting Quasi tab when using OSIRIS data after clicking run.

You will need to follow the instructions here to install `quasielasticbayes` before you can run the Quasi tab.
https://docs.mantidproject.org/nightly/concepts/PipInstall.html

**To Reproduce**
Load the following datasets

Sample
[osiris113015_multi_graphite002_red.zip](https://github.com/mantidproject/mantid/files/14494578/osiris113015_multi_graphite002_red.zip)

Resolution 
[osiris113015_graphite002_red.zip](https://github.com/mantidproject/mantid/files/14494577/osiris113015_graphite002_red.zip)

Click Run and wait. It will eventually crash with

```
Python-[Information] Analyser is graphite, reflection 002
Python-[Information] Version is QLd
Python-[Information]  Number of spectra = 42
Python-[Information]  Erange : 0.7742136866571576  to 3.0963449464517163
Python-[Information]  lptfile : C:/Users/mlc47243/Documents/mantid-data/osiris113015_multi_graphite002_QLd.lpt
Python-[Information] Group 0 at angle 11.499999999999975
Python-[Information]  Log(prob) : 3.4366226196289062 0.1731414794921875 -0.021089553833007812 0.0
Python-[Information] Group 1 at angle 14.829000000000025
Python-[Information]  Log(prob) : 3.0325136184692383 0.1666584014892578 -0.016849517822265625 0.0
Python-[Information] Group 2 at angle 18.159000000000006
Python-[Information]  Log(prob) : 5.166180610656738 -0.11418914794921875 -0.09746932983398438 0.0
Python-[Information] Group 3 at angle 21.487999999999992
Python-[Information]  Log(prob) : 5.205564498901367 0.3659191131591797 -0.004669189453125 0.0
Python-[Information] Group 4 at angle 24.817000000000004
Python-[Information]  Log(prob) : 3.394390106201172 0.02785491943359375 -0.053920745849609375 0.0
Python-[Information] Group 5 at angle 28.14600000000002
Python-[Information]  Log(prob) : 3.6301956176757812 0.2033672332763672 0.0 -0.05436897277832031
Python-[Information] Group 6 at angle 31.476000000000003
STOP  Singular matrix!
QWaitCondition: Destroyed while threads are still waiting
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
```

**Expected behavior**
It shouldn't crash. If necessary there should be a warning message.

**Platform/Version (please complete the following information):**
 - OS: Found on Windows

**Comment by SpencerHowells** [comment]
@robertapplin Do not understand this data whatsoever! 1 - the 2 sets of data are the same sample - the multi version is usually a sum of runs for better statistics. 2 - the peak is at about 3.5 mev so is not QENS and Quasi should not be run. 3 - I've run Reduction & it appears to read a nxs raw file which is not the usual method. 4 - it only has 42 spectra wheres it is now 51. 5 - the run  date is 2015 so it may be a different instrument setup.   And I could go on!

**Comment by robertapplin** [comment]
Agreed, the data doesn't make sense from a science perspective.

Ideally the software shouldn't crash no matter what we throw at it. I've done some investigating and the crash comes from a `STOP` statement in the `quasielasticbayes` fortran PyPi package. There is no way to "catch" these terminations, so the only way to prevent a crash like this would be to change the `quasielasticbayes` package to use exit status codes rather than `STOP`. This would be a lot of work and I would argue not worth the effort given that we hope to use the `quickBayes` package going forward
https://github.com/mantidproject/mantid/issues/35918

**Comment by SpencerHowells** [comment]
@robertapplin Tried running BayesQuasi2 and the fitting crashed but not Mantid. Again due to bad data.

**Comment by robertapplin** [comment]
Opening this PR https://github.com/mantidproject/mantid/pull/36973 so we can start testing quickBayes in the Bayes fitting interface
