### ISSUE TITLE
Integration range changes from Elwin GUI does not change the energy integration window when running the algorithm

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#37012]
**Original reporter:** Franz Demmel

**Describe the bug**
As described by Franz
```
I just now noticed that when I use elwin the energy integration window does not change anymore.
Independent of the changed integration range in the GUI it seems always to integrate around the elastic line=the standard values.
```
**To Reproduce**

1. In Mantid Workbench, open `Interfaces->Inelastic->Data Manipulation` interface and select the `Elwin` tab.
2. On File, browse for file `irs26173_graphite002_red.nxs` and click on `Run`. 
3. Plot the resulting spectra by clicking on `Plot` button. 
4. Change the integration range either by the Property browser or directly using the graph delimiters on the plot widget. 
5. Run again the algorithm, see that the results are unaltered by the change of integration limits.

**Comment by SpencerHowells** [comment]
@adriazalvarez It would be useful if Sample Logs in the results were populated with the energy range values.

**Comment by adriazalvarez** [comment]
@SpencerHowells Noted, thank you.

**Comment by adriazalvarez** [comment]
@SpencerHowells I will open a separate issue for adding the sample logs. It would easier because We will refactor some functionality of Elwin tab in the next sprint and will be a good time to implement this feature.

**Comment by SpencerHowells** [comment]
@adriazalvarez OK
