### ISSUE TITLE
PyChop - incorrect phase offset for disk on MERLIN

### ISSUE THREAD

**Issue by mducle** [mantidproject/mantid#37045]
**Original reporter:** ISIS / T. Williams

**Describe the bug**
A few years ago (~2021?), the disk chopper controller on MERLIN was replaced / upgraded. Unfortunately this lead to an offset (of `4500` us) in the time-delay set by Mantid compared to what PyChop believes the time delay (chopper phase) is. Although it is a feature not often used, PyChop allows users to set the delay time of the disk chopper on MERLIN to govern which "reps" (incident energies) are allow to become incident on the sample. Because of the offset, if users set the delay time which PyChop suggests, they would be setting the wrong chopper phase and may not end up measuring anything and so lose time during experiments.

**To Reproduce**
1. Open PyChop and select Merlin as the instrument. Put `50` in the `Ei` text box. Click `Calculate and Plot`. 
2. Click on the `Time-Distance` tab near the top.
3. Go to the `Options` menu and select `Instrument Scientist Mode` - you should see an addition box `Disk chopper phase delay time` added to the GUI.
4. Change the value `1500` in this box to `3000` and see that the first two "reps" (at 133 and 50meV) are now blocked.

In fact in real life, a phase delay time of `3000` set in the IBEX control actually corresponds to `7500` us in PyChop terms so many more reps will be blocked and it's likely that the user will not be measuring anything.  

**Expected behavior**
The phase input in PyChop matches the phase set by the IBEX controller program.

**Screenshots**
N/A

**Platform/Version (please complete the following information):**
All, since Mantid 3.x

**Additional context**

**Comment by SilkeSchomann** [comment]
@mducle Does this mean we could just subtract the offset of 4500 for `chop2Phase` in https://github.com/mantidproject/mantid/blob/5d7e11729c9d33799d1af45a4daeac69d08311f9/scripts/pychop/MulpyRep.py#L313 for Merlin? Does that also apply to the default of 1500 when the user does not select `Instrument Scientist Mode`?

**Comment by mducle** [comment]
@SilkeSchomann yes, I think we can just subtract the "experimental" offset of 4500 in `chop2Phase` for Merlin. 

It might be good to make this a parameter read from the `yaml` file.

The actual default experimental value in the IBEX program for MERLIN is `12500` us (which corresponds to `17000` us in current PyChop terms [without the offset]). I think that for consistency for user this value should be used instead of the current `1500` value if that's ok?
