### ISSUE TITLE
Algorithm lists search bar "Execute" button doesn't always open correct algorithm

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#37112]
**Describe the bug**
Clicking the "Execute" button next to the name of an algorithm (which is in alias) in the algorithm lists will open the latest version even when the alias refers to a previous version of the algorithm.

**To Reproduce**

1. Open Mantid Workbench
2. Type "SaveAsciiTosca" in the algorithm list search bar
3. Click "Execute"
4. It will open the algorithm dialog for "Save Ascii v2" rather than "Save Ascii v1". "Save Ascii v1" is the algorithm with the "SaveAsciiTosca" alias

**Expected behavior**
It should open the algorithm dialog for the correct algorithm.

**Platform/Version (please complete the following information):**
 - OS: Found on Windows, but exists on all.

**Comment by thomashampson** [comment]
Note that the behaviour when clicking execute directly after using the search bar is different to if the algorithm is manually selected from the list.
