### ISSUE TITLE
Missing images in online docs

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#37253]
Indirect Difraction section of the documentation contains some missing images. 
Check in this link: https://docs.mantidproject.org/nightly/interfaces/indirect/Indirect%20Diffraction.html
**Expected behavior**

Images are loaded correctly on the docs.
**Screenshots**

![image](https://github.com/mantidproject/mantid/assets/146007827/6124cac6-2f01-4a27-a571-fac2f46fe521)
**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

**Comment by sf1919** [comment]
Can you check whether these are showing on the online documents? The developer setup of CMake does not automatically download images which is why it mentions enabling screenshots.

**Comment by adriazalvarez** [comment]
No, it's not a local build. I think it's on the server build. I have added the link to the page in the issue.
