### ISSUE TITLE
Investigate why Doxygen Warnings are not failures

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#37298]
**Describe the outcome that is desired.**
At the moment the Doxygen pipeline will pass if there are only warnings (e.g. https://builds.mantidproject.org/view/Pull%20Requests/job/pull_requests-doxygen/52117/). Instead we want the build to register as a failure to prevent errors getting through.

**Describe any solutions you are considering**
Initially we thought we could change this by changing the Thresholds in the Jenkins interface (see image below) but this is not part of the configuration of the Doxygen pipeline on Jenkins. Another option will need to be found. 

![image (8)](https://github.com/mantidproject/mantid/assets/55837273/b07c5bdd-2aaf-4275-b06e-97adf4407311)

**Additional context**

**Comment by peterfpeterson** [comment]
I don't know if it makes a difference, but [WARN_LOGFILE](https://www.doxygen.nl/manual/config.html#cfg_warn_logfile) is not set in `Framework/Doxygen/Mantid_template.doxyfile`. I don't know if it matters, but the format of the printed warnings is set to
```
  # Put the warning format in something sensible for the generator we are using
  if(MSVC)
    # Allows Visual Studio to mark them as if they were compiler warnings and jump straight to them
    set(DOXY_WARN_FORMAT
        "\"$file($line): $text\""
        CACHE STRING "Warning format for doxygen output, which must include surrounding double quotes"
    )
  else()
    set(DOXY_WARN_FORMAT
        "\"$file:$line: $text \""
        CACHE STRING "Warning format for doxygen output, which must include surrounding double quotes"
    )
  endif()
```

**Comment by sf1919** [comment]
Am changing the milestone as it got in before code freeze.
