### ISSUE TITLE
Crash on Elwin interface when removing all selected workspaces

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#37321]
A crash in Mantid is produced from the elwin interface whenever all the workspaces in the qtable are selected from the keyboard <ctrl+a> and then the `Remove` button clicked.  This was reported by an user.

**Original reporter:** Mona Sarter

**Describe the bug**

**To Reproduce**
- Go to `Interface->Inelastic->Data Manipulation->Elwin` interface.
- Add any suitable workspace (`irs26176_graphite002_red.nxs`)
- Hit `<Ctrl+A>` to select all workspaces
- Click on `Remove Selected` button 
-  💥

**Expected behavior**

There should be no crash when you select all rows from the keyboard and then remove.
**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mantid Version 6.9.1 and Nightly
**Additional context**

**Comment by robertapplin** [comment]
Fixed by [#37359](https://github.com/mantidproject/mantid/pull/37359)
