### ISSUE TITLE
Sliceviewer-Zooming in outside the extent of the data does not change Log colorscale option

### ISSUE THREAD

**Issue by warunawickramasingha** [mantidproject/mantid#37369]
**Describe the bug**

1- While following the testing instructions for sliceviewer at https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#id4
at step 5 when zooming in to a region outside the extent of the data, the log colorscale was still enabled as shown below. But the test instructions says otherwise.

![image](https://github.com/mantidproject/mantid/assets/142818102/16cbfde0-af25-4759-93c3-948142ddc71f)

2- In addition, at step7 at https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#id4 when track cursor is unchecked, clicked on the sliceviewer and when axes are transposed, the values of the table are cleared and does not stay the same for the clicked position above. Is this as expected?

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version [6.9.20240514]

**Comment by RichardWaiteSTFC** [comment]
I think this just needs updating in the manual testing docs - thanks!

**Comment by sf1919** [comment]
@RichardWaiteSTFC maybe we can close this one and open a separate issue to update the testing docs as I think there is another issue that also could be solved by updating the docs?

**Comment by RichardWaiteSTFC** [comment]
> @RichardWaiteSTFC maybe we can close this one and open a separate issue to update the testing docs as I think there is another issue that also could be solved by updating the docs?

Will do just want to check again the behaviour of the cursor info table described in issue 2 of the description

**Comment by RichardWaiteSTFC** [comment]
Closing as all doc updates will be addressed in #37390
