### ISSUE TITLE
Texts on the Mantid Workbench Main Menu could not be seen on OSX Dark mode 

### ISSUE THREAD

**Issue by yusufjimoh** [mantidproject/mantid#37376]
**Describe the bug**
Texts on the Mantid main menu turns white and becomes invisible on OSX when the device display is in dark mode.

**To Reproduce**

For example
1. Change Mac OSX Display to Dark mode
2. Launch the mantid Workbench

**Expected behavior**
Texts should be visible on the main menu when device display is on dark mode.

**Screenshots**
<img width="787" alt="Screenshot 2024-05-15 at 20 14 00" src="https://github.com/mantidproject/mantid/assets/168747442/c09ad165-d25e-49d6-84fa-c7f32d3965d8">

**Platform/Version:**
 - OS:  macOS
 - OS Version: 14.0
 - Mantid Version: 6.9.1

**Comment by jhaigh0** [comment]
This would be easy to detect using Qt 6.5 where they've added `colorScheme` to the style hints
https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop

There might be a hacky way to do it otherwise though.
