### ISSUE TITLE
Instrument View not rendering correctly

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#37370]
**Original reporter:** Mo Aouane

**Describe the bug**
When using Instrument view, zooming in on some detectors can cause a glitch in the display. The glitch only seems to occur when OpenGL is turned off (which is required on IDAaaS at the moment to avoid #36220 )

**To Reproduce**

1. Open Mantid and Load `MAR11015.raw` from the Training Data set
2. Open File->Settings and check that `Use OpenGL in Instrument View` is unticked
3. Right click on the loaded workspace and choose `Show Instrument` from the menu
4. Change the drop down at the top of the Render Tab to Cylindrical X
5. Open the Pick tab and select the Zoom tool (magnifying glass)
6. Choose a part of the instrument to zoom in on and draw a box around it. This shoukd zoom in but the result looks glitchy (see screenshot below for an example)

**Expected behavior**
The Instrument View should zoom into detectors correctly without overlaying other views or looking glitchy

**Screenshots**
It should not look like this

![Zoomed_InstrumentView](https://github.com/mantidproject/mantid/assets/55837273/c240a3cc-4f74-49b9-9323-1e251ae851eb)

It should look like

![Screenshot (375)](https://github.com/mantidproject/mantid/assets/55837273/01d20d60-b405-488d-bfa1-9898e0f30eef)

**Platform/Version (please complete the following information):**
 - OS: Windows 
 - OS Version: 10
 - Mantid Version: 6.9.20240514.1921

Also an issue on IDAaaS

**Additional context**

**Comment by sf1919** [comment]
I've tested this on v6.10.0 on Windows 10 and it is still an issue.

**Comment by sf1919** [comment]
Possibly linked to #35501

**Comment by jhaigh0** [comment]
I can't recreate this on my machine (v6.10 on Windows 10) weirdly.

**Comment by sf1919** [comment]
I've been contacted to say it's still a problem in v6.10 on IDAaaS

**Comment by jclarkeSTFC** [comment]
This is due to the background colour of the instrument view by default in the `mantidworkbench.ini` file giving a transparent colour. A workaround is to just set the background colour in the display settings to anything e.g. black, and then this will be fixed, (and it will stay fixed unless something deletes or edits the `ini` file). This problem is present in 6.8, 6.9, and 6.10 (I didn't go back any further). I'll look at sorting out the default value in `mantidworkbench.ini`.
