### ISSUE TITLE
Sliceviewer-update in slicepoint does not update cursor info table

### ISSUE THREAD

**Issue by warunawickramasingha** [mantidproject/mantid#37371]
**Describe the bug**
When following the sliceviewer test instructions as listed : https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#id5
at step 5, when the slicepoint is changed along one of the non-viewed axis, the slicepoint is not updated in the cursor info table

**To Reproduce**

1. Follow test instructions here: https://developer.mantidproject.org/Testing/SliceViewer/SliceViewer.html#id5
2. at step 5 Untick track cursor
3. click on the plot
4. change slicepoint on one of non-viewed axis. But the values in the table do not change.

**Expected**:
the slicepoint is updated in the cursor info table.

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version [6.9.20240514]

**Comment by jclarkeSTFC** [comment]
This is also in 6.9.1

**Comment by RichardWaiteSTFC** [comment]
We would not expect the values in the cursor info table to change if Track Cursor is unchecked - the values should update if you click on the colorfill (2D) plot

**Comment by RichardWaiteSTFC** [comment]
Closing as all doc updates will be addressed in #37390
