### ISSUE TITLE
Update Engineering Diffraction manual testing instructions

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#37384]
Here are some suggested updates to the manual testing instructions for the Engineering Diffraction interface following manual testing for version 6.10:

- [x] It would be good to introduce a comment at the top of the manual testing instructions warning about the potential difficulty with loading ENGINX files from the archive and how to get around this. This should also include an instruction for how to enter the range of runs specified in Test 4.
- [x] For Test 5, in the instructions it's not clear that the settings you're asked to test are the browse filters for filtering the files that are available to select from the file browser dialog.
- [x] In Test 9, it's not clear from the instructions where the primary log combo box is, as it doesn't seem to have this label on the interface.
- [x] Could consider adding a note to the instructions to address this comment: https://github.com/mantidproject/mantid/issues/37329#issuecomment-2115617319

**Comment by sf1919** [comment]
@warunawickramasingha can this now be closed?

**Comment by warunawickramasingha** [comment]
Closing this issue since all the above suggestions were captured in #37482.
