### ISSUE TITLE
DepolarizedAnalyserTransmission should only fit for p*d

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#37445]
The `DepolarizedAnalyserTransmission` algorithm (completed under #36383) fits equation `T(λ) = TE(λ) * exp(-μ)` to find values for `μ` and `TE`. However, the transmission of the empty cell `TE(λ)` is a function of the wavelength, not a single value as is currently returned by the algorithm. Instead we should just be fitting to obtain the value for `p*d` (pressure * path length).

The value `TE(λ)` represents the transmission of the empty cell, and so when we normalise our depolarized workspace by our empty cell workspace in the algorithm this is actually giving us: `T(λ)/TE(λ) = exp(-μ)`. We should therefore only be fitting for `p*d`.

As we will be fitting for just a single parameter, the covariance matrix that the algorithm outputs is not relevant and can be removed.

**Comment by cailafinn** [comment]
Was merged into `main` but needed to be in `release-next`.
