### ISSUE TITLE
Instrument view crashed on peak overlay

### ISSUE THREAD

**Issue by RichardWaiteSTFC** [mantidproject/mantid#37514]
**Describe the bug**
Overlaying a specific peaks workspace crashes instrument view - the vast majority of peak workspaces are fine so this has been hard to reproduce. But I now have some files for which it is consistently reproducible.

**To Reproduce**
(1) Load in this workspaces (on my babylon)

The instrument workspace is
`"\\olympic\Babylon5\Public\RWaite\UBs_NickF\SXD34361_processed.nxs"`
The peaks workspace is
`"\\olympic\Babylon5\Public\RWaite\UBs_NickF\SXD34361_peaks_predicted.nxs"`

If these aren't available let me know I have a copy on my desktop

(2) Open the instrument workspace `SXD34361_processed` in instrument viewer

(3) Overlay the peaks workspace `SXD34361_peaks_predicted` by dragging from the workspace list onto the instrument viewer

Mantid crashes, with  no error reporter or stack trace

**Expected behavior**
Not crash, would overlay peaks

**Platform/Version (please complete the following information):**
 - OS: seen on IDAaaS and windows
 - Mantid Version seen on v6.8 onwards (including nightly 6.9.20240607)

**Comment by jclarkeSTFC** [comment]
This particular example is caused by a peak having a detector ID of -1:

![image](https://github.com/mantidproject/mantid/assets/139879523/2c656ee0-3d8c-4ee6-8057-1ef9cde795d9)

Maybe the other peak workspaces also have the same thing? We can improve it so that this doesn't take down Mantid in future.

**Comment by RichardWaiteSTFC** [comment]
Thanks for that - yes this can happen if you predict peaks outside detector coverage for instruments that support `extended detector space`  (e.g. WISH). For instruments that don't it makes sense not to plot them - it would be worth checking on WISH using `PredictPeaks` and predict outside detector

**Comment by jhaigh0** [comment]
Did you move the file you mentioned? I can only see these for SXD34361
![image](https://github.com/mantidproject/mantid/assets/35813666/883296d8-b713-4654-8d44-2c734993cb99)

**Comment by RichardWaiteSTFC** [comment]
I think all you need is a peak table with a null detector ID - here is the one I was using (renamed to .txt)
[SXD34361_peaks_predicted.nxs.txt](https://github.com/user-attachments/files/15866037/SXD34361_peaks_predicted.nxs.txt)
