### ISSUE TITLE
Windows installer versions not quite right sometimes

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#3753]
This issue was originally [TRAC 2906](http://trac.mantidproject.org/mantid/ticket/2906)

The version info is retrieved from Mantid which has the version number written by CMake. Unfortunately, for example, if only a change to the Third_Party directory is made then the resulting installer will have the same revision number as the previous build.

**Comment by NickDraper** [comment]
Not seen in a long time - wontfix
