### ISSUE TITLE
3D Surface plot zooming in and out with mouse hover

### ISSUE THREAD

**Issue by GuiMacielPereira** [mantidproject/mantid#37585]
**Describe the bug**
3D surface plots incorrectly trigger zoom when the log axis scale of the colorbar is selected.

**To Reproduce**

1. Load LOQ74041
2. Click `Plot > 3D > Surface`
3. Right-click on the plot > Color bar 
4. That shoud be enough to trigger the bug
5. If you hover the mouse over the plot you'll notice it zooms in and out
6. You can stop it if you click on the plot
7. The scroll wheel doesn't seem to work.

**Expected behavior**
Fix the zooming with hovering and maybe get the scroll wheel working for the zoom.

**Screenshots**
Zoomed out plot:
![image](https://github.com/mantidproject/mantid/assets/80104863/accd0a1a-b738-42c5-80f1-8df17c1c733d)

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 22.04
 - Mantid Version 6.10

**Additional context**

**Comment by jclarkeSTFC** [comment]
I can't get it to do this on IDAaaS, I'll have a go on my Ubuntu VM

**Comment by jhaigh0** [comment]
I can get this to happen on windows 👍
