### ISSUE TITLE
TOF Convertor menu appears compressed in high resolution machines

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#37584]
**Describe the bug**

When opening the TOF converter interface, it appears too minimized, making it unusable.  
**To Reproduce**

You need a high resolution machine to replication the issue
1. Go to interfaces->utility->TOF convertor
2. The window will appear small and unusable

**Expected behavior**

It should appear in normal size with adjustable dimensions
**Screenshots**

![image](https://github.com/mantidproject/mantid/assets/44416400/5c0bb010-9efd-488d-b9e0-d22481cddf98)

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS] Windows 
 - OS Version: 10
 - Mantid Version [e.g. 6.0.0] 6.10.rc1

**Comment by jclarkeSTFC** [comment]
Is this the same in 6.9.1?

**Comment by MohamedAlmaki** [comment]
Yes, it is not a regression bug
