### ISSUE TITLE
Slice Viewer indexOfValue - value out of range error

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#37594]
**Describe the bug**
There is an error when hovering over a specific dataset in the Slice Viewer. The error says:
```
Traceback (most recent call last):
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantid-developer\lib\site-packages\matplotlib\cbook\__init__.py", line 314, in process
    func(*args, **kwargs)
  File "c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\views\cursor.py", line 66, in on_mouse_move
    self.on_cursor_at(xdata, ydata)
  File "c:\users\mlc47243\documents\mantid-dev\mantid-review\mantid\qt\python\mantidqt\mantidqt\widgets\sliceviewer\presenters\imageinfowidget.py", line 88, in _on_cursor_at_axesimage
    self._widget.cursorAt(xdata, ydata, arr[i, j], extra_cols)
Exception: indexOfValue - value out of range
```

**To Reproduce**
1. Load the below data into Workbench
[osiris100318-100329_graphite002_red_elwin_eq.zip](https://github.com/user-attachments/files/15928583/osiris100318-100329_graphite002_red_elwin_eq.zip)

3. Right click the workspace and `Open Slice Viewer`
4. Double click the y axis and change the limits to be from 262 to 266
5. Hover over the thin strip of data
6. The error will happen!

**Expected behavior**
There should be no error

**Screenshots**
![image](https://github.com/mantidproject/mantid/assets/40830825/31d0eb2d-fb9c-4d51-9a9b-8183b4de9f84)

**Platform/Version (please complete the following information):**
 - OS: Found on Windows

**Comment by Despiix** [comment]
@robertapplin 
The error happens [here](https://github.com/mantidproject/mantid/blob/main/qt/widgets/common/src/ImageInfoModelMatrixWS.cpp#L62) in the `ImageInfoModelMatrixWS`. 
It calls the `VectorHelper` function [here](https://github.com/mantidproject/mantid/blob/main/Framework/Kernel/src/VectorHelper.cpp#L442). In that function, `bin_centres` has the 12 'Sample' values in it which seems wrong. They aren't in order or equidistant like you'd expect from bin centres.

Looking back at the slice viewer, it feels like it is plotting the wrong thing? i.e the sample numbers instead of the actual y data you see when you do 'show data'. Is the issue that the slice viewer is plotting the wrong axis?

**Comment by robertapplin** [comment]
> Looking back at the slice viewer, it feels like it is plotting the wrong thing? i.e the sample numbers instead of the actual y data you see when you do 'show data'. Is the issue that the slice viewer is plotting the wrong axis?

It looks like its doing the right thing (i.e. the y data should be represented by the colorbar), and the y axis of the slice viewer plot is usually the y labels for each of the spectra:
![image](https://github.com/user-attachments/assets/8658b691-d498-49d4-be37-0f3388e14520)

Interestingly it only seems to have plotted the last spectrum of the workspace, hence the thin strip. I'm a little confused why its been plotted at 265 rather than 260
![image](https://github.com/user-attachments/assets/19a9cbc0-57f8-43f6-a539-af72ba7468f9)

**Comment by robertapplin** [comment]
Like you say, the y labels are not in order, and are not regularly spaced. It might be worth discussing with Tom or Richard if Slice viewing should not be allowed if this is the case

**Comment by RichardWaiteSTFC** [comment]
I have a couple of thoughts:

1. Spectrum viewer images usually use a class called `ModestImage` - this re-samples the image based on the resolution, could this be an issue with the re-sampling? However I also recall seeing this when viewing MD workspaces which are not modest images - so perhaps this isn't related to the sampling!
2.  It looks like every 10th spectrum in plotted - if sliceviewer interpreted the spectrum number as a bin-edge, the bin-center would be at 265? Not sure then why the y-axis width is so narrow - should always be 1 in spectrum view mode right?
