### ISSUE TITLE
Instrument view crash when left click after changing filter bar

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#37652]
**Original reporter:** David Voneshen

**Describe the bug**

Mantid crashes if you left click a detector on the plot after changing the time-of-flight filter bar at the bottom of the dialog while on the Pick tab.

**To Reproduce**

1) Load some data.
1) Open the instrument view.
1) Go to the Pick tab.
1) Click in the left hand input of the Time-of-Flight filter bar at the bottom of the dialog and change the value.
1) Left click on a detector in the instrument view plot. Mantid should crash.

**Expected behavior**

Mantid shouldn't crash.

**Platform/Version (please complete the following information):**
 - OS: first reported on Windows and can also be replicated on IDAaaS
 - Mantid Version: present since 6.8 but first discovered in 6.10.

**Comment by robertapplin** [comment]
I think this will also be fixed by https://github.com/mantidproject/mantid/pull/37655
