### ISSUE TITLE
Update Anaconda Channel description

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#37702]
**Describe the outcome that is desired.**
The channel description for Mantid on Anaconda is out of date. It currently reads
```
Mantid provides a framework that supports high-performance computing and visualisation of materials science data. To use the optional plotting sub package you must conda install matplotlib 3.5.2 to ensure correct compatibility.
```
(see https://anaconda.org/mantid/mantid)

As pointed out in this Forum post that version of matplotlib is incompatible with more recent versions of Mantid - https://forum.mantidproject.org/t/new-release-of-mantid-6-10-0/894

**Describe any solutions you are considering**
The description on the channel needs updating to be clearer and more relevant.

**Comment by thomashampson** [comment]
We should probably add matplotlib as a `run_constrained` optional dependency to ensure compatibility. I'm building a package to test here:
