### ISSUE TITLE
Fix sphinx file path deprecation warning

### ISSUE THREAD

**Issue by jclarkeSTFC** [mantidproject/mantid#37804]
**Describe the outcome that is desired.**
Fix this deprecation warning in the doc tests:

```
RemovedInSphinx90Warning: Sphinx 9 will drop support for representing paths as strings. Use "pathlib.Path" or "os.fspath" instead
```

**Describe any solutions you are considering**
Using `pathlib.Path` or `os.fspath` to represent paths instead of strings

**Comment by sf1919** [comment]
Sphinx 8 was release in July and Sphinx 7 in May 2023 so I am going to guess Sphinx 9 is not imminent but likely within the enxt 12 months.

Therefore I'm going to put a 6.12 milestone on this as I think this potentially may take some time
