### ISSUE TITLE
Update PG3StripPeaks to not use AlignDetectors algorithm

### ISSUE THREAD

**Issue by sf1919** [mantidproject/mantid#37859]
**Describe the outcome that is desired.**
`SNSPowderRedux.PG3StripPeaks`  should no longer use `AlignDetectors` algorithm.

The proposed change is centered on L219. Currently,
```python
AlignDetectors(InputWorkspace="PG3_4866", OutputWorkspace="PG3_4866", OffsetsWorkspace="PG3_offsets")
ConvertUnits(InputWorkspace="PG3_4866", OutputWorkspace="PG3_4866", Target="TOF")
```
should become
```python
ApplyDiffCal(InstrumentWorkspace="PG3_4866", OffsetsWorkspace="PG3_offsets")
ConvertUnits(InputWorkspace="PG3_4866", OutputWorkspace="PG3_4866", Target="dSpacing")
ApplyDiffCal(InstrumentWorkspace="PG3_4866", ClearCalibration=True)
ConvertUnits(InputWorkspace="PG3_4866", OutputWorkspace="PG3_4866", Target="TOF")
```

**Additional context**
`SNSPowderRedux.PG3StripPeaks` makes use of the AlignDetectors algorithm. This was deprecated in 2021 (see #30163) and is now being removed as part of #31258. This work is blocking #37799 .

**Comment by dmitry-ganyushin** [comment]
Fixed with PR https://github.com/mantidproject/mantid/pull/37872
