### ISSUE TITLE
Correct the equation and errors used in the PolarizerEfficiency algorithm

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantid#37939]
Testing of the new `PolarizerEfficiency` algorithm has highlighted that there is a factor of 2 too much in the equation that was implemented on the original issue (#37616). The equation should be corrected as given below (note that this also requires an update to the error calculation, which is also given below):

### Maths

Polarization:

$$
\huge P_{SM} = \frac{T_{00} - T_{01}}{P_{cell}(T_{00} + T_{01})} = \frac{T_{00} - T_{01}}{(2\epsilon_{cell} - 1)(T_{00} + T_{01})}
$$

Efficiency (this is the equation that the algorithm should implement):

$$
\huge \epsilon_{SM} = \frac{1}{2} + \frac{T_{00} - T_{01}}{2(2\epsilon_{cell} - 1)(T_{00} + T_{01})}
$$

Error calculation:

$$
\huge \sigma_{\epsilon_{SM}} = \sqrt{|\frac{\delta \epsilon_{SM}}{\delta T_{00}}|^2 * \sigma^2_{T_{00}} + |\frac{\delta \epsilon_{SM}}{\delta T_{01}}|^2 * \sigma^2_{T_{01}} + |\frac{\delta \epsilon_{SM}}{\delta \epsilon_{cell}}|^2 * \sigma^2_{\epsilon_{cell}}}
$$

where:

$$
\huge \frac{\delta \epsilon_{SM}}{\delta T_{00}} = \frac{T_{01}}{(2\epsilon_{cell} - 1)(T_{00} + T_{01})^2}
$$

$$
\huge \frac{\delta \epsilon_{SM}}{\delta T_{01}} = \frac{-T_{00}}{(2\epsilon_{cell} - 1)(T_{00} + T_{01})^2}
$$

$$
\huge \frac{\delta \epsilon_{SM}}{\delta \epsilon_{cell}} = \frac{T_{01} - T_{00}}{(2\epsilon_{cell} - 1)^2(T_{00} + T_{01})}
$$

The equations in the algorithm documentation will need to be updated too.

**Comment by dehoni** [comment]
The expression are correct
