### ISSUE TITLE
Update ISIS Reflectometry Manual Testing instructions

### ISSUE THREAD

**Issue by adriazalvarez** [mantidproject/mantid#38024]
**Describe the outcome that is desired.**

During testing the ISIS Reflectometry interface #37994 , we found that the instructions didn't match our results in different systems in the fourth to last point of the `Preview Tab` section of the instructions: 
```
Right-click the workspace and select Show History:
    In the Algorithms list, expand ReflectometryISISLoadAndProcess.
    Click on ReflectometryReductionOneAuto and check in the right hand pane that the inputs for ProcessingInstructions, BackgroundProcessingInstructions and TransmissionProcessingInstructions correspond to the ranges of spectra you selected.
    Expand ReflectometryReductionOneAuto.
    Click on ReflectometryISISSumBanks and check that the input for ROIDetectorIDs matches the range of detector IDs you selected.

```

Particularly, we couldn't find the `ReflectometryISISSumBanks` entry on the history.

**Describe any solutions you are considering**

Update the manual instructions accordingly. 

Additionally, we found during this part of the testing of ISIS Reflectometry (See #37994) that the  last two sections of the instructions would be easier to follow if a numbered list is added.
**Additional context**

**Comment by rbauststfc** [comment]
@adriazalvarez thanks for adding this issue. On the problem with the preview tab instructions where you couldn't find `ReflectometryISISSumBanks` in the workspace history on all operating systems, are you able to provide any more details on this? It works OK for me on Windows and on IDAaaS, so were there other operating systems where this happened?
