### ISSUE TITLE
Plot spectra disables text edit in Moments tab in Inelsatic Data Processor

### ISSUE THREAD

**Issue by warunawickramasingha** [mantidproject/mantid#38065]
On [Moments tab](https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html#id5)
After final step of Plot Spectra, the line edit is disabled and subsequent plots with different spectrum indices cannot be made unless you click Run again

**To Reproduce**
1. Follow test instruction for [Moments tab](https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html#id5)
2. at step 9, after clicking `Plot Spectra`, the text edit is disabled

**Expected behavior**
Text edit should be kept enabled

**Platform/Version (please complete the following information):**
 - OS: [all]
 - OS Version: 
 - Mantid Version 6.11

**Additional context**

**Comment by robertapplin** [comment]
I believe this is a problem in the manual testing instructions. The text edit should remain disabled and should have `0,2,4` (and I think the instructions need to be changed to reflect this)
