### ISSUE TITLE
Windows Smoke Tests: Release 6.11

### ISSUE THREAD

**Issue by MohamedAlmaki** [mantidproject/mantid#38222]
We must test both the .exe installer package and install direct from conda.

* To install via conda:
  - Use Intel Conda and make sure conda-forge is added to channels
```
mamba create -n mantid_rc1 -c mantid/label/v6.11.0rc1 mantidworkbench --yes
mamba activate mantid_rc1
workbench # to launch
```

**Before testing**:
- Check this main issue relates to the OS you will test on.
- Tick the box beside a testing issue listed below to mark *you are testing this issue*
- Enter the testing task issue and assign yourself as for a normal Github issue.

**Afterwards**:
- Comment on the testing issue with any issues you came across.
- If no major issues were found, please **close the testing issue**.

If you have any questions please contact the creator of this issue.

### Tick below before testing the related issue

- [x] #38216

- [x] #38217

- [x] #38218

- [x] #38219

- [x] #38220

- [x] #38221

**Comment by SilkeSchomann** [comment]
I am closing this as all of the sub-tasks are finished.
