### ISSUE TITLE
Signature of XDataConverter::getNewXSize

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#3867]
This issue was originally [TRAC 3020](http://trac.mantidproject.org/mantid/ticket/3020)

This ticket is blocks :  [~~TRAC3008~~](http://trac.mantidproject.org/mantid/ticket/3008)

In principle the return should be ```std::size_t``` since it will be returning the result of ```MatrixWorkspace_sptr->blocksize()```.

**Comment by NickDraper** [comment]
This has been done

  virtual std::size_t
  getNewXSize(const API::MatrixWorkspace_sptr inputWS) const = 0;
