### ISSUE TITLE
Segmentation fault whe showing instrument

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#4041]
This issue was originally [TRAC 3194](http://trac.mantidproject.org/mantid/ticket/3194)

I was running Mantid version 1.29.12480 (Friday 10 Jun 2011) on RHEL6 vis ssh.
I loaded a file, then clicked show instrument. I get segmentation fault. The output is pasted below. First line (QLayout ...) happens when I start MantidPlot. Loading is correct. 
The same file works with the latest stable release of Mantid. If I run the same thing from the terminal, I get no image of the detector banks (only axes), the same error messages, but no segmentation fault.

```
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
Load-[Notice] Load started
LoadInstrument-[Warning] Trying fallback /tmp/SEQUOIA_Definition.vtp
Load-[Notice] Load successful, Duration 4.13 seconds
Object::connect: No such slot InstrumentWindowRenderTab::selectBinButtonClicked()
Vertex shader for simpleShaderProg (MainVertexShader & PositionOnlyVertexShader) failed to compile
Fragment shader for simpleShaderProg (MainFragmentShader & ShockingPinkSrcFragmentShader) failed to compile
Errors linking simple shader: "" 
Vertex shader for blitShaderProg (MainWithTexCoordsVertexShader & UntransformedPositionVertexShader) failed to compile
Fragment shader for blitShaderProg (MainFragmentShader & ImageSrcFragmentShader) failed to compile
Errors linking blit shader: "" 
Warning: "" failed to compile! 
Segmentation fault (core dumped)
```

**Comment by martyngigg** [comment]
We have options to use VirtualGL in our startup wrappers these days and this has not been reported as a problem for some time.
