### ISSUE TITLE
Tidy up visual studio solution

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#4125]
This issue was originally [TRAC 3278](http://trac.mantidproject.org/mantid/ticket/3278)

Turning everything on in CMake results in a Visual Studio solution that is a bit of a mess. Some things to look at:
 * There is a MantidFramework group and a Framework target. They sounds the same
 * There is a UnitTests group and a FrameworkTests target. They sound the same
 * The VatesAPITest is not included with the UnitTests group
 * Each paraview plugin is its own top level target, these should be grouped into a ParaviewPlugins group
 * Maybe consider having an Applications group to house MantidPlot, VatesSimpleGUI and WikiMaker?

**Comment by martyngigg** [comment]
It's really not worth the effort.

**Comment by NickDraper** [comment]
agreed, the change is not worth the confusion
