### ISSUE TITLE
SANS: Allow Wcut and Rcut to be set from gui

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#4268]
sans_feature
This issue was originally [TRAC 3421](http://trac.mantidproject.org/mantid/ticket/3421)

Refering to http://trac.mantidproject.org/mantid/ticket/3167 where the code for handling
Wcut and Rcut was implemented by reading 
L/Q/Wcut and L/Q/Rcut from the userfile.

For this ticket also allow these to be set from the
ISIS SANS custom interface GUI and likely in the
Analysis tab

**Comment by AntonPiccardoSelg** [comment]
If this is done only in the new GUI, this should be easy

**Comment by Mantid-Matthew** [comment]
This is now done #22360
