### ISSUE TITLE
SANS: When using Addrun tab to add files together change output filename

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#4275]
sans_code
This issue was originally [TRAC 3428](http://trac.mantidproject.org/mantid/ticket/3428)

SANS GUI: AddRun tab creates files with run number of first file in add list; we need this changed so that it names the add file with the highest run number in the list no matter what order the runs are specified in.

output file is a nexus file

**Comment by AntonPiccardoSelg** [comment]
@Mantid-Matthew Implement this when you port the `AddTab` to the new ISIS SANS GUI.

**Comment by Mantid-Matthew** [comment]
This has been implemented in the new GUI.
