### ISSUE TITLE
Colormap selection should be clearer

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#4326]
This issue was originally [TRAC 3479](http://trac.mantidproject.org/mantid/ticket/3479)

Rather than making users dig around for a different color map that they want to use, make the list of color maps a selection from ones that mantid found. For clarity you may want the dialog have the directory (with absolute path) where it expects the color maps to be.

**Comment by NickDraper** [comment]
very old and ignored - archive
