### ISSUE TITLE
SANS: untick/tick rows in cvs batch display

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#4432]
sans_feature
This issue was originally [TRAC 3585](http://trac.mantidproject.org/mantid/ticket/3585)

Note this ticket may be completed together with http://trac.mantidproject.org/mantid/ticket/1262.

Steve writes:
1.  We have had several users complaining that, whilst they like the batch feature, once theyâ€™ve loaded one into Mantid they sometimes would like to reprocess (eg, with different binning) a subset of the runs. At present they would have to create a new CSV file and delete the lines that they donâ€™t want and then load that new CSV file. They have asked if alongside each line in the table in the GUI there could be a little check box to tell Mantid whether to process that line, with a global â€˜select allâ€™ (which would also be the default)?

**Comment by AntonPiccardoSelg** [comment]
The new ISIS SANS GUI allows the user to select the rows which she wants to process. I don't think it makes sense to implement this in the old GUI, hence this issue will be closed
