### ISSUE TITLE
Progress arrow in script window

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#4498]
This issue was originally [TRAC 3651](http://trac.mantidproject.org/mantid/ticket/3651)

Create a script like

```python
def doSomething():
    algorithm1(...)
    algorithm2(...)
    algorithm3(...)

Load...
doSomething()
```

During execution, the arrow showing the progress along the script in the script window is staying at the "doSomething()" line after "Load...". Instead, it should move inside the doSomething function, and point to algorithms 1, 2 or 3.

**Comment by NickDraper** [comment]
Yes this would be nice, but very hard to implement.

Not worth the resource at the moment
