### ISSUE TITLE
Ship include files separately

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#4586]
This issue was originally [TRAC 3739](http://trac.mantidproject.org/mantid/ticket/3739)

The installers currently ship the include files for Mantid. The Windows and Mac installers have to ship all of the 3rd party headers for Boost and Poco leading to bloated installer.

If we had these in a separate installer or a simple zip file it would reduce the bloat of the installers.

**Comment by NickDraper** [comment]
This has been superceeded by the agreement to drop the include files from the installer
