### ISSUE TITLE
Dynamic property validation

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#4610]
This issue was originally [TRAC 3763](http://trac.mantidproject.org/mantid/ticket/3763)

This ticket is blocks :  [~~TRAC3925~~](http://trac.mantidproject.org/mantid/ticket/3925)

At present, the NormaliseToMonitor algorithm requires that you enter the spectrum number relating to the monitor you wish to use. It would be much nicer, particularly when using MantidPlot, to give the name of the monitor instead. But this isn't known until the input workspace has been set, so we would need to find a way in which the setting of the input workspace fired an event that the monitor property could catch and update itself. 

Span off from http://trac.mantidproject.org/mantid/ticket/262

**Comment by NickDraper** [comment]
archived the ticket it blocks has moved on. so not important
