### ISSUE TITLE
3D plot: Seems to be a layer stuck on top of everything

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#4662]
This issue was originally [TRAC 3815](http://trac.mantidproject.org/mantid/ticket/3815)

I saw this on the Mac.

* Load a data set
* Double-click on the workspace to bring up the matrix
* Menu 3D Plot->3D Polygons
* Rotate the box inside the plot
* Try and drag the matrix over the plot, it will only go under it.

**Comment by NickDraper** [comment]
duplicate of another ticket that I just assigned to Owen #4912
