### ISSUE TITLE
Set column values in Tables crashes MantidPlot if the formula uses the column you are filling in

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#4664]
This issue was originally [TRAC 3817](http://trac.mantidproject.org/mantid/ticket/3817)

Create a new Table. Right click on the second column and select Set column values.
Enter col("2") in the text coltrol. Press Apply.

**Comment by shahrozahmed1** [comment]
Issue #4664 seems to work fine on Windows

**Comment by FedeMPouzols** [comment]
Tested with current master on debian and the crash doesn't happen. This must have been fixed elsewhere.

I got the impression that the functionality related to "add column" / "add function" might not be very polished. It seems that you can set the columns using numeric values and simple arithmetic formulas, but the "add function" button shows a "deprecated functionality" pop-up and "add column" doesn't seem to have any effect.
