### ISSUE TITLE
SANS: code to replicate COLETTE AREA/COMPRESS/PHI commands

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#4879]
sans_feature
This issue was originally [TRAC 4032](http://trac.mantidproject.org/mantid/ticket/4032)

This ticket is blocked by : 
- [X] [TRAC7776](http://trac.mantidproject.org/mantid/ticket/7776)
- [X] [TRAC7829](http://trac.mantidproject.org/mantid/ticket/7829)
- [ ] [TRAC8111](http://trac.mantidproject.org/mantid/ticket/8111)
- [ ] [TRAC8112](http://trac.mantidproject.org/mantid/ticket/8112)

Implement equivalent code to COLETTE AREA/COMPRESS/PHI commands. Importantly these command mask in Qx-Qy space.

**Comment by gemmaguest** [comment]
Closing as replaced by #23976
