### ISSUE TITLE
SANS: Allow selection of multiple phi masking in GUI

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#4949]
sans_feature
This issue was originally [TRAC 4102](http://trac.mantidproject.org/mantid/ticket/4102)

As a follow up to http://trac.mantidproject.org/mantid/ticket/3015.

In ISIS SANS GUI in Analysis Details tab change

Limit Phi (degrees)  BOX to BOX

to 

COMBOBOX with options "Phi range" and "Phi ranges". When
"Phi ranges" is specified have just one text box which takes
a phi range text using notation in http://trac.mantidproject.org/mantid/ticket/3015

**Comment by gemmaguest** [comment]
Closing as there has been no movement on this for over 5 years and this doesn't seem to be a priority at the moment
