### ISSUE TITLE
Cleanup of ISIS SANS Script Code - Umbrella Ticket

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#5106]
Clarified to Be:
SANS processing is reloading files several times. This should be optimized out.

The steps to complete are:
- [ ] Avoid reload of Data Files (only if the workspace has not been altered) (https://github.com/mantidproject/mantid/issues/15812)
- [ ] Avoid reload of Calibration Files (only if the workspace has not been altered)

**Comment by AntonPiccardoSelg** [comment]
Work on this item has been suspended after SANS meeting on the 6th of April 2016. NexusCansas and rewrite of the reduction-backend have been identified as higher priorities.

**Comment by AntonPiccardoSelg** [comment]
This has been addressed in the new ISIS SANS reduction framework
