### ISSUE TITLE
Improve memory usage for LoadNXSPE

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#5257]
This issue was originally [TRAC 4410](http://trac.mantidproject.org/mantid/ticket/4410)

The rendering of the instrument is VERY memory intensive. Also, detector shape is not taken from the NXSPE file. See comments in ticket http://trac.mantidproject.org/mantid/ticket/2292

**Comment by NickDraper** [comment]
No attention for 4 years - archived
