### ISSUE TITLE
Load dialog box partially unresponsive after inability to acces a file has been reported by load alg.

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#5266]
This issue was originally [TRAC 4419](http://trac.mantidproject.org/mantid/ticket/4419)

Found on Windows 7.  To reproduce:

* Copy a data file to a local drive and change the read permissions of that file to "Deny".
* Run MantidPlot and open the Load dialog.
* Ensure that only the File and Workspace properties are shown.  Enter a nonsensical string in the "File" field if necessary.
* Attempt to access your non-readable file by typing in the path (and NOT by browsing via the browse button).
* Click "Run", and close the dialog that successfully reports that Mantid has been unable to load the file.

The File and Workspace fields are now unresponsive to any user input.

[Set to minor as you have to jump through a few hoops to get to this stage, and it can be worked around by simply closing and reloading the dialog.]

**Comment by NickDraper** [comment]
ignored for years - archived
