### ISSUE TITLE
Uninstall in windows leaves files on the disk

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#5297]
This issue was originally [TRAC 4450](http://trac.mantidproject.org/mantid/ticket/4450)

When uninstalling in Windows, none of the pyc files are deleted in scripts and plugins directories. Also mantid.log in logs, and Mantid.user.properties in bin. MantidInstall directory should be deleted

**Comment by NickDraper** [comment]
ignored for years - archived
