### ISSUE TITLE
Remove OpenGL header includes from MantidPlot

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#5642]
This issue was originally [TRAC 4795](http://trac.mantidproject.org/mantid/ticket/4795)

We have had to include the OpenGL headers (via a Mantid header) into a few files in MantidPlot in order to get it to compile with Qt 4.8

Ideally, including these headers should be the responsibility of upstream (which in this case is qwtplot3d - I think!)

The header included is 

```
#include "MantidGeometry/Rendering/OpenGL_Headers.h"
```

and it was added to:

```
MantidPlot/src/UserFunction.h
MantidPlot/src/Graph3D.h
MantidPlot/src/Cone3D.cpp
MantidPlot/src/Bar.cpp
```

**Comment by peterfpeterson** [comment]
This is no longer relevant.
