### ISSUE TITLE
Add option to set Y-axis label and values to ConjoinWorkspace

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#5824]
This issue was originally [TRAC 4978](http://trac.mantidproject.org/mantid/ticket/4978)

Both Rob (OFFSPEC) and Pascal (WISH) have cause to create a 2D plot from a series of single-spectrum workspaces. For the 2D plot work correctly the data needs to be joined together (which can be done with ConjoinWorkspaces) and the Y-Axis of the workspace needs to be able to be specified by the user. 

This can be done in a long winded manner with CreateWorkspace but we are almost there with Conjoin, we just need some thing that can also take in a set of axis values and a label.

**Comment by KarlPalmen** [comment]
After a chat with Martyn, it was decided that an option of specifying the Y-axis be added to ConjoinWorkspace.
