### ISSUE TITLE
[IDA] Elwin - Allow User to Specify Range of Files

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#5858]
This issue was originally [TRAC 5012](http://trac.mantidproject.org/mantid/ticket/5012)

~~This ticket is blocked by :~~
~~[TRAC7515](http://trac.mantidproject.org/mantid/ticket/7515)~~

In the Energy Transfer tab of C2E, a user can specify a range of files to load by simply typing in the range, e.g. "`2012-2020`".  The interface takes the currently selected instrument, analyser and reflection options, finds the appropriate file(s), and outputs the result with appropriate file names.

No such mechanism exists in IDA.

A possible way to implement this so that a range of files of the form `[INST][RUN]_[ANALYSER][REFLECTION]_red.nxs` could be loaded, would be the following:
- Insist that the user inputs the range, as well as the instrument suffix (i.e. "`IRS2012-2020`" for the range of reduced Iris runs from 2012 to 2020).
- Add functionality to FileFinder to accept a wild card'''^[+]^''' as well as the instrument / run number hint and file extensions.
- Change the tabs so that they feed a wild card to FileFinder, placed between the range string and "`_red.nxs`".

'''[+]''' - The ability to accept any arbitrary string here, and not just a wildcard, would be useful elsewhere.

---

Keywords: IDA

**Update**
**This issue is no longer blocked by TRAC7515 (#8360)**

**Comment by ElliotAOram** [comment]
# Update on issue
This issue was stated to be blocked by TRAC7515 (#8360) . This is no longer the case as such work can commence on this issue.
