### ISSUE TITLE
GroupDetectors should be cleverer with file type

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#5879]
This issue was originally [TRAC 5033](http://trac.mantidproject.org/mantid/ticket/5033)

If you give GroupDetectors an XML file with a '.map' extension it falls over immediately.

I would think it be possible to peek at the first line and if it has an <?XML tag then assume it's XML

**Comment by shahrozahmed1** [comment]
This issue seems to have been fixed

**Comment by FedeMPouzols** [comment]
This is working. GroupDetectors v2 supports xml and map extensions, and also the algorithm dialog gives a explicit list of extensions/formats: xml/map/all files.
