### ISSUE TITLE
Look into wrong instrument display using remote desktop (VPN)

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#5909]
This issue was originally [TRAC 5063](http://trac.mantidproject.org/mantid/ticket/5063)

When using remote desktop to a Windows 7 computer with the following spec:

OS Name	Microsoft Windows 7 Professional
Version	6.1.7601 Service Pack 1 Build 7601
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	NDW892
System Manufacturer	Dell Inc.
System Model	OptiPlex 980
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz, 2927 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A05, 03/11/2010
SMBIOS Version	2.6
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume2
Locale	United Kingdom
Hardware Abstraction Layer	Version = "6.1.7601.17514"
User Name	CLRC\ajm64
Time Zone	GMT Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.99 GB
Available Physical Memory	1.93 GB
Total Virtual Memory	16.0 GB
Available Virtual Memory	9.33 GB
Page File Space	7.99 GB
Page File	C:\pagefile.sys

Areas of the SANS2D detectors when viewed in Mantidplot gets populated with the wrong information. 

See the attached picture, which shows to the left the 'front' detector and to the right the 'rear' detector. Click on Pick tab to get information about the individual detectors. When doing this it display back that parts of the 'rear' detector, as approximately shown by the red circle in the attached picture, belongs to the 'front' detector bank where in fact it belongs to the rear detector bank. 

Perhaps this is just an issue for VPN into this particular computer.

**Comment by NickDraper** [comment]
nomachine seems to work better
