### ISSUE TITLE
Improve migration script

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#6043]
This issue was originally [TRAC 5197](http://trac.mantidproject.org/mantid/ticket/5197)

Currently the migration script only handles simple string replacements and no-arg returns from simple API calls. It also does not handle Python algorithms at all.

It should be improved so that all of these cases are handled.

**Comment by martyngigg** [comment]
The old Python API has been gone for a while I don't think this is worth the time and effort.

**Comment by NickDraper** [comment]
i agree
