### ISSUE TITLE
Mantid Preferences - Unable to Change Facility/Instrument

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#6044]
This issue was originally [TRAC 5198](http://trac.mantidproject.org/mantid/ticket/5198)

To reproduce:
- Go to View->Preferences...->Mantid->Instrument.
- Change the facility and instrument, then click Apply/Ok.

The user is presented with an unexpected exception, qouting "File not found".

(This was seen changing from a default of ISIS to SNS on Win7, 64 bit).

**Comment by DavidFair** [comment]
Can't reproduce, closing as fixed
