### ISSUE TITLE
Linux rpm instrument directory permission incorrect

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#6066]
This issue was originally [TRAC 5220](http://trac.mantidproject.org/mantid/ticket/5220)

The linux rpm instrument directory permissions is not
writable to everyone. An effect of this is that .vtp
files cannot be written to this directory from an installed
version on Linux, and instead default to /tmp. 

In cmake it is setup to be writable but somehow loses
this knowledge. Note this effect is only seen on Linux not Mac (or windows
for that matter).

Make this directory writable on linux also

**Comment by martyngigg** [comment]
No longer relevant. The directories are not writable but now the files go to the mantid user file directory.
