### ISSUE TITLE
Directory handling is not consistent in the Manage User Directories Dialog

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#6098]
This issue was originally [TRAC 5252](http://trac.mantidproject.org/mantid/ticket/5252)

Spencer has reported:

```
There is a 'feature' which sometimes throws out my routines.
In the Data Search Directories list the location ends with / or \.
Default Save Directory when you Browse & Select doesn't have the that last / or \.
Then when I do os.path.join the location is incorrect.
If I remember I add the /  !
```

We need to have a much more consistent handling of directory paths throught Mantid, i.e properties files, GUI etc

---

Keywords: NewStarter

**Comment by Anders-Markvardsen** [comment]
this could be a good candidate for new starter

**Comment by NickDraper** [comment]
if restricted to the paths dialog I agree
