### ISSUE TITLE
Enable SaveMask() to support MaskWorkspace with grouped detectors

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#6157]
This issue was originally [TRAC 5311](http://trac.mantidproject.org/mantid/ticket/5311)

SaveMask() is not able to work with workspaces with grouped detectors, i.e., one spectrum contain more than one detectors.  

Users sometime need to group detectors (such as SumSpectra()) and then create mask from MantidPlot's instrument view. 

This ticket is to make SaveMask() works under this situation.

**Comment by NickDraper** [comment]
archived until the masking redesign
