### ISSUE TITLE
SANS: Event time slicing slow...

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#6159]
sans_code
This issue was originally [TRAC 5313](http://trac.mantidproject.org/mantid/ticket/5313)

Steve asked me to put in a minor priority ticket for now
addressing that Sarah has found the event time slicing slow.

The task of this ticket is to understand better what is meant
by 'slow'.

**Comment by Mantid-Matthew** [comment]
I am closing this issue as we have implemented a new back end since this issue was opened.
