### ISSUE TITLE
SANS: Algorithm for to interface with external user FLL software

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#6226]
sans_feature
This issue was originally [TRAC 5380](http://trac.mantidproject.org/mantid/ticket/5380)

Steve writes:

Please could you create a ticket for the following.

This weekend on SANS2D we measured the first ever flux line lattice superconductors at ISIS with neutrons, and things went pretty well.

One of the contributing user groups has some clever software they have written to simulate the expected 2D QxQy intensities, tested against experiments at ILL. Obviously their program will need tweaking to simulate t-o-f data.

As input data to the simulation, they would like Mantid to output (as one or more files) which detector pixels are contributing to any given QxQy point in a reduced 2D pattern for any given time bin.

This could be a script they could run from within Mantid.

But on first thought it seemed to me that it should be possible to extract this information during a reduction...?

Probably create python script for this since an algorithm which will likely not be executed often, where speed is less of a concern,
and where the user may even want to be able adjust exactly what is outputted

Current status: wait to see what user come back with in their â€˜specâ€™ of exactly what they want.

**Comment by gemmaguest** [comment]
Closing as there has been no movement on this for 5 years and it doesn't seem to be a priority at the moment
