### ISSUE TITLE
Re-categorise PythonAlgorithms

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6491]
This issue was originally [TRAC 5645](http://trac.mantidproject.org/mantid/ticket/5645)

We have too many python algorithms for them to be categorised purely by the development language they were written in.

I suggest one of the following:

* Completely ignore the fact that the algorithms were written in Python and give them a category that only depends upon what they do.
* Do the above, but also keep them dual categorised as python algorithms too.

@Nick : I'm only writing the ticket so that it's recorded as a useful task to be undertaken. Reassign as required.

**Comment by NickDraper** [comment]
Duplicate of #8840
