### ISSUE TITLE
Bug with negative xstep in IDF

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6513]
This issue was originally [TRAC 5667](http://trac.mantidproject.org/mantid/ticket/5667)

Message from Dennis below:

"NEW BUG:  There was a side-effect to the new SXD definition file.  If a new calibration file is not loaded, when an SXD peaks workspace is written to an ISAW peaks file, any detector where xstep is negative in the definition file gets written with a NEGATIVE WIDTH.  Similarly, if ystep is negative in the definition file, the detector gets a NEGATIVE HEIGHT.  We could fix this symptom by making SaveIsawPeaks() just write the absolute value of the width and height to the file, but fixing the symptom may hide worse problems that will be hard to find later.  That is, however the instrument definition information gets placed in the rectangular detector information, it is now getting set with a negative width and/or height for some of the SXD detectors.  Perhaps someone who is more familiar with the system than I could check this out and fix it in a way that should not break other things.  The negative width and height "broke" the detector calibration in Mantid, so I just used an editor to make them positive and used that fixed peaks file to do the calibration in ISAW."

The offending IDF is attached.

**Comment by NickDraper** [comment]
Thsi is too old and has not caused any difficultites in the last 5 years
