### ISSUE TITLE
SANS: Investigate SANS2D distances in Geometry tab

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#6544]
sans_bugfix
This issue was originally [TRAC 5698](http://trac.mantidproject.org/mantid/ticket/5698)

During testing of http://trac.mantidproject.org/mantid/ticket/5268 it was found that the sample - detector
distances saved in canSAS do not match those displayed in 
the geometry tab for SANS2D runs, at least as calculated using
0.001*sqrt(X^2+Z^2). 

It is strongly believed that the distances save with canSAS are
correct.

This ticket: first make Richard/Steve of this discrepancy. If they
think there is something not right then fix this.

**Comment by Mantid-Matthew** [comment]
This ticket refers to the old GUI
