### ISSUE TITLE
[Indirect] - Complete OS Support for F2Py Routines

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#6645]
This issue was originally [TRAC 5799](http://trac.mantidproject.org/mantid/ticket/5799)

This ticket was spawned from http://trac.mantidproject.org/mantid/ticket/5411.

Currently, the [http://www.scipy.org/F2py F2Py] routines currently being used by the Indirect users are only supported on the 32bit Windows builds of Mantid.  (Do a grep for "`is_supported_f2py_platform()`" to find the relevant Python files.  `IndirectImport` contains the code responsible for only importing the F2Py libs if Win32 is the current platform.)

The goal here is that the various F2Py routines we have should be available on ''all'' OS's supported by Mantid, and this should be done without having to manually compile and package the libraries along with Mantid each time a change or new OS is needed.  Talk to Martyn for more info on this, but essentially this should be achieved by having the Mantid build process include compiling the F2Py libraries from their Fortran source code.

Up to this point Spencer Howells has been solely responsible for compiling the F2Py code, so I'm sure a chat with him at some point would be useful.  In the meantime he has advised that the relevant files are mounted at `\\Britannic\modes3\MIDAS` and `ftp://ftp.nd.rl.ac.uk/pub/ida/MIDAS/F2Py/`

Finally, see attached for two DLLs that may help to get the Win64 version of the libs to work on machines that were not used to compile them.

---

Keywords: Indirect

**Comment by martyngigg** [comment]
This is becoming more relevant with the move to cloud Linux machines and needs some consideration on how to handle it.
