### ISSUE TITLE
Trying to load a bad file causes a segfault

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#6651]
This issue was originally [TRAC 5805](http://trac.mantidproject.org/mantid/ticket/5805)

During the testing of the new streaming project at the SNS, I discovered that some of the files that were produced caused mantid to segfault and crash.  Although these files are probably created incorrectly and may contain junk, we still should fail gracefully rather than segfault.

These files are supposed to be event nexus files.

**Comment by NickDraper** [comment]
Tested in M3.10:

The file now just reports an error and there is now crash.  The file itself is obviously a mess and cannot be read properly by HDF reader either.

There is nothing more we should do in Mantid
