### ISSUE TITLE
Motor postions for SNAP

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#6664]
This issue was originally [TRAC 5818](http://trac.mantidproject.org/mantid/ticket/5818)

SNAP has 4 motor positions of the East and West sides in the logs.  Need mapping from log positions to more accurate positions in the IDF.  Also need CalibrateRectangularDetectors to output log positions and accept as input corrected positions from user.

**Comment by NickDraper** [comment]
surely this has been done by now?
