### ISSUE TITLE
VTP on shared drive.

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6745]
This issue was originally [TRAC 5899](http://trac.mantidproject.org/mantid/ticket/5899)

LoadInstrument algorithm can't process *vtp files located on a shared drive. This is at least the state on Windows.

Here's how to reproduce the issue.

* Put the IDF xml on a shared drive
* Run load instrument on that xml file (should work fine and generate the vtp)
* Run load instrument on that xml file a second time round. Throws.

This does not happen if the vtp file is on a local drive. 

Note that the exception is thrown from DOMParser::parse located at line 115 in LoadParameterFile.cpp.

**Comment by NickDraper** [comment]
not a common use case - archived
