### ISSUE TITLE
Names of files saved by Indirect Diffraction interface must better match the raw file names

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#6793]
This issue was originally [TRAC 5947](http://trac.mantidproject.org/mantid/ticket/5947)

If the raw files for a particular run has a full instrument name as prefix rather than a short name, the output files must also have the full name

**Comment by ElliotAOram** [comment]
This issue has since been fixed. The indirect tab uses full instrument names for all instruments.
