### ISSUE TITLE
Remove setAlwaysStoreInADS from new Python API

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#6804]
This issue was originally [TRAC 5958](http://trac.mantidproject.org/mantid/ticket/5958)

The new Python interface currently sets each "sub algorithm" to store its output in the ADS when called through the simple API. This should be removed so that subalgorithms within Python algorithms behave in the same way as the C++ and the developer can then decide whether a workspace is actually kept for future use.

**Comment by martyngigg** [comment]
Duplicate #5617

**Comment by NickDraper** [comment]
agreed
