### ISSUE TITLE
Write a generic LoadImage algorithm

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#6843]
This issue was originally [TRAC 5997](http://trac.mantidproject.org/mantid/ticket/5997)

Write an algorithm to load an image file to a workspace, and create a 'basic' instrument definition if we cannot match up to an existing one based on filename.  This should vote to open files like any other load algorithm but not normally return a particularly high preference so other more specific loaders can override it.

File type we absolutely have to support:
- TIFF
- FITS

It would make sense to use a library that allows us to generically handle multiple file formats.  Two that have spring to mind are:
1. BOOST Generic image library hereafter known as GIL
1. Freeimage

Both work by using the underlying specific libraries LibTIFF, libPNG etc, but give a consistent interface on top.  FreeImage looks simpler as it is just about loading and saving images, GIL is more complex as it also supports image algorithms in a generic way, but is header only and therefore already available on all platforms.

Neither have support for FITS out of the box, but both allow a plug in mechanism to support new formats.  A quick search has found a plugin for FITS in GIL.
http://ds33.ncsa.uiuc.edu/trac/browser/DMS/afw/trunk/include/lsst/afw/image/fits/fits_io.h?rev=13739

**Comment by FedeMPouzols** [comment]
@NickDraper , @OwenArnold : this was an interesting ticket that I'd like to bring up and keep in mind for the discussions next weeks. 
From the imaging point of view, having support for common image formats (TIFF, PNG) well integrated in Mantid would be most convenient. I'd say it's a strong requirement for the near future. FITS is supported via `LoadFITS`.
My recent experience with FreeImage from Python is good. Sufficiently generic support for TIFF images can be challenging, but that's more a problem of the standard than the libraries.

**Comment by FedeMPouzols** [comment]
GIL looks interesting for image processing. It has support for 3 formats: JPEG, TIFF and PNG, which is far less than what FreeImage provides but probably covers >95% of practical needs. But to have support for these file formats you need plugins/hpp files and linking against different libraries: libjpeg, libpng, libtiff.

A point in favor of FreeImage is that I noticed that one of our current dependencies, the `opencascade dev` package depends on `freeimage dev`. So for the CI infrastructure it would only require adding the windows libraries which always need to be added to the `ThirdParty` set anyway.
