### ISSUE TITLE
The Instrument Specific Algorithm Problem

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6876]
This issue was originally [TRAC 6030](http://trac.mantidproject.org/mantid/ticket/6030)

Users, particularly Pascal, are continually (and rightly) complaining that algorithms that should work on their data do not. This is starting to damage the project reputation.

Developers (probably at the SNS, but not necessarily, I'm not pointing fingers here) are continually writing algorithms that cannot cope with 1:many mapping of spectra to detector like we have at ISIS.

We need a way to catch this problem, and enforce that algorithms cannot be written/submitted that break when used on instruments outside of the facility.

**Comment by NickDraper** [comment]
Has to be handled on a case by case basis, Specific algorithms must be named as such to make things specfifc
