### ISSUE TITLE
SANS Diagnostics Unhandled exception if transmission file selected

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#6888]
sans_bugfix
This issue was originally [TRAC 6042](http://trac.mantidproject.org/mantid/ticket/6042)

steps to reproduce:
1. open the sans isis interface
1. load SANS2D...22024
1. Click Horizontal integral (eith fron or rear detector)
1. Error as the workspace only contains 8 spectra

**Comment by Mantid-Matthew** [comment]
This does not lead to an unhandled exception in the new GUI
