### ISSUE TITLE
SANS Diagnostics cannot use file finder with first use

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#6889]
sans_bugfix
This issue was originally [TRAC 6043](http://trac.mantidproject.org/mantid/ticket/6043)

Cannot use the file searching facility on first use of the interface.
1. Open sans isis
2. Diagnostics tab
3. enter "2500"
4. Try to get this to load the file

This is imply because there are no other active controls on the for to tab to so the file widget never loses focus.

You could add a handler for the enter keypress, which would be a good idea anyway.

**Comment by Mantid-Matthew** [comment]
This is not an issue in the new Interface
