### ISSUE TITLE
Seg fault for running two tight-looped quick algorithms while executing another

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#6891]
This issue was originally [TRAC 6045](http://trac.mantidproject.org/mantid/ticket/6045)

This was previously a problem for one thight loop & another alg http://trac.mantidproject.org/mantid/ticket/2883.

It is better now in that it takes two tight loops and another alg to crash.

Set this going in the interpreter and a python script window.
```
for i in range(10000):
   test = CreateWorkspace([1],[1],[1])
```
Then load a workspace using the GUI.

**Comment by martyngigg** [comment]
No longer an issue as the appropriate GIL usage is in place. The live event data processing means that this has to work.
