### ISSUE TITLE
Proper fix to SliceViewer Axis selection

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6892]
This issue was originally [TRAC 6046](http://trac.mantidproject.org/mantid/ticket/6046)

This ticket is blocked by : 
- [X] [TRAC6040](http://trac.mantidproject.org/mantid/ticket/6040)

Was discovered at end of release 2.4 that automatic axis selection wasn't working properly for MDWorkspaces, although it was for MDHisoworkspaces. This required a rapid fix http://trac.mantidproject.org/mantid/ticket/6040.

Although I had time to add some python tests to verify this new behaviour. The fix itself needs improving. Most of the functionality associated with the fix does not belong in MantidQtAPI.

**Comment by OwenArnold** [comment]
possibly the use of the MDFrames might make this easier?

**Comment by Mantid-Matthew** [comment]
Applies to old version of sliceviewer
