### ISSUE TITLE
Investingate SliceViewer Problem 2.2

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#6912]
This issue was originally [TRAC 6066](http://trac.mantidproject.org/mantid/ticket/6066)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)

Problem reported by Russell Ewings:

"Actually I just noticed something about this particular dataset which might explain the problem. You'll notice in the script I sent you that my binning along the AlignedDim called [0,0,L] is from -6 to 6 with 1 bin, and along DeltaE it is 100 to 150 with 1 bin. When I invoke the line viewer the start and end points, and thickness, of these axes are wrong - [0,0,L] is listed as start 0, end (greyed out) 0, thickness 0.1; and DeltaE is start 100, end 100, thickness 0.1. If I manually alter these to be what I set them in the SliceMD command then the line viewer does work. If I follow the same procedure on a slice generated using BinMD then again it works fine as long as I manually change the slice thicknesses.

So it seems the problem is actually what the slice viewer picks up for these axes which have been integrated, and consistency between what the line viewer and slice viewer are picking up."
"

**Comment by OwenArnold** [comment]
@matthew-d-jones. Is this something you have already fixed?

**Comment by matthew-d-jones** [comment]
@OwenArnold Yes, this has been fixed; the Slice Viewer does sensible things with workspaces with integrated dimensions now.
