### ISSUE TITLE
Decide on the future of RebinByPulseTimes and CountEventsInPulses

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#6915]
This issue was originally [TRAC 6069](http://trac.mantidproject.org/mantid/ticket/6069)

We have two similar algorithms and need to consider what the future plan is for them.  [RebinByPulseTimes](http://www.mantidproject.org/RebinByPulseTimes)  and [CountEventsInPulses](http://www.mantidproject.org/CountEventsInPulses). If they are as similar as they seem we only want one.  Look into the functionality and implementation and decide what the future path should be and create the appropriate tickets.

**Comment by peterfpeterson** [comment]
`CountEventsInPulses` was deleted in fac4f470a604e1a418e101258a19eb8296fcfabe (2016).
