### ISSUE TITLE
MultiFileNameParser constructor is run alot on startup

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#6922]
This issue was originally [TRAC 6076](http://trac.mantidproject.org/mantid/ticket/6076)

On startup we have to initialize all of the algorithms and this causes anything using a MultipleFileProperty to construct a MultiFileNameParser object. The constructor does a fair bit of work and it would be better for init times if this could be avoided. This ticket is a task to check whether initialization of MultipleFileProperty  can be improved.

**Comment by NickDraper** [comment]
archived - apparently not the main cause of of the startup performance
