### ISSUE TITLE
Apply button does not work on setting workspace colour

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#6930]
This issue was originally [TRAC 6084](http://trac.mantidproject.org/mantid/ticket/6084)

If one selects View->Preferences->(General)->Colors, and set the workspace colour, the Apply button will not apply the change. The change takes effect when on presses the OK button to close the dialog box.

This does not apply to the panel colour, which does respond to the Apply button.

This was observed on Windows 7 64-bit.

**Comment by NickDraper** [comment]
archived
