### ISSUE TITLE
Adjust Muon IDFs to use locations tag

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7029]
As demonstrated in comment below: Arturs Bekasovs (2014-03-25T10:04:48): for the Muon instruments Musr, EMU, ARGUS and HIFI use <locations> to make IDFs for these instrument shorter.

For document on IDFs see http://docs.mantidproject.org/nightly/concepts/InstrumentDefinitionFile.html

Make these changes and check that detectors are still in the same positions.

**Comment by Anders-Markvardsen** [comment]
@tom-perkins would you be OK if I reassign this issue to you or you reassign it to yourself. I still think it is worth having this issue in the backlog for a rainy day

**Comment by Anders-Markvardsen** [comment]
Hi @AnthonyLim23 had this issue in my list. It is a maintenance issue which as learning exercise, to learn how we describe IDFs, I would recommend you have a go at early in the next release cycle. If you have any question concerning IDFs don't hesitate to find me also.
