### ISSUE TITLE
Currently there are two ways to set a WS name, there should be 1

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7033]
This issue was originally [TRAC 6187](http://trac.mantidproject.org/mantid/ticket/6187)

This ticket is blocks :  [TRAC6797](http://trac.mantidproject.org/mantid/ticket/6797)

Issue details are blank in trac

 - - - - 
Keywords: Maintenance

**Comment by martyngigg** [comment]
Changing this is going to require more effort that the gain will provide.
