### ISSUE TITLE
Reporting and Archiving Architecture UML

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#7097]
This issue was originally [TRAC 6251](http://trac.mantidproject.org/mantid/ticket/6251)

This is actually quite an important problem to solve. 

In general we are plagued by legacy documentation (particularly of an architectural nature). Quite often we might have a class diagram as an image, but the source file has gone missing, or is corrupted, is platform-specific, or in some non-standard legacy format. 

This extension looks quite good and would solve a number of our problems. http://www.mediawiki.org/wiki/Extension:UML

Under this ticket we should :

1) Decide what to do. If we agree to implement the UML extension above, then direct someone to do it under a spearate ticket.

2) Go through the existing documentation and ticket the owner to port their documentation to the new format.

**Comment by NickDraper** [comment]
No longer relevant as we would not use mediawiki for this kind of documentation any longer
