### ISSUE TITLE
Q-vector display convention

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#7143]
This issue was originally [TRAC 6297](http://trac.mantidproject.org/mantid/ticket/6297)

Mantid uses the inelastic scattering convention ```Q=ki-kf```. This confuses the single crystal diffraction people who are accustomed to ```Q=kf-ki```.

Add a feature for all displays (PeaksWorkspace in a table, splatter view of VATES simple gui, slice view, ...) to apply the -1 for Q-vector and hkl values. This should be selectable, with a default value set in the instrument geometry/parameter file.

**Comment by VickieLynch** [comment]
Duplicate to Crystallography convention for displaying HKL #12863
