### ISSUE TITLE
Make MergeMDfiles run in parallel

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#7284]
This issue was originally [TRAC 6438](http://trac.mantidproject.org/mantid/ticket/6438)

Recent changes to MergeMD files done in anger disable parallel executions and splitting of the newly generated boxes. 

In addition to that, the splitting parameters were never available for this algorithm too. 

The ticket should fix these inconveniences.

**Comment by NickDraper** [comment]
Done by Ian bush
