### ISSUE TITLE
[C2E] - Calibration tab doesn't work for event data

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#7316]
This issue was originally [TRAC 6470](http://trac.mantidproject.org/mantid/ticket/6470)

Issue details are blank in trac

**Comment by DanNixon** [comment]
This is not an issue at the moment.
The calibration algorithm is specific to ISIS and currently no indirect inelastic instruments record data in event mode.

**Comment by NickDraper** [comment]
Is it documented anywhere that this only supports histogram data?

**Comment by DanNixon** [comment]
@NickDraper It is now.
