### ISSUE TITLE
FakeEventData listener does not generate ws with correct x-values and lacks any description

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#7320]
This issue was originally [TRAC 6474](http://trac.mantidproject.org/mantid/ticket/6474)

If one runs startLiveData and tests it using FakeEventDataListener, the FakeEventDataListener generate events in the range from 40000 to 60000 but user have no ways of determining that without running a debugger. 

The event workspace comes with ranges from 0 to 10^-308 which also not helping to identify the range of the data. 

Needed:
Some description of the FakeEventDataListener with the range of the events it generates. 

correct X-axis ranges in generated workspace. 

Some description of the FileEventData Listener. It works, but it is absolutely unclear how to use it.

**Comment by NickDraper** [comment]
archived
