### ISSUE TITLE
SANS: how far down the road keep events

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#7378]
sans_code
This issue was originally [TRAC 6532](http://trac.mantidproject.org/mantid/ticket/6532)

This task is to discuss with instrument scientists how far down the read to event data in reduction. This task is associated with tickets http://trac.mantidproject.org/mantid/ticket/6530 and http://trac.mantidproject.org/mantid/ticket/6531

**Comment by AntonPiccardoSelg** [comment]
This has been implemented for the new ISIS SANS reduction backend. We can keep events all the way until we convert to momentum transfer units.
