### ISSUE TITLE
MantidPlot GUI does not allow space character in table workspace column name

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#7395]
This issue was originally [TRAC 6549](http://trac.mantidproject.org/mantid/ticket/6549)

If in MantidPlot, one creates a table then converts it to a table workspace, one cannot then give a column in that table workspace a name that contains a space character. This space character is removed if one attempts to do this.

While this may be a necessary restiction on QTI tables, it is not needed for table workspaces. Furthermore, some algorithms such as ApplyCalibration require a table workspace whose columns have specific names that have a space character.

**Comment by NickDraper** [comment]
archived
