### ISSUE TITLE
SANS: Add LOQ Mantid/COLETTE systemtests

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#7430]
sans_test
This issue was originally [TRAC 6584](http://trac.mantidproject.org/mantid/ticket/6584)

This ticket is blocks :  [TRAC6228](http://trac.mantidproject.org/mantid/ticket/6228)

Add LOQ Mantid/COLETTE systemtests around
data Steve emailed a little while back.

Gesner the data Steve too big to add to this ticked
hence have emailed them separately.

Note once added, make a note of these on http://www.mantidproject.org/SANS_SystemTests

The data below are from Cycle 11/2.

Steve created the add files described in email further below from
(likely):

CARBON
sample SANS 61239-add was: 61217+61231+61239

can SANS 61240-add was: 61218+61232+61240

TK49
(This was harder to fathom as some sans runs are called _TRANS and vice versa! But from the journal, checking the number of spectra...)

sample SANS 61485-add was: (at least) 64179+64185 (possibly also +64191+64197)
sample TRANS 64182-add was: (at least) 64176+64182 (possibly also +64188+64194)

can SANS 64184-add was: (at least) 64178+64184 (possibly also +64190+64196)
can TRANS 64181-add was: (at least) 64175+64181 (possibly also +64187+64193)

direct beam 64180-add was: (at least) 64174+64180 (possibly also +64186+64192)

That ok?

Steve

From: Markvardsen, Anders (STFC,RAL,ISIS) 
Sent: 19 March 2012 09:49
To: King, Stephen (STFC,RAL,ISIS)
Subject: FW: SANS System Tests - and another priority job!

Hi Steve,

Could I ask a few questions about the LOQ Mantid/COLETTE systemtests
you sent a little while back. 

Your attached zip file contains two subdirectories:

COLETTEAnalysis
MANTIDAnalysis

I would like to reproduce the results (or parts of) in MANTIDAnalysis.

In this directory you have 4 .csv files. One of these is Reduce_Carbon_1D.csv:

sample_sans 61239-add   sample_trans    61235   sample_direct_beam  61236   can_sans    61240-add   can_trans   61236   can_direct_beam 61236   output_as   MAN1D_2_Q

Another is Reduce_Standard_1D.csv:

sample_sans 64185-add   sample_trans    64182-add   sample_direct_beam  64180-add   can_sans    64184-add   can_trans   64181-add   can_direct_beam 64180-add   output_as   MAN1D_1_Q

From which runs did you produce 61239-add, 61240-add, 64185-add, 64182-add, 64180-add, 64184-add and 64181-add. 
Or alternatively could you email me a copy of these added data files please (or put on babylon5)?

Thanks,
Anders

From: King, Stephen (STFC,RAL,ISIS) 
Sent: 11 August 2011 17:07
To: Markvardsen, Anders (STFC,RAL,ISIS)
Cc: King, Stephen (STFC,RAL,ISIS)
Subject: SANS System Tests - and another priority job!

Anders,

I have spent the day putting together some LOQ data for you to use for COLETTE comparison system(?) tests.  Extract the attached using folder names.

/COLETTEAnalysis contains data reduced in COLETTE (and the script that generated it), our long established reduction VMS program for LOQ
/MANTIDAnalysis is using SVN13869

.RKH and .txt are ASCII reduced data (written by SaveRKH).
.XML are the same data written by SaveCanSAS1D.

Filenames starting COLâ€¦ are from COLETTE, those starting MANâ€¦ from Mantid.

A _1_ in the filename means the sample â€˜Standardâ€™, and _2_ in the filename means the sample â€˜Carbonâ€™.

The comparisons for data from the main detector look very good.

Steve

**Comment by Mantid-Matthew** [comment]
The system tests are currently being updated to use new data. It seems unlikely that a systemtest based on this old data would be applicable so closing this ticket. Will check with instrument scientists.
