### ISSUE TITLE
Refactor LoadInstrument

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7435]
This issue was originally [TRAC 6589](http://trac.mantidproject.org/mantid/ticket/6589)

Seperate the Instrument definition and parsing of XML.

This is likely to include
* Creation of an XSD file
* Auto Generated code from the XSD
* Refactor so the InstrumentDefinitionParser works on the generated Code, not the XML
* Refactor other places where the XML is used directly

**Comment by Anders-Markvardsen** [comment]
This issues is superseded by work with ESS on Instrument 2.0
