### ISSUE TITLE
InstrumentDefinitionParser review

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7436]
This issue was originally [TRAC 6590](http://trac.mantidproject.org/mantid/ticket/6590)

From technical review

Add a comment to code where helper.Adjust is called in InstrumentDefinitionParser to explain why a new instance of InstrumentDefinitionParser is required

**Comment by Anders-Markvardsen** [comment]
Can't see any reference to code helper.Adjust any longer
