### ISSUE TITLE
Smarter Integrated Peak Area Plotting

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#7666]
This issue was originally [TRAC 6820](http://trac.mantidproject.org/mantid/ticket/6820)

This ticket is blocked by : 
- [X] [TRAC6521](http://trac.mantidproject.org/mantid/ticket/6521)
- [ ] [TRAC7410](http://trac.mantidproject.org/mantid/ticket/7410)
- [ ] [TRAC7411](http://trac.mantidproject.org/mantid/ticket/7411)

In http://trac.mantidproject.org/mantid/ticket/6521 I implemented a warning around the fact that Peaks integrated using IntegratedPeaksMD, could be shown in the PeaksViewer/SliceViewer ontop of a workspace, that has a different coordinate system from the one the PeaksWorkspace was integrated in. i.e. You view peaks integrated using IntegratePeaksMD (from a workspace in LabQ), then you take the HKL workspace (ultimately made from the same LabQ workspace) and visualize that in the SliceViewer, with the integrated workspace ontop. The problem being that the radius is being shown in LabQ, whereas the underlying features of the MDWorkspace are in HKL coordinates.

To fix this, it should be possible to take the UB off the MDWorkspace (assuming it is a HKL one, which we can now determine using the getSpecialCoordinates routine). Then invert the UB and perform a multiplication with the Coordinates of the Radius endpoints. Then set the radius end points to be these newly calculated coodinates (should generate an elipse of some kind).

This is a feature Pascal wants, which is why the priority has been set high.

From Anton : "The problem is that the radius is expressed in the coordinate system in which the integration occurred. If you are visualising in a different coordinate system you have a problem".

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92 Since this is `SCD` related I am passing this to you. Please feel free to reassign if you think that this is not adequate.

**Comment by samueljackson92** [comment]
Removing high priority as this dates from 2013 originally. It needs to be investigated whether this is still a problem, but I'm going to guess nothing has been done about it yet.

**Comment by martyngigg** [comment]
Closing this as it relates to the old sliceviewer and the issue has not been raised for the new sliceviewer yet.
