### ISSUE TITLE
Integrate CHOP and Garretts Python Scripts into single tool

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#7737]
This issue was originally [TRAC 6891](http://trac.mantidproject.org/mantid/ticket/6891)

This ticket is blocks :  [TRAC7597](http://trac.mantidproject.org/mantid/ticket/7597)

We have 2 different sets of routines/tools relating to determining what chopper settings to use, namely `CHOP` (in reality `PyChop`) and the wonderfully named "Garrett's Python Scripts".

The aim is to combine these into a single version.
The implementation of an interface has been moved into it's own ticket http://trac.mantidproject.org/mantid/ticket/7597

Do we need to list out the requirements for this tool ?

**Comment by mducle** [comment]
Garrett's scripts are here: https://github.com/granrothge/Resolution_Planner

CHOP was ported to PyChop a long time ago and also includes information and does not at present include information for the SNS instruments. In principle it can be used with the attached parameters: 

[sns_pychop.zip](https://github.com/mantidproject/mantid/files/5246644/sns_pychop.zip)

But this has not be verified against Garrett's scripts nor included in the code.
