### ISSUE TITLE
SliceViewer history problem

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#7766]
This issue was originally [TRAC 6920](http://trac.mantidproject.org/mantid/ticket/6920)

Load an MD workspace, and plot it using SliceViewer. Use the dynamic rebinning. It will create an MD histo workspace. The history will contain BinMD as the last step, but it has no InputWorkspace. So re-running the script that you get from history will fail at that step.

1 Day

**Comment by OwenArnold** [comment]
@AndreiSavici Is this still a problem?

**Comment by AndreiSavici** [comment]
Not relevant any more
