### ISSUE TITLE
Setting columns from other columns values does not work

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#7776]
This issue was originally [TRAC 6930](http://trac.mantidproject.org/mantid/ticket/6930)

Create a mantid tableworkspace in any way you like (e.g. a mantid table is returned from any fit in MantidPlot)

then
1. In MantidPlot highlight the table and 
2. Open HRP38692a from AutoTestdata
3. right click within table and do 'Add Column'
4. right click on the header of the new column and do 'Set column values ...'

which open a window with the title 'MantidPlot - Set column values'

Functionality in this window is not working
1. the dropdown box to the left of the button 'Add function' is empty
2. When using the Add column button to add columns e.g. this does not work (nothing happen when apply is pressed)

Note 2) above does work with a QTIplot native table.

**Comment by NickDraper** [comment]
mantidplot is deprecated
