### ISSUE TITLE
LoadRKH: browse tab settings

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7829]
sans_feature
This issue was originally [TRAC 6984](http://trac.mantidproject.org/mantid/ticket/6984)

This ticket is blocks :  [TRAC6985](http://trac.mantidproject.org/mantid/ticket/6985)

From Richard Heenan:

LoadRKH, browse tab, could default to â€œall filesâ€, not â€œ.datâ€

**Comment by Mantid-Matthew** [comment]
This issue applies to the old interface
