### ISSUE TITLE
LoadRKH should default the new workspace name to the name of the file being input.

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7831]
sans_feature
This issue was originally [TRAC 6985](http://trac.mantidproject.org/mantid/ticket/6985)

This ticket is blocked by : 
- [ ] [TRAC6984](http://trac.mantidproject.org/mantid/ticket/6984)

Three options for doing this:
1. Create a custom dialog that inherits from the generic dialog box, get hold of the relevant controls and add an signal and slot to do the work.
1. Just create a custom dialog box for this algorithm from an hand built ui file
1. Build a generic framework for allowing the inputs on one property to affect other properties in the same algorithm.

I strongly advise AGAINST option 3.

**Comment by gemmaguest** [comment]
Closing as there has been no movement on this for 5 years and it doesn't look like this algorithm is much used
