### ISSUE TITLE
Obscure PV crash

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#7852]
This issue was originally [TRAC 7006](http://trac.mantidproject.org/mantid/ticket/7006)

Paraview will crash if you try to load it up with an MD Workspace that only has 1 bin in each dimension.

This is handled in the VSI by disabling the launch icon for the VSI until the MDWorkspace has sufficient bins. This mechanism does not protect us in full blown paraview. I observed this on 32 bit windows, but it should affect all platforms. If the file has more than 1 bin in each dimension loading works fine.

The ideal schenario is that it should exit gracefully when this happens.

**Comment by OwenArnold** [comment]
This probably is no longer valid

**Comment by AntonPiccardoSelg** [comment]
Seems to not be relevant any longer. You cannot load MD workspaces with only 1 bin in each dimension. Closing this issue.
