### ISSUE TITLE
Very different environments for Python algorithms, Scripting Console vs. loaded on start up

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#7853]
This issue was originally [TRAC 7007](http://trac.mantidproject.org/mantid/ticket/7007)

From James Lord:

I can write a Python algorithm in the Scripting console and it only needs "from mantid.api import *" as in the online help. If I then try to have that algorithm auto-load on Mantid startup (e.g. View - Preferences - Mantid - Directories - Python Algorithms) I have to make it import several extra libraries such as mantid.kernel, mantid.simpleapi and numpy. Debugging this was not trivial as it means much trial and error, restarting Mantid each time!

**Comment by martyngigg** [comment]
The workbench scripting console does this properly and does not have hidden imports. This is not worth pursuing for MantidPlot.
