### ISSUE TITLE
New curve style works only with qtiplot lines

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#7889]
This issue was originally [TRAC 7043](http://trac.mantidproject.org/mantid/ticket/7043)

In Add/remove curves dialog the new style setting works only for qtiplot lines. We should either disable the checkbox for mantid curves or make it work

**Comment by Anders-Markvardsen** [comment]
Roman confirms this is still a current bug.

A candidate for a new starter issue

**Comment by NickDraper** [comment]
This will superceeded in M4, removing the long parked issue
