### ISSUE TITLE
Show current folder only doesn't work for mantid curves

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#7890]
This issue was originally [TRAC 7044](http://trac.mantidproject.org/mantid/ticket/7044)

This is a checkbox in Add/remove curves which filters curves according to project folder. It works only for qtiplot curves.

**Comment by Anders-Markvardsen** [comment]
Roman confirms this is still a current bug. 

A candidate for a new starter issue

**Comment by NickDraper** [comment]
This will be superseded in M4, removing this long parked issue
