### ISSUE TITLE
Limit the scope of Fit functions in IDF and parameter files

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#7912]
This issue was originally [TRAC 7066](http://trac.mantidproject.org/mantid/ticket/7066)

See http://www.mantidproject.org/NormaliseByDetector, which uses IDF type="fitting" to associate an equation with a detector. However, for this case the scope of this type="fitting" parameter is that particular algorithm only.

See http://www.mantidproject.org/NormaliseByDetector, which uses type="fitting" associate an equation with a detector. What we really want is to avoid confusion by being able to say that a particular equation in the parameter file belongs to a specific algorithm. i.e. type="Algorithm:NormaliseByDetector", and make it incompatible with fit functions so that it doesn't get automatically applied (for the wrong purpose) in the fitting framework.

Please talk to me about this if it doesn't make sense.

**Comment by Anders-Markvardsen** [comment]
Hi @OwenArnold should this issue be closed and arhieved since I am not aware that this feature have been requested since this issue/ticket was created

**Comment by OwenArnold** [comment]
Hi @Anders-Markvardsen. I think it would be a useful addition to the syntax, but I haven't had any further requests directly from instrument scientists for this feature.

**Comment by Anders-Markvardsen** [comment]
Hi @OwenArnold cheers for update - on this basis I am here proposing to archive this issue for future reference
