### ISSUE TITLE
Elipsoidal Integration and SliceViewer

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#7987]
This issue was originally [TRAC 7141](http://trac.mantidproject.org/mantid/ticket/7141)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)

SNS Single Crystal instrument scientists request that the shape of the ellipsoid be drawn in SliceViewer when ellipsoidal integration is used instead of spherical integration.

**Comment by OwenArnold** [comment]
This may be solved with the issue to handle any PeakShape not just elliptical peak shapes.
