### ISSUE TITLE
Live data plugin for watching modified files

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#7992]
This issue was originally [TRAC 7146](http://trac.mantidproject.org/mantid/ticket/7146)

Create a plugin for live data that watches for a file to modified and reload the file. This is useful for interacting with outside programs that can be configured to output to the same file frequently.

**Comment by NickDraper** [comment]
introductory low risk but slightly challenging task.

Speak to @NickDraper, @peterfpeterson or @mantid-roman

**Comment by peterfpeterson** [comment]
On linux, the watching would be done through [inotify](http://linux.die.net/man/7/inotify).
