### ISSUE TITLE
In Results table display results to two significant digits

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#8026]
This issue was originally [TRAC 7180](http://trac.mantidproject.org/mantid/ticket/7180)

Limiting the significant digits displayed on the error of the parameter to two and taking the decimal places displayed on the parameter value to match, i.e.

Fitted parameter 1.2345678 with error 0.007654321

Would become:

Fitted parameter 1.2346 with error 0.0077

**Comment by tom-perkins** [comment]
Discuss with scientists at next meeting
