### ISSUE TITLE
SegFault on CreateEmptyTableWorkspace

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#8096]
This issue was originally [TRAC 7250](http://trac.mantidproject.org/mantid/ticket/7250)

I was running from the script interpreter

```
w=CreateEmptyTableWorkspace()
w.addColumn('double','Value')
w.addRow([0.1])
```

Then, when I use the CreateEmptyTableWorkspace by clicking on the algorithm, and I name the output workspace as w, I get a segmentation fault. I seem to get this problem on Ubuntu 13.04 and Ubuntu 12.10, but it works on 12.04 and RHEL6

**Comment by AndreiSavici** [comment]
This issue is no longer valid. It works for me on Ubuntu 16.04 and RHEL7. I suggest we should close it

**Comment by martyngigg** [comment]
:+1:
