### ISSUE TITLE
Verify equations in Material class

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#8134]
This issue was originally [TRAC 7288](http://trac.mantidproject.org/mantid/ticket/7288)

It appears that the Material class does not return the correct values for:
- cohScatterXSection
- incohScatterXSection
- totalScatterXSection
- absorbXSection

It appears that most of these do not take wavelength into account. Also, totalScatterXSection returns a sum of two of the other values rather than information from NeutronAtom corrected for wavelength dependence.

**Comment by stuartcampbell** [comment]
@peterfpeterson  Is this still a problem ?

**Comment by peterfpeterson** [comment]
I don't remember anymore. Maybe?
