### ISSUE TITLE
QTI Tables and Mantid Table look the same in MantidPlot (on the Mac)

### ISSUE THREAD

**Issue by stuartcampbell** [mantidproject/mantid#8152]
This issue was originally [TRAC 7306](http://trac.mantidproject.org/mantid/ticket/7306)

This follows on from Ticket http://trac.mantidproject.org/mantid/ticket/6906 as it was found that on the Mac (or any other window system that doesn't show the icon in the sub windows) that you cannot tell the difference between the representation of a Mantid TableWorkspace or a QTI table.

**Comment by martyngigg** [comment]
No longer relevant now we are dropping MantidPlot
