### ISSUE TITLE
cmake for the SNS analysis computers

### ISSUE THREAD

**Issue by VickieLynch** [mantidproject/mantid#8192]
This issue was originally [TRAC 7346](http://trac.mantidproject.org/mantid/ticket/7346)

All the SNS analysis machines except biganalysis06 get this link error:
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../lib64/libGL.so: undefined reference to `_XGetRequest'

SNS Linux support just contacted me and said there is an nvidia libGL.so on the analysis machines except biganalysis06, so to make sure Mantid cmake finds the one in /usr/lib64 not /usr/lib64/nvidia:  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64

Pete requested that this be sorted out in cmake

**Comment by peterfpeterson** [comment]
This is invalid
