### ISSUE TITLE
Represent Ellipsoid peaks in the SliceViewer

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8257]
This issue was originally [TRAC 7411](http://trac.mantidproject.org/mantid/ticket/7411)

This ticket is blocks :  [TRAC6820](http://trac.mantidproject.org/mantid/ticket/6820),  [TRAC7410](http://trac.mantidproject.org/mantid/ticket/7410)

This capability will be needed for two reasons.

* Firstly, to show ellipsoid integrated peaks, when the peaks workspaces can carry the shape information.
* Secondly to allow spherical peaks to be transformed according to the UB of the MDWorkspace they are overlaying.

**Comment by AntonPiccardoSelg** [comment]
Ellipsoidal peaks can be displayed in the SliceViewer: https://github.com/mantidproject/mantid/pull/15490

Duplicate
