### ISSUE TITLE
3 SliceView crashes on Windows with fly.vtk

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8267]
This issue was originally [TRAC 7421](http://trac.mantidproject.org/mantid/ticket/7421)

I've just watched Nick repeat this on the lastest version of Mantid. All other views seem to work nicely, and I don't get the problem on my mac.

* Load the fly.vtk data and open VSI
* Bin it using the Rebin option to say (150*150*150) bins
* Open in the Three slice view -> Crash

If it's going to be a real problem to get the development environment up and running. Reassign the ticket to me, but I won't be able to look at it until next week (earliest).

**Comment by NickDraper** [comment]
Much time has passed and many imporvements have happened, this is probably fixed (and so low priority anyway)
