### ISSUE TITLE
Converge MD axis and Axis

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#8318]
This issue was originally [TRAC 7473](http://trac.mantidproject.org/mantid/ticket/7473)

Current MD axis implementation is not in any way related to Axis. 

This creates various difficulties in comparing/working with MD workspaces as separate workflow is necessary to work with MD Axis. 

This does not allow, for example, easy check if two workspaces are compatible, as current MD units are just captions which have noting in common with Mantid units (which identify that the data in two workspaces can not be usually added together and have to be converted one to another). 

The purpose of this ticket is to provide as much similar behaviour between MD Axis and Axis as reasonable. Ideally they have to become one. 

In minimal scenario, MD Axis should use the same units as Axis. (and this is Mantid Units provided by the unit factory)

**Comment by NickDraper** [comment]
This would be nice, but I don't see it happening any time soon - archived
