### ISSUE TITLE
ConvertToDiffractionMDWorkspace V1 and V2 produce different Lorentz corrections

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#8320]
This issue was originally [TRAC 7475](http://trac.mantidproject.org/mantid/ticket/7475)

If one runs Diffraction_Workflow_Test and try to play with algorithm

ConvertToDiffractionMDWorkspace

version (Version=1 or default (2) ) and LorentzCorrections=0 or 1 in rows 104 and 123, the workspaces produced by the algorithm are substantially different. 

We currently assume that Version 2 of algorithm with Lorentz corrections works fine, but there are no sufficient evidence for that, as ConvertToDiffractionMDWorkspace version 1 with Lorentz corrections was there for a while. 

If would be nice to have certainty that current Lorentz corrections are indeed correct.

**Comment by NickDraper** [comment]
No action for 3 years - archived
