### ISSUE TITLE
PredictFractionalPeaks GUI doesn't remember inputs

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8385]
This issue was originally [TRAC 7540](http://trac.mantidproject.org/mantid/ticket/7540)

Users have reported that the HOffset, FOffset and LOffset values are not remembered for some reason.

**Comment by OwenArnold** [comment]
for samuel

**Comment by martyngigg** [comment]
This appears to work on the latest master. A fix has crept in at some point but it's hard to say when.
