### ISSUE TITLE
Create a Qt designer widget for the validator marker.

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#8465]
This issue was originally [TRAC 7619](http://trac.mantidproject.org/mantid/ticket/7619)

Many interfaces use the standard red star as a validator marker. The only problem is that it is implemented differently and some have ended up with different variants of the colour. It should be simple to write a small widget that encapsulates the validator and export it as a designer plugin.

**Comment by NickDraper** [comment]
Not worth doing, closing the isue
