### ISSUE TITLE
Create a dynamic binned MDEventWorkspace with different coordinate basis

### ISSUE THREAD

**Issue by mareuter** [mantidproject/mantid#8477]
This issue was originally [TRAC 7632](http://trac.mantidproject.org/mantid/ticket/7632)

```ConvertToMD``` is locked into a specific regime of coordinate axes, namely (HKL mode, direct mode) [H,K,L,deltaE,....]. One would ideally like to be able to create a ```MDEventWorkspace``` with a coordinate axis set like [H,deltaE,K] and the 4th dimension, L, integrated that takes advantage of the dynamic binning. ```SliceMD``` can be used to effect the coordinate change, but it currently returns a "regularized" ```MDEventWorkspace``` since it relies on the number of bins for each axis being specified.  This isn't really what is desired when creating a new ```MDEventWorkspace``` since it the workspace should leverage the dynamic binning capability. Rather than modify the two aforementioned algorithms, a new slicing algorithm should be created to construct a ```MDEventWorkspace``` with an arbitrary coordinate axes from a given ```MDEventWorkspace``` and that new workspace should be dynamically binned.

**Comment by NickDraper** [comment]
archived
