### ISSUE TITLE
Allow the default colour map to be specified

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#8551]
This issue was originally [TRAC 7706](http://trac.mantidproject.org/mantid/ticket/7706)

It is currently impossible to set the default colourmap for MantidPlot. It is hardwired in the code and any selection for colour fill plots is not persisted.

We should allow a file to be set as default and fallback to the inbuilt one if the file cannot be accessed.

**Comment by NickDraper** [comment]
This has now been done as part of the vates ui work
