### ISSUE TITLE
Mantid window placement restoration not good when moving from dual->single monitor

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#8598]
This issue was originally [TRAC 7753](http://trac.mantidproject.org/mantid/ticket/7753)

A really annoying feature of the windows version of Mantid that I’ve been meaning to mention for a long time is as follows.
 
If I use a machine with 2 screens and place mantid on the 2nd screen and close it down it remembers where it was.
 
However, if I then log onto the machine via a remote desktop Mantid does not detect that the second screen is missing and continues to place itself off screen. There is no easy way to get it back, unfortunately. There is a similar problem with detaching the various sub windows within the GUI. If they are placed off screen you cannot drag them back.
 
Can someone have a look into the Mantid window size detection to try and resolve this.
 
Thanks
 
Rob

**Comment by NickDraper** [comment]
archived
