### ISSUE TITLE
LineViewer enhancements

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#8701]
This issue was originally [TRAC 7856](http://trac.mantidproject.org/mantid/ticket/7856)

In order for lineviewer to be useful, allow errorbar plotting and, more important, allow scaling of the intensity axis

1 Day

**Comment by AntonPiccardoSelg** [comment]
I will remove the high priority since this is a very old issue

**Comment by Mantid-Matthew** [comment]
Closing as stale.
