### ISSUE TITLE
Add pylint to the build system

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#8742]
This issue was originally [TRAC 7897](http://trac.mantidproject.org/mantid/ticket/7897)

There are many defects that pylint should be able to determine. Setup pylint as a cmake task to add to the builds to improve the reliability of our python system. Since there is lots of funny business with our python path upon initialization of mantid some extra work will be need to be done to get it "right." [http://github.com/justinvanwinkle/config-files/blob/master/bin/lintrunner.py Here] is a python script that may help in running pylint from inside python rather than as a command line tool.

**Comment by FedeMPouzols** [comment]
I think that has been working perfectly fine for a while. Maybe it's a duplicate of some other ticket/issue(s).
