### ISSUE TITLE
Crash - Fitting data in plot with layers

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#8748]
This issue was originally [TRAC 7903](http://trac.mantidproject.org/mantid/ticket/7903)

In addition to crash also when multilayers regardless of what is plotted and what layers is highlighted the spectrum which is selected by the Fit Function tools is always the first spectrum in the first layers.

Example demonstrating that first spectrum in layer one always plotted:
1. Load e.g. ARGUS0031800 from AutoTestData
2. Plot e.g. spectrum 1-3 of workspace ARGUS0031800_1
3. Add a new layer Graph->'Add layer'
4. Plot spectrum 1 in layer 2 and spectrum 2-3 in layer 1
5. Have layer 2 highlighted
6. Click on the Fit Function toolbox button. This:

a) specifies a fitting range in both layers, not only the layer which is highlighted

b) In Fit Function properties settings it set the workspace index to fit to be 1, which is spectrum 2, i.e. not the spectrum plotted in layer 2
1. Highlight layer 1. 
2. click on the Fit Function toolbox button. This has no effect on the workspace index that is selected in the Fit Function properties settings

Example demonstrating crash:
1. Load e.g. ARGUS0031800 from AutoTestData
2. Plot e.g. spectrum 1-3 of workspace ARGUS0031800_1
3. Add two new layers
4. In layer 2 plot spectrum 2-3
5. click on the Fit Function toolbox button
6. click on the Selection tools button (6 buttons to the left of the Fit Function toolbox button)
7. Plot spectrum 3 in layer 3
8. click on the Fit Function toolbox button

and MantidPlot crashed

The work in this ticket may be split up into a number of tickets, i.e. a ticket dealing with the crash and a ticket to make the Fit Function toolbox button more sensitive to which layer is highlighted in a multilayer plot

**Comment by NickDraper** [comment]
Disable fitting on multi later plots?

**Comment by mantid-roman** [comment]
That would be my preference.

**Comment by Anders-Markvardsen** [comment]
OK with me also to disable. I am not aware of a user have reported a problem with this since this happens, if I remember correctly, during a Mantid tutorial in 2013.
