### ISSUE TITLE
Python Documentation and Methods

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8760]
This issue was originally [TRAC 7915](http://trac.mantidproject.org/mantid/ticket/7915)

This issue was a suggestion by Emanuel. Reassign as appropriate after checking the validity of this issue. 

Some documentation is completely lacking from the python documentation, in other cases the function naming convention is not consistent. For example, compare http://download.mantidproject.org/docs/current-release/python/html/api/generated/InstrumentWindow.html?highlight=colormap#mantidplot.InstrumentWindow.changeColormap (mixed case) with 

```
#!python
inst = getInstrumentView('x')
inst.show()
tab = inst.getTab(InstrumentWindow.RENDER)
tab.changeColourMap("...")
```
which is camel case (correct)

I suggest that the following things need to be addressed:
* Documentation completely missing from many functions, what do they do?
* Inconsistent cases (changeColourMap vs changeColormap)
* Inconsistent access to plotting i.e. plotSpectrum,  plotBin, plotSlice, but getInstrumentView!
* getInstrumentView only takes the workspace name, not the workspace itself. other plotting functions can handle both.

Apologies for writing an umbrella ticket for all these issues, should probably be resolved as separate issues.

**Comment by NickDraper** [comment]
archived
