### ISSUE TITLE
Peak not displayed on top of background in fit plot window

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#8787]
This issue was originally [TRAC 7942](http://trac.mantidproject.org/mantid/ticket/7942)

When in View->preferences...->Mantid->'Curve Fitting' an auto background is selected then if a fitting peak is added to graph the height of the peak is shown from the background.

However when no auto background is selected and a user manually adds a background then this does not apply (it measures the height of the peak in the fit Plot window from the bottom of the y-axis rather than from the where the background function is)

**Comment by NickDraper** [comment]
unlikely to change this in the near future - archived
