### ISSUE TITLE
PythonAlgorithms category to remove?

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8840]
This issue was originally [TRAC 7995](http://trac.mantidproject.org/mantid/ticket/7995)

I can't ever imagine a user searching for an algorithm and looking for a python one via the categories. Don't see what use the programming language of implementation is for the end user. Does anyone have a use-case for this, or can we remove this category?

**Comment by NickDraper** [comment]
![image](https://cloud.githubusercontent.com/assets/1017173/10884980/dcb93d56-8172-11e5-8197-20a8086c532f.png)

**Comment by NickDraper** [comment]
![image](https://cloud.githubusercontent.com/assets/1017173/10885004/005c9776-8173-11e5-829c-05725aca88da.png)

**Comment by NickDraper** [comment]
After discussion with @martyngigg we agreed that it would be better for python algrotihms to force the developer to state a category, and not have a default.

The error message will have to be good though.

**Comment by peterfpeterson** [comment]
We can blacklist the category, `PythonAlgorithms`, in [CodeConventions.py](/Testing/SystemTests/tests/analysis/CodeConventions.py#L86). That way it cannot be accidentally merged into master.

**Comment by NickDraper** [comment]
Actually thinking more about it, some users will have algorithms themselves that they have not merged into our codebase, and it would be too harsh to have them refuse to work with Mantid.
I'll add a warning to anything that registers the default python category.

**Comment by NickDraper** [comment]
@peterfpeterson Not so easy as that, people have not included PythonAlgorithms as a string, they have just not defined category(self) at all.

**Comment by NickDraper** [comment]
The following violators remain:
AddSampleLogMultiple v1
ApplyNegMuCorrection v1
ApplyPaalmanPingsCorrection v1
BASISReduction311 v1
BASISReduction v1
CalculateSampleTransmission v1
CalibrateRectangularDetectors v1
CheckForSampleLogs v1
CollectHB3AExperimentInfo v1
CompareSampleLogs v1
ConjoinFiles v1
ConjoinSpectra v1
ConvertSnsRoiFileToMask v1
CorrectLogTimes v1
CreateEmptyTableWorkspace v1
CreateLeBailFitInput v1
CreateMD v1
CylinderPaalmanPingsCorrection v1
CylinderPaalmanPingsCorrection v2
DakotaChiSquared v1
DetectorFloodWeighting v1
DNSDetEffCorrVana v1
DNSFlippingRatioCorr v1
DNSMergeRuns v1
DPDFreduction v1
ElasticWindowMultiple v1
EnggCalibrateFull v1
EnggCalibrate v1
EnggFitPeaks v1
EnggFocus v1
EnggVanadiumCorrections v1
EQSANSAzimuthalAverage1D v1
EQSANSDirectBeamTransmission v1
EQSANSNormalise v1
EVSDiffractionReduction v1
ExaminePowderDiffProfile v1
ExampleSaveAscii v1
ExportExperimentLog v1
ExportSampleLogsToCSVFile v1
FilterLogByTime v1
FindReflectometryLines v1
FlatPlatePaalmanPingsCorrection v1
FuryFitMultiple v1
GenerateGroupingSNSInelastic v1
GetEiMonDet v1
GetEiT0atSNS v1
GetNegMuMuonicXRD v1
HFIRSANSReduction v1
ILLIN16BCalibration v1
IndirectAnnulusAbsorption v1
IndirectCalibration v1
IndirectCylinderAbsorption v1
IndirectFlatPlateAbsorption v1
IndirectILLReduction v1
IndirectResolution v1
IndirectTransmissionMonitor v1
IndirectTransmission v1
ISISIndirectDiffractionReduction v1
ISISIndirectEnergyTransfer v1
LiquidsReflectometryReduction v1
LoadDNSLegacy v1
LoadEmptyVesuvio v1
LoadFullprofFile v1
LoadLogPropertyTable v1
LoadMultipleGSS v1
LoadNMoldyn3Ascii v1
LoadNMoldyn4Ascii v1
LoadSINQFile v1
LoadSINQ v1
LoadVesuvio v1
LoadVisionElasticBS v1
LoadVisionElasticEQ v1
LoadVisionInelastic v1
LRPrimaryFraction v1
LRReflectivityOutput v1
LRScalingFactors v1
LRSubtractAverageBackground v1
MaskAngle v1
MaskBTP v1
MaskWorkspaceToCalFile v1
Mean v1
MergeCalFiles v1
MolDyn v1
MSDFit v1
MuscatData v1
MuscatFunc v1
MuscatSofQW v1
NormaliseByThickness v1
OSIRISDiffractionReduction v1
PDToPDFgetN v1
PearlMCAbsorption v1
PoldiCreatePeaksFromFile v1
PoldiDataAnalysis v1
PoldiLoadRuns v1
PoldiMerge v1
QLines v1
Quest v1
ReactorSANSResolution v1
RefinePowderDiffProfileSeq v1
RefLReduction v1
REFLReprocess v1
ResNorm v1
ResNorm v2
RetrieveRunInfo v1
SANSAbsoluteScale v1
SANSAzimuthalAverage1D v1
SANSBeamSpreaderTransmission v1
SANSDirectBeamTransmission v1
SANSMask v1
SANSReduction v1
SANSSubtract v1
SANSWideAngleCorrection v1
SavePlot1DAsJson v1
SavePlot1D v1
SaveVulcanGSS v1
SelectPowderDiffPeaks v1
SimulatedDensityOfStates v1
SNSPowderReduction v1
SofQWMoments v1
SortByQVectors v1
SortDetectors v1
SortXAxis v1
Squares v1
StatisticsOfTableWorkspace v1
SuggestTibCNCS v1
SuggestTibHYSPEC v1
Symmetrise v1
TestWorkspaceGroupProperty v1
TimeSlice v1
TOFTOFCropWorkspace v1
TOFTOFMergeRuns v1
TOSCABankCorrection v1
TransformToIqt v1
UpdatePeakParameterTableValue v1
USANSReduction v1
USANSSimulation v1
VesuvioResolution v1
ViewBOA v1
VisionLoadDetectorTable v1
VisionReduction v1
AddSampleLogMultiple v1
ApplyNegMuCorrection v1
ApplyPaalmanPingsCorrection v1
BASISReduction311 v1
BASISReduction v1
CalculateSampleTransmission v1
CalibrateRectangularDetectors v1
CheckForSampleLogs v1
CollectHB3AExperimentInfo v1
CompareSampleLogs v1
ConjoinFiles v1
ConjoinSpectra v1
ConvertSnsRoiFileToMask v1
CorrectLogTimes v1
CreateEmptyTableWorkspace v1
CreateLeBailFitInput v1
CreateMD v1
CylinderPaalmanPingsCorrection v1
CylinderPaalmanPingsCorrection v2
DakotaChiSquared v1
DetectorFloodWeighting v1
DNSDetEffCorrVana v1
DNSFlippingRatioCorr v1
DNSMergeRuns v1
DPDFreduction v1
ElasticWindowMultiple v1
EnggCalibrateFull v1
EnggCalibrate v1
EnggFitPeaks v1
EnggFocus v1
EnggVanadiumCorrections v1
EQSANSAzimuthalAverage1D v1
EQSANSDirectBeamTransmission v1
EQSANSNormalise v1
EVSDiffractionReduction v1
ExaminePowderDiffProfile v1
ExampleSaveAscii v1
ExportExperimentLog v1
ExportSampleLogsToCSVFile v1
FilterLogByTime v1
FindReflectometryLines v1
FlatPlatePaalmanPingsCorrection v1
FuryFitMultiple v1
GenerateGroupingSNSInelastic v1
GetEiMonDet v1
GetEiT0atSNS v1
GetNegMuMuonicXRD v1
HFIRSANSReduction v1
ILLIN16BCalibration v1
IndirectAnnulusAbsorption v1
IndirectCalibration v1
IndirectCylinderAbsorption v1
IndirectFlatPlateAbsorption v1
IndirectILLReduction v1
IndirectResolution v1
IndirectTransmissionMonitor v1
IndirectTransmission v1
ISISIndirectDiffractionReduction v1
ISISIndirectEnergyTransfer v1
LiquidsReflectometryReduction v1
LoadDNSLegacy v1
LoadEmptyVesuvio v1
LoadFullprofFile v1
LoadLogPropertyTable v1
LoadMultipleGSS v1
LoadNMoldyn3Ascii v1
LoadNMoldyn4Ascii v1
LoadSINQFile v1
LoadSINQ v1
LoadVesuvio v1
LoadVisionElasticBS v1
LoadVisionElasticEQ v1
LoadVisionInelastic v1
LRPrimaryFraction v1
LRReflectivityOutput v1
LRScalingFactors v1
LRSubtractAverageBackground v1
MaskAngle v1
MaskBTP v1
MaskWorkspaceToCalFile v1
Mean v1
MergeCalFiles v1
MolDyn v1
MSDFit v1
MuscatData v1
MuscatFunc v1
MuscatSofQW v1
NormaliseByThickness v1
OSIRISDiffractionReduction v1
PDToPDFgetN v1
PearlMCAbsorption v1
PoldiCreatePeaksFromFile v1
PoldiDataAnalysis v1
PoldiLoadRuns v1
PoldiMerge v1
QLines v1
Quest v1
ReactorSANSResolution v1
RefinePowderDiffProfileSeq v1
RefLReduction v1
REFLReprocess v1
ResNorm v1
ResNorm v2
RetrieveRunInfo v1
SANSAbsoluteScale v1
SANSAzimuthalAverage1D v1
SANSBeamSpreaderTransmission v1
SANSDirectBeamTransmission v1
SANSMask v1
SANSReduction v1
SANSSubtract v1
SANSWideAngleCorrection v1
SavePlot1DAsJson v1
SavePlot1D v1
SaveVulcanGSS v1
SelectPowderDiffPeaks v1
SimulatedDensityOfStates v1
SNSPowderReduction v1
SofQWMoments v1
SortByQVectors v1
SortDetectors v1
SortXAxis v1
Squares v1
StatisticsOfTableWorkspace v1
SuggestTibCNCS v1
SuggestTibHYSPEC v1
Symmetrise v1
TestWorkspaceGroupProperty v1
TimeSlice v1
TOFTOFCropWorkspace v1
TOFTOFMergeRuns v1
TOSCABankCorrection v1
TransformToIqt v1
UpdatePeakParameterTableValue v1
USANSReduction v1
USANSSimulation v1
VesuvioResolution v1
ViewBOA v1
VisionLoadDetectorTable v1
VisionReduction v1

**Comment by mganeva** [comment]
I can remove this category from TOFTOF and DNS algorithms and commit this change to my pending pull request 14153. The problem is that I don't know how to be with the subcategories PythonAlgorithms\\MLZ\\DNS or PythonAlgorithms\\MLZ\\TOFTOF. Should I remove these subcategories either? Please, let me know how to set the correct category.

**Comment by NickDraper** [comment]
Marina,

Don’t worry, I’ll adjust the categories as I’ll be doing it for all of the others anyway.

I’ve moved the subcategories to Workflow\MLZ\TOFTOF etc.

Regards,
Nick Draper
