### ISSUE TITLE
Numpy version upgrade

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8847]
This issue was originally [TRAC 8002](http://trac.mantidproject.org/mantid/ticket/8002)

This has been raised by Rob (cc'd). The versions of Numpy that we use are quite different. This makes saving numpy arrays and reloading them on different platforms impossible.

Looks like we get/use the following versions on platforms I've looked at so far:
1.6.1 Mountain Lion 
1.6.2 Windows 7 x64
1.4.1 RHEL6

A standardised Numpy version would probably solve the issue that Rob is experiencing. Not sure what the wider caveats of this will be. Could we do something about this for release 3.0?

**Comment by martyngigg** [comment]
We've the windows/osx versions on and having the same version everywhere is not going to be possible without getting things confused on Linux platforms.
