### ISSUE TITLE
Add Horace/Mantid std binning option to SliceMD/BinMD

### ISSUE THREAD

**Issue by abuts** [mantidproject/mantid#8869]
This issue was originally [TRAC 8024](http://trac.mantidproject.org/mantid/ticket/8024)

This ticket is blocks :  [TRAC5971](http://trac.mantidproject.org/mantid/ticket/5971)

Standard Mantid/Horace binning format is defined as start,step,end values. 

SliceMD/BinMD do not follow this convention and request binning parameters defined in the form Start,end,NumBins. 

This format is unusual to instrument scientists and often inconvenient. 

Necessary:

1) Modify binning input to allow Horace/Mantid std format.

2) Add switch to change from one format to another with default current format. This is necessary for support number of existing user scripts + some existing framework plugins (e.g sliceviewer)

**Comment by martyngigg** [comment]
Clearing out old issues related to slicing/sliceviewer. Nothing has been done here for 7 years. If needed this can be reopened and prioritised as appropriate.
