### ISSUE TITLE
Issue with ConvertUnits

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#8874]
This issue was originally [TRAC 8029](http://trac.mantidproject.org/mantid/ticket/8029)

From Pascal:

If you make a mistake by choosing Direct instead of elastic, it seems to remember somehow and subsequent conversion don;t work, see below.
This is not urgent as you can reload from scartch and start with proper "elastic" option again and it works.

 ######################################################################
 #Python Script Generated by GeneratePythonScript Algorithm
 ######################################################################
 LoadRaw(Filename=r'/archive/ndxwish/Instrument/data/cycle_13_3/WISH00025470.raw', OutputWorkspace='25470')
 CropWorkspace(InputWorkspace='25470',OutputWorkspace='25470',XMin='6000',XMax='99000')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='Wavelength')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='TOF')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='Wavelength')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='Wavelength')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='TOF')
 ConvertUnits(InputWorkspace='25470',OutputWorkspace='25470',Target='Wavelength')

**Comment by NickDraper** [comment]
The memory is there for a reason to allow subsequent calls to not need that setting to be set.

However this is a good point.  What to do??
We could put some protection in that disallows direct without an efixed value.
Or add a boolean option to override saved values

Assigned to PM for now

**Comment by NickDraper** [comment]
The test above works fine now, looking at the code there appears to be protection to only store efixed if it is actually specified.
