### ISSUE TITLE
WorkspaceList property

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8888]
This issue was originally [TRAC 8043](http://trac.mantidproject.org/mantid/ticket/8043)

This ticket is blocks :  [TRAC8079](http://trac.mantidproject.org/mantid/ticket/8079)

A few algorithms that have been implemented lately (or are due to be implemented) such as Mean, and StitchMany http://trac.mantidproject.org/mantid/ticket/8042, have/will require a single property to accept a sequence of Workspaces.

At present, the only way that this can be done is to have a string list property from which the names/keys are used to map to real workspaces in the ADS. Proper checking of the workspace types then needs to be applied. For example, you may wish to validate that the workspaces are of the same type, or are the same shape. 

The proposal of this ticket is to implement a WorkspaceList property onto which a new set of WorkspaceList validators can be applied.

---

Keywords: CORE

**Comment by matthew-d-jones** [comment]
MergeMD is another example of this problem, leading to having to abuse the ADS in CreateMD and AccumulateMD.

**Comment by OwenArnold** [comment]
@matthew-d-jones I started work on this a few years ago, and had to put it down because something urgent came up. I'll make sure it gets re-prioritised for the next maintenance period. As it happens I'm currently existing the property times for another hole in our type system.

**Comment by matthew-d-jones** [comment]
@OwenArnold Sounds good. For now I've left comments by calls to ADS in CreateMD and AccumulateMD, so hopefully it is clear what is going on and people won't copy and do the same thing in places were it isn't necessary.
