### ISSUE TITLE
Analysis data service allows creation of a workspace group containing two copies of itself

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#8895]
This issue was originally [TRAC 8050](http://trac.mantidproject.org/mantid/ticket/8050)

To reproduce:
 * open a musr file from autotest data, it creates a group with two workspaces
 * rename one of the contained workspaces
 * rename the other workspace to the same name
 * rename the group to the same name as its members

Right-clicking on any of the items in the dock crashes mantid

**Comment by NickDraper** [comment]
Anyone who does this deserves whatever they get.  However the crash no longer happens, when you rename the group to that of the members it just disappears.  So Fixed!
