### ISSUE TITLE
Expose WorkspaceListProperty to python

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#8924]
This issue was originally [TRAC 8079](http://trac.mantidproject.org/mantid/ticket/8079)

This ticket is blocked by : 
- [ ] [TRAC8043](http://trac.mantidproject.org/mantid/ticket/8043)

Issue details are blank in trac

**Comment by soininen** [comment]
We don't have a WorkspaceListProperty.

**Comment by OwenArnold** [comment]
@soininen FYI, @LamarMoore started working on this a few years ago. I still consider it a good idea, but we were unable to complete all the work.
