### ISSUE TITLE
Fixed aspect ratio in SliceViewer

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#8943]
This issue was originally [TRAC 8098](http://trac.mantidproject.org/mantid/ticket/8098)

This ticket is blocks :  [TRAC10647](http://trac.mantidproject.org/mantid/ticket/10647)

Resizing the SliceViewer currently keeps the visible region fixed and stretches space to accomodate it. It would be better if SliceViewer (as an option?) would keep a constant aspect ratio and resizing changed the amount of viewable data.

0.5 days

**Comment by OwenArnold** [comment]
Done
