### ISSUE TITLE
Expand IDF <locations> to work with <facing>

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#9006]
This issue was originally [TRAC 8161](http://trac.mantidproject.org/mantid/ticket/8161)

Allow the following IDF syntax

Currently you can do, see http://www.mantidproject.org/IDF#Using_.3Cfacing.3E

`<location something >`

  `<facing something />`

`</location>`

Also allow 

`<locations something >`

  `<facing something />`

`</locations>`

**Comment by NickDraper** [comment]
Archived until we have a use case for this
