### ISSUE TITLE
Better warnings mixing cartesian/spherical positions in IDF

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/mantid#9007]
This issue was originally [TRAC 8162](http://trac.mantidproject.org/mantid/ticket/8162)

If a user specify 

`<facing t="0.0" y="0.0" z="0.0"/>`

or 

`<location r="2.5" t="19.163020" z="7" >` 

etc where the position of a component or otherwise is specified as a mixture of spherical and cartesian coordinates then output a warning to the user that

"Cannot specify a position as a mixture of spherical and cartesian coordinates. You much use one or the other. Here spherical coordinates ignored"

**Comment by NickDraper** [comment]
Sometimes people deserve everything they get.  Archived
