### ISSUE TITLE
Bounding Boxes for Hexahedrons

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9034]
This issue was originally [TRAC 8189](http://trac.mantidproject.org/mantid/ticket/8189)

Following on from http://trac.mantidproject.org/mantid/ticket/7940, bounding boxes for hexahedrons and tapered-guide shapes should ideally be created automatically, rather than leaving it to the user.

For simpler shapes this appears to be done by defining their own class and defining a `getBoundingBox` function.

**Comment by MikeHart85** [comment]
Fixed as part of #14424.
