### ISSUE TITLE
SliceViewer negative values

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#9083]
This issue was originally [TRAC 8238](http://trac.mantidproject.org/mantid/ticket/8238)

Try

```
CreateWorkspace(OutputWorkspace='w',DataX='1,2,3,1,2,3,1,2,3',DataY='-1,-1,-1,-2,-2,-2,-3,-3,-3',DataE='0,0,0,0,0,0,0,0,0',NSpec='3')
```

and plot using SliceViewer. It does not get the correct colorbar limits, even if no log scaling

**Comment by AntonPiccardoSelg** [comment]
Speaking to Andrei, the SliceViewer should also be able to display negative values. Currently the hoover tool shows the values but the display and the limits don't show anything

**Comment by martyngigg** [comment]
The new sliceviewer is able to plot this. Closing as wontfix.
