### ISSUE TITLE
SaveIsawPeaks for non-rectangular detectors

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9085]
This issue was originally [TRAC 8240](http://trac.mantidproject.org/mantid/ticket/8240)

http://www.mantidproject.org/SaveIsawPeaks is not working for non-rectangular instruments, such as WISH.
- Plan A. Algorithm should be made to work for non-rectangular detectors if possible
- Plan B. Algorithm should give-up and suggest using SaveNexus if not possible (above). See http://trac.mantidproject.org/mantid/ticket/4443
- Plan B. In addition to the step above.  The documentation for this algorithm should inform users on what this algorithm is capable of working for.

**Comment by NickDraper** [comment]
It is worth checking what the current state of this is

**Comment by samueljackson92** [comment]
@NickDraper Pascal indicated today that this may have been done. Worth checking.

**Comment by samueljackson92** [comment]
This looks like I has been generalised to support non-rectangular detectors, but there seems to be a lot of code hard coded to WISH. I wonder if it could be made more general? In any case I'm moving this to low priority.
