### ISSUE TITLE
LoadCanSAS1D outputs workspace group with odd behaviour

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#9094]
This issue was originally [TRAC 8249](http://trac.mantidproject.org/mantid/ticket/8249)

 1. Load testCanSAS1DMultiEntry.xml. A group with two entries is created.
 2. Delete the group. Two ungrouped workspaces appear.
 3. Instead of deleting ungroup it. There are four workspaces now.

**Comment by NickDraper** [comment]
archived
