### ISSUE TITLE
Plot details dialog doesn't change axis position

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#9100]
This issue was originally [TRAC 8255](http://trac.mantidproject.org/mantid/ticket/8255)

Axes page of Plot details dialog should disable the axis options in the combo boxes which not shown on the plot.

**Comment by NickDraper** [comment]
This is for example the top axis options when the axis is not in the graph

**Comment by NickDraper** [comment]
Not worth fixing as this will be replaced in M4
