### ISSUE TITLE
Axis mismatch when saving/loading event data

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9152]
This issue was originally [TRAC 8307](http://trac.mantidproject.org/mantid/ticket/8307)

Run the following script:

```#!python
wsName = "CNCS_7860_event.nxs"

Load(Filename=wsName,OutputWorkspace=wsName)
SaveNexus(InputWorkspace=wsName, Filename="temp.nxs")
LoadNexus(Filename="temp.nxs", OutputWorkspace="roundtrip")

print CheckWorkspacesMatch(wsName, "roundtrip")
```

This prints:

```
Axis 0 values mismatch
```

Essentially, it '''appears''' as if raw event data is not surviving a save/load round-trip, though it may be the case that CheckWorkspacesMatch is not doing a correct/meaningful check in this case.

**Comment by NickDraper** [comment]
archived
