### ISSUE TITLE
Allow copy and pasting from TableWorkspace to fit property table

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9295]
This issue was originally [TRAC 8451](http://trac.mantidproject.org/mantid/ticket/8451)

To reproduce:
- Load a data file and do a fit.
- Open up the TableWorkspace that contains the resulting fitting parameters.
- Copy a value from the table using "copy" from the right-click menu.
- Try to paste it into one of the fit property browser value fields.

Strangely enough, it is possible to paste it elsewhere into Mantid, but not into the property browser.  Also, if you paste it into Notepad, and then copy the value from there, you will be able to paste it into the property browser!

**Comment by NickDraper** [comment]
This is wierd but true

**Comment by NickDraper** [comment]
mantidplot is deprecated
