### ISSUE TITLE
Make sure that newly added layers are a sensible size

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9297]
This issue was originally [TRAC 8453](http://trac.mantidproject.org/mantid/ticket/8453)

Try adding a new layer to an existing plot using the following instructions:

http://www.mantidproject.org/MBC_Displaying_data_Complex

Unfortunately, to get the titles of the two layers to align like they do in the image, you have to adjust the sizes of the layers manually.

It would be nice if the "add layer" functionality was clever enough to see what size layers are there already, and just use that size.

**Comment by NickDraper** [comment]
Layers are unfrequently used in practice.

wontfix
