### ISSUE TITLE
Have focus-stealing modal dialogs ignore "always on top" rule of other windows

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9312]
This issue was originally [TRAC 8468](http://trac.mantidproject.org/mantid/ticket/8468)

Mantid does not accept any mouse input under a certain set of circumstances and has to be closed unless the Alt+F4 keyboard shortcut is used.  To reproduce:

* Open up the Python scripting window and place it in a position similar to that shown in the attached image.
* Set the Python window to be "Always on Top".
* Type "Load" and press enter into the Algorithm field as shown in the image.

The [http://qt-project.org/doc/qt-4.8/qwidget.html#modal-prop modal] nature of the dialog means that you can't click outside of the dialog, but the Python scripting window will block you from clicking on the dialog!

Use Alt+F4 to close the dialog and regain control of Mantid.

I've set this to minor since this will probably be quite a rare occurrence.

**Comment by NickDraper** [comment]
dialog windows are no longer modal

so works4me
