### ISSUE TITLE
Windows Installer Clean-up

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9320]
This issue was originally [TRAC 8476](http://trac.mantidproject.org/mantid/ticket/8476)

We've had a couple of occasions where users have dlls left over in their bin directory after the uninstall.

Most recent one seemed to result in having installed a 32bit install of windows, and then trying to install a 64 bit one on top. 

Rob Dalgleish has asked that we provide some better and more useful error message. Could we do anything better here. Could we better pick up the presence of any mismatching dlls, or even just provide a better help feature around this?

**Comment by NickDraper** [comment]
no recent problems
