### ISSUE TITLE
ExtractSpectra

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9343]
This issue was originally [TRAC 8499](http://trac.mantidproject.org/mantid/ticket/8499)

ExtractSpectra to handle ranges of spectrum to extract. Similar to ExtractSpectrum. Should provide a StartWorkspaceIndex and EndWorkspaceIndex to have a similar interface to CropWorkspace.

**Comment by NickDraper** [comment]
This should be handled with the changes with the workspaceindexproperty, If indeed ever as tyhis is a very low priority, and should not be done alone as this would be a different paradigm than other algorithms.

Archiving
