### ISSUE TITLE
Graph Templates in Mantid

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9361]
Template library for graphs 

There could be specific template or common plots that show up in right-click/context menu of workspaces when data comes from a particular instrument. Example: ENGIN-X, both detectors on color plots side-by-side. Have a mechanism to define templates and use them based on the instrument (from the IDF). Otherwise, they'll do their scripts for these plots but then the usability is poor.

Allow graphs to output python that defines it, use this in the save/load project mechanism as well.

There may be some code in the newer versions of qtiplot we should consider (also test usability)

For reassignment to student

**Comment by NickDraper** [comment]
Raised also at the SSC, asigned to PM so this doesn't get lost
