### ISSUE TITLE
Enable Table Workspace columns of type float to be saved to Nexus

### ISSUE THREAD

**Issue by KarlPalmen** [mantidproject/mantid#9447]
This issue was originally [TRAC 8603](http://trac.mantidproject.org/mantid/ticket/8603)

Issue details are blank in trac

**Comment by KarlPalmen** [comment]
I now see provision in NexusFileIO.cpp .

**Comment by FedeMPouzols** [comment]
This is definitely working in recent Mantid releases, as well as #9448, #9449, and #9450.
