### ISSUE TITLE
Improve LoadDialog created from Python when file not found

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9534]
This issue was originally [TRAC 8690](http://trac.mantidproject.org/mantid/ticket/8690)

We had some feedback in the recent Mantid Training Course whereby it was suggested that LoadDialogs should be more explicit when informing the user that a file was not found.  Consider the following code which is needed in the solution to one of the exercises:

``` #!python
  LoadDialog(
    "LOQ48097",
    OutputWorkspace="small_angle",
    LoadMonitors="Separate",
    Enable="Filename,SpectrumList",
    Disable="SpectrumMin,SpectrumMax")
```

If the default "LOQ48097" run is not on a user's search path then the dialog will not show any of the disabled/enabled fields as was the script-writers intention, and instead the script-user is presented with only the Filename and OutputWorkspaces fields with the standard Mantid red asterisk beside them.

My personal opinion is that the current functionality is fine, albeit slightly unintuitive for new users who may not spot the asterisks and are expecting a different-looking dialog box.  Perhaps the script-writer could guard against this if they wish by doing their own FileFinder check to make sure the default run is there before opening the dialog box?

**Comment by NickDraper** [comment]
Won't fix, the current behaviour is about the best we can get, it is very messy if the user picks a file (after failing to load a file) which uses a different loader with different properties.
