### ISSUE TITLE
Implement fit function back-to-back exponential convoluted with psuedo voigt

### ISSUE THREAD

**Issue by wdzhou** [mantidproject/mantid#9588]
This issue was originally [TRAC 8744](http://trac.mantidproject.org/mantid/ticket/8744)

This ticket is blocks :  [TRAC8745](http://trac.mantidproject.org/mantid/ticket/8745)

Implement a fit function back to back exponential convoluted with pseduo-voigt as an extension of existing fit function BackToBackExponential, which only is convoluted with Gaussian

**Comment by FedeMPouzols** [comment]
We have a function called `Bk2BkExpConvPV` which is available in Mantid. What's the difference between `Bk2BkExpConvPV` and the one proposed in this ticket (`BackToBackExponentialPV`)? 

@Anders-Markvardsen : for documentation purposes it would be nice to clarify what "back-to-back exponential / convoluted with..." functions are available, their variants and how exactly they're defined in Mantid (equations and references). There are no documentation pages for these functions, but we have this wiki page: http://www.mantidproject.org/BackToBackExponentialPV

Related to this, there are these two other functions: `NeutronBk2BkExpConvPVoigt` and `ThermalNeutronBk2BkConvPVoigt` (#9589).

**Comment by Anders-Markvardsen** [comment]
@FedeMPouzols there is a rst for BackToBackExponential, see http://docs.mantidproject.org/nightly/fitfunctions/BackToBackExponential.html for its wiki translation.

You can also find this documentation by clicking on 'Fit functions' on http://www.mantidproject.org/Documentation.

@wdzhou is this issue now a duplicate? I.e. has this function has now been implemented as Bk2BkExpConvPV?

The wiki http://www.mantidproject.org/BackToBackExponentialPV was probably written before we introduced rst documentation for fit functions, and this wiki page should be deleted and its content used for a rst documentation page for the back to back exp PV fit function implementation
