### ISSUE TITLE
ICAT in Reflectometry Code

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9610]
This issue was originally [TRAC 8766](http://trac.mantidproject.org/mantid/ticket/8766)

Replace ALL journal xml parsing with calls to ICAT algorithms. This should not be attempted until after release 3.1 of mantid.

This has been mentioned in http://trac.mantidproject.org/mantid/ticket/8765.

**Comment by MattKing06** [comment]
@OwenArnold can this issue be closed now since we are implementing the ICAT data service?

**Comment by OwenArnold** [comment]
Yes
