### ISSUE TITLE
Expose IMaskWorkspace->getNumberMasked to python

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#9786]
This issue was originally [TRAC 8943](http://trac.mantidproject.org/mantid/ticket/8943)

This ticket is blocked by : 
 - [X] [TRAC8996](http://trac.mantidproject.org/mantid/ticket/8996)
 - [x] [TRAC9807](http://trac.mantidproject.org/mantid/ticket/9807)

This should be a quick ticket that was requested by an instrument scientist.

**Comment by martyngigg** [comment]
This will now be handled under issue #10649 as part of the exposure of the `DataObjects` layer.
