### ISSUE TITLE
User file or equivalent

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9793]
This issue was originally [TRAC 8950](http://trac.mantidproject.org/mantid/ticket/8950)

There is a strong preference from some people that the reflectometry reduction, including masking and detector selection can be driven off a single file. Once a format is provided, I'll need to implement some parsing mechanism.

**Comment by OwenArnold** [comment]
@raquelalvarezbanos I'm not sure this is valid any longer.

**Comment by gemmaguest** [comment]
This is replaced by #18826 with more of a focus on saving/loading the GUI state. The same file could be used to run a reduction directly but this isn't a requirement at the moment so closing this issue.
