### ISSUE TITLE
Colour masked spectra in MantidMatrix

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#9825]
This issue was originally [TRAC 8982](http://trac.mantidproject.org/mantid/ticket/8982)

In a similar way that we now colour monitors in the workspace, colour the background of the row if a spectrum is masked

**Comment by NickDraper** [comment]
I like this idea, marked up for a new started to look at.

**Comment by martyngigg** [comment]
Duplicate of #16938
