### ISSUE TITLE
MultiSlice in the VSI and SliceViewer cross-communicate

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9898]
This issue was originally [TRAC 9055](http://trac.mantidproject.org/mantid/ticket/9055)

This is a requirement captured in the Scientific Steering Committee 2014, and Pascal Manual has recently prompted us to ensure that it happens.

With the current MultiSlice you can shift-click on a slice position and it will render in the SliceViewer. However, the two views are not linked so updates to the slice position on one will not be mirrored in the other. I'm not sure how complicated it would be to drive the MultiSliceView externally, but I think that this will be one of the greatest challenges. 

To make things easier, lets always make it so the the current creation route which involves VSI->SliceViewer is maintained. Also, we should probably disable the projection axis switching controls on the SliceViewer while they are linked. Perhaps, it we should also make it possible to unlink the two, which would get us back to the existing behaviour. 

I've cc'd Michael as he probably has some useful contributions to make here.

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92  This is related to Pascal, hence I am assigning it to you. Please feel free to reassign
