### ISSUE TITLE
Verify, Document and System Test User Scripts

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#9929]
This issue was originally [TRAC 9086](http://trac.mantidproject.org/mantid/ticket/9086)

I have been supplied two workflow scripts for POLREF for the ISIS reflectometry group (attached). These should be checked, added to the scripts and also used for system tests.

**Comment by gemmaguest** [comment]
We should check whether these scripts are still relevant/useful

**Comment by gemmaguest** [comment]
Closing as Stale because these scripts are now very old and have probably moved on a lot.
