### ISSUE TITLE
SANS - SumRowColumn to Support New Instrument

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9981]
sans_feature
This issue was originally [TRAC 9138](http://trac.mantidproject.org/mantid/ticket/9138)

At the moment SumRowColumn has hard coded values that means it only supports instruments with 128x128 or 192x192 detectors.

Make it more generic.

Need to ensure that the Diagnostics tab of the SANS ISIS interface still works after any changes.

**Comment by Mantid-Matthew** [comment]
The diagnostic tab in the new GUI implements this change.
