### ISSUE TITLE
Accommodate Multiple Cd "Shadow" Runs when Calibrating

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9988]
sans_feature
This issue was originally [TRAC 9145](http://trac.mantidproject.org/mantid/ticket/9145)

Richard currently has a calibration script (attached) which goes some way towards calibrating the new tubes in SANS2D.

Unfortunately, it assumes that all the Cadmium "shadows" are to be cast in a single run.  This will not be the case; shadows from multiple runs will have to be combined in some way before the calibration may proceed.

Richard needs a working solution to this problem, ASAP.

**Comment by Mantid-Matthew** [comment]
I am closing this ticket as the SANS2D calibration is currently working.
